Repository apache/doris, pull requests merged in 2019-11, with the labels that each got.

#2125 Fix META read
  fe/src/main/java/org/apache/doris/qe/SessionVariable.java
Labels: bug

#2129 Forward stmt with stmt id generated on origin FE.
  fe/src/main/java/org/apache/doris/qe/ConnectContext.java
  fe/src/main/java/org/apache/doris/qe/ConnectProcessor.java
  fe/src/main/java/org/apache/doris/qe/MasterOpExecutor.java
  fe/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  fe/src/main/java/org/apache/doris/system/HeartbeatMgr.java
  fe/src/test/java/org/apache/doris/qe/StmtExecutorTest.java
  gensrc/thrift/FrontendService.thrift
Labels: enhancement

#2156 Change Null-safe equal operator from cross join to hash join
  be/src/exec/aggregation_node.cpp
  be/src/exec/hash_join_node.cpp
  be/src/exec/hash_join_node.h
  be/src/exec/hash_table.cpp
  be/src/exec/hash_table.h
  be/src/exec/olap_scan_node.cpp
  fe/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/src/main/java/org/apache/doris/planner/DistributedPlanner.java
  fe/src/main/java/org/apache/doris/planner/HashJoinNode.java
  fe/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
  gensrc/thrift/PlanNodes.thrift
Labels: need more test

#2165 Remove failed UT
  be/test/olap/CMakeLists.txt
Labels: enhancement

#2050 segment_v2: Support bitmap index build
  be/src/olap/CMakeLists.txt
  be/src/olap/key_coder.cpp
  be/src/olap/key_coder.h
  be/src/olap/rowset/segment_v2/binary_dict_page.cpp
  be/src/olap/rowset/segment_v2/binary_plain_page.h
  be/src/olap/rowset/segment_v2/bitmap_index_reader.cpp
  be/src/olap/rowset/segment_v2/bitmap_index_reader.h
  be/src/olap/rowset/segment_v2/bitmap_index_writer.cpp
  be/src/olap/rowset/segment_v2/bitmap_index_writer.h
  be/src/olap/rowset/segment_v2/bitshuffle_page.h
  be/src/olap/rowset/segment_v2/column_writer.cpp
  be/src/olap/rowset/segment_v2/column_writer.h
  be/src/olap/rowset/segment_v2/encoding_info.cpp
  be/src/olap/rowset/segment_v2/encoding_info.h
  be/src/olap/rowset/segment_v2/index_page.cpp
  be/src/olap/rowset/segment_v2/index_page.h
  be/src/olap/rowset/segment_v2/indexed_column_reader.cpp
  be/src/olap/rowset/segment_v2/indexed_column_reader.h
  be/src/olap/rowset/segment_v2/indexed_column_writer.cpp
  be/src/olap/rowset/segment_v2/indexed_column_writer.h
  be/src/olap/rowset/segment_v2/page_builder.h
  be/src/olap/rowset/segment_v2/page_decoder.h
  be/src/olap/rowset/segment_v2/page_pointer.h
  be/src/olap/rowset/segment_v2/rle_page.h
  be/src/olap/rowset/segment_v2/segment_writer.cpp
  be/src/olap/rowset/segment_v2/segment_writer.h
  be/src/util/coding.h
  gensrc/proto/segment_v2.proto
Labels: new feature

#2250 fix export to hdfs bug
  fe/src/main/java/org/apache/doris/qe/Coordinator.java
Labels: bug

#2252 Add pipes_as_concat_mode
  docs/documentation/cn/administrator-guide/sql-mode.md
  docs/documentation/en/administrator-guide/sql-mode_EN.md
  fe/src/main/cup/sql_parser.cup
  fe/src/main/jflex/sql_scanner.flex
  fe/src/test/java/org/apache/doris/analysis/SqlModeTest.java
Labels: need more test, tpc-ds

#2276 Move dtor of BetaRowset to cpp file
  be/src/olap/rowset/beta_rowset.cpp
  be/src/olap/rowset/beta_rowset.h
  be/src/olap/rowset/rowset.h
Labels: enhancement

#2260 Add a tool to show segment status
  tools/show_segment_status/README.md
  tools/show_segment_status/be_tablet_reslover.py
  tools/show_segment_status/conf
  tools/show_segment_status/fe_meta_resolver.py
  tools/show_segment_status/show_segment_status.py
Labels: enhancement
