Repository apache/doris, pull requests merged in 2019-12, with the labels that each got.

#2342 Fix bug of getting ES host error
  fe/src/main/java/org/apache/doris/external/EsRestClient.java
Labels: bug

#2358 Remove VersionHash used to comparison in BE
  be/src/olap/schema_change.cpp
  be/src/olap/tablet.cpp
  be/src/olap/task/engine_checksum_task.h
  be/src/olap/task/engine_clone_task.cpp
  be/test/exec/new_olap_scan_node_test.cpp
  be/test/exec/olap_common_test.cpp
  be/test/exec/olap_scan_node_test.cpp
  be/test/exec/olap_scanner_test.cpp
  be/test/olap/mock_command_executor.h
  be/test/olap/olap_reader_test.cpp
  be/test/olap/olap_snapshot_converter_test.cpp
  be/test/olap/rowset/alpha_rowset_test.cpp
  be/test/olap/rowset/beta_rowset_test.cpp
  be/test/olap/rowset/rowset_meta_test.cpp
  be/test/olap/vectorized_olap_reader_test.cpp
  gensrc/proto/AgentService.thrift
  gensrc/thrift/AgentService.thrift
  gensrc/thrift/PlanNodes.thrift
  gensrc/thrift/QueryPlanExtra.thrift
Labels: API changes

#2360 Support subquery with non-scalar result in Binary predicate and Between-and predicate
  be/src/exec/CMakeLists.txt
  be/src/exec/assert_num_rows_node.cpp
  be/src/exec/assert_num_rows_node.h
  be/src/exec/exec_node.cpp
  fe/src/main/java/org/apache/doris/analysis/AssertNumRowsElement.java
  fe/src/main/java/org/apache/doris/analysis/BetweenPredicate.java
  fe/src/main/java/org/apache/doris/analysis/BinaryPredicate.java
  fe/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java
  fe/src/main/java/org/apache/doris/analysis/QueryStmt.java
  fe/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/src/main/java/org/apache/doris/analysis/StmtRewriter.java
  fe/src/main/java/org/apache/doris/load/loadv2/BrokerLoadJob.java
  fe/src/main/java/org/apache/doris/planner/AssertNumRowsNode.java
  fe/src/main/java/org/apache/doris/planner/DistributedPlanner.java
  fe/src/main/java/org/apache/doris/planner/HashJoinNode.java
  fe/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
  fe/src/test/java/org/apache/doris/analysis/BetweenPredicateTest.java
  fe/src/test/java/org/apache/doris/analysis/BinaryPredicateTest.java
  fe/src/test/java/org/apache/doris/planner/DistributedPlannerTest.java
  gensrc/thrift/PlanNodes.thrift
Labels: need more test, tpc-ds

#2412 [CHANGE] change default storage model from aggregate to duplicate(#2318)
  docs/documentation/cn/sql-reference/sql-statements/Data Definition/CREATE TABLE.md
  docs/documentation/en/sql-reference/sql-statements/Data Definition/CREATE TABLE_EN.md
  fe/src/main/java/org/apache/doris/analysis/CreateTableStmt.java
  fe/src/main/java/org/apache/doris/catalog/ScalarType.java
Labels: API changes

#2448 Fix RLE encoding/decoding bug upon large negative number.
  be/src/olap/rowset/run_length_integer_reader.cpp
  be/src/olap/rowset/run_length_integer_writer.cpp
  be/test/olap/run_length_integer_test.cpp
Labels: bug

#2454 Fix RunLengthInteger unit test bug
  be/test/olap/run_length_integer_test.cpp
Labels: bug

#2452 Update README.md
  README.md
Labels: document, enhancement

#2586 Remove meaningless warn log for NullValueReader
  be/src/olap/rowset/column_reader.cpp
Labels: enhancement, storage engine

#2607 delete unused variable in the function of recordeTable
  fe/src/main/java/org/apache/doris/analysis/SelectStmt.java
Labels: enhancement

#2604 [env] Add CREATE_OR_OPEN and rename existing open modes
  be/src/env/env.h
  be/src/env/env_posix.cpp
  be/test/env/env_posix_test.cpp
Labels: storage engine

#2614 [Segment V2] add UT for lazy materialization
  be/src/olap/iterators.h
  be/src/olap/row_block2.cpp
  be/src/olap/row_block2.h
  be/src/olap/rowset/segment_v2/segment.cpp
  be/src/olap/rowset/segment_v2/segment.h
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/olap/rowset/segment_v2/segment_iterator.h
  be/test/olap/rowset/segment_v2/segment_test.cpp
Labels: enhancement

#2620 Set AGG_KEYS upon upgrade from tablet if has_keys_type() is false
  be/src/olap/olap_snapshot_converter.cpp
Labels: bug

#2629 自定义udf version `GLIBCXX_3.4.21' not found
  be/src/udf_samples/CMakeLists.txt
  docs/documentation/cn/extending-doris/user-defined-function.md
  docs/documentation/en/extending-doris/user-defined-function_EN.md
Labels: enhancement

#2623 Fix the missing sync in SegmentWriter
  be/src/olap/rowset/segment_v2/segment_writer.cpp
Labels: bug, storage engine

#2622 Remove VersionHash used to comparison in BE
  be/src/exec/olap_scanner.cpp
  be/src/olap/snapshot_manager.cpp
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
  be/src/olap/task/engine_checksum_task.cpp
Labels: bug
