Repository apache/doris, pull requests merged in 2019-09, with the labels that each got.

#1840 [Bug-fix]: Remove conjuncts for empty set node
  fe/src/main/java/org/apache/doris/planner/PlanNode.java
  fe/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
Labels: bug

#1846 Bug-fix: Enable StringLiteral cast to Varchar
  fe/src/main/java/org/apache/doris/analysis/AnalyticExpr.java
  fe/src/main/java/org/apache/doris/analysis/StringLiteral.java
Labels: SQL Bug, bug

#1858 Fix segment V2 estimate size inaccuracy
  be/src/olap/rowset/segment_v2/binary_dict_page.cpp
Labels: enhancement

#1873 [Bug-fix]: broker load not support inline function in hll_hash
  fe/src/main/java/org/apache/doris/analysis/DataDescription.java
Labels: bug

#1916 Remove unused _request_columns_size from olap_scanner
  be/src/exec/olap_scanner.cpp
  be/src/exec/olap_scanner.h
Labels: enhancement

#1918 Remove unused code and unnecessary check
  be/src/olap/delete_handler.cpp
  be/src/olap/memtable.cpp
  be/src/olap/reader.cpp
  be/src/olap/row_block.h
  be/src/olap/rowset/segment_reader.cpp
  be/src/olap/rowset/segment_reader.h
  be/src/olap/stream_index_common.cpp
  be/src/olap/tablet_meta.cpp
Labels: enhancement

#1923 Miss a break
  be/src/exec/tablet_sink.cpp
Labels: bug
