Repository apache/doris, pull requests merged in 2020-01, with the labels that each got.

#2639 Change introduction document
  docs/documentation/cn/installing/install-deploy.md
Labels: document, enhancement

#2640 change introduction document
  docs/documentation/en/installing/install-deploy_EN.md
Labels: document, enhancement

#2662 Fix FE couldn't start
  fe/src/main/java/org/apache/doris/alter/SchemaChangeJobV2.java
Labels: bug

#2661 Fix bug: parquet scanner don't seek
  be/src/exec/parquet_reader.cpp
Labels: bug

#2692 Remove boost filesystem exception in FileUtils
  be/src/util/file_utils.cpp
Labels: enhancement

#2696 Update notice year to 2020
  NOTICE.txt
Labels: Apache way

#2731 Add bitamp_to_string function
  be/src/common/daemon.cpp
  be/src/exprs/CMakeLists.txt
  be/src/exprs/bitmap_function.cpp
  be/src/exprs/bitmap_function.h
  be/src/exprs/cast_functions.cpp
  be/src/exprs/hash_functions.cpp
  be/src/exprs/hash_functions.h
  be/src/util/bitmap.cpp
  be/src/util/bitmap.h
  be/src/util/mysql_global.h
  be/test/util/bitmap_test.cpp
  docs/documentation/cn/sql-reference/sql-functions/bitmap-functions/bitmap_from_string.md
  docs/documentation/cn/sql-reference/sql-functions/bitmap-functions/bitmap_to_string.md
  docs/documentation/cn/sql-reference/sql-functions/hash-functions/index.rst
  docs/documentation/cn/sql-reference/sql-functions/hash-functions/murmur_hash3_32.md
  docs/documentation/en/sql-reference/sql-functions/bitmap-functions/bitmap_from_string.md
  docs/documentation/en/sql-reference/sql-functions/bitmap-functions/bitmap_to_string.md
  docs/documentation/en/sql-reference/sql-functions/hash-functions/index.rst
  docs/documentation/en/sql-reference/sql-functions/hash-functions/murmur_hash3_32.md
  fe/src/main/java/org/apache/doris/catalog/PrimitiveType.java
  gensrc/script/doris_builtins_functions.py
Labels: new feature

#2293 Support Grouping Sets, Rollup and Cube to extend group by statement
  be/src/common/daemon.cpp
  be/src/exec/CMakeLists.txt
  be/src/exec/exec_node.cpp
  be/src/exec/repeat_node.cpp
  be/src/exec/repeat_node.h
  be/src/exprs/CMakeLists.txt
  be/src/exprs/grouping_sets_functions.cpp
  be/src/exprs/grouping_sets_functions.h
  docs/documentation/cn/internal/grouping_sets_design.md
  docs/documentation/cn/sql-reference/sql-statements/Data Manipulation/GROUP BY.md
  docs/documentation/en/internal/grouping_sets_design_EN.md
  docs/documentation/en/sql-reference/sql-statements/Data Manipulation/GROUP BY_EN.md
  fe/src/main/cup/sql_parser.cup
  fe/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/src/main/java/org/apache/doris/analysis/ArithmeticExpr.java
  fe/src/main/java/org/apache/doris/analysis/BetweenPredicate.java
  fe/src/main/java/org/apache/doris/analysis/BinaryPredicate.java
  fe/src/main/java/org/apache/doris/analysis/BoolLiteral.java
  fe/src/main/java/org/apache/doris/analysis/CompoundPredicate.java
  fe/src/main/java/org/apache/doris/analysis/DateLiteral.java
  fe/src/main/java/org/apache/doris/analysis/DecimalLiteral.java
  fe/src/main/java/org/apache/doris/analysis/ExistsPredicate.java
  fe/src/main/java/org/apache/doris/analysis/Expr.java
  fe/src/main/java/org/apache/doris/analysis/FloatLiteral.java
  fe/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java
  fe/src/main/java/org/apache/doris/analysis/FunctionName.java
  fe/src/main/java/org/apache/doris/analysis/FunctionParams.java
  fe/src/main/java/org/apache/doris/analysis/GroupByClause.java
  fe/src/main/java/org/apache/doris/analysis/GroupingFunctionCallExpr.java
  fe/src/main/java/org/apache/doris/analysis/GroupingInfo.java
  fe/src/main/java/org/apache/doris/analysis/IntLiteral.java
  fe/src/main/java/org/apache/doris/analysis/LargeIntLiteral.java
  fe/src/main/java/org/apache/doris/analysis/LikePredicate.java
  fe/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/src/main/java/org/apache/doris/analysis/SlotRef.java
  fe/src/main/java/org/apache/doris/analysis/StmtRewriter.java
  fe/src/main/java/org/apache/doris/analysis/StringLiteral.java
  fe/src/main/java/org/apache/doris/analysis/VirtualSlotRef.java
  fe/src/main/java/org/apache/doris/catalog/ScalarType.java
  fe/src/main/java/org/apache/doris/planner/AggregationNode.java
  fe/src/main/java/org/apache/doris/planner/DistributedPlanner.java
  fe/src/main/java/org/apache/doris/planner/PlanFragment.java
  fe/src/main/java/org/apache/doris/planner/RepeatNode.java
  fe/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
  fe/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/src/main/jflex/sql_scanner.flex
  fe/src/test/java/org/apache/doris/analysis/AccessTestUtil.java
  fe/src/test/java/org/apache/doris/analysis/GroupByClauseTest.java
  fe/src/test/java/org/apache/doris/analysis/VirtualSlotRefTest.java
  fe/src/test/java/org/apache/doris/planner/RepeatNodeTest.java
  gensrc/script/doris_builtins_functions.py
  gensrc/thrift/PlanNodes.thrift
Labels: need more test, tpc-ds

#2796 Improve comparison and printing of Version
  be/src/olap/data_dir.cpp
  be/src/olap/data_dir.h
  be/src/olap/memtable.cpp
  be/src/olap/olap_common.h
  be/src/olap/olap_define.h
  be/src/olap/olap_snapshot_converter.cpp
  be/src/olap/rowset/beta_rowset.h
  be/src/olap/rowset/beta_rowset_reader.cpp
  be/src/olap/rowset/rowset.h
  be/src/olap/rowset/rowset_converter.h
  be/src/olap/rowset/rowset_meta.h
  be/src/olap/rowset/rowset_writer.h
  be/src/olap/rowset_graph.cpp
  be/src/olap/snapshot_manager.cpp
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
  be/src/olap/tablet_meta.cpp
  be/src/olap/tablet_meta.h
  be/src/olap/task/engine_clone_task.cpp
  be/src/olap/task/engine_publish_version_task.cpp
  be/src/olap/task/engine_publish_version_task.h
  be/src/olap/task/engine_task.h
  be/test/olap/olap_snapshot_converter_test.cpp
  be/test/olap/tablet_mgr_test.cpp
  be/test/olap/txn_manager_test.cpp
Labels: enhancement, storage engine
