Repository apache/doris, pull requests merged in 2020-03, with the labels that each got.

#3047 Fix orc load timestamp bug
  be/src/exec/orc_scanner.cpp
  be/test/exec/orc_scanner_test.cpp
  be/test/exec/test_data/orc_scanner/decimal_and_timestamp.orc
Labels: bug

#3044 Write delete predicate into RowsetMeta upon upgrade from Doris-0.10 to Doris-0.11
  be/src/olap/olap_snapshot_converter.cpp
  be/src/olap/olap_snapshot_converter.h
  be/src/olap/task/engine_clone_task.cpp
Labels: bug

#3096 Rewrite count distinct to bitmap hll
  docs/documentation/cn/administrator-guide/variables.md
  docs/documentation/en/administrator-guide/variables_EN.md
  fe/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java
  fe/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/src/test/java/org/apache/doris/mysql/MysqlServerTest.java
  fe/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: API changes, new feature

#2991 Output null for hll and bitmap column when select *
  be/src/runtime/result_writer.cpp
  fe/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: API changes

#3150 Support non-correlated subquery in having clause
  fe/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/src/main/java/org/apache/doris/analysis/ArithmeticExpr.java
  fe/src/main/java/org/apache/doris/analysis/BinaryPredicate.java
  fe/src/main/java/org/apache/doris/analysis/Expr.java
  fe/src/main/java/org/apache/doris/analysis/InlineViewRef.java
  fe/src/main/java/org/apache/doris/analysis/InsertStmt.java
  fe/src/main/java/org/apache/doris/analysis/OrderByElement.java
  fe/src/main/java/org/apache/doris/analysis/QueryStmt.java
  fe/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/src/main/java/org/apache/doris/analysis/SetOperationStmt.java
  fe/src/main/java/org/apache/doris/analysis/StmtRewriter.java
  fe/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/src/test/java/org/apache/doris/analysis/BinaryPredicateTest.java
  fe/src/test/java/org/apache/doris/analysis/StmtRewriterTest.java
Labels: tpc-ds

#3135 support subquery in case when statement
  fe/src/main/java/org/apache/doris/analysis/FromClause.java
  fe/src/main/java/org/apache/doris/analysis/SelectList.java
  fe/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/src/test/java/org/apache/doris/analysis/SelectStmtTest.java
Labels: tpc-ds

#3206 Rewritten subquery in having clause
  fe/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/src/test/java/org/apache/doris/analysis/StmtRewriterTest.java
Labels: bug

#3209 Add 'IndexKeysType' field in 'Desc all table stmt'
  fe/src/main/java/org/apache/doris/analysis/DescribeStmt.java
  fe/src/test/java/org/apache/doris/analysis/DescribeStmtTest.java
Labels: enhancement

#3215 Add curdate/now function in fe
  fe/src/main/java/org/apache/doris/rewrite/FEFunctions.java
  fe/src/test/java/org/apache/doris/planner/ConstantExpressTest.java
Labels: SQL Improvement, new feature

#3211 use SleepFor() instead of usleep()
  be/src/agent/task_worker_pool.cpp
  be/src/exec/broker_reader.cpp
  be/src/exprs/utility_functions.cpp
  be/src/exprs/utility_functions.h
  be/src/olap/data_dir.cpp
  be/src/olap/out_stream.cpp
  be/src/util/runtime_profile.cpp
  be/src/util/thrift_client.cpp
  be/src/util/thrift_util.cpp
  be/test/runtime/buffered_block_mgr2_test.cpp
  be/test/runtime/data_stream_test.cpp
  be/test/runtime/fragment_mgr_test.cpp
  be/test/runtime/stream_load_pipe_test.cpp
  be/test/util/thread_test.cpp
Labels: enhancement

#3225 [Bug] NPE when using unknown function in broker load process
  fe/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java
  fe/src/main/java/org/apache/doris/load/loadv2/LoadingTaskPlanner.java
  fe/src/main/java/org/apache/doris/planner/BrokerScanNode.java
Labels: API changes, bug
