Repository apache/doris, pull requests merged in 2020-11, with the labels that each got.

#4823 [Refactor] Refactor olap scan node code
  be/src/exec/olap_common.h
  be/src/exec/olap_scan_node.cpp
  be/src/exec/olap_scan_node.h
  be/src/exec/olap_scanner.cpp
Labels: approved

#4771 [LoadBalance] make BeLoadRebalancer extends from base class Rebalancer
  fe/fe-core/src/main/java/org/apache/doris/clone/BeLoadRebalancer.java
  fe/fe-core/src/main/java/org/apache/doris/clone/Rebalancer.java
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletScheduler.java
Labels: approved, area/balance, kind/enhancement

#4632 [Feature] Add CPU and Heap profile in BE webserver
  be/src/agent/utils.cpp
  be/src/agent/utils.h
  be/src/http/action/pprof_actions.cpp
  be/src/http/default_path_handlers.cpp
  be/src/http/web_page_handler.cpp
  be/src/util/CMakeLists.txt
  be/src/util/pprof_utils.cpp
  be/src/util/pprof_utils.h
  conf/be.conf
Labels: approved, area/be/frontpage, kind/enhancement, kind/feature

#4756 [FEATURE]Check date type to avoid scan all partitions
  fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/BinaryPredicatesDateRule.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: approved, area/sql/planner, kind/bug

#4829 [Compaction][Bug-Fix] Fix bug that meta lock need to be held when calculating compaction score
  be/src/olap/base_compaction.cpp
  be/src/olap/cumulative_compaction.cpp
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
  be/src/olap/tablet_manager.cpp
  be/test/olap/cumulative_compaction_policy_test.cpp
Labels: area/compact, kind/bug

#4830 [FE UI] Fix some bugs about new FE UI
  fe/fe-core/src/main/java/org/apache/doris/httpv2/controller/BaseController.java
  ui/public/locales/en-us.json
  ui/public/locales/zh-cn.json
  ui/src/components/table/index.tsx
  ui/src/components/table/table.utils.tsx
  ui/src/pages/layout/index.tsx
  ui/src/pages/playground/content/components/data-prev.tsx
  ui/src/pages/playground/content/content-result.tsx
  ui/src/pages/playground/content/content-structure.tsx
  ui/src/pages/playground/content/index.less
  ui/src/pages/playground/content/index.tsx
  ui/src/pages/playground/page-side/index.less
  ui/src/pages/playground/page-side/index.tsx
  ui/src/pages/playground/tree/index.css
  ui/src/pages/playground/tree/index.tsx
  ui/src/pages/query-profile/index.tsx
Labels: approved, area/fe/frontpage, kind/bug

#4831 Add other license declare in NOTICE
  .rat-excludes
  NOTICE.txt
  be/src/util/utf8_check.h
  conf/odbcinst.ini
  docs/en/community/release-process.md
  docs/en/community/verify-apache-release.md
  docs/zh-CN/community/release-process.md
  docs/zh-CN/community/verify-apache-release.md
  fe/fe-core/src/test/java/org/apache/doris/analysis/CancelLoadStmtTest.java
  ui/postcss.config.js
  ui/public/fonts/Read Me.txt
  ui/public/fonts/style.min.css
  ui/src/components/codemirror-with-fullscreen/doris.css
  ui/src/pages/layout/index.css
  ui/webpack.config.js
Labels: approved, kind/license

#4842 [Bug][SQL] Fix bug that query failed when SQL contains Union and Colocate join
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/test/java/org/apache/doris/qe/CoordinatorTest.java
Labels: approved, area/sql/planner, kind/bug

#4781 [Optimize] Improve LRU cache's performance
  be/src/olap/lru_cache.cpp
  be/src/olap/lru_cache.h
  be/test/olap/lru_cache_test.cpp
Labels: approved, kind/enhancement

#4796 [BUG] Catch retry submit exception
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BrokerLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BulkLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadJobScheduler.java
Labels: area/load, kind/bug

#4852 Update fe-idea-dev.md
  docs/zh-CN/developer-guide/fe-idea-dev.md
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectScheduler.java
Labels: approved, good first issue, kind/documentation

#4853 [refactor] change http server log level
  be/src/agent/task_worker_pool.cpp
  be/src/http/utils.cpp
  be/src/http/web_page_handler.cpp
Labels: approved, kind/refactor

#4869 [Bug] Fix some bugs of load job scheduler
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BrokerLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BrokerLoadPendingTask.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BulkLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadLoadingTask.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadManager.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadTask.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkLoadPendingTask.java
  fe/fe-core/src/main/java/org/apache/doris/task/MasterTaskExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/SparkLoadJobTest.java
Labels: approved, area/load, kind/bug

#4844 【Improvement】Avoid null host when forward to master
  fe/fe-core/src/main/java/org/apache/doris/qe/MasterOpExecutor.java
Labels: approved, kind/bug

#4810 [Broker Load] Ignore empty file when file format is parquet or orc.
  fe/fe-core/src/main/java/org/apache/doris/load/BrokerFileGroup.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BrokerLoadPendingTask.java
  fe/fe-core/src/main/java/org/apache/doris/planner/BrokerScanNode.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/BrokerLoadPendingTaskTest.java
Labels: approved, area/load, kind/bug

#4825 [Feature] Running Profile OLAP_SCAN_NODE layering and enhance readability
  be/src/exec/olap_scan_node.cpp
  be/src/exec/olap_scan_node.h
  be/src/exec/olap_scanner.cpp
  be/src/exec/scan_node.cpp
  be/src/exec/scan_node.h
  be/src/olap/olap_common.h
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  docs/en/administrator-guide/running-profile.md
  docs/zh-CN/administrator-guide/running-profile.md
Labels: approved, kind/documentation, kind/enhancement, kind/refactor

#4850 [Bug] Fix DCHECK failed in group_concat
  be/src/exprs/aggregate_functions.cpp
Labels: approved, kind/bug

#4870 [Bug] Rename table logic error
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/CatalogOperationTest.java
Labels: approved, area/catalog, kind/bug

#4872 [Bug] Make 'LastStartTime' in backends list as the actual BE start time
  be/src/agent/heartbeat_server.cpp
  be/src/agent/heartbeat_server.h
  fe/fe-core/src/main/java/org/apache/doris/system/Backend.java
  fe/fe-core/src/main/java/org/apache/doris/system/BackendHbResponse.java
  fe/fe-core/src/main/java/org/apache/doris/system/HeartbeatMgr.java
  gensrc/thrift/HeartbeatService.thrift
Labels: kind/bug

#4873 [DOCS] Fix some docs typo
  docs/en/administrator-guide/load-data/batch-delete-manual.md
  docs/en/administrator-guide/load-data/routine-load-manual.md
  docs/zh-CN/administrator-guide/load-data/batch-delete-manual.md
  docs/zh-CN/administrator-guide/load-data/routine-load-manual.md
Labels: kind/documentation

#4475 [Refactor] Refactor storage medium migration task process
  be/src/agent/task_worker_pool.cpp
  be/src/agent/task_worker_pool.h
  be/src/olap/snapshot_manager.cpp
  be/src/olap/tablet_meta.cpp
  be/src/olap/tablet_meta_manager.cpp
  be/src/olap/task/engine_storage_migration_task.cpp
  be/src/olap/task/engine_storage_migration_task.h
  gensrc/thrift/AgentService.thrift
Labels: kind/refactor

#4840 [Bug] Fix bug that failed to create view with complex select stmt
  fe/fe-core/src/main/java/org/apache/doris/analysis/BaseViewStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateViewStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SlotRef.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/StatementBase.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/ToSqlContext.java
  fe/fe-core/src/main/java/org/apache/doris/load/Load.java
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/CacheProxy.java
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/PartitionCache.java
Labels: kind/bug

#4861 [Bug] Fix bug that routine load blocked with TOO_MANY_TASKS error
  be/src/runtime/routine_load/data_consumer.cpp
Labels: area/load, kind/bug

#4877 Revert "[FEATURE]Check date type to avoid scan all partitions"
  fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/BinaryPredicatesDateRule.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: approved, kind/revert

#4879 [Profile][UT] Fix UT and remove useless profile
  be/src/exec/csv_scan_node.cpp
  be/src/exec/es_scan_node.cpp
  be/src/exec/mysql_scan_node.cpp
  be/src/exec/odbc_scan_node.cpp
  be/src/exec/scan_node.cpp
  be/src/exec/scan_node.h
  be/src/exec/schema_scan_node.cpp
Labels: approved, area/test

#4887 [Bug] Fix bug #4886 and #4586 by refactoring code of method 'getDbs'
  fe/fe-core/src/main/java/org/apache/doris/analysis/InsertStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/QueryStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SetOperationStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/WithClause.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/SelectStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/qe/StmtExecutorTest.java
Labels: approved, kind/bug

#4881 [Bug] Fix bug introduced by split RowsDelFiltered profile
  be/src/olap/olap_common.h
  be/src/olap/rowset/beta_rowset_reader.h
Labels: approved, kind/bug

#4858 [BUG] Fix field error in information_schema.columns
  be/src/exec/schema_scanner/schema_columns_scanner.cpp
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  gensrc/thrift/FrontendService.thrift
Labels: approved, area/mysql-compatibility, kind/bug

#4878 [Doc] Running Profile document add HASH_JOIN_NODE, etc.
  be/src/exec/union_node.cpp
  be/src/exec/union_node.h
  docs/en/administrator-guide/running-profile.md
  docs/zh-CN/administrator-guide/running-profile.md
Labels: approved, area/profile

#4884 (#4883) Java Version BitmapValue deserialized failed
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/Roaring64Map.java
  fe/spark-dpp/src/test/java/org/apache/doris/load/loadv2/dpp/BitmapValueTest.java
Labels: approved, area/spark-load, kind/bug

#4889 [BUG] modify isDecommissioned be capacity calculate rule
  fe/fe-core/src/main/java/org/apache/doris/system/SystemInfoService.java
Labels: approved, area/catalog, kind/bug

#4890 [Refactor] Remove break label for readability
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowResourcesStmt.java
Labels: approved, kind/refactor

#4895 [BUG] Fix colocate join memory limit problem (#4894)
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
Labels: approved, area/config

#4899 Added #4897: Add table_privileges, schema_privileges and user_privile…
  be/src/exec/CMakeLists.txt
  be/src/exec/schema_scanner.cpp
  be/src/exec/schema_scanner/schema_helper.cpp
  be/src/exec/schema_scanner/schema_helper.h
  be/src/exec/schema_scanner/schema_schema_privileges_scanner.cpp
  be/src/exec/schema_scanner/schema_schema_privileges_scanner.h
  be/src/exec/schema_scanner/schema_table_privileges_scanner.cpp
  be/src/exec/schema_scanner/schema_table_privileges_scanner.h
  be/src/exec/schema_scanner/schema_user_privileges_scanner.cpp
  be/src/exec/schema_scanner/schema_user_privileges_scanner.h
  fe/fe-core/src/main/java/org/apache/doris/catalog/SchemaTable.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/PaloAuth.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/PaloPrivilege.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/PrivTable.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  gensrc/thrift/FrontendService.thrift
Labels: approved, area/mysql-compatibility, good first issue

#4905 Restructure storage type to support complex types expending
  be/src/olap/CMakeLists.txt
  be/src/olap/collection.h
  be/src/olap/column_block.h
  be/src/olap/column_vector.cpp
  be/src/olap/column_vector.h
  be/src/olap/field.h
  be/src/olap/olap_common.h
  be/src/olap/row_block2.cpp
  be/src/olap/row_block2.h
  be/src/olap/rowset/column_reader.cpp
  be/src/olap/rowset/column_writer.cpp
  be/src/olap/rowset/segment_v2/binary_dict_page.cpp
  be/src/olap/rowset/segment_v2/binary_dict_page.h
  be/src/olap/rowset/segment_v2/bitmap_index_reader.cpp
  be/src/olap/rowset/segment_v2/bitshuffle_page.h
  be/src/olap/rowset/segment_v2/bloom_filter_index_reader.cpp
  be/src/olap/rowset/segment_v2/bloom_filter_index_writer.cpp
  be/src/olap/rowset/segment_v2/column_reader.cpp
  be/src/olap/rowset/segment_v2/column_reader.h
  be/src/olap/rowset/segment_v2/column_writer.cpp
  be/src/olap/rowset/segment_v2/column_writer.h
  be/src/olap/rowset/segment_v2/encoding_info.cpp
  be/src/olap/rowset/segment_v2/frame_of_reference_page.h
  be/src/olap/rowset/segment_v2/page_decoder.h
  be/src/olap/rowset/segment_v2/parsed_page.h
  be/src/olap/rowset/segment_v2/plain_page.h
  be/src/olap/rowset/segment_v2/segment.cpp
  be/src/olap/rowset/segment_v2/segment_writer.cpp
  be/src/olap/rowset/segment_v2/segment_writer.h
  be/src/olap/rowset/segment_v2/zone_map_index.cpp
  be/src/olap/tablet_schema.cpp
  be/src/olap/tablet_schema.h
  be/src/olap/types.cpp
  be/src/olap/types.h
  be/test/olap/CMakeLists.txt
  be/test/olap/column_vector_test.cpp
  be/test/olap/rowset/segment_v2/binary_dict_page_test.cpp
  be/test/olap/rowset/segment_v2/binary_plain_page_test.cpp
  be/test/olap/rowset/segment_v2/binary_prefix_page_test.cpp
  be/test/olap/rowset/segment_v2/bitshuffle_page_test.cpp
  be/test/olap/rowset/segment_v2/column_reader_writer_test.cpp
  be/test/olap/rowset/segment_v2/encoding_info_test.cpp
  be/test/olap/rowset/segment_v2/frame_of_reference_page_test.cpp
  be/test/olap/rowset/segment_v2/plain_page_test.cpp
  be/test/olap/rowset/segment_v2/rle_page_test.cpp
  be/test/olap/rowset/segment_v2/segment_test.cpp
  be/test/olap/schema_change_test.cpp
  be/test/olap/storage_types_test.cpp
  gensrc/proto/olap_file.proto
  gensrc/proto/segment_v2.proto
Labels: approved, area/storage, kind/feature

#4911 [Doc] Add keyword for routine load
  docs/zh-CN/administrator-guide/load-data/routine-load-manual.md
Labels: approved, kind/documentation

#4901 Avoid duplicate column when adding slot in empty tuple
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
Labels: approved, area/sql/planner, kind/bug

#4837 [Optimize] Take 'tablet scan frequency' into consideration when selecting a tablet for compaction
  be/src/common/config.h
  be/src/exec/olap_scanner.cpp
  be/src/olap/base_tablet.cpp
  be/src/olap/base_tablet.h
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
  be/src/olap/tablet_manager.cpp
  be/src/util/doris_metrics.cpp
  docs/en/administrator-guide/config/be_config.md
  docs/zh-CN/administrator-guide/config/be_config.md
Labels: approved, area/compact, kind/feature

#4863 [New Feature]Support udf when loading data
  fe/fe-core/src/main/java/org/apache/doris/analysis/StatementBase.java
  fe/fe-core/src/main/java/org/apache/doris/common/FeMetaVersion.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BrokerLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BulkLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadLoadingTask.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadingTaskPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/BrokerLoadJobTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/SparkLoadJobTest.java
  fe/fe-core/src/test/java/org/apache/doris/qe/ConnectProcessorTest.java
  fe/fe-core/src/test/java/org/apache/doris/qe/StmtExecutorTest.java
Labels: approved, area/load, kind/feature, kind/meta-version-change

#4909 Replace tab with spaces
  fe/fe-core/src/main/cup/sql_parser.cup
Labels: approved, kind/refactor

#4906 [Docs] Add doc of be_config.md and change some default value of BE config
  be/src/common/config.h
  docs/en/administrator-guide/config/be_config.md
  docs/zh-CN/administrator-guide/config/be_config.md
Labels: approved, kind/documentation

#4924 [Array][UT]Fix column_reader_writer_test UT
  be/test/olap/rowset/segment_v2/column_reader_writer_test.cpp
Labels: area/array-type, area/test

#4923 [Code refactor] Fix typo
  docs/en/administrator-guide/load-data/broker-load-manual.md
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadManager.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadManager.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadScheduler.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadTaskScheduler.java
  fe/fe-core/src/main/java/org/apache/doris/planner/AssertNumRowsNode.java
Labels: approved, kind/documentation

#4919 [Doc] Fix example content in bitmap_union.md
  docs/zh-CN/sql-reference/sql-functions/bitmap-functions/bitmap_union.md
Labels: approved, good first issue, kind/documentation

#4880 [Improvement]Improve list comparing performance
  fe/fe-core/src/main/java/org/apache/doris/analysis/Expr.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ExprTest.java
Labels: approved, kind/enhancement

#4904 [Optimize] Avoid repeated sending of common components in Fragments
  be/src/olap/push_handler.cpp
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/fragment_mgr.h
  be/src/runtime/plan_fragment_executor.cpp
  be/src/runtime/plan_fragment_executor.h
  be/src/runtime/runtime_state.cpp
  be/src/runtime/runtime_state.h
  be/src/runtime/test_env.cc
  be/src/service/internal_service.cpp
  be/test/runtime/buffered_block_mgr2_test.cpp
  be/test/runtime/fragment_mgr_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/common/util/QueryPlannerProfile.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/RuntimeProfile.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/rpc/BackendServiceProxy.java
  fe/fe-core/src/main/java/org/apache/doris/rpc/PBackendService.java
  gensrc/thrift/PaloInternalService.thrift
Labels: area/sql/execution, kind/enhancement

#4908 [Bug] Fix bug that be thrift client cannot connect to fe thrift server when fe thrift server use `TThreadedSelectorServer` model
  be/src/common/config.h
  be/src/runtime/client_cache.h
  be/src/util/thrift_client.h
  docs/en/administrator-guide/config/be_config.md
  docs/zh-CN/administrator-guide/config/be_config.md
Labels: approved, area/config, kind/bug

#4912 [Refactor] refactor function getScanRangeLength
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
Labels: approved, kind/refactor

#4921 [Bug] Fix partition prune (#4833)
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
Labels: approved, kind/bug

#4929 fix the FE logs dir create issue
  bin/start_fe.sh
Labels: approved, good first issue, kind/bug

#4932 [Bug] Fix the bug of NULL do not show in CTE statement.
  fe/fe-core/src/main/java/org/apache/doris/analysis/InlineViewRef.java
  fe/fe-core/src/test/java/org/apache/doris/planner/PlannerTest.java
Labels: approved, area/sql/planner

#4936 [BUG] Fix Colocate table balance bug
  fe/fe-core/src/main/java/org/apache/doris/clone/ColocateTableBalancer.java
  fe/fe-core/src/test/java/org/apache/doris/clone/ColocateTableBalancerTest.java
Labels: approved, area/balance, kind/bug

#4933 [Refactor] Short circuit return to avoid meaningless loop
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
Labels: approved, area/storage, kind/refactor

#4941 [Bug] Fix be ut compile failed and core in delta_writer_test when unlimit < 60000.
  be/src/olap/storage_engine.cpp
  be/test/olap/delta_writer_test.cpp
  be/test/runtime/fragment_mgr_test.cpp
Labels: approved, area/test, kind/bug

#4950 [Refator]Modify code write error
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/PartitionCache.java
Labels: approved, kind/cleanup

#4914 【Optimize】optimize host selection strategy
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/test/java/org/apache/doris/qe/CoordinatorTest.java
Labels: approved, kind/enhancement

#4943 [Feature] Show FE commit hash on proc
  fe/fe-core/src/main/java/org/apache/doris/common/proc/FrontendsProcNode.java
  fe/fe-core/src/main/java/org/apache/doris/http/rest/BootstrapFinishAction.java
  fe/fe-core/src/main/java/org/apache/doris/qe/GlobalVariable.java
  fe/fe-core/src/main/java/org/apache/doris/system/Frontend.java
  fe/fe-core/src/main/java/org/apache/doris/system/FrontendHbResponse.java
  fe/fe-core/src/main/java/org/apache/doris/system/HeartbeatMgr.java
  fe/fe-core/src/test/java/org/apache/doris/system/HeartbeatMgrTest.java
  gensrc/script/gen_build_version.sh
Labels: approved, kind/enhancement

#4953 fix httpv2 append extra useless information in get_small_file api
  fe/fe-core/src/main/java/org/apache/doris/httpv2/entity/ResponseEntityBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/GetSmallFileAction.java
Labels: approved, kind/bug

#4954 [Improvement] Add parquet file name to the error message
  be/src/exec/parquet_scanner.cpp
Labels: approved, area/load, kind/bug

#4968 [Bug]Parquet map/list/struct structure recognize
  be/src/exec/parquet_reader.cpp
Labels: approved, area/load, kind/bug

#4972 [Doris On ES][Bug-Fix] fix problem for selecting random be
  fe/fe-core/src/main/java/org/apache/doris/external/elasticsearch/EsShardPartitions.java
Labels: approved, area/doris-on-es, kind/bug

#4955 [BUG] Fix colocate balance bug when there is decommissioned be
  fe/fe-core/src/main/java/org/apache/doris/clone/ColocateTableBalancer.java
  fe/fe-core/src/test/java/org/apache/doris/clone/ColocateTableBalancerTest.java
Labels: approved, area/balance, kind/bug

#4893 [Metrics][LOG] Add metrics for compaction permits and log for merge rowsets
  be/src/common/config.h
  be/src/olap/compaction_permit_limiter.cpp
  be/src/olap/compaction_permit_limiter.h
  be/src/olap/merger.cpp
  be/src/util/doris_metrics.cpp
  be/src/util/doris_metrics.h
  docs/en/administrator-guide/config/be_config.md
  docs/zh-CN/administrator-guide/config/be_config.md
Labels: area/compact, kind/enhancement

#4979 [Compile][Bug] Fix FE compilation bug
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
Labels: area/build, kind/bug

#4975 Fix locate bug when start_pos larger than str len
  be/src/exprs/string_functions.cpp
Labels: approved, area/sql/execution, kind/bug

#4978 Use the right queryId to audit master only query in non master
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/MasterOpExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  gensrc/thrift/FrontendService.thrift
Labels: approved, area/sql, kind/bug

#4891 [Refactor] Execute 'pick rowsets' before applying for permits for a compaction task
  be/src/olap/base_compaction.cpp
  be/src/olap/base_compaction.h
  be/src/olap/compaction.cpp
  be/src/olap/compaction.h
  be/src/olap/cumulative_compaction.cpp
  be/src/olap/cumulative_compaction.h
  be/src/olap/olap_define.h
  be/src/olap/olap_server.cpp
  be/src/olap/storage_engine.cpp
  be/src/olap/storage_engine.h
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
  be/src/olap/task/engine_clone_task.cpp
Labels: approved, area/compact, kind/enhancement

#4964 [Bug][Compaction] Fix bug that output rowset is not deleted after compaction failure.
  be/src/olap/base_compaction.cpp
  be/src/olap/base_compaction.h
  be/src/olap/compaction.cpp
  be/src/olap/compaction.h
  be/src/olap/cumulative_compaction.cpp
  be/src/olap/cumulative_compaction.h
  be/src/olap/olap_common.h
  be/src/olap/reader.h
  fe/fe-core/src/test/java/org/apache/doris/catalog/CreateFunctionTest.java
Labels: approved, area/compact, kind/bug
