Repository apache/doris, pull requests merged in 2020-05, with the labels that each got.

#3445 fix delete statement doc display not correctly
  docs/en/sql-reference/sql-statements/Data Manipulation/DELETE.md
Labels: document, enhancement

#3463 vector reserve before push_back
  be/src/olap/rowset/segment_v2/segment_writer.cpp
  thirdparty/build-thirdparty.sh
Labels: approved

#3462 [Memory Engine] Add hash index implementation
  be/src/olap/memory/CMakeLists.txt
  be/src/olap/memory/hash_index.cpp
  be/src/olap/memory/hash_index.h
  be/test/olap/CMakeLists.txt
  be/test/olap/memory/hash_index_test.cpp
  run-ut.sh
Labels: area/storage/in-memory

#3489 fix mismatched tags
  be/src/env/env.h
Labels: approved, area/storage, kind/cleanup

#3478 replace std::tr1::unordered_map with std::unordered_map
  be/src/runtime/descriptors.h
Labels: approved, area/sql/execution, kind/cleanup

#3143 Non blocking OlapTableSink
  be/src/common/config.h
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
  be/test/exec/tablet_sink_test.cpp
Labels: approved, area/load, kind/feature

#3396 (#3395)calculate 'case when expr' when possible
  fe/src/main/java/org/apache/doris/analysis/CaseExpr.java
  fe/src/main/java/org/apache/doris/rewrite/FoldConstantsRule.java
  fe/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: approved, area/sql/execution, area/sql/function

#3502 fix a compile error
  be/src/exec/tablet_sink.cpp
Labels: approved, area/sql/execution, kind/bug

#3512 Update travis.yml
  .travis.yml
Labels: approved, area/website

#3499 Update UT compile path
  .gitignore
  run-ut.sh
Labels: approved, area/build, kind/feature

#3511 [Bug] Fix constant In Predicate result error
  fe/src/main/java/org/apache/doris/analysis/InPredicate.java
  fe/src/test/java/org/apache/doris/planner/ConstantExpressTest.java
  fe/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: area/sql/execution, kind/bug

#3501 Fix the incorrect docs
  docs/en/sql-reference/sql-statements/Data Manipulation/LOAD.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/LOAD.md
Labels: approved, kind/documentation

#3497 [BugFix] Fix the bug let fe can show each fragment execute time percent
  fe/src/main/java/org/apache/doris/common/util/RuntimeProfile.java
  fe/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/src/main/java/org/apache/doris/qe/StmtExecutor.java
Labels: approved, area/profile, area/util, kind/bug

#3485 Enhance AssertNumRowsNode
  be/src/exec/assert_num_rows_node.cpp
  be/src/exec/assert_num_rows_node.h
  fe/src/main/java/org/apache/doris/analysis/ArithmeticExpr.java
  fe/src/main/java/org/apache/doris/analysis/AssertNumRowsElement.java
  fe/src/main/java/org/apache/doris/analysis/BinaryPredicate.java
  fe/src/main/java/org/apache/doris/analysis/QueryStmt.java
  fe/src/main/java/org/apache/doris/planner/AssertNumRowsNode.java
  gensrc/thrift/PlanNodes.thrift
Labels: approved, area/sql/execution

#3486 [BUG] Fix a bug that ignore_broken_disk may not work
  be/src/olap/options.cpp
  be/src/service/doris_main.cpp
Labels: approved, area/storage, kind/bug

#3493 make build script portable on Mac OS
  build.sh
  thirdparty/build-thirdparty.sh
Labels: approved, area/build, kind/feature

#3515 [Bug] Fix bug that SHOW DELETE not return Delete job info
  fe/src/main/java/org/apache/doris/common/MarkedCountDownLatch.java
  fe/src/main/java/org/apache/doris/load/DeleteHandler.java
  fe/src/main/java/org/apache/doris/load/DeleteJob.java
  fe/src/main/java/org/apache/doris/transaction/TxnStateCallbackFactory.java
Labels: approved, area/catalog, kind/bug

#3439 Support append_trailing_char_if_absent function
  be/src/exprs/string_functions.cpp
  be/src/exprs/string_functions.h
  be/test/exprs/string_functions_test.cpp
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/sql-reference/sql-functions/string-functions/append_trailing_char_if_absent.md
  docs/zh-CN/sql-reference/sql-functions/string-functions/append_trailing_char_if_absent.md
  gensrc/script/doris_builtins_functions.py
Labels: approved, area/sql/compatibility, kind/api-change, kind/feature, release-note

#3524 [ut] disable backgrounp scan context gc to speed up unit test
  be/src/runtime/external_scan_context_mgr.cpp
  be/test/runtime/external_scan_context_mgr_test.cpp
Labels: approved, area/test, kind/feature

#3521 [Bug] Fix BE crash when input to hll_merge is null
  be/src/exprs/hll_function.cpp
Labels: SQL Bug, approved, area/sql/execution, kind/bug

#3505 Update plugin document
  .gitignore
  docs/en/extending-doris/audit-plugin.md
  docs/en/extending-doris/plugin-development-manual.md
  docs/en/sql-reference/sql-statements/Administration/INSTALL PLUGIN.md
  docs/zh-CN/extending-doris/audit-plugin.md
  docs/zh-CN/extending-doris/plugin-development-manual.md
  docs/zh-CN/sql-reference/sql-statements/Administration/INSTALL PLUGIN.md
Labels: approved, kind/documentation

#3322 Remove redundant com.baidu:jprotobuf
  fe/pom.xml
Labels: approved, area/build, kind/feature

#3488 [Config] allow user to config BRPC socket_max_unwritten_bytes
  be/src/common/config.h
  be/src/service/brpc_service.cpp
  docs/en/administrator-guide/config/be_config.md
  docs/zh-CN/administrator-guide/config/be_config.md
Labels: kind/feature

#3547 Identify old empty tablet when add tablet to meta in ReportHandler
  fe/src/main/java/org/apache/doris/master/ReportHandler.java
Labels: approved, area/catalog

#3495 [ASAN] Fix some address problems detected by ASAN
  be/src/http/ev_http_server.cpp
  be/src/runtime/runtime_state.cpp
  be/src/runtime/runtime_state.h
  be/src/util/debug/leakcheck_disabler.h
  be/src/util/dynamic_util.cpp
  be/src/util/mem_util.hpp
  be/src/util/path_util.cpp
  be/src/util/url_coding.cpp
  be/test/agent/utils_test.cpp
  be/test/exec/broker_scan_node_test.cpp
  be/test/exec/tablet_sink_test.cpp
  be/test/exprs/timestamp_functions_test.cpp
  be/test/geo/wkt_parse_test.cpp
  be/test/olap/in_list_predicate_test.cpp
  be/test/olap/key_coder_test.cpp
  be/test/olap/rowset/rowset_converter_test.cpp
  be/test/olap/rowset/segment_v2/binary_dict_page_test.cpp
  be/test/olap/rowset/segment_v2/binary_prefix_page_test.cpp
  be/test/olap/rowset/segment_v2/bitmap_index_test.cpp
  be/test/olap/schema_change_test.cpp
  be/test/plugin/plugin_zip_test.cpp
  be/test/runtime/memory_scratch_sink_test.cpp
  be/test/util/aes_util_test.cpp
  be/test/util/zip_util_test.cpp
Labels: approved, area/sql/execution, area/storage, kind/cleanup

#3533 Add -Werror when gcc<=7.3.0 & udf fix
  be/CMakeLists.txt
  be/src/udf/udf.cpp
Labels: approved, area/build, kind/feature

#3542 Throw a UserException when miss plugin's md5 file
  fe/src/main/java/org/apache/doris/plugin/PluginZip.java
Labels: approved, area/plugin, kind/bug

#3513 [Doris On ES]fix bug of query failed in doc_value_mode when fields have none value
  be/src/exec/es/es_scan_reader.cpp
  be/src/exec/es/es_scan_reader.h
  be/src/exec/es/es_scroll_parser.cpp
  be/src/exec/es/es_scroll_parser.h
  be/src/exec/es/es_scroll_query.cpp
  be/src/exec/es/es_scroll_query.h
  be/src/exec/es_http_scan_node.cpp
  be/src/exec/es_http_scanner.cpp
  be/src/exec/es_http_scanner.h
  be/test/exec/es_scan_reader_test.cpp
Labels: approved, area/doris-on-es, area/sql/execution, kind/bug

#3532 Remove unused ColumnType
  be/test/runtime/CMakeLists.txt
  be/test/runtime/dpp_writer_test.cpp
  be/test/runtime/mysql_table_writer_test.cpp
  be/test/runtime/result_writer_test.cpp
  gensrc/proto/olap_file.proto
Labels: approved, area/test, kind/cleanup

#3539 Throw DdlException when use admin set frontend config
  fe/src/main/java/org/apache/doris/analysis/AdminSetConfigStmt.java
  fe/src/test/java/org/apache/doris/analysis/AminSetConfigStmtTest.java
Labels: approved, area/catalog

#3369 Support txn management in db level isolation and use ArrayDeque to improve txn task performance
  .gitignore
  fe/src/main/java/org/apache/doris/analysis/InsertStmt.java
  fe/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/src/main/java/org/apache/doris/catalog/CatalogRecycleBin.java
  fe/src/main/java/org/apache/doris/catalog/TabletInvertedIndex.java
  fe/src/main/java/org/apache/doris/common/proc/TransPartitionProcNode.java
  fe/src/main/java/org/apache/doris/common/proc/TransProcDir.java
  fe/src/main/java/org/apache/doris/common/proc/TransTablesProcDir.java
  fe/src/main/java/org/apache/doris/load/DeleteHandler.java
  fe/src/main/java/org/apache/doris/load/Load.java
  fe/src/main/java/org/apache/doris/load/LoadChecker.java
  fe/src/main/java/org/apache/doris/load/loadv2/BrokerLoadJob.java
  fe/src/main/java/org/apache/doris/load/loadv2/LoadJob.java
  fe/src/main/java/org/apache/doris/load/loadv2/LoadManager.java
  fe/src/main/java/org/apache/doris/load/routineload/RoutineLoadJob.java
  fe/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  fe/src/main/java/org/apache/doris/task/HadoopLoadPendingTask.java
  fe/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java
  fe/src/main/java/org/apache/doris/transaction/GlobalTransactionMgr.java
  fe/src/main/java/org/apache/doris/transaction/PublishVersionDaemon.java
  fe/src/test/java/org/apache/doris/load/DeleteHandlerTest.java
  fe/src/test/java/org/apache/doris/task/LoadPendingTaskTest.java
  fe/src/test/java/org/apache/doris/transaction/DatabaseTransactionMgrTest.java
  fe/src/test/java/org/apache/doris/transaction/GlobalTransactionMgrTest.java
Labels: approved, area/catalog, area/load, enhancement

#3557 [Bug] Fix compile bug
  fe/src/test/java/org/apache/doris/analysis/AdminSetConfigStmtTest.java
Labels: kind/bug

#3565 [Bug] Fix bug of transaction manager
  fe/src/main/java/org/apache/doris/mysql/privilege/PaloAuth.java
  fe/src/main/java/org/apache/doris/transaction/GlobalTransactionMgr.java
Labels: kind/bug

#3522 [community] Add Committer Guide
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/community/committer-guide.md
  docs/zh-CN/community/committer-guide.md
Labels: approved, area/community, area/website, kind/documentation

#3535 [Feature]support documents' fulltext searching (master)
  .travis.yml
  docs/.vuepress/config.js
  docs/README.md
  docs/readme.md
Labels: area/website, kind/feature

#3536 [Feature]support documents' fulltext searching (branch-0.12)
  .travis.yml
  docs/.vuepress/config.js
  docs/README.md
  docs/readme.md
Labels: area/website, kind/feature

#3537 [Feature]support documents' fulltext searching (branch-0.11)
  .travis.yml
  docs/.vuepress/config.js
  docs/README.md
  docs/readme.md
Labels: area/website, kind/feature

#3544 [FIX] fix some doris web page dispaly error
  fe/src/main/java/org/apache/doris/http/action/HelpAction.java
  fe/src/main/java/org/apache/doris/http/action/LogAction.java
  fe/src/main/java/org/apache/doris/http/action/StaticResourceAction.java
  fe/src/main/java/org/apache/doris/http/action/SystemAction.java
  fe/src/main/java/org/apache/doris/http/action/WebBaseAction.java
  webroot/static/bootstrap-theme.css
  webroot/static/bootstrap-theme.css.map
  webroot/static/bootstrap.css
  webroot/static/bootstrap.css.map
  webroot/static/doris-logo.png
  webroot/static/favicon.ico
  webroot/static/glyphicons-halflings-regular.eot
  webroot/static/glyphicons-halflings-regular.svg
  webroot/static/glyphicons-halflings-regular.ttf
  webroot/static/glyphicons-halflings-regular.woff
  webroot/static/glyphicons-halflings-regular.woff2
Labels: approved, area/fe/frontpage

#3476 [Bug] Fix bug of Partition prune of constant in predicate
  fe/src/main/java/org/apache/doris/catalog/Partition.java
  fe/src/main/java/org/apache/doris/planner/OlapScanNode.java
  fe/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
  fe/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: approved, area/sql/planner, kind/bug

#3548 add doc link to char_length
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/sql-reference/sql-functions/string-functions/char_length.md
  docs/zh-CN/sql-reference/sql-functions/string-functions/char_length.md
Labels: approved, kind/documentation

#3424 allow delete duplicated non-key column using delete from
  be/CMakeLists.txt
  be/src/olap/delete_handler.cpp
  be/src/olap/olap_cond.cpp
  be/src/olap/olap_cond.h
  be/src/olap/rowset/alpha_rowset.cpp
  be/src/olap/rowset/column_data.cpp
  be/src/olap/rowset/column_data.h
  be/src/olap/rowset/column_data_writer.cpp
  be/src/olap/rowset/segment_group.cpp
  be/src/olap/rowset/segment_group.h
  be/src/olap/rowset/segment_v2/segment_writer.cpp
  be/src/olap/schema_change.cpp
  be/src/runtime/thread_resource_mgr.cpp
  be/src/util/path_util.cpp
  be/test/olap/delete_handler_test.cpp
  fe/src/main/java/org/apache/doris/alter/MaterializedViewHandler.java
  fe/src/main/java/org/apache/doris/load/DeleteHandler.java
Labels: approved, area/delete, kind/feature

#3551 [Bug] restore tablet action not working because tablet status is shutdown
  be/src/http/action/restore_tablet_action.cpp
  be/src/olap/storage_engine.cpp
  be/src/olap/storage_engine.h
  be/src/olap/tablet_manager.cpp
  be/src/olap/tablet_manager.h
Labels: approved, area/storage, kind/bug

#3558 report error when subquery in case-when returns empty set
  fe/src/main/java/org/apache/doris/analysis/CaseExpr.java
  fe/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/src/main/java/org/apache/doris/planner/AssertNumRowsNode.java
Labels: area/sql, kind/bug

#3573 [Fix]modify download links & remove some links' suffix `_EN`(master)
  docs/en/administrator-guide/alter-table/alter-table-bitmap-index.md
  docs/en/community/verify-apache-release.md
  docs/en/downloads/downloads.md
  docs/zh-CN/community/verify-apache-release.md
  docs/zh-CN/downloads/downloads.md
Labels: approved, area/website, kind/feature

#3574 [Fix]modify download links & remove some links' suffix `_EN`(branch-0.12)
  docs/en/administrator-guide/alter-table/alter-table-bitmap-index.md
  docs/en/community/verify-apache-release.md
  docs/en/downloads/downloads.md
  docs/zh-CN/community/verify-apache-release.md
  docs/zh-CN/downloads/downloads.md
Labels: approved, area/website, kind/bug

#3594 [incubator-doris][thirdpary][glog][bug] calucate file length at the start
  thirdparty/patches/glog-0.3.3-for-palo2.patch
Labels: approved, area/dependency, kind/bug

#3598 Improve the running profile.
  be/src/exec/partitioned_aggregation_node.cc
  be/src/exec/partitioned_aggregation_node.h
  be/src/exec/partitioned_hash_table.cc
  be/src/exec/partitioned_hash_table.h
  be/src/runtime/data_stream_recvr.cc
  be/src/runtime/data_stream_sender.cpp
  be/src/runtime/data_stream_sender.h
Labels: approved, area/profile

#3561 [Bug] generate exceptions to avoid mulitDistinctAggregation produce wrong result #3492
  fe/src/main/java/org/apache/doris/analysis/AggregateInfo.java
  fe/src/test/java/org/apache/doris/analysis/AggregateTest.java
Labels: approved, area/sql/planner, kind/bug

#3605 [Bug] Fix bug that descriptor table is not reset before planning next routine load task
  fe/src/main/java/org/apache/doris/analysis/DescriptorTable.java
  fe/src/main/java/org/apache/doris/planner/StreamLoadPlanner.java
Labels: area/load, kind/bug

#3597 [Bug] fix OrCompoundPredicate predicate fold bug #3596
  fe/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: approved, area/sql/planner, kind/bug

#3577 [Fix]SlotRef.tosql() is the same as the SQL returned by different sql
  fe/src/main/java/org/apache/doris/analysis/SlotRef.java
  fe/src/test/java/org/apache/doris/analysis/StmtRewriterTest.java
Labels: approved, area/sql/planner

#3599 [Bug] Fix bug that DbTxnMgr does not create for db in CatalogRecycleBin
  fe/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/src/main/java/org/apache/doris/catalog/CatalogRecycleBin.java
  fe/src/main/java/org/apache/doris/qe/AuditEventProcessor.java
  fe/src/main/java/org/apache/doris/transaction/GlobalTransactionMgr.java
Labels: approved, area/catalog, kind/bug

#3587 [Bug] Fix bug that ConcurrentModificationException thrown
  fe/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/src/main/java/org/apache/doris/catalog/PartitionInfo.java
  fe/src/main/java/org/apache/doris/catalog/TempPartitions.java
  fe/src/main/java/org/apache/doris/cluster/Cluster.java
Labels: area/catalog, kind/bug

#3523 Refactor some redunant code && Replace some UT by UtFrameUtils
  fe/src/main/java/org/apache/doris/alter/AlterJob.java
  fe/src/main/java/org/apache/doris/backup/RestoreJob.java
  fe/src/main/java/org/apache/doris/catalog/Database.java
  fe/src/main/java/org/apache/doris/catalog/MaterializedIndex.java
  fe/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/src/main/java/org/apache/doris/catalog/Partition.java
  fe/src/main/java/org/apache/doris/catalog/PartitionInfo.java
  fe/src/main/java/org/apache/doris/catalog/Replica.java
  fe/src/main/java/org/apache/doris/catalog/Tablet.java
  fe/src/main/java/org/apache/doris/catalog/TabletMeta.java
  fe/src/main/java/org/apache/doris/clone/BackendLoadStatistic.java
  fe/src/main/java/org/apache/doris/clone/RootPathLoadStatistic.java
  fe/src/main/java/org/apache/doris/clone/TabletScheduler.java
  fe/src/main/java/org/apache/doris/common/proc/ClusterLoadStatisticProcDir.java
  fe/src/main/java/org/apache/doris/system/BackendHbResponse.java
  fe/src/main/java/org/apache/doris/system/BrokerHbResponse.java
  fe/src/test/java/org/apache/doris/catalog/DynamicPartitionTableTest.java
  fe/src/test/java/org/apache/doris/common/PropertyAnalyzerTest.java
Labels: approved, area/test, kind/cleanup

#3572 [trace] Introduce trace util to BE
  be/src/common/logconfig.cpp
  be/src/util/CMakeLists.txt
  be/src/util/logging.h
  be/src/util/trace.cpp
  be/src/util/trace.h
  be/src/util/trace_metrics.cpp
  be/src/util/trace_metrics.h
  be/test/util/CMakeLists.txt
  be/test/util/trace_test.cpp
Labels: approved, area/util

#3581 [Doc] Update table-restore-tool.md
  docs/zh-CN/administrator-guide/operation/tablet-restore-tool.md
Labels: kind/documentation

#3608 Revert "[Bug] Fix bug that descriptor table is not reset before planning next routine load task"
  fe/src/main/java/org/apache/doris/analysis/DescriptorTable.java
  fe/src/main/java/org/apache/doris/planner/StreamLoadPlanner.java
Labels: kind/revert

#3609 Revert "[Bug] fix OrCompoundPredicate predicate fold bug #3596"
  fe/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: kind/revert

#3610 Revert "[Fix]SlotRef.tosql() is the same as the SQL returned by different sql"
  fe/src/main/java/org/apache/doris/analysis/SlotRef.java
  fe/src/test/java/org/apache/doris/analysis/StmtRewriterTest.java
Labels: kind/revert

#3611 Revert "[Bug] Fix bug that DbTxnMgr does not create for db in CatalogRecycleBin"
  fe/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/src/main/java/org/apache/doris/catalog/CatalogRecycleBin.java
  fe/src/main/java/org/apache/doris/qe/AuditEventProcessor.java
  fe/src/main/java/org/apache/doris/transaction/GlobalTransactionMgr.java
Labels: kind/revert

#3612 Revert "[Bug] Fix bug that ConcurrentModificationException thrown "
  fe/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/src/main/java/org/apache/doris/catalog/PartitionInfo.java
  fe/src/main/java/org/apache/doris/catalog/TempPartitions.java
  fe/src/main/java/org/apache/doris/cluster/Cluster.java
Labels: kind/revert

#3613 Revert "Refactor some redundant code && Replace some UT by UtFrameUtils"
  fe/src/main/java/org/apache/doris/alter/AlterJob.java
  fe/src/main/java/org/apache/doris/backup/RestoreJob.java
  fe/src/main/java/org/apache/doris/catalog/Database.java
  fe/src/main/java/org/apache/doris/catalog/MaterializedIndex.java
  fe/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/src/main/java/org/apache/doris/catalog/Partition.java
  fe/src/main/java/org/apache/doris/catalog/PartitionInfo.java
  fe/src/main/java/org/apache/doris/catalog/Replica.java
  fe/src/main/java/org/apache/doris/catalog/Tablet.java
  fe/src/main/java/org/apache/doris/catalog/TabletMeta.java
  fe/src/main/java/org/apache/doris/clone/BackendLoadStatistic.java
  fe/src/main/java/org/apache/doris/clone/RootPathLoadStatistic.java
  fe/src/main/java/org/apache/doris/clone/TabletScheduler.java
  fe/src/main/java/org/apache/doris/common/proc/ClusterLoadStatisticProcDir.java
  fe/src/main/java/org/apache/doris/system/BackendHbResponse.java
  fe/src/main/java/org/apache/doris/system/BrokerHbResponse.java
  fe/src/test/java/org/apache/doris/catalog/DynamicPartitionTableTest.java
  fe/src/test/java/org/apache/doris/common/PropertyAnalyzerTest.java
Labels: kind/revert

#3614 Revert "[trace] Introduce trace util to BE"
  be/src/common/logconfig.cpp
  be/src/util/CMakeLists.txt
  be/src/util/logging.h
  be/src/util/trace.cpp
  be/src/util/trace.h
  be/src/util/trace_metrics.cpp
  be/src/util/trace_metrics.h
  be/test/util/CMakeLists.txt
  be/test/util/trace_test.cpp
Labels: kind/revert

#3607 [Doc] Update table-restore-tool.md
  docs/zh-CN/administrator-guide/operation/tablet-restore-tool.md
Labels: kind/cleanup, kind/documentation, kind/revert

#3615 [Bug] Fix bug that descriptor table is not reset before planning next routine load task
  fe/src/main/java/org/apache/doris/analysis/DescriptorTable.java
  fe/src/main/java/org/apache/doris/planner/StreamLoadPlanner.java
Labels: kind/cleanup, kind/revert

#3616 [Bug] fix OrCompoundPredicate predicate fold bug #3596
  fe/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: kind/cleanup, kind/revert

#3617 [Fix]SlotRef.tosql() is the same as the SQL returned by different sql
  fe/src/main/java/org/apache/doris/analysis/SlotRef.java
  fe/src/test/java/org/apache/doris/analysis/StmtRewriterTest.java
Labels: kind/cleanup, kind/revert

#3618 [Bug] Fix bug that DbTxnMgr does not create for db in CatalogRecycleBin
  fe/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/src/main/java/org/apache/doris/catalog/CatalogRecycleBin.java
  fe/src/main/java/org/apache/doris/qe/AuditEventProcessor.java
  fe/src/main/java/org/apache/doris/transaction/GlobalTransactionMgr.java
Labels: kind/cleanup, kind/revert

#3619 [Bug] Fix bug that ConcurrentModificationException thrown
  fe/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/src/main/java/org/apache/doris/catalog/PartitionInfo.java
  fe/src/main/java/org/apache/doris/catalog/TempPartitions.java
  fe/src/main/java/org/apache/doris/cluster/Cluster.java
Labels: kind/cleanup, kind/revert

#3620 [Refactor] Refactor some redundant code && Replace some UT by UtFrameUtils
  fe/src/main/java/org/apache/doris/alter/AlterJob.java
  fe/src/main/java/org/apache/doris/backup/RestoreJob.java
  fe/src/main/java/org/apache/doris/catalog/Database.java
  fe/src/main/java/org/apache/doris/catalog/MaterializedIndex.java
  fe/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/src/main/java/org/apache/doris/catalog/Partition.java
  fe/src/main/java/org/apache/doris/catalog/PartitionInfo.java
  fe/src/main/java/org/apache/doris/catalog/Replica.java
  fe/src/main/java/org/apache/doris/catalog/Tablet.java
  fe/src/main/java/org/apache/doris/catalog/TabletMeta.java
  fe/src/main/java/org/apache/doris/clone/BackendLoadStatistic.java
  fe/src/main/java/org/apache/doris/clone/RootPathLoadStatistic.java
  fe/src/main/java/org/apache/doris/clone/TabletScheduler.java
  fe/src/main/java/org/apache/doris/common/proc/ClusterLoadStatisticProcDir.java
  fe/src/main/java/org/apache/doris/system/BackendHbResponse.java
  fe/src/main/java/org/apache/doris/system/BrokerHbResponse.java
  fe/src/test/java/org/apache/doris/catalog/DynamicPartitionTableTest.java
  fe/src/test/java/org/apache/doris/common/PropertyAnalyzerTest.java
Labels: kind/cleanup, kind/revert

#3621 [trace] Introduce trace util to BE
  be/src/common/logconfig.cpp
  be/src/util/CMakeLists.txt
  be/src/util/logging.h
  be/src/util/trace.cpp
  be/src/util/trace.h
  be/src/util/trace_metrics.cpp
  be/src/util/trace_metrics.h
  be/test/util/CMakeLists.txt
  be/test/util/trace_test.cpp
Labels: kind/cleanup, kind/revert

#3575 [Fix]modify download links(branch-0.11)
  docs/en/community/verify-apache-release.md
  docs/zh-CN/community/verify-apache-release.md
Labels: area/website, kind/bug

#3631 [Spark on Doris] Shade and provide the thrift lib in spark-doris-connector
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/extending-doris/spark-doris-connector.md
  docs/zh-CN/extending-doris/spark-doris-connector.md
  extension/spark-doris-connector/build.sh
  extension/spark-doris-connector/pom.xml
  fe/src/test/java/org/apache/doris/analysis/AggregateTest.java
Labels: approved, area/spark-connector, kind/documentation

#3602 [Doris On ES]fix bug of like not translate correcttly
  be/src/exec/es/es_query_builder.cpp
Labels: approved, area/doris-on-es, kind/bug

#3592 [Bug] instance mem tracker should has no limit
  be/src/runtime/runtime_state.cpp
Labels: approved, area/sql/execution, kind/bug

#3628 Fix first start error after upgrade doris to support delete dulplicate table value columns
  be/src/olap/rowset/alpha_rowset.cpp
Labels: approved, area/storage, kind/bug

#3632 Add ignore config to determine whether to continue to start be when load tablet from header failed.
  be/src/common/config.h
  be/src/olap/data_dir.cpp
  docs/en/administrator-guide/config/be_config.md
  docs/zh-CN/administrator-guide/config/be_config.md
  thirdparty/vars.sh
Labels: approved, area/config

#3580 [Memory Engine] Add column reader/writer
  be/src/olap/memory/column.cpp
  be/src/olap/memory/column.h
  be/src/olap/memory/column_reader.h
  be/src/olap/memory/column_writer.h
  be/src/olap/memory/typed_column_reader.h
  be/src/olap/memory/typed_column_writer.h
  be/test/olap/CMakeLists.txt
  be/test/olap/memory/column_test.cpp
  be/test/olap/memory/hash_index_test.cpp
Labels: area/storage/in-memory

#3571 Support bitmap_intersect
  be/src/exprs/bitmap_function.cpp
  be/src/exprs/bitmap_function.h
  be/test/exprs/bitmap_function_test.cpp
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/sql-reference/sql-functions/bitmap-functions/bitmap_intersect.md
  docs/en/sql-reference/sql-functions/bitmap-functions/bitmap_union.md
  docs/zh-CN/sql-reference/sql-functions/bitmap-functions/bitmap_intersect.md
  docs/zh-CN/sql-reference/sql-functions/bitmap-functions/bitmap_union.md
  fe/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java
  fe/src/main/java/org/apache/doris/catalog/FunctionSet.java
Labels: api-review, area/sql/function, kind/feature

#3641 [Bug] Ignore loading DELETE status tablet error when restarting BE
  be/src/olap/data_dir.cpp
  be/src/olap/tablet_manager.cpp
  be/src/tools/meta_tool.cpp
  docs/en/administrator-guide/config/be_config.md
  docs/en/administrator-guide/operation/tablet-meta-tool.md
  docs/zh-CN/administrator-guide/config/be_config.md
  docs/zh-CN/administrator-guide/operation/tablet-meta-tool.md
Labels: area/storage, area/util, kind/bug

#3643 fix mem limit in NodeChannel
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
Labels: approved, area/load, kind/bug

#3653 [BugFix] fix travis build timeout (master)
  .travis.yml
Labels: approved, area/website

#3657 Add docs of max_running_txn_num_per_db
  docs/en/administrator-guide/load-data/load-manual.md
  docs/zh-CN/administrator-guide/load-data/load-manual.md
Labels: approved, kind/documentation

#3625 Support more syntax in case when clause
  fe/src/main/java/org/apache/doris/analysis/CaseExpr.java
  fe/src/test/java/org/apache/doris/analysis/SelectStmtTest.java
Labels: approved, area/sql/function, kind/feature

#3664 Fix the ut error of bitmap_intersect
  be/test/exprs/bitmap_function_test.cpp
Labels: area/test, kind/bug

#3647 [Enhancement] Add detail msg to show the reason of publish failure.
  fe/src/main/java/org/apache/doris/common/proc/TransProcDir.java
  fe/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java
  fe/src/main/java/org/apache/doris/transaction/PublishVersionDaemon.java
  fe/src/main/java/org/apache/doris/transaction/TransactionState.java
  fe/src/test/java/org/apache/doris/transaction/DatabaseTransactionMgrTest.java
Labels: approved, area/load

#3662 [Bug] Fix bug that missing OP_SET_REPLICA_STATUS when reading journal
  fe/src/main/java/org/apache/doris/journal/JournalEntity.java
Labels: approved, area/catalog, kind/bug

#3656 Modify hll_hash function return type to HLL
  fe/src/main/cup/sql_parser.cup
  fe/src/main/java/org/apache/doris/catalog/FunctionSet.java
  gensrc/script/doris_builtins_functions.py
Labels: approved, area/sql/function, kind/feature

#3674 [Bug] Fix bug that runningTxnNum does not equal to the real running txn num
  fe/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java
Labels: approved, area/load, kind/bug

#3651 Support create materialized view with bitmap or hll
  fe/src/main/java/org/apache/doris/alter/MaterializedViewHandler.java
  fe/src/main/java/org/apache/doris/analysis/CreateMaterializedViewStmt.java
  fe/src/main/java/org/apache/doris/analysis/DescribeStmt.java
  fe/src/main/java/org/apache/doris/analysis/MVColumnItem.java
  fe/src/main/java/org/apache/doris/catalog/Column.java
  gensrc/thrift/AgentService.thrift
Labels: area/materialized-view, kind/feature

#3670 Allow user to set thrift_client_timeout_ms config for thrift server
  docs/en/administrator-guide/config/fe_config.md
  docs/zh-CN/administrator-guide/config/fe_config.md
  fe/src/main/java/org/apache/doris/common/Config.java
  fe/src/main/java/org/apache/doris/common/ThriftServer.java
Labels: kind/bug

#3642 Fix some unit test failed
  be/test/agent/utils_test.cpp
  be/test/olap/bloom_filter_index_test.cpp
  be/test/olap/bloom_filter_test.cpp
  be/test/olap/column_reader_test.cpp
  be/test/olap/comparison_predicate_test.cpp
  be/test/olap/delta_writer_test.cpp
  be/test/runtime/memory_scratch_sink_test.cpp
  be/test/runtime/routine_load_task_executor_test.cpp
  be/test/util/cidr_test.cpp
  be/test/util/system_metrics_test.cpp
Labels: approved, area/test, kind/cleanup

#3584 [OUTFILE] Support `INTO OUTFILE` to export query result
  be/src/exec/CMakeLists.txt
  be/src/exec/broker_writer.h
  be/src/exec/local_file_writer.h
  be/src/exec/parquet_writer.cpp
  be/src/exec/parquet_writer.h
  be/src/runtime/CMakeLists.txt
  be/src/runtime/buffer_control_block.h
  be/src/runtime/file_result_writer.cpp
  be/src/runtime/file_result_writer.h
  be/src/runtime/mysql_result_writer.cpp
  be/src/runtime/mysql_result_writer.h
  be/src/runtime/query_statistics.h
  be/src/runtime/result_sink.cpp
  be/src/runtime/result_sink.h
  be/src/runtime/result_writer.cpp
  be/src/runtime/result_writer.h
  be/test/runtime/CMakeLists.txt
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/administrator-guide/outfile.md
  docs/zh-CN/administrator-guide/outfile.md
  fe/src/main/cup/sql_parser.cup
  fe/src/main/java/org/apache/doris/analysis/BaseViewStmt.java
  fe/src/main/java/org/apache/doris/analysis/BrokerDesc.java
  fe/src/main/java/org/apache/doris/analysis/OutFileClause.java
  fe/src/main/java/org/apache/doris/analysis/QueryStmt.java
  fe/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/src/main/java/org/apache/doris/common/util/ParseUtil.java
  fe/src/main/java/org/apache/doris/planner/PlanFragment.java
  fe/src/main/java/org/apache/doris/planner/Planner.java
  fe/src/main/java/org/apache/doris/planner/ResultSink.java
  fe/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/src/main/jflex/sql_scanner.flex
  gensrc/proto/data.proto
  gensrc/thrift/DataSinks.thrift
Labels: api-review, area/sql/function, kind/feature, release-note

#3685 [Enhancement] Customize the style of sidebar (branch-0.11)
  docs/.vuepress/theme/styles/index.styl
Labels: approved, area/website

#3684 [Enhancement] Customize the style of sidebar (branch-0.12)
  docs/.vuepress/styles/index.styl
Labels: approved, area/website

#3683 [Enhancement] Customize the style of sidebar (master)
  docs/.vuepress/theme/styles/index.styl
Labels: approved, area/website

#3686 [Bug] Serialize storage format in rollup job
  fe/src/main/java/org/apache/doris/alter/RollupJobV2.java
  fe/src/main/java/org/apache/doris/common/FeMetaVersion.java
  fe/src/test/java/org/apache/doris/alter/RollupJobV2Test.java
Labels: approved, area/storage, kind/bug, kind/meta-version-change

#3676 [Stmt] Add rowCount column to SHOW DATA stmt
  docs/en/sql-reference/sql-statements/Data Manipulation/SHOW DATA.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/SHOW DATA.md
  fe/src/main/java/org/apache/doris/analysis/ShowDataStmt.java
  fe/src/test/java/org/apache/doris/analysis/ShowDataStmtTest.java
Labels: area/statement, kind/feature

#3681 [AuditPlugin] Modify load label of audit plugin to avoid load confliction
  be/src/olap/rowset/alpha_rowset.cpp
  fe/src/main/java/org/apache/doris/plugin/PluginContext.java
  fe_plugins/auditloader/src/main/assembly/plugin.properties
  fe_plugins/auditloader/src/main/java/org/apache/doris/plugin/audit/AuditLoaderPlugin.java
  fe_plugins/auditloader/src/main/java/org/apache/doris/plugin/audit/DorisStreamLoader.java
Labels: area/plugin, kind/bug

#3692 Fixbug: null pointer access in json-load
  be/src/exprs/json_functions.cpp
Labels: approved, area/sql/function, kind/bug

#3649 [bug] init be log file length when restart be
  thirdparty/patches/glog-0.3.3-for-palo2.patch
Labels: approved, area/dependency, kind/bug

#3635 [Enhancement] Convert metric to Json format
  be/src/exec/tablet_sink.cpp
  be/src/http/action/metrics_action.cpp
  be/src/http/action/stream_load.cpp
  be/src/runtime/client_cache.cpp
  be/src/runtime/memory/chunk_allocator.cpp
  be/src/runtime/runtime_state.h
  be/src/runtime/tmp_file_mgr.cc
  be/src/util/doris_metrics.cpp
  be/src/util/doris_metrics.h
  be/src/util/metrics.cpp
  be/src/util/metrics.h
  be/src/util/runtime_profile.cpp
  be/src/util/system_metrics.cpp
  be/src/util/thrift_server.cpp
  be/test/http/metrics_action_test.cpp
  be/test/util/doris_metrics_test.cpp
  be/test/util/new_metrics_test.cpp
  be/test/util/system_metrics_test.cpp
  fe/src/main/java/org/apache/doris/analysis/InsertStmt.java
  fe/src/main/java/org/apache/doris/common/ThreadPoolManager.java
  fe/src/main/java/org/apache/doris/common/proc/IncompleteTabletsProcNode.java
  fe/src/main/java/org/apache/doris/common/proc/StatisticProcDir.java
  fe/src/main/java/org/apache/doris/http/rest/MetricsAction.java
  fe/src/main/java/org/apache/doris/load/loadv2/BrokerLoadJob.java
  fe/src/main/java/org/apache/doris/load/routineload/RoutineLoadTaskInfo.java
  fe/src/main/java/org/apache/doris/master/ReportHandler.java
  fe/src/main/java/org/apache/doris/metric/CounterMetric.java
  fe/src/main/java/org/apache/doris/metric/DoubleCounterMetric.java
  fe/src/main/java/org/apache/doris/metric/GaugeMetric.java
  fe/src/main/java/org/apache/doris/metric/GaugeMetricImpl.java
  fe/src/main/java/org/apache/doris/metric/JsonMetricVisitor.java
  fe/src/main/java/org/apache/doris/metric/LongCounterMetric.java
  fe/src/main/java/org/apache/doris/metric/Metric.java
  fe/src/main/java/org/apache/doris/metric/MetricRepo.java
  fe/src/main/java/org/apache/doris/metric/MetricVisitor.java
  fe/src/main/java/org/apache/doris/metric/PrometheusMetricVisitor.java
  fe/src/main/java/org/apache/doris/metric/SimpleCoreMetricVisitor.java
  fe/src/main/java/org/apache/doris/qe/ConnectProcessor.java
  fe/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  fe/src/main/java/org/apache/doris/task/AgentTaskQueue.java
  fe/src/test/java/org/apache/doris/load/loadv2/BrokerLoadJobTest.java
  fe/src/test/java/org/apache/doris/load/loadv2/LoadJobTest.java
Labels: approved, enhancement

#3708 [Bug][Metrics] Fix bug that some of metrics can not be got
  be/src/util/doris_metrics.cpp
  be/src/util/metrics.cpp
  be/src/util/metrics.h
Labels: area/metrics, kind/bug

#3699 [Bug] Duplicate Key table core when predicate on metric column
  be/src/olap/olap_cond.cpp
Labels: approved, area/storage, kind/bug

#3702 FixBug: Load data Is error in json load
  be/src/exec/json_scanner.cpp
  be/src/exprs/json_functions.cpp
  be/src/exprs/json_functions.h
  be/test/exprs/json_function_test.cpp
Labels: approved, area/load, kind/bug

#3709 [Bug] RuntimeState should be destructed after DataSink
  be/src/runtime/plan_fragment_executor.h
Labels: approved, area/load, kind/bug

#3710 [Bug] Set the 404 error for QueryProfile HttpRequest when query_id not set
  fe/src/main/java/org/apache/doris/common/util/ProfileManager.java
  fe/src/main/java/org/apache/doris/http/action/QueryProfileAction.java
Labels: kind/bug

#3720 [Bug] fix mixed used of counter
  be/src/runtime/mysql_result_writer.cpp
Labels: kind/bug

#3723 Fix UT ThreadPoolManagerTest failure
  fe/src/test/java/org/apache/doris/common/ThreadPoolManagerTest.java
Labels: approved, area/test, kind/cleanup
