Repository apache/doris, pull requests merged in 2020-07, with the labels that each got.

#3979 [Bug] Fix bug that routine load task throw exception when calling afterVisible()
  be/test/exprs/timestamp_functions_test.cpp
  be/test/runtime/datetime_value_test.cpp
  fe/src/main/java/org/apache/doris/load/routineload/RoutineLoadJob.java
Labels: approved, area/load, kind/bug

#3894 [Enhancement] Make report version unchanged for publish task
  be/src/agent/task_worker_pool.cpp
  fe/src/main/java/org/apache/doris/catalog/TabletInvertedIndex.java
  fe/src/main/java/org/apache/doris/master/ReportHandler.java
Labels: approved, kind/enhancement

#3968 [Doris On ES][Feature] Support create table with wildcard or aliase index
  fe/src/main/java/org/apache/doris/external/elasticsearch/DorisEsException.java
  fe/src/main/java/org/apache/doris/external/elasticsearch/EsFieldInfos.java
  fe/src/main/java/org/apache/doris/external/elasticsearch/EsRestClient.java
  fe/src/main/java/org/apache/doris/external/elasticsearch/EsShardPartitions.java
  fe/src/main/java/org/apache/doris/external/elasticsearch/EsShardRouting.java
  fe/src/main/java/org/apache/doris/external/elasticsearch/EsTablePartitions.java
  fe/src/main/java/org/apache/doris/planner/EsScanNode.java
  fe/src/test/java/org/apache/doris/external/elasticsearch/EsRepositoryTest.java
Labels: approved, area/doris-on-es

#3943 [Bug] Fix bug that delete stmt with filter condition delete all data from table on segment v2
  .gitignore
  be/src/olap/olap_cond.cpp
  be/src/olap/rowset/segment_v2/column_reader.cpp
  be/src/olap/rowset/segment_v2/column_reader.h
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
Labels: approved, area/storage, kind/bug

#3974 Improve performance of unique table read
  be/src/olap/reader.cpp
Labels: approved, kind/enhancement

#3806 Remove order by for subquery in set opertion clause
  fe/src/main/java/org/apache/doris/analysis/QueryStmt.java
  fe/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
Labels: approved, area/sql/planner, kind/enhancement

#3898 Support import true or false as boolean value
  be/src/exprs/cast_functions.cpp
  be/src/exprs/cast_functions.h
  be/src/olap/delete_handler.cpp
  be/src/olap/utils.cpp
  be/src/olap/utils.h
  fe/src/main/java/org/apache/doris/analysis/BoolLiteral.java
  fe/src/main/java/org/apache/doris/analysis/CastExpr.java
  fe/src/main/java/org/apache/doris/load/DeleteHandler.java
Labels: approved, area/load, kind/feature

#3985 [Doris On ES] [Bug-Fix][Refactor] Fix potential null pointer exception and refactor function process logic
  be/src/exec/es/es_predicate.cpp
  be/src/exec/es/es_predicate.h
Labels: approved, area/doris-on-es, kind/bug

#3999 Fix some code & comments
  be/src/exec/base_scanner.h
  be/src/exec/broker_scan_node.cpp
  be/src/exec/broker_scan_node.h
  be/src/exec/data_sink.h
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/plan_fragment_executor.cpp
  be/src/runtime/plan_fragment_executor.h
  fe/src/main/java/org/apache/doris/clone/BackendLoadStatistic.java
  fe/src/main/java/org/apache/doris/clone/ClusterLoadStatistic.java
  fe/src/main/java/org/apache/doris/clone/TabletScheduler.java
Labels: approved, kind/cleanup

#3996 Add log for loading image
  fe/src/main/java/org/apache/doris/catalog/Catalog.java
Labels: approved, kind/cleanup

#3983 [Bug] Fix bug that linked schema change for alpha rowset will case BE crash
  be/src/olap/rowset/segment_group.cpp
Labels: approved, area/storage, kind/bug

#4002 [Bug] Cancel the query if OlapScanner prepare failed
  be/src/exec/olap_scan_node.cpp
  be/src/exec/olap_scanner.cpp
  be/src/exec/olap_scanner.h
Labels: area/sql/execution, kind/bug

#3970 Explain verbose stmt to print tupleDesc/slotDesc information
  fe/src/main/cup/sql_parser.cup
  fe/src/main/java/org/apache/doris/analysis/DescriptorTable.java
  fe/src/main/java/org/apache/doris/analysis/SlotDescriptor.java
  fe/src/main/java/org/apache/doris/analysis/StatementBase.java
  fe/src/main/java/org/apache/doris/analysis/TupleDescriptor.java
  fe/src/main/java/org/apache/doris/planner/Planner.java
  fe/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/src/main/jflex/sql_scanner.flex
  fe/src/test/java/org/apache/doris/planner/PlannerTest.java
  fe/src/test/java/org/apache/doris/utframe/DorisAssert.java
  fe/src/test/java/org/apache/doris/utframe/UtFrameUtils.java
Labels: approved, kind/enhancement

#3986 [Config]Allower use to config different thrift server model
  docs/en/administrator-guide/config/fe_config.md
  docs/zh-CN/administrator-guide/config/fe_config.md
  fe/src/main/java/org/apache/doris/common/Config.java
  fe/src/main/java/org/apache/doris/common/ThriftServer.java
Labels: approved, area/config

#3993 Keep order of read from segment consist with the write order
  be/src/olap/generic_iterators.cpp
  be/src/olap/iterators.h
  be/src/olap/rowset/segment_v2/segment_iterator.h
Labels: approved, area/sql/execution, kind/bug

#3997 Use ThreadPoolManager to manage some native thread
  fe/src/main/java/org/apache/doris/common/ThreadPoolManager.java
  fe/src/main/java/org/apache/doris/common/publish/FixedTimePublisher.java
  fe/src/main/java/org/apache/doris/metric/MetricRepo.java
  fe/src/main/java/org/apache/doris/mysql/MysqlServer.java
  fe/src/main/java/org/apache/doris/qe/ConnectScheduler.java
  fe/src/main/java/org/apache/doris/task/MasterTaskExecutor.java
Labels: approved, kind/refactor

#4010 [ShowIndex] Make Show Index stmt act same as MySQL behavior
  fe/src/main/java/org/apache/doris/analysis/ShowIndexStmt.java
  fe/src/test/java/org/apache/doris/analysis/ShowIndexStmtTest.java
Labels: approved, area/sql/compatibility

#4013 [Bug][Memroy Leak]Fix bug TransactionState is not clear from idToFinalStatusTransactionState
  fe/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java
Labels: approved, area/load, kind/bug

#4015 [Bug] Fix bug that BE crash when doing alter table task
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
Labels: approved, kind/bug

#3965 [Dynamic Partition]Support set replication_num in dynamic partition property
  docs/en/administrator-guide/dynamic-partition.md
  docs/zh-CN/administrator-guide/dynamic-partition.md
  fe/src/main/java/org/apache/doris/analysis/ShowDynamicPartitionStmt.java
  fe/src/main/java/org/apache/doris/catalog/DynamicPartitionProperty.java
  fe/src/main/java/org/apache/doris/clone/DynamicPartitionScheduler.java
  fe/src/main/java/org/apache/doris/common/ErrorCode.java
  fe/src/main/java/org/apache/doris/common/util/DynamicPartitionUtil.java
  fe/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/src/test/java/org/apache/doris/catalog/DynamicPartitionTableTest.java
Labels: approved, area/catalog, kind/feature

#4024 Correct typos for zh-CN doc
  docs/zh-CN/sql-reference/sql-statements/Data Definition/CREATE TABLE.md
Labels: approved, good first issue, kind/documentation

#4035 [Doris On ES] [UT] Add UT test for all search phase
  fe/src/test/java/org/apache/doris/catalog/CatalogTestUtil.java
  fe/src/test/java/org/apache/doris/external/elasticsearch/EsShardPartitionsTest.java
  fe/src/test/java/org/apache/doris/external/elasticsearch/EsTestCase.java
  fe/src/test/java/org/apache/doris/external/elasticsearch/MappingPhaseTest.java
  fe/src/test/java/org/apache/doris/external/elasticsearch/PartitionPhaseTest.java
  fe/src/test/java/org/apache/doris/external/elasticsearch/VersionPhaseTest.java
  fe/src/test/resources/data/es/clusterstate1.json
  fe/src/test/resources/data/es/clusterstate2.json
  fe/src/test/resources/data/es/clusterstate3.json
  fe/src/test/resources/data/es/clusterstate4.json
  fe/src/test/resources/data/es/clusterstate5.json
  fe/src/test/resources/data/es/search_shards.json
  fe/src/test/resources/data/es/test_index_mapping.json
  fe/src/test/resources/data/es/test_index_mapping_after_7x.json
  fe/src/test/resources/data/es/test_main_info.json
  fe/src/test/resources/data/es/test_nodes_http.json
  fe/src/test/resources/data/es/test_search_shards.json
Labels: approved, area/doris-on-es, area/test

#4003 Fix except node child not order correctly
  fe/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
  fe/src/test/java/org/apache/doris/planner/PlannerTest.java
Labels: approved, area/sql/planner, kind/bug

#4020 [Load][Json] Refactor json load logic to make it more reasonable
  be/src/common/status.cpp
  be/src/common/status.h
  be/src/exec/broker_scanner.cpp
  be/src/exec/json_scanner.cpp
  be/src/exec/json_scanner.h
  be/src/exprs/json_functions.cpp
  be/src/exprs/json_functions.h
  be/src/runtime/stream_load/stream_load_executor.cpp
  build.sh
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/administrator-guide/load-data/load-json-format.md
  docs/en/sql-reference/sql-statements/Data Manipulation/ROUTINE LOAD.md
  docs/en/sql-reference/sql-statements/Data Manipulation/STREAM LOAD.md
  docs/zh-CN/administrator-guide/load-data/load-json-format.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/MINI LOAD.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/ROUTINE LOAD.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/STREAM LOAD.md
  gensrc/thrift/Status.thrift
Labels: approved, area/load, kind/bug

#4026 Fix mini load NPE
  fe/src/main/java/org/apache/doris/load/Load.java
Labels: approved, area/load, kind/bug

#4021 [webserver] Make BE webserver handle static files
  be/src/common/config.h
  be/src/http/default_path_handlers.cpp
  be/src/http/download_action.cpp
  be/src/http/download_action.h
  be/src/http/ev_http_server.cpp
  be/src/http/ev_http_server.h
  be/src/http/utils.cpp
  be/src/http/utils.h
  be/src/http/web_page_handler.cpp
  be/src/http/web_page_handler.h
Labels: approved, area/be/frontpage

#3957 Make it easier for users to find configuration items needed
  docs/en/sql-reference/sql-statements/Administration/ADMIN SHOW CONFIG.md
  docs/zh-CN/sql-reference/sql-statements/Administration/ADMIN SHOW CONFIG.md
  fe/src/main/cup/sql_parser.cup
  fe/src/main/java/org/apache/doris/analysis/AdminShowConfigStmt.java
  fe/src/main/java/org/apache/doris/common/CaseSensibility.java
  fe/src/main/java/org/apache/doris/common/ConfigBase.java
  fe/src/main/java/org/apache/doris/qe/ShowExecutor.java
Labels: approved, kind/enhancement

#4031 [Config] Enable some features by default
  docs/en/installing/install-deploy.md
  docs/zh-CN/installing/install-deploy.md
  fe/src/main/java/org/apache/doris/common/Config.java
Labels: approved, area/config, kind/documentation

#4042 [Bug] Fix core when modifing char to varchar and loading boolean with replace aggregation
  be/src/olap/aggregate_func.cpp
  be/src/olap/schema_change.cpp
Labels: approved, area/schema-change, kind/bug

#4048 [BUG] fix big inline_view table join small mysql table choose shuffle join bug
  fe/src/main/java/org/apache/doris/planner/MysqlScanNode.java
  fe/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: approved, area/sql/planner, kind/enhancement

#4022 Add thrift_client_retry_interval_ms config in be for thrift client to avoid avalanche disaster in fe thrift server
  be/src/common/config.h
  be/src/runtime/stream_load/stream_load_executor.cpp
  be/src/util/thrift_rpc_helper.cpp
  docs/en/administrator-guide/config/be_config.md
  docs/zh-CN/administrator-guide/config/be_config.md
  fe/src/main/java/org/apache/doris/common/Config.java
  fe/src/main/java/org/apache/doris/common/ThriftServer.java
Labels: approved, kind/enhancement

#3991 Fix the problem of mem exec, when analytic eval node need to spill to disk with a low mem limit
  be/src/exec/analytic_eval_node.cpp
  be/src/exec/analytic_eval_node.h
  be/src/exec/spill_sort_node.cc
  be/src/runtime/spill_sorter.cc
  be/src/runtime/spill_sorter.h
Labels: approved, area/sql/execution, kind/bug

#3981 [Feature] Batch update partition's property in one command
  docs/en/sql-reference/sql-statements/Data Definition/ALTER TABLE.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/ALTER TABLE.md
  fe/src/main/cup/sql_parser.cup
  fe/src/main/java/org/apache/doris/alter/Alter.java
  fe/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
  fe/src/main/java/org/apache/doris/analysis/ModifyPartitionClause.java
  fe/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/src/main/java/org/apache/doris/catalog/DataProperty.java
  fe/src/main/java/org/apache/doris/journal/JournalEntity.java
  fe/src/main/java/org/apache/doris/journal/local/LocalJournalCursor.java
  fe/src/main/java/org/apache/doris/persist/BatchModifyPartitionsInfo.java
  fe/src/main/java/org/apache/doris/persist/EditLog.java
  fe/src/main/java/org/apache/doris/persist/ModifyPartitionInfo.java
  fe/src/main/java/org/apache/doris/persist/OperationType.java
  fe/src/test/java/org/apache/doris/alter/AlterTest.java
  fe/src/test/java/org/apache/doris/persist/BatchModifyPartitionsInfoTest.java
Labels: approved, area/catalog, kind/enhancement

#4041 Fix predicate pushdown may incorrect when groupby with grouping sets
  fe/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
  fe/src/test/java/org/apache/doris/planner/PlannerTest.java
Labels: approved, area/sql/planner, kind/bug

#4045 Fix mem_pool npe
  be/src/olap/rowset/column_reader.cpp
  be/src/runtime/mem_pool.h
Labels: approved, kind/bug

#4050 [webserver] Make BE webserver more pretty
  LICENSE.txt
  be/CMakeLists.txt
  be/src/http/web_page_handler.cpp
  build.sh
  webroot/be/bootstrap/css/bootstrap-table.min.css
  webroot/be/bootstrap/css/bootstrap.min.css
  webroot/be/bootstrap/fonts/glyphicons-halflings-regular.woff
  webroot/be/bootstrap/js/bootstrap-table.min.js
  webroot/be/bootstrap/js/bootstrap.min.js
  webroot/be/d3.v2.js
  webroot/be/doris.css
  webroot/be/doris.js
  webroot/be/epoch.0.5.2.min.css
  webroot/be/epoch.0.5.2.min.js
  webroot/be/favicon.ico
  webroot/be/index.html
  webroot/be/jquery-3.2.1.min.js
  webroot/be/logo.png
Labels: approved, area/be/frontpage

#4055 [Doris On ES] Add docvalue limitation for doc_values scan and enable doc_values scan default
  be/src/exec/es/es_scan_reader.h
  be/src/exec/es/es_scroll_query.cpp
  fe/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/src/main/java/org/apache/doris/catalog/EsTable.java
  fe/src/main/java/org/apache/doris/planner/EsScanNode.java
Labels: approved, area/doris-on-es

#4034 [Bug][Broker] Fix bug that the error exception is not caught when closing the broker writer
  fs_brokers/apache_hdfs_broker/src/main/java/org/apache/doris/broker/hdfs/FileSystemManager.java
Labels: area/broker, kind/bug

#4009 [Bug]Fix some schema change not work right
  be/src/olap/schema_change.cpp
  be/src/olap/schema_change.h
  docs/en/sql-reference/sql-statements/Data Definition/ALTER TABLE.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/ALTER TABLE.md
  fe/src/main/java/org/apache/doris/catalog/Column.java
  fe/src/main/java/org/apache/doris/catalog/ColumnType.java
Labels: area/schema-change, kind/bug

#4052 [Bug] Fix core of double delete, when RowBatch call transfer_resource_ownership
  be/src/runtime/row_batch.cpp
Labels: approved, kind/bug

#4060 Fix bug of count(*) in MV selector
  fe/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/src/main/java/org/apache/doris/planner/MaterializedViewSelector.java
Labels: approved, area/materialized-view, kind/bug

#4061 [Bug]Support get all rowset meta info in memory from tablet meta url
  be/src/http/action/meta_action.cpp
  be/src/olap/tablet.cpp
Labels: approved, kind/bug

#4063 Support using B/K/KB/M/MB/G/GB/T/TB/P/PB as unit in session variable exec_mem_limit
  docs/en/administrator-guide/variables.md
  docs/zh-CN/administrator-guide/variables.md
  fe/src/main/java/org/apache/doris/qe/VariableMgr.java
Labels: SQL Improvement, approved

#4066 Fix some spell problem
  be/src/exec/csv_scan_node.h
  be/src/exec/parquet_reader.cpp
  be/src/olap/data_dir.cpp
  be/src/olap/field.h
  be/src/olap/rowset/column_reader.cpp
  be/src/olap/rowset/column_writer.cpp
Labels: approved, kind/cleanup

#4072 add pull request template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: approved, area/community

#4091 remove licence
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: approved, area/community

#4092 fix PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, area/community

#4070 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: approved, area/community, kind/documentation

#4079 Fix be may core dump when linked schema change
  be/src/olap/rowset/segment_group.cpp
Labels: approved, area/schema-change

#4074 redesign the home page of document website (branch-0.11)
  docs/.vuepress/config.js
  docs/.vuepress/public/images/asf_logo.svg
  docs/.vuepress/public/images/home/aggr.png
  docs/.vuepress/public/images/home/banner-stats.png
  docs/.vuepress/public/images/home/clock.png
  docs/.vuepress/public/images/home/cpu.png
  docs/.vuepress/public/images/home/dev.png
  docs/.vuepress/public/images/home/hero-bg.png
  docs/.vuepress/public/images/home/logo-360.png
  docs/.vuepress/public/images/home/logo-baidu.png
  docs/.vuepress/public/images/home/logo-dingdong.png
  docs/.vuepress/public/images/home/logo-doris-white.png
  docs/.vuepress/public/images/home/logo-huawei.png
  docs/.vuepress/public/images/home/logo-jd.png
  docs/.vuepress/public/images/home/logo-kuaishou.png
  docs/.vuepress/public/images/home/logo-meituan.png
  docs/.vuepress/public/images/home/logo-shopee.png
  docs/.vuepress/public/images/home/logo-sohu.png
  docs/.vuepress/public/images/home/logo-tantan.png
  docs/.vuepress/public/images/home/logo-vipkid.png
  docs/.vuepress/public/images/home/logo-weibo.png
  docs/.vuepress/public/images/home/logo-xiaomi.png
  docs/.vuepress/public/images/home/logo-yidian.png
  docs/.vuepress/public/images/home/logo-youdao.png
  docs/.vuepress/public/images/home/logo-zuoyebang.png
  docs/.vuepress/public/images/home/program.png
  docs/.vuepress/public/images/home/rollup.png
  docs/.vuepress/public/images/home/sql.png
  docs/.vuepress/public/images/home/struct.png
  docs/.vuepress/public/images/home/structure-fresh.png
  docs/.vuepress/theme/components/Footer.vue
  docs/.vuepress/theme/components/Home.vue
  docs/en/README.md
  docs/package.json
  docs/zh-CN/README.md
Labels: approved, area/website

#3873 Support materialized view schema change [#3739]
  be/src/olap/column_mapping.h
  be/src/olap/schema_change.cpp
  be/src/olap/schema_change.h
  be/test/olap/schema_change_test.cpp
  fe/src/main/java/org/apache/doris/alter/RollupJobV2.java
  fe/src/main/java/org/apache/doris/task/AlterReplicaTask.java
  gensrc/thrift/AgentService.thrift
Labels: approved, area/materialized-view, kind/feature

#4069 redesign the home page of document website (master)
  docs/.vuepress/config.js
  docs/.vuepress/public/images/asf_logo.svg
  docs/.vuepress/public/images/home/aggr.png
  docs/.vuepress/public/images/home/banner-stats.png
  docs/.vuepress/public/images/home/clock.png
  docs/.vuepress/public/images/home/cpu.png
  docs/.vuepress/public/images/home/dev.png
  docs/.vuepress/public/images/home/hero-bg.png
  docs/.vuepress/public/images/home/logo-360.png
  docs/.vuepress/public/images/home/logo-baidu.png
  docs/.vuepress/public/images/home/logo-dingdong.png
  docs/.vuepress/public/images/home/logo-doris-white.png
  docs/.vuepress/public/images/home/logo-huawei.png
  docs/.vuepress/public/images/home/logo-jd.png
  docs/.vuepress/public/images/home/logo-kuaishou.png
  docs/.vuepress/public/images/home/logo-meituan.png
  docs/.vuepress/public/images/home/logo-shopee.png
  docs/.vuepress/public/images/home/logo-sohu.png
  docs/.vuepress/public/images/home/logo-tantan.png
  docs/.vuepress/public/images/home/logo-vipkid.png
  docs/.vuepress/public/images/home/logo-weibo.png
  docs/.vuepress/public/images/home/logo-xiaomi.png
  docs/.vuepress/public/images/home/logo-yidian.png
  docs/.vuepress/public/images/home/logo-youdao.png
  docs/.vuepress/public/images/home/logo-zuoyebang.png
  docs/.vuepress/public/images/home/program.png
  docs/.vuepress/public/images/home/rollup.png
  docs/.vuepress/public/images/home/sql.png
  docs/.vuepress/public/images/home/struct.png
  docs/.vuepress/public/images/home/structure-fresh.png
  docs/.vuepress/theme/components/Footer.vue
  docs/.vuepress/theme/components/Home.vue
  docs/en/README.md
  docs/package.json
  docs/zh-CN/README.md
Labels: approved, area/website

#4073 redesign the home page of document website (branch-0.12)
  docs/.vuepress/config.js
  docs/.vuepress/public/images/asf_logo.svg
  docs/.vuepress/public/images/home/aggr.png
  docs/.vuepress/public/images/home/banner-stats.png
  docs/.vuepress/public/images/home/clock.png
  docs/.vuepress/public/images/home/cpu.png
  docs/.vuepress/public/images/home/dev.png
  docs/.vuepress/public/images/home/hero-bg.png
  docs/.vuepress/public/images/home/logo-360.png
  docs/.vuepress/public/images/home/logo-baidu.png
  docs/.vuepress/public/images/home/logo-dingdong.png
  docs/.vuepress/public/images/home/logo-doris-white.png
  docs/.vuepress/public/images/home/logo-huawei.png
  docs/.vuepress/public/images/home/logo-jd.png
  docs/.vuepress/public/images/home/logo-kuaishou.png
  docs/.vuepress/public/images/home/logo-meituan.png
  docs/.vuepress/public/images/home/logo-shopee.png
  docs/.vuepress/public/images/home/logo-sohu.png
  docs/.vuepress/public/images/home/logo-tantan.png
  docs/.vuepress/public/images/home/logo-vipkid.png
  docs/.vuepress/public/images/home/logo-weibo.png
  docs/.vuepress/public/images/home/logo-xiaomi.png
  docs/.vuepress/public/images/home/logo-yidian.png
  docs/.vuepress/public/images/home/logo-youdao.png
  docs/.vuepress/public/images/home/logo-zuoyebang.png
  docs/.vuepress/public/images/home/program.png
  docs/.vuepress/public/images/home/rollup.png
  docs/.vuepress/public/images/home/sql.png
  docs/.vuepress/public/images/home/struct.png
  docs/.vuepress/public/images/home/structure-fresh.png
  docs/.vuepress/theme/components/Footer.vue
  docs/.vuepress/theme/components/Home.vue
  docs/en/README.md
  docs/package.json
  docs/zh-CN/README.md
Labels: approved, area/website

#4103 Do not choose decommissioned BE in colocate balance
  fe/src/main/java/org/apache/doris/clone/ColocateTableBalancer.java
Labels: approved, area/colocated

#4097 Fix load orc decimal value wrong
  be/src/exec/orc_scanner.cpp
  be/test/exec/orc_scanner_test.cpp
  be/test/exec/test_data/orc_scanner/decimal_and_timestamp.orc
Labels: approved, area/load, kind/bug

#4049 [Thread Resource Leak] Fix thread resource leak after checkpoint catalog destroyed
  fe/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/src/main/java/org/apache/doris/common/ThreadPoolManager.java
  fe/src/main/java/org/apache/doris/common/ThriftServer.java
  fe/src/main/java/org/apache/doris/common/publish/ClusterStatePublisher.java
  fe/src/main/java/org/apache/doris/common/publish/FixedTimePublisher.java
  fe/src/main/java/org/apache/doris/load/ExportChecker.java
  fe/src/main/java/org/apache/doris/load/LoadChecker.java
  fe/src/main/java/org/apache/doris/metric/MetricRepo.java
  fe/src/main/java/org/apache/doris/mysql/MysqlServer.java
  fe/src/main/java/org/apache/doris/mysql/nio/NMysqlServer.java
  fe/src/main/java/org/apache/doris/qe/ConnectScheduler.java
  fe/src/main/java/org/apache/doris/system/HeartbeatMgr.java
  fe/src/main/java/org/apache/doris/task/AgentTaskExecutor.java
  fe/src/main/java/org/apache/doris/task/MasterTaskExecutor.java
  fe/src/main/java/org/apache/doris/task/PullLoadJobMgr.java
  fe/src/test/java/org/apache/doris/common/ThreadPoolManagerTest.java
  fe/src/test/java/org/apache/doris/load/routineload/RoutineLoadSchedulerTest.java
  fe/src/test/java/org/apache/doris/task/MasterTaskExecutorTest.java
Labels: approved, area/catalog, kind/bug

#4062 [webserver] Introduce mustache to simplify BE's website render
  be/src/http/default_path_handlers.cpp
  be/src/http/web_page_handler.cpp
  be/src/http/web_page_handler.h
  be/src/util/CMakeLists.txt
  be/src/util/easy_json.cc
  be/src/util/easy_json.h
  be/src/util/mustache/mustache.cc
  be/src/util/mustache/mustache.h
  be/test/util/CMakeLists.txt
  be/test/util/easy_json-test.cpp
  webroot/be/home.mustache
Labels: approved, area/be/frontpage, kind/enhancement

#3677 Support materialized view load and insert
  fe/src/main/java/org/apache/doris/analysis/InsertStmt.java
  fe/src/main/java/org/apache/doris/catalog/Column.java
  fe/src/main/java/org/apache/doris/load/Load.java
  fe/src/test/java/org/apache/doris/analysis/InsertStmtTest.java
Labels: approved, area/materialized-view, kind/feature

#4088 [Bug][Alter] Cancel the alter job if database has been dropped
  fe/src/main/java/org/apache/doris/alter/AlterJob.java
  fe/src/main/java/org/apache/doris/alter/RollupJobV2.java
  fe/src/main/java/org/apache/doris/alter/SchemaChangeJobV2.java
  fe/src/main/java/org/apache/doris/clone/TabletScheduler.java
  fe/src/main/java/org/apache/doris/transaction/GlobalTransactionMgr.java
Labels: approved, area/schema-change, kind/bug

#4112 [Bug] Fix bug that tablet meta lock twice
  be/src/olap/snapshot_manager.cpp
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
  be/src/olap/task/engine_storage_migration_task.cpp
Labels: approved, kind/bug

#4039 Add delayed deletion of rowsets function, fix -230 error.
  be/src/common/config.h
  be/src/olap/CMakeLists.txt
  be/src/olap/base_compaction.cpp
  be/src/olap/cumulative_compaction.cpp
  be/src/olap/rowset_graph.cpp
  be/src/olap/rowset_graph.h
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
  be/src/olap/tablet_manager.cpp
  be/src/olap/tablet_meta.cpp
  be/src/olap/tablet_meta.h
  be/src/olap/txn_manager.cpp
  be/src/olap/version_graph.cpp
  be/src/olap/version_graph.h
  be/test/olap/CMakeLists.txt
  be/test/olap/timestamped_version_tracker_test.cpp
  docs/en/administrator-guide/config/be_config.md
  docs/en/administrator-guide/http-actions/compaction-action.md
  docs/zh-CN/administrator-guide/config/be_config.md
  docs/zh-CN/administrator-guide/http-actions/compaction-action.md
  run-ut.sh
Labels: approved, area/storage, kind/enhancement

#4081 [Bug] Change get load state interface
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/administrator-guide/http-actions/get-load-state.md
  docs/zh-CN/administrator-guide/http-actions/get-load-state.md
  fe/src/main/java/org/apache/doris/http/rest/GetStreamLoadState.java
Labels: kind/api-change, kind/bug

#4094 [Bug] Fix isnull(null) analyze error
  fe/fe-core/src/main/java/org/apache/doris/analysis/IsNullPredicate.java
  fe/src/test/java/org/apache/doris/analysis/IsNullPredicateTest.java
Labels: area/sql/function, kind/bug

#4128 Add compaction point changing log
  be/src/olap/base_compaction.cpp
  be/src/olap/cumulative_compaction.cpp
Labels: approved

#4123 fix boolean support
  fe/fe-core/src/main/java/org/apache/doris/analysis/ColumnDef.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/PropertyAnalyzer.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ColumnDefTest.java
  fe/fe-core/src/test/java/org/apache/doris/common/PropertyAnalyzerTest.java
Labels: approved, area/bloom-filter-index, kind/bug

#4105 Delete bad replicas when no BE can be used to create new replica. for…
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Tablet.java
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletChecker.java
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletSchedCtx.java
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletScheduler.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/StatisticProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/master/ReportHandler.java
Labels: approved, area/balance

#4139 [Bug] Compaction row number cannot be matched between input rowsets and output rowsets
  be/src/olap/reader.cpp
Labels: approved, area/compact, kind/bug

#4154 [Code Structure] Move the code file to the right place
  fe/fe-core/src/test/java/org/apache/doris/analysis/IsNullPredicateTest.java
Labels: approved, kind/refactor

#4089 Fix some problem related with publish version task
  docs/en/administrator-guide/config/fe_config.md
  docs/zh-CN/administrator-guide/config/fe_config.md
  fe/fe-core/src/main/java/org/apache/doris/catalog/Replica.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/common/Log4jConfig.java
  fe/fe-core/src/main/java/org/apache/doris/master/ReportHandler.java
  fe/fe-core/src/main/java/org/apache/doris/task/AgentTask.java
  fe/fe-core/src/main/java/org/apache/doris/task/PublishVersionTask.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/PublishVersionDaemon.java
Labels: approved, kind/bug

#4110 [Feature][ThreadPool]Add Web Page to display thread's stats
  be/src/env/env.h
  be/src/env/env_util.cpp
  be/src/env/env_util.h
  be/src/http/default_path_handlers.cpp
  be/src/http/web_page_handler.cpp
  be/src/util/CMakeLists.txt
  be/src/util/os_util.cpp
  be/src/util/os_util.h
  be/src/util/thread.cpp
  be/src/util/thread.h
  be/src/util/url_coding.cpp
  be/src/util/url_coding.h
  webroot/be/threadz.mustache
Labels: approved, kind/feature

#4068 [Compaction] track RowsetReader's mem & add metric
  be/src/olap/base_compaction.cpp
  be/src/olap/base_compaction.h
  be/src/olap/compaction.cpp
  be/src/olap/compaction.h
  be/src/olap/cumulative_compaction.cpp
  be/src/olap/cumulative_compaction.h
  be/src/olap/row_block.cpp
  be/src/olap/row_block.h
  be/src/olap/rowset/alpha_rowset.cpp
  be/src/olap/rowset/alpha_rowset.h
  be/src/olap/rowset/alpha_rowset_reader.cpp
  be/src/olap/rowset/alpha_rowset_reader.h
  be/src/olap/rowset/beta_rowset.cpp
  be/src/olap/rowset/beta_rowset.h
  be/src/olap/rowset/beta_rowset_reader.cpp
  be/src/olap/rowset/beta_rowset_reader.h
  be/src/olap/rowset/column_data.cpp
  be/src/olap/rowset/column_data.h
  be/src/olap/rowset/rowset.h
  be/src/olap/rowset/segment_reader.cpp
  be/src/olap/rowset/segment_reader.h
  be/src/olap/storage_engine.cpp
  be/src/olap/storage_engine.h
  be/src/runtime/initial_reservations.cc
  be/src/runtime/vectorized_row_batch.cpp
  be/src/runtime/vectorized_row_batch.h
  be/src/util/doris_metrics.h
  docs/en/administrator-guide/operation/monitor-metrics/be-metrics.md
  docs/zh-CN/administrator-guide/operation/monitor-metrics/be-metrics.md
Labels: approved, area/compact, kind/enhancement

#3955 Support checking database used data quota when data load job begin a new txn
  docs/en/administrator-guide/config/fe_config.md
  docs/zh-CN/administrator-guide/config/fe_config.md
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Database.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/GlobalTransactionMgr.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/UpdateDbUsedDataQuotaDaemon.java
Labels: area/config, area/load, kind/enhancement

#4166 Restore build parallel config
  build.sh
Labels: approved, area/build

#4170 Fix recover database not in "show databases"
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
Labels: approved, area/catalog

#4175 [Bug][UpdateDataQuota] Skip update used data quota for information_schema db and fix bug for wrong time interval for UpdateDbUsedDataQuotaDaemon
  fe/fe-core/src/main/java/org/apache/doris/transaction/UpdateDbUsedDataQuotaDaemon.java
Labels: approved, area/catalog, kind/bug

#4178 [Bug] Add db read lock when processing unfinished publish task
  fe/fe-core/src/main/java/org/apache/doris/transaction/PublishVersionDaemon.java
Labels: approved, kind/bug

#4086 [Feature][Meta]Update/Read/Write VisibleVersionTime for Partition#4076
  fe/fe-core/src/main/java/org/apache/doris/catalog/Partition.java
  fe/fe-core/src/main/java/org/apache/doris/common/FeMetaVersion.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/PartitionsProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/PartitionCommitInfo.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/TableCommitInfo.java
Labels: approved, area/catalog, kind/meta-version-change

#4163 [Spark Load]Create spark load's repository in HDFS for dependencies
  fe/fe-core/src/main/java/org/apache/doris/catalog/SparkResource.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/BrokerUtil.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkEtlJobHandler.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkRepository.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/SparkEtlJobHandlerTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/SparkRepositoryTest.java
Labels: approved, area/spark-load, kind/feature

#4183 Fix from/to_base64 may return incorrect value
  be/src/exprs/CMakeLists.txt
  be/src/exprs/base64.cpp
  be/src/exprs/base64.h
  be/src/exprs/encryption_functions.cpp
  be/src/util/aes_util.cpp
  be/src/util/url_coding.cpp
  be/src/util/url_coding.h
  be/test/exprs/CMakeLists.txt
  be/test/exprs/encryption_functions_test.cpp
  be/test/util/aes_util_test.cpp
  run-ut.sh
Labels: approved

#4161 Add transfer destinations detail to profile
  be/src/runtime/data_stream_sender.cpp
Labels: approved

#4177 Reduce conflict of sql_parser.cup
  fe/fe-core/pom.xml
  fe/fe-core/src/main/cup/readme
  fe/fe-core/src/main/cup/sql_parser.cup
Labels: approved, area/sql

#4195 [Bug] Divide the upload in spark repository into two steps
  fe/fe-core/src/main/java/org/apache/doris/common/util/BrokerUtil.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkRepository.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/SparkRepositoryTest.java
Labels: approved, area/spark-load, kind/bug

#4143 Fix alter schema add key column bug in agg model
  be/src/olap/rowset/segment_group.cpp
Labels: approved

#4150 [BUG] fix 4149, add sessionVariable to choose broadcastjoin first when cardinality cannot be estimated
  docs/en/administrator-guide/variables.md
  docs/zh-CN/administrator-guide/variables.md
  fe/fe-core/src/main/java/org/apache/doris/planner/DistributedPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/qe/VariableMgr.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: approved, area/sql/planner

#4192 [Bug][Socket Leak] Fix bug that Mysql NIO server is leaking sockets
  .github/PULL_REQUEST_TEMPLATE.md
  fe/fe-core/src/main/java/org/apache/doris/mysql/MysqlChannel.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/nio/AcceptListener.java
Labels: kind/bug

#4173 [Plugin] Add properties grammar in InstallPluginStmt
  .gitignore
  docs/en/extending-doris/plugin-development-manual.md
  docs/en/sql-reference/sql-statements/Administration/INSTALL PLUGIN.md
  docs/zh-CN/extending-doris/plugin-development-manual.md
  docs/zh-CN/sql-reference/sql-statements/Administration/INSTALL PLUGIN.md
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/InstallPluginStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowPluginsStmt.java
  fe/fe-core/src/main/java/org/apache/doris/plugin/DynamicPluginLoader.java
  fe/fe-core/src/main/java/org/apache/doris/plugin/PluginInfo.java
  fe/fe-core/src/main/java/org/apache/doris/plugin/PluginMgr.java
  fe/fe-core/src/main/java/org/apache/doris/plugin/PluginZip.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/InstallPluginStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/plugin/PluginInfoTest.java
  fe/fe-core/src/test/java/org/apache/doris/plugin/PluginMgrTest.java
  fe/fe-core/src/test/java/org/apache/doris/plugin/PluginZipTest.java
  fe_plugins/auditloader/src/main/java/org/apache/doris/plugin/audit/AuditLoaderPlugin.java
Labels: approved, area/plugin, kind/enhancement

#4146 [CodeRefactor] Modify FE modules
  .gitignore
  build.sh
  fe/README
  fe/fe-common/pom.xml
  fe/fe-common/src/main/java/org/apache/doris/common/jmockit/AutoType.java
  fe/fe-common/src/main/java/org/apache/doris/common/jmockit/ConstructorReflection.java
  fe/fe-common/src/main/java/org/apache/doris/common/jmockit/Deencapsulation.java
  fe/fe-common/src/main/java/org/apache/doris/common/jmockit/FieldReflection.java
  fe/fe-common/src/main/java/org/apache/doris/common/jmockit/GeneratedClasses.java
  fe/fe-common/src/main/java/org/apache/doris/common/jmockit/MethodReflection.java
  fe/fe-common/src/main/java/org/apache/doris/common/jmockit/ParameterReflection.java
  fe/fe-common/src/main/java/org/apache/doris/common/jmockit/ThrowOfCheckedException.java
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkEtlJobHandler.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkRepository.java
  fe/pom.xml
  fe/spark-dpp/pom.xml
  fe/spark-dpp/src/main/java/org/apache/doris/common/Codec.java
  fe/spark-dpp/src/main/java/org/apache/doris/common/SparkDppException.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/BitmapValue.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/ColumnParser.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/DorisKryoRegistrator.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/DorisRangePartitioner.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/DppColumns.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/DppResult.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/DppUtils.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/GlobalDictBuilder.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/Hll.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/MinimumCoverageRollupTreeBuilder.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/Roaring64Map.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/RollupTreeBuilder.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/RollupTreeNode.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/SparkDpp.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/SparkRDDAggregator.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/StringAccumulator.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/etl/EtlJobConfig.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/etl/SparkEtlJob.java
  fe/spark-dpp/src/test/java/org/apache/doris/load/loadv2/dpp/BitmapValueTest.java
  fe/spark-dpp/src/test/java/org/apache/doris/load/loadv2/dpp/DorisRangePartitionerTest.java
  fe/spark-dpp/src/test/java/org/apache/doris/load/loadv2/dpp/DppUtilsTest.java
  fe/spark-dpp/src/test/java/org/apache/doris/load/loadv2/dpp/HllTest.java
  fe/spark-dpp/src/test/java/org/apache/doris/load/loadv2/dpp/MinimumCoverageRollupTreeBuilderTest.java
  fe/spark-dpp/src/test/java/org/apache/doris/load/loadv2/etl/SparkEtlJobTest.java
  run-fe-ut.sh
Labels: area/spark-load, kind/refactor

#4168 Fix large int literal analyze
  fe/fe-core/src/main/java/org/apache/doris/analysis/ColumnDef.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/IntLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/LargeIntLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/LiteralExpr.java
Labels: approved, area/sql/planner, kind/bug

#4148 [Bug][TabletRepair] Fix bug that too many replicas generated when decommission BE
  be/src/olap/task/engine_clone_task.cpp
  docs/en/administrator-guide/config/fe_config.md
  docs/zh-CN/administrator-guide/config/fe_config.md
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletSchedCtx.java
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletScheduler.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/master/ReportHandler.java
Labels: approved, area/balance, kind/bug

#4182 #4181 Let linked-schema change work for BETA tablet
  be/src/olap/schema_change.cpp
Labels: approved, area/schema-change, kind/bug

#4205 [Bug] Fix fe meta version problem, make drop meta check code easy to read and add doc content for drop meta check
  docs/en/sql-reference/sql-statements/Data Definition/ALTER TABLE.md
  docs/en/sql-reference/sql-statements/Data Definition/DROP DATABASE.md
  docs/en/sql-reference/sql-statements/Data Definition/DROP TABLE.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/ALTER TABLE.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/DROP DATABASE.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/DROP TABLE.md
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/DropDbStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/DropPartitionClause.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/DropTableStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/persist/DropDbInfo.java
  fe/fe-core/src/main/java/org/apache/doris/persist/EditLog.java
  fe/fe-core/src/test/java/org/apache/doris/persist/DropDbInfoTest.java
Labels: approved, area/catalog, kind/bug

#4151 [Spill To Disk][1/6] The adjustment of the basic BufferedBlockMgr includes the following change
  be/src/runtime/buffered_block_mgr2.cc
  be/src/runtime/buffered_block_mgr2.h
Labels: approved, kind/enhancement

#4136 Fixbug: json load
  be/src/exec/json_scanner.cpp
  be/src/exec/json_scanner.h
  be/src/exprs/json_functions.cpp
  be/src/exprs/json_functions.h
  be/src/http/action/stream_load.cpp
  be/src/http/http_common.h
  be/test/exec/json_scanner_test.cpp
  docs/en/sql-reference/sql-statements/Data Manipulation/ROUTINE LOAD.md
  docs/en/sql-reference/sql-statements/Data Manipulation/STREAM LOAD.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/ROUTINE LOAD.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/STREAM LOAD.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateRoutineLoadStmt.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/planner/StreamLoadScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/task/StreamLoadTask.java
  gensrc/thrift/FrontendService.thrift
  gensrc/thrift/PlanNodes.thrift
Labels: area/load, kind/bug

#4159 [Feature][Cache]Add interface, cache coordinator, metric, variable and config for query cache
  docs/en/administrator-guide/config/fe_config.md
  docs/zh-CN/administrator-guide/config/fe_config.md
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/metric/MetricRepo.java
  fe/fe-core/src/main/java/org/apache/doris/planner/Planner.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SimpleScheduler.java
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/Cache.java
Labels: approved, area/sql/cache, kind/feature

#4152 [Spill To Disk][2/6] Add some runningtime function and change some function will be called in the future
  be/src/runtime/bufferpool/suballocator.cc
  be/src/runtime/bufferpool/suballocator.h
  be/src/runtime/descriptors.cpp
  be/src/runtime/descriptors.h
  be/src/runtime/row_batch.h
Labels: approved, area/sql/execution, kind/enhancement

#4190 [Feature]Add fetch/update/clear proto of fe&be for cache
  fe/fe-core/src/main/java/org/apache/doris/rpc/BackendServiceProxy.java
  fe/fe-core/src/main/java/org/apache/doris/rpc/PBackendService.java
  gensrc/proto/internal_service.proto
  gensrc/proto/palo_internal_service.proto
Labels: approved, area/sql/cache, kind/feature

#4216 [Bug][ColocateJoin] Fix the bug 'Make a wrong choice of colocate join'
  fe/fe-core/src/main/java/org/apache/doris/planner/DistributedPlanner.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: approved, area/sql/planner, branch-0.13, kind/bug
