Repository apache/doris, pull requests merged in 2020-02, with the labels that each got.

#2842 Fix removing tablet bug from partition_map in TabletManager
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
  be/src/olap/tablet_manager.cpp
  be/src/olap/tablet_manager.h
Labels: bug, storage engine

#2868 Fix lock type when clear trash
  be/src/olap/tablet_manager.cpp
  be/src/olap/tablet_manager.h
Labels: bug, storage engine

#2861 Remove boost exception when parse store path
  be/src/http/download_action.cpp
  be/src/http/download_action.h
  be/src/olap/options.cpp
  be/src/olap/options.h
  be/src/util/path_util.cpp
  be/src/util/path_util.h
  be/test/util/path_util_test.cpp
Labels: enhancement

#2881 Improve the triggering strategy of BE report
  be/src/agent/heartbeat_server.cpp
  be/src/olap/olap_server.cpp
  be/src/olap/storage_engine.cpp
  be/src/olap/storage_engine.h
  be/src/olap/tablet_manager.cpp
  be/src/olap/tablet_manager.h
Labels: enhancement, storage engine

#2884 Add `sync_dir` interface to Env
  be/src/common/status.h
  be/src/env/env.h
  be/src/env/env_posix.cpp
Labels: enhancement, storage engine

#2882 Convert UnionStmt class into to SetOperationStmt, add Syntax support to sql_parser
  fe/src/main/cup/sql_parser.cup
  fe/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/src/main/java/org/apache/doris/analysis/SetOperationStmt.java
  fe/src/main/java/org/apache/doris/analysis/StmtRewriter.java
  fe/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
  fe/src/main/jflex/sql_scanner.flex
  fe/src/test/java/org/apache/doris/analysis/SetOperationStmtTest.java
Labels: tpc-ds

#2898 Add env-util class
  be/src/env/CMakeLists.txt
  be/src/env/env_util.cpp
  be/src/env/env_util.h
Labels: enhancement, storage engine

#2905 [util] Import util tools from KUDU
  be/src/agent/task_worker_pool.cpp
  be/src/agent/task_worker_pool.h
  be/src/olap/data_dir.h
  be/src/olap/lru_cache.h
  be/src/olap/tablet_meta.h
  be/src/olap/utils.cpp
  be/src/olap/utils.h
  be/src/runtime/bufferpool/buffer_pool_internal.h
  be/src/runtime/dpp_sink.cpp
  be/src/util/CMakeLists.txt
  be/src/util/condition_variable.cpp
  be/src/util/condition_variable.h
  be/src/util/count_down_latch.hpp
  be/src/util/countdown_latch.h
  be/src/util/file_utils.cpp
  be/src/util/mem_info.cpp
  be/src/util/monotime.cpp
  be/src/util/monotime.h
  be/src/util/mutex.cpp
  be/src/util/mutex.h
  be/src/util/scoped_cleanup.h
  be/test/olap/skiplist_test.cpp
  be/test/util/CMakeLists.txt
  be/test/util/count_down_latch_test.cpp
  be/test/util/countdown_latch_test.cpp
  be/test/util/monotime_test.cpp
  be/test/util/scoped_cleanup_test.cpp
  run-ut.sh
Labels: enhancement

#2928 [util] Add Apache License 2.0 to Thread
  be/src/util/question
  be/src/util/thread.cpp
  be/src/util/thread.h
Labels: Apache way

#2931 Use ThreadPool to refactor MemTableFlushExecutor
  be/src/exec/olap_scan_node.cpp
  be/src/olap/delta_writer.cpp
  be/src/olap/delta_writer.h
  be/src/olap/memtable_flush_executor.cpp
  be/src/olap/memtable_flush_executor.h
  be/src/runtime/dpp_sink.cpp
  be/src/runtime/exec_env.h
  be/src/runtime/exec_env_init.cpp
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/fragment_mgr.h
  be/src/runtime/routine_load/data_consumer_group.h
  be/src/runtime/routine_load/routine_load_task_executor.h
  be/src/runtime/runtime_state.h
  be/src/runtime/tablets_channel.h
  be/src/service/internal_service.h
  be/src/util/priority_thread_pool.hpp
  be/src/util/thread_pool.hpp
  be/test/olap/skiplist_test.cpp
  be/test/runtime/load_channel_mgr_test.cpp
Labels: enhancement

#2951 [ut] Add log to track problem in small_file_mgr_test
  be/test/runtime/small_file_mgr_test.cpp
Labels: unit test
