Repository apache/doris, pull requests merged in 2020-04, with the labels that each got.

#3240 [segment_v2] Fix a bug that NullBitmapBuilder may not be reset
  be/src/olap/rowset/segment_v2/column_writer.cpp
  be/test/olap/rowset/segment_v2/column_reader_writer_test.cpp
Labels: bug

#3208 Sql reference of materialized view
  docs/documentation/cn/administrator-guide/alter-table/alter-table-schema-change.md
  docs/documentation/cn/administrator-guide/materialized-view/index.rst
  docs/documentation/cn/sql-reference/sql-statements/Data Definition/CREATE MATERIALIZED VIEW.md
  docs/documentation/cn/sql-reference/sql-statements/Data Definition/DROP MATERIALIZED VIEW.md
  docs/documentation/en/sql-reference/sql-statements/Data Definition/CREATE MATERIALIZED VIEW.md
  docs/documentation/en/sql-reference/sql-statements/Data Definition/DROP MATERIALIZED VIEW.md
  fe/src/main/java/org/apache/doris/analysis/CreateMaterializedViewStmt.java
Labels: document

#3214 Fix cast date type return wrong result
  fe/src/main/java/org/apache/doris/analysis/DateLiteral.java
  fe/src/test/java/org/apache/doris/analysis/DateLiteralTest.java
Labels: SQL Bug

#3237 fix the bug that 'username' in broker load is invalid
  fs_brokers/apache_hdfs_broker/src/main/java/org/apache/doris/broker/hdfs/FileSystemManager.java
Labels: bug

#3269 Optimize performance of TxnManager::build_expire_txn_map
  be/src/olap/tablet_manager.cpp
  be/src/olap/txn_manager.cpp
  be/src/olap/txn_manager.h
Labels: Performance, storage engine

#3271 [Bug] Avoid compacting recently added rowset
  be/src/common/config.h
  be/src/olap/cumulative_compaction.cpp
  be/src/olap/rowset/rowset.cpp
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
  be/src/olap/txn_manager.cpp
  be/src/olap/txn_manager.h
  be/src/util/time.h
Labels: bug, storage engine

#3281 fix openssl download url is not avaliable
  thirdparty/vars.sh
Labels: build, dependencies

#3280 Add Google/CCTZ lib in Doris
  thirdparty/build-thirdparty.sh
  thirdparty/vars.sh
Labels: build, dependencies

#3279 [BUG] Fix cast result expr bug
  fe/src/main/java/org/apache/doris/analysis/StatementBase.java
  fe/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: SQL Bug

#3276 [refactor] A small refactor on class DataDir
  be/src/http/action/restore_tablet_action.cpp
  be/src/olap/data_dir.cpp
  be/src/olap/data_dir.h
  be/src/olap/olap_snapshot_converter.cpp
  be/src/olap/tablet.h
  be/src/olap/tablet_manager.cpp
  be/test/olap/olap_snapshot_converter_test.cpp
  gensrc/proto/olap_file.proto
Labels: enhancement, storage engine

#3288 Fix bug when use ZoneMap/BloomFiter on column with REPLACE/REPLACE_IF_NOT_NULL
  be/src/olap/rowset/beta_rowset_writer.cpp
  be/src/olap/rowset/segment_reader.cpp
  be/src/olap/rowset/segment_v2/segment_writer.cpp
  be/src/olap/rowset/segment_v2/segment_writer.h
  be/test/olap/rowset/segment_v2/segment_test.cpp
  fe/src/main/java/org/apache/doris/common/util/PropertyAnalyzer.java
  fe/src/test/java/org/apache/doris/common/PropertyAnalyzerTest.java
Labels: bug

#3291 Forbidden multi subquery in having clause
  fe/src/main/java/org/apache/doris/analysis/DropMaterializedViewStmt.java
  fe/src/main/java/org/apache/doris/analysis/Expr.java
  fe/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/src/main/java/org/apache/doris/analysis/StmtRewriter.java
Labels: SQL Bug

#3283 Support setting replica quota in db level
  docs/documentation/cn/sql-reference/sql-statements/Data Definition/ALTER DATABASE.md
  docs/documentation/cn/sql-reference/sql-statements/Data Manipulation/SHOW DATA.md
  docs/documentation/en/sql-reference/sql-statements/Data Definition/ALTER DATABASE_EN.md
  docs/documentation/en/sql-reference/sql-statements/Data Manipulation/SHOW DATA_EN.md
  fe/src/main/cup/sql_parser.cup
  fe/src/main/java/org/apache/doris/analysis/AlterDatabaseQuotaStmt.java
  fe/src/main/java/org/apache/doris/analysis/ShowDataStmt.java
  fe/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/src/main/java/org/apache/doris/catalog/Database.java
  fe/src/main/java/org/apache/doris/catalog/MaterializedIndex.java
  fe/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/src/main/java/org/apache/doris/catalog/Partition.java
  fe/src/main/java/org/apache/doris/common/FeConstants.java
  fe/src/main/java/org/apache/doris/common/FeMetaVersion.java
  fe/src/main/java/org/apache/doris/common/proc/DbsProcDir.java
  fe/src/main/java/org/apache/doris/common/proc/TablesProcDir.java
  fe/src/main/java/org/apache/doris/common/util/ParseUtil.java
  fe/src/main/java/org/apache/doris/load/Load.java
  fe/src/main/java/org/apache/doris/persist/DatabaseInfo.java
  fe/src/main/java/org/apache/doris/persist/EditLog.java
  fe/src/test/java/org/apache/doris/analysis/AlterDatabaseQuotaStmtTest.java
  fe/src/test/java/org/apache/doris/analysis/ShowDataStmtTest.java
  fe/src/test/java/org/apache/doris/common/proc/DbsProcDirTest.java
Labels: enhancement

#3324 Enable to read and write boolean type data
  be/src/olap/rowset/column_reader.cpp
  be/src/olap/rowset/column_writer.cpp
  fe/src/main/java/org/apache/doris/catalog/ScalarType.java
Labels: enhancement

#3333 fix document bug of storage_cooldown_time
  docs/documentation/cn/getting-started/data-partition.md
  docs/documentation/en/getting-started/data-partition_EN.md
  docs/documentation/en/sql-reference/sql-statements/Data Definition/CREATE TABLE_EN.md
Labels: document

#3330 Fix rowset_meta race condition for commit_txn in TxnManager
  be/src/common/config.h
  be/src/olap/txn_manager.cpp
  be/src/olap/txn_manager.h
Labels: bug

#3338 [ISSUE #3190]Make some correct in delete
  fe/src/main/java/org/apache/doris/load/DeleteHandler.java
  fe/src/main/java/org/apache/doris/load/DeleteJob.java
  fe/src/main/java/org/apache/doris/master/MasterImpl.java
  fe/src/test/java/org/apache/doris/load/DeleteHandlerTest.java
Labels: bug

#3340 [SegmentV2] Optimize the upgrade logic of SegmentV2
  docs/documentation/cn/administrator-guide/segment-v2-usage.md
  fe/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
  fe/src/main/java/org/apache/doris/alter/SchemaChangeJobV2.java
  fe/src/main/java/org/apache/doris/analysis/InstallPluginStmt.java
  fe/src/main/java/org/apache/doris/analysis/UninstallPluginStmt.java
  fe/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/src/main/java/org/apache/doris/catalog/TableProperty.java
  fe/src/main/java/org/apache/doris/common/ErrorCode.java
  fe/src/main/java/org/apache/doris/common/FeMetaVersion.java
  fe/src/main/java/org/apache/doris/common/util/PropertyAnalyzer.java
  fe/src/main/java/org/apache/doris/planner/MaterializedViewSelector.java
  fe/src/main/java/org/apache/doris/planner/RollupSelector.java
  fe/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
  fe/src/main/java/org/apache/doris/plugin/AuditEvent.java
  fe/src/main/java/org/apache/doris/qe/QueryState.java
  fe/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/src/main/java/org/apache/doris/system/HeartbeatFlags.java
  fe/src/test/java/org/apache/doris/alter/AlterJobV2Test.java
  fe_plugins/auditloader/src/main/java/org/apache/doris/plugin/audit/AuditLoaderPlugin.java
  fe_plugins/auditloader/src/main/java/org/apache/doris/plugin/audit/DorisStreamLoader.java
  tools/show_segment_status/README.md
Labels: FE meta version, enhancement

#3366 Modify test to be compative with cov tool
  be/test/common/config_test.cpp
Labels: unit test

#3363 [Bug]Use OlapTableSink::close to replace OlapTableSink::finalize method to avoid OOM
  fe/src/main/java/org/apache/doris/analysis/InsertStmt.java
  fe/src/main/java/org/apache/doris/load/loadv2/LoadingTaskPlanner.java
  fe/src/main/java/org/apache/doris/planner/OlapTableSink.java
  fe/src/main/java/org/apache/doris/planner/Planner.java
  fe/src/main/java/org/apache/doris/planner/StreamLoadPlanner.java
  fe/src/test/java/org/apache/doris/planner/OlapTableSinkTest.java
Labels: bug

#3374 [Bug] `isQuery` field should be reset at the beginning of query execution
  docs/documentation/cn/administrator-guide/segment-v2-usage.md
  fe/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/src/main/java/org/apache/doris/catalog/DomainResolver.java
  fe/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/src/main/java/org/apache/doris/mysql/privilege/PaloAuth.java
  fe/src/main/java/org/apache/doris/mysql/privilege/UserPropertyMgr.java
  fe/src/main/java/org/apache/doris/mysql/privilege/WhiteList.java
  fe/src/main/java/org/apache/doris/qe/QueryState.java
Labels: bug

#3300 Use Google/CCTZ to replace boost at timezone function
  be/CMakeLists.txt
  be/src/exec/orc_scanner.cpp
  be/src/exprs/timestamp_functions.cpp
  be/src/exprs/timestamp_functions.h
  be/src/runtime/datetime_value.cpp
  be/src/runtime/datetime_value.h
  be/test/exprs/timestamp_functions_test.cpp
  be/test/runtime/datetime_value_test.cpp
Labels: Performance

#3360 Alter replication number for table in one command
  docs/documentation/cn/administrator-guide/index.rst
  docs/documentation/cn/administrator-guide/load-data/delete-manual.md
  docs/documentation/cn/administrator-guide/load-data/index.rst
  docs/documentation/cn/sql-reference/sql-statements/Data Definition/ALTER TABLE.md
  docs/documentation/en/administrator-guide/load-data/delete-manual_EN.md
  docs/documentation/en/administrator-guide/load-data/index.rst
  docs/documentation/en/sql-reference/sql-statements/Data Definition/ALTER TABLE_EN.md
  fe/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
  fe/src/main/java/org/apache/doris/analysis/ModifyTablePropertiesClause.java
  fe/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/src/main/java/org/apache/doris/common/util/PropertyAnalyzer.java
  fe/src/test/java/org/apache/doris/alter/AlterTest.java
Labels: new feature

#3423 [Bug] Fix bug that help-resource.zip file is missing.
  build.sh
  docs/build_help_zip.sh
Labels: bug, document

#3436 Fix the error result when assert num rows node is used
  be/src/exec/assert_num_rows_node.cpp
Labels: bug, tpc-ds

#3437 [UT] Fix AlterTest UT failed
  fe/src/test/java/org/apache/doris/alter/AlterTest.java
Labels: unit test
