Repository apache/doris, pull requests merged in 2020-09, with the labels that each got.

#4484 [Bug] Fix bug of select @@sql_mode
  fe/fe-core/src/main/java/org/apache/doris/analysis/StringLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SysVariableDesc.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/SetVariableTest.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/UtFrameUtils.java
Labels: approved, area/mysql-compatibility, kind/bug

#4482 Do not add exchange when table's distributioin satisfy the distribution requirements
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/planner/DistributedPlanner.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: approved, area/sql/planner, kind/enhancement

#4428 [Metrics] Support tablet level metrics
  be/src/agent/task_worker_pool.cpp
  be/src/common/daemon.cpp
  be/src/exec/olap_scanner.cpp
  be/src/exec/tablet_sink.cpp
  be/src/http/action/compaction_action.cpp
  be/src/http/action/metrics_action.cpp
  be/src/http/action/stream_load.cpp
  be/src/http/action/stream_load.h
  be/src/olap/base_compaction.cpp
  be/src/olap/base_tablet.cpp
  be/src/olap/base_tablet.h
  be/src/olap/cumulative_compaction.cpp
  be/src/olap/data_dir.cpp
  be/src/olap/data_dir.h
  be/src/olap/delta_writer.cpp
  be/src/olap/fs/block_manager_metrics.cpp
  be/src/olap/memtable.cpp
  be/src/olap/memtable_flush_executor.h
  be/src/olap/olap_meta.cpp
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/olap/storage_engine.cpp
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
  be/src/olap/tablet_manager.cpp
  be/src/olap/task/engine_alter_tablet_task.cpp
  be/src/olap/task/engine_batch_load_task.cpp
  be/src/olap/task/engine_storage_migration_task.cpp
  be/src/runtime/client_cache.cpp
  be/src/runtime/client_cache.h
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/mem_pool.cpp
  be/src/runtime/memory/chunk_allocator.cpp
  be/src/runtime/memory/chunk_allocator.h
  be/src/runtime/stream_load/stream_load_executor.cpp
  be/src/runtime/tmp_file_mgr.cc
  be/src/runtime/tmp_file_mgr.h
  be/src/util/doris_metrics.cpp
  be/src/util/doris_metrics.h
  be/src/util/metrics.cpp
  be/src/util/metrics.h
  be/src/util/system_metrics.cpp
  be/src/util/system_metrics.h
  be/src/util/thrift_server.cpp
  be/src/util/thrift_server.h
  be/test/agent/cgroups_mgr_test.cpp
  be/test/exprs/hybird_set_test.cpp
  be/test/http/metrics_action_test.cpp
  be/test/olap/push_handler_test.cpp
  be/test/util/doris_metrics_test.cpp
  be/test/util/new_metrics_test.cpp
  be/test/util/system_metrics_test.cpp
Labels: approved, kind/feature, kind/refactor

#4439 Validate the param of rand function in compile step
  fe/fe-core/src/main/java/org/apache/doris/analysis/Expr.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/SelectStmtTest.java
Labels: approved, area/sql/function, kind/bug

#4489 [Spark load][Document] Add docs about spark and yarn client for spark load
  docs/en/administrator-guide/load-data/spark-load-manual.md
  docs/zh-CN/administrator-guide/load-data/spark-load-manual.md
Labels: approved, kind/documentation

#4491 [Spark load][Bug] Fix column terminator for spark load
  fe/fe-core/src/test/java/org/apache/doris/analysis/ColumnSeparatorTest.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/SparkDpp.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/etl/EtlJobConfig.java
Labels: approved, area/spark-load, kind/bug

#4497 [Bug] Support disable colocate join where join clause has join hint
  fe/fe-core/src/main/java/org/apache/doris/planner/DistributedPlanner.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: approved, area/sql/planner

#4330 [Feature][Cache] Sql cache and partition cache #2581
  fe/fe-core/src/main/java/org/apache/doris/common/TreeNode.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/ProfileManager.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/Cache.java
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/CacheAnalyzer.java
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/PartitionCache.java
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/PartitionRange.java
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/RowBatchBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/SqlCache.java
  fe/fe-core/src/test/java/org/apache/doris/qe/PartitionCacheTest.java
Labels: approved, area/sql/cache, kind/feature

#4493 Add a configuration indicating whether to enable the batch delete
  docs/en/administrator-guide/config/fe_config.md
  docs/zh-CN/administrator-guide/config/fe_config.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateTableStmt.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
Labels: approved, kind/feature

#4511 [Bug] Fix bug that BE will crash when querying information_schema.columns
  be/src/exec/schema_scanner/schema_columns_scanner.cpp
Labels: approved, kind/bug

#4513 [BUG] Fix recover persistent stale rowsets bug from multi-single version rowsets in stale rowsets
  be/src/olap/tablet.cpp
  be/src/olap/version_graph.cpp
Labels: approved, area/compact, kind/bug

#4429 Fix parse url bug
  be/src/exprs/string_functions.cpp
  be/src/util/url_parser.cpp
  be/src/util/url_parser.h
  be/test/exprs/string_functions_test.cpp
Labels: approved, area/sql/function, kind/bug

#4498 fix semi/anti join error when table has delete sign column
  fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/SelectStmtTest.java
Labels: approved, area/sql, kind/bug

#4495 [Bug] function str_to_date()'s behavior on BE and FE is inconsistent
  be/src/runtime/datetime_value.cpp
  be/test/runtime/datetime_value_test.cpp
  docs/en/sql-reference/sql-functions/date-time-functions/str_to_date.md
  docs/zh-CN/sql-reference/sql-functions/date-time-functions/str_to_date.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/DateLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/common/InvalidFormatException.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/FEFunctions.java
  fe/fe-core/src/test/java/org/apache/doris/rewrite/FEFunctionsTest.java
Labels: approved, kind/bug

#4430 [ODBC SCAN NODE] 3/4 Add ODBC_TABLE and ODBC_SCAN NODE in FE.
  docs/en/administrator-guide/config/fe_config.md
  docs/zh-CN/administrator-guide/config/fe_config.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateTableStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/DescribeStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ExportStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/InsertStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SlotRef.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OdbcTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Table.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/load/ExportJob.java
  fe/fe-core/src/main/java/org/apache/doris/planner/DistributedPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OdbcScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: approved, kind/feature

#4523 [Bug] Fix bug of core local value
  be/src/util/core_local.cpp
Labels: approved, kind/bug

#4526 [BUG] Fix segment group add zone map bug when schema change.
  be/src/olap/rowset/segment_group.cpp
Labels: approved, kind/bug

#4529 [Bug] Fix bug that query meta fields has been sent twice
  fe/fe-core/src/main/java/org/apache/doris/common/util/DebugUtil.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/ProfileManager.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/CacheAnalyzer.java
Labels: approved, kind/bug

#4256 Support sequence column for UNIQUE_KEYS Table
  be/src/exec/olap_scanner.cpp
  be/src/http/action/stream_load.cpp
  be/src/http/http_common.h
  be/src/olap/memtable.cpp
  be/src/olap/olap_define.h
  be/src/olap/reader.cpp
  be/src/olap/reader.h
  be/src/olap/row.h
  be/src/olap/schema.h
  be/src/olap/tablet_meta.cpp
  be/src/olap/tablet_meta.h
  be/src/olap/tablet_schema.cpp
  be/src/olap/tablet_schema.h
  be/test/olap/delta_writer_test.cpp
  be/test/olap/tablet_mgr_test.cpp
  be/test/olap/test_data/header.txt
  docs/zh-CN/sql-reference/sql-statements/Data Definition/CREATE TABLE.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/BROKER LOAD.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/ROUTINE LOAD.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/STREAM LOAD.md
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/alter/MaterializedViewHandler.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateRoutineLoadStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/DataDescription.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ImportSequenceStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Column.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/IndexInfoProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/org/apache/doris/load/BrokerFileGroup.java
  fe/fe-core/src/main/java/org/apache/doris/load/Load.java
  fe/fe-core/src/main/java/org/apache/doris/load/RoutineLoadDesc.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BulkLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/planner/BrokerScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/StreamLoadPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/task/CreateReplicaTask.java
  fe/fe-core/src/main/java/org/apache/doris/task/LoadTaskInfo.java
  fe/fe-core/src/main/java/org/apache/doris/task/StreamLoadTask.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/DataDescriptionTest.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/CreateTableTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/BrokerLoadJobTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/routineload/KafkaRoutineLoadJobTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/StreamLoadPlannerTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/StreamLoadScanNodeTest.java
  gensrc/proto/olap_file.proto
  gensrc/thrift/AgentService.thrift
  gensrc/thrift/FrontendService.thrift
Labels: approved, kind/feature

#4528 [Spark Load] [Bug] Load job's state will stay in ETL state all the time after FE restart
  fe/fe-core/src/main/java/org/apache/doris/common/FeMetaVersion.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkLoadAppHandle.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkLoadJob.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/SparkLoadJobTest.java
Labels: approved, area/spark-load, kind/bug, kind/meta-version-change

#4535 [Bug] Fix bug that table ids is not set right for hadoop load job
  fe/fe-core/src/main/java/org/apache/doris/load/LoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/task/LoadPendingTask.java
Labels: approved, area/load, kind/bug

#4440 [refactor] Optimize threads usage mode in BE
  be/CMakeLists.txt
  be/src/agent/heartbeat_server.cpp
  be/src/agent/task_worker_pool.cpp
  be/src/agent/task_worker_pool.h
  be/src/common/daemon.cpp
  be/src/common/daemon.h
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
  be/src/http/ev_http_server.cpp
  be/src/http/ev_http_server.h
  be/src/olap/memtable_flush_executor.h
  be/src/olap/olap_meta.cpp
  be/src/olap/olap_server.cpp
  be/src/olap/storage_engine.cpp
  be/src/olap/storage_engine.h
  be/src/runtime/broker_mgr.cpp
  be/src/runtime/broker_mgr.h
  be/src/runtime/disk_io_mgr.cc
  be/src/runtime/exec_env_init.cpp
  be/src/runtime/external_scan_context_mgr.cpp
  be/src/runtime/external_scan_context_mgr.h
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/fragment_mgr.h
  be/src/runtime/load_channel_mgr.cpp
  be/src/runtime/load_channel_mgr.h
  be/src/runtime/load_path_mgr.cpp
  be/src/runtime/load_path_mgr.h
  be/src/runtime/result_buffer_mgr.cpp
  be/src/runtime/result_buffer_mgr.h
  be/src/runtime/routine_load/data_consumer_pool.cpp
  be/src/runtime/routine_load/data_consumer_pool.h
  be/src/service/brpc_service.cpp
  be/src/service/doris_main.cpp
  be/src/service/http_service.cpp
  be/src/service/http_service.h
  be/test/runtime/external_scan_context_mgr_test.cpp
Labels: approved, kind/enhancement

#4505 Add log for trace broker
  fe/fe-core/src/main/java/org/apache/doris/common/util/BrokerUtil.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BrokerLoadPendingTask.java
Labels: approved

#4514 [Feature] support hour time unit with dynamic parition
  docs/en/administrator-guide/dynamic-partition.md
  docs/zh-CN/administrator-guide/dynamic-partition.md
  fe/fe-core/src/main/java/org/apache/doris/common/ErrorCode.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/DynamicPartitionUtil.java
Labels: approved, area/catalog, kind/enhancement

#4504 [Feature]Support SELECT Optimizer Hints SET_VAR
  docs/en/administrator-guide/variables.md
  docs/zh-CN/administrator-guide/variables.md
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectList.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/main/jflex/sql_scanner.flex
  fe/fe-core/src/test/java/org/apache/doris/analysis/SelectStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/DorisAssert.java
Labels: kind/feature

#4531 [BUG] Tablet is not readable and delete handler report -1903 error, when condition value contains \n
  be/src/olap/delete_handler.cpp
Labels: approved, kind/bug

#4533 [Enhance] Support gzip compression for http response
  be/src/http/http_channel.cpp
  be/src/http/http_channel.h
  be/src/http/http_request.cpp
  be/src/util/CMakeLists.txt
  be/src/util/zlib.cpp
  be/src/util/zlib.h
  be/test/util/CMakeLists.txt
  be/test/util/http_channel_test.cpp
Labels: approved, kind/enhancement

#4536 [Spark load][Bug] fix that cancelling a spark load in the `PENDING` phase will not succeed
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkEtlJobHandler.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkLauncherMonitor.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkLoadAppHandle.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkLoadPendingTask.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/SparkEtlJobHandlerTest.java
Labels: approved, area/spark-load, kind/bug

#4532 [Spark Load][Bug] Keep the column splitting in spark load consistent with broker load / mini load
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/SparkDpp.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/etl/EtlJobConfig.java
Labels: approved, area/spark-load, kind/bug

#4521 add version message to fe heartbeat and system page
  fe/src/main/java/org/apache/doris/common/proc/FrontendsProcNode.java
  fe/src/main/java/org/apache/doris/http/rest/BootstrapFinishAction.java
  fe/src/main/java/org/apache/doris/system/Frontend.java
  fe/src/main/java/org/apache/doris/system/FrontendHbResponse.java
  fe/src/main/java/org/apache/doris/system/HeartbeatMgr.java
  gensrc/script/gen_build_version.sh
Labels: approved, good first issue, kind/enhancement

#4542 Add a new global variable "performance_schema" to enable doris support Mysql JDBC 8.0.16 or later.#4537#
  docs/en/administrator-guide/variables.md
  docs/zh-CN/administrator-guide/variables.md
  fe/fe-core/src/main/java/org/apache/doris/qe/GlobalVariable.java
Labels: approved, area/mysql-compatibility, good first issue, kind/enhancement

#4543 [Bug] Fix bug that task_worker_pool not work
  be/src/agent/task_worker_pool.cpp
  fe/fe-core/src/test/java/org/apache/doris/analysis/SelectStmtTest.java
Labels: approved, kind/bug

#4545 [Bug] fix `SparkLoadPendingTest.java` ut test
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/SparkLoadPendingTaskTest.java
Labels: area/test, kind/bug

#4558 fix enable feature error
  fe/fe-core/src/main/java/org/apache/doris/analysis/AlterTableStmt.java
Labels: approved, kind/bug

#4555 Remove primary key type
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Column.java
Labels: approved, area/sql

#4572 Fix null pointer when replay RollupJob
  fe/fe-core/src/main/java/org/apache/doris/alter/RollupJob.java
Labels: area/catalog, kind/bug

#4510 Add a session variable to show or hide hidden columns
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/administrator-guide/load-data/batch-delete-manual.md
  docs/zh-CN/administrator-guide/load-data/batch-delete-manual.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/MaterializedIndexMeta.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/SchemaTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Table.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/IndexInfoProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/Util.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SchemaScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/SelectStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/qe/PartitionCacheTest.java
  gensrc/thrift/FrontendService.thrift
  gensrc/thrift/PlanNodes.thrift
Labels: approved, kind/documentation, kind/enhancement

#4576 Revert "Add a session variable to show or hide hidden columns"
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/administrator-guide/load-data/batch-delete-manual.md
  docs/zh-CN/administrator-guide/load-data/batch-delete-manual.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/MaterializedIndexMeta.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/SchemaTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Table.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/IndexInfoProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/Util.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SchemaScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/SelectStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/qe/PartitionCacheTest.java
  gensrc/thrift/FrontendService.thrift
  gensrc/thrift/PlanNodes.thrift
Labels: kind/revert

#4577 Fix broker load batch delete not work
  fe/fe-core/src/main/java/org/apache/doris/planner/BrokerScanNode.java
Labels: approved, area/load, kind/bug

#4583 [UI Part 1] Update pom.xml of Frontend
  fe/fe-core/pom.xml
  fe/pom.xml
Labels: approved, area/fe/frontpage, kind/feature

#4547 [Bug] Fix bug that colocate join can not perceive parameter parallel_fragment_exec_instance_num (#4546)
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/test/java/org/apache/doris/qe/CoordinatorTest.java
Labels: SQL Bug, approved

#4550 【Feature】Doris can set default configuration of database data quota and replica quota #4540#
  docs/en/administrator-guide/config/fe_config.md
  docs/zh-CN/administrator-guide/config/fe_config.md
  fe/fe-core/src/main/java/org/apache/doris/catalog/Database.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/common/FeConstants.java
Labels: approved, area/config, kind/enhancement

#4561 [Bug] catch plugin init error for Reinstall plugin
  fe/fe-core/src/main/java/org/apache/doris/plugin/DynamicPluginLoader.java
Labels: approved, area/plugin, kind/bug

#4575 [Bug] fix TabletsChannel::add_batch() check state
  be/src/runtime/tablets_channel.cpp
Labels: approved, area/load, kind/bug

#4580 [MemTracker] show all MemTrackers on BE's website
  be/src/http/default_path_handlers.cpp
Labels: approved, area/be/frontpage, kind/feature

#4585 [Bug] fix get_parsed_paths() subscript out of range
  be/src/exprs/json_functions.cpp
Labels: approved, kind/bug

#4524 [SparkDpp] Support complete types
  be/src/olap/push_handler.cpp
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/ColumnParser.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/SparkDpp.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/SparkRDDAggregator.java
  fe/spark-dpp/src/test/java/org/apache/doris/load/loadv2/dpp/ColumnParserTest.java
  fe/spark-dpp/src/test/java/org/apache/doris/load/loadv2/dpp/SparkDppTest.java
Labels: approved, area/spark-load, kind/enhancement

#4539 [storage][compatibility] Add meta format detection to prevent data loss.
  be/src/common/config.h
  be/src/olap/data_dir.cpp
  be/src/olap/data_dir.h
  be/src/olap/tablet_meta_manager.cpp
  docs/en/administrator-guide/config/be_config.md
  docs/zh-CN/administrator-guide/config/be_config.md
Labels: approved, kind/enhancement

#4553 [Feature] FE add default configuration of max_fiter_ratio #4541#
  docs/en/administrator-guide/config/fe_config.md
  docs/zh-CN/administrator-guide/config/fe_config.md
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/load/LoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadJob.java
Labels: approved, area/config

#4567 [Bug]Fix bug that tablet info with wrong capacity may cause fe oom
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
Labels: approved, kind/bug

#4570 fix the the parallesim of fragment which has 3 or more childern #4569
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
Labels: approved, area/sql/planner, kind/bug

#4579 Add a session variable to show or hide hidden columns
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/administrator-guide/load-data/batch-delete-manual.md
  docs/zh-CN/administrator-guide/load-data/batch-delete-manual.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/MaterializedIndexMeta.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Table.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/IndexInfoProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/Util.java
  fe/fe-core/src/main/java/org/apache/doris/planner/RollupSelector.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SchemaScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/SelectStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/qe/PartitionCacheTest.java
  gensrc/thrift/FrontendService.thrift
  gensrc/thrift/PlanNodes.thrift
Labels: approved, area/delete, area/load, kind/documentation

#4590 Set BoolLiteral's selectivity
  fe/fe-core/src/main/java/org/apache/doris/analysis/BoolLiteral.java
Labels: approved, area/sql/planner, kind/bug

#4591 support int datekey format implicit cast to date
  fe/fe-core/src/main/java/org/apache/doris/analysis/BinaryPredicate.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CastExpr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/DateLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/StringLiteral.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/SelectStmtTest.java
Labels: approved, area/sql/planner, kind/bug

#4587 [BUG] ReAgg when adding agg mv on dup base table
  be/src/olap/schema_change.cpp
Labels: approved, area/materialized-view, area/schema-change, kind/bug

#4595 [Bug] Fix bug that BE will crash when querying information_schema.columns
  be/src/exec/schema_scanner/schema_columns_scanner.cpp
Labels: approved, kind/bug

#4582 [Feature] Support alter table syntax for sequence column
  docs/en/sql-reference/sql-statements/Data Definition/ALTER TABLE.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/ALTER TABLE.md
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/alter/MaterializedViewHandler.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/AlterTableStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ColumnDef.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/EnableFeatureClause.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/test/java/org/apache/doris/alter/AlterTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/AlterTableStmtTest.java
Labels: approved, kind/feature

#4599 [compaction][config] Change default config policy to size_based
  be/src/common/config.h
  be/src/olap/tablet.cpp
Labels: approved, area/compact, area/config, kind/api-change

#4612 [Bug] behavior of function str_to_date() and date_format() on BE and FE is inconsistent
  be/src/runtime/datetime_value.cpp
  be/test/runtime/datetime_value_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/analysis/DateLiteral.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/DateLiteralTest.java
Labels: area/sql/function, good first issue, kind/bug

#4005 [Cache][BE] LRU cache for sql/partition cache #2581
  be/src/common/config.h
  be/src/runtime/CMakeLists.txt
  be/src/runtime/cache/cache_utils.h
  be/src/runtime/cache/result_cache.cpp
  be/src/runtime/cache/result_cache.h
  be/src/runtime/cache/result_node.cpp
  be/src/runtime/cache/result_node.h
  be/src/runtime/exec_env.cpp
  be/src/runtime/exec_env.h
  be/src/runtime/exec_env_init.cpp
  be/src/service/internal_service.cpp
  be/src/service/internal_service.h
  be/src/util/doris_metrics.cpp
  be/src/util/doris_metrics.h
  be/src/util/uid_util.h
  be/test/runtime/CMakeLists.txt
  be/test/runtime/cache/partition_cache_test.cpp
  docs/zh-CN/administrator-guide/partition_cache.md
Labels: approved, area/sql/execution, kind/feature

#4597 [Bug] Tablet and Disk report thread not work
  be/src/agent/task_worker_pool.cpp
  be/src/agent/task_worker_pool.h
  be/src/olap/storage_engine.cpp
Labels: approved, kind/bug

#4605 [Bug] Fix bug that forwarding show tablet stmt return error
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
Labels: approved, kind/bug

#4607 [Doc]update documents of dynamic partition
  docs/en/administrator-guide/dynamic-partition.md
  docs/zh-CN/administrator-guide/dynamic-partition.md
Labels: approved, kind/documentation

#4609 [Bug] Fix the calculation of the variable "left_bytes" in data_dir.cpp
  be/src/olap/data_dir.cpp
Labels: approved, kind/bug

#4611 [Bug] Fix the bug of #4608, support order by, where, limit in `show alter table rollup`
  fe/fe-core/src/main/java/org/apache/doris/common/proc/RollupProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
Labels: approved, kind/api-change

#4613 [Bug] catch IllegalArgumentException in DynamicPartitionScheduler
  fe/fe-core/src/main/java/org/apache/doris/clone/DynamicPartitionScheduler.java
Labels: approved, kind/bug

#4615 Change force order in Drop db, Drop table, Drop partition stmt
  fe/fe-core/src/main/cup/sql_parser.cup
Labels: approved, area/sql, kind/bug

#4622 support CTE statement without use db
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/SelectStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/DorisAssert.java
Labels: approved, kind/bug

#4626 [BUG] Some function in odbc external table different in Doris (#4625)
  fe/fe-core/src/main/java/org/apache/doris/planner/OdbcScanNode.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: approved, area/sql/planner, kind/bug

#4627 [Refactor] Remove meaningless return value of RowBlock::init
  be/src/olap/row_block.cpp
  be/src/olap/row_block.h
  be/src/olap/rowset/alpha_rowset_reader.cpp
  be/src/olap/rowset/beta_rowset_reader.cpp
  be/src/olap/rowset/column_data_writer.cpp
  be/src/olap/schema_change.cpp
  be/src/olap/schema_change.h
  be/test/olap/row_block_test.cpp
  be/test/olap/row_block_v2_test.cpp
Labels: approved, kind/refactor

#4629 Fix join Predicate transitivity bug
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: approved, area/sql/planner, kind/bug

#4631 [Bug] Fix bug that wrong usage for HashBasedTable iterator may cause ConcurrentModificationException
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletChecker.java
Labels: approved, kind/bug

#4636 [Compile] Add pluginRepository for java-cup-plugins
  docs/en/installing/compilation.md
  docs/zh-CN/installing/compilation.md
  fe/pom.xml
Labels: approved, area/build

#4610 [Document] Fix some typo in alter table document
  docs/en/sql-reference/sql-statements/Data Definition/ALTER TABLE.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/ALTER TABLE.md
Labels: approved

#4646 [Bug] Fix analysis error when there are different types in case-when-then-else with group by clause
  fe/fe-core/src/main/java/org/apache/doris/analysis/AggregateInfo.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SlotRef.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: approved, area/sql/planner, kind/bug

#4651 Fix all queries failed when one BE network or disk has issue
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
Labels: approved, area/rpc, kind/bug

#4661 [BUG] Fix transaction not be cleared after BE down.
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
Labels: kind/bug

#4653 【bug】Fix unit test bug
  fe/fe-core/src/test/java/org/apache/doris/analysis/SelectStmtTest.java
Labels: approved, area/test, kind/bug

#4664 [License] Add license
  .rat-excludes
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/SparkYarnConfigFilesTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/YarnApplicationReportTest.java
Labels: kind/license

#4663 Fix compile error
  thirdparty/vars.sh
Labels: approved, area/build

#4559 [NewFeature] Support ExternalCatalogResource to simplify external table manage operation.
  docs/en/sql-reference/sql-statements/Data Definition/CREATE TABLE.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/CREATE TABLE.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowResourcesStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/MysqlTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OdbcCatalogResource.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OdbcTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Resource.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/ResourceMgr.java
  fe/fe-core/src/main/java/org/apache/doris/common/FeMetaVersion.java
  fe/fe-core/src/main/java/org/apache/doris/persist/gson/GsonUtils.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/CreateResourceStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/OdbcCatalogResourceTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: approved, kind/feature, kind/meta-version-change

#4659 Update data-model-rollup.md
  docs/zh-CN/getting-started/data-model-rollup.md
Labels: approved, good first issue, kind/documentation

#4648 Fix DATA_TYPE in information_schema.columns is not compatible to mysql meta
  be/src/exec/schema_scanner/schema_columns_scanner.cpp
  be/src/exec/schema_scanner/schema_columns_scanner.h
Labels: approved, area/mysql-compatibility, kind/bug

#4639 [cache][be]Fix the bug of cross-border access cache
  be/src/runtime/cache/result_node.cpp
  be/test/runtime/cache/partition_cache_test.cpp
Labels: approved, area/sql/cache, kind/bug

#4641 [Docs] Supply BE config docs of setting and examples
  docs/en/administrator-guide/config/be_config.md
  docs/zh-CN/administrator-guide/config/be_config.md
Labels: approved, kind/documentation

#4642 [Docs] Change incorrect bos endpoint in broker docs
  docs/en/administrator-guide/broker.md
  docs/zh-CN/administrator-guide/broker.md
Labels: approved, kind/documentation

#4658 [Bug] Fix that the partitions of a dynamic-partitioned table has not been created at the time of load or insert
  fe/fe-core/src/main/java/org/apache/doris/analysis/InsertStmt.java
  fe/fe-core/src/main/java/org/apache/doris/common/ErrorCode.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadingTaskPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/planner/StreamLoadPlanner.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/DynamicPartitionTableTest.java
Labels: approved, kind/bug

#4667 [Doc] Fix typo
  docs/zh-CN/getting-started/data-model-rollup.md
Labels: approved, good first issue, kind/documentation

#4671 [Bug]External engines(e.g. ES) don't have segments, ignore those tables
  tools/show_segment_status/fe_meta_resolver.py
Labels: approved, kind/bug

#4672 [UDF] Improve performance of function money_format
  be/src/exprs/string_functions.h
  be/test/exprs/string_functions_test.cpp
Labels: approved, area/sql/function

#4676 [Bug]Fix information_schema.columns table column_comment does not show
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
Labels: approved, kind/bug

#4474 [Dockerfile] Update Dockerfile
  docker/Dockerfile
  docker/README.md
Labels: area/build

#4683 Fix delete on clause may not work in routineLoad
  be/src/http/action/stream_load.cpp
  docs/en/sql-reference/sql-statements/Data Manipulation/ROUTINE LOAD.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/ROUTINE LOAD.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateRoutineLoadStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/DataDescription.java
  fe/fe-core/src/main/java/org/apache/doris/load/BrokerFileGroup.java
  fe/fe-core/src/main/java/org/apache/doris/load/BrokerFileGroupAggInfo.java
  fe/fe-core/src/main/java/org/apache/doris/load/RoutineLoadDesc.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/CreateRoutineLoadStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/StreamLoadPlannerTest.java
  fe/fe-core/src/test/java/org/apache/doris/qe/PartitionCacheTest.java
Labels: approved, area/load, kind/bug

#4686 Fix hidden cloumn may disappeared
  fe/fe-core/src/main/java/org/apache/doris/alter/MaterializedViewHandler.java
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
Labels: approved, kind/bug
