Repository apache/doris, pull requests merged in 2020-08, with the labels that each got.

#4199 Change type of sum, min, max function column in mv
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateMaterializedViewStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/MVColumnItem.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/CreateMaterializedViewStmtTest.java
Labels: approved, area/materialized-view, branch-0.13

#4207 Fix window function with limit zero bug
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
Labels: approved, area/sql/planner, branch-0.13

#4214 [BUG]Fix remove expired stale rowset path order error
  be/src/olap/tablet.cpp
  be/test/olap/CMakeLists.txt
  be/test/olap/tablet_test.cpp
Labels: approved, branch-0.13

#4219 [BUG] Fix wrong result of querying with cast expr in where clause
  be/src/exec/olap_scan_node.cpp
Labels: approved, area/sql/execution, branch-0.13, kind/bug

#4221 Add approx count distinct function
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/getting-started/hit-the-rollup.md
  docs/en/sql-reference/sql-functions/aggregate-functions/approx_count_distinct.md
  docs/en/sql-reference/sql-statements/Data Definition/HLL.md
  docs/zh-CN/getting-started/hit-the-rollup.md
  docs/zh-CN/sql-reference/sql-functions/aggregate-functions/approx_count_distinct.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/HLL.md
  fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionSet.java
Labels: approved, area/statement, branch-0.13, kind/bug

#4225 Config netty param in HttpServer
  docs/en/administrator-guide/config/fe_config.md
  docs/zh-CN/administrator-guide/config/fe_config.md
  fe/fe-core/src/main/java/org/apache/doris/PaloFe.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/http/HttpServer.java
Labels: approved, branch-0.13

#4127 [Bug][DynamicPartition]Fix bug that Modify a dynamic partition property in a non-dynamic partition table will throw a Exception
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/DynamicPartitionUtil.java
  fe/fe-core/src/test/java/org/apache/doris/alter/AlterTest.java
  fe/fe-core/src/test/java/org/apache/doris/alter/SchemaChangeJobV2Test.java
Labels: approved, area/catalog, branch-0.13

#4211 Fix multi predicate in correlation subquery analyze fail
  fe/fe-core/src/main/java/org/apache/doris/analysis/StmtRewriter.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/SelectStmtTest.java
Labels: approved, area/statement, branch-0.13, kind/bug

#4231 [ColocateJoin] ColocateJoin support table join itself (#4230)
  fe/fe-core/src/main/java/org/apache/doris/planner/DistributedPlanner.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: approved, area/colocated, branch-0.13, kind/feature

#4228 fix decimal delete error
  be/src/olap/tablet_meta.cpp
Labels: approved, branch-0.13, kind/bug

#4217 [Bug][Load][Json] #4124 Load json format with stream load failed
  be/src/common/config.h
  be/src/exec/base_scanner.cpp
  be/src/exec/base_scanner.h
  be/src/exec/broker_scanner.cpp
  be/src/exec/json_scanner.cpp
  be/src/exec/orc_scanner.cpp
  be/src/exec/parquet_scanner.cpp
  be/src/http/action/stream_load.cpp
  be/src/runtime/stream_load/stream_load_pipe.h
  docs/en/administrator-guide/config/be_config.md
  docs/en/administrator-guide/load-data/load-json-format.md
  docs/zh-CN/administrator-guide/config/be_config.md
  docs/zh-CN/administrator-guide/load-data/load-json-format.md
Labels: approved, area/load, branch-0.13, kind/bug

#4243 [Bug] fix after making MemTracker shared
  be/src/util/arrow/row_batch.h
  be/test/runtime/CMakeLists.txt
  be/test/runtime/load_channel_mgr_test.cpp
Labels: approved, area/test, branch-0.13, kind/bug

#4237 [BUG] Using attachement strategy of brpc to send packet with big size.
  be/src/runtime/data_stream_sender.cpp
  be/src/service/brpc.h
  be/src/service/internal_service.cpp
Labels: approved, kind/bug

#4133 generate jave files using maven
  build.sh
  docs/.vuepress/public/images/DEBUG1.png
  docs/.vuepress/public/images/DEBUG2.png
  docs/.vuepress/public/images/DEBUG3.png
  docs/.vuepress/public/images/gen_code.png
  docs/en/developer-guide/fe-eclipse-dev.md
  docs/zh-CN/developer-guide/fe-eclipse-dev.md
  docs/zh-CN/developer-guide/fe-idea-dev.md
  fe/fe-core/pom.xml
  gensrc/script/Makefile
  gensrc/script/gen_build_version.sh
  gensrc/script/gen_builtins_functions.py
  gensrc/thrift/Makefile
Labels: approved, branch-0.13, kind/enhancement

#4250 doc: fix format in doris_storage_optimization.md
  docs/en/internal/doris_storage_optimization.md
Labels: approved, good first issue, kind/cleanup, kind/documentation

#4244 [BUG] fix meta version check bug
  fe/fe-core/src/main/java/org/apache/doris/persist/EditLog.java
Labels: approved, branch-0.13

#4236 Analyze define expr before replay Rollup job
  fe/fe-core/src/main/java/org/apache/doris/alter/RollupJobV2.java
  fe/fe-core/src/test/java/org/apache/doris/alter/RollupJobV2Test.java
Labels: approved, area/materialized-view, branch-0.13, kind/bug

#4267 Revert "[BUG] Using attachement strategy of brpc to send packet with big size."
  be/src/runtime/data_stream_sender.cpp
  be/src/service/brpc.h
  be/src/service/internal_service.cpp
Labels: approved

#4269 Fix daily core
  fe/fe-core/src/main/java/org/apache/doris/analysis/MVColumnItem.java
Labels: kind/bug, kind/revert

#4158 [RoutineLoad] Support modify routine load job
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/administrator-guide/load-data/routine-load-manual.md
  docs/en/sql-reference/sql-statements/Data Manipulation/alter-routine-load.md
  docs/zh-CN/administrator-guide/load-data/routine-load-manual.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/alter-routine-load.md
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/AlterRoutineLoadStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateRoutineLoadStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/RoutineLoadDataSourceProperties.java
  fe/fe-core/src/main/java/org/apache/doris/journal/JournalEntity.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/KafkaProgress.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/KafkaRoutineLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadManager.java
  fe/fe-core/src/main/java/org/apache/doris/persist/AlterRoutineLoadJobOperationLog.java
  fe/fe-core/src/main/java/org/apache/doris/persist/EditLog.java
  fe/fe-core/src/main/java/org/apache/doris/persist/OperationType.java
  fe/fe-core/src/main/java/org/apache/doris/persist/gson/GsonUtils.java
  fe/fe-core/src/main/java/org/apache/doris/qe/DdlExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/AlterRoutineLoadStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/routineload/RoutineLoadManagerTest.java
  fe/fe-core/src/test/java/org/apache/doris/persist/AlterRoutineLoadOperationLogTest.java
  run-fe-ut.sh
Labels: approved, area/load, kind/feature

#4259 [BUG] Fix calculation of cumulative point
  be/src/olap/tablet.cpp
Labels: approved, area/compact, branch-0.13, kind/bug

#4239 Support approx_count_distinct rewrite to hll union in mv rewriter
  fe/fe-core/src/main/java/org/apache/doris/rewrite/mvrewrite/NDVToHll.java
  fe/fe-core/src/test/java/org/apache/doris/planner/MaterializedViewFunctionTest.java
Labels: approved, area/materialized-view, branch-0.13, kind/enhancement

#4229 [Docs] Add Materialized view manual
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/administrator-guide/materialized_view.md
  docs/zh-CN/administrator-guide/materialized_view.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/CREATE MATERIALIZED VIEW.md
Labels: approved, area/materialized-view, branch-0.13, kind/documentation

#4006 [Feature] Support InPredicate in delete statement
  be/src/olap/delete_handler.cpp
  be/src/olap/delete_handler.h
  be/src/olap/olap_cond.cpp
  be/src/olap/olap_cond.h
  be/src/olap/tablet_meta.cpp
  be/src/olap/wrapper_field.cpp
  be/src/olap/wrapper_field.h
  be/test/olap/delete_handler_test.cpp
  docs/en/administrator-guide/config/fe_config.md
  docs/en/administrator-guide/variables.md
  docs/en/sql-reference/sql-statements/Data Manipulation/DELETE.md
  docs/zh-CN/administrator-guide/config/fe_config.md
  docs/zh-CN/administrator-guide/variables.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/DELETE.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/DeleteStmt.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/load/DeleteHandler.java
  fe/fe-core/src/main/java/org/apache/doris/task/PushTask.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/DeleteStmtTest.java
  gensrc/proto/olap_file.proto
Labels: approved, area/delete, branch-0.13, kind/feature

#4272 Change the type of slot when mv is selected
  fe/fe-core/src/main/java/org/apache/doris/analysis/AggregateInfo.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/MaterializedIndexMeta.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/Planner.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
Labels: approved, area/materialized-view, branch-0.13, kind/bug

#4275 Fix cancel query bug
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
Labels: approved, kind/bug

#4249 Fix spelling error
  be/src/runtime/buffered_block_mgr2.cc
Labels: approved, branch-0.13

#4282 Fix be crash caused by decimal to date
  be/src/exprs/decimalv2_operators.cpp
  be/src/exprs/decimalv2_operators.h
Labels: approved, area/sql/execution, branch-0.13, kind/bug

#4289 [Bug][ColocateJoin] Fix bug of #4287 and #4285 of Colocatejoin
  fe/fe-core/src/main/java/org/apache/doris/planner/DistributedPlanner.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: approved, area/sql/execution, branch-0.13, kind/bug

#4297 doc: Update compilation.md
  docs/en/installing/compilation.md
  docs/zh-CN/installing/compilation.md
Labels: approved, area/build

#4298 Remove palo::PInternalService_Stub in BE code
  be/src/exec/tablet_sink.h
  be/src/runtime/data_stream_sender.cpp
  be/src/util/brpc_stub_cache.h
Labels: approved, area/rpc, kind/enhancement

#4235 Fix window function with limit zero bug 2
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: approved, area/sql/planner, branch-0.13, kind/bug

#4257 secure singleton mode
  fe/fe-core/src/main/java/org/apache/doris/service/ExecuteEnv.java
  fe/fe-core/src/test/java/org/apache/doris/service/ExecuteEnvTest.java
Labels: approved, kind/feature

#4248 [Feature][Cache] Cache proxy and coordinator #2581
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/Cache.java
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/CacheBeProxy.java
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/CacheCoordinator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/CacheProxy.java
  gensrc/proto/internal_service.proto
Labels: approved, area/sql/cache, kind/feature

#4318 [BUG] Fix TabletSinkTest unit test
  be/test/exec/tablet_sink_test.cpp
Labels: kind/bug

#4296 build: replace deprecated orc source in 0.12
  thirdparty/vars.sh
Labels: approved, area/build, kind/feature

#4293 Fix duplicate table export fail
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
Labels: approved, branch-0.13, kind/bug

#4245 Do not wrap NULL type expr to IF(TupleIsNull(tids), NULL, expr)
  fe/fe-core/src/main/java/org/apache/doris/analysis/CastExpr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/TupleIsNullPredicate.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/SelectStmtTest.java
Labels: approved, area/sql, area/sql/planner

#4266 [UnitTest] Refactor BE unit test script
  .github/PULL_REQUEST_TEMPLATE.md
  be/test/agent/CMakeLists.txt
  be/test/env/env_posix_test.cpp
  be/test/exprs/CMakeLists.txt
  be/test/olap/CMakeLists.txt
  run-be-ut.sh
  run-ut.sh
Labels: approved, area/build, area/test

#4294 [BUG] Fix NPE when distinct in predicate push down
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: approved, area/sql/planner, branch-0.13, kind/bug

#4300 [Doris On ES][Bug-Fix] Resolve NullPointerException when multi fields with `text` type
  fe/fe-core/src/main/java/org/apache/doris/external/elasticsearch/MappingPhase.java
  fe/fe-core/src/test/java/org/apache/doris/external/elasticsearch/MappingPhaseTest.java
  fe/fe-core/src/test/resources/data/es/test_index_mapping_field_mult_analyzer.json
Labels: approved, area/doris-on-es, kind/bug

#4306 [BugFix][ColocateJoin] Fix bug of issue 4305
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
Labels: kind/bug

#4268 [Feature][Web] Add new feature to list all tablets on a particular BE
  be/src/http/CMakeLists.txt
  be/src/http/action/tablets_info_action.cpp
  be/src/http/action/tablets_info_action.h
  be/src/http/default_path_handlers.cpp
  be/src/olap/tablet_manager.cpp
  be/src/olap/tablet_manager.h
  be/src/service/http_service.cpp
  docs/en/administrator-guide/http-actions/get-tablets.md
  docs/zh-CN/administrator-guide/http-actions/get-tablets.md
  webroot/be/tablets_page.mustache
Labels: approved, area/be/frontpage, kind/feature

#4317 Forbidden no grouping mv on aggregation table
  fe/fe-core/src/main/java/org/apache/doris/alter/MaterializedViewHandler.java
  fe/fe-core/src/test/java/org/apache/doris/alter/MaterializedViewHandlerTest.java
Labels: approved, area/materialized-view, branch-0.13, kind/bug

#4326 [BUG] Fix abs function cannot handle bigint or bigger data type
  be/src/exprs/math_functions.cpp
  be/src/exprs/math_functions.h
  be/test/exprs/CMakeLists.txt
  be/test/exprs/math_functions_test.cpp
  be/test/olap/push_handler_test.cpp
  gensrc/script/doris_builtins_functions.py
Labels: approved, kind/bug

#4291 [Bug fix]fix query id assign bug
  fe/fe-core/src/main/java/org/apache/doris/analysis/InsertStmt.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
Labels: approved, kind/bug

#4304 (#4303)remove unncessary convert from dataframe to rdd
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/SparkDpp.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/SparkRDDAggregator.java
Labels: approved, area/spark-load, branch-0.13, kind/enhancement

#4321 Add LargeInt cast to Date and Datatime, add timezone to stale_version_path_json_doc
  be/src/exprs/cast_functions.cpp
  be/src/exprs/cast_functions.h
  be/src/olap/version_graph.cpp
  be/test/olap/timestamped_version_tracker_test.cpp
Labels: approved, branch-0.13, kind/bug, kind/enhancement

#4332 support datagrip show database information
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/InformationFunction.java
Labels: approved, area/mysql-compatibility, kind/feature

#4337 [Doc][Json Load] Improve json data format load documents
  docs/en/administrator-guide/load-data/load-json-format.md
  docs/zh-CN/administrator-guide/load-data/load-json-format.md
Labels: approved, area/load, kind/documentation

#4339 Fix routine load timezone property invalid
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadJob.java
Labels: approved, area/load, branch-0.13, kind/bug

#4312 Manually trigger compaction restapi interface
  be/src/common/config.h
  be/src/http/action/compaction_action.cpp
  be/src/http/action/compaction_action.h
  be/src/olap/olap_server.cpp
  be/src/service/http_service.cpp
  docs/en/administrator-guide/config/be_config.md
  docs/en/administrator-guide/http-actions/compaction-action.md
  docs/zh-CN/administrator-guide/config/be_config.md
  docs/zh-CN/administrator-guide/http-actions/compaction-action.md
Labels: api-review, area/compact, branch-0.13, kind/feature

#4343 Forbidden aggregated partition key column on mv
  fe/fe-core/src/main/java/org/apache/doris/alter/MaterializedViewHandler.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateMaterializedViewStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/MVColumnItem.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/test/java/org/apache/doris/alter/MaterializedViewHandlerTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/MaterializedViewFunctionTest.java
Labels: approved, area/materialized-view, kind/bug

#4365 support collate field option in compare predicate sql from datagrip
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/test/java/org/apache/doris/analysis/SelectStmtTest.java
Labels: approved, area/mysql-compatibility

#4350 [Bug]Fix bug that BE crash when load ORC file
  be/src/exec/orc_scanner.cpp
  be/src/exec/orc_scanner.h
Labels: approved, branch-0.13, kind/bug

#4357 MOD: modify the document error
  docs/en/sql-reference/sql-statements/Data Definition/CREATE TABLE.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/CREATE TABLE.md
Labels: approved, branch-0.13, kind/documentation

#4369 [BUG] Fix except wrong answer bug
  be/src/exec/except_node.cpp
Labels: kind/bug

#4352 [Doris On ES][Bug-Fix] ES queries always route at same 3 BE nodes (#4351)
  fe/fe-core/src/main/java/org/apache/doris/planner/EsScanNode.java
Labels: approved, area/doris-on-es, kind/bug

#4255 [Tablet][Recovery] Support using empty tablet to repair the damaged or missing tablet
  be/src/agent/task_worker_pool.cpp
  be/src/agent/task_worker_pool.h
  be/src/common/config.h
  be/src/olap/storage_engine.cpp
  be/src/olap/storage_engine.h
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
  docs/.vuepress/sidebar/en.js
  docs/en/administrator-guide/config/fe_config.md
  docs/en/administrator-guide/operation/tablet-restore-tool.md
  docs/zh-CN/administrator-guide/config/fe_config.md
  docs/zh-CN/administrator-guide/operation/tablet-restore-tool.md
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/load/TabletLoadInfo.java
  fe/fe-core/src/main/java/org/apache/doris/master/MasterImpl.java
  fe/fe-core/src/main/java/org/apache/doris/master/ReportHandler.java
  fe/fe-core/src/main/java/org/apache/doris/persist/BackendTabletsInfo.java
  fe/fe-core/src/main/java/org/apache/doris/persist/ReplicaPersistInfo.java
  fe/fe-core/src/main/java/org/apache/doris/task/AgentBatchTask.java
  fe/fe-core/src/main/java/org/apache/doris/task/CreateReplicaTask.java
  fe/fe-core/src/main/java/org/apache/doris/task/RecoverTabletTask.java
  gensrc/thrift/Types.thrift
Labels: approved, area/catalog, kind/enhancement

#4234 Update support batch delete storage design document
  docs/en/internal/doris_storage_optimization.md
  docs/zh-CN/internal/doris_storage_optimization.md
Labels: approved, area/delete, kind/documentation

#4324 [Bug] Fix bug that modification of global variable can not be persisted.
  fe/fe-core/src/main/java/org/apache/doris/analysis/SetVar.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/common/FeMetaVersion.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/TimeUtils.java
  fe/fe-core/src/main/java/org/apache/doris/journal/JournalEntity.java
  fe/fe-core/src/main/java/org/apache/doris/persist/EditLog.java
  fe/fe-core/src/main/java/org/apache/doris/persist/GlobalVarPersistInfo.java
  fe/fe-core/src/main/java/org/apache/doris/persist/OperationType.java
  fe/fe-core/src/main/java/org/apache/doris/qe/GlobalVariable.java
  fe/fe-core/src/main/java/org/apache/doris/qe/VariableMgr.java
  fe/fe-core/src/test/java/org/apache/doris/persist/GlobalVarPersistInfoTest.java
  fe/fe-core/src/test/java/org/apache/doris/qe/VariableMgrTest.java
Labels: approved, kind/bug, kind/meta-version-change

#4345 [Bug][MemTracker] Cleanup the mem tracker's constructor to avoid wrong usage
  be/src/exec/parquet_scanner.cpp
  be/src/exec/parquet_scanner.h
  be/src/olap/push_handler.cpp
  be/src/olap/push_handler.h
  be/src/runtime/mem_tracker.cpp
  be/src/runtime/mem_tracker.h
Labels: approved, area/spark-load, branch-0.13, kind/bug

#4327 [Metrics] Support tablet level metrics
  be/src/exec/olap_scanner.cpp
  be/src/http/action/metrics_action.cpp
  be/src/http/action/stream_load.cpp
  be/src/olap/base_tablet.cpp
  be/src/olap/base_tablet.h
  be/src/olap/data_dir.cpp
  be/src/olap/delta_writer.cpp
  be/src/olap/memtable_flush_executor.h
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
  be/src/util/metrics.cpp
  be/src/util/metrics.h
  be/test/util/new_metrics_test.cpp
  docs/en/administrator-guide/operation/monitor-metrics/be-metrics.md
  docs/zh-CN/administrator-guide/operation/monitor-metrics/be-metrics.md
Labels: approved, area/metrics

#4212 Compaction rules optimization
  be/src/common/config.h
  be/src/olap/CMakeLists.txt
  be/src/olap/cumulative_compaction.cpp
  be/src/olap/cumulative_compaction.h
  be/src/olap/cumulative_compaction_policy.cpp
  be/src/olap/cumulative_compaction_policy.h
  be/src/olap/olap_server.cpp
  be/src/olap/rowset/rowset_meta.h
  be/src/olap/storage_engine.h
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
  be/src/olap/version_graph.cpp
  be/test/olap/cumulative_compaction_policy_test.cpp
  docs/en/administrator-guide/config/be_config.md
  docs/zh-CN/administrator-guide/config/be_config.md
Labels: area/compact, branch-0.13, kind/enhancement

#4198 Add bitmap longitudinal cutting udaf
  contrib/udf/CMakeLists.txt
  contrib/udf/src/udaf_orthogonal_bitmap/CMakeLists.txt
  contrib/udf/src/udaf_orthogonal_bitmap/bitmap_value.h
  contrib/udf/src/udaf_orthogonal_bitmap/orthogonal_bitmap_function.cpp
  contrib/udf/src/udaf_orthogonal_bitmap/orthogonal_bitmap_function.h
  contrib/udf/src/udaf_orthogonal_bitmap/string_value.h
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/extending-doris/udf/contrib/udaf-orthogonal-bitmap-manual.md
  docs/zh-CN/extending-doris/udf/contrib/udaf-orthogonal-bitmap-manual.md
Labels: approved, area/udf

#4392 [Bug] Remove RECOVER_TABLET worker pool to make ASAN compile happy
  be/src/agent/agent_server.cpp
Labels: kind/bug

#4397 Revert "[Metrics] Support tablet level metrics (#4327)"
  be/src/exec/olap_scanner.cpp
  be/src/http/action/metrics_action.cpp
  be/src/http/action/stream_load.cpp
  be/src/olap/base_tablet.cpp
  be/src/olap/base_tablet.h
  be/src/olap/data_dir.cpp
  be/src/olap/delta_writer.cpp
  be/src/olap/memtable_flush_executor.h
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
  be/src/util/metrics.cpp
  be/src/util/metrics.h
  be/test/util/new_metrics_test.cpp
  docs/en/administrator-guide/operation/monitor-metrics/be-metrics.md
  docs/zh-CN/administrator-guide/operation/monitor-metrics/be-metrics.md
Labels: kind/revert

#4347 udf: replace function
  be/src/exprs/string_functions.cpp
  be/src/exprs/string_functions.h
  be/test/exprs/string_functions_test.cpp
  docs/en/sql-reference/sql-functions/string-functions/replace.md
  docs/zh-CN/sql-reference/sql-functions/string-functions/replace.md
  fe/fe-core/src/main/cup/sql_parser.cup
  gensrc/script/doris_builtins_functions.py
Labels: approved, area/sql/function, kind/feature

#4366 Optimise coding bit operation in BE
  be/src/util/coding.h
Labels: approved, area/util

#4379 [JsonLoad] Fix bug that row num stat is not correct when loading json
  be/src/exec/json_scanner.cpp
Labels: approved, area/load, branch-0.13, kind/bug

#4382 Modify mv rewrite rule on 'Count distinct'
  fe/fe-core/src/main/java/org/apache/doris/rewrite/mvrewrite/CountFieldToSum.java
  fe/fe-core/src/test/java/org/apache/doris/rewrite/mvrewrite/CountFieldToSumTest.java
Labels: approved, area/materialized-view, branch-0.13, kind/bug

#4391 [Doc] increase mailing list subscription method.
  README.md
Labels: approved, good first issue, kind/documentation

#4395 Fix spelling errors in dynamic partition docs
  docs/en/administrator-guide/dynamic-partition.md
  docs/zh-CN/administrator-guide/dynamic-partition.md
Labels: approved, kind/documentation

#4407 Fix mispelling
  docs/en/installing/install-deploy.md
Labels: approved, good first issue, kind/documentation

#4375 Fix errors when alter materialized view which based on dup table
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/test/java/org/apache/doris/alter/SchemaChangeHandlerTest.java
Labels: approved, area/materialized-view, branch-0.13, kind/bug

#4406 [UT][Bug-Fix] Resolve UT memory leak problem
  be/src/olap/cumulative_compaction.cpp
  be/src/olap/cumulative_compaction_policy.cpp
  be/src/olap/cumulative_compaction_policy.h
  be/src/olap/tablet.cpp
  be/test/olap/CMakeLists.txt
  be/test/olap/cumulative_compaction_policy_test.cpp
  be/test/olap/tablet_test.cpp
Labels: approved, area/test

#4408 Input correct keys type of index meta when `Add Partition`
  fe/fe-core/src/main/java/org/apache/doris/analysis/CastExpr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateMaterializedViewStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Column.java
Labels: approved, area/materialized-view, branch-0.13, kind/bug

#4387 [SegmentV2] Change the default storage format to SegmentV2
  be/src/olap/delta_writer.cpp
  be/src/olap/push_handler.cpp
  be/src/olap/schema_change.cpp
  be/src/olap/tablet_meta.cpp
  docs/en/administrator-guide/alter-table/alter-table-bitmap-index.md
  docs/zh-CN/administrator-guide/alter-table/alter-table-bitmap-index.md
  docs/zh-CN/administrator-guide/segment-v2-usage.md
  fe/fe-core/src/main/java/org/apache/doris/alter/MaterializedViewHandler.java
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/PropertyAnalyzer.java
  fe/fe-core/src/test/java/org/apache/doris/alter/AlterJobV2Test.java
Labels: approved, area/storage, branch-0.13, kind/api-change, kind/bug

#4371 [License] Organize and modify the license of the code
  .rat-excludes
  DISCLAIMER-WIP
  LICENSE.txt
  be/CMakeLists.txt
  be/src/http/action/tablets_info_action.cpp
  be/src/http/default_path_handlers.cpp
  be/src/http/web_page_handler.cpp
  be/test/olap/timestamped_version_tracker_test.cpp
  build.sh
  docs/en/README.md
  docs/en/downloads/downloads.md
  docs/en/installing/compilation.md
  docs/zh-CN/README.md
  docs/zh-CN/installing/compilation.md
  fe/fe-core/src/main/java/org/apache/doris/http/action/StaticResourceAction.java
  fe/fe-core/src/main/java/org/apache/doris/http/action/WebBaseAction.java
  fe/fe-core/src/test/java/org/apache/doris/load/DeleteHandlerTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/SparkRepositoryTest.java
  fe/fe-core/src/test/java/org/apache/doris/persist/BatchModifyPartitionsInfoTest.java
  fe_plugins/auditloader/src/main/assembly/plugin.conf
  fs_brokers/apache_hdfs_broker/conf/log4j.properties
  thirdparty/build-thirdparty.sh
  thirdparty/vars.sh
  tools/row_to_column/README
  tools/row_to_column/README.md
  tools/row_to_column/conf
  tools/show_segment_status/conf
  webroot/be/bootstrap/css/bootstrap-table.min.css
  webroot/be/bootstrap/css/bootstrap.min.css
  webroot/be/bootstrap/fonts/glyphicons-halflings-regular.woff
  webroot/be/bootstrap/js/bootstrap-table.min.js
  webroot/be/bootstrap/js/bootstrap.min.js
  webroot/be/d3.v2.js
  webroot/be/epoch.0.5.2.min.css
  webroot/be/epoch.0.5.2.min.js
  webroot/be/jquery-3.2.1.min.js
  webroot/static/bootstrap-theme.css
  webroot/static/bootstrap-theme.css.map
  webroot/static/bootstrap.css
  webroot/static/bootstrap.css.map
  webroot/static/datatables_bootstrap.css
  webroot/static/datatables_bootstrap.js
  webroot/static/glyphicons-halflings-regular.eot
  webroot/static/glyphicons-halflings-regular.svg
  webroot/static/glyphicons-halflings-regular.ttf
  webroot/static/glyphicons-halflings-regular.woff
  webroot/static/glyphicons-halflings-regular.woff2
  webroot/static/jquery.dataTables.js
  webroot/static/jquery.js
Labels: area/community, kind/license

#4404 [Doc] Add in predicate support content in delete-manual.md
  docs/en/administrator-guide/load-data/delete-manual.md
  docs/zh-CN/administrator-guide/load-data/delete-manual.md
Labels: approved, branch-0.13, kind/documentation

#4425 Support batch delete[part 2]
  be/src/olap/reader.cpp
  be/src/olap/reader.h
  be/src/olap/row_cursor.h
Labels: approved

#4424 Fix explicit broadcast join bug
  fe/fe-core/src/main/java/org/apache/doris/planner/DistributedPlanner.java
  fe/fe-core/src/test/java/org/apache/doris/planner/DistributedPlannerTest.java
Labels: approved, area/sql/planner

#4201 Rewrite count(distinct if(bool, bitmap, null)) to bitmap_union_count
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
  gensrc/script/doris_builtins_functions.py
Labels: approved, area/sql, kind/bug

#4279 FixTupleIsNull miss in SelectStmt resultExpr
  fe/fe-core/src/main/java/org/apache/doris/planner/Planner.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
Labels: approved, area/sql/planner, branch-0.13, kind/bug

#4373 [Optimize]Optimize the disk selection strategy on BE for tablet creation
  be/src/olap/data_dir.h
  be/src/olap/storage_engine.cpp
Labels: approved, kind/enhancement

#4362 [MySQL Compatibility 2/4][Bug] Fix bug and improve compatibility with mysql protocol
  fe/fe-core/src/main/java/org/apache/doris/analysis/InformationFunction.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/MysqlProto.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/UtFrameUtils.java
Labels: approved, area/mysql-compatibility, kind/api-change, kind/bug

#4393 FIX: fix dynamic partition replicationNum error
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/DynamicPartitionProperty.java
Labels: approved, kind/bug

#4410 [Storage] "align_tag_path" and ALIGN_TAG_PREFIX is needless
  be/src/olap/data_dir.cpp
  be/src/olap/olap_define.h
Labels: approved

#4416 [Doc] Fix typo about plugin content
  docs/.vuepress/sidebar/en.js
  docs/en/sql-reference/sql-statements/Administration/UNINTALL PLUGIN.md
  docs/zh-CN/sql-reference/sql-statements/Administration/UNINSTALL PLUGIN.md
Labels: approved, branch-0.13, kind/documentation

#4432 Forbidden the illegal column types on BITMAP_UNION OR HLL_UNION mv
  be/src/exec/union_node.cpp
  be/src/exec/union_node.h
  be/src/exec/union_node_ir.cpp
  docs/en/administrator-guide/materialized_view.md
  docs/zh-CN/administrator-guide/materialized_view.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/MVColumnBitmapUnionPattern.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/MVColumnHLLUnionPattern.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/MVColumnBitmapUnionPatternTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/MVColumnHLLUnionPatternTest.java
Labels: approved, area/materialized-view, branch-0.13, kind/bug

#4436 Keep the scale and precision of type when creating mv
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateMaterializedViewStmt.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/CreateMaterializedViewStmtTest.java
Labels: approved, area/materialized-view, branch-0.13, kind/bug

#4442 Template nest convert to c++11 syntax and style
  be/src/exec/analytic_eval_node.cpp
  be/src/exec/analytic_eval_node.h
  be/src/exec/es_scan_node.cpp
  be/src/exec/merge_node.cpp
  be/src/exec/merge_node.h
  be/src/exec/olap_common.h
  be/src/exec/olap_scan_node.h
  be/src/exec/topn_node.h
  be/src/exprs/json_functions.cpp
  be/src/gutil/gscoped_ptr.h
  be/src/gutil/hash/hash.h
  be/src/gutil/ref_counted.h
  be/src/gutil/stl_util.h
  be/src/gutil/strings/join.cc
  be/src/gutil/strings/join.h
  be/src/gutil/strings/split.cc
  be/src/gutil/strings/split.h
  be/src/gutil/strings/split_internal.h
  be/src/gutil/type_traits.h
  be/src/olap/rowset/segment_group.cpp
  be/src/olap/rowset/segment_group.h
  be/src/runtime/buffered_block_mgr2.h
  be/src/runtime/buffered_tuple_stream2.h
  be/src/runtime/client_cache.h
  be/src/runtime/data_stream_mgr.h
  be/src/runtime/data_stream_recvr.cc
  be/src/runtime/disk_io_mgr.h
  be/src/runtime/plan_fragment_executor.h
  be/src/runtime/result_buffer_mgr.cpp
  be/src/runtime/result_buffer_mgr.h
  be/src/runtime/spill_sorter.cc
  be/src/runtime/test_env.h
  be/src/util/perf_counters.h
  be/src/util/runtime_profile.h
  be/src/util/thrift_server.h
  be/test/olap/rowset/segment_v2/bitshuffle_page_test.cpp
  be/test/olap/rowset/segment_v2/frame_of_reference_page_test.cpp
  be/test/olap/rowset/segment_v2/plain_page_test.cpp
  be/test/olap/rowset/segment_v2/rle_page_test.cpp
  be/test/runtime/buffered_block_mgr2_test.cpp
  be/test/util/blocking_queue_test.cpp
  be/test/util/internal_queue_test.cpp
Labels: approved, kind/refactor

#4446 Show column display name on `Show Proc` stmt
  fe/fe-core/src/main/java/org/apache/doris/common/proc/IndexSchemaProcNode.java
  fe/fe-core/src/main/java/org/apache/doris/http/rest/TableSchemaAction.java
  fe/fe-core/src/test/java/org/apache/doris/common/proc/IndexSchemaProcNodeTest.java
Labels: approved, area/catalog, area/materialized-view, branch-0.13

#4448 Fix core issue of 4447 and change declare order for compatibility
  be/src/exec/broker_scan_node.cpp
  be/src/exec/json_scanner.cpp
  be/src/runtime/plan_fragment_executor.cpp
  gensrc/thrift/PlanNodes.thrift
  gensrc/thrift/Types.thrift
Labels: approved, kind/bug

#4348 [Profile] Add 2 Segment related metrics in query profile
  be/src/exec/olap_scan_node.cpp
  be/src/exec/olap_scan_node.h
  be/src/exec/olap_scanner.cpp
  be/src/olap/olap_common.h
  be/src/olap/rowset/segment_v2/segment.cpp
  docs/en/administrator-guide/running-profile.md
  docs/zh-CN/administrator-guide/running-profile.md
Labels: approved, area/profile

#4364 [Mysql Compatibility 3/4] Support convert() and signed/unsigned interger cast
  be/src/exec/schema_scanner/schema_columns_scanner.cpp
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/catalog/SchemaTable.java
  fe/fe-core/src/main/jflex/sql_scanner.flex
Labels: approved, area/mysql-compatibility

#4383 [SparkLoad]Use the yarn command to get status and kill the application
  fe/fe-core/src/main/java/org/apache/doris/catalog/SparkResource.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/ConfigFile.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkEtlJobHandler.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkLauncherMonitor.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkLoadAppHandle.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkPendingTaskAttachment.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkRepository.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkYarnConfigFiles.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/YarnApplicationReport.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/SparkEtlJobHandlerTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/SparkLauncherMonitorTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/SparkLoadJobTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/SparkYarnConfigFilesTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/YarnApplicationReportTest.java
  fe/fe-core/src/test/resources/spark_launcher_monitor.log
Labels: approved, area/spark-load

#4401 [Bug-Fix] Some deleted tablets are not recycled on BE
  be/src/olap/data_dir.cpp
  be/src/olap/data_dir.h
  be/src/olap/olap_server.cpp
  be/src/olap/tablet_manager.cpp
  be/src/olap/tablet_manager.h
  be/src/olap/task/engine_clone_task.cpp
  be/src/olap/task/engine_clone_task.h
Labels: approved, area/storage, kind/bug

#4445 support StringLiteral try to cast BigInt
  fe/fe-core/src/main/java/org/apache/doris/analysis/BinaryPredicate.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Type.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/SelectStmtTest.java
Labels: SQL Improvement, approved, area/sql/planner

#4450 Fix mysql return bug
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
Labels: approved, kind/bug

#4388 Add OLAP_ERR_DATE_QUALITY_ERR error status to display schema change failure
  be/src/agent/task_worker_pool.cpp
  be/src/olap/olap_define.h
  be/src/olap/schema_change.cpp
  be/src/olap/schema_change.h
  be/test/olap/schema_change_test.cpp
  docs/en/administrator-guide/materialized_view.md
  docs/zh-CN/administrator-guide/materialized_view.md
  fe/fe-core/src/main/java/org/apache/doris/master/MasterImpl.java
Labels: area/materialized-view

#4461 [Bug] replace libltdl.so when compile the unixodbc library
  be/CMakeLists.txt
  thirdparty/build-thirdparty.sh
Labels: approved, area/dependency

#4464 [Spark load] Fix dpp and submit push task bugs
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkEtlJobHandler.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkLoadJob.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/SparkLoadJobTest.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/ColumnParser.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/SparkDpp.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/etl/EtlJobConfig.java
Labels: approved, area/spark-load, kind/bug

#4435 [DOCS] Add batch delete docs
  docs/en/administrator-guide/load-data/broker-load-manual.md
  docs/en/administrator-guide/load-data/routine-load-manual.md
  docs/en/administrator-guide/load-data/stream-load-manual.md
  docs/en/sql-reference/sql-statements/Data Definition/ALTER TABLE.md
  docs/en/sql-reference/sql-statements/Data Manipulation/BROKER LOAD.md
  docs/en/sql-reference/sql-statements/Data Manipulation/ROUTINE LOAD.md
  docs/en/sql-reference/sql-statements/Data Manipulation/STREAM LOAD.md
  docs/zh-CN/administrator-guide/load-data/broker-load-manual.md
  docs/zh-CN/administrator-guide/load-data/routine-load-manual.md
  docs/zh-CN/administrator-guide/load-data/stream-load-manual.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/ALTER TABLE.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/BROKER LOAD.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/ROUTINE LOAD.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/STREAM LOAD.md
Labels: approved, kind/documentation

#4471 [Colocation] Fix Colocation balance endless loop bug
  fe/fe-core/src/main/java/org/apache/doris/clone/ColocateTableBalancer.java
  fe/fe-core/src/test/java/org/apache/doris/clone/ColocateTableBalancerTest.java
Labels: approved, area/colocated, kind/bug

#4473 [bug] Fix a null pointer in PlanFragmentExecutor.
  be/src/runtime/plan_fragment_executor.cpp
Labels: approved, kind/bug

#4477 [Doc] Fix wrong doc name
  docs/en/sql-reference/sql-statements/Administration/UNINSTALL PLUGIN.md
Labels: area/build, kind/bug, kind/documentation

#4454 Persistence stale rowsets meta
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
  be/src/olap/tablet_meta.cpp
  be/src/olap/tablet_meta.h
  be/src/olap/version_graph.cpp
  be/src/olap/version_graph.h
  be/test/olap/timestamped_version_tracker_test.cpp
  gensrc/proto/olap_file.proto
Labels: approved, kind/enhancement

#4458 [Bug] Fix bug that memory copy may overflow in MemIndex::load_segment
  be/src/olap/olap_index.cpp
  be/src/olap/rowset/segment_group.cpp
Labels: approved, kind/bug

#4463 [Doc] Add spark load sql statement doc and update manual
  docs/.vuepress/sidebar/zh-CN.js
  docs/zh-CN/administrator-guide/load-data/spark-load-manual.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/SPARK LOAD.md
Labels: approved, area/spark-load, kind/documentation

#4466 Compaction show policy type and disk format
  be/src/olap/cumulative_compaction_policy.h
  be/src/olap/tablet.cpp
  docs/en/administrator-guide/http-actions/compaction-action.md
  docs/zh-CN/administrator-guide/http-actions/compaction-action.md
Labels: approved, kind/enhancement

#4470 [Spark Load] Redirect the spark launcher's log to a separated log file
  fe/fe-core/src/main/java/org/apache/doris/catalog/Type.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadManager.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkEtlJobHandler.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkLauncherMonitor.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkLoadAppHandle.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkLoadJob.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/SparkLauncherMonitorTest.java
Labels: approved, area/spark-load, kind/enhancement

#4485 [Doc] Update doc of fe-idea-dev.md
  docs/zh-CN/developer-guide/fe-idea-dev.md
Labels: kind/documentation

#4486 [Bug] Fix bug of load error hub and schema change
  be/src/olap/schema_change.cpp
  be/src/runtime/runtime_state.cpp
Labels: approved, kind/bug
