Repository apache/doris, pull requests merged in 2021-03, with the labels that each got.

#5433 Fix a typo ehco -> echo
  bin/start_be.sh
Labels: approved, area/build

#5411 [Doc] Modify dead link of doc
  docs/en/community/how-to-contribute.md
Labels: approved, kind/documentation

#5342 [Enhancement] Add warn log when client report be state failed and refactor some report code
  be/src/agent/task_worker_pool.cpp
  be/src/agent/task_worker_pool.h
  be/src/olap/tablet_manager.cpp
  be/src/olap/tablet_manager.h
Labels: approved, kind/refactor

#5183 [Audit] Support builtin load audit function to record successful bulk load job
  fe/fe-core/src/main/java/org/apache/doris/common/AuditLog.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BulkLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/plugin/AuditEvent.java
  fe/fe-core/src/main/java/org/apache/doris/plugin/LoadAuditEvent.java
  fe/fe-core/src/main/java/org/apache/doris/qe/AuditLogBuilder.java
Labels: approved, kind/feature

#5441 [Bug-Fix][Bitmap][Be] Resolve bitmap_not calculate wrong result(#5440)
  be/src/util/bitmap_value.h
  be/test/exprs/bitmap_function_test.cpp
Labels: approved, area/sql/function, kind/bug

#5336 [Spark-Doris-Connector][Bug-Fix] Resolve deserialize exception when Spark Doris Connector in aync deserialize mode
  extension/spark-doris-connector/src/main/scala/org/apache/doris/spark/rdd/ScalaValueReader.scala
Labels: approved, area/spark-connector

#5395 [Ut] Add drop meta unit test and remove some redundant code in Alter
  fe/fe-core/src/main/java/org/apache/doris/alter/Alter.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/DropDbTest.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/DropPartitionTest.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/DropTableTest.java
Labels: approved

#5449 [Ut] Fix be ut failed for topn_function_test
  be/test/exprs/topn_function_test.cpp
Labels: approved, area/test, kind/bug

#4479 [Apache][Doris]add query cache docs
  docs/en/administrator-guide/query_cache.md
  docs/zh-CN/administrator-guide/query_cache.md
Labels: approved, kind/documentation

#5379 [Config] Support config validating when BE bootstart and update BE's config by API
  be/src/common/config.h
  be/src/common/configbase.cpp
  be/src/common/configbase.h
  be/test/common/CMakeLists.txt
  be/test/common/config_test.cpp
  be/test/common/config_validator_test.cpp
  be/test/runtime/result_queue_mgr_test.cpp
  be/test/test_util/CMakeLists.txt
  be/test/test_util/test_util.cpp
  be/test/test_util/test_util.h
Labels: approved, kind/feature

#5407 [Bug] The toString() method in PartitionInfo class. Property information strings are concatenated together
  fe/fe-core/src/main/java/org/apache/doris/catalog/PartitionInfo.java
Labels: approved, kind/bug

#5419 Remove order by from `insert into select`
  fe/fe-core/src/main/java/org/apache/doris/analysis/QueryStmt.java
Labels: approved, area/load, kind/enhancement

#5422 [ODBC] Let the type conversion of the fail in query in ODBC of MySQL table to prompt the information of the column
  be/src/exec/mysql_scan_node.cpp
  be/src/exec/odbc_scan_node.cpp
  docs/en/extending-doris/odbc-of-doris.md
  docs/zh-CN/extending-doris/odbc-of-doris.md
Labels: approved

#5427 [Enhancement] Move FeMetaVersion back to fe-core to avoid invalid version upgrade (#5426)
  fe/fe-core/src/main/java/org/apache/doris/common/FeConstants.java
  fe/fe-core/src/main/java/org/apache/doris/common/FeMetaVersion.java
Labels: approved, kind/refactor

#5431 Fix #5430 set dest tuple to null when src_tuple is NULL
  be/src/exec/repeat_node.cpp
Labels: approved, kind/bug

#5444 [Rewrite]Rewrite from_unixtime to reduce calling this function
  fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/RewriteFromUnixTimeRule.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: approved, kind/enhancement

#5418 [Bug] Fix bug that the image cannot be pulled after the new fe nodes added
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/persist/StorageInfoV2.java
Labels: approved, area/catalog, kind/bug

#5457 [BUG] fix DECHECK Fail While Call UDF
  fe/fe-core/src/main/java/org/apache/doris/catalog/AggregateFunction.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/ScalarFunction.java
Labels: approved, area/udf

#5454 [Doc] fix page links
  docs/en/administrator-guide/colocation-join.md
  docs/en/administrator-guide/config/be_config.md
  docs/en/administrator-guide/load-data/delete-manual.md
  docs/en/administrator-guide/operation/metadata-operation.md
  docs/en/administrator-guide/operation/monitor-alert.md
  docs/en/administrator-guide/time-zone.md
  docs/en/administrator-guide/variables.md
  docs/en/community/how-to-contribute.md
  docs/en/community/pull-request.md
  docs/en/community/release-process.md
  docs/en/developer-guide/debug-tool.md
  docs/en/extending-doris/udf/contribute-udf.md
  docs/en/getting-started/data-model-rollup.md
  docs/en/getting-started/data-partition.md
  docs/en/installing/install-deploy.md
  docs/en/internal/metadata-design.md
  docs/zh-CN/administrator-guide/load-data/delete-manual.md
  docs/zh-CN/community/how-to-contribute.md
Labels: approved, kind/documentation

#5465 [Bug] Fix bug that BE failed to start when validating conf from be_custom.conf
  be/src/common/configbase.cpp
  be/src/common/configbase.h
Labels: kind/bug

#5481 Fix dlopen faild by upgrade cmake
  be/src/service/CMakeLists.txt
  be/src/tools/CMakeLists.txt
Labels: approved, area/build

#5473 [Bug] Fix bug that data lost when doing backup job
  fe/fe-core/src/main/java/org/apache/doris/backup/RestoreJob.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/DropPartitionTest.java
Labels: approved, area/backup, kind/bug

#5462 [Load] Support multi bytes LineDelimiter and ColumnSeparator
  be/CMakeLists.txt
  be/src/exec/broker_scanner.cpp
  be/src/exec/broker_scanner.h
  be/src/exec/plain_text_line_reader.cpp
  be/src/exec/plain_text_line_reader.h
  be/src/http/action/stream_load.cpp
  be/src/http/http_common.h
  be/test/exec/plain_text_line_reader_bzip_test.cpp
  be/test/exec/plain_text_line_reader_gzip_test.cpp
  be/test/exec/plain_text_line_reader_lz4frame_test.cpp
  be/test/exec/plain_text_line_reader_lzop_test.cpp
  be/test/exec/plain_text_line_reader_uncompressed_test.cpp
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateRoutineLoadStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/DataDescription.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/Separator.java
  fe/fe-core/src/main/java/org/apache/doris/load/BrokerFileGroup.java
  fe/fe-core/src/main/java/org/apache/doris/load/Load.java
  fe/fe-core/src/main/java/org/apache/doris/load/RoutineLoadDesc.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/planner/BrokerScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/StreamLoadScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/MultiLoadMgr.java
  fe/fe-core/src/main/java/org/apache/doris/task/LoadTaskInfo.java
  fe/fe-core/src/main/java/org/apache/doris/task/StreamLoadTask.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/CreateRoutineLoadStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/DataDescriptionTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/SeparatorTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/routineload/KafkaRoutineLoadJobTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/routineload/RoutineLoadManagerTest.java
  gensrc/thrift/FrontendService.thrift
  gensrc/thrift/PlanNodes.thrift
Labels: approved, kind/feature

#5459 [Bucket Shuffle Join] Support the some featrue of Bucket Shuffle Join
  docs/.vuepress/public/images/bucket_shuffle_join.png
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/administrator-guide/bucket-shuffle-join.md
  docs/en/administrator-guide/variables.md
  docs/zh-CN/administrator-guide/bucket-shuffle-join.md
  docs/zh-CN/administrator-guide/variables.md
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/planner/DistributedPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: approved, area/sql/planner, kind/enhancement

#5482 [Docs] fix a mistake in docs zh-CN installing
  docs/zh-CN/installing/install-deploy.md
Labels: approved, good first issue, kind/documentation

#5347 Fix bug that sql with limit query statistics are wrong
  be/src/runtime/query_statistics.cpp
  be/src/runtime/query_statistics.h
Labels: SQL Bug, area/sql/execution

#5484 [Bug] Fix create view faild when StringLiteral in SelectStmt contains single quotes
  fe/fe-core/src/main/java/org/apache/doris/analysis/StringLiteral.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/CreateViewTest.java
Labels: approved, kind/bug

#5478 [Bug] Fix thread safe problem when check whether olap table is stable
  fe/fe-core/src/main/java/org/apache/doris/alter/AlterJobV2.java
Labels: approved, kind/bug

#5494 [GitHub] Fix PR Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved

#5492 [DOCS] Add missing en doc Setting Up dev env for FE - IntelliJ IDEA
  docs/.vuepress/sidebar/en.js
  docs/en/developer-guide/fe-idea-dev.md
Labels: approved, kind/documentation

#5463 [Load]Support compressed csv file in stream load
  be/src/exec/broker_scanner.cpp
  be/src/http/action/stream_load.cpp
  be/src/http/http_common.h
  gensrc/thrift/PlanNodes.thrift
Labels: approved, kind/feature

#5445 [Export] Expand function of export stmt
  docs/en/administrator-guide/export-manual.md
  docs/en/sql-reference/sql-statements/Data Manipulation/EXPORT.md
  docs/zh-CN/administrator-guide/export-manual.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/EXPORT.md
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/BrokerDesc.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ExportStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/LoadStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/OutFileClause.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/StorageBackend.java
  fe/fe-core/src/main/java/org/apache/doris/common/FeMetaVersion.java
  fe/fe-core/src/main/java/org/apache/doris/load/ExportJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/ExportMgr.java
Labels: api-review, approved, area/backup, kind/enhancement

#5417 [Bug][Spark Load] Spark Repository throws an exception when user configures `spark_ resource_ path`
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkRepository.java
Labels: approved, area/spark-load

#5425 [Hll][Be][Bug-Fix] Resolve be crash when aggregate 160 hll items(#5424)
  be/src/olap/hll.cpp
Labels: approved

#5468 [Enhancement] Support Pallralel Merge In Exchange Node
  be/src/exec/exchange_node.cpp
  be/src/runtime/data_stream_recvr.cc
  be/src/runtime/data_stream_recvr.h
  be/src/runtime/load_channel_mgr.cpp
  be/src/runtime/runtime_state.h
  be/src/runtime/sorted_run_merger.cc
  be/src/runtime/sorted_run_merger.h
  docs/en/administrator-guide/running-profile.md
  docs/en/administrator-guide/variables.md
  docs/zh-CN/administrator-guide/running-profile.md
  docs/zh-CN/administrator-guide/variables.md
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  gensrc/thrift/PaloInternalService.thrift
Labels: approved, kind/enhancement

#5487 [Doc] correct format errors in English doc
  docs/README.md
  docs/en/administrator-guide/alter-table/alter-table-bitmap-index.md
  docs/en/administrator-guide/alter-table/alter-table-rollup.md
  docs/en/administrator-guide/alter-table/alter-table-schema-change.md
  docs/en/administrator-guide/broker.md
  docs/en/administrator-guide/colocation-join.md
  docs/en/administrator-guide/config/be_config.md
  docs/en/administrator-guide/http-actions/fe/get-log-file-action.md
  docs/en/administrator-guide/load-data/sequence-column-manual.md
  docs/en/administrator-guide/load-data/spark-load-manual.md
  docs/en/administrator-guide/operation/metadata-operation.md
  docs/en/administrator-guide/operation/tablet-meta-tool.md
  docs/en/administrator-guide/operation/tablet-repair-and-balance.md
  docs/en/administrator-guide/outfile.md
  docs/en/administrator-guide/query_cache.md
  docs/en/administrator-guide/resource-management.md
  docs/en/community/committer-guide.md
  docs/en/community/release-process.md
  docs/en/extending-doris/doris-on-es.md
  docs/en/extending-doris/odbc-of-doris.md
  docs/en/getting-started/best-practice.md
  docs/en/installing/upgrade.md
  docs/en/sql-reference/sql-statements/Account Management/SET PROPERTY.md
  docs/en/sql-reference/sql-statements/Administration/ADMIN SHOW CONFIG.md
  docs/en/sql-reference/sql-statements/Administration/SHOW FULL COLUMNS.md
  docs/en/sql-reference/sql-statements/Data Definition/CANCEL ALTER.md
  docs/en/sql-reference/sql-statements/Data Definition/CREATE REPOSITORY.md
  docs/en/sql-reference/sql-statements/Data Manipulation/SHOW CREATE FUNCTION.md
  docs/en/sql-reference/sql-statements/Data Manipulation/alter-routine-load.md
Labels: approved, kind/documentation

#5497 [Bug] Fix bug that the log message is wrong when ReportHandler can not find tablet meta from TabletInvertedIndex
  fe/fe-core/src/main/java/org/apache/doris/master/ReportHandler.java
Labels: approved

#5502 Fix compatibility of glibc
  be/src/glibc-compatibility/musl/__polevll.c
  be/src/glibc-compatibility/musl/accept4.c
  be/src/glibc-compatibility/musl/epoll.c
  be/src/glibc-compatibility/musl/getauxval.c
  be/src/glibc-compatibility/musl/lgammal.c
  be/src/glibc-compatibility/musl/mkstemps.c
  be/src/glibc-compatibility/musl/secure_env.c
  be/src/glibc-compatibility/musl/secure_getenv.c
  be/src/glibc-compatibility/musl/strsignal.c
  be/src/glibc-compatibility/musl/sync_file_range.c
  be/src/glibc-compatibility/musl/timerfd.c
Labels: approved, area/build

#5506 [Docs]Fix a typo
  docs/en/community/how-to-contribute.md
Labels: approved, kind/documentation

#5498 [Enhance] Sort directories by available space when do trash sweep
  be/src/olap/olap_common.h
  be/src/olap/storage_engine.cpp
  be/test/olap/CMakeLists.txt
  be/test/olap/common_test.cpp
Labels: approved, kind/enhancement

#5501 [UT] fix memory tracker ut
  be/test/runtime/CMakeLists.txt
  be/test/runtime/mem_limit_test.cpp
Labels: approved, area/test

#5391 (#5390)fix NPE when replay colocate group
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/ColocateTableIndex.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Database.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/InfoSchemaDb.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/TabletInvertedIndex.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/CreateTableTest.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/InfoSchemaDbTest.java
Labels: approved, area/catalog, kind/bug

#5504 [Bug] Fix the memory expand 10~1000x of compression algorithm
  be/src/olap/rowset/segment_v2/page_io.cpp
  docs/en/administrator-guide/bucket-shuffle-join.md
  docs/zh-CN/administrator-guide/bucket-shuffle-join.md
Labels: approved, area/storage, kind/bug, kind/enhancement

#5489 [Outfile] Support exporting query result to local disk
  be/src/runtime/file_result_writer.cpp
  be/src/runtime/file_result_writer.h
  be/src/runtime/result_sink.cpp
  be/src/runtime/result_writer.h
  docs/en/administrator-guide/outfile.md
  docs/zh-CN/administrator-guide/outfile.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/OutFileClause.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  gensrc/thrift/DataSinks.thrift
Labels: api-review, approved, kind/api-change, kind/feature

#5508 [build] support ccache while build BE
  build.sh
  env.sh
Labels: approved, area/build

#5511 [Profile] Add more timer for scan thread
  be/src/exec/olap_scan_node.cpp
  be/src/exec/olap_scan_node.h
  be/src/exec/olap_scanner.h
  docs/en/administrator-guide/running-profile.md
  docs/zh-CN/administrator-guide/running-profile.md
Labels: approved, area/profile

#5518 Use O_SYNC instead of O_DIRECT to be fs agnostic.
  be/src/olap/utils.cpp
Labels: approved, kind/enhancement

#5513 [Improve] Support set multi variables in SET_VAR
  docs/en/administrator-guide/variables.md
  docs/zh-CN/administrator-guide/variables.md
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContext.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: approved, kind/enhancement

#5527 [Bug] Fix bug that the stale rowset file will not be deleted
  be/src/olap/schema_change.cpp
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
  be/src/olap/tablet_meta.cpp
  be/src/olap/tablet_meta.h
  be/src/olap/version_graph.cpp
  be/src/olap/version_graph.h
  fe/fe-core/src/main/java/org/apache/doris/common/proc/BackendProcNode.java
Labels: approved, kind/bug

#5531 [Apache] Add DISCLAIMER back
  DISCLAIMER
  NOTICE.txt
Labels: branch-0.14, kind/license

#5540 [Bug] Fix clone failed when doing incremental clone
  be/src/olap/rowset/alpha_rowset.cpp
  be/src/olap/tablet_meta.cpp
Labels: kind/bug

#5475 [Profile] Visualize the query plan and query profile
  fe/fe-core/pom.xml
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/ExplainOptions.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/QueryStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowQueryProfileStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/StatementBase.java
  fe/fe-core/src/main/java/org/apache/doris/common/profile/CounterNode.java
  fe/fe-core/src/main/java/org/apache/doris/common/profile/ExecNodeNode.java
  fe/fe-core/src/main/java/org/apache/doris/common/profile/PlanTreeBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/common/profile/PlanTreeNode.java
  fe/fe-core/src/main/java/org/apache/doris/common/profile/PlanTreePrinter.java
  fe/fe-core/src/main/java/org/apache/doris/common/profile/ProfileTreeBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/common/profile/ProfileTreeNode.java
  fe/fe-core/src/main/java/org/apache/doris/common/profile/ProfileTreePrinter.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/ProfileManager.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/RuntimeProfile.java
  fe/fe-core/src/main/java/org/apache/doris/planner/AggregationNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/AnalyticEvalNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/AssertNumRowsNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/BrokerScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/CrossJoinNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/EsScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/ExchangeNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/ExportSink.java
  fe/fe-core/src/main/java/org/apache/doris/planner/HashJoinNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/MergeJoinNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/MergeNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/MysqlScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/MysqlTableSink.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OdbcScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapTableSink.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PlanFragment.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PlanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/Planner.java
  fe/fe-core/src/main/java/org/apache/doris/planner/RepeatNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SelectNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SetOperationNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SortNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/StreamLoadScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/main/jflex/sql_scanner.flex
  fe/fe-core/src/test/java/org/apache/doris/planner/DistributedPlannerTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/PlannerTest.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/DorisAssert.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/UtFrameUtils.java
  fe/pom.xml
  gensrc/thrift/Types.thrift
Labels: area/profile, kind/enhancement

#5538 [ODBC] change SQL_DRIVER_COMPLETE_REQUIRED to SQL_DRIVER_NOPROMPT make mysql connect err clear
  be/src/exec/odbc_connector.cpp
Labels: kind/enhancement

#5380 update Dockerfile using gcc 10
  docker/Dockerfile
  docker/Dockerfile.gcc7
Labels: approved, area/build

#5524 support unescape some invisible char in separator
  fe/fe-core/src/main/java/org/apache/doris/analysis/Separator.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/SeparatorTest.java
Labels: approved, kind/enhancement

#5528 turn on glibc compatibility by default for upgrading gcc10
  build.sh
  run-be-ut.sh
Labels: approved, area/build

#5514 [BUG] fix memory limit failure and optimize memory usage in join stage
  be/src/exec/hash_join_node.cpp
  be/src/exec/hash_join_node.h
  be/src/exec/hash_join_node_ir.cpp
  be/test/exec/buffered_reader_test.cpp
Labels: approved, area/sql/execution, kind/bug, kind/enhancement

#5522 [Enhance] Show brokers' hostname
  fe/fe-core/src/main/java/org/apache/doris/catalog/BrokerMgr.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/BackendsProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/FrontendsProcNode.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/NetUtils.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendOptions.java
Labels: approved, kind/enhancement

#5543 [Bug] Fix multi broker load bug
  fe/fe-core/src/main/java/org/apache/doris/analysis/BrokerDesc.java
Labels: approved, kind/bug

#5530 [Docs] Modify schema change sql reference
  docs/en/sql-reference/sql-statements/Data Definition/ALTER TABLE.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/ALTER TABLE.md
Labels: approved, kind/documentation

#5545 remove unused char at end of file
  docker/Dockerfile
Labels: approved, area/build

#5541 [Bug] Fix the bug of rowset file being deleted by mistake
  be/src/olap/rowset/unique_rowset_id_generator.cpp
  be/src/olap/rowset/unique_rowset_id_generator.h
  fe/fe-core/src/test/java/org/apache/doris/catalog/CreateTableTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/PlannerTest.java
Labels: approved, area/storage, kind/bug

#5525 [Docs] fix a mistake in docs basic usage
  docs/en/getting-started/basic-usage.md
  docs/zh-CN/getting-started/basic-usage.md
Labels: approved, kind/documentation

#5533 (#5532) RollupJobV2 support identify cluster when replay
  fe/fe-core/src/main/java/org/apache/doris/alter/RollupJobV2.java
Labels: approved, area/catalog, kind/bug

#5534 [Bug] Fix bug that the last column may be null when using multibytes separator
  be/src/exec/broker_scanner.cpp
  be/test/exec/CMakeLists.txt
  be/test/exec/broker_scanner_test.cpp
  be/test/exec/multi_bytes_separator_test.cpp
  be/test/exec/test_data/broker_scanner/multi_bytes_sep.csv
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateRoutineLoadStmt.java
Labels: approved, kind/bug

#5535 [Docs] Fix typo in docs zh-CN administrator-guide dynamic-partition.md
  docs/zh-CN/administrator-guide/dynamic-partition.md
Labels: approved, kind/documentation

#5536 [Doc] Modify doc for replace table
  docs/en/administrator-guide/alter-table/alter-table-replace-table.md
  docs/zh-CN/administrator-guide/alter-table/alter-table-replace-table.md
Labels: approved, kind/documentation

#5549 [FE] Improve StreamLoadPlanner error log.
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapTableSink.java
Labels: approved

#5394 update gcc to gcc 10 and support c++17
  be/CMakeLists.txt
  be/src/exec/CMakeLists.txt
  be/src/exec/decompressor.cpp
  be/src/exec/olap_common.h
  be/src/exec/scan_node.cpp
  be/src/http/default_path_handlers.cpp
  be/src/http/ev_http_server.cpp
  be/src/olap/rowset/rowset.h
  be/src/olap/rowset/unique_rowset_id_generator.h
  be/src/olap/storage_engine.cpp
  be/src/olap/task/engine_batch_load_task.cpp
  be/src/runtime/buffered_block_mgr2.cc
  be/src/runtime/buffered_tuple_stream2.cc
  be/src/runtime/buffered_tuple_stream3.cc
  be/src/runtime/bufferpool/buffer_allocator.cc
  be/src/runtime/bufferpool/buffer_pool.cc
  be/src/runtime/client_cache.h
  be/src/runtime/data_stream_mgr.h
  be/src/runtime/data_stream_recvr.cc
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/result_buffer_mgr.cpp
  be/src/runtime/snapshot_loader.cpp
  be/src/runtime/spill_sorter.cc
  be/src/runtime/user_function_cache.cpp
  be/src/util/thrift_server.cpp
  be/test/exprs/topn_function_test.cpp
  env.sh
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  thirdparty/build-thirdparty.sh
  thirdparty/download-thirdparty.sh
  thirdparty/patches/incubator-brpc-0.9.5.patch
  thirdparty/patches/mysql-5.7.18-boost.patch
  thirdparty/vars.sh
Labels: approved, area/build

#5566 [DOC] Update gcc10 compile docs
  docs/en/installing/compilation.md
  docs/zh-CN/installing/compilation.md
Labels: approved, kind/documentation

#5520 [Enhance] Support to show more details for 'SHOW TABLES'
  env.sh
  fe/fe-core/src/main/java/org/apache/doris/catalog/Table.java
Labels: approved, kind/enhancement

#5551 [DOC] Add docs of load and export using S3 protocol
  be/src/common/config.h
  be/src/common/daemon.cpp
  docs/.vuepress/public/images/aws_ak_sk.png
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/administrator-guide/config/be_config.md
  docs/en/administrator-guide/export-manual.md
  docs/en/administrator-guide/load-data/load-manual.md
  docs/en/administrator-guide/load-data/s3-load-manual.md
  docs/en/sql-reference/sql-statements/Data Manipulation/BROKER LOAD.md
  docs/en/sql-reference/sql-statements/Data Manipulation/EXPORT.md
  docs/en/sql-reference/sql-statements/Data Manipulation/LOAD.md
  docs/zh-CN/administrator-guide/backup-restore.md
  docs/zh-CN/administrator-guide/config/be_config.md
  docs/zh-CN/administrator-guide/export-manual.md
  docs/zh-CN/administrator-guide/load-data/load-manual.md
  docs/zh-CN/administrator-guide/load-data/s3-load-manual.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/BROKER LOAD.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/EXPORT.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/LOAD.md
Labels: approved, kind/documentation

#5561 optimize cumulative compaction point calculate when after restart be
  be/src/olap/cumulative_compaction_policy.cpp
Labels: approved, area/compact

#5568 [refactor] Remove some unused file for compatible to older kernels
  be/src/glibc-compatibility/musl/getrandom.c
  be/src/glibc-compatibility/musl/sched_getcpu.c
Labels: approved, kind/refactor

#5439 [Bug] Fix some problem with downloading and building thirdparty
  thirdparty/build-thirdparty.sh
  thirdparty/vars.sh
Labels: approved, area/build, kind/bug

#5564 [Bug] Fix bug that call frontend service failed when rpc_timeout is equal with publish_timeout
  fe/fe-core/src/main/java/org/apache/doris/master/MasterImpl.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/MysqlProto.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/nio/NMysqlChannel.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/GlobalTransactionMgr.java
Labels: approved, kind/bug
