Repository apache/doris, pull requests merged in 2021-02, with the labels that each got.

#5305 Support create index on unique value column
  be/src/olap/rowset/segment_v2/segment_writer.cpp
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/IndexDef.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/PropertyAnalyzer.java
  fe/fe-core/src/test/java/org/apache/doris/common/PropertyAnalyzerTest.java
Labels: approved, area/storage, kind/api-change

#5348 [Config] Change some defualt value of Doris config
  docs/en/administrator-guide/config/fe_config.md
  docs/zh-CN/administrator-guide/config/fe_config.md
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/test/java/org/apache/doris/alter/AlterTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: approved, area/config

#5327 [Routine load] Fix kafka load too many task bug
  be/src/runtime/routine_load/routine_load_task_executor.cpp
  be/test/runtime/routine_load_task_executor_test.cpp
Labels: approved, area/load, kind/bug

#4966 Remove redundant code of mini load and insert
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/load/Load.java
  fe/fe-core/src/main/java/org/apache/doris/load/LoadChecker.java
  fe/fe-core/src/main/java/org/apache/doris/planner/CsvScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/DistributedPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapRewriteNode.java
  fe/fe-core/src/main/java/org/apache/doris/task/InsertLoadEtlTask.java
  fe/fe-core/src/main/java/org/apache/doris/task/MiniLoadEtlTask.java
  fe/fe-core/src/main/java/org/apache/doris/task/MiniLoadPendingTask.java
  fe/fe-core/src/main/java/org/apache/doris/task/PullLoadEtlTask.java
  fe/fe-core/src/main/java/org/apache/doris/task/PullLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/task/PullLoadJobMgr.java
  fe/fe-core/src/main/java/org/apache/doris/task/PullLoadTask.java
  fe/fe-core/src/main/java/org/apache/doris/task/PullLoadTaskPlanner.java
Labels: approved, kind/refactor

#5307 [Bug] Duplicate results when reading aggregation table
  be/src/olap/reader.cpp
  be/src/olap/reader.h
Labels: approved, area/storage, kind/bug

#5313 [optimization] use replace top instead of push pop in priority #5312
  be/src/exec/topn_node.cpp
  be/src/exec/topn_node.h
  be/src/util/sort_heap.h
  be/test/util/CMakeLists.txt
  be/test/util/sort_heap_test.cpp
Labels: approved, kind/enhancement

#5351 [Bug] Fix bug of create ODBC table first column is float or double
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateTableStmt.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: approved, kind/bug, kind/datasource

#5250 Fix 5243 Skip repair replica not in colocate group.
  fe/fe-core/src/main/java/org/apache/doris/catalog/Tablet.java
  fe/fe-core/src/main/java/org/apache/doris/clone/ColocateTableBalancer.java
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletScheduler.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/TabletTest.java
  fe/fe-core/src/test/java/org/apache/doris/clone/ColocateTableBalancerTest.java
Labels: approved, area/colocated, kind/bug

#5318 [Enhancement] move common codes from fe-core to fe-common and remove log4j1 (#5317)
  fe/fe-common/pom.xml
  fe/fe-common/src/main/java/org/apache/doris/common/FeConstants.java
  fe/fe-common/src/main/java/org/apache/doris/common/FeMetaVersion.java
  fe/fe-common/src/main/java/org/apache/doris/common/io/DataInputBuffer.java
  fe/fe-common/src/main/java/org/apache/doris/common/io/DataOutputBuffer.java
  fe/fe-common/src/main/java/org/apache/doris/common/io/DeepCopy.java
  fe/fe-common/src/main/java/org/apache/doris/common/io/FastByteArrayInputStream.java
  fe/fe-common/src/main/java/org/apache/doris/common/io/FastByteArrayOutputStream.java
  fe/fe-common/src/main/java/org/apache/doris/common/io/IOUtils.java
  fe/fe-common/src/main/java/org/apache/doris/common/io/InputBuffer.java
  fe/fe-common/src/main/java/org/apache/doris/common/io/LimitInputStream.java
  fe/fe-common/src/main/java/org/apache/doris/common/io/LimitOutputStream.java
  fe/fe-common/src/main/java/org/apache/doris/common/io/OutputBuffer.java
  fe/fe-common/src/main/java/org/apache/doris/common/io/Text.java
  fe/fe-common/src/main/java/org/apache/doris/common/io/Writable.java
  fe/fe-common/src/main/java/org/apache/doris/meta/MetaContext.java
  fe/fe-core/pom.xml
  fe/fe-core/src/test/java/org/apache/doris/analysis/CreateRoutineLoadStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/MaterializedViewSelectorTest.java
  fe/pom.xml
  fe/spark-dpp/pom.xml
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/ColumnParser.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/GlobalDictBuilder.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/SparkDpp.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/etl/SparkEtlJob.java
  fe_plugins/auditloader/pom.xml
  fe_plugins/pom.xml
Labels: approved, kind/refactor

#5315 Adding a column with SUM aggregation to table should restrict the default value
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
Labels: approved, kind/bug

#5230 [Bug][Clone] Fix the bug that incremental clone is not triggered
  be/src/agent/agent_server.cpp
  be/src/agent/task_worker_pool.cpp
  be/src/http/action/snapshot_action.cpp
  be/src/olap/data_dir.cpp
  be/src/olap/data_dir.h
  be/src/olap/olap_snapshot_converter.cpp
  be/src/olap/olap_snapshot_converter.h
  be/src/olap/rowset/rowset.cpp
  be/src/olap/snapshot_manager.cpp
  be/src/olap/snapshot_manager.h
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
  be/src/olap/tablet_manager.cpp
  be/src/olap/tablet_meta.cpp
  be/src/olap/tablet_meta.h
  be/src/olap/task/engine_clone_task.cpp
  be/src/olap/task/engine_clone_task.h
  be/test/olap/CMakeLists.txt
  be/test/olap/tablet_meta_manager_test.cpp
  be/test/olap/test_data/header_without_inc_rs.txt
  gensrc/proto/olap_file.proto
  gensrc/thrift/AgentService.thrift
Labels: approved, kind/bug

#5229 [LOG] Reduce verbose exception log by catch exceptions
  fe/fe-core/src/main/java/org/apache/doris/mysql/MysqlProto.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/nio/NMysqlChannel.java
  fe/fe-core/src/test/java/org/apache/doris/mysql/MysqlProtoTest.java
Labels: approved, kind/refactor

#5278 [Bug] fix bug that dead lock may occur when drop tablet concurrent with tablet distribution interface
  be/src/olap/tablet_manager.cpp
Labels: approved, kind/bug

#5366 Spark doris connector http v2 authentication fails, and HTTP v2 interface returns json nesting problem
  extension/spark-doris-connector/src/main/java/org/apache/doris/spark/rest/RestService.java
  extension/spark-doris-connector/src/test/scala/org/apache/doris/spark/sql/SparkDorisConnector.scala
Labels: approved, area/spark-connector, kind/bug

#5367 [Bug] Fix bug of NPE when replaying spark load job.
  fe/fe-core/src/main/java/org/apache/doris/catalog/SparkResource.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkLoadJob.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/SparkLoadJobTest.java
Labels: area/spark-load, kind/bug

#5319 Set forceDrop to false when getDropPartitionClause for DynamicPartitionScheduler to avoid that the deleted partition cannot be recovered
  fe/fe-core/src/main/java/org/apache/doris/clone/DynamicPartitionScheduler.java
Labels: approved

#5329 [Bug] Fix bug that not erase meta such as tablet when force drop db, table, partition
  fe/fe-core/src/main/java/org/apache/doris/backup/RestoreJob.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/CatalogRecycleBin.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
Labels: approved, kind/bug

#5338 [Feature] Support preceding filter original data when loading
  be/src/exec/base_scanner.cpp
  be/src/exec/base_scanner.h
  be/src/exec/broker_scan_node.cpp
  be/src/exec/broker_scan_node.h
  be/src/exec/broker_scanner.cpp
  be/src/exec/broker_scanner.h
  be/src/exec/json_scanner.cpp
  be/src/exec/json_scanner.h
  be/src/exec/orc_scanner.cpp
  be/src/exec/orc_scanner.h
  be/src/exec/parquet_scanner.cpp
  be/src/exec/parquet_scanner.h
  be/src/olap/push_handler.cpp
  be/src/olap/push_handler.h
  be/test/exec/broker_scanner_test.cpp
  be/test/exec/orc_scanner_test.cpp
  docs/en/administrator-guide/load-data/broker-load-manual.md
  docs/en/sql-reference/sql-statements/Data Manipulation/BROKER LOAD.md
  docs/en/sql-reference/sql-statements/Data Manipulation/ROUTINE LOAD.md
  docs/zh-CN/administrator-guide/load-data/broker-load-manual.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/BROKER LOAD.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/ROUTINE LOAD.md
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateRoutineLoadStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/DataDescription.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ImportWhereStmt.java
  fe/fe-core/src/main/java/org/apache/doris/backup/RestoreJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/BrokerFileGroup.java
  fe/fe-core/src/main/java/org/apache/doris/load/Load.java
  fe/fe-core/src/main/java/org/apache/doris/load/RoutineLoadDesc.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadingTaskPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/planner/BrokerScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/LoadScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PlanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/StreamLoadScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/MultiLoadMgr.java
  fe/fe-core/src/main/java/org/apache/doris/task/LoadTaskInfo.java
  fe/fe-core/src/main/java/org/apache/doris/task/StreamLoadTask.java
  fe/fe-core/src/main/jflex/sql_scanner.flex
  fe/fe-core/src/test/java/org/apache/doris/analysis/DataDescriptionTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/routineload/KafkaRoutineLoadJobTest.java
  gensrc/thrift/PlanNodes.thrift
Labels: api-review, approved, area/load, kind/feature

#5349 [Bug] Fix bug that BE core will loading empty json array
  be/src/exec/json_scanner.cpp
Labels: area/load, kind/bug

#5354 [Config] Modify compaction policy comment in config.h
  be/src/common/config.h
Labels: approved, kind/documentation

#5356 Fix #5355 Add space in case and caseExpr when toSql
  fe/fe-core/src/main/java/org/apache/doris/analysis/CaseExpr.java
Labels: approved

#5357 [Function] Add BE udf bitmap_not (#5346)
  be/src/exprs/bitmap_function.cpp
  be/src/exprs/bitmap_function.h
  be/src/util/bitmap_value.h
  be/test/exprs/bitmap_function_test.cpp
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/sql-reference/sql-functions/bitmap-functions/bitmap_not.md
  docs/zh-CN/sql-reference/sql-functions/bitmap-functions/bitmap_not.md
  gensrc/script/doris_builtins_functions.py
Labels: approved, kind/feature

#5359 [UT] Modify to avoid some UT failure accidentally
  fe/fe-core/src/main/java/org/apache/doris/backup/RestoreJob.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/test/java/org/apache/doris/alter/AlterJobV2Test.java
  fe/fe-core/src/test/java/org/apache/doris/alter/AlterTest.java
  fe/fe-core/src/test/java/org/apache/doris/alter/BatchRollupJobTest.java
Labels: approved, area/test

#5360 [Bug] Fix the problem of floating point precision when importing parquet data
  be/src/exec/orc_scanner.cpp
  be/src/exec/parquet_reader.cpp
Labels: kind/bug

#5364 [Performance Optimization and Refactor] Delete push to segment v2
  be/src/exec/olap_scanner.cpp
  be/src/olap/CMakeLists.txt
  be/src/olap/block_column_predicate.cpp
  be/src/olap/block_column_predicate.h
  be/src/olap/collect_iterator.cpp
  be/src/olap/collect_iterator.h
  be/src/olap/column_predicate.h
  be/src/olap/comparison_predicate.cpp
  be/src/olap/comparison_predicate.h
  be/src/olap/delete_handler.cpp
  be/src/olap/delete_handler.h
  be/src/olap/in_list_predicate.cpp
  be/src/olap/in_list_predicate.h
  be/src/olap/iterators.h
  be/src/olap/null_predicate.cpp
  be/src/olap/null_predicate.h
  be/src/olap/olap_common.h
  be/src/olap/reader.cpp
  be/src/olap/reader.h
  be/src/olap/rowset/beta_rowset_reader.cpp
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/olap/rowset/segment_v2/segment_iterator.h
  be/src/olap/schema_change.cpp
  be/src/olap/schema_change.h
  be/test/olap/CMakeLists.txt
  be/test/olap/block_column_predicate_test.cpp
  be/test/olap/delete_handler_test.cpp
Labels: approved, kind/enhancement, kind/refactor

#5368 [bug] Support if not exists in create table like stmt
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateTableLikeStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateTableStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/CreateTableLikeTest.java
Labels: approved, kind/bug

#5369 [Load Parallel][3/3] Support parallel delta writer
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
  be/src/olap/delta_writer.cpp
  be/src/olap/delta_writer.h
  be/src/olap/olap_define.h
  be/src/olap/rowset/unique_rowset_id_generator.cpp
  be/src/olap/tablet_manager.cpp
  be/src/runtime/load_channel_mgr.cpp
  be/src/runtime/load_channel_mgr.h
  be/src/runtime/tablets_channel.cpp
  be/src/service/internal_service.cpp
  be/test/runtime/load_channel_mgr_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
Labels: approved, area/load, kind/enhancement

#5370 [DOCS] add some missing documents
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/zh-CN/sql-reference/sql-statements/Data Definition/ALTER TABLE.md
Labels: approved, kind/documentation

#5387 [UT] Fix FE ut bugs
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: approved, area/test, kind/bug

#5377 [FE] Fix overflow in RuntimeProfile.sortChildren.
  fe/fe-core/src/main/java/org/apache/doris/common/util/RuntimeProfile.java
Labels: kind/bug

#5378 [Bug] Fix NPE when replaying modify table property
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
Labels: approved, kind/bug

#5385 [optimization] use inline optimize ExprContext::get_value
  be/src/exec/base_scanner.cpp
  be/src/exec/broker_scan_node.cpp
  be/src/exec/es_http_scan_node.cpp
  be/src/exec/es_http_scanner.cpp
  be/src/exec/hash_join_node.cpp
  be/src/exec/hash_table.cpp
  be/src/exec/merge_join_node.cpp
  be/src/exec/merge_node.cpp
  be/src/exec/olap_rewrite_node.cpp
  be/src/exec/olap_scan_node.cpp
  be/src/exec/set_operation_node.cpp
  be/src/exec/tablet_sink.cpp
  be/src/exprs/case_expr.cpp
  be/src/exprs/expr.cpp
  be/src/exprs/expr.h
  be/src/exprs/expr_context.cpp
  be/src/exprs/expr_context.h
  be/src/exprs/in_predicate.cpp
  be/src/exprs/timestamp_functions.cpp
  be/src/runtime/data_spliter.cpp
  be/src/runtime/data_stream_sender.cpp
  be/src/runtime/dpp_sink.cpp
  be/src/runtime/dpp_writer.cpp
  be/src/runtime/export_sink.cpp
  be/src/runtime/file_result_writer.cpp
  be/src/runtime/mysql_result_writer.cpp
  be/src/runtime/mysql_table_writer.cpp
  be/src/runtime/qsorter.cpp
  be/src/runtime/tuple.cpp
  be/src/util/tuple_row_compare.h
  be/test/exec/hash_table_test.cpp
  be/test/exprs/math_functions_test.cpp
  be/test/exprs/topn_function_test.cpp
Labels: approved, kind/enhancement

#5388 [Docs] Reorder docs index in sidebar
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/administrator-guide/export-manual.md
Labels: approved, kind/documentation

#5386 Support for AuthSwitchRequest In HandShakePacket to better support MySQL 8.0 clients
  fe/fe-core/src/main/java/org/apache/doris/mysql/MysqlAuthPacket.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/MysqlHandshakePacket.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/MysqlProto.java
Labels: approved, area/mysql-compatibility

#5310 [Enhancement] Use add method instead of put method to avoid query being stuck when event queue is full
  fe/fe-core/src/main/java/org/apache/doris/qe/AuditEventProcessor.java
Labels: approved, kind/enhancement

#5365 [Doc]: correct wrong num in create table help doc
  docs/en/sql-reference/sql-statements/Data Definition/CREATE TABLE.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/CREATE TABLE.md
Labels: approved, kind/documentation

#5398 Update CREATE TABLE.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/CREATE TABLE.md
Labels: approved, kind/documentation

#5363 [Doris on ES] Fix query failed when ES field value is null
  be/src/exec/es/es_scroll_parser.cpp
Labels: approved, area/doris-on-es, kind/bug

#5373 升级jackson版本号
  fe/pom.xml
Labels: approved, area/dependency

#5382 [BUG] fix scan node create PartitionColumnFilter incorrect
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
Labels: approved, kind/bug

#5413 [bug] Fix bug that compaction failed after deletion
  be/src/olap/reader.h
Labels: approved, kind/bug

#5414 [LICENSE] Add license to files
  .rat-excludes
  docs/en/community/release-process.md
  docs/en/community/verify-apache-release.md
  docs/zh-CN/community/release-process.md
  docs/zh-CN/community/verify-apache-release.md
  extension/spark-doris-connector/src/test/scala/org/apache/doris/spark/sql/SparkDorisConnector.scala
  fe/fe-core/src/test/java/org/apache/doris/backup/BrokerStorageTest.java
  fe/fe-core/src/test/java/org/apache/doris/backup/S3StorageTest.java
  fe/fe-core/src/test/java/org/apache/doris/common/util/S3URITest.java
  ui/src/pages/playground/tree/index.css
Labels: branch-0.14, kind/license

#5410 Column Pruning under count start
  fe/fe-core/src/main/java/org/apache/doris/analysis/AggregateInfo.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
Labels: SQL Improvement, approved, area/optimizer

#5412 [Fix #2440] Server asks us to fall back to SIMPLE auth, but this client is configured to only allow secure connections.
  fs_brokers/apache_hdfs_broker/src/main/java/org/apache/doris/broker/hdfs/FileSystemManager.java
Labels: area/broker

#5321 [Doc] correct format errors in English doc
  docs/en/README.md
  docs/en/administrator-guide/alter-table/alter-table-bitmap-index.md
  docs/en/administrator-guide/broker.md
  docs/en/administrator-guide/config/fe_config.md
  docs/en/administrator-guide/dynamic-partition.md
  docs/en/administrator-guide/export-manual.md
  docs/en/administrator-guide/http-actions/cancel-label.md
  docs/en/administrator-guide/load-data/broker-load-manual.md
  docs/en/administrator-guide/load-data/delete-manual.md
  docs/en/administrator-guide/load-data/load-json-format.md
  docs/en/administrator-guide/load-data/sequence-column-manual.md
  docs/en/administrator-guide/load-data/stream-load-manual.md
  docs/en/administrator-guide/operation/tablet-repair-and-balance.md
  docs/en/administrator-guide/outfile.md
  docs/en/administrator-guide/privilege.md
  docs/en/administrator-guide/resource-management.md
  docs/en/administrator-guide/running-profile.md
  docs/en/administrator-guide/time-zone.md
  docs/en/community/pull-request.md
  docs/en/community/release-process.md
  docs/en/developer-guide/fe-eclipse-dev.md
  docs/en/developer-guide/format-code.md
  docs/en/extending-doris/doris-on-es.md
  docs/en/extending-doris/logstash.md
  docs/en/extending-doris/odbc-of-doris.md
  docs/en/extending-doris/udf/contrib/udaf-orthogonal-bitmap-manual.md
  docs/en/getting-started/advance-usage.md
  docs/en/getting-started/basic-usage.md
  docs/en/getting-started/best-practice.md
  docs/en/getting-started/data-model-rollup.md
  docs/en/getting-started/hit-the-rollup.md
  docs/en/installing/install-deploy.md
  docs/en/installing/upgrade.md
  docs/en/internal/grouping_sets_design.md
  docs/en/sql-reference/sql-functions/date-time-functions/from_unixtime.md
  docs/en/sql-reference/sql-functions/date-time-functions/time_round.md
  docs/en/sql-reference/sql-statements/Account Management/GRANT.md
  docs/en/sql-reference/sql-statements/Account Management/REVOKE.md
  docs/en/sql-reference/sql-statements/Administration/ADMIN CHECK TABLET.md
  docs/en/sql-reference/sql-statements/Administration/ALTER SYSTEM.md
  docs/en/sql-reference/sql-statements/Data Definition/ALTER TABLE.md
  docs/en/sql-reference/sql-statements/Data Definition/CREATE TABLE LIKE.md
  docs/en/sql-reference/sql-statements/Data Definition/CREATE TABLE.md
  docs/en/sql-reference/sql-statements/Data Definition/Colocate Join.md
  docs/en/sql-reference/sql-statements/Data Definition/SHOW RESOURCES.md
  docs/en/sql-reference/sql-statements/Data Manipulation/BROKER LOAD.md
  docs/en/sql-reference/sql-statements/Data Manipulation/LOAD.md
  docs/en/sql-reference/sql-statements/Data Manipulation/MINI LOAD.md
  docs/en/sql-reference/sql-statements/Data Manipulation/MULTI LOAD.md
  docs/en/sql-reference/sql-statements/Data Manipulation/ROUTINE LOAD.md
  docs/en/sql-reference/sql-statements/Data Manipulation/SHOW ALTER.md
  docs/en/sql-reference/sql-statements/Data Manipulation/SHOW DYNAMIC PARTITION TABLES.md
  docs/en/sql-reference/sql-statements/Data Manipulation/STREAM LOAD.md
  docs/en/sql-reference/sql-statements/Data Manipulation/alter-routine-load.md
Labels: approved, kind/documentation
