Repository apache/doris, pull requests merged in 2021-11, with the labels that each got.

#6910 [Feature] Support bitmap_and_not & bitmap_and_not_count
  be/src/exprs/bitmap_function.cpp
  be/src/exprs/bitmap_function.h
  be/test/exprs/bitmap_function_test.cpp
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/sql-reference/sql-functions/bitmap-functions/bitmap_and_not.md
  docs/en/sql-reference/sql-functions/bitmap-functions/bitmap_and_not_count.md
  docs/zh-CN/sql-reference/sql-functions/bitmap-functions/bitmap_and_not.md
  docs/zh-CN/sql-reference/sql-functions/bitmap-functions/bitmap_and_not_count.md
  gensrc/script/doris_builtins_functions.py
Labels: approved, reviewed

#6962 [S3] Support path style endpoint
  be/src/exec/tablet_sink.cpp
  be/src/olap/delta_writer.cpp
  be/src/runtime/load_channel.cpp
  be/src/runtime/tablets_channel.cpp
  be/src/runtime/tablets_channel.h
  be/src/service/internal_service.cpp
  be/src/util/s3_util.cpp
  be/test/util/s3_storage_backend_test.cpp
  docs/en/administrator-guide/load-data/s3-load-manual.md
  docs/zh-CN/administrator-guide/load-data/s3-load-manual.md
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/org/apache/doris/backup/BlobStorage.java
  fe/fe-core/src/main/java/org/apache/doris/backup/Repository.java
  fe/fe-core/src/main/java/org/apache/doris/backup/S3Storage.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/BrokerUtil.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/S3URI.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/manager/NodeAction.java
  fe/fe-core/src/test/java/org/apache/doris/backup/S3StorageTest.java
  fe/fe-core/src/test/java/org/apache/doris/common/util/S3URITest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/StreamLoadScanNodeTest.java
  fe/pom.xml
  gensrc/proto/internal_service.proto
Labels: approved, reviewed, area/s3

#6943 Docker 1.4.1 Compile Environment, First Compile Description
  docs/en/installing/compilation.md
  docs/zh-CN/installing/compilation.md
Labels: approved, reviewed

#6947 [Enhance][Load] Reduce the number of segments when loading a large volume data in one batch
  be/src/common/config.h
  be/src/olap/memtable.cpp
  be/src/olap/memtable.h
  be/src/runtime/load_channel.cpp
  be/src/runtime/tablets_channel.cpp
  be/src/runtime/tablets_channel.h
  docs/en/best-practices/star-schema-benchmark.md
  docs/zh-CN/best-practices/star-schema-benchmark.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/OutFileClause.java
Labels: kind/enhancement, area/load, approved, reviewed

#6917 [Function] add BE bitmap function bitmap_subset_in_range
  be/src/exprs/bitmap_function.cpp
  be/src/exprs/bitmap_function.h
  be/src/util/bitmap_value.h
  be/test/exprs/bitmap_function_test.cpp
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/sql-reference/sql-functions/bitmap-functions/bitmap_subset_in_range.md
  docs/zh-CN/sql-reference/sql-functions/bitmap-functions/bitmap_subset_in_range.md
  gensrc/script/doris_builtins_functions.py
Labels: area/sql/function

#6963 [Doc] Update fe-idea developer guide for latest version
  docs/en/developer-guide/fe-idea-dev.md
  docs/zh-CN/developer-guide/fe-idea-dev.md
Labels: approved, reviewed

#6918 [Function] add bitmap function of bitmap_has_all
  be/src/exprs/bitmap_function.cpp
  be/src/exprs/bitmap_function.h
  be/test/exprs/bitmap_function_test.cpp
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/sql-reference/sql-functions/bitmap-functions/bitmap_has_all.md
  docs/zh-CN/sql-reference/sql-functions/bitmap-functions/bitmap_has_all.md
  gensrc/script/doris_builtins_functions.py
Labels: area/sql/function

#6912 [Feature] add functions of bitmap_and/or_count
  be/src/exprs/bitmap_function.cpp
  be/src/exprs/bitmap_function.h
  be/test/exprs/bitmap_function_test.cpp
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/sql-reference/sql-functions/bitmap-functions/bitmap_and_count.md
  docs/en/sql-reference/sql-functions/bitmap-functions/bitmap_or_count.md
  docs/zh-CN/sql-reference/sql-functions/bitmap-functions/bitmap_and_count.md
  docs/zh-CN/sql-reference/sql-functions/bitmap-functions/bitmap_or_count.md
  gensrc/script/doris_builtins_functions.py
Labels: area/sql/function

#6899 [BUG] fix Calc capacityCoefficient mistake
  fe/fe-core/src/main/java/org/apache/doris/clone/BackendLoadStatistic.java
Labels: kind/bug, approved, area/balance, reviewed

#6932 fix schema change fail as memory allocation on row block sorting
  be/src/olap/schema_change.cpp
  be/src/olap/schema_change.h
Labels: kind/enhancement, area/schema-change, approved, reviewed

#6968 fix flatbuffers download url error
  thirdparty/vars.sh
Labels: area/dependency, approved, reviewed

#6973 [Feature] Spark connector supports to specify fields to write
  docs/en/extending-doris/spark-doris-connector.md
  docs/zh-CN/extending-doris/spark-doris-connector.md
  extension/spark-doris-connector/src/main/java/org/apache/doris/spark/DorisStreamLoad.java
  extension/spark-doris-connector/src/main/java/org/apache/doris/spark/cfg/ConfigurationOptions.java
  extension/spark-doris-connector/src/main/java/org/apache/doris/spark/rest/RestService.java
  extension/spark-doris-connector/src/test/scala/org/apache/doris/spark/sql/DataframeSinkDoris.scala
  extension/spark-doris-connector/src/test/scala/org/apache/doris/spark/sql/SparkDorisConnector.scala
  extension/spark-doris-connector/src/test/scala/org/apache/doris/spark/sql/TestSparkConnector.scala
  extension/spark-doris-connector/src/test/scala/org/apache/doris/spark/sql/TestStreamSinkDoris.scala
Labels: kind/enhancement, area/spark-connector, approved, reviewed

#6975 [BUG][Schedule] Fix getMixLoadScore error.
  fe/fe-core/src/main/java/org/apache/doris/clone/BackendLoadStatistic.java
Labels: kind/bug, approved, area/balance, reviewed

#6976 generage compile_command.json
  be/CMakeLists.txt
Labels: approved, reviewed

#6982 [BitMap-Function] Add bitmap-xor-count function for doris
  be/src/exprs/bitmap_function.cpp
  be/src/exprs/bitmap_function.h
  be/test/exprs/bitmap_function_test.cpp
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/sql-reference/sql-functions/bitmap-functions/bitmap_xor_count.md
  docs/zh-CN/sql-reference/sql-functions/bitmap-functions/bitmap_xor_count.md
  gensrc/script/doris_builtins_functions.py
Labels: approved, area/sql/function, reviewed

#6999 [HTTP][API] Add Backend By Rest API
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/manager/ClusterAction.java
Labels: approved, reviewed

#7002 [BUG] fixbug sql execution sometimes due to failed to get tablet
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
Labels: approved, reviewed

#7004 Revert "[HTTP][API] Add Backend By Rest API"
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/manager/ClusterAction.java
Labels: kind/revert

#6994 [Revert] Revert RestService.java
  extension/spark-doris-connector/src/main/java/org/apache/doris/spark/rest/RestService.java
  extension/spark-doris-connector/src/test/java/org/apache/doris/spark/rest/TestRestService.java
Labels: approved, kind/revert, reviewed

#6980 [Function] Add bitmap function bitmap_subset_limit
  be/src/exprs/bitmap_function.cpp
  be/src/exprs/bitmap_function.h
  be/src/util/bitmap_value.h
  be/test/exprs/bitmap_function_test.cpp
  be/test/util/bitmap_value_test.cpp
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/sql-reference/sql-functions/bitmap-functions/bitmap_subset_limit.md
  docs/zh-CN/sql-reference/sql-functions/bitmap-functions/bitmap_subset_limit.md
  gensrc/script/doris_builtins_functions.py
Labels: approved, area/sql/function, reviewed

#6996 Fix hadoop load failed when enable batch delete in unique table
  fe/fe-core/src/main/java/org/apache/doris/load/Load.java
  fe/fe-core/src/main/java/org/apache/doris/task/HadoopLoadPendingTask.java
Labels: kind/bug, area/load, approved, reviewed

#7003 [Bug] Fix the nullptr of core in schema change
  be/src/olap/schema_change.cpp
Labels: kind/bug, area/schema-change, approved, reviewed

#7005 fix issue for JournalEntity
  fe/fe-core/src/main/java/org/apache/doris/journal/JournalEntity.java
Labels: approved, reviewed

#7017 [refactor] set `forward_to_master` true by default
  be/src/runtime/stream_load/stream_load_executor.cpp
  docs/en/administrator-guide/variables.md
  docs/zh-CN/administrator-guide/variables.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowRoutineLoadTaskStmt.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadManager.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
Labels: approved, area/config, reviewed

#7026 Union stmt support 'OutFileClause'
  fe/fe-core/src/main/java/org/apache/doris/analysis/OutFileClause.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SetOperationStmt.java
  fe/fe-core/src/main/java/org/apache/doris/journal/JournalEntity.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/OutFileClauseFunctionTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/ColocatePlanTest.java
Labels: area/colocated, approved, area/outfile, reviewed

#7023 [Bug]Update Spring version to fix CVE-2020-5421
  fe/pom.xml
Labels: area/dependency, approved, reviewed

#6977 [Function] add BE bitmap function sub_bitmap
  be/src/exprs/bitmap_function.cpp
  be/src/exprs/bitmap_function.h
  be/src/util/bitmap_value.h
  be/test/exprs/bitmap_function_test.cpp
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/sql-reference/sql-functions/bitmap-functions/sub_bitmap.md
  docs/zh-CN/sql-reference/sql-functions/bitmap-functions/sub_bitmap.md
  gensrc/script/doris_builtins_functions.py
Labels: approved, area/sql/function, reviewed

#6933 [Doc] Use Flink CDC to realize real-time MySQL data into Apache Doris
  docs/.vuepress/public/images/cdc/image-20211025162831632.png
  docs/.vuepress/public/images/cdc/image-20211025165547903.png
  docs/.vuepress/public/images/cdc/image-20211025170642628.png
  docs/.vuepress/public/images/cdc/image-20211025182341086.png
  docs/.vuepress/public/images/cdc/image-20211025182435827.png
  docs/.vuepress/public/images/cdc/image-20211026095513892.png
  docs/.vuepress/public/images/cdc/image-20211026100505972.png
  docs/.vuepress/public/images/cdc/image-20211026100804091.png
  docs/.vuepress/public/images/cdc/image-20211026100943474.png
  docs/.vuepress/public/images/cdc/image-20211026101004547.png
  docs/.vuepress/public/images/cdc/image-20211026101203629.png
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/best-practices/datax-doris-writer.md
  docs/en/best-practices/flink-cdc-to-doris.md
  docs/zh-CN/best-practices/flink-cdc-to-doris.md
Labels: approved, area/easy-to-use, reviewed

#6577 Custom config handler #6508
  fe/fe-core/src/main/java/org/apache/doris/common/ConfigBase.java
  fe/fe-core/src/main/java/org/apache/doris/http/rest/SetConfigAction.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/SetConfigAction.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/manager/NodeAction.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/AdminSetConfigStmtTest.java
Labels: kind/enhancement, approved, area/config, reviewed

#6600 [Feature] Extend logger interface, support structured log output #6529
  be/src/common/logconfig.cpp
  be/src/runtime/plan_fragment_executor.cpp
  be/src/util/logging.h
  fe/fe-core/src/main/java/org/apache/doris/common/logger/DefaultDorisLogger.java
  fe/fe-core/src/main/java/org/apache/doris/common/logger/LoggerProvider.java
  fe/fe-core/src/main/java/org/apache/doris/common/logger/TagKey.java
  fe/fe-core/src/main/java/org/apache/doris/common/logger/TaggableLogger.java
  fe/fe-core/src/main/java/org/apache/doris/common/logger/TaggedLogFormat.java
  fe/fe-core/src/main/java/org/apache/doris/common/logger/Tags.java
Labels: approved, reviewed

#6936 Fix some return logic error in init BE encoding_map
  be/src/olap/rowset/segment_v2/encoding_info.cpp
Labels: kind/bug, area/storage, approved, reviewed

#6998 [Refactor] Refactor part of RuntimeFilter's code
  be/src/exec/hash_join_node.cpp
  be/src/exec/hash_join_node.h
  be/src/exprs/bloomfilter_predicate.cpp
  be/src/exprs/hybrid_set.cpp
  be/src/exprs/hybrid_set.h
  be/src/exprs/runtime_filter.cpp
  be/src/exprs/runtime_filter.h
  be/src/exprs/runtime_filter_slots.h
  be/src/runtime/primitive_type.h
Labels: approved, kind/refactor, area/runtime-filter, reviewed

#7029 [Compile] Fix FE compile problem
  fe/fe-core/src/main/java/org/apache/doris/common/logger/TaggableLogger.java
Labels: kind/bug, area/build, approved, reviewed

#7022 [Bug] Change DateTimeValue Memmory Layout To Old
  be/src/runtime/datetime_value.h
Labels: kind/bug, area/sql/compatibility, approved, reviewed

#7043 [Bug] fix Tags empty reference core dump
  be/src/util/logging.h
Labels: kind/bug, approved, reviewed

#7047 [Website][Doc] Add the sharing blog function to the document site
  docs/.vuepress/config.js
  docs/.vuepress/public/images/home/new.svg
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/.vuepress/theme/components/Home.vue
  docs/.vuepress/theme/layouts/Article.vue
  docs/.vuepress/theme/layouts/ArticleList.vue
  docs/en/README.md
  docs/en/article/article-list.md
  docs/en/developer-guide/How-to-Share-blogs.md
  docs/zh-CN/README.md
  docs/zh-CN/article/article-list.md
  docs/zh-CN/developer-guide/How-to-Share-blogs.md
Labels: kind/documentation, area/website, approved, reviewed

#7051 [Build]Compile and output the jar file, add Spark, Flink version and Scala version
  extension/flink-doris-connector/build.sh
  extension/flink-doris-connector/pom.xml
  extension/spark-doris-connector/build.sh
  extension/spark-doris-connector/pom.xml
  extension/spark-doris-connector/pom_3.0.xml
Labels: area/build, area/spark-connector, approved, reviewed

#7052 [Docs] Add hdfs outfile example
  docs/en/administrator-guide/outfile.md
  docs/zh-CN/administrator-guide/outfile.md
Labels: kind/documentation, approved, reviewed

#7057 [Bug] Fix docs website home page last news icon loading failure
  docs/.vuepress/theme/components/Home.vue
Labels: approved, reviewed

#7062 [Bug] Fix version nav button loaded multiple times in docs website header
  docs/.vuepress/theme/layouts/Layout.vue
Labels: approved, reviewed

#7086 [Website][Docs]Add author field to blog
  docs/.vuepress/config.js
  docs/.vuepress/theme/layouts/Article.vue
  docs/.vuepress/theme/layouts/ArticleList.vue
  docs/en/developer-guide/How-to-Share-blogs.md
  docs/zh-CN/developer-guide/How-to-Share-blogs.md
Labels: approved, reviewed

#7050 Add errno for hdfs writer. when no dir, hdfs writer open failed, the dir need to be created.
  be/src/exec/hdfs_file_reader.cpp
  be/src/exec/hdfs_writer.cpp
  be/src/exprs/bitmap_function.h
  be/src/util/bitmap_value.h
Labels: approved, reviewed

#6986 [RoutineLoad] And "runningTxns" fields in SHOW ROUTINE LOAD result.
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadStatistic.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadTaskInfo.java
Labels: kind/enhancement, approved, area/routine load, reviewed

#7048 [Compile] Fix spark-connector compile problem
  extension/spark-doris-connector/build.sh
Labels: area/build, area/spark-connector, approved, reviewed

#7065 fix log error for ActionController
  fe/fe-core/src/main/java/org/apache/doris/http/ActionController.java
Labels: approved, reviewed

#7069 [Bug] Fix bug that NPE thrown when adding partition for table with MV
  fe/fe-core/src/main/java/org/apache/doris/analysis/SlotRef.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Column.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/MaterializedIndexMeta.java
  fe/fe-core/src/main/java/org/apache/doris/task/CreateRollupTask.java
  fe/fe-core/src/main/java/org/apache/doris/task/SchemaChangeTask.java
Labels: kind/bug, area/catalog, approved, reviewed

#7024 fix core problem: use object replace pointer
  be/src/exec/tablet_info.h
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
Labels: kind/bug, approved, reviewed

#7094 [compile] fix unused import
  fe/fe-core/src/main/java/org/apache/doris/http/ActionController.java
Labels: kind/bug, area/build, approved, reviewed

#6846 [bug] fix NumberFormatException for partition cache
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/PartitionRange.java
Labels: kind/bug, approved, area/sql/cache, reviewed

#6873 [BUG] fix streaming_preagg dcheck cause be down
  be/src/exec/partitioned_aggregation_node.cc
Labels: approved, reviewed

#6885 Add not and xor methods to bitmapValue
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/BitmapValue.java
Labels: approved, area/spark-load, reviewed

#6915 [Optimize][Set Operation Node] Reduce the memory expansion operationof the hash table in ExecptNode and IntersectNode
  be/src/exec/except_node.cpp
  be/src/exec/hash_table.cpp
  be/src/exec/hash_table.h
  be/src/exec/intersect_node.cpp
  be/src/exec/set_operation_node.cpp
  be/src/exec/set_operation_node.h
Labels: kind/enhancement, approved, reviewed

#6934 [Bug] Fix the error of inaccurate checking RLE page whether is full
  be/src/olap/rowset/segment_v2/column_writer.cpp
Labels: kind/bug, good first issue, approved, reviewed

#6970 Add stream load info to system info of web site
  fe/fe-core/src/main/java/org/apache/doris/common/proc/ProcService.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/StreamLoadProcNode.java
  fe/fe-core/src/main/java/org/apache/doris/load/StreamLoadRecordMgr.java
Labels: kind/feature, approved, reviewed, area/proc

#6988 mem_tracker optimization
  be/src/runtime/mem_tracker.cpp
  be/src/runtime/mem_tracker.h
  be/src/util/runtime_profile.h
Labels: approved, reviewed

#7061 [Feature] Clean up old sync jobs regularly
  fe/fe-core/src/main/java/org/apache/doris/load/sync/SyncChecker.java
  fe/fe-core/src/main/java/org/apache/doris/load/sync/SyncJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/sync/SyncJobManager.java
  fe/fe-core/src/test/java/org/apache/doris/load/sync/SyncJobManagerTest.java
Labels: approved, kind/cleanup, reviewed, area/mysql-binlog

#7085 [BUG]. Fix CacheAnalyzer's bug when aggregate column contains expr
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/CacheAnalyzer.java
Labels: kind/bug, approved, area/sql/cache, reviewed

#7091 fix bug with use tableId to get table in publish version
  fe/fe-core/src/main/java/org/apache/doris/catalog/Database.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java
Labels: kind/bug, area/load, approved, reviewed

#6971 hll optimize: trace memory usage, new explicit data when really need
  be/src/olap/aggregate_func.h
  be/src/olap/hll.cpp
  be/src/olap/hll.h
Labels: kind/enhancement, approved, reviewed

#7093 [Doc]Organize documents
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/article/articles/datax-doris-writer.md
  docs/en/article/articles/fe-load-balance.md
  docs/en/article/articles/flink-cdc-to-doris.md
  docs/en/benchmark/samples.md
  docs/en/benchmark/star-schema-benchmark.md
  docs/en/benchmark/systemd.md
  docs/zh-CN/article/articles/datax-doris-writer.md
  docs/zh-CN/article/articles/fe-load-balance.md
  docs/zh-CN/article/articles/flink-cdc-to-doris.md
  docs/zh-CN/benchmark/samples.md
  docs/zh-CN/benchmark/star-schema-benchmark.md
  docs/zh-CN/benchmark/systemd.md
Labels: approved, reviewed, area/Blog

#6993 [Alter] Support alter table engine type from MySQL to ODBC
  docs/en/sql-reference/sql-statements/Data Definition/ALTER TABLE.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/ALTER TABLE.md
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/alter/Alter.java
  fe/fe-core/src/main/java/org/apache/doris/alter/AlterOpType.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/AlterTableStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ModifyEngineClause.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OdbcTable.java
  fe/fe-core/src/main/java/org/apache/doris/journal/JournalEntity.java
  fe/fe-core/src/main/java/org/apache/doris/persist/EditLog.java
  fe/fe-core/src/main/java/org/apache/doris/persist/ModifyTableEngineOperationLog.java
  fe/fe-core/src/main/java/org/apache/doris/persist/OperationType.java
  fe/fe-core/src/test/java/org/apache/doris/alter/AlterTest.java
Labels: kind/feature, approved, api-review, area/odbc, reviewed

#7099 [Github] Guiding users to use mailing lists
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: area/community, approved, reviewed

#7064 [Feature] Add degradate strategy for local_replica_selection.
  docs/en/administrator-guide/config/fe_config.md
  docs/zh-CN/administrator-guide/config/fe_config.md
  fe/fe-core/src/main/java/org/apache/doris/catalog/Tablet.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
Labels: kind/enhancement, approved, area/config, reviewed

#7074 add thrift dir for spark connector
  extension/spark-doris-connector/pom.xml
  extension/spark-doris-connector/pom_3.0.xml
Labels: area/build, area/spark-connector, approved, reviewed

#7075 [Feature] Support Flink and Spark connector support String type
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/serialization/RowBatch.java
  extension/flink-doris-connector/src/main/thrift/doris/Types.thrift
  extension/spark-doris-connector/src/main/java/org/apache/doris/spark/serialization/RowBatch.java
  extension/spark-doris-connector/src/main/thrift/doris/Types.thrift
Labels: area/spark-connector, approved, area/flink-connector, reviewed

#7076 Add session variable to close join order
  docs/en/administrator-guide/variables.md
  docs/zh-CN/administrator-guide/variables.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/FromClause.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
Labels: approved, api-review, reviewed

#7088 Openssl development package
  docs/en/developer-guide/be-vscode-dev.md
Labels: good first issue, area/build, approved, reviewed

#7100 REPLACE_IF_NOT_NULL document modification
  docs/en/sql-reference-v2/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE.md
  docs/en/sql-reference/sql-statements/Data Definition/CREATE TABLE.md
  docs/zh-CN/sql-reference-v2/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/CREATE TABLE.md
Labels: kind/documentation, approved, reviewed

#7103 [Website][Doc]website bugfix
  docs/.vuepress/theme/layouts/Article.vue
  docs/.vuepress/theme/layouts/ArticleList.vue
  docs/en/article/articles/datax-doris-writer.md
  docs/en/article/articles/fe-load-balance.md
  docs/en/article/articles/flink-cdc-to-doris.md
  docs/en/developer-guide/How-to-Share-blogs.md
  docs/zh-CN/article/articles/datax-doris-writer.md
  docs/zh-CN/article/articles/fe-load-balance.md
  docs/zh-CN/article/articles/flink-cdc-to-doris.md
  docs/zh-CN/developer-guide/How-to-Share-blogs.md
Labels: area/website, approved, reviewed

#6891 [Enhancement] add thread id in be log
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/plan_fragment_executor.cpp
Labels: kind/enhancement, approved, reviewed

#7112 [Compile] Remove unused import
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
Labels: area/build, approved, reviewed

#7101 logger error in BDBStateChangeListener.java
  fe/fe-core/src/main/java/org/apache/doris/ha/BDBStateChangeListener.java
Labels: approved, reviewed

#7111 [Bug] Fix inappropriate Cmake option used to build ZSTD
  thirdparty/build-thirdparty.sh
Labels: area/dependency, approved, reviewed

#6569 [Feature] Support query hive table
  be/src/exec/broker_scanner.cpp
  be/src/exec/orc_scanner.cpp
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/extending-doris/hive-of-doris.md
  docs/en/sql-reference/sql-statements/Data Definition/CREATE TABLE.md
  docs/zh-CN/extending-doris/hive-of-doris.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/CREATE TABLE.md
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/org/apache/doris/analysis/FromClause.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/HiveMetaStoreClientHelper.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/HiveTable.java
  fe/fe-core/src/main/java/org/apache/doris/load/BrokerFileGroup.java
  fe/fe-core/src/main/java/org/apache/doris/planner/BrokerScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/HiveScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
  fe/pom.xml
  gensrc/thrift/Descriptors.thrift
  gensrc/thrift/PlanNodes.thrift
Labels: kind/feature, approved, area/sql, reviewed, area/extension/hive

#7080 [Blog]Example of binlog load usage
  docs/.vuepress/public/images/binlog/image-20211110145044815.png
  docs/.vuepress/public/images/binlog/image-20211110160106602.png
  docs/.vuepress/public/images/binlog/image-20211110160331479.png
  docs/.vuepress/public/images/binlog/image-20211110160710709.png
  docs/en/article/articles/doris-binlog-load.md
  docs/zh-CN/article/articles/doris-binlog-load.md
Labels: reviewed, area/Blog

#7130 [License] Add License header for missing files
  .licenserc.yaml
  be/src/runtime/runtime_filter_mgr.cpp
  docs/.vuepress/theme/styles/index.styl
  extension/DataX/doriswriter/README
  extension/DataX/doriswriter/src/main/assembly/package.xml
  extension/DataX/doriswriter/src/main/java/com/alibaba/datax/plugin/writer/doriswriter/DorisCodec.java
  extension/DataX/init-env.sh
  extension/flink-doris-connector/pom.xml
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisSink.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/GenericDorisSinkFunction.java
  extension/flink-doris-connector/src/test/java/org/apache/doris/flink/DorisStreamSinkExample.java
  extension/spark-doris-connector/pom.xml
  extension/spark-doris-connector/pom_3.0.xml
  fe/README
  fe/fe-core/src/main/cup/readme
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/test/java/org/apache/doris/analysis/IsNullPredicateTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/RangeCompareTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ShowViewStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/TruncateTableTest.java
  fe/fe-core/src/test/java/org/apache/doris/ldap/LdapAuthenticateTest.java
  fe/fe-core/src/test/java/org/apache/doris/ldap/LdapClientTest.java
  fe/fe-core/src/test/java/org/apache/doris/ldap/LdapPrivsCheckerTest.java
  fe/fe-core/src/test/java/org/apache/doris/persist/LdapInfoTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/JoinCostEvaluationTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/RuntimeFilterGeneratorTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/SingleNodePlannerTest.java
  fe/fe-core/src/test/resources/log4j2.xml
  fe_plugins/auditdemo/src/main/assembly/zip.xml
  fe_plugins/auditloader/src/main/assembly/zip.xml
  fs_brokers/apache_hdfs_broker/conf/hdfs-site.xml
  gensrc/script/gen_builtins_functions.py
  gensrc/thrift/HeartbeatService.thrift
  gensrc/thrift/PaloBrokerService.thrift
  samples/doris-demo/spring-jdbc-demo/src/main/resources/application-druid.yml
  samples/doris-demo/spring-jdbc-demo/src/main/resources/application.yml
Labels: area/build, approved, kind/license, reviewed

#7126 [enhancement] Optimize the fail logic of loading data when some backend failed
  be/src/exec/hdfs_file_reader.cpp
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
  be/test/olap/generic_iterators_test.cpp
Labels: area/load, approved, reviewed

#7000 [Lateral View] Multi lateral views map one TableFunctionNode
  fe/fe-core/src/main/java/org/apache/doris/analysis/LateralViewRef.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
  fe/fe-core/src/main/java/org/apache/doris/planner/TableFunctionNode.java
  fe/fe-core/src/test/java/org/apache/doris/planner/TableFunctionPlanTest.java
  gensrc/thrift/PlanNodes.thrift
Labels: area/sql

#6515 [Memory] BitShufflePageDecoder use memory allocated by ChunkAllocator instead of Faststring
  be/src/olap/rowset/segment_v2/bitshuffle_page.h
  be/src/runtime/memory/chunk_allocator.cpp
  be/src/runtime/memory/chunk_allocator.h
Labels: approved, reviewed

#7105 [BUG] fix profile not working with sql_cache enabled
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
Labels: kind/bug, approved, area/sql/cache, reviewed

#7115 Update members.md
  docs/zh-CN/community/members.md
Labels: kind/documentation, approved, reviewed

#7108 [Bug] Fix the incompatibility of sql mode between Doris and MySQL
  fe/fe-core/src/main/java/org/apache/doris/analysis/ExpressionFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SysVariableDesc.java
  fe/fe-core/src/main/java/org/apache/doris/qe/VariableVarConverters.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/SetVariableTest.java
Labels: kind/bug, area/mysql-compatibility, approved, reviewed

#7127 correct getLogger argument
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/RewriteEncryptKeyRule.java
Labels: good first issue, approved, reviewed, kind/typo

#7128 [Dependency] Add breakpad for minidump
  thirdparty/CHANGELOG.md
  thirdparty/build-thirdparty.sh
  thirdparty/vars.sh
Labels: area/dependency, approved, reviewed

#7136 [Doc] Fix typo in CONTRIBUTING.md and CONTRIBUTING_CN.md
  CONTRIBUTING.md
  CONTRIBUTING_CN.md
Labels: good first issue, kind/documentation, approved, reviewed

#7137 remove Invalid code
  fe/fe-core/src/main/java/org/apache/doris/httpv2/restv2/ImportAction.java
Labels: approved, reviewed

#7138 [Binlog]Add how to open binlog load to the error message
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateDataSyncJobStmt.java
Labels: approved, reviewed, area/mysql-binlog

#7140 [Bug] Do not allow drop or create root user
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateUserStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/DropUserStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/UserIdentity.java
  fe/fe-core/src/test/java/org/apache/doris/mysql/privilege/AuthTest.java
Labels: kind/bug, approved, reviewed

#6883 support bitmap binary data from hive in spark load
  docs/en/administrator-guide/load-data/spark-load-manual.md
  docs/zh-CN/administrator-guide/load-data/spark-load-manual.md
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkLoadPendingTask.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/BitmapValue.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/DppUtils.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/SparkDpp.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/etl/SparkEtlJob.java
Labels: kind/feature, approved, area/spark-load, reviewed

#7087 add replica num limit per tablet
  docs/en/administrator-guide/config/fe_config.md
  docs/zh-CN/administrator-guide/config/fe_config.md
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/PropertyAnalyzer.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/DynamicPartitionTableTest.java
Labels: approved, reviewed

#7119 extract duplicate code to writePropertiesToFile
  fe/fe-core/src/main/java/org/apache/doris/persist/Storage.java
Labels: approved, kind/refactor, reviewed

#7124 [Feature] Add minidump support
  be/CMakeLists.txt
  be/src/common/config.h
  be/src/runtime/CMakeLists.txt
  be/src/runtime/minidump.cpp
  be/src/runtime/minidump.h
  be/src/service/doris_main.cpp
  be/test/runtime/CMakeLists.txt
  be/test/runtime/minidump_test.cpp
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/developer-guide/minidump.md
  docs/zh-CN/developer-guide/minidump.md
Labels: kind/feature, approved, reviewed

#7143 [Export] Fix Export task automatic retry always fail
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
Labels: kind/bug, approved, area/export, reviewed

#7144 bugfix: ReportProfile
  be/src/runtime/plan_fragment_executor.cpp
Labels: approved, reviewed

#7161 [Build] Fix build error caused by Inaccessible pentaho-aggdesigner-algorithm jar
  fe/pom.xml
Labels: approved, reviewed

#7030 [Feature] Print peak memory use of all backend after query in audit log
  be/src/runtime/buffer_control_block.h
  be/src/runtime/mem_tracker.h
  be/src/runtime/plan_fragment_executor.cpp
  be/src/runtime/plan_fragment_executor.h
  be/src/runtime/query_statistics.cpp
  be/src/runtime/query_statistics.h
  be/src/runtime/result_sink.cpp
  be/src/runtime/runtime_state.cpp
  be/src/runtime/runtime_state.h
  fe/fe-core/src/main/java/org/apache/doris/plugin/AuditEvent.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  gensrc/proto/data.proto
  gensrc/thrift/PaloInternalService.thrift
Labels: kind/enhancement, approved, reviewed

#7162 Update multi-tenant.md
  docs/en/administrator-guide/multi-tenant.md
Labels: good first issue, approved, reviewed

#7172 [Memory] fix BUG crash when ~BitShufflePageDecoder destroys uninitialized chunk
  be/src/olap/rowset/segment_v2/bitshuffle_page.h
  be/src/runtime/memory/chunk.h
  be/src/runtime/memory/chunk_allocator.cpp
Labels: kind/bug, approved, reviewed

#6979 [Memory] Add a method to get doris current memory usage and Limt memoey usage when consume
  be/src/exec/hash_table.cpp
  be/src/exec/partitioned_hash_table.cc
  be/src/runtime/buffered_block_mgr2.cc
  be/src/runtime/bufferpool/reservation_tracker.cc
  be/src/runtime/exec_env_init.cpp
  be/src/runtime/mem_pool.cpp
  be/src/runtime/mem_tracker.h
  be/src/service/doris_main.cpp
  be/src/util/mem_info.cpp
  be/src/util/mem_info.h
  be/src/util/parse_util.cpp
  be/src/util/parse_util.h
  be/src/util/system_metrics.cpp
  be/test/exec/hash_table_test.cpp
  be/test/olap/column_reader_test.cpp
  be/test/olap/schema_change_test.cpp
  be/test/runtime/mem_limit_test.cpp
  be/test/util/parse_util_test.cpp
Labels: kind/enhancement, approved, area/memory-consumption, reviewed

#7134 [enhancement] display load bytes in show load stmt
  be/src/exec/tablet_sink.cpp
  be/src/runtime/fragment_mgr.cpp
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BrokerLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadManager.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/DppResult.java
  gensrc/thrift/FrontendService.thrift
Labels: kind/enhancement, approved, reviewed

#7190 [doc]Created commit-format-specification.md
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/developer-guide/commit-format-specification.md
  docs/zh-CN/developer-guide/commit-format-specification.md
Labels: approved, reviewed

#7025 Add tablets number limit to affend wrong usage
  docs/en/administrator-guide/config/fe_config.md
  docs/zh-CN/administrator-guide/config/fe_config.md
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Database.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/common/FeConstants.java
Labels: approved, area/config, reviewed

#7054 [Feature] Refactor predicate function creator
  be/src/exprs/CMakeLists.txt
  be/src/exprs/bloomfilter_predicate.cpp
  be/src/exprs/bloomfilter_predicate.h
  be/src/exprs/create_predicate_function.h
  be/src/exprs/hybrid_map.h
  be/src/exprs/hybrid_set.cpp
  be/src/exprs/hybrid_set.h
  be/src/exprs/in_predicate.cpp
  be/src/exprs/in_predicate.h
  be/src/exprs/minmax_predicate.h
  be/src/exprs/runtime_filter.cpp
  be/src/olap/bloom_filter_predicate.cpp
  be/test/exprs/bloom_filter_predicate_test.cpp
  be/test/exprs/hybrid_set_test.cpp
  be/test/olap/bloom_filter_column_predicate_test.cpp
Labels: approved, reviewed

#7159 [Bug] fix core dump when enable_vectorized_engine open
  be/src/exec/exec_node.cpp
Labels: approved, reviewed

#7173 [doc] add FAQ document
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/developer-guide/minidump.md
  docs/en/faq/faq.md
  docs/zh-CN/developer-guide/minidump.md
  docs/zh-CN/faq/faq.md
Labels: kind/documentation, approved, reviewed

#7174 [doc] Add build-dev image 1.4.2 to compilation document
  docs/en/installing/compilation.md
  docs/zh-CN/installing/compilation.md
Labels: kind/documentation, approved, reviewed

#7181 [Bug] Fix mem limit -1 in partition aggregate node
  be/src/exec/partitioned_aggregation_node.cc
  be/src/runtime/runtime_state.h
Labels: kind/enhancement, approved, reviewed

#7197 [Fix compile bug] could not find protobuf lib during compile
  thirdparty/build-thirdparty.sh
Labels: approved, reviewed

#7151 Optimize bitmap function count, use roaring cardinality method
  be/src/exprs/bitmap_function.cpp
  be/src/util/bitmap_value.h
  be/test/exprs/bitmap_function_test.cpp
Labels: kind/enhancement, approved, reviewed

#7221 [Bug] fix core dump at some bitmap function
  be/src/util/bitmap_value.h
Labels: kind/bug, approved, reviewed

#7148 [Lateral View] Pruning output slot of TableFunctionNode
  fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/BaseTableRef.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/Expr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/LateralViewRef.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SlotRef.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/TableName.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
  fe/fe-core/src/main/java/org/apache/doris/planner/TableFunctionNode.java
  fe/fe-core/src/test/java/org/apache/doris/planner/TableFunctionPlanTest.java
  gensrc/thrift/PlanNodes.thrift
Labels: area/sql/planner, approved, reviewed

#7157 [optimize] optimize get_json_xx function
  be/src/exprs/json_functions.cpp
  be/src/exprs/json_functions.h
Labels: kind/enhancement, approved, reviewed

#7205 fix preaggregation reason error
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
Labels: kind/bug, area/sql/planner, approved, reviewed

#7215 [docs] Refine documents for commit message tags.
  docs/en/developer-guide/commit-format-specification.md
  docs/zh-CN/developer-guide/commit-format-specification.md
Labels: approved, reviewed

#7216 [Feature]. Improve DeltaWriter's performance.
  be/src/olap/delta_writer.cpp
  be/src/olap/delta_writer.h
  be/src/runtime/tablets_channel.cpp
  be/test/runtime/load_channel_mgr_test.cpp
Labels: kind/enhancement, area/load, approved, reviewed

#7217 [fix](alter) Fix bug that partition column of a unique key table can be modified
  fe/fe-core/src/main/java/org/apache/doris/alter/MaterializedViewHandler.java
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
  fe/fe-core/src/test/java/org/apache/doris/alter/AlterTest.java
Labels: kind/bug, approved, area/alter, reviewed

#7224 [Bug] Fix the bug reader call `_capture_rs_readers` function twice
  be/src/olap/reader.cpp
Labels: kind/bug, approved, reviewed

#7244 [docs](release) Update download page to add release 0.15
  docs/en/community/release-process.md
  docs/en/downloads/downloads.md
  docs/zh-CN/community/release-process.md
  docs/zh-CN/downloads/downloads.md
Labels: area/community, kind/documentation, approved, reviewed

#7253 update 0.14 release date
  docs/en/downloads/downloads.md
  docs/zh-CN/downloads/downloads.md
Labels: good first issue, kind/documentation, approved, reviewed

#7193 [fix](broker-load) BE may crash when using preceding filter in broker or routine load
  be/src/exec/base_scanner.cpp
  be/src/exec/base_scanner.h
  be/src/exec/broker_scan_node.cpp
  be/src/exec/broker_scan_node.h
  be/src/exec/broker_scanner.cpp
  be/src/exec/broker_scanner.h
  be/src/exec/json_scanner.cpp
  be/src/exec/json_scanner.h
  be/src/exec/orc_scanner.cpp
  be/src/exec/orc_scanner.h
  be/src/exec/parquet_scanner.cpp
  be/src/exec/parquet_scanner.h
  be/src/olap/push_handler.cpp
  be/src/olap/push_handler.h
  be/test/exec/broker_scanner_test.cpp
  be/test/exec/multi_bytes_separator_test.cpp
  be/test/exec/orc_scanner_test.cpp
Labels: kind/bug, area/load, approved, reviewed

#7155 [Config] Support disable query and load for backend to make Doris more robust and set default value to 1 for max_query_retry_time
  docs/en/administrator-guide/config/fe_config.md
  docs/en/sql-reference/sql-statements/Administration/ALTER SYSTEM.md
  docs/zh-CN/administrator-guide/config/fe_config.md
  docs/zh-CN/sql-reference/sql-statements/Administration/ALTER SYSTEM.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/AddBackendClause.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ModifyBackendClause.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/MetadataViewer.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Tablet.java
  fe/fe-core/src/main/java/org/apache/doris/clone/BackendLoadStatistic.java
  fe/fe-core/src/main/java/org/apache/doris/clone/ColocateTableCheckerAndBalancer.java
  fe/fe-core/src/main/java/org/apache/doris/clone/PartitionRebalancer.java
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletSchedCtx.java
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletScheduler.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/org/apache/doris/http/rest/LoadAction.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/LoadAction.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/util/LoadSubmitter.java
  fe/fe-core/src/main/java/org/apache/doris/journal/bdbje/BDBJEJournal.java
  fe/fe-core/src/main/java/org/apache/doris/load/ExportJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/Load.java
  fe/fe-core/src/main/java/org/apache/doris/planner/BrokerScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/InsertStreamTxnExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/MultiLoadMgr.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SimpleScheduler.java
  fe/fe-core/src/main/java/org/apache/doris/system/Backend.java
  fe/fe-core/src/main/java/org/apache/doris/system/SystemInfoService.java
  fe/fe-core/src/main/java/org/apache/doris/task/ExportPendingTask.java
  fe/fe-core/src/test/java/org/apache/doris/backup/RestoreJobTest.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/ModifyBackendTest.java
  fe/fe-core/src/test/java/org/apache/doris/clone/ColocateTableCheckerAndBalancerTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/sync/canal/CanalSyncDataTest.java
  fe/fe-core/src/test/java/org/apache/doris/qe/MultiLoadMgrTest.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/DemoMultiBackendsTest.java
Labels: kind/feature, approved, area/config, reviewed
