Repository apache/doris, pull requests merged in 2021-09, with the labels that each got.

#6534 [Community] Add new template for issues
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateRoutineLoadStmt.java
Labels: area/community, approved, reviewed

#6524 [Doc] Update stream-load-manual.md
  docs/en/administrator-guide/load-data/stream-load-manual.md
  docs/zh-CN/administrator-guide/load-data/stream-load-manual.md
Labels: approved, reviewed

#6538 [BUG] fix bugs with string type
  be/src/olap/field.h
  be/src/runtime/free_pool.hpp
  be/src/runtime/row_batch.cpp
  fe/fe-core/src/main/java/org/apache/doris/analysis/LiteralExpr.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/AggregateType.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/ListPartitionInfo.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/PartitionKey.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/CreateRoutineLoadStmtTest.java
Labels: kind/bug, area/storage, approved, reviewed

#6506 [Feature] Support for storage layer benchmark
  be/CMakeLists.txt
  be/test/olap/tablet_schema_helper.h
  be/test/test_util/test_util.cpp
  be/test/test_util/test_util.h
  be/test/tools/CMakeLists.txt
  be/test/tools/benchmark_tool.cpp
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/developer-guide/benchmark-tool.md
  docs/zh-CN/developer-guide/benchmark-tool.md
  run-be-ut.sh
  thirdparty/build-thirdparty.sh
  thirdparty/vars.sh
Labels: approved, reviewed, area/tools

#6504 [Feature]support three functions of json
  be/src/exprs/json_functions.cpp
  be/src/exprs/json_functions.h
  be/test/exprs/json_function_test.cpp
  docs/en/sql-reference/sql-functions/string-functions/json_array.md
  docs/en/sql-reference/sql-functions/string-functions/json_object.md
  docs/en/sql-reference/sql-functions/string-functions/json_quote.md
  docs/zh-CN/sql-reference/sql-functions/string-functions/json_array.md
  docs/zh-CN/sql-reference/sql-functions/string-functions/json_object.md
  docs/zh-CN/sql-reference/sql-functions/string-functions/json_quote.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java
  gensrc/script/doris_builtins_functions.py
Labels: approved, reviewed

#6455 [CodeRefactor]Remove useless code for Segment V2
  be/src/olap/generic_iterators.cpp
  be/src/olap/rowset/segment_v2/column_reader.cpp
  be/src/olap/rowset/segment_v2/column_reader.h
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
Labels: approved, reviewed

#5781 [Compaction][ThreadPool]Support adjust compaction threads num at runtime
  be/src/common/config.h
  be/src/olap/olap_server.cpp
  be/src/util/threadpool.cpp
  be/src/util/threadpool.h
  be/test/util/threadpool_test.cpp
Labels: kind/enhancement, approved, area/compact, reviewed

#6480 fix(sparkload): bitmap deep copy in `or` operator
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/BitmapValue.java
  fe/spark-dpp/src/test/java/org/apache/doris/load/loadv2/dpp/BitmapValueTest.java
Labels: kind/bug, approved, area/spark-load, reviewed

#6546 Update load-json-format.md
  docs/zh-CN/administrator-guide/load-data/load-json-format.md
Labels: good first issue, kind/documentation, approved, reviewed

#6559 Fix colocate agg error when group of colocate table is unstable
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
Labels: kind/bug, area/colocated, approved, reviewed

#6557 [bug] Fix the bug that http redirects to master cannot be authenticated, and redirect several http interfaces to master.
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/RestBaseController.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/manager/NodeAction.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/restv2/StatisticAction.java
Labels: kind/bug, approved, area/httpv2, reviewed, area/manager

#6501 add config to support long table name
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/common/FeNameFormat.java
Labels: area/catalog, approved, area/config, reviewed

#6518 [Enhance] Add a rewrite rule of compoundPredicate 'OR' 'AND' to hit prefix index
  fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/CompoundPredicateWriteRule.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: kind/enhancement, area/sql/planner, approved, reviewed

#6522 [Metric] Add more metrics for FE checkpoint operation
  fe/fe-core/src/main/java/org/apache/doris/common/CheckpointException.java
  fe/fe-core/src/main/java/org/apache/doris/master/Checkpoint.java
  fe/fe-core/src/main/java/org/apache/doris/metric/MetricRepo.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
Labels: approved, area/metrics, reviewed

#6539 Support concurrent export of query results
  be/src/exec/data_sink.cpp
  be/src/exec/data_sink.h
  be/src/exec/s3_writer.cpp
  be/src/exec/s3_writer.h
  be/src/runtime/CMakeLists.txt
  be/src/runtime/data_stream_sender.cpp
  be/src/runtime/data_stream_sender.h
  be/src/runtime/file_result_writer.cpp
  be/src/runtime/file_result_writer.h
  be/src/runtime/plan_fragment_executor.cpp
  be/src/runtime/result_file_sink.cpp
  be/src/runtime/result_file_sink.h
  be/src/runtime/result_sink.cpp
  docs/en/administrator-guide/outfile.md
  docs/zh-CN/administrator-guide/outfile.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateRoutineLoadStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/OutFileClause.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/fe-core/src/main/java/org/apache/doris/backup/S3Storage.java
  fe/fe-core/src/main/java/org/apache/doris/load/ExportJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadingTaskPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/load/update/UpdatePlanner.java
  fe/fe-core/src/main/java/org/apache/doris/planner/ExchangeNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PlanFragment.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PlanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/Planner.java
  fe/fe-core/src/main/java/org/apache/doris/planner/ResultFileSink.java
  fe/fe-core/src/main/java/org/apache/doris/planner/ResultSink.java
  fe/fe-core/src/main/java/org/apache/doris/planner/StreamLoadPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/CreateRoutineLoadStmtTest.java
  gensrc/thrift/DataSinks.thrift
Labels: kind/enhancement, approved, api-review, area/outfile, reviewed

#6552 [Bug] [Truncate] Fix tablet number is different between the new partition and base partition after truncate operation
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/TruncateTableTest.java
Labels: kind/bug, area/catalog, approved, reviewed

#6564 [Bug]fix pad function wrong result when len.val==str_char_size
  be/src/exprs/string_functions.cpp
  be/test/exprs/string_functions_test.cpp
Labels: kind/bug, approved, area/sql/function, reviewed

#6566 [Optimize] Remove some unused code to reduce lock contention
  be/src/exec/blocking_join_node.cpp
  be/src/exec/hash_join_node.cpp
  be/src/exec/olap_scan_node.cpp
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/fragment_mgr.h
  be/src/runtime/plan_fragment_executor.cpp
  be/src/runtime/plan_fragment_executor.h
  be/src/runtime/runtime_state.cpp
  be/src/util/runtime_profile.cpp
  be/src/util/runtime_profile.h
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadTaskScheduler.java
Labels: kind/enhancement, Performance, approved, reviewed

#6579 [Feature] Support Integer-Types value in like predicate
  fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/LikePredicate.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/RewriteLikePredicateRule.java
  fe/fe-core/src/test/java/org/apache/doris/rewrite/ExtractCommonFactorsRuleFunctionTest.java
Labels: kind/enhancement, area/sql/planner, approved, reviewed

#6553 [Job Clean] Sort out the cleanup logic of historical jobs
  be/src/common/config.h
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/load/DeleteHandler.java
  fe/fe-core/src/main/java/org/apache/doris/load/ExportJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/ExportMgr.java
  fe/fe-core/src/main/java/org/apache/doris/load/Load.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadManager.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/TruncateTableTest.java
Labels: kind/enhancement, approved, reviewed

#6544 fix bug colocate join table can't repaired
  fe/fe-core/src/main/java/org/apache/doris/catalog/Tablet.java
Labels: good first issue, area/colocated, area/tablet-scheduler

#6572 [Doc] fix irregular documents (like/ not like/ regexp.md)
  docs/en/sql-reference/sql-functions/string-functions/like/like.md
  docs/en/sql-reference/sql-functions/string-functions/like/not_like.md
  docs/en/sql-reference/sql-functions/string-functions/regexp/not_regexp.md
  docs/en/sql-reference/sql-functions/string-functions/regexp/regexp.md
  docs/en/sql-reference/sql-functions/string-functions/regexp/regexp_replace.md
  docs/zh-CN/sql-reference/sql-functions/string-functions/like/like.md
  docs/zh-CN/sql-reference/sql-functions/string-functions/like/not_like.md
  docs/zh-CN/sql-reference/sql-functions/string-functions/regexp/not_regexp.md
  docs/zh-CN/sql-reference/sql-functions/string-functions/regexp/regexp.md
Labels: kind/documentation, approved, reviewed

#6591 [bug] Fix dataTables bootstrap js version differ.
  fe/fe-core/src/main/java/org/apache/doris/http/action/WebBaseAction.java
Labels: good first issue, approved, area/fe-http-server, reviewed

#6594 [BUG] fix some bugs of String type
  be/src/exec/exec_node.h
  be/src/exec/partitioned_aggregation_node.cc
  be/src/exprs/runtime_filter.cpp
  be/src/olap/aggregate_func.h
  be/src/olap/bloom_filter_predicate.cpp
  be/src/olap/delete_handler.cpp
  be/src/olap/field.h
  be/src/olap/push_handler.cpp
  be/src/runtime/buffered_tuple_stream3.cc
  be/src/runtime/buffered_tuple_stream3.h
  be/src/runtime/row_batch.cpp
  be/src/runtime/row_batch.h
  be/src/runtime/string_value.hpp
  be/src/runtime/string_value_ir.cpp
  be/src/util/sse2neo.h
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateTableStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/ColumnType.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionSet.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/PrimitiveType.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/ScalarType.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/jflex/sql_scanner.flex
  gensrc/thrift/PlanNodes.thrift
Labels: kind/bug, area/storage, approved, reviewed

#6599 [BUG] Fix copy in bitmap
  be/src/util/bitmap_value.h
Labels: kind/enhancement, approved, reviewed

#6593 add doc for storage_root_path
  docs/en/administrator-guide/config/be_config.md
  docs/en/installing/install-deploy.md
  docs/zh-CN/administrator-guide/config/be_config.md
  docs/zh-CN/installing/install-deploy.md
Labels: approved, reviewed

#6586 [Bugs] Fix some bugs
  be/src/common/utils.h
  be/src/exec/base_scanner.cpp
  be/src/exec/base_scanner.h
  be/src/exec/hash_join_node.h
  be/src/exec/hash_join_node_ir.cpp
  be/src/exec/olap_scanner.cpp
  be/src/exprs/string_functions.cpp
  be/src/runtime/file_result_writer.h
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/result_file_sink.h
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletSchedCtx.java
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletScheduler.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/common/FeConstants.java
  fe/fe-core/src/main/java/org/apache/doris/common/FeNameFormat.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/DynamicPartitionUtil.java
  fe/fe-core/src/main/java/org/apache/doris/journal/bdbje/BDBEnvironment.java
  fe/fe-core/src/main/java/org/apache/doris/load/DeleteHandler.java
  fe/fe-core/src/main/java/org/apache/doris/load/DeleteJob.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/rpc/BackendServiceProxy.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/DynamicPartitionTableTest.java
  fe/fe-core/src/test/java/org/apache/doris/common/FeNameFormatTest.java
Labels: kind/bug, approved, reviewed

#6268 [BUG][Profile] Fixed the problem that BE's profile could not add chil…
  be/src/util/runtime_profile.cpp
Labels: kind/bug, approved, area/profile, reviewed

#6102 Support create table as select
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateTableAsSelectStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateTableStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/qe/DdlExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/CreateTableAsSelectStmtTest.java
Labels: kind/feature, approved, reviewed

#6601 [Sprak-Doris-Connector] support boolean data type
  be/src/runtime/fragment_mgr.cpp
  be/src/util/arrow/row_batch.cpp
Labels: area/spark-connector, approved, reviewed

#6615 [BUG] fix insert null as string type may coredump
  be/src/olap/field.h
  be/src/olap/rowset/segment_v2/binary_plain_page.h
  be/src/olap/rowset/segment_v2/encoding_info.cpp
  be/src/util/block_compression.cpp
Labels: approved, reviewed

#6627 [UT] fix fe UT failed due to rename string to text
  fe/fe-core/src/test/java/org/apache/doris/analysis/CreateTableAsSelectStmtTest.java
Labels: approved, reviewed

#6634 fix librdkafka depends on high version of glibc
  be/CMakeLists.txt
  thirdparty/build-thirdparty.sh
Labels: area/dependency, approved, reviewed

#6626 Do not print exception in fe.out
  fe/fe-core/src/main/java/org/apache/doris/http/HttpServerHandler.java
Labels: approved, reviewed

#6605 [Bug] fix `replace` function bug
  be/src/exprs/string_functions.cpp
  be/test/exprs/string_functions_test.cpp
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
Labels: kind/bug, SQL Bug, kind/documentation, approved, area/sql/function, reviewed

#6636 [Bug] Fix aes_decrypt to handle null input correctly.
  be/src/exprs/encryption_functions.cpp
  be/test/exprs/encryption_functions_test.cpp
Labels: kind/bug, approved, reviewed

#6643 support change column type from decimal to string
  be/src/olap/rowset/segment_v2/encoding_info.cpp
  be/src/runtime/data_stream_recvr.cc
  be/src/runtime/data_stream_sender.cpp
  be/src/runtime/row_batch.cpp
  be/src/runtime/row_batch.h
  fe/fe-core/src/main/java/org/apache/doris/catalog/Column.java
Labels: kind/bug, approved, reviewed

#6637 [config] use `thrift_rpc_timeout_ms` config replace hard code value
  be/src/common/config.h
  be/src/exec/broker_reader.cpp
  be/src/exec/broker_writer.cpp
  be/src/runtime/broker_mgr.cpp
  be/src/util/broker_storage_backend.cpp
Labels: area/broker, approved, area/config, reviewed

#6638 fix tabletScore expression
  docs/en/administrator-guide/config/be_config.md
  docs/zh-CN/administrator-guide/config/be_config.md
Labels: approved, reviewed

#6668 [Bug] Fix the bug of generating sql_key in SqlCache
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/SqlCache.java
Labels: approved, reviewed

#6646 [Meta][Refactor] Use lambda expressions to save Image
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/common/MetaWriter.java
Labels: kind/enhancement, approved, reviewed, area/metadata

#6653 [PLUGIN] optimize output msg when auditlog plugin error
  fe_plugins/auditloader/src/main/java/org/apache/doris/plugin/audit/DorisStreamLoader.java
Labels: kind/enhancement, approved, area/plugin, reviewed

#6567 [Performance] Improve show proc statistic #6477
  fe/fe-core/src/main/java/org/apache/doris/common/proc/IncompleteTabletsProcNode.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/StatisticProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/task/AgentTaskQueue.java
Labels: kind/enhancement, area/catalog, approved, reviewed

#6677 Download hashes and signatures use "downloads.apache.org"
  docs/en/downloads/downloads.md
  docs/zh-CN/downloads/downloads.md
Labels: kind/documentation, approved, reviewed

#6418 [Enhance] [Binlog] Reduce thread number of SyncJob to save resources
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/ChannelDescription.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/load/sync/SyncChannel.java
  fe/fe-core/src/main/java/org/apache/doris/load/sync/SyncChannelCallback.java
  fe/fe-core/src/main/java/org/apache/doris/load/sync/SyncChannelHandle.java
  fe/fe-core/src/main/java/org/apache/doris/load/sync/SyncChecker.java
  fe/fe-core/src/main/java/org/apache/doris/load/sync/SyncJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/sync/SyncLifeCycle.java
  fe/fe-core/src/main/java/org/apache/doris/load/sync/canal/CanalSyncChannel.java
  fe/fe-core/src/main/java/org/apache/doris/load/sync/canal/CanalSyncDataConsumer.java
  fe/fe-core/src/main/java/org/apache/doris/load/sync/canal/CanalSyncJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/sync/canal/SyncCanalClient.java
  fe/fe-core/src/main/java/org/apache/doris/load/sync/position/PositionMeta.java
  fe/fe-core/src/main/java/org/apache/doris/qe/InsertStreamTxnExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/task/SerialExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/task/SerialExecutorService.java
  fe/fe-core/src/main/java/org/apache/doris/task/SyncPendingTask.java
  fe/fe-core/src/main/java/org/apache/doris/task/SyncTask.java
  fe/fe-core/src/main/java/org/apache/doris/task/SyncTaskPool.java
  fe/fe-core/src/test/java/org/apache/doris/load/sync/canal/CanalSyncDataTest.java
  fe/fe-core/src/test/java/org/apache/doris/task/SerialExecutorServiceTest.java
Labels: kind/enhancement, approved, reviewed, area/mysql-binlog

#6665 [Bug] Fix some bugs
  be/src/exec/tablet_sink.cpp
  be/src/olap/schema_change.cpp
  be/src/olap/tablet.cpp
  fe/fe-core/AlterRoutineLoadOperationLogTest
  fe/fe-core/diskInfoTest
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowLoadStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowTabletStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Replica.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Tablet.java
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletSchedCtx.java
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletScheduler.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/ClusterLoadStatByTag.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/StatisticProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/load/LoadChecker.java
  fe/fe-core/src/main/java/org/apache/doris/planner/DistributedPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ShowLoadStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/clone/TabletSchedCtxTest.java
Labels: kind/bug, approved, reviewed

#6699 [Bug] Fix some memory bugs
  be/src/common/config.h
  be/src/exec/tablet_sink.cpp
  be/src/http/action/mini_load.cpp
  be/src/http/action/stream_load.cpp
  be/src/olap/collect_iterator.cpp
  be/src/olap/collect_iterator.h
  be/src/olap/delta_writer.cpp
  be/src/olap/delta_writer.h
  be/src/olap/olap_define.h
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/message_body_sink.cpp
  be/src/runtime/message_body_sink.h
  be/src/runtime/routine_load/data_consumer_group.cpp
  be/src/runtime/routine_load/routine_load_task_executor.cpp
  be/src/runtime/stream_load/stream_load_context.h
  be/src/runtime/stream_load/stream_load_executor.cpp
  be/src/runtime/stream_load/stream_load_pipe.h
  be/src/service/internal_service.cpp
  be/test/runtime/stream_load_pipe_test.cpp
  docs/en/administrator-guide/config/be_config.md
  docs/zh-CN/administrator-guide/config/be_config.md
  fe/fe-core/src/main/java/org/apache/doris/load/update/UpdateStmtExecutor.java
Labels: kind/bug, Memory Leak, approved, reviewed

#6667 [bug] Fix zone map init error for string type
  be/src/common/config.h
  be/src/exec/olap_scan_node.cpp
  be/src/olap/field.h
  be/src/runtime/tuple.cpp
Labels: kind/bug, approved, reviewed

#6688 Fix a typo
  docs/zh-CN/extending-doris/flink-doris-connector.md
Labels: approved, reviewed

#6644 Support hdfs in select outfile clause
  be/src/exec/CMakeLists.txt
  be/src/exec/hdfs_writer.cpp
  be/src/exec/hdfs_writer.h
  be/src/runtime/file_result_writer.cpp
  be/src/runtime/result_file_sink.cpp
  docs/en/administrator-guide/outfile.md
  docs/zh-CN/administrator-guide/outfile.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/OutFileClause.java
  fe/fe-core/src/main/java/org/apache/doris/backup/HDFSStorage.java
Labels: kind/feature, approved, area/outfile, reviewed

#6729 [Bug] Fix bug that DROP SCHEMA will forcibly drop database
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/test/java/org/apache/doris/catalog/DropDbTest.java
Labels: kind/bug, area/catalog, approved, reviewed

#6570 Spark demo
  samples/doris-demo/spark-demo/pom.xml
  samples/doris-demo/spark-demo/src/main/java/org/apache/doris/demo/spark/constant/SparkToDorisConstants.java
  samples/doris-demo/spark-demo/src/main/java/org/apache/doris/demo/spark/demo/connector/SparkDorisConnectorDemo.java
  samples/doris-demo/spark-demo/src/main/java/org/apache/doris/demo/spark/demo/hdfs/MyForeachPartitionFunction.java
  samples/doris-demo/spark-demo/src/main/java/org/apache/doris/demo/spark/demo/hdfs/SparkHdfsToDorisDemo.java
  samples/doris-demo/spark-demo/src/main/java/org/apache/doris/demo/spark/demo/kafka/SparkKafkaToDorisDemo.java
  samples/doris-demo/spark-demo/src/main/java/org/apache/doris/demo/spark/sink/DorisSink.java
  samples/doris-demo/spark-demo/src/main/java/org/apache/doris/demo/spark/util/DorisStreamLoad.java
  samples/doris-demo/spark-demo/src/main/java/org/apache/doris/demo/spark/vo/TestVo.java
Labels: approved, reviewed, area/samples

#6648 [bug] fix backup bug when comparisons case sensitive
  fe/fe-core/src/main/java/org/apache/doris/analysis/AbstractBackupTableRefClause.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/BackupTest.java
Labels: approved, reviewed

#6655 doris flink connector do not support flink 1.13, refactor doris sink format， not use GenericRowData. use RowData::FieldGetter
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicOutputFormat.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableFactory.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSink.java
Labels: approved, area/flink-connector, reviewed

#6662 [Improvement] Try to finish transaction if all backends of unfinished tasks have been dead
  fe/fe-core/src/main/java/org/apache/doris/transaction/PublishVersionDaemon.java
Labels: area/load, approved, reviewed

#6666 [DOC]Add the description document of the error code returned by the OLAP function on the BE side
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/administrator-guide/operation/be-olap-error-code.md
  docs/zh-CN/administrator-guide/operation/be-olap-error-code.md
Labels: kind/documentation, approved, reviewed

#6686 Table schema add aggregation type information
  docs/en/administrator-guide/http-actions/fe/table-schema-action.md
  docs/zh-CN/administrator-guide/http-actions/fe/table-schema-action.md
  fe/fe-core/src/main/java/org/apache/doris/http/rest/TableSchemaAction.java
Labels: approved, api-review, area/httpv2, reviewed

#6698 [Doc] batch change CN/EN sql-functions single quote in markdown
  docs/en/sql-reference/sql-functions/date-time-functions/curdate.md
  docs/en/sql-reference/sql-functions/date-time-functions/date_format.md
  docs/en/sql-reference/sql-functions/date-time-functions/datediff.md
  docs/en/sql-reference/sql-functions/date-time-functions/dayname.md
  docs/en/sql-reference/sql-functions/date-time-functions/dayofmonth.md
  docs/en/sql-reference/sql-functions/date-time-functions/dayofweek.md
  docs/en/sql-reference/sql-functions/date-time-functions/dayofyear.md
  docs/en/sql-reference/sql-functions/date-time-functions/month.md
  docs/en/sql-reference/sql-functions/date-time-functions/monthname.md
  docs/en/sql-reference/sql-functions/date-time-functions/now.md
  docs/en/sql-reference/sql-functions/date-time-functions/str_to_date.md
  docs/en/sql-reference/sql-functions/date-time-functions/timediff.md
  docs/en/sql-reference/sql-functions/date-time-functions/to_days.md
  docs/en/sql-reference/sql-functions/date-time-functions/weekofyear.md
  docs/en/sql-reference/sql-functions/spatial-functions/st_astext.md
  docs/en/sql-reference/sql-functions/spatial-functions/st_geometryfromtext.md
  docs/en/sql-reference/sql-functions/spatial-functions/st_linefromtext.md
  docs/en/sql-reference/sql-functions/spatial-functions/st_polygon.md
  docs/en/sql-reference/sql-functions/string-functions/bit_length.md
  docs/en/sql-reference/sql-functions/string-functions/concat_ws.md
  docs/en/sql-reference/sql-functions/string-functions/get_json_double.md
  docs/en/sql-reference/sql-functions/string-functions/get_json_int.md
  docs/en/sql-reference/sql-functions/string-functions/get_json_string.md
  docs/en/sql-reference/sql-functions/string-functions/instr.md
  docs/en/sql-reference/sql-functions/string-functions/left.md
  docs/en/sql-reference/sql-functions/string-functions/length.md
  docs/en/sql-reference/sql-functions/string-functions/locate.md
  docs/en/sql-reference/sql-functions/string-functions/lower.md
  docs/en/sql-reference/sql-functions/string-functions/lpad.md
  docs/en/sql-reference/sql-functions/string-functions/ltrim.md
  docs/en/sql-reference/sql-functions/string-functions/money_format.md
  docs/en/sql-reference/sql-functions/string-functions/repeat.md
  docs/en/sql-reference/sql-functions/string-functions/right.md
  docs/en/sql-reference/sql-functions/string-functions/rpad.md
  docs/en/sql-reference/sql-functions/string-functions/split_part.md
  docs/en/sql-reference/sql-functions/string-functions/strleft.md
  docs/en/sql-reference/sql-functions/string-functions/strright.md
  docs/zh-CN/sql-reference/sql-functions/string-functions/get_json_double.md
  docs/zh-CN/sql-reference/sql-functions/string-functions/get_json_int.md
  docs/zh-CN/sql-reference/sql-functions/string-functions/get_json_string.md
  docs/zh-CN/sql-reference/sql-functions/string-functions/money_format.md
  docs/zh-CN/sql-reference/sql-functions/string-functions/regexp/regexp_replace.md
  docs/zh-CN/sql-reference/sql-functions/string-functions/repeat.md
Labels: kind/documentation, approved, reviewed

#6702 [Optimize] Use compact mode to send query plan thrift data structure.
  be/src/service/internal_service.cpp
  be/src/service/internal_service.h
  docs/en/administrator-guide/config/fe_config.md
  docs/zh-CN/administrator-guide/config/fe_config.md
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/main/java/org/apache/doris/rpc/BackendServiceClient.java
  fe/fe-core/src/main/java/org/apache/doris/rpc/BackendServiceProxy.java
  gensrc/proto/internal_service.proto
Labels: kind/enhancement, area/sql/planner, approved, reviewed

#6705 [Bugs] Fix the bugs list of sync job
  fe/fe-core/src/main/java/org/apache/doris/analysis/ChannelDescription.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/LogKey.java
  fe/fe-core/src/main/java/org/apache/doris/load/sync/SyncChecker.java
  fe/fe-core/src/main/java/org/apache/doris/load/sync/SyncFailMsg.java
  fe/fe-core/src/main/java/org/apache/doris/load/sync/SyncJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/sync/SyncJobManager.java
  fe/fe-core/src/main/java/org/apache/doris/load/sync/SyncLifeCycle.java
  fe/fe-core/src/main/java/org/apache/doris/load/sync/canal/CanalSyncChannel.java
  fe/fe-core/src/main/java/org/apache/doris/load/sync/canal/CanalSyncJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/sync/model/Data.java
  fe/fe-core/src/main/java/org/apache/doris/task/SyncPendingTask.java
  fe/fe-core/src/test/java/org/apache/doris/load/sync/SyncJobManagerTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/sync/SyncJobTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/sync/canal/CanalSyncDataTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/sync/canal/CanalSyncJobTest.java
Labels: kind/bug, approved, reviewed, area/mysql-binlog

#6709 [Bug][Docs]Fix outfile docs for parquet
  docs/en/administrator-guide/outfile.md
  docs/zh-CN/administrator-guide/outfile.md
Labels: kind/documentation, approved, reviewed

#6718 [DOCS] improve docs
  docs/en/installing/install-deploy.md
  docs/zh-CN/installing/install-deploy.md
Labels: kind/documentation, approved, reviewed

#6733 [DOC]Add connection reset exception solution
  docs/en/administrator-guide/load-data/stream-load-manual.md
  docs/zh-CN/administrator-guide/load-data/stream-load-manual.md
Labels: kind/documentation, approved, reviewed

#6734 Update doris-on-es.md
  docs/zh-CN/extending-doris/doris-on-es.md
Labels: kind/documentation, approved, reviewed

#6582 handle bdb rollbackexception
  fe/fe-core/src/main/java/org/apache/doris/journal/bdbje/BDBEnvironment.java
  fe/fe-core/src/main/java/org/apache/doris/journal/bdbje/BDBJEJournal.java
Labels: kind/bug, good first issue, approved, area/bdbje, reviewed

#6736 [Bug] When using view, make toSql method generates the final sql
  fe/fe-core/src/main/java/org/apache/doris/analysis/InlineViewRef.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SetOperationStmt.java
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/SqlCache.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/SelectStmtTest.java
Labels: kind/bug, area/catalog, approved, reviewed

#6466 [Bug] Fix Tuple is null predicate may cause be cores
  fe/fe-core/src/main/java/org/apache/doris/analysis/TupleIsNullPredicate.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/TupleIsNullPredicateTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/PlannerTest.java
Labels: kind/bug, area/sql/execution, approved, reviewed

#6622 refactor olap_scan_node: discard boost, remove dynamic_cast
  be/src/exec/olap_common.h
  be/src/exec/olap_scan_node.cpp
  be/src/exec/olap_scan_node.h
Labels: good first issue, approved, kind/refactor, reviewed

#6695 [BUG] If new group name is the same as old group name when mod table colocate group name, the group has been in an unstable state
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/ColocateTableTest.java
Labels: kind/bug, area/colocated, approved, reviewed

#6748 Revert "[Enhancement] Modify the method of calculating compaction score"
  be/src/olap/rowset/rowset_meta.h
Labels: approved, kind/revert, area/compact, reviewed

#6708 [Bug] Fix resource tag bug and add documents
  .github/ISSUE_TEMPLATE/config.yml
  be/src/common/config.h
  be/src/exec/mysql_scanner.cpp
  be/src/exec/odbc_connector.cpp
  be/src/olap/rowset/alpha_rowset.cpp
  be/src/olap/rowset/alpha_rowset.h
  be/src/olap/rowset/beta_rowset.cpp
  be/src/olap/rowset/beta_rowset.h
  be/src/olap/rowset/rowset.h
  be/src/olap/tablet.cpp
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/administrator-guide/config/be_config.md
  docs/en/administrator-guide/config/fe_config.md
  docs/en/administrator-guide/multi-tenant.md
  docs/en/sql-reference-v2/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE.md
  docs/en/sql-reference/sql-statements/Account Management/SET PROPERTY.md
  docs/en/sql-reference/sql-statements/Administration/ALTER SYSTEM.md
  docs/en/sql-reference/sql-statements/Data Definition/CREATE TABLE.md
  docs/zh-CN/administrator-guide/config/be_config.md
  docs/zh-CN/administrator-guide/config/fe_config.md
  docs/zh-CN/administrator-guide/multi-tenant.md
  docs/zh-CN/sql-reference-v2/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE.md
  docs/zh-CN/sql-reference/sql-statements/Account Management/SET PROPERTY.md
  docs/zh-CN/sql-reference/sql-statements/Administration/ALTER SYSTEM.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/CREATE TABLE.md
  fe/fe-core/src/main/java/org/apache/doris/clone/ColocateTableCheckerAndBalancer.java
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletChecker.java
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletScheduler.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/BackendsProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/restv2/MetaInfoActionV2.java
  fe/fe-core/src/main/java/org/apache/doris/journal/JournalEntity.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/MysqlProto.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/UserProperty.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
  fe/fe-core/src/test/java/org/apache/doris/common/proc/BackendsProcDirTest.java
  fe/fe-core/src/test/java/org/apache/doris/common/proc/DbsProcDirTest.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/DemoMultiBackendsTest.java
Labels: kind/bug, kind/documentation, approved, area/config, area/resource-tag, reviewed

#6711 [docs] Update README.md
  README.md
Labels: approved, reviewed

#6554 [Dynamic Partition] reserve specific history periods by dynamic partition.
  docs/en/administrator-guide/dynamic-partition.md
  docs/en/administrator-guide/operation/doris-error-code.md
  docs/en/sql-reference-v2/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE.md
  docs/en/sql-reference/sql-statements/Data Definition/CREATE TABLE.md
  docs/zh-CN/administrator-guide/dynamic-partition.md
  docs/zh-CN/administrator-guide/operation/doris-error-code.md
  docs/zh-CN/sql-reference-v2/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/CREATE TABLE.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowDynamicPartitionStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/DynamicPartitionProperty.java
  fe/fe-core/src/main/java/org/apache/doris/clone/DynamicPartitionScheduler.java
  fe/fe-core/src/main/java/org/apache/doris/common/ErrorCode.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/DynamicPartitionUtil.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/RangeUtils.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/DynamicPartitionTableTest.java
Labels: kind/feature, approved, area/dynamic-partition, reviewed

#6740 [Fix] Flink connector support json import and use httpclient to streamlaod
  docs/en/extending-doris/flink-doris-connector.md
  docs/zh-CN/extending-doris/flink-doris-connector.md
  extension/flink-doris-connector/pom.xml
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicOutputFormat.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableFactory.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSink.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisStreamLoad.java
  extension/flink-doris-connector/src/test/java/org/apache/doris/flink/DorisSinkExample.java
Labels: approved, area/flink-connector, reviewed

#6761 [Feature] support spark connector sink stream data to doris
  docs/en/extending-doris/spark-doris-connector.md
  docs/zh-CN/extending-doris/spark-doris-connector.md
  extension/spark-doris-connector/pom.xml
  extension/spark-doris-connector/src/main/java/org/apache/doris/spark/CachedDorisStreamLoadClient.java
  extension/spark-doris-connector/src/main/java/org/apache/doris/spark/DorisStreamLoad.java
  extension/spark-doris-connector/src/main/java/org/apache/doris/spark/cfg/Settings.java
  extension/spark-doris-connector/src/main/java/org/apache/doris/spark/cfg/SparkSettings.java
  extension/spark-doris-connector/src/main/java/org/apache/doris/spark/rest/RestService.java
  extension/spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/DorisSourceProvider.scala
  extension/spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/DorisStreamWriter.scala
  extension/spark-doris-connector/src/test/scala/org/apache/doris/spark/sql/TestStreamSinkDoris.scala
Labels: kind/feature, area/spark-connector, approved, reviewed

#6769 [Bug] Fix bdbje getDatabaseNames() bug and scan node close bug
  be/src/exec/olap_scan_node.cpp
  be/src/runtime/routine_load/routine_load_task_executor.cpp
  docs/en/extending-doris/datax.md
  docs/en/installing/compilation.md
  docs/zh-CN/extending-doris/datax.md
  docs/zh-CN/installing/compilation.md
  fe/fe-core/src/main/java/org/apache/doris/PaloFe.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/NetUtils.java
  fe/fe-core/src/main/java/org/apache/doris/journal/bdbje/BDBJEJournal.java
  fe/fe-core/src/main/java/org/apache/doris/master/Checkpoint.java
Labels: kind/bug, kind/documentation, approved, area/bdbje, reviewed

#6580 [FOLLOWUP] create table like clause support copy rollup
  docs/en/sql-reference/sql-statements/Data Definition/CREATE TABLE LIKE.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/CREATE TABLE LIKE.md
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateTableLikeStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/CreateTableLikeTest.java
Labels: area/catalog, approved, kind/refactor, reviewed
