Repository apache/doris, pull requests merged in 2021-01, with the labels that each got.

#5092 [Performance Improve] Push Down _conjunct of 'A is NULL' and 'B is not NULL' to Storage Engine.
  be/src/exec/olap_common.h
  be/src/exec/olap_scan_node.cpp
  be/src/exec/olap_scan_node.h
  be/src/exec/olap_scanner.cpp
  be/src/exec/olap_scanner.h
  be/test/exec/CMakeLists.txt
  be/test/exec/olap_common_test.cpp
Labels: approved, kind/enhancement

#5172 [Bug-Fix] Fix the bug of `PERCENTILE_APPROX` return error result `nan` and add `PERCENTILE_APPROX` UT
  be/src/exprs/aggregate_functions.cpp
  be/test/exprs/percentile_approx_test.cpp
Labels: approved, kind/bug

#5180 fix some spelling mistakes and default vaule mistakes in document
  docs/en/administrator-guide/config/fe_config.md
  docs/en/administrator-guide/operation/tablet-repair-and-balance.md
  docs/en/administrator-guide/operation/tablet-restore-tool.md
  docs/zh-CN/administrator-guide/config/fe_config.md
  docs/zh-CN/administrator-guide/operation/tablet-repair-and-balance.md
  docs/zh-CN/administrator-guide/operation/tablet-restore-tool.md
  docs/zh-CN/sql-reference/sql-statements/Administration/ADMIN SET CONFIG.md
  docs/zh-CN/sql-reference/sql-statements/Administration/CREATE FILE.md
Labels: approved

#5098 add BE udf bitmap xor
  be/src/exprs/bitmap_function.cpp
  be/src/exprs/bitmap_function.h
  be/src/util/bitmap_value.h
  docs/en/sql-reference/sql-functions/bitmap-functions/bitmap_xor.md
  docs/zh-CN/sql-reference/sql-functions/bitmap-functions/bitmap_xor.md
  gensrc/script/doris_builtins_functions.py
Labels: approved, area/sql/function

#5111 [Bug] Fix scanner threads heap-use-after-free
  be/src/exec/olap_scan_node.cpp
  be/src/exec/olap_scan_node.h
  be/src/exec/olap_scanner.cpp
Labels: approved, kind/bug

#5123 [UT] Add ut for column predicate of columnblock
  be/test/olap/comparison_predicate_test.cpp
  be/test/olap/in_list_predicate_test.cpp
  be/test/olap/null_predicate_test.cpp
Labels: approved, area/test

#5139 Fix create colocate table bug
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/ColocateTableIndex.java
  fe/fe-core/src/main/java/org/apache/doris/clone/ColocateTableBalancer.java
Labels: approved, kind/bug

#5148 [Feature] Implementation of histogram metric
  LICENSE.txt
  be/src/util/CMakeLists.txt
  be/src/util/histogram.cpp
  be/src/util/histogram.h
  be/src/util/metrics.cpp
  be/src/util/metrics.h
  be/test/util/CMakeLists.txt
  be/test/util/histogram_test.cpp
Labels: approved, area/metrics

#5168 [FE] Add log for abort transaction.
  fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java
Labels: approved

#5008 [Optimize][Cache]Implementation of Separated Page Cache
  be/src/common/config.h
  be/src/olap/page_cache.cpp
  be/src/olap/page_cache.h
  be/src/olap/rowset/segment_v2/column_reader.cpp
  be/src/olap/rowset/segment_v2/column_reader.h
  be/src/olap/rowset/segment_v2/indexed_column_reader.cpp
  be/src/olap/rowset/segment_v2/indexed_column_reader.h
  be/src/olap/rowset/segment_v2/ordinal_page_index.cpp
  be/src/olap/rowset/segment_v2/page_io.cpp
  be/src/olap/rowset/segment_v2/page_io.h
  be/src/olap/rowset/segment_v2/segment.cpp
  be/src/runtime/exec_env_init.cpp
  be/test/olap/page_cache_test.cpp
  be/test/olap/rowset/beta_rowset_test.cpp
  be/test/olap/rowset/rowset_converter_test.cpp
  be/test/olap/rowset/segment_v2/bitmap_index_test.cpp
  be/test/olap/rowset/segment_v2/bloom_filter_index_reader_writer_test.cpp
  be/test/olap/rowset/segment_v2/column_reader_writer_test.cpp
  be/test/olap/rowset/segment_v2/ordinal_page_index_test.cpp
  be/test/olap/rowset/segment_v2/segment_test.cpp
  be/test/olap/rowset/segment_v2/zone_map_index_test.cpp
  docs/en/administrator-guide/config/be_config.md
  docs/zh-CN/administrator-guide/config/be_config.md
Labels: approved, kind/enhancement

#5165 Fix MaterializedView select with CTE bug
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
Labels: approved, area/materialized-view, kind/bug

#5187 fix build thirdparty may be failed
  be/CMakeLists.txt
  be/src/common/daemon.cpp
  build.sh
  docs/en/installing/compilation.md
  docs/zh-CN/installing/compilation.md
  env.sh
  run-be-ut.sh
  thirdparty/build-thirdparty.sh
  thirdparty/download-thirdparty.sh
Labels: approved, area/dependency

#5191 Fix compile error after rebase #5179
  thirdparty/build-thirdparty.sh
Labels: approved, area/build, area/dependency

#5189 [Bug] Fix bug that the min/max function has an error in handling string null values
  be/src/olap/aggregate_func.h
Labels: approved, kind/bug

#5190 Update install-deploy.md
  docs/zh-CN/installing/install-deploy.md
Labels: approved, kind/documentation

#5158 [Config] change some static config to dynamic config and delete some unused config
  be/src/common/config.h
  docs/en/administrator-guide/config/be_config.md
  docs/zh-CN/administrator-guide/config/be_config.md
Labels: approved, area/config

#5133 [Enhancement] Optimize the algorithm of selecting host for a bucket scan task when a backend not alive
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/test/java/org/apache/doris/qe/CoordinatorTest.java
Labels: approved

#5135 [Function] Add timeout of connection when downloading the function object file
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateFunctionStmt.java
Labels: approved, area/udf

#5156 [Load] support ignoring eovercrowded when tablet sink
  be/src/common/config.h
  be/src/exec/tablet_sink.cpp
  docs/en/administrator-guide/config/be_config.md
  docs/zh-CN/administrator-guide/config/be_config.md
Labels: approved, area/config

#5112 [Enhancement] Add more comprehensive prometheus jvm thread metrics on fe
  docs/en/administrator-guide/operation/monitor-metrics/fe-metrics.md
  docs/zh-CN/administrator-guide/operation/monitor-metrics/fe-metrics.md
  fe/fe-core/src/main/java/org/apache/doris/common/proc/JvmProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/metric/PrometheusMetricVisitor.java
  fe/fe-core/src/main/java/org/apache/doris/monitor/jvm/JvmStats.java
Labels: approved, area/metrics

#5170 For #5169 Add publish timout param when exec insert
  docs/en/administrator-guide/variables.md
  docs/zh-CN/administrator-guide/variables.md
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/MasterOpExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  gensrc/thrift/FrontendService.thrift
Labels: approved, area/config, area/load

#5202 [Spark on Doris] fix the encode of varchar when convertArrowToRowBatch
  extension/spark-doris-connector/src/main/java/org/apache/doris/spark/serialization/RowBatch.java
Labels: approved, area/spark-connector

#5211 Fix daily test failed cause by delete condition
  be/CMakeLists.txt
  conf/fe.conf
  fe/fe-core/src/main/java/org/apache/doris/analysis/DataDescription.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/planner/StreamLoadScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/task/LoadTaskInfo.java
  fe/fe-core/src/main/java/org/apache/doris/task/StreamLoadTask.java
Labels: approved, area/delete, area/load, kind/bug

#5222 Fix duplicated add delete condition when run routine load
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadJob.java
Labels: approved, area/delete, area/load, kind/bug

#5096 [Feature] Add a http interface to acquire the tablets distribution between different disks
  be/src/http/CMakeLists.txt
  be/src/http/action/tablets_distribution_action.cpp
  be/src/http/action/tablets_distribution_action.h
  be/src/olap/olap_common.h
  be/src/olap/tablet_manager.cpp
  be/src/olap/tablet_manager.h
  be/src/service/http_service.cpp
  docs/en/administrator-guide/http-actions/tablets_distribution.md
  docs/zh-CN/administrator-guide/http-actions/tablets_distribution.md
Labels: api-review, approved, kind/feature

#5162 [TSAN] Fix tsan bugs (part 1)
  be/CMakeLists.txt
  be/src/exec/data_sink.cpp
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
  be/src/http/ev_http_server.cpp
  be/src/http/ev_http_server.h
  be/src/olap/data_dir.cpp
  be/src/olap/data_dir.h
  be/src/olap/olap_server.cpp
  be/src/olap/storage_engine.cpp
  be/src/runtime/disk_io_mgr.h
  be/src/runtime/fragment_mgr.cpp
  be/src/util/blocking_priority_queue.hpp
  be/src/util/condition_variable.cpp
  be/src/util/debug/sanitizer_scopes.h
  be/src/util/priority_thread_pool.hpp
  be/src/util/runtime_profile.h
  be/src/util/spinlock.h
  be/src/util/thread.cpp
  be/src/util/threadpool.cpp
  be/test/exec/tablet_sink_test.cpp
  be/test/plugin/plugin_zip_test.cpp
  thirdparty/build-thirdparty.sh
  thirdparty/vars.sh
  tsan_suppressions
Labels: approved, kind/enhancement

#5209 [Feature] Support Create Dynamic Partition Immediately FirstTime Without Wating Schedule.
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/clone/DynamicPartitionScheduler.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/DynamicPartitionUtil.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/DynamicPartitionTableTest.java
Labels: approved, area/catalog, kind/enhancement

#5236 [Doc] Update README.md: a reword suggestion
  README.md
Labels: approved, kind/documentation

#5240 [Doc] Update PULL_REQUEST_TEMPLATE.md: a reword suggestion
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, kind/documentation

#5239 [Doc] Update README.md: a reword suggestion
  README.md
Labels: approved, kind/documentation

#5241 [Doc] Update README.md: a reword suggestion
  README.md
Labels: approved, kind/documentation

#5228 [Bug] Fix bucket shuffle join bug of query failed
  be/src/runtime/data_stream_sender.cpp
Labels: approved, area/sql/execution, kind/bug

#4984 [Optimize]Take all scan nodes of one sql into consideration when select host for a tablet
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/test/java/org/apache/doris/qe/CoordinatorTest.java
Labels: approved

#5101 [Feature] Add a http interface for single tablet migration between different disks
  be/src/common/config.h
  be/src/http/CMakeLists.txt
  be/src/http/action/tablet_migration_action.cpp
  be/src/http/action/tablet_migration_action.h
  be/src/service/http_service.cpp
  docs/en/administrator-guide/http-actions/tablet-migration-action.md
  docs/zh-CN/administrator-guide/http-actions/tablet-migration-action.md
Labels: api-review, approved, kind/feature

#5167 [Enhancement] Fill assignment param of bucket shuffle and colocate shuffle for debug
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/test/java/org/apache/doris/qe/CoordinatorTest.java
Labels: approved, kind/enhancement

#5248 [Doc] Update PULL_REQUEST_TEMPLATE.md: a reword suggestion
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, kind/documentation

#5149 [Enhancement] Add system memory metrics for fe
  docs/en/administrator-guide/operation/monitor-metrics/fe-metrics.md
  docs/zh-CN/administrator-guide/operation/monitor-metrics/fe-metrics.md
  fe/fe-core/src/main/java/org/apache/doris/metric/MetricRepo.java
  fe/fe-core/src/main/java/org/apache/doris/metric/SystemMetrics.java
Labels: area/metrics

#5193 [UT] fix the bug of getting current running dir
  be/test/plugin/plugin_loader_test.cpp
  be/test/plugin/plugin_mgr_test.cpp
  be/test/plugin/plugin_zip_test.cpp
  be/test/test_util/test_util.cpp
  be/test/test_util/test_util.h
  be/test/util/system_metrics_test.cpp
  be/test/util/zip_util_test.cpp
Labels: approved, area/test, kind/bug

#5221 Fix fe restart failed bug when replay erase table log
  fe/fe-core/src/main/java/org/apache/doris/catalog/CatalogRecycleBin.java
Labels: approved, area/catalog

#5234 add aws sdk to thirdparty
  be/CMakeLists.txt
  thirdparty/build-thirdparty.sh
  thirdparty/vars.sh
Labels: approved, area/dependency

#5257 [BUG] fix alter routine load not work
  docs/en/sql-reference/sql-statements/Data Manipulation/alter-routine-load.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/alter-routine-load.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/AlterRoutineLoadStmt.java
Labels: area/load, kind/bug

#5254 [Bug] Remove schema hash and fix bug of calculating table signature
  fe/fe-core/src/main/java/org/apache/doris/alter/MaterializedViewHandler.java
  fe/fe-core/src/main/java/org/apache/doris/backup/RestoreJob.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Column.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Table.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/Util.java
  fe/fe-core/src/test/java/org/apache/doris/backup/CatalogMocker.java
Labels: approved, kind/bug, kind/refactor

#5256 [Bug] Colocate Join and Bucket shuffle join may scan some tablet twice time.
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/test/java/org/apache/doris/qe/CoordinatorTest.java
Labels: approved, area/colocated, area/sql/planner, kind/bug

#5207 [Performance Improve] Push Down _conjunctf of 'not in' and '!=' to Storage Engine.
  be/src/exec/olap_common.h
  be/src/exec/olap_scan_node.cpp
  be/src/exec/olap_scan_node.h
  be/src/olap/olap_cond.cpp
  be/src/olap/reader.cpp
  be/src/olap/rowset/segment_v2/column_reader.cpp
  be/test/exec/olap_common_test.cpp
Labels: approved

#5219 Add some consistency check in image put api
  fe/fe-core/src/main/java/org/apache/doris/http/meta/MetaService.java
Labels: approved, area/catalog

#5226 [Bug] Fix row_number and group by have inconsistent partition results for (0.0, -0.0)
  be/src/util/hash_util.hpp
Labels: SQL Bug, approved, kind/bug

#5279 [Bug] Fix bug that recover table throw NPE
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/RecoverTest.java
Labels: approved, kind/bug

#5287 [Doc] Update README.md: two reword suggestions
  README.md
Labels: approved

#5277 [Load Parallel][1/3] Broker Load supports setting the load parallelism
  be/src/olap/version_graph.cpp
  fe/fe-core/src/main/java/org/apache/doris/analysis/LoadStmt.java
  fe/fe-core/src/main/java/org/apache/doris/common/FeMetaVersion.java
  fe/fe-core/src/main/java/org/apache/doris/load/Load.java
  fe/fe-core/src/main/java/org/apache/doris/load/LoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BrokerLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BulkLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/InsertLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadLoadingTask.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadingTaskPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/MiniLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkLoadPendingTask.java
  fe/fe-core/src/main/java/org/apache/doris/planner/BrokerScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/LoadScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PlanFragment.java
  fe/fe-core/src/main/java/org/apache/doris/qe/DdlExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/BrokerLoadJobTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/LoadJobTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/LoadManagerTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/SparkLoadJobTest.java
  fe/fe-core/src/test/java/org/apache/doris/persist/LoadJobV2PersistTest.java
Labels: api-review, approved, area/load, kind/enhancement, kind/meta-version-change

#5163 [Load Parallel][2/3] Support parallel flushing memtable during load
  be/src/common/config.h
  be/src/olap/delta_writer.cpp
  be/src/olap/memtable.cpp
  be/src/olap/memtable.h
  be/src/olap/memtable_flush_executor.cpp
  be/src/olap/memtable_flush_executor.h
  be/src/olap/rowset/beta_rowset_writer.cpp
  be/src/olap/rowset/beta_rowset_writer.h
  be/src/olap/rowset/rowset_writer.h
Labels: approved, area/load, kind/enhancement

#5260 Optimize Zone map create policy
  be/src/common/config.h
  be/src/olap/rowset/segment_v2/column_reader.cpp
  be/src/olap/rowset/segment_v2/column_writer.cpp
  be/src/olap/rowset/segment_v2/zone_map_index.cpp
  be/src/olap/rowset/segment_v2/zone_map_index.h
  docs/en/administrator-guide/config/be_config.md
  docs/zh-CN/administrator-guide/config/be_config.md
  gensrc/proto/segment_v2.proto
Labels: approved, area/storage, kind/enhancement

#5268 (#5267) remove path check when start BE
  be/src/olap/data_dir.cpp
  be/src/olap/tablet_manager.cpp
  be/src/olap/tablet_manager.h
Labels: approved, kind/enhancement

#5285 [Bug] Fix bug of outer join cause error result
  fe/fe-core/src/main/java/org/apache/doris/planner/HashJoinNode.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: approved, area/sql/planner

#5295 [bug] fix bug of getBrokerDesc object is null
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadManager.java
Labels: approved

#5294 [Compile] fix compile error in gcc10
  be/src/olap/hll.h
  be/src/olap/reader.cpp
Labels: approved

#5290 [Doc] Translate a Chinese statement which appears in English version doc
  docs/en/internal/doris_storage_optimization.md
  docs/en/internal/grouping_sets_design.md
  docs/en/internal/metadata-design.md
Labels: approved, kind/documentation

#5289 [gitignore] Update .gitignore: remove a duplicate pattern
  .gitignore
Labels: kind/documentation

#5288 [Doc] Update README.md: a reword suggestion
  README.md
Labels: approved

#5297 Revert "[Bug] Fix row_number and group by have inconsistent partition results for (0.0, -0.0)"
  be/src/util/hash_util.hpp
Labels: kind/revert

#5233 (#5224)some little fix for spark load
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/ColumnParser.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/SparkDpp.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/etl/SparkEtlJob.java
Labels: approved, area/spark-load

#5194 [Enhancement] Fix bug for auditloader plugin that audit event cannot be processed in time
  docs/en/extending-doris/audit-plugin.md
  docs/zh-CN/extending-doris/audit-plugin.md
  fe_plugins/auditloader/src/main/assembly/plugin.properties
  fe_plugins/auditloader/src/main/java/org/apache/doris/plugin/audit/AuditLoaderPlugin.java
Labels: approved, area/plugin, kind/bug

#5244 [Auidt] Fix bug for that only the last statement can be audited when user send multi-statement
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
Labels: approved, kind/bug

#5117 Fix some problems related to thrift rpc when use nonblokcing IO model
  be/src/common/config.h
  be/src/runtime/client_cache.h
  be/src/util/thrift_client.h
  docs/en/installing/install-deploy.md
  docs/zh-CN/installing/install-deploy.md
  fe/fe-core/src/main/java/org/apache/doris/common/ClientPool.java
  fe/fe-core/src/main/java/org/apache/doris/common/GenericPool.java
  fe/fe-core/src/main/java/org/apache/doris/common/ThriftServer.java
  fe/fe-core/src/main/java/org/apache/doris/common/ThriftServerEventProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/system/HeartbeatMgr.java
Labels: approved

#5299 [BackupAndRestore] Support backup and restore view and external odbc table
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupHandler.java
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupJob.java
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupJobInfo.java
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupMeta.java
  fe/fe-core/src/main/java/org/apache/doris/backup/RestoreJob.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Database.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/EsTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/MetaObject.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/MysqlTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OdbcCatalogResource.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OdbcTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Resource.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/ResourceMgr.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/SparkResource.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/View.java
  fe/fe-core/src/main/java/org/apache/doris/common/AnalysisException.java
  fe/fe-core/src/main/java/org/apache/doris/common/FeMetaVersion.java
  fe/fe-core/src/main/java/org/apache/doris/common/io/DeepCopy.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/Util.java
  fe/fe-core/src/main/java/org/apache/doris/persist/EditLog.java
  fe/fe-core/src/test/java/org/apache/doris/backup/BackupHandlerTest.java
  fe/fe-core/src/test/java/org/apache/doris/backup/BackupJobInfoTest.java
  fe/fe-core/src/test/java/org/apache/doris/backup/BackupJobTest.java
  fe/fe-core/src/test/java/org/apache/doris/backup/RestoreJobTest.java
  fe/fe-core/src/test/java/org/apache/doris/common/io/DeepCopyTest.java
Labels: approved, area/backup, kind/feature, kind/meta-version-change

#5302 Fix apply condition to unique table value columns incorrectly
  be/src/olap/reader.cpp
Labels: approved, kind/bug

#5124 [Compaction] Fix bug and add graceful exit for compaction producer
  be/src/common/config.h
  be/src/olap/olap_server.cpp
  be/src/olap/storage_engine.h
Labels: approved, area/compact

#5201 Fix NoSuchElementException when accessing empty partition info
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/test/java/org/apache/doris/planner/PlannerTest.java
Labels: SQL Bug, approved, kind/bug

#5301 [optimization] avoid extra memory copy while build hash table
  be/src/exec/hash_table.cpp
  be/src/exec/hash_table.h
  be/src/exec/hash_table.hpp
  be/src/runtime/data_stream_recvr.hpp
  be/test/exec/CMakeLists.txt
  be/test/exec/hash_table_test.cpp
Labels: area/sql/execution

#5252 [Delete] Support delete with multi partitions
  docs/en/administrator-guide/variables.md
  docs/en/sql-reference/sql-statements/Data Manipulation/DELETE.md
  docs/zh-CN/administrator-guide/variables.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/DELETE.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/DeleteStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowDeleteStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/CatalogRecycleBin.java
  fe/fe-core/src/main/java/org/apache/doris/common/FeMetaVersion.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/DeleteInfoProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/DeleteJobProcNode.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/JobsProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/journal/JournalEntity.java
  fe/fe-core/src/main/java/org/apache/doris/journal/local/LocalJournalCursor.java
  fe/fe-core/src/main/java/org/apache/doris/load/AsyncDeleteJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/DeleteHandler.java
  fe/fe-core/src/main/java/org/apache/doris/load/DeleteInfo.java
  fe/fe-core/src/main/java/org/apache/doris/load/DeleteJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/Load.java
  fe/fe-core/src/main/java/org/apache/doris/load/LoadChecker.java
  fe/fe-core/src/main/java/org/apache/doris/load/LoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/TabletDeleteInfo.java
  fe/fe-core/src/main/java/org/apache/doris/master/MasterImpl.java
  fe/fe-core/src/main/java/org/apache/doris/persist/EditLog.java
  fe/fe-core/src/main/java/org/apache/doris/persist/OperationType.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/MasterOpExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/VariableMgr.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/DeleteStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/DeleteHandlerTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/LoadCheckerTest.java
  fe/fe-core/src/test/java/org/apache/doris/qe/SessionVariablesTest.java
  gensrc/thrift/FrontendService.thrift
Labels: api-review, approved, area/delete, kind/feature, kind/meta-version-change

#5306 [Bugs] Fix bugs that FE heartbeat api of httpv2 does not return version info
  be/src/exec/broker_scanner.cpp
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/BootstrapFinishAction.java
  fe/fe-core/src/main/java/org/apache/doris/system/HeartbeatMgr.java
Labels: kind/bug

#5205 [Load] Load job should not begin transaction when task queue in loadingLoadTaskScheduler is full to avoid txn timeout
  docs/en/administrator-guide/config/fe_config.md
  docs/zh-CN/administrator-guide/config/fe_config.md
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/common/ConfigBase.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadJobScheduler.java
  fe/fe-core/src/main/java/org/apache/doris/task/MasterTaskExecutor.java
Labels: approved

#5273 [Doc] Fix the error description for the number of bytes of double type.
  docs/en/sql-reference/sql-statements/Data Definition/CREATE TABLE.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/CREATE TABLE.md
Labels: approved, good first issue, kind/documentation

#5274 [Bug] Fix CompactionPermitLimiter cv starve bug
  be/src/olap/compaction_permit_limiter.cpp
Labels: approved, kind/bug

#5283 fix ui build error: classnames and react-router dependencies
  ui/package.json
Labels: approved, area/fe/frontpage, kind/bug

#5314 [Backup]Support content, exclude and whole database in backup
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/AbstractBackupStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/AbstractBackupTableRefClause.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/BackupStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/RestoreStmt.java
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupHandler.java
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupJob.java
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupJobInfo.java
  fe/fe-core/src/main/java/org/apache/doris/backup/RestoreJob.java
  fe/fe-core/src/main/jflex/sql_scanner.flex
  fe/fe-core/src/test/java/org/apache/doris/backup/BackupHandlerTest.java
  fe/fe-core/src/test/java/org/apache/doris/backup/BackupJobTest.java
Labels: api-review, approved, area/backup, kind/api-change

#5323 [ODBC] Fix Memory consumption of ODBC MySQL Driver (#5322)
  fe/fe-core/src/main/java/org/apache/doris/catalog/OdbcTable.java
Labels: approved, kind/enhancement
