Repository apache/doris, pull requests merged in 2021-06, with the labels that each got.

#5941 [Docs] update PMC Members & Committers
  docs/en/community/members.md
  docs/zh-CN/community/members.md
Labels: approved, area/community, kind/documentation

#5935 Add Doris error code table
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/administrator-guide/operation/doris-error-code.md
  docs/zh-CN/administrator-guide/operation/doris-error-code.md
Labels: approved, kind/documentation

#5945 [Bug] Rebuilt version graph of a tablet when there are too many orphan vertex
  be/src/common/config.h
  be/src/olap/storage_engine.cpp
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
  be/src/olap/version_graph.cpp
  be/src/olap/version_graph.h
  be/test/olap/timestamped_version_tracker_test.cpp
Labels: approved, kind/bug

#5953 [Bug] Fix lack of rdlock before rowset_with_max_version() in compaction log
  be/src/olap/compaction.cpp
Labels: approved, kind/bug

#5952 [BUG] Fixed the problem that substring function may access illegal ad…
  be/src/exprs/string_functions.cpp
  be/test/exprs/string_functions_test.cpp
Labels: approved, kind/bug

#5946 [Function] Support Function `current_timestamp()`, `curtime()`, `current_time()` in FE.
  fe/fe-core/src/main/java/org/apache/doris/analysis/FloatLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/FEFunctions.java
  fe/fe-core/src/test/java/org/apache/doris/planner/ConstantExpressTest.java
  fe/fe-core/src/test/java/org/apache/doris/rewrite/FEFunctionsTest.java
Labels: approved, area/sql/function

#5961 [Bug] Fix the bug of null pointer exception of colocate join
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/test/java/org/apache/doris/qe/CoordinatorTest.java
Labels: approved, area/colocated, kind/bug

#5919 [Bug-fix] Show view stmt report error when view references invalid table
  fe/fe-core/src/main/java/org/apache/doris/analysis/QueryStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SetOperationStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowViewStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/WithClause.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/SelectStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ShowViewStmtTest.java
Labels: approved, kind/bug

#5937 [Bug][Log] Fix log error when commit transaction in txn manager
  be/src/olap/txn_manager.cpp
Labels: approved

#5942 catch throwable instead of exception
  fe/fe-core/src/main/java/org/apache/doris/mysql/nio/AcceptListener.java
Labels: good first issue

#5963 Fix a log mistake in flink-connector
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicOutputFormat.java
Labels: approved

#5970 [Optimize] convert byte size into a human-readable format
  fe/fe-core/src/main/java/org/apache/doris/common/proc/JvmProcDir.java
Labels: approved, kind/enhancement

#5972 [Doc] Update docke hub url to offical repo
  docker/Dockerfile
  docker/README.md
  docs/en/community/release-process.md
  docs/en/installing/compilation.md
  docs/zh-CN/community/release-process.md
  docs/zh-CN/installing/compilation.md
Labels: approved, area/community

#5982 [DOC] Update zh-CN ALTER TABLE.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/ALTER TABLE.md
Labels: approved, kind/documentation

#5978 [DOC] Corrected a typo in the Chinese document
  docs/zh-CN/getting-started/data-model-rollup.md
Labels: approved, kind/documentation

#5973 [Bug] Ignore drop table log when table has been dropped
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
Labels: approved, kind/bug

#5845 [BrokerLoad] Support read properties for broker load when read data
  be/src/exec/broker_reader.cpp
  docs/en/sql-reference/sql-statements/Data Manipulation/BROKER LOAD.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/BROKER LOAD.md
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/DataDescription.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/LoadStmt.java
  fe/fe-core/src/main/java/org/apache/doris/load/BrokerFileGroup.java
  fe/fe-core/src/main/java/org/apache/doris/planner/BrokerScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/MultiLoadMgr.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/DataDescriptionTest.java
Labels: approved, area/load, kind/feature

#5998 [Bug] Fix bug that cannot cancel alter table operation when table is unstable
  fe/fe-core/src/main/java/org/apache/doris/alter/MaterializedViewHandler.java
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
Labels: approved, area/schema-change

#5938 [Feature] Select outfile support parquet format
  be/src/exec/parquet_writer.cpp
  be/src/exec/parquet_writer.h
  be/src/runtime/file_result_writer.cpp
  be/src/runtime/file_result_writer.h
  fe/fe-core/src/main/java/org/apache/doris/analysis/OutFileClause.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/QueryStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/SelectStmtTest.java
  gensrc/thrift/DataSinks.thrift
Labels: approved, kind/feature

#5966 [Bug] Fix bug that start time is null when SQL is forward to master
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
Labels: approved

#5986 [Bug] Outer join dispose constexpr error in inlineview
  fe/fe-core/src/main/java/org/apache/doris/analysis/TupleIsNullPredicate.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: approved, area/sql/planner, kind/bug

#5987 [Bug] SimplifyInvalidDateBinaryPredicatesDateRule may cause invalid query plan
  be/src/common/config.h
  be/src/olap/storage_engine.cpp
  fe/fe-core/src/main/java/org/apache/doris/analysis/DateLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/common/NotLiteralExprPredicate.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/SimplifyInvalidDateBinaryPredicatesDateRule.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/DateLiteralTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: approved, area/sql/planner, kind/bug

#5990 [Enhancement] Use Parallel Hash Map Replace Unordered Map In Dict Encodeing Map And Hyper Set
  be/src/exprs/hybrid_set.h
  be/src/gutil/endian.h
  be/src/olap/rowset/segment_v2/binary_dict_page.h
  thirdparty/build-thirdparty.sh
  thirdparty/vars.sh
Labels: approved, kind/enhancement

#6000 [Function] Support date function: yearweek(), week(), makedate().
  be/src/exprs/timestamp_functions.cpp
  be/src/exprs/timestamp_functions.h
  be/src/runtime/datetime_value.cpp
  be/src/runtime/datetime_value.h
  be/test/exprs/timestamp_functions_test.cpp
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/sql-reference/sql-functions/date-time-functions/makedate.md
  docs/en/sql-reference/sql-functions/date-time-functions/week.md
  docs/en/sql-reference/sql-functions/date-time-functions/yearweek.md
  docs/zh-CN/sql-reference/sql-functions/date-time-functions/makedate.md
  docs/zh-CN/sql-reference/sql-functions/date-time-functions/week.md
  docs/zh-CN/sql-reference/sql-functions/date-time-functions/yearweek.md
  fe/fe-core/src/main/java/org/apache/doris/rewrite/FEFunctions.java
  gensrc/script/doris_builtins_functions.py
Labels: area/sql/function

#6006 Fix a log issue in BDBJournalCursor
  fe/fe-core/src/main/java/org/apache/doris/journal/bdbje/BDBJournalCursor.java
Labels: approved, good first issue

#6003 [Bug] fix use incorrect table name in expand star
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: approved, area/view, kind/bug

#5811 [Enhancement] Reduce memory consumption by releasing readers earier
  be/src/olap/collect_iterator.cpp
  be/src/olap/collect_iterator.h
  be/src/olap/compaction.cpp
  be/src/olap/generic_iterators.cpp
  be/src/olap/generic_iterators.h
  be/src/olap/merger.cpp
  be/src/olap/reader.cpp
  be/src/olap/reader.h
  be/src/olap/row_block.h
  be/src/olap/row_cursor.cpp
  be/src/olap/rowset/alpha_rowset_reader.cpp
  be/src/olap/rowset/alpha_rowset_reader.h
  be/src/olap/rowset/beta_rowset_reader.cpp
  be/src/olap/storage_engine.cpp
  be/test/olap/generic_iterators_test.cpp
Labels: approved, kind/enhancement

#6007 fix kafka consumer reuse
  be/src/runtime/routine_load/data_consumer.cpp
Labels: approved, area/load, good first issue

#5965 [Bug] Fix bucket shuffle bug when left table is without any data
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
Labels: approved, area/sql/planner, kind/bug

#6010 [optimize] use string_view instead of std::string in string function
  be/src/exec/es/es_query_builder.cpp
  be/src/exec/es/es_scroll_parser.cpp
  be/src/exec/json_scanner.cpp
  be/src/exprs/json_functions.cpp
  be/src/exprs/json_functions.h
  be/src/exprs/string_functions.cpp
  be/src/exprs/string_functions.h
  be/src/runtime/decimal_value.h
  be/src/runtime/decimalv2_value.h
  be/src/runtime/stream_load/stream_load_context.cpp
  be/test/exec/tablet_sink_test.cpp
  be/test/exprs/bitmap_function_test.cpp
Labels: approved, kind/enhancement

#6014 [Docs] update data-model-rollup.md create table ddl
  docs/en/getting-started/data-model-rollup.md
  docs/zh-CN/getting-started/data-model-rollup.md
Labels: approved, good first issue, kind/documentation

#6018 [Bug-fix] Avoid using 'QueryDetail' in planning stage
  fe/fe-core/src/main/java/org/apache/doris/planner/DistributedPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContext.java
Labels: approved, area/colocated, area/sql/planner, kind/bug

#6025 [Doc]Fix a typo
  docs/zh-CN/extending-doris/udf/contrib/udaf-orthogonal-bitmap-manual.md
Labels: approved, good first issue, kind/documentation

#6033 [Bug] Fix that build thirdparty of parallel-hashmap-1.33 failed on ub…
  thirdparty/build-thirdparty.sh
Labels: approved

#6050 [Bug] Fix stream load detailed error message is missing
  be/src/exec/tablet_sink.cpp
Labels: approved

#6029 [Bug-fix] Fix wrong data distribution judgment
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
  fe/fe-core/src/test/java/org/apache/doris/planner/ColocatePlanTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: approved, area/colocated, area/sql/planner, kind/bug

#5975 [DOC]Organize FE configuration file description
  docs/en/administrator-guide/config/be_config.md
  docs/en/administrator-guide/config/fe_config.md
  docs/zh-CN/administrator-guide/config/be_config.md
  docs/zh-CN/administrator-guide/config/fe_config.md
Labels: approved, area/config, kind/documentation

#6019 [Bug] Fix problem for thread safety issues and setting the status of non-existent replica does not prompt any error message
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
Labels: approved, area/catalog, kind/bug, kind/enhancement

#6008 update download info for boost and datatables
  thirdparty/vars.sh
Labels: approved, area/dependency

#6034 [optimization] open gcc strict-aliasing optimization
  be/CMakeLists.txt
  be/src/exec/olap_scan_node.cpp
  be/src/exec/text_converter.hpp
  be/src/exprs/aggregate_functions.cpp
  be/src/exprs/decimalv2_operators.cpp
  be/src/exprs/expr_value.h
  be/src/exprs/string_functions.cpp
  be/src/runtime/decimalv2_value.h
  be/src/util/binary_cast.hpp
  be/src/util/hash_util.hpp
  be/src/util/pretty_printer.h
  be/src/util/runtime_profile.h
  be/src/util/types.h
  be/test/runtime/decimalv2_value_test.cpp
Labels: approved, area/compiler, kind/enhancement

#6026 [Bug][Cache] Add data_size field for InternalService.PCacheValue
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/RowBatchBuilder.java
Labels: approved, area/sql/cache, kind/bug

#5968 Update install-deploy.md
  docs/en/installing/install-deploy.md
  docs/zh-CN/installing/install-deploy.md
Labels: approved, good first issue, kind/documentation

#6012 Fix one more record in the “show export limit n"
  fe/fe-core/src/main/java/org/apache/doris/load/ExportMgr.java
  fe/fe-core/src/main/java/org/apache/doris/task/ExportExportingTask.java
Labels: approved

#6013 Spring boot http upload file maximum limit parameterization
  fe/fe-core/src/main/java/org/apache/doris/PaloFe.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/HttpServer.java
Labels: approved, httpv2

#6043 Compatible with mysql nulls order by
  fe/fe-core/src/main/cup/sql_parser.cup
Labels: approved, area/sql, kind/bug

#6058 [Bug] Fix bug that routine load job may cause dead lock
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadManager.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/TransactionState.java
Labels: approved, area/routine load, kind/bug

#6022 [Enchancement] Validate data file after alter operation success
  be/src/olap/rowset/alpha_rowset.cpp
  be/src/olap/rowset/alpha_rowset.h
  be/src/olap/rowset/beta_rowset.cpp
  be/src/olap/rowset/beta_rowset.h
  be/src/olap/rowset/rowset.h
  be/src/olap/schema_change.cpp
Labels: kind/stability

#6059 [BUG] Fix TotalUsedPct display error
  fe/fe-core/src/main/java/org/apache/doris/common/proc/BackendProcNode.java
Labels: approved, area/show stmt, kind/bug

#6060 [Bug] Fix show data bug
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowDataStmt.java
Labels: approved, area/show stmt, kind/bug

#6062 [BUG] fix select random storage path maybe always same
  be/src/olap/storage_engine.cpp
Labels: approved, area/storage, kind/bug

#6045 [Enhance] Support show unrecoverable tablets
  fe/fe-core/src/main/java/org/apache/doris/catalog/Tablet.java
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletChecker.java
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletScheduler.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/IncompleteTabletsProcNode.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/StatisticProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/HttpServer.java
  fe/fe-core/src/main/java/org/apache/doris/master/ReportHandler.java
Labels: approved

#5947 [Feature] Support recording custom number of backup and restore task information
  docs/en/administrator-guide/config/fe_config.md
  docs/zh-CN/administrator-guide/config/fe_config.md
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowBackupStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowRestoreStmt.java
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupHandler.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
Labels: approved, area/backup, kind/enhancement

#6070 [BUG] fix spring boot web maximum upload file limit config error
  docs/en/administrator-guide/config/fe_config.md
  docs/zh-CN/administrator-guide/config/fe_config.md
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
Labels: approved, kind/bug

#6076 [Build][ARM] Fix some compilation problems on ARM64
  be/CMakeLists.txt
  be/src/exec/CMakeLists.txt
  be/src/exec/broker_scanner.cpp
  be/src/exec/parquet_scanner.cpp
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/installing/compilation-arm.md
  docs/zh-CN/installing/compilation-arm.md
Labels: approved, area/build, kind/ARM64

#6054 [Bug] Fix bug that select into outfile in parquet format may cause NPE
  fe/fe-core/src/main/java/org/apache/doris/analysis/OutFileClause.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/SelectStmtTest.java
Labels: approved, area/outfile, kind/bug

#6084 [Docs] Fix README.md
  README.md
Labels: approved, kind/documentation

#6081 [Bugfix] Misuse logical AND
  be/src/olap/rowset/segment_v2/bloom_filter.cpp
Labels: approved, area/storage, kind/bug

#6089 SIMD instruction speed up the storage layer
  be/src/olap/rowset/segment_v2/binary_dict_page.cpp
  be/src/olap/rowset/segment_v2/binary_plain_page.h
  be/src/runtime/mem_pool.h
  be/src/util/bit_util.h
Labels: Performance, area/storage

#6090 fix stdfs link error in some gcc version
  be/CMakeLists.txt
Labels: approved, area/build, area/compiler

#6030 Fix timeout error when delete condition contains invalid datetime format
  be/src/olap/delete_handler.cpp
  be/src/olap/utils.cpp
  be/test/olap/delete_handler_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/load/DeleteHandler.java
Labels: approved, area/delete, kind/enhancement

#6104 [Docs] ADD: fe-idea-dev.md add thrift version notice
  docs/zh-CN/developer-guide/fe-idea-dev.md
Labels: approved, kind/documentation

#6097 [Docs] Add contact us in README
  README.md
Labels: approved, area/community, kind/documentation

#6087 (#6009) fix bucket key distribute error when using spark load
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/DppUtils.java
Labels: area/spark-load, kind/bug

#5787 [Metrics] Add tablet count on different status metrics
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletChecker.java
  fe/fe-core/src/main/java/org/apache/doris/metric/MetricRepo.java
Labels: approved, area/metrics

#5934 [Feature]Support time interval for flink connector
  docs/en/extending-doris/flink-doris-connector.md
  docs/zh-CN/extending-doris/flink-doris-connector.md
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisExecutionOptions.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicOutputFormat.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableFactory.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisStreamLoad.java
Labels: approved, area/load, kind/enhancement

#6036 [optimization] _Tuple_ptrs into mempool when RowBatch is initialized
  be/src/runtime/row_batch.cpp
  be/src/runtime/row_batch.h
Labels: approved, area/memory-consumption, kind/enhancement

#6053 [Bug] take table_id not table_name as key of runtimeInfo
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/clone/DynamicPartitionScheduler.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/DynamicPartitionTableTest.java
Labels: approved, area/dynamic-partition, kind/bug

#6069 [Metrics] Add metrics for load average.
  be/src/util/system_metrics.cpp
  be/src/util/system_metrics.h
  be/test/util/system_metrics_test.cpp
  be/test/util/test_data/load_avg_normal
Labels: approved, area/metrics, kind/feature

#6111 [Extension] Add DataX doriswriter extension directory
  extension/DataX/README
  extension/DataX/doriswriter/README
  extension/DataX/init-env.sh
  fe/fe-core/src/test/java/org/apache/doris/common/ThreadPoolManagerTest.java
Labels: area/datax, kind/feature
