Repository apache/doris, pull requests merged in 2021-12, with the labels that each got.

#7262 [BUG] Fix an error when fetch string type field may cause malformed packet error
  be/src/exprs/anyval_util.h
  be/src/runtime/buffer_control_block.cpp
  be/src/runtime/buffer_control_block.h
  be/src/service/internal_service.cpp
  be/src/udf/udf.cpp
  be/src/udf/udf.h
  be/src/util/mysql_row_buffer.cpp
  be/src/util/mysql_row_buffer.h
  fe/fe-core/src/main/java/org/apache/doris/mysql/MysqlChannel.java
  gensrc/script/doris_builtins_functions.py
Labels: kind/bug, approved, reviewed

#7149 [Feature] Z-Order Implement
  be/src/olap/collect_iterator.cpp
  be/src/olap/collect_iterator.h
  be/src/olap/memtable.cpp
  be/src/olap/memtable.h
  be/src/olap/rowset/segment_v2/column_reader.cpp
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/olap/skiplist.h
  be/src/olap/tablet.h
  be/src/olap/tablet_meta.cpp
  be/src/olap/tablet_schema.cpp
  be/src/olap/tablet_schema.h
  be/src/util/CMakeLists.txt
  be/src/util/bit_util.h
  be/src/util/tuple_row_zorder_compare.cpp
  be/src/util/tuple_row_zorder_compare.h
  be/test/olap/skiplist_test.cpp
  be/test/olap/test_data/header_without_inc_rs.txt
  be/test/util/CMakeLists.txt
  be/test/util/tuple_row_zorder_compare_test.cpp
  docs/en/sql-reference-v2/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE.md
  docs/zh-CN/sql-reference-v2/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE.md
  fe/fe-core/src/main/java/org/apache/doris/alter/Alter.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/DataSortInfo.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/TableProperty.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/org/apache/doris/task/CreateReplicaTask.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/CreateTableTest.java
  gensrc/proto/olap_file.proto
  gensrc/thrift/AgentService.thrift
  gensrc/thrift/Types.thrift
Labels: kind/enhancement, kind/feature, approved, reviewed

#7164 [BRPC] Support transfer RowBatch in ProtoBuf Request to Controller Attachment
  be/src/common/config.h
  be/src/exec/tablet_sink.cpp
  be/src/runtime/data_stream_sender.cpp
  be/src/service/internal_service.cpp
  be/src/util/proto_util.h
  be/test/exec/tablet_sink_test.cpp
  docs/en/administrator-guide/config/be_config.md
  docs/zh-CN/administrator-guide/config/be_config.md
  gensrc/proto/data.proto
Labels: approved, reviewed

#7242 [Documentation] add enhancement.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
Labels: good first issue, area/community, approved, reviewed

#7249 [refactor] Remove unused log instance creation
  fe/fe-core/src/main/java/org/apache/doris/http/ActionController.java
Labels: approved, reviewed

#7251 [feat] Enable Plain Password Auth at Routine Load
  thirdparty/build-thirdparty.sh
Labels: area/dependency, approved, reviewed

#7272 [Bug](Select outfile) Remove optional properties check of hdfs storage
  docs/en/administrator-guide/outfile.md
  docs/zh-CN/administrator-guide/outfile.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/OutFileClause.java
  fe/fe-core/src/main/java/org/apache/doris/backup/HDFSStorage.java
Labels: kind/bug, approved, area/outfile, reviewed

#7236 [Optimize] Support SIMD function in some string function
  be/src/exprs/math_functions.cpp
  be/src/exprs/string_functions.cpp
  be/src/util/simd/lower_upper_impl.h
  be/src/util/simd/vstring_function.h
  be/src/util/vectorized-tool/lower.h
  be/src/util/vectorized-tool/upper.h
  be/test/exprs/string_functions_test.cpp
Labels: kind/enhancement, approved, area/sql/function, reviewed

#7252 [Documentation Update]Update fe_config.md
  docs/en/administrator-guide/config/fe_config.md
  docs/zh-CN/administrator-guide/config/fe_config.md
Labels: approved, reviewed

#7269 [Improvement](Lateral view) Support lateral view based on subquery
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/BaseTableRef.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/InlineViewRef.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/LateralViewRef.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/TableRef.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
  fe/fe-core/src/main/java/org/apache/doris/planner/TableFunctionNode.java
  fe/fe-core/src/test/java/org/apache/doris/planner/TableFunctionPlanTest.java
Labels: area/sql/planner, approved, reviewed

#7271 [doc] correct sql syntax in upgrade.md
  docs/en/installing/upgrade.md
  docs/zh-CN/installing/upgrade.md
Labels: approved, reviewed

#7273 clean too many bdbje log
  fe/fe-core/src/main/java/org/apache/doris/journal/bdbje/BDBEnvironment.java
Labels: approved, reviewed

#7281 [Improvement]Add 'sink.batch.size' and 'sink.max-retries' options in doris spark-connector
  docs/en/extending-doris/spark-doris-connector.md
  docs/zh-CN/extending-doris/spark-doris-connector.md
  extension/spark-doris-connector/src/main/java/org/apache/doris/spark/cfg/ConfigurationOptions.java
  extension/spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/DorisSourceProvider.scala
  extension/spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/DorisStreamLoadSink.scala
  extension/spark-doris-connector/src/test/scala/org/apache/doris/spark/sql/TestSparkConnector.scala
Labels: kind/enhancement, area/spark-connector, approved, reviewed

#7284 [fix](executor) set the len of StringValue to 0 when it is null
  be/src/runtime/tuple.cpp
Labels: approved, reviewed

#7285 update comment of MasterDaemon
  fe/fe-core/src/main/java/org/apache/doris/common/util/MasterDaemon.java
Labels: approved, reviewed

#7286 [refactor] make RowBatch's implement simpler clearer and better
  be/src/runtime/row_batch.cpp
  be/src/runtime/row_batch.h
Labels: kind/enhancement, approved, kind/refactor, reviewed

#7297 [fix](show) Fix bug that AdminShowDataSkew operation may cause fe oom
  fe/fe-core/src/main/java/org/apache/doris/catalog/MetadataViewer.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
Labels: approved, reviewed

#7300 [enhancement] Enable fe audit plugin to audit more infos for query
  docs/en/extending-doris/audit-plugin.md
  docs/zh-CN/extending-doris/audit-plugin.md
  fe_plugins/auditloader/src/main/java/org/apache/doris/plugin/audit/AuditLoaderPlugin.java
  fe_plugins/auditloader/src/main/java/org/apache/doris/plugin/audit/DorisStreamLoader.java
Labels: approved, reviewed

#7311 [UT] Fix fe unit test failed
  fe/fe-core/pom.xml
  fe/fe-core/src/test/java/org/apache/doris/mysql/MysqlChannelTest.java
  fe/pom.xml
Labels: approved, reviewed

#7312 [revert] "clean too many bdbje log"
  fe/fe-core/src/main/java/org/apache/doris/journal/bdbje/BDBEnvironment.java
Labels: approved, kind/revert, reviewed

#7290 [fix](select join) Make selected slotRef nullable when slotRef is from nullable tuple in outer join sql block
  fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/SelectStmtTest.java
Labels: kind/bug, area/sql/planner, approved, reviewed

#7211 [refactor] move orthogonal bitmap udaf as build in functions
  be/src/exprs/bitmap_function.cpp
  be/src/exprs/bitmap_function.h
  be/src/http/CMakeLists.txt
  be/src/udf/udf.h
  contrib/udf/CMakeLists.txt
  contrib/udf/src/udaf_orthogonal_bitmap/CMakeLists.txt
  contrib/udf/src/udaf_orthogonal_bitmap/bitmap_value.h
  contrib/udf/src/udaf_orthogonal_bitmap/orthogonal_bitmap_function.cpp
  contrib/udf/src/udaf_orthogonal_bitmap/orthogonal_bitmap_function.h
  contrib/udf/src/udaf_orthogonal_bitmap/string_value.h
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/administrator-guide/orthogonal-bitmap-manual.md
  docs/en/sql-reference/sql-functions/bitmap-functions/orthogonal_bitmap_intersect.md
  docs/en/sql-reference/sql-functions/bitmap-functions/orthogonal_bitmap_intersect_count.md
  docs/en/sql-reference/sql-functions/bitmap-functions/orthogonal_bitmap_union_count.md
  docs/zh-CN/administrator-guide/orthogonal-bitmap-manual.md
  docs/zh-CN/sql-reference/sql-functions/bitmap-functions/orthogonal_bitmap_intersect.md
  docs/zh-CN/sql-reference/sql-functions/bitmap-functions/orthogonal_bitmap_intersect_count.md
  docs/zh-CN/sql-reference/sql-functions/bitmap-functions/orthogonal_bitmap_union_count.md
  fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionSet.java
Labels: kind/feature, approved, reviewed

#7254 [fix](load) Fix bug that show load may be blocked
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BulkLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/TransactionState.java
Labels: kind/bug, area/load, approved, reviewed

#7231 [feat-opt](cache) Optimize sql cache
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/CacheAnalyzer.java
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/PartitionCache.java
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/SqlCache.java
  fe/fe-core/src/test/java/org/apache/doris/qe/PartitionCacheTest.java
Labels: kind/enhancement, approved, reviewed

#7310 [document] modify PR template
  .github/PULL_REQUEST_TEMPLATE.md
  fe/fe-core/src/main/java/org/apache/doris/PaloFe.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectScheduler.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SimpleScheduler.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
Labels: approved, reviewed

#7321 Patch 1
  docs/en/getting-started/data-model-rollup.md
  docs/zh-CN/getting-started/data-model-rollup.md
Labels: kind/documentation, approved, reviewed

#7330 [Fix](lateral view)(subquery) Fix column materialization error
  fe/fe-core/src/main/java/org/apache/doris/analysis/LateralViewRef.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/QueryStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/fe-core/src/main/java/org/apache/doris/planner/TableFunctionNode.java
  fe/fe-core/src/test/java/org/apache/doris/planner/TableFunctionPlanTest.java
Labels: kind/bug, area/sql/planner, approved, reviewed

#7335 [fix](forward) Avoid endless forward execution
  docs/en/faq/faq.md
  docs/zh-CN/faq/faq.md
  fe/fe-core/src/main/java/org/apache/doris/common/proc/FrontendsProcNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContext.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
Labels: kind/bug, kind/documentation, approved, reviewed

#7260 [Bug]Fix BE coredump when manual compaction task is triggered
  be/src/http/action/compaction_action.cpp
  be/src/http/action/compaction_action.h
  be/src/olap/olap_server.cpp
  be/src/olap/storage_engine.h
  be/src/olap/tablet.h
Labels: kind/bug, approved, reviewed

#7306 [document] add java formatter in doc
  .github/workflows/clang-format.yml
  docs/en/developer-guide/java-format-code.md
  docs/zh-CN/developer-guide/java-format-code.md
Labels: kind/documentation, approved, reviewed

#7307 [enhancement] add more content of gitignore file
  .gitignore
Labels: approved, reviewed

#7323 [fix](syntax)(log) Can not use stream as identifier
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadJob.java
Labels: approved, reviewed

#7283 [improvement](compaction)(tablet repair) Add missing rowsets in compaction status url and support force dropping redundant replica
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
  be/src/olap/version_graph.cpp
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/administrator-guide/config/fe_config.md
  docs/en/administrator-guide/http-actions/compaction-action.md
  docs/en/community/commit-format-specification.md
  docs/zh-CN/administrator-guide/config/fe_config.md
  docs/zh-CN/administrator-guide/http-actions/compaction-action.md
  docs/zh-CN/community/commit-format-specification.md
  fe/fe-core/src/main/java/org/apache/doris/catalog/TabletInvertedIndex.java
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletScheduler.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/MysqlChannel.java
  fe/fe-core/src/test/java/org/apache/doris/mysql/MysqlChannelTest.java
Labels: approved, area/config, area/compact, reviewed, area/tablet-scheduler

#7302 [refactor] modify the control flow code to improve code readability
  fe/fe-core/src/main/java/org/apache/doris/PaloFe.java
Labels: approved, reviewed

#7319 [refactor] modify the implements of tuple & RowBatch
  be/src/common/utils.h
  be/src/runtime/row_batch.cpp
  be/src/runtime/row_batch.h
  be/src/runtime/tuple.cpp
Labels: approved, kind/refactor, reviewed

#7351 Optimize for single rowset
  be/src/olap/tuple_reader.cpp
Labels: approved, reviewed

#7353 [typo](load)correct the error of ‘EtlJobMgr::get_job_status’ function
  be/src/runtime/etl_job_mgr.cpp
Labels: kind/bug, good first issue, area/load

#7309 [Document] Improve the chapter on debugging FE in doc.
  docs/en/developer-guide/fe-idea-dev.md
  docs/zh-CN/developer-guide/fe-idea-dev.md
Labels: good first issue, kind/documentation, approved, reviewed

#7383 [fix] LRUCache::prune_if may not remove all the entries matching the predicate
  be/src/olap/lru_cache.cpp
  be/src/olap/lru_cache.h
  be/src/olap/segment_loader.cpp
  be/test/olap/lru_cache_test.cpp
Labels: kind/bug, approved, reviewed

#7350 [doc]update the compilation.md
  docs/en/installing/compilation.md
  docs/zh-CN/installing/compilation.md
Labels: kind/documentation, approved, reviewed

#7373 [Refactor && Bug-fix] Refactor the code of fold constant mgr and fix some undefine behavior and mem leak promblem in fold constant
  be/src/runtime/CMakeLists.txt
  be/src/runtime/exec_env.h
  be/src/runtime/exec_env_init.cpp
  be/src/runtime/fold_constant_executor.cpp
  be/src/runtime/fold_constant_executor.h
  be/src/service/internal_service.cpp
  gensrc/thrift/PaloInternalService.thrift
Labels: approved, reviewed

#7378 [log](schema change) Add a clear memory description in the log
  be/src/olap/schema_change.cpp
Labels: approved, reviewed

#7394 [deps](log4j) Upgrade log4j 2 to 2.16.0
  fe/fe-core/pom.xml
  fe/pom.xml
  fe_plugins/pom.xml
  fs_brokers/apache_hdfs_broker/pom.xml
Labels: approved, reviewed

#7276 [Feature] Support return bitmp/hll data in select statement
  be/src/exec/parquet_writer.cpp
  be/src/exec/parquet_writer.h
  be/src/runtime/file_result_writer.cpp
  be/src/runtime/file_result_writer.h
  be/src/runtime/mysql_result_writer.cpp
  be/src/runtime/mysql_result_writer.h
  be/src/runtime/result_file_sink.cpp
  be/src/runtime/result_sink.cpp
  be/src/runtime/result_writer.h
  be/src/runtime/runtime_state.h
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/administrator-guide/variables.md
  docs/en/developer-guide/bitmap-hll-file-format.md
  docs/zh-CN/administrator-guide/variables.md
  docs/zh-CN/developer-guide/bitmap-hll-file-format.md
  fe/fe-common/pom.xml
  fe/fe-common/src/main/java/org/apache/doris/common/io/BitmapValue.java
  fe/fe-common/src/main/java/org/apache/doris/common/io/Codec.java
  fe/fe-common/src/main/java/org/apache/doris/common/io/Hll.java
  fe/fe-common/src/main/java/org/apache/doris/common/io/Roaring64Map.java
  fe/fe-common/src/test/java/org/apache/doris/common/io/BitmapValueTest.java
  fe/fe-common/src/test/java/org/apache/doris/common/io/HllTest.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/OutFileClause.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/spark-dpp/pom.xml
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/DorisKryoRegistrator.java
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/SparkRDDAggregator.java
  gensrc/thrift/PaloInternalService.thrift
Labels: approved, reviewed

#7377 [fix](ut) Fix run fe ut failed, be ut memory leak and build thirdparty failed
  be/CMakeLists.txt
  be/test/exprs/string_functions_test.cpp
  be/test/util/counts_test.cpp
  be/test/util/tuple_row_zorder_compare_test.cpp
  fe/spark-dpp/pom.xml
  thirdparty/build-thirdparty.sh
  thirdparty/vars.sh
Labels: approved, reviewed

#7380 [chore][community](github) Remove travis and add github action
  .github/workflows/build-extension.yml
  .github/workflows/clang-format.yml
  .travis.yml
  extension/flink-doris-connector/build.sh
  extension/flink-doris-connector/pom.xml
  extension/spark-doris-connector/build.sh
Labels: area/community, area/build, approved, reviewed

#7232 [improvement](flink-connector) DataSourceFunction read doris supports parallel
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/datastream/DorisSourceFunction.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/rest/RestService.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSource.java
  extension/flink-doris-connector/src/test/java/org/apache/doris/flink/DorisSourceExample.java
Labels: approved, area/flink-connector, reviewed

#7131 Refactor olap scannode
  be/src/exec/exec_node.cpp
  be/src/exec/exec_node.h
  be/src/exec/olap_scan_node.cpp
  be/src/exec/olap_scan_node.h
  be/src/exec/olap_scanner.cpp
  be/src/exec/olap_scanner.h
  be/src/exec/scan_node.h
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/plan_fragment_executor.cpp
  be/src/runtime/plan_fragment_executor.h
Labels: approved, reviewed

#7348 [Opt] Opt the unique reader to reduce uncessary compare and function call
  be/src/olap/collect_iterator.cpp
  be/src/olap/collect_iterator.h
  be/src/olap/reader.cpp
  be/src/olap/tuple_reader.cpp
Labels: kind/enhancement, approved, reviewed

#7360 [fix] skip the condition of null
  fe/fe-core/src/main/java/org/apache/doris/analysis/InsertStmt.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PlanNode.java
Labels: approved, reviewed

#7370 [Doc]sql block rule bugfix
  docs/en/administrator-guide/block-rule/sql-block.md
  docs/zh-CN/administrator-guide/block-rule/sql-block.md
Labels: kind/documentation, approved, reviewed

#7371 [fix][refactor](broker load) refactor the scheduling logic of broker load
  be/src/runtime/runtime_state.cpp
  be/src/runtime/runtime_state.h
  docs/en/administrator-guide/load-data/broker-load-manual.md
  docs/zh-CN/administrator-guide/load-data/broker-load-manual.md
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/common/ThreadPoolManager.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BrokerLoadPendingTask.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadJobScheduler.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadLoadingTask.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadManager.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadTimeoutChecker.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkLoadPendingTask.java
  fe/fe-core/src/main/java/org/apache/doris/task/MasterTaskExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/LoadJobTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/SparkLoadJobTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/SparkLoadPendingTaskTest.java
Labels: kind/bug, area/load, approved, kind/refactor, reviewed

#7402 [Doc][Website] Develop the caseList component
  docs/.vuepress/components/CaseList.vue
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/.vuepress/theme/components/Home.vue
  docs/en/case-user/case-user.md
  docs/zh-CN/case-user/case-user.md
  docs/zh-CN/downloads/downloads.md
Labels: approved, reviewed

#7384 [docs](doris-flink) Add instructions for flink doris connector
  docs/en/extending-doris/flink-doris-connector.md
  docs/zh-CN/extending-doris/flink-doris-connector.md
Labels: kind/documentation, approved, reviewed

#7255 [feat](lateral-view) Support execution of lateral view stmt
  be/src/common/daemon.cpp
  be/src/exec/CMakeLists.txt
  be/src/exec/exec_node.cpp
  be/src/exec/table_function_node.cpp
  be/src/exec/table_function_node.h
  be/src/exprs/CMakeLists.txt
  be/src/exprs/scalar_fn_call.cpp
  be/src/exprs/scalar_fn_call.h
  be/src/exprs/slot_ref.cpp
  be/src/exprs/table_function/dummy_table_functions.cpp
  be/src/exprs/table_function/dummy_table_functions.h
  be/src/exprs/table_function/explode_bitmap.cpp
  be/src/exprs/table_function/explode_bitmap.h
  be/src/exprs/table_function/explode_json_array.cpp
  be/src/exprs/table_function/explode_json_array.h
  be/src/exprs/table_function/explode_split.cpp
  be/src/exprs/table_function/explode_split.h
  be/src/exprs/table_function/table_function.h
  be/src/exprs/table_function/table_function_factory.cpp
  be/src/exprs/table_function/table_function_factory.h
  be/src/runtime/descriptors.h
  be/src/util/bitmap_value.h
  be/test/util/bitmap_value_test.cpp
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/sql-reference/sql-functions/table-functions/explode-bitmap.md
  docs/en/sql-reference/sql-functions/table-functions/explode-json-array.md
  docs/en/sql-reference/sql-functions/table-functions/explode-split.md
  docs/en/sql-reference/sql-statements/Data Manipulation/lateral-view.md
  docs/zh-CN/sql-reference/sql-functions/table-functions/explode-bitmap.md
  docs/zh-CN/sql-reference/sql-functions/table-functions/explode-json-array.md
  docs/zh-CN/sql-reference/sql-functions/table-functions/explode-split.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/lateral-view.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/LateralViewRef.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SlotRef.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionSet.java
  fe/fe-core/src/main/java/org/apache/doris/planner/DistributedPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/test/java/org/apache/doris/planner/TableFunctionPlanTest.java
Labels: kind/feature, area/sql/execution, approved, reviewed

#7337 [Fix](lateral view)(subquery) Forbidden directly AGG/SORT on lateral view
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SlotRef.java
  fe/fe-core/src/main/java/org/apache/doris/planner/TableFunctionNode.java
  fe/fe-core/src/test/java/org/apache/doris/planner/TableFunctionPlanTest.java
Labels: area/sql/planner, approved, reviewed

#7413 [BUG] [RPC] fix BE crash in SendRpcResponse when high concurrency
  be/src/service/internal_service.cpp
  be/src/util/proto_util.h
  gensrc/proto/data.proto
  gensrc/proto/internal_service.proto
Labels: approved, reviewed

#7386 [enhancement] make concurrent_number for routine load task can be larger than be num
  be/src/common/config.h
  docs/en/administrator-guide/load-data/routine-load-manual.md
  docs/zh-CN/administrator-guide/load-data/routine-load-manual.md
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/KafkaRoutineLoadJob.java
  fe/fe-core/src/test/java/org/apache/doris/load/routineload/KafkaRoutineLoadJobTest.java
Labels: approved, reviewed

#7408 [deps](cyrus_sasl) Add -fPIC for cyrus_sasl
  docker/README.md
  docs/en/installing/compilation.md
  docs/zh-CN/installing/compilation.md
  thirdparty/CHANGELOG.md
  thirdparty/build-thirdparty.sh
Labels: area/dependency, approved, reviewed

#7427 Revert "[improvement](reader) optimize for single rowset reading (#7351)"
  be/src/olap/tuple_reader.cpp
Labels: kind/bug, approved, reviewed

#7404 Fix typos
  docs/zh-CN/administrator-guide/load-data/batch-delete-manual.md
  docs/zh-CN/getting-started/data-model-rollup.md
Labels: approved, reviewed

#7431 Add .asf.yaml
  .asf.yaml
Labels: approved, reviewed

#7440 [deps](log4j) log4j upgrade to 2.17.0
  fe/fe-core/pom.xml
  fe/pom.xml
  fe_plugins/pom.xml
  fs_brokers/apache_hdfs_broker/pom.xml
Labels: approved, reviewed

#7446 [build] upgrade openssl to 1.1.1m
  be/src/util/aes_util.cpp
  docker/Dockerfile
  thirdparty/CHANGELOG.md
  thirdparty/vars.sh
Labels: approved, reviewed

#7375 [fix](cache) Some view stmt cannot be obtained when view in the subquery and add cache key UT
  fe/fe-core/src/main/java/org/apache/doris/analysis/InlineViewRef.java
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/CacheAnalyzer.java
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/PartitionCache.java
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/SqlCache.java
  fe/fe-core/src/test/java/org/apache/doris/qe/PartitionCacheTest.java
Labels: kind/bug, approved, area/view, reviewed

#7407 [fix] fix sql block,move it from ConnectProcessor to StmtExecutor
  docs/en/administrator-guide/block-rule/sql-block.md
  docs/zh-CN/administrator-guide/block-rule/sql-block.md
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/blockrule/SqlBlockRuleMgrTest.java
Labels: approved, reviewed

#7332 [Enhancement] Remove the two lines of duplicate import. (#7331)
  fe/fe-core/src/main/java/org/apache/doris/rewrite/FEFunctions.java
Labels: area/build, approved, reviewed

#7318 add bloomfilter index doc
  docs/.vuepress/public/images/Bloom_filter.svg.png
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/administrator-guide/bloomfilter.md
  docs/zh-CN/administrator-guide/bloomfilter.md
Labels: kind/documentation, approved, reviewed

#7435 [fix](flink-connector) Connector should visit the surviving BE nodes
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/rest/RestService.java
Labels: approved, reviewed

#7439 [community][chore] Modify .asf.yaml and fix BE build warning
  .asf.yaml
  be/src/util/tuple_row_zorder_compare.cpp
  fe/fe-core/src/main/java/org/apache/doris/clone/ClusterLoadStatistic.java
Labels: area/community, approved, reviewed

#7449 [docs][community] Remove articles
  docs/.vuepress/public/images/binlog/image-20211110145044815.png
  docs/.vuepress/public/images/binlog/image-20211110160106602.png
  docs/.vuepress/public/images/binlog/image-20211110160331479.png
  docs/.vuepress/public/images/binlog/image-20211110160710709.png
  docs/.vuepress/public/images/cdc/image-20211025162831632.png
  docs/.vuepress/public/images/cdc/image-20211025165547903.png
  docs/.vuepress/public/images/cdc/image-20211025170642628.png
  docs/.vuepress/public/images/cdc/image-20211025182341086.png
  docs/.vuepress/public/images/cdc/image-20211025182435827.png
  docs/.vuepress/public/images/cdc/image-20211026095513892.png
  docs/.vuepress/public/images/cdc/image-20211026100505972.png
  docs/.vuepress/public/images/cdc/image-20211026100804091.png
  docs/.vuepress/public/images/cdc/image-20211026100943474.png
  docs/.vuepress/public/images/cdc/image-20211026101004547.png
  docs/.vuepress/public/images/cdc/image-20211026101203629.png
  docs/.vuepress/public/images/image-20210903132250723.png
  docs/.vuepress/public/images/image-20210903132539511.png
  docs/.vuepress/public/images/image-20210903134043421.png
  docs/en/article/articles/datax-doris-writer.md
  docs/en/article/articles/doris-binlog-load.md
  docs/en/article/articles/fe-load-balance.md
  docs/en/article/articles/flink-cdc-to-doris.md
  docs/en/developer-guide/How-to-Share-blogs.md
  docs/zh-CN/article/articles/datax-doris-writer.md
  docs/zh-CN/article/articles/doris-binlog-load.md
  docs/zh-CN/article/articles/fe-load-balance.md
  docs/zh-CN/article/articles/flink-cdc-to-doris.md
  docs/zh-CN/developer-guide/How-to-Share-blogs.md
Labels: kind/documentation, approved, reviewed

#7265 [BUG] Rewrite Bigint SlotRef to compare DecimalLiteral in Binary predicate
  fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/DecimalLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/RewriteBinaryPredicatesRule.java
  fe/fe-core/src/test/java/org/apache/doris/planner/PlannerTest.java
Labels: approved, reviewed

#7453 [Feature#7441][Doc] Seatunnel Suppoorts Doris connector
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/extending-doris/seatunnel.md
  docs/zh-CN/extending-doris/seatunnel.md
Labels: approved, reviewed

#7468 [fix](ut) fix testPartitionRebalancer ut
  fe/fe-core/src/test/java/org/apache/doris/clone/RebalanceTest.java
Labels: area/test, approved, reviewed

#7045 [Feature] make BinaryPredicate do not cast date to datetime/varchar
  be/src/exprs/bloomfilter_predicate.h
  fe/fe-core/src/main/java/org/apache/doris/analysis/BinaryPredicate.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Type.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: area/sql/planner, approved, reviewed

#7421 [BUG] fix round function for inaccuracy
  be/src/exprs/math_functions.cpp
  be/test/exprs/math_functions_test.cpp
Labels: approved, reviewed

#7430 [Bug] DCHECK fail at BitmapValue getSizeInBytes
  be/src/util/bitmap_value.h
Labels: approved, reviewed

#7437 [Bug] fix aggregate function min() at type varchar
  be/src/olap/aggregate_func.h
Labels: approved, reviewed

#7447 Add document of docker dev
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/developer-guide/docker-dev.md
  docs/zh-CN/developer-guide/docker-dev.md
  fe/fe-core/src/main/java/org/apache/doris/planner/PlanFragment.java
Labels: approved, reviewed

#7450 [improvement](flink-connector) flush data without multi httpclients
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicOutputFormat.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisStreamLoad.java
Labels: kind/enhancement, approved, reviewed

#7454 memory usage optimization for load job
  be/src/exec/base_scanner.h
  be/src/exec/broker_scan_node.cpp
  be/src/exec/broker_scanner.cpp
  be/src/exec/broker_scanner.h
  be/src/exec/json_scanner.cpp
  be/src/exec/json_scanner.h
  be/src/exec/orc_scanner.cpp
  be/src/exec/orc_scanner.h
  be/src/exec/parquet_scanner.cpp
  be/src/exec/parquet_scanner.h
  be/src/olap/push_handler.cpp
  be/src/olap/push_handler.h
  be/src/runtime/row_batch.cpp
  be/src/runtime/row_batch.h
Labels: approved, reviewed

#7466 [docs]The name of hidden column is incorrect in batch-delete-manual.md(#7465)
  docs/en/administrator-guide/load-data/batch-delete-manual.md
  docs/zh-CN/administrator-guide/load-data/batch-delete-manual.md
Labels: kind/documentation, approved

#7469 fix logic error for Tablet::capture_rs_readers
  be/src/olap/tablet.cpp
Labels: approved, reviewed

#7471 [fix](ut) Fix NPE when start FE in unit test.
  .gitignore
  fe/fe-core/src/main/java/org/apache/doris/httpv2/HttpServer.java
Labels: approved, reviewed

#7481 [Fix][UT] Fix UT `SelectStmtTest.testDeduplicateOrs`
  fe/fe-core/src/test/java/org/apache/doris/analysis/SelectStmtTest.java
Labels: approved, reviewed

#7486 [fix](ut) Fix BE broker scanner unit test bug
  be/test/exec/broker_scanner_test.cpp
  be/test/exec/orc_scanner_test.cpp
Labels: approved, reviewed

#7362 Fix mv rewrite bug
  fe/fe-core/src/main/java/org/apache/doris/analysis/QueryStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SetOperationStmt.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/planner/MaterializedViewFunctionTest.java
Labels: kind/bug, approved, area/materialized-view, reviewed

#7379 [Function]support bitmap_union/intersect have more columns parameters
  be/src/exprs/bitmap_function.cpp
  be/src/exprs/bitmap_function.h
  be/test/exprs/bitmap_function_test.cpp
  docs/en/sql-reference/sql-functions/bitmap-functions/bitmap_and.md
  docs/en/sql-reference/sql-functions/bitmap-functions/bitmap_and_count.md
  docs/en/sql-reference/sql-functions/bitmap-functions/bitmap_or.md
  docs/en/sql-reference/sql-functions/bitmap-functions/bitmap_or_count.md
  docs/en/sql-reference/sql-functions/bitmap-functions/bitmap_xor.md
  docs/en/sql-reference/sql-functions/bitmap-functions/bitmap_xor_count.md
  docs/zh-CN/sql-reference/sql-functions/bitmap-functions/bitmap_and.md
  docs/zh-CN/sql-reference/sql-functions/bitmap-functions/bitmap_and_count.md
  docs/zh-CN/sql-reference/sql-functions/bitmap-functions/bitmap_or.md
  docs/zh-CN/sql-reference/sql-functions/bitmap-functions/bitmap_or_count.md
  docs/zh-CN/sql-reference/sql-functions/bitmap-functions/bitmap_xor.md
  docs/zh-CN/sql-reference/sql-functions/bitmap-functions/bitmap_xor_count.md
  gensrc/script/doris_builtins_functions.py
Labels: approved, reviewed

#7411 [Bug] Grouping set clause act wrong for fucntion expr in view (#7410)
  fe/fe-core/src/main/java/org/apache/doris/planner/RepeatNode.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: approved, reviewed

#7460 [docs](executor) correct some be error code
  docs/en/administrator-guide/operation/be-olap-error-code.md
  docs/zh-CN/administrator-guide/operation/be-olap-error-code.md
Labels: approved, reviewed

#7470 add Dockerfile with clang11
  docker/Dockerfile
Labels: approved, reviewed

#7480 [Bug][SparkLoad] fix Roaring64Map big-endian read/write in de/seriali…
  fe/fe-common/src/main/java/org/apache/doris/common/io/Roaring64Map.java
Labels: kind/bug, approved, area/spark-load, reviewed

#7484 [Feature] support ks3 storage in doris
  fs_brokers/apache_hdfs_broker/src/main/java/org/apache/doris/broker/hdfs/FileSystemManager.java
Labels: area/broker, approved, reviewed

#7485 Modify the maximum number of records written by Spark/Flink connector each time. The default value is 10000.
  docs/en/extending-doris/flink-doris-connector.md
  docs/en/extending-doris/spark-doris-connector.md
  docs/zh-CN/extending-doris/flink-doris-connector.md
  docs/zh-CN/extending-doris/spark-doris-connector.md
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisExecutionOptions.java
  extension/spark-doris-connector/src/main/java/org/apache/doris/spark/cfg/ConfigurationOptions.java
  extension/spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/DorisStreamLoadSink.scala
Labels: approved, reviewed

#7464 [feature] Suport national secret (national commercial password) algorithm SM3/SM4
  be/src/exprs/encryption_functions.cpp
  be/src/exprs/encryption_functions.h
  be/src/olap/data_dir.cpp
  be/src/util/CMakeLists.txt
  be/src/util/aes_util.cpp
  be/src/util/encryption_util.cpp
  be/src/util/encryption_util.h
  be/src/util/sm3.cpp
  be/src/util/sm3.h
  be/test/exprs/encryption_functions_test.cpp
  be/test/util/CMakeLists.txt
  be/test/util/aes_util_test.cpp
  be/test/util/encryption_util_test.cpp
  be/test/util/sm3_test.cpp
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/administrator-guide/variables.md
  docs/en/sql-reference/sql-functions/encrypt-digest-functions/aes.md
  docs/en/sql-reference/sql-functions/encrypt-digest-functions/md5.md
  docs/en/sql-reference/sql-functions/encrypt-digest-functions/md5sum.md
  docs/en/sql-reference/sql-functions/encrypt-digest-functions/sm3.md
  docs/en/sql-reference/sql-functions/encrypt-digest-functions/sm3sum.md
  docs/en/sql-reference/sql-functions/encrypt-digest-functions/sm4.md
  docs/zh-CN/administrator-guide/variables.md
  docs/zh-CN/sql-reference/sql-functions/encrypt-digest-functions/aes.md
  docs/zh-CN/sql-reference/sql-functions/encrypt-digest-functions/md5.md
  docs/zh-CN/sql-reference/sql-functions/encrypt-digest-functions/md5sum.md
  docs/zh-CN/sql-reference/sql-functions/encrypt-digest-functions/sm3.md
  docs/zh-CN/sql-reference/sql-functions/encrypt-digest-functions/sm3sum.md
  docs/zh-CN/sql-reference/sql-functions/encrypt-digest-functions/sm4.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  gensrc/script/doris_builtins_functions.py
Labels: approved, reviewed

#7213 fix partition rebalance bug
  fe/fe-core/src/main/java/org/apache/doris/clone/TwoDimensionalGreedyRebalanceAlgo.java
Labels: kind/bug, approved, area/balance, reviewed

#7434 Implement V2 version of partition prune.
  fe/fe-core/src/main/java/org/apache/doris/analysis/BinaryPredicate.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/PredicateUtils.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SetVar.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/PartitionKey.java
  fe/fe-core/src/main/java/org/apache/doris/planner/ColumnBound.java
  fe/fe-core/src/main/java/org/apache/doris/planner/ColumnRange.java
  fe/fe-core/src/main/java/org/apache/doris/planner/ListPartitionPrunerV2.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PartitionPruner.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PartitionPrunerV2Base.java
  fe/fe-core/src/main/java/org/apache/doris/planner/RangePartitionPrunerV2.java
  fe/fe-core/src/main/java/org/apache/doris/planner/ScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ListPartitionPrunerTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/PartitionPruneTestBase.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/RangePartitionPruneTest.java
Labels: area/sql/planner, approved, reviewed

#7517 Revert "[improvement](planner) make BinaryPredicate do not cast date to datetime/varchar (#7045)"
  be/src/exprs/bloomfilter_predicate.h
  fe/fe-core/src/main/java/org/apache/doris/analysis/BinaryPredicate.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Type.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: kind/revert

#7477 [refactor] Standardize the pom files, prepare for deployment to maven
  .gitignore
  build.sh
  extension/flink-doris-connector/pom.xml
  extension/spark-doris-connector/pom.xml
  extension/spark-doris-connector/pom_3.0.xml
  fe/fe-common/pom.xml
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupJobInfo.java
  fe/fe-core/src/main/java/org/apache/doris/common/profile/MultiProfileTreeBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/CommonUserProperties.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/qe/StmtExecutorTest.java
  fe/pom.xml
  fe/spark-dpp/pom.xml
  fe_plugins/auditdemo/pom.xml
  fe_plugins/auditloader/pom.xml
  fe_plugins/pom.xml
  fs_brokers/apache_hdfs_broker/pom.xml
  samples/doris-demo/flink-demo/pom.xml
  samples/doris-demo/pom.xml
  samples/doris-demo/spark-demo/pom.xml
  samples/doris-demo/spring-jdbc-demo/pom.xml
  samples/doris-demo/stream-load-demo/pom.xml
Labels: area/build, approved, reviewed

#7428 [improvement] optimize java cmd find
  bin/start_be.sh
  bin/start_fe.sh
  env.sh
  fs_brokers/apache_hdfs_broker/bin/start_broker.sh
  gensrc/script/gen_build_version.sh
Labels: approved, area/easy-to-use, reviewed

#7536 Upgrade Log4j to 2.7.1 to solve the CVE-2021-44832 security vulnerability
  fe/fe-core/pom.xml
  fe/pom.xml
  fe_plugins/pom.xml
  fs_brokers/apache_hdfs_broker/pom.xml
Labels: approved, reviewed

#7507 [bug](fold-constant)fix having clause constant folding
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
Labels: approved, reviewed

#7497 Add user manual for hdfs load and transaction.
  be/src/common/config.h
  be/src/env/env_remote.cpp
  be/src/exec/hdfs_writer.cpp
  be/src/olap/data_dir.cpp
  be/src/runtime/export_sink.cpp
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/administrator-guide/outfile.md
  docs/en/sql-reference/sql-statements/Data Manipulation/BROKER LOAD.md
  docs/en/sql-reference/sql-statements/Data Manipulation/EXPORT.md
  docs/en/sql-reference/sql-statements/Data Manipulation/OUTFILE.md
  docs/zh-CN/administrator-guide/outfile.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/BROKER LOAD.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/EXPORT.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/OUTFILE.md
Labels: approved, reviewed

#7495 [fix](lower_case_table_names) Fix the bug of case-sensitive aliases in the query when lower_case_table_names=1 is set
  fe/fe-core/src/main/java/org/apache/doris/analysis/TableRef.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/TableNameStoredLowercaseTest.java
Labels: approved

#7512 [Bug] Fix 'nan' returned by function 'percentile_approx' can not be parsed as double type by JDBC
  be/src/exprs/aggregate_functions.cpp
Labels: approved, reviewed

#7538 [fix] fix TableRef.java checkstyle failed
  fe/fe-core/src/main/java/org/apache/doris/analysis/TableRef.java
Labels: area/build, approved, reviewed

#7533 [fix](cache) Int overflow causes the wrong latest table to be obtained
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/CacheAnalyzer.java
Labels: approved, reviewed

#7357 [feature] (planner) InferPredicate (#7096)
  docs/en/administrator-guide/variables.md
  docs/zh-CN/administrator-guide/variables.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SlotRef.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/TableRef.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/UpdateStmt.java
  fe/fe-core/src/main/java/org/apache/doris/load/ExportJob.java
  fe/fe-core/src/main/java/org/apache/doris/planner/LoadScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/BetweenToCompoundRule.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/CompoundPredicateWriteRule.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/ExprRewriteRule.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/ExprRewriter.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/ExtractCommonFactorsRule.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/FoldConstantsRule.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/InferFiltersRule.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/NormalizeBinaryPredicatesRule.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/RewriteAliasFunctionRule.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/RewriteBinaryPredicatesRule.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/RewriteEncryptKeyRule.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/RewriteFromUnixTimeRule.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/RewriteLikePredicateRule.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/SimplifyInvalidDateBinaryPredicatesDateRule.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/mvrewrite/CountDistinctToBitmap.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/mvrewrite/CountDistinctToBitmapOrHLLRule.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/mvrewrite/CountFieldToSum.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/mvrewrite/HLLHashToSlotRefRule.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/mvrewrite/NDVToHll.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/mvrewrite/ToBitmapToSlotRefRule.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
  fe/fe-core/src/test/java/org/apache/doris/rewrite/InferFiltersRuleTest.java
  fe/fe-core/src/test/java/org/apache/doris/rewrite/mvrewrite/CountFieldToSumTest.java
Labels: kind/feature, good first issue, area/sql/planner, approved, reviewed

#7542 Fix NPE when using `ConnectContext` instance in partition pruning related logic.
  fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/ScanNode.java
Labels: area/sql/planner, approved, reviewed

#7422 [docs] add more faq and FE debugging method
  README.md
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/community/security.md
  docs/en/developer-guide/debug-tool.md
  docs/en/extending-doris/seatunnel.md
  docs/en/faq/faq.md
  docs/zh-CN/community/security.md
  docs/zh-CN/developer-guide/debug-tool.md
  docs/zh-CN/downloads/downloads.md
  docs/zh-CN/extending-doris/seatunnel.md
  docs/zh-CN/faq/faq.md
Labels: kind/documentation, approved, reviewed

#7448 [BloomFilter](bug) Fix error when char(0)
  be/src/exprs/bloomfilter_predicate.h
Labels: approved, reviewed

#7494 [BUGFIX] forbidden create materialized view with distinct
  fe/fe-core/src/main/java/org/apache/doris/alter/RollupJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateMaterializedViewStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/MVColumnBitmapUnionPattern.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/MVColumnHLLUnionPattern.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/MVColumnOneChildPattern.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/AggregateFunction.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/MaterializedIndexMeta.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/CreateMaterializedViewStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/MVColumnBitmapUnionPatternTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/MVColumnHLLUnionPatternTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/MVColumnOneChildPatternTest.java
Labels: kind/bug, approved, area/materialized-view, reviewed

#7506 [Feature] broker load disable cache config added
  docs/en/sql-reference/sql-statements/Data Manipulation/LOAD.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/LOAD.md
  fs_brokers/apache_hdfs_broker/src/main/java/org/apache/doris/broker/hdfs/FileSystemManager.java
Labels: approved, reviewed

#7541 [deps][chore] make openssl works with old glibc version
  be/src/runtime/fragment_mgr.cpp
  env.sh
  thirdparty/CHANGELOG.md
  thirdparty/build-thirdparty.sh
  thirdparty/vars.sh
Labels: approved, reviewed
