Repository apache/doris, pull requests merged in 2021-04, with the labels that each got.

#5587 [bug-fix] Fix cluster property in hadoop/broker load
  fe/fe-core/src/main/java/org/apache/doris/analysis/LoadStmt.java
Labels: approved, area/load, kind/bug

#5591 [Bug] upgrade log4j version from 2.12.1 to 2.14.0 to fix performance issue in JDK11 using ZGC
  fe/pom.xml
Labels: approved

#5594 [FE][Bug]Update log4j-web to fix a security issue
  fe/fe-core/pom.xml
Labels: approved

#5595 [FE][Fix]Update commons-collections to fix a security issue
  fe/pom.xml
Labels: approved

#5596 [Doc] Update required camke version in README.MD
  README.md
Labels: approved, kind/documentation

#5593 [FE][Bug] Update Spark version to fix a security issue
  fe/pom.xml
  fe/spark-dpp/pom.xml
Labels: approved

#5605 [Enhance] Filter all non-journal db when getting journal db names
  fe/fe-core/src/main/java/org/apache/doris/journal/bdbje/BDBEnvironment.java
Labels: approved, area/catalog

#5592 [Metrics][LOG] Update metrics of 'max_compaction_score' and log for compaction
  be/src/olap/compaction.cpp
  be/src/olap/olap_server.cpp
  be/src/olap/tablet_manager.cpp
  be/src/olap/tablet_manager.h
Labels: approved, area/compact

#5585 Solve the situation that the hardware information of the Web UI home page cannot be loaded
  ui/src/pages/home/index.tsx
Labels: approved, area/fe/frontpage

#5584 [FE] [BUG] GroupingFunctionCallExpr: realChildren should be copied too.
  fe/fe-core/src/main/java/org/apache/doris/analysis/GroupingFunctionCallExpr.java
Labels: SQL Bug, approved, kind/bug

#5581 [Function] Add BE udf bitmap_min (#2538)
  be/src/exprs/bitmap_function.cpp
  be/src/exprs/bitmap_function.h
  be/src/util/bitmap_value.h
  be/test/exprs/bitmap_function_test.cpp
  docs/en/sql-reference/sql-functions/bitmap-functions/bitmap_min.md
  docs/zh-CN/sql-reference/sql-functions/bitmap-functions/bitmap_min.md
  gensrc/script/doris_builtins_functions.py
Labels: approved, area/sql/function, good first issue

#5579 [Refactor] Remove boost filesystem
  be/src/agent/agent_server.cpp
  be/src/agent/cgroups_mgr.cpp
  be/src/agent/heartbeat_server.cpp
  be/src/agent/pusher.cpp
  be/src/http/action/restore_tablet_action.cpp
  be/src/olap/data_dir.cpp
  be/src/olap/push_handler.cpp
  be/src/olap/rowset/segment_group.cpp
  be/src/olap/rowset/segment_writer.cpp
  be/src/olap/snapshot_manager.cpp
  be/src/olap/storage_engine.cpp
  be/src/olap/tablet.cpp
  be/src/olap/tablet_manager.cpp
  be/src/olap/task/engine_batch_load_task.cpp
  be/src/olap/task/engine_clone_task.cpp
  be/src/olap/txn_manager.cpp
  be/src/olap/utils.cpp
  be/src/olap/utils.h
  be/src/runtime/etl_job_mgr.cpp
  be/src/runtime/snapshot_loader.cpp
  be/src/runtime/tmp_file_mgr.cc
  be/src/tools/meta_tool.cpp
  be/src/util/broker_storage_backend.cpp
  be/src/util/cpu_info.cpp
  be/src/util/file_utils.cpp
  be/src/util/filesystem_util.cc
  be/src/util/path_util.h
  be/test/agent/cgroups_mgr_test.cpp
  be/test/olap/byte_buffer_test.cpp
  be/test/olap/file_helper_test.cpp
  be/test/olap/file_utils_test.cpp
  be/test/olap/olap_meta_test.cpp
  be/test/olap/olap_snapshot_converter_test.cpp
  be/test/olap/options_test.cpp
  be/test/olap/rowset/alpha_rowset_test.cpp
  be/test/olap/rowset/rowset_converter_test.cpp
  be/test/olap/rowset/rowset_meta_manager_test.cpp
  be/test/olap/rowset/rowset_meta_test.cpp
  be/test/olap/rowset/segment_v2/segment_test.cpp
  be/test/olap/tablet_meta_manager_test.cpp
  be/test/olap/tablet_mgr_test.cpp
  be/test/olap/timestamped_version_tracker_test.cpp
  be/test/olap/txn_manager_test.cpp
  be/test/runtime/buffered_block_mgr2_test.cpp
  be/test/runtime/buffered_tuple_stream2_test.cpp
  be/test/runtime/snapshot_loader_test.cpp
  be/test/runtime/tmp_file_mgr_test.cpp
  be/test/util/filesystem_util_test.cpp
Labels: approved, kind/refactor

#5571 [refacor] Remove minizip source code
  be/CMakeLists.txt
  be/src/util/CMakeLists.txt
  be/src/util/minizip/MiniZip64_info.txt
  be/src/util/minizip/ioapi.c
  be/src/util/minizip/ioapi.h
  be/src/util/minizip/unzip.c
  be/src/util/minizip/unzip.h
  be/src/util/zip_util.h
  docker/Dockerfile.gcc7
  thirdparty/build-thirdparty.sh
Labels: approved, area/dependency

#5578 [Bug] keytab file maybe not thread-safe
  fs_brokers/apache_hdfs_broker/src/main/java/org/apache/doris/broker/hdfs/FileSystemManager.java
Labels: approved

#5552 [Refator] Make LikePredicate's operator public
  fe/fe-core/src/main/java/org/apache/doris/analysis/LikePredicate.java
Labels: approved

#5516 [Enhance] Make MemTracker more accurate (#5515)
  be/src/http/action/compaction_action.h
  be/src/olap/base_tablet.cpp
  be/src/olap/compaction.cpp
  be/src/olap/compaction.h
  be/src/olap/delta_writer.cpp
  be/src/olap/generic_iterators.cpp
  be/src/olap/generic_iterators.h
  be/src/olap/iterators.h
  be/src/olap/lru_cache.cpp
  be/src/olap/lru_cache.h
  be/src/olap/page_cache.cpp
  be/src/olap/page_cache.h
  be/src/olap/push_handler.cpp
  be/src/olap/row_block2.cpp
  be/src/olap/row_block2.h
  be/src/olap/rowset/alpha_rowset.cpp
  be/src/olap/rowset/alpha_rowset.h
  be/src/olap/rowset/beta_rowset.cpp
  be/src/olap/rowset/beta_rowset.h
  be/src/olap/rowset/beta_rowset_reader.cpp
  be/src/olap/rowset/beta_rowset_writer.cpp
  be/src/olap/rowset/rowset.cpp
  be/src/olap/rowset/rowset.h
  be/src/olap/rowset/rowset_writer_context.h
  be/src/olap/rowset/segment_v2/column_reader.cpp
  be/src/olap/rowset/segment_v2/column_reader.h
  be/src/olap/rowset/segment_v2/column_writer.h
  be/src/olap/rowset/segment_v2/options.h
  be/src/olap/rowset/segment_v2/segment.cpp
  be/src/olap/rowset/segment_v2/segment.h
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/olap/rowset/segment_v2/segment_iterator.h
  be/src/olap/rowset/segment_v2/segment_writer.cpp
  be/src/olap/rowset/segment_v2/segment_writer.h
  be/src/olap/schema_change.cpp
  be/src/olap/schema_change.h
  be/src/olap/storage_engine.cpp
  be/src/olap/storage_engine.h
  be/src/olap/tablet_manager.cpp
  be/src/olap/tablet_manager.h
  be/src/olap/tablet_meta.cpp
  be/src/olap/tablet_meta.h
  be/src/olap/tablet_schema.cpp
  be/src/olap/tablet_schema.h
  be/src/olap/task/engine_alter_tablet_task.cpp
  be/src/runtime/exec_env_init.cpp
  be/src/runtime/load_channel_mgr.cpp
  be/src/runtime/mem_tracker.cpp
  be/test/olap/generic_iterators_test.cpp
  be/test/olap/rowset/segment_v2/segment_test.cpp
Labels: approved, kind/enhancement, kind/refactor

#5554 Add fmt library to speed up mysql text result serialization
  be/CMakeLists.txt
  be/src/runtime/mysql_result_writer.cpp
  be/src/util/mysql_row_buffer.cpp
  thirdparty/build-thirdparty.sh
  thirdparty/vars.sh
Labels: approved, kind/enhancement

#5608 [Bug] Fix bug that isPreAggregation is incorrectly set
  be/src/exec/olap_scanner.cpp
  be/src/olap/reader.cpp
  fe/fe-core/src/main/java/org/apache/doris/planner/MaterializedViewSelector.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
Labels: approved, area/materialized-view, kind/bug

#5521 [Colocate plan][Step1] Colocate join covers more situations
  fe/fe-core/src/main/java/org/apache/doris/analysis/Expr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ModifyTablePropertiesClause.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/clone/ColocateTableCheckerAndBalancer.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/planner/DistributedPlanColocateRule.java
  fe/fe-core/src/main/java/org/apache/doris/planner/DistributedPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/planner/HashJoinNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PlanNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/system/SystemInfoService.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ExprTest.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/ColocateTableTest.java
  fe/fe-core/src/test/java/org/apache/doris/clone/ColocateTableCheckerAndBalancerTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/ColocatePlanTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/AnotherDemoTest.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/UtFrameUtils.java
Labels: approved, area/colocated, area/sql/planner, kind/enhancement

#5616 [build] Update Dockerfile add libasan
  docker/Dockerfile
  docker/Dockerfile.gcc7
Labels: approved, area/build, area/test

#5325 [Doris On ES][WIP] Support external ES table with `SSL` secured and configurable node sniffing
  be/src/exec/es/es_scan_reader.cpp
  be/src/exec/es/es_scan_reader.h
  be/src/http/http_client.h
  docs/en/extending-doris/doris-on-es.md
  docs/zh-CN/extending-doris/doris-on-es.md
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/EsTable.java
  fe/fe-core/src/main/java/org/apache/doris/external/elasticsearch/EsNodeInfo.java
  fe/fe-core/src/main/java/org/apache/doris/external/elasticsearch/EsRepository.java
  fe/fe-core/src/main/java/org/apache/doris/external/elasticsearch/EsRestClient.java
  fe/fe-core/src/main/java/org/apache/doris/external/elasticsearch/EsTablePartitions.java
  fe/fe-core/src/main/java/org/apache/doris/external/elasticsearch/EsUtil.java
  fe/fe-core/src/main/java/org/apache/doris/external/elasticsearch/PartitionPhase.java
  fe/fe-core/src/main/java/org/apache/doris/external/elasticsearch/SearchContext.java
  fe/fe-core/src/main/java/org/apache/doris/planner/EsScanNode.java
  fe/fe-core/src/test/java/org/apache/doris/external/elasticsearch/PartitionPhaseTest.java
Labels: approved, area/doris-on-es

#5630 [LICENSE] Fix license issue
  LICENSE.txt
  be/src/olap/rowset/alpha_rowset_writer.h
  be/src/olap/rowset/segment_v2/empty_segment_iterator.cpp
Labels: approved, kind/license

#5642 [LICENSE] Remove unused font file and fix license
  LICENSE.txt
  NOTICE.txt
  ui/public/fonts/Read Me.txt
  ui/public/fonts/fonts/icomoon.eot
  ui/public/fonts/fonts/icomoon.svg
  ui/public/fonts/fonts/icomoon.ttf
  ui/public/fonts/fonts/icomoon.woff
  ui/public/fonts/iconfont/iconfont.eot
  ui/public/fonts/iconfont/iconfont.svg
  ui/public/fonts/iconfont/iconfont.ttf
  ui/public/fonts/iconfont/iconfont.woff
  ui/public/fonts/selection.json
  ui/public/fonts/style.min.css
Labels: approved, kind/license

#5624 [Docs] Update README.md about GCC version
  README.md
Labels: approved, kind/documentation

#5628 [DOC] Add docs of warning of Docker env 1.3 of JDK 11 and some doc of FE config.
  docs/en/administrator-guide/config/fe_config.md
  docs/en/installing/compilation.md
  docs/zh-CN/administrator-guide/config/fe_config.md
  docs/zh-CN/installing/compilation.md
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
Labels: approved, kind/documentation

#5632 [BUG] fix single version decision problem
  be/src/exec/olap_scanner.cpp
Labels: approved, kind/bug

#5611 [refactor] Remove boost_foreach, using c++ foreach instead
  be/src/exec/olap_scan_node.cpp
  be/src/exec/schema_scan_node.cpp
  be/src/exec/schema_scanner/schema_helper.cpp
  be/src/http/http_request.cpp
  be/src/plugin/plugin_mgr.cpp
  be/src/runtime/buffered_block_mgr2.cc
  be/src/runtime/buffered_tuple_stream2.cc
  be/src/runtime/client_cache.cpp
  be/src/runtime/data_stream_recvr.cc
  be/src/runtime/disk_io_mgr.cc
  be/src/runtime/disk_io_mgr.h
  be/src/runtime/disk_io_mgr_reader_context.cc
  be/src/runtime/plan_fragment_executor.cpp
  be/src/runtime/sorted_run_merger.cc
  be/src/runtime/spill_sorter.cc
  be/src/runtime/tmp_file_mgr.cc
  be/src/runtime/types.cpp
  be/src/util/error_util.cc
  be/src/util/network_util.cpp
  be/src/util/runtime_profile.cpp
  be/src/util/thrift_rpc_helper.cpp
  be/test/exec/mysql_scan_node_test.cpp
  be/test/exec/schema_scan_node_test.cpp
  be/test/runtime/buffered_block_mgr2_test.cpp
Labels: approved, kind/refactor

#5617 [Bug] Fix alter table failed when none of new load jobs succeed on alter replica
  fe/fe-core/src/main/java/org/apache/doris/alter/AlterHandler.java
  fe/fe-core/src/main/java/org/apache/doris/alter/AlterJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/alter/RollupJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/MaterializedIndex.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapTableSink.java
  fe/fe-core/src/main/java/org/apache/doris/system/Backend.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/GlobalTransactionMgr.java
Labels: approved, area/schema-change, kind/bug

#5622 (#5621) using KeyMayExist instead of Get when visit rocksdb
  be/src/olap/olap_meta.cpp
  be/src/olap/olap_meta.h
  be/src/olap/rowset/rowset_meta_manager.cpp
Labels: approved

#5627 [Bug] Fix bug that tablets are not dropped when replacing tables
  fe/fe-core/src/main/java/org/apache/doris/alter/Alter.java
  fe/fe-core/src/test/java/org/apache/doris/alter/AlterTest.java
Labels: approved, area/catalog, kind/bug

#5641 [Metric] Add metrics for routine load
  fe/fe-core/src/main/java/org/apache/doris/common/util/TimeUtils.java
  fe/fe-core/src/main/java/org/apache/doris/metric/MetricRepo.java
Labels: approved, area/metrics

#5639 (#5638) stale rowset can't be access after clone finish
  be/src/olap/tablet.cpp
  be/src/olap/tablet_meta.h
Labels: approved, kind/bug

#5653 [Docs]Update README.md about the version of docker image
  README.md
Labels: approved, kind/documentation

#5652 [Docs] fix a typo
  docs/en/administrator-guide/alter-table/alter-table-bitmap-index.md
  docs/zh-CN/administrator-guide/alter-table/alter-table-bitmap-index.md
Labels: approved, kind/documentation

#5671 [Metric] Standardise histogram metric output for prometheus
  be/src/util/metrics.cpp
  be/src/util/metrics.h
  be/test/util/new_metrics_test.cpp
Labels: approved, area/metrics, kind/refactor

#5649 [Refactor] fix warning in gcc8+, update rapidjson
  be/src/agent/user_resource_listener.cpp
  be/src/exprs/anyval_util.cpp
  be/src/olap/memory/hash_index.cpp
  be/src/olap/memory/partial_row_batch.cpp
  be/src/olap/memory/partial_row_batch.h
  thirdparty/vars.sh
Labels: approved

#5619 [BE] Add scanner/etl thread pool queue size metric.
  be/src/runtime/exec_env.h
  be/src/runtime/exec_env_init.cpp
  be/src/util/doris_metrics.h
Labels: approved, area/metrics

#5607 [BE] Set RowBlock's parent memtracker as instance tracker.
  be/src/olap/rowset/beta_rowset_reader.cpp
Labels: approved, kind/enhancement

#5673 [Optimize] Make the max stmt length to be loaded in audit table can be defined by user
  fe_plugins/auditloader/src/main/assembly/plugin.conf
  fe_plugins/auditloader/src/main/java/org/apache/doris/plugin/audit/AuditLoaderPlugin.java
Labels: approved, area/config, area/plugin, good first issue

#5614 [Metrics] Add some large memtrackers' metric
  be/src/olap/schema_change.cpp
  be/src/olap/schema_change.h
  be/src/olap/storage_engine.cpp
  be/src/olap/tablet_manager.cpp
  be/src/olap/tablet_manager.h
  be/src/runtime/exec_env_init.cpp
  be/src/runtime/load_channel_mgr.cpp
  be/src/util/doris_metrics.h
  be/src/util/metrics.h
  be/test/exec/hash_table_test.cpp
  be/test/exprs/topn_function_test.cpp
  be/test/olap/tablet_mgr_test.cpp
Labels: approved, area/metrics

#5644 [Optimize] Remove deserialize check for meta serialization serialization to improve performance
  be/src/olap/rowset/rowset_meta_manager.cpp
  be/src/olap/tablet_meta.cpp
  be/src/olap/tablet_meta_manager.cpp
Labels: approved

#5648 [Metrics] Add metrics to monitor BE's agent task queue size
  be/src/agent/task_worker_pool.cpp
  be/src/agent/task_worker_pool.h
  be/src/util/doris_metrics.h
Labels: approved, area/metrics

#5650 [Refactor] Remove jprotobuf and use grpc client to connect brpc service
  be/src/runtime/buffer_control_block.cpp
  be/src/runtime/buffer_control_block.h
  be/src/service/internal_service.cpp
  be/src/service/internal_service.h
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/common/Status.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/CurrentQueryInfoProvider.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/DebugUtil.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/KafkaUtil.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ResultReceiver.java
  fe/fe-core/src/main/java/org/apache/doris/qe/RowBatch.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/Cache.java
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/CacheAnalyzer.java
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/CacheBeProxy.java
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/CacheCoordinator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/CacheProxy.java
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/PartitionCache.java
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/RowBatchBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/SqlCache.java
  fe/fe-core/src/main/java/org/apache/doris/rpc/BackendServiceClient.java
  fe/fe-core/src/main/java/org/apache/doris/rpc/BackendServiceProxy.java
  fe/fe-core/src/main/java/org/apache/doris/rpc/PBackendService.java
  fe/fe-core/src/main/java/org/apache/doris/rpc/PExecPlanFragmentRequest.java
  fe/fe-core/src/main/java/org/apache/doris/rpc/PFetchDataRequest.java
  fe/fe-core/src/main/java/org/apache/doris/rpc/PTriggerProfileReportRequest.java
  fe/fe-core/src/main/java/org/apache/doris/rpc/ThriftClientAttachmentHandler.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
  fe/fe-core/src/test/java/org/apache/doris/qe/ConnectProcessorTest.java
  fe/fe-core/src/test/java/org/apache/doris/qe/PartitionCacheTest.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/MockedBackend.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/MockedBackendFactory.java
  fe/pom.xml
  gensrc/proto/internal_service.proto
Labels: approved, kind/refactor

#5452 [Audit][Stream Load] Support audit function for stream load
  be/src/common/config.h
  be/src/http/action/stream_load.cpp
  be/src/http/action/stream_load.h
  be/src/olap/storage_engine.cpp
  be/src/olap/storage_engine.h
  be/src/runtime/CMakeLists.txt
  be/src/runtime/routine_load/routine_load_task_executor.cpp
  be/src/runtime/stream_load/stream_load_context.cpp
  be/src/runtime/stream_load/stream_load_context.h
  be/src/runtime/stream_load/stream_load_executor.cpp
  be/src/runtime/stream_load/stream_load_recorder.cpp
  be/src/runtime/stream_load/stream_load_recorder.h
  be/src/service/backend_service.cpp
  be/src/service/backend_service.h
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/common/AuditLog.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/journal/JournalEntity.java
  fe/fe-core/src/main/java/org/apache/doris/load/StreamLoadRecordMgr.java
  fe/fe-core/src/main/java/org/apache/doris/persist/EditLog.java
  fe/fe-core/src/main/java/org/apache/doris/persist/OperationType.java
  fe/fe-core/src/main/java/org/apache/doris/plugin/AuditEvent.java
  fe/fe-core/src/main/java/org/apache/doris/plugin/StreamLoadAuditEvent.java
  fe/fe-core/src/main/java/org/apache/doris/qe/AuditLogBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/system/Backend.java
  fe/fe-core/src/test/java/org/apache/doris/common/GenericPoolTest.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/MockedBackendFactory.java
  gensrc/thrift/BackendService.thrift
Labels: approved, kind/feature

#5659 [Enhancement] Add error msg when tablet not found for a drop tablet task
  be/src/agent/task_worker_pool.cpp
Labels: approved

#5667 Filter partitions by where header when generate stream load plan
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
  fe/fe-core/src/main/java/org/apache/doris/planner/StreamLoadPlanner.java
Labels: approved, area/load, kind/enhancement

#5692 [Bug] Fix stream load UT failed
  be/src/common/config.h
  be/src/http/action/stream_load.cpp
  be/src/olap/storage_engine.cpp
  be/src/olap/storage_engine.h
Labels: approved, area/test

#5375 [Feature] Flink Doris Connector (#5372)
  docs/en/extending-doris/flink-doris-connector.md
  docs/zh-CN/extending-doris/flink-doris-connector.md
  extension/flink-doris-connector/build.sh
  extension/flink-doris-connector/pom.xml
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/backend/BackendClient.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/ConfigurationOptions.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisConnectionOptions.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisExecutionOptions.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisOptions.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisReadOptions.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisStreamOptions.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/datastream/DorisSourceFunction.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/deserialization/DorisDeserializationSchema.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/deserialization/SimpleListDeserializationSchema.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/exception/ConnectedFailedException.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/exception/DorisException.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/exception/DorisInternalException.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/exception/IllegalArgumentException.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/exception/ShouldNeverHappenException.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/exception/StreamLoadException.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/rest/PartitionDefinition.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/rest/RestService.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/rest/SchemaUtils.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/rest/models/Backend.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/rest/models/BackendRow.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/rest/models/Field.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/rest/models/QueryPlan.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/rest/models/RespContent.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/rest/models/Schema.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/rest/models/Tablet.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/serialization/Routing.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/serialization/RowBatch.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicOutputFormat.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableFactory.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSink.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSource.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisRowDataInputFormat.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisStreamLoad.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisTableInputSplit.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/util/ErrorMessages.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/util/IOUtils.java
  extension/flink-doris-connector/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
  extension/flink-doris-connector/src/main/resources/log4j.properties
  extension/flink-doris-connector/src/main/scala/org/apache/doris/flink/datastream/ScalaValueReader.scala
  extension/flink-doris-connector/src/main/thrift/doris/DorisExternalService.thrift
  extension/flink-doris-connector/src/main/thrift/doris/Status.thrift
  extension/flink-doris-connector/src/main/thrift/doris/Types.thrift
  extension/flink-doris-connector/src/test/java/org/apache/doris/flink/DorisSinkExample.java
  extension/flink-doris-connector/src/test/java/org/apache/doris/flink/DorisSourceDataStream.java
  extension/flink-doris-connector/src/test/java/org/apache/doris/flink/DorisSourceExample.java
  extension/flink-doris-connector/src/test/java/org/apache/doris/flink/DorisSourceSinkExample.java
  extension/flink-doris-connector/src/test/java/org/apache/doris/flink/serialization/TestRowBatch.java
Labels: approved, area/spark-connector, good first issue

#5656 [Bug] Fix StackOverFlow bug after rewriting the column descs of load stmt
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowBrokerStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/FsBroker.java
  fe/fe-core/src/main/java/org/apache/doris/load/Load.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/planner/BrokerScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/StreamLoadScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/task/LoadTaskInfo.java
  fe/fe-core/src/main/java/org/apache/doris/task/StreamLoadTask.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/LoadStmtTest.java
Labels: approved, area/load, kind/bug

#5669 Fix #5668 Avoid waiting too long when rpc is slow.
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
Labels: approved, kind/enhancement

#5675 [Optimize] Remove expired txns in batch to avoid holding lock for too long
  be/src/olap/delta_writer.cpp
  be/src/runtime/mysql_result_writer.cpp
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/journal/JournalEntity.java
  fe/fe-core/src/main/java/org/apache/doris/load/Load.java
  fe/fe-core/src/main/java/org/apache/doris/load/LoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadManager.java
  fe/fe-core/src/main/java/org/apache/doris/persist/BatchRemoveTransactionsOperation.java
  fe/fe-core/src/main/java/org/apache/doris/persist/EditLog.java
  fe/fe-core/src/main/java/org/apache/doris/persist/OperationType.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/GlobalTransactionMgr.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/TransactionState.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/FakeEditLog.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/LoadManagerTest.java
  fe/fe-core/src/test/java/org/apache/doris/persist/BatchRemoveTransactionOperationTest.java
  fe/fe-core/src/test/java/org/apache/doris/transaction/DatabaseTransactionMgrTest.java
Labels: approved

#5683 [Optimize] Optimize the assign logic of compaction tasks to avoid starvation
  be/src/common/config.h
  be/src/olap/olap_server.cpp
  be/src/olap/storage_engine.h
  be/src/olap/tablet_manager.cpp
  be/src/olap/tablet_manager.h
Labels: approved, area/compact, kind/enhancement

#5665 [Metrics] Add metrics to show the distribution of tablets version count
  be/src/olap/tablet_manager.cpp
  be/src/util/doris_metrics.cpp
  be/src/util/doris_metrics.h
  be/src/util/metrics.cpp
  be/src/util/metrics.h
Labels: approved, area/metrics

#5686 Support read data with format of parquet from hdfs, using libhdfs3
  be/CMakeLists.txt
  be/src/exec/CMakeLists.txt
  be/src/exec/broker_scanner.cpp
  be/src/exec/hdfs_file_reader.cpp
  be/src/exec/hdfs_file_reader.h
  be/src/exec/parquet_scanner.cpp
  gensrc/thrift/PlanNodes.thrift
  thirdparty/build-thirdparty.sh
  thirdparty/download-thirdparty.sh
  thirdparty/patches/libhdfs3-master.patch
  thirdparty/vars.sh
Labels: approved, kind/feature

#5678 [Optimize] Sort trashed files by name and skip processing unexpired files
  be/src/olap/storage_engine.cpp
Labels: approved, area/optimizer

#5651 [Compaction] Support to switching cumulative compaction policy dynamically
  be/src/common/config.h
  be/src/common/configbase.cpp
  be/src/common/configbase.h
  be/src/http/default_path_handlers.cpp
  be/src/olap/compaction.cpp
  be/src/olap/cumulative_compaction_policy.cpp
  be/src/olap/cumulative_compaction_policy.h
  be/src/olap/olap_server.cpp
  be/src/olap/storage_engine.h
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
  be/src/olap/tablet_manager.cpp
  be/src/olap/tablet_manager.h
  be/test/olap/cumulative_compaction_policy_test.cpp
Labels: approved, area/compact

#5688 [Bug-fix] Ignore modified table log when table has been dropped
  fe/fe-core/src/main/java/org/apache/doris/alter/AlterHandler.java
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Database.java
  fe/fe-core/src/main/java/org/apache/doris/persist/ReplicaPersistInfo.java
Labels: approved, area/catalog, kind/bug

#5689 Data export function, add export to specify certain columns
  docs/zh-CN/administrator-guide/export-manual.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/ExportStmt.java
  fe/fe-core/src/main/java/org/apache/doris/load/ExportJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/ExportMgr.java
Labels: api-review, approved, area/backup, kind/enhancement

#5488 [Feature][Stream Load] Add "show stream load" to show stream load record
  docs/en/sql-reference/sql-statements/Data Manipulation/SHOW STREAM LOAD.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/SHOW STREAM LOAD.md
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowStreamLoadStmt.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/load/StreamLoadRecord.java
  fe/fe-core/src/main/java/org/apache/doris/load/StreamLoadRecordMgr.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/main/jflex/sql_scanner.flex
Labels: approved, kind/feature

#5721 [UT] Fix ut failed for CreateTableTest
  fe/fe-core/src/test/java/org/apache/doris/utframe/UtFrameUtils.java
Labels: approved, area/test

#5731 [Apache] Change download link to archive page
  docs/en/community/release-process.md
  docs/en/downloads/downloads.md
  docs/zh-CN/community/release-process.md
  docs/zh-CN/downloads/downloads.md
Labels: release-note-action-required

#5734 Fix double slashes when join paths
  fe/fe-core/src/main/java/org/apache/doris/backup/Repository.java
Labels: area/backup, kind/bug

#5620 [Bug] The operator on single Sql has affected the session varaiables
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/VariableMgr.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/SelectStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/DorisAssert.java
Labels: approved, good first issue

#5693 [Config]Add uri param to demonstrate tablet meta content of byte type for debug
  be/src/http/action/meta_action.cpp
  be/src/olap/olap_define.h
Labels: api-review, approved

#5710 [Bugfix][Compaction API] Fix the incorrect compaction type got success response
  be/src/http/action/compaction_action.cpp
Labels: approved, area/compact

#5713 [Bug] Fix dead lock in olap scan node and refactor some code in FE profile
  be/src/exec/olap_scan_node.cpp
  fe/fe-core/src/main/java/org/apache/doris/common/util/RuntimeProfile.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
Labels: approved

#5723 [Doc] Fix spelling mistake in alter table doc
  docs/en/sql-reference/sql-statements/Data Definition/ALTER TABLE.md
Labels: approved, kind/documentation

#5727 [Bug][Cache] Fix cache bug
  be/src/runtime/cache/result_cache.cpp
Labels: approved, area/sql/cache

#5725 [Bug] Fix cancel load path variable LABEL_KEY (#5724)
  docs/en/administrator-guide/http-actions/cancel-label.md
  docs/zh-CN/administrator-guide/http-actions/cancel-label.md
  fe/fe-core/src/main/java/org/apache/doris/http/rest/CancelStreamLoad.java
Labels: api-review, approved, area/load, kind/api-change

#5730 [Bugfix] Fix BE metrics http API dead lock bug
  be/src/agent/agent_server.cpp
  be/src/agent/task_worker_pool.cpp
  be/src/agent/task_worker_pool.h
  be/src/olap/storage_engine.cpp
  be/src/olap/tablet_manager.cpp
Labels: approved, area/compact, kind/bug
