Repository apache/doris, pull requests merged in 2022-01, with the labels that each got.

#7403 [feature] sql-block-rule: add partition_num, tablet_num, cardinality in SqlBlockRule to block big/slow sql
  docs/en/administrator-guide/block-rule/sql-block.md
  docs/zh-CN/administrator-guide/block-rule/sql-block.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/AlterSqlBlockRuleStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateSqlBlockRuleStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowSqlBlockRuleStmt.java
  fe/fe-core/src/main/java/org/apache/doris/blockrule/SqlBlockRule.java
  fe/fe-core/src/main/java/org/apache/doris/blockrule/SqlBlockRuleMgr.java
  fe/fe-core/src/main/java/org/apache/doris/common/ErrorCode.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/SqlBlockUtil.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/AlterSqlBlockRuleStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/CreateSqlBlockRuleStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/blockrule/SqlBlockRuleMgrTest.java
  fe/fe-core/src/test/java/org/apache/doris/qe/ShowExecutorTest.java
Labels: kind/feature, approved, reviewed

#7423 [improvement] add a config repair_slow_replica
  docs/en/administrator-guide/config/fe_config.md
  docs/zh-CN/administrator-guide/config/fe_config.md
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Replica.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Tablet.java
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletScheduler.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/test/java/org/apache/doris/clone/TabletReplicaTooSlowTest.java
Labels: approved, reviewed

#7532 [Improvement] Default cooldown time for storage medium SSD
  fe/fe-core/src/main/java/org/apache/doris/catalog/DataProperty.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/DataPropertyTest.java
Labels: approved, reviewed

#7240 [Load] Transaction for load job with no data for all partitions should be considered as normal and should not be aborted
  be/src/agent/task_worker_pool.cpp
  be/src/runtime/stream_load/stream_load_executor.cpp
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/KafkaRoutineLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/update/UpdateStmtExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/TransactionCommitFailedException.java
  fe/fe-core/src/test/java/org/apache/doris/load/update/UpdateStmtExecutorTest.java
Labels: approved, reviewed

#7548 [refactor] update parent pom version and optimize build scripts
  .github/workflows/build-extension.yml
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/community/how-to-deploy-to-maven.md
  docs/en/extending-doris/flink-doris-connector.md
  docs/en/extending-doris/spark-doris-connector.md
  docs/zh-CN/community/how-to-deploy-to-maven.md
  docs/zh-CN/extending-doris/flink-doris-connector.md
  docs/zh-CN/extending-doris/spark-doris-connector.md
  extension/flink-doris-connector/build.sh
  extension/flink-doris-connector/pom.xml
  extension/spark-doris-connector/build.sh
  extension/spark-doris-connector/pom.xml
  extension/spark-doris-connector/pom_3.0.xml
  fe/fe-common/pom.xml
  fe/fe-core/pom.xml
  fe/pom.xml
  fe/spark-dpp/pom.xml
  fe_plugins/auditdemo/pom.xml
  fe_plugins/auditloader/pom.xml
  fe_plugins/pom.xml
  fs_brokers/apache_hdfs_broker/pom.xml
  samples/connect/java/client/pom.xml
Labels: approved, reviewed

#7563 [fix](tablet-scheduler) Fix decommission backend bug
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletScheduler.java
Labels: approved, reviewed

#7567 [vectorized][refactor](common) eliminate class COW dependence on boost
  be/src/vec/common/cow.h
  be/src/vec/exec/vanalytic_eval_node.cpp
  be/src/vec/functions/function_cast.h
Labels: approved, reviewed

#7547 [Optimize] Support merge in runtime filter(#7546)
  be/src/exec/hash_join_node.cpp
  be/src/exec/olap_scan_node.cpp
  be/src/exprs/runtime_filter.cpp
  be/src/exprs/runtime_filter.h
  be/src/exprs/runtime_filter_slots.h
  be/src/runtime/runtime_filter_mgr.cpp
  be/src/runtime/runtime_filter_mgr.h
  be/test/exprs/runtime_filter_test.cpp
  docs/en/administrator-guide/runtime-filter.md
  docs/zh-CN/administrator-guide/runtime-filter.md
  fe/fe-core/src/main/java/org/apache/doris/planner/RuntimeFilter.java
  fe/fe-core/src/main/java/org/apache/doris/planner/RuntimeFilterGenerator.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
  gensrc/proto/internal_service.proto
Labels: kind/feature, kind/api-change, approved, area/runtime-filter, reviewed

#7535 [Website] Make web page base proc dir and varibles orderly
  fe/fe-core/src/main/java/org/apache/doris/common/proc/BaseProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/http/action/VariableAction.java
Labels: kind/enhancement, approved, area/be/frontpage, reviewed

#7602 [improvement](git) add vscode devcontainer config into git ignore
  .gitignore
Labels: approved, reviewed

#7606 [fix](syntax) Add STRUCT to keywords
  fe/fe-core/src/main/cup/sql_parser.cup
Labels: approved, reviewed

#7607 [fix] Fix audit load may stopped when throw unexcepted exceptions
  fe_plugins/auditloader/src/main/java/org/apache/doris/plugin/audit/AuditLoaderPlugin.java
Labels: kind/bug, approved, area/plugin, reviewed

#7609 [MINOR] remove RewriteClasses unused LOG reference
  fe/fe-core/src/main/java/org/apache/doris/rewrite/RewriteAliasFunctionRule.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/RewriteEncryptKeyRule.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/RewriteLikePredicateRule.java
Labels: approved, reviewed

#7616 [docs] add deploy spark/flink connectors to maven release repo docs
  docs/.vuepress/public/images/close_staging.png
  docs/.vuepress/public/images/release-stage.png
  docs/.vuepress/public/images/staging_repo.png
  docs/en/community/how-to-deploy-to-maven.md
  docs/zh-CN/community/how-to-deploy-to-maven.md
  extension/flink-doris-connector/pom.xml
  extension/spark-doris-connector/pom.xml
  fe/pom.xml
  fe_plugins/pom.xml
  fs_brokers/apache_hdfs_broker/pom.xml
Labels: kind/documentation, approved, reviewed

#7600 [vectorized] [block] add new method get_data_type to avoid unnecessary copy by the method get_data_type
  be/src/vec/core/block.cpp
  be/src/vec/core/block.h
  be/src/vec/olap/block_reader.cpp
Labels: approved, Vectorization, reviewed

#7557 [feature-wip](vectorized) Support bloom filter predicate on vectorized engine storage layer
  be/src/olap/bloom_filter_predicate.h
  be/test/olap/bloom_filter_column_predicate_test.cpp
  be/test/olap/null_predicate_test.cpp
Labels: kind/enhancement, area/sql/execution, vectorization

#7568 [Optimize][Extension] optimize extension datax doriswriter
  docs/en/extending-doris/datax.md
  docs/zh-CN/extending-doris/datax.md
  extension/DataX/doriswriter/doc/doriswriter.md
  extension/DataX/doriswriter/src/main/java/com/alibaba/datax/plugin/writer/doriswriter/DorisCodec.java
  extension/DataX/doriswriter/src/main/java/com/alibaba/datax/plugin/writer/doriswriter/DorisCsvCodec.java
  extension/DataX/doriswriter/src/main/java/com/alibaba/datax/plugin/writer/doriswriter/DorisFlushBatch.java
  extension/DataX/doriswriter/src/main/java/com/alibaba/datax/plugin/writer/doriswriter/DorisJsonCodec.java
  extension/DataX/doriswriter/src/main/java/com/alibaba/datax/plugin/writer/doriswriter/DorisWriter.java
  extension/DataX/doriswriter/src/main/java/com/alibaba/datax/plugin/writer/doriswriter/DorisWriterEmitter.java
  extension/DataX/doriswriter/src/main/java/com/alibaba/datax/plugin/writer/doriswriter/Key.java
Labels: kind/enhancement, approved, area/datax, reviewed

#7514 Spark connector Stream load http exception handling
  extension/spark-doris-connector/src/main/java/org/apache/doris/spark/DorisStreamLoad.java
Labels: area/spark-connector, approved, reviewed

#7605 [fix](error-hub) use lock to protect the creation of error hub
  be/src/runtime/runtime_state.cpp
  be/src/runtime/runtime_state.h
Labels: kind/bug, approved, reviewed

#7655 Spark connector deletes useless maven dependencies and some code variable definition issues
  extension/spark-doris-connector/src/main/java/org/apache/doris/spark/backend/BackendClient.java
  extension/spark-doris-connector/src/main/java/org/apache/doris/spark/cfg/Settings.java
  extension/spark-doris-connector/src/main/java/org/apache/doris/spark/rest/RestService.java
  extension/spark-doris-connector/src/main/java/org/apache/doris/spark/serialization/Routing.java
  extension/spark-doris-connector/src/main/java/org/apache/doris/spark/util/IOUtils.java
  extension/spark-doris-connector/src/test/java/org/apache/doris/spark/rest/TestRestService.java
  extension/spark-doris-connector/src/test/java/org/apache/doris/spark/serialization/TestRowBatch.java
Labels: area/spark-connector, approved, reviewed

#7664 Support general hints in select statement
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectList.java
  fe/fe-core/src/main/jflex/sql_scanner.flex
  fe/fe-core/src/test/java/org/apache/doris/analysis/SelectStmtTest.java
Labels: approved, reviewed

#7683 [Website Docs] fix CaseList component bug
  docs/.vuepress/components/CaseList.vue
Labels: approved, reviewed

#7630 [improvement](routine-load) Make routine load work with old kafka version
  be/src/common/config.h
  be/src/runtime/routine_load/data_consumer.cpp
  docs/en/administrator-guide/config/be_config.md
  docs/en/administrator-guide/load-data/routine-load-manual.md
  docs/zh-CN/administrator-guide/config/be_config.md
  docs/zh-CN/administrator-guide/load-data/routine-load-manual.md
Labels: kind/enhancement, approved, area/routine load, reviewed

#7670 [Feature] Support String in vec exc engine
  be/src/olap/olap_define.h
  be/src/olap/row_block2.cpp
  be/src/olap/row_block2.h
  be/src/olap/rowset/beta_rowset_reader.cpp
  be/src/vec/exec/vunion_node.cpp
  fe/fe-core/src/main/java/org/apache/doris/rewrite/FoldConstantsRule.java
Labels: vectorization

#7642 [vectorized] (olap) optimize BlockReader's performance
  be/src/vec/olap/block_reader.cpp
  be/src/vec/olap/block_reader.h
Labels: approved, reviewed

#7688 [Vectorized][Bug] fix 'negative' function ut run fail && fix testIsBucketShuffleJoin run fail && fix some compile fail
  be/src/util/brpc_stub_cache.h
  be/test/vec/function/function_hash_test.cpp
  be/test/vec/function/function_math_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/planner/HashJoinNode.java
  fe/fe-core/src/test/java/org/apache/doris/qe/CoordinatorTest.java
Labels: vectorization

#7691 [fix](s3) Fix bug that can not visit aliyun oss with aws s3 sdk
  fe/fe-common/pom.xml
  fe/fe-core/pom.xml
  fe/pom.xml
Labels: area/dependency, approved, area/backup, reviewed

#7638 [docs] Polish PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: area/community, kind/documentation, approved

#7531 Throw an exception to spark when the data push fails and there are too many retries
  extension/spark-doris-connector/src/main/java/org/apache/doris/spark/DorisStreamLoad.java
  extension/spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/DorisSourceProvider.scala
  extension/spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/DorisStreamLoadSink.scala
Labels: good first issue, area/spark-connector, approved, reviewed

#7543 [improvement](executor) Optimize lock of client cache
  be/src/runtime/client_cache.cpp
  be/src/runtime/client_cache.h
Labels: kind/enhancement, approved, reviewed

#7620 [docs] Improve instructions for the configuration of BE.
  docs/en/administrator-guide/config/be_config.md
  docs/en/installing/install-deploy.md
  docs/zh-CN/administrator-guide/config/be_config.md
  docs/zh-CN/installing/install-deploy.md
Labels: good first issue, kind/documentation, reviewed

#7689 [Docs] update the document format
  docs/zh-CN/administrator-guide/export-manual.md
Labels: kind/documentation, approved, reviewed

#7694 [docs](hive)(function) fix some doc error
  docs/en/extending-doris/hive-of-doris.md
  docs/en/sql-reference/sql-statements/Data Definition/create-function.md
  docs/zh-CN/extending-doris/hive-of-doris.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/create-function.md
Labels: approved, reviewed

#7696 [fix](website) Add trademarks on official website
  README.md
  docs/.vuepress/theme/components/Footer.vue
Labels: area/website, approved, reviewed

#7675 Database ODBC version correspondence
  docs/en/extending-doris/odbc-of-doris.md
  docs/zh-CN/extending-doris/odbc-of-doris.md
Labels: kind/documentation, approved, reviewed

#7707 [fix](show) fix ConcurrentModificationException for show proc /current_queries'
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
Labels: kind/bug, approved, reviewed

#7721 [fix](lateral-view) Fix some bugs about lateral view
  .github/PULL_REQUEST_TEMPLATE.md
  be/src/exec/json_scanner.cpp
  be/src/exec/table_function_node.cpp
  be/src/exprs/json_functions.cpp
  be/src/exprs/json_functions.h
  be/src/exprs/table_function/explode_bitmap.cpp
  be/test/exprs/json_function_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/analysis/LateralViewRef.java
Labels: kind/bug, approved, reviewed, area/lateral-view

#7731 [docs] update seatunnel.md
  docs/zh-CN/extending-doris/seatunnel.md
Labels: kind/documentation, approved, reviewed

#7663 [chore] Add label auto
  .github/workflows/auto-label-title.yml
  .gitmodules
Labels: approved, reviewed

#6830 [fix][cpu-resource] Allow set cpu_resource_limit to -1
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletScheduler.java
  fe/fe-core/src/main/java/org/apache/doris/common/ErrorCode.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/MysqlProto.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/UserProperty.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/UserPropertyTest.java
Labels: approved, reviewed

#7526 [fix](session-variable) fix bug that checkpoint may overwrite the global variables
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/journal/JournalEntity.java
  fe/fe-core/src/main/java/org/apache/doris/master/Checkpoint.java
  fe/fe-core/src/main/java/org/apache/doris/persist/EditLog.java
  fe/fe-core/src/main/java/org/apache/doris/qe/VariableMgr.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/GlobalTransactionMgr.java
  fe/fe-core/src/test/java/org/apache/doris/qe/VariableMgrTest.java
Labels: kind/fix

#7654 Multiple FE WEB UI login issues
  docs/en/faq/faq.md
  docs/zh-CN/faq/faq.md
Labels: kind/docs, approved, reviewed

#7702 [fix](routine-load) fix string type may core dump when using tcmalloc
  be/CMakeLists.txt
  be/src/common/daemon.cpp
  be/src/exec/s3_reader.cpp
  be/src/exec/s3_writer.cpp
  be/src/olap/wrapper_field.h
  be/src/runtime/routine_load/data_consumer.cpp
Labels: area/routine load

#7732 replace Chinese comments with English comments
  fe/fe-core/src/main/java/org/apache/doris/catalog/AccessPrivilege.java
Labels: approved, reviewed

#7613 [Vectorization] support SegmentIterator vectorization
  be/src/olap/column_predicate.h
  be/src/olap/comparison_predicate.cpp
  be/src/olap/in_list_predicate.cpp
  be/src/olap/in_list_predicate.h
  be/src/olap/rowset/segment_v2/binary_dict_page.cpp
  be/src/olap/rowset/segment_v2/binary_plain_page.h
  be/src/olap/rowset/segment_v2/bitshuffle_page.h
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/olap/rowset/segment_v2/segment_iterator.h
  be/src/olap/schema.cpp
  be/src/olap/schema.h
  be/src/vec/columns/column.h
  be/src/vec/columns/column_complex.h
  be/src/vec/columns/column_nullable.cpp
  be/src/vec/columns/column_nullable.h
  be/src/vec/columns/column_vector.h
  be/src/vec/columns/predicate_column.h
Labels: area/storage, area/vectorization

#7725 Flink / Spark connector compilation problem
  extension/flink-doris-connector/build.sh
  extension/flink-doris-connector/pom.xml
  extension/spark-doris-connector/build.sh
  extension/spark-doris-connector/pom.xml
Labels: area/spark-connector, approved, area/flink-connector, reviewed

#7759 [docs] add doc for community feedback and fix CI
  .github/workflows/auto-label-title.yml
  docs/en/community/feedback.md
  docs/zh-CN/community/feedback.md
Labels: approved, reviewed

#7523 [LOAD] fix show load with the same column name in Where Clause
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowLoadStmt.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ShowLoadStmtTest.java
Labels: kind/fix, area/load, approved, reviewed

#7673 [feature](mysql-compatibility) add `WEEKDAY` function
  be/src/exprs/timestamp_functions.cpp
  be/src/exprs/timestamp_functions.h
  be/test/exprs/timestamp_functions_test.cpp
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/sql-reference/sql-functions/date-time-functions/dayofweek.md
  docs/en/sql-reference/sql-functions/date-time-functions/weekday.md
  docs/zh-CN/sql-reference/sql-functions/date-time-functions/dayofweek.md
  docs/zh-CN/sql-reference/sql-functions/date-time-functions/weekday.md
  gensrc/script/doris_builtins_functions.py
Labels: approved, area/sql/function, reviewed

#7705 [improvement][manager] Modify the agent startup service and build cluster logic
  manager/README.md
  manager/dm-agent/src/main/java/org/apache/doris/manager/agent/command/CommandResultService.java
  manager/dm-agent/src/main/java/org/apache/doris/manager/agent/common/AgentConstants.java
  manager/dm-agent/src/main/java/org/apache/doris/manager/agent/service/BeService.java
  manager/dm-agent/src/main/java/org/apache/doris/manager/agent/service/BrokerService.java
  manager/dm-agent/src/main/java/org/apache/doris/manager/agent/service/FeService.java
  manager/dm-agent/src/main/java/org/apache/doris/manager/agent/service/Service.java
  manager/dm-server/src/main/java/org/apache/doris/stack/constants/Constants.java
  manager/dm-server/src/main/java/org/apache/doris/stack/controller/AgentController.java
  manager/dm-server/src/main/java/org/apache/doris/stack/dao/TaskInstanceRepository.java
  manager/dm-server/src/main/java/org/apache/doris/stack/model/request/BuildClusterReq.java
  manager/dm-server/src/main/java/org/apache/doris/stack/service/AgentProcess.java
  manager/dm-server/src/main/java/org/apache/doris/stack/service/impl/AgentProcessImpl.java
  manager/dm-server/src/main/java/org/apache/doris/stack/service/impl/ProcessTaskImpl.java
  manager/dm-server/src/main/java/org/apache/doris/stack/util/JdbcUtil.java
  manager/doc/Doris Manager Server 接口文档.md
  manager/manager-bin/agent/bin/process_exist.sh
Labels: approved, reviewed

#7748 [improvement] create/drop index support if [not] exist
  docs/en/sql-reference/sql-statements/Data Definition/ALTER TABLE.md
  docs/en/sql-reference/sql-statements/Data Definition/CREATE INDEX.md
  docs/en/sql-reference/sql-statements/Data Definition/DROP INDEX.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/ALTER TABLE.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/CREATE INDEX.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/DROP INDEX.md
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/DropIndexClause.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/IndexDef.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/CreateIndexClauseTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/DropIndexClauseTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/IndexDefTest.java
Labels: approved, reviewed

#7754 [improvement](routine-load) Reduce the probability that the routine load task rpc timeout
  be/src/common/config.h
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
  be/src/olap/delta_writer.cpp
  be/src/olap/delta_writer.h
  be/src/olap/memtable_flush_executor.cpp
  be/src/olap/memtable_flush_executor.h
  be/src/runtime/load_channel.cpp
  be/src/runtime/load_channel.h
  be/src/runtime/load_channel_mgr.cpp
  be/src/runtime/routine_load/routine_load_task_executor.cpp
  be/src/runtime/tablets_channel.cpp
  be/src/runtime/tablets_channel.h
  docs/en/administrator-guide/config/be_config.md
  docs/zh-CN/administrator-guide/config/be_config.md
  gensrc/proto/internal_service.proto
Labels: approved, reviewed

#7761 [improvement](be) remove duplicate if that will never be used
  be/src/exec/csv_scan_node.cpp
Labels: approved, reviewed

#7766 fix NPE in SysVariableDesc::equal
  fe/fe-core/src/main/java/org/apache/doris/analysis/SysVariableDesc.java
Labels: approved, reviewed

#7768 [Bug] Fe failed to start due to the port already in use exception in UT.
  fe/fe-core/src/test/java/org/apache/doris/utframe/UtFrameUtils.java
Labels: approved, reviewed

#7769 [docs] fix some typos in documents
  docs/en/administrator-guide/operation/metadata-operation.md
  docs/en/sql-reference/sql-statements/Administration/SHOW PLUGINS.md
  docs/en/sql-reference/sql-statements/Data Definition/CREATE REPOSITORY.md
  docs/en/sql-reference/sql-statements/Data Definition/DROP REPOSITORY.md
  docs/en/sql-reference/sql-statements/Data Definition/SHOW RESOURCES.md
  docs/en/sql-reference/sql-statements/Data Manipulation/lateral-view.md
  docs/zh-CN/administrator-guide/operation/metadata-operation.md
  docs/zh-CN/sql-reference/sql-statements/Administration/SHOW PLUGINS.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/CREATE REPOSITORY.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/CREATE RESOURCE.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/DROP REPOSITORY.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/DROP RESOURCE.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/lateral-view.md
Labels: approved, reviewed

#7601 [vectorized][feature](planner)(executor)support grouping sets,rollup,cube(#7599)
  be/src/exec/exec_node.cpp
  be/src/exec/repeat_node.h
  be/src/vec/CMakeLists.txt
  be/src/vec/exec/vrepeat_node.cpp
  be/src/vec/exec/vrepeat_node.h
  be/src/vec/functions/function_grouping.cpp
  be/src/vec/functions/function_grouping.h
  be/src/vec/functions/simple_function_factory.h
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
  gensrc/script/doris_builtins_functions.py
Labels: kind/feature, area/vectorization

#7780 [Vectorized](compile) Fix compile error and warning
  be/src/vec/columns/column.h
  be/src/vec/functions/function.h
  be/src/vec/functions/function_grouping.cpp
Labels: approved, reviewed

#7499 [Broker] Add some properties that can be set in the broker conf file
  fs_brokers/apache_hdfs_broker/conf/apache_hdfs_broker.conf
Labels: approved, reviewed

#7656 [improvement](colocation) Add a new config to delay the relocation of colocation group
  docs/en/administrator-guide/config/fe_config.md
  docs/en/administrator-guide/operation/tablet-repair-and-balance.md
  docs/zh-CN/administrator-guide/config/fe_config.md
  docs/zh-CN/administrator-guide/operation/tablet-repair-and-balance.md
  fe/fe-core/src/main/java/org/apache/doris/catalog/Tablet.java
  fe/fe-core/src/main/java/org/apache/doris/clone/ColocateTableCheckerAndBalancer.java
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletChecker.java
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletScheduler.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/system/Backend.java
  fe/fe-core/src/main/java/org/apache/doris/system/SystemInfoService.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/BackendTest.java
  fe/fe-core/src/test/java/org/apache/doris/clone/ColocateTableCheckerAndBalancerTest.java
  fe/fe-core/src/test/java/org/apache/doris/clone/TabletRepairAndBalanceTest.java
Labels: area/colocated, approved, reviewed

#7772 [fix](lateral-view) Fix some lateral view bugs
  be/src/exec/table_function_node.cpp
  be/src/exec/table_function_node.h
  be/src/runtime/plan_fragment_executor.cpp
  fe/fe-core/src/main/java/org/apache/doris/planner/TableFunctionNode.java
Labels: kind/fix, approved, reviewed, area/lateral-view

#6319 [Enhance][Load] Cancel the load job ASAP when encounter unqualified data
  be/src/exec/CMakeLists.txt
  be/src/exec/base_scanner.cpp
  be/src/exec/base_scanner.h
  be/src/exec/broker_scanner.cpp
  be/src/exec/broker_scanner.h
  be/src/exec/csv_scan_node.cpp
  be/src/exec/csv_scan_node.h
  be/src/exec/csv_scanner.h
  be/src/exec/data_sink.cpp
  be/src/exec/exec_node.cpp
  be/src/exec/json_scanner.cpp
  be/src/exec/json_scanner.h
  be/src/exec/olap_rewrite_node.cpp
  be/src/exec/olap_rewrite_node.h
  be/src/exec/orc_scanner.cpp
  be/src/exec/orc_scanner.h
  be/src/exec/parquet_scanner.cpp
  be/src/exec/parquet_scanner.h
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
  be/src/http/action/download_action.h
  be/src/http/action/stream_load.cpp
  be/src/runtime/CMakeLists.txt
  be/src/runtime/data_spliter.cpp
  be/src/runtime/data_spliter.h
  be/src/runtime/etl_job_mgr.cpp
  be/src/runtime/plan_fragment_executor.cpp
  be/src/runtime/runtime_state.cpp
  be/src/runtime/runtime_state.h
  be/src/vec/CMakeLists.txt
  be/src/vec/sink/vdata_stream_sender.cpp
  be/src/vec/sink/vtablet_sink.cpp
  be/test/exec/tablet_sink_test.cpp
  be/test/vec/runtime/vdata_stream_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/analysis/UserIdentity.java
  fe/fe-core/src/main/java/org/apache/doris/load/ExportJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BrokerLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BrokerLoadingTaskAttachment.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BulkLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadLoadingTask.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/KafkaRoutineLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/update/UpdateStmtExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/planner/DataPartition.java
  fe/fe-core/src/main/java/org/apache/doris/planner/DataSplitSink.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapTableSink.java
  fe/fe-core/src/main/java/org/apache/doris/planner/StreamLoadPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/task/LoadTaskInfo.java
  fe/fe-core/src/main/java/org/apache/doris/task/StreamLoadTask.java
  fe/fe-core/src/test/java/org/apache/doris/alter/MaterializedViewHandlerTest.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/RecoverTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/BrokerLoadJobTest.java
  gensrc/thrift/DataSinks.thrift
  gensrc/thrift/FrontendService.thrift
  gensrc/thrift/PaloInternalService.thrift
  gensrc/thrift/PlanNodes.thrift
Labels: kind/improvement, area/load, approved, reviewed

#7773 [fix][chore](thrift) Fix warning when generate cpp code by thrift IDL file and use strict mode
  gensrc/thrift/FrontendService.thrift
  gensrc/thrift/Makefile
  gensrc/thrift/PaloExternalDataSourceService.thrift
  gensrc/thrift/PlanNodes.thrift
Labels: approved, reviewed

#7788 [fix](bitmap-index) Fix bug that bitmap index may return wrong result.
  be/src/olap/rowset/segment_v2/index_page.cpp
  be/src/olap/rowset/segment_v2/index_page.h
  be/src/olap/rowset/segment_v2/indexed_column_reader.cpp
  be/src/olap/rowset/segment_v2/ordinal_page_index.h
Labels: kind/fix, approved, reviewed, area/bitmap-index

#7674 [improvement](load) Improve load fault tolerance
  be/src/exec/broker_scanner.cpp
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
  be/src/olap/delta_writer.cpp
  be/src/olap/delta_writer.h
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/load_channel.cpp
  be/src/runtime/load_channel.h
  be/src/runtime/load_channel_mgr.cpp
  be/src/runtime/load_channel_mgr.h
  be/src/runtime/runtime_state.h
  be/src/runtime/tablets_channel.cpp
  be/src/runtime/tablets_channel.h
  be/src/service/internal_service.cpp
  be/src/vec/sink/vtablet_sink.cpp
  be/test/olap/delta_writer_test.cpp
  be/test/runtime/load_channel_mgr_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/common/proc/LoadProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/ldap/LdapAuthenticate.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BrokerLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BrokerLoadingTaskAttachment.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadLoadingTask.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/KafkaRoutineLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/MysqlProto.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContext.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/ErrorTabletInfo.java
  gensrc/proto/internal_service.proto
  gensrc/script/gen_build_version.sh
  gensrc/thrift/FrontendService.thrift
  gensrc/thrift/Types.thrift
Labels: area/load, approved, reviewed

#7787 [Doc]Documentation corrections
  docs/en/extending-doris/logstash.md
  docs/en/installing/install-deploy.md
  docs/zh-CN/extending-doris/logstash.md
  docs/zh-CN/installing/install-deploy.md
Labels: kind/docs, approved, reviewed

#7521 [Feature] Support triggering compaction for a specific partition manually
  be/src/agent/agent_server.cpp
  be/src/agent/agent_server.h
  be/src/agent/task_worker_pool.cpp
  be/src/agent/task_worker_pool.h
  be/src/olap/olap_server.cpp
  be/src/olap/storage_engine.h
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/sql-reference/sql-statements/Administration/ADMIN COMPACT.md
  docs/zh-CN/sql-reference/sql-statements/Administration/ADMIN COMPACT.md
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/AdminCompactTableStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/qe/DdlExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/task/AgentBatchTask.java
  fe/fe-core/src/main/java/org/apache/doris/task/CompactionTask.java
  fe/fe-core/src/main/jflex/sql_scanner.flex
  gensrc/thrift/AgentService.thrift
  gensrc/thrift/Types.thrift
Labels: kind/feature, approved, area/compact, reviewed

#7808 [fix](schema-change) Fix bug that schema change may return -102 error
  be/src/olap/collect_iterator.cpp
  be/src/olap/rowset/alpha_rowset_reader.h
  be/src/olap/rowset/alpha_rowset_writer.h
  be/src/olap/rowset/beta_rowset_reader.h
  be/src/olap/rowset/beta_rowset_writer.h
  be/src/olap/rowset/rowset_reader.h
  be/src/olap/rowset/rowset_writer.h
  be/src/olap/schema_change.cpp
  be/src/vec/olap/vcollect_iterator.cpp
  be/test/util/threadpool_test.cpp
  thirdparty/vars.sh
Labels: kind/fix, area/schema-change, approved, reviewed

#7712 Prolog of hermetic build with GCC 11 and Clang 13.
  CONTRIBUTING_CN.md
  README.md
  be/CMakeLists.txt
  be/src/agent/topic_subscriber.h
  be/src/exec/olap_utils.h
  be/src/exprs/runtime_filter.cpp
  be/src/exprs/runtime_filter.h
  be/src/exprs/table_function/explode_split.cpp
  be/src/glibc-compatibility/CMakeLists.txt
  be/src/glibc-compatibility/glibc-compat-2.32.h
  be/src/glibc-compatibility/glibc-compatibility.c
  be/src/glibc-compatibility/musl/eventfd.c
  be/src/glibc-compatibility/musl/getauxval.c
  be/src/glibc-compatibility/musl/getrandom.c
  be/src/glibc-compatibility/musl/sched_getcpu.c
  be/src/glibc-compatibility/musl/signgam.c
  be/src/gutil/strings/util.cc
  be/src/http/action/pprof_actions.cpp
  be/src/olap/column_vector.cpp
  be/src/olap/column_vector.h
  be/src/olap/rowset/segment_v2/page_handle.h
  be/src/olap/types.h
  be/src/runtime/dpp_sink_internal.cpp
  be/src/runtime/large_int_value.h
  be/src/runtime/raw_value_ir.cpp
  be/src/udf/udf.cpp
  be/src/util/bfd_parser.cpp
  be/src/util/bitmap_value.h
  be/src/util/cidr.cpp
  be/src/util/pprof_utils.cpp
  be/src/util/simd/vstring_function.h
  be/src/vec/common/exception.h
  be/src/vec/functions/function_grouping.h
  be/test/olap/rowset/segment_v2/frame_of_reference_page_test.cpp
  be/test/plugin/plugin_test/source/test.zip
  be/test/plugin/plugin_test/source/test.zip.md5
  build.sh
  contrib/udf/CMakeLists.txt
  docs/en/installing/compilation.md
  env.sh
  gensrc/script/doris_builtins_functions.py
  gensrc/script/gen_builtins_functions.py
  gensrc/script/gen_functions.py
  gensrc/script/gen_vector_functions.py
  run-fe-ut.sh
  thirdparty/build-thirdparty.sh
  thirdparty/download-thirdparty.sh
  thirdparty/patches/googletest-release-1.11.0.patch
  thirdparty/patches/libevent.patch
  thirdparty/patches/libhdfs3-master.patch
  thirdparty/patches/mysql-server-mysql-5.7.18.patch
  thirdparty/patches/rocksdb-5.14.2.patch
  thirdparty/vars.sh
Labels: kind/improvement, kind/chore, approved, reviewed

#7829 [chore] Improve the ldb toolchain compilation documentation
  be/CMakeLists.txt
  build.sh
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/installing/compilation-with-ldb-toolchain.md
  docs/zh-CN/installing/compilation-with-ldb-toolchain.md
  gensrc/script/gen_builtins_functions.py
  gensrc/script/gen_functions.py
  gensrc/script/gen_vector_functions.py
  thirdparty/build-thirdparty.sh
  thirdparty/vars.sh
Labels: kind/chore, approved, reviewed

#7801 [Bug] fix vec round function
  be/src/vec/functions/math.cpp
Labels: approved, reviewed

#7803 [Bug](Vectorized) fix get fold const value fail at datetime type
  be/src/vec/functions/function_cast.h
Labels: approved, reviewed

#7805 [Vectorization][Enhancement]optimize dict read
  be/src/olap/rowset/segment_v2/binary_dict_page.cpp
  be/src/olap/rowset/segment_v2/binary_dict_page.h
  be/src/olap/rowset/segment_v2/column_reader.cpp
  be/src/olap/rowset/segment_v2/column_reader.h
  be/test/olap/rowset/segment_v2/binary_dict_page_test.cpp
  be/test/tools/benchmark_tool.cpp
Labels: approved, area/vectorization, reviewed

#7811 Use ccache to speed recompiling test code up.
  run-be-ut.sh
Labels: approved, reviewed

#7813 [fix](export) fix export failed when table has hidden columns
  fe/fe-core/src/main/java/org/apache/doris/load/ExportJob.java
Labels: kind/fix, approved, area/export, reviewed

#7816 [docs](install-deploy) fix misplaced whitespace(#7814)
  docs/en/installing/install-deploy.md
Labels: approved, reviewed

#7795 [Improvement](Vectorized) optimize SegmentIterator predication evaluate
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/olap/rowset/segment_v2/segment_iterator.h
  be/src/util/simd/bits.h
  be/src/vec/columns/column_decimal.cpp
  be/src/vec/columns/column_vector.cpp
  be/src/vec/columns/columns_common.cpp
  be/src/vec/columns/columns_common.h
Labels: area/storage, approved, area/vectorization, reviewed

#7457 [Feature][flink-connector] support flink delete option
  docs/en/administrator-guide/http-actions/fe/table-schema-action.md
  docs/en/extending-doris/flink-doris-connector.md
  docs/zh-CN/administrator-guide/http-actions/fe/table-schema-action.md
  docs/zh-CN/extending-doris/flink-doris-connector.md
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisExecutionOptions.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/cfg/DorisStreamOptions.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/rest/models/Schema.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicOutputFormat.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableFactory.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisDynamicTableSink.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/TableSchemaAction.java
Labels: approved, reviewed

#7842 [Doc]wrong directory structure
  docs/zh-CN/extending-doris/odbc-of-doris.md
Labels: kind/docs, approved, reviewed

#7846 [fix](toolchain) Support ldb_toolchain on ubuntu 20
  thirdparty/build-thirdparty.sh
  thirdparty/patches/mysql-server-mysql-5.7.18.patch
Labels: kind/fix, approved, reviewed, area/toolchain

#7797 [Doc]Doris compile and install JDK version incompatibility problem
  docs/en/faq/error.md
  docs/zh-CN/faq/error.md
Labels: kind/docs, approved, reviewed

#7790 [Doc] add documents for bitwise functions
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/sql-reference/sql-functions/bitwise-functions/bitand.md
  docs/en/sql-reference/sql-functions/bitwise-functions/bitnot.md
  docs/en/sql-reference/sql-functions/bitwise-functions/bitor.md
  docs/en/sql-reference/sql-functions/bitwise-functions/bitxor.md
  docs/zh-CN/sql-reference/sql-functions/bitwise-functions/bitand.md
  docs/zh-CN/sql-reference/sql-functions/bitwise-functions/bitnot.md
  docs/zh-CN/sql-reference/sql-functions/bitwise-functions/bitor.md
  docs/zh-CN/sql-reference/sql-functions/bitwise-functions/bitxor.md
Labels: kind/docs, approved, reviewed

#7832 [Bug] Fix bug that wrong exception message returned by insert statement
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
Labels: area/planner, approved, reviewed, area/insert

#7838 [chore](docker) Add docker dev image with ldb-toolchain
  docker/Dockerfile
  docker/Dockerfile.gcc10
  docker/Dockerfile.gcc7
  docker/README.md
  docs/en/installing/compilation-with-ldb-toolchain.md
  docs/en/installing/compilation.md
  docs/zh-CN/installing/compilation-with-ldb-toolchain.md
  docs/zh-CN/installing/compilation.md
  fe/fe-core/src/main/java/org/apache/doris/load/Load.java
Labels: kind/chore, approved, reviewed, area/toolchain

#7844 [docs][seatunnel] add seatunnel flink doris sink doc
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/extending-doris/seatunnel/flink-sink.md
  docs/en/extending-doris/seatunnel/spark-sink.md
  docs/zh-CN/extending-doris/seatunnel/flink-sink.md
  docs/zh-CN/extending-doris/seatunnel/spark-sink.md
Labels: approved, reviewed

#7862 [fix](ldap) fix ldap password logic
  fe/fe-core/src/main/java/org/apache/doris/analysis/SetLdapPassVar.java
  fe/fe-core/src/main/java/org/apache/doris/common/FeMetaVersion.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/SymmetricEncryption.java
  fe/fe-core/src/main/java/org/apache/doris/ldap/LdapClient.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/PaloAuth.java
  fe/fe-core/src/main/java/org/apache/doris/persist/LdapInfo.java
  fe/fe-core/src/test/java/org/apache/doris/common/util/SymmetricEncryptionTest.java
  fe/fe-core/src/test/java/org/apache/doris/ldap/LdapClientTest.java
  fe/fe-core/src/test/java/org/apache/doris/persist/LdapInfoTest.java
Labels: kind/fix, kind/meta-version-change, approved, reviewed, area/ldap

#7827 [Vectorized][Bug] fix bug of coalesce function
  be/src/vec/columns/column_complex.h
  be/src/vec/columns/column_decimal.h
  be/src/vec/columns/column_nullable.h
  be/src/vec/columns/column_string.h
  be/src/vec/columns/column_vector.h
  be/src/vec/functions/function_coalesce.cpp
Labels: approved, reviewed

#7888 [fix](function) Change digital_masking function arg type to BIGINT
  docs/en/sql-reference/sql-functions/digital-masking.md
  docs/en/sql-reference/sql-statements/Data Definition/create-function.md
  docs/en/sql-reference/sql-statements/Data Definition/show-functions.md
  docs/zh-CN/sql-reference/sql-functions/digital-masking.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/create-function.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/show-functions.md
  fe/fe-core/src/main/java/org/apache/doris/catalog/AliasFunction.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/CreateFunctionTest.java
Labels: approved, reviewed

#7784 [Bug] Consider backend status when more than one backends exists in same host
  fe/fe-core/src/main/java/org/apache/doris/system/SystemInfoService.java
Labels: kind/fix, approved, reviewed

#7804 [build] fix build auditlog plugin error
  build_plugin.sh
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/administrator-guide/export_with_mysql_dump.md
  docs/en/community/how-to-deploy-to-maven.md
  docs/zh-CN/administrator-guide/export_with_mysql_dump.md
  docs/zh-CN/community/how-to-deploy-to-maven.md
  extension/DataX/doriswriter/pom.xml
  extension/DataX/doriswriter/src/main/assembly/package.xml
  extension/flink-doris-connector/pom.xml
  extension/spark-doris-connector/pom.xml
  fe/checkstyle.xml
  fe/fe-common/pom.xml
  fe/fe-core/pom.xml
  fe/fe-core/src/test/resources/log4j2.xml
  fe/pom.xml
  fe/spark-dpp/pom.xml
  fe_plugins/auditdemo/pom.xml
  fe_plugins/auditdemo/src/main/assembly/zip.xml
  fe_plugins/auditloader/pom.xml
  fe_plugins/auditloader/src/main/assembly/zip.xml
  fe_plugins/pom.xml
  fs_brokers/apache_hdfs_broker/conf/hdfs-site.xml
  fs_brokers/apache_hdfs_broker/pom.xml
  samples/connect/java/client/pom.xml
  samples/doris-demo/flink-demo/pom.xml
  samples/doris-demo/pom.xml
  samples/doris-demo/spark-demo/pom.xml
  samples/doris-demo/spring-jdbc-demo/pom.xml
  samples/doris-demo/spring-jdbc-demo/src/main/resources/logback.xml
  samples/doris-demo/spring-jdbc-demo/src/main/resources/mybatis/DemoMapper.xml
  samples/doris-demo/spring-jdbc-demo/src/main/resources/mybatis/mybatis-config.xml
  samples/doris-demo/stream-load-demo/pom.xml
Labels: approved, reviewed

#7830 [Doc] OS Installation Requirements
  docs/en/installing/install-deploy.md
  docs/zh-CN/installing/install-deploy.md
Labels: approved, reviewed

#7883 [Bug] fix clang compile error
  be/CMakeLists.txt
  be/src/olap/storage_engine.cpp
  be/test/exprs/bitmap_function_test.cpp
  be/test/olap/delta_writer_test.cpp
  be/test/olap/rowset/beta_rowset_test.cpp
  be/test/olap/rowset/rowset_converter_test.cpp
  be/test/olap/rowset/segment_v2/bitmap_index_test.cpp
  be/test/olap/rowset/segment_v2/bloom_filter_index_reader_writer_test.cpp
  be/test/olap/rowset/segment_v2/column_reader_writer_test.cpp
  be/test/olap/rowset/segment_v2/ordinal_page_index_test.cpp
  be/test/olap/rowset/segment_v2/segment_test.cpp
  be/test/olap/rowset/segment_v2/zone_map_index_test.cpp
  be/test/tools/benchmark_tool.cpp
  run-be-ut.sh
Labels: approved, reviewed

#7890 fix error while compiling with -O3
  be/CMakeLists.txt
  be/src/vec/common/cow.h
Labels: approved, reviewed

#7886 [docs]correct SeaTunnel website hyperlink
  docs/en/community/members.md
  docs/en/extending-doris/seatunnel/flink-sink.md
  docs/en/extending-doris/seatunnel/spark-sink.md
  docs/zh-CN/community/members.md
  docs/zh-CN/extending-doris/seatunnel/flink-sink.md
  docs/zh-CN/extending-doris/seatunnel/spark-sink.md
Labels: approved, reviewed

#7800 [Bug] Fix the bug of grouping set core in both vec and no vec query engine
  be/src/vec/common/columns_hashing.h
  be/src/vec/exec/vaggregation_node.cpp
  be/src/vec/exec/vaggregation_node.h
  be/src/vec/exec/vrepeat_node.cpp
  be/src/vec/functions/function_grouping.h
  fe/fe-core/src/main/java/org/apache/doris/analysis/AggregateInfoBase.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/planner/RepeatNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
Labels: kind/fix, area/planner, approved, area/vectorization, reviewed

#7836 (optimization)(vectorized)(olap) optimize pageDecoder by batch processing
  be/src/olap/rowset/segment_v2/binary_dict_page.cpp
  be/src/olap/rowset/segment_v2/bitshuffle_page.h
  be/src/vec/columns/column.h
  be/src/vec/columns/column_nullable.h
  be/src/vec/columns/column_vector.h
Labels: area/vectorization, reviewed

#7852 (refactor)(vectorized)refactor SegmentIterator::BitmapRangeIterator and SegmentIterator
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/olap/schema.h
Labels: approved, reviewed

#7391 [feature-wip](iceberg) Step1: Support create Iceberg external table
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/extending-doris/iceberg-of-doris.md
  docs/en/sql-reference/sql-statements/Data Definition/CREATE DATABASE.md
  docs/en/sql-reference/sql-statements/Data Definition/CREATE TABLE.md
  docs/en/sql-reference/sql-statements/Data Manipulation/SHOW TABLE CREATION.md
  docs/zh-CN/extending-doris/iceberg-of-doris.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/CREATE DATABASE.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/CREATE TABLE.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/SHOW TABLE CREATION.md
  fe/fe-common/src/main/java/org/apache/doris/common/property/PropertySchema.java
  fe/fe-core/pom.xml
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/ColumnDef.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateDbStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateTableStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowTableCreationStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Database.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/DatabaseProperty.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/IcebergProperty.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/IcebergTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Table.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/external/iceberg/DorisIcebergException.java
  fe/fe-core/src/main/java/org/apache/doris/external/iceberg/HiveCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/external/iceberg/IcebergCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/external/iceberg/IcebergCatalogMgr.java
  fe/fe-core/src/main/java/org/apache/doris/external/iceberg/IcebergTableCreationRecord.java
  fe/fe-core/src/main/java/org/apache/doris/external/iceberg/IcebergTableCreationRecordMgr.java
  fe/fe-core/src/main/java/org/apache/doris/external/iceberg/util/DorisTypeToType.java
  fe/fe-core/src/main/java/org/apache/doris/external/iceberg/util/DorisTypeVisitor.java
  fe/fe-core/src/main/java/org/apache/doris/external/iceberg/util/IcebergUtils.java
  fe/fe-core/src/main/java/org/apache/doris/external/iceberg/util/TypeToDorisType.java
  fe/fe-core/src/main/java/org/apache/doris/journal/JournalEntity.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/main/jflex/sql_scanner.flex
  fe/fe-core/src/test/java/org/apache/doris/analysis/CreateDbStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/CreateTableStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ShowTableCreationStmtTest.java
  fe/pom.xml
  gensrc/thrift/Descriptors.thrift
Labels: kind/feature, approved, reviewed, area/iceberg

#7821 [feature](meta) Support show compactionTooSlowTablets and oversizeTablets
  docs/en/administrator-guide/config/fe_config.md
  docs/zh-CN/administrator-guide/config/fe_config.md
  fe/fe-core/src/main/java/org/apache/doris/catalog/Replica.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Tablet.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/IncompleteTabletsProcNode.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/StatisticProcDir.java
Labels: approved, reviewed

#7876 [improvement](rewrite) Make RewriteDateLiteralRule to be compatible with mysql
  be/src/runtime/datetime_value.cpp
  fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/DateLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/ExprRewriter.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/RewriteDateLiteralRule.java
  fe/fe-core/src/test/java/org/apache/doris/rewrite/InferFiltersRuleTest.java
  fe/fe-core/src/test/java/org/apache/doris/rewrite/RewriteDateLiteralRuleTest.java
Labels: kind/improvement, kind/api-change, area/mysql-compatibility, approved, reviewed

#7867 [build][scripts] add set -e to download_thirdparty.sh
  thirdparty/download-thirdparty.sh
Labels: approved, reviewed

#7868 [docs] fix document backup-restore.md typo
  docs/en/administrator-guide/backup-restore.md
  docs/zh-CN/administrator-guide/backup-restore.md
Labels: good first issue, kind/docs, approved, reviewed

#7851 [improvement](executor) Displays cast information with implicit conversions in verbose
  fe/fe-core/src/main/java/org/apache/doris/analysis/CastExpr.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ExplainTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/UtFrameUtils.java
Labels: kind/improvement, area/planner, api-review, reviewed

#7855 [improvement](storage) improving Column inserter
  be/src/vec/columns/column_vector.h
  be/src/vec/columns/predicate_column.h
  be/src/vec/common/pod_array.h
Labels: area/storage, approved, area/vectorization, reviewed

#7865 [fix](lateral-view) fix bugs of lateral view with CTE or where clause
  fe/fe-core/src/main/java/org/apache/doris/analysis/LateralViewRef.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/TableRef.java
  fe/fe-core/src/test/java/org/apache/doris/planner/TableFunctionPlanTest.java
Labels: kind/fix, approved, reviewed, area/lateral-view

#7879 [improvement](meta) Use meta_version constant to replace magic number when check catalog journal version
  fe/fe-core/src/main/java/org/apache/doris/alter/AlterJob.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/MetaObject.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Tablet.java
  fe/fe-core/src/main/java/org/apache/doris/common/FeMetaVersion.java
  fe/fe-core/src/main/java/org/apache/doris/load/HadoopEtlJobInfo.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/UserProperty.java
  fe/fe-core/src/main/java/org/apache/doris/system/Backend.java
Labels: approved, reviewed

#7895 [docs] add function substring document
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/sql-reference/sql-functions/string-functions/substring.md
  docs/zh-CN/sql-reference/sql-functions/string-functions/substring.md
Labels: approved, reviewed

#7898 [Benchmark] Change ssb create table column to NOT NULL
  tools/ssb-tools/create-tables.sql
Labels: approved, reviewed

#7900 [Vectorized][Fix] fix bug multi distinct function get wrong type
  be/src/vec/exec/vaggregation_node.cpp
  be/src/vec/exprs/vectorized_agg_fn.cpp
  be/src/vec/functions/function_conv.cpp
  fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionSet.java
  gensrc/script/doris_builtins_functions.py
Labels: approved, reviewed

#7907 [docs] fix typo
  docs/en/faq/error.md
  docs/zh-CN/faq/error.md
Labels: good first issue, approved, reviewed

#7857 [Fix] fix memory leak in be unit test
  be/CMakeLists.txt
  be/src/util/sm3.cpp
  be/src/util/sm3.h
  be/src/vec/functions/function.h
  be/test/olap/rowset/segment_v2/column_reader_writer_test.cpp
  be/test/runtime/CMakeLists.txt
  be/test/vec/aggregate_functions/agg_test.cpp
  be/test/vec/exprs/vexpr_test.cpp
  be/test/vec/function/function_bitmap_test.cpp
  run-be-ut.sh
Labels: approved, reviewed

#7931 (fix)[planner] Fix the right tuple ids in empty set node
  be/src/runtime/descriptors.cpp
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: kind/fix, area/planner, approved, reviewed

#7914 [improvement](show) Support that user can use show data skew statement instead of admin
  .gitignore
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/sql-reference/sql-statements/Data Manipulation/SHOW DATA SKEW.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/SHOW DATA SKEW.md
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateDbStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowDataSkewStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/MetadataViewer.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Tablet.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/AdminShowReplicaTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/CreateDbStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ShowTableCreationStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: kind/api-change, kind/test, approved, area/show stmt, reviewed

#7917 [typo](storage) Optinmize dict page decoder init
  be/src/olap/rowset/segment_v2/column_reader.cpp
Labels: area/storage, approved, area/vectorization, reviewed

#7866 [fix](toolchain) Allow building when system contains libunwind
  thirdparty/build-thirdparty.sh
  thirdparty/patches/glog-0.4.0.patch
Labels: approved, reviewed

#7893 [chore] Remove BUILD_TYPE bcc
  be/CMakeLists.txt
Labels: approved, reviewed, area/toolchain

#7645 [Optimize] Support adaptive runtime filter(#7546)
  be/src/exprs/runtime_filter.cpp
  be/src/exprs/runtime_filter.h
  be/src/exprs/runtime_filter_slots.h
  be/test/exprs/runtime_filter_test.cpp
  docs/en/administrator-guide/runtime-filter.md
  docs/zh-CN/administrator-guide/runtime-filter.md
  fe/fe-core/src/main/java/org/apache/doris/qe/RuntimeFilterTypeHelper.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/RuntimeFilterGeneratorTest.java
  fe/fe-core/src/test/java/org/apache/doris/qe/RuntimeFilterTypeHelperTest.java
  fe/fe-core/src/test/java/org/apache/doris/qe/VariableMgrTest.java
  gensrc/proto/internal_service.proto
  gensrc/thrift/PlanNodes.thrift
Labels: kind/improvement, kind/api-change, approved, area/runtime-filter, reviewed

#7903 [Enhancement] support build with libc++ && add some build config
  be/CMakeLists.txt
  be/src/agent/cgroups_mgr.h
  be/src/common/configbase.cpp
  be/src/exprs/grouping_sets_functions.h
  be/src/exprs/json_functions.cpp
  be/src/exprs/math_functions.cpp
  be/src/gutil/strings/memutil.h
  be/src/gutil/strtoint.cc
  be/src/gutil/strtoint.h
  be/src/gutil/sysinfo.cc
  be/src/http/http_parser.h
  be/src/olap/delete_handler.h
  be/src/olap/olap_server.cpp
  be/src/olap/tablet_schema.h
  be/src/runtime/data_stream_sender.cpp
  be/src/udf/udf_ir.cpp
  be/src/util/encryption_util.cpp
  be/src/util/errno.cpp
  be/src/util/error_util.cc
  be/src/util/error_util.h
  be/src/util/md5.h
  be/src/util/mysql_load_error_hub.h
  be/src/util/string_parser.hpp
  be/src/util/string_util.h
  be/src/util/utf8_check.cpp
  be/src/vec/functions/function_json.cpp
  be/src/vec/functions/modulo.cpp
  be/src/vec/olap/vcollect_iterator.h
  be/src/vec/sink/vdata_stream_sender.cpp
  build.sh
  run-be-ut.sh
Labels: approved, reviewed

#7912 fix(ui):fix home page spin bug #7170
  .gitignore
  ui/public/locales/en-us.json
  ui/public/locales/zh-cn.json
  ui/src/pages/home/index.tsx
Labels: kind/fix, good first issue, approved, area/fe/frontpage, reviewed

#7933 [fix](storage) Using unique_ptr to refactor some class members
  be/src/olap/rowset/segment_v2/column_reader.cpp
  be/src/olap/rowset/segment_v2/column_reader.h
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/olap/rowset/segment_v2/segment_iterator.h
Labels: area/storage, approved, area/vectorization, reviewed

#7938 [Bug] fix abs function gew wrong result on gcc
  be/src/exprs/math_functions.cpp
Labels: approved, reviewed

#7848 [Compatible]http v2 and v1 interface compatible
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/rest/SchemaUtils.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/rest/models/Field.java
  extension/flink-doris-connector/src/main/java/org/apache/doris/flink/rest/models/Schema.java
  extension/flink-doris-connector/src/test/java/org/apache/doris/flink/serialization/TestRowBatch.java
  extension/spark-doris-connector/src/main/java/org/apache/doris/spark/rest/models/Field.java
  extension/spark-doris-connector/src/main/java/org/apache/doris/spark/rest/models/Schema.java
  extension/spark-doris-connector/src/main/scala/org/apache/doris/spark/sql/SchemaUtils.scala
  extension/spark-doris-connector/src/test/java/org/apache/doris/spark/rest/TestRestService.java
  extension/spark-doris-connector/src/test/java/org/apache/doris/spark/serialization/TestRowBatch.java
  extension/spark-doris-connector/src/test/scala/org/apache/doris/spark/sql/TestSchemaUtils.scala
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/TableSchemaAction.java
Labels: approved, reviewed

#7864 remove useless if statement in segment_writer.cpp
  be/src/olap/rowset/segment_v2/segment_writer.cpp
  gensrc/proto/segment_v2.proto
Labels: approved, reviewed

#7885 [improvement][build] Build script add build broker
  build.sh
Labels: approved, reviewed

#7905 [Vectorized][Join] Mem reuse to speed up join operator
  be/src/vec/columns/column.h
  be/src/vec/columns/column_complex.h
  be/src/vec/columns/column_const.cpp
  be/src/vec/columns/column_const.h
  be/src/vec/columns/column_decimal.cpp
  be/src/vec/columns/column_decimal.h
  be/src/vec/columns/column_nullable.cpp
  be/src/vec/columns/column_nullable.h
  be/src/vec/columns/column_string.cpp
  be/src/vec/columns/column_string.h
  be/src/vec/columns/column_vector.cpp
  be/src/vec/columns/column_vector.h
  be/src/vec/common/hash_table/hash_table.h
  be/src/vec/common/pod_array.h
  be/src/vec/exec/join/vhash_join_node.cpp
  be/src/vec/functions/math.cpp
Labels: approved, reviewed

#7919 [chore] Fix the return code of function download_func
  thirdparty/download-thirdparty.sh
Labels: kind/chore, approved, reviewed

#7922 [docs] rename DDL Statements to SQL Statements in sidebars of docs in english
  docs/.vuepress/sidebar/en.js
Labels: approved, reviewed

#7923 [storage]add Generic debug timer for debugging or profiling
  be/src/exec/olap_scan_node.cpp
  be/src/exec/olap_scan_node.h
  be/src/exec/olap_scanner.cpp
  be/src/olap/olap_common.h
  be/src/olap/rowset/segment_v2/binary_plain_page.h
  be/src/olap/rowset/segment_v2/column_reader.cpp
  be/src/olap/rowset/segment_v2/indexed_column_reader.cpp
  be/src/olap/rowset/segment_v2/options.h
  be/src/olap/rowset/segment_v2/parsed_page.h
Labels: approved, reviewed

#7934 (improvement)[test] Combine multiple tests to use only one Doris cluster
  fe/fe-core/src/main/java/org/apache/doris/analysis/CastExpr.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ExplainTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
  fe/fe-core/src/test/java/org/apache/doris/rewrite/RewriteDateLiteralRuleTest.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/DorisAssert.java
Labels: kind/improvement, area/planner, kind/test, approved, reviewed
