Repository apache/doris, pull requests merged in 2022-03, with the labels that each got.

#8251 [improvement](lateral-view) Add number rows filtered in profile
  be/src/exec/table_function_node.cpp
  be/src/exec/table_function_node.h
  be/src/exprs/table_function/explode_bitmap.cpp
  be/src/exprs/table_function/explode_json_array.cpp
  be/src/exprs/table_function/explode_split.cpp
  be/src/exprs/table_function/table_function.h
Labels: approved, area/profile, reviewed, area/lateral-view, dev/1.0.0

#8257 fix listdb description error
  fe/fe-core/src/main/java/org/apache/doris/PaloFe.java
Labels: kind/docs, approved, reviewed, dev/backlog

#8261 [Bug][Vectorized] fix bitmap_ut result wrong && fix schema_change compile error
  be/test/olap/schema_change_test.cpp
  be/test/vec/function/function_bitmap_test.cpp
Labels: approved, reviewed, dev/1.0.0

#8263 [refactor] remove unused new_in_predicate code
  be/src/common/daemon.cpp
  be/src/exprs/CMakeLists.txt
  be/src/exprs/new_in_predicate.cpp
  be/src/exprs/new_in_predicate.h
Labels: approved, kind/refactor, reviewed, dev/1.0.0

#8265 [fix][chore](insert)(fe) Fix analysis error of insert stmt and modify grpc-netty dependency
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateFunctionStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/InsertStmt.java
  fe/fe-core/src/main/java/org/apache/doris/rpc/BackendServiceClient.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
  fe/pom.xml
Labels: kind/fix, approved, reviewed, area/insert, dev/1.0.0

#8229 [Vec][Opt] better memequal impl to speed up string compare
  be/src/runtime/string_value.hpp
  be/src/vec/common/string_ref.h
Labels: approved, area/vectorization, reviewed, dev/1.0.0

#8238 [fix] Function percentile input null return null
  be/src/exec/mysql_scanner.cpp
  be/src/exprs/minmax_predicate.h
  be/src/util/counts.h
  be/src/vec/functions/function_json.cpp
  be/src/vec/functions/function_string.cpp
  be/src/vec/functions/function_timestamp.cpp
  be/src/vec/functions/function_totype.h
  be/test/vec/function/function_string_test.cpp
  docs/en/sql-reference/sql-functions/aggregate-functions/percentile.md
  docs/zh-CN/sql-reference/sql-functions/aggregate-functions/percentile.md
Labels: area/vectorization, reviewed, dev/1.0.0

#8156 [Transactions][Stmt] Support view transactions info for specified status by `SHOW TRANSACTION` stmt
  docs/en/sql-reference/sql-statements/Data Manipulation/SHOW TRANSACTION.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/SHOW TRANSACTION.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowTransactionStmt.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/GlobalTransactionMgr.java
Labels: approved, reviewed, dev/backlog

#8247 [refactor] Upgrade to MySQL 5.7.37 to reduce unnecessary CVE issues
  docs/en/administrator-guide/variables.md
  docs/zh-CN/administrator-guide/variables.md
  fe/fe-core/src/main/java/org/apache/doris/mysql/MysqlHandshakePacket.java
  fe/fe-core/src/main/java/org/apache/doris/qe/GlobalVariable.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/test/java/org/apache/doris/mysql/MysqlHandshakePacketTest.java
Labels: area/mysql-compatibility, approved, reviewed, dev/backlog

#8250 [revert] "[improvement]upgrade-grpc-version"
  fe/pom.xml
Labels: approved, kind/revert, reviewed, dev/backlog

#8271 make options of build.sh and run-be-ut.sh work
  build.sh
  run-be-ut.sh
Labels: approved, reviewed, dev/backlog

#8274 [Docs] Fix a typo in downloads.md
  docs/zh-CN/downloads/downloads.md
Labels: approved, reviewed

#8291 [Bug][Vectorized] Fix exchange node merge sort null first order wrong
  be/src/vec/core/sort_cursor.h
  be/src/vec/runtime/vsorted_run_merger.cpp
Labels: kind/fix, area/sql/execution, approved, area/vectorization, reviewed, dev/1.0.0

#8279 [feature-wip][array-type] Refactor type info for nested array.
  be/src/olap/aggregate_func.h
  be/src/olap/column_block.h
  be/src/olap/column_vector.cpp
  be/src/olap/column_vector.h
  be/src/olap/field.h
  be/src/olap/push_handler.cpp
  be/src/olap/rowset/segment_v2/binary_dict_page.cpp
  be/src/olap/rowset/segment_v2/bitmap_index_reader.h
  be/src/olap/rowset/segment_v2/bitmap_index_writer.cpp
  be/src/olap/rowset/segment_v2/bitmap_index_writer.h
  be/src/olap/rowset/segment_v2/bloom_filter_index_reader.h
  be/src/olap/rowset/segment_v2/bloom_filter_index_writer.cpp
  be/src/olap/rowset/segment_v2/bloom_filter_index_writer.h
  be/src/olap/rowset/segment_v2/column_reader.cpp
  be/src/olap/rowset/segment_v2/column_reader.h
  be/src/olap/rowset/segment_v2/column_writer.cpp
  be/src/olap/rowset/segment_v2/indexed_column_reader.cpp
  be/src/olap/rowset/segment_v2/indexed_column_reader.h
  be/src/olap/rowset/segment_v2/indexed_column_writer.cpp
  be/src/olap/rowset/segment_v2/indexed_column_writer.h
  be/src/olap/rowset/segment_v2/segment.cpp
  be/src/olap/rowset/segment_v2/zone_map_index.cpp
  be/src/olap/schema_change.cpp
  be/src/olap/types.cpp
  be/src/olap/types.h
  be/test/olap/column_vector_test.cpp
  be/test/olap/rowset/segment_v2/binary_dict_page_test.cpp
  be/test/olap/rowset/segment_v2/binary_prefix_page_test.cpp
  be/test/olap/rowset/segment_v2/bitmap_index_test.cpp
  be/test/olap/rowset/segment_v2/bloom_filter_index_reader_writer_test.cpp
  be/test/olap/rowset/segment_v2/column_reader_writer_test.cpp
  be/test/olap/rowset/segment_v2/encoding_info_test.cpp
  be/test/olap/schema_change_test.cpp
  be/test/olap/storage_types_test.cpp
  be/test/tools/benchmark_tool.cpp
Labels: approved, area/array-type, reviewed, dev/backlog

#8277 [fix] fix a bug of encryption function with iv may return wrong result
  be/src/exprs/encryption_functions.cpp
  be/src/exprs/minmax_predicate.h
  be/src/udf/udf.cpp
  be/src/udf/udf.h
  be/src/util/encryption_util.cpp
  be/src/util/encryption_util.h
  be/test/util/encryption_util_test.cpp
Labels: kind/fix, approved, reviewed, dev/backlog

#8303 [fix](ut) query stmt test error
  fe/fe-core/src/main/java/org/apache/doris/analysis/SetOperationStmt.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/QueryStmtTest.java
Labels: kind/fix, approved, reviewed, dev/backlog

#8293 [fix](fe-ut) Fix FE unit test
  fe/fe-common/src/main/java/org/apache/doris/common/FeMetaVersion.java
  fe/fe-core/src/main/java/org/apache/doris/alter/AlterJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/alter/RollupJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeJobV2.java
  fe/fe-core/src/test/java/org/apache/doris/backup/BackupJobTest.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/ReplicaTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/DppConfigTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/SparkLoadJobTest.java
  fe/fe-core/src/test/java/org/apache/doris/transaction/GlobalTransactionMgrTest.java
Labels: kind/fix, kind/test, approved, reviewed, dev/backlog

#8288 [Refactor] remove pusher.cpp and related mock test code
  be/src/agent/pusher.cpp
  be/src/olap/task/engine_batch_load_task.h
  be/test/agent/mock_pusher.h
Labels: approved, kind/refactor, reviewed, dev/backlog

#8289 [refactor] remove types_test
  be/test/util/CMakeLists.txt
  be/test/util/types_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/catalog/ScalarType.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
Labels: kind/test, approved, kind/refactor, reviewed, dev/backlog

#8309 [chore] remove some ut temp files and add some file to .gitignore
  .gitignore
  fe/fe-core/src/test/java/org/apache/doris/alter/SchemaChangeJobV2Test.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/DiskInfoTest.java
  fe/fe-core/src/test/java/org/apache/doris/persist/AlterRoutineLoadOperationLogTest.java
Labels: approved, kind/cleanup, reviewed

#8123 [improvement] optimize compaction too slow replica process, will set to ok if the replica compaction is done
  fe/fe-core/src/main/java/org/apache/doris/PaloFe.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/GroupingInfo.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/VirtualSlotRef.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Replica.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Tablet.java
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletSchedCtx.java
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletScheduler.java
  fe/fe-core/src/test/java/org/apache/doris/clone/TabletReplicaTooSlowTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: approved, reviewed, dev/backlog, area/tablet-repair

#8207 [fix] fix hash table insert() may be failed but not handle this error
  be/src/exec/except_node.cpp
  be/src/exec/hash_join_node.cpp
  be/src/exec/hash_table.h
  be/src/exec/hash_table.hpp
  be/src/exec/intersect_node.cpp
  be/src/exec/set_operation_node.cpp
  be/src/exec/set_operation_node.h
  be/test/exec/es_predicate_test.cpp
  be/test/olap/rowset/segment_v2/binary_dict_page_test.cpp
Labels: kind/fix, approved, reviewed, dev/1.0.0

#8245 fix restore with partitions cause some query fail
  fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/backup/RestoreJob.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Partition.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
Labels: kind/fix, approved, reviewed, dev/backlog

#8256 [Enhancement](routine-load) Support routine load task succeed with empty data consumed
  be/src/runtime/routine_load/data_consumer_group.cpp
Labels: approved, area/routine load, reviewed, dev/backlog

#8282 [Bug] fix string type length limit error && add runtime filter decimal support
  be/src/exprs/runtime_filter.cpp
  be/src/olap/olap_define.h
  be/src/vec/core/block.cpp
  be/src/vec/functions/function_case.h
  be/src/vec/sink/vtablet_sink.cpp
  be/src/vec/utils/template_helpers.hpp
Labels: kind/fix, approved, reviewed, dev/1.0.0

#8259 [Feature] Support Changing the bucketing mode of the table from Hash Distribution to Random Distribution
  docs/en/sql-reference/sql-statements/Data Definition/ALTER TABLE.md
  docs/en/sql-reference/sql-statements/Data Definition/CREATE TABLE.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/ALTER TABLE.md
  docs/zh-CN/sql-reference/sql-statements/Data Definition/CREATE TABLE.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/ModifyTablePropertiesClause.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/HashDistributionInfo.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Partition.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/RandomDistributionInfo.java
  fe/fe-core/src/main/java/org/apache/doris/persist/EditLog.java
  fe/fe-core/src/test/java/org/apache/doris/alter/SchemaChangeJobV2Test.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/CatalogTestUtil.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/FakeEditLog.java
Labels: approved, reviewed, dev/backlog

#8146 [Enhancement] Support Skipping compaction lower replica where select queryable replica for better scan performance
  be/src/common/config.h
  be/src/olap/tablet_manager.cpp
  be/src/olap/tablet_manager.h
  be/src/olap/tablet_meta_manager.cpp
  docs/en/administrator-guide/config/fe_config.md
  docs/zh-CN/administrator-guide/config/fe_config.md
  fe/fe-core/src/main/java/org/apache/doris/catalog/Replica.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Tablet.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/TabletStatMgr.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
  gensrc/thrift/BackendService.thrift
Labels: approved, reviewed

#8333 [typo]update spark build doc
  docs/en/extending-doris/spark-doris-connector.md
  docs/zh-CN/extending-doris/spark-doris-connector.md
Labels: approved, reviewed

#8308 [refactor] Translate the code comments of gensrc
  gensrc/proto/column_data_file.proto
  gensrc/proto/olap_file.proto
  gensrc/thrift/PaloExternalDataSourceService.thrift
Labels: approved, reviewed, dev/backlog

#8313 [docs] Fix invalid links in docker-dev document
  docs/en/developer-guide/docker-dev.md
  docs/zh-CN/developer-guide/docker-dev.md
Labels: good first issue, kind/docs, approved, reviewed, dev/backlog

#8314 [Weisite][Doc] The sidebar is off by default
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
Labels: approved, reviewed, dev/backlog

#8316 fix error in PushTask.java
  fe/fe-core/src/main/java/org/apache/doris/task/PushTask.java
Labels: approved, reviewed, dev/1.0.0

#8319 [refactor] Remove mysql-connector and replace org.json with com.googlecode.json-simple
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/org/apache/doris/backup/Repository.java
  fe/fe-core/src/main/java/org/apache/doris/deploy/impl/AmbariDeployManager.java
  fe/fe-core/src/main/java/org/apache/doris/external/elasticsearch/EsShardPartitions.java
  fe/fe-core/src/main/java/org/apache/doris/external/elasticsearch/EsShardRouting.java
  fe/fe-core/src/main/java/org/apache/doris/external/elasticsearch/EsUtil.java
  fe/fe-core/src/main/java/org/apache/doris/external/elasticsearch/MappingPhase.java
  fe/fe-core/src/main/java/org/apache/doris/http/rest/StorageTypeCheckAction.java
  fe/fe-core/src/main/java/org/apache/doris/http/rest/TableQueryPlanAction.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/interceptor/AuthInterceptor.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/TableQueryPlanAction.java
  fe/fe-core/src/main/java/org/apache/doris/journal/bdbje/BDBTool.java
  fe/fe-core/src/main/java/org/apache/doris/persist/GlobalVarPersistInfo.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/qe/VariableMgr.java
  fe/fe-core/src/test/java/org/apache/doris/external/elasticsearch/EsUtilTest.java
  fe/fe-core/src/test/java/org/apache/doris/http/TableQueryPlanActionTest.java
  fe/fe-core/src/test/java/org/apache/doris/http/TableRowCountActionTest.java
  fe/fe-core/src/test/java/org/apache/doris/http/TableSchemaActionTest.java
  fe/pom.xml
Labels: approved, kind/refactor, reviewed, dev/backlog

#8321 [typo] translate the comments of schema_change.h
  be/src/olap/schema_change.h
Labels: approved, reviewed, dev/backlog

#8344 [ut] fix be ut fragment_mgr_test compile failed
  be/test/runtime/fragment_mgr_test.cpp
Labels: kind/fix, kind/test, dev/backlog

#7970 [Feature] Support show tablets stmt
  docs/en/sql-reference/sql-statements/Data Manipulation/SHOW TABLET.md
  docs/en/sql-reference/sql-statements/Data Manipulation/SHOW TABLETS.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/SHOW TABLET.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/SHOW TABLETS.md
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/jflex/sql_scanner.flex
Labels: kind/api-change, approved, reviewed, dev/backlog

#8235 [fix](planner) Convert format in RewriteFromUnixTimeRule
  docs/en/sql-reference/sql-functions/date-time-functions/date_format.md
  docs/en/sql-reference/sql-functions/date-time-functions/from_unixtime.md
  docs/zh-CN/sql-reference/sql-functions/date-time-functions/date_format.md
  docs/zh-CN/sql-reference/sql-functions/date-time-functions/from_unixtime.md
  fe/fe-core/src/main/java/org/apache/doris/rewrite/RewriteFromUnixTimeRule.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: approved, reviewed, dev/backlog

#8280 [Bug][Vectorized] Fix core dump of mutable block different of block
  be/src/vec/core/block.cpp
  be/src/vec/core/block.h
  be/src/vec/exec/join/vhash_join_node.cpp
  be/src/vec/exec/vset_operation_node.cpp
Labels: kind/fix, approved, reviewed, dev/1.0.0

#8311 [Bug] Use fmt::to_string replace memory buffer::data()
  be/src/exec/base_scanner.cpp
  be/src/exec/broker_scanner.cpp
  be/src/exec/json_scanner.cpp
  be/src/exec/odbc_connector.cpp
  be/src/exec/tablet_sink.cpp
  be/src/runtime/runtime_state.cpp
  be/src/vec/sink/vmysql_table_writer.cpp
  be/src/vec/sink/vtablet_sink.cpp
Labels: kind/fix, approved, reviewed, dev/1.0.0

#8345 [Bug][Vectorized] Fix error cast to boolean
  be/src/vec/functions/function_cast.h
  be/src/vec/io/io_helper.h
Labels: approved, area/vectorization, reviewed, dev/1.0.0

#8349 [Doc]Add sync job fe configuration item description
  docs/en/administrator-guide/config/fe_config.md
  docs/zh-CN/administrator-guide/config/fe_config.md
Labels: kind/docs, approved, reviewed, dev/backlog

#8346 [docs]modify docs
  docs/zh-CN/administrator-guide/config/fe_config.md
  docs/zh-CN/administrator-guide/operation/tablet-repair-and-balance.md
Labels: approved, reviewed, dev/backlog

#8343 [docs]update http port doc to be more intuitive
  docs/en/installing/install-deploy.md
  docs/zh-CN/installing/install-deploy.md
Labels: approved, reviewed, dev/backlog

#8330 [improvement]support doriswriter build in macos
  extension/DataX/init-env.sh
Labels: approved, reviewed

#8296 [Feature] Support update stmt in vec query engine
  fe/fe-core/src/main/java/org/apache/doris/load/update/UpdatePlanner.java
  fe/fe-core/src/main/java/org/apache/doris/load/update/UpdateStmtExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/planner/HashJoinNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PlanNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
Labels: approved, area/vectorization, reviewed, dev/1.0.0

#8372 [revert] Revert "[refactor] remove unused new_in_predicate code"
  be/src/common/daemon.cpp
  be/src/exprs/CMakeLists.txt
  be/src/exprs/new_in_predicate.cpp
  be/src/exprs/new_in_predicate.h
Labels: approved, kind/revert, reviewed, dev/1.0.0

#8275 [community] Modify doris connector release doc
  docs/en/community/release-and-verify/release-doris-connectors.md
  docs/zh-CN/community/release-and-verify/release-doris-connectors.md
Labels: kind/community, kind/docs, approved, reviewed, dev/backlog

#8325 [typo]fix some typo in fe_config
  docs/en/administrator-guide/config/fe_config.md
  docs/zh-CN/administrator-guide/config/fe_config.md
Labels: approved, reviewed, dev/backlog

#8267 [fix](vectorization)Some small fix for SegmentIter Vectorization
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/vec/columns/column_complex.h
  be/src/vec/columns/column_vector.h
Labels: area/storage, approved, area/vectorization, reviewed, dev/1.0.0

#8307 [Vectorized][Function] support regexp&&sm4&&aes functions
  be/src/exprs/encryption_functions.cpp
  be/src/exprs/encryption_functions.h
  be/src/exprs/string_functions.cpp
  be/src/exprs/string_functions.h
  be/src/vec/CMakeLists.txt
  be/src/vec/aggregate_functions/aggregate_function_percentile_approx.cpp
  be/src/vec/functions/function_encryption.cpp
  be/src/vec/functions/function_hex.cpp
  be/src/vec/functions/function_regexp.cpp
  be/src/vec/functions/function_string.cpp
  be/src/vec/functions/function_string.h
  be/src/vec/functions/math.cpp
  be/src/vec/functions/simple_function_factory.h
  be/test/vec/function/function_like_test.cpp
  be/test/vec/function/function_string_test.cpp
  gensrc/script/doris_builtins_functions.py
Labels: approved, area/vectorization, reviewed, dev/1.0.0

#8096 [optimize] optimze tablet read, avoid to create too much scanner for small tablet
  be/src/common/config.h
  be/src/exec/olap_scan_node.cpp
  be/src/exec/olap_scan_node.h
  be/src/olap/tablet.h
  be/src/olap/tablet_meta.h
  be/src/vec/exec/volap_scan_node.cpp
  be/src/vec/exec/volap_scanner.cpp
  docs/en/administrator-guide/config/be_config.md
  docs/zh-CN/administrator-guide/config/be_config.md
Labels: kind/improvement, approved, reviewed, dev/backlog

#8340 Translate Chinese comment to English
  be/src/olap/rowset/run_length_byte_reader.h
Labels: approved, dev/backlog

#8355 [improvement][fix](insert)(replay) support SHOW LAST INSERT stmt and fix json replay bug
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/administrator-guide/load-data/insert-into-manual.md
  docs/en/sql-reference/sql-statements/Data Manipulation/SHOW-LAST-INSERT.md
  docs/zh-CN/administrator-guide/load-data/insert-into-manual.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/SHOW-LAST-INSERT.md
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowLastInsertStmt.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContext.java
  fe/fe-core/src/main/java/org/apache/doris/qe/InsertResult.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
Labels: kind/fix, area/catalog, approved, reviewed, area/insert, dev/1.0.0

#8363 [fix](broker-load) fix bug that a cancelled job's state is LOADING
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/TransDbProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/load/LoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/JobState.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadLoadingTask.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/GlobalTransactionMgr.java
Labels: kind/fix, approved, reviewed, area/broker-load, dev/1.0.0

#8375 add aggregation tests from trino to doris
  regression-test/data/aggregate/aggregate.out
  regression-test/data/aggregate/datetype.csv
  regression-test/suites/aggregate/aggregate.groovy
Labels: kind/test, approved, reviewed, dev/backlog

#8381 [Bug] fix core dump on minmax_filter with decimal type
  be/src/exprs/minmax_predicate.h
  be/src/exprs/runtime_filter.cpp
Labels: approved, reviewed, dev/1.0.0

#8384 [Feature][Vectorized] support replace()
  be/src/vec/common/string_ref.h
  be/src/vec/functions/function_string.cpp
  be/src/vec/functions/function_string.h
  be/test/exprs/runtime_filter_test.cpp
  be/test/vec/function/function_string_test.cpp
Labels: approved, area/vectorization, reviewed, dev/1.0.0

#8386 [Bug][Vectorized] Fix the datetime type read error and is_same set error in reader
  be/src/olap/row_block2.cpp
  be/src/vec/olap/vcollect_iterator.cpp
Labels: area/storage, approved, area/vectorization, reviewed, dev/1.0.0

#8392 [Bug][Vectorized] fix float to string inaccurate
  be/src/vec/data_types/data_type_number_base.cpp
Labels: approved, area/vectorization, reviewed, dev/1.0.0

#8217 [feature][array-type]support select ARRAY data type on vectorized engine
  be/src/olap/column_vector.h
  be/src/olap/field.h
  be/src/olap/row_block2.cpp
  be/src/olap/row_block2.h
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/olap/schema.cpp
  be/src/olap/schema.h
  be/src/olap/tablet_schema.cpp
  be/src/runtime/descriptors.cpp
  be/src/runtime/descriptors.h
  be/src/runtime/types.h
  be/src/vec/CMakeLists.txt
  be/src/vec/columns/column_array.cpp
  be/src/vec/columns/column_array.h
  be/src/vec/core/block.cpp
  be/src/vec/core/types.h
  be/src/vec/data_types/data_type.cpp
  be/src/vec/data_types/data_type.h
  be/src/vec/data_types/data_type_array.cpp
  be/src/vec/data_types/data_type_array.h
  be/src/vec/data_types/data_type_factory.cpp
  be/src/vec/data_types/data_type_factory.hpp
  be/src/vec/data_types/data_type_number_base.h
  be/src/vec/exprs/vectorized_agg_fn.cpp
  be/src/vec/exprs/vexpr.cpp
  be/src/vec/olap/vgeneric_iterators.cpp
  be/src/vec/sink/mysql_result_writer.cpp
  be/src/vec/sink/mysql_result_writer.h
  be/test/vec/core/CMakeLists.txt
  be/test/vec/core/column_array_test.cpp
  be/test/vec/exec/vgeneric_iterators_test.cpp
Labels: area/array-type

#8397 [fix](docs) fix wrong examples in week.md
  docs/zh-CN/sql-reference/sql-functions/date-time-functions/week.md
Labels: approved, reviewed

#8209 [fix](replica) handle replica version missing info to avoid -214 error
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/EsTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Replica.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/TabletInvertedIndex.java
  fe/fe-core/src/main/java/org/apache/doris/external/elasticsearch/EsRestClient.java
  fe/fe-core/src/main/java/org/apache/doris/journal/JournalEntity.java
  fe/fe-core/src/main/java/org/apache/doris/load/LoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/master/ReportHandler.java
  fe/fe-core/src/main/java/org/apache/doris/persist/BackendReplicasInfo.java
  fe/fe-core/src/main/java/org/apache/doris/persist/BackendTabletsInfo.java
  fe/fe-core/src/main/java/org/apache/doris/persist/EditLog.java
  fe/fe-core/src/main/java/org/apache/doris/persist/OperationType.java
  fe/fe-core/src/test/java/org/apache/doris/persist/BackendReplicaInfosTest.java
Labels: approved, reviewed, dev/backlog

#8226 [Bug][Vectorized] fix arithmetic calculate get wrong result
  be/src/exprs/arithmetic_expr.cpp
  be/src/exprs/arithmetic_expr.h
  be/src/exprs/expr.cpp
  be/src/vec/functions/minus.cpp
  be/src/vec/functions/modulo.cpp
  be/src/vec/functions/multiply.cpp
  be/src/vec/functions/plus.cpp
  fe/fe-core/src/main/cup/sql_parser.cup
Labels: kind/fix, approved, area/vectorization, reviewed, dev/1.0.0

#8273 [Refactor] Remove agent status
  be/src/agent/cgroups_mgr.cpp
  be/src/agent/cgroups_mgr.h
  be/src/agent/heartbeat_server.cpp
  be/src/agent/heartbeat_server.h
  be/src/agent/status.h
  be/src/agent/task_worker_pool.cpp
  be/src/agent/task_worker_pool.h
  be/src/agent/utils.cpp
  be/src/agent/utils.h
  be/src/common/status.cpp
  be/src/common/status.h
  be/src/olap/storage_engine.h
  be/src/olap/tablet_manager.h
  be/src/olap/task/engine_batch_load_task.cpp
  be/src/olap/task/engine_batch_load_task.h
  be/src/olap/task/engine_clone_task.cpp
  be/src/olap/task/engine_clone_task.h
  be/src/olap/txn_manager.h
  be/src/service/doris_main.cpp
  be/test/agent/cgroups_mgr_test.cpp
  be/test/agent/mock_task_worker_pool.h
  be/test/agent/mock_utils.h
  be/test/olap/file_helper_test.cpp
  be/test/olap/file_utils_test.cpp
Labels: approved, kind/refactor, reviewed, dev/backlog

#8339 [docs] add document conditional-functions
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/sql-reference/sql-functions/conditional-functions/case.md
  docs/en/sql-reference/sql-functions/conditional-functions/coalesce.md
  docs/en/sql-reference/sql-functions/conditional-functions/if.md
  docs/en/sql-reference/sql-functions/conditional-functions/ifnull.md
  docs/en/sql-reference/sql-functions/conditional-functions/nullif.md
  docs/zh-CN/sql-reference/sql-functions/conditional-functions/case.md
  docs/zh-CN/sql-reference/sql-functions/conditional-functions/coalesce.md
  docs/zh-CN/sql-reference/sql-functions/conditional-functions/if.md
  docs/zh-CN/sql-reference/sql-functions/conditional-functions/ifnull.md
  docs/zh-CN/sql-reference/sql-functions/conditional-functions/nullif.md
Labels: approved, reviewed, dev/backlog

#8342 [Refactor] remove old sc be
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
  be/src/olap/delta_writer.cpp
  be/src/olap/delta_writer.h
  be/src/runtime/CMakeLists.txt
  be/src/runtime/dpp_sink.cpp
  be/src/runtime/dpp_sink.h
  be/src/runtime/dpp_sink_internal.cpp
  be/src/runtime/dpp_sink_internal.h
  be/src/runtime/tablets_channel.cpp
  be/test/runtime/data_spliter_test.cpp
  be/test/runtime/dpp_sink_internal_test.cpp
  be/test/runtime/dpp_sink_test.cpp
  be/test/runtime/load_channel_mgr_test.cpp
  gensrc/proto/internal_service.proto
  gensrc/thrift/DataSinks.thrift
Labels: approved, reviewed, dev/backlog

#8361 [docs] fix doc
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/BROKER LOAD.md
Labels: approved, reviewed, dev/backlog

#8398 Update substring.md
  docs/zh-CN/sql-reference/sql-functions/string-functions/substring.md
Labels: kind/docs, approved, reviewed, dev/backlog

#8402 translate the comments of delete_handler.cpp
  be/src/olap/delete_handler.cpp
Labels: approved, reviewed, dev/backlog

#8395 [Opt][Vectorized] Merge block in scanner to speed up query with conjunct
  be/src/vec/exec/join/vhash_join_node.cpp
  be/src/vec/exec/volap_scan_node.cpp
Labels: kind/improvement, approved, reviewed, dev/backlog

#8410 [fix] fix compile error
  be/src/agent/cgroups_mgr.cpp
  be/src/olap/task/engine_batch_load_task.cpp
Labels: approved, reviewed

#7234 [Thread] Add thread local variable ThreadContext
  be/src/runtime/CMakeLists.txt
  be/src/runtime/thread_context.cpp
  be/src/runtime/thread_context.h
  be/src/runtime/threadlocal.cc
  be/src/runtime/threadlocal.h
Labels: kind/improvement, approved, reviewed, dev/backlog

#8358 [Doc][Vectorized] Add vectorized execution engine docs
  docs/.vuepress/public/images/vectorized-execution-engine1.png
  docs/.vuepress/public/images/vectorized-execution-engine2.png
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/administrator-guide/vectorized-execution-engine.md
  docs/zh-CN/administrator-guide/vectorized-execution-engine.md
Labels: kind/docs, approved, reviewed, dev/backlog

#8379 Fix dead link in build docker environment in developer guide
  docs/en/developer-guide/docker-dev.md
  docs/zh-CN/developer-guide/docker-dev.md
Labels: good first issue, kind/docs, approved, reviewed, dev/backlog

#8409 [Feature][Vectorized] support digital_masking
  fe/fe-core/src/main/java/org/apache/doris/catalog/AliasFunction.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Function.java
Labels: approved, reviewed, dev/1.0.0

#8429 [Bug][Vectorized] core dump on runtime filter insert because of block address change
  be/src/vec/exec/join/vhash_join_node.cpp
Labels: kind/fix, approved, reviewed, dev/1.0.0

#8403 [doc] fix metadata operation doc links to external docs
  docs/en/administrator-guide/operation/metadata-operation.md
  docs/zh-CN/administrator-guide/operation/metadata-operation.md
Labels: kind/docs, approved, reviewed

#8442 [Vectorized] Support function tuple is null
  be/src/exprs/expr.h
  be/src/vec/CMakeLists.txt
  be/src/vec/columns/column.h
  be/src/vec/columns/column_nullable.cpp
  be/src/vec/columns/column_nullable.h
  be/src/vec/columns/column_vector.cpp
  be/src/vec/exec/join/vhash_join_node.cpp
  be/src/vec/exprs/vexpr.cpp
  be/src/vec/exprs/vtuple_is_null_predicate.cpp
  be/src/vec/exprs/vtuple_is_null_predicate.h
  fe/fe-core/src/main/java/org/apache/doris/analysis/TupleIsNullPredicate.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
Labels: approved, area/vectorization, reviewed, dev/1.0.0

#8365 [feature](user-property) Support user level exec_mem_limit and load_mem_limit
  docs/en/sql-reference/sql-statements/Account Management/SET PROPERTY.md
  docs/zh-CN/sql-reference/sql-statements/Account Management/SET PROPERTY.md
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/CommonUserProperties.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/PaloAuth.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/UserProperty.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/UserPropertyMgr.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
Labels: kind/feature, approved, reviewed, dev/1.0.0

#8373 [Refactor] to_bitmap(-1) return NULL instead of return parse failed error_message
  be/src/exprs/bitmap_function.cpp
  be/src/exprs/hll_function.cpp
  be/src/vec/aggregate_functions/aggregate_function_bitmap.h
  be/src/vec/aggregate_functions/aggregate_function_hll_union_agg.cpp
  be/src/vec/aggregate_functions/aggregate_function_hll_union_agg.h
  be/src/vec/aggregate_functions/aggregate_function_reader.cpp
  be/src/vec/aggregate_functions/aggregate_function_simple_factory.cpp
  be/src/vec/functions/function_bit.cpp
  be/src/vec/functions/function_bitmap.cpp
  be/src/vec/functions/function_encryption.cpp
  be/src/vec/functions/function_string.cpp
  be/src/vec/sink/vtablet_sink.cpp
  be/test/exprs/bitmap_function_test.cpp
  be/test/vec/function/function_string_test.cpp
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/sql-reference/sql-functions/bitmap-functions/to_bitmap.md
  docs/en/sql-reference/sql-functions/bitwise-functions/bit_length.md
  docs/zh-CN/sql-reference/sql-functions/bitmap-functions/to_bitmap.md
  docs/zh-CN/sql-reference/sql-functions/bitwise-functions/bit_length.md
  fe/fe-core/src/main/java/org/apache/doris/catalog/AggregateFunction.java
  gensrc/script/doris_builtins_functions.py
Labels: kind/fix, approved, reviewed, dev/1.0.0

#8436 [improvement] Avoid print large string in error log
  be/src/vec/common/string_ref.h
  be/src/vec/sink/vtablet_sink.cpp
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/sql-reference/sql-functions/string-functions/coalesce.md
  docs/zh-CN/sql-reference/sql-functions/conditional-functions/coalesce.md
  docs/zh-CN/sql-reference/sql-functions/string-functions/coalesce.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateFunctionStmt.java
Labels: kind/improvement, kind/docs, approved, reviewed, dev/1.0.0

#8444 [fix](report) fix bug that tablet may already be delete when reporting
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
Labels: kind/fix, approved, reviewed, dev/1.0.0

#8423 [Fix](transaction) Fix committed transaction couldn't be finished when table is dropped
  fe/fe-core/src/main/java/org/apache/doris/catalog/Database.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Table.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/MetaLockUtils.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/PublishVersionDaemon.java
Labels: kind/fix, approved, reviewed, dev/1.0.0

#8387 [Refactor](storage_engine) Use std::shared_mutex to replace RWMutex
  be/src/agent/task_worker_pool.cpp
  be/src/agent/topic_subscriber.cpp
  be/src/exec/olap_scanner.cpp
  be/src/olap/compaction.cpp
  be/src/olap/data_dir.cpp
  be/src/olap/data_dir.h
  be/src/olap/delta_writer.cpp
  be/src/olap/push_handler.cpp
  be/src/olap/reader.cpp
  be/src/olap/schema_change.cpp
  be/src/olap/snapshot_manager.cpp
  be/src/olap/storage_engine.cpp
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
  be/src/olap/tablet_manager.cpp
  be/src/olap/tablet_manager.h
  be/src/olap/tablet_meta.cpp
  be/src/olap/tablet_meta.h
  be/src/olap/task/engine_checksum_task.cpp
  be/src/olap/task/engine_clone_task.cpp
  be/src/olap/task/engine_storage_migration_task.cpp
  be/src/olap/txn_manager.cpp
  be/src/olap/txn_manager.h
  be/src/util/mutex.cpp
  be/src/util/mutex.h
  be/src/util/thread_group.h
Labels: approved, kind/refactor, reviewed, dev/backlog

#8424 [docs]Update load-manual.md
  docs/zh-CN/administrator-guide/load-data/load-manual.md
Labels: kind/docs

#8324 [Feature](proc) Support proc dir for showing tablet health status
  fe/fe-core/src/main/java/org/apache/doris/common/proc/ClusterHealthProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/IncompleteTabletsProcNode.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/ProcService.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/StatisticProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/StatisticProcNode.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/TabletHealthProcDir.java
Labels: kind/api-change, approved, reviewed, dev/backlog

#8390 [fix] fix hdfs or bos path parser not support glob exprs
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateFunctionStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ExportStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/HdfsURI.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/AggregateFunction.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Function.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/ScalarFunction.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/URI.java
  fe/fe-core/src/test/java/org/apache/doris/common/util/URITest.java
Labels: kind/fix, area/load, approved, reviewed, dev/1.0.0

#8328 small fixes and code cleanups related to schema change
  be/src/olap/schema_change.cpp
  fe/fe-core/src/main/java/org/apache/doris/analysis/ColumnRenameClause.java
Labels: area/schema-change, approved, kind/refactor, reviewed, dev/backlog

#8371 [Doc]Update hive support version
  docs/en/extending-doris/hive-of-doris.md
  docs/zh-CN/extending-doris/hive-of-doris.md
Labels: kind/docs, approved, reviewed

#8425 [chore] disable librdkafka assert and update some thirdparty
  be/CMakeLists.txt
  be/src/exec/parquet_writer.cpp
  be/src/util/arrow/row_batch.cpp
  be/src/util/arrow/row_block.cpp
  docker/Dockerfile
  fe/pom.xml
  thirdparty/CHANGELOG.md
  thirdparty/build-thirdparty.sh
  thirdparty/download-thirdparty.sh
  thirdparty/patches/librdkafka-1.8.2.patch
  thirdparty/vars.sh
Labels: area/dependency, approved, reviewed, dev/backlog

#8453 [fix] BE crash when reporting tablet
  be/src/olap/tablet.cpp
Labels: kind/fix, approved, reviewed, dev/1.0.0

#8450 [Bug] Support BetweenPredicate enable fold const expr
  be/src/runtime/mysql_result_writer.cpp
  be/src/vec/columns/column.h
  be/src/vec/columns/column_nullable.cpp
  be/src/vec/columns/column_nullable.h
  be/src/vec/columns/column_vector.cpp
  be/src/vec/exprs/vtuple_is_null_predicate.cpp
  fe/fe-core/src/main/java/org/apache/doris/rewrite/FoldConstantsRule.java
Labels: approved, reviewed, dev/1.0.0

#8434 [typo]update broker load docs format
  docs/en/sql-reference/sql-statements/Data Manipulation/BROKER LOAD.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/BROKER LOAD.md
Labels: approved, reviewed

#8369 [docs] Update documentation configuration parameter `sink.batch.bytes…
  docs/en/extending-doris/flink-doris-connector.md
  docs/zh-CN/extending-doris/flink-doris-connector.md
Labels: kind/docs, reviewed, dev/backlog

#8233 [Vectorized][HashJoin] add probe timer
  be/src/vec/exec/join/vhash_join_node.cpp
  be/src/vec/exec/join/vhash_join_node.h
Labels: approved, area/vectorization, reviewed

#8456 [chore](dependency) fix build thirdparty errors
  docs/.vuepress/sidebar/en.js
  docs/.vuepress/sidebar/zh-CN.js
  docs/en/sql-reference/sql-functions/bitwise-functions/bit_length.md
  docs/zh-CN/sql-reference/sql-functions/bitwise-functions/bit_length.md
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/ScheduleRule.java
  thirdparty/download-thirdparty.sh
Labels: kind/chore, approved, reviewed, dev/1.0.0

#8451 [improvement](memory) fix olap table scan and sink memory usage problem
  be/src/common/config.h
  be/src/exec/olap_scan_node.cpp
  be/src/exec/olap_scan_node.h
  be/src/exec/olap_scanner.cpp
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
  be/src/vec/exec/volap_scan_node.cpp
  be/src/vec/exec/volap_scanner.cpp
Labels: kind/improvement, approved, area/memory-consumption, reviewed, dev/1.0.0

#8457 [fix][routine-load] fix bug that routine load cannot cancel task when append_data return error
  be/src/runtime/routine_load/data_consumer_group.cpp
Labels: kind/fix, approved, reviewed, dev/merged-1.0.1

#8461 [fix](vectorized) Agg/Unique not null column outer join coredump
  be/src/exec/olap_scanner.cpp
  be/src/exec/olap_scanner.h
  be/src/olap/reader.cpp
  be/src/olap/reader.h
  be/src/olap/tablet_schema.cpp
  be/src/olap/tablet_schema.h
  be/src/vec/olap/vcollect_iterator.cpp
Labels: kind/fix, approved, reviewed, dev/1.0.0, dev/1.0.1

#8202 [improvment] show export support label like
  docs/en/sql-reference/sql-statements/Data Manipulation/SHOW EXPORT.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/SHOW EXPORT.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowExportStmt.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/ExportProcNode.java
  fe/fe-core/src/main/java/org/apache/doris/load/ExportMgr.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ShowExportStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/ExportMgrTest.java
Labels: kind/improvement, approved, area/export, reviewed, dev/1.0.1

#8437 [feature-wip][udf] support java udf in FE
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateFunctionStmt.java
  gensrc/thrift/Types.thrift
Labels: kind/feature, approved, area/udf, reviewed, dev/backlog

#8458 [UT] add unit tests for min/max function, and cleaned up some unused …
  be/src/vec/aggregate_functions/aggregate_function_min_max.h
  be/test/vec/aggregate_functions/CMakeLists.txt
  be/test/vec/aggregate_functions/agg_min_max_test.cpp
Labels: approved, reviewed, dev/backlog

#8460 [test]let framework support sql cases and run cases in parallel and random order
  regression-test/framework/src/main/groovy/org/apache/doris/regression/Config.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/ConfigOptions.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/RegressionTest.groovy
  run-regression-test.sh
Labels: kind/improvement, kind/test, approved, reviewed, dev/backlog

#8462 Update ShowExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
Labels: kind/improvement, approved, reviewed, dev/1.0.1

#8464 [Bug] Fix some mistakes for ReadWriteLock in be
  be/src/olap/tablet.cpp
  be/src/olap/tablet_manager.cpp
Labels: kind/fix, approved, reviewed, dev/1.0.1

#8471 [fix](dynamic-partition) fix bug that can not set "dynamic_partition.replication_allocation" property
  fe/fe-core/src/main/java/org/apache/doris/catalog/TableProperty.java
Labels: kind/fix, approved, area/dynamic-partition, reviewed, dev/1.0.1

#8489 [fix] fix some UT compile or run failed cases
  be/src/exprs/bitmap_function.cpp
  be/src/olap/tablet_schema.h
  be/test/olap/delta_writer_test.cpp
  be/test/util/arrow/arrow_row_batch_test.cpp
Labels: reviewed, dev/1.0.1

#8479 [Bug] min function of not null varchar column get error result
  be/src/exprs/anyval_util.h
Labels: kind/fix, area/sql/execution, approved, reviewed, dev/1.0.1

#8478 [fix](storage)fix bitmap wrong result in storage layer
  be/src/vec/columns/column_complex.h
Labels: kind/fix, approved, reviewed, dev/1.0.1

#8483 [test] support order qt for sql file and fix exception
  regression-test/framework/src/main/groovy/org/apache/doris/regression/RegressionTest.groovy
Labels: kind/test, approved, reviewed, dev/backlog

#8454 [fix](partition_cache) Fix Partition Cache NullPointerException bug
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/PartitionRange.java
  fe/fe-core/src/test/java/org/apache/doris/qe/PartitionCacheTest.java
Labels: kind/fix, approved, reviewed, dev/1.0.1

#8484 [improvement](vectorized) Make bloom filter predicate run short-circuit logic
  be/src/olap/bloom_filter_predicate.h
  be/src/olap/column_predicate.h
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
Labels: area/storage, approved, area/vectorization, reviewed, dev/1.0.1

#8492 [chore](dependency) update Croaring for good performance
  be/src/util/bitmap_value.h
  thirdparty/CHANGELOG.md
  thirdparty/build-thirdparty.sh
  thirdparty/patches/aws-c-cal-0.4.5.patch
  thirdparty/vars.sh
Labels: area/dependency, approved, reviewed, dev/1.0.1

#8496 [Bug][Vectorized] fix core dump on get_json_string and add some ut
  be/CMakeLists.txt
  be/src/vec/functions/function_json.cpp
  be/test/exprs/array_functions_test.cpp
  be/test/http/message_body_sink_test.cpp
  be/test/olap/bit_field_test.cpp
  be/test/olap/column_reader_test.cpp
  be/test/olap/delete_handler_test.cpp
  be/test/olap/delta_writer_test.cpp
  be/test/olap/options_test.cpp
  be/test/olap/rowset/alpha_rowset_test.cpp
  be/test/olap/rowset/beta_rowset_test.cpp
  be/test/olap/rowset/rowset_converter_test.cpp
  be/test/olap/run_length_byte_test.cpp
  be/test/olap/run_length_integer_test.cpp
  be/test/olap/schema_change_test.cpp
  be/test/runtime/memory_scratch_sink_test.cpp
  be/test/runtime/user_function_cache_test.cpp
  be/test/util/arrow/arrow_work_flow_test.cpp
  be/test/vec/function/CMakeLists.txt
  be/test/vec/function/function_json_test.cpp
  build.sh
  run-be-ut.sh
Labels: approved, reviewed, dev/1.0.1

#8499 [test] support run regression test with out load data
  regression-test/framework/src/main/groovy/org/apache/doris/regression/Config.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/ConfigOptions.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/RegressionTest.groovy
Labels: approved, reviewed, dev/backlog

#8481 [Bug](ReportHandler) Fix bug that tabletReport function of ReportHandler in fe may throw NullPointerException due to transaction check logic
  fe/fe-core/src/main/java/org/apache/doris/catalog/TabletInvertedIndex.java
Labels: kind/fix, approved, area/tablet-report, reviewed, dev/1.0.1

#8490 CalcPageLenForRow return void rather than always Status::Ok
  be/src/runtime/buffered_tuple_stream3.cc
  be/src/runtime/buffered_tuple_stream3.h
Labels: reviewed, dev/1.0.1

#8497 [fix](connect)(cpp) fix the condition of breaking for loop in functio…
  samples/connect/cpp/doris_client.cpp
Labels: approved, reviewed, dev/1.0.1

#8501 [fix](load) fix bug that BE may crash when calling `mark_as_failed`
  be/src/exec/tablet_sink.cpp
  be/src/exec/tablet_sink.h
Labels: kind/fix, area/load, approved, reviewed, dev/1.0.0-deprecated, dev/1.0.1

#8503 [fix] Fix may coredump when check if all rowset is beta-rowset of a tablet
  be/src/olap/tablet.h
Labels: kind/fix, approved, reviewed, dev/1.0.0-deprecated, dev/1.0.1

#8507 [Fix] Fix bug that __set_ missing for thrift optional fields in be
  be/src/olap/tablet_manager.cpp
Labels: approved, reviewed, dev/1.0.1

#8511 [Doc]flink 1.14 support
  docs/en/extending-doris/flink-doris-connector.md
  docs/zh-CN/extending-doris/flink-doris-connector.md
Labels: kind/docs, approved, reviewed, dev/merged-1.0.1

#8517 [fix]memory leak in ResourceTls
  be/src/common/resource_tls.cpp
Labels: approved, reviewed, dev/1.0.1

#8515 [fix] fix String type comapaction or agg may crash when string is null
  be/src/olap/field.h
Labels: kind/fix, approved, reviewed, dev/1.0.0-deprecated, dev/1.0.1

#8519 [Doc]Update best-practice.md
  docs/zh-CN/getting-started/best-practice.md
Labels: kind/docs

#8527 [doc]Update best-practice.md
  docs/en/getting-started/best-practice.md
Labels: kind/docs

#8535 [release] Add download link for flink/spark connector
  docs/en/community/release-and-verify/release-complete.md
  docs/en/downloads/downloads.md
  docs/en/extending-doris/flink-doris-connector.md
  docs/en/extending-doris/spark-doris-connector.md
  docs/zh-CN/community/release-and-verify/release-complete.md
  docs/zh-CN/downloads/downloads.md
  docs/zh-CN/extending-doris/flink-doris-connector.md
  docs/zh-CN/extending-doris/spark-doris-connector.md
Labels: kind/docs, approved, reviewed, dev/1.0.1

#8520 [doc] Fix some typo about spark load and broker load
  docs/en/administrator-guide/load-data/spark-load-manual.md
  docs/en/sql-reference/sql-statements/Data Manipulation/BROKER LOAD.md
  docs/zh-CN/administrator-guide/load-data/spark-load-manual.md
  docs/zh-CN/sql-reference/sql-statements/Data Manipulation/BROKER LOAD.md
Labels: kind/docs, approved, reviewed, dev/1.0.1

#8529 [Doc]backup doc fix
  docs/en/administrator-guide/backup-restore.md
  docs/zh-CN/administrator-guide/backup-restore.md
Labels: kind/docs, approved, reviewed, dev/1.0.1

#8537 [license] Update license-dist.txt for thirdparties
  dist/LICENSE-dist.txt
Labels: approved, kind/license, reviewed, dev/1.0.1

#8318 [improvement](storage) Low cardinality string optimization in storage layer
  be/src/common/config.h
  be/src/exprs/expr_value.h
  be/src/olap/column_predicate.h
  be/src/olap/comparison_predicate.cpp
  be/src/olap/comparison_predicate.h
  be/src/olap/in_list_predicate.cpp
  be/src/olap/rowset/segment_v2/binary_dict_page.cpp
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/olap/schema.cpp
  be/src/runtime/string_value.h
  be/src/runtime/string_value.hpp
  be/src/vec/columns/column.h
  be/src/vec/columns/column_dictionary.h
  be/src/vec/columns/column_nullable.h
  be/src/vec/columns/column_string.h
  be/src/vec/columns/predicate_column.h
Labels: kind/feature, area/storage, approved, area/vectorization, reviewed, dev/1.0.1

#8408 [Benchmark] Add TPC-H benchmark tools
  tools/tpch-tools/README.md
  tools/tpch-tools/build-tpch-dbgen.sh
  tools/tpch-tools/create-tpch-tables.sh
  tools/tpch-tools/create-tpch-tables.sql
  tools/tpch-tools/doris-cluster.conf
  tools/tpch-tools/gen-tpch-data.sh
  tools/tpch-tools/load-tpch-data.sh
  tools/tpch-tools/queries/q1.sql
  tools/tpch-tools/queries/q10.sql
  tools/tpch-tools/queries/q11.sql
  tools/tpch-tools/queries/q12.sql
  tools/tpch-tools/queries/q13.sql
  tools/tpch-tools/queries/q14.sql
  tools/tpch-tools/queries/q15.sql
  tools/tpch-tools/queries/q16.sql
  tools/tpch-tools/queries/q17.sql
  tools/tpch-tools/queries/q18.sql
  tools/tpch-tools/queries/q19.sql
  tools/tpch-tools/queries/q2.sql
  tools/tpch-tools/queries/q20.sql
  tools/tpch-tools/queries/q21.sql
  tools/tpch-tools/queries/q22.sql
  tools/tpch-tools/queries/q3.sql
  tools/tpch-tools/queries/q4.sql
  tools/tpch-tools/queries/q5.sql
  tools/tpch-tools/queries/q6.sql
  tools/tpch-tools/queries/q7.sql
  tools/tpch-tools/queries/q8.sql
  tools/tpch-tools/queries/q9.sql
  tools/tpch-tools/run-tpch-queries.sh
Labels: approved, reviewed, dev/1.0.1

#8505 [Bug][Vectorized] fix regexp_replace get wrong result on clang
  be/src/vec/functions/function_regexp.cpp
Labels: approved, reviewed, dev/1.0.1

#8538 [doc]Update data-partition.md
  docs/zh-CN/getting-started/data-partition.md
  docs/zh-CN/getting-started/hit-the-rollup.md
Labels: kind/docs, dev/backlog

#8546 [doc] change http to https in download page
  docs/en/downloads/downloads.md
  docs/zh-CN/downloads/downloads.md
Labels: kind/docs, approved, reviewed, dev/backlog

#8536 [Bug] fix bug in WindowFunctionLastData::data, it keeps the first dat…
  be/src/vec/aggregate_functions/aggregate_function_window.h
Labels: kind/fix, approved, reviewed, dev/1.0.0-deprecated, dev/1.0.1

#8547 [UT] fix some fe ut failed
  fe/fe-core/src/main/java/org/apache/doris/external/elasticsearch/EsShardPartitions.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/TempPartitionTest.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/TruncateTableTest.java
Labels: kind/test, approved, reviewed, dev/backlog

#8486 [Refactor] remove tablet instances since tablet id is unique between base tablet and new schema change tablet
  be/src/olap/schema_change.cpp
  be/src/olap/tablet.h
  be/src/olap/tablet_manager.cpp
  be/src/olap/tablet_manager.h
Labels: approved, reviewed, dev/backlog

#8554 [chore] fix compile error when use clang as compiler and be ut problem
  be/src/vec/columns/column_dictionary.h
  be/test/olap/tablet_mgr_test.cpp
Labels: approved, reviewed, dev/backlog

#8556 [feature-wip][array-type] Fix compilation error.
  be/test/runtime/array_test.cpp
Labels: area/array-type

#8544 [chore] Separate debugging information from BE binaries
  be/src/service/CMakeLists.txt
  be/src/tools/CMakeLists.txt
  build.sh
  docs/en/installing/install-deploy.md
  docs/zh-CN/installing/install-deploy.md
Labels: kind/chore, approved, reviewed, dev/1.0.0-deprecated, dev/1.0.1

#8569 [fix](lru_cache) fix heap-use-after-free problem for lru cache
  be/src/olap/lru_cache.cpp
Labels: kind/fix, approved, reviewed, dev/backlog

#8545 Improve sig handler
  .licenserc.yaml
  .rat-excludes
  LICENSE.txt
  be/CMakeLists.txt
  be/src/common/daemon.cpp
  be/src/common/logconfig.cpp
  be/src/common/signal_handler.h
  be/src/service/doris_main.cpp
  be/src/util/logging.h
  build.sh
  thirdparty/CHANGELOG.md
  thirdparty/build-thirdparty.sh
  thirdparty/vars.sh
Labels: approved, reviewed

#8557 Replace null with empty String in master proxy result set.
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowResultSet.java
Labels: approved, reviewed, dev/1.0.1

#8564 update star-schema-benchmark.md
  docs/en/benchmark/star-schema-benchmark.md
Labels: approved, reviewed, dev/backlog

#8565 update star-schema-benchmark.md
  docs/zh-CN/benchmark/star-schema-benchmark.md
Labels: approved, reviewed, dev/backlog

#8568 [fix] Wrong conf be used for Filesytem in S3Storage
  fe/fe-core/src/main/java/org/apache/doris/backup/S3Storage.java
Labels: kind/fix, approved, reviewed, dev/1.0.1

#8575 [feature-wip](array-type) Create table with nested array type.
  be/src/olap/tablet_meta.cpp
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateTableStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/TypeDef.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/ArrayType.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Column.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Type.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/CreateTableTest.java
Labels: kind/feature, approved, area/array-type, reviewed, dev/backlog

#8582 [feature-wip][array-type] Support ArrayLiteral in SQL.
  be/src/olap/column_vector.cpp
  be/src/olap/rowset/segment_v2/column_reader.cpp
  be/src/olap/rowset/segment_v2/column_reader.h
  be/src/olap/rowset/segment_v2/column_writer.cpp
  be/src/olap/rowset/segment_v2/column_writer.h
  be/src/runtime/collection_value.cpp
  be/src/runtime/mysql_result_writer.cpp
  be/src/runtime/raw_value.cpp
  be/src/runtime/row_batch.cpp
  be/src/runtime/tuple.cpp
  be/test/olap/rowset/segment_v2/column_reader_writer_test.cpp
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/ArrayLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateTableStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/Expr.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/ArrayType.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Column.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Type.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ColumnDefTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/InsertArrayStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/UtFrameUtils.java
Labels: kind/feature, area/array-type, dev/backlog

#8584 [feature-wip](array-type)support select ARRAY data type on vectorized…
  be/src/olap/column_vector.h
  be/src/olap/field.h
  be/src/olap/row_block2.cpp
  be/src/olap/row_block2.h
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/olap/schema.cpp
  be/src/olap/schema.h
  be/src/olap/tablet_schema.cpp
  be/src/runtime/descriptors.cpp
  be/src/runtime/descriptors.h
  be/src/runtime/types.h
  be/src/vec/CMakeLists.txt
  be/src/vec/columns/column_array.cpp
  be/src/vec/columns/column_array.h
  be/src/vec/core/block.cpp
  be/src/vec/core/types.h
  be/src/vec/data_types/data_type.cpp
  be/src/vec/data_types/data_type.h
  be/src/vec/data_types/data_type_array.cpp
  be/src/vec/data_types/data_type_array.h
  be/src/vec/data_types/data_type_factory.cpp
  be/src/vec/data_types/data_type_factory.hpp
  be/src/vec/data_types/data_type_number_base.h
  be/src/vec/exprs/vectorized_agg_fn.cpp
  be/src/vec/exprs/vexpr.cpp
  be/src/vec/olap/vgeneric_iterators.cpp
  be/src/vec/sink/mysql_result_writer.cpp
  be/src/vec/sink/mysql_result_writer.h
  be/test/vec/core/CMakeLists.txt
  be/test/vec/core/column_array_test.cpp
  be/test/vec/exec/vgeneric_iterators_test.cpp
Labels: kind/feature, area/array-type, dev/backlog
