Repository apache/doris, pull requests merged in 2022-07, with the labels that each got.

#10327 [Enhancement] modify comment " to ' compat mysql.
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Column.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/CreateTableAsSelectStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ShowCreateTableStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/TestWithFeService.java
Labels: approved, reviewed

#10517 [fix] (mem tracker) Fix BE hangs at startup, stuck in tcmalloc hook call ExecEnv::GetInstance()
  be/src/runtime/exec_env.h
  be/src/runtime/tcmalloc_hook.h
  be/src/runtime/thread_context.h
  be/src/runtime/thread_mem_tracker_mgr.h
Labels: approved, area/vectorization, reviewed

#10471 [enhancement](proc) Support showing more details in show proc "/dbs"
  fe/fe-core/src/main/java/org/apache/doris/catalog/Database.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/DbsProcDir.java
  fe/fe-core/src/test/java/org/apache/doris/common/proc/DbsProcDirTest.java
Labels: kind/improvement, approved, reviewed, area/proc, dev/backlog

#10522 [fix] block dump_one_line assert error
  be/src/vec/core/block.cpp
Labels: approved, area/vectorization, reviewed

#10518 [Chore][Vectorized] remove unused collator
  be/src/vec/CMakeLists.txt
  be/src/vec/columns/collator.cpp
  be/src/vec/columns/collator.h
  be/src/vec/columns/column_array.cpp
  be/src/vec/columns/column_string.cpp
  be/src/vec/columns/column_string.h
  be/src/vec/core/sort_block.cpp
  be/src/vec/core/sort_cursor.h
  be/src/vec/core/sort_description.h
Labels: area/vectorization

#10514 [fix] (mem tracker) Fix cancel query deadlock during add_block, and query pool tracker error cancel query
  be/src/runtime/data_stream_recvr.cc
  be/src/runtime/exec_env_init.cpp
  be/src/vec/runtime/vdata_stream_recvr.cpp
Labels: approved, area/vectorization, reviewed

#10500 [docs](array-type)Fix keywords in array functions' help documents
  docs/en/docs/sql-manual/sql-functions/array-functions/array_avg.md
  docs/en/docs/sql-manual/sql-functions/array-functions/array_contains.md
  docs/en/docs/sql-manual/sql-functions/array-functions/array_max.md
  docs/en/docs/sql-manual/sql-functions/array-functions/array_min.md
  docs/en/docs/sql-manual/sql-functions/array-functions/array_position.md
  docs/en/docs/sql-manual/sql-functions/array-functions/array_product.md
  docs/en/docs/sql-manual/sql-functions/array-functions/array_sum.md
  docs/zh-CN/docs/sql-manual/sql-functions/array-functions/array_avg.md
  docs/zh-CN/docs/sql-manual/sql-functions/array-functions/array_contains.md
  docs/zh-CN/docs/sql-manual/sql-functions/array-functions/array_max.md
  docs/zh-CN/docs/sql-manual/sql-functions/array-functions/array_min.md
  docs/zh-CN/docs/sql-manual/sql-functions/array-functions/array_position.md
  docs/zh-CN/docs/sql-manual/sql-functions/array-functions/array_product.md
  docs/zh-CN/docs/sql-manual/sql-functions/array-functions/array_sum.md
Labels: kind/docs, approved, reviewed

#10528 [Doc]Change the download url for the binary package #10527
  docs/en/docs/get-starting/get-starting.md
Labels: kind/docs

#10429 [Bugfix](fe) fix add follower failed, conflict socket .
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/ha/BDBHA.java
Labels: approved, reviewed

#10499 [Feature](neireids) Add support of ProjectNode in PlanTranslator
  fe/fe-core/src/main/java/org/apache/doris/analysis/AggregateInfo.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/NereidsPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/operators/plans/physical/PhysicalScan.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/TreeNode.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/translator/ExpressionTranslator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/translator/PhysicalPlanTranslator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/translator/PlanTranslatorContext.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OriginalPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PlanFragment.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PlanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/Planner.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SortNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
Labels: area/planner, area/nereids

#10501 [fix](Insert) fix 5 concurrent "insert...select..." OOM
  be/src/common/config.h
  be/src/exec/tablet_sink.h
  be/src/olap/delta_writer.h
  be/src/runtime/tablets_channel.cpp
  be/src/vec/core/block.h
  be/src/vec/exec/volap_scan_node.cpp
  be/src/vec/exec/volap_scanner.cpp
  be/src/vec/sink/vtablet_sink.cpp
  be/src/vec/sink/vtablet_sink.h
Labels: approved, area/vectorization, reviewed

#10526 [style](*): keep line break.
  build-support/IntelliJ-code-format.xml
Labels: reviewed

#10462 [Enhancement](Nereids) push down predicate through join
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/Job.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/rewrite/RewriteTopDownJob.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/memo/Memo.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/OrderKey.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rewrite/ExpressionRuleExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/logical/PushPredicateThroughJoin.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/Add.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/CompoundPredicate.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/IterationVisitor.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/Literal.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/SlotExtractor.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/ExpressionUtils.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/logical/PushDownPredicateTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/ssb/SSBUtils.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/util/ExpressionUtilsTest.java
Labels: area/nereids

#10347 [style](*): fix declarationOrder error by rearrange code
  fe/fe-core/src/main/java/org/apache/doris/alter/AlterHandler.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/AddColumnsClause.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/AddPartitionClause.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/AddRollupClause.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/AdminShowTabletStorageFormatStmt.java
Labels: area/planner, approved, reviewed

#10438 [Enhancement] remove unused codes for enable_lateral_view
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
Labels: approved, reviewed

#10537 [hotfix](dev-1.0.1) fall back to non vec engine for some outer join cases
  fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/TableRef.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
Labels: kind/fix, approved, area/vectorization, reviewed, dev/1.0.1

#10558 [website](doc)add package-lock.json to resolve docs build failure
  .github/workflows/build-extension.yml
  .gitignore
  .licenserc.yaml
  docs/package-lock.json
Labels: kind/docs, approved, reviewed

#10521 [feature-wip](multi-catalog) end to end to support multi-catalog
  fe/fe-core/src/main/java/org/apache/doris/analysis/AdminCancelRepairTableStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/AdminCompactTableStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/AdminRepairTableStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/AdminShowReplicaDistributionStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/AdminShowReplicaStatusStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/DescribeStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/FromClause.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SlotDescriptor.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SlotRef.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/DataSourceMgr.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalDataSource.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/HMSExternalDataSource.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/MetaInfoAction.java
  fe/fe-core/src/main/java/org/apache/doris/planner/HashJoinNode.java
  fe/fe-core/src/main/java/org/apache/doris/policy/Policy.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContext.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/mvrewrite/CountDistinctToBitmap.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/mvrewrite/CountFieldToSum.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/mvrewrite/HLLHashToSlotRefRule.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/mvrewrite/NDVToHll.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/mvrewrite/ToBitmapToSlotRefRule.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/AccessTestUtil.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/VirtualSlotRefTest.java
  fe/fe-core/src/test/java/org/apache/doris/http/DorisHttpTestCase.java
  fe/fe-core/src/test/java/org/apache/doris/qe/ConnectProcessorTest.java
  fe/fe-core/src/test/java/org/apache/doris/qe/PartitionCacheTest.java
  fe/fe-core/src/test/java/org/apache/doris/qe/ShowExecutorTest.java
Labels: area/planner, reviewed, area/multi-catalog

#10519 [fix](planner)infer predicate generate infered predicate using wrong information from another scope
  fe/fe-core/src/main/java/org/apache/doris/analysis/SlotRef.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/InferFiltersRule.java
  fe/fe-core/src/test/java/org/apache/doris/rewrite/InferFiltersRuleTest.java
Labels: kind/fix, area/planner, approved, reviewed, dev/1.0.1

#10562 [fix](fe-ut) fix ut compile bug
  fe/fe-core/src/test/java/org/apache/doris/nereids/util/ExpressionUtilsTest.java
Labels: kind/fix, kind/test, approved, reviewed

#10555 [hotfix][feature](dev-1.0.1) support `max_by` and `min_by` on row-based engine
  be/src/exprs/aggregate_functions.cpp
  be/src/exprs/aggregate_functions.h
  fe/fe-core/src/main/java/org/apache/doris/analysis/AggregateInfo.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionSet.java
Labels: approved, reviewed, dev/1.0.1

#10571 [fix]fix agg_memleak
  be/src/vec/exec/vaggregation_node.cpp
Labels: approved, area/vectorization, reviewed

#10464 [Bug] fix create table like when having sequence column
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  regression-test/data/data_model/unique/test_unique_table_like.out
  regression-test/suites/data_model/unique/test_unique_table_like.groovy
Labels: kind/test, approved, reviewed

#10476 [fix] fix api of table schema in http v2
  fe/fe-core/src/main/java/org/apache/doris/httpv2/restv2/MetaInfoActionV2.java
Labels: approved, area/httpv2, reviewed

#10529 [feature-wip](unique-key-merge-on-write) add primary key index
  be/src/olap/CMakeLists.txt
  be/src/olap/primary_key_index.cpp
  be/src/olap/primary_key_index.h
  be/test/CMakeLists.txt
  be/test/olap/primary_key_index_test.cpp
Labels: approved, reviewed

#10569 [Compile] turn off java-udf by default when compliling in parallel
  build.sh
Labels: approved, reviewed

#10567 [BUG] fix bug in literal `debug_string` when literal is null
  be/src/vec/exprs/vliteral.cpp
Labels: approved, area/vectorization, reviewed

#10557 [chore][community](github)Change 'max-old-space-size' to 8192
  .github/workflows/build-extension.yml
Labels: approved, reviewed

#10380 [Enhancement][Storage] refactor Comparison Predicates
  be/src/olap/CMakeLists.txt
  be/src/olap/block_column_predicate.cpp
  be/src/olap/bloom_filter_predicate.h
  be/src/olap/column_predicate.h
  be/src/olap/comparison_predicate.cpp
  be/src/olap/comparison_predicate.h
  be/src/olap/in_list_predicate.h
  be/src/olap/null_predicate.cpp
  be/src/olap/null_predicate.h
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/vec/columns/column.h
  be/src/vec/columns/column_dictionary.h
  be/src/vec/columns/column_nullable.h
Labels: area/vectorization, reviewed

#10574 [community] modify release doc to remove incubator
  docs/en/community/release-and-verify/release-complete.md
  docs/en/community/release-and-verify/release-doris-connectors.md
  docs/en/community/release-and-verify/release-prepare.md
  docs/zh-CN/community/release-and-verify/release-complete.md
  docs/zh-CN/community/release-and-verify/release-doris-connectors.md
  docs/zh-CN/community/release-and-verify/release-prepare.md
Labels: kind/community, kind/docs, approved, reviewed

#10564 [improvement]No need to memset flags for vectorization predicates
  be/src/olap/block_column_predicate.cpp
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
Labels: approved, reviewed

#10554 [fix](routine-load) Fix that routine load cannot work with old kafka version
  be/src/common/config.h
  be/src/runtime/routine_load/data_consumer.cpp
  docs/en/docs/admin-manual/config/be-config.md
  docs/en/docs/data-operate/import/import-way/routine-load-manual.md
  docs/zh-CN/docs/admin-manual/config/be-config.md
  docs/zh-CN/docs/data-operate/import/import-way/routine-load-manual.md
Labels: kind/docs, approved, area/routine load, reviewed

#10570 [bug] fix the compile error
  be/src/exec/mysql_scan_node.cpp
  be/src/runtime/mysql_table_writer.cpp
Labels: approved, reviewed

#10394 [Bug][docs] Fix wrong links in README.md
  README.md
Labels: kind/docs, approved, reviewed

#10573 [fix](multi-catalog) fix the core dump on hms table
  be/src/exec/text_converter.h
  be/src/exec/text_converter.hpp
  be/src/vec/exec/file_scanner.cpp
  be/src/vec/exec/file_text_scanner.cpp
  fe/fe-core/src/main/java/org/apache/doris/catalog/HiveMetaStoreClientHelper.java
Labels: approved, area/vectorization, reviewed, area/multi-catalog

#10523 [feature-wip](multi-catalog) Modify the persist method about data source
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowCatalogStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/HiveTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/external/HMSExternalDatabase.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/external/HMSExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/CatalogFactory.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/CatalogLog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/DataSourceMgr.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/DataSourceProperty.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/EsExternalDataSource.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/HMSExternalDataSource.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalDataSource.java
  fe/fe-core/src/main/java/org/apache/doris/persist/gson/GsonUtils.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/ExternalHiveScanProvider.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContext.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ShowCatalogStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/SwitchStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/DatasourceMgrTest.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/TestWithFeService.java
Labels: kind/fix, area/planner, area/metadata, area/multi-catalog

#10582 [Bug][Storage] fix default value get wrong result because no implement read_by_rowids
  be/src/olap/rowset/segment_v2/column_reader.cpp
  be/src/olap/rowset/segment_v2/column_reader.h
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/olap/rowset/segment_v2/segment_iterator.h
Labels: reviewed

#10591 [bugfix] fix coredump of left anti join
  be/src/vec/exec/join/vhash_join_node.cpp
Labels: approved, area/vectorization, reviewed, dev/1.1.1

#10578 [fix][be] Delete uncivilized comments.
  be/src/vec/runtime/vdatetime_value.cpp
Labels: approved, area/vectorization, reviewed

#10592 [multi-catalog] (information schema) Add catalog name to information_schema table columns.
  be/src/exec/schema_scanner/schema_columns_scanner.cpp
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  gensrc/thrift/FrontendService.thrift
Labels: approved, reviewed, area/multi-catalog

#10559 [docs] add quick compaction configs
  docs/en/docs/admin-manual/config/be-config.md
  docs/zh-CN/docs/admin-manual/config/be-config.md
Labels: kind/docs, reviewed

#10588 [fix] [docs] Fixed Use examples in sequence-column-manual.md file.
  docs/en/docs/data-operate/update-delete/sequence-column-manual.md
  docs/zh-CN/docs/data-operate/update-delete/sequence-column-manual.md
Labels: kind/docs, approved, reviewed

#10325 [enhancement](Nereids): replace the header `Lists` and `Precondition`
  fe/fe-core/src/main/java/org/apache/doris/analysis/AddColumnsClause.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/ListPartitionItem.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/ReplicaAllocation.java
  fe/fe-core/src/main/java/org/apache/doris/common/profile/MultiProfileTreeBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/common/profile/PlanTreeBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/SetConfigAction.java
  fe/fe-core/src/main/java/org/apache/doris/journal/bdbje/BDBDebugger.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/analyzer/UnboundRelation.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/PlanTranslatorContext.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/memo/GroupExpression.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/operators/plans/physical/PhysicalOlapScan.java
  fe/fe-core/src/main/java/org/apache/doris/persist/ColocatePersistInfo.java
  fe/fe-core/src/main/java/org/apache/doris/persist/meta/PersistMetaModules.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/CaseExprTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/InPredicateTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/UpdateStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/DynamicPartitionTableTest.java
  fe/fe-core/src/test/java/org/apache/doris/common/util/DynamicPartitionUtilTest.java
  fe/fe-core/src/test/java/org/apache/doris/ldap/LdapClientTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/update/UpdateManagerTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/update/UpdateStmtExecutorTest.java
  fe/fe-core/src/test/java/org/apache/doris/persist/BatchRemoveTransactionOperationTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/UpdatePlannerTest.java
  fe/fe-core/src/test/java/org/apache/doris/rewrite/ExtractCommonFactorsRuleTest.java
Labels: area/planner, area/nereids

#10597 [Doc] Add idea provided error doc.
  docs/.vuepress/public/images/idea_options.png
  docs/en/developer/developer-guide/fe-idea-dev.md
  docs/zh-CN/developer/developer-guide/fe-idea-dev.md
Labels: kind/docs, approved, reviewed

#10599 [chore] remove default REPOSITORY_URL link
  thirdparty/vars.sh
Labels: kind/chore, approved, reviewed

#10581 [Improvement] remove profile with poor readability
  be/src/exec/es_http_scan_node.cpp
  be/src/exec/olap_scan_node.cpp
  be/src/exec/scan_node.cpp
  be/src/exec/scan_node.h
  be/src/vec/exec/ves_http_scan_node.cpp
  be/src/vec/exec/volap_scan_node.cpp
Labels: approved, area/vectorization, reviewed

#10412 [Feature] [nereids] Agg rewrite rule of nereids optmizer
  fe/fe-core/src/main/java/org/apache/doris/nereids/operators/plans/logical/LogicalAggregate.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleSet.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/AggregateDisassemble.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/Alias.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/Expression.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/SlotReference.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/AggregateFunction.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/BoundFunction.java
Labels: approved, reviewed, area/nereids

#10596 [feature-wip](multi-catalog) support "show proc 'catalogs/'"
  fe/fe-core/src/main/java/org/apache/doris/analysis/DescribeStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Database.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/DatabaseIf.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/external/ExternalDatabase.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/external/HMSExternalDatabase.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/external/HMSExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/CatalogsProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/DbsProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/IndexInfoProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/ProcService.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/DataSourceIf.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/DataSourceMgr.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalDataSource.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/HMSExternalDataSource.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalDataSource.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/alter/AlterTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ShowCreateMaterializedViewStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/common/proc/DbsProcDirTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/routineload/RoutineLoadManagerTest.java
Labels: area/planner, area/multi-catalog

#10586 [enhancement] speed up week_of_year by pre_calc table
  be/src/vec/CMakeLists.txt
  be/src/vec/runtime/vdatetime_value.cpp
  be/src/vec/runtime/vdatetime_value.h
  be/src/vec/runtime/week_of_year.data
Labels: approved, area/vectorization, reviewed

#10614 [bugfix] fix bug of vhash join build
  be/src/vec/exec/join/vhash_join_node.cpp
  be/src/vec/exec/join/vhash_join_node.h
Labels: area/vectorization, dev/1.1.1

#10607 [Enhancement] remove duplicate codes in function_test_util.cpp
  be/test/vec/function/function_test_util.cpp
Labels: approved, reviewed

#10593 [fix](load) skip empty orc file
  be/src/exec/orc_scanner.cpp
  be/src/vec/exec/vorc_scanner.cpp
Labels: approved, area/vectorization, reviewed

#10623 [Improvement] remove `beHttpAddress` in regression test
  regression-test/conf/regression-conf.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/Config.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/ConfigOptions.groovy
Labels: kind/test, approved, reviewed

#10547 [multi-catalog]Fix hive partiton prune in hive and hudi exteranl table.
  fe/fe-core/src/main/java/org/apache/doris/catalog/HiveMetaStoreClientHelper.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/HMSExternalDataSource.java
  fe/fe-core/src/main/java/org/apache/doris/planner/HiveScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/HudiScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/ExternalHiveScanProvider.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/HiveMetaStoreClientHelperTest.java
Labels: area/planner, approved, reviewed, area/multi-catalog

#10376 [fix](fe) when bdbje adding follower, master write op may failed.
  fe/fe-core/src/main/java/org/apache/doris/catalog/Catalog.java
  fe/fe-core/src/main/java/org/apache/doris/ha/BDBHA.java
  fe/fe-core/src/main/java/org/apache/doris/journal/bdbje/BDBJEJournal.java
  fe/fe-core/src/main/java/org/apache/doris/persist/EditLog.java
  fe/fe-core/src/main/java/org/apache/doris/system/Frontend.java
  fe/fe-core/src/main/java/org/apache/doris/system/HeartbeatMgr.java
Labels: reviewed

#10530 [fix](nereids) fix ut,check bound should be called recursively on the plan node
  fe/fe-core/src/test/java/org/apache/doris/nereids/AnalyzeSSBTest.java
Labels: area/nereids

#10498 [Fix] select nested type of string within type array should be wrappe…
  be/src/vec/sink/mysql_result_writer.cpp
Labels: approved, area/vectorization, reviewed

#10411 [feature](nereids) support like and regexp predicate
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisLexer.g4
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/NodeType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/Like.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/Regexp.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/StringRegexPredicate.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/ExpressionVisitor.java
Labels: area/nereids

#10551 [fix] Fix RewriteBinaryPredicatesRule which causes wrong query results in some cases.
  fe/fe-core/src/main/java/org/apache/doris/analysis/DecimalLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/IntLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/RewriteBinaryPredicatesRule.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/SelectStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/PlannerTest.java
  fe/fe-core/src/test/java/org/apache/doris/rewrite/RewriteBinaryPredicatesRuleTest.java
Labels: area/planner, approved, reviewed

#10626 [feature](script) add --grace option for stop_be.sh
  bin/stop_be.sh
Labels: approved, reviewed

#10621 [Improvement] remove redundant code of VOlapScanner
  be/src/vec/exec/volap_scanner.cpp
  be/src/vec/exec/volap_scanner.h
Labels: approved, area/vectorization, reviewed

#10496 [Bug][Vectorized] set strleft to always_nullable
  gensrc/script/doris_builtins_functions.py
Labels: approved, area/sql/function, reviewed

#10613 [docs] fix explode-json-array docs format
  docs/en/docs/sql-manual/sql-functions/table-functions/explode-json-array.md
  docs/zh-CN/docs/sql-manual/sql-functions/table-functions/explode-json-array.md
Labels: kind/docs

#10640 [BugFix](Array) fix DataTypeArray to_string use after free
  be/src/vec/data_types/data_type_array.cpp
Labels: approved, area/vectorization, reviewed

#10622 [fix] substr('', 1, 5) return empty string instead of null
  be/src/vec/functions/function_string.h
  be/test/vec/function/function_string_test.cpp
  regression-test/data/query/sql_functions/string_functions/test_string_function.out
Labels: approved, area/sql/function, area/vectorization, reviewed

#10651 [FIX] fix colocate join bug
  fe/fe-core/src/main/java/org/apache/doris/planner/DistributedPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/planner/HashJoinNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PlanNode.java
Labels: approved, reviewed, dev/1.0.1

#10654 [Enhancement] [vectorized] Runtime Filter support equivalent slot of outer join
  fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ExprSubstitutionMap.java
  fe/fe-core/src/main/java/org/apache/doris/planner/HashJoinNode.java
Labels: dev/1.0.1

#10645 [FIX] bottom line solution for vec outer join
  be/src/vec/exec/join/vhash_join_node.cpp
  be/src/vec/exec/vaggregation_node.cpp
  be/src/vec/exec/vaggregation_node.h
  be/src/vec/exec/vanalytic_eval_node.cpp
  be/src/vec/functions/function_case.h
  fe/fe-core/src/main/java/org/apache/doris/analysis/AggregateInfo.java
  fe/fe-core/src/main/java/org/apache/doris/planner/AggregationNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/Planner.java
  gensrc/thrift/PlanNodes.thrift
Labels: approved, reviewed, dev/1.0.1

#10658 [fix](Nereids): fix ut.
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/logical/AnalyzeUtils.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/logical/ColumnPruningTest.java
Labels: kind/fix, approved, reviewed, area/nereids

#10676 [hotfix](dev-1.0.1) Avoid VecNotImplementException for create view operation
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateViewStmt.java
Labels: dev/1.0.1

#10663 [fix][vectorized] Fix bug of VInPredicate on date type
  be/src/exprs/create_predicate_function.h
  be/src/runtime/primitive_type.h
  be/src/vec/functions/in.cpp
  regression-test/data/datatype/date/test_date_in_predicate.out
  regression-test/suites/datatype/date/test_date_in_predicate.groovy
Labels: kind/test, approved, area/sql/function, area/vectorization, reviewed, dev/1.0.1

#10611 [BUG] fix core dump caused by runtime filter
  be/src/vec/exec/volap_scan_node.cpp
  be/src/vec/exec/volap_scan_node.h
Labels: area/vectorization

#10630 [enhancement](nereids) add betweentocompound rewrite rule for ssb
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/AnalyzeRulesJob.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rewrite/ExpressionRuleExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rewrite/rules/BetweenToCompoundRule.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rewrite/rules/NormalizeBinaryPredicatesRule.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rewrite/rules/SimplifyNotExprRule.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/expression/rewrite/ExpressionRewriteTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/logical/PushDownPredicateTest.java
Labels: reviewed, area/nereids

#10606 [feature-wip](array-type) add agg function collect_list and collect_set
  be/src/vec/CMakeLists.txt
  be/src/vec/aggregate_functions/aggregate_function_collect.cpp
  be/src/vec/aggregate_functions/aggregate_function_collect.h
  be/src/vec/aggregate_functions/aggregate_function_simple_factory.cpp
  be/test/CMakeLists.txt
  be/test/vec/aggregate_functions/agg_collect_test.cpp
  docs/en/docs/sql-manual/sql-functions/aggregate-functions/collect_list.md
  docs/en/docs/sql-manual/sql-functions/aggregate-functions/collect_set.md
  docs/zh-CN/docs/sql-manual/sql-functions/aggregate-functions/collect_list.md
  docs/zh-CN/docs/sql-manual/sql-functions/aggregate-functions/collect_set.md
  fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionSet.java
  regression-test/data/query/sql_functions/aggregate_functions/test_aggregate_collect.out
  regression-test/suites/query/sql_functions/aggregate_functions/test_aggregate_collect.groovy
Labels: kind/docs, kind/test, approved, area/vectorization, reviewed

#10615 [Enhancement] Add column prune support for VOlapScanNode
  be/src/vec/exec/volap_scan_node.cpp
  be/src/vec/exec/volap_scan_node.h
  be/src/vec/exec/volap_scanner.cpp
  be/src/vec/exec/volap_scanner.h
  fe/fe-core/src/main/java/org/apache/doris/planner/HashJoinNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PlanNode.java
  fe/fe-core/src/test/java/org/apache/doris/planner/ProjectPlannerFunctionTest.java
  regression-test/data/performance/redundant_conjuncts.out
Labels: area/planner, area/vectorization

#10631 [refactor] add evaluate_and_vec() for ComparisonPredicateBase
  be/src/olap/column_predicate.h
  be/src/olap/comparison_predicate.h
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/olap/rowset/segment_v2/segment_iterator.h
Labels: reviewed

#10635 [Fix][multi-catalog]Fix coredump when reading the parquet file for multi-thread
  be/src/exec/arrow/arrow_reader.h
  be/src/exec/arrow/parquet_reader.cpp
  be/src/exec/arrow/parquet_reader.h
Labels: reviewed, area/multi-catalog

#10671 [docs] fix keywords in sql-functions help documents
  docs/en/docs/sql-manual/sql-functions/array-functions/arrays_overlap.md
  docs/en/docs/sql-manual/sql-functions/json-functions/json_array.md
  docs/en/docs/sql-manual/sql-functions/json-functions/json_object.md
  docs/en/docs/sql-manual/sql-functions/json-functions/json_quote.md
  docs/en/docs/sql-manual/sql-functions/table-functions/explode-bitmap.md
  docs/en/docs/sql-manual/sql-functions/table-functions/explode-json-array.md
  docs/en/docs/sql-manual/sql-functions/table-functions/explode-numbers.md
  docs/en/docs/sql-manual/sql-functions/table-functions/explode-split.md
  docs/zh-CN/docs/sql-manual/sql-functions/array-functions/arrays_overlap.md
  docs/zh-CN/docs/sql-manual/sql-functions/json-functions/json_array.md
  docs/zh-CN/docs/sql-manual/sql-functions/json-functions/json_object.md
  docs/zh-CN/docs/sql-manual/sql-functions/json-functions/json_quote.md
  docs/zh-CN/docs/sql-manual/sql-functions/table-functions/explode-bitmap.md
  docs/zh-CN/docs/sql-manual/sql-functions/table-functions/explode-json-array.md
  docs/zh-CN/docs/sql-manual/sql-functions/table-functions/explode-numbers.md
  docs/zh-CN/docs/sql-manual/sql-functions/table-functions/explode-split.md
Labels: kind/docs, approved, reviewed

#10670 [fix](optimizer) join reorder may cause column non-existence problem
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
Labels: area/planner, approved, reviewed, dev/1.0.1

#10684 [BugFix] Column datas doesn't match nullmap when vectorization load
  be/src/vec/olap/olap_data_convertor.cpp
  be/src/vec/olap/olap_data_convertor.h
Labels: approved, area/vectorization, reviewed

#10660 [Doc] add flink-doris-connector 1.1.0 doc
  docs/en/docs/ecosystem/flink-doris-connector.md
  docs/zh-CN/docs/ecosystem/flink-doris-connector.md
Labels: kind/docs, approved, reviewed

#10678 [feature](nereides) support sort translator
  fe/fe-core/src/main/java/org/apache/doris/analysis/SortInfo.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/NereidsPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/PhysicalPlanTranslator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/PlanTranslatorContext.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PlanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SortNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
Labels: area/planner, approved, reviewed, area/nereids

#10691 [refactor] update stop_be.sh to avoid error message
  bin/stop_be.sh
Labels: reviewed

#10577 [enhancement](regression-test) add real data path for regression test.
  regression-test/conf/regression-conf.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/Config.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/ConfigOptions.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/SuiteContext.groovy
Labels: kind/test, reviewed

#10655 [feature-wip](unique-key-merge-on-write) add interface for segment key bounds, DSIP-018[3/2]
  be/src/olap/rowset/rowset.h
  be/src/olap/rowset/rowset_meta.h
  gensrc/proto/olap_file.proto
Labels: approved, reviewed

#10512 [feature] (vectorization)parquet push down support
  be/src/common/config.h
  be/src/exec/CMakeLists.txt
  be/src/exec/arrow/arrow_reader.cpp
  be/src/exec/arrow/arrow_reader.h
  be/src/exec/arrow/orc_reader.cpp
  be/src/exec/arrow/orc_reader.h
  be/src/exec/arrow/parquet_reader.cpp
  be/src/exec/arrow/parquet_reader.h
  be/src/exec/arrow/parquet_row_group_reader.cpp
  be/src/exec/arrow/parquet_row_group_reader.h
  be/src/exec/base_scanner.cpp
  be/src/exec/base_scanner.h
  be/src/exec/broker_scan_node.cpp
  be/src/exec/parquet_scanner.cpp
  be/src/exprs/expr_context.h
  be/src/vec/exec/file_arrow_scanner.cpp
  be/src/vec/exec/file_scan_node.cpp
  be/src/vec/exec/file_scanner.cpp
  be/src/vec/exec/file_scanner.h
  be/src/vec/exec/varrow_scanner.cpp
  be/src/vec/exec/varrow_scanner.h
  be/src/vec/exec/vbroker_scan_node.cpp
  be/src/vec/exec/vparquet_scanner.cpp
  be/test/exec/parquet_scanner_test.cpp
Labels: area/vectorization, reviewed, area/multi-catalog

#10700 [improvement]pre-serialize aggregation keys
  be/src/vec/columns/column.h
  be/src/vec/columns/column_const.h
  be/src/vec/columns/column_nullable.cpp
  be/src/vec/columns/column_nullable.h
  be/src/vec/columns/column_string.cpp
  be/src/vec/columns/column_string.h
  be/src/vec/columns/column_vector.cpp
  be/src/vec/columns/column_vector.h
  be/src/vec/common/columns_hashing.h
  be/src/vec/exec/vaggregation_node.cpp
  be/src/vec/exec/vaggregation_node.h
Labels: approved, area/vectorization, reviewed

#10698 [Doc]broker load rpc timeout problem FQA
  docs/en/docs/data-operate/import/import-way/broker-load-manual.md
  docs/en/docs/faq/data-faq.md
  docs/zh-CN/docs/data-operate/import/import-way/broker-load-manual.md
  docs/zh-CN/docs/faq/data-faq.md
Labels: kind/docs, approved, reviewed

#10709 [BUG] fix DCHECK failed for vectorized InPredicate
  be/src/vec/exprs/vin_predicate.cpp
  be/src/vec/functions/in.cpp
Labels: area/sql/function, area/vectorization, reviewed

#10695 [BUG](datev2) fix bloom filter for datev2 and remove redundant code
  be/src/olap/bloom_filter_predicate.cpp
  be/src/olap/rowset/segment_v2/column_reader.cpp
Labels: approved, area/vectorization, reviewed

#10692 [refactor]broker rpc timeout configuration parameterization
  docs/en/docs/admin-manual/config/fe-config.md
  docs/zh-CN/docs/admin-manual/config/fe-config.md
  fe/fe-core/src/main/java/org/apache/doris/common/ClientPool.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
Labels: kind/docs, approved, reviewed, dev/1.0.1

#10713 [chore] Update .gitignore to ignore generated files by be ut
  .gitignore
Labels: approved, reviewed

#10656 [ut](array-type) add some case for array type in block_test
  be/test/vec/core/block_test.cpp
Labels: kind/test, approved, area/array-type, reviewed

#10620 [Enhancement][multi-catalog]Impl parallel for file scanner to improve the scanner performance
  be/src/vec/exec/file_arrow_scanner.cpp
  be/src/vec/exec/file_scan_node.cpp
  be/src/vec/exec/file_scan_node.h
  fe/fe-core/src/main/java/org/apache/doris/catalog/external/HMSExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/ExternalFileScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/ExternalHudiScanProvider.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
Labels: area/planner, approved, area/vectorization, reviewed, area/multi-catalog

#10467 [Bug][Vectorized] Support array function in where pre in volap_scan_node
  be/src/exprs/array_functions.cpp
  be/src/exprs/array_functions.h
  fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionSet.java
Labels: reviewed

#10716 [BUG] runtime filter core dump
  be/src/vec/exec/volap_scan_node.cpp
Labels: area/vectorization

#10710 [improve](planner): split output expr to multiple line.
  fe/fe-core/src/main/java/org/apache/doris/planner/PlanFragment.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/StmtRewriterTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/TableFunctionPlanTest.java
  regression-test/data/performance/redundant_conjuncts.out
  regression-test/suites/demo/explain_action.groovy
Labels: kind/api-change, area/planner, kind/test, reviewed

#10448 [Load][Vectorized] opt the mem use of aggregate function in load to speed up
  be/src/olap/memtable.cpp
  be/src/olap/memtable.h
Labels: approved, reviewed

#10447 [Load][Vectorized] load opt code by change `replace` and `replace_if_not_null` do not copy value
  be/src/vec/aggregate_functions/aggregate_function_reader.cpp
  be/src/vec/aggregate_functions/aggregate_function_window.h
Labels: approved, area/vectorization, reviewed

#10738 [Bug] CTAS varchar length lost
  docs/en/docs/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-TABLE-AS-SELECT.md
  docs/zh-CN/docs/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-TABLE-AS-SELECT.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateTableAsSelectStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/ScalarType.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalDataSource.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/CreateTableAsSelectStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/TestWithFeService.java
Labels: kind/docs, area/planner

#10701 [refactor](predicate) refactor predicates in scan node
  be/src/exec/olap_common.cpp
  be/src/exec/olap_common.h
  be/src/exec/olap_scan_node.cpp
  be/src/exec/olap_scan_node.h
  be/src/runtime/primitive_type.h
  be/src/vec/exec/volap_scan_node.cpp
  be/src/vec/exec/volap_scan_node.h
  be/test/exec/olap_common_test.cpp
Labels: approved, area/vectorization, reviewed

#10747 [docs]fix typo in substring docs
  docs/en/docs/sql-manual/sql-functions/string-functions/substring.md
  docs/zh-CN/docs/sql-manual/sql-functions/string-functions/substring.md
Labels: kind/docs

#10542 [Enhancement] support compile with jemalloc
  be/CMakeLists.txt
  be/src/common/daemon.cpp
  be/src/http/action/pprof_actions.cpp
  be/src/http/default_path_handlers.cpp
  be/src/runtime/bufferpool/system_allocator.cc
  be/src/service/doris_main.cpp
  be/src/util/debug/leakcheck_disabler.h
  build.sh
  run-be-ut.sh
Labels: approved, reviewed

#10734 Revert "[Enhancement] Add column prune support for VOlapScanNode
  be/src/vec/exec/volap_scan_node.cpp
  be/src/vec/exec/volap_scan_node.h
  be/src/vec/exec/volap_scanner.cpp
  be/src/vec/exec/volap_scanner.h
  fe/fe-core/src/main/java/org/apache/doris/planner/HashJoinNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PlanNode.java
  fe/fe-core/src/test/java/org/apache/doris/planner/ProjectPlannerFunctionTest.java
  regression-test/data/performance/redundant_conjuncts.out
Labels: area/planner, area/vectorization, reviewed

#10719 [enhancement](alter) Make alter job more robust by ignoring some task failure
  docs/en/docs/admin-manual/config/fe-config.md
  docs/zh-CN/docs/admin-manual/config/fe-config.md
  fe/fe-core/src/main/java/org/apache/doris/alter/RollupJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/common/Config.java
Labels: kind/docs, approved, area/alter, reviewed

#10730 [TLP] how-to-contribute remove incubator
  docs/.vuepress/public/images/create-pr.png
  docs/.vuepress/public/images/create-pr3.png
  docs/.vuepress/public/images/fork-repo.png
  docs/.vuepress/public/images/new-pr.png
  docs/en/community/how-to-contribute/pull-request.md
  docs/zh-CN/community/how-to-contribute/pull-request.md
Labels: kind/docs, approved, reviewed

#10740 [improvement](parquet-reader) Add some profile for parquet reader
  be/src/exec/arrow/parquet_row_group_reader.cpp
  be/src/io/buffered_reader.cpp
  be/src/vec/exec/file_arrow_scanner.cpp
  be/src/vec/exec/file_arrow_scanner.h
  be/src/vec/exec/file_scanner.cpp
  be/src/vec/exec/file_scanner.h
  be/src/vec/exec/file_text_scanner.cpp
  be/src/vec/exec/file_text_scanner.h
  fe/fe-core/src/main/java/org/apache/doris/planner/external/ExternalFileScanNode.java
Labels: area/planner, area/vectorization, area/multi-catalog

#10735 [BUG] Wrong result when build size is beyond IN runtime filter threshold
  be/src/exprs/runtime_filter.cpp
  be/src/vec/exec/volap_scan_node.cpp
Labels: area/vectorization, reviewed

#10751 [fix]ColumnDecimal missed some interfaces about pre-serialization
  be/src/vec/columns/column_decimal.cpp
  be/src/vec/columns/column_decimal.h
Labels: approved, area/vectorization, reviewed

#10746 [Doc]Update flink / spark connector download url
  docs/en/downloads/downloads.md
  docs/zh-CN/downloads/downloads.md
Labels: kind/docs

#10732 [fix] remove unused private field _profile
  be/src/exec/arrow/parquet_reader.cpp
  be/src/exec/arrow/parquet_reader.h
  be/src/exec/arrow/parquet_row_group_reader.cpp
  be/src/exec/arrow/parquet_row_group_reader.h
  be/src/exec/parquet_scanner.cpp
  be/src/vec/exec/file_arrow_scanner.cpp
  be/src/vec/exec/vparquet_scanner.cpp
Labels: area/vectorization, reviewed

#10767 [feature-wip](datev2) add FE functions and fix some bugs
  fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateFunctionStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/DateLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/OutFileClause.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowPartitionsStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/TimestampArithmeticExpr.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/HiveMetaStoreClientHelper.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/PrimitiveType.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/SchemaTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Type.java
  fe/fe-core/src/main/java/org/apache/doris/external/hive/util/HiveUtil.java
  fe/fe-core/src/main/java/org/apache/doris/external/iceberg/util/TypeToDorisType.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/FEFunctions.java
  gensrc/proto/types.proto
Labels: area/planner, area/sql/function

#10769 [improvement]Division of integer is too slow
  be/src/vec/functions/int_div.h
Labels: approved, area/sql/function, area/vectorization, reviewed

#10772 fix Level1Iterator memory leak
  be/src/vec/olap/vcollect_iterator.cpp
Labels: approved, area/vectorization, reviewed

#10756 [Fix](distrubution) DISTRIBUTED BY RANDOM BUCKETS not random
  be/src/exec/tablet_info.cpp
Labels: kind/fix, area/load

#10724 [enhancement][MultiCatalog]Add strong checker for hms table
  fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/external/ExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/external/HMSExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/common/ErrorCode.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/BrokerUtil.java
Labels: area/planner, area/multi-catalog

#10442 optimize substr performance and fix ASAN global buffer overflow
  be/src/exprs/like_predicate.h
  be/src/runtime/string_search.hpp
  be/src/vec/common/string_searcher.h
  be/src/vec/common/volnitsky.h
  be/src/vec/functions/like.cpp
  be/src/vec/functions/like.h
Labels: area/sql/function, area/vectorization, reviewed

#10777 [fix] fix to_string use memory after free
  be/src/vec/data_types/data_type_nullable.cpp
  be/src/vec/data_types/data_type_string.cpp
Labels: approved, area/vectorization, reviewed, dev/1.1.1

#10388 [feature-wip] (array-type) add the array_distinct function
  be/src/vec/CMakeLists.txt
  be/src/vec/functions/array/function_array_distinct.cpp
  be/src/vec/functions/array/function_array_distinct.h
  be/src/vec/functions/array/function_array_register.cpp
  docs/en/docs/sql-manual/sql-functions/array-functions/array_distinct.md
  docs/zh-CN/docs/sql-manual/sql-functions/array-functions/array_distinct.md
  gensrc/script/doris_builtins_functions.py
  regression-test/data/query/sql_functions/array_functions/test_array_functions.out
  regression-test/suites/query/sql_functions/array_functions/test_array_functions.groovy
Labels: kind/docs, kind/test, approved, area/sql/function, area/array-type, area/vectorization, reviewed

#10743 [enhancement] Refactor to improve the usability of MemTracker
  be/src/runtime/memory/mem_tracker_base.cpp
  be/src/runtime/memory/mem_tracker_base.h
  be/src/runtime/memory/mem_tracker_limiter.cpp
  be/src/runtime/memory/mem_tracker_limiter.h
  be/src/runtime/memory/mem_tracker_observe.cpp
  be/src/runtime/memory/mem_tracker_observe.h
  be/src/runtime/memory/mem_tracker_task_pool.cpp
  be/src/runtime/memory/mem_tracker_task_pool.h
Labels: kind/docs, area/vectorization

#10768 [enhancement](be) be asan add asan_suppr.conf to ignore known leak.
  .gitignore
  be/CMakeLists.txt
  bin/start_be.sh
  conf/asan_suppr.conf
Labels: reviewed

#10790 [enhancement](show data skew) Support show avg_row_count for data skew of one table
  docs/.vuepress/sidebar/en/docs.js
  docs/.vuepress/sidebar/zh-CN/docs.js
  docs/en/docs/sql-manual/sql-reference/Show-Statements/SHOW-DATA-SKEW.md
  docs/zh-CN/docs/sql-manual/sql-reference/Show-Statements/SHOW-DATA-SKEW.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowDataSkewStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/MetadataViewer.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Tablet.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/TabletHealthProcDir.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/AdminShowReplicaTest.java
Labels: kind/docs, area/planner

#10785 [Bug][Function] fix DCHECK fail on is_null_pred/is_not_null_pred
  fe/fe-core/src/main/java/org/apache/doris/analysis/IsNullPredicate.java
Labels: area/planner, approved, reviewed

#10775 [Bug][Memtable] fix core dump on int128 because not aligned by 16 byte
  be/src/olap/memtable.cpp
  be/src/olap/memtable.h
  be/src/runtime/mem_pool.h
Labels: approved, reviewed, dev/1.1.1

#10773 [doc]Add common errors to broker load import documentation
  docs/en/docs/data-operate/import/import-way/broker-load-manual.md
  docs/zh-CN/docs/data-operate/import/import-way/broker-load-manual.md
Labels: kind/docs, approved, reviewed

#10736 [Bug] fix datetimev2 decimal error.
  fe/fe-core/src/main/java/org/apache/doris/analysis/DateLiteral.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/DateLiteralTest.java
Labels: area/planner, approved, reviewed

#10686 [regression] update test framework and fix cases
  regression-test/conf/regression-conf.groovy
  regression-test/data/index/test_bitmap_index.out
  regression-test/data/performance/redundant_conjuncts.out
  regression-test/framework/src/main/groovy/org/apache/doris/regression/Config.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/action/StreamLoadAction.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/SuiteContext.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/SuiteScript.groovy
  regression-test/suites/index/test_index.groovy
  regression-test/suites/query/aggregate/aggregate.groovy
  regression-test/suites/query/sql_functions/aggregate_functions/test_aggregate_all_functions.groovy
  regression-test/suites/query/sql_functions/conditional_functions/test_nullif.groovy
  regression-test/suites/sql_block_rule/test_sql_block_rule.groovy
Labels: kind/test, approved, reviewed

#10798 [bugfix] fix bug of ComparisonPredicate for nullable column
  be/src/olap/comparison_predicate.h
Labels: approved, reviewed

#10549 [Bug] Fix array functions arguments mismatch
  fe/fe-core/src/main/java/org/apache/doris/catalog/ArrayType.java
Labels: kind/fix, approved, area/array-type, reviewed

#10806 [Doc] Add log dependency when flink debugs locally
  docs/en/docs/ecosystem/flink-doris-connector.md
  docs/zh-CN/docs/ecosystem/flink-doris-connector.md
Labels: kind/docs

#10706 [feature-wip](unique-key-merge-on-write) add bloom filter index for primary key, DSIP-018[1.2]
  be/src/olap/primary_key_index.cpp
  be/src/olap/primary_key_index.h
  be/test/olap/primary_key_index_test.cpp
  gensrc/proto/segment_v2.proto
Labels: reviewed

#10815 [fix] regression test fix for array
  be/src/olap/rowset/segment_v2/column_writer.cpp
Labels: kind/fix, approved, area/array-type, reviewed

#10793 [bug](multi-catalog) empty hadoop configuration when reading iceberg table
  fe/fe-core/src/main/java/org/apache/doris/analysis/DescribeStmt.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/ExternalHiveScanProvider.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/ExternalIcebergScanProvider.java
Labels: area/planner, approved, reviewed, area/multi-catalog

#10482 [docs] Change the incubator fields before and after Doris' Graduation
  docs/en/docs/install/source-install/compilation-arm.md
  docs/en/docs/install/source-install/compilation-with-ldb-toolchain.md
  docs/en/docs/install/source-install/compilation.md
  docs/zh-CN/community/how-to-contribute/pull-request.md
  docs/zh-CN/community/release-and-verify/release-doris-core.md
  docs/zh-CN/community/release-and-verify/release-doris-manager.md
  docs/zh-CN/docs/install/source-install/compilation-arm.md
  docs/zh-CN/docs/install/source-install/compilation-with-ldb-toolchain.md
  docs/zh-CN/docs/install/source-install/compilation.md
Labels: kind/docs, approved, reviewed

#10822 [enhancement](signal) output query_id when 'be' core dumped.
  be/src/common/signal_handler.h
  be/src/runtime/fragment_mgr.cpp
Labels: kind/improvement, approved, reviewed

#10296 [vectorized][udf] improvement java-udaf with group by clause
  be/src/vec/aggregate_functions/aggregate_function_java_udaf.h
  fe/java-udf/src/main/java/org/apache/doris/udf/UdafExecutor.java
  gensrc/thrift/Types.thrift
Labels: approved, area/vectorization

#10821 [improvement]Use phmap for aggregation with serialized key
  be/src/vec/common/columns_hashing.h
  be/src/vec/common/columns_hashing_impl.h
  be/src/vec/common/hash_table/ph_hash_map.h
  be/src/vec/exec/vaggregation_node.cpp
  be/src/vec/exec/vaggregation_node.h
Labels: kind/improvement, approved, area/vectorization, reviewed

#10814 [feature-wip](unique-key-merge-on-write) Add option to enable unique-key-merge-on-write, DSIP-018[5/1]
  be/src/olap/tablet.h
  be/src/olap/tablet_manager.cpp
  be/src/olap/tablet_meta.cpp
  be/src/olap/tablet_meta.h
  be/test/olap/test_data/header_without_inc_rs.txt
  fe/fe-core/src/main/java/org/apache/doris/alter/RollupJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/backup/RestoreJob.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/TableProperty.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalDataSource.java
  fe/fe-core/src/main/java/org/apache/doris/master/ReportHandler.java
  fe/fe-core/src/main/java/org/apache/doris/task/CreateReplicaTask.java
  fe/fe-core/src/test/java/org/apache/doris/task/AgentTaskTest.java
  gensrc/proto/olap_file.proto
  gensrc/thrift/AgentService.thrift
Labels: kind/feature, reviewed

#10797 [FIX]VMergeIterator should use nullable info from scanner instead of schema
  be/src/olap/rowset/beta_rowset_reader.cpp
  be/src/olap/rowset/rowset_reader_context.h
  be/src/vec/olap/block_reader.cpp
  be/src/vec/olap/vgeneric_iterators.cpp
  be/src/vec/olap/vgeneric_iterators.h
Labels: reviewed, dev/1.1.1

#10836 [Release] add download links for v1.1
  docs/en/community/release-and-verify/release-complete.md
  docs/en/docs/install/source-install/compilation.md
  docs/en/downloads/downloads.md
  docs/zh-CN/community/release-and-verify/release-complete.md
  docs/zh-CN/docs/install/source-install/compilation.md
  docs/zh-CN/downloads/downloads.md
Labels: kind/community, kind/docs, approved, reviewed

#10833 [FIX] fix compatibility issue of using upgraded be with old fe
  be/src/vec/exec/vaggregation_node.cpp
Labels: approved, reviewed, dev/merge-1.1.1

#10832 [improvement]Use uint32 instead of size_t to reduce agg key's length
  be/src/vec/columns/column_string.cpp
Labels: approved, area/vectorization, reviewed

#10830 [doc] Fixed doc typo for materialized views
  docs/zh-CN/docs/advanced/materialized-view.md
Labels: kind/docs, approved, reviewed

#10838 [website]1.1 release formulation
  docs/en/README.md
  docs/zh-CN/README.md
Labels: kind/docs, approved, reviewed

#10817 [fix] Fix olap scan node normalize_in_and_eq_predicate infinite loop bug.
  be/src/exec/olap_scan_node.cpp
  be/src/vec/exec/volap_scan_node.cpp
Labels: area/sql/execution, area/vectorization

#10831 [regression] add ssb sf1 test
  regression-test/conf/regression-conf.groovy
  regression-test/data/ssb_sf1/sql/q1.1.out
  regression-test/data/ssb_sf1/sql/q1.2.out
  regression-test/data/ssb_sf1/sql/q1.3.out
  regression-test/data/ssb_sf1/sql/q2.1.out
  regression-test/data/ssb_sf1/sql/q2.2.out
  regression-test/data/ssb_sf1/sql/q2.3.out
  regression-test/data/ssb_sf1/sql/q3.1.out
  regression-test/data/ssb_sf1/sql/q3.2.out
  regression-test/data/ssb_sf1/sql/q3.3.out
  regression-test/data/ssb_sf1/sql/q3.4.out
  regression-test/data/ssb_sf1/sql/q4.1.out
  regression-test/data/ssb_sf1/sql/q4.2.out
  regression-test/data/ssb_sf1/sql/q4.3.out
  regression-test/framework/src/main/groovy/org/apache/doris/regression/Config.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/ConfigOptions.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/ScriptContext.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/SuiteContext.groovy
  regression-test/suites/ssb_sf1/ddl/customer_create.sql
  regression-test/suites/ssb_sf1/ddl/customer_delete.sql
  regression-test/suites/ssb_sf1/ddl/date_create.sql
  regression-test/suites/ssb_sf1/ddl/date_delete.sql
  regression-test/suites/ssb_sf1/ddl/lineorder_create.sql
  regression-test/suites/ssb_sf1/ddl/lineorder_delete.sql
  regression-test/suites/ssb_sf1/ddl/part_create.sql
  regression-test/suites/ssb_sf1/ddl/part_delete.sql
  regression-test/suites/ssb_sf1/ddl/supplier_create.sql
  regression-test/suites/ssb_sf1/ddl/supplier_delete.sql
  regression-test/suites/ssb_sf1/load.groovy
  regression-test/suites/ssb_sf1/sql/q1.1.sql
  regression-test/suites/ssb_sf1/sql/q1.2.sql
  regression-test/suites/ssb_sf1/sql/q1.3.sql
  regression-test/suites/ssb_sf1/sql/q2.1.sql
  regression-test/suites/ssb_sf1/sql/q2.2.sql
  regression-test/suites/ssb_sf1/sql/q2.3.sql
  regression-test/suites/ssb_sf1/sql/q3.1.sql
  regression-test/suites/ssb_sf1/sql/q3.2.sql
  regression-test/suites/ssb_sf1/sql/q3.3.sql
  regression-test/suites/ssb_sf1/sql/q3.4.sql
  regression-test/suites/ssb_sf1/sql/q4.1.sql
  regression-test/suites/ssb_sf1/sql/q4.2.sql
  regression-test/suites/ssb_sf1/sql/q4.3.sql
Labels: kind/test, approved, reviewed

#10828 fix the coredump when BE start after upgrade.
  be/src/olap/data_dir.cpp
  be/src/olap/tablet.cpp
Labels: approved, reviewed

#10835 save be code
  be/src/exec/mysql_scan_node.cpp
  be/src/runtime/mysql_table_writer.cpp
  be/src/vec/exec/join/vhash_join_node.cpp
  be/src/vec/exec/join/vhash_join_node.h
Labels: area/vectorization

#10848 [fix](planner)nullable info in IntermediateTuple do not be serialized in hash join node
  fe/fe-core/src/main/java/org/apache/doris/planner/HashJoinNode.java
Labels: area/planner

#10834 [BUG] (decimalv3) fix FE UTs
  fe/fe-core/src/main/java/org/apache/doris/analysis/ArithmeticExpr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/TypeDef.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Function.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/ScalarType.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ArithmeticExprTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/FunctionCallExprTest.java
Labels: area/planner, reviewed
