Repository apache/doris, pull requests merged in 2023-12, with the labels that each got.

#27664 [regression](nereids) add regression case for transposeSemiJoinAgg/transposeSemiJoinAggProject rules
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/TransposeSemiJoinAggProject.java
  regression-test/data/nereids_rules_p0/transposeJoin/transposeSemiJoinAgg.out
  regression-test/suites/nereids_rules_p0/transposeJoin/transposeSemiJoinAgg.groovy
Labels: approved, reviewed, dev/2.0.4

#27836 [branch-2.0](fix) Fix broken exception message
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
Labels: approved, reviewed

#27728 [Fix](type) fix wrong type transform for unix_timestamp
  fe/fe-core/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/UnixTimestamp.java
  regression-test/data/nereids_p0/sql_functions/datetime_functions/test_date_function.out
  regression-test/suites/nereids_p0/sql_functions/datetime_functions/test_date_function.groovy
Labels: approved, reviewed, dev/2.0.4

#27730 [Fix](test) Fix an auto partition conflict and add many testcases
  fe/fe-core/src/main/java/org/apache/doris/analysis/PartitionExprUtil.java
  regression-test/data/partition_p0/auto_partition/test_auto_list_partition.out
  regression-test/data/partition_p0/auto_partition/test_auto_partition_behavior.out
  regression-test/suites/partition_p0/auto_partition/test_auto_list_partition.groovy
  regression-test/suites/partition_p0/auto_partition/test_auto_partition_behavior.groovy
Labels: approved, reviewed

#27843 [Bug](func) coredump in equal for null in function
  be/src/vec/functions/comparison_equal_for_null.cpp
Labels: approved, reviewed, p0_crash, dev/2.0.3

#27708 [community](collaborator) add new collaborator KassieZ as a doc contributor
  .asf.yaml
Labels: approved, reviewed

#27771 [chore](log) Add more detail msg for waitRPC exception
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
Labels: approved, reviewed, dev/2.0.3-merged

#27627 [feature](Nereids) support add constraint on table
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisLexer.g4
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/catalog/Table.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/TableIf.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/constraint/Constraint.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/constraint/ForeignKeyConstraint.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/constraint/PrimaryKeyConstraint.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/constraint/TableIdentifier.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/constraint/UniqueConstraint.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PlanType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/AddConstraintCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/Constraint.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/CommandVisitor.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/AddConstraintTest.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/TestWithFeService.java
Labels: approved, reviewed

#27814 [minor](stats) Update olap table row count after analyze
  fe/fe-core/src/main/java/org/apache/doris/statistics/TableStatsMeta.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/AnalysisManagerTest.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/StatisticsAutoCollectorTest.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/TableStatsMetaTest.java
Labels: approved, reviewed, dev/2.0.3

#27858 [minor](stats) Update olap table row count after analyze #27814
  fe/fe-core/src/main/java/org/apache/doris/statistics/TableStatsMeta.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/AnalysisManagerTest.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/StatisticsAutoCollectorTest.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/TableStatsMetaTest.java
Labels: reviewed

#27825 [Chore](case) add case of join with big hashtable
  regression-test/data/ssb_sf100_p2/sql/bigbuild.out
  regression-test/suites/ssb_sf100_p2/sql/bigbuild.sql
Labels: approved, reviewed, dev/2.0.4

#27845 [minor](stats) Throw error when sync analyze failed
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisJob.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/BaseAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsCleaner.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/AnalysisJobTest.java
Labels: approved, reviewed, dev/2.0.3

#27793 [opt](Nereids) improve semi/anti join estimation when column stats are unavailable
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/JoinEstimation.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/StatsCalculator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/AbstractPhysicalJoin.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalOlapScan.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/ColumnStatistic.java
  regression-test/data/nereids_rules_p0/transposeJoin/transposeSemiJoinAgg.out
  regression-test/data/nereids_tpch_shape_sf1000_p0/nostats_rf_prune/q20-rewrite.out
  regression-test/data/nereids_tpch_shape_sf1000_p0/nostats_rf_prune/q20.out
  regression-test/data/nereids_tpch_shape_sf1000_p0/nostats_rf_prune/q21.out
  regression-test/data/nereids_tpch_shape_sf1000_p0/shape_no_stats/q20-rewrite.out
  regression-test/data/nereids_tpch_shape_sf1000_p0/shape_no_stats/q20.out
  regression-test/data/nereids_tpch_shape_sf1000_p0/shape_no_stats/q21.out
  regression-test/suites/nereids_rules_p0/transposeJoin/transposeSemiJoinAgg.groovy
Labels: approved, reviewed, dev/2.0.4

#27860 [bugfix](mergeprofile) ignore null profile to avoid bug
  be/src/vec/sink/async_writer_sink.h
  fe/fe-core/src/main/java/org/apache/doris/common/util/RuntimeProfile.java
Labels: approved, reviewed

#27862 [Fix](statistics)Fix analyze empty table NaN bug.
  fe/fe-core/src/main/java/org/apache/doris/statistics/BaseAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/HMSAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/JdbcAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/OlapAnalysisTask.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/AnalyzeTest.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/HMSAnalysisTaskTest.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/OlapAnalysisTaskTest.java
Labels: approved, reviewed, p0_block, dev/2.0.3

#27842 [fix](like_func) incorrect result of like with 'NO_BACKSLASH_ESCAPES' mode
  be/src/vec/functions/like.cpp
  regression-test/data/query_p0/sql_functions/string_functions/test_like_no_backslash_escapes_mode.out
  regression-test/suites/query_p0/sql_functions/string_functions/test_like_no_backslash_escapes_mode.groovy
Labels: approved, reviewed, usercase, dev/2.0.3

#27875 [doc](flink-connector) update flink doc and options
  docs/en/docs/ecosystem/flink-doris-connector.md
  docs/zh-CN/docs/ecosystem/flink-doris-connector.md
Labels: approved, reviewed

#27870 [fix](nereids)set operation's result type is wrong if decimal overflows
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalSetOperation.java
  regression-test/suites/nereids_p0/datatype/test_cast.groovy
Labels: approved, reviewed, p0_wrong_result, dev/2.0.3

#27867 [tpcds] remove useless tpcds tools config
  tools/tpcds-tools/conf/opt/opt_sf1.sql
  tools/tpcds-tools/conf/opt/opt_sf100.sql
  tools/tpcds-tools/conf/opt/opt_sf1000.sql
  tools/tpcds-tools/conf/opt/opt_sf10000.sql
Labels: approved, reviewed, dev/2.0.4

#27880 [fix](stats) Don't save colToPartitions anymore to save mem #27879
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisInfo.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisJob.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisManager.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticConstants.java
Labels: approved, reviewed, p0_block, dev/2.0.3

#27879 [fix](stats) Don't save colToPartitions anymore to save mem
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisInfo.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisJob.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisManager.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticConstants.java
Labels: approved, reviewed, p0_block, dev/2.0.3

#27872 [fix](nereids)set operation's result type is wrong if decimal overflows
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalSetOperation.java
Labels: area/nereids

#27877 [Config] Modify the default value of tablet_schema_cache_recycle_interval
  be/src/common/config.cpp
Labels: approved, reviewed, p0_block, dev/2.0.3

#27855 [fix](jdbc catalog) fix insert into jdbc table column order
  fe/fe-core/src/main/java/org/apache/doris/analysis/NativeInsertStmt.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/jdbc/JdbcTableSink.java
  regression-test/data/external_table_p0/jdbc/test_doris_jdbc_catalog.out
  regression-test/suites/external_table_p0/jdbc/test_doris_jdbc_catalog.groovy
Labels: approved, reviewed, usercase, dev/2.0.4

#27619 [fix](doc) spell error fixes for FE & BE Config documents
  docs/en/docs/admin-manual/config/be-config.md
  docs/en/docs/admin-manual/config/fe-config.md
  docs/zh-CN/docs/admin-manual/config/be-config.md
  docs/zh-CN/docs/admin-manual/config/fe-config.md
Labels: approved, reviewed

#27079 [fix](doc) spell error
  docs/en/docs/admin-manual/maint-monitor/metadata-operation.md
  docs/en/docs/advanced/cold-hot-separation.md
Labels: approved, reviewed

#27869 [feature](profile) add RuntimeFilterInfo in merge profile
  be/src/pipeline/exec/olap_scan_operator.cpp
  be/src/pipeline/exec/olap_scan_operator.h
  be/src/util/runtime_profile.h
  be/src/vec/exec/scan/new_olap_scan_node.cpp
  be/src/vec/exec/scan/new_olap_scan_node.h
  fe/fe-core/src/main/java/org/apache/doris/common/util/AggCounter.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/RuntimeProfile.java
Labels: approved, reviewed

#27804 [case](regression) Stream load 2pc exceptions
  regression-test/data/load_p0/stream_load/test_stream_load_properties.out
  regression-test/suites/load_p0/stream_load/test_stream_load_properties.groovy
Labels: approved, reviewed, dev/2.0.4

#27789 [fix](fe) Fix show frontends npt in some situations (#27295)
  fe/fe-core/src/main/java/org/apache/doris/common/proc/FrontendsProcNode.java
  fe/fe-core/src/main/java/org/apache/doris/ha/BDBHA.java
  fe/fe-core/src/main/java/org/apache/doris/journal/bdbje/BDBEnvironment.java
Labels: approved, reviewed, dev/2.0.4

#27895 [branch-2.0](fix) Fix extremely high CPU usage caused by rf merge
  be/src/runtime/runtime_filter_mgr.cpp
  be/src/runtime/runtime_filter_mgr.h
Labels: approved, reviewed

#27694 [case](regression) Add backup restore test with specified partition
  regression-test/data/backup_restore/test_backup_restore_partition.out
  regression-test/suites/backup_restore/test_backup_restore_partition.groovy
Labels: approved, reviewed, dev/2.0.4

#27715 [improve](env) Improve catalog not ready tips
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/RestBaseController.java
  fe/fe-core/src/main/java/org/apache/doris/journal/bdbje/BDBJEJournal.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/TokenManager.java
  fe/fe-core/src/main/java/org/apache/doris/persist/EditLog.java
  fe/fe-core/src/main/java/org/apache/doris/qe/MasterCatalogExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/MasterOpExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/MasterTxnExecutor.java
Labels: approved, reviewed, meta-change, dev/2.0.4

#27894 [fix](runtime filter) Fix extremely high CPU usage caused by rf merge
  be/src/runtime/runtime_filter_mgr.cpp
  be/src/runtime/runtime_filter_mgr.h
Labels: approved, reviewed, dev/2.0.3-merged

#27892 [improve](csv_reader) handle csv reader error
  be/src/vec/exec/format/csv/csv_reader.cpp
  be/src/vec/exec/format/csv/csv_reader.h
  be/src/vec/exec/format/generic_reader.h
  be/src/vec/exec/format/parquet/vparquet_reader.cpp
  be/src/vec/exec/format/parquet/vparquet_reader.h
  be/src/vec/exec/scan/vfile_scanner.cpp
Labels: approved, reviewed, dev/2.0.4

#27342 [feature](function) support ip function ipv6numtostring(alias inet6_ntoa)
  be/src/vec/common/format_ip.cpp
  be/src/vec/common/format_ip.h
  be/src/vec/functions/function_ip.cpp
  be/src/vec/functions/function_ip.h
  docs/en/docs/sql-manual/sql-functions/ip-functions/inet6-ntoa.md
  docs/en/docs/sql-manual/sql-functions/ip-functions/ipv6-num-to-string.md
  docs/sidebars.json
  docs/zh-CN/docs/sql-manual/sql-functions/ip-functions/inet6-ntoa.md
  docs/zh-CN/docs/sql-manual/sql-functions/ip-functions/ipv6-num-to-string.md
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinScalarFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Ipv6NumToString.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/ScalarFunctionVisitor.java
  gensrc/script/doris_builtins_functions.py
  regression-test/data/nereids_function_p0/ip_functions.out
  regression-test/data/query_p0/sql_functions/ip_functions/test_ip_functions.out
  regression-test/suites/nereids_function_p0/ip_functions.groovy
  regression-test/suites/query_p0/sql_functions/ip_functions/test_ip_functions.groovy
Labels: kind/feature, approved, reviewed

#27749 [fix](profile) fix error set with peak_memory_usage in pipeline
  be/src/exec/exec_node.cpp
  be/src/pipeline/exec/aggregation_sink_operator.cpp
  be/src/pipeline/exec/exchange_sink_operator.cpp
  be/src/pipeline/exec/exchange_sink_operator.h
  be/src/pipeline/pipeline_x/dependency.h
  be/src/pipeline/pipeline_x/operator.cpp
  be/src/pipeline/pipeline_x/operator.h
  be/src/vec/runtime/vdata_stream_recvr.cpp
Labels: approved, reviewed

#27890 [enhacement](Nerids) fix bugs in struct info
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/joinorder/hypergraph/HyperGraph.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/exploration/mv/BuildStructInfoTest.java
Labels: approved, reviewed

#27883 [feature](profile) add avg/min/max info in uint counter
  fe/fe-core/src/main/java/org/apache/doris/common/util/AggCounter.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/RuntimeProfile.java
Labels: approved, reviewed

#27896 [opt](nereids) Branch-2.0: remove partition & histogram from col stats to reduce memory usage
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/ExpressionEstimation.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/FilterEstimation.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/StatsCalculator.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/ColumnStatistic.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/ColumnStatisticBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsCache.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/util/HyperGraphBuilder.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/CacheTest.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/StatsDeriveResultTest.java
Labels: area/nereids

#27905 [pick](Nereids) temporary partition is selected only if user manually specified: Branch-2.0
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/PartitionPruner.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PruneOlapScanPartition.java
Labels: area/nereids

#27852 [pipelineX](improvement) Support local shuffle for join and agg
  be/src/pipeline/exec/aggregation_sink_operator.cpp
  be/src/pipeline/exec/aggregation_sink_operator.h
  be/src/pipeline/exec/distinct_streaming_aggregation_sink_operator.h
  be/src/pipeline/exec/exchange_sink_operator.cpp
  be/src/pipeline/exec/exchange_sink_operator.h
  be/src/pipeline/exec/exchange_source_operator.cpp
  be/src/pipeline/exec/exchange_source_operator.h
  be/src/pipeline/exec/file_scan_operator.cpp
  be/src/pipeline/exec/file_scan_operator.h
  be/src/pipeline/exec/hashjoin_build_sink.cpp
  be/src/pipeline/exec/hashjoin_build_sink.h
  be/src/pipeline/exec/hashjoin_probe_operator.cpp
  be/src/pipeline/exec/hashjoin_probe_operator.h
  be/src/pipeline/exec/jdbc_scan_operator.cpp
  be/src/pipeline/exec/jdbc_scan_operator.h
  be/src/pipeline/exec/join_probe_operator.h
  be/src/pipeline/exec/multi_cast_data_stream_sink.cpp
  be/src/pipeline/exec/multi_cast_data_stream_sink.h
  be/src/pipeline/exec/olap_scan_operator.cpp
  be/src/pipeline/exec/olap_scan_operator.h
  be/src/pipeline/exec/operator.h
  be/src/pipeline/exec/streaming_aggregation_sink_operator.h
  be/src/pipeline/pipeline.h
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/pipeline/pipeline_fragment_context.h
  be/src/pipeline/pipeline_x/dependency.h
  be/src/pipeline/pipeline_x/local_exchange/local_exchange_sink_operator.h
  be/src/pipeline/pipeline_x/local_exchange/local_exchange_source_operator.cpp
  be/src/pipeline/pipeline_x/local_exchange/local_exchange_source_operator.h
  be/src/pipeline/pipeline_x/local_exchange/local_exchanger.cpp
  be/src/pipeline/pipeline_x/local_exchange/local_exchanger.h
  be/src/pipeline/pipeline_x/operator.cpp
  be/src/pipeline/pipeline_x/operator.h
  be/src/pipeline/pipeline_x/pipeline_x_fragment_context.cpp
  be/src/pipeline/pipeline_x/pipeline_x_fragment_context.h
  be/src/pipeline/pipeline_x/pipeline_x_task.cpp
  be/src/pipeline/pipeline_x/pipeline_x_task.h
  be/src/runtime/fragment_mgr.cpp
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/PhysicalPlanTranslator.java
  fe/fe-core/src/main/java/org/apache/doris/planner/ExchangeNode.java
  gensrc/thrift/PlanNodes.thrift
Labels: approved, reviewed, meta-change

#27904 [improvement](spinlock) remove some potential bad spinlock usage
  be/src/runtime/query_statistics.cpp
  be/src/runtime/query_statistics.h
  be/src/runtime/runtime_filter_mgr.cpp
  be/src/runtime/user_function_cache.cpp
  be/src/util/metrics.cpp
  be/src/util/metrics.h
  be/src/util/streaming_sampler.h
Labels: approved, reviewed

#27903 [chore](Nereids): use debug to show phase of nereids
  fe/fe-core/src/main/java/org/apache/doris/nereids/NereidsPlanner.java
Labels: approved, reviewed

#27545 [Opt](multi-catalog) Opt parquet orc reader null map decoding by `memset()`.
  be/src/vec/exec/format/orc/vorc_reader.cpp
  be/src/vec/exec/format/parquet/parquet_common.cpp
Labels: approved, reviewed, dev/2.0.4

#27706 [feature](parquet)support read parquet lzo compress.
  be/src/util/block_compression.cpp
  regression-test/data/external_table_p2/hive/test_compress_type.out
  regression-test/suites/external_table_p2/hive/test_compress_type.groovy
Labels: approved, reviewed, dev/2.0.4

#27525 [case](regression) using load_parallelism when load csv and json from s3
  regression-test/data/load_p1/broker_load/test_s3_load_parallelism.out
  regression-test/suites/load_p1/broker_load/test_s3_load_parallelism.groovy
Labels: approved, reviewed, dev/2.0.4

#27908 [fix](invert index) Fix the issue where the reader does not release the file descriptor (fd)
  be/src/olap/rowset/segment_v2/inverted_index_cache.cpp
Labels: approved, reviewed

#27750 [FIX](array )fix array<null> literal in fe
  fe/fe-core/src/main/java/org/apache/doris/analysis/ArrayLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/DecimalLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/Expr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/FloatLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/LiteralExpr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/NullLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/NereidsPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OriginalPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/planner/Planner.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ArrayLiteralTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/DateLiteralTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/DecimalLiteralTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/FloatLiteralTest.java
  regression-test/data/query_p0/sql_functions/array_functions/test_array_functions_by_literal.out
  regression-test/data/query_p0/sql_functions/array_functions/test_array_with_scale_type.out
  regression-test/data/query_p0/sql_functions/conditional_functions/test_if_cast.out
  regression-test/suites/nereids_syntax_p0/array_function.groovy
  regression-test/suites/query_p0/sql_functions/conditional_functions/test_if_cast.groovy
Labels: approved, reviewed, dev/2.0.4

#27907 [chore](Nereids): use debug to show phase of nereids (#27903)
  fe/fe-core/src/main/java/org/apache/doris/nereids/NereidsPlanner.java
Labels: area/nereids

#27881 [fix](env) state listener avoid endless waiting
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
Labels: reviewed, dev/2.0.4

#27659 [log](table) add table lock failed log
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Table.java
Labels: approved, reviewed

#27849 [release](version) change branch-2.0 version to 2.0.3-rc05
  gensrc/script/gen_build_version.sh
Labels: reviewed

#27268 [Opt](Coordinator) Don't shuffle scan range locations when performing scan range assignments.
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
Labels: approved, reviewed, dev/2.0.4

#27766 [refactor](scan) change scan reschedule into scan context
  be/src/pipeline/exec/scan_operator.cpp
  be/src/pipeline/exec/scan_operator.h
  be/src/vec/exec/scan/pip_scanner_context.h
Labels: approved, reviewed

#27813 [fix](deploy) K8s deploy manager cannot get group host info by endpoint
  fe/fe-core/src/main/java/org/apache/doris/deploy/impl/K8sDeployManager.java
Labels: approved, reviewed, dev/2.0.4

#27927 [Bug](column) support insert default for ColumnFixedLengthObject
  be/src/vec/columns/column_fixed_length_object.h
Labels: approved, reviewed

#27891 [Chore](function) set normal function use_default_implementation_for_constants to default
  be/src/vec/functions/function.h
  be/src/vec/functions/function_agg_state.h
  be/src/vec/functions/function_cast.h
  be/src/vec/functions/function_date_or_datetime_to_something.h
  be/src/vec/functions/function_fake.h
  be/src/vec/functions/function_json.cpp
  be/src/vec/functions/function_multi_same_args.h
  be/src/vec/functions/function_string.h
  be/src/vec/functions/function_struct_element.cpp
  be/src/vec/functions/function_unary_arithmetic.h
  be/src/vec/functions/least_greast.cpp
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/SubstringIndex.java
Labels: approved, reviewed

#27612 [docs](fix) fix document error
  docs/en/docs/admin-manual/multi-tenant.md
  docs/zh-CN/docs/admin-manual/multi-tenant.md
Labels: approved, reviewed

#27918 [fix](invert index) fix reader does not close fd
  be/src/olap/compaction.cpp
Labels: approved, reviewed

#27940 [fix](case) add "nonConcurrent" to prevent effect other case
  regression-test/suites/meta_action_p0/test_dump_image.groovy
Labels: kind/test, approved, reviewed

#27945 [config](p0) Pipeline p0 open arrow_flight_sql_port
  regression-test/pipeline/p0/conf/be.conf
  regression-test/pipeline/p0/conf/fe.conf
Labels: approved, reviewed

#27757 [enhancement](Nereids) add test for some push down filter rule
  regression-test/data/nereids_rules_p0/filter_push_down/push_down_alias_through_join.out
  regression-test/data/nereids_rules_p0/filter_push_down/push_down_expression_in_hash_join.out
  regression-test/data/nereids_rules_p0/filter_push_down/push_down_filter_other_condition.out
  regression-test/data/nereids_rules_p0/filter_push_down/push_filter_inside_join.out
  regression-test/data/nereids_rules_p0/limit_push_down/order_push_down.out
  regression-test/suites/nereids_rules_p0/filter_push_down/push_down_alias_through_join.groovy
  regression-test/suites/nereids_rules_p0/filter_push_down/push_down_expression_in_hash_join.groovy
  regression-test/suites/nereids_rules_p0/filter_push_down/push_down_filter_other_condition.groovy
  regression-test/suites/nereids_rules_p0/filter_push_down/push_filter_inside_join.groovy
  regression-test/suites/nereids_rules_p0/limit_push_down/limit_push_down.groovy
  regression-test/suites/nereids_rules_p0/limit_push_down/order_push_down.groovy
Labels: approved, reviewed

#27555 [enhance](BE) Refactor TaskWorkerPool
  be/src/agent/agent_server.cpp
  be/src/agent/agent_server.h
  be/src/agent/task_worker_pool.cpp
  be/src/agent/task_worker_pool.h
  be/src/http/action/tablet_migration_action.cpp
  be/src/olap/storage_engine.cpp
  be/src/olap/storage_engine.h
  be/src/olap/tablet_manager.cpp
  be/src/olap/task/engine_alter_tablet_task.h
  be/src/olap/task/engine_batch_load_task.cpp
  be/src/olap/task/engine_batch_load_task.h
  be/src/olap/task/engine_index_change_task.h
  be/src/olap/task/engine_publish_version_task.cpp
  be/src/olap/task/engine_publish_version_task.h
  be/src/olap/task/engine_task.h
  be/src/service/backend_service.cpp
  be/src/service/backend_service.h
  be/src/util/doris_metrics.cpp
  be/src/util/doris_metrics.h
  be/test/agent/mock_task_worker_pool.h
  be/test/agent/task_worker_pool_test.cpp
  be/test/util/doris_metrics_test.cpp
Labels: approved, reviewed

#27938 [fix](Nereids): fix datetime fold-constant-be in Branch-2.0
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/FoldConstantRuleOnBE.java
Labels: area/nereids, usercase, dev/2.0.3

#27850 [test](Nereids): add infer-predicates regression test
  regression-test/data/nereids_rules_p0/predicate_infer/infer_predicate.out
  regression-test/suites/nereids_rules_p0/predicate_infer/infer_predicate.groovy
Labels: approved, reviewed, dev/2.0.4

#27912 [fix](Nereids) should not push down project to the nullable side of outer join
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/join/PushDownProjectThroughInnerOuterJoin.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/exploration/join/PushDownProjectThroughInnerOuterJoinTest.java
Labels: approved, reviewed, p0_crash, dev/2.0.3-merged

#27946 [branch-1.2](backup-restore) add config for upload/download task num per be
  docs/en/docs/admin-manual/config/fe-config.md
  docs/zh-CN/docs/admin-manual/config/fe-config.md
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupJob.java
  fe/fe-core/src/main/java/org/apache/doris/backup/RestoreJob.java
Labels: kind/docs, approved, reviewed

#26943 [fix](restore) fix Restore from __keep_on_local__ throws null pointer…
  fe/fe-core/src/main/java/org/apache/doris/analysis/RestoreStmt.java
  regression-test/suites/backup_restore/test_backup_restore_keep_on_local.groovy
Labels: dev/2.0.4

#27889 [refactor](memtable) remove unused stream output
  be/src/olap/memtable.h
Labels: approved, reviewed

#27975 [improve](heartbeat) show more info when receive invalid cluster id
  be/src/agent/heartbeat_server.cpp
Labels: approved, reviewed, dev/2.0.4

#27980 [fix](move-memtable) free resources before storage engine stop
  be/src/runtime/exec_env_init.cpp
Labels: approved, reviewed

#27983 [fix](move-memtable) only report load stream profile in the end
  be/src/runtime/load_stream.cpp
Labels: approved, reviewed

#27797 [enhancement](Nereids) format some code in functional deps
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/joinorder/hypergraph/receiver/PlanReceiver.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/FunctionalDependencies.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalCatalogRelation.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalCheckPolicy.java
Labels: approved, reviewed

#27568 [feature](nereids) Matiarilzed view query rewrite util implementation
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewJoinRule.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewRule.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/Predicates.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/PredicatesSplitter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/RelationMapping.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/SlotMapping.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/StructInfo.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/mapping/ExpressionIndexMapping.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/mapping/Mapping.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/mapping/RelationMapping.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/mapping/SlotMapping.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/ExpressionVisitors.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/ExpressionLineageReplacer.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/ExpressionUtils.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/exploration/mv/MappingTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/expression/ExpressionRewriteTestHelper.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/expression/PredicatesSplitterTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/util/ExpressionUtilsTest.java
Labels: approved, reviewed

#27982 [fix](move-memtable) fix sink v2 profile
  be/src/vec/sink/writer/vtablet_writer_v2.cpp
Labels: approved, reviewed

#27953 [fix](move-memtable) exclude memtable insert memory in query tracker
  be/src/olap/delta_writer_v2.cpp
Labels: approved, reviewed

#27959 [fix](Nereids): Preserve `""` in single quote strings and `''` in double quote strings.
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/util/StatisticsUtil.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/util/StatisticsUtilTest.java
  regression-test/data/nereids_syntax_p0/one_row_relation.out
  regression-test/suites/nereids_syntax_p0/one_row_relation.groovy
Labels: approved, reviewed, usercase, dev/2.0.4

#27974 [Bug](partition) fix auto list partition error of incorrect partition name
  fe/fe-core/src/main/java/org/apache/doris/analysis/PartitionExprUtil.java
  regression-test/suites/partition_p0/auto_partition/test_auto_list_partition.groovy
Labels: reviewed

#27978 [fix](cache)Fix partition cache support DATEV2
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/PartitionRange.java
Labels: approved, reviewed, dev/2.0.3

#27988 [bug](function) fix compound expr coredump problem
  be/src/vec/exprs/vcompound_pred.h
Labels: approved, reviewed, p0_crash, dev/2.0.3

#27984 [pick](branch-2.0) cherry pick from branch-2.0
  be/src/olap/compaction.cpp
  fe/fe-core/src/main/java/org/apache/doris/nereids/NereidsPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/FoldConstantRuleOnBE.java
Labels: area/nereids

#27948 [Refactor](scan) refactor scan scheduler to improve performance
  be/src/runtime/runtime_state.h
  be/src/vec/exec/scan/pip_scanner_context.h
  be/src/vec/exec/scan/scanner_context.cpp
  be/src/vec/exec/scan/scanner_scheduler.cpp
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  gensrc/thrift/PaloInternalService.thrift
Labels: reviewed, meta-change

#27941 [fix](case) add "nonConcurrent" to prevent effect other case
  regression-test/suites/meta_action_p0/test_dump_image.groovy
Labels: approved, reviewed, dev/2.0.3-merged

#27989 [bug](function) fix compound expr coredump problem
  be/src/vec/exprs/vcompound_pred.h
Labels: approved, reviewed

#27990 [branch-2.0](cache) Fix partition cache support DATEV2
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/PartitionRange.java
Labels: approved, reviewed

#27965 [FIX](serde)fix datetimev2 serde parse from string with scale
  be/src/vec/data_types/serde/data_type_datetimev2_serde.cpp
  regression-test/data/datatype_p0/nested_types/query/test_nestedtypes_csv_insert_into_with_s3.out
  regression-test/data/datatype_p0/nested_types/query/test_nestedtypes_json_insert_into_with_s3.out
  regression-test/data/query_p0/sql_functions/array_functions/test_array_with_scale_type.csv
  regression-test/data/query_p0/sql_functions/array_functions/test_array_with_scale_type.out
  regression-test/suites/query_p0/sql_functions/array_functions/test_array_with_scale_type.groovy
Labels: approved, reviewed, dev/2.0.4

#27798 [improvement](executor)clear unused cgroup path
  be/src/agent/cgroup_cpu_ctl.cpp
  be/src/agent/cgroup_cpu_ctl.h
  be/src/agent/workload_group_listener.cpp
  be/src/runtime/task_group/task_group_manager.cpp
  be/src/runtime/task_group/task_group_manager.h
Labels: approved, reviewed, workload-group

#28001 [branch-2.0] Fix auto partition docs label
  docs/en/docs/advanced/partition/auto-partition.md
  docs/sidebars.json
  docs/zh-CN/docs/advanced/partition/auto-partition.md
Labels: kind/docs

#27956 [fix](Statistics)Drop stats or update updated rows after truncate table.
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisManager.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsAutoCollector.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsCache.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsRepository.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/CacheTest.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/StatisticsAutoCollectorTest.java
  gensrc/thrift/FrontendService.thrift
  regression-test/suites/statistics/analyze_stats.groovy
Labels: kind/test

#27971 [Bug](materialized-view) fix create mv failed on unique table
  fe/fe-core/src/main/java/org/apache/doris/alter/MaterializedViewHandler.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateMaterializedViewStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/CreateMaterializedViewStmtTest.java
  regression-test/data/mv_p0/unique/unique.out
  regression-test/data/mv_p0/varchar_length/varchar_length.out
  regression-test/framework/src/main/groovy/org/apache/doris/regression/action/CreateMVAction.groovy
  regression-test/suites/mv_p0/test_mv_useless/test_agg_mv_useless.groovy
  regression-test/suites/mv_p0/test_mv_useless/test_uniq_mv_useless.groovy
  regression-test/suites/mv_p0/unique/unique.groovy
Labels: approved, reviewed

#27931 [fix](Statistics)Drop stats or update updated rows after truncate table.
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisManager.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsAutoCollector.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsCache.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsRepository.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/CacheTest.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/StatisticsAutoCollectorTest.java
  gensrc/thrift/FrontendService.thrift
  regression-test/suites/statistics/analyze_stats.groovy
Labels: approved, reviewed, dev/2.0.3, meta-change, dev/2.0.4

#27967 [feature](mtmv)add Job and task tvf
  be/src/vec/exec/scan/vmeta_scanner.cpp
  be/src/vec/exec/scan/vmeta_scanner.h
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinTableValuedFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/job/base/AbstractJob.java
  fe/fe-core/src/main/java/org/apache/doris/job/base/Job.java
  fe/fe-core/src/main/java/org/apache/doris/job/common/JobType.java
  fe/fe-core/src/main/java/org/apache/doris/job/extensions/insert/InsertJob.java
  fe/fe-core/src/main/java/org/apache/doris/job/extensions/insert/InsertTask.java
  fe/fe-core/src/main/java/org/apache/doris/job/extensions/mtmv/MTMVJob.java
  fe/fe-core/src/main/java/org/apache/doris/job/extensions/mtmv/MTMVTask.java
  fe/fe-core/src/main/java/org/apache/doris/job/manager/TaskDisruptorGroupManager.java
  fe/fe-core/src/main/java/org/apache/doris/job/task/AbstractTask.java
  fe/fe-core/src/main/java/org/apache/doris/job/task/Task.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVJobManager.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/table/Jobs.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/table/MvInfos.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/table/Tasks.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/TableValuedFunctionVisitor.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/JobsTableValuedFunction.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/MetadataGenerator.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/MetadataTableValuedFunction.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/MvInfosTableValuedFunction.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/TableValuedFunctionIf.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/TasksTableValuedFunction.java
  gensrc/thrift/FrontendService.thrift
  gensrc/thrift/PlanNodes.thrift
  gensrc/thrift/Types.thrift
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
  regression-test/suites/mtmv_p0/test_base_mtmv.groovy
Labels: approved, reviewed, meta-change

#27997 [minor](stats) truncate min/max if too long #27955
  regression-test/suites/statistics/analyze_stats.groovy
Labels: kind/test

#27616 [case](regression-test) add backup recovery for inverted index and bl…
  regression-test/suites/backup_restore/test_backup_restore_bloom_filter.groovy
  regression-test/suites/backup_restore/test_backup_restore_inverted_index.groovy
Labels: approved, reviewed, dev/2.0.4

#28003 [test](execute)Fix workload group regression test unstable
  regression-test/suites/workload_manager_p0/test_curd_wlg.groovy
Labels: kind/test, approved, reviewed, workload-group

#28011 [debug](timeout) add some log to debug timeout== 0
  fe/fe-core/src/main/java/org/apache/doris/planner/StreamLoadPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
Labels: approved, reviewed

#28016 [pipelineX](minor) remove unused code
  be/src/pipeline/exec/exchange_source_operator.h
  be/src/pipeline/pipeline_task.h
  be/src/pipeline/pipeline_x/pipeline_x_task.cpp
  be/src/pipeline/pipeline_x/pipeline_x_task.h
  be/src/pipeline/task_scheduler.cpp
  be/src/vec/runtime/vdata_stream_recvr.h
Labels: approved, reviewed

#27928 [enhancement](main) do not coredump when be can not start
  be/src/service/doris_main.cpp
Labels: approved, reviewed, dev/2.0.4

#27404 [feature](invert index) match_phrase_prefix feature added
  be/src/exec/olap_common.h
  be/src/exec/olap_utils.h
  be/src/olap/match_predicate.cpp
  be/src/olap/rowset/segment_v2/inverted_index/query/phrase_prefix_query.cpp
  be/src/olap/rowset/segment_v2/inverted_index/query/phrase_prefix_query.h
  be/src/olap/rowset/segment_v2/inverted_index/query/prefix_query.cpp
  be/src/olap/rowset/segment_v2/inverted_index/query/prefix_query.h
  be/src/olap/rowset/segment_v2/inverted_index_query_type.h
  be/src/olap/rowset/segment_v2/inverted_index_reader.cpp
  be/src/olap/rowset/segment_v2/inverted_index_reader.h
  be/src/vec/functions/match.cpp
  be/src/vec/functions/match.h
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisLexer.g4
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/MatchPredicate.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/Match.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/MatchPhrasePrefix.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/ExpressionVisitor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/jflex/sql_scanner.flex
  gensrc/thrift/Opcodes.thrift
  gensrc/thrift/PaloInternalService.thrift
  regression-test/data/inverted_index_p0/test_index_match_phrase_prefix.out
  regression-test/suites/inverted_index_p0/test_index_match_phrase_prefix.groovy
Labels: approved, reviewed, meta-change, dev/2.0.4

#27955 [fix](stats) truncate min/max if too long
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisManager.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/BaseAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/JdbcAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/OlapAnalysisTask.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/OlapAnalysisTaskTest.java
  regression-test/suites/statistics/analyze_stats.groovy
Labels: approved, reviewed, p0_block, dev/2.0.3-merged

#28004 [agg](profile) fix incorrect profile
  be/src/pipeline/exec/aggregation_sink_operator.cpp
  be/src/vec/exec/distinct_vaggregation_node.cpp
  be/src/vec/exec/vaggregation_node.cpp
  be/src/vec/exec/vaggregation_node.h
  be/src/vec/exprs/vectorized_agg_fn.cpp
  be/src/vec/exprs/vectorized_agg_fn.h
Labels: approved, reviewed, dev/2.0.4

#27874 [Improvement](multi-catalog)make location easier to modified, decoupling all storage with single location class
  fe/fe-core/src/main/java/org/apache/doris/common/FeConstants.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/LocationPath.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/S3Util.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HiveMetaStoreCache.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/PropertyConverter.java
  fe/fe-core/src/main/java/org/apache/doris/fs/FileSystemFactory.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/FileQueryScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/HiveScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/hudi/HudiScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/iceberg/IcebergScanNode.java
  fe/fe-core/src/test/java/org/apache/doris/common/util/LocationPathTest.java
  fe/fe-core/src/test/java/org/apache/doris/common/util/S3UtilTest.java
Labels: reviewed

#28002 [fix](memtracking) fix capacity when releasing owned slice
  be/src/util/faststring.h
  be/src/util/slice.h
Labels: approved, reviewed

#27986 [fix](regression) backup restore cases adapt force_olap_table_replica_num option
  regression-test/suites/backup_restore/test_backup_restore.groovy
  regression-test/suites/backup_restore/test_backup_restore_alias.groovy
  regression-test/suites/backup_restore/test_backup_restore_db.groovy
  regression-test/suites/backup_restore/test_backup_restore_diff_repo_same_snapshot.groovy
  regression-test/suites/backup_restore/test_backup_restore_dup_without_default_keys.groovy
  regression-test/suites/backup_restore/test_backup_restore_exclude.groovy
  regression-test/suites/backup_restore/test_backup_restore_multi_tables.groovy
  regression-test/suites/backup_restore/test_backup_restore_multi_tables_overwrite.groovy
  regression-test/suites/backup_restore/test_backup_restore_partition.groovy
  regression-test/suites/backup_restore/test_backup_restore_reserve_dynamic_partition_false.groovy
  regression-test/suites/backup_restore/test_backup_restore_reserve_dynamic_partition_true.groovy
  regression-test/suites/backup_restore/test_backup_restore_table_auto_bucket.groovy
  regression-test/suites/backup_restore/test_duplicate_backup_restore.groovy
  regression-test/suites/backup_restore/test_restore_mix_exists_and_new_table.groovy
  regression-test/suites/backup_restore/test_restore_to_new_table.groovy
  regression-test/suites/backup_restore/test_unique_backup_restore.groovy
Labels: approved, reviewed, dev/2.0.4

#27991 [fix](hdfs) Fix hdfsExists that return staled root cause
  be/src/io/fs/hdfs_file_system.cpp
Labels: approved, reviewed, dev/2.0.4

#28032 [pipelineX](local shuffle) Fix local shuffle for colocate/bucket join
  be/src/pipeline/exec/aggregation_sink_operator.h
  be/src/pipeline/exec/aggregation_source_operator.cpp
  be/src/pipeline/exec/distinct_streaming_aggregation_sink_operator.h
  be/src/pipeline/exec/hashjoin_build_sink.cpp
  be/src/pipeline/exec/hashjoin_build_sink.h
  be/src/pipeline/exec/hashjoin_probe_operator.cpp
  be/src/pipeline/exec/hashjoin_probe_operator.h
  be/src/pipeline/exec/join_build_sink_operator.h
  be/src/pipeline/exec/join_probe_operator.h
  be/src/pipeline/exec/scan_operator.h
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/pipeline/pipeline_fragment_context.h
  be/src/pipeline/pipeline_x/dependency.cpp
  be/src/pipeline/pipeline_x/dependency.h
  be/src/pipeline/pipeline_x/local_exchange/local_exchange_sink_operator.cpp
  be/src/pipeline/pipeline_x/local_exchange/local_exchange_sink_operator.h
  be/src/pipeline/pipeline_x/local_exchange/local_exchange_source_operator.cpp
  be/src/pipeline/pipeline_x/local_exchange/local_exchange_source_operator.h
  be/src/pipeline/pipeline_x/local_exchange/local_exchanger.cpp
  be/src/pipeline/pipeline_x/local_exchange/local_exchanger.h
  be/src/pipeline/pipeline_x/operator.h
  be/src/pipeline/pipeline_x/pipeline_x_fragment_context.cpp
  be/src/pipeline/pipeline_x/pipeline_x_fragment_context.h
  be/src/vec/exec/scan/pip_scanner_context.h
  fe/fe-core/src/main/java/org/apache/doris/planner/HashJoinNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PlanFragment.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  gensrc/thrift/PaloInternalService.thrift
  gensrc/thrift/PlanNodes.thrift
Labels: approved, reviewed, meta-change

#28028 [Test](auto-partition) Add auto partition p1 test
  regression-test/suites/partition_p1/auto_partition/ddl/concurrent.sql
  regression-test/suites/partition_p1/auto_partition/doris_dbgen_conf/two_stream_load_conflict.yaml
  regression-test/suites/partition_p1/auto_partition/sql/multi_thread_load.groovy
Labels: approved, reviewed

#28025 [regression-test](variant) fix variant p2 cases
  regression-test/suites/variant_p2/load.groovy
Labels: reviewed, variant

#27703 [Feature](job)support cancel task and fix log invalid
  docs/zh-CN/docs/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-JOB.md
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/AlterJobStatusStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CancelJobTaskStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateJobStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/PauseJobStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/StopJobStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/job/base/AbstractJob.java
  fe/fe-core/src/main/java/org/apache/doris/job/base/Job.java
  fe/fe-core/src/main/java/org/apache/doris/job/common/IntervalUnit.java
  fe/fe-core/src/main/java/org/apache/doris/job/common/TaskStatus.java
  fe/fe-core/src/main/java/org/apache/doris/job/disruptor/TimerJobEvent.java
  fe/fe-core/src/main/java/org/apache/doris/job/executor/DefaultTaskExecutorHandler.java
  fe/fe-core/src/main/java/org/apache/doris/job/executor/DispatchTaskHandler.java
  fe/fe-core/src/main/java/org/apache/doris/job/executor/TimerJobSchedulerTask.java
  fe/fe-core/src/main/java/org/apache/doris/job/extensions/insert/InsertJob.java
  fe/fe-core/src/main/java/org/apache/doris/job/extensions/insert/InsertTask.java
  fe/fe-core/src/main/java/org/apache/doris/job/extensions/mtmv/MTMVJob.java
  fe/fe-core/src/main/java/org/apache/doris/job/manager/JobManager.java
  fe/fe-core/src/main/java/org/apache/doris/job/manager/TaskDisruptorGroupManager.java
  fe/fe-core/src/main/java/org/apache/doris/job/manager/TaskTokenManager.java
  fe/fe-core/src/main/java/org/apache/doris/job/scheduler/JobScheduler.java
  fe/fe-core/src/main/java/org/apache/doris/job/task/AbstractTask.java
  fe/fe-core/src/main/java/org/apache/doris/job/task/Task.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVJobManager.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/InsertExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/InsertIntoTableCommand.java
  fe/fe-core/src/main/java/org/apache/doris/qe/DdlExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/job/base/JobExecutionConfigurationTest.java
  regression-test/pipeline/p0/conf/fe.conf
  regression-test/suites/job_p0/test_base_insert_job.groovy
Labels: approved, reviewed

#28035 [agg](profile) fix incorrect profile (#28004)
  be/src/vec/exec/distinct_vaggregation_node.cpp
  be/src/vec/exec/vaggregation_node.cpp
  be/src/vec/exec/vaggregation_node.h
  be/src/vec/exprs/vectorized_agg_fn.cpp
  be/src/vec/exprs/vectorized_agg_fn.h
Labels: approved, reviewed

#28039 [refactor](unusedcode) remove internalquery since it is useless
  fe/fe-core/src/main/java/org/apache/doris/statistics/util/InternalQuery.java
Labels: approved, reviewed

#28010 [fix](nereids) runtime filter prune skip filter like "__DORIS_DELETE_SIGN__ = 0"
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/RuntimeFilterPruner.java
  regression-test/suites/nereids_rules_p0/runtime_filter/rf_prune.groovy
Labels: approved, reviewed, usercase, dev/2.0.4

#27969 [refactor](queryqueue) using a priority queue in query queue in order to implement priority management in the future
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/resource/workloadgroup/QueryQueue.java
  fe/fe-core/src/main/java/org/apache/doris/resource/workloadgroup/QueueOfferToken.java
  fe/fe-core/src/main/java/org/apache/doris/resource/workloadgroup/QueueToken.java
Labels: approved, reviewed, workload-group

#28026 [FIX](map/struct)fix map/struct literal from fe
  fe/fe-common/src/main/java/org/apache/doris/catalog/Type.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ArrayLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/LiteralExpr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/MapLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/StructLiteral.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ArrayLiteralTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/MapLiteralTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/StructLiteralTest.java
Labels: approved, reviewed

#27985 [test](Nereids): add regression test eliminate/infer rules
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/AggScalarSubQueryToWindowFunction.java
  regression-test/data/nereids_rules_p0/eliminate_not_null/eliminate_not_null.out
  regression-test/data/nereids_rules_p0/eliminate_outer_join/eliminate_outer_join.out
  regression-test/data/nereids_rules_p0/infer_set_operator_distinct/infer_set_operator_distinct.out
  regression-test/suites/nereids_rules_p0/eliminate_not_null/eliminate_not_null.groovy
  regression-test/suites/nereids_rules_p0/eliminate_outer_join/eliminate_outer_join.groovy
  regression-test/suites/nereids_rules_p0/infer_set_operator_distinct/infer_set_operator_distinct.groovy
Labels: reviewed, dev/2.0.4

#27949 [Enhancement](group commit) Add regression case for wal limit
  be/src/http/action/http_stream.cpp
  be/src/http/action/stream_load.cpp
  be/src/http/utils.cpp
  regression-test/data/load_p0/stream_load/test_group_commit_wal_limit.csv.gz
  regression-test/suites/load_p0/stream_load/test_group_commit_wal_limit.groovy
Labels: approved, reviewed

#28020 [chore](log) Add log to trace query cancel
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
Labels: approved, reviewed

#27994 [feature](analyze_cmd) add show-tablets-belong stmt for analyzing a batch of tablet-ids
  docs/en/docs/sql-manual/sql-reference/Show-Statements/SHOW-TABLETS-BELONG.md
  docs/sidebars.json
  docs/zh-CN/docs/sql-manual/sql-reference/Show-Statements/SHOW-TABLETS-BELONG.md
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowTabletsBelongStmt.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/main/jflex/sql_scanner.flex
Labels: reviewed

#28046 [pipelineX](improvement) enable local shuffle by default
  be/src/pipeline/exec/aggregation_sink_operator.cpp
  be/src/pipeline/exec/aggregation_sink_operator.h
  be/src/pipeline/exec/exchange_sink_operator.cpp
  be/src/pipeline/pipeline_x/pipeline_x_fragment_context.cpp
  be/src/pipeline/pipeline_x/pipeline_x_fragment_context.h
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/PhysicalPlanTranslator.java
  fe/fe-core/src/main/java/org/apache/doris/planner/AggregationNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  gensrc/thrift/PlanNodes.thrift
Labels: approved, reviewed, meta-change

#28049 [fix](regression test) fix x load test table name too long
  regression-test/suites/load/insert/test_min_load_replica_num_complicate.groovy
Labels: approved, reviewed

#28064 [feature](nereids) Support to get partition related table from mv and check the query operator
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/MaterializedViewUtils.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/exploration/mv/MaterializedViewUtilsTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/PlanVisitorTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/util/ExpressionUtilsTest.java
Labels: approved, reviewed

#28071 [pipelineX](bug) Fix hash partition shuffle
  be/src/pipeline/exec/exchange_sink_operator.cpp
Labels: approved, reviewed

#28045 [enhance](partitionid) check partition id to avoid unexpected behavior
  be/src/olap/data_dir.cpp
  be/src/olap/rowset/rowset_meta_manager.cpp
  be/src/olap/tablet.cpp
  be/src/olap/tablet_meta_manager.cpp
  be/src/olap/txn_manager.cpp
  be/test/olap/delete_handler_test.cpp
  be/test/olap/delta_writer_test.cpp
  be/test/olap/engine_storage_migration_task_test.cpp
  be/test/olap/remote_rowset_gc_test.cpp
  be/test/olap/tablet_cooldown_test.cpp
  be/test/olap/tablet_mgr_test.cpp
Labels: dev/2.0.3

#28075 [Chore](case) remove dynamic partition on test_delete case
  regression-test/suites/delete_p0/test_delete.groovy
Labels: approved, reviewed, dev/2.0.4

#28059 [minor](s3client) use LOG(INFO) to print s3 client debug log if enabled
  be/src/util/s3_util.cpp
Labels: approved, reviewed, dev/2.0.4

#28050 [Bug](agg-state) fix stream load failed on agg-state column
  fe/fe-core/src/main/java/org/apache/doris/load/Load.java
  regression-test/data/mv_p0/agg_state/test
  regression-test/data/mv_p0/agg_state/test_agg_state_max_by.out
  regression-test/suites/mv_p0/agg_state/test_agg_state_max_by.groovy
Labels: approved, reviewed, dev/2.0.4

#28065 [fix](ci) pass PULL_REQUEST_NUM while trigger new build
  regression-test/pipeline/common/teamcity-utils.sh
Labels: approved, reviewed

#27906 [Config](multi-catalog) Enable query hive views as default.
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
Labels: kind/feature, approved, reviewed, dev/2.0.3-merged

#27951 [minor](orc) opt the log info in orc reader
  be/src/vec/exec/format/orc/vorc_reader.cpp
Labels: approved, reviewed

#27570 [typo](docker) add logs console
  docker/runtime/be/resource/init_be.sh
  docker/runtime/fe/resource/init_fe.sh
Labels: approved, reviewed

#27981 [cleanup](load) remove unused LoadChannel::get_tablets_channels()
  be/src/runtime/load_channel.h
Labels: approved, reviewed

#27609 [fix](doc) spell error and aligned with code
  docs/en/docs/admin-manual/maint-monitor/metadata-operation.md
  docs/zh-CN/docs/admin-manual/maint-monitor/metadata-operation.md
  fe/fe-core/src/main/java/org/apache/doris/master/Checkpoint.java
Labels: approved, reviewed

#27188 [feature](merge-on-write) enable merge-on-write by default
  docs/en/docs/data-table/data-model.md
  docs/en/docs/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-TABLE.md
  docs/zh-CN/docs/data-table/data-model.md
  docs/zh-CN/docs/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-TABLE.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateTableStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/TableProperty.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/CreateTableInfo.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/CreateTableAsSelectStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/CreateTableStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/CreateTableTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/CreateTableCommandTest.java
  regression-test/data/types_p0/unsigned/test_unsigned_int_compatibility.out
  regression-test/suites/cold_heat_separation/empty_table_use_policy/alter_table_add_policy.groovy
  regression-test/suites/cold_heat_separation/empty_table_use_policy/create_table_use_policy.groovy
  regression-test/suites/cold_heat_separation/policy/drop.groovy
  regression-test/suites/data_model_p0/unique/test_unique_table.groovy
  regression-test/suites/data_model_p0/unique/test_unique_table_debug_data.groovy
  regression-test/suites/data_model_p0/unique/test_unique_table_like.groovy
  regression-test/suites/data_model_p0/unique/test_unique_table_new_sequence.groovy
  regression-test/suites/delete_p0/test_delete_on_value.groovy
  regression-test/suites/index_p0/test_bitmap_index.groovy
  regression-test/suites/inverted_index_p0/test_bitmap_index.groovy
  regression-test/suites/mv_p0/unique/unique.groovy
  regression-test/suites/mv_p0/varchar_length/varchar_length.groovy
  regression-test/suites/schema_change_p0/test_alter_table_drop_column.groovy
  regression-test/suites/schema_change_p0/test_rename_column.groovy
  regression-test/suites/schema_change_p0/test_schema_change.groovy
  regression-test/suites/schema_change_p0/test_uniq_delete_sign_schema_change.groovy
  regression-test/suites/update/test_update_unique.groovy
Labels: approved, reviewed

#28054 [feature](workloadgroup) support nereids internal query and all dml query
  fe/fe-core/src/main/java/org/apache/doris/qe/CoordInterface.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/resource/workloadgroup/QueryQueue.java
  fe/fe-core/src/main/java/org/apache/doris/resource/workloadgroup/QueueToken.java
  regression-test/suites/workload_manager_p0/test_curd_wlg.groovy
Labels: approved, reviewed, workload-group

#27992 [typo](test) Use correct sql stmt in regression test
  regression-test/suites/cold_heat_separation_p2/add_drop_partition.groovy
Labels: approved, reviewed, dev/2.0.4

#28080 [opt](resource-tag) root and admin user can use any resource tag by default
  docs/en/docs/admin-manual/multi-tenant.md
  docs/zh-CN/docs/admin-manual/multi-tenant.md
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/CommonUserProperties.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/UserPropertyMgr.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/UserPropertyTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/ResourceTagQueryTest.java
Labels: kind/docs

#28091 [chore](StoragePolicy) Don't print stack when invoking the storage manager
  be/src/olap/storage_policy.cpp
Labels: approved, reviewed

#28077 [improvement](statistics)Analyze empty table.
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/ColStatsData.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/OlapAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatsId.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/util/StatisticsUtil.java
  regression-test/suites/statistics/analyze_stats.groovy
Labels: approved, reviewed, dev/2.0.4

#28058 [test](Job)Delete the JOB show syntax (now we use TVF) and add tvf case
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowJobStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowJobTaskStmt.java
  fe/fe-core/src/main/java/org/apache/doris/job/extensions/insert/InsertTask.java
  fe/fe-core/src/main/java/org/apache/doris/job/extensions/mtmv/MTMVTask.java
  fe/fe-core/src/main/java/org/apache/doris/job/task/Task.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/MetadataGenerator.java
  regression-test/suites/job_p0/test_base_insert_job.groovy
  regression-test/suites/mtmv_p0/test_build_mtmv.groovy
Labels: approved, reviewed

#28048 [fix](profile) fix profile TotalTime is 0ns when pipeline
  be/src/pipeline/pipeline_fragment_context.cpp
Labels: approved, reviewed, dev/2.0.4

#28022 [hotfix](jdbc catalog) fix jdbcmysqlclient npe
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/client/JdbcMySQLClient.java
Labels: dev/2.0.4

#28100 [community](slack)Update slack channel links
  README.md
Labels: approved, reviewed

#28057 [fix](remote-scanner-pool) missing _remote_thread_pool_max_size value
  be/src/vec/exec/scan/scanner_scheduler.cpp
Labels: reviewed, p0_block, dev/2.0.3-merged

#28088 [opt](resource-tag) root and admin user can use any resource tag by default
  docs/en/docs/admin-manual/multi-tenant.md
  docs/zh-CN/docs/admin-manual/multi-tenant.md
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/CommonUserProperties.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/UserPropertyMgr.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/UserPropertyTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/ResourceTagQueryTest.java
Labels: approved, reviewed, dev/2.0.3-merged

#28096 Revert "[feature](merge-on-write) enable merge-on-write by default"
  docs/en/docs/data-table/data-model.md
  docs/en/docs/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-TABLE.md
  docs/zh-CN/docs/data-table/data-model.md
  docs/zh-CN/docs/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-TABLE.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateTableStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/TableProperty.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/CreateTableInfo.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/CreateTableAsSelectStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/CreateTableStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/CreateTableTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/CreateTableCommandTest.java
  regression-test/data/types_p0/unsigned/test_unsigned_int_compatibility.out
  regression-test/suites/cold_heat_separation/empty_table_use_policy/alter_table_add_policy.groovy
  regression-test/suites/cold_heat_separation/empty_table_use_policy/create_table_use_policy.groovy
  regression-test/suites/cold_heat_separation/policy/drop.groovy
  regression-test/suites/data_model_p0/unique/test_unique_table.groovy
  regression-test/suites/data_model_p0/unique/test_unique_table_debug_data.groovy
  regression-test/suites/data_model_p0/unique/test_unique_table_like.groovy
  regression-test/suites/data_model_p0/unique/test_unique_table_new_sequence.groovy
  regression-test/suites/delete_p0/test_delete_on_value.groovy
  regression-test/suites/index_p0/test_bitmap_index.groovy
  regression-test/suites/inverted_index_p0/test_bitmap_index.groovy
  regression-test/suites/mv_p0/unique/unique.groovy
  regression-test/suites/mv_p0/varchar_length/varchar_length.groovy
  regression-test/suites/schema_change_p0/test_alter_table_drop_column.groovy
  regression-test/suites/schema_change_p0/test_rename_column.groovy
  regression-test/suites/schema_change_p0/test_schema_change.groovy
  regression-test/suites/schema_change_p0/test_uniq_delete_sign_schema_change.groovy
  regression-test/suites/update/test_update_unique.groovy
Labels: approved, reviewed

#28029 [fix](move-memtable) temporary disable load stream profile
  be/src/runtime/load_stream.cpp
Labels: approved, reviewed

#28092 [branch-1.2](bug) Fix heap-use-after-free in query cancelled by mem checker when process exceed memory limit
  be/src/runtime/fragment_mgr.cpp
Labels: approved, reviewed

#28104 [Fix](inverted index) fix need read data optimize problem
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
Labels: approved, reviewed

#27972 [refactor](simd_json_reader) refactor simd json parse to adapt stream parse
  be/src/vec/exec/format/json/new_json_reader.cpp
  be/src/vec/exec/format/json/new_json_reader.h
Labels: approved, reviewed

#27961 [imporvement](table property) support for alter table property disable_auto_compaction
  be/src/agent/task_worker_pool.cpp
  fe/fe-core/src/main/java/org/apache/doris/alter/Alter.java
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ModifyTablePropertiesClause.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/TableProperty.java
  fe/fe-core/src/main/java/org/apache/doris/task/UpdateTabletMetaInfoTask.java
  gensrc/thrift/AgentService.thrift
  regression-test/suites/schema_change/test_alter_table_property.groovy
Labels: area/schema-change, approved, reviewed, dev/2.0.4
