Repository apache/doris, pull requests merged in 2023-09, with the labels that each got.

#23610 [Docs] (maint-monitor) when config automatic-service-start, we need config JAVA_HOME in the fe.conf and be.conf firstly
  docs/en/docs/admin-manual/maint-monitor/automatic-service-start.md
  docs/zh-CN/docs/admin-manual/maint-monitor/automatic-service-start.md
Labels: approved, reviewed

#23727 [fix] (mac compile) Fix mac compile error & fe start time related
  be/src/runtime/fragment_mgr.cpp
  fe/fe-core/src/main/java/org/apache/doris/service/ExecuteEnv.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/org/apache/doris/system/Frontend.java
  fe/fe-core/src/main/java/org/apache/doris/system/FrontendHbResponse.java
  fe/fe-core/src/main/java/org/apache/doris/system/HeartbeatMgr.java
  gensrc/thrift/FrontendService.thrift
  gensrc/thrift/HeartbeatService.thrift
Labels: approved, reviewed

#23581 [Fix](column predicate) seperate CHAR primitive type for column predicate
  be/src/exprs/bloom_filter_func.h
  be/src/exprs/create_predicate_function.h
  be/src/olap/like_column_predicate.cpp
  be/src/olap/like_column_predicate.h
  be/src/olap/reader.cpp
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/olap/schema.cpp
  be/src/runtime/primitive_type.h
  be/src/vec/columns/column_dictionary.h
  be/src/vec/columns/predicate_column.h
  be/src/vec/functions/like.cpp
  be/src/vec/functions/like.h
  be/src/vec/olap/block_reader.cpp
  be/src/vec/olap/block_reader.h
Labels: approved, reviewed

#23632 [opt](Nereids) let keywords list same with legacy planner
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisLexer.g4
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/ExpressionEvaluator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/types/DataType.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/types/DataTypeTest.java
Labels: approved, reviewed

#23703 [Improvement](statistics)Show column stats even when error occurred.
  fe/fe-core/src/main/java/org/apache/doris/statistics/ColumnStatistic.java
  regression-test/suites/external_table_p2/hive/test_hive_statistic.groovy
Labels: approved, reviewed, dev/2.0.2

#23574 [Fix](statistics)Fix external table auto analyze bugs.
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Table.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/TableIf.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/external/ExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/external/HMSExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/CatalogIf.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsAutoAnalyzer.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/util/StatisticsUtil.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/StatisticsAutoAnalyzerTest.java
  regression-test/suites/external_table_p2/hive/test_hive_statistic.groovy
Labels: approved, reviewed, dev/2.0.2

#23665 [enhance](policy) Support to change table's storage policy if the two policy has same resource
  docs/en/docs/advanced/cold-hot-separation.md
  docs/zh-CN/docs/advanced/cold-hot-separation.md
  fe/fe-core/src/main/java/org/apache/doris/alter/Alter.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/DataProperty.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/PartitionInfo.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/policy/PolicyMgr.java
  regression-test/suites/cold_heat_separation_p2/add_drop_partition.groovy
  regression-test/suites/cold_heat_separation_p2/create_table_use_dynamic_partition.groovy
Labels: approved, reviewed, dev/2.0.2

#19284 [enhance] use correct default value for show config action
  be/src/common/config.cpp
  regression-test/suites/compaction/test_compaction_cumu_delete.groovy
Labels: approved, reviewed

#23735 [Improve](Job)Job internal interface provides immediate scheduling
  docs/en/docs/sql-manual/sql-reference/Show-Statements/SHOW-JOB.md
  docs/zh-CN/docs/sql-manual/sql-reference/Show-Statements/SHOW-JOB.md
  fe/fe-core/src/main/java/org/apache/doris/scheduler/constants/JobStatus.java
  fe/fe-core/src/main/java/org/apache/doris/scheduler/constants/SystemJob.java
  fe/fe-core/src/main/java/org/apache/doris/scheduler/disruptor/TaskHandler.java
  fe/fe-core/src/main/java/org/apache/doris/scheduler/job/Job.java
  fe/fe-core/src/main/java/org/apache/doris/scheduler/manager/TimerJobManager.java
  fe/fe-core/src/test/java/org/apache/doris/scheduler/disruptor/TimerJobManagerTest.java
Labels: reviewed

#23742 [opt](planner) speed up computeColumnsFilter on ScanNode
  fe/fe-core/src/main/java/org/apache/doris/planner/BackendPartitionedSchemaScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/ScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/ExternalScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/FileQueryScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/hudi/HudiScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/paimon/PaimonScanNode.java
Labels: approved, reviewed, dev/2.0.2

#23664 [fix](date) return right date value even if out of the range of date dictionary
  be/src/service/doris_main.cpp
  be/src/vec/exec/format/orc/vorc_reader.h
  be/src/vec/exec/format/parquet/fix_length_dict_decoder.hpp
  be/src/vec/exec/format/parquet/fix_length_plain_decoder.cpp
  be/src/vec/runtime/vdatetime_value.cpp
  be/src/vec/runtime/vdatetime_value.h
  be/test/vec/exec/parquet/parquet_thrift_test.cpp
  regression-test/data/external_table_p2/hive/test_complex_types.out
  regression-test/suites/external_table_p2/hive/test_complex_types.groovy
Labels: approved, reviewed, dev/2.0.2

#23743 [Improvment](materialized-view) add short circuit for selectBestMV
  fe/fe-core/src/main/java/org/apache/doris/planner/MaterializedViewSelector.java
Labels: approved, reviewed, dev/2.0.2

#23740 [Bug](cte) fix multi cast data stream source not open expr
  be/src/pipeline/exec/multi_cast_data_stream_source.cpp
  regression-test/data/nereids_syntax_p0/cte.out
  regression-test/suites/nereids_syntax_p0/cte.groovy
Labels: approved, reviewed

#23733 [fix](clone) fix cannot further repair clone replica which miss version data
  fe/fe-core/src/main/java/org/apache/doris/catalog/Tablet.java
Labels: approved, reviewed

#23731 [fix](tablet clone) fix tablet sched ctx toString cause null exeption
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletSchedCtx.java
Labels: approved, reviewed, dev/2.0.1

#23729 [fix](tablet clone) fix backend not chose disk based on path hash
  be/src/olap/storage_engine.cpp
  be/src/olap/storage_engine.h
  be/src/olap/task/engine_clone_task.cpp
Labels: approved, reviewed

#17644 [fix](cooldown) Fix potential data loss when clone task's dst tablet is cooldown replica
  be/src/olap/tablet.cpp
  be/src/olap/task/engine_clone_task.cpp
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletSchedCtx.java
Labels: approved, reviewed, dev/2.0.2, p0_data_loss

#23573 [fix](tablet sheduler) change sched period back to 1s
  fe/fe-core/src/main/java/org/apache/doris/common/FeConstants.java
Labels: approved, reviewed, dev/2.0.2

#23723 [chroe](ci) add script for create_issue_comment
  regression-test/pipeline/common/update-or-create-an-issue-comment.sh
Labels: approved, reviewed

#23700 [fix](nereids)NormalizeAggregate may push redundant expr to child project node
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/NormalizeAggregate.java
  regression-test/suites/correctness_p0/test_avg.groovy
Labels: approved, reviewed, dev/2.0.2

#23613 [Fix](Planner) fix create table as select failed
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateTableAsSelectStmt.java
  regression-test/suites/ddl_p0/test_ctas.groovy
Labels: approved, reviewed

#23715 [fix](Nereids) When col stats is Unknow, not expression should return the stats with selectivity of 1
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/FilterEstimation.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/Statistics.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/stats/FilterEstimationTest.java
Labels: approved, reviewed

#23758 [Doc](AuditLoader) improvement auditLoader doc
  docs/en/docs/ecosystem/audit-plugin.md
  docs/zh-CN/docs/ecosystem/audit-plugin.md
Labels: approved, reviewed

#23595 [fix](rest)query_info returns empty rows
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/manager/QueryProfileAction.java
Labels: approved, reviewed

#23746 [improvement](log) optimize template function log for performance
  fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionSet.java
Labels: approved, reviewed, dev/2.0.2-merged

#23720 [doc](alter table) add notes for modify column
  docs/en/docs/sql-manual/sql-reference/Data-Definition-Statements/Alter/ALTER-TABLE-COLUMN.md
  docs/zh-CN/docs/sql-manual/sql-reference/Data-Definition-Statements/Alter/ALTER-TABLE-COLUMN.md
Labels: approved, reviewed

#23694 [Improvement](Slice) support move constructor and operator for Slice
  be/src/util/slice.h
Labels: approved, reviewed

#23738 [branch-2.0](fix) compile error when compiler opens -Werror and -Wunused-result
  be/src/olap/delta_writer.cpp
  be/src/pipeline/pipeline_task.cpp
  be/src/vec/sink/vdata_stream_sender.h
Labels: area/pipeline

#23645 [Branch-2.0](Full compaction) Fix full compaction regressison test (#23487)
  regression-test/data/compaction/test_full_compaction.out
  regression-test/suites/compaction/test_full_compaction.groovy
Labels: kind/test

#23759 [function](bitmap) support bitmap_to_base64 and bitmap_from_base64
  be/src/util/bitmap_value.h
  be/src/vec/functions/function_bitmap.cpp
  be/test/vec/function/function_bitmap_test.cpp
  be/test/vec/function/function_test_util.h
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinScalarFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/BitmapFromBase64.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/BitmapToBase64.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/ScalarFunctionVisitor.java
  gensrc/script/doris_builtins_functions.py
  regression-test/data/query_p0/sql_functions/bitmap_functions/test_bitmap_function.out
  regression-test/suites/query_p0/sql_functions/bitmap_functions/test_bitmap_function.groovy
Labels: approved, reviewed, dev/2.0.2

#23752 [Enhancement](Load) stream tvf support json
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/ExternalFileTableValuedFunction.java
  regression-test/data/load_p0/http_stream/one_array_json.json
  regression-test/data/load_p0/http_stream/test_http_stream_json.out
  regression-test/suites/load_p0/http_stream/test_http_stream_json.groovy
Labels: approved, reviewed

#23411 [fix](json)Fix the bug that read json file Out of bounds access
  be/src/vec/exec/format/json/new_json_reader.cpp
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/json_format_test/nest_json.json
  regression-test/data/external_table_p0/tvf/test_hdfs_tvf.out
  regression-test/pipeline/p0/conf/regression-conf.groovy
Labels: approved, reviewed, dev/2.0.2

#23701 [improvement](config) add a specific be config for segment_cache_capacity
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/runtime/exec_env_init.cpp
  docs/en/docs/admin-manual/config/be-config.md
  docs/zh-CN/docs/admin-manual/config/be-config.md
Labels: approved, reviewed, dev/2.0.2

#23502 [Fix] spark load not found file
  be/src/olap/push_handler.cpp
Labels: approved, reviewed, dev/2.0.2, dev/1.2.8

#23776 [fix](map_agg) lost scale information for decimal type
  be/src/vec/aggregate_functions/aggregate_function_map.h
  fe/fe-core/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java
  regression-test/data/query_p0/aggregate/map_agg.out
  regression-test/suites/query_p0/aggregate/map_agg.groovy
Labels: approved, reviewed, dev/2.0.2

#20932 [fix](be) doris_be compile failed
  be/CMakeLists.txt
  be/src/geo/CMakeLists.txt
Labels: approved, reviewed, dev/2.0.2

#23021 [Feature](Multi-Catalog) support query doris bitmap column in external jdbc catalog
  be/src/runtime/descriptors.h
  be/src/util/bitmap_value.h
  be/src/vec/data_types/data_type_bitmap.cpp
  be/src/vec/data_types/data_type_bitmap.h
  be/src/vec/exec/vjdbc_connector.cpp
  be/src/vec/exec/vjdbc_connector.h
  be/src/vec/functions/function_cast.h
  docs/en/docs/lakehouse/multi-catalog/jdbc.md
  docs/zh-CN/docs/lakehouse/multi-catalog/jdbc.md
  fe/be-java-extensions/jdbc-scanner/src/main/java/org/apache/doris/jdbc/JdbcExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/client/JdbcMySQLClient.java
  regression-test/data/external_table_p0/jdbc/test_doris_jdbc_catalog_query_bitmap.out
  regression-test/suites/external_table_p0/jdbc/test_doris_jdbc_catalog_query_bitmap.groovy
Labels: approved, reviewed, dev/2.0.2

#23773 [Enhancement](binlog) Add ModifyPartition, BatchModifyPartitions && ReplacePartitionOperationLog support
  fe/fe-core/src/main/java/org/apache/doris/binlog/BinlogManager.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/persist/BatchModifyPartitionsInfo.java
  fe/fe-core/src/main/java/org/apache/doris/persist/EditLog.java
  fe/fe-core/src/main/java/org/apache/doris/persist/ReplacePartitionOperationLog.java
  gensrc/thrift/FrontendService.thrift
Labels: approved, reviewed, dev/2.0.2

#23721 [feature](move-memtable) buffer messages in load stream stub
  be/src/runtime/load_stream.cpp
  be/src/runtime/load_stream.h
  be/src/vec/sink/load_stream_stub.cpp
  be/src/vec/sink/load_stream_stub.h
  be/test/runtime/load_stream_test.cpp
Labels: approved, reviewed

#23064 [improvement](colocate table) forbit change colocate table's replica allocation
  fe/fe-core/src/main/java/org/apache/doris/alter/Alter.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/test/java/org/apache/doris/alter/AlterTest.java
  fe/fe-core/src/test/java/org/apache/doris/clone/TabletRepairAndBalanceTest.java
  regression-test/suites/schema_change_p0/test_alter_colocate_table.groovy
Labels: approved, reviewed, dev/2.0.2

#23757 [Fix](thrift) Add fe master check in some thrift calls
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  gensrc/thrift/Status.thrift
Labels: approved, reviewed, dev/2.0.2

#23755 [coverage][test]modify run-be-ut.sh for run be cov, no need merge
  run-be-ut.sh
Labels: approved, reviewed

#23702 [Feature](config) allow update multiple be configs in one request
  be/src/common/config.cpp
  be/src/http/action/config_action.cpp
  docs/en/docs/admin-manual/http-actions/be/config.md
  docs/zh-CN/docs/admin-manual/http-actions/be/config.md
  regression-test/conf/regression-conf.groovy
  regression-test/suites/update/test_update_configs.groovy
Labels: approved, reviewed

#23766 [Fix](IndexColumnWriter) Add logic for `IndexedColumnWriter::add` when the current page is full
  be/src/olap/rowset/segment_v2/indexed_column_writer.cpp
Labels: approved, reviewed

#23679 [Fix](stream load) stearm load record use valid txn info when two txn with same label
  fe/fe-core/src/main/java/org/apache/doris/load/StreamLoadRecordMgr.java
Labels: area/load

#23741 [test](ColdHotSeparation) refresh case
  regression-test/suites/cold_heat_separation/empty_table_use_policy/modify_partition_add_policy.groovy
  regression-test/suites/cold_heat_separation_p2/create_table_use_partition_policy.groovy
  regression-test/suites/cold_heat_separation_p2/table_modify_resouce_and_policy.groovy
Labels: approved, reviewed

#23616 [enhancement](table-meta) flush column unique ids for tables before 1.2 automatically
  docs/en/docs/admin-manual/config/fe-config.md
  docs/en/docs/sql-manual/sql-reference/Show-Statements/SHOW-CONVERT-LIGHR-SCHEMA-CHANGE-PROCESS.md
  docs/zh-CN/docs/admin-manual/config/fe-config.md
  docs/zh-CN/docs/sql-manual/sql-reference/Show-Statements/SHOW-CONVERT-LIGHT-SCHEMA-CHANGE-PROCESS.md
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/alter/AlterLightSchChangeHelper.java
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowConvertLSCStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/ColumnIdFlushDaemon.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/main/jflex/sql_scanner.flex
Labels: approved, reviewed, dev/2.0.2

#23497 [chore](clang-tidy) Apply uninitialized variables check of clang-tidy
  .clang-tidy
Labels: approved, reviewed

#23316 [enhancement](merge-on-write) Add delete bitmap correctness check in commit phase
  be/src/olap/delta_writer.cpp
  be/src/olap/rowset_builder.cpp
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
Labels: approved, reviewed, dev/2.0.2

#22803 [chore](json reader) add original data to error messge for tracing
  be/src/vec/exec/format/json/new_json_reader.cpp
  be/src/vec/exec/format/json/new_json_reader.h
Labels: reviewed, dev/2.0.2

#22798 [Feature](CCR) Support MoW for CCR
  be/src/service/backend_service.cpp
  regression-test/suites/ccr_mow_syncer_p0/test_binlog_config_change.groovy
  regression-test/suites/ccr_mow_syncer_p0/test_create_table_with_binlog_config.groovy
  regression-test/suites/ccr_mow_syncer_p0/test_get_binlog.groovy
  regression-test/suites/ccr_mow_syncer_p0/test_ingest_binlog.groovy
  regression-test/suites/ccr_mow_syncer_p0/test_multi_buckets.groovy
  regression-test/suites/ccr_mow_syncer_p0/test_txn_case.groovy
  regression-test/suites/ccr_mow_syncer_p1/test_backup_restore.groovy
Labels: approved, reviewed, dev/2.0.2

#23247 [enhancement](doc) Lack of detailed parameter documentation
  docs/en/docs/ecosystem/spark-doris-connector.md
  docs/zh-CN/docs/ecosystem/spark-doris-connector.md
Labels: approved, reviewed

#23185 [fix](doc) delete redundant '/' in flink-doris-connector
  docs/en/docs/ecosystem/flink-doris-connector.md
  docs/zh-CN/docs/ecosystem/flink-doris-connector.md
Labels: approved, reviewed

#22475 [fix](doc) modify the document error,about outfile
  docs/en/docs/sql-manual/sql-reference/Data-Manipulation-Statements/OUTFILE.md
  docs/zh-CN/docs/sql-manual/sql-reference/Data-Manipulation-Statements/OUTFILE.md
  fe/.idea/icon.svg
  fe/.idea/vcs.xml
Labels: approved, reviewed

#23784 [Enhance](ip)optimize priority_ network matching logic
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendOptions.java
Labels: reviewed, dev/2.0.2

#23473 [typo](docs) modify standard-deployment doc
  docs/en/docs/install/standard-deployment.md
  docs/zh-CN/docs/install/standard-deployment.md
Labels: approved, reviewed, dev/2.0.2

#23260 [Fix](multi-catalog) Fix zlib init error by using doris's zlib shared library and `jni.log` does not output.
  bin/run-fs-benchmark.sh
  bin/start_be.sh
  build.sh
  thirdparty/build-thirdparty.sh
Labels: approved, reviewed, dev/2.0.2

#22294 [typo](docs) fix docs，characters error
  docs/zh-CN/docs/releasenotes/release-1.2.0.md
Labels: approved, reviewed

#23778 [Fix](vscanner) remove TEMP column in block after filter
  be/src/vec/exec/scan/vscanner.cpp
Labels: approved, reviewed, dev/2.0.2

#21829 [faq](doc) add some FAQ for flink-doris-connector
  docs/en/docs/ecosystem/flink-doris-connector.md
  docs/zh-CN/docs/ecosystem/flink-doris-connector.md
Labels: approved, reviewed, dev/2.0.2

#23785 [regression-test](fix) fix case bug when define local variable
  regression-test/suites/csv_header_p0/test_csv_with_header.groovy
  regression-test/suites/export/test_array_export.groovy
  regression-test/suites/export/test_map_export.groovy
  regression-test/suites/mv_p0/test_dup_mv_year/test_dup_mv_year.groovy
Labels: approved, reviewed, dev/2.0.2

#22687 [Feature](inverted index) push count on index down to scan node
  be/src/olap/rowset/segment_v2/segment.cpp
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/vec/exec/scan/new_olap_scan_node.cpp
  be/src/vec/exec/scan/new_olap_scanner.cpp
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/PhysicalPlanTranslator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/implementation/AggregateStrategies.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalStorageLayerAggregate.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  gensrc/thrift/PlanNodes.thrift
  regression-test/data/inverted_index_p0/documents-1000.json
  regression-test/data/inverted_index_p0/test_count_on_index.out
  regression-test/suites/inverted_index_p0/test_count_on_index.groovy
Labels: approved, reviewed, usercase, dev/2.0.1-merged

#23788 [fix](conf) revert changes in `regression-conf.groovy` in #23702 and fix BE compile error
  be/src/service/backend_service.cpp
  regression-test/conf/regression-conf.groovy
Labels: approved, reviewed

#23791 [fix](doc) Modify README.md Change ‘kafka_default_offset’ to ‘kafka_default_offsets’.
  docs/en/docs/sql-manual/sql-reference/Data-Manipulation-Statements/Load/CREATE-ROUTINE-LOAD.md
  docs/zh-CN/docs/sql-manual/sql-reference/Data-Manipulation-Statements/Load/CREATE-ROUTINE-LOAD.md
Labels: approved, reviewed

#22772 [typo](doc) Modify the error description in the broker-load-manual.
  docs/zh-CN/docs/data-operate/import/import-way/broker-load-manual.md
Labels: approved, reviewed, dev/2.0.2

#21964 [docs] Add BE debug build instruction to docs
  docs/en/docs/install/source-install/compilation-general.md
  docs/en/docs/install/source-install/compilation-with-ldb-toolchain.md
  docs/zh-CN/docs/install/source-install/compilation-general.md
  docs/zh-CN/docs/install/source-install/compilation-with-ldb-toolchain.md
Labels: approved, reviewed

#22776 [fix](sec) upgrade mysql:mysql-connector-java to 8.0.28
  samples/doris-demo/spring-jdbc-demo/pom.xml
Labels: approved, reviewed, dev/2.0.2

#22477 [typo](docs)Correct the odbc markdown comments
  docs/en/docs/advanced/resource.md
  docs/zh-CN/docs/advanced/resource.md
Labels: approved, reviewed

#22797 [typo](docs)Resolved compilation errors caused by using a higher version of Node.js.
  docs/en/community/developer-guide/mac-dev/dev-prepare.md
  docs/zh-CN/community/developer-guide/mac-dev/dev-prepare.md
Labels: approved, reviewed

#22532 [typo][doc]modify tablet_repair_and_balance incorrect parameter description.
  docs/en/docs/admin-manual/maint-monitor/tablet-repair-and-balance.md
  docs/zh-CN/docs/admin-manual/maint-monitor/tablet-repair-and-balance.md
Labels: approved, reviewed

#23609 [typo](docs)Changes to expressions
  docs/en/docs/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-WORKLOAD-GROUP.md
  docs/zh-CN/docs/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-WORKLOAD-GROUP.md
Labels: approved, reviewed, dev/2.0.2

#18889 [regression] Add a case to check if light_schema_change=true when creating table
  regression-test/suites/schema_change_p0/test_light_schema_change_default.groovy
Labels: kind/test, approved, reviewed, dev/2.0.0

#19835 [improvement] delete duplicate code in sql_scanner.flex
  fe/fe-core/src/main/jflex/sql_scanner.flex
Labels: approved, reviewed

#22713 [fix](dpc) Update README.md doris website doc link
  README.md
Labels: approved, reviewed, dev/2.0.2

#23744 [enhancement](jdbc catalog) support postgresql partition table
  docker/thirdparties/docker-compose/postgresql/init/02-create-table.sql
  docker/thirdparties/docker-compose/postgresql/init/04-insert.sql
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/client/JdbcPostgreSQLClient.java
  regression-test/data/external_table_p0/jdbc/test_pg_jdbc_catalog.out
  regression-test/suites/external_table_p0/jdbc/test_pg_jdbc_catalog.groovy
Labels: approved, reviewed, dev/2.0.2

#21664 [fix](doc)description of unique
  docs/en/docs/sql-manual/sql-reference/Data-Manipulation-Statements/Load/BROKER-LOAD.md
  docs/zh-CN/docs/data-table/data-model.md
  docs/zh-CN/docs/sql-manual/sql-reference/Data-Manipulation-Statements/Load/BROKER-LOAD.md
Labels: kind/docs, approved, reviewed, dev/2.0.2

#17730 [fix](load) fix cancel load failed because Job could not be cancelled…
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadManager.java
Labels: area/load, approved, reviewed, kind/behavior-changed, dev/2.0.2

#23736 [pipelineX](minor) Add type check for cast
  be/src/pipeline/pipeline_x/operator.h
Labels: approved, reviewed

#20622 [fix](fe) Support set hive version when create hive external table
  fe/fe-core/src/main/java/org/apache/doris/catalog/HiveTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/HiveTableTest.java
Labels: approved, reviewed, dev/2.0.2

#20798 [improve](spark-load) set status fail message when spark load job cancel.
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkEtlJobHandler.java
Labels: area/load, approved, reviewed, dev/2.0.2

#22715 [typo](doc) modify error description in OUTFILE.
  docs/en/docs/sql-manual/sql-reference/Data-Manipulation-Statements/OUTFILE.md
  docs/zh-CN/docs/sql-manual/sql-reference/Data-Manipulation-Statements/OUTFILE.md
Labels: approved, reviewed

#22834 [typo](docs) add comment of audit plugin
  docs/en/docs/ecosystem/audit-plugin.md
  docs/zh-CN/docs/ecosystem/audit-plugin.md
Labels: approved, reviewed

#21852 [Test](Framework) add enable cache data args for test CommandLine
  regression-test/framework/src/main/groovy/org/apache/doris/regression/Config.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/ConfigOptions.groovy
Labels: approved, reviewed

#23680 [enhancement](load) support dry_run_query for load
  be/src/vec/sink/vtablet_sink.cpp
  be/src/vec/sink/vtablet_sink_v2.cpp
  docs/en/docs/advanced/variables.md
  docs/zh-CN/docs/advanced/variables.md
Labels: dev/2.0.2

#22491 [typo][doc]modify some error descriptions.
  docs/en/docs/admin-manual/maint-monitor/metadata-operation.md
  docs/zh-CN/docs/admin-manual/maint-monitor/metadata-operation.md
Labels: approved, reviewed

#23792 [improvement](show backends) show backends print trash used
  be/src/agent/task_worker_pool.cpp
  be/src/agent/task_worker_pool.h
  be/src/olap/data_dir.cpp
  be/src/olap/data_dir.h
  be/src/olap/olap_common.h
  be/src/olap/storage_engine.cpp
  be/src/olap/storage_engine.h
  be/src/service/backend_service.cpp
  fe/fe-core/src/main/java/org/apache/doris/catalog/DiskInfo.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/BackendsProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/system/Backend.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/BackendsTableValuedFunction.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/MetadataGenerator.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/DemoMultiBackendsTest.java
  gensrc/thrift/MasterService.thrift
  regression-test/suites/external_table_p0/tvf/test_backends_tvf.groovy
  regression-test/suites/nereids_syntax_p0/information_schema.groovy
Labels: approved, reviewed, dev/2.0.2

#23713 [refactor](join) improve join node output when build table rows is 0
  be/src/vec/exec/join/vhash_join_node.cpp
  be/src/vec/exec/join/vhash_join_node.h
  be/src/vec/exec/join/vjoin_node_base.h
  be/src/vec/utils/util.hpp
Labels: approved, usercase, dev/2.0.2

#23812 [Bug](case) remove wrong case from master
  regression-test/suites/nereids_syntax_p0/cte.groovy
Labels: kind/test

#23763 [opt](Nereids) use avl tree to construct continuous union operand
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
Labels: approved, reviewed, dev/2.0.2

#23813 [community](collaborator) add collaborator shuke987 for issue/pr label
  .asf.yaml
Labels: reviewed

#23796 [regression](inverted index) force nereids open for count on index
  regression-test/suites/inverted_index_p0/test_count_on_index.groovy
Labels: approved, reviewed, dev/2.0.2

#23807 [docs](releasenote) 2.0.1&1.2.7 release note
  README.md
  docs/en/docs/releasenotes/release-1.2.7.md
  docs/en/docs/releasenotes/release-2.0.1.md
  docs/sidebars.json
  docs/zh-CN/docs/releasenotes/release-1.2.7.md
  docs/zh-CN/docs/releasenotes/release-2.0.1.md
Labels: approved, reviewed

#23815 [fix](pipeline) Fix cancel_query locks nothing
  be/src/runtime/fragment_mgr.cpp
Labels: approved, reviewed

#23683 [typo](doc) description of datetime in DATETIME.md
  docs/zh-CN/docs/sql-manual/sql-reference/Data-Types/DATETIME.md
Labels: approved, reviewed

#23652 [docs] Correct spelling of words
  docs/zh-CN/docs/install/construct-docker/build-docker-image.md
Labels: approved, reviewed

#23817 [bugfix](fragment mgr) heap used after free in fragment manager when query is cancelled
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/fragment_mgr.h
Labels: approved, reviewed, dev/2.0.2

#23821 [chore](idea) add back .idea dir under fe
  fe/.idea/icon.svg
  fe/.idea/vcs.xml
Labels: approved, reviewed

#23829 [bugfix](topn) fix miss-use of unique_id causing vector buffer overflow
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  regression-test/suites/datatype_p0/scalar_types/load.groovy
  regression-test/suites/datatype_p2/scalar_types/load.groovy
Labels: kind/test, approved, reviewed

#23823 [pipelineX](fix) fix correctness problem
  be/src/pipeline/exec/hashjoin_probe_operator.cpp
  be/src/pipeline/exec/hashjoin_probe_operator.h
  be/src/pipeline/exec/nested_loop_join_probe_operator.cpp
  be/src/pipeline/exec/nested_loop_join_probe_operator.h
  be/src/pipeline/pipeline_x/dependency.h
  be/src/pipeline/pipeline_x/operator.cpp
  be/src/pipeline/pipeline_x/operator.h
Labels: approved, reviewed

#23801 [fix](row-policy) fix creating row policy with forward issue
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/CreatePolicyCommand.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
  tools/single-node-cluster/multi-fe
Labels: approved, reviewed, usercase, dev/2.0.2

#23750 [pipelineX](refactor) add repeat node in pipelineX
  be/src/pipeline/exec/repeat_operator.cpp
  be/src/pipeline/exec/repeat_operator.h
  be/src/pipeline/pipeline_x/operator.cpp
  be/src/pipeline/pipeline_x/operator.h
  be/src/pipeline/pipeline_x/pipeline_x_fragment_context.cpp
  regression-test/data/pipelineX/test_repeat_operator.out
  regression-test/suites/pipelineX/test_repeat_operator.groovy
Labels: approved, reviewed

#23754 [feature](nereids) eliminate cascading outer join
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/EliminateOuterJoin.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/JoinUtils.java
Labels: approved, reviewed

#23830 [bugfix](topn) fix topn be inoperative because Field == Null always return true
  be/src/vec/exec/vsort_node.cpp
Labels: approved, reviewed, dev/2.0.2

#23811 [fix](testcase) sync load of tpcds_sf1_index testcase from tpcds_sf1_p1
  regression-test/suites/inverted_index_p1/tpcds_sf1_index/load.groovy
Labels: approved, reviewed, dev/2.0.2

#23848 [fix] fix case test_external_catalog_es
  regression-test/data/external_table_p2/es/test_external_catalog_es.out
  regression-test/suites/external_table_p2/es/test_external_catalog_es.groovy
Labels: kind/test, approved, reviewed

#23622 [enhancement](stats) Split period from auto collector
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Table.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/TableIf.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/external/ExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisInfo.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisManager.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisTaskExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/OlapAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsAutoCollector.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsCollector.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsPeriodCollector.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/TableStats.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/StatisticsAutoCollectorTest.java
  regression-test/suites/statistics/analyze_stats.groovy
Labels: approved, reviewed

#23850 [fix](nereids)missing return value of resetLogicalProperties()
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/RecomputeLogicalPropertiesProcessor.java
  regression-test/data/nereids_syntax_p0/join_order.out
  regression-test/suites/nereids_syntax_p0/join_order.groovy
Labels: approved, reviewed, dev/2.0.2, p0_crash, p0_wrong_result

#23840 [Bug](compare) fix core dump on decimal128 when be is build by debug mode
  be/src/olap/comparison_predicate.h
  be/src/vec/core/types.h
Labels: approved, reviewed

#23805 [doc](bitmap) add docs from bitmap_to_base64 and bitmap_from_base64
  docs/en/docs/sql-manual/sql-functions/bitmap-functions/bitmap-from-base64.md
  docs/en/docs/sql-manual/sql-functions/bitmap-functions/bitmap-from-string.md
  docs/en/docs/sql-manual/sql-functions/bitmap-functions/bitmap-to-base64.md
  docs/zh-CN/docs/sql-manual/sql-functions/bitmap-functions/bitmap-from-base64.md
  docs/zh-CN/docs/sql-manual/sql-functions/bitmap-functions/bitmap-from-string.md
  docs/zh-CN/docs/sql-manual/sql-functions/bitmap-functions/bitmap-to-base64.md
Labels: approved, reviewed

#23857 [pipelineX](feature) support assert rows num operator
  be/src/pipeline/exec/assert_num_rows_operator.cpp
  be/src/pipeline/exec/assert_num_rows_operator.h
  be/src/pipeline/exec/hashjoin_probe_operator.cpp
  be/src/pipeline/exec/hashjoin_probe_operator.h
  be/src/pipeline/exec/join_probe_operator.h
  be/src/pipeline/exec/nested_loop_join_probe_operator.cpp
  be/src/pipeline/exec/nested_loop_join_probe_operator.h
  be/src/pipeline/exec/repeat_operator.cpp
  be/src/pipeline/exec/repeat_operator.h
  be/src/pipeline/pipeline_x/operator.cpp
  be/src/pipeline/pipeline_x/operator.h
  be/src/pipeline/pipeline_x/pipeline_x_fragment_context.cpp
Labels: approved, reviewed

#23426 [fix](auth)fix after setting the user password to expire, changing the password again will not take effect
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/PasswordPolicy.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/PasswordPolicyManager.java
  regression-test/suites/account_p0/test_alter_user.groovy
Labels: approved, reviewed, dev/2.0.2

#23884 disable unstable case in dir nereids_tpcds_shape_sf100_p0
  regression-test/pipeline/p0/conf/regression-conf.groovy
Labels: approved, reviewed

#23838 [fix](regressionTest) fix `test_external_catalog_es` p2 regression test
  regression-test/suites/external_table_p2/es/test_external_catalog_es.groovy
Labels: approved, reviewed, dev/2.0.2

#23828 [fix](stacktrace) Fix StackTraceCache initialized before ExecEnv
  be/src/common/stack_trace.cpp
  be/src/common/stack_trace.h
  be/src/service/doris_main.cpp
Labels: approved, reviewed

#23869 [bugfix](regression-test) Repeated create user during parallel testing
  regression-test/suites/ccr_syncer_p0/test_get_binlog.groovy
  regression-test/suites/ccr_syncer_p0/test_txn_case.groovy
Labels: approved, reviewed

#23861 [chore](macOS) Fix invalid option errors in start_be.sh
  bin/start_be.sh
Labels: approved, reviewed, dev/2.0.2, dev/1.2.8

#23856 [fix](load) add lock for serialize profile
  be/src/runtime/load_channel.cpp
  be/src/runtime/load_channel.h
Labels: approved, reviewed

#23832 [fix](RemoteUDF) fix string type do not set PGenericType
  be/src/vec/data_types/serde/data_type_string_serde.cpp
  docs/en/docs/ecosystem/udf/remote-user-defined-function.md
  docs/zh-CN/docs/ecosystem/udf/remote-user-defined-function.md
  samples/doris-demo/remote-udf-java-demo/src/main/java/org/apache/doris/udf/FunctionServiceImpl.java
Labels: approved, reviewed, dev/2.0.2

#18891 [Improve](be)check swap
  bin/start_be.sh
Labels: approved, reviewed, dev/2.0.2

#23865 [improvement](graceful shutdown) waiting for all query finished when graceful shutdown
  be/src/agent/heartbeat_server.cpp
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/runtime/exec_env.cpp
  be/src/runtime/exec_env.h
  be/src/runtime/fragment_mgr.h
  be/src/service/doris_main.cpp
  docs/en/docs/admin-manual/config/be-config.md
  docs/zh-CN/docs/admin-manual/config/be-config.md
  fe/fe-core/src/main/java/org/apache/doris/system/Backend.java
  fe/fe-core/src/main/java/org/apache/doris/system/BackendHbResponse.java
  fe/fe-core/src/main/java/org/apache/doris/system/HeartbeatMgr.java
  fe/fe-core/src/test/java/org/apache/doris/system/SystemInfoServiceTest.java
  gensrc/thrift/HeartbeatService.thrift
Labels: approved, reviewed, dev/2.0.2

#23877 [pipelineX](feature) support empty set operator
  be/src/pipeline/exec/empty_set_operator.cpp
  be/src/pipeline/exec/empty_set_operator.h
  be/src/pipeline/pipeline_x/operator.cpp
  be/src/pipeline/pipeline_x/pipeline_x_fragment_context.cpp
Labels: approved, reviewed

#23876 [pipelineX](join) Support shared hash table
  be/src/pipeline/exec/hashjoin_build_sink.cpp
  be/src/pipeline/exec/hashjoin_build_sink.h
  be/src/pipeline/pipeline_x/operator.h
  be/src/pipeline/pipeline_x/pipeline_x_task.cpp
  be/src/pipeline/pipeline_x/pipeline_x_task.h
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/fragment_mgr.h
  be/src/vec/runtime/shared_hash_table_controller.cpp
  be/src/vec/runtime/shared_hash_table_controller.h
Labels: approved, reviewed

#22547 [test](regression) Reduce dependency of other database in `test_alter_table_column`
  regression-test/data/schema_change_p0/baseall.txt
  regression-test/suites/schema_change_p0/test_alter_table_column.groovy
Labels: approved, reviewed, dev/2.0.2

#23888 [Refactor](transformer) convert to file format writer to transformer
  be/src/vec/runtime/vcsv_transformer.cpp
  be/src/vec/runtime/vcsv_transformer.h
  be/src/vec/runtime/vfile_writer_wrapper.h
  be/src/vec/runtime/vorc_transformer.cpp
  be/src/vec/runtime/vorc_transformer.h
  be/src/vec/runtime/vparquet_transformer.cpp
  be/src/vec/runtime/vparquet_transformer.h
  be/src/vec/sink/writer/vfile_result_writer.cpp
  be/src/vec/sink/writer/vfile_result_writer.h
Labels: approved, reviewed

#23872 [fix](inverted)fix inverted index report be hostname error
  be/src/agent/task_worker_pool.cpp
  be/src/agent/task_worker_pool.h
Labels: approved, reviewed, dev/2.0.2

#23878 [fix](UT)fix coverage compute fail if run string cmd directly
  run-be-ut.sh
Labels: approved, reviewed

#23866 [fix](FoldConstant) with FoldConstant in be without DATETIMEV2
  be/src/runtime/fold_constant_executor.cpp
Labels: approved, reviewed, dev/1.2.8

#23797 [Enhancement](Load) stream tvf support csv header
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/ExternalFileTableValuedFunction.java
  regression-test/data/load_p0/http_stream/student_with_names.csv
  regression-test/data/load_p0/http_stream/student_with_names_and_types.csv
  regression-test/data/load_p0/http_stream/test_http_stream_csv_with_names.out
  regression-test/data/load_p0/http_stream/test_http_stream_csv_with_names_and_types.out
  regression-test/suites/load_p0/http_stream/test_http_stream_csv_with_names.groovy
  regression-test/suites/load_p0/http_stream/test_http_stream_csv_with_names_and_types.groovy
Labels: approved, reviewed

#23874 [Fix](Plan)StreamLoad cannot be parsed correctly when it contains complex where conditions
  fe/fe-core/src/main/java/org/apache/doris/planner/StreamLoadPlanner.java
  regression-test/data/load_p0/stream_load/test_include_where_expr.json
  regression-test/suites/load_p0/stream_load/test_stream_load_include_where_expr.groovy
Labels: approved, reviewed, dev/2.0.2

#23819 [Fix](bitmap index) like predicate does not work in bitmap index
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  regression-test/data/inverted_index_p0/test_index_like_select.out
  regression-test/suites/inverted_index_p0/test_index_like_select.groovy
Labels: approved, reviewed, usercase, dev/2.0.2

#23880 [typo](docs) remove redundant column data from the insert statement
  docs/zh-CN/docs/sql-manual/sql-reference/Data-Manipulation-Statements/Manipulation/UPDATE.md
Labels: approved, reviewed

#23887 [improvemnt](script) support custom lib dir to save custom libs
  bin/start_be.sh
  bin/start_fe.sh
  docs/en/docs/lakehouse/faq.md
  docs/en/docs/lakehouse/multi-catalog/jdbc.md
  docs/en/docs/lakehouse/multi-catalog/paimon.md
  docs/zh-CN/docs/lakehouse/faq.md
  docs/zh-CN/docs/lakehouse/multi-catalog/jdbc.md
  docs/zh-CN/docs/lakehouse/multi-catalog/paimon.md
Labels: approved, reviewed, usercase, dev/2.0.2

#16202 [fix](spark load) not setting the file format cause null pointer exception
  fe/spark-dpp/src/main/java/org/apache/doris/load/loadv2/dpp/SparkDpp.java
Labels: kind/docs, area/planner, kind/test, approved, reviewed, area/nereids, dev/2.0.2, dev/1.2.8

#23768 [feature](nereids) pr#23767 for 2.0 branch: push runtime filter to right child of left outer join
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/RuntimeFilterGenerator.java
Labels: area/nereids

#23820 [fix](Nereids) set operation syntax is not compatible with legacy planner
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/FunctionBinder.java
  regression-test/suites/nereids_syntax_p0/cte.groovy
Labels: kind/test, area/nereids, dev/2.0.2-merged

#23896 [pick](predicate) Pick refactor predicate to branch-2.0
  be/src/olap/delete_handler.cpp
  be/src/olap/predicate_creator.h
  be/src/olap/reader.cpp
Labels: dev/2.0.2-merged

#23893 [fix](env)fix feut failed by mockit error
  fe/fe-core/src/test/java/org/apache/doris/analysis/AccessTestUtil.java
Labels: approved, reviewed

#23899 [typo](docs) Add some explanations about AUTO_INCREMENT columns
  docs/en/docs/advanced/variables.md
  docs/zh-CN/docs/advanced/variables.md
Labels: approved, reviewed

#23561 [improve](segment-cache) Change the segment cache granularity from rowset_id to rowset_id+segment_id
  be/src/olap/rowset/beta_rowset.cpp
  be/src/olap/rowset/beta_rowset.h
  be/src/olap/segment_loader.cpp
  be/src/olap/segment_loader.h
  be/src/olap/tablet_manager.cpp
  be/src/olap/txn_manager.cpp
Labels: approved, reviewed

#23714 [fix](nereids)fix CheckPolicy not match uniqueTable in nereids
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/CheckPolicy.java
  fe/fe-core/src/test/java/org/apache/doris/policy/PolicyTest.java
Labels: approved, reviewed, dev/2.0.2

#23901 [feature-wip](arrow-flight) BE not start Arrow Flight Service by default
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/service/arrow_flight/flight_sql_service.cpp
  conf/be.conf
Labels: approved, reviewed

#23907 [fix](shared hash table) fix p0 test failure
  be/src/vec/runtime/shared_hash_table_controller.cpp
Labels: approved, reviewed

#23853 [feat](optimizer) Auto upgrade column_statistics from 1.2
  fe/fe-core/src/main/java/org/apache/doris/catalog/InternalSchemaInitializer.java
Labels: approved, reviewed, dev/2.0.2

#23916 [bugfix](map) fix map offset column DCHECK nullptr
  be/src/olap/rowset/segment_v2/column_writer.cpp
Labels: reviewed

#23751 [Improvement](test)Add property to support manually use auto analyzer to analyze db.
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisManager.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsAutoCollector.java
  regression-test/suites/external_table_p2/hive/test_hive_statistic_auto.groovy
Labels: approved, reviewed, dev/2.0.2

#23753 [feature](information_schema)add metadata_name_ids for quickly get catlogs,db,table and add profiling table in order to Compatible with mysql (#22702)
  be/src/exec/schema_scanner.cpp
  be/src/exec/schema_scanner/schema_helper.cpp
  be/src/exec/schema_scanner/schema_helper.h
  be/src/exec/schema_scanner/schema_metadata_name_ids_scanner.cpp
  be/src/exec/schema_scanner/schema_metadata_name_ids_scanner.h
  be/src/exec/schema_scanner/schema_profiling_scanner.cpp
  be/src/exec/schema_scanner/schema_profiling_scanner.h
  be/src/pipeline/pipeline_task.cpp
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SchemaTableType.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/SchemaTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  gensrc/thrift/Descriptors.thrift
  gensrc/thrift/FrontendService.thrift
  regression-test/data/query_p0/system/test_metadata_name_ids.out
  regression-test/data/query_p0/system/test_query_sys_tables.out
  regression-test/suites/query_p0/system/test_metadata_name_ids.groovy
  regression-test/suites/query_p0/system/test_query_sys_tables.groovy
Labels: area/planner, kind/test, area/pipeline

#23847 [improvement](fe-meta) check the image's meta version
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
Labels: approved, reviewed, dev/2.0.2

#23922 [enhancement](Nereids): remove useless if-condition
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/StatsCalculator.java
Labels: approved, reviewed

#23818 [Fix](inverted index) need_read_data only supports DUP_KEYS
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  regression-test/data/index_p0/test_bitmap_index.out
  regression-test/suites/index_p0/test_bitmap_index.groovy
Labels: dev/2.0.2

#23745 [opt](hudi) reduce the memory usage of avro reader
  fe/be-java-extensions/hudi-scanner/src/main/java/org/apache/doris/hudi/HudiJniScanner.java
  fe/be-java-extensions/hudi-scanner/src/main/scala/org/apache/doris/hudi/BaseSplitReader.scala
Labels: reviewed, dev/2.0.2
