Repository apache/doris, pull requests merged in 2023-08, with the labels that each got.

#22407 [opt](conf) Modify brpc eovercrowded conf
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/pipeline/exec/exchange_sink_buffer.cpp
  be/src/service/brpc_service.cpp
  be/src/vec/sink/vdata_stream_sender.cpp
Labels: approved, reviewed, dev/2.0.0

#22218 [Improvement](shuffle) Accumulate rows in a batch for shuffling
  be/src/vec/sink/vdata_stream_sender.cpp
  be/src/vec/sink/vdata_stream_sender.h
  be/test/vec/runtime/vdata_stream_test.cpp
Labels: approved, reviewed

#22441 [regression](fix) fix test_round case
  regression-test/data/query_p0/sql_functions/math_functions/test_round.out
  regression-test/suites/query_p0/sql_functions/math_functions/test_round.groovy
Labels: approved, reviewed, dev/2.0.0

#22443 Revert "[fix](show-stmt) fix show create table missing storage_medium info (#21757)"
  fe/fe-core/src/main/java/org/apache/doris/catalog/DataProperty.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/CreateTableAsSelectStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/CreateTableTest.java
Labels: approved, reviewed, dev/2.0.0-merged

#22416 [fix](window_funnel_function) fix upgrade compatibility due to the added field in `WindowFunnelState`
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/vec/aggregate_functions/aggregate_function_window_funnel.h
  regression-test/suites/nereids_p0/aggregate/window_funnel.groovy
  regression-test/suites/query_p0/aggregate/window_funnel.groovy
Labels: approved, reviewed, dev/2.0.0

#22384 [Opt](exec) opt the performance of date parquet convert by date dict
  be/src/service/doris_main.cpp
  be/src/vec/exec/format/parquet/decoder.cpp
  be/src/vec/exec/format/parquet/fix_length_dict_decoder.hpp
  be/src/vec/exec/format/parquet/fix_length_plain_decoder.cpp
  be/src/vec/runtime/vdatetime_value.cpp
  be/src/vec/runtime/vdatetime_value.h
  be/test/vec/exec/parquet/parquet_thrift_test.cpp
Labels: approved, reviewed, dev/2.0.0

#22264 [feature](Nereids): pushdown MIN/MAX/SUM through join
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/joinorder/hypergraph/Node.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/joinorder/hypergraph/receiver/PlanReceiver.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/EagerGroupByCount.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/EagerSplit.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/join/PushdownProjectThroughInnerOuterJoin.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/join/PushdownProjectThroughSemiJoin.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PushdownMinMaxThroughJoin.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PushdownSumThroughJoin.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/Statistics.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/PushdownMinMaxThroughJoinTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/PushdownSumThroughJoinTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/util/PlanChecker.java
Labels: approved, reviewed

#22437 [fix](merge-on-write) fix duplicate keys occur when be restart
  be/src/olap/tablet_meta.cpp
Labels: approved, reviewed, dev/2.0.0

#22431 [fix](vertical compaction) compaction block reader should return error when reading next block failed
  be/src/vec/olap/block_reader.cpp
  be/src/vec/olap/olap_data_convertor.cpp
  be/src/vec/olap/vertical_block_reader.cpp
Labels: approved, reviewed, dev/2.0.0

#22350 [Chore](materialized-view) update documentation about materialized-view and update test
  docs/en/docs/query-acceleration/materialized-view.md
  docs/zh-CN/docs/query-acceleration/materialized-view.md
  regression-test/data/mv_p0/test_doc_e4/test_doc_e4.out
  regression-test/suites/mv_p0/test_doc_e4/test_doc_e4.groovy
Labels: approved, reviewed

#22269 [feature](time) using timev2 type to replace the old time type.
  be/src/util/date_func.cpp
  be/src/vec/data_types/data_type_factory.cpp
  be/src/vec/data_types/data_type_time.h
  be/src/vec/data_types/serde/data_type_time_serde.h
  be/src/vec/functions/function_cast.h
  be/src/vec/functions/function_date_or_datetime_computation.h
  be/src/vec/functions/function_running_difference.h
  be/test/vec/function/function_running_difference_test.cpp
  be/test/vec/function/function_time_test.cpp
Labels: approved, reviewed, dev/2.0.1

#22434 [fix](Nereids) fix test framework of hypergraph
  fe/fe-core/src/test/java/org/apache/doris/nereids/util/HyperGraphBuilder.java
Labels: approved, reviewed

#22421 [stats](nereids) fix bug for avg-size
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/FilterEstimation.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/ColumnStatistic.java
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query65.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query72.out
  regression-test/data/nereids_tpch_shape_sf1000_p0/shape/q22.out
  regression-test/data/nereids_tpch_shape_sf500_p0/shape/q22.out
Labels: approved, reviewed

#22452 [test]Add regression test for workload manager
  regression-test/pipeline/p1/conf/regression-conf.groovy
  regression-test/suites/workload_manager_p1/basic_workload_group_test.groovy
  regression-test/suites/workload_manager_p1/query/bquery1
Labels: approved, reviewed, workload-group

#22404 [fix][regression-test] change lazy open regression test name
  be/src/runtime/tablets_channel.cpp
  be/src/runtime/tablets_channel.h
  be/src/vec/sink/vtablet_sink.h
  regression-test/suites/rollup_p0/test_materialized_view_load_open.groovy
Labels: approved, reviewed

#22448 [be](parameter) change default fragment_pool_thread_num_max from 512 to 2048
  be/src/common/config.cpp
  docs/en/docs/admin-manual/config/be-config.md
  docs/zh-CN/docs/admin-manual/config/be-config.md
Labels: approved, reviewed, dev/2.0.0

#22046 [fix](DOE)es catalog not working with pipeline,datetimev2, array and esquery
  be/src/exec/es/es_scroll_parser.cpp
  be/src/pipeline/pipeline_fragment_context.cpp
  fe/fe-core/src/main/java/org/apache/doris/external/elasticsearch/QueryBuilders.java
  regression-test/data/es_p0/test_es_query.out
  regression-test/suites/es_p0/test_es_query.groovy
Labels: approved, reviewed, dev/2.0.0

#22450 [fix](decimal) fix cast rounding half up with negative number
  be/src/vec/data_types/data_type_decimal.h
  regression-test/data/correctness/test_cast_as_decimalv3.out
  regression-test/suites/correctness/test_cast_as_decimalv3.groovy
Labels: approved, reviewed, dev/2.0.0

#22424 [fix](multi-catalog)fix compatible with hdfs HA empty prefix
  docs/en/docs/lakehouse/multi-catalog/iceberg.md
  docs/zh-CN/docs/lakehouse/multi-catalog/iceberg.md
  fe/fe-core/src/main/java/org/apache/doris/catalog/HdfsResource.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/S3Util.java
Labels: approved, reviewed, dev/2.0.0

#22466 [fix](nereids)fix bug of cast expr to decimalv3 without any check
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/SimplifyComparisonPredicate.java
  regression-test/suites/nereids_syntax_p0/test_simplify_comparison.groovy
Labels: approved, reviewed, dev/2.0.0

#22461 [improvement](compaction) compaction policy and options in the properties of a table
  be/src/agent/task_worker_pool.cpp
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/http/action/compaction_action.cpp
  be/src/olap/compaction.cpp
  be/src/olap/cumulative_compaction_policy.cpp
  be/src/olap/cumulative_compaction_policy.h
  be/src/olap/cumulative_compaction_time_series_policy.cpp
  be/src/olap/cumulative_compaction_time_series_policy.h
  be/src/olap/olap_server.cpp
  be/src/olap/storage_engine.h
  be/src/olap/tablet.cpp
  be/src/olap/tablet_manager.cpp
  be/src/olap/tablet_manager.h
  be/src/olap/tablet_meta.cpp
  be/src/olap/tablet_meta.h
  be/test/olap/cumulative_compaction_policy_test.cpp
  be/test/olap/cumulative_compaction_time_series_policy_test.cpp
  docs/en/docs/admin-manual/config/be-config.md
  docs/en/docs/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-TABLE.md
  docs/zh-CN/docs/admin-manual/config/be-config.md
  docs/zh-CN/docs/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-TABLE.md
  fe/fe-core/src/main/java/org/apache/doris/alter/Alter.java
  fe/fe-core/src/main/java/org/apache/doris/alter/AlterOperations.java
  fe/fe-core/src/main/java/org/apache/doris/alter/RollupJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ModifyTablePropertiesClause.java
  fe/fe-core/src/main/java/org/apache/doris/backup/RestoreJob.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/TableProperty.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/master/ReportHandler.java
  fe/fe-core/src/main/java/org/apache/doris/task/CreateReplicaTask.java
  fe/fe-core/src/main/java/org/apache/doris/task/UpdateTabletMetaInfoTask.java
  fe/fe-core/src/test/java/org/apache/doris/task/AgentTaskTest.java
  gensrc/proto/olap_file.proto
  gensrc/thrift/AgentService.thrift
  regression-test/suites/compaction/test_table_level_compaction_policy.groovy
Labels: approved, reviewed, dev/2.0.0

#22427 [opt](conf) remote scanner thread num is changed to core num * 10
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/vec/exec/scan/scanner_scheduler.cpp
  bin/start_be.sh
  conf/be.conf
Labels: approved, reviewed, dev/2.0.0

#22480 [fix](multi-catalog)compatible with hdfs HA empty prefix
  docs/en/docs/lakehouse/multi-catalog/iceberg.md
  docs/zh-CN/docs/lakehouse/multi-catalog/iceberg.md
  fe/fe-core/src/main/java/org/apache/doris/catalog/HdfsResource.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/S3Util.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HiveMetaStoreCache.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/iceberg/IcebergScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/iceberg/IcebergSplit.java
Labels: kind/docs, area/planner

#22469 [fix](fe) Fix stmt forward
  fe/fe-core/src/main/java/org/apache/doris/qe/MasterOpExecutor.java
Labels: approved, reviewed

#22327 [Improvement](aggregation) optimization for aggregation hash_table_lazy_emplace
  be/src/vec/aggregate_functions/aggregate_function_uniq.h
  be/src/vec/common/aggregation_common.h
  be/src/vec/common/columns_hashing.h
  be/src/vec/common/columns_hashing_impl.h
  be/src/vec/common/hash_table/fixed_hash_table.h
  be/src/vec/common/hash_table/hash.h
  be/src/vec/common/hash_table/hash_table_key_holder.h
  be/src/vec/common/hash_table/ph_hash_map.h
  be/src/vec/common/memcpy_small.h
  be/src/vec/exec/distinct_vaggregation_node.cpp
  be/src/vec/exec/distinct_vaggregation_node.h
  be/src/vec/exec/vaggregation_node.cpp
  be/src/vec/exec/vaggregation_node.h
  be/src/vec/exec/vpartition_sort_node.cpp
Labels: approved, reviewed

#22411 [fix](string-column) fix unescape result length error
  be/src/exec/text_converter.cpp
Labels: approved, reviewed, dev/2.0.1

#22483 [Fix](test)exclude workload group test default
  regression-test/pipeline/p0/conf/regression-conf.groovy
  regression-test/pipeline/p1/conf/regression-conf.groovy
Labels: approved, reviewed, workload-group

#22489 [fix](nereids)fix avg-size (pick pr 22421 for 2.0 branch)
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/FilterEstimation.java
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query65.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query72.out
  regression-test/data/nereids_tpch_shape_sf1000_p0/shape/q22.out
  regression-test/data/nereids_tpch_shape_sf500_p0/shape/q22.out
Labels: area/nereids

#22481 [FIX](array) fix array-dcheck-contains_null
  be/src/runtime/types.cpp
Labels: approved, reviewed, dev/2.0.0

#22455 [feature](Nereids): pushdown COUNT through join
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PushdownCountThroughJoin.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/Count.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/PushdownCountThroughJoinTest.java
Labels: approved, reviewed

#22397 [vectorized](udaf) java udaf support with map type
  be/src/vec/aggregate_functions/aggregate_function_java_udaf.h
  be/src/vec/functions/function_java_udf.cpp
  be/src/vec/functions/function_java_udf.h
  fe/be-java-extensions/java-udf/src/main/java/org/apache/doris/udf/BaseExecutor.java
  fe/be-java-extensions/java-udf/src/main/java/org/apache/doris/udf/UdafExecutor.java
  fe/be-java-extensions/java-udf/src/main/java/org/apache/doris/udf/UdfExecutor.java
  regression-test/data/javaudf_p0/test_javaudf_agg_map.out
  regression-test/java-udf-src/src/main/java/org/apache/doris/udf/MySumMapInt.java
  regression-test/java-udf-src/src/main/java/org/apache/doris/udf/MySumMapIntDou.java
  regression-test/suites/javaudf_p0/test_javaudf_agg_map.groovy
  regression-test/suites/javaudf_p0/test_javaudf_ret_map.groovy
Labels: approved, reviewed

#22445 [test](pipline) adjust mem limit to 90 & exclude some cases
  regression-test/pipeline/p0/conf/be.conf
  regression-test/pipeline/p0/conf/regression-conf.groovy
  regression-test/pipeline/p1/conf/be.conf
  regression-test/pipeline/p1/conf/regression-conf.groovy
Labels: approved, reviewed

#22488 [fix](nereids)move RecomputeLogicalPropertiesProcessor rule before topn optimization
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/PlanPostProcessors.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/postprocess/TopNRuntimeFilterTest.java
Labels: approved, reviewed, dev/2.0.0

#22494 [Bug](exchange) fix core dump on send_local_block
  be/src/vec/sink/vdata_stream_sender.cpp
Labels: approved, reviewed

#22464 [fix](load) Crashing caused updating counter with an invalid runtime profile
  be/src/io/fs/buffered_reader.cpp
  be/src/io/fs/buffered_reader.h
  be/src/io/fs/stream_load_pipe.h
  be/src/vec/exec/format/csv/csv_reader.cpp
  be/src/vec/exec/format/csv/csv_reader.h
  be/src/vec/exec/format/generic_reader.h
  be/src/vec/exec/format/parquet/vparquet_reader.cpp
  be/src/vec/exec/format/parquet/vparquet_reader.h
  be/src/vec/exec/scan/vfile_scanner.cpp
Labels: approved, reviewed, dev/2.0.0

#22505 [branch-1.2](shade) modfily shade version to 1.0.1
  fs_brokers/apache_hdfs_broker/pom.xml
Labels: reviewed

#22313 [Refactor](inverted index) refact tokenize function for inverted index
  be/src/vec/functions/function_tokenize.cpp
  be/src/vec/functions/function_tokenize.h
  regression-test/data/inverted_index_p0/test_array_index.out
  regression-test/data/inverted_index_p0/test_tokenize.out
  regression-test/suites/inverted_index_p0/test_tokenize.groovy
Labels: reviewed

#22482 [Fix](Planner) fix create view tosql not include partition
  fe/fe-core/src/main/java/org/apache/doris/analysis/TableRef.java
  regression-test/suites/ddl_p0/test_create_view.groovy
Labels: approved, reviewed, usercase, dev/1.2.7, dev/2.0.1

#22490 [improvement](regression) Add syncer regression test feature
  regression-test/conf/regression-conf.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/Config.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/ConfigOptions.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/SuiteContext.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Syncer.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/util/SyncerUtils.groovy
  regression-test/suites/ccr_syncer_p1/test_backup_restore.groovy
Labels: approved, reviewed, dev/2.0.1

#22506 [fix](planner)runtime filter shouldn't be pushed through window function
  fe/fe-core/src/main/java/org/apache/doris/planner/RuntimeFilter.java
Labels: area/planner

#22485 [log](load) add debug logs for potential duplicate tablet ids
  be/src/runtime/tablets_channel.cpp
  be/src/vec/sink/vtablet_sink.cpp
Labels: approved, reviewed, dev/2.0.0

#21888 [improvement](vectorized) Deserialized elements of count distinct aggregation directly inserted into target hashset
  be/src/vec/aggregate_functions/aggregate_function.h
  be/src/vec/aggregate_functions/aggregate_function_avg.h
  be/src/vec/aggregate_functions/aggregate_function_count.h
  be/src/vec/aggregate_functions/aggregate_function_count_old.h
  be/src/vec/aggregate_functions/aggregate_function_min_max.h
  be/src/vec/aggregate_functions/aggregate_function_nothing.h
  be/src/vec/aggregate_functions/aggregate_function_null.h
  be/src/vec/aggregate_functions/aggregate_function_sum.h
  be/src/vec/aggregate_functions/aggregate_function_uniq.h
  be/src/vec/exec/vaggregation_node.cpp
  be/src/vec/exec/vaggregation_node.h
Labels: area/vectorization, reviewed, dev/2.0.1

#22460 [typo](doc)modify some sql syntax and example description errors.
  docs/en/docs/sql-manual/sql-functions/date-time-functions/curtime.md
  docs/zh-CN/docs/sql-manual/sql-functions/array-functions/array_last_index.md
  docs/zh-CN/docs/sql-manual/sql-functions/date-time-functions/curtime.md
  docs/zh-CN/docs/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-SQL-BLOCK-RULE.md
Labels: approved, reviewed

#22420 [typo](doc)modify some sql syntax description errors.
  docs/en/docs/query-acceleration/statistics.md
  docs/en/docs/sql-manual/sql-reference/Data-Definition-Statements/Alter/ALTER-TABLE-REPLACE.md
  docs/en/docs/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-FILE.md
  docs/en/docs/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-MATERIALIZED-VIEW.md
  docs/en/docs/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-TABLE-AS-SELECT.md
  docs/en/docs/sql-manual/sql-reference/Show-Statements/SHOW-DATA.md
  docs/zh-CN/docs/query-acceleration/statistics.md
  docs/zh-CN/docs/sql-manual/sql-reference/Data-Definition-Statements/Alter/ALTER-TABLE-REPLACE.md
  docs/zh-CN/docs/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-FILE.md
  docs/zh-CN/docs/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-MATERIALIZED-VIEW.md
  docs/zh-CN/docs/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-TABLE-AS-SELECT.md
  docs/zh-CN/docs/sql-manual/sql-reference/Show-Statements/SHOW-DATA.md
Labels: approved, reviewed

#22422 [typo](doc)Add a description of whether one of the dynamic partitioning parameters must be required.
  docs/en/docs/advanced/partition/dynamic-partition.md
  docs/zh-CN/docs/advanced/partition/dynamic-partition.md
Labels: approved, reviewed

#22522 [typo](docs) Change the jdk version on the macOS to 11
  docs/en/community/developer-guide/mac-dev/dev-prepare.md
  docs/en/docs/install/source-install/compilation-mac.md
  docs/zh-CN/community/developer-guide/mac-dev/dev-prepare.md
  docs/zh-CN/docs/install/source-install/compilation-mac.md
Labels: approved, reviewed

#22462 [typo](doc) fix be java env faq
  docs/en/docs/faq/install-faq.md
  docs/zh-CN/docs/faq/install-faq.md
Labels: approved, reviewed

#22449 [docs](docs) Merge Doris Introductions File into Getting Started Category
  docs/en/docs/get-starting/quick-start.md
  docs/en/docs/get-starting/what-is-apache-doris.md
  docs/sidebars.json
Labels: approved, reviewed

#22451 [docs](docs) Capitalize and Rename Title of Install and Deployment Files
  docs/en/docs/install/construct-docker/build-docker-image.md
  docs/en/docs/install/construct-docker/run-docker-cluster.md
  docs/en/docs/install/k8s-deploy.md
  docs/en/docs/install/source-install/compilation-arm.md
  docs/en/docs/install/source-install/compilation-general.md
  docs/en/docs/install/source-install/compilation-mac.md
  docs/en/docs/install/source-install/compilation-win.md
  docs/en/docs/install/source-install/compilation-with-ldb-toolchain.md
  docs/en/docs/install/standard-deployment.md
  docs/sidebars.json
  docs/zh-CN/docs/install/construct-docker/build-docker-image.md
Labels: approved, reviewed

#22453 [docs](docs) Capitalize and Rename Table Design Files
  docs/en/docs/data-table/advance-usage.md
  docs/en/docs/data-table/basic-usage.md
  docs/en/docs/data-table/data-model.md
  docs/en/docs/data-table/data-partition.md
  docs/en/docs/data-table/hit-the-rollup.md
  docs/en/docs/data-table/index/bloomfilter.md
  docs/en/docs/data-table/index/index-overview.md
  docs/en/docs/data-table/index/inverted-index.md
  docs/en/docs/data-table/index/ngram-bloomfilter-index.md
  docs/sidebars.json
  docs/zh-CN/docs/data-table/index/index-overview.md
Labels: approved, reviewed

#22457 [docs](docs) Capitalize and Rename Title of Files in Data Operation-Export
  docs/en/docs/data-operate/export/export-manual.md
  docs/en/docs/data-operate/export/export-with-mysql-dump.md
  docs/en/docs/data-operate/export/outfile.md
  docs/sidebars.json
  docs/zh-CN/docs/data-operate/export/export-with-mysql-dump.md
Labels: approved, reviewed

#22456 [typo](Docs) Capitalize the Title of Files in Data Operation - Import Category
  docs/en/docs/data-operate/import/import-scenes/external-storage-load.md
  docs/en/docs/data-operate/import/import-scenes/external-table-load.md
  docs/en/docs/data-operate/import/import-scenes/jdbc-load.md
  docs/en/docs/data-operate/import/import-scenes/load-atomicity.md
  docs/en/docs/data-operate/import/import-scenes/load-data-convert.md
  docs/en/docs/data-operate/import/import-scenes/load-strict-mode.md
  docs/en/docs/data-operate/import/import-scenes/local-file-load.md
  docs/en/docs/data-operate/import/import-way/load-json-format.md
  docs/en/docs/data-operate/import/import-way/mysql-load-manual.md
  docs/en/docs/data-operate/import/import-way/stream-load-manual.md
  docs/en/docs/data-operate/import/load-manual.md
Labels: approved, reviewed

#22510 [fix](parquet) resolve offset check failed in parquet map type
  be/src/vec/exec/format/parquet/schema_desc.cpp
  be/src/vec/exec/format/parquet/vparquet_column_reader.cpp
  regression-test/data/external_table_emr_p2/hive/test_complex_types.out
  regression-test/suites/external_table_emr_p2/hive/test_complex_types.groovy
Labels: approved, reviewed, dev/2.0.0

#22468 [refactor](config) rename segcompaction_max_threads
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/olap/olap_server.cpp
Labels: approved, reviewed, dev/2.0.0

#21954 [typo](docs) Replace invalid mysql-connector-java download package.
  docs/en/docs/lakehouse/multi-catalog/jdbc.md
  docs/zh-CN/docs/lakehouse/multi-catalog/jdbc.md
Labels: approved, reviewed

#22524 [typo](docs) fix get start zh doc
  docs/zh-CN/docs/get-starting/quick-start.md
  docs/zh-CN/docs/get-starting/what-is-apache-doris.md
Labels: approved, reviewed

#22500 [fix](regression) fix flaky test test_partial_update_schema_change
  regression-test/suites/unique_with_mow_p0/partial_update/test_partial_update_schema_change.groovy
  regression-test/suites/unique_with_mow_p0/partial_update/test_partial_update_strict_mode.groovy
Labels: reviewed, dev/2.0.1

#22436 [improvement](stats) Add more logs and config options
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowAnalyzeStmt.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/StatsCalculator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisManager.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/BaseAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/OlapAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsCache.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/util/StatisticsUtil.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/jobs/cascades/DeriveStatsJobTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/stats/StatsCalculatorTest.java
Labels: approved, reviewed, dev/2.0.0

#22517 [bug](distinct-agg) fix limit value not effective in some case
  be/src/pipeline/exec/distinct_streaming_aggregation_sink_operator.cpp
  be/src/pipeline/exec/distinct_streaming_aggregation_sink_operator.h
Labels: approved, reviewed

#22463 [exec](set_operation) Support one child node in set operation
  be/src/vec/exec/vset_operation_node.cpp
  be/src/vec/exec/vset_operation_node.h
Labels: approved, reviewed, dev/2.0.0

#22533 [cherry-pick](test)fix test case have current date
  regression-test/data/delete_p0/fold_constant/fold_constant.out
  regression-test/suites/delete_p0/fold_constant/fold_constant.groovy
Labels: kind/test

#22412 [improvement](file-scan) reduce the min size of file split
  fe/fe-core/src/main/java/org/apache/doris/planner/external/FileScanNode.java
Labels: approved, reviewed, dev/2.0.1

#22530 [Fix](Planner) fix parse error of view with group_concat order by
  fe/fe-core/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java
  regression-test/data/nereids_p0/group_concat/test_group_concat.out
  regression-test/data/query_p0/group_concat/test_group_concat.out
  regression-test/suites/nereids_p0/group_concat/test_group_concat.groovy
  regression-test/suites/query_p0/group_concat/test_group_concat.groovy
Labels: area/planner, kind/test, dev/2.0.0

#22521 [feature](executor) using max_instance_num to limit automatically instance
  docs/en/docs/admin-manual/config/fe-config.md
  docs/en/docs/query-acceleration/pipeline-execution-engine.md
  docs/zh-CN/docs/admin-manual/config/fe-config.md
  docs/zh-CN/docs/query-acceleration/pipeline-execution-engine.md
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SetVar.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
Labels: approved, reviewed, dev/2.0.0

#22537 [bugfix](profile) excecution summary profile not output some variables correctly
  fe/fe-core/src/main/java/org/apache/doris/common/profile/SummaryProfile.java
Labels: approved, reviewed, dev/2.0.0

#22540 [fix][branch-2.0](memory) fix cache regular clean
  be/src/common/config.cpp
  be/src/olap/page_cache.cpp
  be/src/olap/page_cache.h
Labels: dev/2.0.0

#22465 [feature](Nereids): add or expansion in CBO
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleSet.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/OrExpansion.java
  regression-test/data/nereids_p0/union/or_expansion.out
  regression-test/suites/nereids_p0/union/or_expansion.groovy
Labels: approved, reviewed, dev/2.0.1

#22040 [feature](show-frontends-disk) Add Show frontend disks
  docs/en/docs/sql-manual/sql-reference/Show-Statements/SHOW-FRONTENDS-DISKS.md
  docs/sidebars.json
  docs/zh-CN/docs/sql-manual/sql-reference/Show-Statements/SHOW-FRONTENDS-DISKS.md
  fe/fe-common/src/main/java/org/apache/doris/common/io/DiskUtils.java
  fe/fe-common/src/test/java/org/apache/doris/common/io/DiskUtilsTest.java
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowFrontendsStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/FrontendsProcNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/service/ExecuteEnv.java
  fe/fe-core/src/main/java/org/apache/doris/service/FeDiskInfo.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/org/apache/doris/system/Frontend.java
  fe/fe-core/src/main/java/org/apache/doris/system/FrontendHbResponse.java
  fe/fe-core/src/main/java/org/apache/doris/system/HeartbeatMgr.java
  gensrc/thrift/FrontendService.thrift
Labels: approved, reviewed

#22487 [refactor](Nereids) mv top-n two phase read rule from post processor to rewriter
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/cost/CostModelV1.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/PhysicalPlanTranslator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/Rewriter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/PlanPostProcessors.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/TopNScanOpt.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/TwoPhaseReadOpt.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/ChildOutputPropertyDeriver.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/RequestPropertyDeriver.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleSet.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/implementation/LogicalDeferMaterializeOlapScanToPhysicalDeferMaterializeOlapScan.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/implementation/LogicalDeferMaterializeResultSinkToPhysicalDeferMaterializeResultSink.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/implementation/LogicalDeferMaterializeTopNToPhysicalDeferMaterializeTopN.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/DeferMaterializeTopNResult.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/StatsCalculator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/copier/LogicalPlanDeepCopier.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalDeferMaterializeOlapScan.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalDeferMaterializeResultSink.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalDeferMaterializeTopN.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalOlapScan.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalResultSink.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalTopN.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalDeferMaterializeOlapScan.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalDeferMaterializeResultSink.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalDeferMaterializeTopN.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalFileSink.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalOlapScan.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalOlapTableSink.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalRelation.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalResultSink.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalSink.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalTopN.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/PlanVisitor.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/RelationVisitor.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/SinkVisitor.java
  fe/fe-core/src/main/java/org/apache/doris/planner/ExchangeNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OriginalPlanner.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/postprocess/TopNRuntimeFilterTest.java
Labels: approved, reviewed

#22503 [improvement](stats) Catch exception properly
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisManager.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsAutoAnalyzer.java
Labels: approved, reviewed, dev/2.0.1

#22546 [test](pipline) exclude fail case
  regression-test/pipeline/p0/conf/regression-conf.groovy
Labels: approved, reviewed

#22531 [fix](regression] fix test_table_level_compaction_policy
  regression-test/suites/compaction/test_table_level_compaction_policy.groovy
  regression-test/suites/schema_change/test_alter_database_property.groovy
Labels: approved, reviewed, dev/2.0.0

#22458 [Improvement](statistics)Return meaningful error message when show column stats column name doesn't exist.
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowColumnStatsStmt.java
  fe/fe-core/src/main/java/org/apache/doris/common/profile/SummaryProfile.java
Labels: approved, reviewed, dev/2.0.1

#22538 [config](merge-on-write) use separate config to control primary key index cache
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/olap/primary_key_index.cpp
Labels: approved, reviewed, dev/2.0.0

#22499 [chore](cmake) Refactor be CMakeLists option
  be/CMakeLists.txt
Labels: approved, reviewed

#22548 [fix](regression) fix flaky regression test `delete_mow_partial_update`
  regression-test/suites/nereids_p0/delete/delete_mow_partial_update.groovy
Labels: approved, reviewed, dev/2.0.0

#22549 [fix](stacktrace) Fix Jemalloc enable profile fail to run BE after rewrites `dl_iterate_phdr`.
  be/src/common/phdr_cache.cpp
  be/src/service/doris_main.cpp
  bin/start_be.sh
Labels: approved, reviewed, dev/2.0.1

#22556 [fix](case) add sync, test_range_partition.groovy
  regression-test/suites/partition_p0/multi_partition/test_range_partition.groovy
Labels: approved, reviewed, dev/2.0.0

#22507 [bugfix](S3FileSystem) assign correct use virtual address value
  be/src/agent/task_worker_pool.cpp
Labels: approved, reviewed

#22534 [Bug](exchange) disable implicit conversion of block to bool
  be/src/vec/core/block.h
  be/src/vec/core/materialize_block.cpp
  be/src/vec/core/sort_block.cpp
  be/src/vec/olap/vertical_merge_iterator.cpp
  be/src/vec/olap/vgeneric_iterators.cpp
  be/src/vec/sink/vdata_stream_sender.cpp
Labels: approved, reviewed

#22567 [exec](join) Print join type in profile
  be/src/vec/exec/join/vjoin_node_base.cpp
Labels: approved, reviewed, dev/2.0.0

#22484 [Improvement](statistics)Improve show analyze performance.
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisInfo.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisInfoBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisManager.java
Labels: approved, reviewed, dev/2.0.1

#22558 [Chore](brpc) make error messages more verbose when brpc pool offer failed
  be/src/service/internal_service.cpp
  be/src/util/blocking_priority_queue.hpp
  be/src/util/priority_thread_pool.hpp
Labels: approved, reviewed, dev/2.0.0

#22580 [improvement](nereids) Add logs and config options
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowAnalyzeStmt.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/StatsCalculator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/BaseAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/OlapAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsCache.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/util/StatisticsUtil.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/jobs/cascades/DeriveStatsJobTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/stats/StatsCalculatorTest.java
Labels: area/planner, approved, reviewed, area/nereids, dev/2.0.0

#22563 [Fix](planner)fix delete stmt contains where but delete all data.
  fe/fe-core/src/main/java/org/apache/doris/analysis/DeleteStmt.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/DeleteCommand.java
  regression-test/data/delete_p0/test_delete.out
  regression-test/suites/delete_p0/test_delete.groovy
Labels: approved, reviewed, dev/2.0.0

#22541 [Fix](multi catalog)Fix hive partition contains special character bug.
  fe/fe-core/src/main/java/org/apache/doris/common/util/S3Util.java
Labels: approved, reviewed, dev/2.0.0

#22371 [refactor](reader) move reader from vec/exec/scan to vec/exec/format
  be/src/service/internal_service.cpp
  be/src/vec/exec/format/avro/avro_jni_reader.cpp
  be/src/vec/exec/format/avro/avro_jni_reader.h
  be/src/vec/exec/format/jni_reader.cpp
  be/src/vec/exec/format/jni_reader.h
  be/src/vec/exec/format/table/hudi_jni_reader.cpp
  be/src/vec/exec/format/table/hudi_jni_reader.h
  be/src/vec/exec/format/table/max_compute_jni_reader.cpp
  be/src/vec/exec/format/table/max_compute_jni_reader.h
  be/src/vec/exec/format/table/paimon_reader.cpp
  be/src/vec/exec/format/table/paimon_reader.h
  be/src/vec/exec/scan/vfile_scanner.cpp
Labels: approved, reviewed, dev/2.0.1

#22581 [fix](debug) add bvar counter for memtracker
  be/src/runtime/memory/mem_tracker.cpp
  be/src/runtime/memory/mem_tracker_limiter.cpp
Labels: approved, reviewed, dev/2.0.0

#22392 [peformance](load) cancel unstarted segcompaction tasks when build rowset
  be/src/olap/rowset/beta_rowset_writer.cpp
  be/src/olap/rowset/beta_rowset_writer.h
  be/src/olap/rowset/segcompaction.cpp
  be/src/olap/rowset/segcompaction.h
Labels: reviewed, dev/2.0.1

#22497 [Fix](test) Not run workload group by default
  regression-test/suites/workload_manager_p1/basic_workload_group_test.groovy
Labels: approved, reviewed, workload-group

#22381 [Opt](orc-reader) Opt the performance of date conversion in orc reader.
  be/src/vec/exec/format/orc/vorc_reader.cpp
  be/src/vec/exec/format/orc/vorc_reader.h
Labels: approved, reviewed, dev/2.0.0

#22423 [BugFix](Es Catalog) fix bug that es catalog will return error when query partial columns
  be/src/exec/es/es_scroll_parser.cpp
Labels: approved, reviewed, dev/2.0.0

#22579 [fix](compaction) rowid_conversion should ignore deleted row
  be/src/olap/rowid_conversion.h
  be/src/vec/olap/vertical_block_reader.cpp
Labels: approved, reviewed, dev/2.0.0

#22582 [fix](memory) remove memory tracker profile refresh thread
  be/src/common/daemon.cpp
  be/src/common/daemon.h
Labels: approved, reviewed, dev/2.0.0

#22588 [feature](profile) add DORIS_BUILD_SHORT_HASH in profile
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BrokerLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
Labels: area/load

#22543 [chore](topn-opt) temporary disable two phase read for `TableQueryPla…
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/TableQueryPlanAction.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
Labels: approved, reviewed, dev/2.0.0

#22444 [stats](nereids) improve Anti join stats estimation
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/JoinEstimation.java
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query16.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query69.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query94.out
Labels: approved, reviewed

#22203 [tpcds](nereids) add rule to eliminate empty relation
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/Rewriter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/CheckAfterRewrite.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/EliminateEmptyRelation.java
  regression-test/data/empty_relation/eliminate_empty.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query11.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query23.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query4.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query74.out
  regression-test/suites/empty_relation/eliminate_empty.groovy
  regression-test/suites/empty_relation/load.groovy
  regression-test/suites/nereids_p0/load.groovy
Labels: approved, reviewed

#22596 [shape](nereids)ssb sf100 plan shape check
  regression-test/data/nereids_ssb_shape_sf100_p0/shape/q1.1.out
  regression-test/data/nereids_ssb_shape_sf100_p0/shape/q1.2.out
  regression-test/data/nereids_ssb_shape_sf100_p0/shape/q1.3.out
  regression-test/data/nereids_ssb_shape_sf100_p0/shape/q2.1.out
  regression-test/data/nereids_ssb_shape_sf100_p0/shape/q2.2.out
  regression-test/data/nereids_ssb_shape_sf100_p0/shape/q2.3.out
  regression-test/data/nereids_ssb_shape_sf100_p0/shape/q3.1.out
  regression-test/data/nereids_ssb_shape_sf100_p0/shape/q3.2.out
  regression-test/data/nereids_ssb_shape_sf100_p0/shape/q3.3.out
  regression-test/data/nereids_ssb_shape_sf100_p0/shape/q3.4.out
  regression-test/data/nereids_ssb_shape_sf100_p0/shape/q4.1.out
  regression-test/data/nereids_ssb_shape_sf100_p0/shape/q4.2.out
  regression-test/data/nereids_ssb_shape_sf100_p0/shape/q4.3.out
  regression-test/suites/nereids_ssb_shape_sf100_p0/load.groovy
  regression-test/suites/nereids_ssb_shape_sf100_p0/shape/q1.1.groovy
  regression-test/suites/nereids_ssb_shape_sf100_p0/shape/q1.2.groovy
  regression-test/suites/nereids_ssb_shape_sf100_p0/shape/q1.3.groovy
  regression-test/suites/nereids_ssb_shape_sf100_p0/shape/q2.1.groovy
  regression-test/suites/nereids_ssb_shape_sf100_p0/shape/q2.2.groovy
  regression-test/suites/nereids_ssb_shape_sf100_p0/shape/q2.3.groovy
  regression-test/suites/nereids_ssb_shape_sf100_p0/shape/q3.1.groovy
  regression-test/suites/nereids_ssb_shape_sf100_p0/shape/q3.2.groovy
  regression-test/suites/nereids_ssb_shape_sf100_p0/shape/q3.3.groovy
  regression-test/suites/nereids_ssb_shape_sf100_p0/shape/q3.4.groovy
  regression-test/suites/nereids_ssb_shape_sf100_p0/shape/q4.1.groovy
  regression-test/suites/nereids_ssb_shape_sf100_p0/shape/q4.2.groovy
  regression-test/suites/nereids_ssb_shape_sf100_p0/shape/q4.3.groovy
Labels: approved, reviewed

#22572 [chore](cmake) Split thirdparty into cmake/thirdparty.cmake
  be/CMakeLists.txt
  be/cmake/thirdparty.cmake
Labels: approved, reviewed

#22122 [Enhancement](planner)support fold constant for date_trunc()
  fe/fe-core/src/main/java/org/apache/doris/rewrite/FEFunctions.java
  regression-test/suites/query_p0/sql_functions/datetime_functions/test_date_function.groovy
Labels: approved, reviewed, dev/2.0.1

#22555 [feature](Nereids): normalize join condition after expanding or condition NLJ
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleSet.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/OrExpansion.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PushdownExpressionsInHashCondition.java
  regression-test/data/nereids_p0/union/or_expansion.out
  regression-test/suites/nereids_p0/union/or_expansion.groovy
Labels: approved, reviewed, dev/2.0.1

#22578 [fix](debug) add bvar counter for memtable & loadchannel
  be/src/olap/memtable.cpp
  be/src/runtime/load_channel.cpp
Labels: approved, reviewed, dev/2.0.0

#22502 [improvement](jdbc-catalog) Add Connection Keepalive and Detailed Error Messaging for Druid Pool in FE
  fe/fe-core/src/main/java/org/apache/doris/external/jdbc/JdbcClient.java
Labels: dev/1.2.7

#22378 [fix](tablet clone) fix not add colocate replica and print some logs
  fe/fe-core/src/main/java/org/apache/doris/clone/ColocateTableCheckerAndBalancer.java
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletChecker.java
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletSchedCtx.java
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletScheduler.java
  fe/fe-core/src/main/java/org/apache/doris/master/ReportHandler.java
  fe/fe-core/src/main/java/org/apache/doris/task/CloneTask.java
Labels: approved, reviewed, dev/2.0.1

#22574 [fix](multi catalog)Filter .hive-staging dir under hive file path.
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HiveMetaStoreCache.java
Labels: approved, reviewed, dev/2.0.0

#22559 [Enhancement](binlog) Add Barrier log into BinlogManager
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupJob.java
  fe/fe-core/src/main/java/org/apache/doris/binlog/BinlogManager.java
  fe/fe-core/src/main/java/org/apache/doris/journal/JournalEntity.java
  fe/fe-core/src/main/java/org/apache/doris/persist/BarrierLog.java
  fe/fe-core/src/main/java/org/apache/doris/persist/EditLog.java
  gensrc/thrift/FrontendService.thrift
Labels: approved, reviewed

#22447 [improvement](binlog) Gc BE binlog metas when tablet is dropped
  be/src/olap/binlog.h
  be/src/olap/olap_meta.cpp
  be/src/olap/olap_meta.h
  be/src/olap/rowset/rowset_meta_manager.cpp
  be/src/olap/rowset/rowset_meta_manager.h
  be/src/olap/storage_engine.cpp
  be/src/olap/storage_engine.h
  be/src/olap/tablet.cpp
  fe/fe-core/src/main/java/org/apache/doris/binlog/BinlogTombstone.java
  fe/fe-core/src/main/java/org/apache/doris/binlog/DBBinlog.java
Labels: reviewed, dev/2.0.1

#22535 [typo](kerberos)support read jdk auth creds and add some krb tips in FAQ
  conf/be.conf
  conf/fe.conf
  docs/en/docs/lakehouse/faq.md
  docs/zh-CN/docs/lakehouse/faq.md
Labels: approved, reviewed, dev/2.0.1

#22417 [fix](planner)fix bug of push conjuncts through second phase agg
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
  regression-test/suites/correctness_p0/test_distinct_agg.groovy
Labels: approved, reviewed, dev/1.2.7, dev/2.0.1

#22391 [fix](nereids)allow in or exits subquery in binary operator
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/SubExprAnalyzer.java
  regression-test/data/nereids_syntax_p0/sub_query_diff_old_optimize.out
  regression-test/suites/nereids_syntax_p0/sub_query_diff_old_optimize.groovy
Labels: approved, reviewed, dev/2.0.1

#22492 [Fix](Nereids)rand() and uuid() should not fold constant
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/executable/ExecutableFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Random.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
  regression-test/suites/nereids_p0/datatype/test_date_acquire.groovy
  regression-test/suites/nereids_p0/fold_constant/fold_constant_by_fe.groovy
Labels: approved, reviewed, dev/2.0.1

#22583 [improvement](stats) Reduce unnecessary SQL from full auto analyze
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisInfo.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisManager.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsAutoAnalyzer.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsRepository.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/TaskStatusWrapper.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/AnalysisManagerTest.java
Labels: approved, reviewed, dev/2.0.1

#22608 [fix][branch-2.0](memory) remove memory tracker profile refresh thread
  be/src/common/daemon.cpp
  be/src/common/daemon.h
Labels: dev/2.0.0-merged

#22612 [fix](concat) ColumnString::chars is resized with wrong size
  be/src/vec/columns/column_string.cpp
  be/src/vec/columns/column_string.h
  be/src/vec/functions/function_string.h
  be/test/CMakeLists.txt
  be/test/vec/core/column_string_test.cpp
Labels: approved, area/sql/function, area/vectorization, reviewed, dev/1.2.7-merged

#22590 [fix](compatibility) Version 1.2 upgraded to 2.0 compatible with miniload metadata
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadManager.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/MiniLoadJob.java
Labels: approved, reviewed, dev/2.0.0, dev/2.0.1

#22377 [fix](show-table-status) fix hive view NPE and external meta cache refresh issue
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HiveMetaStoreCache.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/HiveScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/util/StatisticsUtil.java
Labels: reviewed, dev/2.0.0

#22592 [fix](inverted index) return empty result instead of error for empty match query
  be/src/olap/rowset/segment_v2/inverted_index_reader.cpp
  be/src/vec/functions/match.cpp
  regression-test/data/inverted_index_p0/test_index_match_select.out
  regression-test/suites/inverted_index_p0/test_index_match_select.groovy
Labels: approved, reviewed, dev/2.0.0

#22526 [feature](load) add segment bytes limit in segcompaction
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/olap/olap_server.cpp
  be/src/olap/rowset/beta_rowset_writer.cpp
  be/src/olap/rowset/beta_rowset_writer.h
  be/test/olap/segcompaction_test.cpp
  docs/en/docs/admin-manual/config/be-config.md
  docs/en/docs/advanced/best-practice/compaction.md
  docs/zh-CN/docs/admin-manual/config/be-config.md
  docs/zh-CN/docs/advanced/best-practice/compaction.md
Labels: approved, reviewed, dev/2.0.1

#21911 [Feature](Export) Supports concurrently export of table data
  docs/en/docs/sql-manual/sql-reference/Data-Manipulation-Statements/Manipulation/EXPORT.md
  docs/zh-CN/docs/sql-manual/sql-reference/Data-Manipulation-Statements/Manipulation/EXPORT.md
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ExportStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/OutFileClause.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/TableRef.java
  fe/fe-core/src/main/java/org/apache/doris/load/ExportJob.java
  fe/fe-core/src/main/java/org/apache/doris/persist/EditLog.java
  fe/fe-core/src/main/java/org/apache/doris/task/ExportExportingTask.java
Labels: approved, reviewed, kind/behavior-changed, dev/2.0.1

#22589 [fix](stats) Load partition stats unexpectedly
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsCache.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/AnalysisJobTest.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/AnalysisTaskExecutorTest.java
  regression-test/suites/statistics/analyze_stats.groovy
Labels: approved, reviewed, dev/2.0.1

#22613 [Fix](Load)Multi table plan not include task info
  docs/en/docs/sql-manual/sql-reference/Data-Manipulation-Statements/Load/CREATE-ROUTINE-LOAD.md
  docs/zh-CN/docs/sql-manual/sql-reference/Data-Manipulation-Statements/Load/CREATE-ROUTINE-LOAD.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateRoutineLoadStmt.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/KafkaTaskInfo.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadManager.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/org/apache/doris/task/StreamLoadTask.java
Labels: approved, reviewed, dev/2.0.0

#22620 [fix](nereids) disable rf for schema scan
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/RuntimeFilterGenerator.java
Labels: reviewed, area/nereids

#22617 [exec](pipeline) revert FE pipeline instance num pr
  docs/en/docs/query-acceleration/pipeline-execution-engine.md
  docs/zh-CN/docs/query-acceleration/pipeline-execution-engine.md
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContext.java
  fe/fe-core/src/main/java/org/apache/doris/qe/VariableMgr.java
Labels: approved, reviewed, dev/2.0.0

#22610 [fix](concat) ColumnString::chars is resized with wrong size
  be/src/vec/columns/column_string.cpp
  be/src/vec/columns/column_string.h
  be/src/vec/functions/function_string.h
  be/test/vec/core/column_string_test.cpp
Labels: approved, reviewed, dev/2.0.0, dev/2.0.1

#22603 [Fix](Planner) fix window function in aggregation
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
  regression-test/suites/query_p0/sql_functions/window_functions/test_window_fn.groovy
Labels: approved, reviewed, usercase, dev/1.2.7, dev/2.0.1

#22428 [docs](docs)Update spark_load.md
  docs/en/community/design/spark_load.md
  docs/en/community/developer-guide/regression-testing.md
Labels: approved, reviewed

#22515 [docs](docs) Capitalize Ecosystem Files Name and Titles
  docs/en/docs/ecosystem/audit-plugin.md
  docs/en/docs/ecosystem/datax.md
  docs/en/docs/ecosystem/logstash.md
  docs/en/docs/ecosystem/udaf/remote-user-defined-aggregation-function.md
  docs/zh-CN/docs/ecosystem/datax.md
  docs/zh-CN/docs/ecosystem/udaf/remote-user-defined-aggregation-function.md
  docs/zh-CN/docs/ecosystem/udf/remote-user-defined-function.md
Labels: approved, reviewed

#22513 [docs](docs) Rename Lakehouse Files for SEO
  docs/en/docs/lakehouse/external-statistics.md
  docs/en/docs/lakehouse/fs-benchmark-tool.md
  docs/en/docs/lakehouse/multi-catalog/max-compute.md
  docs/en/docs/lakehouse/multi-catalog/multi-catalog.md
  docs/sidebars.json
  docs/zh-CN/docs/lakehouse/external-statistics.md
  docs/zh-CN/docs/lakehouse/fs-benchmark-tool.md
  docs/zh-CN/docs/lakehouse/multi-catalog/max-compute.md
Labels: approved, reviewed

#22512 [docs](docs) Capitalize Query Acceleration Files Name and Title
  docs/en/docs/query-acceleration/hight-concurrent-point-query.md
  docs/en/docs/query-acceleration/join-optimization/doris-join-optimization.md
  docs/en/docs/query-acceleration/materialized-view.md
  docs/en/docs/query-acceleration/nereids.md
  docs/en/docs/query-acceleration/pipeline-execution-engine.md
Labels: approved, reviewed

#22511 [docs](docs) Rename Advanced Usage Files for SEO
  docs/en/docs/advanced/best-practice/compaction.md
  docs/en/docs/advanced/best-practice/debug-log.md
  docs/en/docs/advanced/best-practice/import-analysis.md
  docs/en/docs/advanced/best-practice/query-analysis.md
  docs/en/docs/advanced/cache/partition-cache.md
  docs/en/docs/advanced/cold-hot-separation.md
  docs/en/docs/advanced/compute-node.md
  docs/en/docs/advanced/lateral-view.md
  docs/en/docs/advanced/orthogonal-bitmap-manual.md
  docs/en/docs/advanced/orthogonal-hll-manual.md
  docs/en/docs/advanced/partition/table-temp-partition.md
  docs/en/docs/advanced/resource.md
  docs/en/docs/advanced/sql-mode.md
  docs/en/docs/advanced/time-zone.md
  docs/en/docs/advanced/using-hll.md
  docs/sidebars.json
  docs/zh-CN/docs/advanced/cold-hot-separation.md
  docs/zh-CN/docs/advanced/compute-node.md
Labels: approved, reviewed

#22348 [docs](community) Delete Gitter Mannual of EN & CN Verison
  docs/en/community/gitter.md
  docs/sidebarsCommunity.json
  docs/zh-CN/community/gitter.md
Labels: approved, reviewed

#21725 [refactor](load) add segment creator abstraction in rowset writer
  be/src/olap/rowset/beta_rowset_writer.cpp
  be/src/olap/rowset/beta_rowset_writer.h
  be/src/olap/rowset/rowset_writer_context.h
  be/src/olap/rowset/segment_creator.cpp
  be/src/olap/rowset/segment_creator.h
  be/src/olap/rowset/vertical_beta_rowset_writer.cpp
Labels: approved, reviewed

#22622 [Bug](scan) fix coredump when limit<0 and limit!=-1 with 1.2 fe
  be/src/vec/exec/scan/scanner_context.cpp
Labels: approved, reviewed, dev/2.0.0-merged

#22625 [Fix](ut)Fix NPE due to lack of editlog object in unit test of production consumption model
  fe/fe-core/src/test/java/org/apache/doris/scheduler/disruptor/TimerTaskDisruptorTest.java
Labels: approved, reviewed

#22614 [fix](compaction) none vertical compaction should also use _unique_key_next_block function to read block
  be/src/vec/olap/block_reader.cpp
Labels: approved, reviewed, dev/2.0.0

#22601 [case](fix) add sync after stream load
  regression-test/suites/load_p0/stream_load/test_json_load.groovy
  regression-test/suites/partition_p0/list_partition/test_list_partition_datatype.groovy
  regression-test/suites/partition_p0/test_partition_operation.groovy
  regression-test/suites/unique_with_mow_p0/partial_update/test_partial_update.groovy
  regression-test/suites/unique_with_mow_p0/partial_update/test_partial_update_delete.groovy
  regression-test/suites/unique_with_mow_p0/partial_update/test_partial_update_parallel.groovy
  regression-test/suites/unique_with_mow_p0/partial_update/test_partial_update_upsert.groovy
Labels: approved, reviewed, dev/2.0.0

#22628 [fix](compaction) filter block row locations with delete sign should ignore merge on read scenario
  be/src/vec/olap/vertical_block_reader.cpp
Labels: approved, reviewed, dev/2.0.0

#22520 [fix](bug) fix be custom conf persistence path and read path are inconsistent
  be/src/common/config.cpp
Labels: approved, reviewed

#22525 [docs](delete-recover) merge docs: recover catalog and recover tablet trash
  docs/en/docs/admin-manual/data-admin/delete-recover.md
  docs/en/docs/admin-manual/maint-monitor/disk-capacity.md
  docs/en/docs/admin-manual/maint-monitor/tablet-restore-tool.md
  docs/sidebars.json
  docs/zh-CN/docs/admin-manual/data-admin/delete-recover.md
  docs/zh-CN/docs/admin-manual/data-admin/restore.md
  docs/zh-CN/docs/admin-manual/maint-monitor/disk-capacity.md
  docs/zh-CN/docs/admin-manual/maint-monitor/tablet-restore-tool.md
Labels: approved, reviewed

#22618 [fix](meta) set parallel_pipeline_task_num when upgrading from 1.2 to 2.0
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/qe/VariableMgr.java
Labels: approved, dev/2.0.0, dev/2.0.1

#22619 [fix](nereids)fix join count
  fe/fe-core/src/main/java/org/apache/doris/nereids/memo/Memo.java
Labels: approved, reviewed

#22626 [fix](load)Fix wrong default value for char and varchar of reading json data
  be/src/vec/exec/format/json/new_json_reader.cpp
  regression-test/data/load_p0/stream_load/test_json_load_default_value.out
  regression-test/suites/load_p0/stream_load/test_json_load_default_value.groovy
Labels: approved, reviewed, dev/2.0.0, dev/2.0.1

#22627 [Chore](cmake) Remove ununsed be rowset CMakeLists.txt
  be/CMakeLists.txt
  be/src/olap/CMakeLists.txt
  be/src/olap/rowset/CMakeLists.txt
Labels: approved, reviewed

#22602 [BUG](date_trunc) fix date_trunc function only handle lower string
  be/src/vec/functions/function_timestamp.cpp
  fe/fe-core/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/DateTrunc.java
  regression-test/data/nereids_function_p0/scalar_function/D.out
  regression-test/data/query_p0/sql_functions/datetime_functions/test_date_trunc.out
  regression-test/suites/nereids_function_p0/scalar_function/D.groovy
  regression-test/suites/query_p0/sql_functions/datetime_functions/test_date_trunc.groovy
Labels: approved, reviewed, usercase, dev/2.0.0, dev/2.0.1

#22604 [fix](regression test) redefine variable in the test_table_level_compaction_policy
  regression-test/suites/compaction/test_table_level_compaction_policy.groovy
Labels: reviewed

#22632 [refactor](mysql writer) remove some unused code
  be/src/vec/sink/vmysql_result_writer.cpp
Labels: approved, reviewed

#22633 [regression-test](delete) should drop table test before create it
  regression-test/suites/delete_p0/test_delete.groovy
Labels: approved, reviewed, dev/2.0.0, dev/2.0.1

#22600 [Bug](brpc) fix brpc failed on big query came concurrently
  be/src/olap/olap_server.cpp
  be/src/olap/storage_engine.cpp
  be/src/olap/storage_engine.h
  be/src/runtime/routine_load/data_consumer_group.h
  be/src/runtime/routine_load/routine_load_task_executor.h
  be/src/service/internal_service.cpp
  be/src/service/internal_service.h
  be/src/util/async_io.h
  be/src/util/blocking_priority_queue.hpp
  be/src/util/blocking_queue.hpp
  be/src/util/threadpool.h
  be/src/util/work_thread_pool.hpp
  be/src/vec/exec/scan/scanner_scheduler.cpp
  be/src/vec/exec/scan/scanner_scheduler.h
  be/test/olap/skiplist_test.cpp
Labels: approved, reviewed, dev/2.0.0

#22616 [fix](jdbc catalog) getInsertSql to use databaseProperName for column names
  fe/fe-core/src/main/java/org/apache/doris/catalog/JdbcTable.java
Labels: approved, reviewed, usercase, dev/2.0.1
