Repository apache/doris, pull requests merged in 2023-10, with the labels that each got.

#25017 [Bug](migration) Enhance invalid behavior handling in `copy_files_to`
  be/src/io/fs/local_file_system.cpp
  be/src/io/fs/local_file_system.h
  be/src/olap/rowset/beta_rowset.cpp
Labels: approved, reviewed

#25026 [Opt](performance) refactor and opt time round floor function
  be/src/vec/functions/function_datetime_floor_ceil.cpp
  be/src/vec/runtime/vdatetime_value.h
Labels: reviewed

#24873 [FIX](complex-type) fix agg table with complex type with replace state
  be/src/vec/columns/column_array.h
  be/src/vec/columns/column_map.h
  be/src/vec/columns/column_struct.h
  be/src/vec/olap/block_reader.cpp
  be/src/vec/olap/block_reader.h
  regression-test/data/datatype_p0/nested_types/negative_cases/test_nested_types_insert_into_with_agg_table.out
  regression-test/suites/datatype_p0/nested_types/negative_cases/test_nested_types_insert_into_with_agg_table.groovy
Labels: approved, reviewed

#25036 [fix](regression test)fix ci error
  regression-test/suites/query_p0/sql_functions/json_function/test_query_json_replace.groovy
Labels: approved, reviewed

#25034 [fix](jdbc catalog) fix jdbc catalog read bitmap data crash
  be/src/util/bitmap_value.h
Labels: approved, reviewed, dev/2.0.3

#24954 [fix](insert) Fix test_group_commit_stream_load and add more regressi…
  be/src/runtime/group_commit_mgr.cpp
  regression-test/data/load_p0/http_stream/test_group_commit_http_stream.out
  regression-test/suites/load_p0/http_stream/test_group_commit_http_stream.groovy
  regression-test/suites/load_p0/stream_load/test_group_commit_stream_load.groovy
Labels: approved, reviewed

#24902 [regression-test](merge-on-write) Add cases for partial update using insert statement with schema change
  regression-test/data/unique_with_mow_p0/partial_update/test_partial_update_insert_light_schema_change.out
  regression-test/data/unique_with_mow_p0/partial_update/test_partial_update_insert_schema_change.out
  regression-test/suites/unique_with_mow_p0/partial_update/test_partial_update_insert_light_schema_change.groovy
  regression-test/suites/unique_with_mow_p0/partial_update/test_partial_update_insert_schema_change.groovy
Labels: approved, reviewed, dev/2.0.3

#24763 [improve](move-memtable) always share load streams
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/vec/sink/load_stream_stub_pool.cpp
  be/src/vec/sink/vtablet_sink_v2.cpp
Labels: approved, reviewed

#24722 [fix](move-memtable) exclude rpc memory in flush mem-tracker
  be/src/vec/sink/load_stream_stub.cpp
Labels: approved, reviewed

#25038 [fix](testcase) add state check for ADD INDEX before BUILD INDEX to avoid table state not normal
  regression-test/suites/inverted_index_p0/index_change/test_index_change_3.groovy
  regression-test/suites/inverted_index_p0/index_change/test_index_change_4.groovy
  regression-test/suites/inverted_index_p0/index_change/test_index_change_6.groovy
  regression-test/suites/inverted_index_p0/index_change/test_index_change_7.groovy
  regression-test/suites/inverted_index_p0/index_change/test_index_change_with_compaction.groovy
  regression-test/suites/inverted_index_p0/index_change/test_pk_uk_index_change.groovy
  regression-test/suites/inverted_index_p0/test_build_index.groovy
Labels: approved, reviewed, dev/2.0.3

#25046 [improvement](tablet clone) impr further repair tablet sched priority
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletSchedCtx.java
Labels: approved, reviewed, dev/2.0.3

#25041 [Debug](float) Add clang debug tune float accuracy
  be/src/vec/aggregate_functions/aggregate_function_avg.h
  be/src/vec/aggregate_functions/aggregate_function_avg_weighted.h
  be/src/vec/aggregate_functions/aggregate_function_sum.h
Labels: approved, reviewed

#25008 Revert "[Fix](Nereids) fix infer predicate lost cast of source expression (#23692)"
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PredicatePropagation.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/InferPredicatesTest.java
  regression-test/suites/nereids_p0/infer_predicate/infer_predicate.groovy
Labels: approved, reviewed

#24773 [Improve](metric) Improve FE DorisMetricRegistry
  fe/fe-core/src/main/java/org/apache/doris/metric/DorisMetricRegistry.java
  fe/fe-core/src/main/java/org/apache/doris/metric/JsonMetricVisitor.java
  fe/fe-core/src/main/java/org/apache/doris/metric/MetricRepo.java
  fe/fe-core/src/main/java/org/apache/doris/metric/MetricVisitor.java
  fe/fe-core/src/main/java/org/apache/doris/metric/PrometheusMetricVisitor.java
  fe/fe-core/src/main/java/org/apache/doris/metric/SimpleCoreMetricVisitor.java
  fe/fe-core/src/test/java/org/apache/doris/metric/MetricsTest.java
  fe/fe-core/src/test/java/org/apache/doris/mtmv/MTMVJobManagerTest.java
Labels: approved, reviewed

#25050 [refactor](segment iterator) remove some code to make the logic more clear
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
Labels: approved, reviewed

#24881 [feature](profilev2) Preliminary support for profilev2.
  be/src/exec/exec_node.cpp
  be/src/pipeline/exec/exchange_sink_operator.cpp
  be/src/util/runtime_profile.cpp
  be/src/util/runtime_profile.h
  be/src/vec/exec/join/vjoin_node_base.cpp
  be/src/vec/exec/vaggregation_node.cpp
  be/src/vec/sink/vdata_stream_sender.cpp
  fe/fe-core/src/main/java/org/apache/doris/common/profile/Profile.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/Counter.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/ProfileManager.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/ProfileStatistics.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/RuntimeProfile.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BrokerLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/planner/DataSink.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PlanFragment.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PlanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/Planner.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  gensrc/thrift/RuntimeProfile.thrift
Labels: approved, reviewed, profilev2

#24956 [fix](planner)the common type of date and decimal should be double
  fe/fe-common/src/main/java/org/apache/doris/catalog/ScalarType.java
  regression-test/data/correctness_p0/test_cast_date_decimal.out
  regression-test/suites/correctness_p0/test_cast_date_decimal.groovy
Labels: approved, reviewed, usercase, dev/2.0.2, dev/2.0.3

#24777 [opt](optimizer) Recycle expired table stats
  fe/fe-core/src/main/java/org/apache/doris/datasource/CatalogIf.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/CatalogMgr.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/journal/JournalEntity.java
  fe/fe-core/src/main/java/org/apache/doris/persist/EditLog.java
  fe/fe-core/src/main/java/org/apache/doris/persist/OperationType.java
  fe/fe-core/src/main/java/org/apache/doris/persist/TableStatsDeletionLog.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisInfo.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisManager.java
  regression-test/suites/statistics/analyze_stats.groovy
Labels: approved, reviewed

#25009 [fix](Nereids) create table throw npe when default value is null
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/ColumnDefinition.java
  regression-test/data/nereids_p0/create_table/test_create_table.out
  regression-test/suites/nereids_p0/create_table/ddl/data.sql
  regression-test/suites/nereids_p0/create_table/ddl/table.sql
  regression-test/suites/nereids_p0/create_table/test_create_table.groovy
Labels: approved, reviewed

#24844 [feature-wip](executor)query cpu hard limit based on doris scheduler
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/pipeline/pipeline_task.cpp
  be/src/pipeline/pipeline_task.h
  be/src/pipeline/task_queue.cpp
  be/src/pipeline/task_queue.h
  be/src/pipeline/task_scheduler.cpp
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/task_group/task_group.cpp
  be/src/runtime/task_group/task_group.h
  be/src/vec/exec/scan/scan_task_queue.cpp
  be/src/vec/exec/scan/scan_task_queue.h
  be/src/vec/exec/scan/scanner_scheduler.cpp
  be/src/vec/exec/scan/scanner_scheduler.h
  fe/fe-core/src/main/java/org/apache/doris/resource/workloadgroup/WorkloadGroup.java
  fe/fe-core/src/main/java/org/apache/doris/resource/workloadgroup/WorkloadGroupMgr.java
Labels: approved, reviewed, workload-group

#24919 [Feature](Job)Job tasks support the choice of persistence or storage in memory
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowJobTaskStmt.java
  fe/fe-core/src/main/java/org/apache/doris/scheduler/constants/JobCategory.java
  fe/fe-core/src/main/java/org/apache/doris/scheduler/disruptor/TaskHandler.java
  fe/fe-core/src/main/java/org/apache/doris/scheduler/manager/JobTaskManager.java
  fe/fe-core/src/main/java/org/apache/doris/scheduler/manager/TimerJobManager.java
  fe/fe-core/src/test/java/org/apache/doris/scheduler/disruptor/TaskDisruptorTest.java
Labels: reviewed

#24706 [opt](tvf) refine the class of ExternalFileTableValuedFunction
  fe/fe-core/src/main/java/org/apache/doris/analysis/DataDescription.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/OutFileClause.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/S3TvfLoadStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/StorageBackend.java
  fe/fe-core/src/main/java/org/apache/doris/common/FeConstants.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/FileFormatConstants.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/FileFormatUtils.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/Util.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/LoadCommand.java
  fe/fe-core/src/main/java/org/apache/doris/planner/ResultFileSink.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/FileQueryScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/LoadScanProvider.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/TVFScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/ExternalFileTableValuedFunction.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/HdfsTableValuedFunction.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/HttpStreamTableValuedFunction.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/LocalTableValuedFunction.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/S3TableValuedFunction.java
  fe/fe-core/src/test/java/org/apache/doris/tablefunction/ExternalFileTableValuedFunctionTest.java
  regression-test/data/load_p0/http_stream/student_with_names.csv
  regression-test/data/load_p0/http_stream/student_with_names_and_types.csv
  regression-test/data/load_p0/http_stream/test_http_stream.csv
  regression-test/data/load_p0/http_stream/test_http_stream_data_model.csv
  regression-test/data/load_p0/http_stream/test_http_stream_multiple_times.csv
  regression-test/suites/export_p2/test_export_max_file_size.groovy
  regression-test/suites/export_p2/test_export_with_hdfs.groovy
  regression-test/suites/export_p2/test_outfile_orc_max_file_size.groovy
  regression-test/suites/external_table_p0/hive/test_different_parquet_types.groovy
  regression-test/suites/external_table_p0/tvf/test_hdfs_tvf.groovy
  regression-test/suites/external_table_p2/tvf/test_hdfs_tvf_compression.groovy
  regression-test/suites/external_table_p2/tvf/test_path_partition_keys.groovy
  regression-test/suites/external_table_p2/tvf/test_s3_tvf_compression.groovy
  regression-test/suites/external_table_p2/tvf/test_tvf_p2.groovy
  regression-test/suites/external_table_p2/tvf/test_tvf_view_count_p2.groovy
  regression-test/suites/external_table_p2/tvf/test_tvf_view_p2.groovy
  regression-test/suites/load_p0/http_stream/test_http_stream.groovy
  regression-test/suites/load_p0/http_stream/test_http_stream_compress.groovy
Labels: approved, reviewed

#24094 [Fix](Parquet Reader)Branch 1.2 lts bugfix
  be/src/exec/arrow/parquet_row_group_reader.cpp
  be/src/vec/exec/format/parquet/parquet_thrift_util.h
Labels: area/vectorization, dev/1.2.8

#24841 [bug][auth]Show grant causes role errors in the memory. #24783
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/CatalogPrivEntry.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/DbPrivEntry.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/GlobalPrivEntry.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/PrivEntry.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/PrivTable.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/ResourcePrivEntry.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/TablePrivEntry.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/WorkloadGroupPrivEntry.java
Labels: reviewed

#25016 [fix](multicatalog)fix jdbc catalog current_timestamp default
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/client/JdbcMySQLClient.java
Labels: approved, reviewed, usercase, dev/2.0.3

#24720 [feature](Nereids): push down topN through join
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/Rewriter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/EliminateLimit.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/LimitSortToTopN.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PushdownFilterThroughProject.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PushdownProjectThroughLimit.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PushdownTopNThroughJoin.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PushdownTopNThroughWindow.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/ExpressionUtils.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/PushdownLimitTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/PushdownTopNThroughJoinTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/util/LogicalPlanBuilder.java
Labels: approved, reviewed

#25066 [fix](pipelinex) fix multi cast sink with out init
  be/src/pipeline/exec/multi_cast_data_stream_sink.cpp
  be/src/pipeline/exec/multi_cast_data_stream_sink.h
  be/src/pipeline/exec/multi_cast_data_stream_source.h
  be/src/pipeline/pipeline_x/operator.cpp
  be/src/pipeline/pipeline_x/pipeline_x_fragment_context.cpp
Labels: approved, reviewed

#24997 [refactor](nereids) unify withSel/updateRowCountOnly/withRowCount
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/cascades/DeriveStatsJob.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/ExpressionEstimation.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/FilterEstimation.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/JoinEstimation.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/StatsCalculator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/types/coercion/DateLikeType.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/ColumnStatistic.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/Statistics.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/util/StatisticsUtil.java
Labels: approved, reviewed

#25076 [chore](unused) Remove unused variable CPU_HARD_LIMIT in task_group.cc
  be/src/runtime/task_group/task_group.cpp
Labels: approved, reviewed

#24320 [Fix](stream load) stearm load record use valid txn info when two txn with same label
  fe/fe-core/src/main/java/org/apache/doris/load/StreamLoadRecordMgr.java
Labels: approved, reviewed, dev/1.2.8-merged, dev/2.0.3

#25075 [Monitor](doc)modify incorrect status for doris_be_engine_requests_total
  docs/zh-CN/docs/admin-manual/maint-monitor/monitor-metrics/metrics.md
Labels: approved, reviewed

#25082 [Monitor](doc)modify incorrect name for Cumulative Compaction Score
  docs/zh-CN/docs/admin-manual/maint-monitor/monitor-metrics/metrics.md
Labels: approved, reviewed

#25078 [minor](be) set fd number check to 60000 for BE start script
  bin/start_be.sh
Labels: approved, reviewed, dev/1.2.8, dev/2.0.3

#25059 [improvement](jdbc catalog) Adjustment to JDBC Catalog Configuration Based on Internal Table Lower Case Settings
  docs/en/docs/lakehouse/multi-catalog/jdbc.md
  docs/zh-CN/docs/lakehouse/multi-catalog/jdbc.md
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/JdbcExternalCatalog.java
Labels: approved, reviewed, dev/2.0.3

#25056 [fix](multi-table) fix multi table task cannot end
  be/src/runtime/routine_load/routine_load_task_executor.cpp
Labels: approved, reviewed, dev/2.0.3

#24769 [refactor](stats) Refactor TableStatsMeta
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowColumnStatsStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowTableStatsStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Table.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/TableIf.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/external/ExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/external/HMSExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/external/JdbcExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/journal/JournalEntity.java
  fe/fe-core/src/main/java/org/apache/doris/persist/EditLog.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisManager.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/ColStatsMeta.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/HMSAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/JdbcAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsAutoCollector.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/TableStatsMeta.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/AnalysisManagerTest.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/StatisticsAutoCollectorTest.java
  regression-test/pipeline/p0/conf/regression-conf.groovy
  regression-test/suites/statistics/analyze_stats.groovy
Labels: approved, reviewed

#24968 [fix](insert) fix group commit be ut
  be/test/olap/wal_manager_test.cpp
Labels: approved, reviewed

#25054 [fix](doc) spelling error for colocate join
  docs/en/docs/query-acceleration/join-optimization/bucket-shuffle-join.md
Labels: approved, reviewed

#25043 [bugfix](set_var) fix sql level exec_mem_limit does not take effect
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
Labels: approved, reviewed, dev/2.0.3

#24559 [bugfix](multi-catalog) Esexternalcatalog is missing LastUpdateTime.
  fe/fe-core/src/main/java/org/apache/doris/datasource/CatalogMgr.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/EsExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalCatalog.java
Labels: approved, reviewed

#25074 [Fix](RoutineLoad)Query the transaction status NPE when the task has not yet started scheduling
  docs/en/docs/sql-manual/sql-reference/Show-Statements/SHOW-ROUTINE-LOAD-TASK.md
  docs/zh-CN/docs/sql-manual/sql-reference/Show-Statements/SHOW-ROUTINE-LOAD-TASK.md
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadTaskInfo.java
Labels: approved, reviewed, dev/2.0.3

#24721 [Fix](Outfile) Use data_type_serde to export data to csv file format
  be/src/vec/data_types/serde/data_type_array_serde.cpp
  be/src/vec/data_types/serde/data_type_array_serde.h
  be/src/vec/data_types/serde/data_type_bitmap_serde.h
  be/src/vec/data_types/serde/data_type_date64_serde.cpp
  be/src/vec/data_types/serde/data_type_date64_serde.h
  be/src/vec/data_types/serde/data_type_datetimev2_serde.cpp
  be/src/vec/data_types/serde/data_type_datetimev2_serde.h
  be/src/vec/data_types/serde/data_type_datev2_serde.cpp
  be/src/vec/data_types/serde/data_type_datev2_serde.h
  be/src/vec/data_types/serde/data_type_decimal_serde.cpp
  be/src/vec/data_types/serde/data_type_decimal_serde.h
  be/src/vec/data_types/serde/data_type_fixedlengthobject_serde.h
  be/src/vec/data_types/serde/data_type_hll_serde.cpp
  be/src/vec/data_types/serde/data_type_hll_serde.h
  be/src/vec/data_types/serde/data_type_jsonb_serde.cpp
  be/src/vec/data_types/serde/data_type_jsonb_serde.h
  be/src/vec/data_types/serde/data_type_map_serde.cpp
  be/src/vec/data_types/serde/data_type_map_serde.h
  be/src/vec/data_types/serde/data_type_nullable_serde.cpp
  be/src/vec/data_types/serde/data_type_nullable_serde.h
  be/src/vec/data_types/serde/data_type_number_serde.cpp
  be/src/vec/data_types/serde/data_type_number_serde.h
  be/src/vec/data_types/serde/data_type_object_serde.h
  be/src/vec/data_types/serde/data_type_quantilestate_serde.h
  be/src/vec/data_types/serde/data_type_serde.h
  be/src/vec/data_types/serde/data_type_string_serde.cpp
  be/src/vec/data_types/serde/data_type_string_serde.h
  be/src/vec/data_types/serde/data_type_struct_serde.cpp
  be/src/vec/data_types/serde/data_type_struct_serde.h
  be/src/vec/runtime/vcsv_transformer.cpp
  be/src/vec/runtime/vcsv_transformer.h
  be/src/vec/runtime/vfile_format_transformer.h
  be/test/vec/data_types/serde/data_type_serde_csv_test.cpp
  be/test/vec/data_types/serde/data_type_serde_text_test.cpp
Labels: approved, reviewed

#25024 [Fix](replayer) Fix `FE` crash when replaying analysis logs.
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisManager.java
Labels: approved, reviewed, dev/2.0.3

#25002 [tools](tpc)make tpch-tools and tpcds-tools default scale factor 100
  tools/tpcds-tools/bin/create-tpcds-tables.sh
  tools/tpcds-tools/ddl/create-tpcds-tables-sf1.sql
  tools/tpch-tools/bin/create-tpch-tables.sh
  tools/tpch-tools/conf/doris-cluster.conf
  tools/tpch-tools/ddl/create-tpch-tables-sf1.sql
Labels: approved, reviewed

#25069 [typo](doc)Add be's enable_java_support configuration document
  docs/en/docs/admin-manual/config/be-config.md
  docs/zh-CN/docs/admin-manual/config/be-config.md
Labels: approved, reviewed

#25086 [improvement](start script) start script can not set http proxy
  bin/start_be.sh
  bin/start_fe.sh
Labels: approved, reviewed, dev/2.0.3

#24918 [fix](help-module)fix use regex match replaceAll may cause backtracking
  fe/fe-core/src/main/java/org/apache/doris/common/MarkDownParser.java
Labels: approved, reviewed

#25080 [log](load) PUBLISH_TIMEOUT should not print stacktrace
  be/src/common/status.h
Labels: approved, reviewed, dev/2.0.3

#24839 [fix](es-catalog)fix error when querying the index ,elasticsearch version 8.9.1
  docker/thirdparties/docker-compose/elasticsearch/scripts/data/data5.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/es_init.sh
  docker/thirdparties/docker-compose/elasticsearch/scripts/index/es7_test3.json
  fe/fe-core/src/main/java/org/apache/doris/external/elasticsearch/EsUtil.java
  regression-test/data/external_table_p0/es/test_es_query.out
  regression-test/suites/external_table_p0/es/test_es_query.groovy
Labels: approved, reviewed

#25072 [doc](fix)fix misspell
  docs/zh-CN/docs/sql-manual/sql-reference/Data-Manipulation-Statements/Manipulation/INSERT.md
Labels: approved, reviewed

#25095 [enhancement](tablet_meta_lock) add more trace for write lock of tablet's _meta_lock
  be/src/olap/compaction.cpp
  be/src/olap/full_compaction.cpp
  be/src/olap/rowset_builder.cpp
  be/src/olap/tablet.cpp
  be/src/olap/task/index_builder.cpp
Labels: reviewed, dev/2.0.3

#25014 [Enhance](catalog)add table cache in paimon jni
  be/src/vec/exec/format/table/paimon_reader.cpp
  fe/be-java-extensions/paimon-scanner/src/main/java/org/apache/doris/paimon/PaimonJniScanner.java
  fe/be-java-extensions/paimon-scanner/src/main/java/org/apache/doris/paimon/PaimonTableCache.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/external/PaimonExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/paimon/PaimonScanNode.java
  gensrc/thrift/PlanNodes.thrift
Labels: approved, reviewed

#24960 [bug](partition_sort)partition sort need sort all data in two phase global
  be/src/vec/exec/vpartition_sort_node.cpp
  be/src/vec/exec/vpartition_sort_node.h
  fe/fe-core/src/main/java/org/apache/doris/planner/PartitionSortNode.java
  gensrc/thrift/PlanNodes.thrift
  regression-test/data/ssb_unique_sql_zstd_p0/partition_sort_node/test_partiiton_sort.out
  regression-test/suites/ssb_unique_sql_zstd_p0/partition_sort_node/test_partiiton_sort.groovy
Labels: approved, reviewed

#24978 [fix](streamload) fix http_stream retry mechanism
  be/src/http/action/http_stream.cpp
  be/src/io/file_factory.cpp
  be/src/io/file_factory.h
  be/src/runtime/stream_load/stream_load_context.h
  be/src/service/internal_service.cpp
  be/src/vec/exec/format/csv/csv_reader.cpp
  be/src/vec/exec/format/json/new_json_reader.cpp
  be/src/vec/exec/format/json/new_json_reader.h
Labels: approved, reviewed

#25096 [fix](export) fix ConcurrentModificationException in export
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ExportCommand.java
  fe/fe-core/src/main/java/org/apache/doris/qe/VariableMgr.java
Labels: approved, reviewed

#24900 [fix](auth)fix use regex verify mysql password may cause backtracking
  fe/fe-core/src/main/java/org/apache/doris/mysql/MysqlPassword.java
Labels: reviewed

#24953 [Refactor](Export) delete useless code of Export
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ExportStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/load/ExportJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/ExportMgr.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ExportCommand.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/task/ExportExportingTask.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/CancelExportStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/qe/SessionVariablesTest.java
Labels: approved, reviewed

#25085 [Fix](point query) Not allow subquery for point query optimization
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
  regression-test/suites/point_query_p0/test_update.groovy
Labels: approved, reviewed, usercase, dev/2.0.3

#24754 [typo](docs) Add example for create sql block rule
  docs/en/docs/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-SQL-BLOCK-RULE.md
  docs/zh-CN/docs/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-SQL-BLOCK-RULE.md
Labels: approved, reviewed

#24826 [feature](es-catalog) add `include_hidden_index`in order to get the hidden index.
  docker/thirdparties/docker-compose/elasticsearch/scripts/es_init.sh
  docker/thirdparties/docker-compose/elasticsearch/scripts/index/es6_hide.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/index/es7_hide.json
  docs/en/docs/lakehouse/multi-catalog/es.md
  docs/zh-CN/docs/lakehouse/multi-catalog/es.md
  fe/fe-core/src/main/java/org/apache/doris/catalog/EsResource.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/EsTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/external/EsExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/EsExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/external/elasticsearch/EsRestClient.java
  regression-test/suites/external_table_p0/es/test_es_query.groovy
Labels: approved, reviewed, dev/2.0.3

#25067 [fix](Nerids) fix error when the view has lambda functions
  fe/fe-core/src/main/java/org/apache/doris/analysis/LambdaFunctionCallExpr.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/ComputeSignature.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/ArrayCount.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/ArrayExists.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/ArrayFilter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/ArrayFirstIndex.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/ArrayLastIndex.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/ArraySortBy.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/TypeCoercionUtils.java
  regression-test/data/nereids_function_p0/scalar_function/Array.out
  regression-test/suites/nereids_function_p0/scalar_function/Array.groovy
Labels: approved, reviewed

#25090 [fix](scanner) fix load cannot end when set exec_mem_limit
  be/src/vec/exec/scan/scanner_context.cpp
  regression-test/suites/load_p0/stream_load/test_stream_load_properties.groovy
Labels: approved, reviewed

#25110 [refactor](columndecimal) is_decimal_v2 member is useless because column decimal could detect by itself
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/vec/columns/column.h
  be/src/vec/columns/column_decimal.cpp
  be/src/vec/columns/column_nullable.h
  be/src/vec/data_types/data_type_decimal.cpp
  be/test/vec/columns/column_decimal_test.cpp
Labels: approved, reviewed

#25061 [improvement](tablet clone) fix balanced new replica will be removed when load txn continuously
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Replica.java
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletSchedCtx.java
Labels: dev/2.0.3

#24864 [fix](ES catalog)Doris cannot parse ES date field without time zone
  be/src/exec/es/es_scroll_parser.cpp
  be/src/exec/es/es_scroll_parser.h
  be/src/vec/exec/scan/new_es_scanner.cpp
  docker/thirdparties/docker-compose/elasticsearch/scripts/data/data1.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/data/data1_es6.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/data/data2.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/data/data2_es6.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/data/data3.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/data/data3_es6.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/data/data4.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/index/es6_test1.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/index/es6_test2.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/index/es7_test1.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/index/es7_test2.json
  regression-test/data/external_table_p0/es/test_es_query.out
  regression-test/data/external_table_p0/es/test_es_query_no_http_url.out
  regression-test/suites/external_table_p0/es/test_es_query.groovy
Labels: approved, reviewed, dev/2.0.3

#25108 [fix](fs) fix remove error log failed
  be/src/runtime/load_path_mgr.cpp
Labels: approved, reviewed, dev/2.0.3

#25091 [opt](Nereids) let keywords list same with legacy planner
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisLexer.g4
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/types/DataType.java
Labels: area/nereids, dev/2.0.3

#25114 [pick](point query) pick two PRs according to refactoring and decoupling code from coordinator
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/NativeInsertStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/PrepareStmt.java
  fe/fe-core/src/main/java/org/apache/doris/qe/CoordInterface.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/PointQueryExec.java
  fe/fe-core/src/main/java/org/apache/doris/qe/PrepareStmtContext.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  regression-test/data/insert_p0/prepare_insert.out
  regression-test/suites/insert_p0/prepare_insert.groovy
Labels: area/planner, kind/test

#25116 [schedule](pipeline) Remove wait schedule time in pipeline query engine and change current queue to std::mutex
  be/src/pipeline/pipeline_task.cpp
  be/src/pipeline/pipeline_task.h
  be/src/pipeline/task_scheduler.cpp
  be/src/pipeline/task_scheduler.h
  be/src/vec/exec/scan/pip_scanner_context.h
Labels: area/pipeline

#25087 [Bug](join) corner case cause the mark join + null aware left join core dump in regression test in pipeline query engine
  be/src/pipeline/exec/operator.h
  be/src/pipeline/pipeline_task.cpp
  be/src/vec/exec/join/vhash_join_node.cpp
  be/src/vec/exec/join/vhash_join_node.h
  be/src/vec/exec/join/vjoin_node_base.h
  be/src/vec/exec/scan/vscan_node.cpp
Labels: approved, reviewed, p0_block, pick_pipelinex, dev/2.0.3

#25123 [improvement](processlist) Add more information for show processlist
  docs/en/docs/sql-manual/sql-reference/Show-Statements/SHOW-PROCESSLIST.md
  docs/zh-CN/docs/sql-manual/sql-reference/Show-Statements/SHOW-PROCESSLIST.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowProcesslistStmt.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/controller/SessionController.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContext.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectScheduler.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/qe/ConnectContextTest.java
Labels: kind/docs, area/planner

#25073 [Opt](performance) Optimize timeround with minute / second
  be/src/vec/functions/function_datetime_floor_ceil.cpp
Labels: approved, reviewed, dev/2.0.3

#25136 [fix](hudi) hbase-2.5.5 conflict with hudi
  fe/pom.xml
Labels: approved, reviewed, dev/2.0.3

#25040 [fix](parse_url) fix `parse_url` is not working in some case to extract the HOST
  be/src/util/url_parser.cpp
  be/test/vec/function/function_string_test.cpp
Labels: approved, reviewed, dev/2.0.3

#25111 [fix](mysqldb) Fix mysqldb upgrade
  docs/en/docs/admin-manual/config/fe-config.md
  docs/zh-CN/docs/admin-manual/config/fe-config.md
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/DropDbStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/MysqlDb.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
Labels: approved, reviewed, usercase, dev/2.0.3

#25088 [minor](doc) update the doc for docker env and custom_lib dir
  bin/start_be.sh
  bin/start_fe.sh
  docs/en/docs/admin-manual/cluster-management/upgrade.md
  docs/en/docs/install/source-install/compilation-general.md
  docs/zh-CN/docs/admin-manual/cluster-management/upgrade.md
  docs/zh-CN/docs/install/source-install/compilation-general.md
Labels: approved, reviewed

#24903 [fix](load)fix use regex split partition may cause backtracking
  fe/fe-core/src/main/java/org/apache/doris/qe/MultiLoadMgr.java
  fe/fe-core/src/main/java/org/apache/doris/task/StreamLoadTask.java
Labels: approved, reviewed

#24876 [fix](catalog)fix use regex parse partition may cause backtracking
  fe/fe-core/src/main/java/com/amazonaws/glue/catalog/converters/PartitionNameParser.java
Labels: approved, reviewed

#24941 [doc](data-model) refactor data-model
  docs/en/docs/data-table/data-model.md
  docs/zh-CN/docs/data-table/data-model.md
Labels: approved, reviewed

#25068 [refactor](nereids)align node id in explain with nereids node id
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/PhysicalPlanTranslator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/AbstractTreeNode.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/ObjectId.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalOlapScan.java
  regression-test/suites/nereids_syntax_p0/agg_4_phase.groovy
Labels: approved, reviewed

#25129 [runtimeFilter](thrift) define min max runtime filter type
  gensrc/thrift/PlanNodes.thrift
Labels: approved, reviewed

#25025 [bugfix](policy) Forbid creating policy with same name with different resource name
  fe/fe-core/src/main/java/org/apache/doris/policy/PolicyMgr.java
  regression-test/suites/cold_heat_separation/policy/create.groovy
Labels: approved, reviewed, dev/2.0.3

#25021 [bugfix](DDL) Fix the bug of incorrect partition policy setting
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
  fe/fe-core/src/test/java/org/apache/doris/alter/AlterTest.java
Labels: reviewed, dev/2.0.3

#23800 [Enhancement](Load) stream tvf support two phase commit
  be/src/http/action/http_stream.cpp
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/ExternalFileTableValuedFunction.java
  regression-test/data/load_p0/http_stream/test_http_stream_2pc.out
  regression-test/suites/load_p0/http_stream/test_http_stream_2pc.groovy
Labels: approved, reviewed

#25113 [feature](Nereids): Pushdown LimitDistinct Through Join
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/Rewriter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PushdownLimitDistinctThroughJoin.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PushdownTopNThroughJoin.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalAggregate.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalLimit.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalTopN.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/PushdownLimitDistinctThroughJoinTest.java
  regression-test/data/nereids_p0/join/test_limit_join.out
  regression-test/suites/nereids_p0/join/test_limit_join.groovy
Labels: approved, reviewed

#25145 [fix](Nereids) support empty array and map literal
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
Labels: approved, reviewed

#25134 [chore](workflow) 1/2, remove required checks ("License Check", "Clan…
  .asf.yaml
Labels: approved, reviewed

#25159 [fix](Nereids) miss BoolLiteral when convert literal to Nereids' one
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/Literal.java
Labels: approved, reviewed, dev/2.0.3

#25153 [fix](Nereids) bind sink should use full base schema
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/BindSink.java
Labels: approved, reviewed, dev/2.0.3

#25156 [fix](Nereids) deep copier generate wrong slot for TVF
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/copier/LogicalPlanDeepCopier.java
  regression-test/data/nereids_p0/with/test_with.out
  regression-test/suites/nereids_p0/with/test_with.groovy
Labels: reviewed, dev/2.0.3

#25151 [Bug](java-udf) fix java-udf memory leak
  be/src/vec/functions/function_java_udf.cpp
  be/src/vec/functions/function_java_udf.h
Labels: approved, reviewed, dev/2.0.3

#25150 [fix](Nereids) properties parser should return map
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/NereidsParser.java
Labels: approved, reviewed, dev/2.0.3

#25160 [fix](Nereids) unique table support bitmap column
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/ColumnDefinition.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/CreateTableInfo.java
Labels: approved, reviewed, not-merge/2.0

#24891 [Fix](statistics)Fix alter column stats data size is always 0 bug.
  fe/fe-core/src/main/java/org/apache/doris/statistics/ColumnStatisticBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsRepository.java
  regression-test/suites/external_table_p0/jdbc/test_mysql_jdbc_statistics.groovy
  regression-test/suites/statistics/test_basic_statistics.groovy
Labels: approved, reviewed

#25148 [opt](Nereids) support like and regexp function
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinScalarFunctions.java
  regression-test/data/nereids_function_p0/scalar_function/L.out
  regression-test/data/nereids_function_p0/scalar_function/R.out
  regression-test/suites/nereids_function_p0/scalar_function/L.groovy
  regression-test/suites/nereids_function_p0/scalar_function/R.groovy
Labels: approved, reviewed, dev/2.0.3

#25101 [chore](workflow) 2/2, auto trigger "License Check" and "BE Code Formatter" instead…
  .asf.yaml
  .github/workflows/clang-format.yml
  .github/workflows/license-eyes.yml
Labels: approved, reviewed

#25106 [bugfix](thirdparty) Upgrade aws s3 sdk to prevent mem leak
  be/cmake/thirdparty.cmake
  thirdparty/CHANGELOG.md
  thirdparty/download-thirdparty.sh
  thirdparty/patches/aws-sdk-cpp-1.11.119.patch
  thirdparty/vars.sh
Labels: approved, reviewed, dev/2.0.3

#25166 [pipelineX](fix) fix external table scan operator
  be/src/pipeline/exec/scan_operator.h
Labels: approved, reviewed

#25168 [improvement](regression-test) add stream load json case
  regression-test/data/load_p0/stream_load/basic_array_data.json
  regression-test/data/load_p0/stream_load/basic_array_data_by_line.json
  regression-test/data/load_p0/stream_load/basic_data.json
  regression-test/data/load_p0/stream_load/basic_data_by_line.json
  regression-test/data/load_p0/stream_load/test_stream_load_properties.out
  regression-test/suites/load_p0/stream_load/test_stream_load_properties.groovy
Labels: approved, reviewed, dev/2.0.3

#24990 [improvement](meta) Infer the column name when create view if the column is expression
  fe/fe-core/src/main/java/org/apache/doris/analysis/AnalyticExpr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ColumnRefExpr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/Expr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/LiteralExpr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectListItem.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SlotRef.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/VirtualSlotRef.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/analyzer/UnboundFunction.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/AggregateExpression.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/AssertNumRowsElement.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/Expression.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/NamedExpression.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/SubqueryExpr.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/BoundFunction.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/Literal.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/Utils.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/CreateTableAsSelectStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/qe/OlapQueryCacheTest.java
  regression-test/data/ddl_p0/test_create_view.out
  regression-test/suites/ddl_p0/test_create_view.groovy
Labels: approved, reviewed

#25152 [refactor](column) remove unused method and column definitions
  be/src/runtime/primitive_type.h
  be/src/vec/columns/column.h
  be/src/vec/columns/column_array.h
  be/src/vec/columns/column_complex.h
  be/src/vec/columns/column_const.h
  be/src/vec/columns/column_decimal.cpp
  be/src/vec/columns/column_decimal.h
  be/src/vec/columns/column_dictionary.h
  be/src/vec/columns/column_dummy.h
  be/src/vec/columns/column_fixed_length_object.h
  be/src/vec/columns/column_map.h
  be/src/vec/columns/column_nullable.cpp
  be/src/vec/columns/column_nullable.h
  be/src/vec/columns/column_object.h
  be/src/vec/columns/column_set.h
  be/src/vec/columns/column_string.cpp
  be/src/vec/columns/column_string.h
  be/src/vec/columns/column_struct.cpp
  be/src/vec/columns/column_struct.h
  be/src/vec/columns/column_vector.cpp
  be/src/vec/columns/column_vector.h
  be/src/vec/columns/predicate_column.h
Labels: approved, reviewed

#25172 [opt](Nereids) match predicate support array as first arg
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/FunctionBinder.java
  regression-test/data/inverted_index_p0/test_array_index.out
  regression-test/suites/inverted_index_p0/test_array_index.groovy
Labels: approved, reviewed, dev/2.0.3

#25162 [fix](Nereids) alias function support arithmetic functions
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/BindExpression.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/FunctionBinder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/FunctionBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/udf/AliasUdfBuilder.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/analysis/FunctionRegistryTest.java
  regression-test/suites/nereids_p0/javaudf/test_alias_function.groovy
Labels: approved, reviewed, dev/2.0.3

#24861 [Enhancement](log) Improve Safety and Robustness of Log4j Configuration
  fe/fe-core/src/main/java/org/apache/doris/common/Log4jConfig.java
Labels: approved, reviewed

#25079 [feat](optimizer) Scale sample stats with ratio to make it more precise
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisInfo.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisInfoBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/BaseAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/ColStatsData.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/HMSAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/HistogramTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/MVAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/OlapAnalysisTask.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/OlapAnalysisTaskTest.java
Labels: approved, reviewed

#25169 [opt](Nereids) add two args signature to trim family functions
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Ltrim.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Rtrim.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Trim.java
  regression-test/data/nereids_function_p0/scalar_function/L.out
  regression-test/data/nereids_function_p0/scalar_function/R.out
  regression-test/data/nereids_function_p0/scalar_function/T.out
  regression-test/suites/nereids_function_p0/scalar_function/L.groovy
  regression-test/suites/nereids_function_p0/scalar_function/R.groovy
  regression-test/suites/nereids_function_p0/scalar_function/T.groovy
Labels: approved, reviewed, dev/2.0.3

#25007 [FIX](filter) update for filter_by_select logic
  be/src/olap/schema.cpp
  be/src/vec/columns/column.h
  be/src/vec/columns/column_array.cpp
  be/src/vec/columns/column_array.h
  be/src/vec/columns/column_map.cpp
  be/src/vec/columns/column_map.h
  be/src/vec/columns/column_nullable.cpp
  be/src/vec/columns/column_struct.cpp
  be/src/vec/columns/column_struct.h
  be/src/vec/columns/column_vector.h
  be/src/vec/exec/scan/vscan_node.cpp
  fe/fe-core/src/main/java/org/apache/doris/analysis/DeleteStmt.java
  regression-test/data/delete_p0/test_array_column_delete.out
  regression-test/data/delete_p0/test_map_column_delete.out
  regression-test/data/delete_p0/test_struct_column_delete.out
  regression-test/data/query_p0/arr_max.orc
  regression-test/data/query_p0/test_array_with_single_row_max_than_uint16.out
  regression-test/suites/delete_p0/test_array_column_delete.groovy
  regression-test/suites/delete_p0/test_map_column_delete.groovy
  regression-test/suites/delete_p0/test_struct_column_delete.groovy
  regression-test/suites/inverted_index_p0/index_change/test_index_change_7.groovy
  regression-test/suites/inverted_index_p0/test_array_index.groovy
  regression-test/suites/query_p0/test_array_with_single_row_max_than_uint16.groovy
Labels: approved, reviewed, dev/2.0.3

#25155 [feature](Nereids) fold weeks_sub/add on fe
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/executable/DateTimeArithmetic.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/DateLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/DateTimeLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/DateTimeV2Literal.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/DateV2Literal.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/expression/FoldConstantTest.java
Labels: approved, reviewed

#25185 [fix](export) BufferWritable must be committed before deconstruct
  be/src/vec/runtime/vcsv_transformer.cpp
Labels: approved, reviewed

#25084 [feature](pipelineX) add node id and profilev2 in pipelineX
  be/src/pipeline/exec/multi_cast_data_stream_sink.cpp
  be/src/pipeline/exec/multi_cast_data_stream_sink.h
  be/src/pipeline/exec/multi_cast_data_stream_source.h
  be/src/pipeline/exec/union_sink_operator.cpp
  be/src/pipeline/pipeline_x/operator.cpp
  be/src/pipeline/pipeline_x/operator.h
  be/src/pipeline/pipeline_x/pipeline_x_fragment_context.cpp
  be/src/pipeline/pipeline_x/pipeline_x_fragment_context.h
  be/src/util/runtime_profile.cpp
  be/src/util/runtime_profile.h
  fe/fe-core/src/main/java/org/apache/doris/common/profile/Profile.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/ProfileStatistics.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/RuntimeProfile.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BrokerLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  gensrc/thrift/RuntimeProfile.thrift
Labels: approved, reviewed

#25190 [FIX](serde)fix scale with decimalv2 in mysql writer which get real scale
  be/src/vec/sink/vmysql_result_writer.cpp
Labels: approved, reviewed, dev/2.0.3

#24910 [fix](mark join) mark join column should be nullable
  be/src/pipeline/exec/hashjoin_build_sink.cpp
  be/src/pipeline/exec/join_build_sink_operator.h
  be/src/pipeline/pipeline_x/dependency.h
  be/src/vec/columns/column_filter_helper.cpp
  be/src/vec/columns/column_filter_helper.h
  be/src/vec/exec/join/process_hash_table_probe_impl.h
  be/src/vec/exec/join/vhash_join_node.cpp
  be/src/vec/exec/join/vhash_join_node.h
  be/src/vec/exec/join/vjoin_node_base.cpp
  be/src/vec/exec/join/vjoin_node_base.h
  be/src/vec/exec/join/vnested_loop_join_node.cpp
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/MarkJoinSlotReference.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/JoinUtils.java
  regression-test/data/nereids_syntax_p0/sub_query_correlated.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query10.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query35.out
  regression-test/suites/nereids_syntax_p0/sub_query_correlated.groovy
Labels: approved, reviewed, pick_pipelinex, dev/2.0.3

#25202 [fix](doc) spelling error for colocate join #25053
  docs/en/docs/advanced/variables.md
Labels: approved, reviewed

#25154 [fix](Nereids) support string cast to complex type
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/check/CheckCast.java
  regression-test/data/nereids_syntax_p0/cast.out
  regression-test/suites/nereids_syntax_p0/cast.groovy
Labels: approved, reviewed, not-merge/2.0

#25120 [feature](pipelineX) add runtimefliter in pipelineX multicast sink
  be/src/pipeline/exec/multi_cast_data_stream_source.cpp
  be/src/pipeline/exec/multi_cast_data_stream_source.h
Labels: approved, reviewed

#25199 [compile](fix) ubsan compile failure, with relocation R_X86_64_PC32 out of range
  be/CMakeLists.txt
Labels: approved, reviewed

#25176 [Bug](pipeline) Support the auto partition in pipeline load and insert into enable pipeline load
  be/src/pipeline/pipeline_task.cpp
  be/src/runtime/plan_fragment_executor.cpp
  be/src/vec/sink/async_writer_sink.h
  be/src/vec/sink/writer/async_result_writer.cpp
  be/src/vec/sink/writer/async_result_writer.h
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
Labels: approved, reviewed

#25181 [pipelineX](refactor) Refactor pending finish dependency
  be/src/pipeline/exec/exchange_sink_buffer.cpp
  be/src/pipeline/exec/exchange_sink_buffer.h
  be/src/pipeline/exec/exchange_sink_operator.cpp
  be/src/pipeline/exec/exchange_sink_operator.h
  be/src/pipeline/exec/exchange_source_operator.cpp
  be/src/pipeline/exec/exchange_source_operator.h
  be/src/pipeline/exec/jdbc_table_sink_operator.cpp
  be/src/pipeline/exec/jdbc_table_sink_operator.h
  be/src/pipeline/exec/result_file_sink_operator.cpp
  be/src/pipeline/exec/result_file_sink_operator.h
  be/src/pipeline/exec/result_sink_operator.h
  be/src/pipeline/exec/scan_operator.cpp
  be/src/pipeline/exec/scan_operator.h
  be/src/pipeline/pipeline_x/dependency.h
  be/src/pipeline/pipeline_x/operator.cpp
  be/src/pipeline/pipeline_x/operator.h
  be/src/pipeline/pipeline_x/pipeline_x_task.h
  be/src/vec/exec/scan/pip_scanner_context.h
  be/src/vec/exec/scan/scanner_context.cpp
  be/src/vec/exec/scan/scanner_context.h
  be/src/vec/sink/writer/async_result_writer.cpp
  be/src/vec/sink/writer/async_result_writer.h
Labels: approved, reviewed

#25146 [fix](case) Update analyze_stats.groovy
  regression-test/suites/statistics/analyze_stats.groovy
Labels: approved, reviewed, dev/2.0.3

#25167 [fix](Nereids) count_by_enum signature is wrong
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/CountByEnum.java
  regression-test/data/nereids_function_p0/agg_function/agg.out
  regression-test/suites/nereids_function_p0/agg_function/agg.groovy
Labels: approved, reviewed, dev/2.0.3

#25137 [enhancement](Nereids) avoiding broadcast join heuristically and pruning more in CostAndEnforceJob
  fe/fe-core/src/main/java/org/apache/doris/nereids/cost/CostModelV1.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/cascades/CostAndEnforcerJob.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/PhysicalProperties.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/RequestPropertyDeriver.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/properties/RequestPropertyDeriverTest.java
Labels: approved, reviewed

#25218 [Bug](writer) Fix ub in async writer
  be/src/vec/sink/writer/async_result_writer.cpp
Labels: approved, reviewed

#24974 [typo](doc)hot and cold stratification increases FAQ
  docs/en/docs/advanced/cold-hot-separation.md
  docs/zh-CN/docs/advanced/cold-hot-separation.md
Labels: approved, reviewed

#25214 [fix](function) array distance should return null when result is nan
  be/src/vec/functions/array/function_array_distance.h
  regression-test/data/query_p0/sql_functions/array_functions/test_array_distance_functions.out
  regression-test/suites/query_p0/sql_functions/array_functions/test_array_distance_functions.groovy
Labels: approved, reviewed, dev/2.0.3

#25234 [typo](docs) Delete wrong schema change memory parameters
  docs/en/docs/admin-manual/config/be-config.md
  docs/zh-CN/docs/admin-manual/config/be-config.md
Labels: approved, reviewed

#24986 [fix](dbt) fix dbt doris bug that appeared in annotated models and table column comment bug
  extension/dbt-doris/dbt/adapters/doris/__version__.py
  extension/dbt-doris/dbt/adapters/doris/doris_column_item.py
  extension/dbt-doris/dbt/adapters/doris/impl.py
  extension/dbt-doris/dbt/include/doris/dbt_project.yml
  extension/dbt-doris/dbt/include/doris/macros/adapters/columns.sql
  extension/dbt-doris/dbt/include/doris/macros/materializations/table/create_table_as.sql
  extension/dbt-doris/setup.py
Labels: approved, reviewed

#25224 [feature](Nereids) support metadata tvf and fix bugs in group_commit()
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinTableValuedFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/table/Backends.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/table/Catalogs.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/table/Frontends.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/table/FrontendsDisks.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/table/GroupCommit.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/table/IcebergMeta.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/table/Numbers.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/table/WorkloadGroups.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/TableValuedFunctionVisitor.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/MetadataScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/GroupCommitTableValuedFunction.java
Labels: approved, reviewed

#24933 [fix](stack trace) Optimize stack trace output
  be/src/common/stack_trace.cpp
  be/src/common/stack_trace.h
  be/src/common/status.h
  be/src/util/stack_util.cpp
  be/src/util/stack_util.h
Labels: approved, reviewed, dev/2.0.3

#25173 [fix](Nereids) support AnyDataType in function signature
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/ComputeSignature.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/ComputeSignatureHelper.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/Histogram.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/types/coercion/AnyDataType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/TypeCoercionUtils.java
  regression-test/suites/nereids_function_p0/agg_function/agg.groovy
Labels: approved, reviewed, not-merge/2.0

#25107 [fix](httpserver) creating this cookie without the "secure" flag and enabling cross-origin resource safe
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/config/WebConfigurer.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/controller/BaseController.java
Labels: approved, reviewed, dev/2.0.3

#25227 [feature](Nereids) support query MATERIALIZED_VIEW type table
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/BindRelation.java
Labels: approved, reviewed, not-merge/2.0

#25200 [Fix](func numbers) Remove backend_nums argument of numbers function
  be/src/vec/exec/data_gen_functions/vnumbers_tvf.cpp
  docs/en/docs/sql-manual/sql-functions/table-functions/numbers.md
  docs/zh-CN/docs/sql-manual/sql-functions/table-functions/numbers.md
  fe/fe-core/src/main/java/org/apache/doris/planner/DataGenScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/NumbersTableValuedFunction.java
  regression-test/suites/http_rest_api/post/test_query_stmt.groovy
  regression-test/suites/nereids_syntax_p0/aggregate_strategies.groovy
  regression-test/suites/nereids_syntax_p0/function.groovy
  regression-test/suites/nereids_syntax_p2/aggregate_strategies.groovy
Labels: approved, reviewed, dev/2.0.3

#25242 [refactor](column) remove `get_data_type` in IColumn
  be/src/vec/columns/column.h
  be/src/vec/columns/column_array.h
  be/src/vec/columns/column_complex.h
  be/src/vec/columns/column_const.h
  be/src/vec/columns/column_decimal.h
  be/src/vec/columns/column_dictionary.h
  be/src/vec/columns/column_fixed_length_object.h
  be/src/vec/columns/column_map.h
  be/src/vec/columns/column_nullable.h
  be/src/vec/columns/column_object.cpp
  be/src/vec/columns/column_object.h
  be/src/vec/columns/column_string.h
  be/src/vec/columns/column_struct.h
  be/src/vec/columns/column_vector.h
  be/src/vec/columns/predicate_column.h
Labels: approved, reviewed

#24747 [prune](partition)support prune partition when is auto partition with function call
  be/src/vec/sink/writer/vtablet_writer.cpp
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/BinaryPredicate.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/IntLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/PartitionDesc.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/PartitionExprUtil.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SlotRef.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapTableSink.java
  fe/fe-core/src/main/java/org/apache/doris/planner/ScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
  fe/fe-core/src/main/java/org/apache/doris/planner/StreamLoadPlanner.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/RangePartitionPruneTest.java
Labels: approved, reviewed

#25207 [fix](load) fix MemTableWriter::active_memtable_mem_consumption
  be/src/olap/delta_writer_v2.cpp
  be/src/olap/delta_writer_v2.h
  be/src/olap/memtable_writer.cpp
Labels: approved, reviewed, dev/2.0.3

#25122 [improvement](regression-test) open routine load regression test by default and add data check
  docker/thirdparties/run-thirdparties-docker.sh
  regression-test/data/load_p0/routine_load/test_routine_load.out
  regression-test/pipeline/p0/conf/regression-conf.groovy
  regression-test/suites/load_p0/routine_load/test_routine_load.groovy
Labels: approved, reviewed, dev/2.0.3

#25170 [Feature](Job)Jobs in the Finish state will be automatically deleted after three days
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/scheduler/job/Job.java
  fe/fe-core/src/main/java/org/apache/doris/scheduler/manager/TimerJobManager.java
Labels: reviewed

#25212 [regression-test](merge-on-write) Fix partial update concurrency conflict case
  regression-test/data/unique_with_mow_p0/partial_update/partial_update_parallel1.csv
  regression-test/data/unique_with_mow_p0/partial_update/partial_update_parallel2.csv
  regression-test/data/unique_with_mow_p0/partial_update/partial_update_parallel3.csv
  regression-test/data/unique_with_mow_p0/partial_update/test_partial_update_parallel.out
  regression-test/suites/unique_with_mow_p0/partial_update/test_partial_update_parallel.groovy
Labels: approved, reviewed, dev/2.0.3

#25251 [pipelineX](feature) Support set operation operator
  be/src/pipeline/exec/join_probe_operator.h
  be/src/pipeline/exec/partition_sort_source_operator.h
  be/src/pipeline/exec/set_probe_sink_operator.cpp
  be/src/pipeline/exec/set_probe_sink_operator.h
  be/src/pipeline/exec/set_sink_operator.cpp
  be/src/pipeline/exec/set_sink_operator.h
  be/src/pipeline/exec/set_source_operator.cpp
  be/src/pipeline/exec/set_source_operator.h
  be/src/pipeline/exec/union_sink_operator.h
  be/src/pipeline/exec/union_source_operator.h
  be/src/pipeline/pipeline_x/dependency.h
  be/src/pipeline/pipeline_x/operator.cpp
  be/src/pipeline/pipeline_x/pipeline_x_fragment_context.cpp
  be/src/pipeline/pipeline_x/pipeline_x_fragment_context.h
  be/src/pipeline/pipeline_x/pipeline_x_task.h
  be/src/vec/common/hash_table/hash_table_set_build.h
  be/src/vec/common/hash_table/hash_table_set_probe.h
  be/src/vec/exec/vset_operation_node.cpp
  be/src/vec/exec/vset_operation_node.h
Labels: approved, reviewed

#25226 [FIX](array_function) fix array_map function with array index function without checkout arg…
  be/src/vec/functions/array/function_array_index.h
  regression-test/suites/query_p0/sql_functions/array_functions/test_array_map_function.groovy
Labels: approved, reviewed, dev/2.0.3

#25188 [enhancement](node) add filter in partition sort node in BE
  be/src/vec/exec/vpartition_sort_node.cpp
  regression-test/data/query_p0/view/test_view2.out
  regression-test/suites/query_p0/view/test_view2.groovy
Labels: approved, reviewed

#25210 [enhancement](log) add some decheck log to debug
  be/src/vec/sink/vtablet_block_convertor.cpp
Labels: approved, reviewed

#25196 [feature](Nereids) add array distance functions
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinScalarFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/CosineDistance.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/InnerProduct.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/L1Distance.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/L2Distance.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/ScalarFunctionVisitor.java
  regression-test/data/nereids_function_p0/scalar_function/Array.out
  regression-test/suites/nereids_function_p0/scalar_function/Array.groovy
Labels: approved, reviewed, not-merge/2.0

#25165 [compile](simdjson reader) use `__AVX2__` macro to decide whether use…
  be/src/vec/exec/format/json/new_json_reader.cpp
Labels: approved, reviewed, usercase, dev/2.0.3

#24491 [Enhancement](sql-cache) Add partition update time for hms table and use it at sql-cache.
  fe/fe-core/src/main/java/org/apache/doris/catalog/external/ExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/external/HMSExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/external/PaimonExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/TablesProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/CatalogMgr.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalMetaCacheMgr.java
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/CacheAnalyzer.java
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/SqlCache.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/RefreshTableTest.java
  fe/fe-core/src/test/java/org/apache/doris/qe/HmsQueryCacheTest.java
Labels: approved, reviewed

#25275 [fix](pipelineX) mark join column should be nullable
  be/src/pipeline/exec/hashjoin_build_sink.cpp
  be/src/pipeline/exec/hashjoin_probe_operator.cpp
  be/src/pipeline/exec/join_build_sink_operator.h
  be/src/pipeline/exec/join_probe_operator.cpp
  be/src/pipeline/exec/join_probe_operator.h
  be/src/pipeline/exec/nested_loop_join_probe_operator.cpp
  be/src/pipeline/pipeline_x/dependency.h
  be/src/vec/exec/join/vhash_join_node.cpp
Labels: approved, reviewed

#25233 [coverage](test) Delete unused function to improve test coverage
  be/src/runtime/datetime_value.h
  be/src/runtime/runtime_state.cpp
  be/src/runtime/runtime_state.h
  be/src/vec/common/schema_util.cpp
  be/src/vec/common/schema_util.h
  be/src/vec/core/materialize_block.cpp
  be/src/vec/core/materialize_block.h
  be/src/vec/core/sort_block.cpp
  be/src/vec/core/sort_block.h
  be/src/vec/core/types.h
  be/src/vec/exec/format/parquet/parquet_pred_cmp.h
Labels: approved, reviewed

#25262 [Bug](delete) Use date as common type for date comparison
  fe/fe-core/src/main/java/org/apache/doris/analysis/BinaryPredicate.java
Labels: approved, reviewed

#25243 [fix](Nereids) fix `toSql` of date literal
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/DateLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/DateTimeLiteral.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/expression/FoldConstantTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/expression/rules/SimplifyComparisonPredicateSqlTest.java
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query12.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query16.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query20.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query21.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query32.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query37.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query40.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query5.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query58.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query77.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query80.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query82.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query83.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query92.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query94.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query95.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query98.out
  regression-test/data/nereids_tpch_shape_sf1000_p0/shape/q1.out
  regression-test/data/nereids_tpch_shape_sf1000_p0/shape/q10.out
  regression-test/data/nereids_tpch_shape_sf1000_p0/shape/q12.out
  regression-test/data/nereids_tpch_shape_sf1000_p0/shape/q14.out
  regression-test/data/nereids_tpch_shape_sf1000_p0/shape/q15.out
  regression-test/data/nereids_tpch_shape_sf1000_p0/shape/q20-rewrite.out
  regression-test/data/nereids_tpch_shape_sf1000_p0/shape/q20.out
  regression-test/data/nereids_tpch_shape_sf1000_p0/shape/q3.out
  regression-test/data/nereids_tpch_shape_sf1000_p0/shape/q4.out
  regression-test/data/nereids_tpch_shape_sf1000_p0/shape/q5.out
  regression-test/data/nereids_tpch_shape_sf1000_p0/shape/q6.out
  regression-test/data/nereids_tpch_shape_sf1000_p0/shape/q7.out
  regression-test/data/nereids_tpch_shape_sf1000_p0/shape/q8.out
Labels: approved, reviewed, dev/2.0.3

#25277 [Chore](cases) set enable_nereids_planner on mv cases
  regression-test/suites/mv_p0/agg_have_dup_base/agg_have_dup_base.groovy
  regression-test/suites/mv_p0/sum_divede_count/sum_devide_count.groovy
  regression-test/suites/mv_p0/ut/testAggQueryOnAggMV1/testAggQueryOnAggMV1.groovy
  regression-test/suites/mv_p0/ut/testAggQueryOnAggMV10/testAggQueryOnAggMV10.groovy
  regression-test/suites/mv_p0/ut/testAggQueryOnAggMV2/testAggQueryOnAggMV2.groovy
  regression-test/suites/mv_p0/ut/testAggQueryOnAggMV3/testAggQueryOnAggMV3.groovy
  regression-test/suites/mv_p0/ut/testAggQuqeryOnAggMV5/testAggQuqeryOnAggMV5.groovy
  regression-test/suites/mv_p0/ut/testAggQuqeryOnAggMV6/testAggQuqeryOnAggMV6.groovy
  regression-test/suites/mv_p0/ut/testAggQuqeryOnAggMV7/testAggQuqeryOnAggMV7.groovy
  regression-test/suites/mv_p0/ut/testCountDistinctToBitmap/testCountDistinctToBitmap.groovy
  regression-test/suites/mv_p0/ut/testJoinOnLeftProjectToJoin/testJoinOnLeftProjectToJoin.groovy
  regression-test/suites/mv_p0/ut/testNDVToHll/testNDVToHll.groovy
  regression-test/suites/mv_p0/ut/testSubQuery/testSubQuery.groovy
  regression-test/suites/mv_p0/where/k123/k123.groovy
Labels: approved, reviewed, dev/2.0.3
