Repository apache/doris, pull requests merged in 2023-07, with the labels that each got.

#21385 [fix](hudi) use hudi api to split the COW table
  fe/fe-core/src/main/java/org/apache/doris/planner/external/HiveScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/hudi/HudiScanNode.java
Labels: area/planner, approved, reviewed, dev/2.0.0

#21378 [fix](truncate) it will directly return and avoid throwing IllegalStateException caused by bufferSize equals zero when table has no partition
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
  regression-test/suites/ddl_p0/test_truncate_table1.groovy
Labels: kind/test, approved, reviewed, usercase, dev/1.2.6, dev/2.0.0

#21379 [doc](stream load json) modify `enable_simdjson_reader` since it's de…
  docs/en/docs/admin-manual/config/be-config.md
  docs/zh-CN/docs/admin-manual/config/be-config.md
Labels: approved, reviewed, dev/2.0-beta

#21394 [Chore](metrics) remove trace metrics code using runtime profile instand
  be/src/agent/task_worker_pool.cpp
  be/src/olap/base_compaction.cpp
  be/src/olap/compaction.cpp
  be/src/olap/compaction.h
  be/src/olap/cumulative_compaction.cpp
  be/src/olap/merger.cpp
  be/src/olap/tablet.cpp
  be/src/util/trace.cpp
  be/src/util/trace.h
  be/src/util/trace_metrics.cpp
  be/src/util/trace_metrics.h
  docs/en/docs/admin-manual/config/be-config.md
  docs/zh-CN/docs/admin-manual/config/be-config.md
Labels: kind/docs, approved, reviewed, dev/2.0.0

#21343 [fix](exec) run exec_plan_fragment in pthread to avoid BE crash
  be/src/service/internal_service.cpp
  be/src/service/internal_service.h
  regression-test/data/export_p2/test_outfile_p2.out
  regression-test/suites/export_p2/test_outfile_p2.groovy
Labels: kind/test, approved, reviewed, dev/1.2.6, dev/2.0.0

#21405 [tools](refactor) remove unused session variables
  tools/ssb-tools/ssb-queries/q4.1.sql
  tools/ssb-tools/ssb-queries/q4.2.sql
  tools/ssb-tools/ssb-queries/q4.3.sql
  tools/tpch-tools/queries/q1.sql
  tools/tpch-tools/queries/q10.sql
  tools/tpch-tools/queries/q11.sql
  tools/tpch-tools/queries/q12.sql
  tools/tpch-tools/queries/q13.sql
  tools/tpch-tools/queries/q14.sql
  tools/tpch-tools/queries/q15.sql
  tools/tpch-tools/queries/q16.sql
  tools/tpch-tools/queries/q17.sql
  tools/tpch-tools/queries/q18.sql
  tools/tpch-tools/queries/q19.sql
  tools/tpch-tools/queries/q2.sql
  tools/tpch-tools/queries/q20.sql
  tools/tpch-tools/queries/q21.sql
  tools/tpch-tools/queries/q22.sql
  tools/tpch-tools/queries/q3.sql
  tools/tpch-tools/queries/q4.sql
  tools/tpch-tools/queries/q5.sql
  tools/tpch-tools/queries/q6.sql
  tools/tpch-tools/queries/q7.sql
  tools/tpch-tools/queries/q8.sql
  tools/tpch-tools/queries/q9.sql
Labels: approved, reviewed, dev/2.0.0

#21404 [fix](cup) add keywords KW_PERCENT
  fe/fe-core/src/main/cup/sql_parser.cup
Labels: approved, reviewed, dev/1.2.6-merged, dev/2.0.0

#21329 [refactor](load) move generate_delete_bitmap from memtable to beta rowset writer
  be/src/olap/delta_writer.cpp
  be/src/olap/delta_writer.h
  be/src/olap/memtable.cpp
  be/src/olap/memtable.h
  be/src/olap/rowset/beta_rowset_writer.cpp
  be/src/olap/rowset/beta_rowset_writer.h
  be/src/olap/rowset/rowset_writer.h
  be/src/olap/tablet.cpp
Labels: approved, reviewed

#21400 [bug](proc) fix NumberFormatException in show proc '/current_queries'
  fe/fe-core/src/main/java/org/apache/doris/common/proc/CurrentQueryStatementsProcNode.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/CurrentQueryStatisticsProcDir.java
Labels: approved, reviewed, dev/2.0.0

#21411 [fix]Do filter before projection on multi cast sender
  be/src/pipeline/exec/multi_cast_data_stream_source.cpp
  be/src/vec/exec/vselect_node.h
Labels: area/pipeline

#21238 [fix](multi-catalog)fix obj file cache and dlf iceberg catalog
  fe/fe-core/src/main/java/org/apache/doris/common/util/S3Util.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HiveMetaStoreCache.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/HiveCompatibleCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/dlf/DLFCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/PropertyConverter.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/constants/S3Properties.java
  fe/fe-core/src/main/java/org/apache/doris/fs/FileSystemFactory.java
  fe/fe-core/src/main/java/org/apache/doris/fs/obj/S3ObjStorage.java
  fe/fe-core/src/main/java/org/apache/doris/fs/remote/RemoteFile.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/iceberg/IcebergScanNode.java
Labels: area/planner, approved, reviewed

#21361 [improvement](join) Serialize probe keys in a vectorized (columnar) way
  be/src/vec/exec/join/process_hash_table_probe.h
  be/src/vec/exec/join/process_hash_table_probe_impl.h
  be/src/vec/exec/join/vhash_join_node.cpp
Labels: approved, reviewed

#21306 [Fix](orc-reader) Fix `Wrong data type for column` error when column order in hive table is not same in orc file schema.
  docker/thirdparties/docker-compose/hive/scripts/create_preinstalled_table.hql
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/test_different_column_orders/orc/test_different_column_orders.orc
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/test_different_column_orders/parquet/test_different_column_orders.parquet
  docs/en/docs/lakehouse/faq.md
  docs/zh-CN/docs/lakehouse/faq.md
  fe/fe-core/src/main/java/org/apache/doris/catalog/external/HMSExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/HMSExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HiveVersionUtil.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/HiveScanNode.java
  regression-test/data/external_catalog_p0/hive/test_different_column_orders.out
  regression-test/suites/external_catalog_p0/hive/test_different_column_orders.groovy
Labels: kind/docs, area/planner, kind/test, approved, reviewed, dev/2.0.0

#21408 [Chore](storage) add debug info for TabletColumn::get_aggregate_function
  be/src/olap/memtable.cpp
  be/src/olap/tablet_schema.cpp
Labels: reviewed

#21067 [Feature](materialized view) support query match mv with agg_state on nereids planner
  be/src/util/timezone_utils.cpp
  fe/fe-core/src/main/java/org/apache/doris/analysis/NativeInsertStmt.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/mv/SelectMaterializedIndexWithAggregate.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/combinator/StateCombinator.java
  regression-test/data/mv_p0/agg_state/test_agg_state_max_by.out
  regression-test/suites/mv_p0/agg_state/test_agg_state_max_by.groovy
Labels: area/planner, kind/test, approved, reviewed, area/nereids, dev/2.0.0

#21220 [Fix](nereids) fix a bug in ColumnStatistics.numNulls update
  fe/fe-core/src/main/java/org/apache/doris/statistics/Statistics.java
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query21.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query95.out
Labels: approved, reviewed

#21327 [decimalv2](compatibility) add config to allow invalid decimalv2 literal
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/runtime/decimalv2_value.cpp
Labels: approved, reviewed, dev/1.2.6

#21387 [fix](pipeline) fix coredump caused by uncaught exception
  be/src/pipeline/pipeline_fragment_context.cpp
Labels: approved, reviewed, area/pipeline, dev/2.0.0

#21402 [fix](nereids)miss group id in explain plan
  fe/fe-core/src/main/java/org/apache/doris/nereids/memo/GroupId.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/memo/Memo.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/AbstractPlan.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalHashJoin.java
Labels: approved, reviewed, area/nereids

#21395 [fix](Nereids): winmagic rule forgot to visit plan children.
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/AggScalarSubQueryToWindowFunction.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/EnsureProjectOnTopJoin.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/InferPredicates.java
Labels: approved, reviewed, area/nereids

#21430 [Fix](multi-catalog) Add hadoop system classpath to CLASSPATH to resolve can not enable hadoop short circuit reading in some environments.
  bin/start_be.sh
Labels: approved, reviewed, dev/1.2.6, dev/2.0.0

#21399 [Fix](multi-catalog) Fix read error in mixed partition locations.
  fe/fe-core/src/main/java/org/apache/doris/planner/external/FileQueryScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/HiveScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/MaxComputeScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/TVFScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/iceberg/IcebergScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/paimon/PaimonScanNode.java
  regression-test/data/external_table_emr_p2/hive/test_mixed_par_locations.out
  regression-test/suites/external_table_emr_p2/hive/test_mixed_par_locations.groovy
Labels: area/planner, kind/test, approved, reviewed, dev/2.0.0

#20840 [minor](broker) fix name in broker's pom.xml
  env.sh
  fs_brokers/apache_hdfs_broker/pom.xml
Labels: approved, reviewed, dev/2.0.0

#21434 [fix](nereids)cast filter and join conjunct's return type to boolean
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/Rewriter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/AdjustConjunctsReturnType.java
  regression-test/suites/nereids_p0/datatype/test_cast.groovy
Labels: kind/test, approved, reviewed, area/nereids, dev/2.0.0

#21433 [Bug](excution) avoid core dump on filter_block_internal and add debug information
  be/src/vec/core/block.cpp
  be/src/vec/exprs/vexpr_context.cpp
Labels: approved, reviewed

#21444 [opt](docs) update nereids doc to reflect the latest changes
  docs/en/docs/query-acceleration/nereids.md
  docs/zh-CN/docs/query-acceleration/nereids.md
Labels: kind/docs, approved, reviewed

#21449 [typo](docs)Refactor upgrade documentation
  docs/en/docs/admin-manual/cluster-management/upgrade.md
  docs/zh-CN/docs/admin-manual/cluster-management/upgrade.md
Labels: kind/docs, approved, reviewed

#21441 [Fix](multi-catalog) fix NPE for FileCacheValue.
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HiveMetaStoreCache.java
Labels: approved, reviewed, dev/2.0.0

#21427 [improvement](execute) Eliminate virtual function calls when serializing and deserializing aggregate functions
  be/src/vec/common/string_buffer.hpp
Labels: approved, reviewed, dev/2.0.0

#21420 [improvement](memory) improve inserting sparse rows into string column
  be/src/vec/columns/column_decimal.h
  be/src/vec/columns/column_string.cpp
  be/src/vec/columns/column_string.h
  be/src/vec/columns/column_vector.cpp
Labels: approved, reviewed

#21460 [refactor](load) move validator out of VOlapTableSink
  be/src/vec/sink/vtablet_sink.cpp
  be/src/vec/sink/vtablet_sink.h
  be/src/vec/sink/vtablet_validator.cpp
  be/src/vec/sink/vtablet_validator.h
Labels: approved, reviewed

#21346 [fix](nereids)need run ConvertInnerOrCrossJoin rule again after EliminateNotNull
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/Rewriter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/memo/Group.java
  regression-test/data/correctness_p0/test_case_when_decimal.out
  regression-test/suites/correctness_p0/test_case_when_decimal.groovy
Labels: kind/test, approved, reviewed, area/nereids, dev/2.0.0

#21458 [Performance](Nereids): refactor code speedup analyze
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/cascades/CostAndEnforcerJob.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/minidump/NereidsTracer.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/ChildrenPropertiesRegulator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/EnforceMissingPropertiesHelper.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/Statistics.java
Labels: approved, reviewed, area/nereids

#20793 [fix](MTMV) Disable partition specification temporarily
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/test/java/org/apache/doris/catalog/MultiTableMaterializedViewTest.java
Labels: approved, reviewed

#20771 [fix](pipeline) refactor olap table sink close
  be/src/exec/data_sink.h
  be/src/pipeline/exec/operator.h
  be/src/pipeline/exec/scan_operator.cpp
  be/src/pipeline/exec/scan_operator.h
  be/src/pipeline/pipeline_task.cpp
  be/src/vec/exec/scan/vscan_node.cpp
  be/src/vec/exec/scan/vscan_node.h
  be/src/vec/sink/vtablet_sink.cpp
  be/src/vec/sink/vtablet_sink.h
Labels: approved, reviewed, area/pipeline, dev/2.0.0

#21467 [fix] wrong parameter of _acquire_runtime_filter
  be/src/pipeline/exec/multi_cast_data_stream_source.cpp
  be/src/runtime/runtime_filter_mgr.cpp
  be/src/vec/exec/runtime_filter_consumer.cpp
  be/src/vec/exec/runtime_filter_consumer.h
Labels: area/pipeline

#21431 [improve](dependency)Upgrade dependency version
  docs/en/docs/lakehouse/multi-catalog/jdbc.md
  docs/en/docs/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-CATALOG.md
  docs/zh-CN/docs/lakehouse/multi-catalog/jdbc.md
  docs/zh-CN/docs/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-CATALOG.md
  fe/be-java-extensions/jdbc-scanner/pom.xml
  fe/pom.xml
Labels: kind/docs, approved, reviewed

#21383 [chore](tools) add git submodules in .idea/vcs.xml
  .idea/vcs.xml
Labels: approved, reviewed

#21360 [improvement](join) avoid unnecessary copying in _build_output_block
  be/src/vec/exec/join/vhash_join_node.cpp
  be/src/vec/exec/join/vjoin_node_base.cpp
  be/src/vec/exec/join/vjoin_node_base.h
  be/src/vec/exec/join/vnested_loop_join_node.cpp
Labels: approved, reviewed

#21206 [fix](test) fix json test cases by using def keyword to define local variable
  regression-test/suites/json_p0/test_json_load_and_function.groovy
  regression-test/suites/json_p0/test_json_load_unique_key_and_function.groovy
  regression-test/suites/jsonb_p0/test_jsonb_load_and_function.groovy
  regression-test/suites/jsonb_p0/test_jsonb_load_unique_key_and_function.groovy
Labels: kind/test, approved, reviewed

#21373 [Chore](agg-state) add sessionvariable enable_agg_state
  fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ColumnDef.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/VectorizedUtil.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/RuntimeFilterTranslator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/RuntimeFilterGenerator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/BuildCTEAnchorAndCTEProducer.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/InlineCTE.java
  fe/fe-core/src/main/java/org/apache/doris/planner/DistributedPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  regression-test/suites/datatype_p0/agg_state/group_concat/test_agg_state_group_concat.groovy
  regression-test/suites/datatype_p0/agg_state/max/test_agg_state_max.groovy
  regression-test/suites/datatype_p0/agg_state/nereids/test_agg_state_nereids.groovy
  regression-test/suites/datatype_p0/agg_state/test_agg_state.groovy
Labels: area/planner, kind/test, approved, reviewed, area/nereids, dev/2.0.0

#21455 [typo](docs)Delete unsupported sql statements in GROUP_CONCAT()
  docs/en/docs/sql-manual/sql-functions/aggregate-functions/group_concat.md
  docs/zh-CN/docs/sql-manual/sql-functions/aggregate-functions/group_concat.md
Labels: kind/docs, approved, reviewed

#21452 [Performance](Nereids): speedup analyze by removing sort()/addAll() in OptimizeGroupExpressionJob
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/cascades/OptimizeGroupExpressionJob.java
Labels: approved, reviewed, area/nereids

#21435 [Fix](cache) fix lru cache handle field order
  be/src/olap/lru_cache.h
Labels: approved, reviewed, dev/2.0.0

#21412 [refactor](multicast) change the way multicast do filter, project and shuffle
  be/src/pipeline/exec/multi_cast_data_stream_source.cpp
  be/src/pipeline/exec/multi_cast_data_stream_source.h
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/runtime/runtime_filter_mgr.cpp
  be/src/vec/exec/runtime_filter_consumer.cpp
  be/src/vec/exec/runtime_filter_consumer.h
  be/src/vec/exec/scan/vscan_node.cpp
  be/src/vec/exec/scan/vscan_node.h
  be/src/vec/exec/vselect_node.cpp
  be/src/vec/exec/vselect_node.h
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/PhysicalPlanTranslator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/ChildOutputPropertyDeriver.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/ChildrenPropertiesRegulator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/DistributionSpecMustShuffle.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/PhysicalProperties.java
  fe/fe-core/src/main/java/org/apache/doris/planner/DataStreamSink.java
  fe/fe-core/src/main/java/org/apache/doris/planner/ExchangeNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/MultiCastPlanFragment.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PlanFragment.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PlanNode.java
  gensrc/thrift/DataSinks.thrift
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query1.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query2.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query24.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query30.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query47.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query57.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query81.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query95.out
Labels: area/planner, approved, reviewed, area/nereids, area/pipeline, dev/2.0.0

#21260 [opt](hudi) use spark bundle to read hudi data
  be/src/vec/exec/scan/hudi_jni_reader.cpp
  be/src/vec/exec/scan/hudi_jni_reader.h
  bin/start_be.sh
  fe/be-java-extensions/avro-scanner/src/main/java/org/apache/doris/avro/AvroColumnValue.java
  fe/be-java-extensions/avro-scanner/src/main/java/org/apache/doris/avro/AvroJNIScanner.java
  fe/be-java-extensions/hudi-scanner/pom.xml
  fe/be-java-extensions/hudi-scanner/src/main/java/org/apache/doris/hudi/HudiColumnValue.java
  fe/be-java-extensions/hudi-scanner/src/main/java/org/apache/doris/hudi/HudiJniScanner.java
  fe/be-java-extensions/hudi-scanner/src/main/java/org/apache/doris/hudi/HudiScanParam.java
  fe/be-java-extensions/hudi-scanner/src/main/java/org/apache/doris/hudi/HudiScanUtils.java
  fe/be-java-extensions/hudi-scanner/src/main/java/org/apache/doris/hudi/Utils.java
  fe/be-java-extensions/hudi-scanner/src/main/scala/org/apache/doris/hudi/BaseSplitReader.scala
  fe/be-java-extensions/hudi-scanner/src/main/scala/org/apache/doris/hudi/HoodieRecordIterator.scala
  fe/be-java-extensions/hudi-scanner/src/main/scala/org/apache/doris/hudi/MORSnapshotSplitReader.scala
  fe/be-java-extensions/java-common/src/main/java/org/apache/doris/common/jni/JniScanner.java
  fe/be-java-extensions/java-common/src/main/java/org/apache/doris/common/jni/MockJniScanner.java
  fe/be-java-extensions/java-common/src/main/java/org/apache/doris/common/jni/vec/ColumnValue.java
  fe/be-java-extensions/java-common/src/main/java/org/apache/doris/common/jni/vec/NativeColumnValue.java
  fe/be-java-extensions/java-common/src/main/java/org/apache/doris/common/jni/vec/ScanPredicate.java
  fe/be-java-extensions/java-common/src/main/java/org/apache/doris/common/jni/vec/VectorColumn.java
  fe/be-java-extensions/java-common/src/main/java/org/apache/doris/common/jni/vec/VectorTable.java
  fe/be-java-extensions/max-compute-scanner/src/main/java/org/apache/doris/maxcompute/MaxComputeColumnValue.java
  fe/be-java-extensions/max-compute-scanner/src/main/java/org/apache/doris/maxcompute/MaxComputeJniScanner.java
  fe/be-java-extensions/paimon-scanner/src/main/java/org/apache/doris/paimon/PaimonColumnValue.java
  fe/be-java-extensions/paimon-scanner/src/main/java/org/apache/doris/paimon/PaimonJniScanner.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/HudiUtils.java
Labels: approved, reviewed

#21410 [fix](heartbeat) need to set backend status base on edit log
  fe/fe-core/src/main/java/org/apache/doris/system/Backend.java
  fe/fe-core/src/main/java/org/apache/doris/system/HeartbeatMgr.java
Labels: approved, reviewed, dev/1.2.6-merged, dev/2.0.0

#21265 [improvement](kerberos) disable hdfs fs handle cache to renew kerberos ticket at fix interval
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/io/fs/hdfs_file_system.cpp
  be/src/io/fs/hdfs_file_system.h
  be/src/io/hdfs_builder.cpp
Labels: approved, reviewed, dev/2.0.0

#21354 [fix](Nereids): decrease the memo GroupExpression of limits
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
Labels: approved, reviewed

#21216 [revert](nereids) Revert data size agg
  fe/fe-core/src/main/java/org/apache/doris/statistics/BaseAnalysisTask.java
Labels: approved, reviewed, not-merge/2.0.0

#21194 [fix](regression case) fix variable scope bug in some inverted index regression cases
  regression-test/suites/inverted_index_p0/test_add_drop_index_ignore_case_column.groovy
  regression-test/suites/inverted_index_p0/test_add_drop_index_with_data.groovy
  regression-test/suites/inverted_index_p0/test_add_drop_index_with_delete_data.groovy
  regression-test/suites/inverted_index_p0/test_index_match_phrase.groovy
  regression-test/suites/inverted_index_p0/test_index_match_select.groovy
  regression-test/suites/inverted_index_p0/test_index_range_in_select.groovy
  regression-test/suites/inverted_index_p0/test_index_range_not_in_select.groovy
Labels: kind/test, approved, reviewed

#21445 [typo](docs) fix presto jdbc catalog docs
  docs/en/docs/lakehouse/multi-catalog/jdbc.md
  docs/zh-CN/docs/lakehouse/multi-catalog/jdbc.md
Labels: kind/docs, approved, reviewed

#21447 [fix](jdbc) fix presto jdbc catalog pushDown and nameFormat
  fe/fe-core/src/main/java/org/apache/doris/catalog/JdbcTable.java
  fe/fe-core/src/main/java/org/apache/doris/planner/JdbcScanNode.java
Labels: area/planner, approved, reviewed

#21380 [improvement](jdbc)Support for automatically obtaining the precision of the hana timestamp type
  fe/fe-core/src/main/java/org/apache/doris/external/jdbc/JdbcSapHanaClient.java
Labels: approved, reviewed

#21386 [improvement](jdbc)Support for automatically obtaining the precision of the trino/presto timestamp type
  fe/fe-core/src/main/java/org/apache/doris/external/jdbc/JdbcTrinoClient.java
Labels: approved, reviewed

#21457 [docs](releasenote) 2.0 beta release note
  README.md
  docs/en/docs/releasenotes/release-2.0-beta.md
  docs/images/Beta_1.png
  docs/images/Beta_2.png
  docs/images/Beta_3.png
  docs/images/Beta_4.png
  docs/images/Beta_5.png
  docs/images/Beta_6.png
  docs/images/Beta_7.png
  docs/images/Beta_8.png
  docs/sidebars.json
  docs/zh-CN/docs/releasenotes/release-2.0-beta.md
Labels: kind/docs, approved, reviewed

#21432 [performance](group_concat) avoid extra copy in group_concat
  be/src/vec/aggregate_functions/aggregate_function_group_concat.h
Labels: approved, reviewed

#21486 [fix](memory) fix jemalloc purge arena dirty pages core dump
  be/src/util/mem_info.h
Labels: approved, reviewed, dev/1.2.6

#21440 [enchanment](udf) add more info when download jar package failed
  be/src/runtime/user_function_cache.cpp
Labels: area/planner, approved, reviewed, dev/1.2.6

#21397 [Fix](CCR) Binlog config is missed when create replica task
  fe/fe-core/src/main/java/org/apache/doris/alter/RollupJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/backup/RestoreJob.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/master/ReportHandler.java
  fe/fe-core/src/main/java/org/apache/doris/task/CreateReplicaTask.java
  fe/fe-core/src/test/java/org/apache/doris/task/AgentTaskTest.java
Labels: approved, reviewed, dev/2.0.0

#21466 [Fix](CCR) Use tableId as the credential for CCR syncer instead of tableName
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  gensrc/thrift/FrontendService.thrift
  regression-test/framework/src/main/groovy/org/apache/doris/regression/json/BinlogData.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Syncer.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/SyncerContext.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/util/SyncerUtils.groovy
Labels: kind/test, approved, reviewed

#21498 [fix](feut)should not create a DeriveStatsJob in fe ut
  fe/fe-core/src/test/java/org/apache/doris/nereids/util/HyperGraphBuilder.java
Labels: approved, reviewed, area/nereids

#21494 [fix](hudi) scala can't call Properties.putAll in jdk11
  fe/be-java-extensions/hudi-scanner/src/main/scala/org/apache/doris/hudi/BaseSplitReader.scala
Labels: approved, reviewed, dev/2.0.0

#21500 [Bug](agg-state) fix core dump on not nullable argument for aggstate's nested argument
  be/src/vec/exprs/vectorized_agg_fn.cpp
  fe/fe-core/src/main/java/org/apache/doris/analysis/ArithmeticExpr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/NativeInsertStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/MaterializedIndexMeta.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/AggStateFunctionBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/combinator/MergeCombinator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/combinator/StateCombinator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/combinator/UnionCombinator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/types/AggStateType.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ExprTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/LoadStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/RepeatNodeTest.java
  regression-test/data/datatype_p0/agg_state/max/test_agg_state_max.out
  regression-test/data/mv_p0/k1ap2spa/k1ap2spa.out
  regression-test/suites/datatype_p0/agg_state/max/test_agg_state_max.groovy
  regression-test/suites/mv_p0/k1ap2spa/k1ap2spa.groovy
Labels: area/planner, kind/test, area/nereids, dev/2.0.0

#21492 [fix](dbt) dbt seed config read
  extension/dbt-doris/dbt/include/doris/macros/adapters/relation.sql
  extension/dbt-doris/dbt/include/doris/macros/materializations/seed/helpers.sql
Labels: approved, reviewed

#21392 [fix](dbt) dbt-doris match dbt-core==1.5
  extension/dbt-doris/dbt/adapters/doris/relation.py
  extension/dbt-doris/setup.py
Labels: approved, reviewed

#21345 [fix](dbt) dbt getconfig array or string
  extension/dbt-doris/dbt/include/doris/macros/adapters/relation.sql
Labels: approved, reviewed

#21475 [Chore](runtime filter) change runtime filter dcheck to error status or exception
  be/src/exprs/runtime_filter_slots.h
  be/src/exprs/runtime_filter_slots_cross.h
Labels: approved, reviewed, dev/2.0.0

#21480 [fix](nereids) fix runtime filter expr order
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/RuntimeFilterGenerator.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/Statistics.java
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query95.out
Labels: approved, reviewed, area/nereids

#21499 [branch-2.0](profile)add doris-version to profile
  fe/fe-core/src/main/java/org/apache/doris/common/profile/SummaryProfile.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BrokerLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
Labels: area/load

#21311 [improve](memory) more grace logging for memory exceed limit
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/common/daemon.cpp
  be/src/runtime/memory/mem_tracker_limiter.cpp
  be/src/runtime/memory/mem_tracker_limiter.h
  be/src/runtime/thread_context.h
  be/src/service/doris_main.cpp
  be/src/util/mem_info.cpp
  be/src/vec/common/allocator.cpp
Labels: approved, reviewed, dev/2.0.0

#21223 [Enhancement](regression-test)Add regression test for MoW backup and restore
  regression-test/data/backup_restore/test_MoW_backup_restore.out
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
  regression-test/suites/backup_restore/test_MoW_backup_restore.groovy
Labels: kind/test, approved, reviewed, dev/2.0.0

#21521 [Fix](planner)replace limit to -1 if is Long.MAX_VALUE
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
Labels: area/planner, approved, reviewed, dev/1.2.6

#20964 [Fix](Comment) Comment should be in English
  be/src/olap/snapshot_manager.cpp
Labels: approved, reviewed

#21496 [fix](Nereids) set operation physical properties derive is wrong
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/ChildOutputPropertyDeriver.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/RequestPropertyDeriver.java
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query49.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query75.out
Labels: approved, reviewed, area/nereids, dev/2.0.0

#21437 [feature](Nereids): pushdown distinct through join.
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/Rewriter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/ProjectWithDistinctToAggregate.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/InferSetOperatorDistinct.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PushdownDistinctThroughJoin.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalAggregate.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/PushdownDistinctThroughJoinTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/util/LogicalPlanBuilder.java
Labels: approved, reviewed, area/nereids

#21207 [improvement](statistics, multi catalog)Estimate hive table row count based on file size.
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/external/HMSExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticConstants.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsCache.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/TableStatisticsCacheLoader.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/util/StatisticsUtil.java
Labels: approved, reviewed, area/nereids, dev/2.0.0

#21303 [pipeline](load) return error status in pipeline load
  be/src/pipeline/task_scheduler.cpp
Labels: approved, reviewed, area/pipeline

#21401 [fix](s3) fix s3 fs benchmark tool
  be/src/io/file_factory.cpp
  be/src/io/file_factory.h
  be/src/io/fs/benchmark/base_benchmark.h
  be/src/io/fs/benchmark/benchmark_factory.hpp
  be/src/io/fs/benchmark/fs_benchmark_tool.cpp
  be/src/io/fs/benchmark/s3_benchmark.hpp
  be/src/io/fs/buffered_reader.cpp
  be/src/util/s3_util.cpp
  be/src/util/s3_util.h
  be/src/vec/core/block_spill_reader.cpp
  be/src/vec/exec/format/csv/csv_reader.cpp
  bin/run-fs-benchmark.sh
  bin/start_be.sh
  docs/en/docs/lakehouse/fs_benchmark_tool.md
  docs/zh-CN/docs/lakehouse/fs_benchmark_tool.md
Labels: kind/docs, approved, reviewed, dev/2.0.0

#21333 [Fix](multi-catalog) Fallback to refresh catalog when hms events are missing
  fe/fe-core/src/main/java/org/apache/doris/datasource/HMSExternalCatalog.java
Labels: approved, reviewed, dev/2.0.0

#21446 [Enhancement](multi-catalog) Add some checks for ShowPartitionsStmt.
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowPartitionsStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/DatabaseIf.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
Labels: area/planner, approved, reviewed, dev/2.0.0

#21519 [fix](Nereids): when child is Aggregate, don't infer Distinct for it
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/InferSetOperatorDistinct.java
Labels: approved, reviewed, area/nereids, not-merge/2.0.0

#21520 [fix](backup) fix show snapshot cauing mysql connection lost
  fe/fe-core/src/main/java/org/apache/doris/backup/Repository.java
Labels: approved, reviewed, dev/1.2.6, dev/2.0.0

#21511 [fix](status) Return the correct error code when clucene error occured
  be/src/olap/task/index_builder.cpp
Labels: approved, reviewed, dev/2.0.0

#21476 [refactor](load) expand OlapTableValidator to VOlapTableBlockConvertor
  be/src/vec/sink/vtablet_block_convertor.cpp
  be/src/vec/sink/vtablet_block_convertor.h
  be/src/vec/sink/vtablet_sink.cpp
  be/src/vec/sink/vtablet_sink.h
Labels: approved, reviewed

#21536 [regression-test](load) add streamload default value test
  regression-test/data/load_p0/stream_load/test_default_value.csv
  regression-test/suites/load_p0/stream_load/test_stream_load.groovy
Labels: kind/test, approved, reviewed, dev/1.2.6, dev/2.0.0

#21205 [enhancement](query) enable strong consistency by syncing max journal id from master
  docs/en/docs/advanced/variables.md
  docs/zh-CN/docs/advanced/variables.md
  fe/fe-core/src/main/java/org/apache/doris/qe/MasterOpExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  gensrc/thrift/FrontendService.thrift
Labels: kind/docs, area/planner, approved, reviewed, usercase, dev/1.2.6, dev/2.0.0

#21512 [bugfix](RowsetIterator) use valid stats when creating segment iterator
  be/src/olap/rowset/beta_rowset_reader.cpp
Labels: approved, reviewed, dev/2.0.0

#21517 [Fix](be)fix be core no print queryid
  be/src/common/signal_handler.h
Labels: approved, reviewed

#21372 [refactor](load) split flush_segment_writer into two parts
  be/src/olap/delta_writer.h
  be/src/olap/rowset/beta_rowset_writer.cpp
  be/src/olap/rowset/beta_rowset_writer.h
  be/src/olap/rowset/segcompaction.cpp
  be/src/olap/rowset/segcompaction.h
  be/src/runtime/tablets_channel.cpp
  be/test/olap/delta_writer_test.cpp
  be/test/olap/engine_storage_migration_task_test.cpp
  be/test/olap/remote_rowset_gc_test.cpp
  be/test/olap/tablet_cooldown_test.cpp
Labels: approved, reviewed

#21381 [Enhancement](inverted index) make InvertedIndexReader shared_from_this
  be/src/olap/rowset/segment_v2/column_reader.cpp
  be/src/olap/rowset/segment_v2/column_reader.h
  be/src/olap/rowset/segment_v2/inverted_index_reader.cpp
  be/src/olap/rowset/segment_v2/inverted_index_reader.h
  be/src/olap/rowset/segment_v2/segment.cpp
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
Labels: approved, reviewed, dev/2.0.0

#21506 [Bug](row store) Fix column aggregate info lost when table is unique …
  fe/fe-core/src/main/java/org/apache/doris/analysis/ColumnDef.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateTableStmt.java
  regression-test/suites/row_store/load.groovy
Labels: area/planner, kind/test, approved, reviewed, dev/2.0.0

#21553 [Fix](ScannerScheduler) fix dead lock when shutdown group_local_scan_thread_pool
  be/src/vec/exec/scan/scanner_scheduler.cpp
Labels: approved, reviewed

#21548 [Fix](multi-catalog) Fix hadoop short circuit reading can not enabled in some environments.
  be/CMakeLists.txt
  bin/start_be.sh
  bin/start_fe.sh
  build.sh
  conf/hdfs-site.xml
  docs/en/docs/lakehouse/multi-catalog/hive.md
  docs/zh-CN/docs/lakehouse/multi-catalog/hive.md
  thirdparty/build-thirdparty.sh
Labels: kind/docs, dev/1.2.6

#21510 [profile](join) add collisions into profile
  be/src/vec/common/hash_table/hash_table.h
  be/src/vec/common/hash_table/partitioned_hash_table.h
  be/src/vec/exec/join/process_hash_table_probe_impl.h
  be/src/vec/exec/join/vhash_join_node.cpp
  be/src/vec/exec/join/vhash_join_node.h
Labels: approved, reviewed

#21556 [fix](gc) infinit loop when handle exceed limit memory
  be/src/runtime/load_channel_mgr.cpp
Labels: approved, reviewed, dev/2.0.0

#21516 [Fix](multi-catalog) Fix hadoop short circuit reading can not enabled in some environments.
  be/CMakeLists.txt
  bin/run-fs-benchmark.sh
  bin/start_be.sh
  bin/start_fe.sh
  build.sh
  conf/hdfs-site.xml
  docs/en/docs/lakehouse/multi-catalog/hive.md
  docs/zh-CN/docs/lakehouse/multi-catalog/hive.md
  thirdparty/build-thirdparty.sh
Labels: kind/docs, approved, reviewed, dev/2.0.0

#21471 [Enhancement](multi-catalog) Make meta cache batch loading concurrently.
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/common/ThreadPoolManager.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/CacheBulkLoader.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalMetaCacheMgr.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalSchemaCache.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/HMSExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HiveMetaStoreCache.java
  fe/fe-core/src/test/java/org/apache/doris/common/CacheBulkLoaderTest.java
Labels: approved, reviewed, dev/2.0.0

#20602 [opt](planner) add important time to profile in planner
  fe/fe-core/src/main/java/org/apache/doris/common/profile/SummaryProfile.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OriginalPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
Labels: area/planner, approved, reviewed, area/nereids

#21186 [Fix](Planner) Set inline view output as non constant after analyze
  fe/fe-core/src/main/java/org/apache/doris/analysis/Expr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/QueryStmtTest.java
  regression-test/data/query_p0/sql_functions/conditional_functions/test_nullif.out
  regression-test/suites/query_p0/sql_functions/conditional_functions/test_nullif.groovy
Labels: area/planner, kind/test, approved, reviewed, usercase

#21212 [Fix](Planner) Set inline view output as non constant after analyze
  fe/fe-core/src/main/java/org/apache/doris/analysis/Expr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/QueryStmtTest.java
  regression-test/data/query_p0/sql_functions/conditional_functions/test_nullif.out
  regression-test/suites/query_p0/sql_functions/conditional_functions/test_nullif.groovy
Labels: area/planner, kind/test, approved, reviewed, usercase, dev/2.0.0

#21542 [branch-1.2-lts](memtable) change memtable flush error code
  be/src/olap/memtable_flush_executor.cpp
Labels: approved, reviewed, dev/1.2.6

#21533 [fix](nereids)fix some planner bugs
  fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/check/CheckCast.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PruneOlapScanTablet.java
  fe/fe-core/src/main/java/org/apache/doris/planner/HashDistributionPruner.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
  fe/fe-core/src/test/java/org/apache/doris/planner/HashDistributionPrunerTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/OlapScanNodeTest.java
  regression-test/data/correctness_p0/test_constant_having.out
  regression-test/suites/correctness_p0/test_constant_having.groovy
  regression-test/suites/nereids_p0/datatype/test_cast.groovy
  regression-test/suites/nereids_p0/test_prune_tablet_mv.groovy
Labels: area/planner, kind/test, approved, reviewed, area/nereids, sqlancer, dev/2.0.0

#21462 [refactor](load) move find_tablet() out of VOlapTableSink
  be/src/vec/sink/vtablet_finder.cpp
  be/src/vec/sink/vtablet_finder.h
  be/src/vec/sink/vtablet_sink.cpp
  be/src/vec/sink/vtablet_sink.h
Labels: approved, reviewed

#21547 [refactor](load) move memtable flush logic to flush token and rowset writer
  be/src/olap/delta_writer.cpp
  be/src/olap/delta_writer.h
  be/src/olap/memtable.cpp
  be/src/olap/memtable.h
  be/src/olap/memtable_flush_executor.cpp
  be/src/olap/memtable_flush_executor.h
  be/src/olap/rowset/beta_rowset_writer.cpp
  be/src/olap/rowset/beta_rowset_writer.h
  be/src/olap/rowset/rowset_writer.h
  be/src/olap/tablet.cpp
Labels: approved, reviewed

#21534 [fix](sink) Fix NodeChannel add_block_closure null pointer
  be/src/vec/sink/vtablet_sink.cpp
Labels: approved, reviewed

#21529 [fix](type system) fix datetimev2 write column to arrow
  be/src/vec/data_types/serde/data_type_datetimev2_serde.cpp
  regression-test/suites/source_p0/ddl/create.sql
  regression-test/suites/source_p0/ddl/insert.sql
  regression-test/suites/source_p0/doris_source.groovy
Labels: kind/test, approved, reviewed, dev/2.0.0

#21582 [typo](doc)Delete alter system modify broker related documents
  docs/en/docs/sql-manual/sql-reference/Cluster-Management-Statements/ALTER-SYSTEM-MODIFY-BROKER.md
  docs/sidebars.json
  docs/zh-CN/docs/sql-manual/sql-reference/Cluster-Management-Statements/ALTER-SYSTEM-MODIFY-BROKER.md
Labels: kind/docs

#21493 [fix](executor) make elt / repeat smooth upgrade.
  be/src/agent/be_exec_version_manager.h
  be/src/vec/functions/function_string.cpp
  be/src/vec/functions/function_string.h
Labels: approved, reviewed, dev/2.0.0

#21584 Revert "[Fix](Planner) Set inline view output as non constant after a…
  fe/fe-core/src/main/java/org/apache/doris/analysis/Expr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/QueryStmtTest.java
  regression-test/data/query_p0/sql_functions/conditional_functions/test_nullif.out
  regression-test/suites/query_p0/sql_functions/conditional_functions/test_nullif.groovy
Labels: area/planner, kind/test

#21481 [Improvement](statistics, multi catalog)Support iceberg table stats collection.
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/external/HMSExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/external/IcebergExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/external/hive/util/HiveUtil.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/HMSAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/HiveAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/IcebergAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/util/StatisticsUtil.java
Labels: approved, reviewed

#21459 [Refactor](multi-catalog) Conjuncts are currently split, so refactor source code to handle split conjuncts for dict filters.
  be/src/vec/exec/scan/vfile_scanner.cpp
  be/src/vec/exec/scan/vfile_scanner.h
Labels: approved, reviewed, dev/2.0.0

#21538 [typo](docs) modify java version to 1.8
  docs/en/docs/install/source-install/compilation-mac.md
  docs/zh-CN/docs/install/source-install/compilation-mac.md
Labels: kind/docs

#21562 [improvement](multi catalog)Use getPartitionsByNames to retrieve hive partitions.
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HiveMetaStoreCache.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/PooledHiveMetaStoreClient.java
  fe/fe-core/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
Labels: approved, reviewed, dev/2.0.0

#21577 [fix](dbt) fix _MISSING_TYPE object is not callable bug
  extension/dbt-doris/dbt/adapters/doris/__version__.py
  extension/dbt-doris/dbt/adapters/doris/connections.py
  extension/dbt-doris/dbt/adapters/doris/impl.py
  extension/dbt-doris/dbt/adapters/doris/relation.py
  extension/dbt-doris/dbt/include/doris/dbt_project.yml
  extension/dbt-doris/dbt/include/doris/macros/adapters/relation.sql
  extension/dbt-doris/setup.py
Labels: approved, reviewed

#21388 [refactor](udf) refactor java-udf execute method by using for loop
  be/src/vec/functions/function_java_udf.cpp
  be/src/vec/functions/function_java_udf.h
  fe/be-java-extensions/java-udf/src/main/java/org/apache/doris/udf/UdfConvert.java
  fe/be-java-extensions/java-udf/src/main/java/org/apache/doris/udf/UdfExecutor.java
Labels: approved, reviewed

#20230 (chore) Disable ssl connection to FE by default for compatibility reason
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
Labels: approved, reviewed, dev/2.0.0

#21561 [improve](doc) add doc about explain plan
  docs/en/docs/advanced/best-practice/query-analysis.md
  docs/zh-CN/docs/advanced/best-practice/query-analysis.md
Labels: kind/docs, approved, reviewed

#21566 [fix](test) build internal table for TPCHTest to fix testRank
  fe/fe-core/src/test/java/org/apache/doris/nereids/datasets/tpch/TPCHTestBase.java
Labels: approved, reviewed, area/nereids, dev/2.0.0

#21601 [Enhancement](inverted index) reset global instance for InvertedIndexSearcherCache when destroy
  be/src/olap/rowset/segment_v2/inverted_index_cache.h
  be/src/runtime/exec_env_init.cpp
Labels: approved, reviewed

#21592 [fix](partial update) correct col_nums when init agg state in memtable
  be/src/olap/memtable.cpp
  regression-test/data/unique_with_mow_p0/partial_update/basic_with_duplicate.csv
  regression-test/data/unique_with_mow_p0/partial_update/basic_with_duplicate2.csv
  regression-test/data/unique_with_mow_p0/partial_update/test_partial_update.out
  regression-test/suites/unique_with_mow_p0/partial_update/test_partial_update.groovy
Labels: kind/test, approved, reviewed, dev/2.0.0

#21545 [fix](sink) fix OlapTableSink early close causes load failure
  be/src/vec/sink/vtablet_sink.cpp
  be/src/vec/sink/vtablet_sink.h
Labels: approved, reviewed, dev/2.0.0

#21569 [Improve](mysql)ensure constant time for computing hash value
  fe/fe-core/src/main/java/org/apache/doris/mysql/MysqlPassword.java
Labels: approved, reviewed, dev/2.0.0

#21610 [fix](Nereids) union distinct should not prune any column
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/ColumnPruning.java
  regression-test/data/nereids_syntax_p0/set_operation.out
  regression-test/suites/nereids_syntax_p0/set_operation.groovy
Labels: kind/test, approved, reviewed, area/nereids, dev/2.0.0

#21442 [Enhancement](multi-catalog) Add hdfs read statistics profile.
  be/src/io/file_factory.cpp
  be/src/io/file_factory.h
  be/src/io/fs/benchmark/hdfs_benchmark.hpp
  be/src/io/fs/hdfs_file_reader.cpp
  be/src/io/fs/hdfs_file_reader.h
  be/src/io/fs/hdfs_file_system.cpp
  be/src/io/fs/hdfs_file_system.h
  be/src/runtime/snapshot_loader.cpp
  be/src/vec/runtime/vfile_result_writer.cpp
Labels: approved, reviewed, dev/2.0.0

#21546 [fix](kerberos) should renew the kerberos ticket each half of ticket lifetime
  be/src/io/fs/hdfs_file_system.h
Labels: approved, reviewed, dev/2.0.0

#21578 [typo](doc)Delete alter system modify broker related documents
  docs/en/docs/sql-manual/sql-reference/Cluster-Management-Statements/ALTER-SYSTEM-MODIFY-BROKER.md
  docs/sidebars.json
  docs/zh-CN/docs/sql-manual/sql-reference/Cluster-Management-Statements/ALTER-SYSTEM-MODIFY-BROKER.md
Labels: kind/docs, approved, reviewed

#21428 [fix](nereids) Agg on unknown-stats column
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/StatsCalculator.java
Labels: approved, reviewed, area/nereids, dev/2.0.0

#21598 [fix](catalog) wrong required slot info causing BE crash
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HiveMetaStoreCache.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/FileQueryScanNode.java
  regression-test/data/external_table_emr_p2/hive/test_external_catalog_hive.out
  regression-test/suites/external_table_emr_p2/hive/test_external_catalog_hive.groovy
Labels: area/planner, kind/test, approved, reviewed, dev/2.0.0

#20599 [Fix](Planner) Change return type in where, having and on clause
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/TableRef.java
  regression-test/suites/query_p0/cast/test_cast.groovy
Labels: area/planner, kind/test, approved, reviewed, area/nereids, dev/2.0.0

#21138 [Enhancement](planner&Nereids)support sql_select_limit for master
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/Rewriter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/AddDefaultLimit.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
  regression-test/suites/nereids_p0/session_variable/test_default_limit.groovy
  regression-test/suites/query_p0/session_variable/test_default_limit.groovy
Labels: area/planner, kind/test, approved, reviewed, area/nereids, dev/2.0.0

#21565 [opt](Nereids) forbid some bad case on agg plans
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/PhysicalPlanTranslator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/ChildrenPropertiesRegulator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/implementation/AggregateStrategies.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/AggregateParam.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/MultiDistinctCount.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/MultiDistinctGroupConcat.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/MultiDistinctSum.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/MultiDistinction.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/algebra/Aggregate.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalStorageLayerAggregate.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/ExpressionUtils.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/AggregateStrategiesTest.java
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query94.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query95.out
  regression-test/data/nereids_tpch_shape_sf1000_p0/shape/q16.out
  regression-test/data/nereids_tpch_shape_sf500_p0/shape/q16.out
  regression-test/suites/nereids_p0/join/test_join.groovy
  regression-test/suites/nereids_syntax_p0/agg_4_phase.groovy
  regression-test/suites/nereids_syntax_p0/aggregate_strategies.groovy
  regression-test/suites/nereids_syntax_p0/group_concat.groovy
Labels: kind/test, approved, reviewed, area/nereids, dev/2.0.0

#21362 [improvement](pipeline) ADD LOG in analyze task
  fe/fe-core/src/main/java/org/apache/doris/statistics/OlapAnalysisTask.java
Labels: kind/test, approved, reviewed

#21317 [fix](nereids)don't build cte producer if the consumer is empty relation
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/BuildCTEAnchorAndCTEProducer.java
  regression-test/suites/nereids_syntax_p0/cte.groovy
Labels: kind/test, approved, reviewed, area/nereids, dev/2.0.0

#21631 [fix](Nereids) compile failed because skip pick pr from master
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalAggregate.java
Labels: area/nereids

#21615 [fix](Nereids) Add alias name for system variable
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
Labels: kind/test, approved, reviewed, area/nereids, dev/2.0.0

#21637 [Feature](binlog) Add getBinlogLag
  fe/fe-core/src/main/java/org/apache/doris/binlog/BinlogManager.java
  fe/fe-core/src/main/java/org/apache/doris/binlog/BinlogUtils.java
  fe/fe-core/src/main/java/org/apache/doris/binlog/DBBinlog.java
  fe/fe-core/src/main/java/org/apache/doris/binlog/TableBinlog.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  gensrc/thrift/FrontendService.thrift
Labels: approved, reviewed

#21638 [fix][improvement](fs) add HdfsIO profile and modification time
  be/src/io/file_factory.cpp
  be/src/io/file_factory.h
  be/src/io/fs/benchmark/hdfs_benchmark.hpp
  be/src/io/fs/benchmark/s3_benchmark.hpp
  be/src/io/fs/broker_file_system.cpp
  be/src/io/fs/broker_file_system.h
  be/src/io/fs/buffered_reader.cpp
  be/src/io/fs/buffered_reader.h
  be/src/io/fs/file_reader_options.h
  be/src/io/fs/file_system.cpp
  be/src/io/fs/file_system.h
  be/src/io/fs/fs_utils.cpp
  be/src/io/fs/fs_utils.h
  be/src/io/fs/hdfs_file_reader.cpp
  be/src/io/fs/hdfs_file_reader.h
  be/src/io/fs/hdfs_file_system.cpp
  be/src/io/fs/hdfs_file_system.h
  be/src/io/fs/local_file_system.cpp
  be/src/io/fs/local_file_system.h
  be/src/io/fs/remote_file_system.cpp
  be/src/io/fs/remote_file_system.h
  be/src/io/fs/s3_file_system.cpp
  be/src/io/fs/s3_file_system.h
  be/src/olap/data_dir.cpp
  be/src/olap/data_dir.h
  be/src/olap/rowset/segment_v2/segment.cpp
  be/src/runtime/snapshot_loader.cpp
  be/src/util/os_util.cpp
  be/src/util/path_util.cpp
  be/src/util/path_util.h
  be/src/vec/core/block_spill_reader.cpp
  be/src/vec/exec/format/csv/csv_reader.cpp
  be/src/vec/exec/format/csv/csv_reader.h
  be/src/vec/exec/format/json/new_json_reader.cpp
  be/src/vec/exec/format/json/new_json_reader.h
  be/src/vec/exec/format/orc/vorc_reader.cpp
  be/src/vec/exec/format/orc/vorc_reader.h
  be/src/vec/exec/format/parquet/vparquet_reader.cpp
  be/src/vec/exec/format/parquet/vparquet_reader.h
  be/src/vec/runtime/vfile_result_writer.cpp
  be/test/olap/primary_key_index_test.cpp
  be/test/olap/tablet_cooldown_test.cpp
Labels: approved, reviewed, dev/2.0.0

#21628 [FIX](serde) fix map/struct/array support arrow
  be/src/util/arrow/row_batch.cpp
  be/src/vec/data_types/serde/data_type_array_serde.cpp
  be/src/vec/data_types/serde/data_type_array_serde.h
  be/src/vec/data_types/serde/data_type_bitmap_serde.h
  be/src/vec/data_types/serde/data_type_date64_serde.cpp
  be/src/vec/data_types/serde/data_type_date64_serde.h
  be/src/vec/data_types/serde/data_type_datetimev2_serde.cpp
  be/src/vec/data_types/serde/data_type_datetimev2_serde.h
  be/src/vec/data_types/serde/data_type_datev2_serde.cpp
  be/src/vec/data_types/serde/data_type_datev2_serde.h
  be/src/vec/data_types/serde/data_type_decimal_serde.cpp
  be/src/vec/data_types/serde/data_type_decimal_serde.h
  be/src/vec/data_types/serde/data_type_fixedlengthobject_serde.h
  be/src/vec/data_types/serde/data_type_hll_serde.cpp
  be/src/vec/data_types/serde/data_type_hll_serde.h
  be/src/vec/data_types/serde/data_type_jsonb_serde.cpp
  be/src/vec/data_types/serde/data_type_jsonb_serde.h
  be/src/vec/data_types/serde/data_type_map_serde.cpp
  be/src/vec/data_types/serde/data_type_map_serde.h
  be/src/vec/data_types/serde/data_type_nullable_serde.cpp
  be/src/vec/data_types/serde/data_type_nullable_serde.h
  be/src/vec/data_types/serde/data_type_number_serde.cpp
  be/src/vec/data_types/serde/data_type_number_serde.h
  be/src/vec/data_types/serde/data_type_object_serde.h
  be/src/vec/data_types/serde/data_type_quantilestate_serde.h
  be/src/vec/data_types/serde/data_type_serde.h
  be/src/vec/data_types/serde/data_type_string_serde.cpp
  be/src/vec/data_types/serde/data_type_string_serde.h
  be/src/vec/data_types/serde/data_type_struct_serde.cpp
  be/src/vec/data_types/serde/data_type_struct_serde.h
  be/test/vec/data_types/serde/data_type_serde_arrow_test.cpp
Labels: approved, reviewed, dev/2.0.0

#21642 [opt](Nereids) enable parallel scan for local phase agg
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/PhysicalPlanTranslator.java
Labels: approved, reviewed, area/nereids, dev/2.0.0

#21640 [refactor](planner) refactor automatically set instance_num
  be/src/agent/task_worker_pool.cpp
  fe/fe-core/src/main/java/org/apache/doris/master/ReportHandler.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/system/Backend.java
  fe/fe-core/src/main/java/org/apache/doris/system/SystemInfoService.java
  gensrc/thrift/MasterService.thrift
Labels: approved, reviewed, dev/2.0.0

#21639 [Fix](storage engine) shutdown cooldown and cold data compaction thread when engine stop
  be/src/olap/storage_engine.cpp
Labels: approved, reviewed, dev/2.0.0

#21633 [opt](regression case) add more index change regression case
  regression-test/data/inverted_index_p0/index_change/test_index_change_1.out
  regression-test/data/inverted_index_p0/index_change/test_index_change_2.out
  regression-test/data/inverted_index_p0/index_change/test_index_change_3.out
  regression-test/data/inverted_index_p0/index_change/test_index_change_4.out
  regression-test/data/inverted_index_p0/index_change/test_index_change_5.out
  regression-test/data/inverted_index_p0/index_change/test_index_change_6.out
  regression-test/suites/inverted_index_p0/index_change/test_index_change_1.groovy
  regression-test/suites/inverted_index_p0/index_change/test_index_change_2.groovy
  regression-test/suites/inverted_index_p0/index_change/test_index_change_3.groovy
  regression-test/suites/inverted_index_p0/index_change/test_index_change_4.groovy
  regression-test/suites/inverted_index_p0/index_change/test_index_change_5.groovy
  regression-test/suites/inverted_index_p0/index_change/test_index_change_6.groovy
Labels: kind/test, approved, reviewed, dev/2.0.0

#21596 [refactor](load) remove FlushContext from SegmentWriter
  be/src/olap/rowset/beta_rowset_writer.cpp
  be/src/olap/rowset/segment_v2/segment_writer.cpp
  be/src/olap/rowset/segment_v2/segment_writer.h
Labels: approved, reviewed

#21632 [pipeline](exec) disable pipeline load in now version
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
Labels: approved, reviewed, dev/2.0-beta, dev/2.0.0

#21627 [docs](docs)add more explanation for Fe config
  docs/en/docs/admin-manual/config/fe-config-template.md
  docs/zh-CN/docs/admin-manual/config/fe-config-template.md
Labels: kind/docs, approved, reviewed

#21544 [Enhancement](binlog) Add create/drop table, add/drop paritition && alter job, modify columns binlog support
  fe/fe-core/src/main/java/org/apache/doris/alter/Alter.java
  fe/fe-core/src/main/java/org/apache/doris/alter/AlterHandler.java
  fe/fe-core/src/main/java/org/apache/doris/alter/AlterJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/alter/MaterializedViewHandler.java
  fe/fe-core/src/main/java/org/apache/doris/alter/RollupJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/alter/SystemHandler.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/AbstractBackupStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/IndexDef.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/RestoreStmt.java
  fe/fe-core/src/main/java/org/apache/doris/binlog/BinlogManager.java
  fe/fe-core/src/main/java/org/apache/doris/binlog/CreateTableRecord.java
  fe/fe-core/src/main/java/org/apache/doris/binlog/DBBinlog.java
  fe/fe-core/src/main/java/org/apache/doris/binlog/DropTableRecord.java
  fe/fe-core/src/main/java/org/apache/doris/binlog/TableBinlog.java
  fe/fe-core/src/main/java/org/apache/doris/persist/EditLog.java
  fe/fe-core/src/main/java/org/apache/doris/persist/TableAddOrDropColumnsInfo.java
  fe/fe-core/src/main/java/org/apache/doris/persist/TableAddOrDropInvertedIndicesInfo.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/org/apache/doris/alter/RollupJobV2Test.java
  fe/fe-core/src/test/java/org/apache/doris/alter/SchemaChangeJobV2Test.java
  fe/fe-core/src/test/java/org/apache/doris/persist/TableAddOrDropColumnsInfoTest.java
  gensrc/thrift/FrontendService.thrift
Labels: area/planner, approved, reviewed, dev/2.0.0

#21600 [fix](tablet report) fix fe can not update replica's status with be's report
  fe/fe-core/src/main/java/org/apache/doris/master/ReportHandler.java
Labels: approved, reviewed, dev/2.0.0

#21636 [fix](sink) fix pipeline load stuck
  be/src/vec/sink/vtablet_sink.cpp
Labels: approved, reviewed, dev/2.0.0-merged

#21587 [Improve](point query) audit point query
  fe/fe-core/src/main/java/org/apache/doris/analysis/ExecuteStmt.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/PrepareStmtContext.java
Labels: area/planner, approved, reviewed
