Repository apache/doris, pull requests merged in 2024-11, with the labels that each got.

#42145 [opt][file cache] Do not return error if file cache can not be created if ignore_broken_disk is set
  be/src/runtime/exec_env_init.cpp
Labels: approved, reviewed

#43002 [refactor](metrics) Complete metrics for operators
  be/src/pipeline/exec/result_sink_operator.cpp
  be/src/pipeline/exec/result_sink_operator.h
  be/src/pipeline/exec/set_probe_sink_operator.cpp
  be/src/pipeline/exec/set_probe_sink_operator.h
  be/src/pipeline/exec/set_sink_operator.cpp
  be/src/pipeline/exec/set_sink_operator.h
  be/src/pipeline/exec/set_source_operator.cpp
  be/src/pipeline/exec/set_source_operator.h
  be/src/pipeline/exec/sort_sink_operator.cpp
  be/src/pipeline/exec/sort_sink_operator.h
  be/src/pipeline/exec/table_function_operator.cpp
  be/src/pipeline/exec/table_function_operator.h
  be/src/pipeline/exec/union_sink_operator.cpp
  be/src/pipeline/exec/union_sink_operator.h
Labels: approved, reviewed, dev/3.0.x

#42574 [env](compile)open compile check in sink file
  be/src/util/mysql_row_buffer.cpp
  be/src/util/mysql_row_buffer.h
  be/src/vec/sink/autoinc_buffer.cpp
  be/src/vec/sink/autoinc_buffer.h
  be/src/vec/sink/delta_writer_v2_pool.cpp
  be/src/vec/sink/delta_writer_v2_pool.h
  be/src/vec/sink/load_stream_map_pool.cpp
  be/src/vec/sink/load_stream_map_pool.h
  be/src/vec/sink/load_stream_stub.cpp
  be/src/vec/sink/load_stream_stub.h
  be/src/vec/sink/varrow_flight_result_writer.cpp
  be/src/vec/sink/varrow_flight_result_writer.h
  be/src/vec/sink/vdata_stream_sender.cpp
  be/src/vec/sink/vdata_stream_sender.h
  be/src/vec/sink/vmysql_result_writer.cpp
  be/src/vec/sink/vmysql_result_writer.h
  be/src/vec/sink/vrow_distribution.cpp
  be/src/vec/sink/vrow_distribution.h
  be/src/vec/sink/vtablet_block_convertor.cpp
  be/src/vec/sink/vtablet_block_convertor.h
  be/src/vec/sink/vtablet_finder.cpp
  be/src/vec/sink/vtablet_finder.h
  be/test/io/fs/stream_sink_file_writer_test.cpp
Labels: approved, reviewed

#42882 [fix](build index)Fix build index failed on renamed column
  be/src/olap/tablet_schema.cpp
  be/src/olap/task/index_builder.cpp
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/BuildIndexClause.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateIndexClause.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateTableStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/IndexDef.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Index.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/MaterializedIndexMeta.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/IndexDefinition.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/OlapTableTest.java
  fe/fe-core/src/test/java/org/apache/doris/common/proc/IndexesProcNodeTest.java
  fe/fe-core/src/test/java/org/apache/doris/persist/TableAddOrDropColumnsInfoTest.java
  gensrc/thrift/Descriptors.thrift
  regression-test/suites/inverted_index_p0/index_change/test_index_change_on_renamed_column.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#43019 [deps](hadoop) update hadoop to 3.3.6.4
  thirdparty/CHANGELOG.md
  thirdparty/vars.sh
Labels: approved, reviewed

#42855 [test](stats)Add upgrade and downgrade test for analyze
  regression-test/suites/stats_up_down/load.groovy
  regression-test/suites/stats_up_down/test_upgrade_downgrade_stats.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#43010 [test](mv) Insert into more data when first insert into to make sure using sync mv
  regression-test/data/mv_p0/ssb/q_1_1/q_1_1.out
  regression-test/suites/mv_p0/ssb/q_1_1/q_1_1.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#42856 [Opt](Variant) merge schema in sync_rowsets to prevents from CPU overhead each time describe table
  be/src/cloud/cloud_tablet.cpp
  be/src/cloud/cloud_tablet.h
  be/src/service/internal_service.cpp
Labels: approved, reviewed, dev/3.0.x

#42990 [fix](Nereids) simplify range result wrong when reference is nullable (#41356)
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/FoldConstantRuleOnFE.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/SimplifyRange.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/ExpressionUtils.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/expression/SimplifyRangeTest.java
Labels: area/nereids

#43045 [update](collaborators) add LiBinfeng-01 to collaborator list
  .asf.yaml
Labels: approved, reviewed

#42647 [fix](auditlog) set isQuery to true when query is short circuited
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#42997 [Enhancement](log) Make log of vlog adjustment clear
  be/src/http/action/adjust_log_level.cpp
Labels: approved, reviewed, dev/3.0.x

#42918 [fix](Outfile) It doesn't specify String logical type when it coms to export data to parquet file format.
  fe/fe-core/src/main/java/org/apache/doris/analysis/OutFileClause.java
Labels: area/planner, approved, reviewed, dev/2.0.x

#42906 [fix](hive)fix hive catalog miss partition that have special characters.
  fe/fe-core/src/main/java/org/apache/doris/datasource/TablePartitionValues.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HiveMetaStoreCache.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HiveUtil.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/HMSAnalysisTask.java
  regression-test/data/external_table_p0/hive/test_hive_special_char_partition.out
  regression-test/suites/external_table_p0/hive/test_hive_special_char_partition.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#43005 [Chore](hash-table) remove has_nullable_keys template argument of MethodKeysFixed
  be/src/pipeline/common/agg_utils.h
  be/src/pipeline/common/distinct_agg_utils.h
  be/src/pipeline/common/join_utils.h
  be/src/pipeline/common/partition_sort_utils.h
  be/src/pipeline/common/set_utils.h
  be/src/pipeline/exec/join/process_hash_table_probe_impl.h
  be/src/vec/common/columns_hashing.h
  be/src/vec/common/columns_hashing_impl.h
  be/src/vec/common/hash_table/hash_map_context.h
  be/src/vec/common/hash_table/hash_map_util.h
Labels: approved, reviewed

#43051 [fix](export) fix concurrent modification issue with export job
  fe/fe-core/src/main/java/org/apache/doris/load/ExportMgr.java
Labels: approved, reviewed, p0_b, dev/3.0.x, dev/2.1.7-merged

#41759 [fix](cloud-mow) FE should release mow lock when calculate delete bitmap catch exception
  be/src/cloud/cloud_meta_mgr.cpp
  be/src/cloud/cloud_meta_mgr.h
  cloud/src/common/bvars.cpp
  cloud/src/common/bvars.h
  cloud/src/meta-service/meta_service.cpp
  cloud/src/meta-service/meta_service.h
  fe/fe-core/src/main/java/org/apache/doris/cloud/rpc/MetaServiceClient.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/rpc/MetaServiceProxy.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/transaction/CloudGlobalTransactionMgr.java
  gensrc/proto/cloud.proto
  regression-test/data/fault_injection_p0/cloud/test_cloud_mow_stream_load_with_timeout.out
  regression-test/suites/fault_injection_p0/cloud/test_cloud_mow_broker_load_with_retry.groovy
  regression-test/suites/fault_injection_p0/cloud/test_cloud_mow_stream_load_with_timeout.groovy
Labels: approved, reviewed, dev/3.0.x

#42941 [enhancement](Nereids) boost characterLiteralTypeCoercion
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/SearchSignature.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/DateLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/DateTimeLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/DateTimeV2Literal.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/DecimalV3Literal.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/Result.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/format/AndChecker.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/format/AtLeastChecker.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/format/CharChecker.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/format/CheckResult.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/format/CustomCharChecker.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/format/DateTimeChecker.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/format/DebugChecker.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/format/DigitChecker.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/format/FloatChecker.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/format/FormatChecker.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/format/IntegerChecker.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/format/LetterChecker.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/format/OptionChecker.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/format/OrChecker.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/format/StringChecker.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/format/StringInspect.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/types/DecimalV3Type.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/TypeCoercionUtils.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/expressions/literal/DateLiteralTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/expressions/literal/DateTimeLiteralTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/expressions/literal/FloatLiteralTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/expressions/literal/IntegerLiteralTest.java
Labels: approved, reviewed, p0_b, dev/2.1.x, dev/3.0.x, cir

#43040 [feature](doris compose) run docker as host user
  docker/runtime/doris-compose/Dockerfile
  docker/runtime/doris-compose/cluster.py
  docker/runtime/doris-compose/command.py
  docker/runtime/doris-compose/resource/entrypoint.sh
Labels: approved, reviewed, dev/3.0.x

#41482 [cloud](Variant) limit column size in MetaService and support handle rowset schema in backend side
  be/src/cloud/cloud_meta_mgr.cpp
  be/src/cloud/pb_convert.cpp
  be/src/cloud/pb_convert.h
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/olap/rowset/segment_v2/vertical_segment_writer.cpp
  cloud/src/common/config.h
  cloud/src/meta-service/meta_service.cpp
  cloud/src/meta-service/meta_service_schema.cpp
  cloud/src/meta-service/meta_service_schema.h
  gensrc/proto/cloud.proto
  regression-test/suites/variant_p0/column_size_limit.groovy
Labels: approved, reviewed, usercase, dev/3.0.x

#42929 [Refactor](pipeline) Remove some unused code in pipeline query engine
  be/src/pipeline/dependency.cpp
  be/src/pipeline/dependency.h
  be/src/pipeline/pipeline.h
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/pipeline/task_scheduler.h
  be/src/runtime/exec_env_init.cpp
  be/src/runtime/workload_group/workload_group.cpp
Labels: approved, reviewed

#42886 [fix](regression-test) fix test_hive_serde_prop
  regression-test/data/external_table_p0/hive/test_hive_serde_prop.out
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#43075 [fix](Nereids) replay create function npe since connect context not exists
  fe/fe-core/src/main/java/org/apache/doris/qe/SqlModeHelper.java
Labels: p0_b, dev/2.1.x

#43084 [fix](Export) fix dead lock of parallel Exporting
  fe/fe-core/src/main/java/org/apache/doris/load/ExportJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/ExportJobStateTransfer.java
  fe/fe-core/src/main/java/org/apache/doris/persist/EditLog.java
Labels: approved, reviewed

#43106 [chore](auto-pick)Support cherry pick to 2.1
  .github/workflows/auto-cherry-pick.yml
Labels: approved, reviewed, dev/2.1.x

#43085 [feature](doris compose) enable fe jvm debug port
  docker/runtime/doris-compose/cluster.py
  docker/runtime/doris-compose/command.py
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#42865 [fix](cloud) Fix constant folding for requests sent to BE without dis…
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/FoldConstantRuleOnBE.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/FoldConstantsRule.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/org/apache/doris/system/SystemInfoService.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/LocalTableValuedFunction.java
Labels: approved, reviewed, dev/3.0.x

#43016 [test](stream load) add cases to ensure the correctness of the document
  regression-test/data/doc/data-operate/import/import-way/stream-load-manual.md.out
  regression-test/data/doc/data-operate/import/import-way/streamload_example.csv
  regression-test/data/doc/data-operate/import/import-way/streamload_example.json
  regression-test/data/doc/data-operate/import/import-way/test_array.csv
  regression-test/data/doc/data-operate/import/import-way/test_bitmap.csv
  regression-test/data/doc/data-operate/import/import-way/test_default.csv
  regression-test/data/doc/data-operate/import/import-way/test_enclose_and_escape.csv
  regression-test/data/doc/data-operate/import/import-way/test_hll.csv
  regression-test/data/doc/data-operate/import/import-way/test_map.json
  regression-test/data/doc/data-operate/import/import-way/test_merge_type.csv
  regression-test/data/doc/data-operate/import/import-way/test_seq.csv
  regression-test/suites/doc/data-operate/import/import-way/stream-load-manual.md.groovy
Labels: approved, reviewed, dev/3.0.x

#43066 [fix](case) fix mow cluster key case
  regression-test/data/unique_with_mow_c_p0/partial_update/test_new_partial_update_delete.out
  regression-test/suites/unique_with_mow_c_p0/partial_update/test_new_partial_update_delete.groovy
  regression-test/suites/unique_with_mow_c_p0/partial_update/test_partial_update_delete.groovy
Labels: approved, reviewed

#43109 [fix](export) fix potential export concurrency issue
  fe/fe-core/src/main/java/org/apache/doris/analysis/ExportStmt.java
  fe/fe-core/src/main/java/org/apache/doris/load/ExportJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/ExportMgr.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ExportCommand.java
Labels: approved, reviewed, p0_b, dev/2.1.x, dev/3.0.x

#43079 [fix](persist) Fix the generated dropping tmp partition sql
  fe/fe-core/src/main/java/org/apache/doris/persist/DropPartitionInfo.java
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x

#43097 [fix](Export) fix dead lock of parallel Exporting
  fe/fe-core/src/main/java/org/apache/doris/load/ExportJob.java
  fe/fe-core/src/main/java/org/apache/doris/persist/EditLog.java
Labels: area/load

#43083 [fix](Export) fix dead lock of parallel Exporting
  fe/fe-core/src/main/java/org/apache/doris/load/ExportJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/ExportJobStateTransfer.java
  fe/fe-core/src/main/java/org/apache/doris/persist/EditLog.java
Labels: approved, reviewed, p0_b, dev/3.0.x, dev/2.1.7-merged, dev/2.0.16-merged

#42585 [Fix](PaimonCatalog) fix the problem that paimon catalog can not access to OSS-HDFS
  fe/fe-core/src/main/java/org/apache/doris/common/util/LocationPath.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/paimon/PaimonFileExternalCatalog.java
  fe/fe-core/src/test/java/org/apache/doris/common/util/LocationPathTest.java
Labels: approved, reviewed, usercase, p0_b, dev/2.1.x, dev/3.0.x

#43049 [bugfix](hive)fix after insert overwrite hive table, data error
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HMSTransaction.java
  fe/fe-core/src/main/java/org/apache/doris/fs/remote/RemoteFSPhantomManager.java
  fe/fe-core/src/main/java/org/apache/doris/fs/remote/S3FileSystem.java
  fe/fe-core/src/main/java/org/apache/doris/fs/remote/dfs/DFSFileSystem.java
  fe/fe-core/src/main/java/org/apache/doris/planner/HiveTableSink.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#42262 [fix](auditlog) add missing audit log fields and duplicate audit log error
  fe/fe-core/src/main/java/org/apache/doris/catalog/InternalSchema.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/CallCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/call/CallFlushAuditLogFunc.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/call/CallFunc.java
  fe/fe-core/src/main/java/org/apache/doris/plugin/AuditEvent.java
  fe/fe-core/src/main/java/org/apache/doris/plugin/PluginMgr.java
  fe/fe-core/src/main/java/org/apache/doris/plugin/audit/AuditLoader.java
  fe/fe-core/src/main/java/org/apache/doris/plugin/audit/AuditLogBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/qe/AuditLogHelper.java
  regression-test/data/audit/test_audit_log_behavior.out
  regression-test/suites/audit/test_audit_log_behavior.groovy
Labels: approved, reviewed, kind/behavior-changed, dev/2.0.x, dev/3.0.x, dev/2.1.7-merged

#43130 [chore](auto-pick)Optimize the cherry-pick script
  .github/workflows/auto-cherry-pick.yml
  tools/auto-pick-script.py
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#42908 [fix](regression) fix flaky partial update cases
  regression-test/suites/unique_with_mow_p0/partial_update/test_mix_partial_update.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#42674 [feature](statistics)Support get row count for pg and sql server.
  docker/thirdparties/docker-compose/mysql/init/04-insert.sql
  docker/thirdparties/docker-compose/postgresql/init/04-insert.sql
  docker/thirdparties/docker-compose/sqlserver/init/04-insert.sql
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/JdbcExternalTable.java
  regression-test/suites/external_table_p0/jdbc/test_jdbc_row_count.groovy
  regression-test/suites/external_table_p0/jdbc/test_mysql_jdbc_statistics.groovy
Labels: approved, reviewed, dev/3.0.x

#38946 [improvement](external)add some improvements for external scan
  fe/be-java-extensions/paimon-scanner/src/main/java/org/apache/doris/paimon/PaimonJniScanner.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/FederationBackendPolicy.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/FileSplit.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/source/IcebergDeleteFileFilter.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/source/IcebergScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/source/IcebergSplit.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/paimon/source/PaimonScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/paimon/source/PaimonSplit.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/PhysicalPlanTranslator.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/spi/Split.java
  fe/fe-core/src/test/java/org/apache/doris/planner/FederationBackendPolicyTest.java
Labels: approved, reviewed, dev/2.1.x, doing

#43046 [fix] (inverted index) fix index compaction
  be/src/olap/compaction.cpp
  regression-test/suites/inverted_index_p0/index_compaction/test_index_compaction_empty_segments.groovy
Labels: approved, reviewed

#43072 [Chore](pipeline) Retire some pipeline relative properities
  be/src/exprs/runtime_filter.cpp
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/query_context.cpp
  be/src/runtime/query_context.h
  be/src/runtime/runtime_filter_mgr.cpp
  gensrc/proto/internal_service.proto
Labels: approved, reviewed

#43166 [Fix](auto-pick)Allow doris-robot to trigger the workflow
  .github/workflows/build-extension.yml
  .github/workflows/build-thirdparty.yml
  .github/workflows/checkstyle.yaml
  .github/workflows/clang-format.yml
  .github/workflows/license-eyes.yml
Labels: approved, reviewed

#43162 [fix](case) Delete invalid row
  regression-test/suites/nereids_syntax_p0/distribute/local_shuffle.groovy
Labels: approved, reviewed

#43063 [fix](compatibility) Fix correctness problem during upgrading
  be/src/pipeline/exec/operator.h
  be/src/pipeline/pipeline_fragment_context.cpp
Labels: approved, reviewed, dev/3.0.x

#41290 [fix](new_json_reader)fix new_json_reader core
  be/src/vec/exec/format/json/new_json_reader.cpp
  regression-test/suites/jsonb_p0/test_json_reader_without_object.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x

#42693 [compile](exec) open compile check in date floor/ceil function
  be/src/vec/functions/function_datetime_floor_ceil.cpp
Labels: reviewed

#40682 [opt](agg function) Signature verification of aggregate function.
  be/src/pipeline/exec/aggregation_sink_operator.cpp
  be/src/pipeline/exec/analytic_source_operator.cpp
  be/src/pipeline/exec/distinct_streaming_aggregation_operator.cpp
  be/src/pipeline/exec/streaming_aggregation_operator.cpp
  be/src/vec/aggregate_functions/aggregate_function.h
  be/src/vec/exprs/vectorized_agg_fn.cpp
  be/src/vec/exprs/vectorized_agg_fn.h
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#42419 [fix](auth)Fix concurrency issue during role manager upgrade
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/RoleManager.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#43078 [Bug](runtime-filter) avoid wrong partitial ignore minmax filter
  be/src/exprs/runtime_filter_slots.h
Labels: approved, reviewed, dev/3.0.x

#43153 [Bug](set) fix wrong result on single nullable set operators
  be/src/pipeline/common/set_utils.h
  regression-test/data/nereids_rules_p0/infer_predicate/pull_up_predicate_set_op.out
  regression-test/suites/nereids_rules_p0/infer_predicate/pull_up_predicate_set_op.groovy
Labels: approved, reviewed

#42697 [Opt](ShortCircuit) add more stats info to trace
  be/src/olap/base_tablet.cpp
  be/src/olap/base_tablet.h
  be/src/olap/primary_key_index.cpp
  be/src/olap/primary_key_index.h
  be/src/olap/rowset/segment_v2/bloom_filter_index_reader.cpp
  be/src/olap/rowset/segment_v2/bloom_filter_index_reader.h
  be/src/olap/rowset/segment_v2/indexed_column_reader.cpp
  be/src/olap/rowset/segment_v2/indexed_column_reader.h
  be/src/olap/rowset/segment_v2/segment.cpp
  be/src/olap/rowset/segment_v2/segment.h
  be/src/olap/segment_loader.cpp
  be/src/olap/segment_loader.h
  be/src/service/internal_service.cpp
  be/src/service/point_query_executor.cpp
  be/src/service/point_query_executor.h
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#42451 [enhancement](cloud) refine block file cache evict policy
  be/src/common/config.cpp
  be/src/io/cache/block_file_cache.cpp
  be/src/io/cache/block_file_cache.h
  be/src/io/cache/file_cache_common.cpp
  be/src/io/cache/file_cache_common.h
  be/test/io/cache/block_file_cache_test.cpp
Labels: approved, reviewed, kind/behavior-changed, p0_c, dev/3.0.x

#43197 [fix](backup) Fix compressed backup job
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupJob.java
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x

#43073 [env](compile) add check of compile_check_begin.h and compile_check_end.h
  be/src/common/compile_check_begin.h
  be/src/common/compile_check_end.h
Labels: approved, reviewed

#43114 [Fix](segment compaction) fix error using of inverted index file writer in segment compaction
  be/src/olap/rowset/beta_rowset_writer.cpp
  be/src/olap/rowset/beta_rowset_writer.h
  be/src/olap/rowset/segcompaction.cpp
  be/src/olap/rowset/segcompaction.h
  be/test/olap/segcompaction_test.cpp
Labels: approved, reviewed

#43203 [Test](index compaction) refine index compaction case
  regression-test/data/inverted_index_p0/index_compaction/documents-1.json
  regression-test/data/inverted_index_p0/index_compaction/documents-10.json
  regression-test/data/inverted_index_p0/index_compaction/documents-11.json
  regression-test/data/inverted_index_p0/index_compaction/documents-12.json
  regression-test/data/inverted_index_p0/index_compaction/documents-13.json
  regression-test/data/inverted_index_p0/index_compaction/documents-14.json
  regression-test/data/inverted_index_p0/index_compaction/documents-15.json
  regression-test/data/inverted_index_p0/index_compaction/documents-16.json
  regression-test/data/inverted_index_p0/index_compaction/documents-17.json
  regression-test/data/inverted_index_p0/index_compaction/documents-18.json
  regression-test/data/inverted_index_p0/index_compaction/documents-19.json
  regression-test/data/inverted_index_p0/index_compaction/documents-2.json
  regression-test/data/inverted_index_p0/index_compaction/documents-20.json
  regression-test/data/inverted_index_p0/index_compaction/documents-3.json
  regression-test/data/inverted_index_p0/index_compaction/documents-4.json
  regression-test/data/inverted_index_p0/index_compaction/documents-5.json
  regression-test/data/inverted_index_p0/index_compaction/documents-6.json
  regression-test/data/inverted_index_p0/index_compaction/documents-7.json
  regression-test/data/inverted_index_p0/index_compaction/documents-8.json
  regression-test/data/inverted_index_p0/index_compaction/documents-9.json
  regression-test/suites/inverted_index_p0/index_compaction/test_index_compaction_p0.groovy
Labels: approved, reviewed

#43000 [feat](nereids)disable join reorder if any table row count is not available
  fe/fe-core/src/main/java/org/apache/doris/nereids/NereidsPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/StatsCalculator.java
Labels: approved, reviewed

#43103 [Feat](Nereids) support unset command
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PlanType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/UnsetDefaultStorageVaultCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/UnsetVariableCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/CommandVisitor.java
  regression-test/data/nereids_p0/ddl/set_and_unset_commands/set_and_unset_variable_command.out
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
  regression-test/suites/nereids_p0/ddl/set_and_unset_commands/set_and_unset_variable_command.groovy
Labels: approved, reviewed

#43216 [fix](test) fix some test cases #43217
  regression-test/data/audit/test_audit_log_behavior.out
  regression-test/data/external_table_p0/jdbc/test_mysql_jdbc_catalog.out
  regression-test/suites/audit/test_audit_log_behavior.groovy
  regression-test/suites/external_table_p0/jdbc/test_mysql_jdbc_catalog.groovy
Labels: approved, reviewed

#43077 [fix](regression case) Fix `test_dynamic_partition_with_update` regre…
  regression-test/suites/partition_p1/dynamic_partition/test_dynamic_partition.groovy
Labels: approved, reviewed, dev/3.0.x

#42066 [Feature](cloud) Add cloud report for clean up expired tablets
  be/src/agent/agent_server.cpp
  be/src/agent/heartbeat_server.cpp
  be/src/agent/task_worker_pool.cpp
  be/src/agent/task_worker_pool.h
  be/src/cloud/cloud_tablet.cpp
  be/src/cloud/cloud_tablet.h
  be/src/cloud/cloud_tablet_mgr.cpp
  be/src/cloud/cloud_tablet_mgr.h
  be/src/cloud/config.cpp
  be/src/cloud/config.h
  be/src/http/action/tablets_info_action.cpp
  be/src/olap/base_tablet.h
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
  be/src/service/http_service.cpp
  fe/fe-core/src/main/java/org/apache/doris/cloud/CacheHotspotManager.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/catalog/CloudTabletRebalancer.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/master/CloudReportHandler.java
  fe/fe-core/src/main/java/org/apache/doris/master/MasterImpl.java
  fe/fe-core/src/main/java/org/apache/doris/master/ReportHandler.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/system/HeartbeatMgr.java
  fe/fe-core/src/test/java/org/apache/doris/clone/RepairVersionTest.java
  gensrc/thrift/HeartbeatService.thrift
  gensrc/thrift/MasterService.thrift
  regression-test/suites/cloud_p0/tablets/test_clean_tablet_when_drop_force_table.groovy
  regression-test/suites/cloud_p0/tablets/test_clean_tablet_when_rebalance.groovy
Labels: approved, reviewed, dev/3.0.x

#42283 [test](ES Catalog)Add mapping _routing test case (#42074)
  docker/thirdparties/docker-compose/elasticsearch/scripts/es_init.sh
  docker/thirdparties/docker-compose/elasticsearch/scripts/index/es6_test3.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/index/es7_test3.json
  regression-test/data/external_table_p0/es/test_es_query.out
  regression-test/suites/external_table_p0/es/test_es_query.groovy
Labels: kind/test

#43215 [Chore](hash-table) remove some unused code of PartitionedHashMap
  be/src/vec/common/hash_table/hash_map.h
  be/src/vec/common/hash_table/hash_map_context.h
  be/src/vec/common/hash_table/hash_table.h
  be/src/vec/common/hash_table/partitioned_hash_map.h
  be/src/vec/common/hash_table/partitioned_hash_table.h
  be/src/vec/common/hash_table/ph_hash_map.h
Labels: approved, reviewed

#43204 [Optimize](Expr) Opt getting value of VLitreal
  be/src/vec/exprs/vliteral.cpp
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#42900 [Enhancement](log) Make query relative BE log more reasonable
  be/src/pipeline/exec/result_sink_operator.cpp
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/query_context.cpp
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#43065 [fix](ip) fix datatype serde for ipv6 with rowstore
  be/src/vec/data_types/serde/data_type_ipv6_serde.cpp
  be/test/vec/data_types/serde/data_type_serde_test.cpp
  regression-test/data/datatype_p0/ip/test_ip_basic.out
  regression-test/suites/datatype_p0/ip/test_ip_basic.groovy
Labels: approved, reviewed, p0_c, dev/2.1.x, dev/3.0.x

#43219 [Test](segcompaction) refine segment compaction inverted index ut case
  be/test/olap/segcompaction_test.cpp
Labels: approved, reviewed

#43177 [improve](backup) Only compress the running backup/restore job
  fe/fe-core/src/main/java/org/apache/doris/backup/AbstractJob.java
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x

#43172 [fix](restore) Add synchronized to avoid concurrent modification
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupJob.java
  fe/fe-core/src/main/java/org/apache/doris/backup/RestoreJob.java
  regression-test/suites/backup_restore/test_backup_restore_atomic_with_alter.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x

#43196 [fix](test) fix clickhouse jdbc catalog func push down case
  docker/thirdparties/docker-compose/clickhouse/init/03-create-table.sql
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#43003 [Refactor](inverted index) refactor inverted index interface in tablet schema
  be/src/cloud/cloud_meta_mgr.cpp
  be/src/cloud/cloud_tablet.cpp
  be/src/cloud/cloud_warm_up_manager.cpp
  be/src/olap/compaction.cpp
  be/src/olap/delta_writer.cpp
  be/src/olap/rowset/beta_rowset.cpp
  be/src/olap/rowset/beta_rowset_writer.cpp
  be/src/olap/rowset/segcompaction.cpp
  be/src/olap/rowset/segment_v2/column_writer.h
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/olap/rowset/segment_v2/segment_writer.cpp
  be/src/olap/rowset/segment_v2/vertical_segment_writer.cpp
  be/src/olap/schema_change.cpp
  be/src/olap/snapshot_manager.cpp
  be/src/olap/tablet.cpp
  be/src/olap/tablet_schema.cpp
  be/src/olap/tablet_schema.h
  be/src/olap/task/engine_storage_migration_task.cpp
  be/src/olap/task/index_builder.cpp
  be/src/service/backend_service.cpp
  be/src/vec/common/schema_util.cpp
  be/src/vec/common/schema_util.h
  be/test/olap/rowset/segment_v2/inverted_index/compaction/index_compaction_test.cpp
  be/test/olap/tablet_index_test.cpp
Labels: approved, reviewed

#43180 [enhancement][docker]update kafka docker file for branch-2.0"
  docker/thirdparties/run-thirdparties-docker.sh
  regression-test/framework/pom.xml
  regression-test/suites/load_p0/routine_load/data/basic_array_data.csv
  regression-test/suites/load_p0/routine_load/data/basic_array_data_json.json
  regression-test/suites/load_p0/routine_load/data/basic_array_data_json_by_line.json
  regression-test/suites/load_p0/routine_load/data/basic_array_data_timezone.csv
  regression-test/suites/load_p0/routine_load/data/basic_array_data_with_errors.csv
  regression-test/suites/load_p0/routine_load/data/basic_data.csv
  regression-test/suites/load_p0/routine_load/data/basic_data_json.json
  regression-test/suites/load_p0/routine_load/data/basic_data_json_by_line.json
  regression-test/suites/load_p0/routine_load/data/basic_data_timezone.csv
  regression-test/suites/load_p0/routine_load/data/basic_data_with_errors.csv
  regression-test/suites/load_p0/routine_load/data/invalid_json_path.json
  regression-test/suites/load_p0/routine_load/data/multi_table_csv.csv
  regression-test/suites/load_p0/routine_load/data/multi_table_csv1.csv
  regression-test/suites/load_p0/routine_load/data/multi_table_json.json
  regression-test/suites/load_p0/routine_load/data/multi_table_json1.json
  regression-test/suites/load_p0/routine_load/data/multi_table_load_invalid_table.csv
  regression-test/suites/load_p0/routine_load/data/test_enclose_and_escape0.csv
  regression-test/suites/load_p0/routine_load/data/test_enclose_and_escape1.csv
  regression-test/suites/load_p0/routine_load/data/test_offset_time.csv
  regression-test/suites/load_p0/routine_load/data/test_out_of_range.csv
  regression-test/suites/load_p0/routine_load/data/test_routine_load_with_sc.csv
  regression-test/suites/load_p0/routine_load/data/test_schedule.csv
  regression-test/suites/load_p0/routine_load/data/test_show_routine_load.csv
  regression-test/suites/load_p0/routine_load/data/test_topic_after.csv
  regression-test/suites/load_p0/routine_load/data/test_topic_before.csv
  regression-test/suites/load_p0/routine_load/data/test_where_condition.csv
  regression-test/suites/load_p0/routine_load/test_routine_load.groovy
Labels: kind/test, approved, reviewed

#43246 [fix] (build index) fix build index coredump
  be/src/olap/task/index_builder.cpp
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#43245 [feat](nereids)disable join reorder if any table row count is not available #43000 (branch-2.0）
  fe/fe-core/src/main/java/org/apache/doris/nereids/NereidsPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/StatsCalculator.java
Labels: area/nereids

#43123 [test](doc) add some import-example in doris's doc to regression test
  regression-test/data/doc/data-operate/import/import-way/insert-into-manual.md.out
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
  regression-test/suites/doc/data-operate/import/import-way/client_local.csv
  regression-test/suites/doc/data-operate/import/import-way/data.csv
  regression-test/suites/doc/data-operate/import/import-way/group-commit-manual.md.groovy
  regression-test/suites/doc/data-operate/import/import-way/insert-into-manual.md.groovy
  regression-test/suites/doc/data-operate/import/import-way/mysql-load-manual.md.groovy
Labels: approved, reviewed

#43280 [fix] (UT) fix BE UT
  be/test/olap/rowset/segment_v2/inverted_index/compaction/index_compaction_with_deleted_term.cpp
Labels: approved, reviewed

#43277 [fix](restore) Add synchronized to avoid concurrent modification #43172
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupJob.java
  fe/fe-core/src/main/java/org/apache/doris/backup/RestoreJob.java
  regression-test/suites/backup_restore/test_backup_restore_atomic_with_alter.groovy
Labels: kind/test

#43239 [chore](agent) log the binary message size of agent tasks
  fe/fe-common/src/main/java/org/apache/doris/common/ThriftUtils.java
  fe/fe-core/src/main/java/org/apache/doris/task/AgentBatchTask.java
Labels: approved, reviewed

#42038 [Improvement](LDAP Auth)Enhance LDAP authentication with a configurable group filter
  conf/ldap.conf
  fe/fe-common/src/main/java/org/apache/doris/common/LdapConfig.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/authenticate/ldap/LdapClient.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#43276 [fix](backup) Load backup meta and job info bytes from disk
  fe/fe-core/src/main/java/org/apache/doris/backup/AbstractJob.java
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupHandler.java
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupJob.java
  fe/fe-core/src/main/java/org/apache/doris/backup/RestoreJob.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x

#43288 [fix](regression) test_primary_key_partial_update fail due to the U.S. change from DST to standard time
  regression-test/data/unique_with_mow_c_p0/partial_update/test_partial_update.out
  regression-test/data/unique_with_mow_p0/partial_update/test_partial_update.out
  regression-test/suites/unique_with_mow_c_p0/partial_update/test_partial_update.groovy
  regression-test/suites/unique_with_mow_p0/partial_update/test_partial_update.groovy
Labels: approved, reviewed

#43257 [improve](report) split agent batch tasks automaticlly
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/master/ReportHandler.java
Labels: approved, reviewed

#43206 [fix](conn-pool) Avoid some invalid connections returned to pool (#41597)
  fe/fe-core/src/main/java/org/apache/doris/cloud/catalog/CloudTabletRebalancer.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/ProfileManager.java
Labels: approved, reviewed

#43184 [enhancement](rowset-meta) Remove rowset meta from olap meta directly…
  be/src/olap/cold_data_compaction.cpp
  be/src/olap/schema_change.cpp
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
  be/src/olap/tablet_meta.cpp
Labels: approved, reviewed

#43261 [fix](cloud-mow) Should clear GetDeleteBitmapResponse when geting delete bitmap fail and retry
  cloud/src/meta-service/meta_service_helper.h
Labels: approved, reviewed, p0_b, dev/3.0.x

#43090 [Fix](flexible partial update) Don't set default value for `TOlapTableIndexSchema.unique_key_update_mode`
  gensrc/thrift/Descriptors.thrift
Labels: approved, reviewed

#43228 [fix](complex-column)fix column bitmap with agg behavior
  be/src/vec/columns/column_complex.h
  regression-test/suites/query_p0/sql_functions/aggregate_functions/test_aggregate_all_functions2.groovy
Labels: kind/test, approved, reviewed

#43199 [Improvement](shuffle) Use a knob to decide whether a serial exchange should be used
  fe/fe-core/src/main/java/org/apache/doris/planner/ExchangeNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PlanFragment.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PlanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/ScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
Labels: approved, reviewed, dev/3.0.x

#43287 [Test](inverted index) add test data for inverted index p2 case
  regression-test/data/inverted_index_p2/documents-1000.json
Labels: approved, reviewed

#43250 [fix](export) make sure the export task being executed after writing "create export job" edit log
  fe/fe-core/src/main/java/org/apache/doris/load/ExportJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/ExportMgr.java
Labels: approved, reviewed, p0_b, dev/3.0.x, dev/2.1.7-merged

#43275 [fix](auth)Fix after fe restarting, external permissions are lost
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/Auth.java
  regression-test/suites/auth_up_down_hive_p0/load.groovy
  regression-test/suites/auth_up_down_hive_p0/test_up_down_hive_auth.groovy
Labels: approved, reviewed, usercase, p0_b, dev/2.0.x, dev/2.1.x, dev/3.0.x

#41674 [improvement](mtmv) Support rewrite by materialized view when join has other join conjuncts
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/joinorder/hypergraph/edge/Edge.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/HyperGraphComparator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/StructInfo.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/mapping/RelationMapping.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/exploration/mv/MappingTest.java
  regression-test/data/nereids_rules_p0/mv/other_join_conjuncts/anti/other_join_conjuncts_anti.out
  regression-test/data/nereids_rules_p0/mv/other_join_conjuncts/inner/other_join_conjuncts_inner.out
  regression-test/data/nereids_rules_p0/mv/other_join_conjuncts/outer/other_join_conjuncts_outer.out
  regression-test/data/nereids_rules_p0/mv/other_join_conjuncts/semi/other_join_conjuncts_semi.out
  regression-test/data/nereids_rules_p0/mv/tpch/mv_tpch_test.out
  regression-test/suites/nereids_rules_p0/mv/negative/negative_test.groovy
  regression-test/suites/nereids_rules_p0/mv/other_join_conjuncts/anti/other_join_conjuncts_anti.groovy
  regression-test/suites/nereids_rules_p0/mv/other_join_conjuncts/inner/other_join_conjuncts_inner.groovy
  regression-test/suites/nereids_rules_p0/mv/other_join_conjuncts/outer/other_join_conjuncts_outer.groovy
  regression-test/suites/nereids_rules_p0/mv/other_join_conjuncts/semi/other_join_conjuncts_semi.groovy
  regression-test/suites/nereids_rules_p0/mv/tpch/mv_tpch_test.groovy
  regression-test/suites/nereids_rules_p0/mv/variant/variant_mv.groovy
Labels: approved, reviewed, dev/3.0.x

#43237 [Opt](Serde) optimize serialization to string on variant type
  be/src/vec/columns/column_object.cpp
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#43038 [Improve](auditlog) audit log print real sql in prepared statement
  fe/fe-core/src/main/java/org/apache/doris/plugin/AuditEvent.java
  fe/fe-core/src/main/java/org/apache/doris/qe/AuditLogHelper.java
  fe/fe-core/src/main/java/org/apache/doris/qe/MysqlConnectProcessor.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#43217 [fix](test) fix some test cases
  regression-test/data/external_table_p0/jdbc/test_mysql_jdbc_catalog.out
  regression-test/suites/audit/test_audit_log_behavior.groovy
  regression-test/suites/external_table_p0/jdbc/test_mysql_jdbc_catalog.groovy
Labels: approved, reviewed, dev/3.0.x, dev/2.1.7-merged

#43242 [Exec](pipeline) refactor the task queue code
  be/src/pipeline/pipeline_task.cpp
  be/src/pipeline/pipeline_task.h
  be/src/pipeline/task_queue.cpp
  be/src/pipeline/task_queue.h
  be/src/pipeline/task_scheduler.cpp
  be/src/pipeline/task_scheduler.h
  be/src/runtime/exec_env_init.cpp
  be/src/runtime/workload_group/workload_group.cpp
Labels: approved, reviewed

#42448 [Opt](TabletSchema) reuse TabletColumn info to reduce mem
  be/src/olap/rowset/segment_v2/inverted_index_writer.cpp
  be/src/olap/rowset/segment_v2/inverted_index_writer.h
  be/src/olap/tablet_column_object_pool.cpp
  be/src/olap/tablet_column_object_pool.h
  be/src/olap/tablet_schema.cpp
  be/src/olap/tablet_schema.h
  be/src/olap/tablet_schema_cache.cpp
  be/src/pipeline/query_cache/query_cache.h
  be/src/runtime/exec_env.h
  be/src/runtime/exec_env_init.cpp
  be/src/runtime/memory/cache_policy.h
  be/src/util/block_compression.cpp
  be/test/testutil/run_all_tests.cpp
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#43080 [fix](mtmv)Fix the problem where the job does not exist, which prevents the deletion of MTMV
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVJobManager.java
Labels: approved, reviewed, p0_b, dev/2.1.x, dev/3.0.x

#43086 [enhance](mtmv)MTMV interface optimization
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HMSExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/job/extensions/mtmv/MTMVTask.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVBaseTableIf.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVRelatedTableIf.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#43223 [Opt](exec) change transmit block to rw lock to opt performance
  be/src/io/hdfs_util.cpp
  be/src/vec/runtime/vdata_stream_mgr.cpp
  be/src/vec/runtime/vdata_stream_mgr.h
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#43060 [feat](cloud) S3 storage vault support property `use_path_style`
  be/src/io/fs/s3_file_system.cpp
  be/src/util/s3_util.cpp
  cloud/src/meta-service/meta_service_resource.cpp
  fe/fe-core/src/main/java/org/apache/doris/catalog/S3StorageVault.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/constants/S3Properties.java
  gensrc/proto/cloud.proto
  regression-test/suites/vault_p0/alter/test_alter_use_path_style.groovy
  regression-test/suites/vault_p0/default/test_default_vault.groovy
Labels: approved, reviewed, p0_b, dev/3.0.x

#42279 [test](mtmv) Auto calc the value of sync_cbo_rewrite variable to makesure the same test code in different version
  fe/fe-core/src/main/java/org/apache/doris/nereids/NereidsPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/MaterializationContext.java
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#42109 [fix](auth)fix show load priv bug (#41723)
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BulkLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadManager.java
Labels: area/load

#41001 [cases](ip) improve cases for ip functions
  regression-test/data/nereids_function_p0/fn_test_ip_invalid.csv
  regression-test/data/nereids_function_p0/fn_test_ip_normal.csv
  regression-test/data/nereids_function_p0/fn_test_ip_nullable.csv
  regression-test/data/nereids_function_p0/fn_test_ip_special.csv
  regression-test/data/nereids_function_p0/fn_test_ip_special_no_null.csv
  regression-test/data/nereids_function_p0/scalar_function/IP.out
  regression-test/data/nereids_function_p0/test_ip.csv
  regression-test/suites/nereids_function_p0/load.groovy
  regression-test/suites/nereids_function_p0/scalar_function/IP.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#43243 [fix](array-funcs)fix array funcs which ret can be nullable
  be/src/vec/functions/array/function_array_distance.h
  be/src/vec/functions/array/function_array_element.h
  be/src/vec/functions/array/function_array_index.h
  regression-test/data/inverted_index_p0/test_array_with_inverted_index_all_type.out
  regression-test/suites/inverted_index_p0/test_array_with_inverted_index_all_type.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x, lfs-detected!

#43359 [opt](pr-template) change committer to author
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, reviewed

#43290 [misc](regression) adjust doc case for unique.md
  regression-test/pipeline/p0/conf/fe.conf
  regression-test/suites/doc/table-design/data-model/unique.md.groovy
  regression-test/suites/partition_p0/dynamic_partition/test_dynamic_partition.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#42996 [refine](pipeline) Remove condition_variable from MultiCastDataStreamer.
  be/src/pipeline/exec/multi_cast_data_streamer.cpp
  be/src/pipeline/exec/multi_cast_data_streamer.h
Labels: approved, reviewed

#42367 [feature](information_schema) add rowsets table into information_schema in cloud mode
  be/src/exec/schema_scanner/schema_rowsets_scanner.cpp
  regression-test/data/query_p0/system/test_query_sys_scan_rowsets.out
  regression-test/suites/query_p0/system/test_query_sys_scan_rowsets.groovy
Labels: approved

#43335 [fix](cloud) Replace `cloud cluster` to `compute group` in error hint
  fe/fe-core/src/main/java/org/apache/doris/cloud/analysis/UseCloudClusterStmt.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/catalog/CloudEnv.java
Labels: approved, reviewed, dev/3.0.x

#42470 [fix](cluster key) improve cluster key lookup rowkey
  be/src/olap/base_tablet.cpp
Labels: approved, reviewed

#43378 [fix](bloom filter)Fix drop column with bloom filter (#41369)
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
  regression-test/data/bloom_filter_p0/test_bloom_filter_drop_column.out
  regression-test/suites/bloom_filter_p0/test_bloom_filter_drop_column.groovy
Labels: approved, reviewed

#43358 [fix](cloud-mow) Fix clear GetDeleteBitmapResponse problem when geting delete bitmap fail and retry
  be/src/cloud/cloud_meta_mgr.cpp
  cloud/src/meta-service/meta_service.cpp
  cloud/src/meta-service/meta_service_helper.h
  cloud/test/meta_service_test.cpp
Labels: approved, reviewed, dev/3.0.x

#43355 [opt](max-compute) avoid repeated location path creation
  fe/fe-core/src/main/java/org/apache/doris/datasource/maxcompute/source/MaxComputeScanNode.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.3-merged

#43230 [test](routine load) add routine load doc case
  regression-test/data/doc/data-operate/import/import-way/routine-load-manual.md.out
  regression-test/data/doc/data-operate/import/import-way/test_rl_array.json
  regression-test/data/doc/data-operate/import/import-way/test_rl_bitmap.json
  regression-test/data/doc/data-operate/import/import-way/test_rl_column_mapping.csv
  regression-test/data/doc/data-operate/import/import-way/test_rl_csv.csv
  regression-test/data/doc/data-operate/import/import-way/test_rl_delete.csv
  regression-test/data/doc/data-operate/import/import-way/test_rl_hll.csv
  regression-test/data/doc/data-operate/import/import-way/test_rl_json.json
  regression-test/data/doc/data-operate/import/import-way/test_rl_json_path.json
  regression-test/data/doc/data-operate/import/import-way/test_rl_json_root.json
  regression-test/data/doc/data-operate/import/import-way/test_rl_map.json
  regression-test/data/doc/data-operate/import/import-way/test_rl_max_filter_ratio.csv
  regression-test/data/doc/data-operate/import/import-way/test_rl_partition.csv
  regression-test/suites/doc/data-operate/import/import-way/routine-load-manual.md.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#43360 [Chore](exchange) add LZ4_MAX_INPUT_SIZE check on DataTypeString::get_uncompressed_seri…
  be/src/vec/data_types/data_type_string.cpp
  be/test/vec/jsonb/serialize_test.cpp
Labels: approved, reviewed

#43336 [fix](build index)Fix build index empty index file on renamed column
  be/src/olap/task/index_builder.cpp
  regression-test/suites/fault_injection_p0/test_match_without_index_fault_injection.groovy
  regression-test/suites/inverted_index_p0/index_change/test_index_change_on_renamed_column.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41176 [fix](ES Catalog)Only like on keyword can be applied to wildcard query
  fe/fe-core/src/main/java/org/apache/doris/catalog/EsTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/es/EsExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/es/EsSchemaCacheValue.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/es/EsUtil.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/es/QueryBuilders.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/es/source/EsScanNode.java
  fe/fe-core/src/test/java/org/apache/doris/external/elasticsearch/EsUtilTest.java
  fe/fe-core/src/test/java/org/apache/doris/external/elasticsearch/QueryBuildersTest.java
  regression-test/data/external_table_p0/es/test_es_query.out
  regression-test/suites/external_table_p0/es/test_es_query.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x

#43262 [fix](cloud) fix core dump in CloudWarmUpManager::handle_jobs
  be/src/cloud/cloud_warm_up_manager.cpp
  be/src/cloud/cloud_warm_up_manager.h
Labels: approved, reviewed, dev/3.0.x

#42677 [cherry-pick](branch-3.0)add SessionVariable for enableCooldownReplicaAffinity
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  regression-test/suites/show_p0/test_show_variables.groovy
Labels: kind/behavior-changed

#42680 [opt](store) allow to set storage_page_size for tables
  be/src/cloud/pb_convert.cpp
  be/src/olap/compaction.cpp
  be/src/olap/delta_writer_v2.cpp
  be/src/olap/rowset/rowset_writer_context.h
  be/src/olap/rowset/segment_v2/options.h
  be/src/olap/rowset/segment_v2/segment_writer.cpp
  be/src/olap/rowset/segment_v2/vertical_segment_writer.cpp
  be/src/olap/rowset_builder.cpp
  be/src/olap/tablet_meta.cpp
  be/src/olap/tablet_meta.h
  fe/fe-core/src/main/java/org/apache/doris/alter/CloudRollupJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/alter/CloudSchemaChangeJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/alter/RollupJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ModifyTablePropertiesClause.java
  fe/fe-core/src/main/java/org/apache/doris/backup/RestoreJob.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/TableProperty.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/datasource/CloudInternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/master/ReportHandler.java
  fe/fe-core/src/main/java/org/apache/doris/task/CreateReplicaTask.java
  fe/fe-core/src/test/java/org/apache/doris/common/PropertyAnalyzerTest.java
  fe/fe-core/src/test/java/org/apache/doris/task/AgentTaskTest.java
  gensrc/proto/olap_file.proto
  gensrc/thrift/AgentService.thrift
  regression-test/data/query_p0/system/test_table_properties.out
  regression-test/suites/fault_injection_p0/test_storage_page_size_fault.groovy
  regression-test/suites/query_p0/system/test_storage_page_size.groovy
Labels: approved, reviewed, dev/3.0.x

#41607 [opt](variable) force update some variable by variable version
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/DocGenerator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/GlobalVariable.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/qe/VariableMgr.java
Labels: approved, reviewed, dev/2.1.7-merged

#41037 [enhancement](cloud) support BE http action: list_cache and clear
  be/src/http/action/file_cache_action.cpp
  be/src/io/cache/block_file_cache_factory.cpp
  be/src/io/cache/block_file_cache_factory.h
  be/src/io/cache/file_block.cpp
  be/src/io/cache/file_block.h
  be/src/io/cache/file_cache_storage.h
  be/src/io/cache/fs_file_cache_storage.cpp
  be/src/io/cache/fs_file_cache_storage.h
  be/src/io/cache/mem_file_cache_storage.cpp
  be/src/io/cache/mem_file_cache_storage.h
  regression-test/suites/cloud_p0/cache/http/test_list_cache_file.groovy
Labels: approved, reviewed

#43240 [test](doc) add some `data-admin` example in doris's doc to regression test
  regression-test/suites/doc/admin-manual/data-admin/backup.md.groovy
  regression-test/suites/doc/admin-manual/data-admin/recyclebin.md.groovy
  regression-test/suites/doc/admin-manual/data-admin/restore.md.groovy
Labels: approved, reviewed, dev/3.0.x

#43244 [fix](statistics)Change column statistics table varchar length to 1024.
  fe/fe-core/src/main/java/org/apache/doris/analysis/ModifyColumnClause.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/InternalSchemaInitializer.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticConstants.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/InternalSchemaInitializerTest.java
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x

#42379 [fix](cloud-mow) MS should delete the existing keys before rewriting it when processing old version delete bitmap on cu compaction
  be/src/cloud/cloud_cumulative_compaction.cpp
  be/src/cloud/cloud_cumulative_compaction.h
  be/src/cloud/cloud_delete_bitmap_action.cpp
  be/src/cloud/cloud_meta_mgr.cpp
  be/src/cloud/cloud_meta_mgr.h
  cloud/src/meta-service/meta_service.cpp
  cloud/test/meta_service_test.cpp
Labels: approved, reviewed, p0_c, dev/3.0.x

#43370 [fix](planner) NullLiteral should always having a correct Type and set to be analyzed
  fe/fe-core/src/main/java/org/apache/doris/analysis/NullLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/StringLiteral.java
  regression-test/data/insert_p0/test_insert_nan.out
  regression-test/suites/insert_p0/test_insert_nan.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x

#43376 [fix](mtmv)fix mtmv deadlock issue
  fe/fe-core/src/main/java/org/apache/doris/catalog/MTMV.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/PartitionsProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVPartitionUtil.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVRelatedTableIf.java
Labels: approved, reviewed, p0_b, dev/2.1.x, dev/3.0.x

#43348 [fix](test) fix clickhouse jdbc catalog func with cast push down case
  regression-test/suites/external_table_p0/jdbc/test_clickhouse_jdbc_catalog.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#43234 [Dependency](Fe) Upgrade HikariCP version to 6.0.0
  fe/pom.xml
Labels: approved, reviewed, dev/3.0.x

#36520 [test](mtmv)Test and check the differences between MTMV and OLAP
  regression-test/suites/mtmv_p0/test_mtmv_outfile.groovy
  regression-test/suites/mtmv_p0/test_mtmv_property.groovy
  regression-test/suites/mtmv_p0/test_mtmv_sql_cache_and_profile.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#43381 [opt](cloud) Simplify default config file of meta-service
  cloud/conf/doris_cloud.conf
  cloud/src/common/config.h
Labels: approved, reviewed, dev/3.0.x

#43025 [fix](resource) fix can't update BE s3 resource config
  be/src/agent/task_worker_pool.cpp
  be/src/io/fs/s3_file_system.cpp
Labels: approved, reviewed

#43266 [fix](build index)Fix build index failed on renamed column (#42882)(#43246)(#43336)
  be/src/olap/tablet_schema.cpp
  be/src/olap/task/index_builder.cpp
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/BuildIndexClause.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateIndexClause.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateTableStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/IndexDef.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Index.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/MaterializedIndexMeta.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/IndexDefinition.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/OlapTableTest.java
  fe/fe-core/src/test/java/org/apache/doris/common/proc/IndexesProcNodeTest.java
  fe/fe-core/src/test/java/org/apache/doris/persist/TableAddOrDropColumnsInfoTest.java
  gensrc/thrift/Descriptors.thrift
  regression-test/data/inverted_index_p0/index_change/test_index_change_on_renamed_column.out
  regression-test/suites/fault_injection_p0/test_match_without_index_fault_injection.groovy
  regression-test/suites/inverted_index_p0/index_change/test_index_change_on_renamed_column.groovy
Labels: approved, reviewed

#43167 [improvement](paimon)Using table serialization on the jni side
  be/src/vec/exec/format/table/paimon_jni_reader.cpp
  fe/be-java-extensions/paimon-scanner/src/main/java/org/apache/doris/paimon/PaimonJniScanner.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/paimon/source/PaimonScanNode.java
  gensrc/thrift/PlanNodes.thrift
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#43271 [Feat](Nereids) support show variables and show view command
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/catalog/Database.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PlanType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/Command.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ShowCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ShowVariablesCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ShowViewCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/TableNameInfo.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/CommandVisitor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  regression-test/data/nereids_p0/ddl/show_variables/show_variables_command.out
  regression-test/data/nereids_p0/ddl/show_view/show_view_command.out
  regression-test/suites/nereids_p0/ddl/show_variables/show_variables_command.groovy
  regression-test/suites/nereids_p0/ddl/show_view/show_view_command.groovy
Labels: approved, reviewed

#43459 [fix](ES Catalog)Only like on keyword can be applied to wildcard query (#41176)
  fe/fe-core/src/main/java/org/apache/doris/catalog/EsTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/external/EsExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/external/elasticsearch/EsUtil.java
  fe/fe-core/src/main/java/org/apache/doris/external/elasticsearch/QueryBuilders.java
  fe/fe-core/src/main/java/org/apache/doris/planner/EsScanNode.java
  fe/fe-core/src/test/java/org/apache/doris/external/elasticsearch/EsUtilTest.java
  fe/fe-core/src/test/java/org/apache/doris/external/elasticsearch/QueryBuildersTest.java
  regression-test/data/external_table_p0/es/test_es_query.out
  regression-test/suites/external_table_p0/es/test_es_query.groovy
Labels: area/planner, kind/test

#43397 [fix] Implementing match_phrase_edge without index query method (#41658)
  be/src/vec/functions/match.cpp
  be/src/vec/functions/match.h
  regression-test/data/inverted_index_p0/test_index_match_phrase_edge.out
  regression-test/suites/inverted_index_p0/test_index_match_phrase_edge.groovy
Labels: approved, reviewed

#43395 [fix](inverted index) Fix incorrect exception handling (#41874)
  be/test/olap/rowset/segment_v2/inverted_index/index_compaction_test.cpp
Labels: approved, reviewed

#43394 [fix](inverted index) Fix incorrect usage of regexp compile_err (#41944)
  be/src/vec/functions/match.cpp
  regression-test/suites/inverted_index_p0/test_no_index_match.groovy
Labels: approved, reviewed

#43393 [fix](inverted index) fix error handling in fast_execute (#40024)
  be/src/vec/exprs/vexpr.cpp
  be/src/vec/exprs/vexpr.h
Labels: approved, reviewed

#43352 [fix](cloud) Add check for alter storage vault type
  cloud/src/meta-service/meta_service_resource.cpp
  regression-test/suites/vault_p0/alter/test_alter_vault_type.groovy
  regression-test/suites/vault_p0/create/test_create_vault.groovy
Labels: approved, reviewed, dev/3.0.x

#39649 [test](inverted index)Add fault injection cases for index writing
  be/src/olap/compaction.cpp
  be/src/olap/inverted_index_parser.cpp
  be/src/olap/olap_server.cpp
  be/src/olap/rowset/segment_v2/inverted_index/char_filter/char_filter_factory.h
  be/src/olap/rowset/segment_v2/inverted_index_compaction.cpp
  be/src/olap/rowset/segment_v2/inverted_index_file_writer.cpp
  be/src/olap/rowset/segment_v2/inverted_index_file_writer.h
  be/src/olap/rowset/segment_v2/inverted_index_fs_directory.cpp
  be/src/olap/rowset/segment_v2/inverted_index_writer.cpp
  be/src/olap/task/index_builder.cpp
  regression-test/suites/fault_injection_p0/test_index_compaction_exception_fault_injection.groovy
  regression-test/suites/fault_injection_p0/test_write_inverted_index_exception_fault_injection.groovy
  regression-test/suites/fault_injection_p2/test_build_index_exception_fault_injection.groovy
Labels: approved, reviewed, dev/2.1.x

#43334 [chore](log) Use correct error type of uneven user behaviour
  be/src/vec/columns/column_array.cpp
  be/src/vec/columns/column_map.cpp
  be/src/vec/functions/array/function_array_with_constant.cpp
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#43340 [chore](log) Reduce unnecessary warning log of file not found
  be/src/olap/tablet.cpp
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#43451 [fix](cloud version) fix version of information_schema table backward when query in follower node
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
Labels: approved, reviewed, dev/3.0.x

#43279 [improvement](statistics)Remove useless stats validation check.
  fe/fe-core/src/main/java/org/apache/doris/statistics/ColStatsData.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/ColumnStatisticsCacheLoader.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsCache.java
  regression-test/suites/statistics/analyze_stats.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x

#42998 [fix](profile) When all preds are always_true, input rows not be counted in the profile.
  be/src/olap/bitmap_filter_predicate.h
  be/src/olap/bloom_filter_predicate.h
  be/src/olap/column_predicate.h
  be/src/olap/in_list_predicate.h
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/olap/rowset/segment_v2/segment_iterator.h
Labels: approved, reviewed, dev/2.1.x

#43417 [cherry-pick][test](doc) add some `data-admin` example in doris's doc to regression test (#43240)
  regression-test/suites/doc/admin-manual/data-admin/backup.md.groovy
  regression-test/suites/doc/admin-manual/data-admin/recyclebin.md.groovy
  regression-test/suites/doc/admin-manual/data-admin/restore.md.groovy
Labels: dev/2.1.x, dev/3.0.x
