Repository apache/doris, pull requests merged in 2024-06, with the labels that each got.

#35744 [Fix](inverted index) fix fast execute condition for vexpr #35673
  be/src/vec/exprs/vectorized_fn_call.cpp
  be/src/vec/exprs/vexpr.h
  be/src/vec/exprs/vliteral.h
  regression-test/data/inverted_index_p0/test_index_rqg_bug2.out
  regression-test/suites/inverted_index_p0/test_index_rqg_bug2.groovy
Labels: kind/test

#35673 [Fix](inverted index) fix fast execute condition for vexpr
  be/src/vec/exprs/vectorized_fn_call.cpp
  be/src/vec/exprs/vexpr.h
  be/src/vec/exprs/vliteral.h
  regression-test/data/inverted_index_p0/test_index_rqg_bug2.out
  regression-test/suites/inverted_index_p0/test_index_rqg_bug2.groovy
Labels: approved, reviewed, p0_b, dev/2.1.x, dev/2.0.11-merged

#35608 [feature](be jvm monitor)append enable_jvm_monitor in be.conf to control jvm monitor.
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/util/jvm_metrics.cpp
  be/src/util/jvm_metrics.h
  regression-test/pipeline/external/conf/be.conf
  regression-test/pipeline/p0/conf/be.conf
  regression-test/pipeline/p1/conf/be.conf
Labels: approved, reviewed, dev/2.1.x

#35719 [Bug](load) fix s3 load not display the progress info
  be/src/runtime/fragment_mgr.cpp
Labels: approved, reviewed

#35536 [fix](Nereids): Convert VarcharLiteral to StringLikeLiteral in Function Signatures
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/executable/DateTimeExtractAndTransform.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/executable/ExecutableFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/StringLikeLiteral.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/expression/FoldConstantTest.java
Labels: approved, reviewed, dev/2.1.x

#35756 [refactor](cleancode) remove unused code from be
  be/src/exec/data_sink.h
  be/src/exec/exec_node.h
  be/src/pipeline/exec/exchange_sink_buffer.cpp
  be/src/pipeline/exec/exchange_sink_buffer.h
  be/src/pipeline/exec/multi_cast_data_streamer.h
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/pipeline/pipeline_task.cpp
  be/src/pipeline/pipeline_task.h
  be/src/vec/exec/vanalytic_eval_node.cpp
  be/src/vec/exec/vanalytic_eval_node.h
  be/src/vec/exec/vpartition_sort_node.cpp
  be/src/vec/exec/vpartition_sort_node.h
  be/src/vec/sink/async_writer_sink.h
  be/src/vec/sink/multi_cast_data_stream_sink.h
  be/src/vec/sink/vdata_stream_sender.cpp
  be/src/vec/sink/vdata_stream_sender.h
  be/src/vec/sink/vmemory_scratch_sink.cpp
  be/src/vec/sink/vmemory_scratch_sink.h
  be/src/vec/sink/writer/async_result_writer.h
Labels: approved, reviewed

#35725 [Test](regression-test): do not use path style to access aliyun OSS
  regression-test/suites/export_p0/outfile/csv/test_outfile_empty_data.groovy
  regression-test/suites/export_p2/test_export_with_parallelism.groovy
  regression-test/suites/external_table_p0/tvf/test_s3_tvf.groovy
  regression-test/suites/external_table_p0/tvf/test_s3_tvf_compression.groovy
  regression-test/suites/external_table_p0/tvf/test_s3_tvf_with_resource.groovy
  regression-test/suites/external_table_p2/tvf/test_path_partition_keys.groovy
Labels: approved, reviewed

#35527 [chore](cloud) Add show hotspot tablet API on BE
  be/src/cloud/cloud_rowset_builder.cpp
  be/src/http/action/show_hotspot_action.cpp
  be/src/http/action/show_hotspot_action.h
  be/src/olap/base_tablet.h
  be/src/olap/compaction.cpp
  be/src/service/http_service.cpp
  be/src/vec/exec/scan/new_olap_scanner.cpp
Labels: approved, reviewed

#35739 [fix](partial update) duplicate key occur when BE restart after conflict concurrent partial update
  be/src/olap/base_tablet.cpp
  be/src/olap/base_tablet.h
Labels: approved, reviewed, p0_c, dev/2.0.x, dev/2.1.x

#35714 [revert](fe) revert upgrade dependencies of #33360
  fe/be-java-extensions/avro-scanner/pom.xml
  fe/be-java-extensions/hudi-scanner/pom.xml
  fe/be-java-extensions/preload-extensions/pom.xml
  fe/fe-core/pom.xml
  fe/pom.xml
Labels: area/planner, usercase, dev/2.0.x

#35437 [fix](drop table) Improve error prompts when deleting materialized views
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/DropMaterializedViewTest.java
  fe/fe-core/src/test/java/org/apache/doris/common/util/UnitTestUtil.java
Labels: approved, reviewed, dev/2.1.x

#35713 [Performance](opt) opt the memcpy and string compare performance
  be/src/gutil/strings/fastmem.h
  be/src/gutil/strings/stringpiece.h
  be/src/util/bitmap.h
  be/src/util/faststring.h
  be/src/util/memcpy_inlined.h
  be/src/vec/columns/column_string.cpp
  be/src/vec/common/string_ref.h
  be/test/util/mysql_row_buffer_test.cpp
Labels: approved, reviewed

#35750 [Enhancement] support to erase all tables and partitions with same DbId while drop a database which is not in catalog recycle bin
  fe/fe-core/src/main/java/org/apache/doris/catalog/CatalogRecycleBin.java
  regression-test/suites/catalog_recycle_bin_p0/test_drop_catalog_recycle_bin.groovy
Labels: approved, reviewed

#35761 [enhancement](oom) add exception in olap data convertor when memory is not enough to prevent oom
  be/src/olap/rowset/segment_v2/plain_page.h
  be/src/olap/rowset/segment_v2/segment_writer.cpp
  be/src/olap/rowset/segment_v2/vertical_segment_writer.cpp
  be/src/pipeline/exec/group_commit_block_sink_operator.cpp
  be/src/vec/core/block.cpp
  be/src/vec/core/block.h
  be/src/vec/olap/olap_data_convertor.cpp
  be/src/vec/olap/olap_data_convertor.h
  be/src/vec/sink/group_commit_block_sink.cpp
  be/src/vec/sink/writer/vtablet_writer.cpp
Labels: approved, reviewed

#35395 [regression] Add test checkpoint for the Show Procedure status and Show create procedure command
  regression-test/suites/plsql_p0/test_plsql_show_procedure.groovy
Labels: approved, reviewed, dev/2.1.x

#31508 [Scanner](revert) revert the scanner change by apache#35604
  be/src/vec/exec/scan/scanner_context.cpp
Labels: approved, reviewed

#35710 [fix](audit log) Fix audit plugin run in cloud mode
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/LoadAction.java
Labels: approved, reviewed

#35690 [fix](s3) move s3 providers to fe-common to be accessible for jni reader
  fe/be-java-extensions/avro-scanner/pom.xml
  fe/fe-common/pom.xml
  fe/fe-common/src/main/java/org/apache/doris/common/credentials/CloudCredential.java
  fe/fe-common/src/main/java/org/apache/doris/common/credentials/CloudCredentialWithEndpoint.java
  fe/fe-common/src/main/java/org/apache/doris/common/credentials/DataLakeAWSCredentialsProvider.java
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/org/apache/doris/catalog/S3Resource.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/S3Util.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/dlf/DLFCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/maxcompute/MaxComputeExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/PropertyConverter.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/constants/BaseProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/constants/CosProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/constants/DLFProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/constants/GCSProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/constants/GlueProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/constants/MCProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/constants/MinioProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/constants/ObsProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/constants/OssProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/constants/PaimonProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/constants/S3Properties.java
  fe/fe-core/src/main/java/org/apache/doris/fs/obj/S3ObjStorage.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/S3TableValuedFunction.java
Labels: approved, reviewed

#35770 [fix](rpc) fix transfer large data and enable transfer_large_data_by_brpc by default
  be/src/common/config.cpp
  be/src/util/proto_util.h
  regression-test/suites/load_p2/test_large_data_by_rpc.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x

#35769 [fix](ub) fix some ub error
  be/src/exprs/hybrid_set.h
  be/src/olap/memtable_memory_limiter.h
  be/src/olap/rowset/segment_v2/bloom_filter.cpp
  be/src/pipeline/exec/exchange_source_operator.cpp
  be/src/runtime/decimalv2_value.cpp
  be/src/util/frame_of_reference_coding.h
  be/src/util/timezone_utils.cpp
  be/src/vec/columns/column_decimal.h
  be/src/vec/columns/column_nullable.h
  be/src/vec/columns/column_object.cpp
  be/src/vec/columns/column_vector.h
  be/src/vec/common/hash_table/hash_map_context.h
  be/src/vec/common/hash_table/hash_table.h
  be/src/vec/data_types/serde/data_type_datetimev2_serde.cpp
  be/src/vec/exec/format/parquet/byte_array_dict_decoder.cpp
  be/src/vec/exec/format/parquet/fix_length_dict_decoder.hpp
  be/src/vec/exec/jni_connector.cpp
  be/src/vec/functions/array/function_array_element.h
  be/src/vec/functions/function_bit_shift.cpp
  be/src/vec/json/path_in_data.cpp
  regression-test/data/correctness_p0/test_bit_shift_lagency.out
  regression-test/data/correctness_p0/test_bit_shift_nereids.out
  regression-test/data/query_p0/sql_functions/datetime_functions/test_date_function.out
  regression-test/suites/correctness_p0/test_bit_shift_nereids.groovy
  regression-test/suites/query_p0/sql_functions/datetime_functions/test_date_function.groovy
Labels: approved, reviewed

#35775 [improve](session) print more error msg when set a wrong session variable name
  fe/fe-core/src/main/java/org/apache/doris/common/ErrorCode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/VariableMgr.java
Labels: approved, reviewed, dev/2.1.x

#35736 [fix](compile) avoid use jdk17 api Optional#isEmpty since target is 1.8
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/FilterEstimation.java
Labels: reviewed, not-merge/2.1

#35639 [enhancement](memory) Add PODArray UT and pick some patch
  be/src/vec/common/pod_array.h
  be/src/vec/common/pod_array_fwd.h
  be/test/vec/common/pod_array_test.cpp
Labels: approved, reviewed

#35688 [opt](fe) Remove redundant fe config `cloud_meta_service_rpc_failed_retry_times`
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/datasource/CloudInternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/rpc/VersionHelper.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/transaction/CloudGlobalTransactionMgr.java
Labels: approved, reviewed

#35777 [fix](pipeline) Fix reporting status if prepare failed
  be/src/pipeline/pipeline_fragment_context.cpp
Labels: approved, reviewed

#35644 [fix](mtmv)Fix that the storage medium specified for the mtmv is SSD, but the partition storage medium for the mtmv is still HDD
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
  regression-test/pipeline/p0/conf/be.conf
  regression-test/suites/mtmv_p0/test_storage_medium_mtmv.groovy
Labels: approved, reviewed, dev/2.1.x

#35642 [opt](exchange) Add buffer size limit for exchange sink operator
  be/src/pipeline/exec/exchange_sink_buffer.cpp
  be/src/pipeline/exec/exchange_sink_buffer.h
  be/src/pipeline/exec/exchange_sink_operator.cpp
  be/src/pipeline/exec/exchange_sink_operator.h
  be/src/vec/sink/vdata_stream_sender.cpp
  be/src/vec/sink/vdata_stream_sender.h
Labels: approved, reviewed

#35730 [Chore](bitmap) set enable_set_in_bitmap_value default value to true
  be/src/common/config.cpp
Labels: approved, reviewed

#35762 [fix](s3) fix invalid s3 properties checking logic
  be/src/util/s3_util.cpp
  fe/fe-core/src/main/java/org/apache/doris/catalog/S3Resource.java
  fe/fe-core/src/main/java/org/apache/doris/fs/remote/S3FileSystem.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/table/Hdfs.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/table/Local.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/table/S3.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/S3TableValuedFunction.java
  regression-test/suites/external_table_p0/tvf/test_s3_tvf_with_resource.groovy
Labels: approved, reviewed, dev/2.1.4-merged

#35749 [fix](mtmv) Mapping materialization statistics's expressionToColumnStats to mv scan plan based
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewAggregateRule.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewJoinRule.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewRule.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AsyncMaterializationContext.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/MaterializationContext.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/MaterializedViewScanRule.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/Statistics.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/mv/IdStatisticsMapTest.java
Labels: approved, reviewed, dev/2.1.x

#34313 [Feat](nereids) add transform rule MergePercentileToArray
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/Rewriter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/MergePercentileToArray.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/MergePercentileToArrayTest.java
  regression-test/data/nereids_rules_p0/merge_percentile_to_array/merge_percentile_to_array.out
  regression-test/plugins/plugin_must_contains.groovy
  regression-test/suites/nereids_rules_p0/merge_percentile_to_array/merge_percentile_to_array.groovy
Labels: approved, reviewed, dev/2.1.x

#35653 [fix](fe) Add check editlog size mechanism for backupJob
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupJob.java
  fe/fe-core/src/main/java/org/apache/doris/journal/Journal.java
  fe/fe-core/src/main/java/org/apache/doris/journal/bdbje/BDBJEJournal.java
  fe/fe-core/src/main/java/org/apache/doris/journal/local/LocalJournal.java
  fe/fe-core/src/main/java/org/apache/doris/persist/EditLog.java
Labels: approved, reviewed, meta-change

#35790 [enhancement](oom) return error when bloom filter allocate memory failed
  be/src/olap/primary_key_index.cpp
  be/src/olap/rowset/segment_v2/bloom_filter_index_writer.cpp
  be/src/olap/rowset/segment_v2/bloom_filter_index_writer.h
  be/src/olap/rowset/segment_v2/column_writer.cpp
  be/src/vec/core/block.cpp
  be/test/olap/rowset/segment_v2/bloom_filter_index_reader_writer_test.cpp
Labels: approved, reviewed

#35798 [enhancement](debugtimeout) should print debug stack when timeout
  be/src/pipeline/pipeline_fragment_context.cpp
Labels: approved, reviewed

#35797 [Chore](materialized-view) enable create mv on mow table
  fe/fe-core/src/main/java/org/apache/doris/alter/MaterializedViewHandler.java
  regression-test/data/mv_p0/test_mv_mow/test_mv_mow.out
  regression-test/suites/mv_p0/test_mv_mow/test_mv_mow.groovy
Labels: approved, reviewed

#35727 [fix](Nereids) unix_timestamp compute signature and fold const is wrong
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/executable/DateTimeExtractAndTransform.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/UnixTimestamp.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/expression/FoldConstantTest.java
Labels: approved, reviewed, p0_w, dev/2.1.x

#35796 [opt](load) use notify to replace polling for FlushToken
  be/src/olap/memtable_flush_executor.cpp
  be/src/olap/memtable_flush_executor.h
Labels: approved, reviewed, dev/2.1.x

#35792 [enhancement](regression-test) modify a key type tests
  regression-test/suites/schema_change_p0/test_unique_schema_key_change_modify.groovy
  regression-test/suites/schema_change_p0/test_unique_schema_key_change_modify1.groovy
Labels: approved, reviewed

#29641 [Feature](exec) Support group by limit opt in BE code
  be/src/pipeline/dependency.cpp
  be/src/pipeline/dependency.h
  be/src/pipeline/exec/aggregation_sink_operator.cpp
  be/src/pipeline/exec/aggregation_sink_operator.h
  be/src/pipeline/exec/aggregation_source_operator.cpp
  be/src/pipeline/exec/aggregation_source_operator.h
  be/src/pipeline/exec/operator.cpp
  be/src/vec/columns/column_nullable.cpp
  be/src/vec/columns/column_string.cpp
  be/src/vec/columns/column_string.h
  be/src/vec/columns/column_vector.cpp
  be/src/vec/core/block.cpp
  be/src/vec/core/block.h
  be/src/vec/exec/vaggregation_node.cpp
  be/src/vec/exec/vaggregation_node.h
Labels: approved, reviewed

#35734 [Feature](IP) support ipv4/ipv6 with inverted index and conjuncts for query
  be/src/exec/olap_common.h
  be/src/olap/olap_common.h
  be/src/olap/rowset/segment_v2/inverted_index_writer.cpp
  be/src/olap/utils.h
  be/src/pipeline/exec/scan_operator.cpp
  be/src/vec/exec/scan/vscan_node.cpp
  fe/fe-core/src/main/java/org/apache/doris/analysis/IndexDef.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/IndexDefinition.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/types/DataType.java
  regression-test/data/datatype_p0/ip/test_ip_in_inverted_index.out
  regression-test/suites/datatype_p0/ip/test_ip_in_inverted_index.groovy
Labels: approved, reviewed, dev/2.1.x

#35815 [fix](be) Fix invalid memory order argument to atomic operation
  be/src/runtime/exec_env.h
Labels: approved, reviewed

#35818 [Fix](show data) fix show data total size wrong
  fe/fe-core/src/main/java/org/apache/doris/catalog/TabletStatMgr.java
  regression-test/suites/inverted_index_p0/test_show_data.groovy
Labels: approved, reviewed

#35805 [fix](third-party) enable keepalive on socket created by libevent
  thirdparty/patches/libevent-1532.patch
  thirdparty/patches/libevent-enable_keepalive_accepted_socket.patch
Labels: approved, reviewed, dev/2.1.x, dev/1.2.10

#35802 [improvement](partial update)add more logs for partial update
  be/src/olap/base_tablet.cpp
  be/src/olap/compaction.cpp
  be/src/olap/rowset/beta_rowset_writer.h
  be/src/olap/rowset/beta_rowset_writer_v2.h
  be/src/olap/rowset/rowset_writer.h
  be/src/olap/rowset/segment_creator.cpp
  be/src/olap/rowset/segment_creator.h
  be/src/olap/rowset/segment_v2/segment_writer.cpp
  be/src/olap/rowset/segment_v2/segment_writer.h
  be/src/olap/rowset/segment_v2/vertical_segment_writer.cpp
  be/src/olap/rowset/segment_v2/vertical_segment_writer.h
  be/src/olap/rowset_builder.cpp
  be/src/olap/tablet_meta.cpp
  be/src/olap/tablet_meta.h
Labels: approved, reviewed, dev/2.1.x

#35807 [feature](http) Support to acquire md5 digest of the file to download
  be/src/http/http_client.cpp
  be/src/http/http_client.h
  be/src/http/utils.cpp
  be/src/http/utils.h
  be/test/http/http_client_test.cpp
Labels: reviewed

#35781 [fix](simd-json-reader) fix SIMD json reader lose data and support stream parser
  be/src/vec/exec/format/json/new_json_reader.cpp
  be/src/vec/exec/format/json/new_json_reader.h
  regression-test/data/load_p0/stream_load/iterate_read_json.json
  regression-test/data/load_p0/stream_load/test_json_load.out
  regression-test/suites/load_p0/stream_load/test_json_load.groovy
Labels: approved, reviewed

#35741 [Improvement](coldheat) add statment to show objects which use storage policy
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowStoragePolicyUsingStmt.java
  fe/fe-core/src/main/java/org/apache/doris/policy/PolicyMgr.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  regression-test/suites/cold_heat_separation_p2/test_show_storage_policy_using.groovy
Labels: approved, reviewed

#35679 [opt](log) refine the FE logger
  bin/start_fe.sh
  fe/fe-common/pom.xml
  fe/fe-common/src/main/java/org/apache/doris/cloud/security/UrlSecurityChecker.java
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-common/src/main/java/org/apache/doris/common/LogUtils.java
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/org/apache/doris/DorisFE.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/common/Log4jConfig.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/DocGenerator.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/JdkUtils.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/PlatformName.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/Util.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/lakesoul/LakeSoulExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/ha/BDBStateChangeListener.java
  fe/fe-core/src/main/java/org/apache/doris/journal/bdbje/BDBEnvironment.java
  fe/fe-core/src/main/java/org/apache/doris/journal/bdbje/BDBJEJournal.java
  fe/fe-core/src/main/java/org/apache/doris/journal/bdbje/BDBJournalCursor.java
  fe/fe-core/src/main/java/org/apache/doris/journal/bdbje/BDBTool.java
  fe/fe-core/src/main/java/org/apache/doris/journal/local/LocalJournal.java
  fe/fe-core/src/main/java/org/apache/doris/journal/local/LocalJournalCursor.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/rewrite/CustomRewriteJob.java
  fe/fe-core/src/main/java/org/apache/doris/persist/EditLog.java
  fe/pom.xml
Labels: approved, reviewed, kind/behavior-changed, meta-change, dev/2.1.x

#35810 [Enchancement](scan) enable parallel scan when preagg is on
  be/src/pipeline/exec/olap_scan_operator.cpp
Labels: approved, reviewed

#35789 [Enchancement](bitmap) optimize bitmap deserialize and remove some unused code
  be/src/olap/bitmap_filter_predicate.h
  be/src/util/bitmap_value.h
  be/src/vec/aggregate_functions/aggregate_function_approx_count_distinct.cpp
  be/src/vec/functions/function_coalesce.cpp
  be/src/vec/jsonb/serialize.cpp
  be/src/vec/sink/vmysql_result_writer.cpp
  be/test/util/bitmap_value_test.cpp
Labels: approved, reviewed

#35820 [Enhancement](inverted index) low level log for fulltext query info
  be/src/olap/rowset/segment_v2/inverted_index_reader.cpp
Labels: approved, reviewed

#35821 [fix](multi-catalog)fix hive partition insert regression case
  fe/fe-core/src/main/java/org/apache/doris/nereids/analyzer/UnboundTableSinkCreator.java
  regression-test/suites/external_table_p0/hive/ddl/test_hive_write_type.groovy
Labels: approved, reviewed

#35716 [Improvement](local shuffle) Use grouping expr for hash shuffling
  be/src/pipeline/exec/aggregation_sink_operator.cpp
  be/src/pipeline/exec/aggregation_sink_operator.h
  be/src/pipeline/exec/analytic_sink_operator.cpp
  be/src/pipeline/exec/analytic_sink_operator.h
  be/src/pipeline/exec/distinct_streaming_aggregation_operator.cpp
  be/src/pipeline/exec/distinct_streaming_aggregation_operator.h
  be/src/pipeline/exec/partitioned_aggregation_sink_operator.h
  be/src/pipeline/exec/sort_sink_operator.cpp
  be/src/pipeline/exec/sort_sink_operator.h
  be/src/pipeline/exec/spill_sort_sink_operator.h
  be/src/pipeline/pipeline_fragment_context.cpp
Labels: approved, reviewed

#35811 [fix](nereids)keep equal predicate as join conjunct even if it can be fold to null literal
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/ExpressionRewrite.java
  regression-test/data/nereids_p0/join/test_mark_join.out
  regression-test/suites/nereids_p0/join/test_mark_join.groovy
Labels: approved, reviewed, dev/2.1.x

#35686 [fix](mtmv)mtmv disable dynamic partition
  fe/fe-core/src/main/java/org/apache/doris/analysis/ModifyTablePropertiesClause.java
  fe/fe-core/src/main/java/org/apache/doris/clone/DynamicPartitionScheduler.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/CreateMTMVInfo.java
  regression-test/suites/mtmv_p0/test_build_mtmv.groovy
  regression-test/suites/mtmv_p0/test_limit_op_mtmv.groovy
Labels: approved, reviewed, dev/2.1.x

#35235 [Bug](udtf) fix udtf core dump use as normal function
  be/src/vec/exprs/vectorized_fn_call.cpp
  be/src/vec/functions/function_fake.h
  fe/fe-core/src/main/java/org/apache/doris/catalog/Database.java
  regression-test/suites/javaudf_p0/test_javaudtf_all_types.groovy
  regression-test/suites/javaudf_p0/test_javaudtf_int.groovy
Labels: approved, reviewed, usercase

#35836 [Improvement](coldhot) add statement to show objects which use storage policy
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowStoragePolicyUsingStmt.java
  fe/fe-core/src/main/java/org/apache/doris/policy/PolicyMgr.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  regression-test/suites/cold_heat_separation_p2/test_show_storage_policy_using.groovy
Labels: area/planner, kind/test, approved, reviewed

#35813 [enhancement](nereids)eliminate repeat node if there is only 1 grouping set and no grouping scalar function
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/NormalizeRepeat.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/analysis/NormalizeRepeatTest.java
  regression-test/suites/nereids_rules_p0/grouping_sets/grouping_normalize_test.groovy
Labels: approved, reviewed, dev/2.1.x

#35768 [Fix](Tablet) Fix the issue of redundant loading of stale rowset meta
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/olap/tablet_meta.cpp
Labels: approved, reviewed, dev/2.1.x

#35876 [fix](Nereids) add one arg truncate
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Truncate.java
Labels: area/nereids

#35822 [fix](stream_load) fix stream load may failed caused by column name with keyword
  fe/fe-core/src/main/cup/sql_parser.cup
  regression-test/data/load_p0/stream_load/test_keyword.csv
  regression-test/data/load_p0/stream_load/test_stream_load_keyword.out
  regression-test/suites/load_p0/stream_load/test_stream_load_keyword.groovy
Labels: approved, reviewed

#35676 [fix](export) fix that export table retry with same label should succeed when first export job failed
  fe/fe-core/src/main/java/org/apache/doris/load/ExportMgr.java
  regression-test/data/export_p0/test_export_table_with_label_retry.out
  regression-test/suites/export_p0/test_export_table_with_label_retry.groovy
Labels: approved, reviewed

#35814 [feature](statistics)Remove not exist partition stats while analyzing.
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowTableStatsStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/InternalSchema.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/InternalSchemaInitializer.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisManager.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/BaseAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/ExternalAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/HMSAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/HistogramTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/OlapAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsAutoCollector.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsRepository.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/TableStatsMeta.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/util/StatisticsUtil.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/util/StatisticsUtilTest.java
  regression-test/suites/statistics/test_partition_stats.groovy
Labels: approved, reviewed, not-merge/2.1

#35845 [improve](fe) Support to config max msg/frame size of the thrift server
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/common/ThriftServer.java
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x

#35862 [regression](backup-restore) Add a `huge tables` backup-restore test case
  regression-test/suites/backup_restore_p2/test_backup_restore_with_many_tables.groovy
Labels: approved, reviewed

#35722 [Bugfix] Fix nullptr cache object because init file cache concurrently
  be/src/io/cache/block_file_cache_factory.cpp
  be/src/io/cache/block_file_cache_factory.h
Labels: approved, reviewed

#35869 [improve](cloud) Add profile for sync_rowsets while quering
  be/src/pipeline/exec/olap_scan_operator.cpp
  be/src/pipeline/exec/olap_scan_operator.h
Labels: approved, reviewed

#35643 [fix](broker) fix no error url when broker data quality error
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BrokerLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BrokerLoadingTaskAttachment.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadLoadingTask.java
  regression-test/suites/load_p0/broker_load/test_etl_failed.groovy
Labels: approved, reviewed, dev/2.1.x

#35603 [improve](cache) optimize the cache log
  be/src/io/cache/block_file_cache.cpp
Labels: approved, reviewed

#35880 [Fix](MS) Fix get tablet stats value api
  cloud/src/meta-service/http_encode_key.cpp
  cloud/src/meta-service/meta_service_tablet_stats.cpp
  cloud/src/meta-service/meta_service_tablet_stats.h
  cloud/test/http_encode_key_test.cpp
Labels: approved, reviewed

#35853 [fix](fe) Set is electable for checking compatibility mode
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
Labels: approved, reviewed

#34889 [fix](clone) Fix clone and alter tablet use same tablet path
  be/src/olap/data_dir.cpp
  be/src/olap/data_dir.h
  be/src/olap/storage_engine.cpp
  be/src/olap/tablet_manager.cpp
  be/src/olap/tablet_manager.h
  be/src/olap/task/engine_clone_task.cpp
  be/src/olap/task/engine_storage_migration_task.cpp
  regression-test/suites/clone_p0/test_drop_clone_tablet_path_race.groovy
Labels: approved, reviewed, p0_c, dev/2.0.x, dev/2.1.x

#35840 [streamload](redirect) Support redirect-policy for streamload which is used by audit plugin
  be/src/common/utils.h
  be/src/http/utils.cpp
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/LoadAction.java
  fe/fe-core/src/main/java/org/apache/doris/load/StreamLoadHandler.java
  fe/fe-core/src/main/java/org/apache/doris/plugin/audit/AuditStreamLoader.java
Labels: approved, reviewed

#35835 [fix](regression test) test_alter_colocate_group due to force_olap_table_replication_num
  regression-test/suites/alter_p2/test_alter_colocate_group.groovy
Labels: approved, reviewed

#35824 [fix](dynamic partition) fix dynamic partition thread met uncatch exception #35778
  fe/fe-core/src/main/java/org/apache/doris/catalog/ColocateGroupSchema.java
  fe/fe-core/src/main/java/org/apache/doris/clone/DynamicPartitionScheduler.java
  fe/fe-core/src/main/java/org/apache/doris/common/ErrorCode.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/DynamicPartitionUtil.java
  fe/fe-core/src/test/java/org/apache/doris/alter/AlterTest.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/ColocateTableTest.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/DynamicPartitionTableTest.java
  regression-test/suites/delete_p0/test_delete.groovy
  regression-test/suites/index_p0/test_bitmap_index.groovy
  regression-test/suites/partition_p0/dynamic_partition/test_dynamic_partition_failed.groovy
Labels: kind/test

#35458 [fix](move-memtable) fix move memtable core when use multi table load
  be/src/io/file_factory.cpp
  be/src/io/fs/multi_table_pipe.cpp
  be/src/io/fs/multi_table_pipe.h
Labels: approved, reviewed

#35877 (chore)[profile] remove non-pipeline logical from profile
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/query_context.cpp
  be/src/runtime/query_context.h
  be/src/runtime/runtime_query_statistics_mgr.cpp
  be/src/runtime/runtime_query_statistics_mgr.h
  fe/fe-core/src/main/java/org/apache/doris/common/profile/ExecutionProfile.java
  fe/fe-core/src/main/java/org/apache/doris/common/profile/Profile.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
Labels: approved, reviewed

#35829 [BUG] fix scan range boundary handling is incorrect #34832
  be/src/exec/olap_common.h
  regression-test/data/query_p0/scan_range/test_scan_range.out
  regression-test/suites/query_p0/scan_range/test_scan_range.groovy
Labels: kind/test

#35598 [chore](FE) Fix issues with the activation of profile protoc_rosetta
  fe/fe-core/pom.xml
Labels: approved, reviewed

#35867 [Chore](log) do not print stacktrace on ABORTED/NOT_IMPLEMENTED_ERROR
  be/src/common/status.h
Labels: approved, reviewed

#35783 [enhancement](fe-meta) Support skip specified journal to avoid FE can't be start due to a damaged journal
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/journal/bdbje/BDBJournalCursor.java
Labels: approved, reviewed

#35881 [fix](case)fix regress case for test_ip_in_inverted_index
  regression-test/data/datatype_p0/ip/test_ip_in_inverted_index.out
  regression-test/suites/datatype_p0/ip/test_ip_in_inverted_index.groovy
Labels: approved, reviewed

#35865 [fix](build) fix include for macOS compile
  be/src/io/fs/s3_obj_storage_client.cpp
Labels: approved, reviewed

#35759 [fix](RecycleBin) fix race condition issue when do execute ShowCatalogRecycleBinStmt
  fe/fe-core/src/main/java/org/apache/doris/catalog/CatalogRecycleBin.java
Labels: approved, reviewed

#35196 [improvement](jdbcScan) Change the mysql function that does not support pushdown in JdbcScan to Config
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/source/JdbcFunctionPushDownRule.java
  regression-test/suites/external_table_p0/jdbc/test_mysql_jdbc_catalog.groovy
Labels: approved, reviewed, dev/2.1.4-merged

#35860 [fix](mtmv)Mtmv support row column
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/CreateMTMVInfo.java
  regression-test/data/mtmv_p0/test_row_column_mtmv.out
  regression-test/suites/mtmv_p0/test_row_column_mtmv.groovy
Labels: approved, reviewed, dev/2.1.x

#35804 [fix](arrow-flight-sql) Fix pipelineX Unknown result sink type
  be/src/pipeline/exec/result_sink_operator.cpp
Labels: approved, reviewed

#35590 [fix](memory) Add cache manager check for exist
  be/src/runtime/memory/cache_manager.h
Labels: approved, reviewed

#35886 [fix](multicast) should not ignore Status of block::merge
  be/src/pipeline/exec/multi_cast_data_stream_source.cpp
  be/src/pipeline/exec/multi_cast_data_streamer.cpp
  be/src/pipeline/exec/multi_cast_data_streamer.h
Labels: approved, reviewed

#34721 [improve](txn insert) Txn load support cloud mode
  cloud/src/common/bvars.cpp
  cloud/src/common/bvars.h
  cloud/src/meta-service/meta_service.h
  cloud/src/meta-service/meta_service_txn.cpp
  cloud/src/recycler/recycler.cpp
  cloud/test/meta_service_test.cpp
  cloud/test/recycler_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/cloud/rpc/MetaServiceClient.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/rpc/MetaServiceProxy.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/transaction/CloudGlobalTransactionMgr.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/TransactionEntry.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/TransactionState.java
  gensrc/proto/cloud.proto
  regression-test/data/insert_p0/txn_insert.out
  regression-test/data/insert_p0/txn_insert_inject_case.out
  regression-test/suites/insert_p0/txn_insert.groovy
  regression-test/suites/insert_p0/txn_insert_concurrent_insert.groovy
  regression-test/suites/insert_p0/txn_insert_inject_case.groovy
  regression-test/suites/insert_p0/txn_insert_with_schema_change.groovy
Labels: approved, reviewed, meta-change

#35890 [fix](storage_policy) fix cannot cancel a partition's storage policy
  fe/fe-core/src/main/java/org/apache/doris/alter/Alter.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/PropertyAnalyzer.java
  regression-test/suites/cold_heat_separation_p2/test_show_storage_policy_using.groovy
Labels: approved, reviewed

#35885 [fix](coldhot) fix cannot cancel storage policy of partition
  fe/fe-core/src/main/java/org/apache/doris/alter/Alter.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/PropertyAnalyzer.java
  regression-test/suites/cold_heat_separation_p2/test_show_storage_policy_using.groovy
Labels: kind/test, approved, reviewed

#35477 [fix](datetime) Fix date floor functions overflow
  be/src/vec/data_types/data_type_number.h
  be/src/vec/data_types/data_type_time_v2.cpp
  be/src/vec/exec/format/column_type_convert.h
  be/src/vec/functions/function.h
  be/src/vec/functions/function_datetime_floor_ceil.cpp
  be/src/vec/functions/function_timestamp.cpp
  be/src/vec/runtime/vdatetime_value.cpp
  be/src/vec/runtime/vdatetime_value.h
  be/test/olap/delta_writer_test.cpp
  be/test/olap/segment_cache_test.cpp
  be/test/vec/aggregate_functions/vec_sequence_match_test.cpp
  be/test/vec/aggregate_functions/vec_window_funnel_test.cpp
  be/test/vec/exprs/vexpr_test.cpp
  be/test/vec/runtime/vdatetime_value_test.cpp
  regression-test/data/query_p0/sql_functions/datetime_functions/test_date_floor_ceil.out
  regression-test/suites/query_p0/sql_functions/datetime_functions/test_date_floor_ceil.groovy
Labels: approved, reviewed

#35888 [refactor](coordinator) remove non pipeline code from coordinator
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
Labels: approved, reviewed

#35916 [enhance](recycler) Don't do delete request when encountering empty objs and log more error msg
  cloud/src/recycler/azure_obj_client.cpp
  cloud/src/recycler/s3_obj_client.cpp
Labels: approved, reviewed

#35847 [enhancement](regression-test) modify a value type tests
  regression-test/data/schema_change_p0/test_unique_model_schema_value_change.out
  regression-test/suites/schema_change_p0/test_unique_model_schema_value_change.groovy
Labels: approved, reviewed

#35905 [fix](cloud) ignore black list in cloud mode
  fe/fe-core/src/main/java/org/apache/doris/qe/SimpleScheduler.java
Labels: approved, reviewed

#35637 [Bug](function) Fix function for cast string as date/datetime
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/DateLiteral.java
  regression-test/data/correctness_p0/test_cast_date_decimal.out
  regression-test/suites/correctness_p0/test_cast_date_decimal.groovy
Labels: approved, reviewed

#35873 [tools] update tools schema
  tools/tpcds-tools/ddl/create-tpcds-tables-sf1.sql
  tools/tpcds-tools/ddl/create-tpcds-tables-sf100.sql
  tools/tpcds-tools/ddl/create-tpcds-tables-sf1000.sql
  tools/tpcds-tools/ddl/create-tpcds-tables-sf10000.sql
Labels: approved, reviewed, dev/2.1.x

#35850 [enhance](BE) Avoid memcpy in `OlapMeta::iterate`
  be/src/http/action/restore_tablet_action.cpp
  be/src/olap/data_dir.cpp
  be/src/olap/olap_meta.cpp
  be/src/olap/olap_meta.h
  be/src/olap/rowset/rowset_meta.cpp
  be/src/olap/rowset/rowset_meta.h
  be/src/olap/rowset/rowset_meta_manager.cpp
  be/src/olap/rowset/rowset_meta_manager.h
  be/src/olap/storage_engine.cpp
  be/src/olap/tablet.cpp
  be/src/olap/tablet_manager.cpp
  be/src/olap/tablet_manager.h
  be/src/olap/tablet_meta.cpp
  be/src/olap/tablet_meta.h
  be/src/olap/tablet_meta_manager.cpp
  be/src/olap/tablet_meta_manager.h
  be/src/olap/utils.h
  be/test/olap/olap_meta_test.cpp
  be/test/olap/tablet_meta_manager_test.cpp
Labels: approved, reviewed

#35843 [feat](nereids) add nereids profile
  fe/fe-core/src/main/java/org/apache/doris/common/profile/SummaryProfile.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/NereidsPlanner.java
Labels: approved, reviewed, area/nereids

#35900 [refactor](pipeline) Refactor non-pipeline code structure
  be/src/pipeline/common/agg_utils.h
  be/src/pipeline/common/data_gen_functions/vdata_gen_function_inf.h
  be/src/pipeline/common/data_gen_functions/vnumbers_tvf.cpp
  be/src/pipeline/common/data_gen_functions/vnumbers_tvf.h
  be/src/pipeline/common/join_utils.h
  be/src/pipeline/common/runtime_filter_consumer.cpp
  be/src/pipeline/common/runtime_filter_consumer.h
  be/src/pipeline/dependency.cpp
  be/src/pipeline/dependency.h
  be/src/pipeline/exec/aggregation_sink_operator.cpp
  be/src/pipeline/exec/aggregation_sink_operator.h
  be/src/pipeline/exec/aggregation_source_operator.cpp
  be/src/pipeline/exec/analytic_sink_operator.cpp
  be/src/pipeline/exec/analytic_source_operator.cpp
  be/src/pipeline/exec/datagen_operator.cpp
  be/src/pipeline/exec/datagen_operator.h
  be/src/pipeline/exec/distinct_streaming_aggregation_operator.cpp
  be/src/pipeline/exec/distinct_streaming_aggregation_operator.h
  be/src/pipeline/exec/es_scan_operator.cpp
  be/src/pipeline/exec/hashjoin_build_sink.cpp
  be/src/pipeline/exec/hashjoin_build_sink.h
  be/src/pipeline/exec/hashjoin_probe_operator.cpp
  be/src/pipeline/exec/hashjoin_probe_operator.h
  be/src/pipeline/exec/join/cross_join_impl.cpp
  be/src/pipeline/exec/join/full_outer_join_impl.cpp
  be/src/pipeline/exec/join/inner_join_impl.cpp
  be/src/pipeline/exec/join/join_op.h
  be/src/pipeline/exec/join/left_anti_join_impl.cpp
  be/src/pipeline/exec/join/left_outer_join_impl.cpp
  be/src/pipeline/exec/join/left_semi_join_impl.cpp
  be/src/pipeline/exec/join/null_aware_left_anti_join_impl.cpp
  be/src/pipeline/exec/join/null_aware_left_semi_join_impl.cpp
  be/src/pipeline/exec/join/process_hash_table_probe.h
  be/src/pipeline/exec/join/process_hash_table_probe_impl.h
  be/src/pipeline/exec/join/right_anti_join_impl.cpp
  be/src/pipeline/exec/join/right_outer_join_impl.cpp
  be/src/pipeline/exec/join/right_semi_join_impl.cpp
  be/src/pipeline/exec/multi_cast_data_stream_source.cpp
  be/src/pipeline/exec/multi_cast_data_stream_source.h
  be/src/pipeline/exec/olap_scan_operator.cpp
  be/src/pipeline/exec/partitioned_aggregation_sink_operator.h
  be/src/pipeline/exec/scan_operator.cpp
  be/src/pipeline/exec/scan_operator.h
  be/src/pipeline/exec/set_source_operator.cpp
  be/src/pipeline/exec/set_source_operator.h
  be/src/pipeline/exec/streaming_aggregation_operator.cpp
  be/src/pipeline/exec/streaming_aggregation_operator.h
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/query_context.cpp
  be/src/runtime/query_context.h
  be/src/vec/common/hash_table/hash_map_context.h
  be/src/vec/common/hash_table/hash_table_set_build.h
  be/src/vec/exec/join/vacquire_list.hpp
  be/src/vec/exec/join/vhash_join_node.h
  be/src/vec/exec/scan/vscan_node.h
  be/src/vec/exec/vaggregation_node.h
Labels: approved, reviewed

#35682 [feature](pipelline)add local merge sort exchaner
  be/src/pipeline/dependency.h
  be/src/pipeline/exec/exchange_sink_operator.cpp
  be/src/pipeline/exec/exchange_sink_operator.h
  be/src/pipeline/exec/operator.h
  be/src/pipeline/exec/sort_source_operator.cpp
  be/src/pipeline/exec/sort_source_operator.h
  be/src/pipeline/local_exchange/local_exchange_sink_operator.cpp
  be/src/pipeline/local_exchange/local_exchange_sink_operator.h
  be/src/pipeline/local_exchange/local_exchange_source_operator.h
  be/src/pipeline/local_exchange/local_exchanger.cpp
  be/src/pipeline/local_exchange/local_exchanger.h
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/runtime/runtime_state.h
  be/src/vec/core/sort_cursor.h
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  gensrc/thrift/PaloInternalService.thrift
Labels: approved, reviewed, meta-change

#35909 [Fix](inverted index) fix index_id wrong size in V2
  be/src/olap/rowset/segment_v2/inverted_index_desc.cpp
  be/src/olap/rowset/segment_v2/inverted_index_desc.h
  be/src/olap/rowset/segment_v2/inverted_index_file_reader.cpp
  be/src/olap/rowset/segment_v2/inverted_index_file_writer.cpp
Labels: approved, reviewed

#35556 [enhancement](export)export job for olap table will only hit the base index, so skip other tablets of rollup index when do splitTablets
  fe/fe-core/src/main/java/org/apache/doris/load/ExportJob.java
  regression-test/data/export_p0/test_export_table_with_materialized_view.out
  regression-test/suites/export_p0/test_export_table_with_materialized_view.groovy
Labels: approved, reviewed

#35863 [opt](Nereids) use date signature for date arithmetic as far as possible
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/ComputeSignatureForDateArithmetic.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/DaysAdd.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/DaysSub.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/MonthsAdd.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/MonthsSub.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/WeeksAdd.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/WeeksSub.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/YearsAdd.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/YearsSub.java
  fe/fe-core/src/test/java/org/apache/doris/planner/ConstantExpressTest.java
  regression-test/data/nereids_p0/expression/fold_constant/fold_constant_by_fe.out
  regression-test/data/nereids_syntax_p0/test_date_add.out
  regression-test/data/nereids_syntax_p0/test_date_sub.out
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x

#35924 [fix](statistics)Fix partition table health rate evaluation bug.
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisInfo.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisManager.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/BaseAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/TableStatsMeta.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/util/StatisticsUtil.java
Labels: approved, reviewed

#35936 [minor](log) Add debug log in Coordinator
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
Labels: approved, reviewed

#35837 [FIX] Pick array inverted index bugfix
  be/src/exec/olap_common.h
  be/src/exec/olap_utils.h
  be/src/olap/match_predicate.cpp
  be/src/olap/rowset/segment_v2/inverted_index_writer.cpp
  be/src/vec/functions/match.cpp
  be/src/vec/functions/match.h
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisLexer.g4
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/IndexDef.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/MatchPredicate.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/IndexDefinition.java
  fe/fe-core/src/main/jflex/sql_scanner.flex
  gensrc/thrift/Opcodes.thrift
  regression-test/data/inverted_index_p0/test_array_contains_with_inverted_index.out
  regression-test/data/inverted_index_p0/test_array_inverted_index/sql/insert_with_query.out
  regression-test/data/inverted_index_p0/test_array_with_inverted_index_all_type.json
  regression-test/data/inverted_index_p0/test_array_with_inverted_index_all_type.out
  regression-test/data/inverted_index_p0/test_array_with_inverted_index_all_type_agg.json
  regression-test/data/inverted_index_p2/test_array_with_large_dataset.out
  regression-test/suites/datatype_p0/nested_types/query/array_functions/test_array_functions_array_intersect_sort.groovy
  regression-test/suites/inverted_index_p0/test_array_contains_with_inverted_index.groovy
  regression-test/suites/inverted_index_p0/test_array_index.groovy
  regression-test/suites/inverted_index_p0/test_array_inverted_index/load.groovy
  regression-test/suites/inverted_index_p0/test_array_inverted_index/sql/insert_with_query.sql
  regression-test/suites/inverted_index_p0/test_array_with_inverted_index_all_type.groovy
  regression-test/suites/inverted_index_p2/test_array_with_large_dataset.groovy
Labels: approved, reviewed, meta-change

#35866 [improve](cloud) Add more cost time log for sync_rowset while calculaing delete bitmap
  be/src/cloud/cloud_engine_calc_delete_bitmap_task.cpp
  be/src/cloud/cloud_meta_mgr.cpp
  be/src/olap/base_tablet.cpp
Labels: approved, reviewed

#35910 [chore](ci) add required check for branch-2.1
  .asf.yaml
  .github/workflows/comment-to-trigger-teamcity.yml
Labels: approved, reviewed

#35938 [fix](keyword) let some keyword be non-reserved between old parser and new parser
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisLexer.g4
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
Labels: approved, reviewed, dev/2.1.x

#35773 [feat](Nereids): Optimize Join Penalty Calculation Based on Build Side Data Volume
  fe/fe-core/src/main/java/org/apache/doris/nereids/cost/CostModelV1.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/Statistics.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/cost/CostModelV1Test.java
  regression-test/data/nereids_rules_p0/eager_aggregate/basic.out
  regression-test/data/nereids_rules_p0/eager_aggregate/push_down_count_through_join.out
  regression-test/data/nereids_rules_p0/eager_aggregate/push_down_count_through_join_one_side.out
  regression-test/data/nereids_rules_p0/eager_aggregate/push_down_max_through_join.out
  regression-test/data/nereids_rules_p0/eager_aggregate/push_down_min_through_join.out
  regression-test/data/nereids_rules_p0/eager_aggregate/push_down_sum_through_join.out
  regression-test/data/nereids_rules_p0/eager_aggregate/push_down_sum_through_join_one_side.out
  regression-test/data/nereids_rules_p0/eliminate_outer_join/eliminate_outer_join.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/shape/query4.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/shape/query74.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/noStatsRfPrune/query95.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/no_stats_shape/query95.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/rf_prune/query4.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/rf_prune/query74.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query4.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query74.out
Labels: approved, reviewed, dev/2.1.x

#35884 [fix](functions) fix be crash for function random_bytes and mark_first/last_n
  be/src/vec/functions/function_string.h
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/MaskFirstN.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/MaskLastN.java
  regression-test/suites/correctness_p0/test_mask_function.groovy
  regression-test/suites/nereids_function_p0/scalar_function/R.groovy
Labels: approved, reviewed, p0_c, dev/2.0.x, dev/2.1.x

#32523 [Enhancement](Nereids) Nereids supports group_commit with insert
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/LoadAction.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/PhysicalPlanTranslator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/GroupCommitInsertExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/GroupCommitInserter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/InsertIntoTableCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/InsertUtils.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/OlapInsertExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/planner/GroupCommitPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContext.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  regression-test/data/insert_p0/insert_group_commit_into_max_filter_ratio.out
  regression-test/suites/insert_p0/insert_group_commit_into.groovy
  regression-test/suites/insert_p0/insert_group_commit_into_max_filter_ratio.groovy
  regression-test/suites/insert_p0/insert_group_commit_into_unique.groovy
  regression-test/suites/insert_p0/insert_group_commit_into_unique_sync_mode.groovy
  regression-test/suites/insert_p0/insert_group_commit_with_exception.groovy
  regression-test/suites/insert_p0/insert_group_commit_with_large_data.groovy
  regression-test/suites/insert_p0/insert_with_null.groovy
  regression-test/suites/insert_p0/test_group_commit_data_bytes_property.groovy
  regression-test/suites/insert_p0/test_group_commit_interval_ms_property.groovy
Labels: approved, reviewed

#35902 [opt](variable) add a new variable tag REMOVED
  fe/fe-common/src/main/java/org/apache/doris/common/VariableAnnotation.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/qe/VariableMgr.java
  regression-test/suites/correctness/test_removed_session_var.groovy
Labels: approved, reviewed, dev/2.1.x

#35931 [Bug](function) Fix function for cast string as date/datetime (#35637)
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/DateLiteral.java
  regression-test/data/correctness_p0/test_cast_date_decimal.out
  regression-test/suites/correctness_p0/test_cast_date_decimal.groovy
Labels: kind/test, area/nereids

#35303 [Update](inverted index) set default inverted index storage format to v2
  be/src/olap/rowset/segment_v2/inverted_index_desc.cpp
  be/src/olap/rowset/segment_v2/inverted_index_desc.h
  be/src/olap/rowset/segment_v2/inverted_index_file_reader.cpp
  be/src/olap/rowset/segment_v2/inverted_index_file_writer.cpp
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/CreateTableAsSelectStmtTest.java
  regression-test/data/query_p0/system/test_table_options.out
  regression-test/data/show_p0/test_show_create_table_and_views.out
  regression-test/data/show_p0/test_show_create_table_and_views_nereids.out
  regression-test/suites/fault_injection_p0/test_calc_crc_fault_injection.groovy
Labels: approved, reviewed, not-merge/2.1

#35861 [Feature](information-schema) add SCHEMA_VERSION into information_schema.rowsets
  be/src/exec/schema_scanner/schema_rowsets_scanner.cpp
  fe/fe-core/src/main/java/org/apache/doris/catalog/SchemaTable.java
  regression-test/data/query_p0/system/test_query_sys_rowsets.out
Labels: reviewed

#35871 [enhancement](Nereids) support 4 phases distinct aggregate with full distribution
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/ChildrenPropertiesRegulator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/implementation/AggregateStrategies.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/algebra/Aggregate.java
  regression-test/data/nereids_p0/aggregate/aggregate.out
  regression-test/suites/nereids_p0/aggregate/aggregate.groovy
  regression-test/suites/nereids_syntax_p0/agg_4_phase.groovy
Labels: approved, reviewed, usercase, dev/2.1.x

#35431 [feature](tvf) support max_filter_ratio
  fe/fe-core/src/main/java/org/apache/doris/cloud/CacheHotspotManagerUtils.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/AbstractInsertExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/planner/GroupCommitPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/util/StatisticsUtil.java
  regression-test/data/external_table_p0/tvf/test_hdfs_tvf.out
  regression-test/suites/external_table_p0/tvf/test_hdfs_tvf.groovy
Labels: approved, reviewed, dev/2.1.x

#35935 [feature](Nereids) support select ALL
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  regression-test/suites/nereids_syntax_p0/select_const.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x

#35833 [bugfix](hive)fix the error message when creating hive table
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/PartitionTableInfo.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/CreateTableCommandTest.java
Labels: approved, reviewed, dev/2.1.x

#35628 [Feature](agg-state) OLAP_FIELD_TYPE_AGG_STATE support more serialized_type
  be/src/olap/field.h
  be/src/olap/rowset/segment_v2/binary_plain_page.h
  be/src/olap/rowset/segment_v2/column_reader.cpp
  be/src/olap/rowset/segment_v2/column_reader.h
  be/src/olap/rowset/segment_v2/column_writer.cpp
  be/src/olap/rowset/segment_v2/column_writer.h
  be/src/olap/rowset/segment_v2/segment.cpp
  be/src/olap/rowset/segment_v2/segment_writer.cpp
  be/src/olap/tablet_schema.h
  be/src/olap/types.cpp
  be/src/vec/data_types/data_type_factory.cpp
  be/src/vec/olap/olap_data_convertor.cpp
  be/src/vec/olap/olap_data_convertor.h
  gensrc/proto/segment_v2.proto
  regression-test/data/mv_p0/agg_state/diffrent_serialize/diffrent_serialize.out
  regression-test/suites/mv_p0/agg_state/diffrent_serialize/diffrent_serialize.groovy
Labels: approved, reviewed, meta-change

#35913 [fix](scan) In-predicate should not be pushed down for non-key column
  be/src/pipeline/exec/scan_operator.cpp
  regression-test/data/correctness_p0/test_in_predicate_push_down.out
  regression-test/suites/correctness_p0/test_in_predicate_push_down.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x

#35939 [Update](regression) refine case for inverted index show data
  regression-test/suites/inverted_index_p0/test_show_data.groovy
Labels: approved, reviewed

#35892 [build](docker) add repo for new version of git
  docker/compilation/Dockerfile
Labels: approved, reviewed, dev/2.1.x

#35914 [fix](scan) In-predicate should not be pushed down for non-key column
  be/src/vec/exec/scan/vscan_node.cpp
  regression-test/data/correctness_p0/test_in_predicate_push_down.out
  regression-test/suites/correctness_p0/test_in_predicate_push_down.groovy
Labels: kind/test

#35921 [fix](proc) fix keyword case sensitive issue for stmt show_frontends_disks
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowFrontendsStmt.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/FrontendsProcNode.java
  regression-test/suites/node_p0/test_frontend.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x

#35943 [refactor](pipeline) Delete pipeline option
  be/src/exprs/runtime_filter.cpp
  be/src/exprs/runtime_filter.h
  be/src/pipeline/exec/aggregation_sink_operator.cpp
  be/src/pipeline/exec/streaming_aggregation_operator.cpp
  be/src/pipeline/local_exchange/local_exchanger.cpp
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/query_context.cpp
  be/src/runtime/query_context.h
  be/src/runtime/runtime_filter_mgr.cpp
  be/src/runtime/runtime_filter_mgr.h
  be/src/runtime/runtime_state.h
  be/src/vec/runtime/vdata_stream_recvr.cpp
  be/src/vec/runtime/vdata_stream_recvr.h
  be/src/vec/runtime/vsorted_run_merger.cpp
  be/src/vec/runtime/vsorted_run_merger.h
Labels: approved, reviewed

#35901 [fix](routine-load) dealing with the high watermark of Kafka may fallback
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/KafkaRoutineLoadJob.java
Labels: approved, reviewed

#35975 [bugfix](hive)fix the error message when creating hive table for 2.1
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/PartitionTableInfo.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/CreateTableCommandTest.java
Labels: approved, reviewed

#35831 [bugfix](iceberg)fix datetime conversion error for 2.0
  fe/fe-core/src/main/java/org/apache/doris/analysis/DateLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/external/iceberg/util/IcebergUtils.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/DateLiteralTest.java
Labels: area/planner

#35960 [Chore](scan) normalize push down logic for tablet reader predicates
  be/src/olap/tablet_reader.cpp
Labels: approved, reviewed

#35964 [fix](nereids)should not push down constant output expr in window expression
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/ExtractAndNormalizeWindowExpression.java
Labels: area/nereids

#35961 [fix](nereids)should not push down constant output expr in window expression
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/ExtractAndNormalizeWindowExpression.java
  regression-test/suites/nereids_p0/aggregate/agg_window_project.groovy
Labels: kind/test, area/nereids

#35982 [fix](jdbc catalog) fix mariadb test conf port
  regression-test/pipeline/external/conf/regression-conf.groovy
Labels: approved, reviewed

#35899 [fix](Nereids) not do distinct when aggregate with distinct project
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/PhysicalPlanTranslator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/BindExpression.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/FillUpMissingSlots.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/NormalizeRepeat.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/join/OuterJoinLAsscomProject.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/QueryColumnCollector.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/AdjustPreAggStatus.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/MergeAggregate.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/mv/SelectMaterializedIndexWithAggregate.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/TreeNode.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/ComputeSignatureHelper.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/udf/AliasUdfBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/algebra/Repeat.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/DeleteFromCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/BatchInsertIntoTableCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/GroupCommitInsertExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/InsertIntoTableCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/InsertOverwriteTableCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalRepeat.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/ExpressionUtils.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/PlanUtils.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/mv/SelectMvIndexTest.java
  regression-test/data/nereids_p0/aggregate/agg_with_distinct_project.out
  regression-test/suites/nereids_p0/aggregate/agg_with_distinct_project.groovy
Labels: approved, reviewed, p0_w, dev/2.0.x, dev/2.1.x

#35937 [feature](Nereids) support cast to unsigned / signed
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/types/BigIntType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/types/DataType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/types/LargeIntType.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/types/DataTypeTest.java
  regression-test/suites/nereids_syntax_p0/cast.groovy
  regression-test/suites/types_p0/unsigned/test_unsigned_int_compatibility.groovy
Labels: approved, reviewed, kind/behavior-changed, not-merge/2.1

#35855 [fix](DDL) not set table type as default comment when create table
  fe/fe-core/src/main/java/org/apache/doris/catalog/Table.java
  fe/fe-core/src/test/java/org/apache/doris/alter/AlterTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/CreateTableAsSelectStmtTest.java
  regression-test/data/datatype_p0/scalar_types/get_assignment_compatible_type.out
  regression-test/data/ddl_p0/test_create_view.out
  regression-test/data/ddl_p0/test_create_view_nereids.out
  regression-test/data/show_p0/test_show_create_table_and_views.out
  regression-test/data/show_p0/test_show_create_table_and_views_nereids.out
  regression-test/data/view_p0/create_view_star_except_and_cast_to_sql.out
Labels: approved, reviewed, kind/behavior-changed, dev/2.0.x, dev/2.1.x

#35942 [opt](log) refine the BE logger
  be/CMakeLists.txt
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/common/logconfig.cpp
  bin/start_be.sh
  regression-test/framework/pom.xml
Labels: approved, reviewed, kind/behavior-changed, dev/2.1.x

#35841 [Chore](type) remove duplicate uint128/int128/uint256 defines
  be/src/gutil/CMakeLists.txt
  be/src/gutil/endian.h
  be/src/gutil/hash/city.cc
  be/src/gutil/hash/city.h
  be/src/gutil/hash/hash.cc
  be/src/gutil/hash/hash.h
  be/src/gutil/hash/hash128to64.h
  be/src/gutil/hash/legacy_hash.h
  be/src/gutil/hash/string_hash.h
  be/src/gutil/int128.cc
  be/src/gutil/int128.h
  be/src/gutil/strings/numbers.cc
  be/src/gutil/strings/numbers.h
  be/src/gutil/strings/stringpiece.cc
  be/src/gutil/strings/stringpiece.h
  be/src/io/cache/file_cache_common.h
  be/src/io/fs/hdfs_file_system.cpp
  be/src/io/hdfs_util.cpp
  be/src/olap/rowset/segment_v2/binary_dict_page.h
  be/src/olap/rowset/segment_v2/bloom_filter_index_writer.cpp
  be/src/olap/rowset/segment_v2/page_io.h
  be/src/olap/rowset/segment_v2/page_pointer.h
  be/src/olap/schema_change.cpp
  be/src/olap/single_replica_compaction.cpp
  be/src/olap/tablet.cpp
  be/src/olap/task/engine_clone_task.cpp
  be/src/service/point_query_executor.h
  be/src/util/hash_util.hpp
  be/src/util/lru_multi_cache.h
  be/src/util/lru_multi_cache.inline.h
  be/src/util/path_util.cpp
  be/src/util/path_util.h
  be/src/util/s3_util.h
  be/src/util/trace.h
  be/src/vec/common/hash_table/hash.h
  be/src/vec/common/hash_table/string_hash_map.h
  be/src/vec/common/hash_table/string_hash_table.h
  be/src/vec/common/string_ref.h
  be/src/vec/common/uint128.h
  be/src/vec/core/wide_integer.h
  be/src/vec/data_types/convert_field_to_type.cpp
  be/src/vec/json/path_in_data.cpp
  be/test/util/path_util_test.cpp
  regression-test/data/nereids_function_p0/scalar_function/Array.out
  regression-test/suites/nereids_function_p0/scalar_function/Array.groovy
Labels: approved, reviewed

#35941 [fix](fe) avoid setting the value of batch_size excessively high
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
Labels: approved, reviewed

#35974 [Chore](log) do not get stacktrace when error_code's stacktrace is false
  be/src/agent/task_worker_pool.cpp
  be/src/common/exception.cpp
  be/src/common/exception.h
  be/src/olap/rowset/segment_v2/segment_writer.cpp
  be/src/olap/rowset/segment_v2/vertical_segment_writer.cpp
Labels: approved, reviewed

#35729 [fix](mtmv)fix mtmv show partition error when base table dropped
  fe/fe-core/src/main/java/org/apache/doris/common/proc/PartitionsProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVPartitionUtil.java
  regression-test/suites/mtmv_p0/test_show_partitions_mtmv.groovy
Labels: approved, reviewed, dev/2.1.x

#35919 [fix](proc) fix keyword case sensitive issue for stmt show_frontends_disks
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowFrontendsStmt.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/FrontendsProcNode.java
  regression-test/suites/node_p0/test_frontend.groovy
Labels: approved, reviewed

#35500 [fix](Nereids): add be test number in some tests
  regression-test/data/nereids_rules_p0/eager_aggregate/push_down_count_through_join_one_side.out
  regression-test/data/nereids_rules_p0/eliminate_outer_join/eliminate_outer_join.out
  regression-test/data/nereids_rules_p0/push_down_top_n/push_down_top_n_distinct_through_join.out
  regression-test/suites/nereids_p0/hint/test_distribute.groovy
  regression-test/suites/nereids_rules_p0/eager_aggregate/push_down_count_through_join_one_side.groovy
  regression-test/suites/nereids_rules_p0/eliminate_gby_key/eliminate_gby_key.groovy
  regression-test/suites/nereids_rules_p0/eliminate_outer_join/eliminate_outer_join.groovy
  regression-test/suites/nereids_rules_p0/filter_push_down/push_down_alias_through_join.groovy
  regression-test/suites/nereids_rules_p0/push_down_top_n/push_down_top_n_distinct_through_join.groovy
  regression-test/suites/performance_p0/redundant_conjuncts.groovy
  regression-test/suites/query_p0/join/test_join.groovy
Labels: approved, reviewed, dev/2.1.x

#35973 [minor](log) Refactor some warning logs
  be/src/runtime/fragment_mgr.cpp
  be/src/vec/runtime/vdata_stream_mgr.cpp
  be/src/vec/sink/vdata_stream_sender.cpp
Labels: approved, reviewed

#35971 [FIX](cases)fix cases for test_ip_in_inverted_index
  regression-test/data/datatype_p0/ip/test_ip_in_inverted_index.out
  regression-test/suites/datatype_p0/ip/test_ip_in_inverted_index.groovy
Labels: reviewed

#35958 [fix](fe) Fix compatibility issues with old cloud code
  fe/fe-core/src/main/java/org/apache/doris/persist/gson/GsonUtils.java
  fe/fe-core/src/main/java/org/apache/doris/persist/gson/RuntimeTypeAdapterFactory.java
Labels: approved, reviewed
