Repository apache/doris, pull requests merged in 2024-04, with the labels that each got.

#32673 [featrue](expr) support common subexpression elimination be part
  be/src/exec/exec_node.cpp
  be/src/exec/exec_node.h
  be/src/pipeline/pipeline_x/operator.cpp
  be/src/pipeline/pipeline_x/operator.h
  be/src/vec/core/block.cpp
  be/src/vec/core/block.h
  be/src/vec/exec/scan/vscanner.cpp
  be/src/vec/exec/scan/vscanner.h
  gensrc/thrift/PlanNodes.thrift
Labels: approved, reviewed, meta-change

#32884 [Bug](Variant) forbit variant column with filter, group by or order by
  fe/fe-core/src/main/java/org/apache/doris/nereids/types/DataType.java
  regression-test/suites/variant_p0/load.groovy
Labels: approved, reviewed, variant, dev/2.1.1-merged

#33077 [bugfix](asyncwriter) async writer's lock should not include finish or close method
  be/src/vec/sink/writer/async_result_writer.cpp
Labels: approved, reviewed

#33036 [Chore](column) remove ColumnVectorHelper
  be/src/vec/columns/column_decimal.h
  be/src/vec/columns/column_vector.h
  be/src/vec/columns/column_vector_helper.h
  be/src/vec/common/hash_table/hash_map_context.h
  be/src/vec/exec/vaggregation_node.h
Labels: approved, reviewed

#33031 [fix](avro) avoid BE crash if avro scanner's dependency jars is mssing
  be/src/service/internal_service.cpp
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
  regression-test/suites/datatype_p0/bitmap/test_bitmap_int.groovy
  regression-test/suites/datatype_p0/nested_types/query/test_nestedtypes_insert_into_select.groovy
  regression-test/suites/demo_p0/test_action.groovy
  regression-test/suites/nereids_p0/insert_into_table/update_on_current_timestamp.groovy
  regression-test/suites/query_p0/join/test_join2.groovy
Labels: approved, reviewed, p0_c, dev/2.0.x

#32737 [Enhancement](partition) Refine some auto partition behaviours
  be/src/exec/tablet_info.cpp
  be/src/vec/sink/vrow_distribution.cpp
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/ListPartitionDesc.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/PartitionDesc.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/RangePartitionDesc.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/PartitionTableInfo.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/CreateTableInfo.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/RangePartitionPruneTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/exploration/mv/MaterializedViewUtilsTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/CreateTableCommandTest.java
  fe/fe-core/src/test/java/org/apache/doris/service/FrontendServiceImplTest.java
  regression-test/suites/nereids_rules_p0/mv/dimension/dimension_1.groovy
  regression-test/suites/nereids_rules_p0/mv/dimension/dimension_2_3.groovy
  regression-test/suites/nereids_rules_p0/mv/dimension/dimension_2_4.groovy
  regression-test/suites/nereids_rules_p0/mv/dimension/dimension_2_5.groovy
  regression-test/suites/nereids_rules_p0/mv/dimension/dimension_2_6.groovy
  regression-test/suites/nereids_rules_p0/mv/dimension/dimension_2_full_join.groovy
  regression-test/suites/nereids_rules_p0/mv/dimension/dimension_2_inner_join.groovy
  regression-test/suites/nereids_rules_p0/mv/dimension/dimension_2_left_anti_join.groovy
  regression-test/suites/nereids_rules_p0/mv/dimension/dimension_2_left_join.groovy
  regression-test/suites/nereids_rules_p0/mv/dimension/dimension_2_left_semi_join.groovy
  regression-test/suites/nereids_rules_p0/mv/dimension/dimension_2_right_anti_join.groovy
  regression-test/suites/nereids_rules_p0/mv/dimension/dimension_2_right_join.groovy
  regression-test/suites/nereids_rules_p0/mv/dimension/dimension_2_right_semi_join.groovy
  regression-test/suites/nereids_rules_p0/mv/dimension_2_join_agg/dimension_2_join_agg.groovy
  regression-test/suites/nereids_rules_p0/mv/dimension_equal/filter_equal_or_notequal.groovy
  regression-test/suites/nereids_rules_p0/mv/increment_create/cross_join_range_date_increment_create.groovy
  regression-test/suites/nereids_rules_p0/mv/increment_create/full_join_range_date_increment_create.groovy
  regression-test/suites/nereids_rules_p0/mv/increment_create/inner_join_range_date_increment_create.groovy
  regression-test/suites/nereids_rules_p0/mv/increment_create/left_anti_join_range_date_increment_create.groovy
  regression-test/suites/nereids_rules_p0/mv/increment_create/left_join_range_date_increment_create.groovy
  regression-test/suites/nereids_rules_p0/mv/increment_create/left_semi_join_range_date_increment_create.groovy
  regression-test/suites/nereids_rules_p0/mv/increment_create/right_anti_join_range_date_increment_create.groovy
  regression-test/suites/nereids_rules_p0/mv/increment_create/right_join_range_date_increment_create.groovy
  regression-test/suites/nereids_rules_p0/mv/increment_create/right_semi_join_range_date_increment_create.groovy
  regression-test/suites/nereids_rules_p0/mv/increment_create/self_conn_range_date_increment_create.groovy
  regression-test/suites/nereids_rules_p0/mv/negative/negative_test.groovy
  regression-test/suites/partition_p0/auto_partition/test_auto_partition_behavior.groovy
  regression-test/suites/partition_p0/auto_partition/test_auto_partition_load.groovy
  regression-test/suites/partition_p0/auto_partition/test_auto_range_partition.groovy
  regression-test/suites/partition_p1/auto_partition/ddl/concurrent.sql
  regression-test/suites/partition_p1/auto_partition/ddl/stress_destination.sql
  regression-test/suites/partition_p2/auto_partition/ddl/small_data_high_concurrrent_load.sql
  regression-test/suites/partition_p2/auto_partition/ddl/stream_load_range_test_table.sql
Labels: approved, reviewed, kind/behavior-changed

#33050 [feature](local-tvf) support local tvf on shared storage
  fe/fe-core/src/main/java/org/apache/doris/datasource/tvf/source/TVFScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/system/BeSelectionPolicy.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/LocalTableValuedFunction.java
Labels: approved, reviewed

#32946 [feature](profile) make WaitForLocalExchangeBuffer timer merge
  be/src/pipeline/exec/exchange_sink_operator.cpp
Labels: approved, reviewed

#32925 [feature](merge-cloud) Add tablet rebalance run in cloud
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/catalog/CloudEnv.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/catalog/CloudTabletRebalancer.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/datasource/CloudInternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/persist/UpdateCloudReplicaInfo.java
  fe/fe-core/src/main/java/org/apache/doris/journal/JournalEntity.java
  fe/fe-core/src/main/java/org/apache/doris/persist/EditLog.java
Labels: approved, reviewed, meta-change

#32912 [Feature](materialized-view) support ignore not slot is null when count(slot) not has key in mv
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/mv/AbstractSelectMaterializedIndexRule.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/mv/SelectMaterializedIndexWithAggregate.java
  regression-test/data/mv_p0/mv_ignore_predicate/mv_ignore_predicate.out
  regression-test/suites/mv_p0/mv_ignore_predicate/mv_ignore_predicate.groovy
  regression-test/suites/mv_p0/test_dup_mv_repeat/test_dup_mv_repeat.groovy
Labels: approved, reviewed

#32853 [Fix](nereids) fix qualifier problem that affects delete stmt in another catalog
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/BindRelation.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalCatalogRelation.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalCatalogRelation.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/analysis/BindRelationTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/ColumnPruningTest.java
Labels: approved, reviewed, dev/2.0.x

#32993 [Fix](test) add sync to ensure data synchronization in test_set_operater
  regression-test/suites/query_p0/operator/test_set_operator.groovy
Labels: approved, reviewed, dev/2.0.x

#33088 [Chore](runtime-filter) add check is broadcast on nlj
  be/src/pipeline/exec/nested_loop_join_build_operator.cpp
  fe/fe-core/src/main/java/org/apache/doris/planner/RuntimeFilter.java
Labels: approved, reviewed

#33075 [improvement](spill) avoid spill if memory is enough
  be/src/pipeline/exec/partitioned_aggregation_sink_operator.cpp
  be/src/pipeline/exec/partitioned_aggregation_sink_operator.h
  be/src/pipeline/exec/partitioned_aggregation_source_operator.cpp
  be/src/pipeline/exec/partitioned_aggregation_source_operator.h
  be/src/pipeline/exec/spill_sort_sink_operator.cpp
  be/src/pipeline/exec/spill_sort_sink_operator.h
  be/src/pipeline/exec/spill_sort_source_operator.cpp
  be/src/pipeline/exec/spill_sort_source_operator.h
  be/src/pipeline/pipeline_x/dependency.h
  be/src/vec/common/sort/sorter.cpp
  be/src/vec/spill/spill_stream.cpp
Labels: approved, reviewed

#33102 [chore](ci) set cloud_p1 (Doris Cloud Regression) as required
  .asf.yaml
Labels: approved, reviewed

#30809 [feature](load) support compressed JSON format data for broker load
  be/src/exec/decompressor.cpp
  be/src/exec/decompressor.h
  be/src/util/block_compression.cpp
  be/src/vec/exec/format/csv/csv_reader.cpp
  be/src/vec/exec/format/json/new_json_reader.cpp
  be/src/vec/exec/format/json/new_json_reader.h
  docs/en/docs/sql-manual/sql-reference/Data-Manipulation-Statements/Load/BROKER-LOAD.md
  docs/zh-CN/docs/sql-manual/sql-reference/Data-Manipulation-Statements/Load/BROKER-LOAD.md
  fe/fe-core/src/main/java/org/apache/doris/datasource/FileGroupInfo.java
  regression-test/data/load_p0/broker_load/test_compress_type.out
  regression-test/data/load_p0/stream_load/basic_data_by_line.json.bz2
  regression-test/data/load_p0/stream_load/basic_data_by_line.json.gz
  regression-test/data/load_p0/stream_load/basic_data_by_line.json.lz4
  regression-test/suites/load_p0/broker_load/test_compress_type.groovy
Labels: approved, reviewed, dev/2.0.x

#33106 [fix](cloud-auth) Fix cloud cluster auth due to #32825 and #32918
  regression-test/suites/cloud_p0/auth/test_grant_revoke_cluster_role.groovy
  regression-test/suites/cloud_p0/auth/test_grant_revoke_cluster_to_user.groovy
Labels: approved, reviewed

#33091 [fix](Nereids) fix group concat
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/pipeline/pipeline_x/pipeline_x_fragment_context.cpp
  be/src/runtime/descriptors.h
  be/src/vec/exec/vaggregation_node.h
  fe/fe-core/src/main/java/org/apache/doris/nereids/memo/Group.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/memo/GroupExpression.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/ChildrenPropertiesRegulator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/PhysicalProperties.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/NormalizeAggregate.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/implementation/AggregateStrategies.java
Labels: approved, reviewed

#33117 [fix](Nereids) fix bind group by int literal
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/BindExpression.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/ResolveOrdinalInOrderByAndGroupBy.java
  regression-test/data/nereids_syntax_p0/bind_priority.out
  regression-test/suites/nereids_syntax_p0/bind_priority.groovy
Labels: approved, reviewed

#32840 [feature](merge-cloud) Add stage auth for `copy into` in cloud
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/GrantStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ResourcePattern.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowRolesStmt.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/AuthProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/Auth.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/PrivBitSet.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/PrivPredicate.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/Role.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/RoleManager.java
  fe/fe-core/src/main/jflex/sql_scanner.flex
  regression-test/suites/cloud_p0/auth/test_grant_revoke_cluster_role.groovy
  regression-test/suites/cloud_p0/auth/test_grant_revoke_cluster_to_user.groovy
Labels: approved, reviewed

#32991 [Enhancement](merge-on-write) Support dynamic delete bitmap cache
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/olap/tablet_meta.cpp
Labels: approved, reviewed, dev/2.0.x

#32982 [opt](nereids) push down runtime filter to all children of SetOperation
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/RuntimeFilterGenerator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/ExpressionVisitors.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/AbstractPhysicalPlan.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalHashAggregate.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalProject.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalSetOperation.java
  regression-test/data/nereids_tpcds_shape_sf100_p0/noStatsRfPrune/query14.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/noStatsRfPrune/query47.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/noStatsRfPrune/query57.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/no_stats_shape/query14.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/no_stats_shape/query47.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/no_stats_shape/query57.out
  regression-test/data/nereids_tpch_shape_sf1000_p0/runtime_filter/test_pushdown_setop.out
  regression-test/suites/nereids_tpch_shape_sf1000_p0/runtime_filter/test_pushdown_setop.groovy
Labels: approved, reviewed

#33087 [feature](nereids) support common sub expression by multi-layer projections (fe part)
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/PhysicalPlanTranslator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/CommonSubExpressionCollector.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/CommonSubExpressionOpt.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/PlanPostProcessors.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalProject.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PlanNode.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/CreateFunctionTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/postprocess/CommonSubExpressionTest.java
  regression-test/data/tpch_sf0.1_p1/sql/cse.out
  regression-test/framework/src/main/groovy/org/apache/doris/regression/action/ExplainAction.groovy
  regression-test/suites/tpch_sf0.1_p1/sql/cse.groovy
Labels: approved, reviewed

#32926 [Fix](partial-update) Fix partial update fail when the datetime default value is 'current_time'
  be/src/exec/tablet_info.cpp
  be/src/exec/tablet_info.h
  be/src/olap/delta_writer_v2.cpp
  be/src/olap/partial_update_info.h
  be/src/olap/rowset/segment_v2/segment_writer.cpp
  be/src/olap/rowset/segment_v2/vertical_segment_writer.cpp
  be/src/olap/rowset_builder.cpp
  be/src/vec/sink/writer/vtablet_writer.cpp
  be/src/vec/sink/writer/vtablet_writer_v2.cpp
  gensrc/proto/descriptors.proto
  regression-test/data/unique_with_mow_p0/partial_update/test_partial_update.out
  regression-test/suites/unique_with_mow_p0/partial_update/test_partial_update.groovy
Labels: approved, reviewed, p0_b, meta-change, dev/2.0.x

#32910 [feature-wip](Cloud) Support set default storage vault and pass vault id to all write paths
  be/src/cloud/cloud_delete_task.cpp
  be/src/cloud/cloud_rowset_builder.cpp
  be/src/cloud/cloud_schema_change_job.cpp
  be/src/cloud/cloud_storage_engine.cpp
  be/src/cloud/cloud_storage_engine.h
  be/src/olap/compaction.cpp
  be/src/olap/schema_change.h
  cloud/src/meta-service/meta_service.cpp
  cloud/src/meta-service/meta_service_resource.cpp
  cloud/test/meta_service_test.cpp
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/alter/RollupJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SetDefaultStorageVaultStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/InternalSchemaInitializer.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/StorageVaultMgr.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/TableProperty.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/datasource/CloudInternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/common/FeConstants.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/load/DeleteJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapTableSink.java
  fe/fe-core/src/main/java/org/apache/doris/qe/DdlExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/task/AlterReplicaTask.java
  fe/fe-core/src/main/java/org/apache/doris/task/PushTask.java
  fe/fe-core/src/test/java/org/apache/doris/cloud/catalog/HdfsStorageVaultTest.java
  gensrc/proto/cloud.proto
  gensrc/thrift/AgentService.thrift
Labels: approved, reviewed, meta-change

#32839 [Bug](schame-change) fix wrong result after reorder mor table
  be/src/olap/column_mapping.h
  be/src/olap/schema_change.cpp
  regression-test/data/mv_p0/multi_slot_k1a2p2ap3p/multi_slot_k1a2p2ap3p.out
  regression-test/data/schema_change_p0/reorder_mor/reorder_mor.out
  regression-test/suites/mv_p0/multi_slot_k1a2p2ap3p/multi_slot_k1a2p2ap3p.groovy
  regression-test/suites/schema_change_p0/reorder_mor/reorder_mor.groovy
Labels: kind/test, dev/2.0.x

#33032 [fix](nereids)partition prune should consider <=> operator
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/OneRangePartitionEvaluator.java
  regression-test/data/nereids_rules_p0/partition_prune/test_nullsafe_eq_prune.out
  regression-test/suites/nereids_rules_p0/partition_prune/test_nullsafe_eq_prune.groovy
Labels: kind/test, area/nereids

#33121 [cherry-pick](function) fix milliseconds_diff function return wrong result (#32897)
  be/src/vec/functions/function_date_or_datetime_computation.h
  be/src/vec/runtime/vdatetime_value.h
  docs/en/docs/sql-manual/sql-functions/date-time-functions/timediff.md
  docs/zh-CN/docs/sql-manual/sql-functions/date-time-functions/timediff.md
  regression-test/data/query_p0/sql_functions/datetime_functions/test_time_diff.out
Labels: kind/docs

#33134 [fix](Nereids) fix link children failed
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/rewrite/PlanTreeRewriteJob.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/SetOperationTest.java
Labels: approved, reviewed

#33129 [fix](show_variables) fix default value for special variables
  fe/fe-core/src/main/java/org/apache/doris/qe/VariableMgr.java
Labels: approved, reviewed

#32994 [Fix](Nereids) ntile function should check argument
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/window/Ntile.java
  regression-test/suites/nereids_p0/sql_functions/window_functions/test_ntile_function.groovy
  regression-test/suites/query_p0/sql_functions/window_functions/test_ntile_function.groovy
Labels: approved, reviewed, dev/2.0.x

#33089 [Optimize](Variant) Move strings_pool from individual tree nodes to the tree itself
  be/src/vec/columns/subcolumn_tree.h
Labels: approved, reviewed, variant

#33137 [profile](name) add table rollup name in profile
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
Labels: approved, reviewed, dev/2.0.x

#33111 [opt](nereids)push topn-filter to both sides of inner join
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/TopNScanOpt.java
  regression-test/suites/nereids_tpch_p0/tpch/topn-filter.groovy
Labels: approved, reviewed

#33108 [fix](fe) partitionInfo is null, fe can not start
  fe/fe-core/src/main/java/org/apache/doris/catalog/CatalogRecycleBin.java
Labels: approved, reviewed

#32945 [fix](pipeline) no alloc_resource projections in VSetOperationNode
  be/src/exec/exec_node.h
  be/src/pipeline/exec/union_source_operator.cpp
  be/src/vec/exec/vset_operation_node.cpp
  be/src/vec/exec/vunion_node.cpp
  be/src/vec/exec/vunion_node.h
  regression-test/data/correctness_p0/test_vexcept_not_open.out
  regression-test/suites/correctness_p0/test_vexcept_not_open.groovy
Labels: kind/test, approved, reviewed, area/pipeline

#33092 [bugfix](iceberg)Convert the datetime type in the predicate according to the target column for 2.0
  fe/fe-core/src/main/java/org/apache/doris/external/iceberg/util/IcebergUtils.java
  fe/fe-core/src/test/java/org/apache/doris/external/iceberg/util/TestIcebergPredict.java
  regression-test/data/external_table_p2/hive/test_external_catalog_glue_table.out
  regression-test/suites/external_table_p2/hive/test_external_catalog_glue_table.groovy
Labels: kind/test

#33145 [enhancement](be-meta) disable sync rocksdb by default for better performance #32714
  be/src/common/config.cpp
Labels: approved, reviewed

#33146 [fix](merge-iterator) fix NOT_IMPLEMENTED_ERROR when read next block view #32961
  be/src/vec/olap/vgeneric_iterators.cpp
Labels: approved, reviewed

#33136 [fix](analyze) correct duplicated counting of updated rows for mv in cloud mode
  cloud/src/meta-service/meta_service_txn.cpp
  fe/fe-core/src/main/java/org/apache/doris/cloud/transaction/CloudGlobalTransactionMgr.java
  gensrc/proto/cloud.proto
  regression-test/suites/statistics/analyze_stats.groovy
  regression-test/suites/statistics/test_analyze_mtmv.groovy
  regression-test/suites/statistics/test_analyze_mv.groovy
Labels: reviewed, meta-change

#33149 [enhance](StorageVault) Print the vault id and vault message for invalid vault
  be/src/cloud/cloud_storage_engine.cpp
Labels: approved, reviewed

#33005 [Feature] support function uuid_to_int and int_to_uuid
  be/src/vec/functions/function_uuid.cpp
  be/src/vec/functions/simple_function_factory.h
  be/test/vec/function/function_string_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinScalarFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/InttoUuid.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/UuidtoInt.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/ScalarFunctionVisitor.java
  gensrc/script/doris_builtins_functions.py
Labels: approved, reviewed

#32746 [enhancement](function truncate) truncate can use column as scale argument
  be/src/vec/functions/function_truncate.h
  be/src/vec/functions/math.cpp
  be/src/vec/functions/round.h
  be/test/vec/function/function_truncate_decimal_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/ComputePrecisionForRound.java
  regression-test/data/query_p0/sql_functions/math_functions/test_function_truncate.out
  regression-test/suites/query_p0/sql_functions/math_functions/test_function_truncate.groovy
Labels: approved, reviewed, usercase, dev/2.0.x

#32841 [fix](inverted index) Cloud mode supports Chinese tokenizer with default conversion to lowercase
  be/src/olap/inverted_index_parser.h
  be/src/olap/tablet_schema.cpp
  fe/fe-core/src/main/java/org/apache/doris/catalog/Index.java
  regression-test/pipeline/cloud_p0/conf/regression-conf-custom.groovy
  regression-test/suites/backup_restore/test_backup_restore_inverted_index.groovy
  regression-test/suites/fault_injection_p0/test_index_lowercase_fault_injection.groovy
  regression-test/suites/index_p0/test_index_meta.groovy
Labels: approved, reviewed

#32875 [refactor](Mysql) Refactoring the process of using external component…
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-common/src/main/java/org/apache/doris/common/LdapConfig.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateUserStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/DropUserStmt.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/MysqlProto.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/authenticate/MysqlAuth.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/authenticate/MysqlAuthType.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/authenticate/ldap/LdapAuthenticate.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/authenticate/ldap/LdapClient.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/authenticate/ldap/LdapManager.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/authenticate/ldap/LdapUserInfo.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/Auth.java
  fe/fe-core/src/test/java/org/apache/doris/mysql/MysqlProtoTest.java
  fe/fe-core/src/test/java/org/apache/doris/mysql/authenticate/ldap/LdapAuthenticateTest.java
  fe/fe-core/src/test/java/org/apache/doris/mysql/authenticate/ldap/LdapClientTest.java
  fe/fe-core/src/test/java/org/apache/doris/mysql/authenticate/ldap/LdapManagerTest.java
Labels: approved, reviewed

#32805 [fix](arrow-flight) BE upgrade arrow to 15.0.2
  thirdparty/CHANGELOG.md
  thirdparty/vars.sh
Labels: approved, reviewed

#33148 [fix](Nereids) fix bind having aggregate failed again
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/BindExpression.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/SlotBinder.java
  regression-test/data/nereids_syntax_p0/bind_priority.out
  regression-test/suites/nereids_syntax_p0/bind_priority.groovy
Labels: kind/test, area/nereids

#33030 [fix](nereids)SimplifyRange didn't process NULL value correctly
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/SimplifyRange.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/expression/SimplifyRangeTest.java
Labels: area/nereids

#33156 [improvement](spill) avoid small spill write and improve spill timers
  be/src/pipeline/exec/partitioned_aggregation_sink_operator.h
  be/src/pipeline/exec/partitioned_aggregation_source_operator.cpp
  be/src/pipeline/exec/partitioned_hash_join_probe_operator.cpp
  be/src/pipeline/exec/partitioned_hash_join_probe_operator.h
  be/src/pipeline/exec/partitioned_hash_join_sink_operator.cpp
  be/src/pipeline/exec/partitioned_hash_join_sink_operator.h
  be/src/pipeline/exec/spill_sort_sink_operator.cpp
  be/src/pipeline/exec/spill_sort_source_operator.cpp
  be/src/pipeline/pipeline_x/operator.h
  be/src/pipeline/pipeline_x/pipeline_x_task.cpp
  be/src/vec/spill/spill_stream.cpp
  be/src/vec/spill/spill_stream.h
Labels: approved, reviewed

#33152 [Bug](min-max) store string data in MinMaxNumFunc to avoid use after free when cancel
  be/src/exprs/minmax_predicate.h
  be/src/exprs/runtime_filter.cpp
Labels: approved, reviewed

#33058 [enhancement](mysql compatible) add user and procs_priv tables to mysql db in all catalogs
  be/src/exec/schema_scanner.cpp
  be/src/exec/schema_scanner/schema_helper.cpp
  be/src/exec/schema_scanner/schema_helper.h
  be/src/exec/schema_scanner/schema_user_scanner.cpp
  be/src/exec/schema_scanner/schema_user_scanner.h
  fe/fe-core/src/main/java/org/apache/doris/analysis/RefreshDbStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SchemaTableType.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/MysqlDBTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/MysqlDb.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalDatabase.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/infoschema/ExternalMysqlDatabase.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/infoschema/ExternalMysqlTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/client/JdbcClient.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/client/JdbcMySQLClient.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/Auth.java
  fe/fe-core/src/main/java/org/apache/doris/persist/gson/GsonUtils.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/RefreshTableTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/RefreshCatalogTest.java
  fe/fe-core/src/test/java/org/apache/doris/service/FrontendServiceImplTest.java
  gensrc/thrift/Descriptors.thrift
  gensrc/thrift/FrontendService.thrift
  regression-test/data/external_table_p0/jdbc/test_clickhouse_jdbc_catalog.out
  regression-test/data/external_table_p0/jdbc/test_db2_jdbc_catalog.out
  regression-test/data/external_table_p0/jdbc/test_mariadb_jdbc_catalog.out
  regression-test/data/external_table_p0/jdbc/test_mysql_jdbc_catalog.out
  regression-test/data/external_table_p0/jdbc/test_mysql_jdbc_driver5_catalog.out
  regression-test/data/external_table_p0/jdbc/test_oracle_jdbc_catalog.out
  regression-test/data/external_table_p0/jdbc/test_pg_jdbc_catalog.out
  regression-test/data/external_table_p0/jdbc/test_sqlserver_jdbc_catalog.out
Labels: approved, reviewed, kind/behavior-changed, meta-change

#33180 [fix](compaction) fix incorrect grouping of vertical compaction columns in tables only with key columns
  be/src/olap/merger.cpp
Labels: kind/test, approved, reviewed

#33182 [fix](dns-cache) do not detach the refresh thread
  be/src/runtime/exec_env_init.cpp
  be/src/util/dns_cache.cpp
Labels: approved, reviewed

#33119 [feature](external) process tbl/db exist when create/drop db/tbl
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HiveMetadataOps.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HiveUtil.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/ThriftHMSCachedClient.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/IcebergMetadataOps.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/operations/ExternalMetadataOps.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/hive/HiveDDLAndDMLPlanTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/hive/HiveMetadataOpsTest.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/TestWithFeService.java
Labels: approved, reviewed

#33172 [Enhancement](inverted index) set need to read data only when delete predicate contains the column
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
Labels: reviewed, p0_w, dev/2.0.x

#32896 [fix](compaction) fix incorrect grouping of vertical compaction columns in tables only with key columns
  be/src/olap/merger.cpp
  regression-test/data/compaction/test_base_compaction.out
  regression-test/data/compaction/test_base_compaction_no_value.out
  regression-test/suites/compaction/test_base_compaction.groovy
  regression-test/suites/compaction/test_base_compaction_no_value.groovy
Labels: approved, reviewed, p0_b, dev/2.0.8-merged

#32984 [enhance](mtmv)support create mtmv with other mtmv
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/CreateMTMVInfo.java
  regression-test/data/mtmv_p0/test_multi_level_mtmv.out
  regression-test/suites/mtmv_p0/test_build_mtmv.groovy
  regression-test/suites/mtmv_p0/test_multi_level_mtmv.groovy
Labels: approved, reviewed

#32188 [Enhencement](Nereids) reduce child output rows if agg child is literal
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/Rewriter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/ReduceAggregateChildOutputRows.java
  regression-test/data/nereids_rules_p0/eliminate_aggregate_constant/eliminate_aggregate_constant.out
  regression-test/suites/nereids_rules_p0/eliminate_aggregate_constant/eliminate_aggregate_constant.groovy
Labels: approved, reviewed

#33181 [bugfix](deadlock) fix dead lock in cancel fragment
  be/src/pipeline/exec/exchange_sink_buffer.cpp
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/pipeline/pipeline_fragment_context.h
  be/src/pipeline/pipeline_x/pipeline_x_fragment_context.cpp
  be/src/pipeline/task_scheduler.cpp
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/query_context.cpp
  be/src/runtime/query_context.h
Labels: approved, reviewed

#32776 [enhancement](commands) Clarify user feedback messages
  bin/start_be.sh
  bin/start_fe.sh
  bin/stop_be.sh
  bin/stop_fe.sh
Labels: approved, reviewed, dev/2.0.x

#33185 [chore](spill) add timers for performance tuning
  be/src/pipeline/exec/partitioned_aggregation_sink_operator.cpp
  be/src/pipeline/exec/partitioned_aggregation_source_operator.cpp
  be/src/pipeline/exec/partitioned_hash_join_probe_operator.cpp
  be/src/pipeline/exec/partitioned_hash_join_probe_operator.h
  be/src/pipeline/exec/partitioned_hash_join_sink_operator.cpp
  be/src/pipeline/exec/partitioned_hash_join_sink_operator.h
  be/src/pipeline/exec/spill_sort_sink_operator.cpp
  be/src/pipeline/exec/spill_sort_source_operator.cpp
  be/src/pipeline/pipeline_x/operator.h
Labels: approved, reviewed

#33130 [FIX](agg) fix vertical_compaction_reader for agg table with array/map type
  be/src/vec/columns/column.h
  be/src/vec/columns/column_array.h
  be/src/vec/columns/column_const.h
  be/src/vec/columns/column_map.h
  be/src/vec/columns/column_nullable.h
  be/src/vec/columns/column_string.h
  be/src/vec/olap/block_reader.cpp
  be/src/vec/olap/vertical_block_reader.cpp
  be/src/vec/olap/vertical_block_reader.h
  regression-test/data/compaction/test_compaction_agg_keys_with_array_map.out
  regression-test/suites/compaction/test_compaction_agg_keys_with_array_map.groovy
Labels: approved, reviewed, p0_c, dev/2.1.0, dev/2.0.x

#33178 [Fix](trino-connector) Disable JUL from printing logs to the console
  fe/be-java-extensions/trino-connector-scanner/src/main/java/org/apache/doris/trinoconnector/TrinoConnectorPluginLoader.java
Labels: approved, reviewed

#33013 [Fix](nereids) forward the user define variables to master
  fe/fe-core/src/main/java/org/apache/doris/analysis/LiteralExpr.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContext.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/MasterOpExecutor.java
  gensrc/thrift/FrontendService.thrift
Labels: approved, reviewed, dev/2.0.x

#33010 [fix](nereids) runtime filter with probe expr should be pushed though set operator
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/RuntimeFilterGenerator.java
  regression-test/data/nereids_tpch_shape_sf1000_p0/runtime_filter/test_pushdown_setop.out
  regression-test/suites/nereids_tpch_shape_sf1000_p0/runtime_filter/test_pushdown_setop.groovy
Labels: approved, reviewed

#32810 [fix](fe)reduce memory usage in alter
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeJobV2.java
Labels: approved, reviewed, p0_c, dev/2.0.x

#33164 [fix](inverted index) fix the incorrect result issue of COUNT_ON_INDEX for key columns
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/olap/rowset/segment_v2/segment_iterator.h
  regression-test/data/inverted_index_p0/test_index_delete.out
  regression-test/suites/inverted_index_p0/test_index_delete.groovy
Labels: approved, reviewed, p0_w, dev/2.0.x

#33196 [fix](inverted index) fix the incorrect result issue of COUNT_ON_INDEX for key columns
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/olap/rowset/segment_v2/segment_iterator.h
  regression-test/data/inverted_index_p0/test_index_delete.out
  regression-test/suites/inverted_index_p0/test_index_delete.groovy
Labels: kind/test, reviewed

#33208 [fix](Nereids) convert agg state type failed in some cases
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/ConvertAggStateCast.java
Labels: approved, reviewed

#33202 [fix](tvf) Support fs.defaultFS with postfix '/'
  be/src/io/hdfs_util.cpp
  regression-test/suites/external_table_p0/export/hive_read/parquet/test_hive_read_parquet_comlex_type.groovy
Labels: approved, reviewed, dev/2.0.x

#32854 [fix](nereids)SimplifyRange didn't process NULL value correctly
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/SimplifyRange.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/expression/SimplifyRangeTest.java
Labels: approved, reviewed, p0_w, dev/2.0.8-merged

#33186 [fix](plsql) Fix plsql variable initialization
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/PLLexer.g4
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/PLParser.g4
  fe/fe-core/src/main/java/org/apache/doris/plsql/Exec.java
  fe/fe-core/src/main/java/org/apache/doris/plsql/executor/DorisRowResult.java
  regression-test/data/plsql_p0/test_plsql_variable.out
  regression-test/suites/plsql_p0/test_plsql_loop_cursor.groovy
  regression-test/suites/plsql_p0/test_plsql_variable.groovy
Labels: approved, reviewed

#33200 [opt](Nereids) let inverted index work with top opt (#29000)
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/CheckAfterRewrite.java
Labels: area/nereids

#32830 [fix](Export) Set the default value of the `data_consistence` property of export to `partition`
  fe/fe-core/src/main/java/org/apache/doris/analysis/ExportStmt.java
  fe/fe-core/src/main/java/org/apache/doris/load/ExportJob.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ExportCommand.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ExportToOutfileLogicalPlanTest.java
  regression-test/suites/export_p0/test_export_basic.groovy
  regression-test/suites/export_p0/test_export_data_consistency.groovy
Labels: approved, reviewed, kind/behavior-changed, dev/2.0.x

#32010 [refactor](coordinator) split profile logic and instance report logic
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/common/Status.java
  fe/fe-core/src/main/java/org/apache/doris/common/profile/ExecutionProfile.java
  fe/fe-core/src/main/java/org/apache/doris/common/profile/Profile.java
  fe/fe-core/src/main/java/org/apache/doris/common/profile/SummaryProfile.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/ProfileManager.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/RuntimeProfile.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BrokerLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadLoadingTask.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/LoadCommand.java
  fe/fe-core/src/main/java/org/apache/doris/qe/CoordInterface.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/PointQueryExec.java
  fe/fe-core/src/main/java/org/apache/doris/qe/QeProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/QeProcessorImpl.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/rpc/BackendServiceClient.java
  fe/fe-core/src/main/java/org/apache/doris/rpc/BackendServiceProxy.java
  fe/fe-core/src/test/java/org/apache/doris/common/util/RuntimeProfileTest.java
  fe/fe-core/src/test/java/org/apache/doris/qe/StmtExecutorTest.java
Labels: approved, reviewed, meta-change

#33211 [Bug](runtime-filter) set need_local_merge to false when rf is broadcast
  be/src/exprs/runtime_filter.cpp
  be/src/exprs/runtime_filter.h
  be/src/pipeline/exec/nested_loop_join_build_operator.cpp
Labels: approved, reviewed

#33162 [fix](memory) Fix memory log compile by ASAN
  be/src/runtime/memory/mem_tracker_limiter.cpp
  be/src/util/mem_info.cpp
  be/src/util/perf_counters.cpp
Labels: approved, reviewed

#33214 [fix](Nereids) support update without filter
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
Labels: approved, reviewed

#33165 [fix](move-memtable) fix initial use count of streams for auto partition
  be/src/vec/sink/load_stream_stub.cpp
  be/src/vec/sink/load_stream_stub.h
  be/src/vec/sink/load_stream_stub_pool.cpp
  be/src/vec/sink/load_stream_stub_pool.h
  be/src/vec/sink/writer/vtablet_writer_v2.cpp
  be/src/vec/sink/writer/vtablet_writer_v2.h
  be/test/io/fs/stream_sink_file_writer_test.cpp
  be/test/vec/exec/load_stream_stub_pool_test.cpp
Labels: approved, reviewed

#33209 [Cherry-pick](branch-2.0) Pick "[Fix](partial update) Fix partial update load false when schema includes auto increment column (#31725)"
  be/src/exec/tablet_info.cpp
  be/src/exec/tablet_info.h
  be/src/olap/delta_writer.cpp
  be/src/olap/partial_update_info.h
  be/src/olap/rowset/segment_v2/segment_writer.cpp
  be/src/vec/sink/vtablet_sink.cpp
  gensrc/proto/descriptors.proto
  regression-test/data/unique_with_mow_p0/partial_update/test_partial_update.out
  regression-test/suites/unique_with_mow_p0/partial_update/test_partial_update.groovy
Labels: kind/test

#33216 [FIX](agg) fix vertical_compaction_reader for agg table with array/map type #33130
  be/src/vec/columns/column.h
  be/src/vec/columns/column_array.h
  be/src/vec/columns/column_const.h
  be/src/vec/columns/column_map.h
  be/src/vec/columns/column_nullable.h
  be/src/vec/columns/column_string.h
  be/src/vec/olap/block_reader.cpp
  be/src/vec/olap/vertical_block_reader.cpp
  be/src/vec/olap/vertical_block_reader.h
  regression-test/data/compaction/test_compaction_agg_keys_with_array_map.out
  regression-test/suites/compaction/test_compaction_agg_keys_with_array_map.groovy
Labels: kind/test

#33197 [Fix](executor)Fix normal group can not be appended when image exits
  fe/fe-core/src/main/java/org/apache/doris/resource/workloadgroup/WorkloadGroupMgr.java
Labels: approved, reviewed, usercase, workload-group

#33189 [test](cast) add test for stream load cast
  regression-test/data/load_p0/stream_load/test_cast1.csv
  regression-test/data/load_p0/stream_load/test_cast1.json
  regression-test/data/load_p0/stream_load/test_cast2.csv
  regression-test/data/load_p0/stream_load/test_cast2.json
  regression-test/data/load_p0/stream_load/test_cast3.csv
  regression-test/data/load_p0/stream_load/test_cast3.json
  regression-test/data/load_p0/stream_load/test_stream_load_cast.out
  regression-test/suites/load_p0/stream_load/test_stream_load_cast.groovy
Labels: approved, reviewed, dev/2.0.x

#33234 [fix](plsql) Fix regression test execute the same name procedure in parallel
  regression-test/suites/plsql_p0/test_plsql_variable.groovy
Labels: approved, reviewed

#32652 [enhance](cloud_p0) morecases for cloud_p0
  regression-test/pipeline/cloud_p0/conf/regression-conf-custom.groovy
Labels: approved, reviewed

#33230 [branch-2.0][improvement](serde) Handle NaN values in number for MySQL result write
  be/src/vec/data_types/serde/data_type_number_serde.cpp
  regression-test/data/datatype_p0/double/test_double_nan.out
  regression-test/data/datatype_p0/float/test_float_nan.out
  regression-test/data/nereids_function_p0/scalar_function/A.out
  regression-test/suites/datatype_p0/double/test_double_nan.groovy
  regression-test/suites/datatype_p0/float/test_float_nan.groovy
Labels: kind/test

#33242 [opt](hive) simplify the isSplitable method to avoid too many hadoop metrics
  fe/fe-core/src/main/java/org/apache/doris/catalog/external/HMSExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/external/hive/util/HiveUtil.java
Labels: dev/2.0.x

#32876 [feature](merge-cloud) Add table stat metrics in FE
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/metric/PrometheusMetricVisitor.java
Labels: approved, reviewed

#33183 (cloud-merge) Fix the is not same in invertedIndex and catalog
  fe/fe-core/src/main/java/org/apache/doris/alter/CloudRollupJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/alter/CloudSchemaChangeJobV2.java
Labels: approved, reviewed

#33238 [fix](cloud) fix failed to get delete bitmap update lock key info
  cloud/src/meta-service/meta_service_txn.cpp
Labels: approved, reviewed

#33150 [fix](compile) fix gcc compile failed (#30596)
  cloud/src/meta-service/codec.cpp
Labels: approved, reviewed

#33168 [feature](index compaction)support index compaction in cloud mode
  be/src/olap/compaction.cpp
  be/src/olap/compaction.h
  regression-test/suites/fault_injection_p0/test_index_compaction_fault_injection.groovy
  regression-test/suites/inverted_index_p0/index_compaction/test_index_compaction_dup_keys.groovy
  regression-test/suites/inverted_index_p0/index_compaction/test_index_compaction_null.groovy
  regression-test/suites/inverted_index_p0/index_compaction/test_index_compaction_unique_keys.groovy
  regression-test/suites/inverted_index_p0/index_compaction/test_index_compaction_with_multi_index_segments.groovy
Labels: approved, reviewed

#33072 [fix](case) ignore single_replica_compaction in cloud mode
  regression-test/suites/load_p0/stream_load/test_stream_load_move_memtable.groovy
  regression-test/suites/schema_change/test_alter_table_property.groovy
  regression-test/suites/schema_change_p0/test_rename_column.groovy
Labels: approved, reviewed

#33253 [fix](cloud-cases) exclude cache ttl
  regression-test/pipeline/p0/conf/regression-conf.groovy
Labels: approved, reviewed

#33250 [fix](cloud) Fix coredump during graceful shutdown
  be/src/cloud/cloud_storage_engine.cpp
  be/src/cloud/cloud_tablet_mgr.cpp
  be/src/cloud/cloud_tablet_mgr.h
Labels: approved, reviewed

#33237 [debug](log) Add some debug logs
  be/src/pipeline/pipeline_x/local_exchange/local_exchange_sink_operator.cpp
  be/src/pipeline/pipeline_x/pipeline_x_fragment_context.cpp
Labels: approved, reviewed

#33194 [fix](merge-cloud) fix backend id in tablet invert index
  fe/fe-core/src/main/java/org/apache/doris/catalog/TabletInvertedIndex.java
Labels: approved, reviewed

#33244 [enhancement](merge-on-write) consider version count on size-based cloud cu compaction policy
  be/src/cloud/cloud_cumulative_compaction_policy.cpp
  be/src/cloud/cloud_cumulative_compaction_policy.h
Labels: approved, reviewed

#33249 [Feature](Cloud) Add show storage vault stmt
  cloud/src/meta-service/meta_service_resource.cpp
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowStorageVaultStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/StorageVault.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/rpc/MetaServiceClient.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/rpc/MetaServiceProxy.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
Labels: approved, reviewed

#33248 [fix](cloud) fix routine load can not consume in cloud mode
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/KafkaRoutineLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadJob.java
Labels: approved, reviewed

#33255 [enhance](cloud) Validate and normalize hdfs conf when adding new vault
  cloud/src/meta-service/meta_service_resource.cpp
  cloud/src/recycler/meta_checker.cpp
  cloud/test/meta_service_test.cpp
Labels: approved, reviewed

#33256 [fix](move-memtable) fix timeout to get tablet schema
  be/src/runtime/exec_env.cpp
  be/src/runtime/exec_env.h
  be/src/runtime/exec_env_init.cpp
  be/src/vec/sink/load_stream_map_pool.cpp
  be/src/vec/sink/load_stream_map_pool.h
  be/src/vec/sink/load_stream_stub.cpp
  be/src/vec/sink/volap_table_sink_v2.cpp
  be/src/vec/sink/writer/vtablet_writer_v2.cpp
  be/src/vec/sink/writer/vtablet_writer_v2.h
  be/test/vec/exec/load_stream_stub_map_test.cpp
Labels: approved, reviewed

#33174 [improve](function) the offset params in lead/lag function could use 0
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/window/Lag.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/window/Lead.java
  regression-test/data/correctness_p0/test_always_nullable_window_function.out
  regression-test/suites/correctness_p0/test_always_nullable_window_function.groovy
Labels: approved, reviewed, usercase, dev/2.0.x

#33177 [Enhancement](partial update)Add timezone case for partial update timestamp
  regression-test/data/unique_with_mow_p0/partial_update/test_partial_update.out
  regression-test/suites/unique_with_mow_p0/partial_update/test_partial_update.groovy
Labels: approved, reviewed, dev/2.0.x

#33120 [Fix](point query) avoid nullptr in _block_pool
  be/src/service/point_query_executor.cpp
Labels: approved, reviewed, p0_c, dev/2.0.8-merged

#33122 [fix](nereids)reject nse-rf for nested loop outer join
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalNestedLoopJoin.java
Labels: approved, reviewed

#33113 [BugFix](Iceberg Catalog) Fix iceberg catalog of hms and hadoop not support iceberg properties
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/IcebergHMSExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/IcebergHadoopExternalCatalog.java
Labels: approved, reviewed, dev/2.0.x

#33259 [fix](cloud) Always use absolute path in hdfs
  be/src/io/hdfs_util.cpp
  cloud/src/recycler/hdfs_accessor.cpp
Labels: approved, reviewed

#33266 [fix](regression) fix mtmv statistics case failure in cloud mode
  fe/fe-core/src/main/java/org/apache/doris/catalog/CloudTabletStatMgr.java
Labels: approved, reviewed

#33268 [fix](merge-cloud) add injection test http api and fix cloud compaction http api
  be/CMakeLists.txt
  be/src/cloud/cloud_compaction_action.cpp
  be/src/cloud/cloud_compaction_action.h
  be/src/cloud/cloud_storage_engine.h
  be/src/cloud/cloud_tablet.cpp
  be/src/cloud/injection_point_action.cpp
  be/src/cloud/injection_point_action.h
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/service/http_service.cpp
  build.sh
Labels: approved, reviewed

#33228 [fix](parquet) fix time zone error in parquet reader
  be/src/vec/exec/format/parquet/decoder.cpp
  be/src/vec/exec/format/parquet/decoder.h
  be/src/vec/exec/format/parquet/parquet_pred_cmp.h
  regression-test/data/external_table_p0/hive/test_hive_basic_type.out
  regression-test/data/external_table_p2/hive/test_external_catalog_hive.out
  regression-test/suites/external_table_p2/hive/test_external_catalog_hive.groovy
Labels: kind/test

#33101 [Improvement](executor)Add BypassWorkloadGroup to pass query queue
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  regression-test/suites/workload_manager_p0/test_curd_wlg.groovy
Labels: approved, reviewed, workload-group

#33263 [fix](merge-cloud) update modify backend's cluster name
  fe/fe-core/src/main/java/org/apache/doris/cloud/system/CloudSystemInfoService.java
  fe/fe-core/src/main/java/org/apache/doris/system/SystemInfoService.java
Labels: approved, reviewed

#33275 [fix](routine-load) fix routine load lock do not release
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadJob.java
Labels: approved, reviewed

#33271 [chore](ci) set enableKafkaTest=true for test_routine_load
  regression-test/pipeline/cloud_p0/conf/regression-conf-custom.groovy
Labels: approved, reviewed

#33261 [fix](merge-cloud) change cloud rebalance config to masterOnly=true
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
Labels: approved, reviewed

#33269 [test](Cloud) Add more storage vault ut
  cloud/src/meta-service/meta_service.cpp
  cloud/src/meta-service/meta_service_resource.cpp
  cloud/test/meta_service_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/catalog/StorageVault.java
  gensrc/proto/cloud.proto
Labels: approved, reviewed, meta-change

#33258 [fix](cloud_p0) exclude cache ttl in cloud_p0
  regression-test/pipeline/cloud_p0/conf/regression-conf-custom.groovy
Labels: approved, reviewed

#33279 (cloud-merge) Modify the cluster name in ttl test
  regression-test/data/cloud_p0/cache/ttl/test_show_ttl.out
  regression-test/suites/cloud_p0/cache/compaction/test_stale_rowset.groovy
  regression-test/suites/cloud_p0/cache/http/test_cache_metrics_format.groovy
  regression-test/suites/cloud_p0/cache/http/test_clear_cache.groovy
  regression-test/suites/cloud_p0/cache/http/test_clear_cache_async.groovy
  regression-test/suites/cloud_p0/cache/ttl/alter_ttl_1.groovy
  regression-test/suites/cloud_p0/cache/ttl/alter_ttl_2.groovy
  regression-test/suites/cloud_p0/cache/ttl/alter_ttl_3.groovy
  regression-test/suites/cloud_p0/cache/ttl/alter_ttl_4.groovy
  regression-test/suites/cloud_p0/cache/ttl/alter_ttl_error.groovy
  regression-test/suites/cloud_p0/cache/ttl/alter_ttl_max_int64.groovy
  regression-test/suites/cloud_p0/cache/ttl/alter_ttl_random.groovy
  regression-test/suites/cloud_p0/cache/ttl/alter_ttl_seconds.groovy
  regression-test/suites/cloud_p0/cache/ttl/create_table_as_select.groovy
  regression-test/suites/cloud_p0/cache/ttl/create_table_like.groovy
  regression-test/suites/cloud_p0/cache/ttl/test_ttl.groovy
  regression-test/suites/cloud_p0/cache/ttl/test_ttl_preempt.groovy
Labels: approved, reviewed

#33274 [fix](UT) Fix incorrect command for cloud run_all_tests.sh
  cloud/script/run_all_tests.sh
Labels: approved, reviewed

#33280 [feature](cloud) Support hdfs accessor in Checker
  be/src/io/fs/hdfs_file_system.cpp
  cloud/src/recycler/checker.cpp
  cloud/src/recycler/checker.h
  cloud/src/recycler/hdfs_accessor.cpp
  cloud/src/recycler/hdfs_accessor.h
  cloud/src/recycler/obj_store_accessor.h
  cloud/src/recycler/s3_accessor.cpp
  cloud/src/recycler/util.cpp
  cloud/test/hdfs_accessor_test.cpp
Labels: approved, reviewed

#33281 [chore](cloud) Fix clear file cache implementation and regression case
  be/src/http/action/clear_file_cache_action.cpp
  be/src/io/cache/block_file_cache.cpp
  be/src/io/cache/block_file_cache.h
  be/src/io/cache/block_file_cache_factory.cpp
  be/src/io/cache/block_file_cache_factory.h
  regression-test/suites/cloud_p0/cache/http/test_clear_cache.groovy
  regression-test/suites/cloud_p0/cache/http/test_clear_cache_async.groovy
Labels: approved, reviewed

#33270 [enhance](httpaction) log response of http
  regression-test/framework/src/main/groovy/org/apache/doris/regression/action/HttpCliAction.groovy
Labels: approved, reviewed

#33287 [fix](cloud) add load.groovy for cache cases
  regression-test/suites/cloud_p0/cache/load.groovy
Labels: approved, reviewed

#33290 [fix](iceberg) fix iceberg predicate conversion bug #33283
  fe/fe-core/src/main/java/org/apache/doris/external/iceberg/util/IcebergUtils.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/iceberg/IcebergScanNode.java
  fe/fe-core/src/test/java/org/apache/doris/external/iceberg/util/IcebergPredicateTest.java
  fe/fe-core/src/test/java/org/apache/doris/external/iceberg/util/TestIcebergPredict.java
  regression-test/data/external_table_p2/iceberg/test_iceberg_predicate_conversion.out
  regression-test/suites/external_table_p2/iceberg/test_iceberg_predicate_conversion.groovy
Labels: area/planner, kind/test

#33198 [Bug](materialized-view) fix wrong result when salias name same with base slot on mv
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/mv/AbstractSelectMaterializedIndexRule.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/mv/SelectMaterializedIndexWithAggregate.java
  regression-test/data/mv_p0/test_upper_alias/test_upper_alias.out
  regression-test/suites/mv_p0/test_dup_mv_year/test_dup_mv_year.groovy
  regression-test/suites/mv_p0/test_upper_alias/test_upper_alias.groovy
Labels: approved, reviewed, p0_w, dev/2.0.x

#33227 [improvement](serde) Handle NaN values in number for MySQL result write
  be/src/vec/data_types/serde/data_type_number_serde.cpp
  regression-test/data/datatype_p0/double/test_double_nan.out
  regression-test/data/datatype_p0/float/test_float_nan.out
  regression-test/data/nereids_function_p0/scalar_function/A.out
  regression-test/suites/datatype_p0/double/test_double_nan.groovy
  regression-test/suites/datatype_p0/float/test_float_nan.groovy
Labels: approved, reviewed, dev/2.0.8-merged

#33294 [pipelineX](fix) Fix coredump by incorrect cancel order
  be/src/runtime/query_context.cpp
Labels: approved, reviewed

#33304 [branch-2.0](test) fix some unstable tests
  regression-test/suites/external_table_p2/iceberg/test_iceberg_predicate_conversion.groovy
Labels: kind/test

#33273 [fix](spill) fix hash join error 'invalid slot id'
  be/src/pipeline/exec/partitioned_hash_join_probe_operator.cpp
Labels: approved, reviewed

#33098 [Fix](Cases) nereids support window function but some cases does not open yet
  regression-test/data/nereids_p0/aggregate/aggregate.out
  regression-test/data/nereids_p0/sql_functions/window_functions/test_window_fn.out
  regression-test/data/nereids_p0/sql_functions/window_functions/test_window_function.out
  regression-test/suites/nereids_p0/aggregate/aggregate.groovy
  regression-test/suites/nereids_p0/join/test_join_15.groovy
  regression-test/suites/nereids_p0/keyword/order_group.groovy
  regression-test/suites/nereids_p0/sql_functions/window_functions/test_select_stddev_variance_window.groovy
  regression-test/suites/nereids_p0/sql_functions/window_functions/test_sum.groovy
  regression-test/suites/nereids_p0/sql_functions/window_functions/test_window_fn.groovy
  regression-test/suites/nereids_p0/sql_functions/window_functions/test_window_function.groovy
Labels: approved, reviewed, dev/2.0.x

#33232 [Improvement](min-max) reduce copy on store_string_ref
  be/src/exprs/minmax_predicate.h
Labels: approved, reviewed

#33306 [chore](license) fix incomplete license header
  tools/cost_model_evaluate/requirements.txt
Labels: approved, reviewed

#33283 [fix](iceberg) fix iceberg predicate conversion bug
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/IcebergUtils.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/source/IcebergScanNode.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/iceberg/IcebergPredicateTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/iceberg/TestIcebergPredict.java
  regression-test/data/external_table_p2/iceberg/test_iceberg_predicate_conversion.out
  regression-test/suites/external_table_p2/iceberg/test_iceberg_predicate_conversion.groovy
Labels: approved, reviewed, dev/2.0.8-merged

#32916 [feature](replica) support force set replicate allocation for olap tables
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/PropertyAnalyzer.java
Labels: approved, reviewed

#33245 [Feature][Enhancement](hive-writer) Add hive-writer runtime profiles, change output file names and Use `table_sink_partition_write_max_partition_nums_per_writer`.
  be/src/common/config.h
  be/src/vec/sink/writer/vhive_partition_writer.cpp
  be/src/vec/sink/writer/vhive_partition_writer.h
  be/src/vec/sink/writer/vhive_table_writer.cpp
  be/src/vec/sink/writer/vhive_table_writer.h
Labels: approved, reviewed

#33233 [chore](Nereids) load command always could fallback
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/LoadCommand.java
Labels: approved, reviewed

#33070 [bug](cloud) fix null pointer exception in get partition visible version rpc
  fe/fe-core/src/main/java/org/apache/doris/cloud/qe/SnapshotProxy.java
Labels: approved, reviewed

#33231 [fix](Nereids) array_range not support amount without unit
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
Labels: approved, reviewed

#33226 [chore](Nereids) create policy always allow fallback
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/CreatePolicyCommand.java
Labels: approved, reviewed

#33300 (cloud-merge) Fix the case timeout because the sql fetches too many datas
  regression-test/suites/cloud_p0/cache/ttl/alter_ttl_4.groovy
Labels: approved, reviewed

#33282 [fix](variables) change column type of @@autocommit to BIGINT
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/qe/VariableMgr.java
  fe/fe-core/src/test/java/org/apache/doris/qe/VariableMgrTest.java
Labels: approved, reviewed, kind/behavior-changed, usercase

#33316 [fix](merge-cloud) change config security_checker_class_name to masterOnly=false
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
Labels: approved, reviewed

#33324 [Bug](case) fix wrong case test_mv_partition
  regression-test/suites/mv_p0/test_mv_partition/test_mv_partition.groovy
Labels: approved, reviewed

#32949 [improvement](doris-compose) Add more config for custom file
  docker/runtime/doris-compose/Readme.md
  docker/runtime/doris-compose/cluster.py
  docker/runtime/doris-compose/command.py
Labels: reviewed

#33314 [chore](third-party) Fix compatibility issues with GLIBC(>= 2.34) for prebuilt thirdparty packages
  thirdparty/download-thirdparty.sh
  thirdparty/patches/krb5-1.19.patch
Labels: approved, reviewed

#33328 [fix](Nereids) variant column prune push down failed on variant literal
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/PushDownToProjectionFunction.java
Labels: approved, reviewed

#33195 [fix](hdfs-writer) Catch error information after `hdfsCloseFile()`
  be/src/io/fs/hdfs_file_writer.cpp
Labels: approved, reviewed, dev/2.0.8-merged

#33217 [fix](parquet) fix time zone error in parquet reader
  be/src/vec/exec/format/parquet/parquet_column_convert.h
  be/src/vec/exec/format/parquet/parquet_pred_cmp.h
  regression-test/data/external_table_p0/hive/test_hive_basic_type.out
  regression-test/data/external_table_p0/tvf/test_s3_tvf_parquet_compress.out
  regression-test/data/external_table_p2/hive/test_external_catalog_hive.out
  regression-test/suites/external_table_p2/hive/test_external_catalog_hive.groovy
Labels: approved, reviewed, dev/2.0.8-merged

#33317 [chore](multi-table-load) add context info in log when using single-stream-multi-table load
  be/src/io/fs/multi_table_pipe.cpp
  be/src/runtime/routine_load/routine_load_task_executor.cpp
Labels: approved, reviewed
