Repository apache/doris, pull requests merged in 2024-02, with the labels that each got.

#30664 [MINOR](fe) remove unused member in `HMSExternalTable`
  fe/fe-core/src/main/java/org/apache/doris/catalog/external/HMSExternalTable.java
Labels: approved, reviewed

#30661 [Improvement](exec) fix wrong profile on distinct agg and pass reference on uint136's com…
  be/src/vec/common/uint128.h
  be/src/vec/exec/distinct_vaggregation_node.cpp
  be/src/vec/exec/vaggregation_node.h
Labels: approved, reviewed

#30402 [chore](show replica) show replica print path
  fe/fe-core/src/main/java/org/apache/doris/common/proc/BackendProcNode.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/ReplicasProcNode.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/TabletsProcDir.java
  fe/fe-core/src/test/java/org/apache/doris/common/proc/BackendProcNodeTest.java
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
  regression-test/suites/compaction/test_base_compaction_with_dup_key_max_file_size_limit.groovy
  regression-test/suites/compaction/test_compacation_with_delete.groovy
  regression-test/suites/compaction/test_compaction_agg_keys.groovy
  regression-test/suites/compaction/test_compaction_agg_keys_with_delete.groovy
  regression-test/suites/compaction/test_compaction_dup_keys.groovy
  regression-test/suites/compaction/test_compaction_dup_keys_with_delete.groovy
  regression-test/suites/compaction/test_compaction_uniq_cluster_keys_with_delete.groovy
  regression-test/suites/compaction/test_compaction_uniq_keys.groovy
  regression-test/suites/compaction/test_compaction_uniq_keys_cluster_key.groovy
  regression-test/suites/compaction/test_compaction_uniq_keys_row_store.groovy
  regression-test/suites/compaction/test_compaction_uniq_keys_with_delete.groovy
  regression-test/suites/compaction/test_full_compaction.groovy
  regression-test/suites/compaction/test_full_compaction_by_table_id.groovy
  regression-test/suites/compaction/test_single_replica_compaction.groovy
  regression-test/suites/compaction/test_vertical_compaction_agg_keys.groovy
  regression-test/suites/compaction/test_vertical_compaction_dup_keys.groovy
  regression-test/suites/compaction/test_vertical_compaction_uniq_keys.groovy
  regression-test/suites/fault_injection_p0/test_index_compaction_fault_injection.groovy
  regression-test/suites/inverted_index_p0/index_change/test_index_change_with_compaction.groovy
  regression-test/suites/inverted_index_p0/index_compaction/test_index_compaction_dup_keys.groovy
  regression-test/suites/inverted_index_p0/index_compaction/test_index_compaction_null.groovy
  regression-test/suites/inverted_index_p0/index_compaction/test_index_compaction_unique_keys.groovy
  regression-test/suites/inverted_index_p0/index_compaction/test_index_compaction_with_multi_index_segments.groovy
  regression-test/suites/load_p0/stream_load/test_map_load_and_compaction.groovy
  regression-test/suites/nereids_p0/select_tablets/select_with_tablets.groovy
  regression-test/suites/variant_p0/compaction/test_compaction.groovy
Labels: approved, reviewed, dev/2.0.5

#30570 [Bug](insert) try to fix invalid slot when insert
  fe/fe-core/src/main/java/org/apache/doris/analysis/Expr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OriginalPlanner.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
  regression-test/suites/datatype_p0/agg_state/max/test_agg_state_max.groovy
Labels: approved, reviewed, p0_c, dev/2.0.5

#30574 [Refact](inverted index) refact inverted index cache to decouple with reader
  be/src/olap/rowset/segment_v2/inverted_index/query/query_factory.h
  be/src/olap/rowset/segment_v2/inverted_index_cache.cpp
  be/src/olap/rowset/segment_v2/inverted_index_cache.h
  be/src/olap/rowset/segment_v2/inverted_index_query_type.h
  be/src/olap/rowset/segment_v2/inverted_index_reader.cpp
  be/src/olap/rowset/segment_v2/inverted_index_reader.h
  be/src/olap/rowset/segment_v2/inverted_index_searcher.cpp
  be/src/olap/rowset/segment_v2/inverted_index_searcher.h
  be/src/olap/rowset/segment_v2/inverted_index_writer.cpp
  be/test/olap/rowset/segment_v2/inverted_index_searcher_cache_test.cpp
Labels: approved, reviewed

#30585 [fix](test) fix case with same catalog name
  regression-test/suites/external_table_p2/iceberg/test_external_catalog_icebergv2_nereids.groovy
Labels: approved, reviewed, dev/2.0.5

#30658 [chore](code format) fix code format problem
  be/src/olap/row_cursor.cpp
  be/src/runtime/export_sink.cpp
Labels: approved, reviewed

#30653 [fix](decimalv2) update set with a decimal literal overflowed make be crash
  be/src/vec/exprs/vexpr.cpp
  be/src/vec/sink/vtablet_sink.cpp
Labels: approved, area/vectorization, reviewed

#30666 [improvement](statistics)Sync stats cache while task finished, doesn't need to query column_statistics table. (#30609)
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisJob.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisManager.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/BaseAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/ColStatsData.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/ColumnStatistic.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/HMSAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/JdbcAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsCache.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatsId.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/AnalysisJobTest.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/CacheTest.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/ColStatsDataTest.java
  gensrc/thrift/FrontendService.thrift
Labels: reviewed

#30656 [Fix](json) avoid print warn log when parse failed
  be/src/runtime/jsonb_value.cpp
  be/src/util/jsonb_parser_simd.h
Labels: approved, reviewed, dev/2.0.5

#30614 [Enhancement](group commit) Optimize WAL insufficient space error messages
  be/src/http/action/http_stream.cpp
  be/src/http/action/stream_load.cpp
  be/src/olap/wal/wal_dirs_info.cpp
  be/src/olap/wal/wal_dirs_info.h
  be/src/olap/wal/wal_manager.cpp
  be/src/olap/wal/wal_manager.h
Labels: approved, reviewed

#30528 [Test](Nereids) Add SSB dataset to test materialized view rewrite
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVCache.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewAggregateRule.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewJoinRule.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/MaterializedViewUtils.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/StructInfo.java
  regression-test/data/nereids_rules_p0/mv/ssb/mv_ssb_test.out
  regression-test/suites/nereids_rules_p0/mv/join/left_outer/outer_join.groovy
  regression-test/suites/nereids_rules_p0/mv/ssb/ddl/customer_create.sql
  regression-test/suites/nereids_rules_p0/mv/ssb/ddl/customer_delete.sql
  regression-test/suites/nereids_rules_p0/mv/ssb/ddl/date_create.sql
  regression-test/suites/nereids_rules_p0/mv/ssb/ddl/date_delete.sql
  regression-test/suites/nereids_rules_p0/mv/ssb/ddl/lineorder_create.sql
  regression-test/suites/nereids_rules_p0/mv/ssb/ddl/lineorder_delete.sql
  regression-test/suites/nereids_rules_p0/mv/ssb/ddl/lineorder_flat_create.sql
  regression-test/suites/nereids_rules_p0/mv/ssb/ddl/lineorder_flat_delete.sql
  regression-test/suites/nereids_rules_p0/mv/ssb/ddl/part_create.sql
  regression-test/suites/nereids_rules_p0/mv/ssb/ddl/part_delete.sql
  regression-test/suites/nereids_rules_p0/mv/ssb/ddl/supplier_create.sql
  regression-test/suites/nereids_rules_p0/mv/ssb/ddl/supplier_delete.sql
  regression-test/suites/nereids_rules_p0/mv/ssb/mv_ssb_test.groovy
Labels: approved, reviewed

#30682 [doc](partial update) update plan of flexible column updates
  docs/en/docs/data-operate/update-delete/partial-update.md
  docs/zh-CN/docs/data-operate/update-delete/partial-update.md
Labels: approved, reviewed

#30684 [fix](Nereids): fix offset in PlanTranslator (#29789)
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/PhysicalPlanTranslator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/AddOffsetIntoDistribute.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/PlanPostProcessors.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/DistributionSpec.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalDistribute.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalLimit.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/util/PlanChecker.java
Labels: area/nereids

#30459 [fix](Nereids) add logical project to prevent extra wrong column
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/SubqueryToApply.java
  regression-test/data/nereids_syntax_p0/sub_query_diff_old_optimize.out
  regression-test/suites/nereids_syntax_p0/sub_query_diff_old_optimize.groovy
Labels: approved, reviewed

#30599 [enhance](mtmv)use version instead of timestamp
  fe/fe-core/src/main/java/org/apache/doris/alter/Alter.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/MTMV.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/external/HMSExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/job/extensions/mtmv/MTMVTask.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVMaxTimestampSnapshot.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVRefreshPartitionSnapshot.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVRefreshSnapshot.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVRelatedTableIf.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVSnapshotIf.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVTimestampSnapshot.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVUtil.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVVersionSnapshot.java
  fe/fe-core/src/main/java/org/apache/doris/persist/AlterMTMV.java
  fe/fe-core/src/main/java/org/apache/doris/persist/gson/GsonUtils.java
Labels: approved, reviewed

#30592 [improve](catalog recycle bin) show data size info when show catalog recycle bin
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowCatalogRecycleBinStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/CatalogRecycleBin.java
  regression-test/data/catalog_recycle_bin_p0/all_types.csv.gz
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
  regression-test/suites/catalog_recycle_bin_p0/show.groovy
  regression-test/suites/correctness_p0/test_bugfix_block_reuse.groovy
  regression-test/suites/correctness_p0/test_many_inlineview.groovy
Labels: reviewed, dev/2.0.5

#30679 [chore](debug) check the const exprs count in union node
  be/src/pipeline/exec/union_source_operator.cpp
  be/src/vec/exec/vunion_node.cpp
Labels: approved, reviewed

#30688 [enhancement](paimon)support predict for null and notnull
  fe/fe-core/src/main/java/org/apache/doris/planner/external/paimon/PaimonPredicateConverter.java
Labels: area/planner

#30689 [bugfix](iceberg)fix read NULL with date partition
  fe/fe-core/src/main/java/org/apache/doris/planner/external/iceberg/IcebergScanNode.java
  regression-test/data/external_table_p2/iceberg/test_external_catalog_iceberg_partition.out
  regression-test/suites/external_table_p2/iceberg/test_external_catalog_iceberg_partition.groovy
Labels: area/planner, kind/test

#30685 [fix](Nereids): add def in test (#29796)
  regression-test/suites/nereids_p0/expression/case_when_to_if.groovy
  regression-test/suites/nereids_p0/expression/topn_to_max.groovy
Labels: kind/test

#30698 [docs][fix] Fix invalid link and name of Doris Streamloader-Branch 2.0
  docs/en/docs/data-operate/import/import-way/stream-load-manual.md
  docs/en/docs/ecosystem/doris-streamloader.md
  docs/zh-CN/docs/data-operate/import/import-way/stream-load-manual.md
  docs/zh-CN/docs/ecosystem/doris-streamloader.md
Labels: kind/docs

#30696 [docs](fix) Fix invalid link and unified name of Doris Streamloader
  docs/en/docs/data-operate/import/import-way/stream-load-manual.md
  docs/en/docs/ecosystem/doris-streamloader.md
  docs/zh-CN/docs/data-operate/import/import-way/stream-load-manual.md
  docs/zh-CN/docs/ecosystem/doris-streamloader.md
Labels: approved, reviewed

#30699 [bugfix](paimon)fix paimon testcases
  be/src/vec/exec/format/orc/vorc_reader.cpp
  be/src/vec/exec/format/orc/vorc_reader.h
  be/src/vec/exec/scan/vfile_scanner.cpp
  fe/fe-core/src/main/java/org/apache/doris/planner/external/paimon/PaimonValueConverter.java
  regression-test/data/external_table_p0/paimon/test_paimon_catalog.out
  regression-test/suites/external_table_p0/paimon/test_paimon_catalog.groovy
  regression-test/suites/external_table_p2/paimon/paimon_timestamp_types.groovy
Labels: area/planner, kind/test

#30700 [fix](decimal) fix arithmetic overflow error of casting decimal null values
  be/src/vec/functions/function_cast.h
Labels: approved, reviewed, dev/2.0.5

#30678 [fix](invert index) fixed the issue of insufficient index idx generat…
  be/src/exec/tablet_info.cpp
  be/src/vec/functions/match.cpp
  regression-test/data/fault_injection_p0/test_index_mow_fault_injection.out
  regression-test/suites/fault_injection_p0/test_index_mow_fault_injection.groovy
Labels: approved, reviewed

#30694 [bugfix](paimon)support native and jni to read paimon for minio/cos
  docs/en/docs/lakehouse/multi-catalog/paimon.md
  docs/zh-CN/docs/lakehouse/multi-catalog/paimon.md
  fe/fe-core/src/main/java/org/apache/doris/datasource/paimon/PaimonFileExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/constants/PaimonProperties.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/paimon/PaimonScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  regression-test/data/external_table_p2/paimon/paimon_base_filesystem.out
  regression-test/suites/external_table_p2/paimon/paimon_base_filesystem.groovy
Labels: kind/docs, area/planner, kind/test

#30650 [Fix](nereids)Disable getting partition related table and column when self join
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/MaterializedViewUtils.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/exploration/mv/MaterializedViewUtilsTest.java
Labels: approved, reviewed

#30455 [fix](routine-load) update partition offset cache timely to avoid negative lag
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/KafkaRoutineLoadJob.java
Labels: approved, reviewed, dev/2.0.5

#30454 [log](rpc) print log when offer_failed in internal service
  be/src/service/internal_service.cpp
Labels: approved, reviewed

#30432 [improve](stream-load) add observability on receiving HTTP request
  be/src/http/action/stream_load.cpp
  be/src/runtime/stream_load/stream_load_context.h
  be/src/runtime/stream_load/stream_load_executor.cpp
Labels: approved, reviewed, dev/2.0.5

#29067 [fix](outfile) fix outfile csv did not write json column with string
  be/src/vec/data_types/serde/data_type_jsonb_serde.cpp
  regression-test/data/export_p0/test_outfile_csv_with_names.out
  regression-test/suites/export_p0/test_outfile_csv_with_names.groovy
Labels: approved, reviewed, dev/2.0.5-merged

#30677 [improve](backup) Skip all backup/restore jobs if max allowd option is set to 0
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupHandler.java
Labels: approved, reviewed, usercase, dev/2.0.5

#30161 [BugFix](MultiCatalog) Iceberg table get split fail when use date type conjunct
  fe/fe-core/src/main/java/org/apache/doris/analysis/DateLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/external/iceberg/util/IcebergUtils.java
Labels: area/planner

#30531 [improve](test) fix regression test case report error when run times
  regression-test/data/query_p0/sql_functions/aggregate_functions/test_aggregate_all_functions2.out
  regression-test/suites/javaudf_p0/test_javaudf_int.groovy
  regression-test/suites/query_p0/sql_functions/aggregate_functions/test_aggregate_all_functions2.groovy
Labels: approved, reviewed, dev/2.0.5

#30511 [refacotr](node) refactor partition sort node to improve readability
  be/src/pipeline/exec/partition_sort_sink_operator.cpp
  be/src/pipeline/exec/partition_sort_sink_operator.h
  be/src/pipeline/exec/partition_sort_source_operator.cpp
  be/src/pipeline/pipeline_x/dependency.h
  be/src/vec/common/sort/partition_sorter.cpp
  be/src/vec/common/sort/partition_sorter.h
  be/src/vec/exec/vpartition_sort_node.cpp
  be/src/vec/exec/vpartition_sort_node.h
Labels: approved, reviewed

#30595 [fix](multi-catalog)access HMS need ugiDoAs
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/ThriftHMSCachedClient.java
Labels: approved, reviewed, usercase, dev/2.0.5

#30452 [enhance](function) refactor from_format_str and support more format
  be/src/vec/functions/function.cpp
  be/src/vec/functions/function.h
  be/src/vec/functions/function_bitmap.cpp
  be/src/vec/functions/nullif.cpp
  be/src/vec/runtime/vdatetime_value.cpp
  be/src/vec/runtime/vdatetime_value.h
  be/test/vec/function/function_array_index_test.cpp
  be/test/vec/function/function_test_util.h
  docs/en/docs/sql-manual/sql-functions/date-time-functions/date-format.md
  docs/zh-CN/docs/sql-manual/sql-functions/date-time-functions/date-format.md
  fe/fe-core/src/main/java/org/apache/doris/analysis/DateLiteral.java
  regression-test/data/correctness/test_str_to_date.out
  regression-test/data/datatype_p0/date/test_invalid_date.out
  regression-test/suites/correctness/test_str_to_date.groovy
  regression-test/suites/datatype_p0/date/test_invalid_date.groovy
Labels: approved, reviewed

#30711 [chore](ci) trigger a must success pipeline
  .github/workflows/comment-to-trigger-teamcity.yml
  regression-test/pipeline/common/teamcity-utils.sh
Labels: approved, reviewed

#30683 [Opt](exec) opt the repeat node code
  be/src/pipeline/exec/repeat_operator.cpp
  be/src/vec/columns/column_vector.h
  be/src/vec/exec/vrepeat_node.cpp
Labels: approved, reviewed

#30286 [Fix](JDK17) Fixed that BE could not be started using JDK17
  fe/be-java-extensions/preload-extensions/pom.xml
Labels: approved, reviewed

#30693 [opt](exec) change string ser der way to improve performance
  be/src/vec/data_types/data_type_string.cpp
Labels: approved, reviewed

#30687 [Refactor](executor)Remove useless statistics report path
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/pipeline/pipeline_x/pipeline_x_fragment_context.cpp
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/plan_fragment_executor.cpp
  be/src/runtime/query_context.h
  gensrc/thrift/FrontendService.thrift
Labels: reviewed, meta-change, workload-schedule

#30718 [Fix](group commit) Fix pre allocated err handling for group commit async load and add regression test
  be/src/olap/wal/wal_manager.cpp
  be/src/olap/wal/wal_manager.h
  be/src/runtime/group_commit_mgr.cpp
  be/src/runtime/group_commit_mgr.h
  be/src/vec/sink/group_commit_block_sink.cpp
  regression-test/data/fault_injection_p0/group_commit_wal_msg.csv
  regression-test/suites/fault_injection_p0/test_group_commit_async_wal_msg_fault_injection.groovy
Labels: reviewed

#30654 [Fix](doc) Fix word spelling errors
  docs/zh-CN/docs/admin-manual/workload-group.md
Labels: approved, reviewed

#30392 [Enhancement](function)make SUBSTRING_INDEX function DEPEND_ON_ARGUMENT
  be/src/agent/be_exec_version_manager.h
  be/src/vec/functions/function_string.cpp
  be/src/vec/functions/function_string.h
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/SubstringIndex.java
  gensrc/script/doris_builtins_functions.py
Labels: approved, reviewed

#30738 [fix](orc) be crash while read orc with mismatch types
  be/src/vec/exec/format/orc/vorc_reader.cpp
Labels: area/vectorization

#30611 [revert](move-memtable) Revert enable brpc debug log in regression pelines (#30389)
  be/src/common/logging.h
  regression-test/pipeline/external/conf/be.conf
  regression-test/pipeline/p0/conf/be.conf
  regression-test/pipeline/p1/conf/be.conf
Labels: approved, reviewed

#30735 [fix](mtmv)compatibility metadata without refreshsnapshot
  fe/fe-core/src/main/java/org/apache/doris/catalog/MTMV.java
Labels: approved, reviewed

#30702 [fix](merge-cloud) Ignore in_memory property in cloud mode
  fe/fe-core/src/main/java/org/apache/doris/cloud/common/util/CloudPropertyAnalyzer.java
Labels: approved, reviewed

#30593 [Feature](Job)STARTS and AT allow setting current_timestamp
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateJobStmt.java
  fe/fe-core/src/main/java/org/apache/doris/job/base/JobExecutionConfiguration.java
  regression-test/suites/job_p0/test_base_insert_job.groovy
Labels: approved, reviewed

#30676 [pick](nereids)do not check invisible column stats
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/PhysicalPlanTranslator.java
  regression-test/suites/nereids_p0/forbid_unknown_col_stats.groovy
Labels: kind/test, area/nereids

#30152 [Feature](runtime filter) normalize ignore runtime filter
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/exprs/create_predicate_function.h
  be/src/exprs/minmax_predicate.h
  be/src/exprs/runtime_filter.h
  be/src/olap/accept_null_predicate.h
  be/src/olap/bitmap_filter_predicate.h
  be/src/olap/bloom_filter_predicate.h
  be/src/olap/column_predicate.h
  be/src/olap/comparison_predicate.h
  be/src/olap/in_list_predicate.h
  be/src/olap/like_column_predicate.cpp
  be/src/olap/like_column_predicate.h
  be/src/olap/match_predicate.h
  be/src/olap/null_predicate.cpp
  be/src/olap/null_predicate.h
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/vec/exprs/vruntimefilter_wrapper.cpp
  be/src/vec/exprs/vruntimefilter_wrapper.h
  be/test/olap/bitmap_filter_column_predicate_test.cpp
  docs/en/docs/query-acceleration/join-optimization/runtime-filter.md
  docs/zh-CN/docs/query-acceleration/join-optimization/runtime-filter.md
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  regression-test/data/variable_p0/set_and_unset_variable.out
Labels: approved, reviewed

#30752 [chore](ci) try to set 'performance (Doris Performance)' to required
  .asf.yaml
Labels: approved, reviewed

#30755 [chore](ci) revert "try to set 'performance (Doris Performance)' to required #30752"
  .asf.yaml
Labels: approved, reviewed

#30757 [fix](Nereids) add logical project to prevent extra wrong column
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/SubqueryToApply.java
  regression-test/data/nereids_syntax_p0/sub_query_diff_old_optimize.out
  regression-test/suites/nereids_syntax_p0/sub_query_diff_old_optimize.groovy
Labels: kind/test, area/nereids

#30758 [fix](nereids)need substitute agg function using agg node's output if it's in order by key
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/FillUpMissingSlots.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/analysis/FillUpMissingSlotsTest.java
Labels: area/nereids

#30691 [pick](nereids) fix bug in case-when/if stats estimation (pick30265)
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/ExpressionEstimation.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/stats/ExpressionEstimationTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/stats/FilterEstimationTest.java
Labels: area/nereids

#30737 [fix](merge-cloud) Ignore uninit cloud delta writers
  be/src/cloud/cloud_tablets_channel.cpp
  be/src/cloud/cloud_tablets_channel.h
  be/src/runtime/tablets_channel.cpp
Labels: approved, reviewed

#30659 [Bug](pipeline) fix pipeline task execute without wait second start rpc
  be/src/pipeline/pipeline_task.cpp
  be/src/pipeline/pipeline_task.h
Labels: approved, reviewed, dev/2.0.5

#30750 [fix](move-memtable) use signed integer when calculating remain ms
  be/src/vec/sink/writer/vtablet_writer_v2.cpp
Labels: approved, reviewed

#30749 [enhencement](config) change default write buffer size
  be/src/common/config.cpp
  be/src/common/config.h
Labels: approved, reviewed, dev/2.1.0

#30720 [Bug](java-udf) fix core dump when javaudf input 0 row block
  be/src/olap/schema_change.cpp
  be/src/vec/exec/jni_connector.cpp
  fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateMaterializedViewStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/MaterializedIndexMeta.java
  regression-test/data/javaudf_p0/test_javaudf_float.out
  regression-test/suites/javaudf_p0/test_javaudf_float.groovy
Labels: approved, reviewed, usercase, dev/2.0.5

#30704 [fix](nereids)need substitute agg function using agg node's output if it's in order by key
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/FillUpMissingSlots.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/analysis/FillUpMissingSlotsTest.java
Labels: approved, reviewed, usercase, dev/2.0.5-merged

#30740 [feature](merge-cloud) Init calc delete bitmap executor for cloud storage engine
  be/src/cloud/cloud_rowset_builder.cpp
  be/src/cloud/cloud_storage_engine.cpp
  be/src/olap/storage_engine.cpp
  be/src/olap/storage_engine.h
  be/src/vec/core/block.cpp
Labels: approved, reviewed

#30770 [feature](binlog) Add show proc '/binlog' impl
  fe/fe-core/src/main/java/org/apache/doris/binlog/BinlogConfigCache.java
  fe/fe-core/src/main/java/org/apache/doris/binlog/BinlogManager.java
  fe/fe-core/src/main/java/org/apache/doris/binlog/BinlogUtils.java
  fe/fe-core/src/main/java/org/apache/doris/binlog/DBBinlog.java
  fe/fe-core/src/main/java/org/apache/doris/binlog/TableBinlog.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/BinlogProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/ProcService.java
Labels: approved, reviewed

#30588 [improvement](jdbc catalog) Optimize connection pool parameter settings
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/runtime/descriptors.cpp
  be/src/runtime/descriptors.h
  be/src/vec/exec/scan/new_jdbc_scanner.cpp
  be/src/vec/exec/vjdbc_connector.cpp
  be/src/vec/exec/vjdbc_connector.h
  be/src/vec/sink/writer/vjdbc_table_writer.cpp
  fe/be-java-extensions/jdbc-scanner/src/main/java/org/apache/doris/jdbc/JdbcDataSource.java
  fe/be-java-extensions/jdbc-scanner/src/main/java/org/apache/doris/jdbc/JdbcDataSourceConfig.java
  fe/be-java-extensions/jdbc-scanner/src/main/java/org/apache/doris/jdbc/JdbcExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/JdbcResource.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/JdbcTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Resource.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/ResourceMgr.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/external/JdbcExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/JdbcExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/client/JdbcClient.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/client/JdbcClientConfig.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/JdbcResourceTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/jdbc/JdbcExternalCatalogTest.java
  fe/pom.xml
  gensrc/thrift/Descriptors.thrift
  gensrc/thrift/Types.thrift
Labels: approved, reviewed, meta-change

#30736 [fix](regression) Make catalog recycle bin regression stable
  regression-test/suites/catalog_recycle_bin_p0/show.groovy
Labels: approved, reviewed, dev/2.0.5

#30760 [test](Nereids): add push_down_distinct_through_join regression test
  regression-test/data/nereids_rules_p0/push_down_distinct_through_join/push_down_distinct_through_join.out
  regression-test/suites/nereids_rules_p0/push_down_distinct_through_join/push_down_distinct_through_join.groovy
Labels: approved, reviewed

#30778 [pick][improvement](catalog) fix jdbc mysql catalog to_date fun pushdown
  fe/fe-core/src/main/java/org/apache/doris/planner/external/jdbc/JdbcFunctionPushDownRule.java
  regression-test/data/external_table_p0/jdbc/test_mysql_jdbc_catalog.out
  regression-test/suites/external_table_p0/jdbc/test_mysql_jdbc_catalog.groovy
Labels: area/planner, kind/test

#30773 [Fix](ser) serialize bitmap/hll some not fixed length object maybe over INT_MAX
  be/src/vec/data_types/data_type_bitmap.cpp
  be/src/vec/data_types/data_type_hll.cpp
  be/src/vec/data_types/data_type_quantilestate.cpp
Labels: approved, reviewed, usercase, dev/2.0.5

#30779 [Fix](Job)Fix One-Time type JOB parameter verification error
  fe/fe-core/src/main/java/org/apache/doris/job/base/JobExecutionConfiguration.java
  fe/fe-core/src/test/java/org/apache/doris/job/base/JobExecutionConfigurationTest.java
  regression-test/suites/job_p0/test_base_insert_job.groovy
Labels: approved, reviewed

#30328 [fix](legacy-planner) fixed loss of BetweenPredicate rewrite on reana…
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
  regression-test/data/query_p0/having/having_between.out
  regression-test/suites/query_p0/having/having_between.groovy
Labels: approved, reviewed, dev/2.0.5

#30641 [doc](jdbc catalog) add connection pool doc
  docs/en/docs/lakehouse/multi-catalog/jdbc.md
  docs/zh-CN/docs/lakehouse/multi-catalog/jdbc.md
Labels: approved, reviewed

#30765 [fix](Nereids) date >= simplify to > by mistake
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/DateFunctionRewrite.java
Labels: approved, reviewed, usercase, p0_w, dev/2.0.5-merged

#30764 [fix](compile) be cannot compile on MacOS (#26155)
  be/src/vec/common/memcmp_small.h
  be/src/vec/common/memcpy_small.h
  be/src/vec/common/string_utils/string_utils.cpp
  be/src/vec/common/string_utils/string_utils.h
Labels: approved, reviewed

#30741 [Doc](auto-inc) Add doc for auto increment start value
  docs/en/docs/advanced/auto-increment.md
  docs/en/docs/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-TABLE.md
  docs/zh-CN/docs/advanced/auto-increment.md
  docs/zh-CN/docs/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-TABLE.md
Labels: approved, reviewed

#30731 [Fix](multi-catalog) Fix truncate_char_or_varchar_column crash.
  be/src/vec/exec/scan/vfile_scanner.cpp
Labels: approved, reviewed, p0_c, dev/2.1.0

#30739 [fix](insert into) 'output_tuple_slot_num should be equal to output_expr_num' when insert into unique table with sequence column map
  fe/fe-core/src/main/java/org/apache/doris/analysis/NativeInsertStmt.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
  regression-test/suites/correctness_p0/test_sequence_col_default_value.groovy
Labels: area/planner, kind/test, approved, reviewed

#30716 [Fix](parquet-reader) Fix decimal test case out files.
  regression-test/data/external_table_p0/hive/test_hive_parquet.out
Labels: approved, reviewed

#30734 [Fix](Nereids) Fix rewrite by materialized view fail when join input has agg
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewAggregateRule.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewJoinRule.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/StructInfo.java
  regression-test/data/nereids_rules_p0/mv/join/dphyp_outer/outer_join_dphyp.out
  regression-test/data/nereids_rules_p0/mv/join/left_outer/outer_join.out
  regression-test/suites/nereids_rules_p0/mv/join/dphyp_outer/outer_join_dphyp.groovy
  regression-test/suites/nereids_rules_p0/mv/join/left_outer/outer_join.groovy
Labels: approved, reviewed

#30710 [Fix](json) avoid print warn log when parse failed (#30656)
  be/src/runtime/jsonb_value.cpp
  be/src/util/jsonb_parser_simd.h
Labels: reviewed

#30460 [fix](rowset writer) check segment num when build rowset meta
  be/src/cloud/cloud_rowset_writer.cpp
  be/src/olap/rowset/beta_rowset_writer.cpp
  be/src/olap/rowset/beta_rowset_writer.h
Labels: approved, reviewed, dev/2.0.5

#30771 [improvement](binlog) Change BinlogConfig default TTL_SECONDS to 86400 (1day)
  fe/fe-core/src/main/java/org/apache/doris/catalog/BinlogConfig.java
  regression-test/data/insert_p0/test_group_commit_interval_ms_property.out
  regression-test/data/query_p0/show/test_show_create_table.out
  regression-test/data/show_p0/test_show_create_table_and_views.out
Labels: approved, reviewed

#30443 [bug](function) fix date_sub function failed when arg type is datev2
  fe/fe-core/src/main/java/org/apache/doris/analysis/TimestampArithmeticExpr.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/FEFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/FoldConstantsRule.java
  regression-test/suites/delete_p0/test_delete.groovy
Labels: approved, reviewed, usercase, dev/2.0.5

#30717 [cherry-pick] Cherry-pick report runtime workload statistics
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/common/daemon.cpp
  be/src/common/daemon.h
  be/src/exec/data_sink.cpp
  be/src/exec/data_sink.h
  be/src/exec/exec_node.cpp
  be/src/exec/exec_node.h
  be/src/pipeline/exec/exchange_sink_buffer.cpp
  be/src/pipeline/exec/exchange_sink_buffer.h
  be/src/pipeline/exec/exchange_sink_operator.cpp
  be/src/pipeline/exec/operator.h
  be/src/pipeline/pipeline.h
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/pipeline/pipeline_fragment_context.h
  be/src/pipeline/pipeline_task.cpp
  be/src/pipeline/pipeline_task.h
  be/src/runtime/buffer_control_block.cpp
  be/src/runtime/buffer_control_block.h
  be/src/runtime/exec_env.h
  be/src/runtime/exec_env_init.cpp
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/fragment_mgr.h
  be/src/runtime/memory/mem_tracker.h
  be/src/runtime/memory/mem_tracker_limiter.cpp
  be/src/runtime/plan_fragment_executor.cpp
  be/src/runtime/plan_fragment_executor.h
  be/src/runtime/query_context.h
  be/src/runtime/query_statistics.cpp
  be/src/runtime/query_statistics.h
  be/src/runtime/runtime_query_statistics_mgr.cpp
  be/src/runtime/runtime_query_statistics_mgr.h
  be/src/vec/exec/scan/new_olap_scan_node.cpp
  be/src/vec/exec/scan/new_olap_scan_node.h
  be/src/vec/exec/scan/vscan_node.cpp
  be/src/vec/exec/scan/vscanner.cpp
  be/src/vec/exec/scan/vscanner.h
  be/src/vec/exec/vexchange_node.cpp
  be/src/vec/exec/vexchange_node.h
  be/src/vec/runtime/vdata_stream_mgr.cpp
  be/src/vec/runtime/vdata_stream_mgr.h
  be/src/vec/runtime/vdata_stream_recvr.cpp
  be/src/vec/runtime/vdata_stream_recvr.h
  be/src/vec/sink/vdata_stream_sender.cpp
  be/src/vec/sink/vdata_stream_sender.h
  be/src/vec/sink/vresult_file_sink.cpp
  be/src/vec/sink/vresult_file_sink.h
  be/src/vec/sink/vresult_sink.cpp
  be/src/vec/sink/vresult_sink.h
  be/test/vec/runtime/vdata_stream_test.cpp
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/plugin/AuditEvent.java
  fe/fe-core/src/main/java/org/apache/doris/qe/AuditLogHelper.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/QeProcessorImpl.java
  fe/fe-core/src/main/java/org/apache/doris/resource/workloadschedpolicy/WorkloadRuntimeStatusMgr.java
  gensrc/thrift/FrontendService.thrift
Labels: area/pipeline, workload-schedule

#30767 [feat-wip](join) support mark join for right semi join(without mark join conjunct)
  be/src/pipeline/exec/hashjoin_probe_operator.cpp
  be/src/pipeline/exec/join_build_sink_operator.cpp
  be/src/vec/common/hash_table/join_hash_table.h
  be/src/vec/exec/join/process_hash_table_probe.h
  be/src/vec/exec/join/process_hash_table_probe_impl.h
  be/src/vec/exec/join/vhash_join_node.cpp
  be/src/vec/exec/join/vjoin_node_base.cpp
Labels: approved, reviewed

#30753 [Pick](nereids) if column stats are unknown, 10-20 table-join optimization use cascading instead of dphyp (branch-2.0)
  fe/fe-core/src/main/java/org/apache/doris/nereids/StatementContext.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/Optimizer.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/StatsCalculator.java
Labels: area/nereids

#30776 [chore](Nereids) turn on nereids dml when update to 2.1
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/qe/VariableMgr.java
Labels: approved, reviewed

#30672 [feature](function) support atan2 math function
  be/src/vec/functions/math.cpp
  docs/en/docs/sql-manual/sql-functions/numeric-functions/atan2.md
  docs/sidebars.json
  docs/zh-CN/docs/sql-manual/sql-functions/numeric-functions/atan2.md
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinScalarFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Atan2.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/ScalarFunctionVisitor.java
  gensrc/script/doris_builtins_functions.py
  regression-test/data/nereids_function_p0/scalar_function/A.out
  regression-test/suites/nereids_function_p0/scalar_function/A.groovy
Labels: approved, reviewed

#27318 [enhancement](plubin)support json format and other options in logstash doris output plugin
  docs/en/docs/ecosystem/logstash.md
  docs/zh-CN/docs/ecosystem/logstash.md
  extension/logstash/lib/logstash/outputs/doris.rb
  extension/logstash/logstash-output-doris.gemspec
Labels: approved, reviewed, dev/2.0.5

#29595 [feature](mtmv)mtmv support workload group
  fe/fe-core/src/main/java/org/apache/doris/catalog/MTMV.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVPlanUtil.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/AlterMTMVPropertyInfo.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/CreateMTMVInfo.java
  regression-test/data/mtmv_p0/test_workload_group_mtmv.out
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
  regression-test/suites/mtmv_p0/test_workload_group_mtmv.groovy
Labels: approved, reviewed

#30651 [feature](test)Add mtmv basic one and two dimensional test cases
  regression-test/suites/nereids_rules_p0/mv/dimension/dimension_1.groovy
  regression-test/suites/nereids_rules_p0/mv/dimension/dimension_2_1.groovy
  regression-test/suites/nereids_rules_p0/mv/dimension/dimension_2_2.groovy
  regression-test/suites/nereids_rules_p0/mv/dimension/dimension_2_3.groovy
  regression-test/suites/nereids_rules_p0/mv/dimension/dimension_2_4.groovy
  regression-test/suites/nereids_rules_p0/mv/dimension/dimension_2_5.groovy
  regression-test/suites/nereids_rules_p0/mv/dimension/dimension_2_6.groovy
Labels: approved, reviewed

#30709 [Bug](compaction) pass arena to function->add_batch_range
  be/src/vec/olap/vertical_block_reader.cpp
  be/src/vec/olap/vertical_block_reader.h
  regression-test/data/compaction/test_vertical_compaction_agg_state.out
  regression-test/suites/compaction/test_vertical_compaction_agg_state.groovy
Labels: approved, reviewed, usercase, dev/2.0.5

#30780 [Fix](ser) serialize bitmap/hll some not fixed length object maybe over INT_MAX
  be/src/vec/data_types/data_type_bitmap.cpp
  be/src/vec/data_types/data_type_hll.cpp
  be/src/vec/data_types/data_type_quantilestate.cpp
Labels: approved, reviewed

#30789 [Feature][UDF][WASM] support wasm udf
  be/cmake/thirdparty.cmake
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/runtime/exec_env.h
  be/src/runtime/exec_env_init.cpp
  be/src/runtime/user_function_cache.cpp
  be/src/runtime/user_function_cache.h
  be/src/util/wasm_manager.cpp
  be/src/util/wasm_manager.h
  be/src/vec/exprs/vectorized_agg_fn.cpp
  be/src/vec/exprs/vectorized_fn_call.cpp
  be/src/vec/functions/function_wasm.cpp
  be/src/vec/functions/function_wasm.h
  be/test/util/wasm_manager_test.cpp
  be/test/util/wasm_test.cpp
  docs/en/docs/ecosystem/udf/wasm-user-defined-function.md
  docs/zh-CN/docs/ecosystem/udf/wasm-user-defined-function.md
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateFunctionStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/ScalarFunction.java
  gensrc/thrift/Types.thrift
  regression-test/data/wasmudf_p0/test_wasmudf_float.out
  regression-test/data/wasmudf_p0/test_wasmudf_int.out
  regression-test/suites/wasmudf_p0/test_wasmudf_float.groovy
  regression-test/suites/wasmudf_p0/test_wasmudf_int.groovy
  regression-test/suites/wasmudf_p0/wat/f32_add.wat
  regression-test/suites/wasmudf_p0/wat/i32_add.wat
Labels: meta-change

#30783 [chore](mac compile) remove using regex to avoid mac compile failed frequently
  be/src/olap/delete_handler.cpp
Labels: approved, reviewed

#30787 [enhancement](backup) Add build version in backup snapshot info
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupJobInfo.java
Labels: approved, reviewed

#30675 [fix](char) fix char column type not check lenght
  fe/fe-core/src/main/java/org/apache/doris/analysis/TypeDef.java
  regression-test/suites/datatype_p0/string/test_string_basic.groovy
Labels: area/planner, kind/test, approved, reviewed

#30540 [feature](statistics)Support analyze materialized view.
  fe/fe-core/src/main/java/org/apache/doris/analysis/AnalyzeTblStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/DropStatsStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowAnalyzeTaskStatus.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowColumnStatsStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Table.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/TableIf.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/external/ExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/minidump/MinidumpUtils.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/BindRelation.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/StatsCalculator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalOlapScan.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisInfo.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisJob.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisManager.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/BaseAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/ExternalAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/OlapAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/OlapScanStatsDerive.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsAutoCollector.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsCache.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsCacheKey.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsCleaner.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsRepository.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/util/StatisticsUtil.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/CacheTest.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/HMSAnalysisTaskTest.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/OlapAnalysisTaskTest.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/StatisticsAutoCollectorTest.java
  regression-test/suites/external_table_p0/hive/test_hive_statistics_all_type_p0.groovy
  regression-test/suites/external_table_p0/hive/test_hive_statistics_p0.groovy
  regression-test/suites/external_table_p0/jdbc/test_mysql_jdbc_statistics.groovy
  regression-test/suites/external_table_p2/hive/test_hive_statistic.groovy
  regression-test/suites/external_table_p2/hive/test_hive_statistic_auto.groovy
  regression-test/suites/external_table_p2/hive/test_hive_statistic_cache.groovy
  regression-test/suites/external_table_p2/hive/test_hive_statistic_clean.groovy
  regression-test/suites/external_table_p2/hive/test_hive_statistic_sample.groovy
  regression-test/suites/external_table_p2/hive/test_hive_statistics_from_hms.groovy
  regression-test/suites/statistics/analyze_stats.groovy
  regression-test/suites/statistics/test_agg_complex_type.groovy
  regression-test/suites/statistics/test_analyze_mv.groovy
  regression-test/suites/statistics/test_basic_statistics.groovy
Labels: approved, reviewed, dev/2.0.5

#30769 [Test](nereids) Add materialized view availability regression test
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/StructInfo.java
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
  regression-test/suites/nereids_rules_p0/mv/agg_with_roll_up/aggregate_with_roll_up.groovy
  regression-test/suites/nereids_rules_p0/mv/agg_without_roll_up/aggregate_without_roll_up.groovy
  regression-test/suites/nereids_rules_p0/mv/availability/grace_period.groovy
  regression-test/suites/nereids_rules_p0/mv/availability/materialized_view_switch.groovy
  regression-test/suites/nereids_rules_p0/mv/join/dphyp_inner/inner_join_dphyp.groovy
  regression-test/suites/nereids_rules_p0/mv/join/dphyp_outer/outer_join_dphyp.groovy
  regression-test/suites/nereids_rules_p0/mv/join/inner/inner_join.groovy
  regression-test/suites/nereids_rules_p0/mv/join/left_outer/outer_join.groovy
  regression-test/suites/nereids_rules_p0/mv/ssb/mv_ssb_test.groovy
Labels: approved, reviewed

#30494 [regression-test][conf] add master_sync_policy = WRITE_NO_SYNC replic…
  regression-test/pipeline/p0/conf/fe.conf
Labels: approved, reviewed, dev/2.0.5

#30451 [fix](analyze) keep threads in pool alive to maintain reasonable parallelism
  fe/fe-core/src/main/java/org/apache/doris/common/ThreadPoolManager.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisManager.java
Labels: approved, reviewed, dev/2.0.5

#30657 [fix](function) fix error result in time_to_sec and timediff (#30248)
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/TimeToSec.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/FEFunctions.java
  fe/fe-core/src/test/java/org/apache/doris/rewrite/FEFunctionsTest.java
  gensrc/script/doris_builtins_functions.py
  regression-test/data/correctness/test_time_function.out
  regression-test/suites/correctness/test_time_function.groovy
Labels: kind/test, area/nereids

#30795 Revert "[dep](thirdparty) import wasmtime library (#30591)"
  thirdparty/CHANGELOG.md
  thirdparty/build-thirdparty.sh
  thirdparty/vars.sh
Labels: approved, reviewed

#30806 [fix](Nereids) query mv column directly (#30444)
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalOlapScan.java
  regression-test/suites/statistics/test_select_mv.groovy
Labels: kind/test, area/nereids

#30812 [doc](statistics)Update docs for statistics (#29926)
  docs/en/docs/query-acceleration/statistics.md
  docs/zh-CN/docs/query-acceleration/statistics.md
Labels: kind/docs

#30174 [fix][security] BE log exists print sensitive msg
  be/src/olap/task/engine_clone_task.cpp
  be/src/olap/task/engine_clone_task.h
Labels: area/nereids

#30172 [Fix][security] The doris_be file has too big permission should be re…
  bin/start_be.sh
Labels: approved, reviewed

#30763 [Feature](executor)Stream load support workload group
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
Labels: approved, reviewed, workload-group

#30814 [Fix](Nereids) Fix datatype length wrong when string contains chinese (#29885)
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/StringLikeLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/Utils.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/util/UtilsTest.java
Labels: area/nereids

#30708 [chore](3rd) update CRoaring bitmap version to 2.1.2
  thirdparty/vars.sh
Labels: approved, reviewed

#30791 [cherry-pick](function) fix date_sub function failed when arg type is datev2 (#30443)
  fe/fe-core/src/main/java/org/apache/doris/analysis/DeleteStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/TimestampArithmeticExpr.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/FEFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/FoldConstantsRule.java
  regression-test/suites/delete_p0/test_delete.groovy
Labels: area/planner, kind/test

#30792 [Bug](pipeline) fix pipeline task execute without wait second start rpc (#30659)
  be/src/pipeline/pipeline_task.cpp
  be/src/pipeline/pipeline_task.h
Labels: area/pipeline

#30815 Pick "[fix](Cooldown) enhance the policy existence check logic when drop storage policy #30404"
  fe/fe-core/src/main/java/org/apache/doris/policy/PolicyMgr.java
  regression-test/suites/cold_heat_separation/policy/drop.groovy
Labels: kind/test

#30808 [test](mtmv)fix table name duplicate
  regression-test/suites/nereids_rules_p0/mv/dimension/dimension_2_4.groovy
  regression-test/suites/nereids_rules_p0/mv/dimension/dimension_2_5.groovy
  regression-test/suites/nereids_rules_p0/mv/dimension/dimension_2_6.groovy
Labels: approved, reviewed

#30796 [ehmancement](binlog) Add show proc '/binlog' impl (#30770)
  fe/fe-core/src/main/java/org/apache/doris/binlog/BinlogConfigCache.java
  fe/fe-core/src/main/java/org/apache/doris/binlog/BinlogManager.java
  fe/fe-core/src/main/java/org/apache/doris/binlog/BinlogUtils.java
  fe/fe-core/src/main/java/org/apache/doris/binlog/DBBinlog.java
  fe/fe-core/src/main/java/org/apache/doris/binlog/TableBinlog.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/BinlogProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/ProcService.java
Labels: approved, reviewed

#30802 [improve](log) print query_id when fold constant on BE
  be/src/runtime/fold_constant_executor.cpp
  be/src/vec/exec/vpartition_sort_node.cpp
Labels: approved, reviewed

#30743 [Enhancement](fuction) change function REPEAT nullable mode
  be/src/vec/functions/function_string.cpp
  be/src/vec/functions/function_string.h
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Repeat.java
  gensrc/script/doris_builtins_functions.py
Labels: approved, reviewed

#30790 [feature](statistics)Support analyze materialized view. #30540
  fe/fe-core/src/main/java/org/apache/doris/analysis/AnalyzeTblStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/DropStatsStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowAnalyzeTaskStatus.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowColumnStatsStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Table.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/TableIf.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/external/ExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/BindRelation.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/StatsCalculator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalOlapScan.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisInfo.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisJob.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisManager.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/BaseAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/HMSAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/OlapAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/OlapScanStatsDerive.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsAutoCollector.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsCache.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsCacheKey.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsCleaner.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsRepository.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/util/StatisticsUtil.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/CacheTest.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/HMSAnalysisTaskTest.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/OlapAnalysisTaskTest.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/StatisticsAutoCollectorTest.java
  regression-test/suites/external_table_p0/hive/test_hive_statistics_all_type_p0.groovy
  regression-test/suites/external_table_p0/hive/test_hive_statistics_p0.groovy
  regression-test/suites/external_table_p0/jdbc/test_mysql_jdbc_statistics.groovy
  regression-test/suites/external_table_p2/hive/test_hive_statistic.groovy
  regression-test/suites/external_table_p2/hive/test_hive_statistic_auto.groovy
  regression-test/suites/external_table_p2/hive/test_hive_statistic_cache.groovy
  regression-test/suites/external_table_p2/hive/test_hive_statistic_clean.groovy
  regression-test/suites/external_table_p2/hive/test_hive_statistic_sample.groovy
  regression-test/suites/external_table_p2/hive/test_hive_statistics_from_hms.groovy
  regression-test/suites/statistics/analyze_stats.groovy
  regression-test/suites/statistics/test_agg_complex_type.groovy
  regression-test/suites/statistics/test_analyze_mv.groovy
  regression-test/suites/statistics/test_basic_statistics.groovy
Labels: area/planner, kind/test, approved, reviewed, area/nereids

#30824 [fix](arrow-flight) Modify FE Arrow version to 15.0.0
  fe/pom.xml
  regression-test/framework/pom.xml
Labels: approved, reviewed

#30811 [Enhancement](group commit) Optimize group commit block sink wal disk space log
  be/src/vec/sink/group_commit_block_sink.cpp
Labels: approved, reviewed

#30730 [fix](ip) change IPv6 to little-endian byte order storage (like IPv4)
  be/src/vec/columns/column_vector.h
  be/src/vec/common/format_ip.cpp
  be/src/vec/common/format_ip.h
  be/src/vec/common/ipv6_to_binary.h
  be/src/vec/functions/function_ip.h
  be/src/vec/runtime/ip_address_cidr.h
  be/src/vec/runtime/ipv4_value.h
  be/src/vec/runtime/ipv6_value.h
  be/test/vec/runtime/ip_value_test.cpp
  regression-test/data/datatype_p0/ip/test_ip_basic.out
  regression-test/data/query_p0/sql_functions/ip_functions/test_ip_functions.out
  regression-test/suites/datatype_p0/ip/test_ip_basic.groovy
  regression-test/suites/query_p0/sql_functions/ip_functions/test_ip_functions.groovy
  regression-test/suites/query_p0/sql_functions/ip_functions/test_ipv6_cidr_to_range_function.groovy
  regression-test/suites/query_p0/sql_functions/ip_functions/test_is_ip_address_in_range_function.groovy
Labels: approved, reviewed

#30775 [enhance](mtmv)mtmv disable hive auto refresh
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/external/HMSExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/PartitionsProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/TablesProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/job/extensions/mtmv/MTMVTask.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVPartitionUtil.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVRelatedTableIf.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVRelationManager.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVRewriteUtil.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVService.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVUtil.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewRule.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/MaterializedViewUtils.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/RefreshMTMVInfo.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/MetadataGenerator.java
  fe/fe-core/src/test/java/org/apache/doris/mtmv/MTMVPartitionUtilTest.java
  fe/fe-core/src/test/java/org/apache/doris/mtmv/MTMVRefreshSnapshotTest.java
  fe/fe-core/src/test/java/org/apache/doris/mtmv/MTMVRewriteUtilTest.java
  fe/fe-core/src/test/java/org/apache/doris/mtmv/MTMVTaskTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/exploration/mv/MaterializedViewUtilsTest.java
  regression-test/data/mtmv_p0/test_hive_mtmv.out
  regression-test/suites/mtmv_p0/test_hive_mtmv.groovy
Labels: approved, reviewed

#30772 [ci](cloud) add cloud p0 pipeline
  .github/workflows/comment-to-trigger-teamcity.yml
  .licenserc.yaml
  be/src/cloud/config.h
  regression-test/pipeline/cloud_p0/clean.sh
  regression-test/pipeline/cloud_p0/conf/be_custom.conf
  regression-test/pipeline/cloud_p0/conf/fe_custom.conf
  regression-test/pipeline/cloud_p0/conf/regression-conf-custom.groovy
  regression-test/pipeline/cloud_p0/conf/session_variables.sql
  regression-test/pipeline/cloud_p0/deploy.sh
  regression-test/pipeline/cloud_p0/prepare.sh
  regression-test/pipeline/cloud_p0/run.sh
  regression-test/pipeline/common/doris-utils.sh
  regression-test/pipeline/common/github-utils.sh
  regression-test/pipeline/common/oss-utils.sh
  regression-test/pipeline/common/teamcity-utils.sh
  regression-test/pipeline/performance/prepare.sh
  regression-test/pipeline/tpch/tpch-sf100/conf/regression-conf.groovy
Labels: approved, reviewed

#30836 [Fix](executor)Fix start be core caused by query statistics report
  be/src/common/daemon.cpp
Labels: p0_c, workload-schedule, dev/2.0.5

#30833 [fix](merge-cloud) Disable memtable on sink node & unique key merge on write
  be/src/exec/data_sink.cpp
  fe/fe-core/src/main/java/org/apache/doris/cloud/common/util/CloudPropertyAnalyzer.java
Labels: approved, reviewed

#30818 [fix](Nereids) colcoate node attr lost after merge fragment
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/PlanTranslatorContext.java
  fe/fe-core/src/main/java/org/apache/doris/planner/MultiCastPlanFragment.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PlanFragment.java
  regression-test/data/nereids_p0/colocate/test_multi_cast_colocate.out
  regression-test/data/nereids_p0/colocate/test_set_operation_colocate.out
  regression-test/suites/nereids_p0/colocate/test_multi_cast_colocate.groovy
  regression-test/suites/nereids_p0/colocate/test_set_operation_colocate.groovy
Labels: approved, reviewed, p0_w, dev/2.0.5

#30816 [typo](doc) modify format
  docs/en/docs/sql-manual/sql-reference/Data-Definition-Statements/Alter/ALTER-TABLE-COLUMN.md
  docs/zh-CN/docs/sql-manual/sql-reference/Data-Definition-Statements/Alter/ALTER-TABLE-COLUMN.md
Labels: approved, reviewed

#29521 [chore](clang-tidy): add bugprone linters
  .clang-tidy
  be/src/olap/rowset/segment_creator.cpp
  be/src/service/backend_service.cpp
  be/src/vec/common/hash_table/hash_table.h
  be/src/vec/exec/format/orc/vorc_reader.cpp
  be/src/vec/exec/format/parquet/vparquet_group_reader.cpp
  be/src/vec/exec/scan/new_olap_scan_node.cpp
  be/src/vec/functions/function.cpp
Labels: approved, reviewed

#30841 [fix](Nereids) colcoate node attr lost after merge fragment (#30818)
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/PlanTranslatorContext.java
  fe/fe-core/src/main/java/org/apache/doris/planner/MultiCastPlanFragment.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PlanFragment.java
  regression-test/data/nereids_p0/colocate/test_multi_cast_colocate.out
  regression-test/data/nereids_p0/colocate/test_set_operation_colocate.out
  regression-test/suites/nereids_p0/colocate/test_multi_cast_colocate.groovy
  regression-test/suites/nereids_p0/colocate/test_set_operation_colocate.groovy
Labels: area/planner, kind/test, area/nereids

#30837 [fix](join) JoinHashTable::pre_build_idxs should be const
  be/src/vec/common/hash_table/join_hash_table.h
Labels: approved, reviewed

#30838 [fix](Nereids) physical property deriver on some node is not right (#…
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/ChildOutputPropertyDeriver.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/PhysicalProperties.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/properties/ChildOutputPropertyDeriverTest.java
Labels: area/nereids

#30831 [config](move-memtable) set StreamWait timeout default to 10min
  be/src/common/config.cpp
Labels: approved, reviewed

#30573 [improvement](load) Enable lzo & Remove dependency on Markus F.X.J. Oberhumer's lzo library
  be/CMakeLists.txt
  be/cmake/thirdparty.cmake
  be/src/exec/decompressor.cpp
  be/src/exec/decompressor.h
  be/src/exec/lzo_decompressor.cpp
  be/src/olap/utils.cpp
  be/src/pch/pch.h
  be/src/vec/exec/format/csv/csv_reader.cpp
  build.sh
  regression-test/data/load_p0/stream_load/test_compress_type.out
  regression-test/suites/load_p0/stream_load/test_compress_type.groovy
Labels: approved, reviewed, usercase, dev/2.0.5

#30797 [Feature](executor)open workload group for broker load regression test
  regression-test/pipeline/external/conf/fe.conf
Labels: approved, reviewed, workload-group

#30798 [improvement](binlog) Change BinlogConfig default TTL_SECONDS to 86400 (1day) (#30771)
  fe/fe-core/src/main/java/org/apache/doris/catalog/BinlogConfig.java
  regression-test/data/query_p0/show/test_show_create_table.out
  regression-test/data/show_p0/test_show_create_table_and_views.out
Labels: approved, reviewed

#30832 [refactor](taskqueue) remove old task scheduler based wg
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/pipeline/pipeline_fragment_context.h
  be/src/pipeline/pipeline_task.cpp
  be/src/pipeline/pipeline_task.h
  be/src/pipeline/task_queue.cpp
  be/src/pipeline/task_queue.h
  be/src/runtime/exec_env.h
  be/src/runtime/exec_env_init.cpp
  be/src/runtime/query_context.cpp
  be/src/runtime/query_context.h
  be/src/runtime/task_group/task_group.cpp
  be/src/runtime/task_group/task_group.h
  be/src/runtime/task_group/task_group_manager.cpp
  be/src/runtime/task_group/task_group_manager.h
  be/src/util/mem_info.cpp
Labels: approved, reviewed, workload-group

#30851 [chore](ci) fix the check if need to run cloud p0 and typos
  regression-test/pipeline/cloud_p0/clean.sh
  regression-test/pipeline/cloud_p0/deploy.sh
  regression-test/pipeline/cloud_p0/prepare.sh
  regression-test/pipeline/cloud_p0/run.sh
  regression-test/pipeline/common/doris-utils.sh
  regression-test/pipeline/common/github-utils.sh
  regression-test/pipeline/performance/compile.sh
  regression-test/pipeline/performance/deploy.sh
  regression-test/pipeline/performance/prepare.sh
  regression-test/pipeline/performance/run-clickbench.sh
  regression-test/pipeline/performance/run-load.sh
  regression-test/pipeline/performance/run-tpcds.sh
  regression-test/pipeline/performance/run-tpch.sh
Labels: approved, reviewed

#30855 [improvement](mtmv, statistics)Collect index row count for MTMV.
  fe/fe-core/src/main/java/org/apache/doris/catalog/TabletStatMgr.java
Labels: approved, reviewed, not-merge/2.0

#30857 [fix](rowset writer) disable check segment when build rowset meta by default
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/olap/rowset/beta_rowset_writer.cpp
Labels: approved, reviewed, dev/2.0.5

#30835 [fix](cosn) use s3 client to read cosn on BE side
  fe/fe-core/src/main/java/org/apache/doris/common/util/LocationPath.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/HiveScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/iceberg/IcebergScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/paimon/PaimonScanNode.java
  fe/fe-core/src/test/java/org/apache/doris/common/util/LocationPathTest.java
Labels: approved, reviewed, dev/2.0.5

#30830 [config](move-memtable) set LOAD_STREAM_PER_NODE default to 2
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
Labels: approved, reviewed

#30810 [fix](segcompaction) enable segcompaction by default
  be/src/common/config.cpp
  docs/en/docs/admin-manual/config/be-config.md
  docs/zh-CN/docs/admin-manual/config/be-config.md
Labels: approved, reviewed

#30825 [opt](string_to_unsigned_int) performance opt
  be/src/util/string_parser.hpp
Labels: approved, reviewed

#30793 [feature](test)Add mtmv agg under join cases
  regression-test/suites/nereids_rules_p0/mv/dimension_2_join_agg/dimension_2_join_agg.groovy
Labels: approved, reviewed

#30807 [fix](catalog) fix data_sub/data_add func pushdown in jdbcscan
  fe/fe-core/src/main/java/org/apache/doris/planner/external/jdbc/JdbcFunctionPushDownRule.java
  regression-test/data/external_table_p0/jdbc/test_mysql_jdbc_catalog.out
  regression-test/suites/external_table_p0/jdbc/test_mysql_jdbc_catalog.groovy
Labels: approved, reviewed, usercase, dev/2.0.5

#30876 [enhance](Nereids): support more DateLiteral
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/DateLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/DateTimeLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/DateTimeV2Literal.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/types/DateTimeV2Type.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/DateTimeFormatterUtils.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/expressions/literal/DateLiteralTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/expressions/literal/DateTimeLiteralTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/util/DateTimeFormatterUtilsTest.java
Labels: area/nereids

#30872 [fix](regression)Fix unstable analyze mv case. (#30859)
  regression-test/suites/statistics/test_analyze_mv.groovy
  regression-test/suites/statistics/test_select_mv.groovy
Labels: kind/test

#30761 [BugFix](MultiCatalog) Fix oss file location is not avaiable in iceberg hadoop catalog
  fe/fe-core/src/main/java/org/apache/doris/common/util/LocationPath.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/iceberg/IcebergScanNode.java
  fe/fe-core/src/test/java/org/apache/doris/common/util/LocationPathTest.java
Labels: approved, reviewed, usercase, dev/2.0.5
