Repository apache/doris, pull requests merged in 2024-10, with the labels that each got.

#41382 [fix](regression test) fix test_abort_txn_by_fe
  be/src/cloud/cloud_stream_load_executor.cpp
  regression-test/framework/src/main/groovy/org/apache/doris/regression/Config.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/SuiteCluster.groovy
  regression-test/suites/schema_change_p0/test_abort_txn_by_be.groovy
  regression-test/suites/schema_change_p0/test_abort_txn_by_be_cloud1.groovy
  regression-test/suites/schema_change_p0/test_abort_txn_by_be_cloud2.groovy
  regression-test/suites/schema_change_p0/test_abort_txn_by_be_local6.groovy
  regression-test/suites/schema_change_p0/test_abort_txn_by_fe.groovy
  regression-test/suites/schema_change_p0/test_abort_txn_by_fe_cloud4.groovy
Labels: approved, reviewed

#41515 [bugfix](brpc) Should use status to generate protobuf message, because it will encoding Backend Info
  be/src/service/internal_service.h
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41517 [chore](test)Print docker-related process information when executing kerbreos-related cases
  regression-test/suites/external_table_p0/kerberos/test_single_hive_kerberos.groovy
  regression-test/suites/external_table_p0/kerberos/test_two_hive_kerberos.groovy
Labels: approved, reviewed

#41388 [Exec](mem) Reduce the memory usage during JOIN operations
  be/src/pipeline/exec/hashjoin_build_sink.cpp
  be/src/pipeline/exec/hashjoin_build_sink.h
  be/src/pipeline/exec/join/process_hash_table_probe_impl.h
  be/src/vec/core/block.cpp
  be/src/vec/core/block.h
  be/src/vec/runtime/shared_hash_table_controller.cpp
  be/src/vec/runtime/shared_hash_table_controller.h
Labels: approved, reviewed

#41240 [Enhancement](doris-future) Support "REGR_" aggregation functions (PART II)
  be/src/vec/aggregate_functions/aggregate_function_regr_union.cpp
  be/src/vec/aggregate_functions/aggregate_function_regr_union.h
  be/src/vec/aggregate_functions/aggregate_function_simple_factory.cpp
  fe/fe-core/src/main/java/org/apache/doris/catalog/AggregateFunction.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinAggregateFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionSet.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/RegrIntercept.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/RegrSlope.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/AggregateFunctionVisitor.java
  regression-test/data/query_p0/aggregate/test_regr_intercept.out
  regression-test/data/query_p0/aggregate/test_regr_slope.out
  regression-test/suites/query_p0/aggregate/test_regr_intercept.groovy
  regression-test/suites/query_p0/aggregate/test_regr_slope.groovy
Labels: approved, reviewed

#41292 [fix](pipeline) Make all upstream tasks runnable if all tasks finishe…
  be/src/pipeline/exec/hashjoin_build_sink.cpp
  be/src/pipeline/exec/operator.h
  be/src/pipeline/exec/partitioned_aggregation_sink_operator.h
  be/src/pipeline/exec/spill_sort_sink_operator.h
  be/src/pipeline/local_exchange/local_exchange_sink_operator.cpp
  be/src/pipeline/pipeline.cpp
  be/src/pipeline/pipeline.h
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/pipeline/pipeline_fragment_context.h
  be/src/pipeline/pipeline_task.cpp
  be/src/pipeline/pipeline_task.h
  be/src/pipeline/task_scheduler.cpp
  be/src/runtime/runtime_filter_mgr.cpp
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41498 [Improvement](predicate) reduce useless check on HybridSet::find
  be/src/exprs/hybrid_set.h
  be/src/olap/in_list_predicate.h
  be/src/vec/aggregate_functions/aggregate_function_group_array_intersect.h
Labels: approved, reviewed

#39540 [Enhancement](multi-catalog) Set hdfs native client logger to glog and redirect jvm stdout/stderr logger to jni.log.
  be/src/io/hdfs_builder.cpp
  bin/start_be.sh
  bin/start_fe.sh
  fe/be-java-extensions/java-common/src/main/java/org/apache/doris/common/classloader/ScannerLoader.java
  fe/be-java-extensions/java-common/src/main/java/org/apache/doris/common/jni/utils/Log4jOutputStream.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41359 [improvement](statistics)Reduce partition column sample BE memory consumption. (#41203)
  fe/fe-core/src/main/java/org/apache/doris/statistics/BaseAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/HMSAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/OlapAnalysisTask.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/BaseAnalysisTaskTest.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/OlapAnalysisTaskTest.java
  regression-test/suites/external_table_p0/hive/test_hive_statistics_all_type_p0.groovy
Labels: kind/test

#41456 [chore](query err) fix cutting err msg incorrectly
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
Labels: approved, reviewed

#41463 [improvement](create table) add backend details to creating table failed msg
  fe/fe-core/src/main/java/org/apache/doris/common/util/DynamicPartitionUtil.java
  fe/fe-core/src/main/java/org/apache/doris/system/Backend.java
  fe/fe-core/src/main/java/org/apache/doris/system/SystemInfoService.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/CreateTableTest.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/ModifyBackendTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/CreateTableCommandTest.java
Labels: approved, reviewed

#41539 [fix](ce) Wshorten-64-to-32-error in incr_created_tasks
  be/src/pipeline/pipeline.h
Labels: approved, reviewed

#41464 [fix](nereids)do not add delta row count to BE reported row count
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/StatsCalculator.java
Labels: approved, reviewed

#41466 [fix](fe) Fix `PluginMgr.getActivePluginList` npt
  fe/fe-core/src/main/java/org/apache/doris/plugin/PluginMgr.java
Labels: approved, reviewed, p0_c, dev/3.0.x

#41543 [Chore](checks) Clang Tidy Preparation do not open build_cloud
  .github/workflows/code-checks.yml
Labels: approved, reviewed

#41386 [Enhancement](maxCompute)Implement compatibility with existing maxcompute catalogs from previous versions.
  be/src/vec/exec/jni_connector.cpp
  fe/be-java-extensions/max-compute-scanner/src/main/java/org/apache/doris/maxcompute/MaxComputeColumnValue.java
  fe/be-java-extensions/max-compute-scanner/src/main/java/org/apache/doris/maxcompute/MaxComputeJniScanner.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/maxcompute/MaxComputeExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/maxcompute/source/MaxComputeScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/constants/MCProperties.java
  fe/pom.xml
  regression-test/data/external_table_p2/maxcompute/test_external_catalog_maxcompute.out
  regression-test/data/external_table_p2/maxcompute/test_max_compute_all_type.out
  regression-test/data/external_table_p2/maxcompute/test_max_compute_complex_type.out
  regression-test/suites/external_table_p2/maxcompute/test_external_catalog_maxcompute.groovy
  regression-test/suites/external_table_p2/maxcompute/test_max_compute_all_type.groovy
  regression-test/suites/external_table_p2/maxcompute/test_max_compute_complex_type.groovy
Labels: approved, reviewed

#41542 [fix](upgrade) fix version check failure of window_funnel when upgrading
  be/src/vec/aggregate_functions/aggregate_function_window_funnel.h
Labels: approved, reviewed

#41497 [Enhancement](tvf)catalog tvf implements user permission checks and hides sensitive information
  be/src/vec/exec/scan/vmeta_scanner.cpp
  fe/fe-core/src/main/java/org/apache/doris/datasource/CatalogMgr.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/MetadataGenerator.java
  regression-test/data/external_table_p0/tvf/test_catalogs_tvf.out
  regression-test/suites/external_table_p0/tvf/test_catalogs_tvf.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41547 [Enhancement](inverted index) apply inverted index when has any
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/olap/rowset/segment_v2/segment_iterator.h
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41427 [fix] (inverted index) disable index compaction
  be/src/common/config.cpp
Labels: approved, reviewed, dev/3.0.2-merged

#41554 [fix](crash) fix be crash because of int overflow
  be/src/pipeline/task_queue.h
Labels: approved, reviewed, usercase, dev/2.1.x

#41534 [compile](minor) Fix unsafe type conversion
  be/src/pipeline/pipeline.h
  be/src/pipeline/pipeline_fragment_context.cpp
Labels: approved, reviewed

#41247 [feature](paimon)support paimon with dlf
  fe/fe-core/src/main/java/org/apache/doris/datasource/paimon/PaimonDLFExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/paimon/PaimonExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/paimon/PaimonExternalCatalogFactory.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/paimon/PaimonExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/PropertyConverter.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/constants/PaimonProperties.java
  fe/fe-core/src/main/java/org/apache/doris/persist/gson/GsonUtils.java
  regression-test/data/external_table_p2/paimon/test_paimon_dlf_catalog.out
  regression-test/suites/external_table_p2/paimon/test_paimon_dlf_catalog.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41523 [fix](test) fix unstable test_export_external_table cases
  regression-test/data/external_table_p0/export/test_export_external_table.out
  regression-test/suites/external_table_p0/export/test_export_external_table.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41525 [ubsan](PODArray)Avoid applying non-zero offset to null pointer
  be/src/vec/common/pod_array.h
Labels: approved, reviewed

#41495 [Fix](inverted index) Resolve null processing issue in arrays_overlap
  be/src/vec/functions/array/function_arrays_overlap.h
  regression-test/data/inverted_index_p0/test_array_contains_with_inverted_index.out
  regression-test/suites/inverted_index_p0/test_array_contains_with_inverted_index.groovy
Labels: approved, reviewed

#41564 [test](inverted index) fix test case for no need read data
  regression-test/suites/inverted_index_p0/test_need_read_data.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#38215 [bugfix](arrow) Fix time zone issues and accuracy issues
  be/src/pipeline/exec/memory_scratch_sink_operator.cpp
  be/src/pipeline/exec/result_sink_operator.cpp
  be/src/util/arrow/row_batch.cpp
  be/src/util/arrow/row_batch.h
  be/src/vec/runtime/vparquet_transformer.cpp
  be/test/vec/data_types/serde/data_type_serde_arrow_test.cpp
  regression-test/data/arrow_flight_sql_p0/test_select.out
  regression-test/framework/pom.xml
  regression-test/suites/arrow_flight_sql_p0/test_select.groovy
Labels: approved, reviewed, usercase, dev/2.1.x

#40947 [fix](FoldConst)The length function returns incorrect results under FoldConst.
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/executable/StringArithmetic.java
  regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy
Labels: approved, reviewed, dev/2.1.x

#41569 [Compile](fix) Fix mac complie BE error because codecvt_utf8_utf16 deprecated in C++17 and atomic_long not support in mac
  be/src/vec/exec/scan/scanner_context.h
  be/src/vec/functions/function_string.h
Labels: approved, reviewed

#41559 [chore](scan) remove useless enable_scan_node_run_serial
  be/src/runtime/runtime_state.h
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/util/StatisticsUtil.java
  gensrc/thrift/PaloInternalService.thrift
Labels: approved, reviewed, dev/3.0.x

#41565 [Fix](inverted index) add DATEV2 and DATETIMEV2 for inverted index reader
  be/src/olap/rowset/segment_v2/inverted_index_reader.h
Labels: approved, reviewed

#41567 [Enhancement](inverted index) return OK instead of not supported in expr evaluate_inverted_index
  be/src/vec/exprs/vexpr.h
  be/src/vec/functions/function.h
Labels: approved, reviewed

#41555 [local exchange](fix) Fix correctness caused by local exchange
  be/src/pipeline/exec/aggregation_sink_operator.h
  be/src/pipeline/exec/analytic_sink_operator.h
  be/src/pipeline/exec/distinct_streaming_aggregation_operator.h
  be/src/pipeline/exec/hashjoin_build_sink.h
  be/src/pipeline/exec/hashjoin_probe_operator.h
  be/src/pipeline/exec/operator.h
  be/src/pipeline/exec/partitioned_hash_join_probe_operator.h
  be/src/pipeline/exec/partitioned_hash_join_sink_operator.h
  be/src/pipeline/exec/sort_sink_operator.h
  be/src/pipeline/exec/union_sink_operator.h
  be/src/pipeline/exec/union_source_operator.h
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/pipeline/pipeline_task.h
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41548 [opt](Nereids) use 1 instead narrowest column when do column pruning
  be/src/pipeline/exec/table_function_operator.cpp
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalProject.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/jobs/joinorder/TPCHTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/ColumnPruningTest.java
  regression-test/data/nereids_rules_p0/eliminate_aggregate_constant/eliminate_aggregate_constant.out
  regression-test/data/nereids_rules_p0/eliminate_join_condition/eliminate_join_condition.out
  regression-test/data/nereids_rules_p0/filter_push_down/push_down_filter_other_condition.out
  regression-test/data/nereids_rules_p0/limit_push_down/limit_push_down.out
  regression-test/data/nereids_rules_p0/limit_push_down/order_push_down.out
  regression-test/data/nereids_rules_p0/push_down_top_n/push_down_top_n_distinct_through_join.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/shape/query90.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/rf_prune/query90.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query90.out
  regression-test/data/nereids_tpch_shape_sf1000_p0/runtime_filter/test_pushdown_setop.out
  regression-test/data/new_shapes_p0/tpcds_sf100/rf_prune/query90.out
  regression-test/data/new_shapes_p0/tpcds_sf100/shape/query90.out
  regression-test/data/new_shapes_p0/tpcds_sf1000/shape/query90.out
  regression-test/data/new_shapes_p0/tpch_sf1000/runtime_filter/test_pushdown_setop.out
Labels: approved, reviewed, dev/2.1.x

#41570 [fix](test) fix unstable test_export_external_table cases (#41523)
  regression-test/data/external_table_p0/export/test_export_external_table.out
  regression-test/suites/external_table_p0/export/test_export_external_table.groovy
Labels: reviewed

#41084 [fix](glue) support glue on aws
  fe/fe-core/src/main/java/com/amazonaws/glue/catalog/credentials/ConfigurationAWSCredentialsProvider2x.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/PropertyConverter.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/constants/GlueProperties.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/property/PropertyConverterTest.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41568 [fix](crash) fix be crash because of int overflow (#41554)
  be/src/pipeline/task_queue.h
Labels: approved, reviewed

#41142 [chore](dependencies)upgrade fe dependencies
  fe/fe-core/src/main/java/org/apache/doris/common/util/SerializationUtils.java
  fe/fe-core/src/main/java/org/apache/doris/qe/VariableMgr.java
  fe/fe-core/src/test/java/org/apache/doris/common/util/SerializationUtilsTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/iceberg/IcebergTransactionTest.java
  fe/pom.xml
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41574 [chore](plugin)It's allowed for the plugin directory to be empty when loading plugins
  fe/fe-core/src/main/java/org/apache/doris/common/util/ClassLoaderUtils.java
Labels: approved, reviewed

#41375 [fix] (inverted index) fix the error result in the query when using count on index
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/implementation/AggregateStrategies.java
  regression-test/data/inverted_index_p0/test_count_on_index_2.out
  regression-test/suites/inverted_index_p0/test_count_on_index_2.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x

#39906 Revert "[fix](inverted index) Fix Session Variable Compatibility"
  gensrc/thrift/PaloInternalService.thrift
Labels: approved, reviewed

#41592 [fix](schema scan) Finish schema scanner if limitation is reached
  be/src/pipeline/exec/schema_scan_operator.cpp
Labels: approved, reviewed

#41589 [minor](log) Delete useless logics checking
  be/src/pipeline/local_exchange/local_exchange_sink_operator.cpp
  be/src/pipeline/local_exchange/local_exchange_sink_operator.h
Labels: approved, reviewed

#41612 [ci](ga) skip scope-label
  .github/workflows/scope-label.yml
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41170 [opt](blacklist) Backend should not be added to blacklist easily
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SimpleScheduler.java
  fe/fe-core/src/test/java/org/apache/doris/qe/SimpleSchedulerTest.java
Labels: approved, reviewed

#41601 [Bug](runtime-filter) send rf when hash join build early close and add check for BloomFilterFuncBase
  be/src/exprs/bloom_filter_func.h
  be/src/pipeline/exec/hashjoin_build_sink.cpp
Labels: approved, reviewed

#41526 [enhance](parquet) support decimal256 for parquet reader
  be/src/gutil/endian.h
  be/src/util/bit_util.h
  be/src/vec/exec/format/parquet/parquet_column_convert.cpp
  be/src/vec/exec/format/parquet/parquet_column_convert.h
  be/test/util/bit_util_test.cpp
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/hdfs_tvf/test_parquet_decimal256.parquet
  regression-test/data/external_table_p0/tvf/test_hdfs_tvf.out
  regression-test/suites/external_table_p0/tvf/test_hdfs_tvf.groovy
Labels: approved, reviewed, usercase, dev/2.1.x

#41336 [bugfix](iceberg)add prefix for endpoint with s3 client
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/dlf/DLFCatalog.java
  regression-test/data/external_table_p2/iceberg/test_iceberg_dlf_catalog.out
  regression-test/suites/external_table_p2/iceberg/test_iceberg_dlf_catalog.groovy
Labels: approved, reviewed, p0_b, dev/2.1.x, dev/3.0.x

#41549 [refactor](wg&memtracker) using weak ptr to delete memtracker and query context automatically
  be/src/common/daemon.cpp
  be/src/runtime/load_channel.cpp
  be/src/runtime/load_channel.h
  be/src/runtime/memory/mem_tracker_limiter.h
  be/src/runtime/query_context.cpp
  be/src/runtime/workload_group/workload_group.cpp
  be/src/runtime/workload_group/workload_group.h
  be/src/runtime/workload_group/workload_group_manager.cpp
  be/src/runtime/workload_group/workload_group_manager.h
Labels: approved, reviewed

#41571 [Improve](array-overlaps) improve array overlaps
  be/src/vec/functions/array/function_array_index.h
  be/src/vec/functions/array/function_arrays_overlap.h
  regression-test/data/inverted_index_p0/test_array_contains_with_inverted_index.out
  regression-test/suites/inverted_index_p0/test_array_contains_with_inverted_index.groovy
Labels: approved, reviewed

#41506 [fix](parquet) fix dict page offset zero incompatible behaviour
  be/src/vec/exec/format/parquet/vparquet_column_chunk_reader.cpp
  be/src/vec/exec/format/parquet/vparquet_column_chunk_reader.h
  be/src/vec/exec/format/parquet/vparquet_column_reader.cpp
  regression-test/data/external_table_p0/tvf/test_hdfs_parquet_group0.out
  regression-test/suites/external_table_p0/tvf/test_hdfs_parquet_group0.groovy
  regression-test/suites/external_table_p0/tvf/test_hdfs_parquet_group5.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41621 [fix](jdbc) fix Unknown command(27)
  fe/fe-core/src/main/java/org/apache/doris/mysql/MysqlCommand.java
  fe/fe-core/src/main/java/org/apache/doris/qe/MysqlConnectProcessor.java
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x

#41597 [fix](conn-pool) Avoid some invalid connections returned to pool
  fe/fe-core/src/main/java/org/apache/doris/cloud/catalog/CloudTabletRebalancer.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/ProfileManager.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41529 [test](copy into) add copy into regression test case
  regression-test/suites/load_p0/copy_into/test_copy_into.groovy
Labels: approved, reviewed, dev/3.0.x

#41519 [fix](cache) fix show cache hotspot syntax error
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowCacheHotSpotStmt.java
Labels: approved, reviewed, dev/3.0.2-merged

#41468 [fix](case) ajust timeout to make case stable
  regression-test/suites/external_table_p0/hive/test_partial_update_broker_load.groovy
Labels: approved, reviewed

#40770 [chore](docker) adjust subnet in kafka.yaml.tpl to prevent conflict
  docker/thirdparties/docker-compose/kafka/kafka.yaml.tpl
Labels: approved, reviewed

#41603 [fix](case) try to drop function before create it
  regression-test/suites/javaudf_p0/function_meta/load.groovy
Labels: approved, reviewed, dev/3.0.x

#41432 [opt](inverted index) Optimize sequential phrase query logic
  be/src/olap/rowset/segment_v2/inverted_index/analyzer/analyzer.cpp
  be/src/olap/rowset/segment_v2/inverted_index/analyzer/analyzer.h
  be/src/olap/rowset/segment_v2/inverted_index/query/phrase_query.cpp
  be/src/olap/rowset/segment_v2/inverted_index/query/phrase_query.h
  be/src/olap/rowset/segment_v2/inverted_index/query/query.h
  be/src/olap/rowset/segment_v2/inverted_index_reader.cpp
  be/test/olap/rowset/segment_v2/inverted_index/query/phrase_query_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  gensrc/thrift/PaloInternalService.thrift
  regression-test/data/inverted_index_p0/test_index_match_phrase_ordered.out
  regression-test/suites/inverted_index_p0/test_index_match_phrase_ordered.groovy
Labels: approved, reviewed

#41640 [fix](jdbc) fix Unknown command(27) (#41621)
  fe/fe-core/src/main/java/org/apache/doris/mysql/MysqlCommand.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
  regression-test/suites/insert_p0/test_jdbc.groovy
Labels: kind/test

#41648 [Chore](runtime-filter) change bloom filter DCHECK to error status
  be/src/exprs/bloom_filter_func.h
Labels: approved, reviewed

#41459 [Feature](compatibility) make some agg function restrict
  be/src/agent/be_exec_version_manager.cpp
  be/src/agent/be_exec_version_manager.h
  be/src/vec/aggregate_functions/aggregate_function_covar.cpp
  be/src/vec/aggregate_functions/aggregate_function_covar.h
  be/src/vec/aggregate_functions/aggregate_function_percentile.cpp
  be/src/vec/aggregate_functions/aggregate_function_percentile.h
  be/src/vec/aggregate_functions/aggregate_function_percentile_approx.cpp
  be/src/vec/aggregate_functions/aggregate_function_percentile_approx.h
  be/src/vec/aggregate_functions/aggregate_function_stddev.cpp
  be/src/vec/aggregate_functions/aggregate_function_stddev.h
  be/src/vec/aggregate_functions/aggregate_function_window_funnel.cpp
  be/src/vec/aggregate_functions/aggregate_function_window_funnel.h
  be/test/vec/aggregate_functions/vec_window_funnel_test.cpp
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
Labels: approved, reviewed

#41331 [feat](Nereids) support set var in hint when parse sql
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/SelectHintSetVar.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/EliminateLogicalSelectHint.java
  fe/fe-core/src/test/java/org/apache/doris/qe/SessionVariablesTest.java
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x

#41605 [enhancement](util) print if using nereids planner when be coredump #31981
  be/src/common/signal_handler.h
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/query_context.h
  be/src/runtime/runtime_state.cpp
  be/src/runtime/runtime_state.h
  be/src/runtime/thread_context.cpp
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  gensrc/thrift/PaloInternalService.thrift
Labels: approved, reviewed

#40878 [feature](nereids) extend infer predicates
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Table.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/TableIf.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/Rewriter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/InferPredicateByReplace.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/InferPredicates.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PredicatePropagation.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PullUpPredicates.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/UnequalPredicateInfer.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/Like.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/Not.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/StringRegexPredicate.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/BoundFunction.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/Function.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/ScalarFunction.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/PredicateInferUtils.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/properties/UniformTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/InferPredicateByReplaceTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/PredicatePropagationTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/UnequalPredicateInferTest.java
  fe/fe-core/src/test/java/org/apache/doris/policy/PolicyTest.java
  regression-test/data/nereids_hint_tpch_p0/shape/q12.out
  regression-test/data/nereids_rules_p0/infer_predicate/extend_infer_equal_predicate.out
  regression-test/data/nereids_rules_p0/infer_predicate/infer_unequal_predicates.out
  regression-test/data/nereids_rules_p0/predicate_infer/infer_predicate.out
  regression-test/data/nereids_tpch_shape_sf1000_p0/nostats_rf_prune/q12.out
  regression-test/data/nereids_tpch_shape_sf1000_p0/rf_prune/q12.out
  regression-test/data/nereids_tpch_shape_sf1000_p0/shape/q12.out
  regression-test/data/nereids_tpch_shape_sf1000_p0/shape_no_stats/q12.out
  regression-test/data/new_shapes_p0/hint_tpch/shape/q12.out
  regression-test/data/new_shapes_p0/tpch_sf1000/nostats_rf_prune/q12.out
  regression-test/data/new_shapes_p0/tpch_sf1000/rf_prune/q12.out
  regression-test/data/new_shapes_p0/tpch_sf1000/shape/q12.out
  regression-test/data/new_shapes_p0/tpch_sf1000/shape_no_stats/q12.out
  regression-test/suites/nereids_p0/infer_predicate/infer_predicate.groovy
  regression-test/suites/nereids_rules_p0/infer_predicate/extend_infer_equal_predicate.groovy
  regression-test/suites/nereids_rules_p0/infer_predicate/infer_unequal_predicates.groovy
  regression-test/suites/nereids_rules_p0/mv/union_all_compensate/union_all_compensate.groovy
  regression-test/suites/nereids_rules_p0/partition_prune/test_multi_range_partition.groovy
Labels: approved, reviewed, dev/3.0.x

#41608 [bugfix](segmentload) should remove segment from segment cache if load segment failed
  be/src/olap/rowset/segment_v2/segment.cpp
  be/src/olap/rowset/segment_v2/segment.h
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/olap/segment_loader.cpp
  be/src/olap/segment_loader.h
Labels: approved, reviewed, p0_c, dev/2.1.x, dev/3.0.x

#41573 pick 40084 40200 40178
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/FilterEstimation.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
Labels: area/nereids

#41644 [chore](case) adjust db name
  regression-test/suites/nereids_syntax_p1/mv/aggregate/agg_sync_mv.groovy
  regression-test/suites/nereids_syntax_p1/mv/load.groovy
Labels: approved, reviewed

#41641 [fix](pipelinex) fix fragment instance progress reports (part 2) (#40694)
  be/src/runtime/fragment_mgr.cpp
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  gensrc/thrift/FrontendService.thrift
Labels: meta-change

#41652 Revert "[Improvement](sort) do not sort partitial when spill disabled(#40528)"
  be/src/vec/common/sort/sorter.h
Labels: approved, reviewed

#41670 [Bug](runtime-filter) fix wrong check on BloomFilterFuncBase::merge
  be/src/exprs/bloom_filter_func.h
Labels: approved, reviewed

#41669 Revert "[fix](env) state listener avoid endless waiting #27881 (#41462)"
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
Labels: approved, reviewed

#41602 [fix](counters) fix MemoryUsage and PeakMemoryUsage counters of some operators
  be/src/pipeline/dependency.cpp
  be/src/pipeline/dependency.h
  be/src/pipeline/exec/aggregation_sink_operator.cpp
  be/src/pipeline/exec/aggregation_sink_operator.h
  be/src/pipeline/exec/aggregation_source_operator.cpp
  be/src/pipeline/exec/analytic_sink_operator.cpp
  be/src/pipeline/exec/analytic_sink_operator.h
  be/src/pipeline/exec/analytic_source_operator.cpp
  be/src/pipeline/exec/assert_num_rows_operator.cpp
  be/src/pipeline/exec/cache_source_operator.cpp
  be/src/pipeline/exec/distinct_streaming_aggregation_operator.cpp
  be/src/pipeline/exec/exchange_sink_buffer.cpp
  be/src/pipeline/exec/exchange_sink_operator.cpp
  be/src/pipeline/exec/exchange_sink_operator.h
  be/src/pipeline/exec/exchange_source_operator.cpp
  be/src/pipeline/exec/group_commit_block_sink_operator.cpp
  be/src/pipeline/exec/hashjoin_build_sink.cpp
  be/src/pipeline/exec/hashjoin_build_sink.h
  be/src/pipeline/exec/hashjoin_probe_operator.cpp
  be/src/pipeline/exec/join/process_hash_table_probe.h
  be/src/pipeline/exec/join/process_hash_table_probe_impl.h
  be/src/pipeline/exec/multi_cast_data_stream_source.cpp
  be/src/pipeline/exec/operator.cpp
  be/src/pipeline/exec/operator.h
  be/src/pipeline/exec/partition_sort_sink_operator.cpp
  be/src/pipeline/exec/partition_sort_source_operator.cpp
  be/src/pipeline/exec/partitioned_aggregation_sink_operator.cpp
  be/src/pipeline/exec/partitioned_hash_join_probe_operator.cpp
  be/src/pipeline/exec/partitioned_hash_join_sink_operator.cpp
  be/src/pipeline/exec/repeat_operator.cpp
  be/src/pipeline/exec/scan_operator.h
  be/src/pipeline/exec/sort_sink_operator.cpp
  be/src/pipeline/exec/spill_sort_sink_operator.cpp
  be/src/pipeline/exec/streaming_aggregation_operator.cpp
  be/src/pipeline/exec/streaming_aggregation_operator.h
  be/src/pipeline/local_exchange/local_exchange_source_operator.cpp
  be/src/pipeline/local_exchange/local_exchanger.cpp
  be/src/runtime/memory/mem_tracker.cpp
  be/src/runtime/memory/mem_tracker.h
  be/src/vec/runtime/partitioner.cpp
  be/src/vec/runtime/partitioner.h
  be/src/vec/runtime/vdata_stream_mgr.cpp
  be/src/vec/runtime/vdata_stream_mgr.h
  be/src/vec/runtime/vdata_stream_recvr.cpp
  be/src/vec/runtime/vdata_stream_recvr.h
  be/src/vec/sink/vdata_stream_sender.cpp
  be/src/vec/sink/vdata_stream_sender.h
Labels: approved, reviewed

#41654 [fix](case) fix test_schema_change_ck
  regression-test/data/unique_with_mow_c_p0/test_schema_change_ck.out
  regression-test/suites/insert_p0/test_jdbc.groovy
  regression-test/suites/unique_with_mow_c_p0/test_schema_change_ck.groovy
Labels: approved, reviewed

#41392 [chore](log) Adjust log level for replaying a batch editlog cost time
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
Labels: approved, reviewed

#41413 [fix](cluster key) Cluster key skip non vertical compact
  be/src/olap/compaction.cpp
Labels: approved, reviewed

#41404 [improve](group commit) set internal group commit timeout
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/GroupCommitTableValuedFunction.java
Labels: approved, reviewed

#41507 [improve](cloud) set default vaule for file_path
  be/src/common/config.cpp
Labels: approved, reviewed, dev/3.0.2-merged

#41384 [enhance]change SpinLock to mutex for _tablets_channels_lock
  be/src/runtime/load_channel.cpp
  be/src/runtime/load_channel.h
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x

#40621 [Test](Orc) Add tests for exception orc files
  regression-test/suites/external_table_p0/tvf/orc_format/test_orc_exception_files.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41616 [opt](hive) make supported hive table error msg clearer
  fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/common/ErrorCode.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HMSExternalTable.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41613 [fix](Nerieds) column prune should retain at least one column for union all
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/ColumnPruning.java
  regression-test/suites/nereids_rules_p0/column_pruning/union_const_expr_column_pruning.groovy
Labels: approved, reviewed

#41575 [enhance](catalog)Allow parallel running of insert overwrite on the external table
  fe/fe-core/src/main/java/org/apache/doris/insertoverwrite/InsertOverwriteManager.java
  fe/fe-core/src/test/java/org/apache/doris/insertoverwrite/InsertOverwriteManagerTest.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41610 [Enhancement](MaxCompute)Refactoring maxCompute catalog using Storage API.(#40225 , #40888 ,#41386 )
  be/src/runtime/descriptors.cpp
  be/src/runtime/descriptors.h
  be/src/vec/exec/format/table/max_compute_jni_reader.cpp
  be/src/vec/exec/jni_connector.cpp
  be/src/vec/exec/scan/vfile_scanner.cpp
  conf/be.conf
  fe/be-java-extensions/java-common/src/main/java/org/apache/doris/common/jni/vec/ColumnValue.java
  fe/be-java-extensions/java-common/src/main/java/org/apache/doris/common/jni/vec/VectorColumn.java
  fe/be-java-extensions/max-compute-scanner/pom.xml
  fe/be-java-extensions/max-compute-scanner/src/main/java/org/apache/doris/maxcompute/MaxComputeColumnValue.java
  fe/be-java-extensions/max-compute-scanner/src/main/java/org/apache/doris/maxcompute/MaxComputeJniScanner.java
  fe/be-java-extensions/max-compute-scanner/src/main/java/org/apache/doris/maxcompute/MaxComputePartitionValue.java
  fe/be-java-extensions/max-compute-scanner/src/main/java/org/apache/doris/maxcompute/MaxComputeTableScan.java
  fe/be-java-extensions/max-compute-scanner/src/test/java/org/apache/doris/maxcompute/MaxComputeJniScannerTest.java
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/org/apache/doris/analysis/DateLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/maxcompute/MaxComputeExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/maxcompute/MaxComputeExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/maxcompute/MaxComputeMetadataCache.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/maxcompute/source/MaxComputeScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/maxcompute/source/MaxComputeSplit.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/constants/MCProperties.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/property/PropertyConverterTest.java
  fe/pom.xml
  gensrc/thrift/Descriptors.thrift
  gensrc/thrift/PlanNodes.thrift
  regression-test/data/external_table_p0/mc/test_max_compute_complex_type.out
  regression-test/data/external_table_p2/maxcompute/test_external_catalog_maxcompute.out
  regression-test/data/external_table_p2/maxcompute/test_max_compute_all_type.out
  regression-test/data/external_table_p2/maxcompute/test_max_compute_complex_type.out
  regression-test/suites/external_table_p2/maxcompute/test_external_catalog_maxcompute.groovy
  regression-test/suites/external_table_p2/maxcompute/test_max_compute_all_type.groovy
  regression-test/suites/external_table_p2/maxcompute/test_max_compute_complex_type.groovy
Labels: meta-change

#41685 [bugfix](becore) use after free problem when the segment is pop
  be/src/olap/segment_loader.h
Labels: approved, reviewed, p0_c, dev/2.1.x, dev/3.0.x

#41540 [Refactor](exec) refactor schema scanner del unless code
  be/src/exec/schema_scanner.cpp
  be/src/exec/schema_scanner.h
  be/src/exec/schema_scanner/schema_statistics_scanner.cpp
  be/src/exec/schema_scanner/schema_statistics_scanner.h
  be/test/vec/exec/parquet/parquet_thrift_test.cpp
Labels: approved, reviewed

#41676 [Improvement](shuffle) Reduce memory consumption in data stream sender
  be/src/pipeline/exec/exchange_sink_operator.cpp
  be/src/pipeline/exec/exchange_sink_operator.h
  be/src/vec/sink/vdata_stream_sender.cpp
  be/src/vec/sink/vdata_stream_sender.h
Labels: approved, reviewed

#41678 [Fix](delete) Fix some delete p2 case
  regression-test/suites/insert_p2/test_group_commit_http_stream_lineitem_schema_change.groovy
  regression-test/suites/insert_p2/test_group_commit_insert_into_lineitem_scheme_change.groovy
  regression-test/suites/insert_p2/test_group_commit_stream_load_lineitem_schema_change.groovy
  regression-test/suites/insert_p2/txn_insert_with_schema_change.groovy
  regression-test/suites/tpch_sf100_p2/ddl/customer.sql
  regression-test/suites/tpch_sf100_p2/ddl/lineitem.sql
  regression-test/suites/tpch_sf100_p2/ddl/nation.sql
  regression-test/suites/tpch_sf100_p2/ddl/orders.sql
  regression-test/suites/tpch_sf100_p2/ddl/part.sql
  regression-test/suites/tpch_sf100_p2/ddl/partsupp.sql
  regression-test/suites/tpch_sf100_p2/ddl/region.sql
  regression-test/suites/tpch_sf100_p2/ddl/supplier.sql
  regression-test/suites/tpch_sf1_p2/ddl/create_table.sql
  regression-test/suites/tpch_sf1_p2/ddl/customer.sql
  regression-test/suites/tpch_sf1_p2/ddl/lineitem.sql
  regression-test/suites/tpch_sf1_p2/ddl/nation.sql
  regression-test/suites/tpch_sf1_p2/ddl/orders.sql
  regression-test/suites/tpch_sf1_p2/ddl/part.sql
  regression-test/suites/tpch_sf1_p2/ddl/partsupp.sql
  regression-test/suites/tpch_sf1_p2/ddl/region.sql
  regression-test/suites/tpch_sf1_p2/ddl/supplier.sql
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x

#41563 [fix](jdbc catalog) Disable oracle scan null operator pushdown
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/source/JdbcScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  regression-test/data/external_table_p0/jdbc/test_oracle_jdbc_catalog.out
  regression-test/suites/external_table_p0/jdbc/test_oracle_jdbc_catalog.groovy
Labels: approved, reviewed, dev/2.1.x

#41499 [enhance](mtmv)Mtmv support audit log
  fe/fe-core/src/main/java/org/apache/doris/job/extensions/mtmv/MTMVTask.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVPlanUtil.java
Labels: approved, reviewed, dev/3.0.x, dev/2.1.7-merged

#41273 [fix](scanner) Fix incorrect _max_thread_num in scanner context when many queries are running.
  be/src/pipeline/exec/scan_operator.cpp
  be/src/vec/exec/scan/scanner_context.cpp
  be/src/vec/exec/scan/scanner_context.h
  be/src/vec/exec/scan/scanner_scheduler.cpp
  be/src/vec/exec/scan/scanner_scheduler.h
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41668 [Fix](bug) Is null predicate get error query result
  be/src/exec/olap_common.h
  regression-test/data/query_p0/scan_range/test_scan_range.out
  regression-test/suites/query_p0/scan_range/test_scan_range.groovy
Labels: kind/fix, approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x

#41371 [opt](index compaction)Use RAM dir to create tmp index_writer
  be/src/olap/rowset/segment_v2/inverted_index_compaction.cpp
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x

#41295 [extension](kettle) add kettle plugins to write doris
  extension/kettle/README.md
  extension/kettle/README_zh.md
  extension/kettle/assemblies/plugin/pom.xml
  extension/kettle/assemblies/plugin/src/assembly/assembly.xml
  extension/kettle/assemblies/plugin/src/main/resources/version.xml
  extension/kettle/assemblies/pom.xml
  extension/kettle/images/create.png
  extension/kettle/images/create_zh.png
  extension/kettle/images/running.png
  extension/kettle/images/running_zh.png
  extension/kettle/impl/pom.xml
  extension/kettle/impl/src/main/java/org/pentaho/di/trans/steps/dorisstreamloader/DorisStreamLoader.java
  extension/kettle/impl/src/main/java/org/pentaho/di/trans/steps/dorisstreamloader/DorisStreamLoaderData.java
  extension/kettle/impl/src/main/java/org/pentaho/di/trans/steps/dorisstreamloader/DorisStreamLoaderMeta.java
  extension/kettle/impl/src/main/java/org/pentaho/di/trans/steps/dorisstreamloader/load/BatchBufferHttpEntity.java
  extension/kettle/impl/src/main/java/org/pentaho/di/trans/steps/dorisstreamloader/load/BatchBufferStream.java
  extension/kettle/impl/src/main/java/org/pentaho/di/trans/steps/dorisstreamloader/load/BatchRecordBuffer.java
  extension/kettle/impl/src/main/java/org/pentaho/di/trans/steps/dorisstreamloader/load/DefaultThreadFactory.java
  extension/kettle/impl/src/main/java/org/pentaho/di/trans/steps/dorisstreamloader/load/DorisBatchStreamLoad.java
  extension/kettle/impl/src/main/java/org/pentaho/di/trans/steps/dorisstreamloader/load/DorisOptions.java
  extension/kettle/impl/src/main/java/org/pentaho/di/trans/steps/dorisstreamloader/load/DorisRuntimeException.java
  extension/kettle/impl/src/main/java/org/pentaho/di/trans/steps/dorisstreamloader/load/EscapeHandler.java
  extension/kettle/impl/src/main/java/org/pentaho/di/trans/steps/dorisstreamloader/load/HttpPutBuilder.java
  extension/kettle/impl/src/main/java/org/pentaho/di/trans/steps/dorisstreamloader/load/HttpUtil.java
  extension/kettle/impl/src/main/java/org/pentaho/di/trans/steps/dorisstreamloader/load/LoadConstants.java
  extension/kettle/impl/src/main/java/org/pentaho/di/trans/steps/dorisstreamloader/load/LoadStatus.java
  extension/kettle/impl/src/main/java/org/pentaho/di/trans/steps/dorisstreamloader/load/RespContent.java
  extension/kettle/impl/src/main/java/org/pentaho/di/trans/steps/dorisstreamloader/serializer/DorisRecordSerializer.java
  extension/kettle/impl/src/main/resources/log4j.properties
  extension/kettle/impl/src/main/resources/org/pentaho/di/trans/steps/dorisstreamloader/messages/messages_en_US.properties
  extension/kettle/impl/src/main/resources/org/pentaho/di/trans/steps/dorisstreamloader/messages/messages_zh_CN.properties
  extension/kettle/impl/src/test/java/org/pentaho/di/trans/steps/dorisstreamloader/DorisBatchStreamLoadTest.java
  extension/kettle/impl/src/test/resources/log4j2-test.properties
  extension/kettle/pom.xml
  extension/kettle/ui/pom.xml
  extension/kettle/ui/src/main/java/org/pentaho/di/ui/trans/steps/dorisstreamloader/DorisStreamLoaderDialog.java
  extension/kettle/ui/src/main/resources/doris.svg
  extension/kettle/ui/src/main/resources/logo.png
  extension/kettle/ui/src/main/resources/org/pentaho/di/ui/trans/steps/dorisstreamloader/messages/messages_en_US.properties
  extension/kettle/ui/src/main/resources/org/pentaho/di/ui/trans/steps/dorisstreamloader/messages/messages_zh_CN.properties
Labels: approved, reviewed

#41369 [fix](bloom filter)Fix drop column with bloom filter
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
  regression-test/data/bloom_filter_p0/test_bloom_filter_drop_column.out
  regression-test/suites/bloom_filter_p0/test_bloom_filter_drop_column.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x

#41698 [Improvement](runtime-filter) set some rf brpc request to ignore_eovercrowded
  be/src/exprs/runtime_filter.cpp
  be/src/runtime/runtime_filter_mgr.cpp
Labels: approved, reviewed

#41472 [fix](mtmv) Fix enable_materialized_view_nest_rewrite session variable is useless in some scene
  fe/fe-core/src/main/java/org/apache/doris/nereids/CascadesContext.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/memo/StructInfoMap.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleSet.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewRule.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/MaterializedViewOnlyJoinRule.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/MaterializedViewProjectFilterJoinRule.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/MaterializedViewUtils.java
  regression-test/suites/nereids_rules_p0/mv/direct_query/direct_query.groovy
  regression-test/suites/nereids_rules_p0/mv/nested_mtmv_switch/nested_mtmv_rewrite_switch.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#40106 [fix](mtmv) Disable sql_limit variable when query rewrite by materialize view
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVPlanUtil.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/MaterializedViewUtils.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalOlapScan.java
  regression-test/data/mtmv_p0/limit/refresh_with_sql_limit.out
  regression-test/data/nereids_rules_p0/mv/with_sql_limit/query_with_sql_limit.out
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
  regression-test/suites/mtmv_p0/limit/refresh_with_sql_limit.groovy
  regression-test/suites/nereids_rules_p0/mv/with_sql_limit/query_with_sql_limit.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41692 [Fix](compile) Fix control reaches end of non-void function
  be/src/olap/partial_update_info.h
Labels: approved, reviewed

#41696 Revert "[feature](nereids) extend infer predicates (#40878)"
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Table.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/TableIf.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/Rewriter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/InferPredicateByReplace.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/InferPredicates.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PredicatePropagation.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PullUpPredicates.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/UnequalPredicateInfer.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/Like.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/Not.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/StringRegexPredicate.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/BoundFunction.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/Function.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/ScalarFunction.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/PredicateInferUtils.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/properties/UniformTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/InferPredicateByReplaceTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/PredicatePropagationTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/UnequalPredicateInferTest.java
  fe/fe-core/src/test/java/org/apache/doris/policy/PolicyTest.java
  regression-test/data/nereids_hint_tpch_p0/shape/q12.out
  regression-test/data/nereids_rules_p0/infer_predicate/extend_infer_equal_predicate.out
  regression-test/data/nereids_rules_p0/infer_predicate/infer_unequal_predicates.out
  regression-test/data/nereids_rules_p0/predicate_infer/infer_predicate.out
  regression-test/data/nereids_tpch_shape_sf1000_p0/nostats_rf_prune/q12.out
  regression-test/data/nereids_tpch_shape_sf1000_p0/rf_prune/q12.out
  regression-test/data/nereids_tpch_shape_sf1000_p0/shape/q12.out
  regression-test/data/nereids_tpch_shape_sf1000_p0/shape_no_stats/q12.out
  regression-test/data/new_shapes_p0/hint_tpch/shape/q12.out
  regression-test/data/new_shapes_p0/tpch_sf1000/nostats_rf_prune/q12.out
  regression-test/data/new_shapes_p0/tpch_sf1000/rf_prune/q12.out
  regression-test/data/new_shapes_p0/tpch_sf1000/shape/q12.out
  regression-test/data/new_shapes_p0/tpch_sf1000/shape_no_stats/q12.out
  regression-test/suites/nereids_p0/infer_predicate/infer_predicate.groovy
  regression-test/suites/nereids_rules_p0/infer_predicate/extend_infer_equal_predicate.groovy
  regression-test/suites/nereids_rules_p0/infer_predicate/infer_unequal_predicates.groovy
  regression-test/suites/nereids_rules_p0/mv/union_all_compensate/union_all_compensate.groovy
  regression-test/suites/nereids_rules_p0/partition_prune/test_multi_range_partition.groovy
Labels: approved, reviewed, not-merge/3.0

#41207 [enhance](auth)Optimize the authentication logic of Ranger Doris
  fe/fe-core/src/main/java/org/apache/doris/catalog/authorizer/ranger/RangerAccessController.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/authorizer/ranger/cache/CatalogCacheAccessController.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/authorizer/ranger/cache/DatamaskCacheKey.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/authorizer/ranger/cache/RangerCache.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/authorizer/ranger/cache/RangerCacheInvalidateListener.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/authorizer/ranger/cache/RowFilterCacheKey.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/authorizer/ranger/doris/DorisAccessType.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/authorizer/ranger/doris/DorisObjectType.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/authorizer/ranger/doris/RangerCacheDorisAccessController.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/authorizer/ranger/doris/RangerDorisAccessController.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/authorizer/ranger/doris/RangerDorisResource.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/authorizer/ranger/hive/RangerCacheHiveAccessController.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/authorizer/ranger/hive/RangerHiveAccessControllerFactory.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/AccessControllerManager.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/RangerDorisAccessControllerFactory.java
Labels: approved, reviewed, kind/behavior-changed, dev/3.0.x

#41691 [enhance](mtmv)Provide a method to determine whether incremental updates of multiple tables are allowed
  fe/fe-core/src/main/java/org/apache/doris/analysis/PartitionExprUtil.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/DynamicPartitionUtil.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVPartitionCheckUtil.java
  fe/fe-core/src/test/java/org/apache/doris/mtmv/MTMVPartitionCheckUtilTest.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41655 [enhancement](sequence col) add session variable to skip sequence column check while INSERT INTO
  fe/fe-core/src/main/java/org/apache/doris/analysis/NativeInsertStmt.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/BindSink.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  regression-test/data/data_model_p0/unique/test_unique_table_sequence.out
  regression-test/suites/data_model_p0/unique/test_unique_table_sequence.groovy
Labels: approved, reviewed

#39617 [fix](regression-test) Multi threaded testing
  regression-test/suites/schema_change_p0/test_agg_schema_key_change_modify.groovy
  regression-test/suites/schema_change_p0/test_agg_schema_key_change_modify1.groovy
  regression-test/suites/schema_change_p0/test_agg_schema_value_modify.groovy
  regression-test/suites/schema_change_p0/test_agg_schema_value_modify2.groovy
  regression-test/suites/schema_change_p0/test_agg_schema_value_modify3.groovy
  regression-test/suites/schema_change_p0/test_dup_schema_key_change_modify.groovy
  regression-test/suites/schema_change_p0/test_dup_schema_key_change_modify1.groovy
  regression-test/suites/schema_change_p0/test_dup_schema_value_modify.groovy
  regression-test/suites/schema_change_p0/test_dup_schema_value_modify1.groovy
  regression-test/suites/schema_change_p0/test_dup_schema_value_modify2.groovy
  regression-test/suites/schema_change_p0/test_dup_schema_value_modify3.groovy
  regression-test/suites/schema_change_p0/test_dup_schema_value_modify4.groovy
  regression-test/suites/schema_change_p0/test_unique_schema_key_change_add.groovy
  regression-test/suites/schema_change_p0/test_unique_schema_key_change_modify.groovy
  regression-test/suites/schema_change_p0/test_unique_schema_value_drop.groovy
  regression-test/suites/schema_change_p0/test_unique_schema_value_modify.groovy
  regression-test/suites/schema_change_p0/test_unique_schema_value_modify2.groovy
Labels: approved, reviewed

#41535 [enhancement](err-msg) Output column info when size invalid in block data convertor
  be/src/vec/olap/olap_data_convertor.cpp
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41667 [Bug](runtime-filter) send ignored rf when hash join build closed early
  be/src/exprs/runtime_filter.cpp
  be/src/exprs/runtime_filter_slots.h
  be/src/pipeline/exec/hashjoin_build_sink.cpp
  be/src/runtime/runtime_filter_mgr.cpp
Labels: approved, reviewed

#41609 [fix](heartbeat) fill default value for required field in TFrontendPingFrontendResult
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41217 [fix](serde)fix the bug in DataTypeNullableSerDe.deserialize_column_from_fixed_json
  be/src/vec/data_types/serde/data_type_datetimev2_serde.cpp
  be/src/vec/data_types/serde/data_type_datev2_serde.cpp
  be/src/vec/data_types/serde/data_type_decimal_serde.cpp
  be/src/vec/data_types/serde/data_type_nullable_serde.cpp
  be/src/vec/data_types/serde/data_type_number_serde.cpp
  be/src/vec/data_types/serde/data_type_serde.h
  be/src/vec/data_types/serde/data_type_string_serde.h
  be/src/vec/exec/format/parquet/vparquet_group_reader.cpp
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41391 [feat](job)Implementing Job in Nereids
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateJobStmt.java
  fe/fe-core/src/main/java/org/apache/doris/job/extensions/insert/InsertJob.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PlanType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/CreateJobCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/CreateJobInfo.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/InsertIntoTableCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/CommandVisitor.java
  regression-test/data/job_p0/job_meta/job_query_test.out
  regression-test/suites/job_p0/test_base_insert_job.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41628 [fix](followup) Stop tasks if waken by downstream tasks
  be/src/exprs/runtime_filter.cpp
  be/src/exprs/runtime_filter.h
  be/src/pipeline/common/runtime_filter_consumer.cpp
  be/src/pipeline/common/runtime_filter_consumer.h
  be/src/pipeline/exec/hashjoin_build_sink.cpp
  be/src/pipeline/exec/multi_cast_data_stream_sink.h
  be/src/pipeline/exec/operator.h
  be/src/pipeline/pipeline.cpp
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/pipeline/pipeline_task.cpp
  be/src/pipeline/pipeline_task.h
  be/src/vec/runtime/shared_hash_table_controller.h
  be/test/exprs/runtime_filter_test.cpp
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41673 [chore](Variant) forbid variant type as hash join key
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/CheckAfterRewrite.java
  regression-test/suites/nereids_p0/join/test_join_on.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#40173 [fix](mtmv) Fix written by mv successfully but not get mv lock. If use mv, data maybe wrong
  fe/fe-core/src/main/java/org/apache/doris/catalog/MTMV.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/StatementContext.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewRule.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/util/PlanChecker.java
  regression-test/suites/nereids_rules_p0/mv/dml/with_lock/dml_rewrite_with_lock.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41712 [fix](jdbc catalog) Disable oracle scan null operator pushdown
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/source/JdbcScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  regression-test/data/external_table_p0/jdbc/test_oracle_jdbc_catalog.out
  regression-test/suites/external_table_p0/jdbc/test_oracle_jdbc_catalog.groovy
Labels: approved, reviewed

#41717 [fix](regression-test) fix flaky case test_partial_update_compaction_with_higher_version
  regression-test/suites/fault_injection_p0/partial_update/test_partial_update_compaction_with_higher_version.groovy
Labels: approved, reviewed

#41702 [Fix](bug) Is null predicate get error query result
  be/src/exec/olap_common.h
  regression-test/data/query_p0/scan_range/test_scan_range.out
  regression-test/suites/query_p0/scan_range/test_scan_range.groovy
Labels: kind/test

#41310 [opt](memory) Support Memory Profile
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/common/daemon.cpp
  be/src/http/default_path_handlers.cpp
  be/src/olap/rowset/beta_rowset_writer.cpp
  be/src/olap/rowset/segcompaction.cpp
  be/src/olap/rowset/segcompaction.h
  be/src/olap/task/engine_publish_version_task.cpp
  be/src/runtime/exec_env.h
  be/src/runtime/exec_env_init.cpp
  be/src/runtime/memory/cache_policy.h
  be/src/runtime/memory/global_memory_arbitrator.cpp
  be/src/runtime/memory/global_memory_arbitrator.h
  be/src/runtime/memory/mem_tracker_limiter.cpp
  be/src/runtime/memory/mem_tracker_limiter.h
  be/src/runtime/memory/memory_profile.cpp
  be/src/runtime/memory/memory_profile.h
  be/src/runtime/memory/memory_reclamation.cpp
  be/src/runtime/memory/thread_mem_tracker_mgr.h
  be/src/runtime/process_profile.cpp
  be/src/runtime/process_profile.h
  be/src/runtime/routine_load/routine_load_task_executor.cpp
  be/src/util/mem_info.cpp
  be/src/util/mem_info.h
  be/src/util/runtime_profile.cpp
  be/src/util/runtime_profile.h
  be/src/vec/common/allocator.cpp
  be/test/runtime/memory/mem_tracker_test.cpp
  be/test/testutil/run_all_tests.cpp
Labels: approved, reviewed, dev/3.0.x

#41743 [fix](pipeline) Prevent re-scheduling a task at the same time
  be/src/pipeline/pipeline_task.cpp
  be/src/pipeline/pipeline_task.h
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41728 [fix](parser) should not use selectHint in any place (#41260)
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
Labels: area/nereids

#41732 [enhancement](sequence col) add session variable to skip sequence column check while INSERT INTO (#41655)
  fe/fe-core/src/main/java/org/apache/doris/analysis/NativeInsertStmt.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/BindSink.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  regression-test/data/data_model_p0/unique/test_unique_table_sequence.out
  regression-test/suites/data_model_p0/unique/test_unique_table_sequence.groovy
Labels: area/planner, kind/test, area/nereids

#41580 [Bug](materialized-view) Fixed the problem of using drop table force and create mv stmt at the…
  fe/fe-core/src/main/java/org/apache/doris/alter/RollupJobV2.java
  regression-test/suites/mv_p0/mv_with_force_drop/mv_with_force_drop.groovy
Labels: approved, reviewed

#41429 [Fix]count tablet meta's static memory load from disk
  be/src/olap/metadata_adder.h
  be/src/olap/rowset/rowset_meta.cpp
  be/src/olap/rowset/rowset_meta.h
  be/src/olap/rowset/segment_v2/bitmap_index_reader.h
  be/src/olap/rowset/segment_v2/bloom_filter_index_reader.cpp
  be/src/olap/rowset/segment_v2/bloom_filter_index_reader.h
  be/src/olap/rowset/segment_v2/column_reader.cpp
  be/src/olap/rowset/segment_v2/column_reader.h
  be/src/olap/rowset/segment_v2/index_page.cpp
  be/src/olap/rowset/segment_v2/index_page.h
  be/src/olap/rowset/segment_v2/indexed_column_reader.cpp
  be/src/olap/rowset/segment_v2/indexed_column_reader.h
  be/src/olap/rowset/segment_v2/inverted_index_reader.h
  be/src/olap/rowset/segment_v2/ordinal_page_index.cpp
  be/src/olap/rowset/segment_v2/ordinal_page_index.h
  be/src/olap/rowset/segment_v2/segment.cpp
  be/src/olap/rowset/segment_v2/segment.h
  be/src/olap/rowset/segment_v2/zone_map_index.cpp
  be/src/olap/rowset/segment_v2/zone_map_index.h
  be/src/olap/tablet_meta.cpp
  be/src/olap/tablet_meta.h
  be/src/olap/tablet_schema.cpp
  be/src/olap/tablet_schema.h
Labels: approved, reviewed

#41748 [deps](hadoop) update hadoop to 3.3.6.3 #39376
  thirdparty/CHANGELOG.md
  thirdparty/vars.sh
Labels: approved, reviewed

#41740 [followup](memory) Block should be moved by hash shuffling
  be/src/pipeline/exec/exchange_sink_operator.cpp
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41735 [improvement](jdbc catalog) Print more errors when Jdbc Catalog fails to obtain a connection on FE
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/client/JdbcClient.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/client/JdbcClientException.java
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x

#41755 [fix](case) fix group commit case
  be/src/runtime/group_commit_mgr.cpp
  regression-test/suites/insert_p0/insert_group_commit_into_max_filter_ratio.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41233 [enhancement](cloud) make active warmup job number configurable
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/CacheHotspotManager.java
Labels: approved, reviewed, dev/3.0.x

#41677 [fix](cloud) fix multi table load can not plan after FE restart or leader change
  fe/fe-core/src/main/java/org/apache/doris/cloud/load/CloudRoutineLoadManager.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadJob.java
Labels: approved, reviewed, dev/3.0.x

#41169 [improvement](iceberg)Parallelize splits for count(*)
  be/src/vec/exec/format/table/iceberg_reader.cpp
  be/src/vec/exec/format/table/iceberg_reader.h
  be/src/vec/exec/scan/vfile_scanner.cpp
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/source/IcebergScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/source/IcebergSplit.java
  gensrc/thrift/PlanNodes.thrift
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41662 [Fix](Export) `show export` statement supports specify the catalog name
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowExportStmt.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ShowExportStmtTest.java
  regression-test/suites/external_table_p0/export/test_export_external_table.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41606 [Test](tvf) add regression tests for testing orc reader
  be/src/vec/data_types/serde/data_type_datetimev2_serde.cpp
  regression-test/data/external_table_p0/tvf/orc_tvf/test_hdfs_orc_group0_orc_files.out
  regression-test/data/external_table_p0/tvf/orc_tvf/test_hdfs_orc_group1_orc_files.out
  regression-test/data/external_table_p0/tvf/orc_tvf/test_hdfs_orc_group2_orc_files.out
  regression-test/data/external_table_p0/tvf/orc_tvf/test_hdfs_orc_group3_orc_files.out
  regression-test/data/external_table_p0/tvf/orc_tvf/test_hdfs_orc_group4_orc_files.out
  regression-test/data/external_table_p0/tvf/orc_tvf/test_hdfs_orc_group5_orc_files.out
  regression-test/data/external_table_p0/tvf/orc_tvf/test_hdfs_orc_group6_orc_files.out
  regression-test/data/external_table_p0/tvf/orc_tvf/test_hdfs_orc_group7_orc_files.out
  regression-test/suites/external_table_p0/tvf/orc_tvf/test_hdfs_orc_group0_orc_files.groovy
  regression-test/suites/external_table_p0/tvf/orc_tvf/test_hdfs_orc_group1_orc_files.groovy
  regression-test/suites/external_table_p0/tvf/orc_tvf/test_hdfs_orc_group2_orc_files.groovy
  regression-test/suites/external_table_p0/tvf/orc_tvf/test_hdfs_orc_group3_orc_files.groovy
  regression-test/suites/external_table_p0/tvf/orc_tvf/test_hdfs_orc_group4_orc_files.groovy
  regression-test/suites/external_table_p0/tvf/orc_tvf/test_hdfs_orc_group5_orc_files.groovy
  regression-test/suites/external_table_p0/tvf/orc_tvf/test_hdfs_orc_group6_orc_files.groovy
  regression-test/suites/external_table_p0/tvf/orc_tvf/test_hdfs_orc_group7_orc_files.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41679 [fix](jdbc catalog) fix and add mysql and doris extremum test
  docker/thirdparties/docker-compose/mysql/init/03-create-table.sql
  docker/thirdparties/docker-compose/mysql/init/04-insert.sql
  fe/be-java-extensions/jdbc-scanner/src/main/java/org/apache/doris/jdbc/BaseJdbcExecutor.java
  fe/be-java-extensions/jdbc-scanner/src/main/java/org/apache/doris/jdbc/MySQLJdbcExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/client/JdbcMySQLClient.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/util/JdbcFieldSchema.java
  regression-test/data/external_table_p0/jdbc/test_mariadb_jdbc_catalog.out
  regression-test/data/external_table_p0/jdbc/test_mysql_jdbc_catalog.out
  regression-test/data/external_table_p0/jdbc/type_test/ctas/test_mysql_all_types_ctas.out
  regression-test/data/external_table_p0/jdbc/type_test/select/test_doris_all_types_select.out
  regression-test/data/external_table_p0/jdbc/type_test/select/test_mysql_all_types_select.out
  regression-test/data/external_table_p0/jdbc/type_test/tvf/test_mysql_all_types_tvf.out
  regression-test/suites/external_table_p0/jdbc/type_test/ctas/test_mysql_all_types_ctas.groovy
  regression-test/suites/external_table_p0/jdbc/type_test/select/test_doris_all_types_select.groovy
  regression-test/suites/external_table_p0/jdbc/type_test/select/test_mysql_all_types_select.groovy
  regression-test/suites/external_table_p0/jdbc/type_test/tvf/test_mysql_all_types_tvf.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41659 [Enhancement](ExternalTable)Optimize the performance of getCachedRowCount when reading ExternalTable
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HMSExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/IcebergHMSExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/IcebergMetadataCache.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/IcebergUtils.java
  regression-test/suites/external_table_p0/iceberg/test_iceberg_table_stats.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41666 [fix](information-meta) fix information column_type and data_type for ip/variant
  be/src/exec/schema_scanner/schema_columns_scanner.cpp
  regression-test/suites/datatype_p0/scalar_types/test_information_types.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41642 [fix](nestedtype) support change order in table for nested type #39210
  fe/fe-core/src/main/java/org/apache/doris/catalog/Column.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/ColumnType.java
  regression-test/data/datatype_p0/nested_types/ddl/create_nestedtypes_with_schemachange.out
  regression-test/suites/datatype_p0/nested_types/ddl/create_nestedtypes_with_schemachange.groovy
Labels: kind/test

#39546 [feature](agg-func) linear_histogram
  be/src/vec/aggregate_functions/aggregate_function_linear_histogram.cpp
  be/src/vec/aggregate_functions/aggregate_function_linear_histogram.h
  be/src/vec/aggregate_functions/aggregate_function_simple_factory.cpp
  be/test/vec/aggregate_functions/agg_linear_histogram_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/AggregateFunction.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinAggregateFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionSet.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/LinearHistogram.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/AggregateFunctionVisitor.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/analysis/GenerateFunction.java
  regression-test/data/nereids_function_p0/agg_function/agg.out
  regression-test/data/nereids_p0/aggregate/agg_nullable.out
  regression-test/data/nereids_p0/aggregate/agg_nullable_2.out
  regression-test/data/nereids_syntax_p0/mv/aggregate/agg_sync_mv.out
  regression-test/suites/nereids_function_p0/agg_function/agg.groovy
  regression-test/suites/nereids_p0/aggregate/agg_nullable.groovy
  regression-test/suites/nereids_p0/aggregate/agg_nullable_2.groovy
  regression-test/suites/nereids_syntax_p0/mv/aggregate/agg_sync_mv.groovy
Labels: approved, reviewed

#41553 [Refactor](statistics)Refactor of statistics buildConnectContext.
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/JdbcExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/qe/AuditLogHelper.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisJob.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/BaseAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/OlapAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/util/StatisticsUtil.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/OlapAnalysisTaskTest.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#40152 [enhancement](compaction) optimize the cpu consumption of the compaction task producer thread
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/olap/compaction.cpp
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
  be/src/olap/tablet_manager.cpp
  be/test/olap/compaction_score_test.cpp
  be/test/olap/cumulative_compaction_policy_test.cpp
  be/test/olap/cumulative_compaction_time_series_policy_test.cpp
  be/test/olap/tablet_mgr_test.cpp
Labels: approved, reviewed

#41623 [improve](column) implement insert_many_from function for all column
  be/src/pipeline/exec/nested_loop_join_probe_operator.cpp
  be/src/vec/columns/column_array.cpp
  be/src/vec/columns/column_array.h
  be/src/vec/columns/column_complex.h
  be/src/vec/columns/column_const.h
  be/src/vec/columns/column_decimal.cpp
  be/src/vec/columns/column_decimal.h
  be/src/vec/columns/column_map.cpp
  be/src/vec/columns/column_map.h
  be/src/vec/columns/column_nullable.cpp
  be/src/vec/columns/column_nullable.h
  be/src/vec/columns/column_string.cpp
  be/src/vec/columns/column_string.h
  be/src/vec/columns/column_struct.cpp
  be/src/vec/columns/column_struct.h
  be/src/vec/columns/column_vector.cpp
  be/src/vec/columns/column_vector.h
Labels: approved, reviewed

#41761 [opt](profile) Move ExecutedByFrontend to execution summary profile
  fe/fe-core/src/main/java/org/apache/doris/common/profile/SummaryProfile.java
Labels: approved, reviewed

#41718 [enhance](cloud)support SHOW-TRANSACTION
  fe/fe-core/src/main/java/org/apache/doris/cloud/transaction/CloudGlobalTransactionMgr.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/transaction/TxnUtil.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/TransactionUtil.java
  regression-test/pipeline/cloud_p0/conf/regression-conf-custom.groovy
  regression-test/suites/query_p0/show/test_show_transaction.groovy
Labels: approved, reviewed, dev/3.0.x

#41661 [ci](branch-3.0) set required checks
  .asf.yaml
Labels: approved, reviewed

#41758 [cherry-pick](branch-2.0) Pick "[Fix](delete) Fix some delete p2 case (#37689) (#41678)"
  regression-test/suites/unique_with_mow_p2/ssb_unique_load_zstd/ddl/customer_create.sql
  regression-test/suites/unique_with_mow_p2/ssb_unique_load_zstd/ddl/customer_sequence_create.sql
  regression-test/suites/unique_with_mow_p2/ssb_unique_load_zstd/ddl/date_create.sql
  regression-test/suites/unique_with_mow_p2/ssb_unique_load_zstd/ddl/date_sequence_create.sql
  regression-test/suites/unique_with_mow_p2/ssb_unique_load_zstd/ddl/lineorder_create.sql
  regression-test/suites/unique_with_mow_p2/ssb_unique_load_zstd/ddl/lineorder_sequence_create.sql
  regression-test/suites/unique_with_mow_p2/ssb_unique_load_zstd/ddl/part_create.sql
  regression-test/suites/unique_with_mow_p2/ssb_unique_load_zstd/ddl/part_sequence_create.sql
  regression-test/suites/unique_with_mow_p2/ssb_unique_load_zstd/ddl/supplier_create.sql
  regression-test/suites/unique_with_mow_p2/ssb_unique_load_zstd/ddl/supplier_sequence_create.sql
  regression-test/suites/unique_with_mow_p2/ssb_unique_sql_zstd/ddl/customer_create.sql
  regression-test/suites/unique_with_mow_p2/ssb_unique_sql_zstd/ddl/date_create.sql
  regression-test/suites/unique_with_mow_p2/ssb_unique_sql_zstd/ddl/lineorder_create.sql
  regression-test/suites/unique_with_mow_p2/ssb_unique_sql_zstd/ddl/part_create.sql
  regression-test/suites/unique_with_mow_p2/ssb_unique_sql_zstd/ddl/supplier_create.sql
Labels: kind/test

#41477 [refine](rf) Adjust the calculation logic for rf's always_true.
  be/src/common/config.cpp
  be/src/exprs/runtime_filter.cpp
  be/src/olap/column_predicate.h
  be/src/olap/comparison_predicate.h
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/vec/exprs/vexpr.h
  be/src/vec/exprs/vexpr_context.cpp
  be/src/vec/exprs/vruntimefilter_wrapper.cpp
  be/src/vec/exprs/vruntimefilter_wrapper.h
Labels: approved, reviewed

#41664 [Fix](Nereids) change name of plan replayer
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisLexer.g4
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ReplayCommand.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/parser/NereidsParserTest.java
Labels: approved, reviewed, dev/3.0.x

#40958 [fix](Nereids) fix leading tag can not work when leading is used
  fe/fe-core/src/main/java/org/apache/doris/nereids/CascadesContext.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/AnalyzeCTE.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/analysis/AnalyzeCTETest.java
  regression-test/data/nereids_hint_tpcds_p0/shape/query64.out
  regression-test/data/nereids_hint_tpcds_p0/shape/query81.out
  regression-test/data/nereids_p0/hint/multi_leading.out
  regression-test/data/nereids_p0/hint/test_hint.out
  regression-test/suites/nereids_p0/hint/multi_leading.groovy
  regression-test/suites/nereids_p0/hint/test_hint.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x

#41719 [opt](Nereids) use 1 as narrowest column when do column pruning on union
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/ColumnPruning.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/ColumnPruningTest.java
  regression-test/suites/nereids_rules_p0/column_pruning/union_const_expr_column_pruning.groovy
  regression-test/suites/nereids_rules_p0/column_pruning/window_column_pruning.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#41751 [Bug](runtime-filter) use wake_up_by_downstream to judge early close
  be/src/pipeline/exec/hashjoin_build_sink.cpp
  be/src/pipeline/pipeline_task.h
Labels: approved, reviewed

#41746 [Fix](inverted index) fix match null for inverted index
  be/src/vec/exprs/vmatch_predicate.cpp
  be/src/vec/functions/match.cpp
  be/src/vec/functions/match.h
  regression-test/data/inverted_index_p0/test_null_index.out
  regression-test/suites/inverted_index_p0/test_null_index.groovy
Labels: approved, reviewed

#40078 [opt](file-cache) support system table file_cache_statistics
  be/src/exec/schema_scanner.cpp
  be/src/exec/schema_scanner/schema_file_cache_statistics.cpp
  be/src/exec/schema_scanner/schema_file_cache_statistics.h
  be/src/io/cache/block_file_cache.cpp
  be/src/io/cache/block_file_cache.h
  be/src/io/cache/block_file_cache_factory.cpp
  be/src/io/cache/block_file_cache_factory.h
  fe/fe-core/src/main/java/org/apache/doris/analysis/SchemaTableType.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/SchemaTable.java
  fe/fe-core/src/main/java/org/apache/doris/planner/BackendPartitionedSchemaScanNode.java
  regression-test/data/external_table_p0/cache/test_file_cache_statistics.out
  regression-test/suites/external_table_p0/cache/test_file_cache_statistics.groovy
Labels: approved, reviewed, dev/3.0.x, dev/2.1.6-merged
