Repository apache/doris, pull requests merged in 2024-05, with the labels that each got.

#34142 (cloud-merge) Support to validate TTL keys
  be/src/cloud/cloud_storage_engine.cpp
  be/src/cloud/cloud_storage_engine.h
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/io/cache/block_file_cache.cpp
  be/src/io/cache/block_file_cache.h
  be/test/io/cache/block_file_cache_test.cpp
Labels: approved, reviewed

#34350 [improve] Make the schema change memory space adaptive
  be/src/agent/task_worker_pool.cpp
  be/src/cloud/cloud_schema_change_job.cpp
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/olap/schema_change.cpp
  be/src/olap/schema_change.h
  be/src/olap/storage_engine.cpp
  be/src/olap/storage_engine.h
  be/src/olap/task/engine_index_change_task.cpp
Labels: approved, reviewed, usercase, dev/2.0.x

#34375 [opt](inverted index) add inlist condition handling to compound
  be/src/exec/olap_common.h
  be/src/exec/olap_utils.h
  be/src/olap/column_predicate.h
  be/src/olap/comparison_predicate.h
  be/src/olap/reader.cpp
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/olap/rowset/segment_v2/segment_iterator.h
  be/src/vec/exec/scan/vscan_node.cpp
  be/src/vec/exec/scan/vscan_node.h
  regression-test/data/inverted_index_p0/test_compound_inlist.out
  regression-test/suites/inverted_index_p0/test_compound_inlist.groovy
Labels: kind/test

#34034 [branch-2.0](create tablet) create tablet chose disk round robin
  be/src/agent/task_worker_pool.cpp
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/olap/data_dir.cpp
  be/src/olap/data_dir.h
  be/src/olap/storage_engine.cpp
  be/src/olap/storage_engine.h
  be/src/olap/task/engine_clone_task.cpp
  regression-test/suites/partition_p0/test_partition_create_tablet_rr.groovy
Labels: kind/test

#33383 [enhancement](profile) get real-time query profile
  fe/fe-core/src/main/java/org/apache/doris/common/util/ProfileManager.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/Util.java
  fe/fe-core/src/main/java/org/apache/doris/qe/CoordInterface.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/PointQueryExec.java
  fe/fe-core/src/test/java/org/apache/doris/common/util/UtilTest.java
Labels: approved, reviewed, meta-change

#33810 [fix](profile) Should set is done when reporting profile
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/query_context.cpp
  be/src/runtime/runtime_query_statistics_mgr.cpp
  be/src/runtime/runtime_query_statistics_mgr.h
  be/src/service/backend_service.cpp
  fe/fe-core/src/main/java/org/apache/doris/common/profile/ExecutionProfile.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/RuntimeProfile.java
  fe/fe-core/src/main/java/org/apache/doris/qe/QeProcessorImpl.java
Labels: approved, reviewed

#34362 [fix](cloud) Fix the byte order during integer decoding
  cloud/src/meta-service/mem_txn_kv.cpp
  cloud/src/meta-service/mem_txn_kv.h
  cloud/src/meta-service/meta_service.cpp
  cloud/src/meta-service/meta_service_partition.cpp
  cloud/src/meta-service/txn_kv.cpp
  cloud/src/meta-service/txn_kv.h
Labels: approved, reviewed

#34364 [fix](csv-reader) fix column split error when there is escape character
  be/src/vec/exec/format/file_reader/new_plain_text_line_reader.cpp
  be/src/vec/exec/format/file_reader/new_plain_text_line_reader.h
Labels: reviewed

#34367 [Bug](runtime-filter) release rf count dependency when query canceled
  be/src/exprs/runtime_filter.cpp
  be/src/exprs/runtime_filter.h
  be/src/exprs/runtime_filter_slots.h
  be/src/pipeline/dependency.h
  be/src/pipeline/exec/hashjoin_build_sink.cpp
  be/src/vec/functions/function_cast.h
Labels: approved, reviewed

#34309 [Improve](regresscases)fix function array index with null param and add regress cases for ar…
  be/src/vec/functions/array/function_array_index.h
  regression-test/data/inverted_index_p0/test_array_with_inverted_index_all_type.json
  regression-test/data/inverted_index_p0/test_array_with_inverted_index_all_type.out
  regression-test/data/inverted_index_p0/test_array_with_inverted_index_all_type_agg.json
  regression-test/suites/inverted_index_p0/test_array_with_inverted_index_all_type.groovy
Labels: approved, reviewed

#34373 [Opt](func) opt the percentile func performance
  be/src/agent/be_exec_version_manager.h
  be/src/util/counts.h
  be/src/vec/aggregate_functions/aggregate_function_percentile.cpp
  be/src/vec/aggregate_functions/aggregate_function_percentile.h
  be/src/vec/aggregate_functions/aggregate_function_percentile_approx.cpp
  be/src/vec/aggregate_functions/aggregate_function_percentile_approx.h
  be/src/vec/aggregate_functions/aggregate_function_simple_factory.cpp
  be/src/vec/common/string_buffer.hpp
  be/src/vec/functions/simple_function_factory.h
  be/test/util/counts_test.cpp
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
Labels: reviewed

#34378 [Fix](Job)Job repaly logic error
  fe/fe-core/src/main/java/org/apache/doris/job/manager/JobManager.java
Labels: approved, reviewed, dev/2.1.x

#34377 [Fix](executor)normal group not auth
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/Auth.java
Labels: approved, reviewed

#34339 [feature](Cloud) Introduce S3 rate limiter to recycler
  cloud/src/common/config.h
  cloud/src/common/sync_point.h
  cloud/src/rate-limiter/CMakeLists.txt
  cloud/src/rate-limiter/s3_rate_limiter.cpp
  cloud/src/rate-limiter/s3_rate_limiter.h
  cloud/src/recycler/recycler_service.cpp
  cloud/src/recycler/s3_accessor.cpp
  cloud/src/recycler/s3_accessor.h
  cloud/test/CMakeLists.txt
  cloud/test/s3_rate_limiter_test.cpp
Labels: approved, reviewed

#34361 [fix](create table) Add hit err msg when create table all be on same …
  fe/fe-core/src/main/java/org/apache/doris/system/SystemInfoService.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/CreateTableTest.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/ModifyBackendTest.java
Labels: approved, reviewed

#34340 [fix](regression) Fix regression run in cloud use non-root user
  regression-test/framework/src/main/groovy/org/apache/doris/regression/Config.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/SuiteContext.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/util/JdbcUtils.groovy
Labels: approved, reviewed

#31183 [feature](regression test) stream load support direct load to be #26829
  regression-test/data/demo_p0/streamLoad_action.out
  regression-test/framework/src/main/groovy/org/apache/doris/regression/action/StreamLoadAction.groovy
  regression-test/suites/chaos/test_docker_example.groovy
  regression-test/suites/demo_p0/streamLoad_action.groovy
Labels: kind/test, approved, reviewed

#34388 [fix](inverted index) Add session switch to compound inlist
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  gensrc/thrift/PaloInternalService.thrift
Labels: approved, reviewed

#34382 [exec](agg) multi merge sort opt the PERCENTILE
  be/src/util/counts.h
  be/test/util/counts_test.cpp
Labels: approved, reviewed

#33634 [feature](pred) Support xor function
  be/src/vec/functions/functions_logical.cpp
  be/src/vec/functions/functions_logical.h
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisLexer.g4
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinScalarFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Xor.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/ScalarFunctionVisitor.java
  regression-test/data/correctness_p0/test_xor_pred.out
  regression-test/suites/correctness_p0/test_xor_pred.groovy
Labels: approved, reviewed

#34393 [opt](func) opt the revert_null_map performance
  be/src/vec/data_types/serde/data_type_serde.h
Labels: approved, reviewed

#34395 [chore](session_variable) Add 'data_queue_max_blocks' to prevent the DataQueue from occupying too much memory. (#34017)
  be/src/pipeline/exec/data_queue.cpp
  be/src/pipeline/exec/data_queue.h
  be/src/pipeline/exec/union_sink_operator.cpp
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/runtime/runtime_state.h
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  gensrc/thrift/PaloInternalService.thrift
  regression-test/data/query_p0/aggregate/distinct_streaming_agg.out
  regression-test/suites/query_p0/aggregate/distinct_streaming_agg.groovy
Labels: meta-change

#34328 [refactor](agg) Use monostate to prevent invalid access to agg variants
  be/src/exec/exec_node.cpp
  be/src/pipeline/dependency.cpp
  be/src/pipeline/dependency.h
  be/src/pipeline/exec/aggregation_sink_operator.cpp
  be/src/pipeline/exec/aggregation_source_operator.cpp
  be/src/pipeline/exec/distinct_streaming_aggregation_operator.cpp
  be/src/pipeline/exec/distinct_streaming_aggregation_operator.h
  be/src/pipeline/exec/hashjoin_build_sink.cpp
  be/src/pipeline/exec/operator.h
  be/src/pipeline/exec/partition_sort_sink_operator.cpp
  be/src/pipeline/exec/partitioned_aggregation_sink_operator.cpp
  be/src/pipeline/exec/streaming_aggregation_operator.cpp
  be/src/pipeline/exec/streaming_aggregation_operator.h
  be/src/pipeline/pipeline_task.cpp
  be/src/pipeline/pipeline_task.h
  be/src/vec/exec/distinct_vaggregation_node.cpp
  be/src/vec/exec/distinct_vaggregation_node.h
  be/src/vec/exec/vaggregation_node.cpp
  be/src/vec/exec/vaggregation_node.h
Labels: approved, reviewed

#34379 [fix](spill) incorrect revocable mem size of hash join
  be/src/pipeline/exec/partitioned_hash_join_probe_operator.cpp
  be/src/pipeline/exec/partitioned_hash_join_sink_operator.cpp
  be/src/runtime/runtime_state.h
Labels: approved, reviewed

#34347 [fix](json) fix be crash while load json data (#34283)
  be/src/vec/exec/format/json/new_json_reader.cpp
Labels: approved, area/vectorization, reviewed

#34249 [test](case) add batch size in long time case
  regression-test/suites/nereids_rules_p0/mv/ssb/mv_ssb_test.groovy
Labels: approved, reviewed, dev/2.0.x

#34398 [revert](cloud) revert support stream load cluster load balance
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/LoadAction.java
Labels: approved, reviewed

#34320 [fix](memory) Fix page cache memory tracker consumption in prune
  be/src/olap/page_cache.h
  be/src/runtime/memory/cache_policy.h
  be/src/runtime/memory/lru_cache_policy.h
Labels: approved, reviewed

#34407 [fix](Fe): remove code `List.of` in java11 grammar
  fe/fe-core/src/main/java/org/apache/doris/backup/Repository.java
Labels: approved, reviewed

#34287 [fix](mtmv)use isManagedTable instead of check table type
  fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/CatalogRecycleBin.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Database.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/transaction/CloudGlobalTransactionMgr.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/IndexInfoProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/RemoteIndexSchemaProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/StatisticProcNode.java
  fe/fe-core/src/main/java/org/apache/doris/consistency/ConsistencyChecker.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/ShowAction.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/StorageTypeCheckAction.java
  fe/fe-core/src/main/java/org/apache/doris/load/ExportJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/ExportTaskExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/DropMTMVInfo.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/query/IndexStats.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/query/QueryStats.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/query/TableStats.java
  regression-test/suites/mtmv_p0/test_recover_mtmv.groovy
Labels: approved, reviewed

#34041 [docker](k8s)Determine the adjustment of the jdk version in the image through the doris version
  docker/runtime/base-image/Dockerfile_base
  docker/runtime/be/Dockerfile
  docker/runtime/broker/Dockerfile
  docker/runtime/fe/Dockerfile
Labels: approved, reviewed

#34415 [opt](Nereids) let behavior of function char same with legacy planner
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Char.java
  regression-test/suites/query_p0/sql_functions/string_functions/test_string_function.groovy
Labels: approved, reviewed

#34392 [opt](ranger) modify and enhance the feature of ranger access controller
  fe/fe-core/src/main/java/org/apache/doris/backup/Repository.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/authorizer/ranger/RangerAccessController.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/authorizer/ranger/doris/DorisAccessType.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/authorizer/ranger/doris/RangerDorisAccessController.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/authorizer/ranger/hive/RangerHiveAccessController.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/PrintableMap.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/Auth.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/Role.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/DateTrunc.java
  fe/fe-core/src/test/java/org/apache/doris/mysql/privilege/RangerTest.java
Labels: approved, reviewed, dev/2.1.x

#34284 [Chore](hash) split out init_hash_method from node/operator
  be/src/pipeline/exec/aggregation_sink_operator.cpp
  be/src/pipeline/exec/distinct_streaming_aggregation_operator.cpp
  be/src/pipeline/exec/partition_sort_sink_operator.cpp
  be/src/pipeline/exec/streaming_aggregation_operator.cpp
  be/src/vec/common/hash_table/hash_map_context_creator.h
  be/src/vec/exec/vaggregation_node.cpp
  be/src/vec/exec/vaggregation_node.h
  be/src/vec/exec/vpartition_sort_node.cpp
  be/src/vec/exec/vpartition_sort_node.h
Labels: approved, reviewed

#34125 [fix](memory) Fix thread context init in MacOS and not use memory tracker
  be/src/runtime/thread_context.h
Labels: approved, reviewed, dev/2.1.x

#34352 [chore](fe) Add some important information in fe log for debug
  fe/fe-core/src/main/java/org/apache/doris/DorisFE.java
  fe/fe-core/src/main/java/org/apache/doris/journal/bdbje/BDBEnvironment.java
  fe/fe-core/src/main/java/org/apache/doris/journal/bdbje/BDBJEJournal.java
Labels: approved, reviewed, dev/2.0.x

#34420 [fix](merge-cloud) fix cloud autobucket num
  fe/fe-core/src/main/java/org/apache/doris/common/util/AutoBucketUtils.java
Labels: approved, reviewed

#34262 [opt](memory) BE memory info compatible with Cgroup
  be/src/util/cgroup_util.cpp
  be/src/util/cgroup_util.h
  be/src/util/mem_info.cpp
  be/src/util/mem_info.h
Labels: approved, reviewed

#34417 [WIP](test) remove enable_nereids_planner in regression cases (part 1)
  regression-test/data/query_p0/sql_functions/array_functions/test_array_functions.out
  regression-test/data/query_p0/sql_functions/cast_function/test_nullable_functions.out
  regression-test/data/show_p0/test_show_create_table_and_views.out
  regression-test/data/view_p0/create_view_star_except_and_cast_to_sql.out
  regression-test/suites/query_p0/sql_functions/aggregate_functions/test_aggregate_push_down_agg.groovy
  regression-test/suites/query_p0/sql_functions/aggregate_functions/test_count_distinct_with_collection_type.groovy
  regression-test/suites/query_p0/sql_functions/array_functions/test_array_functions.groovy
  regression-test/suites/query_p0/sql_functions/cast_function/test_nullable_functions.groovy
  regression-test/suites/query_p0/sql_functions/conditional_functions/test_if.groovy
  regression-test/suites/query_p0/sql_functions/conditional_functions/test_if_cast.groovy
  regression-test/suites/query_p0/sql_functions/conditional_functions/test_ifnull.groovy
  regression-test/suites/query_p0/sql_functions/conditional_functions/test_nullif.groovy
  regression-test/suites/query_p0/sql_functions/table_function/explode_array_decimal.groovy
  regression-test/suites/query_p0/sql_functions/test_alias_function.groovy
  regression-test/suites/query_p0/stats/query_stats_test.groovy
  regression-test/suites/show_p0/test_show_create_table_and_views.groovy
  regression-test/suites/tpcds_sf1_p1/functions_test/test_right_join.groovy
  regression-test/suites/trino_p0/constant_group_key.groovy
  regression-test/suites/unique_with_mow_p0/cluster_key/test_create_table.groovy
  regression-test/suites/update/test_unique_table_update.groovy
  regression-test/suites/update/test_update_mow.groovy
  regression-test/suites/view_p0/create_view_star_except_and_cast_to_sql.groovy
  regression-test/suites/view_p0/view_p0.groovy
Labels: approved, reviewed

#34424 [fix](load) acquire latest token instead of oldest token in TokenManager
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/TokenManager.java
Labels: approved, reviewed, usercase, dev/2.0.x

#34385 [build](third-party) Support to download specified third-party only
  thirdparty/build-thirdparty.sh
  thirdparty/download-thirdparty.sh
Labels: approved, reviewed

#34316 [enhancement](plsql) add regression for failure path
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ShowProcedureStatusCommand.java
  regression-test/suites/plsql_p2/test_plsql_show_procedure_fail.groovy
Labels: approved, reviewed

#34391 [enhancement](function) floor/ceil/round/round_bankers can use column as scale argument
  be/src/vec/functions/function_truncate.h
  be/src/vec/functions/math.cpp
  be/src/vec/functions/round.cpp
  be/src/vec/functions/round.h
  be/src/vec/functions/simple_function_factory.h
  be/test/vec/function/function_round_test.cpp
  be/test/vec/function/function_truncate_decimal_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/ComputePrecisionForRound.java
  regression-test/data/query_p0/sql_functions/math_functions/test_function_truncate.out
  regression-test/data/query_p0/sql_functions/math_functions/test_round.out
  regression-test/suites/query_p0/sql_functions/math_functions/test_function_truncate.groovy
  regression-test/suites/query_p0/sql_functions/math_functions/test_round.groovy
Labels: approved, reviewed

#34432 [Refactor](vec) remove the useless code in column vector
  be/src/pipeline/exec/repeat_operator.cpp
  be/src/vec/columns/column_nullable.h
  be/src/vec/columns/column_vector.h
  be/src/vec/exec/data_gen_functions/vnumbers_tvf.cpp
  be/src/vec/exec/vrepeat_node.cpp
  be/src/vec/exprs/table_function/vexplode_bitmap.cpp
  be/src/vec/exprs/table_function/vexplode_json_array.h
  be/src/vec/exprs/table_function/vexplode_numbers.cpp
  be/src/vec/functions/function_hash.cpp
Labels: approved, reviewed

#34440 [fix](agg) Fix nullptr access
  be/src/pipeline/exec/aggregation_source_operator.cpp
  be/src/vec/common/hash_table/hash_map_context.h
Labels: approved, reviewed

#34442 [fix](load) fix repeatedly open tablets_channel when tablets_channel already cancelled
  be/src/runtime/tablets_channel.cpp
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x

#34445 [improvement](spill) improve cancel
  be/src/pipeline/exec/partitioned_aggregation_sink_operator.cpp
  be/src/pipeline/exec/partitioned_aggregation_sink_operator.h
  be/src/pipeline/exec/partitioned_aggregation_source_operator.cpp
  be/src/pipeline/exec/partitioned_aggregation_source_operator.h
  be/src/pipeline/exec/partitioned_hash_join_probe_operator.cpp
  be/src/pipeline/exec/partitioned_hash_join_probe_operator.h
  be/src/pipeline/exec/partitioned_hash_join_sink_operator.cpp
  be/src/pipeline/exec/partitioned_hash_join_sink_operator.h
  be/src/pipeline/exec/spill_sort_sink_operator.cpp
  be/src/pipeline/exec/spill_sort_sink_operator.h
  be/src/pipeline/exec/spill_sort_source_operator.cpp
  be/src/pipeline/exec/spill_sort_source_operator.h
Labels: approved, reviewed, dev/2.1.3-merged

#34443 [bugfix](memtracker) should count cancelled query in wg memory
  be/src/runtime/memory/mem_tracker_limiter.h
  be/src/runtime/workload_group/workload_group.cpp
Labels: approved, reviewed

#34439 [fix](kerberos)enable hadoop auto renew tgt
  fe/fe-common/src/main/java/org/apache/doris/common/security/authentication/AuthenticationConfig.java
  fe/fe-common/src/main/java/org/apache/doris/common/security/authentication/HadoopUGI.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/HiveTable.java
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x

#34401 [fix](merge-cloud) fix replay modify colocate failed in cloud mode
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
Labels: approved, reviewed

#34134 [opt](inverted index) add inlist condition handling to compound
  be/src/exec/olap_common.h
  be/src/exec/olap_utils.h
  be/src/olap/column_predicate.h
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/olap/rowset/segment_v2/segment_iterator.h
  be/src/olap/tablet_reader.cpp
  be/src/vec/exec/scan/vscan_node.cpp
  be/src/vec/exec/scan/vscan_node.h
  regression-test/data/inverted_index_p0/test_compound_inlist.out
  regression-test/suites/inverted_index_p0/test_compound_inlist.groovy
Labels: approved, reviewed, usercase, dev/2.0.10-merged

#34363 [Improvement](sort) insert data by batch on VSortedRunMerger::get_next
  be/src/vec/columns/column.cpp
  be/src/vec/columns/column.h
  be/src/vec/common/sort/partition_sorter.cpp
  be/src/vec/common/sort/sorter.cpp
  be/src/vec/core/sort_cursor.h
  be/src/vec/data_types/serde/data_type_nullable_serde.cpp
  be/src/vec/runtime/vsorted_run_merger.cpp
  be/src/vec/runtime/vsorted_run_merger.h
Labels: approved, reviewed

#34411 [bug](not in) if not in (null) could eos early
  be/src/pipeline/exec/scan_operator.cpp
Labels: approved, reviewed, dev/2.0.x

#34042 [fix](serde) fix ipv4/v6 serde functions for arrow, orc, parquet format
  be/src/util/arrow/row_batch.cpp
  be/src/vec/data_types/serde/data_type_ipv4_serde.cpp
  be/src/vec/data_types/serde/data_type_ipv4_serde.h
  be/src/vec/data_types/serde/data_type_ipv6_serde.cpp
  be/src/vec/data_types/serde/data_type_ipv6_serde.h
  be/src/vec/data_types/serde/data_type_number_serde.cpp
  be/src/vec/functions/function_cast.h
  be/src/vec/runtime/vorc_transformer.cpp
  fe/fe-core/src/main/java/org/apache/doris/analysis/OutFileClause.java
  regression-test/data/export_p0/test_export_csv.out
  regression-test/data/export_p0/test_export_data_types.out
  regression-test/data/export_p0/test_export_orc.out
  regression-test/data/export_p0/test_export_parquet.out
  regression-test/data/export_p0/test_outfile_csv_with_names.out
  regression-test/data/export_p0/test_outfile_csv_with_names_and_types.out
  regression-test/suites/export_p0/test_export_csv.groovy
  regression-test/suites/export_p0/test_export_data_types.groovy
  regression-test/suites/export_p0/test_export_empty_table.groovy
  regression-test/suites/export_p0/test_export_orc.groovy
  regression-test/suites/export_p0/test_export_parquet.groovy
  regression-test/suites/export_p0/test_outfile_csv_with_names.groovy
  regression-test/suites/export_p0/test_outfile_csv_with_names_and_types.groovy
Labels: approved, reviewed

#34266 [FIX]fix is_ip_address_in_range func with const param
  be/src/vec/functions/function_ip.h
  be/test/vec/function/function_ip_test.cpp
  regression-test/data/query_p0/sql_functions/ip_functions/test_is_ip_address_in_range_function.out
  regression-test/suites/query_p0/sql_functions/ip_functions/test_is_ip_address_in_range_function.groovy
Labels: approved, reviewed

#34472 [fix](ci) kafka docker image missed, walk around it tmp
  regression-test/pipeline/cloud_p0/conf/regression-conf-custom.groovy
  regression-test/pipeline/cloud_p0/run.sh
  regression-test/pipeline/p0/conf/regression-conf.groovy
Labels: approved, reviewed

#33610 [opt](catalog) support using loading cache for db/table list in external catalog
  fe/be-java-extensions/trino-connector-scanner/src/main/java/org/apache/doris/trinoconnector/TrinoConnectorJniScanner.java
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Database.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/DatabaseIf.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/JdbcResource.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/MysqlCompatibleDatabase.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/RefreshManager.java
  fe/fe-core/src/main/java/org/apache/doris/common/CacheFactory.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/Util.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/CatalogFactory.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/CatalogIf.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/CatalogMgr.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalDatabase.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalMetaCacheMgr.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalSchemaCache.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/es/EsExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/es/EsExternalDatabase.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HMSExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HMSExternalDatabase.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HiveMetaStoreCache.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/event/AlterTableEvent.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/event/InsertEvent.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hudi/source/HudiCachedPartitionProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/IcebergExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/IcebergExternalDatabase.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/IcebergMetadataCache.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/IcebergMetadataOps.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/infoschema/ExternalInfoSchemaDatabase.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/infoschema/ExternalMysqlDatabase.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/JdbcExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/JdbcExternalDatabase.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/maxcompute/MaxComputeExternalDatabase.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/metacache/MetaCache.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/paimon/PaimonExternalDatabase.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/test/TestExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/test/TestExternalDatabase.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/trinoconnector/TrinoConnectorExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/trinoconnector/TrinoConnectorExternalDatabase.java
  fe/fe-core/src/main/java/org/apache/doris/qe/GlobalVariable.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsCleaner.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/query/DataBaseStats.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/AlterCatalogPropsStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/common/CacheFactoryTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/CatalogMgrTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/RefreshCatalogTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/iceberg/CreateIcebergTableTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/property/PropertyConverterTest.java
  fe/fe-core/src/test/java/org/apache/doris/external/hms/HmsCatalogTest.java
  fe/fe-core/src/test/java/org/apache/doris/qe/HmsQueryCacheTest.java
  regression-test/data/external_table_p0/hive/test_hive_use_meta_cache.out
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
  regression-test/suites/external_table_p0/hive/test_hive_use_meta_cache.groovy
  regression-test/suites/external_table_p0/hive/write/test_hive_write_partitions.groovy
Labels: approved, reviewed, dev/2.1.x

#34466 [Bug](RegressionTest) fix regresstion test failed
  be/src/vec/functions/round.h
Labels: approved, reviewed

#34290 [feat](Nereids): Put the Child with Least Row Count in the First Position of Intersect
  fe/fe-core/src/main/java/org/apache/doris/nereids/cost/CostModelV1.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleSet.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/IntersectReorder.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/exploration/IntersectReorderTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/util/LogicalPlanBuilder.java
  regression-test/data/nereids_tpcds_shape_sf1000_p0/bs_downgrade_shape/query8.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/shape/query38.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/shape/query8.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/noStatsRfPrune/query14.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/noStatsRfPrune/query38.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/noStatsRfPrune/query8.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/no_stats_shape/query14.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/no_stats_shape/query38.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/no_stats_shape/query8.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/rf_prune/query38.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/rf_prune/query8.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query38.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query8.out
Labels: approved, reviewed

#34233 [feat](Nereids): compute func deps in logical plan
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/FuncDeps.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/FuncDepsDAG.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/FuncDepsDG.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/FunctionalDependencies.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/BlockFuncDepsPropagation.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PropagateFuncDeps.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalAggregate.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalAssertNumRows.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalCatalogRelation.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalDeferMaterializeTopN.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalExcept.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalFilter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalGenerate.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalHaving.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalIntersect.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalJoin.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalLimit.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalOneRowRelation.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalPlan.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalProject.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalRepeat.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalSubQueryAlias.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalTopN.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalUnion.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalView.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalWindow.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/ImmutableEqualSet.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/properties/FuncDepsDGTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/properties/FuncDepsTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/properties/FunctionalDependenciesTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/properties/UniformTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/properties/UniqueTest.java
Labels: approved, reviewed

#34430 [chore](planner) remove some useless code
  fe/fe-core/src/main/java/org/apache/doris/analysis/ArithmeticExpr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/BinaryPredicate.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/BitmapFilterPredicate.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CastExpr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ColumnRefExpr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/DecimalLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/EncryptKeyRef.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ExistsPredicate.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/Expr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/GroupingFunctionCallExpr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/IPv4Literal.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/IPv6Literal.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/InPredicate.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/IntLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/JsonLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/LambdaFunctionExpr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/LargeIntLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/MatchPredicate.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/PlaceHolderExpr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SlotRef.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/VirtualSlotRef.java
Labels: approved, reviewed

#34383 [fix](compactiono) fix time series compaction policy in cloud
  be/src/cloud/cloud_cumulative_compaction_policy.cpp
  be/src/cloud/cloud_tablet.cpp
  be/src/cloud/cloud_tablet.h
  be/src/olap/base_tablet.cpp
  be/src/olap/base_tablet.h
  be/src/olap/cumulative_compaction_time_series_policy.cpp
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
  regression-test/suites/compaction/test_time_series_compaction_policy.groovy
Labels: approved, reviewed

#34397 [chore](status) unify error code between thrift,pb, status.h
  be/src/common/status.cpp
  be/src/common/status.h
  be/src/service/doris_main.cpp
  be/test/common/status_test.cpp
  gensrc/thrift/Status.thrift
  regression-test/suites/external_table_p0/hive/ddl/test_hive_write_type.groovy
Labels: approved, reviewed, meta-change

#34493 [fix](ci) exclude routine load case tmp
  regression-test/pipeline/cloud_p0/conf/regression-conf-custom.groovy
  regression-test/pipeline/p0/conf/regression-conf.groovy
Labels: approved, reviewed

#32980 [improve](txn insert) txn insert support write to one table many times
  fe/fe-common/src/main/java/org/apache/doris/common/FeMetaVersion.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/TabletInvertedIndex.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/transaction/CloudGlobalTransactionMgr.java
  fe/fe-core/src/main/java/org/apache/doris/journal/JournalEntity.java
  fe/fe-core/src/main/java/org/apache/doris/load/DeleteHandler.java
  fe/fe-core/src/main/java/org/apache/doris/load/DeleteJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/EtlStatus.java
  fe/fe-core/src/main/java/org/apache/doris/load/FailMsg.java
  fe/fe-core/src/main/java/org/apache/doris/load/TxnDeleteJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadJobFinalOperation.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/MiniLoadTxnCommitAttachment.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/KafkaProgress.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RLTaskTxnCommitAttachment.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadProgress.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/InsertIntoTableCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/InsertUtils.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/OlapInsertExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/OlapTxnInsertExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/persist/gson/GsonUtils.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContext.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/task/PublishVersionTask.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/GlobalTransactionMgr.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/GlobalTransactionMgrIface.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/PublishVersionDaemon.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/SubTransactionState.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/TableCommitInfo.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/TransactionEntry.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/TransactionState.java
  fe/fe-core/src/test/java/org/apache/doris/transaction/DatabaseTransactionMgrTest.java
  fe/fe-core/src/test/java/org/apache/doris/transaction/GlobalTransactionMgrTest.java
  fe/fe-core/src/test/java/org/apache/doris/transaction/TransactionStateTest.java
  regression-test/data/insert_p0/txn_insert.out
  regression-test/data/insert_p0/txn_insert_with_schema_change.out
  regression-test/data/insert_p2/txn_insert.out
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
  regression-test/suites/insert_p0/insert_group_commit_into.groovy
  regression-test/suites/insert_p0/txn_insert.groovy
  regression-test/suites/insert_p0/txn_insert_concurrent_insert.groovy
  regression-test/suites/insert_p0/txn_insert_inject_case.groovy
  regression-test/suites/insert_p0/txn_insert_values_with_schema_change.groovy
  regression-test/suites/insert_p0/txn_insert_with_schema_change.groovy
  regression-test/suites/insert_p2/txn_insert.groovy
Labels: approved, reviewed, meta-change

#34479 [fix](mow) cloud tablet should consider delete in cumu compaction
  be/src/cloud/cloud_base_compaction.cpp
  be/src/cloud/cloud_cumulative_compaction.cpp
  be/src/cloud/cloud_tablet.cpp
  be/src/cloud/cloud_tablet.h
Labels: approved, reviewed

#34405 [fix](compile) fix macos compile error
  be/src/io/cache/block_file_cache_downloader.cpp
  be/src/vec/functions/functions_logical.cpp
  fe/fe-core/src/main/java/org/apache/doris/analysis/DateLiteral.java
Labels: approved, reviewed

#34465 [fix](core) fix error sort in profile
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/runtime_state.cpp
  be/src/runtime/runtime_state.h
  be/src/util/runtime_profile.cpp
  be/src/util/runtime_profile.h
  fe/fe-core/src/main/java/org/apache/doris/common/profile/ExecutionProfile.java
Labels: approved, reviewed

#34497 [refactor](executor)Rename workload schedule policy
  be/src/exec/schema_scanner.cpp
  be/src/exec/schema_scanner/schema_workload_sched_policy_scanner.cpp
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/SchemaTableType.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/SchemaTable.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/MetadataGenerator.java
  gensrc/thrift/Descriptors.thrift
  regression-test/data/external_table_p0/jdbc/test_mariadb_jdbc_catalog.out
  regression-test/data/external_table_p0/jdbc/test_mysql_jdbc_catalog.out
  regression-test/data/external_table_p0/jdbc/test_mysql_jdbc_catalog_nereids.out
  regression-test/data/external_table_p0/jdbc/test_mysql_jdbc_driver5_catalog.out
  regression-test/suites/workload_manager_p0/test_workload_sched_policy.groovy
Labels: approved, reviewed, meta-change, workload-schedule

#34433 [improvement](statistics)Write audit log while doing drop stats.
  fe/fe-core/src/main/java/org/apache/doris/statistics/util/StatisticsUtil.java
Labels: approved, reviewed

#34448 [Fix](third-party) Fix missing patching jemalloc when build third-party introduced by #34385
  thirdparty/build-thirdparty.sh
  thirdparty/download-thirdparty.sh
Labels: approved, reviewed

#34492 [fix](test) Rewrite `test_show_data_warehouse` case due to not stable
  regression-test/suites/show_p0/test_show_data_warehouse.groovy
Labels: approved, reviewed

#34486 [typo](log) Let env lock msg more distinct #27493
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
Labels: approved, reviewed

#34488 [refactor](move-memtable) simplify LoadStreamStub::open
  be/src/vec/sink/load_stream_stub.cpp
  be/src/vec/sink/load_stream_stub.h
  be/src/vec/sink/writer/vtablet_writer_v2.cpp
Labels: approved, reviewed

#32958 [feature](shuffle) enable strict consistency dml by default
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalOlapTableSink.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/planner/PlannerTest.java
Labels: approved, reviewed, dev/2.1.x

#34247 [Feature](PreparedStatement) implement general server side prepared
  be/src/runtime/runtime_state.h
  be/src/service/point_query_executor.cpp
  be/src/vec/sink/vresult_sink.cpp
  fe/fe-common/src/main/java/org/apache/doris/catalog/Type.java
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/BinaryPredicate.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/Expr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/LiteralExpr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/NativeInsertStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/PlaceHolderExpr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/PrepareStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/StatementBase.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/StringLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/MysqlProto.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/PointQueryExec.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/main/jflex/sql_scanner.flex
  regression-test/data/point_query_p0/test_point_query.out
  regression-test/data/prepared_stmt_p0/prepared_stmt.out
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/util/JdbcUtils.groovy
  regression-test/suites/point_query_p0/test_point_query.groovy
  regression-test/suites/prepared_stmt_p0/prepared_stmt.groovy
Labels: area/planner, kind/test, approved, reviewed

#34450 [fix](spill) incorrect result of hash join
  be/src/pipeline/exec/partitioned_hash_join_probe_operator.cpp
  be/src/pipeline/exec/partitioned_hash_join_sink_operator.cpp
  be/src/vec/core/block.cpp
Labels: approved, reviewed

#34121 [bug](ipv6) the ipv6 type should be uint128_t
  be/src/olap/types.h
  regression-test/data/datatype_p0/ip/test_ip_basic.out
  regression-test/suites/datatype_p0/ip/test_ip_basic.groovy
Labels: approved, reviewed

#34305 [feature](statistics)Create partition statistics table.
  fe/fe-core/src/main/java/org/apache/doris/catalog/InternalSchema.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/InternalSchemaInitializer.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/ExternalAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/JdbcAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/OlapAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticConstants.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsCleaner.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsRepository.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/util/StatisticsUtil.java
  fe/fe-core/src/test/java/org/apache/doris/alter/InternalSchemaAlterTest.java
Labels: approved, reviewed

#34476 [opt](inverted index)Modify the parameter passing method for compound inlist
  be/src/exec/olap_utils.h
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/vec/exec/scan/vscan_node.cpp
Labels: approved, reviewed

#34454 [fix](tracing) Fix wrong global variable init order of tracing log dir
  be/src/pipeline/pipeline_tracing.cpp
  be/src/pipeline/pipeline_tracing.h
Labels: approved, reviewed, meta-change

#34495 [improvement](cloud-merge) Enables concurrent file downloads
  be/src/cloud/cloud_warm_up_manager.cpp
  be/src/cloud/cloud_warm_up_manager.h
  be/src/io/cache/block_file_cache_downloader.cpp
Labels: approved, reviewed

#34462 [pipeline](fix) Prevent re-cancel pipeline tasks
  be/src/pipeline/pipeline_fragment_context.cpp
Labels: approved, reviewed, only-4.0

#34441 [test](ES Catalog) Add test cases for ES 5.x
  docker/thirdparties/docker-compose/elasticsearch/es.env
  docker/thirdparties/docker-compose/elasticsearch/es.yaml.tpl
  docker/thirdparties/docker-compose/elasticsearch/scripts/data/data3_es5.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/es_init.sh
  regression-test/conf/regression-conf.groovy
  regression-test/data/external_table_p0/es/test_es_query.out
  regression-test/pipeline/external/conf/regression-conf.groovy
  regression-test/suites/external_table_p0/es/test_es_query.groovy
Labels: approved, reviewed

#34024 [opt](inverted index) opt for log output when matching without an index
  be/src/vec/functions/match.cpp
Labels: approved, reviewed

#34431 [fix](mtmv)fix refresh failed when not use db before create MTMV
  fe/fe-core/src/main/java/org/apache/doris/job/extensions/mtmv/MTMVTask.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVPlanUtil.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/TableCollector.java
  fe/fe-core/src/test/java/org/apache/doris/cluster/DecommissionBackendTest.java
  regression-test/suites/mtmv_p0/test_env_db_dropped_mtmv.groovy
Labels: approved, reviewed

#34402 [Refactor](exec) refactor the pipline code
  be/src/common/status.h
  be/src/pipeline/exec/operator.cpp
  be/src/pipeline/exec/operator.h
  be/src/pipeline/pipeline_task.cpp
  be/src/pipeline/pipeline_task.h
  be/src/pipeline/pipeline_tracing.h
  be/src/pipeline/task_queue.cpp
  be/src/pipeline/task_queue.h
  be/src/pipeline/task_scheduler.cpp
  be/src/pipeline/task_scheduler.h
Labels: approved, reviewed

#34509 [bugfix](compile error) unused variables compile error
  be/src/common/status.h
  be/src/pipeline/pipeline_task.h
Labels: approved, reviewed, 4.0.0

#34503 [chore](log) add try lock db failed log
  fe/fe-core/src/main/java/org/apache/doris/catalog/Database.java
Labels: approved, reviewed

#34423 [optimization](agg) add more type in agg percentile
  be/src/util/counts.h
  be/src/vec/aggregate_functions/aggregate_function_percentile.cpp
  be/src/vec/aggregate_functions/aggregate_function_percentile.h
  be/test/util/counts_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/Percentile.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/PercentileArray.java
  regression-test/data/mv_p0/mv_percentile/mv_percentile.out
  regression-test/data/nereids_p0/sql_functions/aggregate_functions/test_aggregate_percentile_no_cast.out
  regression-test/suites/mv_p0/mv_percentile/mv_percentile.groovy
  regression-test/suites/nereids_p0/sql_functions/aggregate_functions/test_aggregate_percentile_no_cast.groovy
Labels: approved, reviewed

#31268 [fix](merge-on-write) remove some CHECKs in Tablet::revise_tablet_meta
  be/src/olap/base_tablet.cpp
  be/src/olap/base_tablet.h
  be/src/olap/tablet.cpp
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x

#34515 [improve] Make the schema change memory space adaptive
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/olap/schema_change.h
  be/src/olap/storage_engine.cpp
  be/src/olap/storage_engine.h
  be/src/olap/task/engine_alter_tablet_task.cpp
  be/src/olap/task/engine_index_change_task.cpp
Labels: approved, reviewed

#34293 [test](fix) Fix test check fail when test nested mv hit
  regression-test/suites/nereids_rules_p0/mv/nested_mtmv/nested_mtmv.groovy
Labels: approved, reviewed

#34531 [fix](local exchange) fix bug of local exchange free blocks
  be/src/pipeline/pipeline_x/local_exchange/local_exchanger.cpp
Labels: approved, reviewed

#34196 [Fix](nereids) fix NormalizeRepeat, change the outputExpression rewrite logic
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/NormalizeRepeat.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/NormalizeToSlot.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/BuiltinFunctionBuilder.java
  regression-test/data/nereids_rules_p0/grouping_sets/grouping_normalize_test.out
  regression-test/suites/nereids_rules_p0/grouping_sets/grouping_normalize_test.groovy
Labels: approved, reviewed

#34506 [Fix](job)Reclaim resources held by finished tasks
  fe/fe-core/src/main/java/org/apache/doris/job/extensions/insert/InsertTask.java
  fe/fe-core/src/main/java/org/apache/doris/job/extensions/mtmv/MTMVTask.java
  fe/fe-core/src/main/java/org/apache/doris/job/task/AbstractTask.java
Labels: approved, reviewed, dev/2.1.x

#34535 [fix](load) acquire latest token instead of oldest token in TokenManager (#34424)
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/TokenManager.java
Labels: area/load

#34513 [improve](restore) Release useless info for the finished job to reduce mem usage
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupJobInfo.java
  fe/fe-core/src/main/java/org/apache/doris/backup/RestoreFileMapping.java
  fe/fe-core/src/main/java/org/apache/doris/backup/RestoreJob.java
Labels: approved, reviewed, dev/2.0.x

#34502 [pipeline](fix) Logging blocking dependency if task is not cancelled
  be/src/pipeline/pipeline_task.cpp
Labels: approved, reviewed, dev/2.1.3-merged

#34549 [Refactor](Sink) Remove is_append mode in table sink
  be/src/olap/delta_writer.cpp
  be/src/olap/delta_writer.h
  be/src/olap/memtable.cpp
  be/src/olap/memtable.h
  be/src/runtime/tablets_channel.cpp
  be/src/vec/sink/vtablet_sink.cpp
  be/src/vec/sink/vtablet_sink.h
Labels: approved, reviewed

#34526 [Improve] Estimated column reader memory to control segment cache
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/olap/rowset/segment_v2/segment.cpp
  be/src/olap/rowset/segment_v2/segment.h
  be/src/olap/segment_loader.cpp
  be/src/olap/segment_loader.h
  be/src/runtime/exec_env_init.cpp
Labels: approved, reviewed, dev/2.0.x

#34444 [config](move-memtable) support HTTP header load_stream_per_node in stream load
  be/src/http/action/stream_load.cpp
  be/src/http/http_common.h
Labels: approved, reviewed

#34530 [fix](local exchange) fix bug of local exchange free blocks
  be/src/pipeline/local_exchange/local_exchanger.cpp
Labels: approved, reviewed, dev/2.1.3-merged

#34547 [fix](txn insert) Txn insert stuck if execute on observer fe
  fe/fe-core/src/main/java/org/apache/doris/analysis/NativeInsertStmt.java
  regression-test/suites/insert_p0/insert_group_commit_into.groovy
Labels: approved, reviewed

#34546 [bugfix](gccompile) fix gcc compile error
  be/src/service/doris_main.cpp
Labels: approved, reviewed

#34536 [localexchange](conf) Add a variable to limit free blocks memory
  be/src/pipeline/local_exchange/local_exchanger.cpp
  be/src/pipeline/local_exchange/local_exchanger.h
  be/src/pipeline/pipeline_fragment_context.cpp
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  gensrc/thrift/PaloInternalService.thrift
Labels: approved, reviewed, meta-change

#34475 [opt](Nereids) support where, group by, having, order by clause without from clause in query statement
  fe/fe-common/src/main/java/org/apache/doris/catalog/ScalarType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/BindExpression.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/analysis/FunctionRegistryTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/expressions/UdfTest.java
  regression-test/data/nereids_p0/select_no_from/sql/withWhereFalse.out
  regression-test/suites/nereids_p0/select_no_from/sql/withWhereFalse.sql
  regression-test/suites/nereids_syntax_p0/bind_priority.groovy
  regression-test/suites/nereids_syntax_p0/one_row_relation.groovy
Labels: kind/test, area/nereids

#34543 [fix](Nereids) array_intersect should be a variadic function
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/ArrayIntersect.java
Labels: approved, reviewed

#34561 [tools] update bucket number in schema file
  tools/tpcds-tools/ddl/create-tpcds-tables-sf1000.sql
Labels: approved, reviewed

#34477 [fix](hive) fix query external table make BE crash
  fe/fe-core/src/main/java/org/apache/doris/planner/external/ExternalFileScanNode.java
Labels: area/planner

#34435 [Fix](planner) fix ScalarType.getAssignmentCompatibleType() when deal boolean and decimal
  fe/fe-common/src/main/java/org/apache/doris/catalog/ScalarType.java
  regression-test/data/datatype_p0/scalar_types/get_assignment_compatible_type.out
  regression-test/suites/datatype_p0/scalar_types/get_assignment_compatible_type.groovy
Labels: approved, reviewed, dev/2.0.x

#33807 [Feature](PreparedStatement) implement general server side prepared
  be/src/pipeline/exec/result_sink_operator.cpp
  be/src/runtime/runtime_state.h
  be/src/service/point_query_executor.cpp
  be/src/vec/sink/vresult_sink.cpp
  fe/fe-common/src/main/java/org/apache/doris/catalog/Type.java
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/BinaryPredicate.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/Expr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/LiteralExpr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/NativeInsertStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/PlaceHolderExpr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/PrepareStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/StatementBase.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/StringLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/MysqlConnectProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/PointQueryExec.java
  fe/fe-core/src/main/java/org/apache/doris/qe/PrepareStmtContext.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/main/jflex/sql_scanner.flex
  regression-test/data/point_query_p0/test_point_query.out
  regression-test/data/point_query_p0/test_point_query_cluster_key.out
  regression-test/data/prepared_stmt_p0/prepared_stmt.out
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/util/JdbcUtils.groovy
  regression-test/suites/point_query_p0/test_point_query.groovy
  regression-test/suites/point_query_p0/test_point_query_cluster_key.groovy
  regression-test/suites/prepared_stmt_p0/prepared_stmt.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x

#34463 [refactor](type) change some type inheritance relationship and remove useless interface
  fe/fe-common/src/main/java/org/apache/doris/catalog/AggStateType.java
  fe/fe-common/src/main/java/org/apache/doris/catalog/ArrayType.java
  fe/fe-common/src/main/java/org/apache/doris/catalog/MapType.java
  fe/fe-common/src/main/java/org/apache/doris/catalog/ScalarType.java
  fe/fe-common/src/main/java/org/apache/doris/catalog/StructType.java
  fe/fe-common/src/main/java/org/apache/doris/catalog/Type.java
  fe/fe-common/src/main/java/org/apache/doris/catalog/VariantType.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/Expr.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/types/AggStateType.java
  regression-test/suites/datatype_p0/agg_state/max/test_agg_state_max.groovy
Labels: approved, reviewed

#34569 [chore](sink) remove `load_block_to_single_tablet` flag in sink
  be/src/vec/sink/vtablet_sink.cpp
Labels: approved, reviewed

#34517 [fix](catalog) refactor the schema cache for external table
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalDatabase.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalSchemaCache.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/SchemaCacheValue.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/es/EsExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HMSExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HMSSchemaCacheValue.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/IcebergExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/infoschema/ExternalInfoSchemaTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/infoschema/ExternalMysqlTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/JdbcExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/maxcompute/MaxComputeExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/maxcompute/MaxComputeSchemaCacheValue.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/metacache/MetaCache.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/paimon/PaimonExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/paimon/PaimonSchemaCacheValue.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/paimon/source/PaimonSource.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/test/TestExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/trinoconnector/TrinoConnectorExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/trinoconnector/TrinoSchemaCacheValue.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/AcceptListener.java
Labels: approved, reviewed, dev/2.1.x

#34552 [feature](statistics)Support collect OlapTable partition stats
  fe/fe-core/src/main/java/org/apache/doris/catalog/Table.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/TableIf.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HMSExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/BaseAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/OlapAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticConstants.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/util/StatisticsUtil.java
Labels: approved, reviewed

#34428 [fix](compatibility) add some keywords #29251
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisLexer.g4
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/test/java/org/apache/doris/nereids/parser/NereidsParserTest.java
Labels: approved, reviewed, area/nereids

#34244 [improve](shcema change)fix alter table faild when modify multiple columns with column changed positions
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
  regression-test/suites/alter_p0/test_alter_muti_modify_column.groovy
Labels: approved, reviewed

#34580 [fix](s3) fix SdkClientException: Multiple HTTP implementations were found on the classpath #17136
  fe/fe-core/src/main/java/org/apache/doris/PaloFe.java
Labels: approved, reviewed

#34150 [Bug](Variant) fix rapidjson::Allocator may cause mem allocate issue when build with `DENABLE_CLANG_COVERAGE`
  be/src/vec/columns/column_object.cpp
  be/src/vec/data_types/serde/data_type_array_serde.cpp
  be/src/vec/data_types/serde/data_type_array_serde.h
  be/src/vec/data_types/serde/data_type_jsonb_serde.cpp
  be/src/vec/data_types/serde/data_type_jsonb_serde.h
  be/src/vec/data_types/serde/data_type_nullable_serde.cpp
  be/src/vec/data_types/serde/data_type_nullable_serde.h
  be/src/vec/data_types/serde/data_type_number_serde.h
  be/src/vec/data_types/serde/data_type_serde.cpp
  be/src/vec/data_types/serde/data_type_serde.h
  be/src/vec/data_types/serde/data_type_string_serde.h
Labels: approved, reviewed

#34575 [bug](config) Fix modifying `label_num_threshold` does not take effect
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java
Labels: approved, reviewed, dev/2.0.x

#34219 [branch-2.1](resource)fix check available fail when s3 aws_token is set and reset as, sk faild on be.
  be/src/agent/task_worker_pool.cpp
  be/src/io/fs/s3_file_system.cpp
  be/src/io/fs/s3_file_system.h
  fe/fe-core/src/main/java/org/apache/doris/catalog/S3Resource.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/constants/S3Properties.java
  gensrc/thrift/AgentService.thrift
  regression-test/suites/cold_heat_separation/policy/alter.groovy
Labels: approved, reviewed, meta-change

#34576 [bug](branch2.0) Fix modifying label_num_threshold does not take effect
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java
Labels: approved, reviewed

#34605 [fix](shuffle) compensate num rows filtered in ExchangeNode
  be/src/pipeline/exec/exchange_sink_operator.cpp
Labels: approved, reviewed

#34571 [fix](cloud) Fix working dir of the cloud start.sh
  cloud/script/start.sh
Labels: approved, reviewed, 4.0.0

#34559 [refactor](nereids) do not deny a runtime filter by removing an entry in aliasMap
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/RuntimeFilterContext.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/RuntimeFilterGenerator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/RuntimeFilterPushDownVisitor.java
  regression-test/data/nereids_tpcds_shape_sf1000_p0/shape/query35.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/rf_prune/query35.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query35.out
Labels: approved, reviewed

#34491 [Improvement](sink) remove unused check on string's write_column_to_mysql
  be/src/vec/columns/column_string.h
  be/src/vec/data_types/serde/data_type_string_serde.h
Labels: approved, reviewed

#34589 [bugfix](multi catalog) fixed an issue where the hive catalog field d…
  fe/fe-core/src/main/java/org/apache/doris/planner/external/HiveScanNode.java
Labels: area/planner, approved, reviewed

#34583 [Fix](functions) Fix bug in makedate and str_to_date functions
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/executable/DateTimeExtractAndTransform.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/DateUtils.java
  regression-test/data/query_p0/sql_functions/datetime_functions/test_date_function.out
  regression-test/suites/query_p0/sql_functions/datetime_functions/test_date_function.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x

#34527 [pipeline](refactor) remove pipeline task state
  be/src/pipeline/dependency.cpp
  be/src/pipeline/dependency.h
  be/src/pipeline/pipeline_task.cpp
  be/src/pipeline/pipeline_task.h
  be/src/pipeline/pipeline_tracing.h
  be/src/pipeline/task_scheduler.cpp
Labels: approved, reviewed

#34588 [fix](merge-on-write) cloud mow delete bitmap correctness check core
  be/src/cloud/cloud_tablet.cpp
  be/src/olap/base_tablet.cpp
  be/src/olap/tablet.cpp
  fe/fe-core/src/main/java/org/apache/doris/cloud/transaction/CloudGlobalTransactionMgr.java
  regression-test/data/fault_injection_p0/cloud/test_cloud_mow_delete_bitmap_calc_timeout.out
  regression-test/suites/fault_injection_p0/cloud/test_cloud_mow_delete_bitmap_calc_timeout.groovy
Labels: approved, reviewed

#34516 [feature](tvf) support query table value function
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinTableValuedFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/JdbcExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/JdbcExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/client/JdbcClient.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/source/JdbcScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/table/Query.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/TableValuedFunctionVisitor.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/JdbcQueryTableValueFunction.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/QueryTableValueFunction.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/TableValuedFunctionIf.java
  regression-test/data/external_table_p0/jdbc/test_jdbc_query_tvf.out
  regression-test/suites/external_table_p0/jdbc/test_jdbc_query_tvf.groovy
Labels: approved, reviewed, kind/need-document, dev/2.0.x, dev/2.1.x

#34578 [fix](memory) Fix jdk17 and jemalloc hook not compatible on some envs
  be/CMakeLists.txt
  be/src/common/daemon.cpp
  be/src/http/action/jeprofile_actions.cpp
  be/src/http/action/pprof_actions.cpp
  be/src/http/default_path_handlers.cpp
  be/src/pch/pch.h
  be/src/runtime/CMakeLists.txt
  be/src/runtime/memory/tcmalloc_hook.h
  be/src/runtime/thread_context.h
  be/src/service/doris_main.cpp
  be/src/util/mem_info.cpp
  be/src/util/mem_info.h
  bin/start_be.sh
  build.sh
  cloud/CMakeLists.txt
  cloud/cmake/thirdparty.cmake
  cloud/src/common/CMakeLists.txt
  regression-test/pipeline/performance/compile.sh
  thirdparty/build-thirdparty.sh
Labels: approved, reviewed

#34573 [fix](Nereids): fix choose id when there is enforcer in group
  fe/fe-core/src/main/java/org/apache/doris/nereids/memo/Group.java
Labels: approved, reviewed

#34289 [fix](json function) fix failed when json_exists_path use not null input
  be/src/vec/functions/function_jsonb.cpp
  regression-test/data/json_p0/test_json_load_and_function.out
  regression-test/suites/json_p0/test_json_load_and_function.groovy
Labels: approved, reviewed, dev/2.0.x

#34593 [enhance](mtmv)add baseTablesOneLevel for MTMVRelation and MTMVRelationManager
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVPlanUtil.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVRelation.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVRelationManager.java
  fe/fe-core/src/test/java/org/apache/doris/mtmv/MTMVRelationManagerTest.java
  fe/fe-core/src/test/java/org/apache/doris/mtmv/MTMVTaskTest.java
  fe/fe-core/src/test/java/org/apache/doris/mtmv/MTMVTest.java
Labels: approved, reviewed

#34622 [fix](merge-cloud) fix single rowset did not trigger compaction in cloud mode
  be/src/cloud/cloud_cumulative_compaction_policy.cpp
  regression-test/suites/compaction/test_base_compaction.groovy
  regression-test/suites/compaction/test_base_compaction_no_value.groovy
Labels: reviewed

#34484 [Fix](Planner) add date/month/year add function fe constant fold with dateV2/dateTimeV2
  fe/fe-core/src/main/java/org/apache/doris/rewrite/FEFunctions.java
  regression-test/suites/query_p0/sql_functions/datetime_functions/test_date_function.groovy
Labels: kind/test, approved, reviewed

#34519 [opt](nereids)estimate rowcount for is-null filter when column stats are not available
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/FilterEstimation.java
  regression-test/data/nereids_tpcds_shape_sf100_p0/noStatsRfPrune/query76.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/no_stats_shape/query76.out
Labels: approved, reviewed

#34602 [Bug](runtime-filter) fix coredump won change_null_to_true when argument column is not null…
  be/src/vec/utils/util.hpp
  regression-test/data/query_p0/join/rqg/rqg471923/rqg1333347798.out
  regression-test/suites/query_p0/join/rqg/rqg471923/rqg1333347798.groovy
Labels: approved, reviewed

#34512 [regression-test](pipelinex parameter) modify fuzz batch_size to make regression more faster
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
Labels: approved, reviewed

#34528 [chore](remove code) Remove dragonbox related
  be/cmake/thirdparty.cmake
  be/src/gutil/CMakeLists.txt
  be/src/gutil/strings/numbers.cc
  be/src/gutil/strings/numbers.h
  be/src/runtime/runtime_state.h
  be/src/util/mysql_row_buffer.cpp
  be/src/util/mysql_row_buffer.h
  be/src/vec/sink/vmysql_result_writer.cpp
  be/src/vec/sink/vmysql_result_writer.h
  be/test/util/mysql_row_buffer_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  gensrc/thrift/PaloInternalService.thrift
  regression-test/data/mysql_tupleconvert_p0/mysql_tupleconvert.out
  regression-test/suites/mysql_tupleconvert_p0/mysql_tupleconvert.groovy
  thirdparty/build-thirdparty.sh
  thirdparty/vars.sh
Labels: approved, reviewed, meta-change

#34613 [fix](keyword) let some keyword as non-reserved
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisLexer.g4
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/cup/sql_parser.cup
Labels: approved, reviewed, dev/2.1.x

#34618 [fix](jdbc catalog) Fix ClassLoader Scope in JdbcExecutor Initialization
  fe/be-java-extensions/jdbc-scanner/src/main/java/org/apache/doris/jdbc/BaseJdbcExecutor.java
  fe/be-java-extensions/jdbc-scanner/src/main/java/org/apache/doris/jdbc/DefaultJdbcExecutor.java
Labels: approved, reviewed, dev/2.0.x, dev/2.1.4-merged

#34581 [opt](join) For a mark join without other conjuncts, stop probing after matching one row
  be/src/vec/common/hash_table/join_hash_table.h
Labels: approved, reviewed

#34554 [fix](replication_allocation) fix two problems for force_olap_table_replication_allocation
  fe/fe-core/src/main/java/org/apache/doris/common/util/DynamicPartitionUtil.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/UserPropertyMgr.java
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x

#34550 [Fix](executor)Fix duplicate normal workload group when upgrade 2.0->2.1.1->2.1.2
  fe/fe-core/src/main/java/org/apache/doris/resource/workloadgroup/WorkloadGroupMgr.java
Labels: approved, reviewed, workload-group, dev/2.1.3-merged

#34434 [Fix](Nereids) fix leading hint with update of alias name
  fe/fe-core/src/main/java/org/apache/doris/nereids/hint/LeadingHint.java
  regression-test/data/nereids_hint_tpch_p0/shape/q15.out
  regression-test/suites/nereids_hint_tpch_p0/shape/q15.groovy
  regression-test/suites/nereids_p0/hint/fix_leading.groovy
Labels: approved, reviewed

#34562 [fix](compaction) fix time series compaction merge empty rowsets priority
  be/src/cloud/cloud_cumulative_compaction_policy.cpp
  be/src/olap/cumulative_compaction_time_series_policy.cpp
  be/test/olap/cumulative_compaction_time_series_policy_test.cpp
Labels: approved, reviewed

#34471 [fix](round) Fix incorrect decimal scale inference in round functions
  be/src/vec/functions/round.h
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/ComputePrecisionForRound.java
  regression-test/data/query_p0/sql_functions/math_functions/test_round.out
  regression-test/suites/query_p0/sql_functions/math_functions/test_round.groovy
Labels: approved, reviewed
