Repository apache/doris, pull requests merged in 2024-09, with the labels that each got.

#40217 [fix](regression) fix regression failure of window_funnel caused by duplicated table name
  regression-test/data/nereids_p0/aggregate/window_funnel.out
  regression-test/data/nereids_p0/sql_functions/window_functions/window_funnel.out
  regression-test/data/query_p0/aggregate/window_funnel.out
  regression-test/suites/nereids_p0/aggregate/window_funnel.groovy
  regression-test/suites/nereids_p0/sql_functions/window_functions/window_funnel.sql
  regression-test/suites/query_p0/aggregate/window_funnel.groovy
Labels: approved, reviewed

#40111 [fix](ES Catalog)Do not push down limit to ES when predicates can not be processed by ES.
  be/src/pipeline/exec/es_scan_operator.cpp
  regression-test/data/external_table_p0/es/test_es_query.out
  regression-test/suites/external_table_p0/es/test_es_query.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x, doing

#40002 [fix](arrow-flight-sql) Fix return result from FE Arrow Flight server error `0.0.0.0:xxx, connection refused`
  fe/fe-core/src/main/java/org/apache/doris/service/arrowflight/DorisFlightSqlService.java
Labels: approved, reviewed, dev/2.1.x

#39792 [fix](cloud) Fix migrate tablets between backends back and forth
  be/src/cloud/cloud_backend_service.cpp
  fe/fe-core/src/main/java/org/apache/doris/cloud/catalog/CloudTabletRebalancer.java
  regression-test/suites/cloud_p0/multi_cluster/test_warmup_rebalance.groovy
Labels: approved, reviewed, usercase, dev/3.0.x

#38243 [feature](cloud) Add lazy commit mechanism for `commit_txn`
  be/src/cloud/cloud_meta_mgr.cpp
  be/src/cloud/config.cpp
  be/src/cloud/config.h
  cloud/src/common/config.h
  cloud/src/meta-service/CMakeLists.txt
  cloud/src/meta-service/meta_service.cpp
  cloud/src/meta-service/meta_service.h
  cloud/src/meta-service/meta_service_txn.cpp
  cloud/src/meta-service/txn_lazy_committer.cpp
  cloud/src/meta-service/txn_lazy_committer.h
  cloud/src/recycler/recycler.cpp
  cloud/src/recycler/recycler.h
  cloud/src/recycler/recycler_service.cpp
  cloud/src/recycler/recycler_service.h
  cloud/test/CMakeLists.txt
  cloud/test/meta_service_test.cpp
  cloud/test/recycler_test.cpp
  cloud/test/txn_lazy_commit_test.cpp
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/alter/CloudRollupJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/alter/CloudSchemaChangeJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/datasource/CloudInternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/transaction/CloudGlobalTransactionMgr.java
  gensrc/proto/cloud.proto
  regression-test/data/large_txn_load_p1/test_insert_with_many_buckets.out
  regression-test/data/large_txn_load_p1/test_insert_with_many_partitions.out
  regression-test/data/large_txn_load_p1/test_insert_with_many_partitions_and_buckets.out
  regression-test/suites/large_txn_load_p1/test_insert_with_many_buckets.groovy
  regression-test/suites/large_txn_load_p1/test_insert_with_many_partitions.groovy
  regression-test/suites/large_txn_load_p1/test_insert_with_many_partitions_and_buckets.groovy
Labels: kind/feature, approved, reviewed, meta-change, dev/3.0.x, doing

#40105 [fix](move-memtable) do not execute close if create rowset failed when loading MOW table
  be/src/runtime/load_stream.cpp
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x

#39961 [chore](cancel) Print query id to client when query_ctx not found.
  be/src/runtime/fragment_mgr.cpp
Labels: approved, reviewed, dev/2.1.x

#40186 [fix](ut) Fix TestParseMemSpec UT
  be/src/util/parse_util.cpp
  be/test/util/parse_util_test.cpp
Labels: approved, reviewed, dev/2.1.x

#40170 [branch-2.0-fix](partial update) `enable_unique_key_partial_update` should not affect tables which are not merge-on-write unique tables
  fe/fe-core/src/main/java/org/apache/doris/analysis/NativeInsertStmt.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/PhysicalPlanTranslator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/BindSink.java
  regression-test/data/unique_with_mow_p0/partial_update/partial_update_columns_check1.csv
  regression-test/data/unique_with_mow_p0/partial_update/test_partial_update_columns_check.out
  regression-test/data/unique_with_mow_p0/partial_update/test_partial_update_native_insert_stmt.out
  regression-test/suites/unique_with_mow_p0/partial_update/test_partial_update_columns_check.groovy
  regression-test/suites/unique_with_mow_p0/partial_update/test_partial_update_native_insert_stmt.groovy
Labels: area/planner, kind/test, approved, reviewed, area/nereids

#40097 [fix](regression) fix unstable insert_p2/txn_insert_with_schema_change and test_group_commit_interval_ms_property
  regression-test/suites/insert_p0/test_group_commit_interval_ms_property.groovy
  regression-test/suites/insert_p2/txn_insert_with_schema_change.groovy
Labels: approved, reviewed

#40197 [Fix](delete) Fix error when creating a non-MOW table while the default value of `enable_mow_light_delete` is true
  fe/fe-core/src/main/java/org/apache/doris/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
Labels: approved, reviewed

#39222 [feat](nereids) adjust stats derive by delta row
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/FilterEstimation.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/StatsCalculator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/types/coercion/CharacterType.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/ColumnStatisticBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/Statistics.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsBuilder.java
  regression-test/suites/nereids_p0/delta_row/delta_row.groovy
Labels: approved, reviewed, dev/2.1.x, doing, dev/2.0.15-merged

#40091 [Refactor](SchemaCache) remove redundant Schema cache
  be/src/olap/rowset/beta_rowset_reader.cpp
  be/src/olap/schema_cache.cpp
  be/src/olap/schema_cache.h
  be/src/vec/exec/scan/new_olap_scanner.cpp
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x

#39521 [chore](conf) Specify UTF8 as the default charset.
  conf/be.conf
  conf/fe.conf
Labels: approved, reviewed, kind/behavior-changed, dev/2.0.x, dev/2.1.x, dev/3.0.x

#40234 [test](inverted index) move show data case from p1 to p2
  regression-test/suites/inverted_index_p2/test_show_data.groovy
Labels: approved, reviewed

#40201 [Bug](function) fix encryption_function return wrong result at const column
  be/src/vec/functions/function_encryption.cpp
  regression-test/data/query_p0/sql_functions/encryption_digest/test_encryption_function.out
  regression-test/suites/query_p0/sql_functions/encryption_digest/test_encryption_function.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#40199 [fix](nereids)update session var for broadcast penalty
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  regression-test/data/nereids_ssb_shape_sf100_p0/shape/flat.out
  regression-test/data/nereids_ssb_shape_sf100_p0/shape/q2.2.out
  regression-test/data/nereids_ssb_shape_sf100_p0/shape/q2.3.out
  regression-test/data/nereids_ssb_shape_sf100_p0/shape/q3.3.out
  regression-test/data/nereids_ssb_shape_sf100_p0/shape/q3.4.out
  regression-test/data/nereids_ssb_shape_sf100_p0/shape/q4.3.out
Labels: reviewed

#40203 [opt](Nereids) add job, analyze, load and cancel statements syntax
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/analysis/AlterJobStatusStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/AnalyzeDBStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/AnalyzeTblStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CancelAlterSystemStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CancelAlterTableStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CancelBackupStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CancelCloudWarmUpStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CancelExportStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CancelJobTaskStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CancelLoadStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CleanLabelStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CleanProfileStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CleanQueryStatsStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateJobStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateRoutineLoadStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ImportColumnsStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ImportDeleteOnStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ImportSequenceStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ImportWhereStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/KillAnalysisJobStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/LoadStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/PauseRoutineLoadStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/PauseSyncJobStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/RefreshCatalogStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/RefreshDbStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/RefreshLdapStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/RefreshTableStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ResumeRoutineLoadStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ResumeSyncJobStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowCreateLoadStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowCreateRoutineLoadStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowRoutineLoadStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowRoutineLoadTaskStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/StopRoutineLoadStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/StopSyncJobStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SyncStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/UnifiedLoadStmt.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/LoadCommand.java
Labels: approved, reviewed

#40232 [Chore](inverted index) remove useless code in scan operator for normalize compound and match predicate
  be/src/pipeline/exec/scan_operator.cpp
  be/src/pipeline/exec/scan_operator.h
Labels: approved, reviewed

#40245 [debug](auto-partition) debug auto&dynamic partition creation
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
Labels: approved, reviewed

#40241 [fix](topn) Fix wrong rows returned by TOPN sorter
  be/src/vec/common/sort/sorter.cpp
  regression-test/data/query_p0/operator/test_sort_operator.out
  regression-test/suites/query_p0/operator/test_sort_operator.groovy
Labels: approved, reviewed, dev/2.1.6-merged

#40100 [fix](nereids) fix union all instance number
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  regression-test/suites/query_p0/union/test_union_instance.groovy
Labels: kind/test

#40251 [ut](jsonb) fix expected output for cast json type
  be/test/vec/function/function_jsonb_test.cpp
Labels: approved, reviewed

#40098 [fix] (regression test) fix error test
  regression-test/suites/compaction/test_single_compaction_with_variant_inverted_index.groovy
Labels: approved, reviewed

#40000 [Improve](Legacy planner)forbidden mvrewrite when there is no mv index in legacy planner
  fe/fe-core/src/main/java/org/apache/doris/analysis/BinaryPredicate.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SlotRef.java
Labels: area/planner, approved, reviewed

#40279 [fix](Nereids) datetimev2 literal equals should compare microsecond (#40121)
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/DateTimeV2Literal.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/expressions/literal/DateTimeLiteralTest.java
Labels: area/nereids

#40277 [opt](Nereids) forbid one step topn with distribute as child (#40066)
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/ChildrenPropertiesRegulator.java
Labels: area/nereids

#40252 [improve](statistics)Clean expired TableStatsMeta. (#39779)
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowTableStatsStmt.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisManager.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsCleaner.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/TableStatsMeta.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/AnalysisManagerTest.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/StatisticsAutoCollectorTest.java
  regression-test/suites/external_table_p0/hive/test_drop_expired_table_stats.groovy
Labels: area/planner, kind/test

#40210 [feature](metacache) add system table catalog_meta_cache_statistics #40155
  be/src/exec/schema_scanner.cpp
  be/src/exec/schema_scanner/schema_catalog_meta_cache_stats_scanner.cpp
  be/src/exec/schema_scanner/schema_catalog_meta_cache_stats_scanner.h
  be/src/vec/exec/scan/vmeta_scanner.h
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SchemaTableType.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/SchemaTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalMetaCacheMgr.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HiveMetaStoreCache.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hudi/source/HudiCachedPartitionProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/IcebergMetadataCache.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/MetadataGenerator.java
  gensrc/thrift/Descriptors.thrift
  gensrc/thrift/FrontendService.thrift
  gensrc/thrift/PlanNodes.thrift
  gensrc/thrift/Types.thrift
  regression-test/suites/external_table_p0/hive/test_external_catalog_hive.groovy
  regression-test/suites/external_table_p0/iceberg/test_iceberg_table_stats.groovy
Labels: meta-change

#40261 [improvement](jdbc catalog)Optimize JDBC Catalog refresh to reduce frequent client creation.
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/JdbcExternalCatalog.java
Labels: dev/2.0.x

#40254 [fix](index compaction)Fix core when having multiple dest segments
  be/src/olap/compaction.cpp
  regression-test/suites/inverted_index_p0/index_compaction/test_index_compaction_dup_keys.groovy
  regression-test/suites/inverted_index_p0/index_compaction/test_index_compaction_null.groovy
  regression-test/suites/inverted_index_p0/index_compaction/test_index_compaction_unique_keys.groovy
  regression-test/suites/inverted_index_p0/index_compaction/test_index_compaction_with_multi_index_segments.groovy
Labels: approved, reviewed, dev/3.0.x

#40281 [Fix](planner)legacy planner repeat group by has grouping report error
  fe/fe-core/src/main/java/org/apache/doris/analysis/GroupByClause.java
  regression-test/suites/nereids_rules_p0/grouping_sets/valid_grouping.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x

#40287 [fix](ut) fix SegmentTest and SegmentMoWTest asan core
  be/test/olap/segcompaction_mow_test.cpp
  be/test/olap/segcompaction_test.cpp
Labels: approved, reviewed

#40237 [fix](regression) speed up some case
  regression-test/suites/insert_p0/group_commit/test_group_commit_replay_wal.groovy
  regression-test/suites/insert_p0/transaction/txn_insert_inject_case.groovy
  regression-test/suites/insert_p0/transaction/txn_insert_with_drop.groovy
Labels: approved, reviewed

#40258 [Chore](inverted index) remove useless code of compound filters for inverted index
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/exec/olap_common.h
  be/src/olap/iterators.h
  be/src/olap/rowset/beta_rowset_reader.cpp
  be/src/olap/rowset/rowset_reader_context.h
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/olap/tablet_reader.cpp
  be/src/olap/tablet_reader.h
  be/src/pipeline/exec/olap_scan_operator.cpp
  be/src/pipeline/exec/olap_scan_operator.h
  be/src/pipeline/exec/scan_operator.h
  be/src/vec/exec/scan/new_olap_scanner.cpp
  be/src/vec/exec/scan/new_olap_scanner.h
Labels: approved, reviewed

#40120 [Enhancement](Group commit) Remove the redundant `iscloud` parameter
  fe/fe-core/src/main/java/org/apache/doris/cloud/planner/CloudGroupCommitPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/LoadAction.java
  fe/fe-core/src/main/java/org/apache/doris/load/GroupCommitManager.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/OlapGroupCommitInsertExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/planner/GroupCommitPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/qe/MasterOpExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  gensrc/thrift/FrontendService.thrift
Labels: approved, reviewed

#40109 [Fix](regression-test) Fix `test_group_commit_stream_load_with_nonexist_db_and_table` regression test case
  regression-test/suites/load_p0/stream_load/test_group_commit_stream_load_with_nonexist_db_and_table.groovy
Labels: approved, reviewed

#40266 [fix](ES Catalog)Do not push down limit to ES when predicates can not be processed by ES. (#40111)
  be/src/vec/exec/scan/new_es_scan_node.cpp
  regression-test/data/external_table_p0/es/test_es_query.out
  regression-test/suites/external_table_p0/es/test_es_query.groovy
Labels: kind/test

#40169 [enhance](mtmv)Optimize the speed of obtaining the last update time of Hive
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HMSExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HiveMetaStoreCache.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#40016 [fix](memory) When Load ends, check memory tracker value returns is equal to 0
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/runtime/memory/mem_tracker_limiter.cpp
  be/src/runtime/memory/mem_tracker_limiter.h
Labels: approved, reviewed

#40155 [feature](metacache) add system table catalog_meta_cache_statistics
  be/src/exec/schema_scanner.cpp
  be/src/exec/schema_scanner/schema_catalog_meta_cache_stats_scanner.cpp
  be/src/exec/schema_scanner/schema_catalog_meta_cache_stats_scanner.h
  be/src/vec/exec/scan/vmeta_scanner.h
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SchemaTableType.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/SchemaTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalMetaCacheMgr.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HiveMetaStoreCache.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hudi/source/HudiCachedPartitionProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/IcebergMetadataCache.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/MetadataGenerator.java
  gensrc/thrift/Descriptors.thrift
  gensrc/thrift/FrontendService.thrift
  gensrc/thrift/PlanNodes.thrift
  gensrc/thrift/Types.thrift
  regression-test/data/external_table_p0/jdbc/test_mariadb_jdbc_catalog.out
  regression-test/data/external_table_p0/jdbc/test_mysql_jdbc_catalog.out
  regression-test/data/external_table_p0/jdbc/test_mysql_jdbc_catalog_nereids.out
  regression-test/data/external_table_p0/jdbc/test_mysql_jdbc_driver5_catalog.out
  regression-test/suites/external_table_p0/hive/test_external_catalog_hive.groovy
  regression-test/suites/external_table_p0/iceberg/test_iceberg_table_stats.groovy
  regression-test/suites/external_table_p0/jdbc/test_mariadb_jdbc_catalog.groovy
  regression-test/suites/external_table_p0/jdbc/test_mysql_jdbc_catalog.groovy
  regression-test/suites/external_table_p0/jdbc/test_mysql_jdbc_catalog_nereids.groovy
  regression-test/suites/external_table_p0/jdbc/test_mysql_jdbc_driver5_catalog.groovy
Labels: approved, reviewed, dev/3.0.x, dev/2.1.6-merged

#40289 [fix](execution) fix wrong check when blocking result sink
  be/src/runtime/buffer_control_block.cpp
Labels: approved, reviewed

#40124 [fix](testcase) fix unstable case
  regression-test/suites/insert_p0/insert_group_commit_into.groovy
Labels: approved, reviewed

#39532 [feature](statistics)Support enable/disable auto analyze for table.
  fe/fe-core/src/main/java/org/apache/doris/alter/Alter.java
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/AlterTableStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ModifyTablePropertiesClause.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowTableStatsStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Table.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/TableIf.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/TableProperty.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/alter/CloudSchemaChangeHandler.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/persist/ModifyTablePropertyOperationLog.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/util/StatisticsUtil.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/util/StatisticsUtilTest.java
  regression-test/suites/external_table_p0/hive/test_hive_statistics_p0.groovy
  regression-test/suites/statistics/test_auto_analyze_black_white_list.groovy
Labels: approved, reviewed

#40116 [Bug](sink) update error status on BufferControlBlock::close
  be/src/runtime/buffer_control_block.cpp
Labels: approved, reviewed, dev/3.0.x

#40215 [fix](recycler) Implement missing delete_prefix() of hdfs accessor
  be/src/cloud/cloud_meta_mgr.cpp
  be/src/cloud/cloud_stream_load_executor.cpp
  be/src/cloud/injection_point_action.cpp
  cloud/src/common/config.h
  cloud/src/meta-service/meta_service_txn.cpp
  cloud/src/recycler/hdfs_accessor.cpp
  cloud/src/recycler/recycler.cpp
Labels: reviewed, p0_c, dev/3.0.x

#40313 [test](inverted index) fix case for index_compaction
  regression-test/suites/inverted_index_p0/index_compaction/test_index_compaction_null.groovy
Labels: reviewed

#40317 [ut](data type) fix get_common_type_test
  be/src/vec/data_types/get_least_supertype.cpp
  be/test/vec/core/get_common_type_test.cpp
Labels: approved, reviewed, dev/3.0.x

#40297 [chore](errmsg) Daemon thread interruption should be info log
  fe/fe-core/src/main/java/org/apache/doris/common/util/Daemon.java
Labels: approved, reviewed

#40307 [Fix](testcase) Split auto and dynamic partition into individual case
  regression-test/data/partition_p0/auto_partition/test_auto_dynamic.out
  regression-test/data/partition_p0/auto_partition/test_auto_partition_behavior.out
  regression-test/suites/partition_p0/auto_partition/test_auto_dynamic.groovy
  regression-test/suites/partition_p0/auto_partition/test_auto_partition_behavior.groovy
Labels: approved, reviewed

#40324 [Fix](inverted index) fix profile metrics for inverted index after refactor
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
Labels: approved, reviewed

#40167 [Feat](Nereids) add use mv hint
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/hint/UseMvHint.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/pre/PullUpSubqueryAliasToCTE.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/SelectHintUseMv.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/EliminateLogicalSelectHint.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/mv/AbstractSelectMaterializedIndexRule.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalSelectHint.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/jobs/joinorder/joinhint/DistributeHintTest.java
  regression-test/suites/nereids_p0/hint/test_use_mv.groovy
Labels: approved, reviewed

#40076 [chore](recycler) Change tablet_rowset_stale_sweep_time_sec=600 to reduce possibility failed to find rowset
  be/src/common/config.cpp
Labels: approved, reviewed, dev/3.0.x

#40218 [chore](cloud) Improve cloud start stop script: wait for quit synchronously
  cloud/script/start.sh
  cloud/script/stop.sh
Labels: approved, reviewed, dev/3.0.x

#40160 [chore] Reduce range of nextId when calling advanceNextId()
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
Labels: approved, reviewed, dev/3.0.x

#40267 [fix](unary function) Fix wrong result of asin, acos and sqrt when processing invalid input
  be/src/vec/functions/function_math_unary_alway_nullable.h
  be/src/vec/functions/math.cpp
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Acos.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Asin.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Dsqrt.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Sqrt.java
  regression-test/data/query_p0/sql_functions/math_functions/test_math_unary_always_nullable.out
  regression-test/suites/query_p0/sql_functions/math_functions/test_math_unary_always_nullable.groovy
Labels: approved, reviewed, dev/2.1.x

#39927 [opt](scanner) Control the degree of parallelism of scanner when only limit involved
  be/src/pipeline/exec/scan_operator.cpp
  fe/fe-core/src/main/java/org/apache/doris/planner/ScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  gensrc/thrift/PaloInternalService.thrift
  regression-test/suites/query_profile/adaptive_pipeline_task_serial_read_on_limit.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#40304 [fix](memory) Fix `sum_of_all_trackers` duplicated contain reserved memory
  be/src/runtime/memory/mem_tracker.h
  be/src/runtime/memory/mem_tracker_limiter.cpp
Labels: approved, reviewed

#40303 [fix](OrcWriter) fix be core when upgrading BE without upgrading FE
  be/src/vec/sink/vresult_sink.h
  be/src/vec/sink/writer/vfile_result_writer.cpp
  fe/fe-core/src/main/java/org/apache/doris/analysis/OutFileClause.java
  gensrc/thrift/DataSinks.thrift
Labels: meta-change

#40338 [Fix](inverted index) fix comparison for string after refactor compound
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/olap/rowset/segment_v2/segment_iterator.h
  be/src/vec/functions/functions_comparison.h
Labels: approved, reviewed

#40295 [Fix](Variant) sparse columns should not be added in init segment iterator
  be/src/olap/rowset/segment_v2/segment.cpp
  regression-test/suites/variant_p0/load.groovy
Labels: approved, reviewed, p0_c, dev/2.1.x, dev/3.0.x

#40343 [fix](ga) fix scope label and add samples exclusion to shell checks
  .github/workflows/code-checks.yml
  .github/workflows/scope-label.yml
Labels: approved, reviewed

#40107 [opt](function)Some geo functions incorrectly used get.
  be/src/vec/functions/functions_geo.cpp
Labels: approved, reviewed

#39252 [Feat](nereids) add max/min filter push down rewrite rule
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleSet.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/MaxMinFilterPushDown.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/MaxMinFilterPushDownTest.java
  regression-test/data/nereids_rules_p0/eager_aggregate/push_down_max_through_join.out
  regression-test/data/nereids_rules_p0/max_min_filter_push_down/max_min_filter_push_down.out
  regression-test/suites/nereids_rules_p0/max_min_filter_push_down/max_min_filter_push_down.groovy
Labels: approved, reviewed, doing

#40306 [Fix](planner) legacy planner repeat group by has grouping report error (#40281)
  fe/fe-core/src/main/java/org/apache/doris/analysis/GroupByClause.java
  regression-test/suites/nereids_rules_p0/grouping_sets/valid_grouping.groovy
Labels: area/planner, kind/test

#40285 [Fix](function) Refine crypto functions signature to fix wrong result
  fe/fe-core/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinScalarFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/AesDecrypt.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/AesDecryptV2.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/AesEncrypt.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/AesEncryptV2.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Sm4Decrypt.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Sm4DecryptV2.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Sm4Encrypt.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Sm4EncryptV2.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/ScalarFunctionVisitor.java
  regression-test/data/nereids_p0/sql_functions/encryption_digest/test_encryption_function.out
  regression-test/data/query_p0/sql_functions/encryption_digest/test_encryption_function.out
  regression-test/suites/nereids_function_p0/scalar_function/S.groovy
  regression-test/suites/nereids_p0/sql_functions/encryption_digest/test_encryption_function.groovy
  regression-test/suites/query_p0/sql_functions/encryption_digest/test_encryption_function.groovy
Labels: approved, reviewed, kind/behavior-changed, dev/2.1.x, dev/3.0.x

#39936 [fix](nereids) fix bug for A>n, where A.max is infinity
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/FilterEstimation.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticRange.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/stats/FilterEstimationTest.java
  regression-test/data/nereids_tpcds_shape_sf1000_p0/shape/query4.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/noStatsRfPrune/query11.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/noStatsRfPrune/query4.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/no_stats_shape/query11.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/no_stats_shape/query4.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/rf_prune/query4.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query4.out
  regression-test/data/new_shapes_p0/tpcds_sf100/noStatsRfPrune/query11.out
  regression-test/data/new_shapes_p0/tpcds_sf100/noStatsRfPrune/query4.out
  regression-test/data/new_shapes_p0/tpcds_sf100/no_stats_shape/query11.out
  regression-test/data/new_shapes_p0/tpcds_sf100/no_stats_shape/query4.out
  regression-test/data/new_shapes_p0/tpcds_sf100/rf_prune/query4.out
  regression-test/data/new_shapes_p0/tpcds_sf100/shape/query4.out
  regression-test/data/new_shapes_p0/tpcds_sf1000/shape/query4.out
Labels: approved, reviewed, dev/2.1.x

#40355 [test](inverted index) refine test_ignore_above case, add compound query sql
  regression-test/data/inverted_index_p0/test_ignore_above_in_index.out
  regression-test/suites/inverted_index_p0/test_ignore_above_in_index.groovy
Labels: approved, reviewed

#40188 [test](mtmv) SSB mv rewrite test use little data set for test performance
  regression-test/data/nereids_rules_p0/mv/ssb/mv_ssb_test.out
  regression-test/suites/nereids_rules_p0/mv/ssb/mv_ssb_test.groovy
Labels: approved, reviewed, dev/2.1.x

#40067 [enhencement](sample) add delta and kudu samples
  samples/datalake/deltalake_and_kudu/README.md
  samples/datalake/deltalake_and_kudu/data/customer/_delta_log/00000000000000000000.json
  samples/datalake/deltalake_and_kudu/data/customer/part-00000-44ff362c-110d-44ca-aed8-93ed65c19492-c000.snappy.parquet
  samples/datalake/deltalake_and_kudu/data/customer/part-00001-749ded2d-a84b-4e2c-9e6f-5ac6a59ee91d-c000.snappy.parquet
  samples/datalake/deltalake_and_kudu/data/customer/part-00002-137a1b68-bafd-46a7-b231-400a174b520c-c000.snappy.parquet
  samples/datalake/deltalake_and_kudu/data/customer/part-00003-75203d54-ef95-4fbe-95c9-2012fd9dbaed-c000.snappy.parquet
  samples/datalake/deltalake_and_kudu/login-doris.sh
  samples/datalake/deltalake_and_kudu/login-spark.sh
  samples/datalake/deltalake_and_kudu/scripts/create-delta-table.sh
  samples/datalake/deltalake_and_kudu/scripts/doris-sql.sql
  samples/datalake/deltalake_and_kudu/scripts/spark-delta.sh
  samples/datalake/deltalake_and_kudu/scripts/spark-delta.sql
  samples/datalake/deltalake_and_kudu/scripts/start_doris.sh
  samples/datalake/deltalake_and_kudu/start-trinoconnector-compose.sh
  samples/datalake/deltalake_and_kudu/stop-trinoconnector-compose.sh
  samples/datalake/deltalake_and_kudu/trinoconnector-compose.env
  samples/datalake/deltalake_and_kudu/trinoconnector-compose.yml
Labels: approved, reviewed, dev/3.0.x

#39912 [opt](in expr) Optimize the IN expression by skipping constant columns.
  be/src/vec/exprs/vexpr.h
  be/src/vec/exprs/vin_predicate.cpp
  be/src/vec/exprs/vin_predicate.h
  be/src/vec/functions/function_collection_in.h
Labels: approved, reviewed

#40242 [fix] (compaction) fix compaction score in time series policy
  be/src/olap/cumulative_compaction_time_series_policy.cpp
  be/test/olap/cumulative_compaction_time_series_policy_test.cpp
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x

#40290 [fix](decimal) throw overflow exception if result is NaN of Infinit when converting from decimal to float
  be/src/vec/data_types/data_type_decimal.h
  regression-test/data/datatype_p0/decimalv3/test_decimal256_cast.out
  regression-test/suites/datatype_p0/decimalv3/test_decimal256_cast.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#40381 [fix](ci) add retry to avoid compile fail
  cloud/CMakeLists.txt
Labels: approved, reviewed

#40331 [chore](Nereids) do not fallback if parse failed for all case
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
  regression-test/suites/datatype_p0/bitmap/test_bitmap_int.groovy
  regression-test/suites/datatype_p0/nested_types/query/test_nestedtypes_insert_into_select.groovy
  regression-test/suites/demo_p0/test_action.groovy
  regression-test/suites/external_table_p0/hive/ddl/test_hive_ddl.groovy
  regression-test/suites/nereids_p0/insert_into_table/update_on_current_timestamp.groovy
  regression-test/suites/query_p0/grouping_sets/test_grouping_sets.groovy
  regression-test/suites/query_p0/join/test_join2.groovy
Labels: approved, reviewed

#40282 [fix](OrcWriter) fix be core when upgrading BE without upgrading FE
  be/src/pipeline/exec/result_sink_operator.h
  be/src/vec/sink/writer/vfile_result_writer.cpp
  fe/fe-core/src/main/java/org/apache/doris/analysis/OutFileClause.java
  gensrc/thrift/DataSinks.thrift
Labels: approved, reviewed, dev/3.0.x, dev/2.1.6-merged

#40322 [Opt](delete) Skip newly inserted rows check in non-strict mode partial update if the row's delete sign is marked
  be/src/olap/rowset/segment_v2/segment_writer.cpp
  be/src/olap/rowset/segment_v2/vertical_segment_writer.cpp
  regression-test/data/unique_with_mow_p0/partial_update/partial_update_delete.csv
  regression-test/data/unique_with_mow_p0/partial_update/test_partial_update_delete.out
  regression-test/suites/unique_with_mow_p0/partial_update/test_partial_update_delete.groovy
Labels: approved, reviewed, usercase

#40300 [Fix](ShortCircuit) consider delete sign flag when hits row
  be/src/service/point_query_executor.cpp
  be/src/service/point_query_executor.h
  regression-test/data/point_query_p0/test_point_query.out
  regression-test/suites/point_query_p0/test_point_query.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x

#40223 [chore](cloud) Support starting both meta-service and recycler within single process
  cloud/script/start.sh
  cloud/src/common/config.h
  cloud/src/main.cpp
  cloud/src/recycler/checker.cpp
  cloud/src/recycler/recycler.cpp
  cloud/src/recycler/recycler_service.cpp
  cloud/test/recycler_test.cpp
Labels: approved, reviewed, dev/3.0.x

#40260 [fix](cloud) Fix missing privilege to storage vault after restarting FE
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/Role.java
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
  regression-test/suites/vaults/privilege_restart.groovy
Labels: reviewed, dev/3.0.x

#40183 [fix](decompressor) consider the large_block_len is 0
  be/src/exec/decompressor.cpp
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#40392 [chore](ci) tmp remove required of Clang Formatter
  .asf.yaml
Labels: approved, reviewed

#40393 [fix](ga) try fix clang format action
  .github/workflows/clang-format.yml
Labels: approved, reviewed

#40375 Revert "[fix](compaction) fix the longest continuous rowsets cannot be selected when missing rowsets (#38728) (#39262)"
  be/src/olap/compaction.cpp
  be/src/olap/cumulative_compaction.cpp
  be/test/olap/cumulative_compaction_test.cpp
Labels: approved, reviewed

#39923 [enhancement](show) Move storage policy info from show create table to show partitions
  fe/fe-core/src/main/java/org/apache/doris/catalog/ListPartitionInfo.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/RangePartitionInfo.java
  regression-test/suites/show_p0/test_show_create_table_with_storage_policy.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x

#40194 [fix](restore) update is_being_synced properties
  fe/fe-core/src/main/java/org/apache/doris/backup/RestoreJob.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x

#40360 [Bug](sink) take turns getting data from backends to avoid dead lock
  be/src/runtime/buffer_control_block.cpp
  be/src/runtime/buffer_control_block.h
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
Labels: approved, reviewed

#40244 [improvement](mtmv) Support to contain select constant clause when create async materialized view
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/CreateMTMVInfo.java
  regression-test/data/mtmv_p0/contain_one_row_relation/one_row_relation_when_create.out
  regression-test/suites/mtmv_p0/contain_one_row_relation/one_row_relation_when_create.groovy
Labels: approved, reviewed, dev/2.1.x

#39450 [Feat](nereids) support pull up predicate from set operator
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/Rewriter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleSet.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/EliminateEmptyRelation.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/InferPredicates.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PullUpPredicates.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PushProjectIntoUnion.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/ExpressionUtils.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/InferPredicatesTest.java
  regression-test/data/nereids_hint_tpcds_p0/shape/query8.out
  regression-test/data/nereids_rules_p0/filter_push_down/push_down_expression_in_hash_join.out
  regression-test/data/nereids_rules_p0/filter_push_down/push_filter_through.out
  regression-test/data/nereids_rules_p0/infer_predicate/infer_intersect_except.out
  regression-test/data/nereids_rules_p0/infer_predicate/pull_up_predicate_literal.out
  regression-test/data/nereids_rules_p0/infer_predicate/pull_up_predicate_set_op.out
  regression-test/data/nereids_rules_p0/infer_set_operator_distinct/infer_set_operator_distinct.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/bs_downgrade_shape/query8.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/shape/query8.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/noStatsRfPrune/query8.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/no_stats_shape/query8.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/rf_prune/query8.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query8.out
  regression-test/data/new_shapes_p0/tpcds_sf100/noStatsRfPrune/query8.out
  regression-test/data/new_shapes_p0/tpcds_sf100/no_stats_shape/query8.out
  regression-test/data/new_shapes_p0/tpcds_sf100/rf_prune/query8.out
  regression-test/data/new_shapes_p0/tpcds_sf100/shape/query8.out
  regression-test/data/new_shapes_p0/tpcds_sf1000/bs_downgrade_shape/query8.out
  regression-test/data/new_shapes_p0/tpcds_sf1000/shape/query8.out
  regression-test/regression-test/realData/insert_p0/txn_insert_values_with_schema_change.out
  regression-test/suites/nereids_rules_p0/adjust_nullable/set_operation.groovy
  regression-test/suites/nereids_rules_p0/infer_predicate/infer_intersect_except.groovy
  regression-test/suites/nereids_rules_p0/infer_predicate/pull_up_predicate_literal.groovy
  regression-test/suites/nereids_rules_p0/infer_predicate/pull_up_predicate_set_op.groovy
  regression-test/suites/nereids_rules_p0/infer_set_operator_distinct/infer_set_operator_distinct.groovy
Labels: approved, reviewed

#39962 [fix](memory) Fix conf `max_sys_mem_available_low_water_mark_bytes`
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/util/mem_info.cpp
Labels: approved, reviewed, dev/2.1.x

#39828 [improve](cast) support ipv4 cast to ipv6 type
  be/src/vec/functions/function_cast.h
  fe/fe-common/src/main/java/org/apache/doris/catalog/PrimitiveType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/TypeCoercionUtils.java
  regression-test/data/datatype_p0/ip/test_ip_implicit_cast.out
  regression-test/suites/datatype_p0/ip/test_ip_implicit_cast.groovy
Labels: approved, reviewed

#40384 [chore](thrift compatibility) Fix thrift id on master is not compatible with branch-2.1
  gensrc/thrift/PaloInternalService.thrift
Labels: approved, reviewed, dev/3.0.x

#40255 [chore](analysis) Simplify the condition of whether any partition is restoring
  fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java
Labels: approved, reviewed

#40387 [Enhancement](delete) Modify some delete cases to ajust `enable_mow_light_delete` config
  regression-test/suites/compaction/test_full_compaction.groovy
  regression-test/suites/compaction/test_full_compaction_by_table_id.groovy
  regression-test/suites/nereids_p0/delete/delete_mow_partial_update.groovy
  regression-test/suites/nereids_p0/explain/test_pushdown_explain.groovy
  regression-test/suites/unique_with_mow_p0/partial_update/test_new_partial_update_delete.groovy
  regression-test/suites/unique_with_mow_p0/partial_update/test_partial_update_after_delete.groovy
  regression-test/suites/unique_with_mow_p0/partial_update/test_partial_update_delete.groovy
Labels: approved, reviewed, dev/2.1.6-merged

#40286 [fix] (regression test) reduce testing time
  regression-test/data/load/insert/test_move_memtable_multi_segment_index.out
  regression-test/suites/load/insert/test_move_memtable_multi_segment_index.groovy
Labels: approved, reviewed

#39670 [feature-WIP](query cache) cache tablets aggregate result, FE part
  fe/fe-core/src/main/java/org/apache/doris/analysis/Expr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SlotRef.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionSet.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/PartitionKey.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/RangePartitionInfo.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/NereidsPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/Utils.java
  fe/fe-core/src/main/java/org/apache/doris/planner/AggregationNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PlanFragment.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PlanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/normalize/NormalizedPartitionPredicates.java
  fe/fe-core/src/main/java/org/apache/doris/planner/normalize/Normalizer.java
  fe/fe-core/src/main/java/org/apache/doris/planner/normalize/PartitionRangePredicateNormalizer.java
  fe/fe-core/src/main/java/org/apache/doris/planner/normalize/PredicateToRange.java
  fe/fe-core/src/main/java/org/apache/doris/planner/normalize/QueryCacheNormalizer.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryCacheNormalizerTest.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/TestWithFeService.java
  gensrc/thrift/Normalization.thrift
  gensrc/thrift/Planner.thrift
  gensrc/thrift/QueryCache.thrift
Labels: approved, reviewed

#38110 [feat](job)Internal job cancellation immediately and the strong association with the STARTS parameter (#36805)
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateJobStmt.java
  fe/fe-core/src/main/java/org/apache/doris/job/base/JobExecutionConfiguration.java
  fe/fe-core/src/main/java/org/apache/doris/job/base/TimerDefinition.java
  fe/fe-core/src/main/java/org/apache/doris/job/scheduler/JobScheduler.java
  fe/fe-core/src/test/java/org/apache/doris/job/base/JobExecutionConfigurationTest.java
Labels: reviewed

#40004 [feature](aes_encrypt) support GCM mode for aes_encrypt and aes_decrypt
  be/src/util/encryption_util.cpp
  be/src/util/encryption_util.h
  be/src/vec/functions/function_encryption.cpp
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/AesCryptoFunction.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/AesDecrypt.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/AesEncrypt.java
  gensrc/script/doris_builtins_functions.py
  regression-test/data/nereids_p0/sql_functions/encryption_digest/test_encryption_function.out
  regression-test/suites/nereids_p0/sql_functions/encryption_digest/test_encryption_function.groovy
Labels: approved, reviewed, dev/2.1.x

#40356 [fix](test) fix move memtable injection test may cause other case stuck
  be/src/olap/delta_writer_v2.cpp
  regression-test/pipeline/cloud_p0/conf/regression-conf-custom.groovy
  regression-test/pipeline/p0/conf/regression-conf.groovy
Labels: approved, reviewed

#40382 [Opt](delete) Skip newly inserted rows check in non-strict mode partial update if the row's delete sign is marked #40322
  be/src/olap/rowset/segment_v2/segment_writer.cpp
  regression-test/data/unique_with_mow_p0/partial_update/partial_update_delete.csv
  regression-test/data/unique_with_mow_p0/partial_update/test_partial_update_delete.out
  regression-test/suites/unique_with_mow_p0/partial_update/test_partial_update_delete.groovy
Labels: kind/test

#40296 [chore](error msg) More convenient error msg when function not found.
  be/src/vec/exprs/vectorized_fn_call.cpp
Labels: approved, reviewed, dev/2.1.x

#40432 [opt](Nereids) support search from override udfs with same arity
  fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionRegistry.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionSignature.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/udf/AliasUdf.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/udf/AliasUdfBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/udf/JavaUdafBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/udf/JavaUdfBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/udf/JavaUdtfBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/udf/UdfBuilder.java
Labels: approved, reviewed, dev/2.1.x

#40388 [enhance](variant) throw exception when field type is not supported in cast elimation
  be/src/olap/tablet_reader.cpp
  regression-test/suites/variant_p0/load.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#40380 [fix](memory) Fix ThreadMemTrackerMgr consumer tracker remove reserve memory
  be/src/runtime/exec_env.h
  be/src/runtime/exec_env_init.cpp
  be/src/runtime/memory/mem_tracker_limiter.cpp
  be/src/runtime/memory/thread_mem_tracker_mgr.cpp
  be/src/runtime/memory/thread_mem_tracker_mgr.h
  be/src/runtime/thread_context.h
  be/src/vec/common/allocator.cpp
  be/test/runtime/memory/thread_mem_tracker_mgr_test.cpp
Labels: approved, reviewed

#40330 [opt](cpu-profile) enable cpu profile in BE webui
  .licenserc.yaml
  LICENSE.txt
  be/src/http/action/pprof_actions.cpp
  be/src/http/default_path_handlers.cpp
  be/src/util/pprof_utils.cpp
  be/src/vec/exec/scan/vfile_scanner.cpp
  be/src/vec/exec/scan/vfile_scanner.h
  build.sh
  dist/LICENSE-dist.txt
  tools/FlameGraph/README
  tools/FlameGraph/flamegraph.pl
  tools/FlameGraph/stackcollapse-perf.pl
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#40439 [fix](memory) Reflect Allocator memory tracker
  be/src/olap/page_cache.cpp
  be/src/olap/page_cache.h
  be/src/runtime/thread_context.h
  be/src/util/byte_buffer.h
  be/src/vec/common/allocator.cpp
  be/src/vec/common/allocator.h
Labels: approved, reviewed

#40193 [Compatibility](agg-state) add be_exec_version check to avoid aggregation data format changed le…
  be/src/agent/be_exec_version_manager.cpp
  be/src/agent/be_exec_version_manager.h
  be/src/olap/memtable.cpp
  be/src/olap/rowset/segment_v2/column_reader.cpp
  be/src/olap/rowset/segment_v2/column_reader.h
  be/src/olap/rowset/segment_v2/segment.cpp
  be/src/olap/rowset/segment_v2/segment.h
  be/src/olap/schema_change.cpp
  be/src/olap/tablet_reader.h
  be/src/olap/tablet_schema.cpp
  be/src/olap/tablet_schema.h
  be/src/vec/aggregate_functions/aggregate_function_distinct.cpp
  be/src/vec/aggregate_functions/aggregate_function_foreach.cpp
  be/src/vec/aggregate_functions/aggregate_function_simple_factory.h
  be/src/vec/data_types/data_type_agg_state.h
  be/src/vec/olap/block_reader.cpp
  be/src/vec/olap/vertical_block_reader.cpp
  be/test/vec/aggregate_functions/agg_bitmap_test.cpp
  be/test/vec/aggregate_functions/agg_collect_test.cpp
  be/test/vec/aggregate_functions/agg_histogram_test.cpp
  be/test/vec/aggregate_functions/agg_min_max_by_test.cpp
  be/test/vec/aggregate_functions/agg_min_max_test.cpp
  be/test/vec/aggregate_functions/agg_replace_test.cpp
  be/test/vec/aggregate_functions/agg_test.cpp
  be/test/vec/aggregate_functions/vec_count_by_enum_test.cpp
  be/test/vec/aggregate_functions/vec_retention_test.cpp
  be/test/vec/aggregate_functions/vec_sequence_match_test.cpp
  be/test/vec/aggregate_functions/vec_window_funnel_test.cpp
Labels: approved, reviewed

#39840 [bugfix](hive/iceberg)align with Hive insert overwrite table functionality
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HMSTransaction.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/IcebergTransaction.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/HiveInsertCommandContext.java
  fe/fe-core/src/main/java/org/apache/doris/planner/HiveTableSink.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/iceberg/IcebergTransactionTest.java
  regression-test/data/external_table_p0/hive/write/test_hive_insert_overwrite_with_empty_table.out
  regression-test/data/external_table_p0/iceberg/write/test_iceberg_insert_overwrite_with_empty_table.out
  regression-test/suites/external_table_p0/hive/write/test_hive_insert_overwrite_with_empty_table.groovy
  regression-test/suites/external_table_p0/iceberg/write/test_iceberg_insert_overwrite_with_empty_table.groovy
Labels: approved, reviewed

#40422 [chore](persist) reduce truncate table operation log size
  fe/fe-core/src/main/java/org/apache/doris/persist/TruncateTableInfo.java
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x

#40308 [fix](regression-test) Sync after insert to get stable results
  regression-test/suites/alter_p0/test_alter_muti_modify_column.groovy
Labels: approved, reviewed

#40271 [enhancement](compaction) Abort compaction tasks when correspoding tablet states have been changed
  be/src/olap/olap_server.cpp
  be/src/olap/tablet.cpp
Labels: approved, reviewed

#40187 [fix](cloud-schema-change) Exclude merged dropped columns from projection columns
  be/src/cloud/cloud_schema_change_job.cpp
  regression-test/suites/schema_change_p0/test_merge_dropped_column.groovy
Labels: area/schema-change, approved, reviewed, dev/3.0.x

#38388 [feature](cloud) Support multi follower fe in cloud
  cloud/src/resource-manager/resource_manager.cpp
  docker/runtime/doris-compose/cluster.py
  docker/runtime/doris-compose/command.py
  docker/runtime/doris-compose/resource/init_fe.sh
  fe/fe-core/src/main/java/org/apache/doris/cloud/catalog/CloudClusterChecker.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/catalog/CloudEnv.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/catalog/CloudTabletRebalancer.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/system/CloudSystemInfoService.java
  gensrc/proto/cloud.proto
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/SuiteCluster.groovy
  regression-test/suites/cloud_p0/multi_cluster/test_multi_follower.groovy
Labels: approved, reviewed, meta-change, dev/3.0.x

#40325 [fix](pipelinex) fix fragment instance progress reports
  be/src/runtime/fragment_mgr.cpp
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  gensrc/thrift/FrontendService.thrift
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x

#39957 [improve](s3) s3 load provider should be case insensitive
  be/src/util/s3_util.cpp
  fe/fe-core/src/main/java/org/apache/doris/analysis/CopyStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/LoadStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/StageProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/constants/S3Properties.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/StageTest.java
  regression-test/framework/src/main/groovy/org/apache/doris/regression/Config.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
Labels: approved, reviewed

#40456 [chore] remove duplicate code in schema scanner
  be/src/exec/schema_scanner/schema_active_queries_scanner.cpp
  be/src/exec/schema_scanner/schema_routine_scanner.cpp
  be/src/exec/schema_scanner/schema_scanner_helper.cpp
  be/src/exec/schema_scanner/schema_scanner_helper.h
  be/src/runtime/runtime_query_statistics_mgr.cpp
  be/src/runtime/workload_group/workload_group.cpp
  be/src/runtime/workload_group/workload_group_manager.cpp
Labels: approved, reviewed

#40113 [feat](Authenticator) Pluginization of Authenticator
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/authenticate/AuthenticateType.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/authenticate/AuthenticatorFactory.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/authenticate/AuthenticatorManager.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/authenticate/DefaultAuthenticatorFactory.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/authenticate/ldap/LdapAuthenticator.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/authenticate/ldap/LdapAuthenticatorFactory.java
  fe/fe-core/src/main/resources/META-INF/services/org.apache.doris.mysql.authenticate.AuthenticatorFactory
Labels: approved, reviewed

#39593 [metrics](rpc) Add rpc latency metrics
  be/src/service/internal_service.cpp
  be/src/service/internal_service.h
  be/src/vec/runtime/vdata_stream_mgr.cpp
  be/src/vec/runtime/vdata_stream_mgr.h
  be/src/vec/runtime/vdata_stream_recvr.cpp
  be/src/vec/runtime/vdata_stream_recvr.h
Labels: approved, reviewed

#40425 [fix] (inverted index) fix error result in compound query
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  regression-test/data/inverted_index_p0/test_index_rqg_bug5.out
  regression-test/suites/inverted_index_p0/test_index_rqg_bug5.groovy
Labels: p0_w, dev/2.0.x

#40438 [Bug](compatibility) fix stddev_samp function coredump when upgrade
  be/src/vec/aggregate_functions/aggregate_function_stddev.h
Labels: approved, reviewed, dev/3.0.x

#40399 [chore](log) Do not print profile in be log if query comes from FE
  be/src/pipeline/pipeline_fragment_context.cpp
Labels: approved, reviewed, dev/3.0.x

#40347 [Enhancement](be-logger) Support custom date time format functionality in be log.
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/common/logconfig.cpp
Labels: approved, reviewed

#40423 [Chore](utils) remove some unused code
  be/src/olap/utils.cpp
  be/src/olap/utils.h
Labels: approved, reviewed

#40454 [Bug](map) fix wrong result on map_agg with streaming agg
  be/src/vec/aggregate_functions/aggregate_function_map.h
  regression-test/data/nereids_syntax_p0/mv/agg_mv_test.dat
  regression-test/data/nereids_syntax_p0/mv/aggregate/agg_sync_mv.out
  regression-test/suites/nereids_syntax_p0/mv/aggregate/agg_sync_mv.groovy
Labels: approved, reviewed, p0_w, dev/3.0.x

#40402 [enhance](mtmv)During cache generation, no longer hold the write lock for mtmv
  fe/fe-core/src/main/java/org/apache/doris/catalog/MTMV.java
Labels: approved, reviewed

#39991 [Fix]Fix cgroup v2 init
  be/src/agent/cgroup_cpu_ctl.cpp
  be/src/agent/cgroup_cpu_ctl.h
  be/src/runtime/workload_group/workload_group.cpp
Labels: approved, reviewed

#40126 [opt](nereids)stats derive for min()/max() agg function
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/ExpressionEstimation.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/stats/ExpressionEstimationTest.java
Labels: approved, reviewed

#40455 [Enhancement] add row count in show partition
  fe/fe-core/src/main/java/org/apache/doris/common/proc/PartitionsProcDir.java
Labels: approved, reviewed

#38610 [Fix](hdfs-fs)The cache expiration should explicitly release the held fs
  fe/fe-core/src/main/java/org/apache/doris/fs/remote/RemoteFSPhantomManager.java
  fe/fe-core/src/main/java/org/apache/doris/fs/remote/RemoteFileSystem.java
  fe/fe-core/src/main/java/org/apache/doris/fs/remote/RemoteFileSystemPhantomReference.java
  fe/fe-core/src/main/java/org/apache/doris/fs/remote/S3FileSystem.java
  fe/fe-core/src/main/java/org/apache/doris/fs/remote/dfs/DFSFileSystem.java
Labels: approved, reviewed, p0_b, dev/2.0.x, dev/2.1.x, dev/3.0.x, doing

#40407 [Fix](ShortCircuit) consider delete sign flag when hits row
  be/src/service/point_query_executor.cpp
  be/src/service/point_query_executor.h
  regression-test/data/point_query_p0/test_point_query.out
  regression-test/suites/point_query_p0/test_point_query.groovy
Labels: kind/test

#40465 [Chore](agg-state) modify be exec version comments and catch exception on memtable insert
  be/src/agent/be_exec_version_manager.cpp
  be/src/agent/be_exec_version_manager.h
  be/src/olap/memtable.cpp
Labels: approved, reviewed, dev/3.0.x

#40315 [fix](decompressor) impl ZstdDecompressor
  be/src/exec/decompressor.cpp
  be/src/exec/decompressor.h
  regression-test/data/external_table_p0/hive/write/test_hive_text_write_insert.out
  regression-test/suites/external_table_p0/hive/write/test_hive_text_write_insert.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#40449 [feature](Nereids) support query on ES table in internal catalog
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/PhysicalPlanTranslator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/BindRelation.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalEsScan.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalEsScan.java
  fe/fe-core/src/test/java/org/apache/doris/planner/StatisticDeriveTest.java
  regression-test/suites/correctness_p0/test_push_conjunct_external_table.groovy
Labels: approved, reviewed, dev/2.1.x

#40122 [fix](jdbc catalog) Fix type recognition error when using `query` tvf to query doris
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/client/JdbcMySQLClient.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/util/JdbcFieldSchema.java
  regression-test/data/external_table_p0/jdbc/test_doris_jdbc_catalog.out
  regression-test/suites/external_table_p0/jdbc/test_doris_jdbc_catalog.groovy
Labels: approved, reviewed, usercase, dev/2.1.x, dev/3.0.x

#40144 [opt](scanner profile) More counter for scanner
  be/src/pipeline/exec/scan_operator.cpp
  be/src/pipeline/exec/scan_operator.h
  be/src/vec/exec/scan/scanner_context.cpp
  be/src/vec/exec/scan/scanner_context.h
  be/src/vec/exec/scan/scanner_scheduler.cpp
  be/src/vec/exec/scan/vscanner.cpp
  regression-test/suites/query_profile/scanner_profile.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#40450 [fix](logstash) fix group_commit error in logstash
  extension/logstash/lib/logstash/outputs/doris.rb
  extension/logstash/logstash-output-doris.gemspec
Labels: approved, reviewed

#36355 [opt](plugin) improve filebeat doris output plugin
  extension/beats/doris/client.go
  extension/beats/doris/config.go
  extension/beats/doris/doris.go
  extension/beats/go.mod
  extension/beats/go.sum
  extension/logstash/lib/logstash/outputs/doris.rb
Labels: approved, reviewed, doing

#40371 [enhance](cloud) Add a policy when be abnormal, tablet delay switch be
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/catalog/CloudReplica.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/catalog/CloudTabletRebalancer.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/datasource/CloudInternalCatalog.java
  regression-test/suites/cloud_p0/multi_cluster/test_rebalance.groovy
Labels: approved, reviewed, dev/3.0.x

#40482 [fix](table-func) fix explode-func with old pipeline
  be/src/vec/exec/vtable_function_node.cpp
Labels: approved, reviewed

#40419 [ci](trigger) user 9208457 can skip buildall on branch-2.1
  .github/workflows/comment-to-trigger-teamcity.yml
Labels: approved, reviewed

#40470 [Chore](status) Disable stack trace printing for NotFound error status
  be/src/io/fs/s3_obj_storage_client.cpp
Labels: approved, reviewed

#40469 [fix] (inverted index) fix error result in compound query (#40425)
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  regression-test/data/inverted_index_p0/test_index_rqg_bug5.out
  regression-test/suites/inverted_index_p0/test_index_rqg_bug5.groovy
Labels: kind/test

#40457 [improvement](statistics)Return -1 to neredis if report olap table row count for new table is not done for all tablets.
  be/src/olap/tablet_manager.cpp
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowTableStatsStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/CloudTabletStatMgr.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/MaterializedIndex.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Replica.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/TabletStatMgr.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/StatsCalculator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisInfo.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisManager.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/BaseAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/OlapAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsRepository.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/TableStatsMeta.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java
  gensrc/thrift/BackendService.thrift
  regression-test/suites/statistics/analyze_stats.groovy
  regression-test/suites/statistics/test_analyze_mv.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x

#40504 [Fix](hdfs-fs)The cache expiration should explicitly release the held fs #38610
  fe/fe-core/src/main/java/org/apache/doris/fs/remote/RemoteFSPhantomManager.java
  fe/fe-core/src/main/java/org/apache/doris/fs/remote/RemoteFileSystem.java
  fe/fe-core/src/main/java/org/apache/doris/fs/remote/RemoteFileSystemPhantomReference.java
  fe/fe-core/src/main/java/org/apache/doris/fs/remote/S3FileSystem.java
  fe/fe-core/src/main/java/org/apache/doris/fs/remote/dfs/DFSFileSystem.java
Labels: approved, reviewed

#40503 [fix](scan) fix predicate contains cast that results in null, the pr…
  be/src/vec/exec/scan/vscan_node.cpp
  regression-test/data/correctness/test_scan_with_cast_null_value.out
  regression-test/suites/correctness/test_scan_with_cast_null_value.groovy
Labels: kind/test

#40499 [chore](routine load) make error msg clear if routine load name illegal (#40037)
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateRoutineLoadStmt.java
  fe/fe-core/src/main/java/org/apache/doris/common/FeNameFormat.java
Labels: area/planner

#40353 [feature](restore) support atomic restore
  be/src/olap/snapshot_manager.cpp
  be/src/olap/snapshot_manager.h
  be/src/olap/tablet_manager.cpp
  fe/fe-core/src/main/java/org/apache/doris/analysis/RestoreStmt.java
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupHandler.java
  fe/fe-core/src/main/java/org/apache/doris/backup/RestoreFileMapping.java
  fe/fe-core/src/main/java/org/apache/doris/backup/RestoreJob.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/org/apache/doris/task/SnapshotTask.java
  fe/fe-core/src/test/java/org/apache/doris/backup/RestoreFileMappingTest.java
  fe/fe-core/src/test/java/org/apache/doris/backup/RestoreJobTest.java
  gensrc/thrift/AgentService.thrift
  gensrc/thrift/FrontendService.thrift
  regression-test/data/backup_restore/test_backup_restore_atomic.out
  regression-test/suites/backup_restore/test_backup_restore_atomic.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x

#40414 [fix](cloud) MS limit max aborted txn num for the same txn label
  cloud/src/common/config.h
  cloud/src/meta-service/meta_service_txn.cpp
  cloud/test/meta_service_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadManager.java
  regression-test/data/load_p0/stream_load/test_stream_load_with_data_quality.csv
  regression-test/data/load_p0/stream_load/test_stream_load_with_data_quality2.csv
  regression-test/suites/load_p0/stream_load/test_steam_load_with_data_quality.groovy
Labels: approved, reviewed, dev/3.0.x

#40498 [improve](routine load) delay schedule EOF tasks to avoid too many small transactions (#39975)
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/KafkaTaskInfo.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadTaskInfo.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadTaskScheduler.java
Labels: area/load

#40501 [Bug](materialized-view) fix analyze where clause failed on mv #39061
  fe/fe-core/src/main/java/org/apache/doris/analysis/SlotRef.java
  regression-test/data/mv_p0/routine_load_mapping/test2
  regression-test/suites/mv_p0/routine_load_mapping/routine_load_mapping.groovy
Labels: area/planner, kind/test
