Repository apache/doris, pull requests merged in 2024-01, with the labels that each got.

#29075 [fix](mtmv)fix insert overwrite will generate garbage temporary partition when restarting FE
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/insertoverwrite/InsertOverwriteLog.java
  fe/fe-core/src/main/java/org/apache/doris/insertoverwrite/InsertOverwriteManager.java
  fe/fe-core/src/main/java/org/apache/doris/insertoverwrite/InsertOverwriteTask.java
  fe/fe-core/src/main/java/org/apache/doris/insertoverwrite/InsertOverwriteUtil.java
  fe/fe-core/src/main/java/org/apache/doris/journal/JournalEntity.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/InsertOverwriteTableCommand.java
  fe/fe-core/src/main/java/org/apache/doris/persist/EditLog.java
  fe/fe-core/src/main/java/org/apache/doris/persist/OperationType.java
  fe/fe-core/src/main/java/org/apache/doris/persist/meta/MetaPersistMethod.java
  fe/fe-core/src/main/java/org/apache/doris/persist/meta/PersistMetaModules.java
Labels: approved, reviewed, meta-change

#29330 [bug](join) fix left anti join output wrong result
  be/src/vec/exec/join/process_hash_table_probe_impl.h
  regression-test/data/correctness_p0/test_null_aware_left_anti_join.out
  regression-test/suites/correctness_p0/test_null_aware_left_anti_join.groovy
Labels: kind/test, approved, reviewed

#29251 [fix](compatibility) add some keywords
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisLexer.g4
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/test/java/org/apache/doris/nereids/parser/NereidsParserTest.java
Labels: approved, reviewed

#27549 [doc](mtmv)mtmv doc
  docs/en/docs/query-acceleration/async-materialized-view.md
  docs/en/docs/sql-manual/sql-functions/table-functions/jobs.md
  docs/en/docs/sql-manual/sql-functions/table-functions/mv_infos.md
  docs/en/docs/sql-manual/sql-functions/table-functions/tasks.md
  docs/en/docs/sql-manual/sql-reference/Data-Definition-Statements/Alter/ALTER-ASYNC-MATERIALIZED-VIEW.md
  docs/en/docs/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-ASYNC-MATERIALIZED-VIEW.md
  docs/en/docs/sql-manual/sql-reference/Data-Definition-Statements/Drop/DROP-ASYNC-MATERIALIZED-VIEW.md
  docs/en/docs/sql-manual/sql-reference/Utility-Statements/CANCEL-MATERIALIZED-VIEW-TASK.md
  docs/en/docs/sql-manual/sql-reference/Utility-Statements/PAUSE-MATERIALIZED-VIEW.md
  docs/en/docs/sql-manual/sql-reference/Utility-Statements/REFRESH-MATERIALIZED-VIEW.md
  docs/en/docs/sql-manual/sql-reference/Utility-Statements/RESUME-MATERIALIZED-VIEW.md
  docs/zh-CN/docs/query-acceleration/async-materialized-view.md
  docs/zh-CN/docs/sql-manual/sql-functions/table-functions/jobs.md
  docs/zh-CN/docs/sql-manual/sql-functions/table-functions/mv_infos.md
  docs/zh-CN/docs/sql-manual/sql-functions/table-functions/tasks.md
  docs/zh-CN/docs/sql-manual/sql-reference/Data-Definition-Statements/Alter/ALTER-ASYNC-MATERIALIZED-VIEW.md
  docs/zh-CN/docs/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-ASYNC-MATERIALIZED-VIEW.md
  docs/zh-CN/docs/sql-manual/sql-reference/Data-Definition-Statements/Drop/DROP-ASYNC-MATERIALIZED-VIEW.md
  docs/zh-CN/docs/sql-manual/sql-reference/Utility-Statements/CANCEL-MATERIALIZED-VIEW-TASK.md
  docs/zh-CN/docs/sql-manual/sql-reference/Utility-Statements/PAUSE-MATERIALIZED-VIEW.md
  docs/zh-CN/docs/sql-manual/sql-reference/Utility-Statements/REFRESH-MATERIALIZED-VIEW.md
  docs/zh-CN/docs/sql-manual/sql-reference/Utility-Statements/RESUME-MATERIALIZED-VIEW.md
Labels: approved

#29364 [minor](context) duplicate query context in fragment ctx
  be/src/pipeline/pipeline_fragment_context.h
  be/src/pipeline/pipeline_task.cpp
  be/src/pipeline/task_scheduler.cpp
  be/src/runtime/exec_env_init.cpp
  be/src/runtime/fragment_mgr.cpp
  be/src/vec/exec/scan/new_olap_scanner.cpp
Labels: approved, reviewed

#29346 [fix](ctx) manager the lifecycle of connection context
  be/src/runtime/group_commit_mgr.cpp
  fe/fe-core/src/main/java/org/apache/doris/planner/external/FederationBackendPolicy.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
Labels: approved, reviewed, dev/2.0.4

#29178 [Enhancement](wal) Add timout for wal memory back pressure
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/runtime/group_commit_mgr.cpp
  be/src/runtime/group_commit_mgr.h
  be/src/vec/sink/group_commit_block_sink.cpp
  be/src/vec/sink/group_commit_block_sink.h
Labels: approved, reviewed

#29340 [fix](sink) add writting restriction for OlapTableSinkV2Operator
  be/src/pipeline/exec/olap_table_sink_v2_operator.h
Labels: approved, reviewed, pick_pipelinex

#29371 Revert "[improve](move-memtable) cancel load rapidly when stream close wait (#29322)"
  be/src/vec/sink/load_stream_stub.cpp
  be/src/vec/sink/load_stream_stub.h
  be/src/vec/sink/load_stream_stub_pool.cpp
  be/src/vec/sink/load_stream_stub_pool.h
  be/src/vec/sink/writer/vtablet_writer_v2.cpp
  be/test/io/fs/stream_sink_file_writer_test.cpp
  be/test/vec/exec/load_stream_stub_pool_test.cpp
  regression-test/suites/fault_injection_p0/test_load_stream_stub_close_wait_fault_injection.groovy
Labels: approved, reviewed

#29377 Revert "[improvement](statistics) Analyze partition columns when new partition loaded data for the first time. (#29154) (#29296)"
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowTableStatsStmt.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisManager.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsAutoCollector.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/TableStatsMeta.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/StatisticsAutoCollectorTest.java
  regression-test/suites/statistics/analyze_stats.groovy
Labels: area/planner, kind/test

#29184 [nereids] consider numNulls in filter estimation
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/FilterEstimation.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/stats/FilterEstimationTest.java
Labels: approved, reviewed

#29150 [fix](doc) show catalog example output fix
  docs/en/docs/lakehouse/multi-catalog/multi-catalog.md
  docs/en/docs/sql-manual/sql-reference/Show-Statements/SHOW-CATALOGS.md
  docs/zh-CN/docs/lakehouse/multi-catalog/multi-catalog.md
  docs/zh-CN/docs/sql-manual/sql-reference/Show-Statements/SHOW-CATALOGS.md
Labels: approved, reviewed

#29313 [doc](fix)fix kill doc error and add example
  docs/en/docs/ecosystem/audit-plugin.md
  docs/en/docs/sql-manual/sql-reference/Database-Administration-Statements/KILL.md
  docs/zh-CN/docs/sql-manual/sql-reference/Database-Administration-Statements/KILL.md
Labels: approved, reviewed

#29385 [Fix](Job)Concurrency may result in event loss
  fe/fe-core/src/main/java/org/apache/doris/job/disruptor/TaskDisruptor.java
  fe/fe-core/src/main/java/org/apache/doris/scheduler/disruptor/TaskDisruptor.java
Labels: approved, reviewed

#29368 [improvement](disk) pick disk randomly when usage is less than 0.7
  be/src/olap/data_dir.cpp
  be/src/olap/data_dir.h
  be/src/olap/storage_engine.cpp
Labels: approved, reviewed

#29388 [improvement](task exec context) add parent class HasTaskExecutionCtx to own the task ctx
  be/src/pipeline/task_scheduler.cpp
  be/src/runtime/task_execution_context.h
  be/src/vec/exec/scan/scanner_context.cpp
  be/src/vec/exec/scan/scanner_context.h
  be/src/vec/exec/scan/scanner_scheduler.cpp
Labels: reviewed

#28853 [feature](Nereids): eliminate left outer join by unique
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/Rewriter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/EliminateJoinByUnique.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/EliminateJoinByUniqueTest.java
Labels: approved, reviewed

#29315 [fix](planner)nullable info of agg node's intermediate and output slots should be same
  fe/fe-core/src/main/java/org/apache/doris/planner/AggregationNode.java
  regression-test/data/correctness_p0/test_agg_materialize.out
  regression-test/suites/correctness_p0/test_agg_materialize.groovy
Labels: approved, reviewed, usercase, dev/2.0.4

#29188 [refactor](wal) move group commit load content length to runtime state
  be/src/http/action/http_stream.cpp
  be/src/http/action/stream_load.cpp
  be/src/runtime/group_commit_mgr.cpp
  be/src/runtime/group_commit_mgr.h
  be/src/runtime/plan_fragment_executor.cpp
  be/src/runtime/runtime_state.h
  be/src/vec/sink/group_commit_block_sink.cpp
  be/src/vec/sink/group_commit_block_sink.h
  gensrc/thrift/PaloInternalService.thrift
Labels: approved, reviewed, meta-change

#29226 [Bug](rollup) fallback and disable tulpe when rollup select failed on old planner
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
  regression-test/data/mv_p0/test_28741/test_28741.out
  regression-test/suites/mv_p0/test_28741/test_28741.groovy
Labels: approved, reviewed, usercase, dev/2.0.4

#29393 [cases](index compaction)Add index compaction cases
  regression-test/data/inverted_index_p0/index_compaction/test_index_compaction_dup_keys.out
  regression-test/data/inverted_index_p0/index_compaction/test_index_compaction_unique_keys.out
  regression-test/data/inverted_index_p0/index_compaction/test_index_compaction_with_multi_index_segments.out
  regression-test/suites/inverted_index_p0/index_compaction/test_index_compaction_dup_keys.groovy
  regression-test/suites/inverted_index_p0/index_compaction/test_index_compaction_unique_keys.groovy
  regression-test/suites/inverted_index_p0/index_compaction/test_index_compaction_with_multi_index_segments.groovy
Labels: approved, reviewed, dev/2.0.4

#29395 [fix](statistics)Fix set partition loaded replayer try to write edit log bug.
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisManager.java
Labels: approved, reviewed, p0_c, dev/2.0.4

#29242 [improve](agg)support push down min/max on unique table
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/implementation/AggregateStrategies.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  regression-test/data/nereids_p0/explain/test_pushdown_explain.out
  regression-test/suites/nereids_p0/explain/test_pushdown_explain.groovy
Labels: approved, reviewed, usercase, dev/2.0.4

#29359 [pick](nereids) partition prunner evaluates "not x=const" on single no…
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/OneRangePartitionEvaluator.java
  regression-test/suites/nereids_rules_p0/partition_prune/test_multi_range_partition.groovy
Labels: kind/test, area/nereids

#29404 [fix](planner)nullable info of agg node's intermediate and output slots should be same
  fe/fe-core/src/main/java/org/apache/doris/planner/AggregationNode.java
  regression-test/data/correctness_p0/test_agg_materialize.out
  regression-test/suites/correctness_p0/test_agg_materialize.groovy
Labels: area/planner, kind/test

#29424 [Improve](Variant) catch exception when set_source_content throw exception
  be/src/olap/rowset/segment_v2/segment_writer.cpp
Labels: approved, reviewed

#29413 [minor](Nereids): cleanup code
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/PhysicalPlanTranslator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/DistributionSpec.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalDistribute.java
  fe/fe-core/src/main/java/org/apache/doris/planner/EmptySetNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PlanNode.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/util/PlanChecker.java
Labels: approved, reviewed

#29351 [improve](move-memtable) report failed tablets with status
  be/src/runtime/load_stream.cpp
  be/src/runtime/load_stream.h
  be/src/vec/sink/load_stream_stub.cpp
  be/src/vec/sink/load_stream_stub.h
  be/src/vec/sink/writer/vtablet_writer_v2.cpp
  be/src/vec/sink/writer/vtablet_writer_v2.h
  be/test/runtime/load_stream_test.cpp
  gensrc/proto/internal_service.proto
Labels: approved, reviewed, meta-change

#29380 [Debug](Variant) sanitize variant in `write_column_to_mysql`
  be/src/vec/columns/column_object.cpp
  be/src/vec/columns/column_object.h
  be/src/vec/data_types/serde/data_type_object_serde.cpp
Labels: approved, reviewed, variant

#29389 [Improve](Variant) make output stable
  be/src/vec/columns/column_object.cpp
  be/src/vec/columns/subcolumn_tree.h
  regression-test/data/variant_p0/compaction/test_compaction.out
  regression-test/data/variant_p0/complexjson.out
  regression-test/data/variant_p0/delete_update.out
  regression-test/data/variant_p0/insert_into_select.out
  regression-test/data/variant_p0/load.out
  regression-test/data/variant_p0/schema_change/test_alter_table_column_with_delete.out
  regression-test/data/variant_p0/sql/gh_data.out
  regression-test/data/variant_p0/with_index/load.out
  regression-test/data/variant_p0/with_index/var_index.out
  regression-test/suites/variant_p0/desc.groovy
Labels: approved, reviewed

#29412 [improvement](statistics) Analyze partition columns when new partition loaded data for the first time. (#29154)
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowTableStatsStmt.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisManager.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsAutoCollector.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/TableStatsMeta.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/StatisticsAutoCollectorTest.java
  regression-test/suites/statistics/analyze_stats.groovy
Labels: area/planner, kind/test

#29425 [cases](index compaction)Add index compaction cases (#29393)
  regression-test/data/inverted_index_p0/index_compaction/test_index_compaction_dup_keys.out
  regression-test/data/inverted_index_p0/index_compaction/test_index_compaction_unique_keys.out
  regression-test/data/inverted_index_p0/index_compaction/test_index_compaction_with_multi_index_segments.out
  regression-test/suites/inverted_index_p0/index_compaction/test_index_compaction_dup_keys.groovy
  regression-test/suites/inverted_index_p0/index_compaction/test_index_compaction_unique_keys.groovy
  regression-test/suites/inverted_index_p0/index_compaction/test_index_compaction_with_multi_index_segments.groovy
Labels: kind/test

#29399 [fix](group commit) fix http stream group commit begin a txn
  fe/fe-core/src/main/java/org/apache/doris/analysis/NativeInsertStmt.java
  regression-test/suites/insert_p2/test_group_commit_http_stream_lineitem_schema_change.groovy
Labels: approved, reviewed

#29427 [improve](move-memtable) skip load stream stub close wait when cancel
  be/src/vec/sink/load_stream_stub.cpp
  be/src/vec/sink/load_stream_stub.h
  be/src/vec/sink/load_stream_stub_pool.cpp
  be/src/vec/sink/load_stream_stub_pool.h
  be/src/vec/sink/writer/vtablet_writer_v2.cpp
  be/test/vec/exec/load_stream_stub_pool_test.cpp
  regression-test/suites/fault_injection_p0/test_load_stream_stub_close_wait_fault_injection.groovy
Labels: approved, reviewed

#29386 [fix](merge-on-write) fix schema change may result in delete bitmap incorrect
  be/src/olap/schema_change.cpp
  be/src/olap/schema_change.h
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
  be/src/olap/task/engine_clone_task.cpp
Labels: approved, reviewed, dev/2.0.4

#29298 [Regression-test](wal) Add fault injection case for wal mem back pressure
  be/src/common/config.cpp
  be/src/common/config.h
  regression-test/data/fault_injection_p0/test_wal_mem_back_pressure_fault_injection.csv.gz
  regression-test/suites/fault_injection_p0/test_wal_mem_back_pressure_fault_injection.groovy
Labels: approved, reviewed

#29402 [Bug](fix) str_to_date "" should be null
  be/src/vec/functions/function_timestamp.cpp
  be/src/vec/runtime/vdatetime_value.cpp
  regression-test/data/query_p0/sql_functions/datetime_functions/test_date_function.out
  regression-test/suites/query_p0/sql_functions/datetime_functions/test_date_function.groovy
Labels: approved, reviewed, p0_w, dev/2.0.4

#29415 [Chore](Notice)Update Notice year
  NOTICE.txt
  dist/NOTICE-dist.txt
Labels: approved, reviewed, dev/2.0.4

#29421 [Enhancement](inverted index) strictly checkout inverted index properties
  fe/fe-core/src/main/java/org/apache/doris/analysis/InvertedIndexUtil.java
  regression-test/suites/inverted_index_p0/test_properties.groovy
Labels: approved, reviewed

#29312 [fix](Nereids) topn runtime filter only support simplest case
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/TopNScanOpt.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/postprocess/TopNRuntimeFilterTest.java
Labels: approved, reviewed, p0_c, dev/2.0.4

#29416 [Chore](sort) fix block used after it was moved
  be/src/vec/common/sort/heap_sorter.cpp
Labels: approved, reviewed, p0_c, dev/2.0.4

#29440 [Chore](ci)Temporarily cancel the mandatory restrictions of shellCheck
  .asf.yaml
Labels: approved, reviewed

#29442 [Chore](ci) Temporarily cancel the mandatory restrictions on the 2.0 branch shellCheck
  .asf.yaml
Labels: approved, reviewed

#29436 [fix](pipelineX) Fix unexpected OOM on pipelineX
  be/src/pipeline/exec/aggregation_sink_operator.h
  be/src/pipeline/pipeline_x/dependency.h
  be/src/pipeline/pipeline_x/operator.cpp
Labels: approved, reviewed

#29431 [fix](move-memtable) fix load stream stub fault injection test
  regression-test/suites/fault_injection_p0/test_load_stream_stub_failure_injection.groovy
Labels: approved, reviewed

#29420 [opt](ES catalog)Add more description for limitations of docvalue_scan
  docs/en/docs/lakehouse/multi-catalog/es.md
  docs/zh-CN/docs/lakehouse/multi-catalog/es.md
Labels: approved, reviewed

#29439 [Opt](rf) Opt broadcast join remote runtime filter merge and wait
  be/src/exprs/runtime_filter.cpp
  be/src/exprs/runtime_filter.h
  be/src/exprs/runtime_filter_slots.h
  be/src/pipeline/exec/hashjoin_build_sink.cpp
  be/src/runtime/runtime_filter_mgr.cpp
  be/src/vec/exec/join/vhash_join_node.cpp
  fe/fe-core/src/main/java/org/apache/doris/planner/RuntimeFilter.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
Labels: approved, reviewed

#29361 [fix](memory) Fix mem tracker web page notice
  be/src/http/default_path_handlers.cpp
  be/src/runtime/memory/mem_tracker_limiter.cpp
Labels: approved, reviewed

#29438 [improve](move-memtable) add log on idle timeout
  be/src/runtime/load_stream.cpp
Labels: approved, reviewed

#28107 [Enhance](fe) Iceberg table in HMS catalog supports broker scan
  docs/en/docs/lakehouse/multi-catalog/hive.md
  docs/zh-CN/docs/lakehouse/multi-catalog/hive.md
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/broker/BrokerInputFile.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/broker/BrokerInputStream.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/broker/IcebergBrokerIO.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/FileQueryScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/iceberg/IcebergMetadataCache.java
Labels: reviewed

#29426 [fix](scan) [fix](scan) _insert_data_normal should catch exception when BlockReader::_unique_key_next_block
  be/src/vec/olap/block_reader.cpp
  be/src/vec/olap/block_reader.h
Labels: approved, reviewed, usercase, dev/2.0.4

#29448 [Chore](CI)Re-configure branch-2.0 shell-check as a required check
  .asf.yaml
Labels: approved, reviewed

#29065 [fix](load) fix single replica load with auto partition
  be/src/vec/sink/writer/vtablet_writer.cpp
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapTableSink.java
Labels: approved, reviewed

#29401 [fix](thirdparty) change boost thirdparty url to offical archives.boost.io
  thirdparty/vars.sh
Labels: approved, reviewed

#29365 [fix](export)fix core when export jsonb field
  be/src/exec/olap_scanner.cpp
  be/src/olap/field.h
  be/src/olap/row_cursor.cpp
  be/src/olap/tablet_schema.h
  be/src/runtime/export_sink.cpp
Labels: approved, reviewed

#29446 [fix](pipelinex) coredump caused by VRuntimeFilterSlots::_is_global was not set
  be/src/pipeline/exec/hashjoin_build_sink.cpp
  be/src/vec/exec/join/vhash_join_node.h
Labels: approved, reviewed

#29129 [Improvement](nereids)Support ODBC table for new planner.
  fe/fe-core/src/main/java/org/apache/doris/nereids/cost/CostModelV1.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/cost/CostModelV2.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/PhysicalPlanTranslator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/Rewriter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/ChildOutputPropertyDeriver.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleSet.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/BindRelation.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/implementation/LogicalOdbcScanToPhysicalOdbcScan.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PushConjunctsIntoOdbcScan.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/StatsCalculator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/copier/LogicalPlanDeepCopier.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PlanType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalOdbcScan.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalOdbcScan.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/RelationVisitor.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/odbc/OdbcScanNode.java
Labels: approved, reviewed, usercase, dev/2.0.4-merged

#29134 [enhancement](paimon)support predict for null and notnull
  fe/fe-core/src/main/java/org/apache/doris/planner/external/paimon/PaimonPredicateConverter.java
  regression-test/data/external_table_p0/paimon/test_paimon_catalog.out
  regression-test/suites/external_table_p0/paimon/test_paimon_catalog.groovy
Labels: approved, reviewed, usercase, dev/2.0.4-merged

#29369 [docs](hive-transactional-tables) Add hive transactional tables documents.
  docs/en/docs/lakehouse/multi-catalog/hive.md
  docs/zh-CN/docs/lakehouse/multi-catalog/hive.md
Labels: approved, reviewed

#29243 [enhancement](nereids)throw readable exception when meet missing column in agg's output
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/CheckAfterRewrite.java
  regression-test/suites/nereids_p0/aggregate/aggregate.groovy
Labels: approved, reviewed

#29355 [doc](fix)invalid character 。 in en docs
  docs/en/community/developer-guide/be-clion-dev.md
  docs/en/community/developer-guide/be-vscode-dev.md
  docs/en/community/developer-guide/benchmark-tool.md
  docs/en/docs/admin-manual/cluster-management/load-balancing.md
  docs/en/docs/admin-manual/http-actions/be/tablet-distribution.md
  docs/en/docs/admin-manual/http-actions/fe/debug-point-action.md
  docs/en/docs/admin-manual/http-actions/fe/query-profile-action.md
  docs/en/docs/admin-manual/http-actions/fe/statistic-action.md
  docs/en/docs/admin-manual/privilege-ldap/ldap.md
  docs/en/docs/advanced/cold-hot-separation.md
  docs/en/docs/data-operate/import/import-way/binlog-load-manual.md
  docs/en/docs/data-operate/import/import-way/spark-load-manual.md
  docs/en/docs/ecosystem/flink-doris-connector.md
  docs/en/docs/ecosystem/kyuubi.md
  docs/en/docs/ecosystem/udaf/remote-user-defined-aggregation-function.md
  docs/en/docs/ecosystem/udf/remote-user-defined-function.md
  docs/en/docs/get-starting/quick-start.md
  docs/en/docs/install/source-install/compilation-mac.md
  docs/en/docs/lakehouse/file.md
  docs/en/docs/query-acceleration/join-optimization/bucket-shuffle-join.md
  docs/en/docs/query-acceleration/pipeline-execution-engine.md
  docs/en/docs/releasenotes/release-1.2.2.md
  docs/en/docs/sql-manual/sql-functions/bitmap-functions/bitmap-count.md
  docs/en/docs/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-TABLE.md
Labels: approved, reviewed

#29354 [regression](move-memtable) test LoadStream on_idle_timeout
  be/src/common/config.cpp
  be/src/runtime/load_stream.cpp
  be/src/service/internal_service.cpp
  be/src/vec/sink/load_stream_stub.cpp
  regression-test/suites/fault_injection_p0/test_load_stream_fault_injection.groovy
Labels: approved, reviewed

#29434 [refactor](wal) refactor some wal code
  be/src/http/action/http_stream.cpp
  be/src/http/action/stream_load.cpp
  be/src/io/fs/local_file_system.cpp
  be/src/olap/wal/wal_dirs_info.cpp
  be/src/olap/wal/wal_dirs_info.h
  be/src/olap/wal/wal_manager.cpp
  be/src/olap/wal/wal_manager.h
  be/src/runtime/group_commit_mgr.cpp
  be/test/vec/exec/vwal_scanner_test.cpp
Labels: reviewed

#29465 [fix](ci) exclude case load_stream_fault_injection
  regression-test/pipeline/p0/conf/regression-conf.groovy
Labels: approved, reviewed

#29462 [improvement](statistics)Enable minmax push down for unique table while doing analyze.
  fe/fe-core/src/main/java/org/apache/doris/statistics/util/StatisticsUtil.java
Labels: approved, reviewed

#29405 [Fix](Nereids) fix leading hint dealing with big brace
  fe/fe-core/src/main/java/org/apache/doris/nereids/hint/LeadingHint.java
  regression-test/data/nereids_p0/hint/fix_leading.out
  regression-test/suites/nereids_p0/hint/fix_leading.groovy
Labels: approved, reviewed, usercase, dev/2.0.4

#27977 [fix](docs)Fix description for error code 1051 #27751
  docs/en/docs/admin-manual/maint-monitor/doris-error-code.md
Labels: approved, reviewed

#29256 [fix](nereids) fix aggregate function roll up when expression arguments is not equals
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewAggregateRule.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/TreeNode.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/Any.java
  regression-test/data/nereids_rules_p0/mv/agg_with_roll_up/aggregate_with_roll_up.out
  regression-test/suites/nereids_rules_p0/mv/agg_with_roll_up/aggregate_with_roll_up.groovy
Labels: approved, reviewed

#29460 [pipelineX](fix) Fix query cancel timeout
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/query_context.cpp
  be/src/vec/exec/scan/scanner_context.cpp
Labels: approved, reviewed

#29481 [fix](auditloader) support audit table millisecond and fix stmt truncated by '\r'
  fe_plugins/auditloader/src/main/java/org/apache/doris/plugin/audit/AuditLoaderPlugin.java
Labels: approved, reviewed

#29331 [bugfix](scannerscheduler) should minus num_of_scanners before check should schedule #28926
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/common/status.h
  be/src/exec/exec_node.h
  be/src/pipeline/exec/scan_operator.cpp
  be/src/pipeline/exec/scan_operator.h
  be/src/pipeline/pipeline_task.h
  be/src/pipeline/task_scheduler.cpp
  be/src/runtime/fragment_mgr.cpp
  be/src/service/backend_service.cpp
  be/src/vec/exec/scan/pip_scanner_context.h
  be/src/vec/exec/scan/scanner_context.cpp
  be/src/vec/exec/scan/scanner_context.h
  be/src/vec/exec/scan/scanner_scheduler.cpp
  be/src/vec/exec/scan/scanner_scheduler.h
  be/src/vec/exec/scan/vscan_node.cpp
  be/src/vec/exec/scan/vscan_node.h
  be/src/vec/exec/scan/vscanner.h
  regression-test/pipeline/p0/conf/be.conf
Labels: approved, reviewed

#29479 [fix](auditloader) support audit table millisecond and fix stmt truncated by '\r'
  fe_plugins/auditloader/src/main/java/org/apache/doris/plugin/audit/AuditLoaderPlugin.java
Labels: approved, reviewed

#29430 [improvement](compaction) start 1 cumu compaction thread each disk by default
  be/src/agent/task_worker_pool.cpp
  be/src/common/config.cpp
  be/src/olap/olap_server.cpp
  docs/en/docs/admin-manual/config/be-config.md
  docs/zh-CN/docs/admin-manual/config/be-config.md
Labels: approved, reviewed, kind/behavior-changed

#29342 [improve](move-memtable) add move memtable too many segments fault injection
  regression-test/data/fault_injection_p0/test_too_many_segments_fault_injection.out
  regression-test/suites/fault_injection_p0/test_too_many_segments_fault_injection.groovy
Labels: approved, reviewed

#29476 [Bug](fix) str_to_date "" should be null
  be/src/vec/functions/function_timestamp.cpp
  be/src/vec/runtime/vdatetime_value.cpp
  regression-test/data/query_p0/sql_functions/datetime_functions/test_date_function.out
  regression-test/suites/query_p0/sql_functions/datetime_functions/test_date_function.groovy
Labels: kind/test, approved, reviewed

#29461 [fix](group_commit) Fix check auth error when relaying wal
  be/src/http/action/http_stream.cpp
  be/src/olap/wal/wal_table.cpp
Labels: approved, reviewed

#29455 [fix](Nereids) topn runtime filter only support simplest case (#29312)
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/TopNScanOpt.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/postprocess/TopNRuntimeFilterTest.java
Labels: area/nereids

#29414 [fix](doc) fix en doc content that list partition column must be NOT NULL
  docs/en/docs/data-table/data-partition.md
Labels: approved, reviewed

#29394 [improvement](scan) make global runtime filter support in-list filter
  be/src/exprs/runtime_filter.cpp
  be/src/exprs/runtime_filter.h
  be/src/exprs/runtime_filter_slots.h
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/RuntimeFilterGenerator.java
Labels: approved, reviewed

#29370 [doc](nereids)Add query rewrite by materialized view feature summary and desc doc
  docs/en/docs/query-acceleration/async-materialized-view.md
  docs/en/docs/query-acceleration/async-materialized-view/query-rewrite-summary-and-desc.md
  docs/zh-CN/docs/query-acceleration/async-materialized-view.md
  docs/zh-CN/docs/query-acceleration/async-materialized-view/query-rewrite-summary-and-desc.md
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVUtil.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
Labels: approved, reviewed

#29454 [Bug](config) set enabe_agg_state to need forward
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
Labels: approved, reviewed, p0_b, dev/2.0.4

#29321 [Bug](mark-join) fix wrong result on mark join + other conjunct
  be/src/vec/common/hash_table/hash_map.h
  be/src/vec/exec/join/process_hash_table_probe_impl.h
  regression-test/data/query_p0/join/rqg/doris8317/doris8317.out
  regression-test/data/query_p0/join/rqg/doris9097/doris9097.out
  regression-test/data/query_p0/join/rqg/doris9100/doris9100.out
  regression-test/data/query_p0/join/rqg/doris9161/doris9161.out
  regression-test/suites/query_p0/join/rqg/doris8317/doris8317.groovy
  regression-test/suites/query_p0/join/rqg/doris9097/doris9097.groovy
  regression-test/suites/query_p0/join/rqg/doris9100/doris9100.groovy
  regression-test/suites/query_p0/join/rqg/doris9161/doris9161.groovy
Labels: approved, reviewed, p0_w

#29339 [feature](paimon)support native reader
  be/src/vec/exec/scan/vfile_scanner.cpp
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/constants/PaimonProperties.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/paimon/PaimonScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/paimon/PaimonSource.java
  fe/fe-core/src/main/java/org/apache/doris/planner/external/paimon/PaimonSplit.java
  fe/pom.xml
  gensrc/thrift/PlanNodes.thrift
Labels: approved, reviewed, usercase, meta-change, dev/2.0.4

#29477 [fix](regression) spare .testfile to make disk checker happy when injecting fault
  be/src/io/fs/local_file_system.cpp
  be/src/olap/data_dir.cpp
  be/src/olap/data_dir.h
Labels: approved, reviewed

#29512 [bugfix](scanner done) should not set process status to query context
  be/src/vec/exec/scan/scanner_context.cpp
Labels: approved, reviewed

#29504 [fix](2.0) error value when no rpc in sink buffer
  be/src/pipeline/exec/exchange_sink_buffer.cpp
Labels: approved, reviewed, area/pipeline

#29506 [doc](mv) add mv docs to sidebar
  docs/dev.json
  docs/en/docs/query-acceleration/async-materialized-view/async-materialized-view.md
  docs/en/docs/query-acceleration/async-materialized-view/query-async-materialized-view.md
  docs/sidebars.json
  docs/zh-CN/docs/query-acceleration/async-materialized-view/async-materialized-view.md
  docs/zh-CN/docs/query-acceleration/async-materialized-view/query-async-materialized-view.md
Labels: approved, reviewed

#29530 [doc](fix) fix dead link of mv doc
  docs/en/docs/query-acceleration/async-materialized-view/async-materialized-view.md
  docs/zh-CN/docs/query-acceleration/async-materialized-view/async-materialized-view.md
Labels: approved, reviewed

#28420 [Bug](load) fix load failed on stream load tvf into agg state
  fe/fe-core/src/main/java/org/apache/doris/analysis/NativeInsertStmt.java
  fe/fe-core/src/main/java/org/apache/doris/load/Load.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OriginalPlanner.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/InsertStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/QueryPlanTest.java
  regression-test/data/mv_p0/agg_state/test_agg_state_max_by.out
  regression-test/suites/mv_p0/agg_state/test_agg_state_max_by.groovy
Labels: approved, reviewed

#29539 [ci](case) exclude case test_dump_image
  regression-test/pipeline/p0/conf/regression-conf.groovy
Labels: approved, reviewed

#29507 [cherry-pick](agg)support push down min/max on unique table (#29242)
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/implementation/AggregateStrategies.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  regression-test/data/nereids_p0/explain/test_pushdown_explain.out
  regression-test/suites/nereids_p0/explain/test_pushdown_explain.groovy
Labels: kind/test, area/nereids

#29497 [LOG](exec) Add timer for hostname_to_ip
  be/src/util/network_util.cpp
Labels: approved, reviewed

#29494 [docs](timezone) refactor docs of timezone
  docs/en/docs/advanced/time-zone.md
  docs/en/docs/advanced/variables.md
  docs/en/docs/sql-manual/sql-reference/Data-Manipulation-Statements/Load/STREAM-LOAD.md
  docs/en/docs/sql-manual/sql-reference/Data-Types/DATETIME.md
  docs/en/docs/sql-manual/sql-reference/Database-Administration-Statements/SET-VARIABLE.md
  docs/zh-CN/docs/advanced/time-zone.md
  docs/zh-CN/docs/advanced/variables.md
  docs/zh-CN/docs/sql-manual/sql-reference/Data-Manipulation-Statements/Load/STREAM-LOAD.md
  docs/zh-CN/docs/sql-manual/sql-reference/Data-Types/DATETIME.md
  docs/zh-CN/docs/sql-manual/sql-reference/Database-Administration-Statements/SET-VARIABLE.md
  regression-test/data/datatype_p0/datetimev2/test_tz_streamload.out
  regression-test/data/datatype_p0/datetimev2/test_tz_streamload2.csv
Labels: approved, reviewed, dev/2.0.4

#29464 [enhancement](disk) log disk path when creating tablet
  be/src/olap/data_dir.cpp
  be/src/olap/tablet_manager.cpp
Labels: approved, reviewed, dev/2.1.0

#28492 [Improve](regresstests)add test cases for array functions
  regression-test/data/datatype_p0/nested_types/query/array_functions/test_array_element_at_and_slice.out
  regression-test/data/datatype_p0/nested_types/query/array_functions/test_array_functions_array_intersect_sort.out
  regression-test/data/datatype_p0/nested_types/query/array_functions/test_array_functions_array_join.out
  regression-test/data/datatype_p0/nested_types/query/array_functions/test_array_functions_array_with_const.out
  regression-test/data/datatype_p0/nested_types/query/array_functions/test_array_functions_concat_compact_difference.out
  regression-test/data/datatype_p0/nested_types/query/array_functions/test_array_functions_in_ck_case.out
  regression-test/data/datatype_p0/nested_types/query/array_functions/test_array_push_pop_backfront.out
  regression-test/data/datatype_p0/nested_types/query/array_functions/test_array_zip_array_enumerate_uniq.out
  regression-test/data/query_p0/sql_functions/array_functions/test_array_functions_of_array_countEqual.out
  regression-test/data/query_p0/sql_functions/array_functions/test_array_functions_of_array_difference.out
  regression-test/suites/datatype_p0/nested_types/query/array_functions/load.groovy
  regression-test/suites/datatype_p0/nested_types/query/array_functions/test_array_element_at_and_slice.groovy
  regression-test/suites/datatype_p0/nested_types/query/array_functions/test_array_functions_array_intersect_sort.groovy
  regression-test/suites/datatype_p0/nested_types/query/array_functions/test_array_functions_array_join.groovy
  regression-test/suites/datatype_p0/nested_types/query/array_functions/test_array_functions_array_with_const.groovy
  regression-test/suites/datatype_p0/nested_types/query/array_functions/test_array_functions_concat_compact_difference.groovy
  regression-test/suites/datatype_p0/nested_types/query/array_functions/test_array_push_pop_backfront.groovy
  regression-test/suites/datatype_p0/nested_types/query/array_functions/test_array_zip_array_enumerate_uniq.groovy
  regression-test/suites/query_p0/sql_functions/array_functions/test_array_functions_of_array_countEqual.groovy
  regression-test/suites/query_p0/sql_functions/array_functions/test_array_functions_of_array_difference.groovy
Labels: approved, reviewed, dev/2.0.4

#29452 [fix](scan) _insert_data_normal should catch exception when BlockReader::_unique_key_next_block
  be/src/vec/olap/block_reader.cpp
  be/src/vec/olap/block_reader.h
Labels: approved, reviewed

#29459 [opt](ES catalog)Add more description for limitations of docvalue_scan
  docs/en/docs/lakehouse/multi-catalog/es.md
  docs/zh-CN/docs/lakehouse/multi-catalog/es.md
Labels: kind/docs

#29515 [fix](nereids)logicalhaving is in wrong place after logicalagg and logicalwindow
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/FillUpMissingSlots.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/NormalizeAggregate.java
  regression-test/data/nereids_p0/aggregate/agg_window_project.out
  regression-test/suites/nereids_p0/aggregate/agg_window_project.groovy
Labels: kind/test, area/nereids

#29550 [fix](case) Update test_stream_load.groovy
  regression-test/suites/load_p0/stream_load/test_stream_load.groovy
Labels: kind/test

#29547 [fix](move-memtable) check eos when close stream
  be/src/runtime/load_stream.cpp
  be/src/runtime/load_stream.h
  be/src/vec/sink/load_stream_stub.cpp
  be/src/vec/sink/load_stream_stub.h
  gensrc/proto/internal_service.proto
Labels: approved, reviewed, meta-change

#29267 [improve](move-memtable) log rpc failures in stream file writer
  be/src/io/fs/stream_sink_file_writer.cpp
Labels: approved, reviewed

#29153 [feature](mv) add mv rewrite info to explain
  fe/fe-core/src/main/java/org/apache/doris/nereids/NereidsPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/joinorder/hypergraph/edge/Edge.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/joinorder/hypergraph/node/StructInfoNode.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewAggregateRule.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewJoinRule.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewRule.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/ComparisonResult.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/EquivalenceClass.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/HyperGraphComparator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/LogicalCompatibilityContext.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/MaterializationContext.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/Predicates.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/StructInfo.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/mapping/ExpressionMapping.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/mapping/Mapping.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/mapping/SlotMapping.java
  regression-test/suites/nereids_rules_p0/mv/agg_with_roll_up/aggregate_with_roll_up.groovy
  regression-test/suites/nereids_rules_p0/mv/agg_without_roll_up/aggregate_without_roll_up.groovy
  regression-test/suites/nereids_rules_p0/mv/join/inner/inner_join.groovy
  regression-test/suites/nereids_rules_p0/mv/join/left_outer/outer_join.groovy
  regression-test/suites/nereids_rules_p0/mv/partition_mv_rewrite.groovy
Labels: approved, reviewed, meta-change

#29437 [improve](move-memtable) handle EAGAIN in load stream
  be/src/runtime/load_stream.cpp
  be/src/runtime/load_stream.h
Labels: approved, reviewed

#29552 [improve](move-memtable) add stream sink file writer finalize fault injection
  be/src/io/fs/stream_sink_file_writer.cpp
  regression-test/suites/fault_injection_p0/test_load_stream_stub_failure_injection.groovy
Labels: approved, reviewed

#29362 [fix](move-memtable) disable move memtable when light schema change is false
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BrokerLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/InsertIntoTableCommand.java
  fe/fe-core/src/main/java/org/apache/doris/planner/StreamLoadPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  regression-test/suites/fault_injection_p0/test_disable_move_memtable.groovy
Labels: approved, reviewed

#29391 [opt](config) create custom conf dir if not exists
  fe/fe-common/src/main/java/org/apache/doris/common/ConfigBase.java
Labels: approved, reviewed, dev/2.0.4

#29495 [fix](profile) Fix row distribution timer in loadv1
  be/src/vec/sink/vrow_distribution.cpp
  be/src/vec/sink/vrow_distribution.h
  be/src/vec/sink/writer/vtablet_writer.cpp
Labels: approved, reviewed

#29559 [fix](pipelinex) coredump caused by null pointer of Dependency::_shared_state
  be/src/pipeline/exec/aggregation_sink_operator.h
Labels: approved, reviewed

#29499 [fix](test)Fix index_compaction unstable cases
  regression-test/suites/inverted_index_p0/index_compaction/test_index_compaction_dup_keys.groovy
  regression-test/suites/inverted_index_p0/index_compaction/test_index_compaction_unique_keys.groovy
  regression-test/suites/inverted_index_p0/index_compaction/test_index_compaction_with_multi_index_segments.groovy
Labels: reviewed, dev/2.0.4

#29356 [chore](test) make configuration of parallel scan fuzzy
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  regression-test/data/query_p0/sql_functions/array_functions/test_array_with_scale_type.out
  regression-test/data/query_p0/sql_functions/window_functions/test_window_fn.out
  regression-test/data/variant_p0/column_name.out
  regression-test/suites/bloom_filter_p0/test_bloom_filter_hit.groovy
  regression-test/suites/correctness_p0/test_order_by.groovy
  regression-test/suites/datatype_p0/date/test_date_in_predicate.groovy
  regression-test/suites/mv_p0/ssb/multiple_no_where/multiple_no_where.groovy
  regression-test/suites/mv_p0/ssb/multiple_ssb/multiple_ssb.groovy
  regression-test/suites/mv_p0/ssb/multiple_ssb_between/multiple_ssb_between.groovy
  regression-test/suites/mv_p0/ssb/q_1_1/q_1_1.groovy
  regression-test/suites/mv_p0/ssb/q_2_1/q_2_1.groovy
  regression-test/suites/mv_p0/ssb/q_3_1/q_3_1.groovy
  regression-test/suites/mv_p0/ssb/q_4_1/q_4_1.groovy
  regression-test/suites/query_p0/sql_functions/array_functions/test_array_with_scale_type.groovy
  regression-test/suites/query_p0/sql_functions/window_functions/test_window_fn.groovy
  regression-test/suites/variant_p0/column_name.groovy
  regression-test/suites/variant_p0/compaction/test_compaction.groovy
Labels: approved, reviewed

#29527 [Opt](parquet-reader) Opt `ColumnSelectVector::set_run_length_null_map()` in parquet reader.
  be/src/vec/exec/format/parquet/parquet_common.cpp
Labels: approved, reviewed, dev/2.0.4

#29433 [fix](Nereids) should cast NOT's child to boolean when analyze
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/FunctionBinder.java
Labels: approved, reviewed, dev/2.0.4, dev/2.1.0

#29403 [improve](function) get result from constant_col when expr is const
  be/src/vec/exprs/vcase_expr.cpp
  be/src/vec/exprs/vectorized_fn_call.cpp
  be/src/vec/exprs/vexpr.cpp
  be/src/vec/exprs/vexpr.h
  be/src/vec/exprs/vin_predicate.cpp
Labels: approved, reviewed

#28557 [enchancement](delete) fix delete stmt return error with fold on be
  fe/fe-core/src/main/java/org/apache/doris/analysis/DeleteStmt.java
  regression-test/suites/delete_p0/test_delete.groovy
Labels: approved, reviewed, dev/2.0.4

#29496 [nereids] consider numNulls in filter estimation
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/FilterEstimation.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/stats/FilterEstimationTest.java
Labels: area/nereids

#29554 [Fix](Variant) fix heap use after free when updating tablet schema
  be/src/olap/rowset/segment_creator.cpp
Labels: approved, reviewed

#29409 [fix](Nereids) mark join should not eliminate join when child is empty
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/EliminateEmptyRelation.java
  regression-test/data/empty_relation/eliminate_empty.out
  regression-test/suites/empty_relation/eliminate_empty.groovy
Labels: approved, reviewed, p0_w, dev/2.0.4, dev/2.1.0

#29555 [ut](fe) remove useless and unsatbale tests
  fe/fe-core/src/test/java/org/apache/doris/mysql/MysqlServerTest.java
Labels: approved, reviewed

#29541 [refactor](fold) refactor fold executor could get error status
  be/src/runtime/fold_constant_executor.cpp
  be/src/runtime/fold_constant_executor.h
  be/src/service/internal_service.cpp
Labels: approved, reviewed

#29523 [fix](regression-test) result is not stable for test_show_statistic_proc
  regression-test/suites/show_p0/test_show_statistic_proc.groovy
Labels: approved, reviewed, dev/2.0.4

#27338 [optimize](cooldown)Improved filtering conditions for cooldown tablet
  be/src/olap/tablet.cpp
Labels: approved, reviewed

#27294 [enhancement](Nereids) add test for push filter through operator
  regression-test/data/nereids_rules_p0/filter_push_down/push_filter_through.out
  regression-test/suites/nereids_rules_p0/filter_push_down/push_filter_through.groovy
Labels: approved, reviewed, dev/2.0.4

#29569 [fix](regresion) fix 2.0 regression catch unsupported hive formatted exception
  regression-test/suites/external_table_p2/hive/test_external_catalog_hive.groovy
Labels: kind/test, reviewed

#29586 [Docs](Community)Use the standard ASF Code of Conduct template
  CODE_OF_CONDUCT.md
Labels: approved, reviewed

#29390 [test](Nereids): add more test for eliminate inner join by fk
  regression-test/data/nereids_rules_p0/pkfk/eliminate_inner.out
  regression-test/suites/nereids_rules_p0/pkfk/eliminate_inner.groovy
Labels: approved, reviewed

#29568 [Fix](show data) Inverted index size not added to data size after index build
  be/src/olap/task/index_builder.cpp
  regression-test/suites/inverted_index_p0/test_show_data.groovy
Labels: approved, reviewed

#29581 [improve](insert-into) record rows info in log for check
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/load_channel.cpp
  be/src/runtime/load_channel.h
  be/src/runtime/tablets_channel.cpp
  be/src/runtime/tablets_channel.h
Labels: approved, reviewed

#29503 [opt](Nereids) add float type signature for sum aggregate function
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/MultiDistinctSum.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/Sum.java
  regression-test/suites/nereids_function_p0/agg_function/agg.groovy
Labels: approved, reviewed, p0_w, dev/2.0.4, dev/2.1.0

#29435 [fix](Nereids) exists should not return null
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/SubqueryToApply.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/ExistsApplyToJoin.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalApply.java
  regression-test/data/nereids_tpcds_shape_sf1000_p0/shape/query10.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/shape/query35.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/noStatsRfPrune/query10.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/noStatsRfPrune/query35.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/no_stats_shape/query10.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/no_stats_shape/query35.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/rf_prune/query10.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/rf_prune/query35.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query10.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query35.out
Labels: approved, reviewed, dev/2.0.4, dev/2.1.0

#29536 [fix](delete) fix incorrect tablet schema of delete predicate rowset
  fe/fe-core/src/main/java/org/apache/doris/load/DeleteJob.java
Labels: approved, reviewed, p0_c, dev/2.0.4

#28757 [improvement](group commit) Add an option of enable relay wal on all regression test
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/olap/wal/wal_manager.cpp
  be/src/olap/wal/wal_manager.h
  be/src/olap/wal/wal_table.cpp
  be/src/runtime/group_commit_mgr.cpp
  be/src/vec/sink/writer/vwal_writer.cpp
  be/src/vec/sink/writer/vwal_writer.h
Labels: approved, reviewed

#29590 [Bug](config) set enabe_agg_state to need forward (#29454)
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
Labels: approved, reviewed

#27324 [optimize](cooldown)If cooldowned_rowsets is empty, there is no need to follow the logic of traversing the files
  be/src/olap/tablet.cpp
Labels: reviewed

#28361 [feature](function) support ip function ipv6_string_to_num(_or_default, _or_null), inet6_aton
  be/src/vec/common/format_ip.cpp
  be/src/vec/common/format_ip.h
  be/src/vec/functions/function_ip.cpp
  be/src/vec/functions/function_ip.h
  docs/en/docs/sql-manual/sql-functions/ip-functions/inet6-aton.md
  docs/en/docs/sql-manual/sql-functions/ip-functions/ipv6-string-to-num-or-default.md
  docs/en/docs/sql-manual/sql-functions/ip-functions/ipv6-string-to-num-or-null.md
  docs/en/docs/sql-manual/sql-functions/ip-functions/ipv6-string-to-num.md
  docs/sidebars.json
  docs/zh-CN/docs/sql-manual/sql-functions/ip-functions/inet6-aton.md
  docs/zh-CN/docs/sql-manual/sql-functions/ip-functions/inet6-ntoa.md
  docs/zh-CN/docs/sql-manual/sql-functions/ip-functions/ipv6-num-to-string.md
  docs/zh-CN/docs/sql-manual/sql-functions/ip-functions/ipv6-string-to-num-or-default.md
  docs/zh-CN/docs/sql-manual/sql-functions/ip-functions/ipv6-string-to-num-or-null.md
  docs/zh-CN/docs/sql-manual/sql-functions/ip-functions/ipv6-string-to-num.md
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinScalarFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Ipv6StringToNum.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Ipv6StringToNumOrDefault.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Ipv6StringToNumOrNull.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/ScalarFunctionVisitor.java
  gensrc/script/doris_builtins_functions.py
  regression-test/data/nereids_function_p0/ip_functions.out
  regression-test/data/query_p0/sql_functions/ip_functions/test_ip_functions.out
  regression-test/suites/nereids_function_p0/ip_functions.groovy
  regression-test/suites/query_p0/sql_functions/ip_functions/test_ip_functions.groovy
Labels: approved, reviewed, meta-change

#29363 [Fix](partition) Skip rowset partition id eq 0 smaller than config wh…
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/olap/data_dir.cpp
  be/src/olap/rowset/rowset_meta_manager.cpp
  be/src/olap/rowset/rowset_meta_manager.h
  be/src/olap/tablet_manager.cpp
  be/src/olap/tablet_meta.cpp
  be/src/olap/txn_manager.cpp
  be/test/olap/rowset/rowset_meta_manager_test.cpp
Labels: approved, reviewed, usercase

#29510 [Fix](partition) Skip rowset partition id eq 0 smaller than config wh…
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/olap/data_dir.cpp
  be/src/olap/rowset/rowset_meta_manager.cpp
  be/src/olap/rowset/rowset_meta_manager.h
  be/src/olap/tablet_manager.cpp
  be/src/olap/tablet_meta.cpp
  be/src/olap/txn_manager.cpp
  be/test/olap/path_gc_test.cpp
  be/test/olap/rowset/rowset_meta_manager_test.cpp
Labels: approved, reviewed

#29458 [feature](Nereids): InferPredicates support In
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/InferPredicates.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PredicatePropagation.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PullUpPredicates.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/EqualTo.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/InPredicate.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/InferPredicatesTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/PredicatePropagationTest.java
  regression-test/data/nereids_p0/hint/fix_leading.out
  regression-test/data/nereids_p0/hint/test_leading.out
  regression-test/suites/nereids_p0/infer_predicate/infer_predicate.groovy
Labels: approved, reviewed, meta-change, dev/2.0.4

#29583 [Fix](wal) Fix update wal dir core
  be/src/io/fs/local_file_system.cpp
  be/src/olap/wal/wal_dirs_info.cpp
Labels: approved, reviewed

#29429 [ci](perf) integration clickbench test into new performance pipeline
  .licenserc.yaml
  regression-test/pipeline/common/doris-utils.sh
  regression-test/pipeline/common/github-utils.sh
  regression-test/pipeline/performance/clickbench/check-query-result.sh
  regression-test/pipeline/performance/clickbench/conf/be_custom.conf
  regression-test/pipeline/performance/clickbench/conf/fe_custom.conf
  regression-test/pipeline/performance/clickbench/conf/opt_session_variables.sql
  regression-test/pipeline/performance/clickbench/queries-sort.sql
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q1.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q10.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q11.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q12.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q13.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q14.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q15.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q16.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q17.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q18.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q19.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q2.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q20.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q21.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q22.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q23.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q24.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q25.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q26.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q27.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q28.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q29.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q3.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q30.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q31.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q32.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q33.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q34.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q35.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q36.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q37.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q38.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q39.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q4.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q40.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q41.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q42.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q43.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q5.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q6.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q7.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q8.result
  regression-test/pipeline/performance/clickbench/query-result-target/doris-q9.result
  regression-test/pipeline/performance/compile.sh
  regression-test/pipeline/performance/conf/be_custom.conf
  regression-test/pipeline/performance/conf/fe_custom.conf
  regression-test/pipeline/performance/deploy.sh
  regression-test/pipeline/performance/prepare.sh
  regression-test/pipeline/performance/run-clickbench.sh
  regression-test/pipeline/performance/run-load.sh
  regression-test/pipeline/performance/run-tpcds.sh
  regression-test/pipeline/performance/run-tpch.sh
Labels: approved, reviewed

#29594 [fix](planner) Fix table sample not take effect
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/PhysicalPlanTranslator.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
Labels: approved, reviewed, usercase, dev/2.0.4

#29588 [fix](memory) Fix LRUCacheType::NUMBER charge
  be/src/olap/lru_cache.cpp
  be/src/olap/lru_cache.h
  be/src/runtime/exec_env_init.cpp
  be/test/olap/lru_cache_test.cpp
Labels: approved, reviewed

#29297 [FIX](complextype)fix compare_at base function support nested types
  be/src/vec/columns/column.h
  be/src/vec/columns/column_array.cpp
  be/src/vec/columns/column_array.h
  be/src/vec/columns/column_map.cpp
  be/src/vec/columns/column_map.h
  be/src/vec/columns/column_struct.cpp
  be/src/vec/columns/column_struct.h
Labels: approved, reviewed, p0_c, dev/2.0.4

#29610 [fix](delete) fix incorrect tablet schema of delete predicate rowset (#29536)
  fe/fe-core/src/main/java/org/apache/doris/load/DeleteHandler.java
Labels: area/load, approved, reviewed, dev/2.0.4

#29546 [fix](nereids)need do type coercion after simplify comparasion predicate
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/SimplifyComparisonPredicate.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/expression/rules/SimplifyComparisonPredicateTest.java
Labels: approved, reviewed, usercase, dev/2.0.4

#29528 [fix](jni) add datetimev2 precision
  be/src/vec/exec/jni_connector.cpp
  fe/be-java-extensions/java-common/src/main/java/org/apache/doris/common/jni/vec/ColumnType.java
  fe/be-java-extensions/paimon-scanner/src/main/java/org/apache/doris/paimon/PaimonJniScanner.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/external/PaimonExternalTable.java
  regression-test/data/external_table_p0/paimon/test_paimon_catalog.out
Labels: approved, reviewed, usercase, dev/2.0.4

#29549 [fix](proc)Merge fix for long-running queries into 1.2
  fe/fe-core/src/main/java/org/apache/doris/common/proc/CurrentQueryStatementsProcNode.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/CurrentQueryStatisticsProcDir.java
Labels: approved, reviewed

#29548 [FIX](complextype) update complex nested support complex type in fe
  fe/fe-common/src/main/java/org/apache/doris/catalog/Type.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ArrayLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/DecimalLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/Expr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/FloatLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/LiteralExpr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/MapLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/StructLiteral.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ArrayLiteralTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/MapLiteralTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/StructLiteralTest.java
Labels: area/planner, approved, reviewed, usercase, dev/2.0.4

#29614 [improvement](function) standardize some ip functions' signatures
  be/src/vec/functions/function_ip.cpp
  be/src/vec/functions/function_ip.h
  docs/en/docs/sql-manual/sql-functions/ip-functions/ipv4-num-to-string.md
  docs/en/docs/sql-manual/sql-functions/ip-functions/ipv4-string-to-num-or-default.md
  docs/en/docs/sql-manual/sql-functions/ip-functions/ipv4-string-to-num-or-null.md
  docs/en/docs/sql-manual/sql-functions/ip-functions/ipv4-string-to-num.md
  docs/en/docs/sql-manual/sql-functions/ip-functions/ipv6-num-to-string.md
  docs/zh-CN/docs/sql-manual/sql-functions/ip-functions/ipv4-num-to-string.md
  docs/zh-CN/docs/sql-manual/sql-functions/ip-functions/ipv4-string-to-num-or-default.md
  docs/zh-CN/docs/sql-manual/sql-functions/ip-functions/ipv4-string-to-num-or-null.md
  docs/zh-CN/docs/sql-manual/sql-functions/ip-functions/ipv4-string-to-num.md
  docs/zh-CN/docs/sql-manual/sql-functions/ip-functions/ipv6-num-to-string.md
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinScalarFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Ipv4NumToString.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Ipv4StringToNum.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Ipv4StringToNumOrDefault.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Ipv4StringToNumOrNull.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Ipv6NumToString.java
  gensrc/script/doris_builtins_functions.py
  regression-test/suites/nereids_function_p0/ip_functions.groovy
  regression-test/suites/query_p0/sql_functions/ip_functions/test_ip_functions.groovy
Labels: approved, reviewed

#29607 [fix](http) throw RejectedExecutionException to prevent http hanging by Future
  docs/en/docs/admin-manual/config/fe-config.md
  docs/zh-CN/docs/admin-manual/config/fe-config.md
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/common/ThreadPoolManager.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/util/LoadSubmitter.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/util/StatementSubmitter.java
Labels: approved, reviewed

#29488 [fix](polixy)support drop policy for user or role
  docs/en/docs/sql-manual/sql-reference/Data-Definition-Statements/Drop/DROP-POLICY.md
  docs/en/docs/sql-manual/sql-reference/Show-Statements/SHOW-POLICY.md
  docs/zh-CN/docs/sql-manual/sql-reference/Data-Definition-Statements/Drop/DROP-POLICY.md
  docs/zh-CN/docs/sql-manual/sql-reference/Show-Statements/SHOW-POLICY.md
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/DropPolicyStmt.java
  fe/fe-core/src/main/java/org/apache/doris/policy/DropPolicyLog.java
  fe/fe-core/src/main/java/org/apache/doris/policy/RowPolicy.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/analysis/CheckRowPolicyTest.java
  fe/fe-core/src/test/java/org/apache/doris/policy/PolicyTest.java
  regression-test/suites/account_p0/test_nereids_row_policy.groovy
Labels: approved, reviewed, kind/behavior-changed, dev/2.0.4
