Repository apache/doris, pull requests merged in 2024-08, with the labels that each got.

#38618 [Opt](load) print tablet id when memtable flush coredump
  be/src/olap/memtable_flush_executor.cpp
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x

#38476 [chore](olap) Unify the parameters into SegmentWriterOptions
  be/src/olap/rowset/beta_rowset_writer.cpp
  be/src/olap/rowset/segment_creator.cpp
  be/src/olap/rowset/segment_v2/segment_writer.cpp
  be/src/olap/rowset/segment_v2/segment_writer.h
  be/src/olap/rowset/segment_v2/vertical_segment_writer.cpp
  be/src/olap/rowset/segment_v2/vertical_segment_writer.h
  be/src/olap/rowset/vertical_beta_rowset_writer.cpp
  be/test/olap/delete_bitmap_calculator_test.cpp
Labels: approved, reviewed

#38543 [chore](explain) Add algorithm item to VSORT explainition and modify dump_data of Block
  be/src/vec/core/block.cpp
  be/src/vec/core/block.h
  be/src/vec/functions/function.cpp
  fe/fe-core/src/main/java/org/apache/doris/planner/SortNode.java
Labels: approved, reviewed

#38550 [fix](Nereids): fix be core when array_map is not nullable (#24488)
  be/src/vec/exprs/lambda_function/varray_map_function.cpp
  fe/fe-core/src/main/java/org/apache/doris/analysis/Expr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/LambdaFunctionCallExpr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/LambdaFunctionExpr.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/Validator.java
  regression-test/data/nereids_function_p0/scalar_function/Array.out
Labels: area/planner, kind/test, area/nereids

#38567 [test](routine load) add routine load case with timestamp as offset
  regression-test/data/load_p0/routine_load/test_routine_load_offset.out
  regression-test/suites/load_p0/routine_load/data/test_offset_time.csv
  regression-test/suites/load_p0/routine_load/test_routine_load_offset.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#38523 [fix](routine load) fix show routine load task result incorrect
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowRoutineLoadTaskStmt.java
  regression-test/suites/load_p0/routine_load/data/test_show_routine_load.csv
  regression-test/suites/load_p0/routine_load/test_show_routine_load.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x

#38611 [fix](group commit) add debug log show why group commit not work; delete wal when replay success
  be/src/olap/wal/wal_table.cpp
  be/src/runtime/group_commit_mgr.cpp
  fe/fe-core/src/main/java/org/apache/doris/analysis/NativeInsertStmt.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/InsertIntoTableCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/OlapGroupCommitInsertExecutor.java
  regression-test/suites/fault_injection_p0/test_group_commit_async_wal_msg_fault_injection.groovy
  regression-test/suites/insert_p0/insert_group_commit_into.groovy
Labels: approved, reviewed

#38524 [chore](bdbtool) Skip read checksum and log escaped value
  fe/fe-core/src/main/java/org/apache/doris/journal/bdbje/BDBTool.java
Labels: approved, reviewed

#38431 [fix](bloom filter)Fix rename column with bloom filter
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  regression-test/suites/bloom_filter_p0/test_bloom_filter_hit_with_renamed_column.groovy
Labels: approved, reviewed, 2.1.0-conflict, dev/2.1.x, doing

#38025 [Feat](nereids)Support date_trunc function in partition prune
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/ColumnRange.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/OneRangePartitionEvaluator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/PartitionSlotInput.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/Monotonic.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/DateTrunc.java
  regression-test/suites/nereids_rules_p0/partition_prune/test_date_trunc_prune.groovy
Labels: approved, reviewed

#38617 [Bug](fix) fix ubsan use int32_t pointer access bool value
  be/src/exprs/runtime_filter.cpp
  regression-test/data/query_p0/join/test_runtime_filter_boolean.out
  regression-test/suites/query_p0/join/test_runtime_filter_boolean.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x

#38443 [improvement](test)Use show_nested_index_file to check inverted index
  regression-test/plugins/plugin_curl_requester.groovy
  regression-test/suites/inverted_index_p0/index_format_v2/test_add_build_index_with_format_v2.groovy
  regression-test/suites/inverted_index_p0/index_format_v2/test_create_table_with_format_v2.groovy
  regression-test/suites/inverted_index_p0/index_format_v2/test_cumulative_compaction_with_format_v2.groovy
  regression-test/suites/inverted_index_p0/index_format_v2/test_drop_column_with_format_v2.groovy
  regression-test/suites/inverted_index_p0/index_format_v2/test_drop_index_with_format_v2.groovy
  regression-test/suites/inverted_index_p0/index_format_v2/test_mor_table_with_format_v2.groovy
  regression-test/suites/inverted_index_p0/index_format_v2/test_mow_table_with_format_v2.groovy
  regression-test/suites/inverted_index_p0/index_format_v2/test_recover_with_format_v2.groovy
  regression-test/suites/inverted_index_p0/index_format_v2/test_rename_column_with_format_v2.groovy
  regression-test/suites/inverted_index_p0/index_format_v2/test_single_replica_compaction_with_format_v2.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x, doing

#38648 [Fix](regression-test) fix wrong variable name in test_index_compaction_with_multi_index_segments #38182
  regression-test/suites/inverted_index_p0/index_compaction/test_index_compaction_with_multi_index_segments.groovy
Labels: kind/test

#38649 [Regression](inverted index) fix build index case for wrong debug point #38112
  regression-test/suites/fault_injection_p0/test_index_builder_drop_index_fault_injection.groovy
Labels: kind/test

#37653 [branch-2.0](timezone) make TimeUtils formatter use correct time_zone (#37465)
  fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupHandler.java
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupJob.java
  fe/fe-core/src/main/java/org/apache/doris/backup/Repository.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/DynamicPartitionUtil.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/TimeUtils.java
  fe/fe-core/src/main/java/org/apache/doris/external/iceberg/IcebergTableCreationRecordMgr.java
  fe/fe-core/src/main/java/org/apache/doris/load/StreamLoadRecordMgr.java
  fe/fe-core/src/main/java/org/apache/doris/load/sync/canal/CanalUtils.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVJobFactory.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/FoldConstantRuleOnBE.java
  fe/fe-core/src/main/java/org/apache/doris/planner/StreamLoadPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/policy/StoragePolicy.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/FoldConstantsRule.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/AdminCancelRebalanceDiskStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/AdminRebalanceDiskStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/AlterCatalogNameStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/AlterCatalogPropsStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/AlterSqlBlockRuleStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/BackupTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/CreateCatalogStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/CreateDbStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/CreateRoutineLoadStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/CreateSqlBlockRuleStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/CreateTableStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/DeleteStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/DropCatalogStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/DropDbStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/DropTableStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/DropUserStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/GrantStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/LoadStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/SetOperationStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/SetPassVarTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/SetStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/SetUserPropertyStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/SetVarTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ShowDataTypesStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ShowDbIdStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ShowEncryptKeysStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ShowFunctionsStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ShowIndexStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ShowPartitionIdStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ShowTableCreationStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ShowTableIdStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ShowTableStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ShowUserPropertyStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/UseStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/common/util/TimeUtilsTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/routineload/KafkaRoutineLoadJobTest.java
  fe/fe-core/src/test/java/org/apache/doris/mysql/privilege/MockedAuth.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/jobs/cascades/DeriveStatsJobTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/stats/StatsCalculatorTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/RuntimeFilterGeneratorTest.java
  fe/fe-core/src/test/java/org/apache/doris/qe/StmtExecutorTest.java
Labels: area/load, area/planner, area/nereids

#38384 [fix](array-func)fix func array_enumerate_uniq with param is nullable return
  be/src/vec/functions/array/function_array_enumerate.cpp
  be/src/vec/functions/array/function_array_enumerate_uniq.cpp
  regression-test/suites/datatype_p0/nested_types/query/array_functions/test_array_zip_array_enumerate_uniq.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x, doing

#38650 [Fix](inverted index) fix fast execute for not_in expr #37745
  be/src/vec/exprs/vexpr.cpp
  be/src/vec/functions/function.h
  regression-test/data/inverted_index_p0/test_index_rqg_bug3.out
  regression-test/suites/inverted_index_p0/test_index_rqg_bug3.groovy
Labels: kind/test

#38651 [Fix](inverted index) fix wrong no need read data when same column in inverted index and like function #36687
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  regression-test/data/inverted_index_p0/test_need_read_data.out
  regression-test/suites/inverted_index_p0/test_need_read_data.groovy
Labels: kind/test

#38487 [opt](merge-on-write) Skip the alignment process of some rowsets in partial update
  be/src/olap/base_tablet.cpp
  be/src/olap/partial_update_info.h
  be/src/olap/rowset/rowset.h
  be/src/olap/rowset/rowset_meta.h
  be/src/olap/rowset_builder.cpp
  be/src/olap/rowset_builder.h
  be/src/olap/task/engine_publish_version_task.cpp
  fe/fe-core/src/main/java/org/apache/doris/cloud/transaction/CloudGlobalTransactionMgr.java
  regression-test/data/fault_injection_p0/partial_update/concurrency_update1.csv
  regression-test/data/fault_injection_p0/partial_update/concurrency_update2.csv
  regression-test/data/fault_injection_p0/partial_update/concurrency_update3.csv
  regression-test/data/fault_injection_p0/partial_update/test_partial_update_column_num_fault_injection.out
  regression-test/data/fault_injection_p0/partial_update/test_partial_update_compaction_with_higher_version.out
  regression-test/data/fault_injection_p0/partial_update/test_partial_update_conflict_skip_compaction.out
  regression-test/data/fault_injection_p0/partial_update/test_partial_update_publish_conflict_with_error.out
  regression-test/data/fault_injection_p0/partial_update/test_partial_update_skip_compaction.out
  regression-test/suites/fault_injection_p0/partial_update/test_partial_update_column_num_fault_injection.groovy
  regression-test/suites/fault_injection_p0/partial_update/test_partial_update_compaction_with_higher_version.groovy
  regression-test/suites/fault_injection_p0/partial_update/test_partial_update_conflict_skip_compaction.groovy
  regression-test/suites/fault_injection_p0/partial_update/test_partial_update_publish_conflict_with_error.groovy
  regression-test/suites/fault_injection_p0/partial_update/test_partial_update_skip_compaction.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x

#36867 [cherry-pick](function) add date_floor/ceil function
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java
  gensrc/script/doris_builtins_functions.py
  regression-test/data/query_p0/sql_functions/datetime_functions/test_date_floor_ceil.out
  regression-test/suites/query_p0/sql_functions/datetime_functions/test_date_floor_ceil.groovy
Labels: area/planner, kind/test, usercase

#38466 [fix](type)support runtime predicate for time type (#38258)
  be/src/exec/olap_common.h
  be/src/runtime/runtime_predicate.cpp
  be/src/vec/runtime/time_value.h
  regression-test/data/datatype_p0/time_type/test_time_in_runtimepredicate.out
  regression-test/suites/datatype_p0/time_type/test_time_in_runtimepredicate.groovy
Labels: kind/test

#32344 [minor](fe) simplfy some code in HMSExternalTable
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HMSExternalTable.java
Labels: approved, reviewed, dev/2.1.x

#38619 [fix](multicatalog) fix metacache is null issue when show_dbs
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalCatalog.java
Labels: approved, reviewed

#38679 [Chore](GH)Setting CK as the code owner for pom.xml.
  .github/CODEOWNERS
Labels: approved, reviewed

#38439 [improvement](jdbc catalog) improvement some jdbc catalog properties check order
  fe/fe-core/src/main/java/org/apache/doris/datasource/CatalogFactory.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/CatalogProperty.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/JdbcExternalCatalog.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/jdbc/JdbcExternalCatalogTest.java
Labels: approved, reviewed, dev/2.1.x

#38663 [fix](regression)Set enable_partition_analyze session back to false in finally block.
  regression-test/suites/nereids_p0/stats/partition_col_stats.groovy
Labels: approved, reviewed, doing

#38556 [opt](join) check datatype of intermediate slots in hash join
  be/src/pipeline/exec/hashjoin_probe_operator.cpp
Labels: approved, reviewed, dev/2.1.x

#38369 [fix](merge-on-write) segcompaction should process delete bitmap if necessary
  be/src/olap/merger.cpp
  be/src/olap/merger.h
  be/src/olap/rowset/beta_rowset_writer.cpp
  be/src/olap/rowset/beta_rowset_writer.h
  be/src/olap/rowset/segcompaction.cpp
  be/src/olap/rowset/segcompaction.h
  be/src/olap/simple_rowid_conversion.h
  be/src/vec/olap/vertical_block_reader.cpp
  be/test/common/status_test.cpp
  be/test/olap/segcompaction_mow_test.cpp
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x

#38671 [2.0](dependencies)upgrade dependencies
  fe/pom.xml
Labels: approved, reviewed

#38561 Revert "[feat](Nereids): Optimize Query Plan by Pulling Up Join with Common Child from Union (#36397)"
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/Rewriter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PullUpJoinFromUnion.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/PullUpJoinFromUnionTest.java
  regression-test/data/nereids_hint_tpcds_p0/shape/query14.out
  regression-test/data/nereids_hint_tpcds_p0/shape/query71.out
  regression-test/data/nereids_hint_tpcds_p0/shape/query76.out
  regression-test/data/nereids_rules_p0/join_pull_up_union/join_pull_up_union.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/shape/query14.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/shape/query71.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/shape/query76.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/noStatsRfPrune/query14.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/noStatsRfPrune/query71.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/noStatsRfPrune/query76.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/no_stats_shape/query14.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/no_stats_shape/query71.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/no_stats_shape/query76.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/rf_prune/query14.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/rf_prune/query71.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/rf_prune/query76.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query14.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query71.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query76.out
  regression-test/data/new_shapes_p0/tpcds_sf100/noStatsRfPrune/query14.out
  regression-test/data/new_shapes_p0/tpcds_sf100/noStatsRfPrune/query71.out
  regression-test/data/new_shapes_p0/tpcds_sf100/noStatsRfPrune/query76.out
  regression-test/data/new_shapes_p0/tpcds_sf100/no_stats_shape/query14.out
  regression-test/data/new_shapes_p0/tpcds_sf100/no_stats_shape/query71.out
  regression-test/data/new_shapes_p0/tpcds_sf100/no_stats_shape/query76.out
  regression-test/data/new_shapes_p0/tpcds_sf100/rf_prune/query14.out
  regression-test/data/new_shapes_p0/tpcds_sf100/rf_prune/query71.out
  regression-test/data/new_shapes_p0/tpcds_sf100/rf_prune/query76.out
  regression-test/data/new_shapes_p0/tpcds_sf100/shape/query14.out
  regression-test/data/new_shapes_p0/tpcds_sf100/shape/query71.out
  regression-test/data/new_shapes_p0/tpcds_sf100/shape/query76.out
  regression-test/data/new_shapes_p0/tpcds_sf1000/shape/query14.out
  regression-test/data/new_shapes_p0/tpcds_sf1000/shape/query71.out
  regression-test/data/new_shapes_p0/tpcds_sf1000/shape/query76.out
  regression-test/suites/nereids_rules_p0/join_pull_up_union/join_pull_up_union.groovy
Labels: approved, reviewed, not-merge/2.1, dev/3.0.x, doing

#38653 [bugfix](asan core) should use weak ptr in rpc context to release rf context during query context deconstructed
  be/src/exprs/runtime_filter.cpp
Labels: approved, reviewed, doing

#38657 [fix](local exchange) Fix local exchange blocked by a huge data block
  be/src/pipeline/local_exchange/local_exchange_sink_operator.h
  be/src/pipeline/local_exchange/local_exchange_source_operator.cpp
  be/src/pipeline/local_exchange/local_exchange_source_operator.h
  be/src/pipeline/local_exchange/local_exchanger.cpp
  be/src/pipeline/local_exchange/local_exchanger.h
Labels: approved, reviewed, not-merge/2.0, p0_b, dev/2.1.x, doing

#38674 [improvement](statisitcs)Disable external catalog auto analyze by default.
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/util/StatisticsUtil.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/util/StatisticsUtilTest.java
Labels: approved, reviewed

#38661 [fix](case) fix jsonb-load output
  regression-test/data/nereids_p0/jsonb_p0/test_jsonb_load_and_function.out
Labels: approved, reviewed, dev/3.0.x, doing

#38629 [fix](jsonb)fix jsonb deserialze
  be/src/vec/functions/function_cast.h
  regression-test/data/jsonb_p0/test_jsonb_unescaped.csv
  regression-test/data/jsonb_p0/test_jsonb_unescaped.json
  regression-test/data/jsonb_p0/test_jsonb_with_unescaped_string.out
  regression-test/suites/jsonb_p0/test_jsonb_with_unescaped_string.groovy
Labels: kind/test

#38660 [fix](Nereids) remove db readlock before get table from db
  fe/fe-core/src/main/java/org/apache/doris/nereids/CascadesContext.java
Labels: approved, reviewed, usercase, p0_b, dev/2.0.x, dev/2.1.x

#38727 [fix](inverted index) Incorrect handling of NULL literal
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  regression-test/data/fault_injection_p0/test_index_inlist_fault_injection.out
  regression-test/suites/fault_injection_p0/test_index_inlist_fault_injection.groovy
Labels: kind/test

#38730 [fix](Nereids) remove db readlock before get table from db (#38660)
  fe/fe-core/src/main/java/org/apache/doris/nereids/CascadesContext.java
Labels: area/nereids

#38705 [Improve](Prepared Statment) optimize hint for prepared statement
  fe/fe-core/src/main/java/org/apache/doris/analysis/PrepareStmt.java
Labels: area/planner

#38493 [Improvement](expr) fold child when const expr not folded
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/FoldConstantRuleOnBE.java
  regression-test/data/nereids_p0/expression/fold_constant/fold_constant_by_be.out
  regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_by_be.groovy
  regression-test/suites/query_p0/aggregate/select_random_distributed_tbl.groovy
Labels: approved, reviewed

#38722 [fix](inverted index) disable range query in StringTypeInvertedIndexReader (#38218)
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  regression-test/data/inverted_index_p0/test_ignore_above_in_index.out
  regression-test/suites/inverted_index_p0/test_ignore_above_in_index.groovy
Labels: kind/test, doing

#38620 [Bug](fix) fix ubsan use int32_t pointer access bool value
  be/src/exprs/runtime_filter.cpp
  regression-test/data/query_p0/join/test_runtime_filter_boolean.out
  regression-test/suites/query_p0/join/test_runtime_filter_boolean.groovy
Labels: kind/test

#38712 [fix](array_range) fix array_range func for large param which should return error #38284
  be/src/vec/functions/array/function_array_range.cpp
  regression-test/suites/query_p0/sql_functions/array_functions/test_array_functions.groovy
Labels: kind/test

#38485 [fix](recycler) Fix recycler compilation issue with libhdfs3
  cloud/src/recycler/hdfs_accessor.cpp
  cloud/src/recycler/hdfs_accessor.h
Labels: approved, reviewed, dev/3.0.x

#38438 [opt](memory) Optimize `ClearCacheAction`implementation
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/common/daemon.cpp
  be/src/common/daemon.h
  be/src/http/action/clear_cache_action.cpp
  be/src/http/action/clear_cache_action.h
  be/src/olap/olap_server.cpp
  be/src/olap/storage_engine.h
  be/src/runtime/memory/cache_manager.cpp
  be/src/runtime/memory/cache_manager.h
  be/src/runtime/memory/cache_policy.h
  be/src/runtime/memory/memory_reclamation.cpp
  be/src/runtime/memory/thread_mem_tracker_mgr.h
  be/src/service/http_service.cpp
  be/src/vec/common/allocator.cpp
Labels: approved, reviewed

#38623 [feature] (expr) support expression IS [NOT] TURE/FALSE
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/expressions/ExpressionParserTest.java
  regression-test/data/nereids_syntax_p0/sql/test_compare_expression.out
  regression-test/suites/nereids_syntax_p0/sql/test_compare_expression.sql
Labels: approved, reviewed

#38670 [fix](syntax) multi statements must delim with semicolon
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/test/java/org/apache/doris/nereids/parser/NereidsParserTest.java
  regression-test/suites/insert_p0/insert.groovy
Labels: approved, reviewed, usercase, dev/2.0.x, dev/2.1.x

#38717 [enhancement](tools) make benchmark scripts better use
  regression-test/pipeline/common/github-utils.sh
  tools/clickbench-tools/load-clickbench-data.sh
  tools/clickbench-tools/run-clickbench-queries.sh
  tools/ssb-tools/bin/load-ssb-data.sh
  tools/tpcds-tools/ddl/create-tpcds-tables-sf100.sql
  tools/tpcds-tools/ddl/create-tpcds-tables-sf1000.sql
  tools/tpcds-tools/ddl/create-tpcds-tables-sf10000.sql
Labels: approved, reviewed, doing

#38737 [Bug](fix) fix coredump case in (not null, null) execpt (not null, t null) case
  be/src/pipeline/dependency.h
  be/src/pipeline/exec/set_sink_operator.cpp
  regression-test/data/query_p0/except/test_query_except.out
  regression-test/suites/query_p0/except/test_query_except.groovy
Labels: approved, reviewed, dev/2.1.x, doing

#38612 [bug](expr)fix operator do_projections should use local_state intermediate_projections
  be/src/pipeline/exec/operator.cpp
  regression-test/data/javaudf_p0/test_javaudf_string.out
  regression-test/suites/javaudf_p0/test_javaudf_string.groovy
Labels: approved, reviewed, usercase, p0_c, dev/2.1.x, dev/3.0.x, doing

#38736 [fix](test)Fix build index fault test
  regression-test/suites/fault_injection_p0/test_build_index_fault.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x, doing

#38732 [fix](index compaction)Remove return error in merged rows check
  be/src/olap/compaction.cpp
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x, doing

#38733 [fix](test)Make index change with cu compaction nonconcurrent
  regression-test/suites/inverted_index_p0/index_change/test_index_change_with_cumulative_compaction.groovy
Labels: approved, reviewed, dev/3.0.x, doing

#38698 [fix](mtmv)fix second level MTMV will refresh all partition
  fe/fe-core/src/main/java/org/apache/doris/job/extensions/mtmv/MTMVTask.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVPartitionUtil.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVRewriteUtil.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVUtil.java
  fe/fe-core/src/test/java/org/apache/doris/mtmv/MTMVPartitionUtilTest.java
  regression-test/data/mtmv_p0/test_multi_level_mtmv.out
  regression-test/suites/mtmv_p0/test_multi_level_mtmv.groovy
Labels: approved, reviewed, p0_b, dev/2.1.x

#38744 [Feature](function) support group concat with distinct and order by
  be/src/vec/aggregate_functions/aggregate_function.h
  be/src/vec/aggregate_functions/aggregate_function_distinct.cpp
  be/src/vec/aggregate_functions/aggregate_function_distinct.h
  be/src/vec/aggregate_functions/aggregate_function_foreach.h
  be/src/vec/aggregate_functions/aggregate_function_null.h
  be/src/vec/aggregate_functions/aggregate_function_simple_factory.cpp
  be/src/vec/aggregate_functions/aggregate_function_sort.h
Labels: approved, reviewed, usercase, dev/2.1.x, doing

#38687 [fix](test) fix `test_numbers` case
  regression-test/data/external_table_p0/tvf/test_numbers.out
  regression-test/suites/external_table_p0/tvf/test_numbers.groovy
Labels: approved, reviewed, doing

#38245 [fix](serde)fix the bug in DataTypeNullableSerDe.deserialize_column_from_fixed_json
  be/src/vec/data_types/serde/data_type_nullable_serde.cpp
  docker/thirdparties/docker-compose/hive/scripts/create_preinstalled_scripts/run65.hql
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/orc_table/orc_partition_multi_stripe/partition_col1=hello/partition_col2=1/000000_0_copy_10
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/orc_table/orc_partition_multi_stripe/partition_col1=hello/partition_col2=1/000000_0_copy_11
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/orc_table/orc_partition_multi_stripe/partition_col1=hello/partition_col2=1/000000_0_copy_12
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/orc_table/orc_partition_multi_stripe/partition_col1=hello/partition_col2=1/000000_0_copy_13
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/parquet_table/parquet_partition_multi_row_group/partition_col1=hello/partition_col2=1/000000_0_copy_10
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/parquet_table/parquet_partition_multi_row_group/partition_col1=hello/partition_col2=1/000000_0_copy_11
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/parquet_table/parquet_partition_multi_row_group/partition_col1=hello/partition_col2=1/000000_0_copy_9
  regression-test/data/external_table_p0/hive/test_hive_opt_fill_partition.out
  regression-test/suites/external_table_p0/hive/test_hive_opt_fill_partition.groovy
Labels: approved, reviewed, dev/2.1.x

#38432 [feature](hive)Support reading renamed Parquet Hive and Orc Hive tables.
  be/src/vec/exec/format/orc/vorc_reader.cpp
  be/src/vec/exec/format/orc/vorc_reader.h
  be/src/vec/exec/format/parquet/vparquet_reader.cpp
  be/src/vec/exec/format/parquet/vparquet_reader.h
  be/src/vec/exec/scan/vfile_scanner.cpp
  docker/thirdparties/docker-compose/hive/scripts/create_preinstalled_scripts/run64.hql
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/orc_table/simulation_hive1_orc/000000_0
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/orc_table/test_hive_rename_column_orc/000000_0
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/orc_table/test_hive_rename_column_orc/000000_0_copy_1
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/orc_table/test_hive_rename_column_orc/000000_0_copy_2
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/orc_table/test_hive_rename_column_orc/000000_0_copy_3
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/parquet_table/test_hive_rename_column_parquet/000000_0
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/parquet_table/test_hive_rename_column_parquet/000000_0_copy_1
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/parquet_table/test_hive_rename_column_parquet/000000_0_copy_2
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/parquet_table/test_hive_rename_column_parquet/000000_0_copy_3
  fe/fe-core/src/main/java/org/apache/doris/datasource/FileQueryScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  gensrc/thrift/PaloInternalService.thrift
  regression-test/data/external_table_p0/hive/test_hive_rename_column_orc_parquet.out
  regression-test/suites/external_table_p0/hive/test_hive_rename_column_orc_parquet.groovy
Labels: approved, reviewed, meta-change, dev/2.1.x

#38647 [regression](kerberos)add hive with kerberos write back case
  regression-test/data/external_table_p0/kerberos/test_two_hive_kerberos.out
  regression-test/suites/external_table_p0/kerberos/test_two_hive_kerberos.groovy
Labels: approved, reviewed, dev/2.1.x, doing

#38566 [bugfix](iceberg)revert count(*) directly returned by fe
  fe/fe-core/src/main/java/org/apache/doris/datasource/FileScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/source/IcebergScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/NereidsPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OriginalPlanner.java
Labels: approved, reviewed, dev/2.1.6-merged

#37293 (cloud-merge) Support shadow tablet to do cumulative compaction in cloud mode
  be/src/cloud/cloud_base_compaction.cpp
  be/src/cloud/cloud_cumulative_compaction.cpp
  be/src/cloud/cloud_engine_calc_delete_bitmap_task.cpp
  be/src/cloud/cloud_meta_mgr.cpp
  be/src/cloud/cloud_schema_change_job.cpp
  be/src/cloud/cloud_schema_change_job.h
  be/src/cloud/cloud_storage_engine.cpp
  be/src/cloud/cloud_tablet.cpp
  be/src/cloud/cloud_tablet.h
  be/src/cloud/config.cpp
  be/src/cloud/config.h
  be/src/olap/base_tablet.cpp
  cloud/src/meta-service/meta_service_job.cpp
  cloud/test/meta_service_job_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/alter/CloudRollupJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/alter/CloudSchemaChangeJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/alter/RollupJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/datasource/CloudInternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/rpc/MetaServiceClient.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/rpc/MetaServiceProxy.java
  gensrc/proto/cloud.proto
  regression-test/pipeline/cloud_p0/conf/be_custom.conf
  regression-test/plugins/plugin_curl_requester.groovy
  regression-test/suites/cloud_p0/schema_change/compaction1/test_schema_change_with_compaction1.groovy
  regression-test/suites/cloud_p0/schema_change/compaction10/test_schema_change_with_compaction10.groovy
  regression-test/suites/cloud_p0/schema_change/compaction11/test_schema_change_with_compaction11.groovy
  regression-test/suites/cloud_p0/schema_change/compaction2/test_schema_change_with_compaction2.groovy
  regression-test/suites/cloud_p0/schema_change/compaction3/test_schema_change_with_compaction3.groovy
  regression-test/suites/cloud_p0/schema_change/compaction4/test_schema_change_with_compaction4.groovy
  regression-test/suites/cloud_p0/schema_change/compaction5/test_schema_change_with_compaction5.groovy
  regression-test/suites/cloud_p0/schema_change/compaction6/test_schema_change_with_compaction6.groovy
  regression-test/suites/cloud_p0/schema_change/compaction7/test_schema_change_with_compaction7.groovy
  regression-test/suites/cloud_p0/schema_change/compaction8/test_schema_change_with_compaction8.groovy
  regression-test/suites/cloud_p0/schema_change/compaction9/test_schema_change_with_compaction9.groovy
  regression-test/suites/cloud_p0/schema_change/ddl/date_create.sql
  regression-test/suites/cloud_p0/schema_change/ddl/date_delete.sql
  regression-test/suites/cloud_p0/schema_change/ddl/date_load.sql
  regression-test/suites/cloud_p0/schema_change/ddl/date_unique_create.sql
Labels: approved, reviewed, meta-change, doing

#38752 [fix](syntax) multi statements must delim with semicolon (#38670)
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/test/java/org/apache/doris/nereids/parser/NereidsParserTest.java
Labels: area/nereids

#38665 [chore](test) disable fault injection to make pipeline task check happy
  regression-test/pipeline/cloud_p0/conf/regression-conf-custom.groovy
  regression-test/pipeline/p0/conf/regression-conf.groovy
Labels: approved, reviewed, dev/2.1.x, doing

#38605 [fix](load) fix miss writer in concurrency incremental open
  be/src/cloud/cloud_tablets_channel.cpp
  be/src/runtime/tablets_channel.cpp
  be/src/runtime/tablets_channel.h
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#34529 [fix](session) fix select * from variables system table
  be/src/exec/schema_scanner/schema_variables_scanner.cpp
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  gensrc/thrift/FrontendService.thrift
  regression-test/data/variable_p0/set_and_unset_variable.out
  regression-test/suites/variable_p0/set_and_unset_variable.groovy
Labels: approved, reviewed, meta-change, dev/2.0.x, dev/2.1.x, dev/3.0.x

#38748 [fix](test) fix routine load case unstable
  regression-test/suites/load_p0/routine_load/test_routine_load_offset.groovy
Labels: approved, reviewed, doing

#36850 [BugFix](VScanner) fix file scanner is still running when the query is timeout/killed
  be/src/vec/exec/scan/vfile_scanner.cpp
Labels: approved, reviewed

#38773 [fix](test)Fix unstable test drop index fault #38768
  regression-test/suites/fault_injection_p0/test_index_builder_drop_index_fault_injection.groovy
Labels: kind/test

#38758 [opt](test) add header check test case
  regression-test/suites/mysql_compatibility_p0/header.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, doing

#38783 [Fix](Load)Audit logs avoid recording certain sensitive information #38769
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateCatalogStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateResourceStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/LoadStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/StorageBackend.java
Labels: area/planner, approved, reviewed

#38615 [improvement](statistics)Analyze table if it hasn't been analyzed for longer than 1 day.
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/util/StatisticsUtil.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/util/StatisticsUtilTest.java
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, doing

#38697 [opt](variables) enlarge the default value of max_allowed_packet
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
Labels: approved, reviewed, kind/behavior-changed, dev/2.1.x, doing

#38720 [fix](array-func)fix func array_enumerate_uniq with param is nullable return #38384
  be/src/vec/functions/array/function_array_enumerate.cpp
  be/src/vec/functions/array/function_array_enumerate_uniq.cpp
  regression-test/suites/query_p0/sql_functions/array_functions/test_array_functions.groovy
Labels: kind/test

#38763 [fix](test)Fix build index fault test (#38736)
  regression-test/suites/fault_injection_p0/test_build_index_fault.groovy
Labels: kind/test

#38782 [fix](recycler) Fix uninitialized num_entries when list a non-exist directory
  cloud/src/recycler/hdfs_accessor.cpp
  cloud/test/hdfs_accessor_test.cpp
Labels: reviewed, dev/3.0.x, doing

#38754 [fix](group commit) Fix group commit debug log and improve performance
  fe/fe-core/src/main/java/org/apache/doris/analysis/NativeInsertStmt.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/OlapGroupCommitInsertExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  regression-test/suites/insert_p0/txn_insert_concurrent_insert.groovy
Labels: approved, reviewed, dev/2.1.x, doing

#38778 [fix](nereids) fix The children format needs to be [WhenClause+, DefaultValue?] (#38491)
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/DefaultExpressionRewriter.java
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
  regression-test/suites/nereids_syntax_p0/join.groovy
Labels: kind/test, area/nereids

#38634 [COMPILE](macos) do not patch bitshuffle on macos
  be/src/olap/rowset/segment_v2/bitshuffle_wrapper.cpp
  thirdparty/build-thirdparty.sh
  thirdparty/download-thirdparty.sh
Labels: approved, reviewed, doing

#38768 [fix](test)Fix unstable test drop index fault
  regression-test/suites/fault_injection_p0/test_index_builder_drop_index_fault_injection.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x, doing, dev/2.0.14-merged

#38774 [improvement](log)Add log for load report update rows.
  be/src/olap/task/engine_publish_version_task.cpp
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisManager.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/PublishVersionDaemon.java
Labels: approved, reviewed, doing

#38760 [Bug](fix) fix coredump case in (not null, null) execpt (not null, not null) case
  be/src/vec/exec/vset_operation_node.cpp
  regression-test/data/query_p0/except/test_query_except.out
  regression-test/suites/query_p0/except/test_query_except.groovy
Labels: kind/test

#38699 [cases](array-functions)align function with master
  regression-test/data/datatype_p0/nested_types/query/array_functions/test_array_element_at_and_slice.out
  regression-test/data/datatype_p0/nested_types/query/array_functions/test_array_functions_array_intersect_sort.out
  regression-test/data/datatype_p0/nested_types/query/array_functions/test_array_functions_array_join.out
  regression-test/data/datatype_p0/nested_types/query/array_functions/test_array_functions_array_with_const.out
  regression-test/data/datatype_p0/nested_types/query/array_functions/test_array_functions_concat_compact_difference.out
  regression-test/data/datatype_p0/nested_types/query/array_functions/test_array_functions_in_ck_case.out
  regression-test/data/datatype_p0/nested_types/query/array_functions/test_array_push_pop_backfront.out
  regression-test/data/datatype_p0/nested_types/query/array_functions/test_array_zip_array_enumerate_uniq.out
  regression-test/data/query_p0/sql_functions/array_functions/test_array_functions_of_array_countEqual.out
  regression-test/data/query_p0/sql_functions/array_functions/test_array_functions_of_array_difference.out
  regression-test/suites/datatype_p0/nested_types/query/array_functions/load.groovy
  regression-test/suites/datatype_p0/nested_types/query/array_functions/test_array_element_at_and_slice.groovy
  regression-test/suites/datatype_p0/nested_types/query/array_functions/test_array_functions_array_intersect_sort.groovy
  regression-test/suites/datatype_p0/nested_types/query/array_functions/test_array_functions_array_join.groovy
  regression-test/suites/datatype_p0/nested_types/query/array_functions/test_array_functions_array_with_const.groovy
  regression-test/suites/datatype_p0/nested_types/query/array_functions/test_array_functions_concat_compact_difference.groovy
  regression-test/suites/datatype_p0/nested_types/query/array_functions/test_array_push_pop_backfront.groovy
  regression-test/suites/datatype_p0/nested_types/query/array_functions/test_array_zip_array_enumerate_uniq.groovy
  regression-test/suites/query_p0/sql_functions/array_functions/test_array_functions_of_array_countEqual.groovy
  regression-test/suites/query_p0/sql_functions/array_functions/test_array_functions_of_array_difference.groovy
Labels: kind/test

#38569 [fix](auth)fix create table like need create_priv of existed table #37879 #25711
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/AccessControllerManager.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContext.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  regression-test/suites/nereids_p0/insert_into_table/insert_auth.groovy
Labels: kind/test

#38800 [fix](segcompaction) fix convert delete bitmap core
  be/src/olap/rowset/segcompaction.cpp
  be/test/olap/segcompaction_mow_test.cpp
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, doing

#38776 [Bug](function) use emplace to replace insert_or_assign on stable distinct
  be/src/vec/aggregate_functions/aggregate_function_distinct.h
Labels: approved, reviewed, doing

#38815 [fix](case) fix testcase out file upper case
  regression-test/data/schema_change_p0/schema_change_modify_mv_column_type.out
  regression-test/suites/datatype_p0/time_type/test_time_in_runtimepredicate.groovy
  regression-test/suites/inverted_index_p2/test_array_with_large_dataset.groovy
  regression-test/suites/tpch_sf0.1_p1/function/test_not_supported_agg_fn.groovy
Labels: kind/test

#38668 [Improvement](mow) Make calculate delete bitmap timeout configurable
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/transaction/CloudGlobalTransactionMgr.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
Labels: approved, reviewed, usercase, dev/3.0.x, doing

#38761 [Enhancement](merge-on-write) Support dynamic delete bitmap txn_delete_bitmap_cache
  be/src/cloud/cloud_storage_engine.cpp
Labels: approved, reviewed, p0_l, doing

#38585 [log](s3) print detailed error message when failed to access object storage
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateStageStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/LoadStmt.java
  fe/fe-core/src/main/java/org/apache/doris/common/UserException.java
  regression-test/suites/load_p0/broker_load/test_domain_connection_and_ak_sk_correction.groovy
Labels: approved, reviewed, doing

#38798 [fix](regression) fix test_primary_key_simple_case
  regression-test/suites/unique_with_mow_c_p0/test_primary_key_simple_case.groovy
  regression-test/suites/unique_with_mow_p0/test_primary_key_simple_case.groovy
Labels: approved, reviewed, dev/2.1.x, doing

#38777 [fix](txn) fix abortTxn by label does not acquire table write lock
  fe/fe-core/src/main/java/org/apache/doris/transaction/GlobalTransactionMgr.java
Labels: approved, reviewed, p0_b, dev/2.1.x, doing

#38799 [fix](gson) Fix Expr deserialize compatibility
  fe/fe-core/src/main/java/org/apache/doris/persist/gson/GsonUtils.java
  fe/fe-core/src/main/java/org/apache/doris/persist/gson/GsonUtils134.java
  fe/fe-core/src/test/java/org/apache/doris/persist/ExprTest.java
Labels: approved, reviewed, p0_b, dev/3.0.x, doing

#38688 [fix](fe) Fix the default value of ReplacePartitionClause.isStrictRange
  fe/fe-core/src/main/java/org/apache/doris/analysis/ReplacePartitionClause.java
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, doing

#38780 [enhancement](compaction) reduce the base compaction freeze interval
  be/src/cloud/config.cpp
Labels: approved, reviewed, usercase, p0_l, dev/3.0.x, doing

#38742 [fix](compaction) disable cumu delete rowset from performing ordered data compaction
  be/src/olap/compaction.cpp
Labels: approved, reviewed, not-merge/2.1, doing

#38728 [fix](compaction) fix the longest continuous rowsets cannot be selected when missing rowsets
  be/src/olap/cumulative_compaction.cpp
  be/src/olap/cumulative_compaction.h
  be/test/olap/cumulative_compaction_test.cpp
Labels: approved, reviewed, dev/2.1.x, doing

#38790 [Fix](load) The value of the index id printed in the log is incorrect
  be/src/runtime/tablets_channel.cpp
Labels: approved, reviewed, dev/2.1.x, doing

#38695 [fix](clone) fix stale tablet report miss the new cloning replica
  be/src/agent/task_worker_pool.cpp
  be/src/olap/task/engine_clone_task.cpp
  be/src/olap/task/engine_clone_task.h
  fe/fe-core/src/main/java/org/apache/doris/master/MasterImpl.java
Labels: reviewed, dev/2.1.x, doing

#38784 [Fix](Load)Audit logs avoid recording certain sensitive information #38769
  fe/fe-core/src/main/java/org/apache/doris/analysis/LoadStmt.java
Labels: usercase

#38555 [case](mtmv)some features are not yet supported on the cloud
  regression-test/suites/mtmv_p0/test_set_partition_version_mtmv.groovy
  regression-test/suites/mtmv_p0/test_storage_medium_mtmv.groovy
Labels: approved, reviewed, dev/3.0.x

#38553 [case](mtmv)wait task finish before select
  regression-test/suites/auth_p0/test_select_column_auth.groovy
Labels: approved, reviewed

#38205 [fix](auth)Fix some exception info of the auth case
  regression-test/suites/auth_p0/test_master_slave_consistency_auth.groovy
  regression-test/suites/auth_p0/test_select_column_auth.groovy
Labels: approved, reviewed

#38769 [Fix](Load)Audit logs avoid recording certain sensitive information
  fe/fe-core/src/main/java/org/apache/doris/analysis/LoadStmt.java
Labels: approved, reviewed, usercase, dev/3.0.x, doing, dev/2.0.14-merged, dev/2.1.6-merged

#38806 [fix](schema-change) Fix schema change run into nullable check specified for MV
  be/src/olap/schema_change.cpp
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeJobV2.java
  regression-test/suites/variant_p0/schema_change/test_column_reorder.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x

#38644 [Fix](group commit) Fix multiple cluster group commit BE select strategy
  fe/fe-core/src/main/java/org/apache/doris/load/GroupCommitManager.java
Labels: approved, reviewed, dev/3.0.x, doing

#38828 [revert](cloud-merge) Support shadow tablet to do cumulative compaction in cloud mode (apache#37293)"
  be/src/cloud/cloud_base_compaction.cpp
  be/src/cloud/cloud_cumulative_compaction.cpp
  be/src/cloud/cloud_engine_calc_delete_bitmap_task.cpp
  be/src/cloud/cloud_meta_mgr.cpp
  be/src/cloud/cloud_schema_change_job.cpp
  be/src/cloud/cloud_schema_change_job.h
  be/src/cloud/cloud_storage_engine.cpp
  be/src/cloud/cloud_tablet.cpp
  be/src/cloud/cloud_tablet.h
  be/src/cloud/config.cpp
  be/src/cloud/config.h
  be/src/olap/base_tablet.cpp
  cloud/src/meta-service/meta_service_job.cpp
  cloud/test/meta_service_job_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/alter/CloudRollupJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/alter/CloudSchemaChangeJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/alter/RollupJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/datasource/CloudInternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/rpc/MetaServiceClient.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/rpc/MetaServiceProxy.java
  fe/fe-core/src/main/java/org/apache/doris/master/MetaHelper.java
  fe/fe-core/src/main/java/org/apache/doris/persist/meta/MetaWriter.java
  gensrc/proto/cloud.proto
  regression-test/pipeline/cloud_p0/conf/be_custom.conf
  regression-test/plugins/plugin_curl_requester.groovy
  regression-test/suites/cloud_p0/schema_change/compaction1/test_schema_change_with_compaction1.groovy
  regression-test/suites/cloud_p0/schema_change/compaction10/test_schema_change_with_compaction10.groovy
  regression-test/suites/cloud_p0/schema_change/compaction11/test_schema_change_with_compaction11.groovy
  regression-test/suites/cloud_p0/schema_change/compaction2/test_schema_change_with_compaction2.groovy
  regression-test/suites/cloud_p0/schema_change/compaction3/test_schema_change_with_compaction3.groovy
  regression-test/suites/cloud_p0/schema_change/compaction4/test_schema_change_with_compaction4.groovy
  regression-test/suites/cloud_p0/schema_change/compaction5/test_schema_change_with_compaction5.groovy
  regression-test/suites/cloud_p0/schema_change/compaction6/test_schema_change_with_compaction6.groovy
  regression-test/suites/cloud_p0/schema_change/compaction7/test_schema_change_with_compaction7.groovy
  regression-test/suites/cloud_p0/schema_change/compaction8/test_schema_change_with_compaction8.groovy
  regression-test/suites/cloud_p0/schema_change/compaction9/test_schema_change_with_compaction9.groovy
  regression-test/suites/cloud_p0/schema_change/ddl/date_create.sql
  regression-test/suites/cloud_p0/schema_change/ddl/date_delete.sql
  regression-test/suites/cloud_p0/schema_change/ddl/date_load.sql
  regression-test/suites/cloud_p0/schema_change/ddl/date_unique_create.sql
Labels: approved, reviewed, meta-change, doing

#38817 [fix] add null check before accessing pointer
  be/src/vec/functions/function_split_by_regexp.cpp
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x, doing

#38789 [Opt](cloud) Using file cache disks number to determine the size of the flush memtable thread pool
  be/src/cloud/cloud_storage_engine.cpp
Labels: approved, reviewed, usercase, dev/3.0.x, doing

#38779 [Fix](Nereids) remove some unstable and not important cases
  regression-test/data/nereids_p0/hint/multi_leading.out
  regression-test/suites/nereids_p0/hint/multi_leading.groovy
  regression-test/suites/nereids_p0/hint/test_distribute.groovy
Labels: approved, reviewed, doing

#38387 [improvement](mtmv) Not roll up when aggregate rewrite if roll up group by expr is uniform
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewAggregateRule.java
  regression-test/data/nereids_rules_p0/mv/agg_optimize_when_uniform/agg_optimize_when_uniform.out
  regression-test/suites/nereids_rules_p0/mv/agg_optimize_when_uniform/agg_optimize_when_uniform.groovy
  regression-test/suites/nereids_rules_p0/mv/agg_with_roll_up/aggregate_with_roll_up.groovy
  regression-test/suites/nereids_rules_p0/mv/agg_without_roll_up/aggregate_without_roll_up.groovy
Labels: approved, reviewed, usercase, dev/2.1.x, doing

#38327 [fix](inverted index) fix match_phrase_edge query result error
  be/src/olap/rowset/segment_v2/inverted_index/query/phrase_edge_query.cpp
  be/src/olap/rowset/segment_v2/inverted_index/query/phrase_edge_query.h
  regression-test/data/inverted_index_p0/test_index_match_phrase_edge.out
  regression-test/suites/inverted_index_p0/test_index_match_phrase_edge.groovy
Labels: approved, reviewed, p0_w, dev/3.0.x, doing, dev/2.1.6-merged

#38220 [fix] (compaction) fix time series compaction policy
  be/src/cloud/cloud_cumulative_compaction_policy.cpp
  be/src/cloud/config.cpp
  be/src/cloud/config.h
  be/src/olap/compaction.cpp
  be/src/olap/cumulative_compaction.cpp
  be/src/olap/tablet.cpp
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, doing, dev/3.0.1-merged

#34258 [Enhancement] (doris-future) Support auto partition name function
  be/src/vec/functions/function_string.cpp
  be/src/vec/functions/function_string.h
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinScalarFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/AutoPartitionName.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/ScalarFunctionVisitor.java
  gensrc/script/doris_builtins_functions.py
  regression-test/data/nereids_function_p0/scalar_function/A.out
  regression-test/suites/nereids_function_p0/scalar_function/A.groovy
Labels: approved, reviewed, meta-change, doing

#38764 [fix](function) Fix wrong nullable processing for convert_tz
  be/src/vec/functions/function_convert_tz.h
  regression-test/data/query_p0/sql_functions/datetime_functions/test_convert_tz.out
  regression-test/suites/query_p0/sql_functions/datetime_functions/test_convert_tz.groovy
Labels: approved, reviewed, usercase, p0_w, dev/2.1.x, dev/3.0.x, doing

#38813 [fix](testcase) add order by to fix unstable output of passwordLeaked
  regression-test/suites/brown_p2/sql/passwordLeaked.sql
Labels: approved, reviewed, dev/2.1.x, doing

#38608 [fix](hist) Fix unstable result of aggregrate function hist
  be/src/vec/aggregate_functions/aggregate_function_histogram.h
  regression-test/data/query_p0/sql_functions/aggregate_functions/test_aggregate_all_functions2.out
  regression-test/suites/query_p0/sql_functions/aggregate_functions/test_aggregate_all_functions2.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x, doing

#36696 [opt](index) add more inverted index profile metrics
  be/src/olap/olap_common.h
  be/src/olap/rowset/segment_v2/inverted_index_reader.cpp
  be/src/olap/rowset/segment_v2/inverted_index_reader.h
  be/src/pipeline/exec/olap_scan_operator.cpp
  be/src/pipeline/exec/olap_scan_operator.h
  be/src/vec/exec/scan/new_olap_scanner.cpp
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x, dev/2.0.12-merged

#38840 [minor](fix) Fix incorrect fmt arguments
  be/src/pipeline/local_exchange/local_exchanger.h
Labels: approved, reviewed, dev/2.1.x, doing

#38857 [fix asan core](memoryleak) should deconstruct filter entity in scope of query context
  be/src/runtime/fragment_mgr.cpp
Labels: approved, reviewed

#38528 [improvement](tablet scheduler) Adjust tablet sched priority to help load data succ
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Tablet.java
  fe/fe-core/src/main/java/org/apache/doris/clone/ColocateTableCheckerAndBalancer.java
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletChecker.java
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletSchedCtx.java
  fe/fe-core/src/main/java/org/apache/doris/clone/TabletScheduler.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/TabletHealthProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/TabletSchedulerDetailProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/master/ReportHandler.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/OlapInsertExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapTableSink.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/DatabaseTransactionMgr.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/TabletTest.java
  fe/fe-core/src/test/java/org/apache/doris/clone/TabletHealthTest.java
  fe/fe-core/src/test/java/org/apache/doris/cluster/DecommissionBackendTest.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/TestWithFeService.java
Labels: approved, reviewed, dev/2.1.x, doing

#38701 [opt](info) processlist schema table support show all fe
  be/src/exec/schema_scanner.h
  be/src/exec/schema_scanner/schema_processlist_scanner.cpp
  be/src/pipeline/exec/schema_scan_operator.cpp
  fe/fe-core/src/main/java/org/apache/doris/catalog/SchemaTable.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SchemaScanNode.java
  gensrc/thrift/PlanNodes.thrift
Labels: approved, reviewed, usercase, dev/2.1.x

#38865 [Enhancement](audit log) Set print audit log sesssion variable default value to false
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
Labels: approved, reviewed, dev/2.1.x

#36563 [fix] (regression test) Fix unstable regression test
  regression-test/suites/clone_p0/test_clone_missing_version.groovy
  regression-test/suites/compaction/test_compaction_with_visible_version.groovy
  regression-test/suites/compaction/test_single_compaction_fault_injection.groovy
  regression-test/suites/compaction/test_single_compaction_with_variant_inverted_index.groovy
  regression-test/suites/compaction/test_single_replica_compaction.groovy
  regression-test/suites/compaction/test_time_series_compaction_policy.groovy
  regression-test/suites/fault_injection_p0/test_index_compaction_fault_injection.groovy
  regression-test/suites/fault_injection_p0/test_segcompaction_fault_injection.groovy
  regression-test/suites/fault_injection_p0/test_too_many_segments_fault_injection.groovy
  regression-test/suites/schema_change/test_number_overflow.groovy
  regression-test/suites/schema_change_p0/test_agg_keys_schema_change.groovy
  regression-test/suites/schema_change_p0/test_agg_mv_schema_change.groovy
  regression-test/suites/schema_change_p0/test_agg_rollup_schema_change.groovy
  regression-test/suites/schema_change_p0/test_agg_vals_schema_change.groovy
  regression-test/suites/schema_change_p0/test_dup_keys_schema_change.groovy
  regression-test/suites/schema_change_p0/test_dup_mv_schema_change.groovy
  regression-test/suites/schema_change_p0/test_dup_rollup_schema_change.groovy
  regression-test/suites/schema_change_p0/test_dup_vals_schema_change.groovy
  regression-test/suites/schema_change_p0/test_uniq_keys_schema_change.groovy
  regression-test/suites/schema_change_p0/test_uniq_mv_schema_change.groovy
  regression-test/suites/schema_change_p0/test_uniq_rollup_schema_change.groovy
  regression-test/suites/schema_change_p0/test_uniq_vals_schema_change.groovy
  regression-test/suites/schema_change_p0/test_varchar_schema_change.groovy
  regression-test/suites/segcompaction_p2/test_segcompaction_agg_keys.groovy
  regression-test/suites/segcompaction_p2/test_segcompaction_agg_keys_index.groovy
  regression-test/suites/segcompaction_p2/test_segcompaction_dup_keys.groovy
  regression-test/suites/segcompaction_p2/test_segcompaction_dup_keys_index.groovy
  regression-test/suites/segcompaction_p2/test_segcompaction_unique_keys.groovy
  regression-test/suites/segcompaction_p2/test_segcompaction_unique_keys_index.groovy
  regression-test/suites/segcompaction_p2/test_segcompaction_unique_keys_mow.groovy
  regression-test/suites/segcompaction_p2/test_segcompaction_unique_keys_mow_index.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x, doing

#38886 [fix](gson) Fix gson Pretty Printing
  fe/fe-core/src/main/java/org/apache/doris/persist/gson/GsonUtils.java
Labels: approved, reviewed, doing

#38814 [Enhancement]use awaitility.await() replace thread.sleep() #37817
  regression-test/suites/compaction/test_base_compaction.groovy
  regression-test/suites/compaction/test_base_compaction_no_value.groovy
  regression-test/suites/compaction/test_compaction_agg_keys.groovy
  regression-test/suites/compaction/test_compaction_uniq_keys.groovy
Labels: approved, reviewed, doing

#38902 [Fix](multi-catalog) Fix not throw error when call close() in hive/iceberg writer.
  be/src/vec/sink/writer/iceberg/viceberg_partition_writer.cpp
  be/src/vec/sink/writer/iceberg/viceberg_table_writer.cpp
  be/src/vec/sink/writer/vhive_partition_writer.cpp
  be/src/vec/sink/writer/vhive_table_writer.cpp
Labels: dev/2.1.x

#38904 [optimize](regression-test)use explain action to verify the explain result
  regression-test/suites/query_p0/aggregate/select_random_distributed_tbl.groovy
Labels: approved, reviewed, doing

#38900 [Enhancement]use awaitility in partial update testcases
  regression-test/suites/unique_with_mow_p0/partial_update/test_partial_update_insert_light_schema_change.groovy
  regression-test/suites/unique_with_mow_p0/partial_update/test_partial_update_insert_schema_change.groovy
  regression-test/suites/unique_with_mow_p0/partial_update/test_partial_update_schema_change.groovy
  regression-test/suites/unique_with_mow_p0/partial_update/test_partial_update_schema_change_row_store.groovy
Labels: approved, reviewed, doing

#38885 [fix](pipeline) Fix mem control in local exchanger
  be/src/pipeline/dependency.h
Labels: approved, reviewed, dev/2.1.x

#38514 [scheduler](core) Use signed int as number of cores
  be/src/pipeline/task_queue.cpp
  be/src/pipeline/task_queue.h
  be/src/pipeline/task_scheduler.cpp
Labels: approved, reviewed, not-merge/2.0, p0_c, dev/2.1.x

#38843 [Chore](dependnecies)remove javax.el and upgrade jackson to 2.17.2
  fe/pom.xml
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x, doing

#38829 [improvement](statistics)Improve statistics cache loading logic.
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HMSExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisManager.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/ColumnStatistic.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/ColumnStatisticsCacheLoader.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/PartitionColumnStatistic.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/PartitionColumnStatisticCacheLoader.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsRepository.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/util/StatisticsUtil.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/CacheTest.java
Labels: approved, reviewed, doing

#38527 [improvement](mtmv) Support to partition prune when query rewrite by sync materialized view
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewRule.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AsyncMaterializationContext.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/MaterializationContext.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/MaterializedViewUtils.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/SyncMaterializationContext.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/mv/IdStatisticsMapTest.java
  regression-test/data/mv_p0/partition_prune/partition_prune.out
  regression-test/suites/auth_p0/test_select_column_auth.groovy
  regression-test/suites/mv_p0/partition_prune/partition_prune.groovy
Labels: approved, reviewed, not-merge/2.1, doing

#38393 [opt](nereids) support partitionTopn for multi window exprs
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/CreatePartitionTopNFromWindow.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PushDownLimit.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PushDownTopNThroughWindow.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalWindow.java
  regression-test/suites/nereids_rules_p0/push_down_filter_through_window/push_down_multi_filter_through_window.groovy
Labels: approved, reviewed, dev/2.1.x, doing

#38787 [fix](update null map) Fix update_null_map
  be/src/vec/utils/util.hpp
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, doing

#38537 [enhancement](nereids) Support eliminate outer join by match expression
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/CheckAfterRewrite.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/FoldConstantRuleOnFE.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/PartitionPruner.java
  regression-test/data/nereids_syntax_p0/match.out
  regression-test/suites/nereids_syntax_p0/match.groovy
Labels: approved, reviewed, usercase, p0_b, dev/2.1.x, doing

#38796 [chore](sql) Forbid show hidden columns and create table with hidden column
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateTableStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Column.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/CreateTableInfo.java
  regression-test/framework/src/main/groovy/org/apache/doris/regression/action/TestAction.groovy
  regression-test/suites/show_p0/test_show_create_table_and_views.groovy
  regression-test/suites/show_p0/test_show_create_table_and_views_nereids.groovy
Labels: approved, reviewed, dev/2.1.x, doing

#38645 [improvement](file cache) Try to read from remote storage when opening segment with CachedRemoteFileReader
  be/src/cloud/injection_point_action.cpp
  be/src/olap/rowset/segment_v2/segment.cpp
Labels: approved, reviewed, p0_w, dev/3.0.x, doing

#38891 [fix](index) fix inverted index compound file entry size int32 overflow
  be/src/olap/rowset/segment_v2/inverted_index_file_writer.h
Labels: approved, reviewed, usercase, dev/2.1.x, dev/3.0.x

#37141 [Feature](Cloud) Support session variable disable_file_cache and enable_segment_cache in query
  be/src/exec/rowid_fetcher.cpp
  be/src/olap/parallel_scanner_builder.cpp
  be/src/olap/rowset/beta_rowset.cpp
  be/src/olap/rowset/beta_rowset.h
  be/src/olap/rowset/beta_rowset_reader.cpp
  be/src/olap/segment_loader.cpp
  be/src/olap/segment_loader.h
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  gensrc/thrift/PaloInternalService.thrift
Labels: approved, reviewed, meta-change, dev/3.0.x, doing

#38907 [Fix](inverted index) fix missed array inverted index null bitmap
  be/src/olap/rowset/segment_v2/column_writer.cpp
  be/src/olap/rowset/segment_v2/inverted_index_writer.cpp
  be/src/olap/rowset/segment_v2/inverted_index_writer.h
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, doing

#38917 [fix] (compaction) fix time series compaction policy (#38220)
  be/src/olap/cumulative_compaction.cpp
  be/src/olap/tablet.cpp
Labels: approved, reviewed

#38915 [fix] (compaction) fix time series compaction policy (#38220)
  be/src/olap/cumulative_compaction.cpp
  be/src/olap/tablet.cpp
Labels: approved, reviewed

#38400 [Fix](Export) Export delete multiple times when specify the `delete_existing_files` property
  be/src/service/internal_service.cpp
  fe/fe-core/src/main/java/org/apache/doris/common/util/BrokerUtil.java
  fe/fe-core/src/main/java/org/apache/doris/load/ExportJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/ExportMgr.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkEtlJobHandler.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/SparkRepository.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/common/util/BrokerUtilTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/SparkEtlJobHandlerTest.java
  gensrc/proto/internal_service.proto
Labels: approved, reviewed, meta-change, dev/2.1.x, doing

#38919 [fix](testcase) make set global cases non parallel
  regression-test/suites/variable_p0/set_and_unset_variable.groovy
Labels: approved, reviewed, doing

#38664 [Improve](Schema Change) avoid printing stack trace when check __DORIS_ROW_STORE_COL__
  be/src/olap/schema_change.cpp
  be/src/olap/tablet_schema.cpp
  be/src/olap/tablet_schema.h
Labels: approved, reviewed, dev/3.0.x, doing

#38852 [regression test](framework) add waitFor action (#30289)
  regression-test/framework/src/main/groovy/org/apache/doris/regression/action/WaitForAction.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
  regression-test/framework/src/main/groovy/suite.gdsl
  regression-test/suites/schema_change_p0/test_alter_table_column.groovy
Labels: kind/test

#38878 [fix](multi table) fix single stream multi table access denied in cloud mode
  fe/fe-core/src/main/java/org/apache/doris/load/StreamLoadHandler.java
  regression-test/data/load_p0/routine_load/test_routine_load_with_user.out
  regression-test/suites/load_p0/routine_load/data/test_routine_load_with_user.csv
  regression-test/suites/load_p0/routine_load/data/test_routine_load_with_user_multi_table.csv
  regression-test/suites/load_p0/routine_load/test_routine_load_with_user.groovy
Labels: approved, reviewed, usercase, doing

#38474 [fix](routine load) reset Kafka progress cache when routine load job topic change
  cloud/src/common/bvars.cpp
  cloud/src/common/bvars.h
  cloud/src/meta-service/meta_service.h
  cloud/src/meta-service/meta_service_txn.cpp
  fe/fe-core/src/main/java/org/apache/doris/cloud/rpc/MetaServiceClient.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/rpc/MetaServiceProxy.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/KafkaProgress.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/KafkaRoutineLoadJob.java
  gensrc/proto/cloud.proto
  regression-test/data/load_p0/routine_load/test_routine_load_topic_change.out
  regression-test/suites/load_p0/routine_load/data/test_topic_after.csv
  regression-test/suites/load_p0/routine_load/data/test_topic_before.csv
  regression-test/suites/load_p0/routine_load/test_routine_load_topic_change.groovy
Labels: approved, reviewed, meta-change, dev/2.0.x, dev/2.1.x, doing

#38912 [fix](move-memtable) close stream when cancel load stream stub
  be/src/vec/sink/load_stream_stub.cpp
Labels: approved, reviewed, dev/2.1.x, doing
