Repository apache/doris, pull requests merged in 2024-07, with the labels that each got.

#37025 [Exec](agg) Fix agg limit result error
  be/src/pipeline/dependency.cpp
  be/src/pipeline/dependency.h
  be/src/pipeline/exec/aggregation_sink_operator.cpp
  be/src/pipeline/exec/aggregation_source_operator.cpp
Labels: approved, reviewed

#37020 [refactor](spill) unify the entry point of spill tasks
  be/src/pipeline/exec/partitioned_aggregation_sink_operator.cpp
  be/src/pipeline/exec/partitioned_aggregation_source_operator.cpp
  be/src/pipeline/exec/partitioned_aggregation_source_operator.h
  be/src/pipeline/exec/partitioned_hash_join_probe_operator.cpp
  be/src/pipeline/exec/partitioned_hash_join_probe_operator.h
  be/src/pipeline/exec/partitioned_hash_join_sink_operator.cpp
  be/src/pipeline/exec/partitioned_hash_join_sink_operator.h
  be/src/pipeline/exec/spill_sort_sink_operator.cpp
  be/src/pipeline/exec/spill_sort_source_operator.cpp
  be/src/pipeline/exec/spill_sort_source_operator.h
  be/src/pipeline/exec/spill_utils.h
Labels: approved, reviewed

#37000 [chore](Regression) Remove useless get provider code in regression framework
  regression-test/framework/src/main/groovy/org/apache/doris/regression/Config.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
Labels: approved, reviewed

#36864 [regression-test](connector) Add a case for the response of streamload that the connector depends
  regression-test/data/flink_connector_p0/test_response.csv
  regression-test/suites/flink_connector_p0/flink_connector_response.groovy
Labels: approved, reviewed

#37017 [fix](local shuffle) Fix wrong partitioned expr in local exchanger
  be/src/pipeline/exec/hashjoin_build_sink.h
  be/src/pipeline/exec/hashjoin_probe_operator.h
Labels: approved, reviewed

#36898 [fix](bitmap) incorrect type of BitmapValue with fastunion (#36834)
  be/src/util/bitmap_value.h
  be/test/util/bitmap_value_test.cpp
Labels: approved, reviewed

#36936 [fix](ES Catalog)Add array types support in esquery function
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/EsQuery.java
  gensrc/script/doris_builtins_functions.py
  regression-test/data/external_table_p0/es/test_es_query.out
  regression-test/suites/external_table_p0/es/test_es_query.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x

#36689 [regression-test](case) modify statistics table name
  regression-test/suites/pipeline_p0/statitics_compaction.groovy
Labels: approved, reviewed

#36883 [feature](function) support ip functions named ipv4_to_ipv6 and cut_ipv6
  be/src/vec/functions/function_ip.cpp
  be/src/vec/functions/function_ip.h
  be/test/vec/function/function_ip_test.cpp
  be/test/vec/function/function_test_util.cpp
  be/test/vec/function/function_test_util.h
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinScalarFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/CutIpv6.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Ipv4ToIpv6.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/ScalarFunctionVisitor.java
  gensrc/script/doris_builtins_functions.py
  regression-test/data/query_p0/sql_functions/ip_functions/test_cut_ipv6_function.out
  regression-test/data/query_p0/sql_functions/ip_functions/test_ipv4_to_ipv6_function.out
  regression-test/suites/query_p0/sql_functions/ip_functions/test_cut_ipv6_function.groovy
  regression-test/suites/query_p0/sql_functions/ip_functions/test_ipv4_to_ipv6_function.groovy
Labels: approved, reviewed

#37008 [opt](hive) save hive table schema in transaction
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HMSTransaction.java
Labels: approved, reviewed, dev/2.1.x

#37021 [fix](jdbc catalog) fix jdbc table sink writer close nullptr and add log
  be/src/vec/sink/vjdbc_table_sink.cpp
Labels: approved, reviewed

#37003 [opt](function)avoid virtual function calls in geo functions
  be/src/vec/functions/functions_geo.cpp
  be/src/vec/functions/functions_geo.h
Labels: approved, reviewed

#37053 [fix](cloud) Allow access to MS during the replay
  fe/fe-core/src/main/java/org/apache/doris/alter/CloudSchemaChangeJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/rpc/MetaServiceProxy.java
Labels: approved, reviewed

#37055 [fix](cloud) Update mtime only if partitions have updated time
  fe/fe-core/src/main/java/org/apache/doris/cloud/catalog/CloudPartition.java
Labels: approved, reviewed

#36035 [feat](Nereids): Optimize query by pushing down aggregation through join on foreign key
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/Rewriter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/FuncDeps.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PushDownAggThroughJoinOnPkFk.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/PushDownAggThroughJoinOnPkFkTest.java
  regression-test/data/nereids_tpcds_shape_sf1000_p0/shape/query38.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/shape/query87.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/noStatsRfPrune/query38.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/noStatsRfPrune/query87.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/no_stats_shape/query38.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/no_stats_shape/query87.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/rf_prune/query38.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/rf_prune/query87.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query38.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query87.out
Labels: approved, reviewed, not-merge/2.1

#36498 [opt](arena) lazy memory allocation in arena
  be/src/vec/common/arena.h
Labels: approved, reviewed

#37015 [improvement](jdbc catalog)Rename config from `disable_jdbc_sqlserver_encrypt` to `force_sqlserver_jdbc_encrypt_false`
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/JdbcResource.java
Labels: approved, reviewed

#36661 [Fix](Nereids) fix leading with different be instance number (#36613)
  regression-test/data/nereids_p0/hint/fix_leading.out
  regression-test/suites/nereids_p0/hint/fix_leading.groovy
Labels: kind/test

#37048 [Fix](regression) Fix p0 case `test_unique_table_auto_inc_concurrent`
  regression-test/data/data_model_p0/unique/test_unique_auto_inc_concurrent.out
  regression-test/suites/data_model_p0/unique/test_unique_auto_inc_concurrent.groovy
Labels: approved, reviewed

#37040 [opt](catalog) add some profile for parquet reader and change meta cache config
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/vec/exec/format/parquet/vparquet_reader.cpp
  be/src/vec/exec/format/parquet/vparquet_reader.h
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HiveMetaStoreCache.java
Labels: approved, reviewed, dev/2.1.x

#36968 [pick21][opt](mow) reduce memory usage for mow table compaction
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/olap/compaction.cpp
  be/src/olap/tablet.cpp
  be/src/olap/utils.h
  regression-test/pipeline/external/conf/be.conf
  regression-test/pipeline/p0/conf/be.conf
  regression-test/pipeline/p1/conf/be.conf
Labels: approved, reviewed

#37061 [fix](Nereids) simplify window expression should inherit data type
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/SimplifyWindowExpression.java
  regression-test/data/nereids_rules_p0/simplify_window_expression/simplify_window_expression.out
  regression-test/suites/nereids_rules_p0/simplify_window_expression/simplify_window_expression.groovy
Labels: approved, reviewed, p0_b, dev/2.1.x

#37010 [profile](fe)update format of min/hour/sec unit in profile
  fe/fe-core/src/main/java/org/apache/doris/common/util/DebugUtil.java
  fe/fe-core/src/test/java/org/apache/doris/common/util/DebugUtilTest.java
Labels: approved, reviewed

#37044 [fix](nereids) ColStatsMeta.partitionUpdateRows npe
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/StatsCalculator.java
Labels: approved, reviewed

#36782 [feat](nereids) support explain delete from clause
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/DeleteFromCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/DeleteFromUsingCommand.java
  regression-test/suites/nereids_p0/explain/explain_dml.groovy
Labels: approved, reviewed, dev/2.1.x

#36937 [fix](map)fix upgrade behavior from 1.2 version
  be/src/olap/rowset/segment_v2/column_reader.cpp
  be/src/olap/rowset/segment_v2/column_writer.cpp
  be/src/olap/tablet_schema.cpp
Labels: approved, reviewed, dev/2.0.12-merged, dev/2.1.5-merged

#36762 [improve](json)improve json support empty keys
  be/src/util/jsonb_document.h
  be/src/util/jsonb_utils.h
  be/src/util/jsonb_writer.h
  regression-test/data/json_p0/test_json_load_and_function.out
  regression-test/data/jsonb_p0/test_jsonb_load_and_function.out
  regression-test/data/nereids_p0/json_p0/test_json_load_and_function.out
  regression-test/data/nereids_p0/jsonb_p0/test_jsonb_load_and_function.out
  regression-test/suites/json_p0/test_json_load_and_function.groovy
  regression-test/suites/jsonb_p0/test_jsonb_load_and_function.groovy
  regression-test/suites/nereids_p0/json_p0/test_json_load_and_function.groovy
  regression-test/suites/nereids_p0/jsonb_p0/test_jsonb_load_and_function.groovy
Labels: approved, reviewed, usercase, dev/2.0.x, dev/2.1.x

#37074 [fix](stmt) fix show create table consistency
  fe/fe-core/src/main/java/org/apache/doris/analysis/SlotRef.java
Labels: approved, reviewed

#36902 [fix](mtmv)Fix mtmv name to resolve conflicts in regression test
  regression-test/suites/nereids_rules_p0/mv/dimension_2_join_agg/dimension_join_agg_negative.groovy
Labels: approved, reviewed, dev/2.1.x

#37065 [fix](function) fix nereids fold constant wrong result of abs
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/executable/ExecutableFunctions.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/expressions/functions/ExecutableFunctionsTest.java
Labels: approved, reviewed, p0_w, dev/2.0.x, dev/2.1.x

#36843 [opt](split) add max wait time of getting splits
  be/src/pipeline/exec/file_scan_operator.cpp
  be/src/vec/exec/scan/split_source_connector.cpp
  be/src/vec/exec/scan/split_source_connector.h
  be/src/vec/exec/scan/vfile_scanner.cpp
  be/src/vec/exec/scan/vfile_scanner.h
  fe/fe-core/src/main/java/org/apache/doris/datasource/FileQueryScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/SplitSource.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
Labels: approved, reviewed, dev/2.1.x

#37081 [test](tvf) move p2 tvf tests from p2 to p0
  regression-test/data/external_table_p0/tvf/test_tvf_view.out
  regression-test/data/external_table_p2/tvf/test_tvf_view_p2.out
  regression-test/suites/external_table_p0/tvf/test_tvf_view.groovy
  regression-test/suites/external_table_p0/tvf/test_tvf_view_count.groovy
Labels: approved, reviewed, dev/2.1.x

#37011 [fix](parquet) prevent parquet page reader print much warning logs
  be/src/util/thrift_util.h
Labels: approved, reviewed, usercase, dev/2.1.x

#36892 [fix](regression) fix txn_insert case
  regression-test/data/insert_p0/txn_insert.out
  regression-test/suites/insert_p0/txn_insert.groovy
  regression-test/suites/insert_p2/txn_insert_concurrent_insert_duplicate.groovy
  regression-test/suites/insert_p2/txn_insert_concurrent_insert_ud.groovy
  regression-test/suites/insert_p2/txn_insert_concurrent_insert_unique.groovy
  regression-test/suites/insert_p2/txn_insert_concurrent_insert_update.groovy
  regression-test/suites/insert_p2/txn_insert_with_schema_change.groovy
Labels: approved, reviewed

#37071 [fix](routine-load) fix auto resume invalid when FE leader change
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadJob.java
Labels: approved, reviewed

#37001 [fix](merge-on-write) when full clone failed, duplicate key might occur
  be/src/olap/snapshot_manager.cpp
  be/src/olap/tablet.cpp
  be/src/olap/task/engine_clone_task.cpp
  regression-test/data/unique_with_mow_p0/test_mow_full_clone_exception.out
  regression-test/suites/unique_with_mow_p0/test_mow_full_clone_exception.groovy
Labels: approved, reviewed, p0_w, dev/2.0.x, dev/2.1.x

#37028 [Fix]add set thread num config for wg flush pool
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/olap/delta_writer_v2.cpp
  be/src/olap/storage_engine.cpp
  be/src/olap/storage_engine.h
  be/src/runtime/query_context.cpp
  be/src/runtime/query_context.h
  be/src/runtime/workload_group/workload_group.cpp
  be/src/runtime/workload_group/workload_group.h
  be/src/vec/sink/writer/async_result_writer.cpp
Labels: approved, reviewed, kind/behavior-changed, workload-group, dev/2.1.x

#37095 [fix](nereids) fix This stopwatch is already running
  fe/fe-core/src/main/java/org/apache/doris/nereids/NereidsPlanner.java
Labels: approved, reviewed

#37112 [fix](recycler) Fix DCHECK in ObjectListIterator
  cloud/src/recycler/azure_obj_client.cpp
  cloud/src/recycler/s3_obj_client.cpp
Labels: approved, reviewed

#37018 [fix](group commit) remove non pipeline code
  be/src/runtime/group_commit_mgr.cpp
  be/src/runtime/group_commit_mgr.h
Labels: approved, reviewed

#36863 [opt](function) opt pad function process the input const column
  be/src/vec/functions/function_string.h
Labels: approved, reviewed

#36882 [opt](function) opt ParseUrl function by process the input const column
  be/src/vec/columns/column_const.h
  be/src/vec/functions/function_string.h
Labels: approved, reviewed

#37088 [Readme](Community)Update README.md
  README.md
Labels: approved, reviewed

#37057 [regression](kerberos)fix regression pipeline env when write hosts
  docker/thirdparties/run-thirdparties-docker.sh
Labels: approved, reviewed

#37073 [fix](null safe equal join) fix coredump if both sides of the conjunct is not nullable #36263
  be/src/pipeline/exec/hashjoin_build_sink.cpp
  be/src/pipeline/exec/hashjoin_probe_operator.cpp
  regression-test/data/query_p0/join/rqg/rqg12257/rqg12257.out
  regression-test/suites/query_p0/join/rqg/rqg12257/rqg12257.groovy
Labels: approved, reviewed

#37090 [enhancement](nereids) speedup sql cache with variable
  fe/fe-core/src/main/java/org/apache/doris/common/NereidsSqlCacheManager.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/NereidsPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/SqlCacheContext.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/ComputeResultSet.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalEmptyRelation.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalOneRowRelation.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalResultSink.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalSqlCache.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  regression-test/suites/nereids_p0/cache/parse_sql_from_sql_cache.groovy
Labels: approved, reviewed, dev/2.1.x

#37059 [Fix](Scanner) Fix reinitialization of TabletReader
  be/src/vec/exec/scan/scanner_scheduler.cpp
Labels: approved, reviewed, dev/2.1.x

#37072 [Bug](QueryStatistics) use std::atomic<int64_t> for returned_rows to save data
  be/src/runtime/query_statistics.cpp
  be/src/runtime/query_statistics.h
Labels: approved, reviewed

#36840 [fix](mtmv)fix MTMVTask log has null pointer
  fe/fe-core/src/main/java/org/apache/doris/job/task/AbstractTask.java
  fe/fe-core/src/test/java/org/apache/doris/mtmv/MTMVTest.java
Labels: approved, reviewed

#37087 [fix](statistics)Fix partition record update rows bug. Remove useless code.
  fe/fe-core/src/main/java/org/apache/doris/analysis/AnalyzeStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowAnalyzeStmt.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisInfo.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisInfoBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisManager.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsAutoCollector.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/TableStatsMeta.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/AnalysisManagerTest.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/AnalysisTaskExecutorTest.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/AnalyzeTest.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/HistogramTaskTest.java
  regression-test/suites/statistics/test_partition_stats.groovy
Labels: approved, reviewed

#37019 [fix](Nereids) null type in result set will be cast to tinyint
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/BindExpression.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/TypeCoercionUtils.java
  regression-test/data/mtmv_p0/test_create_with_null_type.out
  regression-test/suites/mtmv_p0/test_create_with_null_type.groovy
Labels: approved, reviewed, dev/2.1.x

#37103 [Chore](runtime-filter) enlarge sync filter size rpc timeout limit
  be/src/common/config.cpp
  be/src/exprs/runtime_filter.cpp
  be/src/exprs/runtime_filter.h
  be/src/exprs/runtime_filter_slots.h
  regression-test/suites/query_p0/join/test_join5.groovy
Labels: approved, reviewed, dev/2.1.x

#36928 [fix](auth)support check priv when tvf use resource
  fe/fe-core/src/main/java/org/apache/doris/analysis/AlterPolicyStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreatePolicyStmt.java
  fe/fe-core/src/main/java/org/apache/doris/common/ErrorCode.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/CheckPrivileges.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/table/TableValuedFunction.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/ExternalFileTableValuedFunction.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/TableValuedFunctionIf.java
  regression-test/suites/external_table_p0/tvf/test_s3_tvf_with_resource.groovy
Labels: approved, reviewed, kind/behavior-changed, dev/2.1.x

#37094 [Chore](exec) remove some unused code
  be/src/pipeline/exec/exchange_sink_operator.cpp
  be/src/vec/data_types/data_type_decimal.h
Labels: approved, reviewed

#37104 [Compatibility](agg-state) do not throw eception when DataTypeAggState meet old be exec version
  be/src/vec/data_types/data_type_agg_state.h
Labels: approved, reviewed

#36954 [bugfix](hive)Prevent multiple `fs` from being generated
  fe/fe-common/src/main/java/org/apache/doris/common/security/authentication/HadoopUGI.java
Labels: approved, reviewed, dev/2.1.x

#37086 [fix](multi-catalog) Revert #36575 and check nullptr of data column
  be/src/vec/core/block.cpp
  be/src/vec/exec/format/orc/vorc_reader.cpp
  be/src/vec/exec/format/parquet/vparquet_reader.cpp
Labels: approved, reviewed, dev/2.1.x

#36934 [fix](array) fix array_except/union for left const return only one row result
  be/src/vec/functions/array/function_array_set.h
  regression-test/data/query_p0/sql_functions/array_functions/test_array_functions.out
  regression-test/suites/query_p0/sql_functions/array_functions/test_array_functions.groovy
Labels: kind/test, approved, reviewed

#36887 [feature](json)support explode_json_object func
  be/src/vec/exprs/table_function/table_function_factory.cpp
  be/src/vec/exprs/table_function/vexplode_json_object.cpp
  be/src/vec/exprs/table_function/vexplode_json_object.h
  be/src/vec/functions/function_fake.cpp
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinTableGeneratingFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/generator/ExplodeJsonObject.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/generator/ExplodeJsonObjectOuter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/TableGeneratingFunctionVisitor.java
  regression-test/data/nereids_p0/jsonb_p0/test_jsonb_load_and_function.out
  regression-test/suites/jsonb_p0/test_jsonb_load_and_function.groovy
  regression-test/suites/nereids_p0/jsonb_p0/test_jsonb_load_and_function.groovy
Labels: approved, reviewed, kind/need-document

#37069 [opt](ctas) add a variable to control varchar length in ctas
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/CreateTableCommand.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  regression-test/data/nereids_p0/create_table/test_ctas.out
  regression-test/suites/nereids_p0/create_table/test_ctas.groovy
Labels: approved, reviewed, dev/2.1.x

#36749 [enhance](mtmv)support replace materialized view
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/alter/Alter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/AlterMTMVInfo.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/AlterMTMVRenameInfo.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/AlterMTMVReplaceInfo.java
  regression-test/data/mtmv_p0/test_multi_level_rename_mtmv.out
  regression-test/data/mtmv_p0/test_multi_level_replace_mtmv.out
  regression-test/data/mtmv_p0/test_replace_mtmv.out
  regression-test/suites/mtmv_p0/test_multi_level_rename_mtmv.groovy
  regression-test/suites/mtmv_p0/test_multi_level_replace_mtmv.groovy
  regression-test/suites/mtmv_p0/test_replace_mtmv.groovy
Labels: approved, reviewed, kind/need-document, dev/2.1.x

#37101 [feature](ES Catalog) map nested/object type in ES to JSON type in Doris
  be/src/exec/es/es_scroll_parser.cpp
  docker/thirdparties/docker-compose/elasticsearch/scripts/data/data1.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/data/data1_es6.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/data/data2.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/data/data2_es6.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/data/data3.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/data/data3_es5.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/data/data3_es6.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/data/data4.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/index/array_meta.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/index/es6_hide.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/index/es6_test1.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/index/es6_test2.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/index/es7_hide.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/index/es7_test1.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/index/es7_test2.json
  fe/fe-core/src/main/java/org/apache/doris/datasource/es/EsUtil.java
  regression-test/data/external_table_p0/es/test_es_query.out
  regression-test/data/external_table_p0/es/test_es_query_no_http_url.out
  regression-test/data/mtmv_p0/test_es_mtmv.out
  regression-test/suites/external_table_p0/es/test_es_query.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x

#37045 [feat](Nereids): Add support for slot pruning in functional dependencies
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/DataTrait.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/FuncDeps.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/FuncDepsDG.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PushDownAggThroughJoinOnPkFk.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalPlan.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalProject.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/ImmutableEqualSet.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/properties/FuncDepsDGTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/util/ImmutableEqualSetTest.java
Labels: approved, reviewed, not-merge/2.1

#37056 [fix](ES Catalog)Add array types support in esquery function (#36936)
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/EsQuery.java
  gensrc/script/doris_builtins_functions.py
  regression-test/data/external_table_p0/es/test_es_query.out
  regression-test/suites/external_table_p0/es/test_es_query.groovy
Labels: kind/test, area/nereids

#37068 [env](compile) compile failed caused by <immintrin.h>
  be/src/util/simd/vstring_function.h
Labels: approved, reviewed

#37124 [improvement](statistics)Support show column partition update rows info.
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowTableStatsStmt.java
  regression-test/suites/statistics/test_partition_stats.groovy
Labels: approved, reviewed, not-merge/2.1

#37109 [fix](Nereids) normalize aggregate should not push down lambda's param
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/Expression.java
  regression-test/data/nereids_rules_p0/normalize_aggregate/normalize_aggregate_test.out
  regression-test/suites/nereids_rules_p0/normalize_aggregate/normalize_aggregate_test.groovy
Labels: approved, reviewed, p0_b, dev/2.1.x

#37106 [refactor](nereids) refactor analyze view
  fe/fe-core/src/main/java/org/apache/doris/nereids/CascadesContext.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/AbstractBatchJobExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/Rewriter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/rewrite/PlanTreeRewriteBottomUpJob.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/rewrite/PlanTreeRewriteJob.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/rewrite/PlanTreeRewriteTopDownJob.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/rewrite/RootPlanTreeRewriteJob.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/BindRelation.java
Labels: approved, reviewed, dev/2.1.x

#37135 [fix](txn insert) Forbid delete condition in txn insert
  fe/fe-core/src/main/java/org/apache/doris/load/TxnDeleteJob.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/OlapTxnInsertExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/TransactionEntry.java
  regression-test/data/insert_p0/txn_insert.out
  regression-test/data/insert_p0/txn_insert_with_schema_change.out
  regression-test/suites/insert_p0/txn_insert.groovy
  regression-test/suites/insert_p0/txn_insert_with_schema_change.groovy
  regression-test/suites/insert_p2/txn_insert_concurrent_insert_ud.groovy
  regression-test/suites/insert_p2/txn_insert_concurrent_insert_update.groovy
  regression-test/suites/insert_p2/txn_insert_with_schema_change.groovy
Labels: approved, reviewed

#37116 [fix](fe) Avoid infinite dropping index in check compatibility mode
  fe/fe-core/src/main/java/org/apache/doris/alter/CloudSchemaChangeJobV2.java
Labels: approved, reviewed

#37113 [Enhancement](partial update) Add partial update mix cases
  regression-test/data/unique_with_mow_p0/partial_update/test_mix_partial_update.out
  regression-test/data/unique_with_mow_p0/partial_update/test_mix_partial_update_load1.csv
  regression-test/data/unique_with_mow_p0/partial_update/test_mix_partial_update_load2.csv
  regression-test/data/unique_with_mow_p0/partial_update/test_mix_partial_update_load3.csv
  regression-test/data/unique_with_mow_p0/partial_update/test_mix_partial_update_load4.csv
  regression-test/data/unique_with_mow_p0/partial_update/test_mix_partial_update_load5.csv
  regression-test/data/unique_with_mow_p0/partial_update/test_mix_partial_update_load6.csv
  regression-test/data/unique_with_mow_p0/partial_update/test_mix_partial_update_load7.csv
  regression-test/data/unique_with_mow_p0/partial_update/test_mix_partial_update_load_A.csv
  regression-test/data/unique_with_mow_p0/partial_update/test_mix_partial_update_load_B.csv
  regression-test/data/unique_with_mow_p0/partial_update/test_mix_partial_update_load_C.csv
  regression-test/data/unique_with_mow_p0/partial_update/test_mix_partial_update_load_D.csv
  regression-test/suites/unique_with_mow_p0/partial_update/test_mix_partial_update.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x

#37099 [enhancement](compaction) optimizing memory usage for compaction
  be/src/cloud/cloud_base_compaction.cpp
  be/src/cloud/cloud_cumulative_compaction.cpp
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/olap/base_compaction.cpp
  be/src/olap/base_tablet.h
  be/src/olap/compaction.cpp
  be/src/olap/compaction.h
  be/src/olap/cumulative_compaction.cpp
  be/src/olap/iterators.h
  be/src/olap/merger.cpp
  be/src/olap/merger.h
  be/src/olap/rowset/rowset_meta.h
  be/src/olap/rowset/segcompaction.cpp
  be/src/olap/tablet_reader.h
  be/src/vec/olap/vertical_block_reader.cpp
  be/src/vec/olap/vertical_block_reader.h
  be/src/vec/olap/vertical_merge_iterator.cpp
  be/src/vec/olap/vertical_merge_iterator.h
  be/test/olap/base_compaction_test.cpp
  be/test/olap/rowid_conversion_test.cpp
  be/test/vec/olap/vertical_compaction_test.cpp
  regression-test/suites/compaction/compaction_width_array_column.groovy
Labels: approved, reviewed

#36711 [Enhancement](s3-load) Add domain connection and aksk correction check for S3 load
  fe/fe-core/src/main/java/org/apache/doris/analysis/LoadStmt.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/constants/S3Properties.java
  regression-test/suites/load_p0/broker_load/test_domain_connection_and_ak_sk_correction.groovy
Labels: approved, reviewed

#37153 [Fix](csv_reader) Add a session variable to control whether empty rows in CSV files are read as NULL values
  be/src/runtime/runtime_state.h
  be/src/vec/exec/format/csv/csv_reader.cpp
  be/src/vec/exec/format/csv/csv_reader.h
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  gensrc/thrift/PaloInternalService.thrift
  regression-test/data/external_table_p0/tvf/test_read_csv_empty_line_as_null.out
  regression-test/suites/external_table_p0/tvf/test_read_csv_empty_line_as_null.groovy
Labels: meta-change

#37130 [fix](auth)ldap set passwd need forward to master (#36436)
  fe/fe-core/src/main/java/org/apache/doris/analysis/SetStmt.java
Labels: area/planner

#37043 [fix](hive) support find serde info from both tbl properties and serde properties
  docker/thirdparties/docker-compose/hive/scripts/data/regression/serde_prop/run.sh
  docker/thirdparties/docker-compose/hive/scripts/data/regression/serde_prop/some_serde_table.hql
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HiveMetaStoreClientHelper.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/source/HiveScanNode.java
  regression-test/data/external_table_p0/hive/test_hive_serde_prop.out
  regression-test/suites/external_table_p0/hive/test_hive_serde_prop.groovy
Labels: approved, reviewed, dev/2.1.x

#37167 [Fix](export/outfile) Support compression when exporting data to Parquet / ORC.
  be/src/vec/runtime/vorc_transformer.cpp
  be/src/vec/runtime/vorc_transformer.h
  be/src/vec/runtime/vparquet_transformer.cpp
  be/src/vec/sink/vresult_sink.h
  be/src/vec/sink/writer/iceberg/viceberg_partition_writer.cpp
  be/src/vec/sink/writer/vfile_result_writer.cpp
  be/src/vec/sink/writer/vhive_partition_writer.cpp
  fe/fe-core/src/main/java/org/apache/doris/analysis/ExportStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/OutFileClause.java
  fe/fe-core/src/main/java/org/apache/doris/load/ExportJob.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ExportCommand.java
  gensrc/thrift/DataSinks.thrift
  regression-test/data/export_p0/test_parquet_orc_compression.out
  regression-test/suites/export_p0/test_parquet_orc_compression.groovy
Labels: meta-change

#37138 [fix](Nereids)Fix bug of external table didn't set row count in StatsCalculator.
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/StatsCalculator.java
  regression-test/suites/external_table_p0/hive/test_hive_statistics_p0.groovy
Labels: approved, reviewed, not-merge/2.1

#36877 [Fix](Nereids) TopN should forbid two-phase topN if child is DistributionSpecGather
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/ChildrenPropertiesRegulator.java
  regression-test/data/nereids_rules_p0/limit_push_down/order_push_down.out
  regression-test/data/nereids_rules_p0/push_down_top_n/push_down_top_n_through_union.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/bs_downgrade_shape/query61.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/bs_downgrade_shape/query95.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/shape/query16.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/shape/query61.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/shape/query90.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/shape/query92.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/shape/query94.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/shape/query95.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/shape/query96.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/noStatsRfPrune/query16.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/noStatsRfPrune/query61.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/noStatsRfPrune/query90.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/noStatsRfPrune/query92.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/noStatsRfPrune/query94.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/noStatsRfPrune/query95.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/noStatsRfPrune/query96.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/no_stats_shape/query16.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/no_stats_shape/query61.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/no_stats_shape/query90.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/no_stats_shape/query92.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/no_stats_shape/query94.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/no_stats_shape/query95.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/no_stats_shape/query96.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/rf_prune/query16.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/rf_prune/query61.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/rf_prune/query90.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/rf_prune/query92.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/rf_prune/query94.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/rf_prune/query95.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/rf_prune/query96.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query16.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query61.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query90.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query92.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query94.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query95.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query96.out
Labels: approved, reviewed, dev/2.1.x

#36886 [opt](Nereids) Replace Slot in Each Data Trait Separately
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/DataTrait.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/FuncDepsDG.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/AbstractPlan.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/BlockFuncDepsPropagation.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PropagateFuncDeps.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalExcept.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalIntersect.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalPlan.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalSubQueryAlias.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/properties/FuncDepsDGTest.java
Labels: approved, reviewed, not-merge/2.1

#37031 [opt](binlog) support rename binlog
  fe/fe-core/src/main/java/org/apache/doris/binlog/BinlogManager.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/persist/EditLog.java
  fe/fe-core/src/main/java/org/apache/doris/persist/TableInfo.java
  gensrc/thrift/FrontendService.thrift
Labels: approved, reviewed, meta-change, dev/2.1.x

#37121 [Fix](Short Circuit) fix no project list in OlapScanNode
  fe/fe-core/src/main/java/org/apache/doris/qe/ShortCircuitQueryContext.java
  regression-test/data/point_query_p0/test_point_query.out
  regression-test/suites/point_query_p0/test_point_query.groovy
Labels: approved, reviewed, usercase, dev/2.1.x

#37067 [Fix](schema change) Fix can't do reorder column schema change for MOW table and duplicate key table
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/ColumnDefinition.java
  regression-test/data/schema_change/test_schema_change_datev2_with_delete.out
  regression-test/data/schema_change_p0/datev2/test_dup_keys_schema_change_datev2.out
  regression-test/data/schema_change_p0/test_modify_reorder_column.out
  regression-test/suites/ddl_p0/test_create_table_generated_column/alter_column_test_generated_column.groovy
  regression-test/suites/schema_change/test_schema_change_datev2_with_delete.groovy
  regression-test/suites/schema_change_p0/datev2/test_dup_keys_schema_change_datev2.groovy
  regression-test/suites/schema_change_p0/test_modify_reorder_column.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x

#37156 [Performance](func) Opt the any_value agg function no group by
  be/src/vec/aggregate_functions/aggregate_function_min_max.h
Labels: approved, reviewed

#37193 [fix](hash join) fix numeric overflow when calculating hash table bucket size
  be/src/vec/common/hash_table/join_hash_table.h
Labels: approved, reviewed, dev/2.1.x

#37198 [chore](errmsg) Add more clear error message when loading timed out
  be/src/vec/sink/writer/vtablet_writer.cpp
Labels: approved, reviewed

#37160 [fix](Nereids) partition not exists error msg is not contain table name
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/BindRelation.java
Labels: approved, reviewed, dev/2.1.x

#37159 [improvement] Log workload group's thread num when publish
  be/src/agent/cgroup_cpu_ctl.cpp
  be/src/agent/cgroup_cpu_ctl.h
  be/src/agent/workload_group_listener.cpp
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/pipeline/task_scheduler.h
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/workload_group/workload_group.cpp
  be/src/runtime/workload_group/workload_group.h
  be/src/util/threadpool.h
  be/src/vec/exec/scan/scanner_scheduler.h
Labels: approved, reviewed, workload-group, dev/2.1.x

#37214 [feature](datatype) add BE config to allow zero date (#34961)
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/vec/io/io_helper.h
  be/src/vec/runtime/vdatetime_value.cpp
  be/src/vec/runtime/vdatetime_value.h
  be/test/vec/exprs/vexpr_test.cpp
Labels: approved, reviewed

#37178 [branch-2.0](function) fix date_format and from_unixtime core when meet long format string (#35883)
  be/src/olap/types.h
  be/src/vec/data_types/serde/data_type_datetimev2_serde.cpp
  be/src/vec/functions/date_time_transforms.h
  be/src/vec/runtime/vdatetime_value.cpp
  be/src/vec/runtime/vdatetime_value.h
  regression-test/data/datatype_p0/date/test_from_unixtime.out
  regression-test/data/nereids_p0/sql_functions/datetime_functions/test_date_function.out
  regression-test/suites/datatype_p0/date/test_from_unixtime.groovy
  regression-test/suites/nereids_p0/sql_functions/datetime_functions/test_date_function.groovy
Labels: kind/test

#37118 [test](case) add java-udf function meta test case
  regression-test/data/javaudf_p0/function_meta/function_query_test.out
  regression-test/suites/javaudf_p0/function_meta/function_query_test.groovy
  regression-test/suites/javaudf_p0/function_meta/load.groovy
Labels: approved, reviewed

#37227 [fix](merge-on-write) when full clone failed, duplicate key might occur (#37001)
  be/src/olap/snapshot_manager.cpp
  be/src/olap/tablet.cpp
  regression-test/data/unique_with_mow_p0/test_mow_full_clone_exception.out
  regression-test/suites/unique_with_mow_p0/test_mow_full_clone_exception.groovy
Labels: kind/test

#37216 [chore](planner) use NotFallbackInPasrser to label stmt impl in Nereids
  fe/fe-core/src/main/java/org/apache/doris/analysis/AlterViewStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateTableAsSelectStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateTableLikeStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateTableStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateViewStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/DeleteStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/InsertStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/NativeInsertStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/NotFallbackInParser.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/QueryStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SetOperationStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/UpdateStmt.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
Labels: approved, reviewed, dev/2.1.x

#36927 [opt](fucntion) improve json_extract function handle const column
  be/src/vec/functions/function_json.cpp
Labels: approved, reviewed

#37060 [opt](nereids) refine left semi/anti shortcut cost
  fe/fe-core/src/main/java/org/apache/doris/nereids/cost/CostModelV1.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  regression-test/data/nereids_tpcds_shape_sf1000_p0/shape/query16.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/shape/query78.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/shape/query94.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/noStatsRfPrune/query14.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/noStatsRfPrune/query58.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/noStatsRfPrune/query95.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/no_stats_shape/query14.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/no_stats_shape/query58.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/no_stats_shape/query95.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/rf_prune/query14.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/rf_prune/query16.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/rf_prune/query78.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/rf_prune/query94.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query14.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query16.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query78.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query94.out
Labels: approved, reviewed, dev/2.1.x

#36784 [opt](nereids) recover adoptive bucket shuffle
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/ChildrenPropertiesRegulator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  regression-test/data/nereids_tpcds_shape_sf1000_p0/bs_downgrade_shape/query19.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/bs_downgrade_shape/query44.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/bs_downgrade_shape/query54.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/bs_downgrade_shape/query56.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/bs_downgrade_shape/query6.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/bs_downgrade_shape/query61.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/bs_downgrade_shape/query68.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/bs_downgrade_shape/query8.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/bs_downgrade_shape/query91.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/bs_downgrade_shape/query95.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/shape/query85.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/rf_prune/query61.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/rf_prune/query85.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query61.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query85.out
  regression-test/suites/correctness_p0/test_bucket_shuffle_join.groovy
  regression-test/suites/inverted_index_p1/tpcds_sf1_index/sql/q78.sql
  regression-test/suites/nereids_p0/hint/fix_leading.groovy
  regression-test/suites/nereids_p0/hint/multi_leading.groovy
  regression-test/suites/nereids_p0/hint/test_distribute.groovy
  regression-test/suites/nereids_p0/hint/test_leading.groovy
  regression-test/suites/nereids_p0/join/bucket_shuffle_join.groovy
  regression-test/suites/nereids_tpcds_shape_sf1000_p0/bs_downgrade_shape/query13.groovy
  regression-test/suites/nereids_tpcds_shape_sf1000_p0/bs_downgrade_shape/query19.groovy
  regression-test/suites/nereids_tpcds_shape_sf1000_p0/bs_downgrade_shape/query44.groovy
  regression-test/suites/nereids_tpcds_shape_sf1000_p0/bs_downgrade_shape/query45.groovy
  regression-test/suites/nereids_tpcds_shape_sf1000_p0/bs_downgrade_shape/query54.groovy
  regression-test/suites/nereids_tpcds_shape_sf1000_p0/bs_downgrade_shape/query56.groovy
  regression-test/suites/nereids_tpcds_shape_sf1000_p0/bs_downgrade_shape/query6.groovy
  regression-test/suites/nereids_tpcds_shape_sf1000_p0/bs_downgrade_shape/query61.groovy
  regression-test/suites/nereids_tpcds_shape_sf1000_p0/bs_downgrade_shape/query68.groovy
  regression-test/suites/nereids_tpcds_shape_sf1000_p0/bs_downgrade_shape/query8.groovy
  regression-test/suites/nereids_tpcds_shape_sf1000_p0/bs_downgrade_shape/query91.groovy
  regression-test/suites/nereids_tpcds_shape_sf1000_p0/bs_downgrade_shape/query95.groovy
Labels: approved, reviewed

#37107 [branch-2.0](function) fix nereids fold constant wrong result of abs (#37065)
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/executable/ExecutableFunctions.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/expressions/functions/ExecutableFunctionsTest.java
Labels: area/nereids

#37223 [Bug](runtime-filter) fix brpc ctrl use after free
  be/src/runtime/runtime_filter_mgr.cpp
Labels: meta-change

#37222 [fix](meta) do not serialize nametotable map
  fe/fe-common/src/main/java/org/apache/doris/common/FeMetaVersion.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Database.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Replica.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Tablet.java
Labels: approved, reviewed, meta-change

#37211 [fix](gson) Fix GSON pretty printting setting
  fe/fe-core/src/main/java/org/apache/doris/persist/gson/GsonUtils.java
Labels: approved, reviewed

#36957 [test](migrate) move 3 cases from p2 to p0
  docker/thirdparties/docker-compose/hive/scripts/data/multi_catalog/test_chinese_orc/create_table.hql
  docker/thirdparties/docker-compose/hive/scripts/data/multi_catalog/test_chinese_orc/data.tar.gz
  docker/thirdparties/docker-compose/hive/scripts/data/multi_catalog/test_chinese_orc/run.sh
  docker/thirdparties/docker-compose/hive/scripts/data/multi_catalog/test_chinese_parquet/create_table.hql
  docker/thirdparties/docker-compose/hive/scripts/data/multi_catalog/test_chinese_parquet/data.tar.gz
  docker/thirdparties/docker-compose/hive/scripts/data/multi_catalog/test_chinese_parquet/run.sh
  docker/thirdparties/docker-compose/hive/scripts/data/multi_catalog/test_chinese_text/create_table.hql
  docker/thirdparties/docker-compose/hive/scripts/data/multi_catalog/test_chinese_text/data.tar.gz
  docker/thirdparties/docker-compose/hive/scripts/data/multi_catalog/test_chinese_text/run.sh
  docker/thirdparties/docker-compose/hive/scripts/data/multi_catalog/test_multi_langs_orc/create_table.hql
  docker/thirdparties/docker-compose/hive/scripts/data/multi_catalog/test_multi_langs_orc/data.tar.gz
  docker/thirdparties/docker-compose/hive/scripts/data/multi_catalog/test_multi_langs_orc/run.sh
  docker/thirdparties/docker-compose/hive/scripts/data/multi_catalog/test_multi_langs_parquet/create_table.hql
  docker/thirdparties/docker-compose/hive/scripts/data/multi_catalog/test_multi_langs_parquet/data.tar.gz
  docker/thirdparties/docker-compose/hive/scripts/data/multi_catalog/test_multi_langs_parquet/run.sh
  docker/thirdparties/docker-compose/hive/scripts/data/multi_catalog/test_multi_langs_text/create_table.hql
  docker/thirdparties/docker-compose/hive/scripts/data/multi_catalog/test_multi_langs_text/data.tar.gz
  docker/thirdparties/docker-compose/hive/scripts/data/multi_catalog/test_multi_langs_text/run.sh
  docker/thirdparties/docker-compose/hive/scripts/data/multi_catalog/type_change_orc/create_table.hql
  docker/thirdparties/docker-compose/hive/scripts/data/multi_catalog/type_change_orc/data.tar.gz
  docker/thirdparties/docker-compose/hive/scripts/data/multi_catalog/type_change_orc/run.sh
  docker/thirdparties/docker-compose/hive/scripts/data/multi_catalog/type_change_origin/create_table.hql
  docker/thirdparties/docker-compose/hive/scripts/data/multi_catalog/type_change_origin/data.tar.gz
  docker/thirdparties/docker-compose/hive/scripts/data/multi_catalog/type_change_origin/run.sh
  docker/thirdparties/docker-compose/hive/scripts/data/multi_catalog/type_change_parquet/create_table.hql
  docker/thirdparties/docker-compose/hive/scripts/data/multi_catalog/type_change_parquet/data.tar.gz
  docker/thirdparties/docker-compose/hive/scripts/data/multi_catalog/type_change_parquet/run.sh
  regression-test/data/external_table_p0/hive/test_hive_schema_change.out
  regression-test/data/external_table_p0/hive/test_hive_star_qualifier.out
  regression-test/data/external_table_p0/hive/test_multi_langs.out
  regression-test/suites/external_table_p0/hive/test_hive_schema_change.groovy
  regression-test/suites/external_table_p0/hive/test_hive_star_qualifier.groovy
  regression-test/suites/external_table_p0/hive/test_multi_langs.groovy
  regression-test/suites/external_table_p2/hive/test_multi_langs.groovy
Labels: approved, reviewed

#37168 [fix](nereids) the stop watch is not reset
  fe/fe-core/src/main/java/org/apache/doris/nereids/NereidsPlanner.java
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x

#36889 [Test](iceberg-writer) Add iceberg partition transform unit tests and fix some issues.
  be/src/vec/sink/writer/iceberg/partition_transformers.cpp
  be/src/vec/sink/writer/iceberg/partition_transformers.h
  be/test/vec/sink/writer/iceberg/partition_transformers_test.cpp
Labels: approved, reviewed, dev/2.1.x

#37171 [fix](compaction) fix null pointer when retrieving CPU load average
  be/src/olap/olap_server.cpp
  be/src/util/system_metrics.cpp
Labels: approved, reviewed

#37170 [enhancement](trash) support skip trash, update trash default expire time
  be/src/common/config.cpp
  be/src/olap/data_dir.cpp
Labels: approved, reviewed, kind/behavior-changed, dev/2.1.x

#37085 [Fix](Prepared Statment) use fixed charset to init StringLiteral
  fe/fe-core/src/main/java/org/apache/doris/analysis/StringLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
Labels: area/planner

#36990 [bugfix]thread pool resource leak
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HMSTransaction.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/ThriftHMSCachedClient.java
Labels: approved, reviewed

#37186 [opt](autoinc) Forbid some schema change when the table has auto-increment column
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
  regression-test/data/schema_change_p0/test_schema_change_auto_inc.out
  regression-test/suites/schema_change_p0/test_schema_change_auto_inc.groovy
Labels: approved, reviewed, dev/2.1.x

#37241 [enhancement](regression-test) dup modify case
  regression-test/data/schema_change_p0/test_dup_schema_value_modify3.out
  regression-test/suites/schema_change_p0/test_dup_schema_value_modify3.groovy
Labels: approved, reviewed

#37137 [enhancement](regression-test) dup modify case
  regression-test/data/schema_change_p0/test_dup_schema_value_modify1.out
  regression-test/suites/schema_change_p0/test_dup_schema_value_modify1.groovy
Labels: approved, reviewed

#37111 [enhancement](regression-test) dup modify case
  regression-test/data/schema_change_p0/test_dup_schema_value_modify.out
  regression-test/suites/schema_change_p0/test_dup_schema_value_modify.groovy
Labels: approved, reviewed

#37154 [fix](nereids)mv selection should rule out shadow index from schema change
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/InitMaterializationContextHook.java
Labels: approved, reviewed, not-merge/2.1

#37233 [Fix](regression) Fix cluster privilege for workload group case in cloud mode
  regression-test/suites/workload_manager_p0/test_curd_wlg.groovy
Labels: approved, reviewed

#37016 [chore](join) delete code that's useless
  be/src/pipeline/exec/hashjoin_probe_operator.cpp
  be/src/pipeline/exec/hashjoin_probe_operator.h
Labels: approved, reviewed

#37212 [fix](spill) handle possible filesystem exception
  be/src/vec/spill/spill_stream_manager.cpp
Labels: approved, reviewed

#37206 [Fix](auth)add user cluster USAGE_PRIV in cloud mode
  regression-test/suites/auth_p0/test_master_slave_consistency_auth.groovy
  regression-test/suites/auth_p0/test_select_column_auth.groovy
  regression-test/suites/auth_up_down_p0/load.groovy
Labels: approved, reviewed

#36710 [chore](log) reduce print warning msg during be starting up
  be/src/runtime/fragment_mgr.cpp
Labels: approved, reviewed, dev/2.1.x

#37144 [spill](logs) add logs to debug spill bugs
  be/src/pipeline/dependency.cpp
  be/src/pipeline/exec/partitioned_hash_join_probe_operator.cpp
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/pipeline/pipeline_task.cpp
  be/src/runtime/runtime_state.h
Labels: approved, reviewed

#36848 [refact](meta-service) Split `commit_txn` into several functions
  cloud/src/meta-service/meta_service.h
  cloud/src/meta-service/meta_service_txn.cpp
Labels: approved, reviewed

#37062 [Refactor](timezone) refactor tzdata load to accelerate and unify timezone parsing
  .gitignore
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/runtime/exec_env_init.cpp
  be/src/util/timezone_utils.cpp
  be/src/util/timezone_utils.h
  be/test/vec/function/function_time_test.cpp
  be/test/vec/utils/arrow_column_to_doris_column_test.cpp
  build.sh
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/DateLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/DateTimeLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/DateTimeFormatterUtils.java
  regression-test/data/datatype_p0/datetimev2/test_timezone.out
  regression-test/data/datatype_p0/datetimev2/test_tz_streamload.csv
  regression-test/data/datatype_p0/datetimev2/test_tz_streamload2.csv
  regression-test/suites/datatype_p0/datetimev2/test_timezone.groovy
  regression-test/suites/datatype_p0/datetimev2/test_tz_streamload.groovy
  regression-test/suites/external_table_p0/jdbc/test_jdbc_query_mysql.groovy
  regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_by_fe.groovy
  regression-test/suites/nereids_p0/sql_functions/datetime_functions/test_date_function.groovy
  regression-test/suites/query_p0/sql_functions/datetime_functions/test_date_function.groovy
  resource/zoneinfo.tar.gz
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x

#36803 [regression](set) add test case for set operator
  regression-test/data/query_p0/set_operations/sql/intersect_nullable_not_nullable.out
  regression-test/suites/query_p0/set_operations/sql/intersect_nullable_not_nullable.groovy
Labels: approved, reviewed

#37239 [chore](Nereids) let nereids planner be EXPERIMENTAL_ONLINE
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
Labels: approved, reviewed

#37248 [spill](regression test) check spill temporary files are deleted after all cases are done
  be/src/vec/spill/spill_stream_manager.cpp
  regression-test/suites/check_before_quit/check_before_quit.groovy
Labels: approved, reviewed

#37176 [improve](serde) support json string format with escaped charactors
  be/src/vec/data_types/serde/data_type_string_serde.h
  be/src/vec/functions/function_cast.h
  regression-test/data/jsonb_p0/test_jsonb_cast.csv
  regression-test/data/jsonb_p0/test_jsonb_cast.out
  regression-test/suites/jsonb_p0/test_jsonb_cast.groovy
Labels: approved, reviewed

#37187 [fix](HadoopLz4BlockCompression)Fixed the bug that HadoopLz4BlockCompression creates _decompressor every time it decompresses.
  be/src/util/block_compression.cpp
Labels: approved, reviewed, dev/2.1.x

#37263 [Fix]check nullptr when log thread num
  be/src/runtime/workload_group/workload_group.cpp
Labels: approved, reviewed, workload-group

#37202 [Fix](case) add log for flink connector case download file
  regression-test/suites/flink_connector_p0/flink_connector_syncdb.groovy
Labels: approved, reviewed

#37205 [dependencies](fe)upgrade paimon to 0.8.1
  fe/pom.xml
Labels: approved, reviewed, dev/2.1.x

#37256 [fix](regression) Fix p0 case `test_modify_reorder_column`
  regression-test/data/schema_change_p0/test_modify_reorder_column.out
Labels: approved, reviewed

#37261 [fix](recyclebin) db can not be serialized with gson directly.
  fe/fe-common/src/main/java/org/apache/doris/common/FeMetaVersion.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/CatalogRecycleBin.java
Labels: approved, reviewed, meta-change

#37120 [refactor](spill) Refactor logics of spilling
  be/src/agent/workload_group_listener.cpp
  be/src/pipeline/exec/sort_sink_operator.cpp
  be/src/pipeline/exec/sort_sink_operator.h
  be/src/pipeline/exec/spill_sort_sink_operator.cpp
  be/src/pipeline/exec/spill_sort_sink_operator.h
  be/src/pipeline/exec/spill_sort_source_operator.cpp
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/pipeline/pipeline_task.cpp
  be/src/pipeline/pipeline_task.h
  be/src/runtime/workload_group/workload_group.cpp
  be/src/runtime/workload_group/workload_group.h
  be/src/vec/common/sort/sorter.h
  fe/fe-core/src/main/java/org/apache/doris/planner/SortNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  gensrc/thrift/PlanNodes.thrift
Labels: approved, reviewed, meta-change

#37244 [improvement](jdbc catalog) Delete unnecessary schema and optimize insert logic
  fe/fe-core/src/main/java/org/apache/doris/analysis/NativeInsertStmt.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/client/JdbcClient.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/client/JdbcMySQLClient.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/client/JdbcOracleClient.java
  regression-test/data/external_table_p0/jdbc/test_mysql_jdbc_catalog.out
  regression-test/suites/external_table_p0/jdbc/test_mysql_jdbc_catalog.groovy
Labels: area/planner, kind/test, approved, reviewed

#37002 [fix](group commit) Fix group commit in nereids
  be/src/pipeline/exec/group_commit_block_sink_operator.cpp
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/group_commit_mgr.cpp
  be/src/runtime/group_commit_mgr.h
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/GroupCommitInsertExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/InsertIntoTableCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/OlapGroupCommitInsertExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/OlapInsertExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/OlapTxnInsertExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  gensrc/thrift/FrontendService.thrift
  regression-test/suites/insert_p0/insert_group_commit_into.groovy
  regression-test/suites/insert_p0/insert_group_commit_into_max_filter_ratio.groovy
  regression-test/suites/insert_p0/insert_group_commit_into_unique.groovy
  regression-test/suites/insert_p0/insert_group_commit_into_unique_sync_mode.groovy
  regression-test/suites/insert_p0/test_group_commit_timeout.groovy
Labels: approved, reviewed, meta-change

#37273 [Bug](runtime-filter) fix some rf error problems
  be/src/exprs/runtime_filter.cpp
  be/src/exprs/runtime_filter_slots.h
  be/src/pipeline/pipeline_fragment_context.h
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/runtime_filter_mgr.cpp
Labels: approved, reviewed, dev/2.1.x

#37218 [improvement](statistics)Enable estimate hive table row count using file size.
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HMSExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/qe/GlobalVariable.java
  regression-test/suites/external_table_p0/hive/test_hive_partition_column_analyze.groovy
Labels: approved, reviewed, dev/2.1.x

#37291 [enhance](Recycler) Make sheme of request to object storage a config
  cloud/src/common/config.h
  cloud/src/recycler/s3_accessor.cpp
Labels: approved, reviewed, dev/3.0.x

#37298 [enhance](Recycler) Catch RequestFailedException for all azure request
  cloud/src/recycler/azure_obj_client.cpp
Labels: approved, reviewed, dev/3.0.x

#37091 [case](restart_fe) add demo case for restart_fe test
  regression-test/README.md
  regression-test/data/javaudf_p0/null/test.out
  regression-test/suites/auth_up_down_p0/load.groovy
  regression-test/suites/auth_up_down_p0/test_grant_revoke_auth.groovy
  regression-test/suites/javaudf_p0/null/load.groovy
  regression-test/suites/javaudf_p0/null/test.groovy
  regression-test/suites/javaudf_p0/test_javaudf_null.groovy
Labels: approved, reviewed

#37082 [fix](manager)fix manager interface case.
  regression-test/suites/manager/test_manager_interface_1.groovy
  regression-test/suites/manager/test_manager_interface_2.groovy
Labels: approved, reviewed

#37203 [fix](fe) Remove cloudWarmUpJob from DEPRECATED_MODULES_NAMES
  fe/fe-core/src/main/java/org/apache/doris/persist/meta/MetaPersistMethod.java
  fe/fe-core/src/main/java/org/apache/doris/persist/meta/PersistMetaModules.java
Labels: approved, reviewed, meta-change, dev/3.0.x

#37308 [enhance](Azure) Use s3Uri to specify the object's bucket and key for azure in FE
  fe/fe-core/src/main/java/org/apache/doris/fs/obj/AzureObjStorage.java
  fe/fe-core/src/main/java/org/apache/doris/fs/remote/AzureFileSystem.java
Labels: approved, reviewed, dev/3.0.x

#37240 [fix](TVF) Enable azure tvf without specifying s3 bucket property.
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/S3TableValuedFunction.java
Labels: approved, reviewed, dev/3.0.x

#37267 [chore](cloud) add selected partition ids and visible version in log
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
Labels: approved, reviewed

#37297 [pipeline](fix) Set upstream operators always runnable once source operator closed
  be/src/pipeline/exec/operator.cpp
Labels: approved, reviewed, usercase, dev/2.1.x

#37195 [pipeline](datagen) Improve datagen operator parallelism
  be/src/pipeline/exec/datagen_operator.cpp
  be/src/pipeline/pipeline_fragment_context.cpp
  fe/fe-core/src/main/java/org/apache/doris/planner/DataGenScanNode.java
  regression-test/pipeline/cloud_p1/conf/regression-conf-custom.groovy
  regression-test/pipeline/p1/conf/regression-conf.groovy
  regression-test/suites/correctness_p0/test_assert_row_num.groovy
  regression-test/suites/external_table_p0/tvf/test_numbers.groovy
Labels: approved, reviewed

#37201 [fix](case)Fix case failure caused by different pipeline configurations
  regression-test/suites/external_table_p0/tvf/test_partitions_tvf.groovy
  regression-test/suites/external_table_p0/tvf/test_s3_tvf_with_resource.groovy
Labels: approved, reviewed, dev/2.1.x

#37295 [fix](fe) Fix the sql of AddPartitionRecord
  fe/fe-core/src/main/java/org/apache/doris/binlog/AddPartitionRecord.java
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x

#37282 [Improvement](scan) Refine ignoring data distribution without join
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
Labels: approved, reviewed

#37277 [fix](partitionkey) serialize expr in PartitionKey via gson
  fe/fe-common/src/main/java/org/apache/doris/catalog/PrimitiveType.java
  fe/fe-common/src/main/java/org/apache/doris/common/FeMetaVersion.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Index.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/MaterializedIndexMeta.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Partition.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/PartitionKey.java
Labels: approved, reviewed, meta-change, dev/3.0.x

#35891 [feature](move-memtable) support for inverted index file
  be/src/io/fs/stream_sink_file_writer.cpp
  be/src/io/fs/stream_sink_file_writer.h
  be/src/olap/delta_writer_v2.cpp
  be/src/olap/rowset/beta_rowset_writer.cpp
  be/src/olap/rowset/beta_rowset_writer.h
  be/src/olap/rowset/beta_rowset_writer_v2.cpp
  be/src/olap/rowset/beta_rowset_writer_v2.h
  be/src/olap/rowset/rowset_writer.h
  be/src/olap/rowset/rowset_writer_context.h
  be/src/olap/rowset/segment_creator.cpp
  be/src/olap/rowset/segment_creator.h
  be/src/olap/rowset/segment_v2/inverted_index_file_writer.cpp
  be/src/olap/rowset/segment_v2/inverted_index_file_writer.h
  be/src/olap/rowset/segment_v2/inverted_index_fs_directory.cpp
  be/src/olap/rowset/segment_v2/inverted_index_fs_directory.h
  be/src/olap/rowset/segment_v2/segment_writer.cpp
  be/src/olap/rowset/segment_v2/segment_writer.h
  be/src/olap/rowset/segment_v2/vertical_segment_writer.cpp
  be/src/olap/rowset/segment_v2/vertical_segment_writer.h
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/runtime/load_stream.cpp
  be/src/runtime/load_stream.h
  be/src/runtime/load_stream_writer.cpp
  be/src/runtime/load_stream_writer.h
  be/src/util/thrift_util.cpp
  be/src/util/thrift_util.h
  be/src/vec/sink/load_stream_stub.cpp
  be/src/vec/sink/load_stream_stub.h
  be/test/io/fs/stream_sink_file_writer_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapTableSink.java
  gensrc/proto/internal_service.proto
  gensrc/proto/olap_common.proto
  gensrc/thrift/Descriptors.thrift
  regression-test/data/inverted_index_p0/load/test_insert.out
  regression-test/data/inverted_index_p0/load/test_stream_load.out
  regression-test/data/inverted_index_p0/test_index_lowercase_fault_injection.out
  regression-test/data/inverted_index_p2/load_with_inverted_index_p2/test_stream_load_with_inverted_index.out
  regression-test/suites/fault_injection_p0/test_delta_writer_v2_back_pressure_fault_injection.groovy
  regression-test/suites/fault_injection_p0/test_load_stream_fault_injection.groovy
  regression-test/suites/inverted_index_p0/load/test_insert.groovy
  regression-test/suites/inverted_index_p0/load/test_spark_load.groovy
  regression-test/suites/inverted_index_p0/load/test_stream_load.groovy
  regression-test/suites/inverted_index_p0/test_index_lowercase_fault_injection.groovy
  regression-test/suites/inverted_index_p2/load_with_inverted_index_p2/test_stream_load_with_inverted_index.groovy
  regression-test/suites/inverted_index_p2/test_insert_into_index.groovy
  regression-test/suites/load_p0/http_stream/test_http_stream.groovy
  regression-test/suites/load_p0/mysql_load/test_mysql_load.groovy
  regression-test/suites/load_p0/mysql_load/test_mysql_load_big_file.groovy
Labels: approved, reviewed, meta-change
