Repository apache/doris, pull requests merged in 2025-09, with the labels that each got.

#55501 [chore](compile) Add COMPILE_CHECK for some files
  be/src/pipeline/exec/spill_sort_sink_operator.cpp
  be/src/pipeline/exec/spill_sort_sink_operator.h
  be/src/pipeline/exec/spill_sort_source_operator.cpp
  be/src/pipeline/exec/spill_sort_source_operator.h
  be/src/runtime/descriptors.cpp
  be/src/runtime/descriptors.h
  be/src/util/brpc_client_cache.cpp
  be/src/util/brpc_client_cache.h
Labels: approved, reviewed

#55490 [Enchancement](bitmap) reserve set on BitmapValue::deserialize
  be/src/util/bitmap_value.h
Labels: approved, reviewed

#54933 [refactore](cloud) separate cloud restore create tablet rpc into multiple batches
  cloud/src/recycler/recycler.cpp
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/backup/CloudRestoreJob.java
Labels: approved, reviewed, dev/3.1.x

#55473 [test](docker) adapt paimon on hms and gcs
  docker/thirdparties/docker-compose/hive/hadoop-hive-3x.env.tpl
  docker/thirdparties/docker-compose/hive/hive-3x_settings.env
  docker/thirdparties/docker-compose/hive/scripts/create_external_paimon_scripts/create_paimon_tables.hql
  docker/thirdparties/docker-compose/hive/scripts/hive-metastore.sh
Labels: approved, reviewed, dev/3.1.x

#55273 [Chore](nereids) remove CreateMaterializedViewStmt
  fe/fe-core/src/main/java/org/apache/doris/alter/Alter.java
  fe/fe-core/src/main/java/org/apache/doris/alter/MaterializedViewHandler.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateMaterializedViewStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/qe/DdlExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/alter/MaterializedViewHandlerTest.java
  fe/fe-core/src/test/java/org/apache/doris/alter/RollupJobV2Test.java
Labels: approved, reviewed

#55407 [fix](unique function) add between back for fix unique function
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/ExpressionAnalyzer.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/Between.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Random.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/ExpressionVisitor.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/PlanUtils.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/parser/BetweenTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/expression/SimplifyRangeTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/expressions/ExpressionEqualsTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/expressions/ExpressionParserTest.java
  regression-test/data/nereids_rules_p0/unique_function/between_with_unique_function.out
  regression-test/suites/nereids_rules_p0/unique_function/between_with_unique_function.groovy
Labels: approved, reviewed

#55417 [fix](unique function) fix in predicate extract non-constant for unique function
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/InPredicateExtractNonConstant.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/expression/rules/ExpressionRewriteSqlTest.java
Labels: approved, reviewed

#55457 [chore](format) Remove benchmark dir from code style check dirs
  build-support/clang-format.sh
Labels: approved, reviewed

#55476 [opt](nereids) improve performance of cast big string to complex type
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/FoldConstantRuleOnFE.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/StringLikeLiteral.java
Labels: approved, reviewed, dev/3.1.x

#55379 [Fix](iceberg) Fix NoSuchElementException in IcebergSysTableJniScanner when reading empty system tables
  fe/be-java-extensions/iceberg-metadata-scanner/src/main/java/org/apache/doris/iceberg/IcebergSysTableJniScanner.java
Labels: approved, reviewed, dev/3.1.0-merged

#55408 [fix](test) The table_version is strictly increasing but non-consecutive
  regression-test/suites/table_p0/test_table_version.groovy
Labels: approved, reviewed, cloud, snapshot

#55508 [Chore](nereids) optimize iter in validate()
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/AdminCopyTabletCommand.java
Labels: approved, reviewed

#55516 [chore](test) enable logging conflict keys in regression test
  regression-test/pipeline/cloud_p0/conf/ms_custom.conf
  regression-test/pipeline/cloud_p1/conf/ms_custom.conf
  regression-test/pipeline/vault_p0/conf/ms_custom.conf
Labels: approved, reviewed

#55509 [fix](load): fix incorrect progress on finished loads
  be/src/runtime/fragment_mgr.cpp
Labels: approved, reviewed, usercase, dev/3.0.x, dev/3.1.x

#55155 [chore](object client) Adjust object storage sdk log level from `WARN` to `ERROR`
  be/src/common/config.cpp
  cloud/src/common/config.h
  conf/be.conf
Labels: approved, reviewed

#55520 [test](nereids) add ut for sql cache/sorted partition cache
  fe/fe-core/src/main/java/org/apache/doris/common/cache/NereidsSortedPartitionsCacheManager.java
  fe/fe-core/src/main/java/org/apache/doris/common/cache/NereidsSqlCacheManager.java
  fe/fe-core/src/test/java/org/apache/doris/qe/SortedPartitionsCacheTest.java
  fe/fe-core/src/test/java/org/apache/doris/qe/SqlCacheTest.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/TestWithFeService.java
Labels: approved, reviewed, dev/3.1.x

#55484 [test](iceberg) add polaris test
  docker/thirdparties/docker-compose/polaris/docker-compose.yaml.tpl
  docker/thirdparties/docker-compose/polaris/init-catalog.sh
  docker/thirdparties/docker-compose/polaris/polaris_settings.env
  docker/thirdparties/run-thirdparties-docker.sh
  regression-test/conf/regression-conf.groovy
  regression-test/pipeline/external/conf/regression-conf.groovy
  regression-test/pipeline/nonConcurrent/conf/regression-conf.groovy
  regression-test/pipeline/p0/conf/regression-conf.groovy
  regression-test/suites/external_table_p0/polaris/test_polaris.groovy
Labels: approved, reviewed, dev/3.1.x

#55322 [fix](cast)Update float/double to string format.
  fe/fe-core/src/main/java/org/apache/doris/analysis/FloatLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/DoubleLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/FloatLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/FractionalLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/format/FractionalFormat.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/FloatLiteralTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/expressions/literal/DoubleLiteralTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/expressions/literal/FloatLiteralTest.java
  regression-test/data/correctness_p0/test_cast_null.out
  regression-test/data/query_p0/cast/test_cast.out
  regression-test/suites/query_p0/cast/test_cast.groovy
Labels: approved, reviewed

#55055 branch-3.0: [enhance](transaction) add completeness of commit tablet info check in cloud mode (#53979)
  be/src/vec/sink/writer/vtablet_writer.cpp
  fe/fe-core/src/main/java/org/apache/doris/cloud/transaction/CloudGlobalTransactionMgr.java
  regression-test/suites/fault_injection_p0/test_incomplete_commit_info.groovy
Labels: approved, reviewed

#55532 [fix](cloud) Fix get_tablet_compact_stats
  cloud/src/meta-store/meta_reader.cpp
  cloud/test/meta_reader_test.cpp
Labels: approved, reviewed, cloud, snapshot

#54590 [test](iceberg) Add iceberg rest test for different storage
  docker/thirdparties/docker-compose/iceberg-rest/docker-compose.yaml.tpl
  docker/thirdparties/docker-compose/iceberg-rest/iceberg-rest_settings.env
  docker/thirdparties/run-thirdparties-docker.sh
  regression-test/conf/regression-conf.groovy
  regression-test/pipeline/external/conf/regression-conf.groovy
  regression-test/pipeline/nonConcurrent/conf/regression-conf.groovy
  regression-test/pipeline/p0/conf/regression-conf.groovy
  regression-test/suites/external_table_p2/iceberg/iceberg_rest_s3_storage_test.groovy
Labels: approved, reviewed, dev/3.1.0-merged

#55548 fix(docker): disaggregated probe does not support ipv6
  docker/runtime/be/resource/be_disaggregated_probe.sh
  docker/runtime/fe/resource/fe_disaggregated_probe.sh
Labels: approved, reviewed

#55256 [fix](maxcompute)fix maxcompute catalog international user can not access.
  fe/fe-core/src/main/java/org/apache/doris/datasource/maxcompute/MaxComputeExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/constants/MCProperties.java
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x

#55552 [fix](compile) Fix compile warnings and errors
  be/src/olap/rowset/segment_v2/indexed_column_writer.cpp
  be/src/olap/task/index_builder.cpp
  be/src/olap/task/index_builder.h
Labels: approved, reviewed

#55498 [Fix](Load) Use deferred file format properties for broker load without format (#55450)
  fe/fe-core/src/main/java/org/apache/doris/analysis/DataDescription.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/fileformat/DeferredFileFormatProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/fileformat/FileFormatProperties.java
  fe/fe-core/src/main/java/org/apache/doris/load/BrokerFileGroup.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BrokerLoadPendingTask.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/MysqlLoadManager.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/load/NereidsDataDescription.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/load/MysqlDataDescription.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/load/MysqlLoadCommand.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/commands/LoadCommandTest.java
  regression-test/suites/ddl_p0/test_create_table_generated_column/stream_load_and_mysql_load.groovy
  regression-test/suites/external_table_p0/refactor_storage_param/hdfs_load_default_file_format.groovy
Labels: approved, reviewed, dev/3.1.0-merged

#55555 [opt](properties) remove old dlf properties
  fe/fe-core/src/main/java/org/apache/doris/catalog/HMSResource.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/PrintableMap.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/lakesoul/LakeSoulExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/ConnectorPropertiesUtils.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/ConnectorProperty.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/PropertyConverter.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/constants/DLFProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/metastore/AliyunDLFBaseProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/metastore/AliyunDLFProperties.java
  fe/fe-core/src/test/java/org/apache/doris/common/util/PrintableMapTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/property/PropertyConverterTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/property/metastore/AliyunDLFBasePropertiesTest.java
Labels: approved, reviewed, dev/3.1.x

#55550 [fix](compaction) skip tablets with compaction score 0 during compaction
  be/src/olap/tablet_manager.cpp
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x, dev/3.1.x

#55063 [enhance](csv reader) limit csv line reader output buffer size
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/vec/exec/format/file_reader/new_plain_text_line_reader.cpp
  be/src/vec/exec/format/file_reader/new_plain_text_line_reader.h
  regression-test/suites/load_p0/stream_load/test_csv_buffer_size_limit.groovy
Labels: approved, reviewed

#55127 [fix](variant) compaction compatible with both the old and new versions of variant.
  be/src/olap/rowset/segment_v2/variant/variant_column_reader.cpp
  be/src/vec/common/schema_util.cpp
  be/src/vec/common/schema_util.h
  be/test/vec/common/schema_util_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/CreateTableInfo.java
  regression-test/data/variant_p0/predefine/test_predefine_ddl.out
  regression-test/data/variant_p0/predefine/variant_different_max_subcolumns_count.out
  regression-test/suites/variant_github_events_new_p0/load.groovy
  regression-test/suites/variant_github_events_nonConcurrent_p2/load.groovy
  regression-test/suites/variant_p0/agg.groovy
  regression-test/suites/variant_p0/predefine/delete_update.groovy
  regression-test/suites/variant_p0/predefine/insert_into_select.groovy
  regression-test/suites/variant_p0/predefine/load.groovy
  regression-test/suites/variant_p0/predefine/multi_var.groovy
  regression-test/suites/variant_p0/predefine/test_multi_index_nonCurrent.groovy
  regression-test/suites/variant_p0/predefine/test_predefine_ddl.groovy
  regression-test/suites/variant_p0/predefine/test_predefine_pattern.groovy
  regression-test/suites/variant_p0/predefine/variant_different_max_subcolumns_count.groovy
  regression-test/suites/variant_p0/predefine/variant_hirachinal.groovy
  regression-test/suites/variant_p0/schema_change/test_add_multi_var_mulit_indexes.groovy
Labels: approved, reviewed

#55545 [fix](nereids)use bigint instead of int literal to compare with count() agg function
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/SubqueryToApply.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/ExistsApplyToJoin.java
Labels: approved, reviewed, dev/3.1.x

#55542 [fix][vcg] Fix SystemInfoService cannot be cast to CloudSystemInfoSer…
  fe/fe-core/src/main/java/org/apache/doris/qe/AuditLogHelper.java
Labels: approved, reviewed

#55592 [fix](test) Support discontinuous table version
  regression-test/suites/statistics/analyze_stats.groovy
Labels: approved, reviewed, cloud, snapshot

#55585 [fix](cloud) Init instance multi version status
  cloud/src/resource-manager/resource_manager.cpp
  cloud/test/resource_test.cpp
Labels: approved, reviewed, cloud, snapshot

#55380 [feature]support build index for inverted/ngram in cloud
  be/src/agent/agent_server.cpp
  be/src/agent/task_worker_pool.cpp
  be/src/agent/task_worker_pool.h
  be/src/cloud/cloud_delete_task.cpp
  be/src/cloud/cloud_index_change_compaction.cpp
  be/src/cloud/cloud_index_change_compaction.h
  be/src/cloud/cloud_storage_engine.cpp
  be/src/cloud/cloud_storage_engine.h
  be/src/cloud/cloud_tablet.cpp
  be/src/cloud/cloud_tablet.h
  be/src/cloud/config.cpp
  be/src/cloud/config.h
  be/src/olap/compaction.cpp
  be/src/olap/compaction.h
  be/src/olap/task/engine_cloud_index_change_task.cpp
  be/src/olap/task/engine_cloud_index_change_task.h
  be/test/olap/cloud_index_change_compaction_test.cpp
  be/test/olap/cloud_index_change_task_test.cpp
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/alter/IndexChangeJob.java
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/BuildIndexClause.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Index.java
  fe/fe-core/src/main/java/org/apache/doris/load/DeleteJob.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/BuildIndexOp.java
  fe/fe-core/src/main/java/org/apache/doris/task/AlterInvertedIndexTask.java
  fe/fe-core/src/main/java/org/apache/doris/task/PushTask.java
  gensrc/thrift/AgentService.thrift
  regression-test/plugins/plugin_index_change.groovy
  regression-test/suites/index_p0/test_ngram_bloomfilter_index_change.groovy
  regression-test/suites/inverted_index_p0/index_format_v2/test_add_build_index_with_format_v2.groovy
Labels: approved, reviewed

#55465 [refactor](predicate) remove 'can_do_apply_safe' on column predicate
  be/src/olap/accept_null_predicate.h
  be/src/olap/bitmap_filter_predicate.h
  be/src/olap/block_column_predicate.h
  be/src/olap/bloom_filter_predicate.h
  be/src/olap/column_predicate.h
  be/src/olap/comparison_predicate.h
  be/src/olap/in_list_predicate.h
  be/src/olap/like_column_predicate.h
  be/src/olap/null_predicate.h
  be/src/olap/rowset/segment_v2/segment.cpp
  be/src/olap/rowset/segment_v2/segment.h
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/olap/shared_predicate.h
  regression-test/data/variant_p0/cast.out
  regression-test/suites/variant_p0/cast.groovy
Labels: approved, reviewed

#55596 [improvement](compile) enable compile check for some files
  be/src/exec/decompressor.h
  be/src/exec/schema_scanner/schema_encryption_keys_scanner.cpp
  be/src/runtime/decimalv2_value.cpp
  be/src/runtime/decimalv2_value.h
  be/src/runtime/result_block_buffer.cpp
  be/src/util/arrow/block_convertor.cpp
  be/src/util/block_compression.cpp
  be/src/vec/common/custom_allocator.h
Labels: approved, reviewed

#55421 [refactor](exec) Refactor BE floating-point comparisons.
  be/src/common/compare.h
  be/src/vec/aggregate_functions/aggregate_function_min_max.h
  be/src/vec/columns/column_vector.cpp
  be/src/vec/columns/column_vector.h
  be/src/vec/core/accurate_comparison.h
  be/src/vec/core/sort_block.h
  be/src/vec/functions/functions_comparison.h
  regression-test/data/correctness/test_compare_float.out
  regression-test/data/datatype_p0/double/test_double_special_values.out
  regression-test/data/datatype_p0/float/test_float_special_values.out
  regression-test/suites/correctness/test_compare_float.groovy
Labels: approved, reviewed

#55241 [chore](sk) Encrypt `secret key` and hide `access key` for log
  be/src/cloud/cloud_meta_mgr.cpp
  be/src/util/s3_util.cpp
  be/src/util/s3_util.h
  be/test/util/s3_util_test.cpp
  cloud/src/meta-service/meta_service.cpp
  cloud/src/meta-service/meta_service_helper.h
  cloud/src/meta-service/meta_service_http.cpp
  cloud/src/meta-service/meta_service_resource.cpp
  cloud/src/resource-manager/resource_manager.cpp
  cloud/test/meta_service_http_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/cloud/system/CloudSystemInfoService.java
Labels: approved, reviewed, usercase, dev/3.0.x, dev/3.1.x

#55562 [chore](compile check) Fix compile check
  be/src/util/runtime_profile.cpp
  be/src/util/runtime_profile.h
  be/src/util/runtime_profile_counter_tree_node.cpp
  be/src/util/runtime_profile_counter_tree_node.h
  be/src/util/system_metrics.cpp
Labels: approved, reviewed

#55571 [Chore](compile) add compile_check for some external connector
  be/src/exec/es/es_scroll_parser.cpp
  be/src/vec/exec/jni_connector.cpp
  be/src/vec/exec/jni_connector.h
  be/src/vec/exec/vjdbc_connector.cpp
Labels: approved, reviewed

#55574 [opt](txn lazy commit) Make convert tmp rowsets batch more adaptive (#55035)
  cloud/src/common/config.h
  cloud/src/meta-service/txn_lazy_committer.cpp
  cloud/test/txn_lazy_commit_test.cpp
Labels: approved, reviewed

#55591 [fix](proto) fix miss-ordered proto
  gensrc/proto/cloud.proto
Labels: approved, reviewed

#55568 [Chore](compile) add compile check in llm
  be/src/vec/functions/llm/functions_llm.h
  be/src/vec/functions/llm/llm_adapter.h
  fe/fe-core/src/main/java/org/apache/doris/catalog/LLMResource.java
  gensrc/thrift/PaloInternalService.thrift
Labels: approved, reviewed, meta-change

#55593 [chore](function) remove useless code in function conv
  be/src/vec/functions/function_conv.cpp
Labels: approved, reviewed

#55505 [chore](compile) fix some implicit conversions
  be/src/cloud/cloud_snapshot_loader.h
  be/src/cloud/cloud_snapshot_mgr.cpp
  be/src/cloud/cloud_warm_up_manager.cpp
  be/src/exec/tablet_info.h
Labels: approved, reviewed

#55582 [Enhancement](check) Add compile check for some files
  be/src/util/cpu_info.cpp
  be/src/util/cpu_info.h
  be/src/util/date_func.cpp
  be/src/util/date_func.h
  be/src/util/mysql_row_buffer.cpp
  be/src/util/time_lut.cpp
  be/src/util/time_lut.h
  be/src/vec/runtime/vdatetime_value.h
Labels: approved, reviewed

#55610 [fix](filecache) no fd num limit for segment cache when cloud mode
  be/src/runtime/exec_env_init.cpp
Labels: approved, reviewed, dev/3.1.x

#55613 [fix](case) fix case: variant build index
  regression-test/suites/variant_github_events_nonConcurrent_p2/load.groovy
Labels: approved, reviewed, dev/3.0.x, p0_test

#55632 [chore](compile) Fix implicit conversion in stream_load_forward_handler
  be/src/http/action/stream_load_forward_handler.cpp
  be/src/http/action/stream_load_forward_handler.h
Labels: approved, reviewed

#55588 [fix](case) fix test_paimon_schema_change case error
  regression-test/data/external_table_p0/paimon/test_paimon_schema_change.out
Labels: approved, reviewed

#55605 [Improvement](projection) reduce shuffle_columns overhead
  be/src/vec/core/block.cpp
Labels: approved, reviewed

#55606 [Fix](case) Fix some cases
  regression-test/suites/fault_injection_p0/partial_update/test_delete_publish_skip_read.groovy
  regression-test/suites/fault_injection_p0/partial_update/test_partial_update_conflict_skip_compaction.groovy
  regression-test/suites/fault_injection_p0/partial_update/test_partial_update_with_delete_col_in_publish.groovy
  regression-test/suites/unique_with_mow_p0/partial_update/test_partial_update_merge_type.groovy
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x, p0_test

#55499 [Feature](llm) Support llm_agg function
  be/src/vec/aggregate_functions/aggregate_function.h
  be/src/vec/aggregate_functions/aggregate_function_llm_agg.cpp
  be/src/vec/aggregate_functions/aggregate_function_llm_agg.h
  be/src/vec/aggregate_functions/aggregate_function_null.h
  be/src/vec/aggregate_functions/aggregate_function_simple_factory.cpp
  be/src/vec/exprs/vectorized_agg_fn.cpp
  be/src/vec/functions/llm/llm_adapter.h
  be/test/llm/aggregate_function_llm_agg_test.cpp
  be/test/vec/aggregate_functions/agg_function_test.h
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinAggregateFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionSet.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/LLMAgg.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/AggregateFunctionVisitor.java
  regression-test/suites/llm_p0/test_llm_functions.groovy
Labels: approved, reviewed

#55124 [enhance](variant)enhance max_sparse_column_statistics_size for variant
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/common/consts.h
  be/src/olap/rowset/segment_v2/variant/variant_column_reader.cpp
  be/src/olap/rowset/segment_v2/variant/variant_column_reader.h
  be/src/olap/rowset/segment_v2/variant/variant_column_writer_impl.cpp
  be/src/olap/rowset/segment_v2/variant_stats_calculator.cpp
  be/src/olap/rowset/segment_v2/variant_stats_calculator.h
  be/src/olap/tablet_meta.cpp
  be/src/olap/tablet_schema.cpp
  be/src/olap/tablet_schema.h
  be/src/vec/common/schema_util.cpp
  be/src/vec/common/schema_util.h
  be/test/olap/rowset/segment_v2/mock/mock_segment.h
  be/test/olap/rowset/segment_v2/variant_column_writer_reader_test.cpp
  be/test/olap/rowset/segment_v2/variant_stats_calculator_test.cpp
  be/test/vec/common/schema_util_test.cpp
  fe/fe-common/src/main/java/org/apache/doris/catalog/ScalarType.java
  fe/fe-common/src/main/java/org/apache/doris/catalog/VariantType.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Column.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/types/DataType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/types/VariantType.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/test/java/org/apache/doris/common/PropertyAnalyzerTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/expressions/functions/ComputeSignatureHelperTest.java
  fe/fe-core/src/test/java/org/apache/doris/persist/ScalarTypeTest.java
  gensrc/proto/olap_file.proto
  gensrc/thrift/Descriptors.thrift
  regression-test/pipeline/cloud_p0/conf/regression-conf-custom.groovy
  regression-test/pipeline/p0/conf/regression-conf.groovy
  regression-test/suites/fault_injection_p0/test_variant_compaction_with_sparse_limit.groovy
  regression-test/suites/variant_p0/predefine/test_variant_compaction_with_sparse_limit.groovy
Labels: approved, reviewed, dev/3.1.x

#55652 [fix](cloud) Versioned read supports empty rowset optimization
  cloud/src/meta-service/meta_service.cpp
  cloud/src/meta-store/meta_reader.cpp
  cloud/src/meta-store/meta_reader.h
  cloud/test/meta_service_versioned_read_test.cpp
Labels: approved, reviewed, cloud, snapshot

#55622 [fix](prepare statement)Allow all commands and queries to execute prepare command.
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/PrepareCommand.java
  regression-test/suites/datatype_p0/double/test_double_special_values.groovy
  regression-test/suites/datatype_p0/float/test_float_special_values.groovy
  regression-test/suites/prepared_stmt_p0/prepare_server_side.groovy
  regression-test/suites/prepared_stmt_p0/prepared_stmt.groovy
  regression-test/suites/variant_p0/variant_with_rowstore.groovy
Labels: approved, reviewed

#55336 [opt](point query) optimize point query
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
Labels: approved, reviewed, dev/3.1.0-merged

#55639 branch-3.0: [Fix](mow) Fix mow coreudmp in `BaseTablet::get_rowset_by_ids()` (#55539)
  be/src/cloud/cloud_rowset_builder.cpp
  be/src/olap/olap_common.h
  be/src/olap/rowset/beta_rowset_writer.cpp
  be/src/olap/rowset/segment_v2/segment_writer.cpp
  be/src/olap/rowset/segment_v2/vertical_segment_writer.cpp
  be/src/olap/rowset_builder.cpp
  be/src/olap/rowset_builder.h
  be/test/olap/segcompaction_mow_test.cpp
Labels: approved, reviewed

#52677 [opt](recycler) Add concurrency recycle for tmp rowset
  cloud/src/recycler/recycler.cpp
  cloud/test/recycler_test.cpp
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x, cloud

#55671 [fix](script)update variable use conffile
  docker/runtime/be/resource/be_disaggregated_entrypoint.sh
Labels: approved, reviewed

#55556 [opt](spill) make spilling operators be blocking mode
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/pipeline/dependency.cpp
  be/src/pipeline/dependency.h
  be/src/pipeline/exec/multi_cast_data_stream_sink.cpp
  be/src/pipeline/exec/multi_cast_data_stream_sink.h
  be/src/pipeline/exec/multi_cast_data_stream_source.cpp
  be/src/pipeline/exec/multi_cast_data_stream_source.h
  be/src/pipeline/exec/multi_cast_data_streamer.cpp
  be/src/pipeline/exec/multi_cast_data_streamer.h
  be/src/pipeline/exec/operator.h
  be/src/pipeline/exec/partitioned_aggregation_sink_operator.cpp
  be/src/pipeline/exec/partitioned_aggregation_sink_operator.h
  be/src/pipeline/exec/partitioned_aggregation_source_operator.cpp
  be/src/pipeline/exec/partitioned_aggregation_source_operator.h
  be/src/pipeline/exec/partitioned_hash_join_probe_operator.cpp
  be/src/pipeline/exec/partitioned_hash_join_probe_operator.h
  be/src/pipeline/exec/partitioned_hash_join_sink_operator.cpp
  be/src/pipeline/exec/partitioned_hash_join_sink_operator.h
  be/src/pipeline/exec/spill_sort_sink_operator.cpp
  be/src/pipeline/exec/spill_sort_sink_operator.h
  be/src/pipeline/exec/spill_sort_source_operator.cpp
  be/src/pipeline/exec/spill_sort_source_operator.h
  be/src/pipeline/exec/spill_utils.h
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/pipeline/pipeline_task.cpp
  be/src/pipeline/pipeline_task.h
  be/src/runtime/query_context.cpp
  be/src/vec/spill/spill_stream_manager.cpp
  be/src/vec/spill/spill_stream_manager.h
  be/test/pipeline/exec/multi_cast_data_streamer_test.cpp
  be/test/pipeline/operator/partitioned_aggregation_sink_operator_test.cpp
  be/test/pipeline/operator/partitioned_aggregation_source_operator_test.cpp
  be/test/pipeline/operator/partitioned_aggregation_test_helper.cpp
  be/test/pipeline/operator/partitioned_hash_join_probe_operator_test.cpp
  be/test/pipeline/operator/partitioned_hash_join_sink_operator_test.cpp
  be/test/pipeline/operator/partitioned_hash_join_test_helper.cpp
  be/test/pipeline/operator/partitioned_hash_join_test_helper.h
  be/test/pipeline/operator/spill_sort_sink_operator_test.cpp
  be/test/pipeline/operator/spill_sort_source_operator_test.cpp
  be/test/pipeline/operator/spillable_operator_test_helper.cpp
  be/test/pipeline/operator/spillable_operator_test_helper.h
  be/test/pipeline/pipeline_task_test.cpp
Labels: approved, reviewed

#55630 [Fix](cloud) `calc_sync_versions` should consider full compaction
  be/src/cloud/cloud_cumulative_compaction_policy.cpp
  be/src/cloud/cloud_full_compaction.cpp
  be/src/cloud/cloud_meta_mgr.cpp
  be/src/cloud/cloud_tablet.h
  cloud/src/meta-service/meta_service.cpp
  cloud/src/meta-service/meta_service_job.cpp
  cloud/test/meta_service_test.cpp
  gensrc/proto/cloud.proto
  regression-test/data/fault_injection_p0/cloud/test_cloud_calc_sync_version.out
  regression-test/suites/fault_injection_p0/cloud/test_cloud_calc_sync_version.groovy
Labels: approved, reviewed, p0_w, dev/3.0.x, dev/3.1.x

#55649 [thirdparty](patch)fix brpc core when enable ssl
  thirdparty/patches/brpc-1.6.0-fix-core-when-enable-SSL.patch
Labels: approved, reviewed, dev/3.1.x

#55658 [thirdparty](patch)brpc force ssl for all connections
  thirdparty/patches/brpc-1.6.0-Force-SSL-for-all-connections-of-Acceptor.patch
Labels: approved, reviewed, dev/3.1.x

#55631 [refactor](array distance) Change return type of array distance functions to AlwaysNotNullable
  be/src/vec/functions/array/function_array_distance.h
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/CosineDistance.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/InnerProduct.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/InnerProductApproximate.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/L1Distance.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/L2Distance.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/L2DistanceApproximate.java
  regression-test/data/nereids_function_p0/scalar_function/Array.out
  regression-test/data/query_p0/sql_functions/array_functions/test_array_distance_functions.out
  regression-test/suites/nereids_function_p0/scalar_function/Array.groovy
  regression-test/suites/query_p0/sql_functions/array_functions/test_array_distance_functions.groovy
Labels: approved, reviewed

#55543 [opt](nereids) sum literal rewrite rule support non slot expression
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/SumLiteralRewrite.java
  regression-test/data/nereids_rules_p0/sumRewrite.out
  regression-test/data/shape_check/clickbench/query30.out
  regression-test/suites/nereids_rules_p0/sumRewrite.groovy
Labels: approved, reviewed

#52004 [regression-test](point query) remove test_point_query nonconcurrent
  regression-test/suites/point_query_p0/test_point_query.groovy
Labels: approved, reviewed, dev/3.0.x

#55687 [fix](case) fix some failure cases
  regression-test/suites/compaction/test_cu_compaction_remove_old_version_delete_bitmap.groovy
  regression-test/suites/fault_injection_p0/cloud/test_cloud_mow_stream_load_with_commit_fail.groovy
  regression-test/suites/fault_injection_p0/cloud/test_cloud_version_already_merged.groovy
Labels: approved, reviewed

#54503 [enhancement](filecache) fix read_cache_file_directly
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/io/cache/block_file_cache.cpp
  be/src/io/cache/block_file_cache.h
  be/src/io/cache/cached_remote_file_reader.cpp
  be/src/io/cache/file_block.h
  be/test/io/cache/block_file_cache_test.cpp
  be/test/io/cache/block_file_cache_test_lru_dump.cpp
Labels: approved, reviewed

#55697 [fix](txn lazy commit) fix txn lazy commit conflict with schema change
  cloud/src/meta-service/txn_lazy_committer.cpp
  cloud/test/txn_lazy_commit_test.cpp
Labels: approved, reviewed

#55668 branch-2.1: [Fix](oss-hdfs)Fix insert failure on Hive partitioned table with oss-hdfs #55565
  fe/fe-core/src/main/java/org/apache/doris/common/util/LocationPath.java
  fe/fe-core/src/test/java/org/apache/doris/fs/remote/RemoteFileSystemTest.java
Labels: approved, reviewed

#54842 [enchement](tvf)support tvf topn lazy materialize.
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/PhysicalPlanTranslator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/materialize/LazyMaterializeTopN.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/materialize/LazySlotPruning.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/materialize/MaterializeProbeVisitor.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/materialize/MaterializeSource.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/BindExpression.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/BindRelation.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/implementation/LogicalTVFRelationToPhysicalTVFRelation.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/OperativeColumnDerive.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalTVFRelation.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalLazyMaterialize.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalLazyMaterializeTVFScan.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalTVFRelation.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/PlanVisitor.java
  regression-test/data/external_table_p0/tvf/test_tvf_topn_lazy_mat.out
  regression-test/suites/external_table_p0/tvf/test_tvf_topn_lazy_mat.groovy
Labels: approved, reviewed

#55705 [fix](table) Move drop editlog in table lock
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
Labels: approved, reviewed

#55653 [fix](cloud) Avoid creating another txn during read versioned keys
  cloud/src/meta-service/meta_service.cpp
  cloud/src/meta-service/meta_service_tablet_stats.cpp
  cloud/src/meta-service/txn_lazy_committer.cpp
Labels: approved, reviewed, cloud, snapshot

#55608 [fix](backup) Support backup meta/job info exceeds 2GB
  fe/fe-common/src/main/java/org/apache/doris/common/GZIPUtils.java
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupHandler.java
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupJob.java
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupJobInfo.java
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupMeta.java
  fe/fe-core/src/main/java/org/apache/doris/backup/Snapshot.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/RestoreCommand.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
Labels: approved, reviewed, dev/3.1.x

#55713 [bugfix](compaction) the avg segment size should always be less than input rows
  be/src/olap/compaction.cpp
  be/test/olap/base_compaction_test.cpp
Labels: approved, reviewed

#55717 [chore](cloud) Fix txn_lazy_commit_test ut not stable
  cloud/src/recycler/recycler.cpp
  cloud/test/txn_lazy_commit_test.cpp
Labels: approved, reviewed

#55190 [fix](iceberg)fix read parquet page index core when read iceberg with equal delete.
  be/src/vec/exec/format/parquet/vparquet_reader.cpp
  regression-test/data/external_table_p2/iceberg/test_iceberg_equal_delete.out
  regression-test/suites/external_table_p2/iceberg/test_iceberg_equal_delete.groovy
Labels: approved, reviewed

#55149 [fix](meta) make OP_CERATE_DB compatible with 3.1
  fe/fe-core/src/main/java/org/apache/doris/catalog/Database.java
  fe/fe-core/src/main/java/org/apache/doris/persist/EditLog.java
Labels: approved, reviewed

#55643 [Feature](agg) Support bool agg functions
  be/src/vec/aggregate_functions/aggregate_function_bool_union.cpp
  be/src/vec/aggregate_functions/aggregate_function_bool_union.h
  be/src/vec/aggregate_functions/aggregate_function_simple_factory.cpp
  be/test/vec/aggregate_functions/agg_bool_union_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinAggregateFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/BoolAnd.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/BoolOr.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/BoolXor.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/executable/NumericArithmetic.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/AggregateFunctionVisitor.java
  regression-test/data/query_p0/sql_functions/aggregate_functions/test_aggregate_all_functions2.out
  regression-test/suites/query_p0/sql_functions/aggregate_functions/test_aggregate_all_functions2.groovy
Labels: approved, reviewed

#55676 [Improvement](column) fully support only_null
  be/src/vec/columns/column_nullable.cpp
  be/src/vec/columns/column_nullable.h
  be/src/vec/exprs/vexpr_context.cpp
Labels: approved, reviewed

#55538 [Chore](nereids) remove LoadStmt
  fe/fe-core/src/main/java/org/apache/doris/analysis/CopyIntoProperties.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CopyProperties.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/LoadStmt.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/load/CloudLoadManager.java
  fe/fe-core/src/main/java/org/apache/doris/job/extensions/insert/InsertJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BulkLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadManager.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/MysqlLoadManager.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/load/NereidsRoutineLoadTaskInfo.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ExportCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/LoadCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/CopyIntoInfo.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/BrokerLoadJobTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/loadv2/LoadJobTest.java
  fe/fe-core/src/test/java/org/apache/doris/persist/LoadJobV2PersistTest.java
Labels: approved, reviewed

#55736 [fix](scheduler) Fix coredump due to different queue size
  be/src/pipeline/pipeline_task.h
  be/src/pipeline/task_queue.cpp
  be/src/pipeline/task_scheduler.cpp
  be/src/pipeline/task_scheduler.h
Labels: approved, reviewed

#55739 [fix](case) fix some cases
  regression-test/suites/compaction/test_compaction_score_action.groovy
  regression-test/suites/compaction/test_config_prune_delete_sign.groovy
Labels: reviewed, dev/3.0.x, dev/3.1.x

#55678 [feat](cloud) Recycle operation logs according the snapshot keys
  cloud/src/meta-service/meta_service_job.cpp
  cloud/src/meta-store/mem_txn_kv.h
  cloud/src/meta-store/meta_reader.cpp
  cloud/src/meta-store/meta_reader.h
  cloud/src/recycler/recycler.h
  cloud/src/recycler/recycler_operation_log.cpp
  cloud/test/meta_reader_test.cpp
  cloud/test/recycler_operation_log_test.cpp
Labels: approved, reviewed, cloud, snapshot

#55506 [fix](profile) Add parser time to total time of summary profile
  fe/fe-core/src/main/java/org/apache/doris/common/profile/SummaryProfile.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
Labels: approved, reviewed

#54978 [fix](struct)fix fe struct functions
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Array.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/CreateMap.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/CreateNamedStruct.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/CreateStruct.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/StructElement.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/types/StructType.java
  regression-test/data/doc/sql-manual/StructNullsafe.out
  regression-test/suites/doc/sql-manual/StructNullsafe.groovy
Labels: approved, reviewed

#55742 [fix](sc) fix check_table_size_correctness failed after schema change when enable skip_writing_empty_rowset_metadata
  be/src/olap/compaction.cpp
Labels: approved, reviewed

#55757 [fix](restore) Clear restored table/partition/resource to reduce overhead
  fe/fe-core/src/main/java/org/apache/doris/backup/RestoreJob.java
Labels: approved, reviewed, cloud, snapshot

#55425 [fix](constant fold)Do not do BE constant fold when float/double is NaN
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/FoldConstantRuleOnBE.java
  regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_by_be.groovy
Labels: approved, reviewed, dev/3.1.x

#55711 [fix](mysql protocol)Set more stmt exists flag correctly when forward to master.
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/FEOpExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  gensrc/thrift/FrontendService.thrift
  regression-test/suites/query_p0/test_multiple_stmt.groovy
Labels: area/mysql-compatibility, approved, reviewed, dev/2.1.x, dev/3.0.x, dev/3.1.x

#55785 [Enhancement](cast) Support colon as delimater between date and time
  be/src/util/string_parser.hpp
  be/test/vec/function/cast/cast_to_date_test.cpp
  be/test/vec/function/cast/cast_to_datetime_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/StringLikeLiteral.java
  regression-test/data/nereids_p0/expression/fold_constant/fe_constant_cast_to_date.out
  regression-test/data/nereids_p0/expression/fold_constant/fe_constant_cast_to_datetime.out
  regression-test/suites/nereids_p0/expression/fold_constant/fe_constant_cast_to_date.groovy
  regression-test/suites/nereids_p0/expression/fold_constant/fe_constant_cast_to_datetime.groovy
Labels: approved, reviewed

#55472 [improve](nereids) Adjust the conditions for confirming hot values
  fe/fe-core/src/main/java/org/apache/doris/analysis/SlotDescriptor.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/FilterEstimation.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/StatsCalculator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/BaseAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/ColStatsData.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/ColumnStatistic.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/HMSAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/OlapAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsRepository.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/util/StatisticsUtil.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/stats/FilterEstimationTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/stats/StatsCalculatorTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/stats/StatsTestUtil.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/OlapAnalysisTaskTest.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/util/StatisticsUtilTest.java
  regression-test/data/shape_check/tpcds_sf100/noStatsRfPrune/query11.out
  regression-test/data/shape_check/tpcds_sf100/noStatsRfPrune/query4.out
  regression-test/data/shape_check/tpcds_sf100/noStatsRfPrune/query74.out
  regression-test/data/shape_check/tpcds_sf100/no_stats_shape/query11.out
  regression-test/data/shape_check/tpcds_sf100/no_stats_shape/query4.out
  regression-test/data/shape_check/tpcds_sf100/no_stats_shape/query74.out
  regression-test/data/shape_check/tpcds_sf100/rf_prune/query4.out
  regression-test/data/shape_check/tpcds_sf100/shape/query4.out
  regression-test/data/shape_check/tpcds_sf1000/shape/query4.out
  regression-test/data/shape_check/tpcds_sf10t_orc/shape/query11.out
  regression-test/data/shape_check/tpcds_sf10t_orc/shape/query4.out
  regression-test/data/shape_check/tpcds_sf10t_orc/shape/query74.out
  regression-test/suites/nereids_rules_p0/skew_join/skew_join.groovy
  regression-test/suites/statistics/test_hot_value.groovy
Labels: approved, reviewed

#55735 [Chore](FE) Add comment to AnyDataType and rename improper function name
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/ComputeSignature.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/ComputeSignatureHelper.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/types/coercion/AnyDataType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/types/coercion/FollowToAnyDataType.java
Labels: approved, reviewed

#55633 [improve](zonemap) support zonemap for float/double type
  be/src/common/compare.h
  be/src/exec/olap_common.cpp
  be/src/exec/olap_common.h
  be/src/exprs/hybrid_set.h
  be/src/olap/comparison_predicate.h
  be/src/olap/in_list_predicate.h
  be/src/olap/rowset/segment_v2/column_reader.cpp
  be/src/olap/rowset/segment_v2/column_reader.h
  be/src/olap/rowset/segment_v2/segment.cpp
  be/src/olap/rowset/segment_v2/zone_map_index.cpp
  be/src/olap/rowset/segment_v2/zone_map_index.h
  be/src/olap/wrapper_field.h
  be/src/pipeline/exec/aggregation_sink_operator.cpp
  be/src/pipeline/exec/distinct_streaming_aggregation_operator.cpp
  be/src/pipeline/exec/mock_scan_operator.h
  be/src/pipeline/exec/scan_operator.cpp
  be/src/pipeline/exec/scan_operator.h
  be/src/pipeline/exec/streaming_aggregation_operator.cpp
  be/src/vec/columns/column.h
  be/src/vec/columns/column_array.cpp
  be/src/vec/columns/column_array.h
  be/src/vec/columns/column_const.cpp
  be/src/vec/columns/column_const.h
  be/src/vec/columns/column_map.cpp
  be/src/vec/columns/column_map.h
  be/src/vec/columns/column_nullable.h
  be/src/vec/columns/column_struct.cpp
  be/src/vec/columns/column_struct.h
  be/src/vec/columns/column_vector.cpp
  be/src/vec/columns/column_vector.h
  be/src/vec/common/hash_table/phmap_fwd_decl.h
  be/src/vec/exec/jni_connector.h
  be/src/vec/olap/olap_data_convertor.h
  be/test/olap/block_column_predicate_test.cpp
  be/test/olap/rowset/segment_v2/zone_map_index_test.cpp
  be/test/pipeline/operator/scan_normalize_predicate_test.cpp
  be/test/vec/columns/column_const_test.cpp
  be/test/vec/exec/format/parquet/parquet_reader_test.cpp
  gensrc/proto/segment_v2.proto
  regression-test/data/datatype_p0/float/test_float_special_values.out
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/util/OutputUtils.groovy
  regression-test/suites/datatype_p0/float/test_float_special_values.groovy
  regression-test/suites/nereids_p0/join/test_join_14.groovy
  regression-test/suites/query_p0/join/test_join.groovy
  regression-test/suites/show_p0/test_show_data_warehouse.groovy
Labels: approved, reviewed

#55790 [feat](streaming job) introduce streaming job schedule task
  fe/fe-core/src/main/java/org/apache/doris/job/base/AbstractJob.java
  fe/fe-core/src/main/java/org/apache/doris/job/common/JobStatus.java
  fe/fe-core/src/main/java/org/apache/doris/job/common/PauseReason.java
  fe/fe-core/src/main/java/org/apache/doris/job/executor/DispatchTaskHandler.java
  fe/fe-core/src/main/java/org/apache/doris/job/extensions/insert/streaming/StreamingInsertJob.java
  fe/fe-core/src/main/java/org/apache/doris/job/extensions/insert/streaming/StreamingJobSchedulerTask.java
Labels: approved, reviewed

#55693 [Refactor](function) Refactor date arithmetic function signatures
  be/src/vec/exprs/vectorized_fn_call.cpp
  be/src/vec/exprs/vexpr.h
  be/src/vec/functions/array/function_array_range.cpp
  be/src/vec/functions/function_date_or_datetime_computation.cpp
  be/src/vec/functions/function_date_or_datetime_computation.h
  be/src/vec/functions/function_date_or_datetime_computation_v2.cpp
  be/test/vec/function/function_time_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionRegistry.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVPartitionExprDateTrunc.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVRelatedPartitionDescSyncLimitGenerator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/ComputeSignatureForDateArithmetic.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/executable/DateTimeAcquire.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/executable/DateTimeArithmetic.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/CurrentDate.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/DaysAdd.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/DaysSub.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/HoursAdd.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/HoursSub.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/MicroSecondsAdd.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/MicroSecondsSub.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/MilliSecondsAdd.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/MilliSecondsSub.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/MinutesAdd.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/MinutesSub.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/MonthsAdd.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/MonthsSub.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/QuartersAdd.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/QuartersSub.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/SecondsAdd.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/SecondsSub.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/WeeksAdd.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/WeeksSub.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/YearsAdd.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/YearsSub.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/DateTimeV2Literal.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/Interval.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/TypeCoercionUtils.java
  fe/fe-core/src/test/java/org/apache/doris/mtmv/MTMVRelatedPartitionDescSyncLimitGeneratorTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/expression/FoldConstantTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/expression/SimplifyArithmeticRuleTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/expressions/UdfTest.java
  regression-test/data/datatype_p0/datetimev2/test_exprs.out
  regression-test/suites/datatype_p0/datetimev1/test_datetimev1_calc.groovy
  regression-test/suites/datatype_p0/datetimev2/test_exprs.groovy
  regression-test/suites/datatype_p0/datev1/test_datev1_calc.groovy
Labels: approved, reviewed

#55789 [Feature](function) Support uniform function
  be/src/vec/functions/simple_function_factory.h
  be/src/vec/functions/uniform.cpp
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinScalarFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Uniform.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/ScalarFunctionVisitor.java
  regression-test/suites/nereids_function_p0/scalar_function/U.groovy
Labels: approved, reviewed

#55777 [test]fix test_follower_consistent_auth failed
  regression-test/suites/auth_p0/test_master_slave_consistency_auth.groovy
Labels: approved, reviewed

#55824 [Feature](k8s)script support tls
  docker/runtime/be/Dockerfile
  docker/runtime/be/resource/be_disaggregated_entrypoint.sh
  docker/runtime/be/resource/be_disaggregated_probe.sh
  docker/runtime/fe/Dockerfile
  docker/runtime/fe/resource/fe_disaggregated_entrypoint.sh
  docker/runtime/fe/resource/fe_disaggregated_probe.sh
  docker/runtime/ms/Dockerfile
Labels: approved, reviewed

#55818 [fix](ci) skip beut case
  be/test/io/cache/block_file_cache_test.cpp
Labels: approved, reviewed

#55811 [fix](case) fix some failure cases
  regression-test/suites/export/test_array_export.groovy
  regression-test/suites/load_p0/broker_load/test_array_load.groovy
  regression-test/suites/load_p0/broker_load/test_broker_load_seq.groovy
  regression-test/suites/load_p0/broker_load/test_broker_load_with_merge.groovy
  regression-test/suites/load_p0/broker_load/test_broker_load_with_partition.groovy
  regression-test/suites/load_p0/broker_load/test_broker_load_with_where.groovy
  regression-test/suites/load_p0/stream_load/test_json_load.groovy
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x

#55794 [Fix](regression) fix wrong regression result of bool_agg
  regression-test/data/query_p0/sql_functions/aggregate_functions/test_aggregate_all_functions2.out
  regression-test/suites/query_p0/sql_functions/aggregate_functions/test_aggregate_all_functions2.groovy
Labels: approved, reviewed

#55808 [Enhancement](Log) change some logs from info to debug
  fe/fe-core/src/main/java/org/apache/doris/load/GroupCommitManager.java
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x, p0_test

#55749 [opt](be) Use a custom allocator to allocate memory in order to avoid untracked memory usage
  be/src/io/fs/broker_file_system.cpp
  be/src/io/fs/buffered_reader.cpp
  be/src/io/fs/buffered_reader.h
  be/src/io/fs/stream_load_pipe.cpp
  be/src/io/fs/stream_load_pipe.h
  be/src/olap/tablet.cpp
  be/src/util/faststring.cc
  be/src/util/slice.h
  be/src/vec/common/allocator.cpp
  be/src/vec/common/allocator.h
  be/src/vec/common/custom_allocator.h
  be/src/vec/exec/format/file_reader/new_plain_binary_line_reader.h
  be/src/vec/exec/format/json/new_json_reader.cpp
  be/src/vec/exec/format/json/new_json_reader.h
  be/src/vec/exec/format/orc/orc_file_reader.cpp
  be/src/vec/exec/format/orc/orc_file_reader.h
  be/src/vec/exec/format/parquet/byte_array_dict_decoder.cpp
  be/src/vec/exec/format/parquet/byte_array_dict_decoder.h
  be/src/vec/exec/format/parquet/decoder.h
  be/src/vec/exec/format/parquet/fix_length_dict_decoder.hpp
  be/src/vec/exec/format/parquet/parquet_thrift_util.h
  be/src/vec/exec/format/parquet/vparquet_column_chunk_reader.cpp
  be/src/vec/exec/format/parquet/vparquet_column_chunk_reader.h
  be/src/vec/exec/format/parquet/vparquet_group_reader.cpp
  be/src/vec/exec/format/parquet/vparquet_group_reader.h
  be/src/vec/functions/function_jsonb.cpp
  be/test/vec/common/custom_allocator_test.cpp
  be/test/vec/exec/format/parquet/byte_array_dict_decoder_test.cpp
  be/test/vec/exec/format/parquet/fix_length_dict_decoder_test.cpp
Labels: approved, reviewed

#55836 [fix](case) fix case bug
  regression-test/suites/fault_injection_p0/test_delta_writer_v2_back_pressure_fault_injection.groovy
Labels: approved, reviewed

#55826 [fix](case) fix ingestion load and broker load cases (#55361)
  regression-test/data/load_p0/broker_load/test_array_load.out
  regression-test/data/load_p0/broker_load/test_broker_load_seq.out
  regression-test/framework/src/main/groovy/org/apache/doris/regression/action/HttpCliAction.groovy
  regression-test/suites/load_p0/broker_load/test_array_load.groovy
  regression-test/suites/load_p0/broker_load/test_broker_load_seq.groovy
  regression-test/suites/load_p0/broker_load/test_broker_load_with_merge.groovy
  regression-test/suites/load_p0/broker_load/test_broker_load_with_partition.groovy
  regression-test/suites/load_p0/broker_load/test_broker_load_with_properties.groovy
  regression-test/suites/load_p0/broker_load/test_broker_load_with_where.groovy
  regression-test/suites/load_p0/broker_load/test_broker_load_without_filepath.groovy
  regression-test/suites/load_p0/ingestion_load/test_ingestion_load.groovy
  regression-test/suites/load_p0/ingestion_load/test_ingestion_load_alter_column.groovy
  regression-test/suites/load_p0/ingestion_load/test_ingestion_load_alter_partition.groovy
  regression-test/suites/load_p0/ingestion_load/test_ingestion_load_drop_table.groovy
  regression-test/suites/load_p0/ingestion_load/test_ingestion_load_multi_table.groovy
  regression-test/suites/load_p0/ingestion_load/test_ingestion_load_with_inverted_index.groovy
  regression-test/suites/load_p0/ingestion_load/test_ingestion_load_with_partition.groovy
Labels: approved, reviewed, p0_test, dev/4.0.x

#55837 [fix](compaction) fix compaction core dump when enable skip_writing_empty_rowset_metadata
  be/src/olap/compaction.cpp
  be/src/olap/compaction.h
  be/test/cloud/cloud_compaction_test.cpp
  regression-test/data/compaction/test_compaction_with_empty_rowset.out
  regression-test/suites/compaction/test_compaction_with_empty_rowset.groovy
Labels: approved, reviewed

#55832 [regression-test](point query) fix unstable cases
  regression-test/data/point_query_p0/test_point_query.out
  regression-test/pipeline/cloud_p0/conf/regression-conf-custom.groovy
  regression-test/pipeline/p0/conf/regression-conf.groovy
  regression-test/suites/compaction/test_compaction_uniq_keys_row_store.groovy
  regression-test/suites/point_query_p0/test_point_query.groovy
Labels: approved, reviewed

#55681 [fix](mtmv) Fix set disable join reorder fail when table row count is -1 when init join order
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/InitJoinOrder.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/stats/StatsCalculatorTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/util/PlanChecker.java
Labels: approved, reviewed

#55169 [fix](test) Modify regression test to make stable and change expected log level
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/ExpressionLineageReplacer.java
  regression-test/data/nereids_rules_p0/mv/date_trunc/mv_with_date_trunc.out
  regression-test/suites/nereids_rules_p0/mv/date_trunc/mv_with_date_trunc.groovy
Labels: approved, reviewed, dev/3.1.x

#55852 [opt](load) add some metrics for flush memtable
  be/src/io/fs/s3_file_writer.cpp
  be/src/olap/memtable_writer.cpp
  be/src/olap/rowset/beta_rowset_writer.cpp
  be/src/olap/rowset/segment_creator.cpp
Labels: approved, reviewed

#55765 [feat](recycler) ​​Compatibility between deleted instance recycling and cluster snapshots.
  cloud/src/meta-store/keys.cpp
  cloud/src/meta-store/keys.h
  cloud/src/recycler/recycler.cpp
  cloud/src/recycler/recycler.h
  cloud/test/keys_test.cpp
  cloud/test/recycler_operation_log_test.cpp
  cloud/test/recycler_test.cpp
Labels: approved, reviewed, cloud, snapshot

#55994 [fix](github) fix stale action
  .github/workflows/stale.yml
Labels: approved, reviewed

#55965 [fix](test) Fix some recycler cases
  regression-test/suites/cloud_p0/recycler/test_recycler_with_drop_column.groovy
  regression-test/suites/cloud_p0/recycler/test_recycler_with_drop_index.groovy
  regression-test/suites/cloud_p0/recycler/test_recycler_with_drop_mv.groovy
  regression-test/suites/cloud_p0/recycler/test_recycler_with_drop_rollup.groovy
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x, p0_test

#54527 [feat](checker) Add table/partition version key consistency checking for checker
  cloud/src/common/config.h
  cloud/src/recycler/checker.cpp
  cloud/src/recycler/checker.h
  cloud/src/recycler/meta_checker.cpp
  cloud/src/recycler/meta_checker.h
  cloud/test/recycler_test.cpp
Labels: approved, reviewed

#56021 [Chore](Segment) avoid print stack trace when column_unique_id not found
  be/src/olap/rowset/segment_v2/column_reader_cache.cpp
  be/src/olap/rowset/segment_v2/segment.cpp
Labels: approved, reviewed

#55964 [Enhancement](date) Enhance the sec_to_time function to support return microseconds
  be/src/vec/functions/function_date_or_datetime_computation.h
  be/src/vec/runtime/time_value.h
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/executable/DateTimeExtractAndTransform.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/SecToTime.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/TimeV2Literal.java
  regression-test/data/correctness/test_time_function.out
  regression-test/suites/correctness/test_time_function.groovy
Labels: approved, reviewed

#55929 [fix](filecache) fix BytesScannedFromCache/Local always zero
  be/src/io/cache/cached_remote_file_reader.cpp
  be/src/vec/exec/scan/olap_scanner.cpp
Labels: approved, reviewed, dev/3.1.x

#55960 [fix](inverted index) Add CompositeReader to support multi-field boolean queries
  be/src/olap/rowset/segment_v2/inverted_index/query_v2/boolean_query/boolean_weight.h
  be/src/olap/rowset/segment_v2/inverted_index/query_v2/composite_reader.h
  be/src/olap/rowset/segment_v2/inverted_index/query_v2/term_query/term_weight.h
  be/src/olap/rowset/segment_v2/inverted_index/query_v2/weight.h
  be/test/olap/rowset/segment_v2/inverted_index/query_v2/boolean_query_test.cpp
  be/test/olap/rowset/segment_v2/inverted_index/query_v2/composite_reader_test.cpp
Labels: approved, reviewed

#55983 [fix](case) test_manager_interface_5
  regression-test/suites/manager/test_manager_interface_5.groovy
Labels: approved, reviewed

#55982 [fix](case) fix workload group case
  regression-test/suites/auth_p0/test_master_slave_consistency_auth.groovy
  regression-test/suites/auth_p0/test_select_column_auth.groovy
Labels: approved, reviewed, p0_test, dev/4.0.x

#55953 [chore](function) Add a range limit to the second parameter of format_round.
  be/src/vec/functions/function_string.h
  regression-test/suites/query_p0/sql_functions/math_functions/test_format_round.groovy
Labels: approved, reviewed

#56030 [fix](largeint) Return error if largeint literal overflow
  be/src/vec/data_types/data_type_number_base.cpp
Labels: approved, reviewed

#55738 [fix](es) Fix array not supporting json subtype
  be/src/exec/es/es_scroll_parser.cpp
  docker/thirdparties/docker-compose/elasticsearch/scripts/data/composite_type_array_bulk.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/index/array_meta_composite_type_array.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/index/es6_composite_type_array.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/index/es7_composite_type_array.json
  regression-test/data/external_table_p0/es/test_es_query.out
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x, dev/3.1.x

#55876 Fix(Variant) Fix null value handling when serializing to JSON string
  be/src/olap/rowset/segment_v2/variant/hierarchical_data_iterator.cpp
  be/src/vec/columns/column_variant.cpp
  regression-test/data/variant_p0/variant_hirachinal.out
  regression-test/suites/variant_p0/variant_hirachinal.groovy
Labels: approved, reviewed, dev/3.1.x

#55853 [Fix](date) Fix the ambiguous usage of TimeInterval
  be/src/vec/aggregate_functions/aggregate_function_window_funnel.cpp
  be/src/vec/aggregate_functions/aggregate_function_window_funnel.h
  be/src/vec/functions/function_date_or_datetime_computation.h
  be/src/vec/functions/function_datetime_floor_ceil.cpp
  be/src/vec/runtime/vdatetime_value.cpp
  be/src/vec/runtime/vdatetime_value.h
  be/test/vec/aggregate_functions/vec_window_funnel_test.cpp
  be/test/vec/runtime/vdatetime_value_test.cpp
  regression-test/data/query_p0/sql_functions/datetime_functions/test_date_floor_ceil.out
  regression-test/suites/nereids_p0/sql_functions/aggregate_functions/test_aggregate_window_functions.groovy
  regression-test/suites/query_p0/sql_functions/datetime_functions/test_date_floor_ceil.groovy
Labels: approved, reviewed

#56047 [chore](regression-test) optimize test time on variant_p2
  regression-test/suites/variant_p2/load.groovy
Labels: approved, reviewed

#56033 [fix](test) fix result of mtmv_p0/test_create_with_json_object
  regression-test/data/mtmv_p0/test_create_with_json_object.out
Labels: approved, reviewed

#55942 [Bug](runtime-filter) use skip_process to replace terminate
  be/src/pipeline/exec/hashjoin_build_sink.cpp
  be/src/pipeline/exec/partitioned_hash_join_sink_operator.cpp
  be/src/pipeline/exec/set_sink_operator.cpp
  be/src/runtime_filter/runtime_filter_producer.cpp
  be/src/runtime_filter/runtime_filter_producer_helper.cpp
  be/src/runtime_filter/runtime_filter_producer_helper.h
  be/test/runtime_filter/runtime_filter_producer_helper_test.cpp
  regression-test/data/nereids_syntax_p0/agg_4_phase.out
  regression-test/suites/nereids_syntax_p0/agg_4_phase.groovy
Labels: approved, reviewed

#55892 [chore](case) log out msg to find reason of case failure
  regression-test/suites/alter_p2/test_alter_colocate_group.groovy
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x

#56020 [regression](show)fix show load warnings
  regression-test/suites/nereids_p0/show/test_nereids_show_load_warnings.groovy
Labels: approved, reviewed

#55877 [feature](function) Support more types for to_json
  be/src/vec/data_types/serde/data_type_datetimev2_serde.h
  be/src/vec/data_types/serde/data_type_map_serde.cpp
  be/src/vec/data_types/serde/data_type_map_serde.h
  be/src/vec/data_types/serde/data_type_number_serde.cpp
  be/src/vec/data_types/serde/data_type_number_serde.h
  be/src/vec/data_types/serde/data_type_time_serde.h
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/ToJson.java
  regression-test/data/jsonb_p0/test_json_to_json.out
  regression-test/suites/jsonb_p0/test_json_to_json.groovy
  regression-test/suites/query_p0/sql_functions/json_function/test_query_json_array.groovy
Labels: approved, reviewed

#55899 [fix](cast) Fix the incorrect nullable property setting for variant cast to JSON.
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/Cast.java
  regression-test/data/query_p0/cast/test_complextype_to_json.out
  regression-test/suites/query_p0/cast/test_complextype_to_json.groovy
Labels: approved, reviewed

#56048 [fix](union) Local shuffle for union operator
  be/src/pipeline/exec/union_sink_operator.cpp
  be/src/pipeline/exec/union_sink_operator.h
Labels: approved, reviewed

#55812 [opt](ann index) Support scalar quantization
  be/src/olap/rowset/segment_v2/ann_index/ann_index.h
  be/src/olap/rowset/segment_v2/ann_index/ann_index_writer.cpp
  be/src/olap/rowset/segment_v2/ann_index/ann_index_writer.h
  be/src/olap/rowset/segment_v2/ann_index/faiss_ann_index.cpp
  be/src/olap/rowset/segment_v2/ann_index/faiss_ann_index.h
  fe/fe-core/src/main/java/org/apache/doris/analysis/AnnIndexPropertiesChecker.java
  regression-test/data/ann_index_p0/scalar_quantization.out
  regression-test/suites/ann_index_p0/scalar_quantization.groovy
Labels: approved, reviewed

#55907 [fix](nereids) not use cte split multi distinct when agg has source repeat
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/DistinctAggStrategySelector.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/SplitMultiDistinctStrategy.java
  regression-test/suites/nereids_rules_p0/agg_strategy/distinct_agg_strategy_selector.groovy
Labels: approved, reviewed

#55976 [feat](cloud) Add snapshot manager
  cloud/CMakeLists.txt
  cloud/src/common/bvars.cpp
  cloud/src/common/bvars.h
  cloud/src/meta-service/meta_server.cpp
  cloud/src/meta-service/meta_service.cpp
  cloud/src/meta-service/meta_service.h
  cloud/src/meta-service/meta_service_snapshot.cpp
  cloud/src/recycler/recycler.cpp
  cloud/src/recycler/recycler.h
  cloud/src/snapshot/CMakeLists.txt
  cloud/src/snapshot/snapshot_manager.cpp
  cloud/src/snapshot/snapshot_manager.h
  cloud/test/fdb_injection_test.cpp
  cloud/test/meta_server_test.cpp
  cloud/test/meta_service_http_test.cpp
  cloud/test/meta_service_snapshot_test.cpp
  cloud/test/meta_service_test.cpp
  cloud/test/rate_limiter_test.cpp
  cloud/test/recycle_versioned_keys_test.cpp
  cloud/test/recycler_operation_log_test.cpp
  cloud/test/recycler_test.cpp
  cloud/test/resource_test.cpp
  cloud/test/rpc_kv_bvar_test.cpp
  cloud/test/txn_lazy_commit_test.cpp
Labels: approved, reviewed, cloud, snapshot

#54036 [feature](doris-future) Support "map_entries" and "map_contains_entry" functions
  be/src/vec/functions/function_map.cpp
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinScalarFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/MapContainsEntry.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/MapEntries.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/ScalarFunctionVisitor.java
  regression-test/data/load_p0/stream_load/test_map_load_and_function.out
  regression-test/suites/load_p0/stream_load/test_map_load_and_function.groovy
Labels: approved, reviewed

#56071 [chore](cloud) Add optional code dir enterprise/
  cloud/CMakeLists.txt
  cloud/test/CMakeLists.txt
Labels: approved, reviewed, cloud

#55882 [chore](opt) Avoid extra copies of string types in histogram_to_json.
  be/src/vec/utils/histogram_helpers.hpp
Labels: approved, reviewed

#55952 [chore](test)Icebebrg test uses doris's fileio
  regression-test/suites/external_table_p0/kerberos/test_iceberg_hadoop_catalog_kerberos.groovy
Labels: approved, reviewed, dev/3.1.x

#53918 [fix](nereids)fix load command failed with bitmap column expr mapping
  fe/fe-core/src/main/java/org/apache/doris/nereids/load/NereidsDataDescription.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/commands/LoadCommandTest.java
Labels: approved, reviewed, dev/4.0.x

#56077 [chore](auditlog) Enable audit log plugin by default
  fe/fe-core/src/main/java/org/apache/doris/qe/GlobalVariable.java
Labels: approved, reviewed, kind/behavior-changed, dev/3.1.x, dev/4.0.x

#56057 [Fix](AI) remove thread_pool in AI Functions
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/vec/functions/ai/ai_functions.h
  be/test/ai/aggregate_function_ai_agg_test.cpp
  be/test/ai/ai_function_test.cpp
Labels: approved, reviewed

#55883 [fix](nereids) agg table does not support topn-lazy-materialization
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/materialize/MaterializeProbeVisitor.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/MaterializationContext.java
  regression-test/data/query_p0/topn_lazy/topn_lazy_on_data_model.out
  regression-test/suites/query_p0/topn_lazy/topn_lazy_on_data_model.groovy
Labels: approved, reviewed

#56088 [fix](exchange) remove const_cast in VDataStreamMgr
  be/src/vec/runtime/vdata_stream_mgr.cpp
Labels: approved, reviewed

#56072 [case](tvf) add tvf abnormal cases
  regression-test/data/load_p0/tvf/test_tvf_error_data.out
  regression-test/suites/load_p0/tvf/test_tvf_error_column.groovy
  regression-test/suites/load_p0/tvf/test_tvf_error_data.groovy
Labels: approved, reviewed

#55990 branch-3.0: [fix](database) Fix rename db and create table race #55054
  fe/fe-core/src/main/java/org/apache/doris/catalog/Database.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
Labels: reviewed

#56061 [fix](compaction) Make creating tablet idempotently to keep compaction Job idempotent
  cloud/src/meta-service/meta_service.cpp
  cloud/src/meta-service/meta_service.h
  cloud/test/meta_service_http_test.cpp
  cloud/test/meta_service_job_test.cpp
  cloud/test/meta_service_test.cpp
Labels: approved, reviewed, p0_b, dev/3.0.x, dev/3.1.x, dev/4.0.x
