Repository apache/doris, pull requests merged in 2025-08, with the labels that each got.

#53855 [branch-3.0](core) Fix format round would core under boundary conditions
  be/src/exprs/math_functions.cpp
  be/src/vec/functions/function_string.h
  be/test/exprs/math_functions_test.cpp
  regression-test/data/query_p0/sql_functions/math_functions/test_format_round.out
  regression-test/suites/query_p0/sql_functions/math_functions/test_format_round.groovy
Labels: approved, reviewed

#54084 [chore](cloud) Add Transaction::batch_scan function
  cloud/src/meta-store/mem_txn_kv.cpp
  cloud/src/meta-store/mem_txn_kv.h
  cloud/src/meta-store/txn_kv.cpp
  cloud/src/meta-store/txn_kv.h
  cloud/test/mem_txn_kv_test.cpp
  cloud/test/txn_kv_test.cpp
Labels: approved, reviewed, cloud, snapshot

#53950 [Chore](nereids) Remove SetDefaultStorageVaultStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/SetDefaultStorageVaultStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/StorageVaultMgr.java
  fe/fe-core/src/main/java/org/apache/doris/qe/DdlExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/cloud/catalog/HdfsStorageVaultTest.java
Labels: approved, reviewed

#53970 branch-2.1: (fix)[case] add fast fail to avoid routine load case hang
  regression-test/suites/load_p0/routine_load/test_multi_table_load_error.groovy
  regression-test/suites/load_p0/routine_load/test_out_of_range_error.groovy
  regression-test/suites/load_p0/routine_load/test_routine_load.groovy
  regression-test/suites/load_p0/routine_load/test_routine_load_condition.groovy
  regression-test/suites/load_p0/routine_load/test_routine_load_eof.groovy
  regression-test/suites/load_p0/routine_load/test_routine_load_error.groovy
  regression-test/suites/load_p0/routine_load/test_routine_load_error_info.groovy
  regression-test/suites/load_p0/routine_load/test_routine_load_jsonpath_dollar.groovy
  regression-test/suites/load_p0/routine_load/test_routine_load_metrics.groovy
  regression-test/suites/load_p0/routine_load/test_routine_load_offset.groovy
  regression-test/suites/load_p0/routine_load/test_routine_load_property.groovy
  regression-test/suites/load_p0/routine_load/test_routine_load_schedule.groovy
  regression-test/suites/load_p0/routine_load/test_routine_load_topic_change.groovy
  regression-test/suites/load_p0/routine_load/test_routine_load_with_sc.groovy
  regression-test/suites/load_p0/routine_load/test_show_routine_load.groovy
Labels: approved, reviewed

#54140 [fix](decimal256) fix casting decimal256 to float
  be/src/vec/data_types/data_type_decimal.h
  regression-test/data/datatype_p0/decimalv3/test_decimal256_cast.out
  regression-test/data/datatype_p0/decimalv3/test_decimalv3_cast4.out
  regression-test/suites/datatype_p0/decimalv3/test_decimal256_cast.groovy
Labels: usercase, dev/2.1.x

#54155 [fix](case) make some cases stable
  regression-test/data/doc/sql-manual/basic-elements/data-types/array-md.out
  regression-test/data/doc/sql-manual/basic-elements/data-types/map-md.out
  regression-test/data/doc/sql-manual/basic-elements/data-types/struct-md.out
  regression-test/suites/doc/sql-manual/basic-elements/data-types/array-md.groovy
  regression-test/suites/doc/sql-manual/basic-elements/data-types/map-md.groovy
  regression-test/suites/doc/sql-manual/basic-elements/data-types/struct-md.groovy
Labels: approved, reviewed

#54173 [fix](test) use drop view for views in test_show_keys
  regression-test/suites/nereids_syntax_p0/test_show_keys.groovy
Labels: approved, reviewed

#54124 [refactor](prepare_txn) move prepare_txn to tablet to reduce duplicated
  be/src/olap/push_handler.cpp
  be/src/olap/rowset_builder.cpp
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
  be/src/service/backend_service.cpp
Labels: approved, reviewed

#54143 [improve](cast) improve cast performance
  be/src/vec/data_types/number_traits.h
  be/src/vec/functions/cast/cast_to_basic_number_common.h
  be/src/vec/functions/cast/cast_to_decimal.h
  be/src/vec/functions/cast/cast_to_float.h
  be/src/vec/functions/cast/cast_to_int.h
Labels: approved, reviewed

#51725 [Enhancement](llm) Support some LLM functions
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/http/http_client.h
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/query_context.h
  be/src/vec/functions/llm/functions_llm.h
  be/src/vec/functions/llm/llm_adapter.h
  be/src/vec/functions/llm/llm_classify.h
  be/src/vec/functions/llm/llm_extract.h
  be/src/vec/functions/llm/llm_fix_grammar.h
  be/src/vec/functions/llm/llm_functions.cpp
  be/src/vec/functions/llm/llm_generate.h
  be/src/vec/functions/llm/llm_mask.h
  be/src/vec/functions/llm/llm_sentiment.h
  be/src/vec/functions/llm/llm_summarize.h
  be/src/vec/functions/llm/llm_translate.h
  be/src/vec/functions/simple_function_factory.h
  be/test/llm/build_prompt_test.cpp
  be/test/llm/llm_adapter_test.cpp
  be/test/testutil/mock/mock_query_context.h
  be/test/testutil/mock/mock_runtime_state.h
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinScalarFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/LLMResource.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Resource.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/constants/LLMProperties.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/FoldConstantRuleOnBE.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/llm/LLMClassify.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/llm/LLMExtract.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/llm/LLMFixGrammar.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/llm/LLMFunction.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/llm/LLMGenerate.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/llm/LLMMask.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/llm/LLMSentiment.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/llm/LLMSummarize.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/llm/LLMTranslate.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/ScalarFunctionVisitor.java
  fe/fe-core/src/main/java/org/apache/doris/persist/gson/GsonUtils.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/qe/runtime/ThriftPlansBuilder.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/LLMResourceTest.java
  gensrc/thrift/PaloInternalService.thrift
  regression-test/suites/auth_call/test_ddl_llm_resource_auth.groovy
  regression-test/suites/llm_p0/test_create_llm_resource.groovy
  regression-test/suites/llm_p0/test_llm_functions.groovy
Labels: approved, reviewed

#54145 [Improvement](runtime-filter) fixed_len_to_uint32_v2 change hash method to crc32
  be/src/exprs/bloom_filter_func.h
  be/src/exprs/bloom_filter_func_impl.h
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/pipeline/pipeline_task.cpp
  be/src/runtime_filter/runtime_filter.cpp
  be/src/runtime_filter/runtime_filter_definitions.h
  be/src/util/runtime_profile.cpp
  be/src/util/runtime_profile.h
  be/src/vec/common/hash_table/hash.h
  be/test/exprs/bloom_filter_func_test.cpp
  be/test/runtime_filter/runtime_filter_wrapper_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
Labels: approved, reviewed

#54139 [test](UT) add be ut for key coder
  be/test/olap/key_coder_test.cpp
  be/test/olap/test_data/key_coder_complex.dat
  be/test/olap/test_data/key_coder_test.dat
Labels: approved, reviewed

#54152 [fix](json) handle space characters in JsonbPath
  be/src/util/jsonb_document.h
  regression-test/data/query_p0/sql_functions/json_functions/json_search.out
  regression-test/suites/query_p0/sql_functions/json_functions/json_search.groovy
Labels: approved, reviewed

#54179 [Fix](cast) fix uncatched parse error in strict mode to datev2
  be/src/vec/functions/cast/cast_to_datev2_impl.hpp
  be/test/vec/function/cast/cast_to_date_test.cpp
Labels: approved, reviewed

#54178 [fix](decimal256) fix casting decimal256 to float
  be/src/vec/data_types/data_type_decimal.h
  regression-test/data/datatype_p0/decimalv3/test_decimal256_cast.out
  regression-test/data/datatype_p0/decimalv3/test_decimalv3_cast4.out
  regression-test/suites/datatype_p0/decimalv3/test_decimal256_cast.groovy
Labels: approved, reviewed

#54218 [improve](cast) improve cast performance
  be/src/vec/data_types/number_traits.h
  be/src/vec/functions/cast/cast_to_basic_number_common.h
  be/src/vec/functions/cast/cast_to_decimal.h
  be/src/vec/functions/cast/cast_to_float.h
  be/src/vec/functions/cast/cast_to_int.h
Labels: approved, reviewed

#54234 [fix](init-catalog) use equals instead of ==
  fe/fe-core/src/main/java/org/apache/doris/mysql/MysqlProto.java
Labels: approved, reviewed, dev/3.1.x

#54137 [Bug](agg) fix agg with topn limit coredump with ctor same key twice
  be/src/pipeline/exec/aggregation_sink_operator.cpp
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x

#54236 [fix](regression-test)fix metric checker ignore empty label values
  regression-test/framework/src/main/groovy/org/apache/doris/regression/util/PromethuesChecker.groovy
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x, p0_test

#52345 [fix](inverted index) fix CN_Quantifier problem in IK analyzer
  be/src/olap/rowset/segment_v2/inverted_index/analyzer/ik/core/CN_QuantifierSegmenter.cpp
  be/test/olap/rowset/segment_v2/inverted_index/analyzer/ik_anayzer_test.cpp
Labels: approved, reviewed

#54160 [test](ut) add more ut for match
  be/test/vec/function/function_match_test.cpp
Labels: approved, reviewed

#54227 [Fix](case) Fix some docker case
  be/src/vec/exec/scan/olap_scanner.cpp
  regression-test/suites/cloud_p0/node_mgr/test_cloud_decommission.groovy
  regression-test/suites/fault_injection_p0/cloud/test_cloud_concurrent_calc_dbm_task.groovy
  regression-test/suites/fault_injection_p0/cloud/test_cloud_full_compaction_multi_segments.groovy
  regression-test/suites/fault_injection_p0/cloud/test_cloud_mow_retry_txn_interleave.groovy
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x, p0_test

#54077 [fix](query tvf): resolve column mismatch error in JDBC query function
  be/src/pipeline/exec/jdbc_scan_operator.cpp
  be/src/pipeline/exec/jdbc_scan_operator.h
  be/src/vec/exec/scan/jdbc_scanner.cpp
  be/src/vec/exec/scan/jdbc_scanner.h
  be/src/vec/exec/vjdbc_connector.cpp
  be/src/vec/exec/vjdbc_connector.h
  fe/be-java-extensions/jdbc-scanner/src/main/java/org/apache/doris/jdbc/BaseJdbcExecutor.java
  fe/be-java-extensions/jdbc-scanner/src/main/java/org/apache/doris/jdbc/MySQLJdbcExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/source/JdbcScanNode.java
  gensrc/thrift/PlanNodes.thrift
  gensrc/thrift/Types.thrift
  regression-test/data/external_table_p0/jdbc/test_doris_jdbc_catalog.out
  regression-test/suites/external_table_p0/jdbc/test_doris_jdbc_catalog.groovy
Labels: approved, reviewed, usercase, dev/2.1.x, dev/3.0.x, dev/3.1.x

#53866 [feat](cloud) create_tablet writes versioned meta keys
  cloud/src/meta-service/meta_service.cpp
  cloud/src/recycler/recycler.cpp
  cloud/test/meta_service_test.cpp
  cloud/test/recycler_test.cpp
Labels: approved, reviewed, cloud, snapshot

#54235 [chore](BE) Remove some useless code of resource context
  be/src/runtime/workload_management/resource_context.cpp
  be/src/runtime/workload_management/resource_context.h
Labels: approved, reviewed

#54158 [fix](nereids) Fix query err when topn push through union_all
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PushDownTopNThroughUnion.java
  regression-test/data/nereids_rules_p0/push_down_top_n/push_down_top_n_through_union.out
  regression-test/suites/nereids_rules_p0/push_down_top_n/push_down_top_n_through_union.groovy
Labels: approved, reviewed, usercase, dev/2.1.x, dev/3.0.x, dev/3.1.x

#54083 [enhance](hudi) upgrade hudi to version 1.0.2
  fe/be-java-extensions/hadoop-hudi-scanner/pom.xml
  fe/fe-core/src/main/java/org/apache/doris/datasource/hudi/HudiSchemaCacheValue.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hudi/HudiUtils.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hudi/source/COWIncrementalRelation.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hudi/source/HudiCachedFsViewProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hudi/source/HudiCachedPartitionProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hudi/source/HudiLocalEngineContext.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hudi/source/HudiPartitionProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hudi/source/HudiScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hudi/source/MORIncrementalRelation.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/HudiTableValuedFunction.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/MetadataGenerator.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/hudi/HudiUtilsTest.java
  fe/pom.xml
  regression-test/data/external_table_p2/hudi/test_hudi_meta.out
Labels: approved, reviewed, dev/3.1.x

#54189 [opt](hive) unify the serde name of hive table
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HiveMetaStoreClientHelper.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/source/HiveScanNode.java
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x

#54220 [cleanup](type) Remove TIME v1 type from FE
  be/src/runtime/primitive_type.cpp
  be/test/pipeline/operator/hashjoin_build_sink_test.cpp
  fe/fe-common/src/main/java/org/apache/doris/catalog/PrimitiveType.java
  fe/fe-common/src/main/java/org/apache/doris/catalog/ScalarType.java
  fe/fe-common/src/main/java/org/apache/doris/catalog/Type.java
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateFunctionStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/FloatLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/LiteralExpr.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/LiteralUtils.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/MysqlSerializer.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/CreateFunctionCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/types/DataType.java
  fe/fe-core/src/main/java/org/apache/doris/qe/cache/PartitionRange.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/FEFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/ColumnStatistic.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/ColumnTypeTest.java
  gensrc/script/doris_builtins_functions.py
  gensrc/thrift/Types.thrift
Labels: approved, reviewed

#54201 [chore](code) Use the function of string view to implement start_with / end_with
  be/src/vec/functions/function_string.cpp
Labels: approved, reviewed

#54150 [fix](nereids) when ColumnStatistics.avgSizeByte is NaN, use default size 1.
  fe/fe-core/src/main/java/org/apache/doris/statistics/Statistics.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/StatisticsTest.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x, dev/3.1.x

#54223 [fix](virtual slot) TimeV2 type should not be used as virtual slot ref
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PushDownVirtualColumnsIntoOlapScan.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/PushDownVirtualColumnsIntoOlapScanTest.java
  regression-test/data/query_p0/virtual_slot_ref/expr_with_runtime_return_type.out
  regression-test/suites/query_p0/virtual_slot_ref/expr_with_runtime_return_type.groovy
Labels: approved, reviewed

#54027 [refine](cast) Use the new cast to implement array/map/struct cast
  be/src/vec/common/string_ref.cpp
  be/src/vec/common/string_ref.h
  be/src/vec/data_types/serde/complex_type_deserialize_util.h
  be/src/vec/data_types/serde/data_type_array_serde.cpp
  be/src/vec/data_types/serde/data_type_array_serde.h
  be/src/vec/data_types/serde/data_type_bitmap_serde.cpp
  be/src/vec/data_types/serde/data_type_bitmap_serde.h
  be/src/vec/data_types/serde/data_type_date_or_datetime_serde.cpp
  be/src/vec/data_types/serde/data_type_date_or_datetime_serde.h
  be/src/vec/data_types/serde/data_type_datetimev2_serde.cpp
  be/src/vec/data_types/serde/data_type_datetimev2_serde.h
  be/src/vec/data_types/serde/data_type_datev2_serde.cpp
  be/src/vec/data_types/serde/data_type_datev2_serde.h
  be/src/vec/data_types/serde/data_type_decimal_serde.cpp
  be/src/vec/data_types/serde/data_type_decimal_serde.h
  be/src/vec/data_types/serde/data_type_hll_serde.cpp
  be/src/vec/data_types/serde/data_type_hll_serde.h
  be/src/vec/data_types/serde/data_type_ipv4_serde.cpp
  be/src/vec/data_types/serde/data_type_ipv4_serde.h
  be/src/vec/data_types/serde/data_type_ipv6_serde.cpp
  be/src/vec/data_types/serde/data_type_ipv6_serde.h
  be/src/vec/data_types/serde/data_type_jsonb_serde.cpp
  be/src/vec/data_types/serde/data_type_jsonb_serde.h
  be/src/vec/data_types/serde/data_type_map_serde.cpp
  be/src/vec/data_types/serde/data_type_map_serde.h
  be/src/vec/data_types/serde/data_type_nullable_serde.cpp
  be/src/vec/data_types/serde/data_type_number_serde.cpp
  be/src/vec/data_types/serde/data_type_serde.h
  be/src/vec/data_types/serde/data_type_string_serde.cpp
  be/src/vec/data_types/serde/data_type_string_serde.h
  be/src/vec/data_types/serde/data_type_struct_serde.cpp
  be/src/vec/data_types/serde/data_type_struct_serde.h
  be/src/vec/data_types/serde/data_type_time_serde.cpp
  be/src/vec/data_types/serde/data_type_time_serde.h
  be/src/vec/functions/cast/cast_base.cpp
  be/src/vec/functions/cast/cast_base.h
  be/src/vec/functions/cast/cast_to_array.h
  be/src/vec/functions/cast/cast_to_map.h
  be/src/vec/functions/cast/cast_to_struct.h
  be/test/vec/data_types/serde/data_type_from_string_test.cpp
  regression-test/data/datatype_p0/nested_types/query/test_nestedtypes_csv_insert_into_with_s3.out
  regression-test/data/datatype_p0/nested_types/query/test_nestedtypes_json_insert_into_with_s3.out
  regression-test/data/function_p0/cast/test_cast_to_complex_types_strict.out
  regression-test/data/load_p0/broker_load/simple_array.csv
  regression-test/data/load_p0/stream_load/basic_array_data_with_errors.csv
  regression-test/data/load_p0/stream_load/test_map.csv
  regression-test/data/load_p0/stream_load/test_map_load_and_function.out
  regression-test/data/load_p0/stream_load/test_stream_load_properties.out
  regression-test/data/query_p0/sql_functions/cast_function/test_cast_string_to_array.out
  regression-test/suites/function_p0/cast/test_cast_to_complex_types_strict.groovy
  regression-test/suites/load_p0/stream_load/test_stream_load_properties.groovy
  regression-test/suites/unique_with_mow_p0/flexible/legacy/test_f_complex_type_schema_change.groovy
Labels: approved, reviewed

#54282 [fix](case) catch exception to figure out failures
  regression-test/suites/cloud_p1/schema_change/compaction9/test_schema_change_with_compaction9.groovy
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x, p0_test

#53979 [enhance](transaction) add completeness of commit tablet info check in cloud mode
  be/src/vec/sink/writer/vtablet_writer.cpp
  fe/fe-core/src/main/java/org/apache/doris/cloud/transaction/CloudGlobalTransactionMgr.java
  regression-test/suites/fault_injection_p0/test_incomplete_commit_info.groovy
Labels: approved, reviewed, p0_b, dev/3.0.x, dev/3.1.x

#54287 [fix](test) fix test_black_list fail
  regression-test/suites/load_p0/routine_load/test_black_list.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x, dev/3.1.x, p0_test

#54245 [Chore](nereids) Remove DropEncryptKeyStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/DropEncryptKeyStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/EncryptKeyHelper.java
  fe/fe-core/src/main/java/org/apache/doris/qe/DdlExecutor.java
Labels: approved, reviewed

#54321 [bug] [k8s]update variable have not prefix
  docker/runtime/fe/resource/fe_entrypoint.sh
Labels: approved, reviewed

#54319 [fix](case) do not use global var in groovy
  regression-test/suites/cloud_p1/schema_change/compaction1/test_schema_change_with_compaction1.groovy
  regression-test/suites/cloud_p1/schema_change/compaction10/test_schema_change_with_compaction10.groovy
  regression-test/suites/cloud_p1/schema_change/compaction2/test_schema_change_with_compaction2.groovy
  regression-test/suites/cloud_p1/schema_change/compaction3/test_schema_change_with_compaction3.groovy
  regression-test/suites/cloud_p1/schema_change/compaction4/test_schema_change_with_compaction4.groovy
  regression-test/suites/cloud_p1/schema_change/compaction5/test_schema_change_with_compaction5.groovy
  regression-test/suites/cloud_p1/schema_change/compaction6/test_schema_change_with_compaction6.groovy
  regression-test/suites/cloud_p1/schema_change/compaction7/test_schema_change_with_compaction7.groovy
  regression-test/suites/cloud_p1/schema_change/compaction8/test_schema_change_with_compaction8.groovy
  regression-test/suites/cloud_p1/schema_change/compaction9/test_schema_change_with_compaction9.groovy
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x, p0_test

#54302 [Chore](agg) add creator_with_type_list and any_value/ndv/avg/avg_weighted/min/max case
  be/src/vec/aggregate_functions/aggregate_function_approx_count_distinct.cpp
  be/src/vec/aggregate_functions/aggregate_function_avg.cpp
  be/src/vec/aggregate_functions/helpers.h
  regression-test/data/query_p0/aggregate/support_type/any_value/any_value.out
  regression-test/data/query_p0/aggregate/support_type/avg/avg.out
  regression-test/data/query_p0/aggregate/support_type/avg_weighted/avg_weighted.out
  regression-test/data/query_p0/aggregate/support_type/max/max.out
  regression-test/data/query_p0/aggregate/support_type/min/min.out
  regression-test/data/query_p0/aggregate/support_type/ndv/ndv.out
  regression-test/suites/query_p0/aggregate/support_type/any_value/any_value.groovy
  regression-test/suites/query_p0/aggregate/support_type/avg/avg.groovy
  regression-test/suites/query_p0/aggregate/support_type/avg_weighted/avg_weighted.groovy
  regression-test/suites/query_p0/aggregate/support_type/max/max.groovy
  regression-test/suites/query_p0/aggregate/support_type/min/min.groovy
  regression-test/suites/query_p0/aggregate/support_type/ndv/ndv.groovy
Labels: approved, reviewed

#54256 [chore](cloud) Add some helper functions
  cloud/src/meta-store/meta_reader.cpp
  cloud/src/meta-store/meta_reader.h
  cloud/src/meta-store/versioned_value.cpp
  cloud/src/meta-store/versioned_value.h
  cloud/src/meta-store/versionstamp.h
  cloud/test/meta_reader_test.cpp
  cloud/test/versioned_value_test.cpp
Labels: approved, reviewed, cloud, snapshot

#54301 [refine](cast) Add the line processing function of cast to string
  be/src/vec/data_types/data_type_date.cpp
  be/src/vec/data_types/data_type_date_or_datetime_v2.cpp
  be/src/vec/data_types/data_type_date_time.cpp
  be/src/vec/data_types/data_type_decimal.cpp
  be/src/vec/data_types/data_type_ipv4.cpp
  be/src/vec/data_types/data_type_ipv6.cpp
  be/src/vec/data_types/data_type_number.cpp
  be/src/vec/data_types/data_type_time.cpp
  be/src/vec/functions/cast/cast_to_string.h
  be/src/vec/functions/cast/cast_to_variant.h
  be/test/vec/function/cast/cast_to_string_api_test.cpp
Labels: approved, reviewed

#53202 [fix](nereids)prevent NullPointerException in visitWarmUpCluster method
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
Labels: approved, reviewed

#54096 [Chore](nereids) Remove CreateFunctionStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateFunctionStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/AggregateFunction.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/ScalarFunction.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/CreateFunctionCommand.java
  fe/fe-core/src/main/java/org/apache/doris/qe/DdlExecutor.java
Labels: approved, reviewed

#54335 [regression-test](variant) add disable_variant_flatten_nested session var conf in nest table test case
  regression-test/suites/variant_github_events_nonConcurrent_upgrade_p2/load.groovy
Labels: approved, reviewed, dev/3.1.x

#54314 [refine](cast) Remove the rollback logic from parsing complex types.
  be/src/vec/data_types/serde/data_type_nullable_serde.cpp
  be/src/vec/data_types/serde/data_type_struct_serde.cpp
Labels: approved, reviewed

#54293 [feat](Variant) Add Schema Templates Syntax and Parsing
  fe/fe-common/src/main/java/org/apache/doris/catalog/ScalarType.java
  fe/fe-common/src/main/java/org/apache/doris/catalog/Type.java
  fe/fe-common/src/main/java/org/apache/doris/catalog/VariantField.java
  fe/fe-common/src/main/java/org/apache/doris/catalog/VariantType.java
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisLexer.g4
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/analysis/CastExpr.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Column.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/check/CheckCast.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/VariantSubPathPruning.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/generator/ExplodeVariantArray.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/ElementAt.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/types/DataType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/types/VariantField.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/types/VariantType.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/util/StatisticsUtil.java
  fe/fe-core/src/test/java/org/apache/doris/persist/ScalarTypeTest.java
  regression-test/data/variant_p0/predefine/test_predefine_ddl.out
  regression-test/suites/variant_p0/predefine/test_predefine_ddl.groovy
Labels: approved, reviewed

#54341 [fix](test) fix test_routine_load_job_schedule unstable
  regression-test/suites/load_p0/routine_load/test_routine_load_job_schedule.groovy
Labels: approved, reviewed, dev/3.1.x

#54348 [fix](array) Fix array distance functions
  be/src/vec/functions/array/function_array_distance.h
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/CosineDistance.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/InnerProduct.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/L1Distance.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/L2Distance.java
  regression-test/data/query_p0/sql_functions/array_functions/test_array_distance_functions.out
  regression-test/suites/query_p0/sql_functions/array_functions/test_array_distance_functions.groovy
Labels: approved, reviewed, usercase, dev/3.0.x, dev/3.1.x

#53796 [feat](cloud) Write and recycle commit_index and drop_index log
  cloud/src/meta-service/meta_service_partition.cpp
  cloud/src/recycler/recycler.cpp
  cloud/src/recycler/recycler_operation_log.cpp
  cloud/test/meta_service_operation_log_test.cpp
  cloud/test/recycler_operation_log_test.cpp
  gensrc/proto/cloud.proto
Labels: approved, reviewed

#54360 [fix](case) remove global variable declarations in compaction test [f…
  regression-test/suites/cloud_p1/schema_change/compaction1/test_schema_change_with_compaction1.groovy
  regression-test/suites/cloud_p1/schema_change/compaction10/test_schema_change_with_compaction10.groovy
  regression-test/suites/cloud_p1/schema_change/compaction11/test_schema_change_with_compaction11.groovy
  regression-test/suites/cloud_p1/schema_change/compaction2/test_schema_change_with_compaction2.groovy
  regression-test/suites/cloud_p1/schema_change/compaction3/test_schema_change_with_compaction3.groovy
  regression-test/suites/cloud_p1/schema_change/compaction4/test_schema_change_with_compaction4.groovy
  regression-test/suites/cloud_p1/schema_change/compaction5/test_schema_change_with_compaction5.groovy
  regression-test/suites/cloud_p1/schema_change/compaction6/test_schema_change_with_compaction6.groovy
  regression-test/suites/cloud_p1/schema_change/compaction7/test_schema_change_with_compaction7.groovy
  regression-test/suites/cloud_p1/schema_change/compaction8/test_schema_change_with_compaction8.groovy
  regression-test/suites/cloud_p1/schema_change/compaction9/test_schema_change_with_compaction9.groovy
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x, p0_test

#53420 [Chore](nereids) Remove DropRepositoryStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/DropRepositoryStmt.java
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupHandler.java
  fe/fe-core/src/main/java/org/apache/doris/qe/DdlExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/backup/BackupHandlerTest.java
Labels: approved, reviewed

#54383 [Chore](nereids) Remove AlterColocateGroupStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/AlterColocateGroupStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/ColocateTableIndex.java
  fe/fe-core/src/main/java/org/apache/doris/qe/DdlExecutor.java
Labels: approved, reviewed

#54347 [feature](cast)Implement complex type cast.
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/check/CheckCast.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/JsonLiteral.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/expression/check/CheckCastTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/expressions/CastTest.java
Labels: approved, reviewed

#51763 [fix](mow) fix check delete bitmap for mow tables with seq column
  be/src/olap/base_tablet.cpp
  cloud/src/recycler/checker.cpp
  cloud/src/recycler/checker.h
  cloud/test/recycler_test.cpp
  regression-test/data/compaction/test_mow_compaction_agg_and_remove_pre_delete_bitmap.out
  regression-test/suites/compaction/test_mow_compaction_agg_and_remove_pre_delete_bitmap.groovy
Labels: approved, reviewed, dev/3.1.x

#53834 [fix](nereids) fix bug in StatsCalculator.disableJoinReorderIfStatsInvalid when rowCount is not aviable
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/InitJoinOrder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/StatsCalculator.java
  regression-test/data/nereids_p0/join/invalid_stats/invalid_stats_join_order.out
  regression-test/data/nereids_rules_p0/agg_skew_rewrite/agg_skew_rewrite.out
  regression-test/data/nereids_rules_p0/constant_propagation/constant_propagation.out
  regression-test/suites/nereids_p0/join/invalid_stats/invalid_stats_join_order.groovy
  regression-test/suites/nereids_rules_p0/agg_skew_rewrite/agg_skew_rewrite.groovy
  regression-test/suites/nereids_rules_p0/constant_propagation/constant_propagation.groovy
  regression-test/suites/nereids_rules_p0/mv/ssb/mv_ssb_test.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x, dev/3.1.x

#54389 [Chore](nereids) Remove CreateCatalogStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateCatalogStmt.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/CatalogFactory.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/CatalogMgr.java
  fe/fe-core/src/main/java/org/apache/doris/qe/DdlExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/RefreshDbTest.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/RefreshTableTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/ColumnPrivTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/ExternalCatalogTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/RefreshCatalogTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/hive/HiveDDLAndDMLPlanTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/iceberg/CreateIcebergTableTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/lowercase/ExternalTableNameComparedLowercaseMetaCacheFalseTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/lowercase/ExternalTableNameComparedLowercaseMetaCacheTrueTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/lowercase/ExternalTableNameStoredLowercaseMetaCacheFalseTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/lowercase/ExternalTableNameStoredLowercaseMetaCacheTrueTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/property/PropertyConverterTest.java
  fe/fe-core/src/test/java/org/apache/doris/external/hms/HmsCatalogTest.java
  fe/fe-core/src/test/java/org/apache/doris/qe/HmsQueryCacheTest.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/TestWithFeService.java
Labels: approved, reviewed

#54380 [Chore](nereids) Remove ShowCreateMTMVStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowCreateMTMVStmt.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
Labels: approved, reviewed

#54363 [fix](filecache) warm up download data less than actual
  be/src/io/cache/block_file_cache_downloader.cpp
Labels: reviewed, p0_b, dev/3.0.x, dev/3.1.x, cloud

#54381 [Chore](nereids) Remove DropFunctionStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/DropFunctionStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/qe/DdlExecutor.java
Labels: approved, reviewed

#53751 [fix](vcg) use "vcg cancel" as cancel message for warm up jobs
  fe/fe-core/src/main/java/org/apache/doris/cloud/CacheHotspotManager.java
Labels: approved, reviewed, dev/3.1.0-merged, cloud, dev/3.0.7-merged

#54369 [fix](test) make test_writer_fault_injection do not affected by other cases
  regression-test/suites/fault_injection_p0/test_writer_fault_injection.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x, dev/3.1.x, p0_test

#54413 [fix](variant) change session var for disable_variant_flatten_nested to enable_variant_flatten_nested
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  regression-test/suites/variant_p0/delete_update.groovy
  regression-test/suites/variant_p0/nested.groovy
  regression-test/suites/variant_p0/schema_change/test_double_write_when_schema_change.groovy
Labels: approved, reviewed, dev/3.1.x

#54388 [Chore](nereids) remove CreateWorkloadSchedPolicyStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateWorkloadSchedPolicyStmt.java
  fe/fe-core/src/main/java/org/apache/doris/qe/DdlExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/resource/workloadschedpolicy/WorkloadSchedPolicyMgr.java
Labels: approved, reviewed

#54424 [fix](statistics)Fix drop expired stats.
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsCleaner.java
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x

#54322 [fix](txn lazy commit) fix multi table load error with txn lazy commit
  cloud/src/meta-service/meta_service_txn.cpp
  cloud/src/meta-service/txn_lazy_committer.cpp
  cloud/test/txn_lazy_commit_test.cpp
Labels: approved, reviewed, p0_w, dev/3.0.x, dev/3.1.x

#54187 [opt](mtmv) Should not mv rewrite when point query short circuit
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/InitMaterializationContextHook.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/mv/PointQueryShouldNotMvRewriteTest.java
  regression-test/suites/nereids_rules_p0/mv/agg_optimize_when_uniform/agg_optimize_when_uniform.groovy
  regression-test/suites/point_query_p0/test_should_not_mv_rewrite.groovy
Labels: approved, reviewed, usercase, dev/2.1.x, dev/3.0.x, dev/3.1.x

#54422 [feature](nereids) support explain command return empty string to test planner performance
  fe/fe-core/src/main/java/org/apache/doris/nereids/NereidsPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/planner/Planner.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/ExplainInsertCommandTest.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x, dev/3.1.x

#54416 [opt](warm up) support delaying compaction commit until rowset warm-up finishes
  be/src/cloud/cloud_internal_service.cpp
  be/src/cloud/cloud_meta_mgr.cpp
  be/src/cloud/cloud_warm_up_manager.cpp
  be/src/cloud/cloud_warm_up_manager.h
  be/src/cloud/config.cpp
  be/src/cloud/config.h
  be/src/io/fs/s3_file_reader.cpp
  gensrc/proto/internal_service.proto
  regression-test/suites/cloud_p0/cache/multi_cluster/warm_up/cluster/test_warm_up_cluster_event_compaction_sync_wait.groovy
  regression-test/suites/cloud_p0/cache/multi_cluster/warm_up/cluster/test_warm_up_cluster_event_compaction_sync_wait_timeout.groovy
Labels: approved, reviewed

#54278 [refactor](cloud) Add versioned read checking
  cloud/src/meta-service/meta_service.cpp
  cloud/src/meta-service/meta_service.h
  cloud/src/meta-service/meta_service_job.cpp
  cloud/src/meta-service/meta_service_partition.cpp
  cloud/src/meta-service/meta_service_txn.cpp
  cloud/src/meta-service/txn_lazy_committer.cpp
  cloud/test/txn_lazy_commit_test.cpp
  gensrc/proto/cloud.proto
Labels: approved, reviewed, cloud, snapshot

#54156 [fix](fe) Fix S3Resource cannot alter iam role arn and ak/sk
  fe/fe-core/src/main/java/org/apache/doris/catalog/S3Resource.java
  regression-test/suites/aws_iam_role_p0/test_alter_resource_with_role.groovy
Labels: approved, reviewed, usercase, dev/3.0.x, dev/3.1.x

#54403 [fix](checker) Fix inverted check and test for checker
  cloud/src/recycler/checker.cpp
  cloud/test/recycler_test.cpp
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x, p0_test

#54415 [fix](nereids)fix sql be blocked fall back to legacy planner
  fe/fe-core/src/main/java/org/apache/doris/blockrule/SqlBlockRuleMgr.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/blockrule/SqlBlockRuleMgrTest.java
  regression-test/suites/sql_block_rule_p0/block_not_fall_back.groovy
Labels: approved, reviewed, dev/2.1.x

#54450 branch-3.0: [fix](binlog)default partition dont append version_info
  fe/fe-core/src/main/java/org/apache/doris/binlog/AddPartitionRecord.java
Labels: approved, reviewed

#54433 [fix](test) Fix two regression test
  docker/runtime/doris-compose/database.py
  regression-test/suites/datatype_p0/nested_types/query/test_nestedtypes_json_insert_into_with_s3.groovy
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x, p0_test

#54394 [feat](cloud) change the type to optional in the alter storage vault command
  fe/fe-core/src/main/java/org/apache/doris/catalog/StorageVaultMgr.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/AlterStorageVaultCommand.java
  regression-test/suites/vault_p0/alter/test_alter_vault_type.groovy
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x, p0_easy

#54437 [conf](pool) incrase `fragment_mgr_async_work_pool_thread_num_max`
  be/src/common/config.cpp
Labels: approved, reviewed

#54386 [Chore](nereids) remove AlterWorkloadSchedPolicyStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/AlterWorkloadSchedPolicyStmt.java
  fe/fe-core/src/main/java/org/apache/doris/qe/DdlExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/resource/workloadschedpolicy/WorkloadSchedPolicyMgr.java
Labels: approved, reviewed

#54472 [Chore](nereids) remove AlterRepositoryStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/AlterRepositoryStmt.java
  fe/fe-core/src/main/java/org/apache/doris/qe/DdlExecutor.java
Labels: approved, reviewed

#54375 [refine](from string) remove from string function in datatype
  be/src/olap/base_tablet.cpp
  be/src/olap/rowset/segment_v2/vertical_segment_writer.cpp
  be/src/vec/data_types/data_type.cpp
  be/src/vec/data_types/data_type.h
  be/src/vec/data_types/data_type_array.cpp
  be/src/vec/data_types/data_type_array.h
  be/src/vec/data_types/data_type_bitmap.cpp
  be/src/vec/data_types/data_type_bitmap.h
  be/src/vec/data_types/data_type_date.cpp
  be/src/vec/data_types/data_type_date.h
  be/src/vec/data_types/data_type_date_or_datetime_v2.cpp
  be/src/vec/data_types/data_type_date_or_datetime_v2.h
  be/src/vec/data_types/data_type_date_time.cpp
  be/src/vec/data_types/data_type_date_time.h
  be/src/vec/data_types/data_type_decimal.cpp
  be/src/vec/data_types/data_type_decimal.h
  be/src/vec/data_types/data_type_hll.cpp
  be/src/vec/data_types/data_type_hll.h
  be/src/vec/data_types/data_type_ipv4.cpp
  be/src/vec/data_types/data_type_ipv4.h
  be/src/vec/data_types/data_type_ipv6.cpp
  be/src/vec/data_types/data_type_ipv6.h
  be/src/vec/data_types/data_type_jsonb.cpp
  be/src/vec/data_types/data_type_jsonb.h
  be/src/vec/data_types/data_type_map.cpp
  be/src/vec/data_types/data_type_map.h
  be/src/vec/data_types/data_type_nullable.cpp
  be/src/vec/data_types/data_type_nullable.h
  be/src/vec/data_types/data_type_number_base.cpp
  be/src/vec/data_types/data_type_number_base.h
  be/src/vec/data_types/data_type_string.cpp
  be/src/vec/data_types/data_type_string.h
  be/src/vec/data_types/data_type_struct.cpp
  be/src/vec/data_types/data_type_struct.h
  be/src/vec/data_types/serde/data_type_serde.cpp
  be/src/vec/data_types/serde/data_type_serde.h
  be/src/vec/functions/cast/cast_to_jsonb.h
  be/test/vec/data_types/serde/data_type_serde_text_test.cpp
Labels: approved, reviewed

#54379 [Chore](nereids) Remove ShowCreateLoadStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowCreateLoadStmt.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
Labels: approved, reviewed

#54465 [Chore](nereids) Remove DropCatalogStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/DropCatalogStmt.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/CatalogMgr.java
  fe/fe-core/src/main/java/org/apache/doris/qe/DdlExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/RefreshDbTest.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/RefreshTableTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/ColumnPrivTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/RefreshCatalogTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/lowercase/ExternalTableNameComparedLowercaseMetaCacheFalseTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/lowercase/ExternalTableNameComparedLowercaseMetaCacheTrueTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/lowercase/ExternalTableNameStoredLowercaseMetaCacheFalseTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/lowercase/ExternalTableNameStoredLowercaseMetaCacheTrueTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/property/PropertyConverterTest.java
Labels: approved, reviewed

#54467 [Chore](nereids) remove AlterJobStatusStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/AlterJobStatusStmt.java
  fe/fe-core/src/main/java/org/apache/doris/qe/DdlExecutor.java
Labels: approved, reviewed

#54419 [fix](sc) retry on network error
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/alter/AlterJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/alter/RollupJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/task/AgentBatchTask.java
  regression-test/suites/cloud_p1/schema_change/compaction11/test_schema_change_with_compaction11.groovy
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x, p0_easy

#54440 [case](schema)fix case test_temp_table
  regression-test/suites/temp_table_p0/test_temp_table.groovy
Labels: approved, reviewed, dev/3.1.x

#54477 [feat](cloud) get_version support versioned read
  cloud/src/meta-service/meta_service.cpp
  cloud/src/meta-service/meta_service.h
  cloud/test/CMakeLists.txt
  cloud/test/meta_service_test.cpp
  cloud/test/meta_service_versioned_read_test.cpp
Labels: approved, reviewed, cloud, snapshot

#54002 [feat](checker) Add meta key consistency checking for checker
  cloud/src/common/config.h
  cloud/src/recycler/meta_checker.cpp
  cloud/src/recycler/meta_checker.h
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x, p0_test

#54481 [fix](case) fix some case
  regression-test/data/insert_p0/insert_group_commit_into.out
  regression-test/data/insert_p0/transaction/txn_insert_restart_fe_with_schema_change.out
  regression-test/suites/insert_p0/group_commit/replay_wal_restart_fe.groovy
  regression-test/suites/insert_p0/insert_group_commit_into.groovy
  regression-test/suites/insert_p0/test_group_commit_timeout.groovy
  regression-test/suites/insert_p0/transaction/txn_insert_restart_fe_with_schema_change.groovy
  regression-test/suites/schema_change_p0/test_unique_schema_key_change_multi_tablets.groovy
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x

#54407 [feat](variant) add ComputeSignature and get variant type function
  be/src/vec/functions/function_variant_type.cpp
  be/src/vec/functions/simple_function_factory.h
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinScalarFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/ComputeSignature.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/ComputeSignatureHelper.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/GetVariantType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/ScalarFunctionVisitor.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/expressions/functions/ComputeSignatureHelperTest.java
  regression-test/data/variant_p0/load.out
  regression-test/suites/variant_p0/load.groovy
Labels: approved, reviewed

#53656 [enhance](recycler)collect fdb metric when recycler start
  cloud/src/main.cpp
  cloud/src/meta-service/meta_server.cpp
  cloud/src/meta-service/meta_server.h
  cloud/test/meta_server_test.cpp
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x, cloud, p0_easy

#54300 [Fix](MS)Handle missing endpoint in DLF-only Metastore scenario with region fallback
  fe/fe-core/src/main/java/org/apache/doris/common/util/PathUtils.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HMSTransaction.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/event/MetastoreEventsProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/dlf/DLFCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/paimon/source/PaimonScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/metastore/AliyunDLFBaseProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/metastore/HMSAliyunDLFMetaStoreProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/metastore/HMSBaseProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/metastore/IcebergAliyunDLFMetaStoreProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/metastore/IcebergFileSystemMetaStoreProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/metastore/IcebergHMSMetaStoreProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/storage/AbstractS3CompatibleProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/storage/COSProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/storage/OBSProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/storage/OSSProperties.java
  fe/fe-core/src/main/java/org/apache/doris/planner/HiveTableSink.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/IcebergTableValuedFunction.java
  fe/fe-core/src/test/java/org/apache/doris/common/util/PathUtilsTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/property/metastore/AliyunDLFBasePropertiesTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/property/metastore/AliyunDLFPropertiesTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/property/storage/OSSPropertiesTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/HiveTableSinkTest.java
Labels: approved, reviewed, dev/3.1.x

#54514 [chore](build) Update build script
  gensrc/script/Makefile
  gensrc/script/gen_build_version.sh
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x, p0_easy

#54343 [Opt](Clone) Use log debug instead DCHECK when get_peers_replica_backends reps is empty
  be/src/olap/storage_engine.cpp
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x, dev/3.1.x, p0_test

#54515 [Func](exec) allow not nullable column call non_nullable func
  be/src/vec/functions/function_nullables.cpp
  regression-test/data/query_p0/sql_functions/cast_function/test_nullable_functions.out
  regression-test/suites/query_p0/sql_functions/cast_function/test_nullable_functions.groovy
Labels: approved, reviewed

#54133 [fix](nereids) project distinct to agg checker exclude window function
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/BindExpression.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/CheckAnalysis.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/OneRowRelationExtractAggregate.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/ProjectToGlobalAggregate.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/ProjectWithDistinctToAggregate.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/ExpressionUtils.java
  regression-test/data/nereids_rules_p0/project_distinct_to_agg/project_distinct_to_agg.out
  regression-test/plugins/plugin_planner.groovy
  regression-test/suites/nereids_rules_p0/project_distinct_to_agg/project_distinct_to_agg.groovy
Labels: approved, reviewed, usercase, p0_w, dev/2.1.x, dev/3.0.x, dev/3.1.x

#54359 [Opt](cast) Speed up new cast to datelike type
  be/src/util/asan_util.h
  be/src/util/string_parser.hpp
  be/src/vec/functions/cast/cast_base.h
  be/src/vec/functions/cast/cast_parameters.h
  be/src/vec/functions/cast/cast_to_date_or_datetime_impl.hpp
  be/src/vec/functions/cast/cast_to_datetimev2_impl.hpp
  be/src/vec/functions/cast/cast_to_datev2_impl.hpp
  be/src/vec/functions/cast/cast_to_time_impl.hpp
  be/test/vec/function/cast/cast_to_time_test.cpp
  regression-test/data/cast_p0/cast_to_time.out
  regression-test/suites/cast_p0/cast_to_time.groovy
Labels: approved, reviewed

#54497 [feat](cloud) get_rowset support versioned read
  cloud/src/meta-service/meta_service.cpp
  cloud/src/meta-store/meta_reader.cpp
  cloud/src/meta-store/meta_reader.h
  cloud/test/meta_reader_test.cpp
  cloud/test/meta_service_test.cpp
  cloud/test/meta_service_versioned_read_test.cpp
Labels: approved, reviewed, cloud, snapshot

#54519 [chore](build) Fix macOS compilation without PCH enabled
  be/CMakeLists.txt
  be/src/pipeline/dependency.h
  be/src/vec/common/allocator.h
  be/src/vec/core/wide_integer.h
  be/src/vec/core/wide_integer_impl.h
Labels: approved, reviewed

#54521 [Enhancement](build) disable build azure on arm and suppress libunwind build warning
  build.sh
  env.sh
  thirdparty/build-thirdparty.sh
Labels: approved, reviewed

#54353 [fix](nereids) set CompoundPredicate.nullableFromNereids after flattern and/or
  fe/fe-core/src/main/java/org/apache/doris/analysis/Expr.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/ExpressionTranslator.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/glue/translator/ExpressionTranslatorTest.java
Labels: approved, reviewed, dev/3.1.x

#54243 [workloadgroup](improvement) using min/max cpu and memory percent to unify soft and hard limit
  be/src/agent/cgroup_cpu_ctl.cpp
  be/src/agent/cgroup_cpu_ctl.h
  be/src/exec/schema_scanner/schema_workload_groups_scanner.cpp
  be/src/runtime/workload_group/workload_group.cpp
  be/src/runtime/workload_group/workload_group.h
  be/src/runtime/workload_group/workload_group_manager.cpp
  be/test/runtime/memory/thread_mem_tracker_mgr_test.cpp
  be/test/runtime/workload_group/workload_group_manager_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/catalog/SchemaTable.java
  fe/fe-core/src/main/java/org/apache/doris/resource/workloadgroup/WorkloadGroup.java
  fe/fe-core/src/main/java/org/apache/doris/resource/workloadgroup/WorkloadGroupMgr.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/MetadataGenerator.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/commands/GrantResourcePrivilegeCommandTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/commands/RevokeResourcePrivilegeCommandTest.java
  fe/fe-core/src/test/java/org/apache/doris/resource/workloadgroup/WorkloadGroupMgrTest.java
  fe/fe-core/src/test/java/org/apache/doris/resource/workloadgroup/WorkloadGroupTest.java
  gensrc/thrift/BackendService.thrift
  regression-test/data/workload_manager_p0/test_curd_wlg.out
  regression-test/suites/account_p0/test_grant_priv_workload.groovy
  regression-test/suites/auth_p0/test_master_slave_consistency_auth.groovy
  regression-test/suites/auth_up_down_p0/load.groovy
  regression-test/suites/load_p0/broker_load/test_s3_load.groovy
  regression-test/suites/load_p0/routine_load/test_routine_load.groovy
  regression-test/suites/load_p2/broker_load/test_s3_load_properties.groovy
  regression-test/suites/load_p2/routine_load/test_routine_load.groovy
  regression-test/suites/nereids_p0/ddl/grant/test_grant_nereids.groovy
  regression-test/suites/ranger_p2/test_ranger_access_resource_workload_group.groovy
  regression-test/suites/workload_manager_p0/test_curd_wlg.groovy
  regression-test/suites/workload_manager_p0/test_workload_sched_policy.groovy
Labels: approved, reviewed

#54526 [Chore](nereids) Remove CopyStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/CopyStmt.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/load/CloudLoadManager.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/load/CopyJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BulkLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/CopyIntoCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/CopyIntoInfo.java
  fe/fe-core/src/main/java/org/apache/doris/qe/DdlExecutor.java
Labels: approved, reviewed

#53818 [Enhancement] add show create storage vault
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PlanType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ShowCreateStorageVaultCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/CommandVisitor.java
  regression-test/suites/vault_p0/create/test_nereids_show_create_storage_vault.groovy
Labels: approved, reviewed

#54547 [Chore](memory) add jemalloc_hook to make jemalloc control malloc
  be/src/runtime/CMakeLists.txt
  be/src/runtime/memory/jemalloc_hook.cpp
  build.sh
  cloud/src/common/CMakeLists.txt
Labels: approved, reviewed

#54392 [k8s][computegroup]script support use right cg name to add backend
  docker/runtime/base-image/Dockerfile_base
  docker/runtime/be/Dockerfile
  docker/runtime/be/resource/be_disaggregated_entrypoint.sh
  docker/runtime/broker/Dockerfile
  docker/runtime/fe/Dockerfile
  docker/runtime/ms/Dockerfile
Labels: approved, reviewed

#54382 [chore](cloud) Optimize fuzzy test for txn lazy commit
  cloud/src/common/config.h
  cloud/src/meta-service/meta_service_txn.cpp
  cloud/test/txn_lazy_commit_test.cpp
  regression-test/pipeline/cloud_p0/conf/ms_custom.conf
  regression-test/pipeline/cloud_p1/conf/ms_custom.conf
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x, cloud

#54518 [fix](checker) Use `cloud::blob_get/put` to get tablet schema
  cloud/src/recycler/checker.cpp
  cloud/test/recycler_test.cpp
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x, p0_test

#54548 [fix](audit log) fix audit log return rows incorrect when statement need forward
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/FEOpExecutor.java
  gensrc/thrift/FrontendService.thrift
  regression-test/suites/load_p0/insert/test_insert_from_follower.groovy
Labels: approved, reviewed, usercase, dev/3.0.x, dev/3.1.x

#54578 [fix](test)fix failed test case by add alias for select list item
  regression-test/data/schema_change_p0/test_index_change_after_mv.out
  regression-test/suites/schema_change_p0/test_index_change_after_mv.groovy
Labels: approved, reviewed

#54536 [Chore](nereids) remove DropSqlBlockRuleStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/DropSqlBlockRuleStmt.java
  fe/fe-core/src/main/java/org/apache/doris/blockrule/SqlBlockRuleMgr.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/DropSqlBlockRuleCommand.java
  fe/fe-core/src/main/java/org/apache/doris/qe/DdlExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/TestWithFeService.java
Labels: approved, reviewed

#53989 branch-3.0: [opt](nereids) opt range inference for or expression when out of order #46303
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/SimplifyRange.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/expression/SimplifyRangeTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/mv/BaseMaterializedIndexSelectTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/mv/SelectMvIndexTest.java
Labels: reviewed

#53897 branch-3.0 cherry-pick [fix](variant) fix the reading core caused by inserting nested column and scalar column in variant sub-column
  be/src/cloud/cloud_meta_mgr.cpp
  be/src/cloud/schema_cloud_dictionary_cache.cpp
  be/src/olap/base_tablet.cpp
  be/src/olap/rowset/beta_rowset_writer.cpp
  be/src/olap/rowset/beta_rowset_writer.h
  be/src/olap/rowset/segment_v2/hierarchical_data_reader.h
  be/src/service/internal_service.cpp
  be/src/vec/common/schema_util.cpp
  be/src/vec/common/schema_util.h
  be/src/vec/json/parse2column.cpp
  be/test/cloud/test_schema_cloud_dictionary_cache.cpp
  be/test/common/schema_util_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  gensrc/thrift/AgentService.thrift
  regression-test/data/variant_p0/nested/load.out
  regression-test/data/variant_p0/nested/sql/q01.out
  regression-test/suites/variant_p0/delete_update.groovy
  regression-test/suites/variant_p0/nested.groovy
  regression-test/suites/variant_p0/nested/load.groovy
  regression-test/suites/variant_p0/nested/sql/q01.sql
  regression-test/suites/variant_p0/nested2.groovy
  regression-test/suites/variant_p0/schema_change/test_double_write_when_schema_change.groovy
Labels: approved, reviewed

#54589 [Chore](nereids) remove ShowWarningStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowWarningStmt.java
Labels: approved, reviewed

#54572 [ci](perf) use ldb-toolchain v0.26
  regression-test/pipeline/performance/compile.sh
Labels: approved, reviewed

#54167 branch-3.0:[fix](orc)fix core that iceberg-orc reader read miss iceberg.id orc file.(#49051)
  be/src/vec/exec/format/orc/vorc_reader.cpp
  be/src/vec/exec/format/orc/vorc_reader.h
  be/src/vec/exec/format/parquet/schema_desc.h
  be/src/vec/exec/format/table/iceberg_reader.cpp
  be/src/vec/exec/format/table/iceberg_reader.h
  be/src/vec/exec/format/table/table_format_reader.cpp
  be/src/vec/exec/format/table/table_format_reader.h
  be/src/vec/exec/format/table/transactional_hive_reader.cpp
  be/src/vec/exec/scan/vfile_scanner.cpp
  docker/thirdparties/docker-compose/iceberg/scripts/create_preinstalled_scripts/iceberg/run08.sql
  regression-test/data/external_table_p0/iceberg/iceberg_schema_change2.out
  regression-test/suites/external_table_p0/iceberg/iceberg_schema_change2.groovy
Labels: approved, reviewed

#54491 branch-3.0: [fix](txn lazy commit) fix multi table load error with txn lazy commit #54322
  cloud/src/meta-service/meta_service_txn.cpp
  cloud/src/meta-service/txn_lazy_committer.cpp
  cloud/test/txn_lazy_commit_test.cpp
Labels: approved, reviewed

#54525 [fix](iceberg) Remove duplicated warehouse propert
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/metastore/IcebergRestProperties.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/property/metastore/IcebergRestPropertiesTest.java
Labels: approved, reviewed, dev/3.1.x

#54455 [opt](build) auto use llvm@16 to format BE's code on MacOS
  build-support/clang-format.sh
Labels: approved, reviewed

#52629 [opt](nereids) Improve sql parse performance by avoid parse twice when collect hint map
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/NereidsParser.java
Labels: approved, reviewed

#54409 [fix](config) dynamic set FE masterOnly config will lost after change MASTER
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/AdminSetFrontendConfigCommand.java
Labels: approved, reviewed, kind/behavior-changed, dev/2.1.x, dev/3.0.x, dev/3.1.x

#54556 [test](docker) adapt paimon on hms and s3/oss/obs/cos
  docker/thirdparties/docker-compose/hive/hadoop-hive-3x.env.tpl
  docker/thirdparties/docker-compose/hive/hive-3x_settings.env
  docker/thirdparties/docker-compose/hive/scripts/create_external_paimon_scripts/create_paimon_tables.hql
  docker/thirdparties/docker-compose/hive/scripts/hive-metastore.sh
  docker/thirdparties/docker-compose/kerberos/entrypoint-hive-master.sh
  docker/thirdparties/docker-compose/kerberos/hadoop-hive.env.tpl
  docker/thirdparties/docker-compose/kerberos/kerberos1_settings.env
  docker/thirdparties/docker-compose/kerberos/kerberos2_settings.env
  docker/thirdparties/run-thirdparties-docker.sh
Labels: approved, reviewed, dev/3.1.x

#54588 [Chore](nereids) remove CreateIndexPolicyStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateIndexPolicyStmt.java
  fe/fe-core/src/main/java/org/apache/doris/indexpolicy/IndexPolicyMgr.java
  fe/fe-core/src/main/java/org/apache/doris/qe/DdlExecutor.java
Labels: approved, reviewed

#54554 [minor](pipeline) Report error if fragment closed
  be/src/pipeline/pipeline_task.cpp
Labels: approved, reviewed

#54613 [feature](regression) add retry to stream load when connection reset by s3
  regression-test/framework/src/main/groovy/org/apache/doris/regression/action/StreamLoadAction.groovy
  regression-test/suites/tpcds_sf1_unique_ck_p1/load.groovy
  regression-test/suites/tpcds_sf1_unique_p1/load.groovy
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x, p0_test

#54597 [feat](cloud) index_exists/partition_exists support versioned read
  cloud/src/meta-service/meta_service_partition.cpp
  cloud/src/meta-store/meta_reader.cpp
  cloud/src/meta-store/meta_reader.h
  cloud/test/meta_reader_test.cpp
  cloud/test/meta_service_versioned_read_test.cpp
Labels: approved, reviewed, cloud, snapshot

#53924 [chore] reduce the time consumption of be ut
  be/test/vec/function/function_compressed_materialization_test.cpp
Labels: approved, reviewed

#54154 [opt](inverted index) enhance inverted index query profiling for better performance monitoring
  be/src/olap/olap_common.h
  be/src/olap/rowset/segment_v2/inverted_index/analyzer/analyzer.cpp
  be/src/olap/rowset/segment_v2/inverted_index/analyzer/analyzer.h
  be/src/olap/rowset/segment_v2/inverted_index/query/phrase_query.cpp
  be/src/olap/rowset/segment_v2/inverted_index/query/phrase_query.h
  be/src/olap/rowset/segment_v2/inverted_index_reader.cpp
  be/src/pipeline/exec/olap_scan_operator.cpp
  be/src/pipeline/exec/olap_scan_operator.h
  be/src/vec/exec/scan/olap_scanner.cpp
  be/test/olap/rowset/segment_v2/inverted_index/query/phrase_query_test.cpp
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x, cloud

#54397 [fix](load)fix load json format boolean type to int column.
  be/src/vec/exec/format/json/new_json_reader.cpp
  regression-test/data/load_p0/stream_load/test_json_load.out
  regression-test/data/load_p0/stream_load/test_read_boolean_to_int.json
  regression-test/suites/load_p0/stream_load/test_json_load.groovy
Labels: approved, reviewed, usercase, dev/3.0.x, dev/3.1.x

#54594 branch-2.1: [fix](hudi) fix quering hudi table with timestamp key (#53791)
  fe/fe-core/src/main/java/org/apache/doris/datasource/hudi/source/HudiCachedPartitionProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hudi/source/HudiPartitionProcessor.java
  regression-test/data/external_table_p2/hudi/test_hudi_partition_prune.out
  regression-test/suites/external_table_p2/hudi/test_hudi_partition_prune.groovy
Labels: approved, reviewed

#54565 [Enhancement](function) Support isnan,isinf
  be/src/vec/functions/math.cpp
  be/test/vec/function/function_math_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinScalarFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/executable/NumericArithmetic.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/IsInf.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/IsNan.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/ScalarFunctionVisitor.java
  regression-test/data/function_p0/isnan_isinf_function.out
  regression-test/suites/function_p0/isnan_isinf_function.groovy
Labels: approved, reviewed

#54436 [refine](Agg)Reduce the binary size by providing more information to agg
  be/src/vec/aggregate_functions/aggregate_function.h
  be/src/vec/aggregate_functions/aggregate_function_approx_count_distinct.h
  be/src/vec/aggregate_functions/aggregate_function_approx_top_k.h
  be/src/vec/aggregate_functions/aggregate_function_approx_top_sum.h
  be/src/vec/aggregate_functions/aggregate_function_array_agg.h
  be/src/vec/aggregate_functions/aggregate_function_avg.h
  be/src/vec/aggregate_functions/aggregate_function_avg_weighted.h
  be/src/vec/aggregate_functions/aggregate_function_binary.h
  be/src/vec/aggregate_functions/aggregate_function_bit.h
  be/src/vec/aggregate_functions/aggregate_function_bitmap.h
  be/src/vec/aggregate_functions/aggregate_function_bitmap_agg.h
  be/src/vec/aggregate_functions/aggregate_function_collect.h
  be/src/vec/aggregate_functions/aggregate_function_count.h
  be/src/vec/aggregate_functions/aggregate_function_count_by_enum.h
  be/src/vec/aggregate_functions/aggregate_function_covar.h
  be/src/vec/aggregate_functions/aggregate_function_distinct.h
  be/src/vec/aggregate_functions/aggregate_function_foreach.h
  be/src/vec/aggregate_functions/aggregate_function_group_array_intersect.h
  be/src/vec/aggregate_functions/aggregate_function_group_concat.h
  be/src/vec/aggregate_functions/aggregate_function_histogram.h
  be/src/vec/aggregate_functions/aggregate_function_hll_union_agg.h
  be/src/vec/aggregate_functions/aggregate_function_java_udaf.h
  be/src/vec/aggregate_functions/aggregate_function_linear_histogram.h
  be/src/vec/aggregate_functions/aggregate_function_map.h
  be/src/vec/aggregate_functions/aggregate_function_map_v2.h
  be/src/vec/aggregate_functions/aggregate_function_min_max_by.h
  be/src/vec/aggregate_functions/aggregate_function_orthogonal_bitmap.h
  be/src/vec/aggregate_functions/aggregate_function_percentile.h
  be/src/vec/aggregate_functions/aggregate_function_product.h
  be/src/vec/aggregate_functions/aggregate_function_retention.h
  be/src/vec/aggregate_functions/aggregate_function_sequence_match.h
  be/src/vec/aggregate_functions/aggregate_function_stddev.h
  be/src/vec/aggregate_functions/aggregate_function_sum.h
  be/src/vec/aggregate_functions/aggregate_function_topn.h
  be/src/vec/aggregate_functions/aggregate_function_uniq.h
  be/src/vec/aggregate_functions/aggregate_function_uniq_distribute_key.h
  be/src/vec/aggregate_functions/aggregate_function_window.cpp
  be/src/vec/aggregate_functions/aggregate_function_window.h
  be/src/vec/aggregate_functions/aggregate_function_window_funnel.h
  be/src/vec/aggregate_functions/helpers.h
  be/src/vec/exprs/vectorized_agg_fn.cpp
Labels: approved, reviewed

#54595 branch-3.0: [fix](hudi) fix quering hudi table with timestamp key (#53791)
  fe/fe-core/src/main/java/org/apache/doris/datasource/hudi/source/HudiCachedPartitionProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hudi/source/HudiPartitionProcessor.java
  regression-test/data/external_table_p2/hudi/test_hudi_partition_prune.out
  regression-test/suites/external_table_p2/hudi/test_hudi_partition_prune.groovy
Labels: reviewed

#54480 [fix](nereids) fix regression case bug: push_down_top_n_through_union
  regression-test/data/nereids_rules_p0/push_down_top_n/push_down_top_n_through_union.out
  regression-test/data/nereids_rules_p0/push_down_topn/push_down_topn_through_union.out
  regression-test/suites/nereids_rules_p0/push_down_top_n/push_down_top_n_through_union.groovy
Labels: approved, reviewed

#54625 [test](inverted index) fix case segment count assert
  regression-test/suites/inverted_index_p1/show_data/test_show_index_data.groovy
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x

#54585 [Chore](nereids) remove CreateJobStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateJobStmt.java
  fe/fe-core/src/main/java/org/apache/doris/qe/DdlExecutor.java
Labels: approved, reviewed

#54609 [Chore](thread) use std::atomic<std::shared_ptr> to replace atomic_load_explicit
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
  be/src/pipeline/pipeline_tracing.cpp
  be/src/pipeline/pipeline_tracing.h
  be/src/util/debug_points.cpp
  be/src/util/debug_points.h
Labels: approved, reviewed

#54629 [regression-test](fix) fix tpcds q24 query and result (#51497)
  regression-test/data/inverted_index_p1/tpcds_sf1_index/sql/q24_1.out
  regression-test/data/inverted_index_p1/tpcds_sf1_index/sql/q24_2.out
  regression-test/data/tpcds_sf100_dup_without_key_p2/sql/q24_1.out
  regression-test/data/tpcds_sf100_dup_without_key_p2/sql/q24_2.out
  regression-test/data/tpcds_sf100_p2/sql/q24_1.out
  regression-test/data/tpcds_sf100_p2/sql/q24_2.out
  regression-test/data/tpcds_sf1_p1/sql/q24_1.out
  regression-test/data/tpcds_sf1_p1/sql/q24_2.out
  regression-test/data/tpcds_sf1_unique_p1/sql/q24_1.out
  regression-test/data/tpcds_sf1_unique_p1/sql/q24_2.out
  regression-test/suites/inverted_index_p1/tpcds_sf1_index/sql/q24_1.sql
  regression-test/suites/inverted_index_p1/tpcds_sf1_index/sql/q24_2.sql
  regression-test/suites/tpcds_sf100_dup_without_key_p2/sql/q24_1.sql
  regression-test/suites/tpcds_sf100_dup_without_key_p2/sql/q24_2.sql
  regression-test/suites/tpcds_sf100_p2/sql/q24_1.sql
  regression-test/suites/tpcds_sf100_p2/sql/q24_2.sql
  regression-test/suites/tpcds_sf1_p1/sql/q24_1.sql
  regression-test/suites/tpcds_sf1_p1/sql/q24_2.sql
  regression-test/suites/tpcds_sf1_unique_p1/sql/q24_1.sql
  regression-test/suites/tpcds_sf1_unique_p1/sql/q24_2.sql
Labels: p0_test

#54583 [Chore](nereids) Remove ShowEnginesStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowEnginesStmt.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/qe/ShowExecutorTest.java
Labels: approved, reviewed

#53801 [opt](filecache) Let base compaction output rowsets write filecache when cache size is enough
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/io/cache/block_file_cache.h
  be/src/io/fs/broker_file_writer.h
  be/src/io/fs/file_writer.h
  be/src/io/fs/hdfs_file_writer.cpp
  be/src/io/fs/hdfs_file_writer.h
  be/src/io/fs/local_file_writer.h
  be/src/io/fs/s3_file_writer.cpp
  be/src/io/fs/s3_file_writer.h
  be/src/io/fs/stream_sink_file_writer.h
  be/src/olap/compaction.cpp
  be/src/olap/rowset/rowset_writer_context.h
  be/test/olap/tablet_cooldown_test.cpp
  regression-test/suites/compaction/test_filecache_with_base_compaction.groovy
Labels: usercase, dev/3.0.x, dev/3.1.x

#54639 [fix](paimon) disable some query type of paimon
  fe/fe-core/src/main/java/org/apache/doris/datasource/paimon/source/PaimonScanNode.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/paimon/source/PaimonScanNodeTest.java
  regression-test/data/external_table_p0/paimon/paimon_incr_read.out
  regression-test/suites/external_table_p0/paimon/paimon_incr_read.groovy
Labels: approved, reviewed, dev/3.1.x

#54568 [fix](prepare statement)Use client prepare statement when placeholders are more than 65536.
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/PrepareCommand.java
  regression-test/suites/prepared_stmt_p0/prepared_stmt.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x, dev/3.1.x

#54569 [Chore](agg) prune agg functions symbols
  be/src/service/internal_service.cpp
  be/src/vec/aggregate_functions/aggregate_function_approx_top_sum.cpp
  be/src/vec/aggregate_functions/aggregate_function_avg.cpp
  be/src/vec/aggregate_functions/aggregate_function_distinct.cpp
  be/src/vec/aggregate_functions/aggregate_function_group_array_intersect.cpp
  be/src/vec/aggregate_functions/aggregate_function_orthogonal_bitmap.cpp
  be/src/vec/aggregate_functions/aggregate_function_percentile.cpp
  be/src/vec/aggregate_functions/aggregate_function_reader.cpp
  be/src/vec/aggregate_functions/aggregate_function_regr_union.cpp
  be/src/vec/aggregate_functions/aggregate_function_sequence_match.cpp
  be/src/vec/aggregate_functions/aggregate_function_simple_factory.cpp
  be/src/vec/aggregate_functions/aggregate_function_simple_factory.h
  be/src/vec/aggregate_functions/aggregate_function_stddev.cpp
  be/src/vec/aggregate_functions/aggregate_function_sum.cpp
  be/src/vec/aggregate_functions/aggregate_function_topn.cpp
  be/src/vec/aggregate_functions/aggregate_function_uniq.cpp
  be/src/vec/aggregate_functions/aggregate_function_uniq_distribute_key.cpp
  be/src/vec/aggregate_functions/aggregate_function_window_funnel.cpp
  be/src/vec/aggregate_functions/aggregate_function_window_funnel.h
  be/src/vec/aggregate_functions/helpers.h
  be/src/vec/functions/array/function_array_aggregation.cpp
  be/src/vec/functions/array/function_array_mapped.h
  be/test/vec/aggregate_functions/vec_sequence_match_test.cpp
  be/test/vec/aggregate_functions/vec_window_funnel_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/RegrIntercept.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/RegrSlope.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/SequenceCount.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/SequenceMatch.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/Stddev.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/StddevSamp.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/Sum.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/Sum0.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/TopN.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/Variance.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/VarianceSamp.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/WindowFunnel.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/ArrayAvg.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/ArrayProduct.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/ArraySum.java
  regression-test/data/function_p0/test_array_agg.out
  regression-test/data/variant_p0/test_array_function.out
  regression-test/suites/nereids_syntax_p0/analyze_agg.groovy
Labels: approved, reviewed

#54516 [refactor](cloud restore) Add more states to cloud restore job
  be/src/agent/task_worker_pool.cpp
  be/src/cloud/cloud_meta_mgr.cpp
  be/src/cloud/cloud_meta_mgr.h
  be/src/cloud/cloud_snapshot_mgr.cpp
  be/src/cloud/cloud_snapshot_mgr.h
  cloud/src/meta-service/meta_service.cpp
  cloud/src/recycler/recycler.cpp
  cloud/test/meta_service_test.cpp
  cloud/test/recycler_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupJob.java
  fe/fe-core/src/main/java/org/apache/doris/backup/RestoreJob.java
  fe/fe-core/src/main/java/org/apache/doris/task/ReleaseSnapshotTask.java
  gensrc/proto/cloud.proto
  gensrc/thrift/AgentService.thrift
Labels: approved, reviewed, dev/3.1.x

#54094 [feat](cloud) Write and recycle compaction log
  cloud/src/meta-service/meta_service_job.cpp
  cloud/src/recycler/recycler.cpp
  cloud/src/recycler/recycler_operation_log.cpp
  cloud/test/meta_service_operation_log_test.cpp
  cloud/test/recycler_operation_log_test.cpp
Labels: approved, reviewed, cloud, snapshot

#52960 [fix](mtmv) Fix aggregate function roll up fail when function is always nullable
  regression-test/data/mv_p0/agg_use_key_direct/agg_use_key_direct.out
  regression-test/suites/nereids_rules_p0/mv/agg_variety/agg_variety.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x, dev/3.1.x

#54663 [refactor](variant) remove some useless code
  be/src/cloud/cloud_meta_mgr.cpp
  be/src/cloud/cloud_meta_mgr.h
  be/src/cloud/cloud_rowset_writer.cpp
  be/src/cloud/cloud_storage_engine.cpp
  be/src/cloud/cloud_storage_engine.h
  be/src/cloud/cloud_tablet.cpp
  be/src/cloud/cloud_tablet.h
  be/src/cloud/schema_cloud_dictionary_cache.cpp
  be/src/cloud/schema_cloud_dictionary_cache.h
  be/src/olap/base_tablet.cpp
  be/src/olap/base_tablet.h
  be/src/olap/rowset/beta_rowset_writer.cpp
  be/src/olap/rowset/beta_rowset_writer.h
  be/src/olap/rowset/beta_rowset_writer_v2.cpp
  be/src/olap/rowset/beta_rowset_writer_v2.h
  be/src/olap/rowset/rowset_writer.h
  be/src/olap/rowset/rowset_writer_context.h
  be/src/olap/rowset/segment_creator.cpp
  be/src/olap/rowset/segment_creator.h
  be/src/olap/rowset/segment_v2/segment_writer.h
  be/src/olap/rowset/segment_v2/vertical_segment_writer.h
  be/src/olap/rowset_builder.cpp
  be/src/runtime/load_stream.cpp
  be/src/runtime/load_stream_writer.cpp
  be/src/runtime/load_stream_writer.h
  be/src/runtime/memory/cache_policy.h
  be/src/service/internal_service.cpp
  be/src/vec/sink/load_stream_stub.cpp
  be/src/vec/sink/load_stream_stub.h
  be/test/cloud/test_schema_cloud_dictionary_cache.cpp
  cloud/src/meta-service/meta_service_schema.cpp
Labels: approved, reviewed

#54617 [fix](cast) Fix overflow issue when converting from double to int
  be/src/vec/functions/cast/cast_to_basic_number_common.h
  be/test/vec/function/cast/cast_to_integer.cpp
  regression-test/data/query_p0/cast/test_cast.out
  regression-test/suites/query_p0/cast/test_cast.groovy
Labels: approved, reviewed

#54632 [Fix](case) fix auto&dynamic partition case
  regression-test/suites/partition_p0/auto_partition/test_auto_dynamic.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x, dev/3.1.x

#54701 [fix](test)fix some docker regression test
  regression-test/suites/cloud_p0/multi_cluster/test_tvf.groovy
  regression-test/suites/external_table_p0/info_schema_db/test_backend_configuration.groovy
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x, p0_test

#54693 branch-3.0: [opt](filecache) Let base compaction output rowsets write filecache when cache size is enough (#53801)
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/io/cache/block_file_cache.h
  be/src/io/fs/broker_file_writer.h
  be/src/io/fs/file_writer.h
  be/src/io/fs/hdfs_file_writer.cpp
  be/src/io/fs/hdfs_file_writer.h
  be/src/io/fs/local_file_writer.h
  be/src/io/fs/s3_file_writer.cpp
  be/src/io/fs/s3_file_writer.h
  be/src/io/fs/stream_sink_file_writer.h
  be/src/olap/compaction.cpp
  be/src/olap/rowset/rowset_writer_context.h
  be/test/olap/tablet_cooldown_test.cpp
  regression-test/suites/compaction/test_filecache_with_base_compaction.groovy
Labels: approved, reviewed
