Repository apache/doris, pull requests merged in 2025-10, with the labels that each got.

#56415 [opt](catalog) support nested namespaces of iceberg
  docker/thirdparties/docker-compose/iceberg/scripts/create_preinstalled_scripts/iceberg/run20.sql
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/common/FeNameFormat.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/IcebergMetadataOps.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/metastore/IcebergRestProperties.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/MysqlProto.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/DropCatalogCommand.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContextUtil.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/GlobalVariable.java
  fe/fe-core/src/main/java/org/apache/doris/qe/MysqlConnectProcessor.java
  fe/fe-core/src/test/java/org/apache/doris/common/FeNameFormatTest.java
  fe/fe-core/src/test/java/org/apache/doris/mysql/MysqlProtoTest.java
  fe/fe-core/src/test/java/org/apache/doris/qe/ConnectContextTest.java
  regression-test/data/external_table_p0/iceberg/iceberg_and_internal_nested_namespace.out
  regression-test/suites/external_table_p0/iceberg/iceberg_and_internal_nested_namespace.groovy
Labels: approved, reviewed, dev/3.1.x, dev/4.0.x

#56632 [Chore](runtime-filter) add more rf merger info to debug string and add release_undone_filters logic
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/query_context.cpp
  be/src/runtime_filter/runtime_filter.h
  be/src/runtime_filter/runtime_filter_mgr.cpp
  be/src/runtime_filter/runtime_filter_mgr.h
Labels: approved, reviewed

#56699 [fix](inverted index) Fix NULL bitmap handling in MATCH OR queries
  be/src/olap/rowset/segment_v2/inverted_index_reader.h
  be/test/olap/rowset/segment_v2/inverted_index_reader_test.cpp
  regression-test/suites/inverted_index_p0/test_match_or_null_semantics.groovy
Labels: approved, reviewed, dev/4.0.x

#56706 [fix](search) add restriction for search function
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/CheckSearchUsage.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/analysis/CheckSearchUsageTest.java
  regression-test/data/search/test_search_usage_restrictions.out
  regression-test/suites/search/test_search_usage_restrictions.groovy
Labels: approved, reviewed

#56704 [test](search) add more regression case
  regression-test/suites/inverted_index_p0/test_complex_or_null_semantics.groovy
  regression-test/suites/inverted_index_p0/test_cross_field_or_with_null.groovy
  regression-test/suites/inverted_index_p0/test_search_or_null_semantics.groovy
Labels: approved, reviewed, dev/4.0.x

#56678 [fix](mulit-az) fix missing virtual CG to physical CG routing bug
  fe/fe-core/src/main/java/org/apache/doris/cloud/catalog/CloudReplica.java
  regression-test/suites/cloud_p0/multi_cluster/virtual_compute_group/default_vcg_auto_failover.groovy
  regression-test/suites/cloud_p0/multi_cluster/virtual_compute_group/load_trigger_failover.groovy
  regression-test/suites/cloud_p0/multi_cluster/virtual_compute_group/standby_disable_compaction.groovy
  regression-test/suites/cloud_p0/multi_cluster/virtual_compute_group/use_default_vcg_read_write.groovy
  regression-test/suites/cloud_p0/multi_cluster/virtual_compute_group/use_vcg_read_write.groovy
  regression-test/suites/cloud_p0/multi_cluster/virtual_compute_group/use_vcg_read_write_routine_load.groovy
  regression-test/suites/cloud_p0/multi_cluster/virtual_compute_group/use_vcg_read_write_s3_load.groovy
  regression-test/suites/cloud_p0/multi_cluster/virtual_compute_group/use_vcg_read_write_unhealthy_node_50.groovy
  regression-test/suites/cloud_p0/multi_cluster/virtual_compute_group/vcg_auto_failover.groovy
  regression-test/suites/cloud_p0/multi_cluster/virtual_compute_group/vcg_auto_failover_manual_failback.groovy
Labels: approved, reviewed, dev/3.1.x, dev/4.0.x

#56698 [fix](nereids) fix copy into fail when enable debug log
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/CopyIntoInfo.java
Labels: approved, reviewed, dev/4.0.x

#56577 [fix](groupcommit) remove NDEBUG for groupcommit's memory tracker
  be/src/pipeline/pipeline_fragment_context.cpp
Labels: approved, reviewed
