Repository apache/doris, pull requests merged in 2025-01, with the labels that each got.

#44942 [fix](cloud) serialize cache init to avoid unstable cache pick (#44429)
  be/src/runtime/exec_env_init.cpp
Labels: approved, reviewed

#46152 [fix](cross join) fix memory usage counter
  be/src/pipeline/exec/nested_loop_join_build_operator.cpp
  be/src/pipeline/exec/nested_loop_join_build_operator.h
  be/src/pipeline/exec/nested_loop_join_probe_operator.cpp
Labels: approved, reviewed, dev/3.0.x

#43144 [feat](metrics) Unify metrics of thread pool
  be/src/olap/memtable_flush_executor.cpp
  be/src/olap/memtable_flush_executor.h
  be/src/runtime/exec_env.h
  be/src/runtime/exec_env_init.cpp
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/workload_group/workload_group.cpp
  be/src/util/doris_metrics.cpp
  be/src/util/doris_metrics.h
  be/src/util/interval_histogram.cpp
  be/src/util/interval_histogram.h
  be/src/util/metrics.cpp
  be/src/util/threadpool.cpp
  be/src/util/threadpool.h
  be/src/vec/exec/scan/scanner_scheduler.cpp
  be/src/vec/exec/scan/scanner_scheduler.h
  be/test/io/fs/buffered_reader_test.cpp
  be/test/io/fs/remote_file_system_test.cpp
  be/test/io/fs/s3_file_writer_test.cpp
  be/test/olap/rowset/beta_rowset_test.cpp
  be/test/olap/rowset/unique_rowset_id_generator_test.cpp
  be/test/testutil/run_all_tests.cpp
  be/test/util/countdown_latch_test.cpp
  be/test/util/interval_histogram_test.cpp
  be/test/vec/aggregate_functions/agg_linear_histogram_test.cpp
  regression-test/suites/workload_manager_p0/test_curd_wlg.groovy
Labels: approved, reviewed

#39468 [Enhancement](Short Circuit) short circuit query supports `IN`
  be/src/olap/base_tablet.cpp
  be/src/service/internal_service.cpp
  be/src/service/internal_service.h
  be/src/service/point_query_executor.cpp
  fe/fe-core/src/main/java/org/apache/doris/catalog/PartitionKey.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/LogicalResultSinkToShortCircuitPointQuery.java
  fe/fe-core/src/main/java/org/apache/doris/planner/HashDistributionPruner.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PartitionPruneV2ForShortCircuitPlan.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PartitionPrunerV2Base.java
  fe/fe-core/src/main/java/org/apache/doris/planner/RangePartitionPrunerV2.java
  fe/fe-core/src/main/java/org/apache/doris/qe/PointQueryExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/rpc/BackendServiceClient.java
  fe/fe-core/src/main/java/org/apache/doris/rpc/BackendServiceProxy.java
  gensrc/proto/internal_service.proto
  regression-test/data/point_query_p0/test_point_IN_query.out
  regression-test/data/point_query_p0/test_point_query.out
  regression-test/data/point_query_p0/test_point_query_partition.out
  regression-test/data/point_query_p0/test_rowstore.out
  regression-test/data/point_query_p0/test_rowstore_query.out
  regression-test/data/prepared_stmt_p0/prepared_stmt_in_list.out
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
  regression-test/suites/cloud_p0/row_store_page_size/test_row_store_page_size.groovy
  regression-test/suites/point_query_p0/test_dynamic_partition_point_query.groovy
  regression-test/suites/point_query_p0/test_point_IN_query.groovy
  regression-test/suites/point_query_p0/test_point_query.groovy
  regression-test/suites/point_query_p0/test_point_query_ck.groovy
  regression-test/suites/point_query_p0/test_point_query_partition.groovy
  regression-test/suites/point_query_p0/test_rowstore.groovy
  regression-test/suites/point_query_p0/test_rowstore_query.groovy
  regression-test/suites/prepared_stmt_p0/prepared_stmt_in_list.groovy
Labels: reviewed

#46180 ·[Refactor](vec) remove the unless api in column nullable
  be/src/olap/base_tablet.cpp
  be/src/olap/partial_update_info.cpp
  be/src/olap/rowset/segment_v2/column_reader.cpp
  be/src/olap/rowset/segment_v2/column_reader.h
  be/src/vec/columns/column_nullable.h
  be/src/vec/data_types/data_type_struct.cpp
  be/src/vec/exec/format/orc/vorc_reader.cpp
  be/src/vec/exec/format/parquet/vparquet_column_reader.cpp
  be/src/vec/olap/vgeneric_iterators.cpp
  be/test/vec/columns/column_nullable_test.cpp
  be/test/vec/core/block_test.cpp
  be/test/vec/data_types/serde/data_type_serde_pb_test.cpp
  be/test/vec/data_types/serde/data_type_serde_test.cpp
  be/test/vec/jsonb/serialize_test.cpp
Labels: approved, reviewed

#46190 [fix](report) report queue size based on the number of Bes and config
  fe/fe-core/src/main/java/org/apache/doris/master/ReportHandler.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#45163 [Enhancement] (nereids)implement alterCatalogRenameCommand in nereids
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/datasource/CatalogMgr.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PlanType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/AlterCatalogRenameCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/CommandVisitor.java
  regression-test/data/nereids_p0/test_alter_catalog_rename_command.out
  regression-test/suites/nereids_p0/test_alter_catalog_rename_command.groovy
Labels: approved, reviewed

#45145 [Enhancement] (nereids)implement showUserPropertiesCommand and showAllPropertiesCommand in nereids
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PlanType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ShowUserPropertyCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/CommandVisitor.java
  regression-test/suites/nereids_p0/show/test_show_user_properties_command.groovy
Labels: approved, reviewed

#45373 [Enhancement] (nereids)implement showStagesCommand in nereids
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PlanType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ShowStagesCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/CommandVisitor.java
  regression-test/suites/nereids_p0/test_show_stages_command.groovy
Labels: approved, reviewed

#46201 [fix](azure) Add FE azure object storage UT and fix log
  fe/fe-core/src/main/java/org/apache/doris/fs/obj/AzureObjStorage.java
  fe/fe-core/src/test/java/org/apache/doris/fs/obj/AzureObjStorageTest.java
Labels: approved, reviewed, dev/3.0.x

#46166 [fix](schema-change) Fix job replay failure when partitions added to table after job finish
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeJobV2.java
Labels: approved, reviewed, p0_c, dev/2.1.x, dev/3.0.x

#46249 [Chore](regression-test) adjust variant tpch/q09_trans.sql batch_size…
  regression-test/suites/variant_p0/tpch/sql/q09_trans.sql
Labels: reviewed

#45905 [fix](new_json_reader)fix core for new_json_reader
  be/src/vec/exec/format/json/new_json_reader.cpp
  regression-test/data/load_p0/stream_load/load_json_parse_failed/test_error_json.json
  regression-test/suites/load_p0/stream_load/load_json_parse_failed/load_error_json.groovy
Labels: approved, reviewed, dev/3.0.x

#45955 [Bug](auto-partition) fix auto partition could set storage_medium properties
  fe/fe-core/src/main/java/org/apache/doris/analysis/PartitionExprUtil.java
  fe/fe-core/src/test/java/org/apache/doris/service/FrontendServiceImplTest.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#46020 [fix](mtmv)The refresh method for MTMV is commit. If the status is PAUSED, no more tasks should be generated
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVJobManager.java
  regression-test/data/mtmv_p0/test_commit_mtmv.out
  regression-test/suites/mtmv_p0/test_commit_mtmv.groovy
Labels: approved, reviewed, usercase, p0_b, dev/2.1.x, dev/3.0.x

#46217 [opt](arrow-flight-sql) Support `arrow-flight-sql` protocol `getStreamCatalogs`, `getStreamSchemas`, `getStreamTables`
  fe/fe-core/src/main/java/org/apache/doris/service/arrowflight/DorisFlightSqlProducer.java
  fe/fe-core/src/main/java/org/apache/doris/service/arrowflight/FlightSqlSchemaHelper.java
  fe/fe-core/src/main/java/org/apache/doris/service/arrowflight/auth2/FlightAuthUtils.java
Labels: approved, reviewed

#46136 [fix](memory) Fix Jemalloc dirty page usage strategy and some memory management bugs
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/common/daemon.cpp
  be/src/common/daemon.h
  be/src/runtime/memory/global_memory_arbitrator.cpp
  be/src/runtime/memory/global_memory_arbitrator.h
  be/src/runtime/memory/heap_profiler.cpp
  be/src/runtime/memory/mem_tracker_limiter.cpp
  be/src/runtime/memory/mem_tracker_limiter.h
  be/src/runtime/memory/memory_reclamation.cpp
  be/src/runtime/memory/memory_reclamation.h
  be/src/util/mem_info.cpp
  be/src/util/mem_info.h
  be/src/util/system_metrics.cpp
  be/src/vec/common/allocator.cpp
  be/src/vec/common/allocator.h
Labels: approved, reviewed, not-merge/2.1, dev/3.0.x

#46214 [fix](regression-test) fix `test_outfile_csv_with_names_and_types` case
  regression-test/data/nereids_p0/outfile/test_outfile_csv_with_names_and_types.out
  regression-test/suites/export_p0/test_outfile_csv_with_names_and_types.groovy
  regression-test/suites/nereids_p0/outfile/test_outfile_csv_with_names_and_types.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#45921 [enchement](api)Change the behavior of follower http api redirect to master to follower request master.
  fe/fe-core/src/main/java/org/apache/doris/httpv2/meta/ColocateMetaService.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/CancelLoadAction.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/GetLoadInfoAction.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/GetStreamLoadState.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/LoadAction.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/MultiAction.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/RestBaseController.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/ShowAction.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/manager/NodeAction.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/restv2/AddStoragePolicyAction.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/restv2/ESCatalogAction.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/restv2/StatisticAction.java
  fe/fe-core/src/test/java/org/apache/doris/http/ForwardToMasterTest.java
Labels: approved, reviewed, dev/3.0.x, dev/2.1.x-experimental

#46246 [fix](nereids)allow use REPLACE as agg type when add value column for unique table
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/AddColumnOp.java
  regression-test/suites/schema_change_p0/test_schema_change_unique.groovy
Labels: approved, reviewed

#46200 [Fix]Fix local data dir metric missing
  be/src/io/fs/local_file_reader.cpp
  be/src/olap/olap_common.h
  be/src/runtime/workload_group/workload_group.cpp
  be/src/runtime/workload_group/workload_group_metrics.cpp
  be/src/runtime/workload_group/workload_group_metrics.h
Labels: approved, reviewed

#46235 [Improvement](fragment) Use partitioned hash map to manage contexts
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/fragment_mgr.h
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#46261 [opt](nereids) improve prune partition with lots of `in (xxx)`
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/OneRangePartitionEvaluator.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#45948 [opt](mtmv) Add log when compute olap scan cost to locate problem easier
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/StatsCalculator.java
Labels: approved, reviewed

#46251 [Improvement](local shuffle) Reduce locking scope in local exchanger
  be/src/pipeline/local_exchange/local_exchanger.cpp
  be/src/pipeline/local_exchange/local_exchanger.h
Labels: dev/2.1.x, dev/3.0.x

#46206 [fix](group commit) fix group commit use prepared statement and connect to observer
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/InsertIntoTableCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/OlapGroupCommitInsertExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
  regression-test/suites/insert_p0/insert_group_commit_with_exception.groovy
  regression-test/suites/insert_p0/insert_group_commit_with_prepare_stmt.groovy
Labels: approved, reviewed, dev/3.0.x

#46123 [feat](nereids)implement alterDatabaseRenameCommand in nereids
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PlanType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/alter/AlterDatabaseRenameCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/CommandVisitor.java
  regression-test/data/nereids_p0/ddl/alter/test_nereids_alter_database_rename.out
  regression-test/suites/nereids_p0/ddl/alter/test_nereids_alter_database_rename.groovy
Labels: approved, reviewed

#44948 [opt](mtmv) support rewrite when mv has date_trunc but query doesn't have
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewAggregateRule.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewJoinRule.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewRule.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewScanRule.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/Predicates.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/PredicatesSplitter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/StructInfo.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/ExpressionUtils.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/expression/PredicatesSplitterTest.java
  regression-test/data/nereids_rules_p0/mv/date_trunc/mv_with_date_trunc.out
  regression-test/suites/nereids_rules_p0/mv/date_trunc/mv_with_date_trunc.groovy
Labels: approved, reviewed, dev/3.0.x

#46274 [test](case) skip unstable case in cloud mode
  regression-test/suites/nereids_p0/cache/parse_sql_from_sql_cache.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#44346 [Refactor](join) some refactor of join process
  be/src/pipeline/dependency.h
  be/src/pipeline/exec/hashjoin_build_sink.cpp
  be/src/pipeline/exec/hashjoin_build_sink.h
  be/src/pipeline/exec/hashjoin_probe_operator.cpp
  be/src/pipeline/exec/hashjoin_probe_operator.h
  be/src/pipeline/exec/join/process_hash_table_probe.h
  be/src/pipeline/exec/join/process_hash_table_probe_impl.h
  be/src/vec/common/hash_table/join_hash_table.h
Labels: approved, reviewed

#46045 [Opt](load) only MoW table need table commit lock when commit transaction for cloud mode (#45220)
  fe/fe-core/src/main/java/org/apache/doris/cloud/transaction/CloudGlobalTransactionMgr.java
Labels: approved, reviewed, dev/3.0.x

#45417 [regression](minio) test minio as doris storage vault
  docker/thirdparties/docker-compose/minio/minio-RELEASE.2024-11-07.env
  docker/thirdparties/docker-compose/minio/minio-RELEASE.2024-11-07.yaml.tpl
  docker/thirdparties/docker-compose/minio/script/minio_init.sh
  docker/thirdparties/run-thirdparties-docker.sh
  regression-test/conf/regression-conf.groovy
  regression-test/data/vault_p0/create/test_minio_storage_vault.out
  regression-test/suites/vault_p0/create/test_minio_storage_vault.groovy
Labels: approved, reviewed, dev/3.0.x

#46156 [fix](external)using saved member variables
  fe/fe-core/src/main/java/org/apache/doris/datasource/FileQueryScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/source/HiveScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hudi/source/HudiScanNode.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#46258 [fix](regression-test) flush out file to fix hudi p2
  regression-test/data/external_table_p2/hudi/test_hudi_snapshot.out
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#45673 [fix](cloud-mow) FE should release delete bitmap lock when calculating delete bitmap failed
  fe/fe-core/src/main/java/org/apache/doris/cloud/transaction/CloudGlobalTransactionMgr.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/transaction/DeleteBitmapUpdateLockContext.java
  regression-test/data/fault_injection_p0/cloud/test_cloud_mow_stream_load_with_commit_fail.out
  regression-test/suites/fault_injection_p0/cloud/test_cloud_mow_stream_load_with_commit_fail.groovy
Labels: approved, reviewed, dev/3.0.x

#45668 [enhancement](cloud) reconnect after the RPC request to the meta service fails
  be/src/cloud/cloud_meta_mgr.cpp
  be/src/cloud/config.cpp
  be/src/cloud/config.h
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/rpc/MetaServiceProxy.java
Labels: approved, reviewed, p0_c, dev/3.0.x

#46306 [fix](statistics)Fix sample all tablets scale factor incorrect bug.
  fe/fe-core/src/main/java/org/apache/doris/statistics/BaseAnalysisTask.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/OlapAnalysisTask.java
  fe/fe-core/src/test/java/org/apache/doris/statistics/OlapAnalysisTaskTest.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#46318 [improve](move-memtable) disable stack trace in load stream reply
  be/src/vec/sink/load_stream_stub.cpp
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#46204 [Test](check) Add check for create view
  regression-test/suites/check_before_quit/check_before_quit.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#44001 [feature](hive)Support read hive4 transaction tables.
  be/src/vec/exec/format/table/transactional_hive_reader.cpp
  docker/thirdparties/docker-compose/hive/scripts/create_preinstalled_scripts/run25.hql
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/AcidUtil.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HMSCachedClient.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HMSExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HiveMetaStoreCache.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HiveMetadataOps.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HiveTransaction.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/PostgreSQLJdbcHMSCachedClient.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/ThriftHMSCachedClient.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/source/HiveScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/InsertIntoTableCommand.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/TestHMSCachedClient.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/hive/HiveAcidTest.java
  regression-test/data/external_table_p0/hive/test_transactional_hive.out
  regression-test/data/external_table_p2/hive/test_hive_translation_insert_only.out
  regression-test/suites/external_table_p0/hive/test_transactional_hive.groovy
  regression-test/suites/external_table_p2/hive/test_hive_translation_insert_only.groovy
Labels: approved, reviewed, dev/2.1.x-experimental, dev/3.0.x-experimental

#46307 [Fix](index build) should not append index to meta while column id is -1
  be/src/olap/tablet_schema.h
  be/src/olap/task/index_builder.cpp
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#46320 [fix](test) fix test_autoinc_broker_load.groovy
  regression-test/suites/external_table_p0/hive/test_autoinc_broker_load.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#46315 [fix](test) use different catalog name for test_hive_parquet_skip_page
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/RelationUtil.java
  regression-test/suites/external_table_p0/hive/test_hive_parquet_skip_page.groovy
Labels: approved, reviewed, dev/3.0.x, dev/2.1.8-merged

#46313 [fix](regression-test) fix `test_trino_kafka_base` case
  regression-test/suites/external_table_p0/trino_connector/kafka/test_trino_kafka_base.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#46250 [fix](ip) fix ip nullable param without check (#44700)
  be/src/vec/functions/function_ip.h
  regression-test/data/nereids_function_p0/scalar_function/IP.out
  regression-test/suites/nereids_function_p0/scalar_function/IP.groovy
  regression-test/suites/query_p0/sql_functions/ip_functions/test_ipv6_cidr_to_range_function.groovy
Labels: approved, reviewed

#46324 [fix](regression)Nereids support external table MODIFY_TABLE_PROPERTY_SYNC operation.
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/AlterTableCommand.java
Labels: approved, reviewed

#46263 [fix](test) Fix mysql catalog check db test
  regression-test/data/external_table_p0/jdbc/test_mysql_jdbc_catalog.out
  regression-test/suites/external_table_p0/jdbc/test_mysql_jdbc_catalog.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#46279 [fix](variant) fix schema change for variant from not null to null
  be/src/olap/rowset/segment_v2/hierarchical_data_reader.h
  be/src/vec/common/schema_util.cpp
  regression-test/data/variant_p0/schema_change/schema_change.out
  regression-test/suites/variant_p0/schema_change/schema_change.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#46322 [opt](test) add more debug info in test_jdbc_catalog_ddl.groovy
  regression-test/suites/external_table_p0/jdbc/test_jdbc_catalog_ddl.groovy
Labels: approved, reviewed, dev/3.0.x, dev/2.1.8-merged

#46296 [Bug](scan) do not release tablet_reader on NewOlapScanner::close
  be/src/vec/exec/scan/new_olap_scanner.cpp
Labels: approved, reviewed, p0_c, dev/2.1.x, dev/3.0.x

#45928 [enhance](nerieds) month, day, hour, minute, second, day_of_year, day_of_month, week_of_year implement monotonic
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/OneRangePartitionEvaluator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/Cast.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/FromSecondMonotonic.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/DateFormat.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/DayOfMonth.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/DayOfYear.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/FromMicrosecond.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/FromMillisecond.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/FromSecond.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/FromUnixtime.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Hour.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/MakeDate.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Microsecond.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Minute.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Month.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Quarter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Second.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/WeeksAdd.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/WeeksDiff.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/WeeksSub.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/YearWeek.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/DateUtils.java
  regression-test/suites/nereids_rules_p0/partition_prune/int_as_date_partition_col.groovy
  regression-test/suites/nereids_rules_p0/partition_prune/month_quarter_cast_in_prune.groovy
  regression-test/suites/nereids_rules_p0/partition_prune/test_add_sub_diff_ceil_floor.groovy
Labels: approved, reviewed

#45543 [opt](nereids) simplify arithmethic handle with mix add/sub/multiply/divide
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/SimplifyArithmeticRule.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/expression/SimplifyArithmeticRuleTest.java
Labels: approved, reviewed

#45412 [opt](inverted index) Time Series Compaction Level 2 Logical Optimization
  be/src/cloud/cloud_cumulative_compaction_policy.cpp
  be/src/cloud/cloud_cumulative_compaction_policy.h
  be/src/cloud/pb_convert.cpp
  be/src/olap/compaction.cpp
  be/src/olap/compaction.h
  be/src/olap/cumulative_compaction.cpp
  be/src/olap/cumulative_compaction_policy.h
  be/src/olap/cumulative_compaction_time_series_policy.cpp
  be/src/olap/cumulative_compaction_time_series_policy.h
  be/src/olap/full_compaction.cpp
  gensrc/proto/olap_file.proto
  regression-test/suites/compaction/test_time_series_compaction_level2.groovy
Labels: approved, reviewed

#46357 [fix](regression-test) fix injection would not be removed when exception
  regression-test/README.md
  regression-test/suites/load_p0/routine_load/test_multi_table_load_error.groovy
Labels: approved, reviewed

#45501 [enhancement](test) Add show data test
  regression-test/plugins/aliyun_oss_sdk.groovy
  regression-test/plugins/cloud_show_data_plugin.groovy
  regression-test/suites/show_data/ddl/lineitem_delete.sql
  regression-test/suites/show_data/ddl/lineitem_dup.sql
  regression-test/suites/show_data/ddl/lineitem_mow.sql
  regression-test/suites/show_data_p2/test_cloud_follower_show_data.groovy
  regression-test/suites/show_data_p2/test_table_modification/test_cloud_mtmv_show_data.groovy
  regression-test/suites/show_data_p2/test_table_modification/test_cloud_schema_change_add_and_drop_column_show_data.groovy
  regression-test/suites/show_data_p2/test_table_modification/test_cloud_schema_change_add_and_drop_index_show_data.groovy
  regression-test/suites/show_data_p2/test_table_modification/test_cloud_schema_change_reorder_column_show_data.groovy
  regression-test/suites/show_data_p2/test_table_operation/test_cloud_delete_table_rows_show_data.groovy
  regression-test/suites/show_data_p2/test_table_operation/test_cloud_drop_and_recover_partition_show_data.groovy
  regression-test/suites/show_data_p2/test_table_operation/test_cloud_drop_table_show_data.groovy
  regression-test/suites/show_data_p2/test_table_operation/test_cloud_truncate_and_recover_table_show_data.groovy
  regression-test/suites/show_data_p2/test_table_property/test_cloud_disable_compaction_show_data.groovy
  regression-test/suites/show_data_p2/test_table_property/test_cloud_inverted_index_v1_show_data.groovy
  regression-test/suites/show_data_p2/test_table_property/test_cloud_inverted_index_v2_show_data.groovy
  regression-test/suites/show_data_p2/test_table_property/test_cloud_lz4_show_data.groovy
  regression-test/suites/show_data_p2/test_table_property/test_cloud_zstd_show_data.groovy
  regression-test/suites/show_data_p2/test_table_type/test_cloud_agg_show_data.groovy
  regression-test/suites/show_data_p2/test_table_type/test_cloud_dup_show_data.groovy
  regression-test/suites/show_data_p2/test_table_type/test_cloud_mor_show_data.groovy
  regression-test/suites/show_data_p2/test_table_type/test_cloud_mow_partial_update_show_data.groovy
  regression-test/suites/show_data_p2/test_table_type/test_cloud_mow_show_data.groovy
Labels: approved, reviewed, dev/3.0.x

#46262 [Refactor](exec) refactor the partion sort code
  be/src/pipeline/common/partition_sort_utils.cpp
  be/src/pipeline/exec/partition_sort_sink_operator.cpp
  be/src/pipeline/exec/partition_sort_source_operator.cpp
  be/src/vec/common/sort/partition_sorter.cpp
  be/src/vec/common/sort/partition_sorter.h
Labels: approved, reviewed

#46287 [fix](metaCache)fix bug that names cache can not invalidate.
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalDatabase.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HMSExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/metacache/MetaCache.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/MetaCacheTest.java
Labels: approved, reviewed, dev/3.0.x, dev/2.1.8-merged

#46353 [Bug](join) fix out of range about probe_index
  be/src/pipeline/exec/join/process_hash_table_probe_impl.h
  regression-test/data/query_p0/join/rqg/rqg500079780/rqg500079780.out
  regression-test/suites/query_p0/join/rqg/rqg500079780/rqg500079780.groovy
Labels: approved, reviewed

#45255 [Fix](cloud) Cloud enable fe deploy mode from master-observers to multi-followers
  cloud/src/common/config.h
  cloud/src/common/network_util.cpp
  cloud/src/meta-service/injection_point_http.cpp
  cloud/src/meta-service/meta_service_resource.cpp
  cloud/src/resource-manager/resource_manager.cpp
  cloud/test/fdb_injection_test.cpp
  cloud/test/meta_service_http_test.cpp
  cloud/test/resource_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/cloud/catalog/CloudEnv.java
  gensrc/proto/cloud.proto
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/SuiteCluster.groovy
  regression-test/suites/cloud_p0/node_mgr/test_ms_api.groovy
  regression-test/suites/cloud_p0/node_mgr/test_sql_mode_node_mgr.groovy
Labels: approved, reviewed, dev/3.0.x

#46137 [multi-catalog](hudi) impl hudi_metadata table value function
  be/src/vec/exec/scan/vmeta_scanner.cpp
  be/src/vec/exec/scan/vmeta_scanner.h
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinTableValuedFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hudi/source/HudiCachedMetaClientProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hudi/source/HudiMetadataCacheMgr.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/table/HudiMeta.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/TableValuedFunctionVisitor.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/HudiTableValuedFunction.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/MetadataGenerator.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/MetadataTableValuedFunction.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/TableValuedFunctionIf.java
  gensrc/thrift/FrontendService.thrift
  gensrc/thrift/PlanNodes.thrift
  gensrc/thrift/Types.thrift
  regression-test/data/external_table_p2/hudi/test_hudi_meta.out
  regression-test/suites/external_table_p2/hudi/test_hudi_meta.groovy
Labels: approved, reviewed, dev/2.1.x-experimental, dev/3.0.x-experimental

#46236 [opt](schema_change) Fix null message when trying to alter forbidden table properties
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/alter/CloudSchemaChangeHandler.java
  regression-test/suites/schema_change/test_alter_table_property.groovy
Labels: approved, reviewed, dev/3.0.x

#46164 [Enhancement](compaction) enable the compaction producer to generate multiple compaction tasks in a single run (#45411)
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/olap/tablet_manager.cpp
  be/test/olap/tablet_mgr_test.cpp
Labels: reviewed

#46087 [fix](nereids)fix rangeSet intersect in PartitionPredicateToRange
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/PartitionPredicateToRange.java
  regression-test/suites/nereids_rules_p0/partition_prune/test_binary_search_prune.groovy
Labels: approved, reviewed

#44790 [chore](conf) Set enable_advance_next_id=true by default
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ExportToOutfileLogicalPlanTest.java
  fe/fe-core/src/test/java/org/apache/doris/common/proc/IndexesProcNodeTest.java
  fe/fe-core/src/test/java/org/apache/doris/service/FrontendServiceImplTest.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/TestWithFeService.java
Labels: approved, reviewed, kind/behavior-changed, dev/3.0.x

#45958 [feat](nerieds)Push encode slot
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVPlanUtil.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/Rewriter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/LogicalProperties.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/CompressedMaterialize.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/DecoupleEncodeDecode.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PullUpJoinFromUnionAll.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PullUpProjectBetweenTopNAndAgg.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PushDownEncodeSlot.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PushDownFilterThroughProject.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/SimplifyEncodeDecode.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/WindowExpression.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/EncodeAsBigInt.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/EncodeAsInt.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/EncodeAsLargeInt.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/EncodeAsSmallInt.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/EncodeString.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalHashAggregate.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/ExpressionUtils.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/PlanUtils.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  regression-test/data/nereids_p0/compress_materialize/compress_materialize.out
  regression-test/data/nereids_p0/compress_materialize/pushdown_encode.out
  regression-test/data/nereids_rules_p0/pull_up_join_from_union/pull_up_join_from_union.out
  regression-test/suites/nereids_p0/compress_materialize/compress_materialize.groovy
  regression-test/suites/nereids_p0/compress_materialize/pushdown_encode.groovy
Labels: approved, reviewed

#46364 [fix](index meta) make has_inverted_index function more robust
  be/src/olap/tablet_schema.h
Labels: approved, reviewed

#46266 [fix](cancel) Fix `BufferControlBlock` cancel msg
  be/src/runtime/buffer_control_block.cpp
  be/src/runtime/result_buffer_mgr.cpp
Labels: approved, reviewed, usercase, dev/2.1.x, dev/3.0.x

#46369 [fix](external catalog) Fixed non-master FE log replay during refresh
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalDatabase.java
  regression-test/suites/external_table_p0/lower_case/test_conflict_name.groovy
  regression-test/suites/external_table_p0/lower_case/test_lower_case_meta_include.groovy
  regression-test/suites/external_table_p0/lower_case/test_lower_case_meta_show_and_select.groovy
  regression-test/suites/external_table_p0/lower_case/test_lower_case_meta_with_lower_table_conf_show_and_select.groovy
  regression-test/suites/external_table_p0/lower_case/test_lower_case_mtmv.groovy
  regression-test/suites/external_table_p0/lower_case/test_meta_cache_select_without_refresh.groovy
  regression-test/suites/external_table_p0/lower_case/test_meta_names_mapping.groovy
  regression-test/suites/external_table_p0/lower_case/test_timing_refresh_catalog.groovy
  regression-test/suites/external_table_p0/lower_case/upgrade/load.groovy
Labels: approved, reviewed

#46280 [Improve](mtmv) skip the generation of invalid task for refresh mtmv
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVService.java
  regression-test/data/mtmv_p0/test_commit_mtmv.out
  regression-test/suites/mtmv_p0/test_commit_mtmv.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#45209 [enhance](nereids) add rule MultiDistinctSplit
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/Rewriter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/CheckAnalysis.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/implementation/AggregateStrategies.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/CheckMultiDistinct.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/SplitMultiDistinct.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/Count.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/GroupConcat.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/Sum.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/Sum0.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/SupportMultiDistinct.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/SplitMultiDistinctTest.java
  regression-test/data/nereids_rules_p0/distinct_split/disitinct_split.out
  regression-test/suites/nereids_rules_p0/distinct_split/disitinct_split.groovy
  regression-test/suites/nereids_rules_p0/mv/agg_without_roll_up/aggregate_without_roll_up.groovy
  regression-test/suites/nereids_rules_p0/mv/dimension/dimension_1.groovy
  regression-test/suites/nereids_rules_p0/mv/dimension/dimension_2_3.groovy
  regression-test/suites/nereids_rules_p0/mv/dimension/dimension_2_4.groovy
  regression-test/suites/nereids_syntax_p0/aggregate_strategies.groovy
Labels: approved, reviewed

#46385 [fix](regression)fix hive translation unstable case.
  docker/thirdparties/docker-compose/hive/scripts/create_preinstalled_scripts/run25.hql
  regression-test/suites/external_table_p2/hive/test_hive_translation_insert_only.groovy
Labels: approved, reviewed

#46408 [fix](compile) fix fe compile failed by code too large
  fe/fe-core/src/main/java/org/apache/doris/nereids/pattern/generator/ExpressionTypeMappingGenerator.java
Labels: approved, reviewed

#46224 [fix](nereids) Create Runtime filter even if equal.right is not in aliasTransferMap-branch3.0
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/RuntimeFilterGenerator.java
Labels: usercase, p0_b

#46334 [opt](iceberg) opt the error msg when create db which already exists
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/IcebergMetadataOps.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#46381 [test](test) fix unstable paimon test cases
  regression-test/suites/external_table_p0/paimon/paimon_base_filesystem.groovy
Labels: approved, reviewed, dev/3.0.x, dev/2.1.8-merged

#46410 [fix](test) fix unstable lower case test
  regression-test/suites/external_table_p0/lower_case/test_lower_case_meta_show_and_select.groovy
  regression-test/suites/external_table_p0/lower_case/test_lower_case_meta_with_lower_table_conf_show_and_select.groovy
  regression-test/suites/external_table_p0/lower_case/test_timing_refresh_catalog.groovy
  regression-test/suites/external_table_p0/lower_case/upgrade/load.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#44696 [fix](cloud) initial startup failure due to unconfigured metadata node
  be/src/cloud/cloud_meta_mgr.cpp
Labels: approved, reviewed, dev/3.0.x

#46423 Fix install and deploy URL
  README.md
Labels: approved, reviewed

#46412 [chore](logformat) add space
  be/src/runtime/load_stream_writer.cpp
Labels: approved, reviewed

#45924 [fix](Nereids) fix bug for TimestampArithmetic.equals() branch-3.0
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/TimestampArithmetic.java
  regression-test/data/nereids_hint_tpcds_p0/shape/query21.out
  regression-test/data/nereids_hint_tpcds_p0/shape/query40.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/shape/query21.out
  regression-test/data/nereids_tpcds_shape_sf1000_p0/shape/query40.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/noStatsRfPrune/query21.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/noStatsRfPrune/query40.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/no_stats_shape/query21.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/no_stats_shape/query40.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/rf_prune/query21.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/rf_prune/query40.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query21.out
  regression-test/data/nereids_tpcds_shape_sf100_p0/shape/query40.out
  regression-test/data/nereids_tpcds_shape_sf10t_orc/shape/query21.out
  regression-test/data/nereids_tpcds_shape_sf10t_orc/shape/query40.out
  regression-test/data/new_shapes_p0/tpcds_sf100/noStatsRfPrune/query21.out
  regression-test/data/new_shapes_p0/tpcds_sf100/noStatsRfPrune/query40.out
  regression-test/data/new_shapes_p0/tpcds_sf100/no_stats_shape/query21.out
  regression-test/data/new_shapes_p0/tpcds_sf100/no_stats_shape/query40.out
  regression-test/data/new_shapes_p0/tpcds_sf100/rf_prune/query21.out
  regression-test/data/new_shapes_p0/tpcds_sf100/rf_prune/query40.out
  regression-test/data/new_shapes_p0/tpcds_sf100/shape/query21.out
  regression-test/data/new_shapes_p0/tpcds_sf100/shape/query40.out
  regression-test/data/new_shapes_p0/tpcds_sf1000/shape/query21.out
  regression-test/data/new_shapes_p0/tpcds_sf1000/shape/query40.out
Labels: approved, reviewed

#46394 [opt](regression) Fix unstable regression test test_alter_table_property and test_compaction_score_action
  regression-test/plugins/plugin_curl_requester.groovy
  regression-test/suites/compaction/test_compaction_score_action.groovy
  regression-test/suites/schema_change/test_alter_table_property.groovy
Labels: approved, reviewed, dev/3.0.x

#46361 [Fix](case) Ensure Kerberos starts after other components
  docker/thirdparties/docker-compose/kerberos/kerberos.yaml.tpl
  docker/thirdparties/run-thirdparties-docker.sh
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#46101 [fix](test)fix unstable case correctness_p0/test_mv_case/test_mv_case
  regression-test/suites/correctness_p0/test_mv_case/test_mv_case.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#46406 [fix](nereids) Create Runtime filter even if equal.right is not in aliasTransferMap
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/RuntimeFilterGenerator.java
  regression-test/data/nereids_p0/runtime_filter/check_rf.out
  regression-test/suites/nereids_p0/runtime_filter/check_rf.groovy
Labels: approved, reviewed, usercase, dev/2.1.8-merged, dev/3.0.4-merged

#46348 [fix](case) fix cluster key case in cloud mode
  be/src/cloud/cloud_schema_change_job.cpp
  regression-test/suites/unique_with_mow_c_p0/test_compact_with_seq.groovy
  regression-test/suites/unique_with_mow_c_p0/test_compact_with_seq2.groovy
  regression-test/suites/unique_with_mow_c_p0/test_schema_change_add_key_column.groovy
Labels: approved, reviewed

#46292 [improve](routine load) introduce routine load task min timeout
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/KafkaRoutineLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadJob.java
  regression-test/suites/load_p0/routine_load/data/test_routine_load_timeout_value.csv
  regression-test/suites/load_p0/routine_load/test_routine_load_timeout_value.groovy
Labels: approved, reviewed, dev/3.0.x

#46387 [fix](doris compose) fix wait master fe ip 10s for ls command
  docker/runtime/doris-compose/cluster.py
  docker/runtime/doris-compose/command.py
  docker/runtime/doris-compose/database.py
Labels: approved, reviewed

#46411 [fix] let backup work on azure
  be/src/io/fs/azure_obj_storage_client.cpp
  be/src/util/s3_util.cpp
  fe/fe-core/src/main/java/org/apache/doris/analysis/StorageBackend.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/S3ClientBEProperties.java
  fe/fe-core/src/main/java/org/apache/doris/fs/obj/AzureObjStorage.java
  fe/fe-core/src/main/java/org/apache/doris/fs/obj/S3ObjStorage.java
  fe/fe-core/src/main/java/org/apache/doris/fs/remote/AzureFileSystem.java
  fe/fe-core/src/main/java/org/apache/doris/persist/gson/GsonUtils.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/property/PropertyConverterTest.java
  fe/fe-core/src/test/java/org/apache/doris/fs/obj/AzureObjStorageTest.java
Labels: approved, reviewed, dev/3.0.x

#46440 [fix](regression)Fix unstable invalid_stats case.
  regression-test/suites/nereids_p0/stats/invalid_stats/invalid_stats.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#46433 [fix](regression)Fix schema change statistics case. Neredis not allow change MV schema.
  regression-test/suites/statistics/test_schema_change_statistics.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#46299 [test](mtmv) Fix regression test unstable and add relevant test log
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/InitMaterializationContextHook.java
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
  regression-test/suites/export_p0/test_export_table_with_materialized_view.groovy
  regression-test/suites/nereids_rules_p0/mv/external_table/mv_contain_external_table.groovy
  regression-test/suites/nereids_rules_p0/mv/external_table/part_partition_invalid.groovy
  regression-test/suites/nereids_rules_p0/mv/external_table/single_external_table.groovy
  regression-test/suites/nereids_syntax_p0/mv/ut/distinctQuery.groovy
  regression-test/suites/rollup_p0/test_materialized_view.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#46325 [case](mtmv)external pipeline set enable_job_schedule_second_for_test = true
  regression-test/pipeline/cloud_p1/conf/fe_custom.conf
  regression-test/pipeline/external/conf/fe.conf
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#46100 [regression-test](fix) fix test_audit_log_behavior.groovy bug
  regression-test/suites/audit/test_audit_log_behavior.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#46115 [enhance](auth)Reduce the scope of permission locks
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/Auth.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#46288 [enhance](query)Schema ScanNode supports explain
  fe/fe-core/src/main/java/org/apache/doris/planner/SchemaScanNode.java
  regression-test/suites/nereids_p0/system/test_explain_information_schema.groovy
Labels: approved, reviewed

#46370 [fix](nereids)fix bug of PushDownFilterThroughSetOperation
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PushDownFilterThroughSetOperation.java
  regression-test/data/nereids_rules_p0/infer_predicate/pull_up_predicate_set_op.out
  regression-test/suites/nereids_rules_p0/infer_predicate/pull_up_predicate_set_op.groovy
Labels: approved, reviewed, p0_w, dev/2.1.x, dev/3.0.x

#46257 [regression](mtmv)Support show iceberg external table partition. Add more test case for iceberg mtmv.
  docker/thirdparties/docker-compose/iceberg/scripts/create_preinstalled_scripts/iceberg/run08.sql
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowPartitionsStmt.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/IcebergExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  regression-test/data/mtmv_p0/test_iceberg_mtmv.out
  regression-test/suites/mtmv_p0/test_iceberg_mtmv.groovy
Labels: approved, reviewed

#46310 [fix](inverted index) Fix for Inaccurate match_phrase_prefix Cache in Query Processing
  be/src/olap/rowset/segment_v2/inverted_index_reader.cpp
  regression-test/data/inverted_index_p0/test_index_match_phrase_prefix_1.out
  regression-test/data/inverted_index_p0/test_index_match_regexp.out
  regression-test/suites/inverted_index_p0/test_index_match_phrase_prefix_1.groovy
  regression-test/suites/inverted_index_p0/test_index_match_regexp.groovy
Labels: approved, reviewed, dev/3.0.x

#46402 [fix](storage vault) Fix some bug and add more regression test
  fe/fe-core/src/main/java/org/apache/doris/catalog/StorageVaultMgr.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/catalog/CloudInstanceStatusChecker.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/AlterStorageVaultCommand.java
  fe/fe-core/src/test/java/org/apache/doris/cloud/catalog/HdfsStorageVaultTest.java
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
  regression-test/suites/vault_p0/alter/test_alter_hdfs_vault.groovy
  regression-test/suites/vault_p0/alter/test_alter_s3_vault.groovy
  regression-test/suites/vault_p0/alter/test_alter_use_path_style.groovy
  regression-test/suites/vault_p0/alter/test_alter_vault_name.groovy
  regression-test/suites/vault_p0/alter/test_alter_vault_type.groovy
  regression-test/suites/vault_p0/create/load.groovy
  regression-test/suites/vault_p0/create/test_create_vault.groovy
  regression-test/suites/vault_p0/default/test_default_vault.groovy
  regression-test/suites/vault_p0/default/test_s3_vault_path_start_with_slash.groovy
  regression-test/suites/vault_p0/forbid/test_forbid_vault.groovy
  regression-test/suites/vault_p0/privilege/test_vault_privilege.groovy
  regression-test/suites/vault_p0/privilege/test_vault_privilege_restart.groovy
  regression-test/suites/vault_p0/privilege/test_vault_privilege_with_role.groovy
  regression-test/suites/vault_p0/privilege/test_vault_privilege_with_user.groovy
Labels: approved, reviewed, p0_c, dev/3.0.x

#46455 [test](regression)Add log for waitingMTMVTaskFinished
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
Labels: approved, reviewed

#45394 [feature](meta-service) Support dynamic configuration for meta service
  cloud/src/common/config.h
  cloud/src/common/configbase.cpp
  cloud/src/common/configbase.h
  cloud/src/main.cpp
  cloud/src/meta-service/meta_service_http.cpp
  cloud/test/meta_service_http_test.cpp
Labels: approved, reviewed, p0_c, dev/3.0.x

#46395 [fix](fe.conf) use g1 by default for jdk17
  conf/fe.conf
Labels: approved, reviewed

#46099 [opt](cache) enhance cache key computation by removing comments and trimming SQL input
  fe/fe-core/src/main/java/org/apache/doris/nereids/SqlCacheContext.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#46467 [chore](ci) support run minio case
  regression-test/pipeline/vault_p0/conf/regression-conf-custom.groovy
  regression-test/pipeline/vault_p0/run.sh
Labels: approved, reviewed, dev/3.0.x

#46405 [fix](mem) heap-buffer-overflow for function convert_to
  be/src/vec/functions/function_string.h
  regression-test/data/nereids_function_p0/scalar_function/C.out
  regression-test/data/query_p0/sql_functions/string_functions/test_string_function.out
  regression-test/suites/nereids_function_p0/scalar_function/C.groovy
  regression-test/suites/query_p0/sql_functions/string_functions/test_string_function.groovy
Labels: approved, reviewed, p0_c, dev/2.0.x, dev/2.1.x, dev/3.0.x

#46478 [log](regression)add log for datetrunc case.
  regression-test/suites/nereids_rules_p0/mv/date_trunc/mv_with_date_trunc.groovy
Labels: reviewed

#46473 [fix](regression-test) adjust hudi cases
  regression-test/data/external_table_p2/hudi/test_hudi_snapshot.out
  regression-test/suites/external_table_p2/hudi/test_hudi_catalog.groovy
  regression-test/suites/external_table_p2/hudi/test_hudi_incremental.groovy
  regression-test/suites/external_table_p2/hudi/test_hudi_meta.groovy
  regression-test/suites/external_table_p2/hudi/test_hudi_orc_tables.groovy
  regression-test/suites/external_table_p2/hudi/test_hudi_partition_prune.groovy
  regression-test/suites/external_table_p2/hudi/test_hudi_schema_evolution.groovy
  regression-test/suites/external_table_p2/hudi/test_hudi_snapshot.groovy
  regression-test/suites/external_table_p2/hudi/test_hudi_timestamp.groovy
  regression-test/suites/external_table_p2/hudi/test_hudi_timetravel.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#46485 [fix](hms)fix hive catalog follower not get event.
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HMSExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/event/MetastoreEventsProcessor.java
Labels: approved, reviewed

#46384 [fix](Nereids) insert into with cte cannot be explained
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/InsertIntoTableCommand.java
  regression-test/suites/nereids_p0/explain/explain_dml.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#46470 [bugfix](be) the config could not be modified on line
  be/src/common/config.cpp
Labels: approved, reviewed, dev/3.0.x

#46463 [fix](variable) variable version not persist in image
  fe/fe-core/src/main/java/org/apache/doris/qe/GlobalVariable.java
Labels: approved, reviewed, p0_b, dev/2.1.x, dev/3.0.x

#46443 [fix](nereids) fix sql cache bug and some tests
  fe/fe-core/src/main/java/org/apache/doris/common/cache/NereidsSqlCacheManager.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/SqlCacheContext.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/StatementContext.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/AbstractPlan.java
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
  regression-test/suites/nereids_p0/cache/parse_sql_from_sql_cache.groovy
  regression-test/suites/nereids_syntax_p0/distribute/colocate_union_numbers.groovy
  regression-test/suites/nereids_syntax_p0/distribute/prune_bucket_with_bucket_shuffle_join.groovy
  regression-test/suites/nereids_syntax_p0/explain.groovy
Labels: approved, reviewed

#41986 [opt](vec) opt the date/datetime is invalid func performance
  be/src/util/time_lut.cpp
  be/src/util/time_lut.h
  be/src/vec/functions/date_time_transforms.h
  be/src/vec/runtime/vdatetime_value.cpp
  be/src/vec/runtime/vdatetime_value.h
Labels: approved, reviewed

#45233 [fix](Nereids) fix fe folding constant of string functions and add more cases
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/executable/StringArithmetic.java
  regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy
Labels: approved, reviewed, p0_w, dev/2.1.x, dev/3.0.x

#46366 Fix threadpool blocked when create thread failed in init()
  be/src/util/threadpool.cpp
  be/src/util/threadpool.h
Labels: approved, reviewed, p0_b, dev/2.1.x, dev/3.0.x

#46436 [regression-test](fix) ignore e-2000 in compaction
  regression-test/plugins/plugin_compaction.groovy
Labels: approved, reviewed

#46514 [regression-test](fix) fix global var bug in compaction/test_cumu_compaction_with_delete.groovy
  regression-test/suites/compaction/test_cumu_compaction_with_delete.groovy
Labels: approved, reviewed

#46438 [regression-test](fix) fix test_bloom_filter_hit.groovy case bug
  regression-test/suites/bloom_filter_p0/test_bloom_filter_hit.groovy
Labels: approved, reviewed

#46362 [fix](hive) Incorrect location conversion
  fe/fe-core/src/main/java/org/apache/doris/planner/HiveTableSink.java
  fe/fe-core/src/test/java/org/apache/doris/planner/HiveTableSinkTest.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#46441 [fix](cases) fix unstable leading cases
  regression-test/data/nereids_p0/hint/test_leading.out
  regression-test/suites/nereids_p0/hint/test_leading.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#46522 [regression-test](fix) ignore E-2000 in compaction cases
  regression-test/plugins/plugin_compaction.groovy
Labels: approved, reviewed

#45952 [Enchancement](sort) change priority_queue to ck SortingQueue
  be/src/vec/columns/column.h
  be/src/vec/common/pod_array.h
  be/src/vec/common/sort/partition_sorter.cpp
  be/src/vec/common/sort/partition_sorter.h
  be/src/vec/common/sort/sorter.cpp
  be/src/vec/common/sort/sorter.h
  be/src/vec/core/sort_cursor.h
  fe/fe-core/src/main/java/org/apache/doris/planner/PartitionSortNode.java
Labels: approved, reviewed

#46273 [opt](flexible partial update) Don't store table property `enable_unique_key_skip_bitmap_column`
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/AlterTableStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateTableStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ModifyTablePropertiesClause.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/InternalSchemaInitializer.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/TableProperty.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/CreateTableInfo.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/ModifyTablePropertiesOp.java
  regression-test/data/query_p0/system/test_table_properties.out
  regression-test/suites/unique_with_mow_p0/flexible/test_flexible_partial_update_property.groovy
Labels: approved, reviewed

#46496 [fix](shellcheck) fix hive-metastore and enable shellcheck in docker
  .github/workflows/code-checks.yml
  docker/thirdparties/docker-compose/hive/scripts/hive-metastore.sh
Labels: approved, reviewed

#46532 (fix)[test] avoid use gloabal define in cache load.groovy
  regression-test/suites/cloud_p0/cache/load.groovy
Labels: approved, reviewed

#46474 [chore](MTMV) catch all exception when get mtmvs to avoid plan failed
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVRelationManager.java
Labels: reviewed, p0_b, dev/2.1.x, dev/3.0.x

#46444 [Fix](Variant) variant should not implicit be short key column when create mv
  fe/fe-common/src/main/java/org/apache/doris/catalog/Type.java
  fe/fe-core/src/main/java/org/apache/doris/alter/MaterializedViewHandler.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateMaterializedViewStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateTableStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/CreateMTMVInfo.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/CreateTableInfo.java
  regression-test/data/variant_p0/mv/multi_slot.out
  regression-test/suites/mv_p0/test_create_mv_complex_type/test_create_mv_complex_type.groovy
  regression-test/suites/rollup_p0/test_materialized_view_array.groovy
  regression-test/suites/rollup_p0/test_materialized_view_struct.groovy
  regression-test/suites/variant_p0/mv/multi_slot.groovy
Labels: approved, reviewed, usercase, dev/2.1.x, dev/3.0.x

#46492 [chore](thrift) remove some useless thrift definitions
  be/src/common/config.h
  be/src/exec/schema_scanner/schema_helper.cpp
  be/src/exec/schema_scanner/schema_helper.h
  be/src/pipeline/exec/schema_scan_operator.cpp
  be/src/service/backend_service.cpp
  be/src/service/backend_service.h
  be/src/service/internal_service.cpp
  be/src/service/internal_service.h
  be/src/util/debug_util.h
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/org/apache/doris/common/GenericPoolTest.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/MockedBackendFactory.java
  gensrc/proto/internal_service.proto
  gensrc/thrift/BackendService.thrift
  gensrc/thrift/Data.thrift
  gensrc/thrift/Ddl.thrift
  gensrc/thrift/FrontendService.thrift
  gensrc/thrift/PaloInternalService.thrift
  gensrc/thrift/PaloService.thrift
  gensrc/thrift/PlanNodes.thrift
  gensrc/thrift/Types.thrift
Labels: approved, reviewed

#46537 [fix](cache) fix mtmv cache can not use test
  fe/fe-core/src/main/java/org/apache/doris/common/cache/NereidsSqlCacheManager.java
  regression-test/suites/mtmv_p0/test_mtmv_sql_cache_and_profile.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#46149 [fix](cloud) fix routine load loss data when fe master node restart
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/KafkaRoutineLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadScheduler.java
Labels: approved, reviewed, usercase, dev/3.0.x

#46238 [improve](routine load) improve routine load observability
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadJob.java
  regression-test/suites/load_p0/routine_load/data/test_error_info.csv
  regression-test/suites/load_p0/routine_load/test_routine_load_error_info.groovy
Labels: approved, reviewed, usercase, dev/2.1.x, dev/3.0.x

#46289 [opt](iceberg docker)Use PostgreSQL as the backend for the Iceberg REST server.
  docker/thirdparties/docker-compose/iceberg/entrypoint.sh.tpl
  docker/thirdparties/docker-compose/iceberg/iceberg.yaml.tpl
Labels: reviewed, dev/2.1.x, dev/3.0.x

#46484 [Fix](recycler) Fix protobuf out-of-bounds problem in recycler
  cloud/src/meta-service/meta_service_job.cpp
  cloud/src/recycler/recycler.cpp
Labels: approved, reviewed, p0_c, dev/3.0.x

#46565 [bugfix](asan core) should use weak ptr in rpc context to release rf context during query context deconstructed
  be/src/exprs/runtime_filter.cpp
Labels: approved, reviewed

#45585 [chore](session) remove some unused session variables
  be/src/runtime/runtime_state.h
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  gensrc/thrift/PaloInternalService.thrift
  regression-test/suites/datatype_p0/nested_types/query/test_nested_type_with_resize.groovy
  regression-test/suites/nereids_rules_p0/mv/variant/variant_mv.groovy
  regression-test/suites/query_p0/join/test_partitioned_hash_join.groovy
  regression-test/suites/variant_p0/load.groovy
  regression-test/suites/variant_p0/nested.groovy
  regression-test/suites/variant_p0/test_sub_path_pruning.groovy
Labels: approved, reviewed

#46521 [Fix](func) fix group_array_intersect result error in all arr contain null
  be/src/exprs/hybrid_set.h
  be/src/vec/aggregate_functions/aggregate_function_group_array_intersect.h
  regression-test/data/query_p0/aggregate/group_array_intersect.out
  regression-test/suites/query_p0/aggregate/group_array_intersect.groovy
Labels: kind/fix, approved, reviewed, dev/2.1.x, dev/3.0.x

#46352 [fix](nereids) fix bug of LogicalRepeat computing uniform datatrait
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalRepeat.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/properties/DataTraitTest.java
  regression-test/data/nereids_rules_p0/eliminate_gby_key/eliminate_group_by_key_by_uniform.out
  regression-test/suites/nereids_rules_p0/eliminate_gby_key/eliminate_group_by_key_by_uniform.groovy
Labels: approved, reviewed, p0_w, dev/3.0.x

#46554 [fix](ES catalog)Fix query long value exception with doc_value
  be/src/exec/es/es_scroll_parser.cpp
  docker/thirdparties/docker-compose/elasticsearch/scripts/data/data1_es6.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/data/data2_es6.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/data/data3_es6.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/data/data4_es6.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/index/es6_test1.json
  docker/thirdparties/docker-compose/elasticsearch/scripts/index/es6_test2.json
  regression-test/data/external_table_p0/es/test_es_query.out
  regression-test/data/external_table_p0/es/test_es_query_no_http_url.out
  regression-test/suites/external_table_p0/es/test_es_query.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#46527 [fix](test)Fix unstable index_change_with_cumu case
  regression-test/suites/inverted_index_p0/index_change/test_index_change_with_cumulative_compaction.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#46551 [fix](nereids) topN filter: use ObjectId as map key instead of Topn node
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/TopnFilterContext.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/algebra/TopN.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalDeferMaterializeTopN.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalTopN.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalDeferMaterializeTopN.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalTopN.java
Labels: approved, reviewed, p0_b, dev/3.0.x

#46493 [fix](pipelineX) fix DCHECK error when reuse _join_block in nested loop join
  be/src/pipeline/exec/nested_loop_join_probe_operator.cpp
Labels: approved, reviewed, dev/2.1.x

#46508 [fix](index compaction)Fix construct index compaction columns core when reader close error
  be/src/olap/compaction.cpp
  regression-test/data/fault_injection_p0/test_index_compaction_fault_injection.out
  regression-test/suites/fault_injection_p0/test_index_compaction_fault_injection.groovy
Labels: reviewed

#46573 [fix](shellcheck) fix hive-metastore and enable shellcheck in docker (#46496)
  .github/workflows/code-checks.yml
  docker/thirdparties/docker-compose/hive/scripts/hive-metastore.sh
Labels: reviewed

#46574 [fix](shellcheck) fix hive-metastore and enable shellcheck in docker (#46496)
  .github/workflows/code-checks.yml
  docker/thirdparties/docker-compose/hive/scripts/hive-metastore.sh
Labels: reviewed

#46461 [Bug](join) fix columnstr64's offset overflow on serialize_value_into_arena
  be/src/vec/columns/column_string.cpp
  be/src/vec/columns/column_string.h
  regression-test/data/query_p1/str64_serialize/str64_serialize.out
  regression-test/suites/query_p1/str64_serialize/str64_serialize.groovy
Labels: approved, reviewed, usercase, p0_w, dev/3.0.x, dev/2.1.8-merged

#46203 [Enchancement](join) do not build non-output column on join probe
  be/src/pipeline/exec/hashjoin_probe_operator.h
  be/src/pipeline/exec/join/process_hash_table_probe_impl.h
  be/src/pipeline/exec/join_probe_operator.cpp
  be/src/service/internal_service.cpp
  be/src/vec/core/block.cpp
  be/src/vec/exprs/vexpr_context.cpp
Labels: approved, reviewed

#46588 [regression-test](fix) test_audit_log_behavior.groovy case bug
  regression-test/suites/audit/test_audit_log_behavior.groovy
Labels: approved, reviewed, dev/3.0.x

#46434 [fix](test) Optimize the health check after oceanbase docker starts
  docker/thirdparties/docker-compose/oceanbase/oceanbase.yaml.tpl
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#46437 [opt](jni) Modify Exception Cause Formatting in JniUtil for Better Readability
  fe/be-java-extensions/java-common/src/main/java/org/apache/doris/common/jni/utils/JniUtil.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#46446 [fix](fe) Ignore `removeDroppedFrontends` when fe using metadata fail…
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
Labels: approved, reviewed, p0_c, dev/2.1.x, dev/3.0.x
