Repository apache/doris, pull requests merged in 2025-02, with the labels that each got.

#46990 [opt](paimon)Upgrade the Paimon version to 1.0.0 and Iceberg to 1.6.1
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/source/IcebergScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/paimon/PaimonExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/paimon/PaimonExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/paimon/PaimonMetadataCache.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/paimon/PaimonUtil.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/paimon/source/PaimonScanNode.java
  fe/pom.xml
Labels: approved, reviewed, dev/2.1.x-experimental, dev/3.0.x-experimental

#47457 [fix](case)rm hms event use_meta_chache is false case.
  regression-test/suites/external_table_p0/hive/test_hms_event_notification.groovy
  regression-test/suites/external_table_p0/hive/test_hms_event_notification_multi_catalog.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#46326 [fix](hive) sync DDL command to other FE
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/CatalogIf.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HiveMetadataOps.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/IcebergMetadataOps.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/operations/ExternalMetadataOps.java
  fe/fe-core/src/main/java/org/apache/doris/journal/JournalEntity.java
  fe/fe-core/src/main/java/org/apache/doris/persist/CreateDbInfo.java
  fe/fe-core/src/main/java/org/apache/doris/persist/CreateTableInfo.java
  fe/fe-core/src/main/java/org/apache/doris/persist/DropDbInfo.java
  fe/fe-core/src/main/java/org/apache/doris/persist/DropInfo.java
  fe/fe-core/src/main/java/org/apache/doris/persist/EditLog.java
  fe/fe-core/src/main/java/org/apache/doris/persist/OperationType.java
  fe/fe-core/src/main/java/org/apache/doris/persist/TruncateTableInfo.java
  fe/fe-core/src/test/java/org/apache/doris/persist/CreateDbInfoTest.java
Labels: approved, reviewed, meta-change, dev/2.1.x-experimental, dev/3.0.x-experimental, dev/3.1.x

#47127 [Chore](dependencies)upgrade dependencies
  fe/be-java-extensions/hadoop-hudi-scanner/pom.xml
  fe/pom.xml
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#47472 [fix](cloud) shorten cache lock held time and add metrics
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/io/cache/block_file_cache.cpp
  be/src/io/cache/block_file_cache.h
  be/src/io/cache/file_block.cpp
  be/src/io/cache/file_block.h
  be/src/io/cache/fs_file_cache_storage.cpp
  build.sh
Labels: approved, reviewed, p0_c, dev/3.0.x

#47486 [Fix](recycler) Further fix for #47475
  cloud/src/recycler/hdfs_accessor.cpp
  cloud/src/recycler/recycler.cpp
  cloud/src/recycler/recycler.h
  cloud/test/recycler_test.cpp
Labels: approved, reviewed, p0_b, dev/3.0.x

#47126 [improve](ipv6) Enhance ipv6 type to accept uint128 strings in network byte order
  be/src/vec/functions/function_ip.cpp
  be/src/vec/functions/function_ip.h
  be/src/vec/runtime/ipv6_value.h
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinScalarFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Ipv6FromUInt128StringOrNull.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/ScalarFunctionVisitor.java
  gensrc/script/doris_builtins_functions.py
  regression-test/data/datatype_p0/ip/test_data/ipv6_uint128.csv
  regression-test/data/datatype_p0/ip/test_ip_basic.out
  regression-test/suites/datatype_p0/ip/test_ip_basic.groovy
Labels: approved, reviewed

#47465 [fix](profile) Fix merge profile failed due to NonZeroCounter
  fe/fe-core/src/main/java/org/apache/doris/common/profile/RuntimeProfile.java
Labels: approved, reviewed

#47367 [fix](memory) Fix WorkloadGroup memory GC cancel msg
  be/src/runtime/workload_group/workload_group.cpp
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#47476 [Bug](fix) fix the broadcast cause result error
  be/src/pipeline/exec/exchange_sink_operator.cpp
  be/src/vec/sink/vdata_stream_sender.cpp
Labels: approved, reviewed, p0_w

#47377 [chore](compaction) Enable schema change new tablet to do compaction by default
  be/src/cloud/config.cpp
Labels: approved, reviewed, dev/3.0.x

#47487 [enhancement](brpc) remove client from brpc cache if the underlying channel has error
  be/src/util/brpc_client_cache.h
  be/test/util/brpc_client_cache_test.cpp
Labels: approved, reviewed

#47382 [fix](case) make inverted index up down case robust
  regression-test/suites/inverted_index_up_down_p0/inverted_index.groovy
Labels: approved, reviewed

#47499 [cherry-pick](branch-3.0) Pick "[Fix](recycler) Further fix for #47475 (#47486)"
  cloud/src/recycler/recycler.cpp
  cloud/src/recycler/recycler.h
  cloud/test/recycler_test.cpp
Labels: approved, reviewed

#43992 [feature](inverted index) add index searcher after writing inverted index
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/olap/rowset/segment_v2/inverted_index_file_reader.cpp
  be/src/olap/rowset/segment_v2/inverted_index_file_reader.h
  be/src/olap/rowset/segment_v2/inverted_index_file_writer.cpp
  be/src/olap/rowset/segment_v2/inverted_index_file_writer.h
  be/src/olap/rowset/segment_v2/inverted_index_reader.cpp
  be/src/olap/rowset/segment_v2/inverted_index_reader.h
  be/test/olap/rowset/segment_v2/inverted_index_file_writer_test.cpp
  regression-test/pipeline/cloud_p0/conf/be_custom.conf
  regression-test/pipeline/cloud_p1/conf/be_custom.conf
  regression-test/pipeline/p0/conf/be.conf
  regression-test/pipeline/p1/conf/be.conf
Labels: approved, reviewed, dev/3.0.x

#47512 [regression-test](case) fix two cases using same table
  regression-test/suites/schema_change_p0/test_agg_schema_key_change_modify.groovy
Labels: approved, reviewed

#47511 [Fix](testcase) Add enable_cloud_txn_lazy_commit for testcases relates to many partitions
  regression-test/suites/partition_p2/auto_partition/high_concur_load/stress_test_high_concurrency_load.groovy
  regression-test/suites/partition_p2/auto_partition/same_data/stress_test_same_date_range.groovy
  regression-test/suites/partition_p2/auto_partition/two_stream_load/stress_test_two_stream_load.groovy
Labels: approved, reviewed, dev/3.0.x

#47400 [Test](Export) add some debug logs for export
  fe/fe-core/src/main/java/org/apache/doris/load/ExportTaskExecutor.java
  regression-test/pipeline/p0/conf/fe.conf
Labels: approved, reviewed, dev/3.0.4-merged

#47498 [fix](local shuffle) Set serial execution for schema scan operator
  be/src/pipeline/exec/schema_scan_operator.cpp
  regression-test/suites/query_p0/system/test_query_sys.groovy
Labels: approved, reviewed, p0_w, dev/2.1.x, dev/3.0.x

#47495 [fix](compaction) fix the issue of schema loss caused by cloud disable auto compaction
  cloud/src/meta-service/meta_service.cpp
  cloud/test/schema_kv_test.cpp
  regression-test/suites/schema_change_p0/alter_disable_auto_compaction.groovy
Labels: approved, reviewed, p0_b, dev/3.0.x

#47523 [Fix]Fix double-free when memtable agg
  be/src/olap/memtable.cpp
Labels: approved, reviewed, p0_b, dev/2.1.x, dev/3.0.x

#47028 [improve](cloud-mow)Add delete bitmap metrics
  be/src/cloud/cloud_storage_engine.cpp
  be/src/cloud/cloud_storage_engine.h
  be/src/cloud/cloud_tablet_mgr.cpp
  be/src/cloud/cloud_tablet_mgr.h
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/olap/base_tablet.cpp
  be/src/olap/base_tablet.h
  be/src/olap/olap_server.cpp
  be/src/olap/storage_engine.cpp
  be/src/olap/storage_engine.h
  be/src/olap/tablet_manager.cpp
  be/src/olap/tablet_manager.h
  be/src/olap/tablet_meta.cpp
  be/src/olap/tablet_meta.h
  regression-test/data/metrics_p0/test_delete_bitmap_metrics.out
  regression-test/suites/metrics_p0/test_delete_bitmap_metrics.groovy
Labels: approved, reviewed, p0_b, dev/3.0.x

#47389 [fix](prepared statement) fix protocol with TIME datatype
  be/src/util/mysql_row_buffer.cpp
  be/test/util/mysql_row_buffer_test.cpp
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#44690 [feat](scan) Adaptive scan concurrency
  be/src/exprs/runtime_filter_slots.h
  be/src/pipeline/exec/scan_operator.cpp
  be/src/pipeline/exec/scan_operator.h
  be/src/runtime/runtime_state.h
  be/src/vec/exec/scan/scanner_context.cpp
  be/src/vec/exec/scan/scanner_context.h
  be/src/vec/exec/scan/scanner_scheduler.cpp
  be/src/vec/exec/scan/scanner_scheduler.h
  be/src/vec/exec/scan/simplified_scan_scheduler.cpp
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  gensrc/thrift/PaloInternalService.thrift
  regression-test/suites/query_profile/adaptive_pipeline_task_serial_read_on_limit.groovy
  regression-test/suites/query_profile/scanner_profile.groovy
Labels: approved, reviewed

#47404 [Feature](function) support function array_flatten
  be/src/vec/functions/array/function_array_flatten.cpp
  be/src/vec/functions/array/function_array_register.cpp
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinScalarFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/ArrayFlatten.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/ScalarFunctionVisitor.java
  regression-test/data/nereids_function_p0/scalar_function/Array.out
  regression-test/data/query_p0/sql_functions/array_functions/array_flatten.out
  regression-test/suites/nereids_function_p0/scalar_function/Array.groovy
  regression-test/suites/query_p0/sql_functions/array_functions/array_flatten.groovy
Labels: approved, reviewed

#47505 [Refactor](UDF) Refactor the java udf code to reduce the unless code
  fe/be-java-extensions/java-common/src/main/java/org/apache/doris/common/jni/utils/JavaUdfDataType.java
  fe/be-java-extensions/java-common/src/main/java/org/apache/doris/common/jni/utils/UdfClassCache.java
  fe/be-java-extensions/java-udf/src/main/java/org/apache/doris/udf/BaseExecutor.java
  fe/be-java-extensions/java-udf/src/main/java/org/apache/doris/udf/UdafExecutor.java
  fe/be-java-extensions/java-udf/src/main/java/org/apache/doris/udf/UdfExecutor.java
Labels: approved, reviewed

#46864 [fix](nereids)Add catalog/db/table filter info in SchemaScanNode
  be/src/exec/schema_scanner/schema_tables_scanner.cpp
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/PhysicalPlanTranslator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/Rewriter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/implementation/LogicalSchemaScanToPhysicalSchemaScan.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PushDownFilterIntoSchemaScan.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalSchemaScan.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalSchemaScan.java
  fe/fe-core/src/main/java/org/apache/doris/planner/BackendPartitionedSchemaScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SchemaScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  gensrc/thrift/FrontendService.thrift
  regression-test/data/information_schema_p0/test_information_schema.out
  regression-test/suites/information_schema_p0/test_information_schema.groovy
Labels: approved, reviewed, usercase, dev/3.0.x

#47539 [fix](hive docker)Table `partition_location_1` miss data
  docker/thirdparties/docker-compose/hive/scripts/data/multi_catalog/partition_location_1/create_table.hql
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#47540 [improve](test) Fix unstable cases
  regression-test/suites/delete_p0/test_delete_unicode.groovy
  regression-test/suites/show_p0/test_show_create_table_with_storage_policy.groovy
  regression-test/suites/show_p0/test_show_data_skew.groovy
Labels: approved, reviewed

#47535 [fix](exchanger) Fix DCHECK failure when ref count is not set correctly
  be/src/pipeline/local_exchange/local_exchanger.cpp
Labels: approved, reviewed, dev/3.0.x

#47115 [feature](iceberg) support s3 tables
  be/src/util/s3_util.cpp
  be/src/util/s3_util.h
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/IcebergExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/IcebergExternalCatalogFactory.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/IcebergS3TablesExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/s3tables/CustomAwsCredentialsProvider.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/source/IcebergScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/S3ClientBEProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/constants/S3Properties.java
  fe/fe-core/src/main/java/org/apache/doris/persist/gson/GsonUtils.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/property/PropertyConverterTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/s3tables/S3TablesTest.java
  fe/pom.xml
  regression-test/conf/regression-conf.groovy
  regression-test/data/external_table_p2/iceberg/test_s3tables_insert_overwrite.out
  regression-test/data/external_table_p2/iceberg/test_s3tables_write_insert.out
  regression-test/data/external_table_p2/iceberg/test_s3tables_write_partitions.out
  regression-test/suites/external_table_p2/iceberg/test_s3tables_insert_overwrite.groovy
  regression-test/suites/external_table_p2/iceberg/test_s3tables_write_insert.groovy
  regression-test/suites/external_table_p2/iceberg/test_s3tables_write_partitions.groovy
Labels: approved, reviewed, dev/2.1.x-experimental, dev/3.0.x-experimental

#47522 [regression-test](fix) fix final check
  regression-test/suites/check_before_quit/check_before_quit.groovy
Labels: approved, reviewed, dev/3.0.x

#47307 [Enhancement] Support some compress functions
  be/src/vec/functions/function_compress.cpp
  be/src/vec/functions/simple_function_factory.h
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinScalarFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Compress.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Uncompress.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/ScalarFunctionVisitor.java
  regression-test/data/query_p0/sql_functions/string_functions/test_compress_uncompress.out
  regression-test/suites/query_p0/sql_functions/string_functions/test_compress_uncompress.groovy
Labels: approved, reviewed, dev/3.0.x

#47568 [regression-test](config) modify regression config
  regression-test/pipeline/cloud_p0/conf/fe_custom.conf
  regression-test/pipeline/p0/conf/fe.conf
Labels: approved, reviewed

#47562 [fix](index compaction)Add column unique id check before use
  be/src/olap/compaction.cpp
  be/src/olap/tablet_schema.cpp
  be/src/olap/tablet_schema.h
Labels: approved, reviewed, dev/3.0.x

#47572 [Fix](macOS) Fix unnecessary installation of thirdparty libs in Darwin
  build.sh
Labels: approved, reviewed

#47578 [fix](docker) Starting thirdpaty script with only the reserve-ports parameter does not work
  docker/thirdparties/run-thirdparties-docker.sh
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#46993 [Fix][regression-test] Fix unstable adaptive_pipeline_task_serial_read_on_limit
  regression-test/suites/query_profile/adaptive_pipeline_task_serial_read_on_limit.groovy
Labels: approved, reviewed

#47501 [Improvement](tablet) Prefetch tablets before opening
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/olap/parallel_scanner_builder.cpp
  be/src/olap/parallel_scanner_builder.h
  be/src/pipeline/exec/olap_scan_operator.cpp
  be/src/pipeline/exec/olap_scan_operator.h
  be/src/pipeline/exec/operator.h
  be/src/pipeline/pipeline_task.cpp
Labels: approved, reviewed

#47586 [Bug](function) fix wrong result when percentile's second argument is 1
  be/src/util/counts.h
  regression-test/data/nereids_p0/sql_functions/aggregate_functions/test_aggregate_percentile_no_cast.out
  regression-test/suites/nereids_p0/sql_functions/aggregate_functions/test_aggregate_percentile_no_cast.groovy
Labels: approved, reviewed, dev/3.0.x

#47565 [fix](test) Use single tablet table to verify compaction score action
  regression-test/suites/compaction/test_compaction_score_action.groovy
Labels: approved, reviewed, dev/3.0.x

#47525 [test](jdbc catalog) add more jdbc catalog extreme test
  docker/thirdparties/docker-compose/clickhouse/init/03-create-table.sql
  docker/thirdparties/docker-compose/clickhouse/init/04-insert.sql
  docker/thirdparties/docker-compose/oracle/init/03-create-table.sql
  docker/thirdparties/docker-compose/oracle/init/04-insert.sql
  docker/thirdparties/docker-compose/postgresql/init/02-create-table.sql
  docker/thirdparties/docker-compose/postgresql/init/04-insert.sql
  docker/thirdparties/docker-compose/sqlserver/init/03-create-table.sql
  docker/thirdparties/docker-compose/sqlserver/init/04-insert.sql
  regression-test/data/external_table_p0/jdbc/type_test/select/test_clickhouse_all_types_select.out
  regression-test/data/external_table_p0/jdbc/type_test/select/test_oracle_all_types_select.out
  regression-test/data/external_table_p0/jdbc/type_test/select/test_pg_all_types_select.out
  regression-test/data/external_table_p0/jdbc/type_test/select/test_sqlserver_all_types_select.out
  regression-test/suites/external_table_p0/jdbc/type_test/select/test_clickhouse_all_types_select.groovy
  regression-test/suites/external_table_p0/jdbc/type_test/select/test_oracle_all_types_select.groovy
  regression-test/suites/external_table_p0/jdbc/type_test/select/test_pg_all_types_select.groovy
  regression-test/suites/external_table_p0/jdbc/type_test/select/test_sqlserver_all_types_select.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#47609 [fix](cloud) fix file cache get_or_set timer overflow
  be/src/io/cache/block_file_cache.cpp
Labels: approved, reviewed, dev/3.0.x

#47545 [test](beut) add hash-table HashMethod be ut test
  be/test/exec/hash_map/hash_table_method_test.cpp
  be/test/testutil/column_helper.cpp
  be/test/testutil/column_helper.h
Labels: approved, reviewed

#47588 [chore](ci) fix _monitor_regression_log for "regression-test/log/sedW…
  regression-test/pipeline/common/doris-utils.sh
Labels: approved, reviewed, dev/3.0.x

#47589 [fix] (build) Fix MacOS running error `check failed: is_attach_task`
  be/src/runtime/thread_context.h
Labels: approved, reviewed

#47601 [fix](test) fix test_routine_load case unstable
  regression-test/suites/load_p0/routine_load/ddl/agg_tbl_basic_drop.sql
  regression-test/suites/load_p0/routine_load/ddl/dup_tbl_array_drop.sql
  regression-test/suites/load_p0/routine_load/ddl/dup_tbl_basic_drop.sql
  regression-test/suites/load_p0/routine_load/ddl/dup_tbl_basic_multi_table_drop.sql
  regression-test/suites/load_p0/routine_load/ddl/mow_tbl_array_drop.sql
  regression-test/suites/load_p0/routine_load/ddl/mow_tbl_basic_drop.sql
  regression-test/suites/load_p0/routine_load/ddl/uniq_tbl_array_drop.sql
  regression-test/suites/load_p0/routine_load/ddl/uniq_tbl_basic_drop.sql
  regression-test/suites/load_p0/routine_load/ddl/uniq_tbl_basic_drop_sequence.sql
Labels: approved, reviewed, dev/3.0.x

#47314 [feature](restore) support force_replace restore
  fe/fe-core/src/main/java/org/apache/doris/analysis/RestoreStmt.java
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupHandler.java
  fe/fe-core/src/main/java/org/apache/doris/backup/RestoreJob.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/org/apache/doris/backup/RestoreJobTest.java
  gensrc/thrift/FrontendService.thrift
  regression-test/suites/backup_restore/test_backup_restore_force_replace_diff_column.groovy
  regression-test/suites/backup_restore/test_backup_restore_force_replace_diff_part_type.groovy
  regression-test/suites/backup_restore/test_backup_restore_force_replace_diff_part_val.groovy
Labels: approved, reviewed

#47571 [fix](partition) Remove invalid partition property in synced table
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
  regression-test/suites/partition_p0/test_partition_storage_policy.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#47547 [feat](binlog) Speed binlog gc by locked binlogs
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/binlog/BinlogManager.java
  fe/fe-core/src/main/java/org/apache/doris/binlog/DBBinlog.java
  fe/fe-core/src/main/java/org/apache/doris/binlog/TableBinlog.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#47610 [Fix](load) Reset memtable immediately after insert failure to prevent crash
  be/src/olap/memtable_writer.cpp
Labels: approved, reviewed, dev/3.0.x

#47551 [chore](binlog) Save properties in CreateTableRecord
  fe/fe-core/src/main/java/org/apache/doris/binlog/CreateTableRecord.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#47557 [feat](binlog) Support getting binlogs in batch
  fe/fe-core/src/main/java/org/apache/doris/binlog/BinlogManager.java
  fe/fe-core/src/main/java/org/apache/doris/binlog/BinlogUtils.java
  fe/fe-core/src/main/java/org/apache/doris/binlog/DBBinlog.java
  fe/fe-core/src/main/java/org/apache/doris/binlog/TableBinlog.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  gensrc/thrift/FrontendService.thrift
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#47582 [fix](UT) Fix cloud UT network_util_test and resource_test
  cloud/test/network_util_test.cpp
  cloud/test/resource_test.cpp
Labels: approved, reviewed, dev/3.0.x

#41925 [Enhancement](regression-test)Add regression test for database properties backup and restore
  regression-test/suites/backup_restore/test_backup_store_with_db_properties.groovy
  regression-test/suites/backup_restore/test_backup_store_with_db_properties_kv.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#47271 [fix](schema-change) Forbid modifying mv related columns
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/RelationUtil.java
  regression-test/data/schema_change_p0/modify_col_type_agg/schema_change_modify_mv_column_type_agg.out
  regression-test/data/schema_change_p0/modify_col_type_dup/schema_change_modify_mv_column_type.out
  regression-test/suites/mv_p0/routine_load_mapping/routine_load_mapping.groovy
  regression-test/suites/schema_change_p0/modify_col_type_agg/schema_change_modify_mv_column_type_agg.groovy
  regression-test/suites/schema_change_p0/modify_col_type_dup/schema_change_modify_mv_column_type.groovy
Labels: approved, reviewed, kind/behavior-changed, dev/3.0.x

#47580 [fix](cloud-mow)Fix not release delete bitmap lock when checking txn state is visible
  fe/fe-core/src/main/java/org/apache/doris/cloud/transaction/CloudGlobalTransactionMgr.java
  regression-test/suites/fault_injection_p0/cloud/test_cloud_mow_stream_load_with_commit_fail.groovy
  regression-test/suites/fault_injection_p0/cloud/test_cloud_mow_stream_load_with_timeout.groovy
Labels: approved, reviewed, p0_b, dev/3.0.x

#47630 [UT](local exchanger) Add UT case for local exchanger
  be/src/pipeline/local_exchange/local_exchange_source_operator.cpp
  be/test/pipeline/local_exchanger_test.cpp
Labels: approved, reviewed

#47566 [improvement](status) Change the return type for block_compression
  be/src/util/block_compression.cpp
  be/src/vec/functions/function_compress.cpp
Labels: approved, reviewed

#47364 [enhance](column) add has_enough_capacity function interface for column and fix analytic operator string overflow
  be/src/pipeline/exec/analytic_sink_operator.cpp
  be/src/vec/columns/column.h
  be/src/vec/columns/column_array.cpp
  be/src/vec/columns/column_array.h
  be/src/vec/columns/column_complex.h
  be/src/vec/columns/column_const.h
  be/src/vec/columns/column_decimal.h
  be/src/vec/columns/column_dictionary.h
  be/src/vec/columns/column_dummy.h
  be/src/vec/columns/column_fixed_length_object.h
  be/src/vec/columns/column_map.cpp
  be/src/vec/columns/column_map.h
  be/src/vec/columns/column_nullable.cpp
  be/src/vec/columns/column_nullable.h
  be/src/vec/columns/column_object.h
  be/src/vec/columns/column_string.cpp
  be/src/vec/columns/column_string.h
  be/src/vec/columns/column_struct.cpp
  be/src/vec/columns/column_struct.h
  be/src/vec/columns/column_vector.h
  be/src/vec/columns/predicate_column.h
  be/src/vec/common/sort/sorter.cpp
  be/src/vec/common/sort/sorter.h
  be/test/vec/exec/sort/sort_test.cpp
  regression-test/data/query_p0/sql_functions/window_functions/test_column_boundary.out
  regression-test/suites/query_p0/sql_functions/window_functions/test_column_boundary.groovy
Labels: approved, reviewed

#45936 [refactor](plugin) unify the plugin dir
  be/src/common/config.cpp
  be/src/runtime/user_function_cache.cpp
  be/src/runtime/user_function_cache.h
  bin/start_be.sh
  bin/start_fe.sh
  build.sh
  fe/be-java-extensions/trino-connector-scanner/src/main/java/org/apache/doris/trinoconnector/TrinoConnectorPluginLoader.java
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateFunctionStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/JdbcResource.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/trinoconnector/TrinoConnectorPluginLoader.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/JdbcResourceTest.java
Labels: approved, reviewed, kind/behavior-changed, dev/2.1.x-experimental, dev/3.0.x-experimental

#47620 [refactor](local exchange) Simplify block wrapper
  be/src/pipeline/dependency.h
  be/src/pipeline/local_exchange/local_exchanger.cpp
  be/src/pipeline/local_exchange/local_exchanger.h
  be/test/pipeline/local_exchanger_test.cpp
Labels: approved, reviewed

#47625 [fix](orc) dont't push down null aware predicate
  be/src/vec/exec/format/orc/vorc_reader.cpp
  docker/thirdparties/docker-compose/hive/scripts/data/multi_catalog/orc_predicate/orc_predicate_table.hql
  regression-test/data/external_table_p0/hive/test_hive_orc_predicate.out
  regression-test/suites/external_table_p0/hive/test_hive_orc_predicate.groovy
Labels: approved, reviewed, dev/3.0.x, dev/2.1.x-experimental

#47514 branch-2.1: [fix](nereids) fix compare ipv4 / ipv6 always equals
  fe/fe-core/pom.xml
  fe/fe-core/src/main/java/org/apache/doris/analysis/DateLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/DecimalLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/FloatLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/IPv4Literal.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/IPv6Literal.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/IntLiteral.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/ComparisonPredicate.java
  fe/fe-core/src/test/java/org/apache/doris/common/proc/IndexesProcNodeTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/expressions/literal/CompareLiteralTest.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/TestWithFeService.java
  regression-test/suites/nereids_p0/literal/test_compare_literal.groovy
Labels: approved, reviewed

#47649 [refactor](fe) remove some forward session var logic
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/FEOpExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/MasterOpExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/QueryStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/qe/SessionVariablesTest.java
Labels: approved, reviewed

#46738 [fix] fix npe for olap scan node
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
Labels: approved, reviewed

#47664 [fix](inverted index) Downgrade ICU version to support lower OS versions
  thirdparty/build-thirdparty.sh
  thirdparty/vars.sh
Labels: approved, reviewed

#47025 [enhance](runtime filter) impl partition pruning in runtime filer
  be/src/vec/core/block.cpp
  be/src/vec/exec/scan/vfile_scanner.cpp
  be/src/vec/exec/scan/vfile_scanner.h
  docker/thirdparties/docker-compose/hive/scripts/create_preinstalled_scripts/run73.hql
  docker/thirdparties/docker-compose/hive/scripts/create_preinstalled_scripts/run74.hql
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/partition_tables/date_partition_table/partition_col=2025-01-01/000000_0
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/partition_tables/date_partition_table/partition_col=2025-01-02/000000_0
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/partition_tables/date_partition_table/partition_col=2025-01-03/000000_0
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/partition_tables/decimal_partition_table/partition_col=100.01/000000_0
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/partition_tables/decimal_partition_table/partition_col=200.02/000000_0
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/partition_tables/decimal_partition_table/partition_col=300.03/000000_0
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/partition_tables/int_partition_table/partition_col=1/000000_0
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/partition_tables/int_partition_table/partition_col=2/000000_0
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/partition_tables/int_partition_table/partition_col=3/000000_0
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/partition_tables/string_partition_table/partition_col=A/000000_0
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/partition_tables/string_partition_table/partition_col=B/000000_0
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/partition_tables/string_partition_table/partition_col=C/000000_0
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  gensrc/thrift/PaloInternalService.thrift
  regression-test/data/external_table_p0/hive/test_hive_runtime_filter_partition_pruning.out
  regression-test/suites/external_table_p0/hive/test_hive_runtime_filter_partition_pruning.groovy
Labels: approved, reviewed, dev/2.1.x-experimental, dev/3.0.x-experimental

#47663 [fix](test) fix test_routine_load_eof case execute too long
  regression-test/suites/load_p0/routine_load/test_routine_load_eof.groovy
Labels: approved, reviewed, dev/3.0.x

#47656 [UT](local exchange) Add UT case for AdaptivePassthrough/Broadcast Ex…
  be/src/pipeline/local_exchange/local_exchanger.cpp
  be/test/pipeline/local_exchanger_test.cpp
Labels: approved, reviewed

#47634 [fix](inverted index) resolve io_ctx heap-use-after-free in concurrent reader access
  be/src/olap/rowset/segment_v2/inverted_index_compound_reader.cpp
  be/src/olap/rowset/segment_v2/inverted_index_compound_reader.h
  be/src/olap/rowset/segment_v2/inverted_index_file_reader.cpp
  be/src/olap/rowset/segment_v2/inverted_index_file_reader.h
  be/src/olap/rowset/segment_v2/inverted_index_reader.cpp
  regression-test/suites/fault_injection_p0/test_index_io_context.groovy
Labels: approved, reviewed, p0_c, dev/3.0.x

#47651 [test](case) add system table simple query test
  regression-test/suites/query_p0/system/test_query_sys_tables.groovy
Labels: approved, reviewed

#47635 [log](regression)Add log for failed analyze task and the regression case.
  fe/fe-core/src/main/java/org/apache/doris/statistics/BaseAnalysisTask.java
  regression-test/suites/statistics/test_update_rows_mv.groovy
Labels: approved, reviewed

#47556 [fix](resource) Fix `MemTableWriter` attach resource context to thread context
  be/src/olap/memtable_writer.cpp
  be/src/runtime/load_channel.cpp
  be/src/runtime/load_channel.h
  be/src/runtime/load_channel_mgr.cpp
  be/src/runtime/memory/thread_mem_tracker_mgr.cpp
  be/src/runtime/memory/thread_mem_tracker_mgr.h
  be/src/runtime/thread_context.cpp
  be/src/runtime/thread_context.h
  be/test/runtime/memory/thread_mem_tracker_mgr_test.cpp
Labels: approved, reviewed

#47646 [Fix](recycler) Fix recycler pipeline case check_meta
  regression-test/suites/correctness_p0/test_mv_case/test_mv_case.groovy
Labels: approved, reviewed, dev/3.0.x

#47654 [improvement](test) improvement case compatible with multi platform(l…
  regression-test/suites/auth_call/test_dml_broker_load_auth.groovy
  regression-test/suites/load_p0/broker_load/test_domain_connection_and_ak_sk_correction.groovy
  regression-test/suites/load_p0/broker_load/test_seq_load.groovy
  regression-test/suites/load_p0/stream_load/test_stream_load_error_url.groovy
Labels: approved, reviewed, dev/3.0.x

#47318 [fix](nereids)keep at least one hash output slot when prune slots in hash join node
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/PhysicalPlanTranslator.java
  regression-test/data/correctness_p0/test_column_prune_in_hash_join.out
  regression-test/suites/correctness_p0/test_column_prune_in_hash_join.groovy
Labels: approved, reviewed, p0_c, dev/2.0.x, dev/2.1.x, dev/3.0.x

#46838 [Enhancement] (nereids)implement alterRepositoryCommand in nereids
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupHandler.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PlanType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/alter/AlterRepositoryCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/CommandVisitor.java
  regression-test/suites/alter_p2/test_alter_repository_command.groovy
Labels: approved, reviewed

#47677 [fix](cases)rename test case file name
  regression-test/data/nereids_function_p0/array/test_array_map_char_double.csv
  regression-test/data/nereids_function_p0/array/test_array_map_datetime_decimal.csv
  regression-test/data/nereids_function_p0/array/test_array_map_ipv4_ipv6.csv
  regression-test/data/nereids_function_p0/array/test_array_map_largeInt_string.csv
Labels: approved, reviewed

#47686 [chore](case) exclude some cases
  regression-test/pipeline/external/conf/regression-conf.groovy
  regression-test/pipeline/p0/conf/regression-conf.groovy
Labels: kind/test

#47431 [test](hudi) add more hudi jni test cases
  regression-test/data/external_table_p2/hudi/test_hudi_incremental.out
  regression-test/data/external_table_p2/hudi/test_hudi_schema_evolution.out
  regression-test/data/external_table_p2/hudi/test_hudi_snapshot.out
  regression-test/data/external_table_p2/hudi/test_hudi_timetravel.out
  regression-test/suites/external_table_p2/hudi/test_hudi_incremental.groovy
  regression-test/suites/external_table_p2/hudi/test_hudi_schema_evolution.groovy
  regression-test/suites/external_table_p2/hudi/test_hudi_snapshot.groovy
  regression-test/suites/external_table_p2/hudi/test_hudi_timetravel.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#47192 [Fix](catalog)Fixes query failures for Paimon tables stored in Kerberized HDFS
  fe/be-java-extensions/hadoop-hudi-scanner/src/main/java/org/apache/doris/hudi/HadoopHudiJniScanner.java
  fe/be-java-extensions/paimon-scanner/pom.xml
  fe/be-java-extensions/paimon-scanner/src/main/java/org/apache/doris/paimon/PaimonJniScanner.java
  fe/fe-common/src/main/java/org/apache/doris/common/security/authentication/AuthenticationConfig.java
  fe/fe-common/src/main/java/org/apache/doris/common/security/authentication/PreExecutionAuthenticatorCache.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#47280 [feature](neredis)Support show analyze in Nereids.
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PlanType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ShowAnalyzeCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/CommandVisitor.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisManager.java
  regression-test/suites/statistics/analyze_stats.groovy
Labels: approved, reviewed

#47599 [test](beut) add pipeline operator be ut case
  be/src/pipeline/exec/assert_num_rows_operator.h
  be/src/pipeline/exec/datagen_operator.h
  be/src/pipeline/exec/empty_set_operator.h
  be/src/pipeline/exec/mock_operator.h
  be/src/pipeline/exec/operator.cpp
  be/src/pipeline/exec/operator.h
  be/test/pipeline/operator/assert_nums_rows_operator.cpp
  be/test/pipeline/operator/datagen_operator_test.cpp
  be/test/pipeline/operator/empty_set_operator_test.cpp
  be/test/pipeline/operator/operator_helper.h
  be/test/testutil/column_helper.h
Labels: approved, reviewed

#47626 branch-2.0: [fix](mem leak) fe non_heap mem leak while use jdbc catalog #45806
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/client/JdbcClient.java
Labels: approved, reviewed

#47332 [chore](file cache) Disable show cache hotspot stmt
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowCacheHotSpotStmt.java
Labels: approved, reviewed, dev/3.0.x

#47600 [opt](log) Add some logs for recycler
  cloud/src/recycler/recycler.cpp
Labels: approved, reviewed, dev/3.0.x

#47647 [log](mow) reduce log for data load on mow table
  be/src/cloud/cloud_engine_calc_delete_bitmap_task.cpp
  be/src/cloud/cloud_txn_delete_bitmap_cache.cpp
  be/src/olap/base_tablet.cpp
  be/src/olap/rowset_builder.cpp
Labels: approved, reviewed, dev/3.0.x

#47583 [Fix](regression) Fix case `test_add_key_partial_update`
  regression-test/suites/fault_injection_p0/partial_update/test_add_key_partial_update.groovy
Labels: approved, reviewed, dev/3.0.x

#47510 [improve](load) improve error messages for "no backend available"
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/system/SystemInfoService.java
  regression-test/suites/workload_manager_p0/test_resource_tag.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#47470 [improve](move-memtable) improve error log and message for "not enough streams"
  be/src/vec/sink/writer/vtablet_writer_v2.cpp
  regression-test/suites/fault_injection_p0/test_multi_replica_fault_injection.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#47706 [fix](ut) fix cases for rename file name link pr 47677
  be/test/vec/data_types/data_type_array_test.cpp
Labels: approved, reviewed

#47679 [fix](jni) pass krb5 conf to jni
  be/src/util/jni-util.cpp
Labels: dev/2.1.x

#47603 [fix](external catalog) Fix missing fields when rebuilding metadata from image
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalDatabase.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/InitCatalogLog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/InitDatabaseLog.java
Labels: approved, reviewed, usercase, p0_b, dev/2.1.x, dev/3.0.4-merged

#47727 [fix](coordinator) Fix wrong `recvrId` in fragment contains BHJ
  be/src/pipeline/local_exchange/local_exchanger.cpp
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
Labels: approved, reviewed, dev/2.1.x

#47506 [fix](orc) remove unnecessary fields of orc_reader
  be/src/vec/exec/format/orc/vorc_reader.cpp
  be/src/vec/exec/format/orc/vorc_reader.h
Labels: approved, reviewed, dev/2.1.x-experimental, dev/3.0.x-experimental

#47715 [Fix](memory) Add try catch block for `Segment::load_pk_index_and_bf`
  be/src/olap/rowset/segment_v2/segment.cpp
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#47740 [chore](github)Delete inactive collaborators
  .asf.yaml
Labels: approved, reviewed

#47745 [fix](github)Fix the incorrect format of branch-3.0 .asf.yaml
  .asf.yaml
Labels: approved, reviewed

#47228 [fix](Nereids) fix log bug and add more numeric arithmetic function cases
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/executable/NumericArithmetic.java
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
  regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_numeric_arithmatic.groovy
Labels: approved, reviewed, p0_w, dev/2.1.x, dev/3.0.x

#47750 [fix](be) fix be compile error
  be/src/vec/exec/format/orc/vorc_reader.cpp
  be/src/vec/exec/scan/vfile_scanner.cpp
Labels: approved, reviewed

#47573 [regression-test](fix) sleep after mv job finished
  regression-test/suites/schema_change_p0/test_dup_rollup_schema_change.groovy
  regression-test/suites/schema_change_p0/test_uniq_rollup_schema_change.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#47549 [regression-test](suite) add sleep to waitingMVTaskFinishedByMvName
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#47553 [regression-test](cases) remove 3 cases not suitable for cloud
  regression-test/pipeline/cloud_p0/conf/regression-conf-custom.groovy
  regression-test/suites/nereids_rules_p0/partition_prune/auto_partition.groovy
Labels: approved, reviewed

#47097 [test](cloud-mow)Add update big delete bitmap case
  be/src/cloud/cloud_meta_mgr.cpp
  regression-test/suites/compaction/test_compaction_update_big_delete_bitmap.groovy
Labels: approved, reviewed, dev/3.0.x

#47761 branch-3.0: [fix](Nereids) not release lock if schema changed when insert #47733
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/InsertIntoTableCommand.java
Labels: approved, reviewed

#47763 bump to 3.0.4-rc01
  gensrc/script/gen_build_version.sh
Labels: approved, reviewed

#47644 [opt](debug) remove redundant DCHECK to allow graceful error handling
  be/src/io/fs/hdfs_file_writer.cpp
Labels: approved, reviewed

#47627 [improve](functon) improve json_object with complex type
  be/src/vec/functions/function_json.cpp
  fe/fe-core/src/main/java/org/apache/doris/analysis/CastExpr.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/JsonObject.java
  regression-test/data/query_p0/cast/test_complextype_to_json.out
  regression-test/data/query_p0/sql_functions/json_function/test_query_json_object.out
  regression-test/suites/query_p0/sql_functions/json_function/test_query_json_object.groovy
Labels: approved, reviewed, kind/behavior-changed, dev/2.1.x, dev/3.0.x

#47716 [fix](nereids)use visitNullableAggregateFunction for NullableAggregateFunction
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/AggregateFunctionVisitor.java
Labels: approved, reviewed

#47593 [opt](paimon) Optimize error prompt
  fe/fe-core/src/main/java/org/apache/doris/datasource/paimon/PaimonExternalCatalog.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/paimon/PaimonExternalCatalogTest.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#47787 [UT](exchanger) Add UT case to test local merge exchanger
  be/src/pipeline/exec/operator.h
  be/src/pipeline/local_exchange/local_exchange_sink_operator.h
  be/src/pipeline/local_exchange/local_exchange_source_operator.h
  be/src/pipeline/local_exchange/local_exchanger.cpp
  be/src/pipeline/local_exchange/local_exchanger.h
  be/src/vec/core/sort_cursor.h
  be/test/pipeline/local_exchanger_test.cpp
Labels: approved, reviewed

#47690 [fix](restore) Filter partition property storage policy in synced table
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  regression-test/suites/backup_restore/test_backup_restore_storage_policy.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#47758 [Test](cbq) Filter checks for light_schema_change
  regression-test/suites/check_before_quit/check_before_quit.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#47732 [fix](table) Supply rollup for get ddl for sync
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/CreateTableLikeTest.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#47561 [test](case) fix tpcds_sf100_dup_without_key_p2 q17 result file
  regression-test/data/tpcds_sf100_dup_without_key_p2/sql/q17.out
Labels: approved, reviewed, dev/3.0.x

#47739 [Enhancement](recycler) Add some UT for recycler
  cloud/src/recycler/recycler.cpp
  cloud/src/recycler/s3_accessor.cpp
  cloud/test/hdfs_accessor_test.cpp
  cloud/test/recycler_test.cpp
Labels: approved, reviewed, dev/3.0.x

#47596 [chore](rename) Forbid renaming partition columns since this is a buggy feature
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  regression-test/suites/partition_p0/dynamic_partition/test_dynamic_partition_with_rename.groovy
  regression-test/suites/schema_change_p0/test_rename_partition_column.groovy
Labels: approved, reviewed, kind/behavior-changed

#47772 [fix](nereids) fix join condition with AddMinMax rule hung
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/ExpressionRewrite.java
  regression-test/data/nereids_syntax_p0/join_condition.out
  regression-test/suites/nereids_syntax_p0/join_condition.groovy
Labels: approved, reviewed, p0_b, dev/2.1.x, dev/3.0.x

#47434 [fix](nereids) fix range inference generate an empty range
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/AddMinMax.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/RangeInference.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/expression/ExpressionRewriteTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/expression/SimplifyRangeTest.java
Labels: approved, reviewed

#47528 [fix](routine load) fix incorrect auto-resume interval caused by excessive auto-resume attempts
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/ScheduleRule.java
  fe/fe-core/src/test/java/org/apache/doris/load/routineload/RoutineLoadManagerTest.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#47655 [fix](column) Math default value showed incorrectly
  fe/fe-core/src/main/java/org/apache/doris/catalog/Column.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/commands/ShowCreateTableCommandTest.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#47735 Revert "[Improvement]downgrade resource tag when there is not queryab…
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/FederationBackendPolicy.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/LoadAction.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/MysqlProto.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/Auth.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/CommonUserProperties.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/UserProperty.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/UserPropertyMgr.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContext.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/system/BeSelectionPolicy.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/OlapTableTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/ResourceTagQueryTest.java
  fe/fe-core/src/test/java/org/apache/doris/system/SystemInfoServiceTest.java
  regression-test/data/workload_manager_p0/skip_rg_test_table.csv
  regression-test/suites/workload_manager_p0/test_resource_tag.groovy
Labels: approved, reviewed

#47570 [opt](nereids) optimize limit on distinct aggregate
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/PhysicalPlanTranslator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/LimitAggToTopNAgg.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/algebra/Aggregate.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalAggregate.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalHashAggregate.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/PushDownLimitDistinctThroughJoinTest.java
  regression-test/data/nereids_rules_p0/push_down_limit_distinct/push_down_limit_distinct_through_join.out
  regression-test/data/nereids_tpch_p0/tpch/push_topn_to_agg.out
  regression-test/suites/nereids_tpch_p0/tpch/push_topn_to_agg.groovy
Labels: approved, reviewed, dev/3.0.x

#47762 [fix](regression-test) alter some cases nonConcurrent to prevent MapRedTask Execution Error
  regression-test/suites/external_table_p0/hive/ddl/test_hive_ddl_text_format.groovy
  regression-test/suites/mtmv_p0/test_hive_default_mtmv.groovy
  regression-test/suites/mtmv_p0/test_hive_limit_partition_mtmv.groovy
  regression-test/suites/mtmv_p0/test_hive_multi_partition_mtmv.groovy
Labels: approved, reviewed

#47818 [regression-test](case) remove test_auto_partition_behavior before fix
  regression-test/pipeline/p0/conf/regression-conf.groovy
Labels: approved, reviewed

#47741 [fix](regression) regression case: limit_push_down is unstable
  regression-test/data/nereids_rules_p0/limit_push_down/limit_push_down.out
  regression-test/suites/nereids_rules_p0/limit_push_down/limit_push_down.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#47769 [regression-test](debug) add debug info
  regression-test/pipeline/cloud_p0/conf/fe_custom.conf
  regression-test/pipeline/p0/conf/fe.conf
Labels: approved, reviewed

#47785 [regression-test](fix) fix some fail filecache cases
  regression-test/plugins/cloud_filecache_plugin.groovy
  regression-test/suites/cloud_p0/cache/multi_cluster/warm_up/hotspot/test_warmup_show_stmt.groovy
  regression-test/suites/cloud_p0/cache/multi_cluster/warm_up/hotspot/test_warmup_show_stmt_2.groovy
  regression-test/suites/cloud_p0/cache/multi_cluster/warm_up/hotspot/test_warmup_show_stmt_3.groovy
  regression-test/suites/cloud_p0/cache/ttl/alter_ttl_1.groovy
  regression-test/suites/cloud_p0/cache/ttl/alter_ttl_2.groovy
Labels: approved, reviewed, dev/3.0.x

#46912 [fix](jdbc catalog) Change BE jdbc Driver loading to Java code
  be/src/runtime/user_function_cache.cpp
  be/src/runtime/user_function_cache.h
  be/src/vec/exec/vjdbc_connector.cpp
  be/src/vec/exec/vjdbc_connector.h
  fe/be-java-extensions/jdbc-scanner/src/main/java/org/apache/doris/jdbc/BaseJdbcExecutor.java
  fe/be-java-extensions/jdbc-scanner/src/main/java/org/apache/doris/jdbc/JdbcDataSourceConfig.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/JdbcResource.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/JdbcResourceTest.java
  gensrc/thrift/Types.thrift
Labels: approved, reviewed, usercase, dev/2.1.x, dev/3.0.x

#47827 [regresion-test](fix) fix cache plugin bug
  regression-test/plugins/cloud_filecache_plugin.groovy
Labels: approved, reviewed, dev/3.0.x

#47733 [fix](Nereids) not release lock if schema changed when insert
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/InsertIntoTableCommand.java
Labels: approved, reviewed, p0_b, dev/2.1.x, dev/3.0.4-merged

#47650 [fix](mv) Fix use sync mv wrongly when use rbo materialized view rewrite rule
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/mv/SelectMaterializedIndexWithAggregate.java
  regression-test/data/mv_p0/agg_use_key_direct/agg_use_key_direct.out
  regression-test/suites/mv_p0/agg_use_key_direct/agg_use_key_direct.groovy
Labels: approved, reviewed, p0_w, dev/2.1.x, dev/3.0.x

#47821 [fix](case) add regression-test/data/variant_github_events_nonConcurr…
  regression-test/data/variant_github_events_nonConcurrent_p2/load.out
Labels: approved, reviewed, dev/3.0.x

#47712 [Opt](cloud) Add some injection points for mow
  be/src/cloud/cloud_engine_calc_delete_bitmap_task.cpp
  be/src/olap/base_tablet.cpp
  regression-test/data/fault_injection_p0/cloud/test_cloud_mow_correctness_inject.out
  regression-test/suites/fault_injection_p0/cloud/test_cloud_mow_correctness_inject.groovy
  regression-test/suites/fault_injection_p0/cloud/test_cloud_mow_partial_update_retry.groovy
  regression-test/suites/fault_injection_p0/cloud/test_cloud_mow_stale_resp_load_compaction_conflict.groovy
  regression-test/suites/fault_injection_p0/cloud/test_cloud_mow_stale_resp_load_load_conflict.groovy
Labels: approved, reviewed, dev/3.0.x

#43913 [Opt](multi-catalog)Improve performance by introducing cache of list directory files when getting split for each query.
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/common/EmptyCache.java
  fe/fe-core/src/main/java/org/apache/doris/common/EvictableCache.java
  fe/fe-core/src/main/java/org/apache/doris/common/EvictableCacheBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HMSExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HiveMetaStoreCache.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/source/HiveScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hudi/source/HudiScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/fs/DirectoryLister.java
  fe/fe-core/src/main/java/org/apache/doris/fs/FileSystemDirectoryLister.java
  fe/fe-core/src/main/java/org/apache/doris/fs/FileSystemIOException.java
  fe/fe-core/src/main/java/org/apache/doris/fs/RemoteFileRemoteIterator.java
  fe/fe-core/src/main/java/org/apache/doris/fs/RemoteIterator.java
  fe/fe-core/src/main/java/org/apache/doris/fs/SimpleRemoteIterator.java
  fe/fe-core/src/main/java/org/apache/doris/fs/TransactionDirectoryListingCacheKey.java
  fe/fe-core/src/main/java/org/apache/doris/fs/TransactionScopeCachingDirectoryLister.java
  fe/fe-core/src/main/java/org/apache/doris/fs/TransactionScopeCachingDirectoryListerFactory.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/PhysicalPlanTranslator.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
  fe/fe-core/src/test/java/org/apache/doris/common/TestEvictableCache.java
  fe/fe-core/src/test/java/org/apache/doris/fs/TransactionScopeCachingDirectoryListerTest.java
Labels: approved, reviewed, dev/2.1.x-experimental, dev/3.0.x-experimental

#47530 [improve](routine load) ensure abnormal jobs do not interfere with normal task scheduling
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/KafkaRoutineLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadJob.java
  fe/fe-core/src/test/java/org/apache/doris/load/routineload/RoutineLoadManagerTest.java
Labels: approved, reviewed, usercase, dev/2.1.x, dev/3.0.x

#47653 [branch-20](bug) fix analytic illegal frame range
  be/src/vec/aggregate_functions/aggregate_function_window.h
  be/src/vec/exec/vanalytic_eval_node.cpp
  regression-test/data/nereids_syntax_p0/window_function.out
  regression-test/suites/nereids_syntax_p0/window_function.groovy
Labels: kind/test, approved, reviewed

#47836 [improvement](test) improvement case compatible with multi platform(l…
  regression-test/suites/auth_call/test_dml_broker_load_auth.groovy
  regression-test/suites/load_p0/broker_load/test_domain_connection_and_ak_sk_correction.groovy
  regression-test/suites/load_p0/broker_load/test_seq_load.groovy
  regression-test/suites/load_p0/stream_load/test_stream_load_error_url.groovy
Labels: approved, reviewed

#47607 [fix](load) fix metrics memtable_flush_duration_us
  be/src/olap/memtable_flush_executor.cpp
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#47815 [minor](exchange) Rename shuffle partition type
  be/src/pipeline/exec/exchange_sink_operator.cpp
  be/src/vec/sink/tablet_sink_hash_partitioner.cpp
  be/src/vec/sink/writer/vtablet_writer.cpp
  be/src/vec/sink/writer/vtablet_writer_v2.cpp
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/PhysicalPlanTranslator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/DistributionSpecHiveTableSinkHashPartitioned.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/DistributionSpecHiveTableSinkUnPartitioned.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/DistributionSpecOlapTableSinkHashPartitioned.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/properties/PhysicalProperties.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/OlapInsertExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalHiveTableSink.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/physical/PhysicalIcebergTableSink.java
  fe/fe-core/src/main/java/org/apache/doris/planner/DataPartition.java
  fe/fe-core/src/main/java/org/apache/doris/planner/ExchangeNode.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/hive/HiveDDLAndDMLPlanTest.java
  gensrc/thrift/DataSinks.thrift
  gensrc/thrift/Partitions.thrift
  regression-test/suites/insert_p0/test_insert_tablet_sink.groovy
Labels: approved, reviewed

#47336 [test](ms) Add injection point to randomly fail in `txn->commit()` for test
  cloud/src/meta-service/injection_point_http.cpp
  cloud/src/meta-service/txn_kv.cpp
  regression-test/data/fault_injection_p0/cloud/test_txn_commit_inject.out
  regression-test/suites/fault_injection_p0/cloud/test_txn_commit_inject.groovy
Labels: approved, reviewed, dev/3.0.x

#47830 [opt](nereids) simplify range kept in predicate options' order
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/RangeInference.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/expression/rules/InPredicateExtractNonConstantTest.java
  regression-test/suites/nereids_rules_p0/expression/test_simplify_range.groovy
Labels: approved, reviewed, usercase, p0_b, dev/2.1.x, dev/3.0.4-merged

#47844 [Bug](fix) Fix topn agg limit may get error result in when refresh heap
  be/src/pipeline/dependency.cpp
  be/src/pipeline/dependency.h
  be/src/pipeline/exec/aggregation_sink_operator.cpp
  be/test/pipeline/operator/agg_shared_state_test.cpp
Labels: approved, reviewed, dev/3.0.x

#47185 [enhance](auth)The priority of attributes is higher than session variable
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContext.java
  fe/fe-core/src/main/java/org/apache/doris/qe/Coordinator.java
  fe/fe-core/src/main/java/org/apache/doris/qe/CoordinatorContext.java
  fe/fe-core/src/test/java/org/apache/doris/qe/ConnectContextTest.java
  regression-test/suites/account_p0/test_property_session.groovy
Labels: approved, reviewed, kind/behavior-changed, usercase, dev/2.1.x, dev/3.0.x

#45674 [feature](nereids)support CreateMaterializedViewCommand in nereids
  fe/fe-core/src/main/java/org/apache/doris/alter/Alter.java
  fe/fe-core/src/main/java/org/apache/doris/alter/MaterializedViewHandler.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/MVColumnItem.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/SlotReference.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PlanType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/CreateMaterializedViewCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/CommandVisitor.java
  fe/fe-core/src/test/java/org/apache/doris/alter/MaterializedViewHandlerTest.java
  regression-test/suites/ddl_p0/create_view_nereids/create_view_use_mv.groovy
  regression-test/suites/mv_p0/agg_state/order_by/order_by.groovy
  regression-test/suites/mv_p0/ut/testProjectionMV1/testProjectionMV1.groovy
Labels: approved, reviewed

#45874 [feature](nereids)support create function command in nereids
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PlanType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/CreateFunctionCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/DropFunctionCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/ColumnDefinition.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/FunctionArgTypesInfo.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/CommandVisitor.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/types/DataType.java
  regression-test/suites/ddl_p0/test_alias_function.groovy
  regression-test/suites/query_p0/sql_functions/test_alias_function.groovy
Labels: approved, reviewed

#47823 [fix](table) Fix get sycned ddl for table without rollup
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/CreateTableLikeTest.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#47744 [fix](scanner) fix shared rowset reader in different scanners
  be/src/pipeline/exec/olap_scan_operator.cpp
Labels: approved, reviewed, dev/3.0.x

#47860 [fix](load) add null check for memtable after write failure reset
  be/src/olap/memtable_writer.cpp
Labels: approved, reviewed, p0_c, dev/3.0.x
