Repository apache/doris, pull requests merged in 2025-04, with the labels that each got.

#49644 [third-party](faiss) Enable FAISS integration in Doris.
  be/CMakeLists.txt
  be/cmake/thirdparty.cmake
  build.sh
  thirdparty/build-thirdparty.sh
  thirdparty/download-thirdparty.sh
  thirdparty/patches/faiss-1.10.0.patch
  thirdparty/vars.sh
Labels: approved, reviewed

#49700 [fix](shutdown) Fix coredump due to shutdown in the wrong order
  be/src/runtime/exec_env_init.cpp
Labels: approved, reviewed

#49628 Revert "[opt](nereids) remove redundant hash join condition (#48363)"
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVPlanUtil.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/Rewriter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/MaterializedViewUtils.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/EliminateConstHashJoinCondition.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalJoin.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/jobs/joinorder/hypergraph/PullupExpressionTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/exploration/mv/MaterializedViewUtilsTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/EliminateConstHashJoinConditionTest.java
  regression-test/data/nereids_p0/runtime_filter/runtime_filter.out
  regression-test/data/nereids_rules_p0/infer_predicate/extend_infer_equal_predicate.out
  regression-test/data/nereids_rules_p0/infer_predicate/pull_up_predicate_literal.out
  regression-test/data/nereids_rules_p0/infer_predicate/pull_up_predicate_set_op.out
  regression-test/data/nereids_rules_p0/pkfk/eliminate_inner.out
  regression-test/suites/nereids_p0/cte/test_cte_filter_pushdown.groovy
  regression-test/suites/nereids_rules_p0/cte/test_cte_filter_pushdown.groovy
  regression-test/suites/nereids_rules_p0/filter_push_down/push_filter_through.groovy
  regression-test/suites/nereids_rules_p0/infer_predicate/pull_up_predicate_literal.groovy
  regression-test/suites/nereids_rules_p0/mv/agg_optimize_when_uniform/agg_optimize_when_uniform.groovy
  regression-test/suites/nereids_rules_p0/mv/agg_with_roll_up/aggregate_with_roll_up.groovy
  regression-test/suites/nereids_rules_p0/mv/agg_without_roll_up/aggregate_without_roll_up.groovy
  regression-test/suites/nereids_rules_p0/mv/dimension/dimension_1.groovy
  regression-test/suites/nereids_rules_p0/mv/dimension/dimension_2_full_join.groovy
  regression-test/suites/nereids_rules_p0/mv/dimension/dimension_2_inner_join.groovy
  regression-test/suites/nereids_rules_p0/mv/dimension/dimension_2_left_join.groovy
  regression-test/suites/nereids_rules_p0/mv/dimension/dimension_2_right_join.groovy
  regression-test/suites/nereids_rules_p0/mv/join/dphyp_inner/inner_join_dphyp.groovy
  regression-test/suites/nereids_rules_p0/mv/join/dphyp_outer/outer_join_dphyp.groovy
  regression-test/suites/nereids_rules_p0/mv/join/inner/inner_join.groovy
  regression-test/suites/nereids_rules_p0/mv/join/left_outer/outer_join.groovy
  regression-test/suites/nereids_rules_p0/mv/join_infer_derive/inner_join_infer_and_derive.groovy
  regression-test/suites/nereids_rules_p0/mv/nested/nested_materialized_view.groovy
  regression-test/suites/nereids_rules_p0/predicate_infer/infer_predicate.groovy
Labels: approved, reviewed

#49418 [feat](test)add some be ut for orc/parquet reader
  be/src/vec/exec/format/orc/vorc_reader.cpp
  be/src/vec/exec/format/parquet/parquet_column_convert.cpp
  be/src/vec/exec/format/parquet/parquet_column_convert.h
  be/test/vec/exec/column_type_convert_test.cpp
  be/test/vec/exec/orc/orc_convert_dict_test.cpp
  be/test/vec/exec/orc/orc_convert_to_orc_literal_test.cpp
  be/test/vec/exec/orc/orc_file_reader_test.cpp
  be/test/vec/exec/orc/orc_memory_stream_test.h
  be/test/vec/exec/orc/orc_reader_fill_data_test.cpp
  be/test/vec/exec/orc/orc_reader_init_column_test.cpp
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#49702 [Fix](case) Fix cold data compaction fault injection case
  be/src/olap/tablet.cpp
Labels: approved, reviewed, dev/3.0.x

#49630 [Chore](gutil) remove all unused include integral_types.h
  be/src/agent/agent_server.cpp
  be/src/agent/utils.cpp
  be/src/cloud/cloud_schema_change_job.cpp
  be/src/common/dwarf.cpp
  be/src/exec/es/es_scroll_parser.cpp
  be/src/exprs/bitmapfilter_predicate.h
  be/src/gutil/strings/util.h
  be/src/io/fs/hdfs_file_system.cpp
  be/src/olap/delta_writer_v2.cpp
  be/src/olap/memtable.h
  be/src/olap/memtable_writer.h
  be/src/olap/rowset/beta_rowset_writer_v2.cpp
  be/src/olap/rowset/segment_v2/bloom_filter.h
  be/src/olap/rowset/segment_v2/inverted_index/query_v2/roaring_query.h
  be/src/olap/rowset/segment_v2/inverted_index_reader.cpp
  be/src/olap/schema_change.cpp
  be/src/olap/tablet_manager.cpp
  be/src/olap/tablet_meta.cpp
  be/src/olap/task/index_builder.cpp
  be/src/pipeline/dependency.h
  be/src/pipeline/exec/data_queue.cpp
  be/src/runtime/cache/result_cache.h
  be/src/runtime/cache/result_node.h
  be/src/runtime/define_primitive_type.h
  be/src/runtime/exec_env_init.cpp
  be/src/runtime/load_stream_writer.cpp
  be/src/runtime/runtime_query_statistics_mgr.h
  be/src/runtime/runtime_state.h
  be/src/service/internal_service.cpp
  be/src/service/point_query_executor.cpp
  be/src/service/point_query_executor.h
  be/src/util/bitmap_value.h
  be/src/util/memcpy_inlined.h
  be/src/util/runtime_profile.cpp
  be/src/util/zlib.cpp
  be/src/vec/aggregate_functions/aggregate_function_retention.h
  be/src/vec/aggregate_functions/aggregate_function_window.h
  be/src/vec/columns/column.h
  be/src/vec/columns/column_decimal.h
  be/src/vec/columns/column_string.h
  be/src/vec/columns/column_vector.h
  be/src/vec/common/custom_allocator.h
  be/src/vec/common/hash_table/hash_map_context.h
  be/src/vec/common/hash_table/hash_map_util.h
  be/src/vec/exec/format/parquet/schema_desc.h
  be/src/vec/exprs/vbitmap_predicate.cpp
  be/src/vec/exprs/vcompound_pred.h
  be/src/vec/functions/function_bit_count.cpp
  be/src/vec/functions/function_bit_shift.cpp
  be/src/vec/functions/function_case.h
  be/src/vec/functions/functions_logical.cpp
  be/src/vec/functions/multiply.cpp
  be/src/vec/olap/olap_data_convertor.h
  be/src/vec/sink/vmysql_result_writer.cpp
  be/src/vec/sink/vrow_distribution.h
  be/test/olap/storage_types_test.cpp
  be/test/runtime/cache/partition_cache_test.cpp
  be/test/vec/function/function_bitmap_test.cpp
  be/test/vec/function/function_string_test.cpp
Labels: approved, reviewed

#49677 [improve](thrift) Config thrift_max_message_size for THREAD_POOL and …
  be/src/util/thrift_server.cpp
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#49678 [improve](thrift) Config thrift_max_message_size for FE SIMPLE and TH…
  fe/fe-core/src/main/java/org/apache/doris/common/ThriftServer.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#49674 [fix](test) Complete the missing db name in check_before_quit test
  regression-test/suites/check_before_quit/check_before_quit.groovy
Labels: approved, reviewed, dev/3.0.x

#49689 [Chore](runtime-filter) enlarge default value of runtimeBloomFilterMaxSize, runtimeFilterMaxInNum
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
Labels: approved, reviewed

#47282 [Fix](Compaction) Cumulative Points Not Incrementing After Delete Operation
  be/src/cloud/cloud_cumulative_compaction.cpp
  be/src/cloud/cloud_cumulative_compaction_policy.cpp
  be/test/cloud/cloud_cumulative_compaction_policy_test.cpp
  regression-test/data/fault_injection_p0/test_first_delete_compaction.out
  regression-test/suites/fault_injection_p0/test_first_delete_compaction.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#49664 [Enhancement] (nereids)implement unlockTablesCommand in nereids
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PlanType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/UnlockTablesCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/CommandVisitor.java
  regression-test/suites/nereids_p0/test_unlock_tables_command.groovy
Labels: approved, reviewed

#49575 [fix](Nereids) fix regression framework compare issue and fix code point count
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/executable/NumericArithmetic.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/executable/StringArithmetic.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/expression/FoldConstantTest.java
  regression-test/data/query_p0/sql_functions/string_functions/test_string_function.out
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
  regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_cast.groovy
  regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_date_arithmatic.groovy
  regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_numeric_arithmatic.groovy
  regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy
Labels: approved, reviewed, p0_w, dev/2.1.x, dev/3.0.x

#48759 [Enhancement](Compaction) Add cumulative compaction delay strategy
  be/src/cloud/cloud_compaction_action.cpp
  be/src/cloud/cloud_cumulative_compaction.h
  be/src/cloud/cloud_storage_engine.cpp
  be/src/cloud/cloud_storage_engine.h
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/http/action/compaction_action.cpp
  be/src/olap/compaction.cpp
  be/src/olap/compaction.h
  be/src/olap/olap_server.cpp
  be/src/olap/storage_engine.cpp
  be/src/olap/storage_engine.h
  be/src/util/threadpool.cpp
  be/test/olap/cumulative_compaction_test.cpp
  regression-test/pipeline/cloud_p0/conf/be_custom.conf
  regression-test/pipeline/cloud_p1/conf/be_custom.conf
  regression-test/pipeline/p0/conf/be.conf
  regression-test/pipeline/p1/conf/be.conf
  regression-test/suites/fault_injection_p0/test_cumu_compaction_delay_fault_injection.groovy
Labels: approved, reviewed, p0_b, dev/3.0.x

#49638 [refactor](terminate) add terminate interface
  be/src/pipeline/dependency.cpp
  be/src/pipeline/exec/hashjoin_build_sink.cpp
  be/src/pipeline/exec/hashjoin_build_sink.h
  be/src/pipeline/exec/operator.cpp
  be/src/pipeline/exec/operator.h
  be/src/pipeline/exec/partitioned_hash_join_sink_operator.cpp
  be/src/pipeline/exec/set_probe_sink_operator.cpp
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/pipeline/pipeline_task.cpp
  be/src/pipeline/pipeline_task.h
  be/src/runtime/runtime_state.h
  be/src/runtime_filter/runtime_filter_producer_helper.cpp
  be/src/runtime_filter/runtime_filter_producer_helper.h
  be/src/runtime_filter/runtime_filter_producer_helper_cross.h
  be/src/vec/exprs/vexpr.cpp
  be/test/pipeline/operator/partitioned_aggregation_test_helper.cpp
  be/test/pipeline/operator/partitioned_hash_join_test_helper.cpp
  be/test/pipeline/operator/spill_sort_test_helper.cpp
  be/test/pipeline/pipeline_test.cpp
  be/test/runtime_filter/runtime_filter_consumer_helper_test.cpp
  be/test/runtime_filter/runtime_filter_producer_helper_cross_test.cpp
  be/test/runtime_filter/runtime_filter_producer_helper_test.cpp
Labels: approved, reviewed

#49645 [fix](paimon) Covert Paimon DeletionFile Path to StoragePath in fe
  fe/fe-core/src/main/java/org/apache/doris/datasource/paimon/source/PaimonScanNode.java
  regression-test/data/external_table_p0/paimon/test_paimon_deletion_vector_oss.out
  regression-test/suites/external_table_p0/paimon/test_paimon_deletion_vector_oss.groovy
Labels: approved, reviewed, usercase, dev/2.1.x, dev/3.0.x

#49743 [Bug](runtime-filter) fix error of not found merge addr
  be/src/runtime/fragment_mgr.cpp
Labels: approved, reviewed

#49147 Fix inaccurate memory size for metadata
  be/src/olap/metadata_adder.h
  be/src/olap/rowset/segment_v2/index_page.cpp
  be/src/olap/rowset/segment_v2/index_page.h
  be/src/olap/rowset/segment_v2/ordinal_page_index.cpp
  be/src/olap/rowset/segment_v2/ordinal_page_index.h
  be/src/olap/tablet_schema.cpp
  be/src/olap/tablet_schema.h
  be/test/olap/metadata_adder_test.cpp
Labels: approved, reviewed

#49737 [fix](function) check return type is nullptr in FunctionBasePtr::build
  be/src/vec/functions/array/function_array_cum_sum.cpp
  be/src/vec/functions/array/function_array_difference.h
  be/src/vec/functions/array/function_array_element.h
  be/src/vec/functions/array/function_array_enumerate_uniq.cpp
  be/src/vec/functions/function.h
  be/test/vec/function/simple_function_factory_test.cpp
Labels: approved, reviewed, p0_c, dev/2.1.x, dev/3.0.x

#49568 [fix](jdbc catalog) Fix connection leak in PostgreSQL JDBC client
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/client/JdbcPostgreSQLClient.java
Labels: approved, reviewed, p0_b, dev/3.0.x

#49747 branch-3.0: [fix](lock) Fix ~VDataStreamMgr lock _receiver_map #48057
  be/src/vec/runtime/vdata_stream_mgr.cpp
Labels: approved, reviewed

#49489 [opt](iceberg)Optimize the batch mode conditions for Iceberg.
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/IcebergUtils.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/source/IcebergScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/iceberg/IcebergUtilsTest.java
  regression-test/suites/external_table_p0/iceberg/test_iceberg_filter.groovy
  regression-test/suites/external_table_p0/iceberg/test_iceberg_optimize_count.groovy
Labels: approved, reviewed, dev/2.1.x-experimental, dev/3.0.x-experimental

#49459 [fix](auth)Fixed the issue of not adding escape characters in the regular code, which allowed usernames to use colons
  fe/fe-core/src/main/java/org/apache/doris/common/FeNameFormat.java
  fe/fe-core/src/test/java/org/apache/doris/common/FeNameFormatTest.java
Labels: approved, reviewed, p0_w, dev/2.1.x, dev/3.0.x

#49701 [fix](spill) Finish dependency of join sink operator was released early
  be/src/pipeline/exec/partitioned_hash_join_probe_operator.cpp
  be/src/pipeline/exec/partitioned_hash_join_probe_operator.h
  be/src/pipeline/exec/partitioned_hash_join_sink_operator.cpp
  be/src/pipeline/exec/partitioned_hash_join_sink_operator.h
  be/test/pipeline/operator/partitioned_hash_join_probe_operator_test.cpp
  be/test/pipeline/operator/partitioned_hash_join_sink_operator_test.cpp
Labels: approved, reviewed, p0_c

#49753 [refactor](pipeline) Re-construct ownership of pipeline components
  be/src/pipeline/dependency.cpp
  be/src/pipeline/dependency.h
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/pipeline/pipeline_fragment_context.h
  be/src/pipeline/pipeline_task.cpp
  be/src/pipeline/pipeline_task.h
  be/src/pipeline/task_queue.cpp
  be/src/pipeline/task_queue.h
  be/src/pipeline/task_scheduler.cpp
  be/src/pipeline/task_scheduler.h
  be/test/pipeline/dummy_task_queue.h
  be/test/pipeline/pipeline_test.cpp
Labels: approved, reviewed, dev/3.0.x

#49654 [fix](thirdparty)Fix uuid_string_t compilation issue with newer XCode SDKs on macOS
  thirdparty/patches/brpc-uuid-string.patch
Labels: approved, reviewed

#49483 [feature](cast) support time cast to date/datetime
  be/src/vec/core/call_on_type_index.h
  be/src/vec/functions/function_cast.h
  be/src/vec/runtime/time_value.h
  be/src/vec/runtime/vdatetime_value.h
  be/test/runtime/time_value_test.cpp
  be/test/vec/function/function_time_cast_to_date_test.cpp
  fe/fe-common/src/main/java/org/apache/doris/catalog/PrimitiveType.java
  regression-test/suites/correctness/test_cast_time_to_datetime.groovy
Labels: approved, reviewed

#49711 [Fix]fix report query statistics to FE cores
  be/src/runtime/runtime_query_statistics_mgr.cpp
Labels: approved, reviewed

#49233 [improve](restore) Link existing rowset files bidirectionally
  be/src/runtime/snapshot_loader.cpp
  be/src/runtime/snapshot_loader.h
  be/test/runtime/snapshot_loader_test.cpp
Labels: approved, reviewed, dev/3.0.x

#49765 [chore](ut) fix run be ut build script
  run-be-ut.sh
Labels: approved, reviewed

#49764 [fix](test) Adapta case to multi FE node test
  regression-test/suites/load_p0/routine_load/test_routin_load_abnormal_job_monitor.groovy
Labels: approved, reviewed, dev/3.0.x

#49348 [fix](auth)Ignore replay edit log error of auth
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/Auth.java
Labels: approved, reviewed, usercase, dev/2.1.x, dev/3.0.x

#49754 [fix](oss) the write to hive table on oss-hdfs may fail
  fe/fe-core/src/main/java/org/apache/doris/common/util/LocationPath.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HiveMetaStoreCache.java
  fe/fe-core/src/main/java/org/apache/doris/fs/remote/SwitchingFileSystem.java
  fe/fe-core/src/test/java/org/apache/doris/common/util/LocationPathTest.java
Labels: approved, reviewed, usercase, dev/2.1.x, dev/3.0.x

#49679 [Feature](runtime-filter) support rf on set operator: be part
  be/src/pipeline/exec/set_sink_operator.cpp
  be/src/pipeline/exec/set_sink_operator.h
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime_filter/runtime_filter_producer_helper_set.h
Labels: approved, reviewed

#49119 [feature](functions) impl function next_day
  be/src/vec/functions/function_date_or_datetime_computation.cpp
  be/src/vec/functions/function_date_or_datetime_computation.h
  be/test/vec/function/function_time_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinScalarFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/executable/DateTimeExtractAndTransform.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/NextDay.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/ScalarFunctionVisitor.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/expression/FoldConstantTest.java
  regression-test/data/query_p0/sql_functions/string_functions/test_next_day.out
  regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_date_arithmatic.groovy
  regression-test/suites/query_p0/sql_functions/string_functions/test_next_day.groovy
Labels: approved, reviewed, kind/need-document, dev/2.1.x, dev/3.0.x

#49037 [fix](Parquet) add a memory tracker to parquet meta
  be/src/runtime/exec_env.h
  be/src/runtime/exec_env_init.cpp
  be/src/vec/exec/format/parquet/parquet_thrift_util.h
  be/src/vec/exec/format/parquet/vparquet_file_metadata.cpp
  be/src/vec/exec/format/parquet/vparquet_file_metadata.h
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#49710 [Fix](cloud-mow) Check partition's version to avoid wrongly update visible versions' delete bitmaps
  be/src/cloud/cloud_engine_calc_delete_bitmap_task.cpp
  be/src/cloud/cloud_meta_mgr.cpp
  be/src/cloud/cloud_meta_mgr.h
  be/src/cloud/cloud_tablet.cpp
  be/src/cloud/cloud_tablet.h
  be/src/olap/base_tablet.cpp
  be/src/olap/base_tablet.h
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
  cloud/src/meta-service/meta_service.cpp
  cloud/src/meta-service/meta_service_txn.cpp
  cloud/test/meta_service_test.cpp
  gensrc/proto/cloud.proto
Labels: approved, reviewed, p0_w, dev/3.0.x

#48946 [case](mtmv)add case for insert overwrite of mtmv force drop partition
  regression-test/suites/mtmv_p0/test_iot_recycle_mtmv.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x, p0_test

#49415 [opt](nereids) catch all exceptions in StatsCalculator
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/ExpressionEstimation.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/StatsCalculator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/GroupPlan.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/ColumnStatistic.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/stats/ExpressionEstimationTest.java
Labels: approved, reviewed, p0_b, dev/2.1.x, dev/3.0.x

#48887 [fix](mtmv) Fix materialized rewrite oom when the num of relation mapping is too large
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewRule.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/mapping/Mapping.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/mapping/RelationMapping.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/mv/RelationMappingTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/exploration/mv/HyperGraphAggTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/exploration/mv/MappingTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/sqltest/SqlTestBase.java
  regression-test/suites/nereids_rules_p0/mv/many_self_join/many_self_join.groovy
Labels: approved, reviewed, p0_b, dev/2.1.x, dev/3.0.x

#49804 [Chore](catch) add catch exception on sync_filter_size
  be/src/runtime/fragment_mgr.cpp
Labels: approved, reviewed

#49794 branch-2.1:[fix](auth)Delete from should not check select_priv
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/DeleteFromCommand.java
  regression-test/suites/auth_call/test_dml_delete_table_auth.groovy
Labels: approved, reviewed

#49808 branch-3.0: [opt](identifer) let unicode format as a superset of latin format #48078
  fe/fe-core/src/main/java/org/apache/doris/common/FeNameFormat.java
  fe/fe-core/src/test/java/org/apache/doris/common/FeNameFormatTest.java
Labels: approved, reviewed

#49810 [Bug][function] fix the string cast jsonb cause null map have not init value
  be/src/vec/functions/function_cast.h
  regression-test/data/query_p0/sql_functions/json_functions/test_json_function.out
  regression-test/suites/query_p0/sql_functions/json_functions/test_json_function.groovy
Labels: kind/fix, approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x

#49791 [opt](match) add debug point to error log when enable debug point
  be/src/vec/functions/match.cpp
Labels: approved, reviewed

#49691 [enhancement](thriftconnection) change default timeout when user not set
  be/src/runtime/client_cache.cpp
Labels: approved, reviewed

#49159 [fix](variant) building index on the variant column is prohibited
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
  regression-test/suites/variant_p0/with_index/var_index.groovy
Labels: approved, reviewed, kind/behavior-changed, dev/2.1.x

#49811 [Chore](dep) upgrade libdivide from 5.0 to 5.2
  thirdparty/CHANGELOG.md
  thirdparty/vars.sh
Labels: approved, reviewed

#49739 [Bug](runtime-filter) add lock for RuntimeFilterConsumer::acquire_expr/signal to avoid mult…
  be/src/pipeline/exec/hashjoin_build_sink.cpp
  be/src/runtime_filter/runtime_filter_consumer.cpp
  be/src/runtime_filter/runtime_filter_consumer.h
  be/test/io/fs/s3_obj_storage_client_test.cpp
  be/test/pipeline/operator/partitioned_hash_join_sink_operator_test.cpp
  be/test/runtime_filter/runtime_filter_consumer_test.cpp
Labels: approved, reviewed

#49261 branch-3.0: [fix](mtmv) Fix collecting mv candidates when dml controlled by enable_dml_materialized_view_rewrite switch #48374
  fe/fe-core/src/main/java/org/apache/doris/nereids/CascadesContext.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/StatementContext.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/TableCollectAndHookInitializer.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/AddInitMaterializationHook.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/CollectRelation.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
Labels: approved, reviewed

#48695 [Enhancement] Support some spatial functions
  be/src/geo/geo_types.cpp
  be/src/geo/geo_types.h
  be/src/vec/functions/functions_geo.cpp
  be/test/geo/geo_types_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinScalarFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/StDisjoint.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/StIntersects.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/StTouches.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/ScalarFunctionVisitor.java
  regression-test/data/nereids_p0/sql_functions/spatial_functions/test_gis_function.out
  regression-test/data/query_p0/sql_functions/spatial_functions/test_gis_function.out
  regression-test/suites/nereids_p0/sql_functions/spatial_functions/test_gis_function.groovy
  regression-test/suites/query_p0/sql_functions/spatial_functions/test_gis_function.groovy
Labels: approved, reviewed

#49704 [chore](log) Fix typo when meta-service checks priority_networks
  cloud/src/common/network_util.cpp
Labels: approved, reviewed, dev/3.0.x

#49813 [chore](log) Standardize S3 failure log formats to enable critical operation monitoring
  be/src/io/fs/s3_file_reader.cpp
  be/src/io/fs/s3_file_system.cpp
  be/src/io/fs/s3_file_writer.cpp
Labels: approved, reviewed, p0_b, dev/3.0.x

#49036 [Fix](Serde) Support hive compatible output format
  be/src/vec/data_types/serde/data_type_array_serde.cpp
  be/src/vec/data_types/serde/data_type_map_serde.cpp
  be/src/vec/data_types/serde/data_type_number_serde.cpp
  be/src/vec/data_types/serde/data_type_serde.h
  be/src/vec/data_types/serde/data_type_struct_serde.cpp
  be/src/vec/sink/vmysql_result_writer.cpp
  fe/fe-core/src/main/java/org/apache/doris/nereids/NereidsPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  gensrc/thrift/PaloInternalService.thrift
  regression-test/data/datatype_p0/serde/test_serde_dialect_hive.out
  regression-test/suites/datatype_p0/serde/test_serde_dialect_hive.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#48854 [fix](columns) fix bug found by UT and add regression test (#48554)
  be/src/vec/columns/column_decimal.cpp
  be/src/vec/columns/column_string.cpp
  be/src/vec/columns/column_string.h
  be/src/vec/columns/columns_number.h
  be/src/vec/core/field.cpp
  be/src/vec/data_types/serde/data_type_decimal_serde.cpp
  regression-test/data/query_p0/sort/heap_sort.csv
  regression-test/data/query_p0/sort/heap_sort.out
  regression-test/suites/query_p0/sort/heap_sort.groovy
Labels: p0_b

#49082 [fix](opt)fix create expr tree to avoid the dangling reference
  be/src/vec/exprs/vexpr.cpp
  regression-test/data/correctness/test_expression_tree_reconstruction.out
  regression-test/suites/correctness/test_expression_tree_reconstruction.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#49763 [feature](function) upper lower support utf8 input
  be/cmake/thirdparty.cmake
  be/src/vec/functions/function_string.cpp
  be/test/vec/function/function_string_test.cpp
  dist/LICENSE-dist.txt
  dist/licenses/LICENSE-icu.txt
  regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy
  thirdparty/CHANGELOG.md
  thirdparty/build-thirdparty.sh
  thirdparty/vars.sh
Labels: usercase

#49721 [fix](gson) Missing the serialization of the partition's storage policy
  fe/fe-core/src/main/java/org/apache/doris/catalog/PartitionInfo.java
  regression-test/suites/partition_p0/test_partition_serialized_sp.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#48993 [Enhancement] (nereids) implement transactionBegin/Commit/RollbackCommand in nereids
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PlanType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/TransactionBeginCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/TransactionCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/TransactionCommitCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/TransactionRollbackCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/CommandVisitor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  regression-test/suites/nereids_p0/test_transaction.groovy
Labels: approved, reviewed

#48830 [fix](mtmv)fix mtmv may have repeat tasks after canceled
  fe/fe-core/src/main/java/org/apache/doris/job/extensions/insert/InsertTask.java
  fe/fe-core/src/main/java/org/apache/doris/job/extensions/mtmv/MTMVTask.java
  fe/fe-core/src/main/java/org/apache/doris/job/task/AbstractTask.java
  fe/fe-core/src/main/java/org/apache/doris/job/task/Task.java
  regression-test/suites/mtmv_p0/test_task_mtmv.groovy
Labels: approved, reviewed, dev/3.1.x

#49826 [bugfix](becore) be core when exist elegantly
  be/src/runtime/exec_env_init.cpp
  be/src/vec/spill/spill_stream_manager.h
Labels: approved, reviewed

#49820 [UT](pipeline) Add UT cases for pipeline task
  be/src/pipeline/exec/operator.cpp
  be/src/pipeline/exec/operator.h
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/pipeline/pipeline_task.cpp
  be/src/pipeline/pipeline_task.h
  be/test/pipeline/pipeline_task_test.cpp
  be/test/pipeline/pipeline_test.cpp
Labels: approved, reviewed

#49843 [enhancement](case) add cases for mow table load empty file
  regression-test/data/load_p0/stream_load/test_stream_load_empty_file.out
  regression-test/suites/load_p0/stream_load/test_stream_load_empty_file.groovy
Labels: approved, reviewed

#49839 [chore](memcmp)Remove the template parameter in memcmp_small_allow_overflow15
  be/src/vec/common/memcmp_small.h
  be/src/vec/functions/function_string.h
Labels: approved, reviewed

#49783 [opt](UI) Optimization for frontend UI
  fe/fe-core/src/main/java/org/apache/doris/httpv2/controller/QueryProfileController.java
  ui/src/api/api.ts
  ui/src/pages/query-profile/index.tsx
Labels: approved, reviewed

#49842 [fix](multi-catalog) Fix multi-thread issue in hive/iceberg writer commit meta-info to fe.
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/runtime_state.h
  be/src/vec/sink/writer/iceberg/viceberg_partition_writer.cpp
  be/src/vec/sink/writer/vhive_partition_writer.cpp
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#49718 [opt](orc-reader)Turn on late materialization of orc complex types.
  be/src/vec/exec/format/orc/vorc_reader.cpp
  docker/thirdparties/docker-compose/hive/scripts/data/multi_catalog/orc_nested_types/create_table.hql
  docker/thirdparties/docker-compose/hive/scripts/data/multi_catalog/orc_nested_types/data.tar.gz
  docker/thirdparties/docker-compose/hive/scripts/data/multi_catalog/orc_nested_types/run.sh
  regression-test/data/external_table_p0/hive/test_orc_nested_types.out
  regression-test/suites/external_table_p0/hive/test_orc_nested_types.groovy
Labels: approved, reviewed, dev/2.1.x-experimental, dev/3.0.x-experimental

#49823 [fix] (inverted index) Disallow variant columns from using inverted index format v1
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateTableStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/IndexDef.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/CreateTableInfo.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/IndexDefinition.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/IndexDefTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/commands/IndexDefinitionTest.java
  regression-test/suites/compaction/test_single_compaction_with_variant_inverted_index.groovy
  regression-test/suites/inverted_index_p0/load/test_insert.groovy
  regression-test/suites/inverted_index_p0/load/test_stream_load.groovy
  regression-test/suites/inverted_index_p0/test_show_nested_index_file_http_action_with_variant.groovy
  regression-test/suites/inverted_index_p2/test_variant_index_format_v1.groovy
  regression-test/suites/load_p2/test_single_replica_load.groovy
  regression-test/suites/variant_p0/with_index/test_array_contains_with_inverted_index.groovy
  regression-test/suites/variant_p0/with_index/test_array_index_write.groovy
  regression-test/suites/variant_p0/with_index/test_array_inverted_index_profile.groovy
  regression-test/suites/variant_p0/with_index/var_index.groovy
Labels: approved, reviewed, dev/3.0.x

#49278 [Test](nereids) Add ut for alter column/table stats command in nereids
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/AlterColumnStatsCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/AlterTableStatsCommand.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/commands/AlterColumnStatsCommandTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/commands/AlterTableStatsCommandTest.java
Labels: approved, reviewed

#49860 [chore](log) change PointQueryExecutor log to VLOG_DEBUG
  be/src/service/point_query_executor.h
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#47925 [enhance](auth)ranger support storage vault and compute group
  fe/fe-core/src/main/java/org/apache/doris/catalog/authorizer/ranger/doris/DorisAccessType.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/authorizer/ranger/doris/DorisObjectType.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/authorizer/ranger/doris/RangerDorisAccessController.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/authorizer/ranger/doris/RangerDorisResource.java
  fe/fe-core/src/test/java/org/apache/doris/mysql/privilege/RangerTest.java
Labels: approved, reviewed

#49793 [fix](cloud) fix get_or_set emptry <offset, cell> map
  be/src/io/cache/block_file_cache.cpp
  be/test/io/cache/block_file_cache_test.cpp
Labels: approved, reviewed, p0_c, dev/3.0.x

#49668 [opt](test case) Opt adaptive_pipeline_task_serial_read_on_limit in multiple be env
  regression-test/suites/query_profile/adaptive_pipeline_task_serial_read_on_limit.groovy
Labels: approved, reviewed

#49777 [refactor](profile) Refactor of RuntimeFilter profile
  be/src/exec/olap_common.h
  be/src/olap/bitmap_filter_predicate.h
  be/src/olap/column_predicate.h
  be/src/olap/comparison_predicate.h
  be/src/olap/filter_olap_param.h
  be/src/olap/olap_common.h
  be/src/olap/rowset/segment_v2/segment_iterator.cpp
  be/src/olap/tablet_reader.cpp
  be/src/pipeline/exec/datagen_operator.cpp
  be/src/pipeline/exec/multi_cast_data_stream_source.cpp
  be/src/pipeline/exec/olap_scan_operator.cpp
  be/src/pipeline/exec/olap_scan_operator.h
  be/src/pipeline/exec/scan_operator.cpp
  be/src/runtime/runtime_state.cpp
  be/src/runtime/runtime_state.h
  be/src/runtime_filter/runtime_filter_consumer.cpp
  be/src/runtime_filter/runtime_filter_consumer.h
  be/src/runtime_filter/runtime_filter_consumer_helper.cpp
  be/src/runtime_filter/runtime_filter_consumer_helper.h
  be/src/runtime_filter/runtime_filter_mgr.cpp
  be/src/runtime_filter/runtime_filter_mgr.h
  be/src/util/runtime_profile.cpp
  be/src/util/runtime_profile.h
  be/src/vec/exec/scan/olap_scanner.cpp
  be/src/vec/exprs/vruntimefilter_wrapper.cpp
  be/src/vec/exprs/vruntimefilter_wrapper.h
  be/test/runtime_filter/runtime_filter_consumer_helper_test.cpp
  be/test/runtime_filter/runtime_filter_consumer_test.cpp
  be/test/runtime_filter/runtime_filter_mgr_test.cpp
  be/test/runtime_filter/runtime_filter_producer_test.cpp
  be/test/util/runtime_profile_counter_tree_node_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/common/profile/Counter.java
  fe/fe-core/src/main/java/org/apache/doris/common/profile/RuntimeProfile.java
  gensrc/thrift/RuntimeProfile.thrift
Labels: approved, reviewed

#49864 [Opt](profile) Add profile for `sync_rowsets`
  be/src/cloud/cloud_meta_mgr.cpp
  be/src/cloud/cloud_meta_mgr.h
  be/src/cloud/cloud_storage_engine.cpp
  be/src/cloud/cloud_storage_engine.h
  be/src/cloud/cloud_tablet.cpp
  be/src/cloud/cloud_tablet.h
  be/src/cloud/cloud_tablet_mgr.cpp
  be/src/cloud/cloud_tablet_mgr.h
  be/src/olap/storage_engine.cpp
  be/src/olap/storage_engine.h
  be/src/pipeline/exec/olap_scan_operator.cpp
  be/src/pipeline/exec/olap_scan_operator.h
  be/src/runtime/exec_env.cpp
  be/src/runtime/exec_env.h
Labels: approved, reviewed, usercase, dev/3.0.x

#49697 [fix](function) wrong result of arrays_overlap (#49403)
  be/src/vec/functions/array/function_arrays_overlap.h
  be/test/vec/function/function_arrays_overlap_test.cpp
  be/test/vec/function/function_test_util.cpp
  regression-test/data/inverted_index_p0/test_array_contains_with_inverted_index.out
  regression-test/data/query_p0/sql_functions/array_functions/test_array_functions.out
  regression-test/data/query_p0/sql_functions/array_functions/test_array_functions_by_literal.out
  regression-test/data/variant_p0/with_index/test_array_contains_with_inverted_index.out
Labels: usercase

#49819 Fix thrift core in asan mode
  be/src/runtime/runtime_query_statistics_mgr.cpp
Labels: reviewed

#49879 [regression-test](cases) un-drop table after tests
  regression-test/suites/alter_p2/test_alter_table_property.groovy
  regression-test/suites/bitmap_functions/test_bitmap_intersect.groovy
  regression-test/suites/data_model_p0/duplicate/test_duplicate_table.groovy
  regression-test/suites/data_model_p0/duplicate/test_duplicate_table_without_keys.groovy
  regression-test/suites/data_model_p0/unique/test_sequence_multi_same_key.groovy
  regression-test/suites/data_model_p0/unique/test_unique_bitmap.groovy
  regression-test/suites/data_model_p0/unique/test_unique_table.groovy
  regression-test/suites/datatype_p0/date/test_default_current_timestamp.groovy
  regression-test/suites/datatype_p0/ip/test_ip_crud.groovy
  regression-test/suites/demo_p0/streamLoad_action.groovy
  regression-test/suites/index_p0/test_bitmap_index.groovy
  regression-test/suites/internal_schema_p0/operate_internal_schema.groovy
  regression-test/suites/load_p0/stream_load/test_csv_split_line.groovy
  regression-test/suites/nereids_p0/aggregate/aggregate_count1.groovy
  regression-test/suites/nereids_p0/aggregate/aggregate_group_by_metric_type.groovy
  regression-test/suites/nereids_p0/aggregate/aggregate_grouping_function.groovy
  regression-test/suites/nereids_p0/aggregate/aggregate_having_grouping.groovy
  regression-test/suites/nereids_p0/aggregate/aggregate_output_null.groovy
  regression-test/suites/nereids_p0/datatype/test_datev1.groovy
  regression-test/suites/nereids_p0/datatype/test_decimalv2.groovy
  regression-test/suites/nereids_p0/sql_functions/conditional_functions/test_conditional_function.groovy
  regression-test/suites/nereids_p0/sql_functions/datetime_functions/test_date_or_datetime_computation_negative.groovy
  regression-test/suites/nereids_p0/sql_functions/json_function/test_query_json_array.groovy
  regression-test/suites/nereids_p0/sql_functions/json_function/test_query_json_insert.groovy
  regression-test/suites/nereids_p0/sql_functions/json_function/test_query_json_object.groovy
  regression-test/suites/nereids_p0/sql_functions/json_function/test_query_json_replace.groovy
  regression-test/suites/nereids_p0/sql_functions/json_function/test_query_json_set.groovy
  regression-test/suites/nereids_p0/sql_functions/string_functions/test_string_function_like_pushdown.groovy
  regression-test/suites/nereids_p0/test_data_type_marks.groovy
  regression-test/suites/nereids_p0/type_inference/test_largeint.groovy
  regression-test/suites/nereids_syntax_p0/group_bit.groovy
  regression-test/suites/nereids_syntax_p0/rollup/bitmap.groovy
  regression-test/suites/nereids_syntax_p0/rollup/date.groovy
  regression-test/suites/partition_p0/dynamic_partition/test_dynamic_partition_with_alter.groovy
  regression-test/suites/partition_p0/multi_partition/test_multi_partition.groovy
  regression-test/suites/partition_p0/multi_partition/test_range_partition.groovy
  regression-test/suites/query_p0/aggregate/aggregate_output_null.groovy
  regression-test/suites/query_p0/aggregate/array_agg.groovy
  regression-test/suites/query_p0/aggregate/map_agg_nested_insert_doris.groovy
  regression-test/suites/query_p0/aggregate/select_random_distributed_tbl.groovy
  regression-test/suites/query_p0/sql_functions/conditional_functions/test_ifnull.groovy
  regression-test/suites/query_p0/sql_functions/datetime_functions/test_from_iso8601_date.groovy
  regression-test/suites/query_p0/sql_functions/ip_functions/test_ipv4_to_ipv6_function.groovy
  regression-test/suites/query_p0/sql_functions/ip_functions/test_is_ip_string_functions.groovy
  regression-test/suites/query_p0/sql_functions/ip_functions/test_to_ip_functions.groovy
  regression-test/suites/query_p0/sql_functions/json_function/test_query_json_array.groovy
  regression-test/suites/query_p0/sql_functions/json_function/test_query_json_insert.groovy
  regression-test/suites/query_p0/sql_functions/json_function/test_query_json_replace.groovy
  regression-test/suites/query_p0/sql_functions/json_function/test_query_json_set.groovy
  regression-test/suites/query_p0/type_inference/test_largeint.groovy
  regression-test/suites/schema_change/test_alter_table_column_with_delete_drop_column_dup_key.groovy
  regression-test/suites/schema_change_p0/test_alter_table_column.groovy
  regression-test/suites/statistics/analyze_stats.groovy
  regression-test/suites/statistics/test_basic_statistics.groovy
  regression-test/suites/statistics/test_drop_stats_and_truncate.groovy
  regression-test/suites/statistics/test_partition_stats.groovy
Labels: approved, reviewed

#48023 [test](ranger) Init ranger case
  regression-test/data/ranger_p2/test_ranger_masking.out
  regression-test/data/ranger_p2/test_ranger_row_level_filter.out
  regression-test/framework/pom.xml
  regression-test/framework/src/main/groovy/org/apache/doris/regression/action/HttpCliAction.groovy
  regression-test/plugins/plugin_ranger.groovy
  regression-test/suites/ranger_p2/test_ranger_access_resource_catalog.groovy
  regression-test/suites/ranger_p2/test_ranger_access_resource_column.groovy
  regression-test/suites/ranger_p2/test_ranger_access_resource_database.groovy
  regression-test/suites/ranger_p2/test_ranger_access_resource_global.groovy
  regression-test/suites/ranger_p2/test_ranger_access_resource_resource.groovy
  regression-test/suites/ranger_p2/test_ranger_access_resource_table.groovy
  regression-test/suites/ranger_p2/test_ranger_access_resource_workload_group.groovy
  regression-test/suites/ranger_p2/test_ranger_access_role_resource_catalog.groovy
  regression-test/suites/ranger_p2/test_ranger_masking.groovy
  regression-test/suites/ranger_p2/test_ranger_row_level_filter.groovy
Labels: approved, reviewed, dev/3.0.x

#49876 [enhancement](memoryfailed) throw exception instead of log fatal during memory allocate failed
  be/src/vec/aggregate_functions/aggregate_function_sort.h
  be/src/vec/aggregate_functions/aggregate_function_window_funnel.h
Labels: approved, reviewed, usercase, p0_c, dev/2.1.x, dev/3.0.x

#49727 [improve](string) remove check for string type can't as distributed hash key
  fe/fe-core/src/main/java/org/apache/doris/analysis/HashDistributionDesc.java
  regression-test/data/ddl_p0/test_distributed_string_type.out
  regression-test/suites/ddl_p0/test_distributed_string_type.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#49838 [fix](runtime filter) Terminate runtime filter in partitioned hash join
  be/src/pipeline/exec/partitioned_hash_join_sink_operator.cpp
  be/src/pipeline/exec/partitioned_hash_join_sink_operator.h
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/pipeline/pipeline_task.cpp
  be/src/pipeline/pipeline_task.h
  be/src/runtime_filter/runtime_filter.cpp
  be/src/runtime_filter/runtime_filter.h
  regression-test/suites/query_p0/join/test_terminate.groovy
Labels: approved, reviewed

#49890 [fix] (inverted index) Disallow variant columns from using inverted index format v1 (#49823)
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeHandler.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateTableStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/IndexDef.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/CreateTableInfo.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/IndexDefinition.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/IndexDefTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/commands/IndexDefinitionTest.java
  regression-test/suites/compaction/test_single_compaction_with_variant_inverted_index.groovy
  regression-test/suites/inverted_index_p0/load/test_insert.groovy
  regression-test/suites/inverted_index_p0/load/test_stream_load.groovy
  regression-test/suites/inverted_index_p0/test_show_nested_index_file_http_action_with_variant.groovy
  regression-test/suites/inverted_index_p2/test_variant_index_format_v1.groovy
  regression-test/suites/load_p2/test_single_replica_load.groovy
  regression-test/suites/variant_p0/with_index/test_array_contains_with_inverted_index.groovy
  regression-test/suites/variant_p0/with_index/test_array_index_write.groovy
  regression-test/suites/variant_p0/with_index/test_array_inverted_index_profile.groovy
  regression-test/suites/variant_p0/with_index/var_index.groovy
Labels: approved, reviewed

#49885 [fix](iceberg)Fix the failure of creating a table in COS
  conf/fe.conf
Labels: approved, reviewed, dev/3.0.x, p0_test

#49392 [fix](function) support `json_extract_no_quotes` fucntion and `unhex_null` function
  be/src/vec/functions/function_json.cpp
  be/src/vec/functions/function_string.cpp
  be/src/vec/functions/function_totype.h
  be/test/vec/function/function_json_test.cpp
  be/test/vec/function/function_string_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinScalarFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/JsonExtractNoQuotes.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/UnhexNull.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/ScalarFunctionVisitor.java
  regression-test/data/query_p0/sql_functions/json_functions/test_json_function.out
  regression-test/data/query_p0/sql_functions/string_functions/test_string_function.out
  regression-test/suites/query_p0/sql_functions/json_functions/test_json_function.groovy
  regression-test/suites/query_p0/sql_functions/string_functions/test_string_function.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#49084 [feature](function) support format_round scala function
  be/src/vec/functions/function_string.cpp
  be/src/vec/functions/function_string.h
  be/test/vec/function/function_math_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinScalarFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/FormatRound.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/ScalarFunctionVisitor.java
  gensrc/script/doris_builtins_functions.py
  regression-test/data/query_p0/sql_functions/math_functions/test_format_round.out
  regression-test/suites/query_p0/sql_functions/math_functions/test_format_round.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#49886 [deps](jindofs) update jindofs from 6.3.4 to 6.8.2
  thirdparty/CHANGELOG.md
  thirdparty/vars.sh
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#49735 [regression-test](framework) add multi cluster result compare on cloud mode.
  regression-test/framework/src/main/groovy/org/apache/doris/regression/Config.groovy
  regression-test/framework/src/main/groovy/org/apache/doris/regression/ConfigOptions.groovy
  regression-test/plugins/plugin_multi_cluster.groovy
  regression-test/suites/check_before_quit/check_before_quit.groovy
Labels: approved, reviewed

#49878 [Fix]Fix some thrift core
  be/src/runtime/runtime_query_statistics_mgr.cpp
Labels: approved, reviewed

#49903 [deps](jindofs) build.sh support any version of jindofs
  build.sh
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#49825 [Fix](full compaction) Fix problems for full compaction
  be/src/cloud/cloud_full_compaction.cpp
  be/src/cloud/cloud_full_compaction.h
  be/src/olap/full_compaction.cpp
  be/src/olap/full_compaction.h
  be/src/olap/tablet_meta.cpp
  regression-test/data/fault_injection_p0/cloud/test_cloud_full_compaction_mow.out
  regression-test/data/fault_injection_p0/test_full_compaction_mow.out
  regression-test/suites/fault_injection_p0/cloud/test_cloud_full_compaction_mow.groovy
  regression-test/suites/fault_injection_p0/test_full_compaction_mow.groovy
Labels: approved, reviewed, p0_w, dev/2.1.x, dev/3.0.x

#49062 [fix](cloud-schema-change) Remove schema change job even if alter version < 2
  cloud/src/meta-service/meta_service_job.cpp
  regression-test/suites/compaction/test_base_compaction_after_sc.groovy
Labels: approved, reviewed, p0_b, dev/3.0.x

#49757 [fix](config) Turn on default value of `enable_cloud_tablet_report`
  be/src/cloud/config.cpp
Labels: approved, reviewed

#49928 Revert "[enhancement](hive)Initial support for Hive org.openx.data.jsonserde.JsonSerDe"
  be/src/vec/exec/format/json/new_json_reader.cpp
  be/src/vec/exec/format/json/new_json_reader.h
  docker/thirdparties/docker-compose/hive/scripts/auxlib/json-serde-1.3.9.tar.gz
  docker/thirdparties/docker-compose/hive/scripts/create_preinstalled_scripts/run76.hql
  docker/thirdparties/docker-compose/hive/scripts/hive-metastore.sh
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/json/openx_json/json_data_arrays_tb/1
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/json/openx_json/json_one_column_table/1
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/json/openx_json/json_table/1
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/json/openx_json/json_table/2
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/json/openx_json/scalar_to_array_tb/1
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HMSExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HiveMetaStoreClientHelper.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HiveProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/source/HiveScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  gensrc/thrift/PlanNodes.thrift
  regression-test/data/external_table_p0/hive/test_hive_openx_json.out
  regression-test/suites/external_table_p0/hive/test_hive_openx_json.groovy
Labels: reviewed

#49902 [refactor](minor) Delete unused RuntimeFilterDependency
  be/src/pipeline/dependency.cpp
  be/src/pipeline/dependency.h
  be/src/pipeline/exec/multi_cast_data_stream_source.h
  be/src/pipeline/exec/scan_operator.h
  be/src/pipeline/pipeline_task.h
  be/src/runtime_filter/runtime_filter_consumer.cpp
  be/src/runtime_filter/runtime_filter_consumer.h
  be/src/runtime_filter/runtime_filter_consumer_helper.cpp
  be/src/runtime_filter/runtime_filter_consumer_helper.h
  be/test/runtime_filter/runtime_filter_consumer_helper_test.cpp
Labels: approved, reviewed

#49846 [feature](function) support utf8 input in initcap
  be/src/vec/functions/function_string.cpp
  be/test/vec/function/function_string_test.cpp
  regression-test/data/function_p0/test_function_string.out
  regression-test/suites/function_p0/test_function_string.groovy
  regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_string_arithmatic.groovy
Labels: approved, reviewed, p0_w, dev/2.1.x, dev/3.0.x

#49914 [Chore](operator) move eos flag to specific operators
  be/src/pipeline/exec/hashjoin_build_sink.cpp
  be/src/pipeline/exec/operator.h
  be/src/pipeline/exec/partitioned_aggregation_sink_operator.h
  be/src/pipeline/exec/set_sink_operator.cpp
  be/src/pipeline/exec/spill_sort_sink_operator.h
Labels: approved, reviewed

#49871 [Chore](rpc) set and clean signal task id on some rpc thread
  be/src/service/internal_service.cpp
  be/src/service/internal_service.h
Labels: approved, reviewed

#49792 [refine](time) Support more time cast formats and refine some code.
  be/src/vec/functions/function_cast.h
  be/src/vec/runtime/time_value.h
  be/test/runtime/time_value_test.cpp
  regression-test/data/correctness/test_cast_as_time.out
  regression-test/data/nereids_p0/sql_functions/datetime_functions/test_date_function.out
  regression-test/data/nereids_syntax_p0/cast.out
  regression-test/suites/correctness/test_cast_as_time.groovy
Labels: approved, reviewed

#49874 [fix](doris compose) fix chose arrow_flight_sql_port
  docker/runtime/doris-compose/cluster.py
  docker/runtime/doris-compose/command.py
  docker/runtime/doris-compose/resource/init_be.sh
  docker/runtime/doris-compose/resource/init_fe.sh
Labels: approved, reviewed

#49939 [fix](timer) Fix task execution timer
  be/src/pipeline/pipeline_task.cpp
Labels: approved, reviewed, dev/3.0.x

#49802 [opt](nereids) do not throw exception in fold const rule
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/FoldConstantRule.java
Labels: approved, reviewed

#49940 [UT](pipeline) Test pipeline tasks
  be/src/pipeline/exec/operator.h
  be/src/pipeline/pipeline_task.cpp
  be/test/pipeline/pipeline_task_test.cpp
Labels: approved, reviewed

#49955 [fix](test) Fix ranger test cases
  regression-test/data/ranger_p2/test_ranger_masking.out
  regression-test/suites/ranger_p2/test_ranger_access_resource_catalog.groovy
  regression-test/suites/ranger_p2/test_ranger_access_resource_global.groovy
  regression-test/suites/ranger_p2/test_ranger_access_resource_resource.groovy
  regression-test/suites/ranger_p2/test_ranger_access_resource_workload_group.groovy
  regression-test/suites/ranger_p2/test_ranger_access_role_resource_catalog.groovy
Labels: approved, reviewed, dev/3.0.x

#48673 [enhance](mtmv)Only restrict MTMV to not allow concurrent insert overwrite execution
  fe/fe-core/src/main/java/org/apache/doris/insertoverwrite/InsertOverwriteManager.java
  fe/fe-core/src/main/java/org/apache/doris/insertoverwrite/InsertOverwriteUtil.java
  fe/fe-core/src/test/java/org/apache/doris/insertoverwrite/InsertOverwriteManagerTest.java
  fe/fe-core/src/test/java/org/apache/doris/insertoverwrite/InsertOverwriteUtilTest.java
  regression-test/suites/insert_overwrite_p1/test_iot_auto_detect_concurrent.groovy
Labels: approved, reviewed, kind/behavior-changed, usercase, dev/2.1.x, dev/3.0.x

#49872 [Refactor](lock) Remove SpinLock compeletely
  be/src/cloud/cloud_tablets_channel.cpp
  be/src/common/object_pool.h
  be/src/olap/delta_writer.h
  be/src/olap/delta_writer_v2.h
  be/src/olap/memtable_writer.cpp
  be/src/olap/memtable_writer.h
  be/src/olap/rowset/beta_rowset_writer.h
  be/src/olap/rowset/beta_rowset_writer_v2.h
  be/src/olap/rowset/segment_creator.h
  be/src/olap/rowset/vertical_beta_rowset_writer.cpp
  be/src/olap/storage_engine.cpp
  be/src/pipeline/exec/data_queue.h
  be/src/runtime/load_channel.cpp
  be/src/runtime/load_channel.h
  be/src/runtime/load_stream.h
  be/src/runtime/load_stream_writer.h
  be/src/runtime/tablets_channel.cpp
  be/src/runtime/tablets_channel.h
  be/src/util/lru_multi_cache.h
  be/src/util/lru_multi_cache.inline.h
  be/src/util/spinlock.h
  be/src/util/trace.h
  be/src/util/uuid_generator.h
  be/src/vec/sink/writer/vtablet_writer.cpp
  be/src/vec/sink/writer/vtablet_writer.h
  be/test/util/threadpool_test.cpp
  be/test/vec/exec/format/parquet/parquet_thrift_test.cpp
Labels: approved, reviewed

#49335 [Refactor](Exchange) do exchange sink buffer refactor
  be/src/pipeline/exec/exchange_sink_buffer.cpp
  be/src/pipeline/exec/exchange_sink_buffer.h
  be/src/pipeline/exec/exchange_sink_operator.cpp
  be/src/pipeline/exec/exchange_sink_operator.h
  be/src/vec/sink/vdata_stream_sender.cpp
  be/src/vec/sink/vdata_stream_sender.h
  be/test/pipeline/pipeline_test.cpp
  be/test/vec/exec/exchange_sink_test.cpp
  be/test/vec/exec/exchange_sink_test.h
Labels: approved, reviewed

#49929 [enhance](hive) support skip.header.line.count
  docker/thirdparties/docker-compose/hive/scripts/create_preinstalled_scripts/run76.hql
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/text/text_table_compressed_skip_header/000000_0.gz
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/text/text_table_normal_skip_header/000000_0
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HiveProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/source/HiveScanNode.java
  regression-test/data/external_table_p0/hive/test_text_skip_header.out
  regression-test/suites/external_table_p0/hive/test_text_skip_header.groovy
Labels: approved, reviewed, dev/3.0.x

#49942 branch-2.1: [fix](Nereids) cse extract wrong expression from lambda expressions (#49166)
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/CommonSubExpressionCollector.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/processor/post/CommonSubExpressionOpt.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/postprocess/CommonSubExpressionTest.java
  regression-test/suites/nereids_rules_p0/cse/cse.groovy
Labels: approved, reviewed

#49919 branch-2.1-pick: [Fix](full compaction) Fix problems for full compaction #49825
  be/src/olap/full_compaction.cpp
  be/src/olap/full_compaction.h
  regression-test/data/fault_injection_p0/test_full_compaction_mow.out
  regression-test/suites/fault_injection_p0/test_full_compaction_mow.groovy
Labels: approved, reviewed

#49969 [fix](UT) Fix UT failure
  be/src/pipeline/pipeline_task.h
  be/test/pipeline/pipeline_task_test.cpp
Labels: approved, reviewed

#49798 [opt](column) Optimize the execution of the append_data_by_selector function in ColumnNullable
  be/src/vec/columns/column_nullable.cpp
  be/src/vec/columns/column_nullable.h
  be/test/vec/columns/column_nullable_test.cpp
Labels: approved, reviewed

#49926 branch-3.0-pick: [Opt](profile) Add profile for `sync_rowsets` (#49864)
  be/src/cloud/cloud_meta_mgr.cpp
  be/src/cloud/cloud_meta_mgr.h
  be/src/cloud/cloud_storage_engine.cpp
  be/src/cloud/cloud_storage_engine.h
  be/src/cloud/cloud_tablet.cpp
  be/src/cloud/cloud_tablet.h
  be/src/cloud/cloud_tablet_mgr.cpp
  be/src/cloud/cloud_tablet_mgr.h
  be/src/olap/storage_engine.cpp
  be/src/olap/storage_engine.h
  be/src/pipeline/exec/olap_scan_operator.cpp
  be/src/pipeline/exec/olap_scan_operator.h
  be/src/runtime/exec_env.cpp
  be/src/runtime/exec_env.h
Labels: approved, reviewed

#49870 [feature](restore) Support force_replace different schema of view for restore
  fe/fe-core/src/main/java/org/apache/doris/backup/RestoreJob.java
  regression-test/suites/backup_restore/test_backup_restore_force_replace_diff_view.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#47554 [Enhancement] (nereids)implement CreateUserCommand in nereids
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/Auth.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PlanType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/CreateUserCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/CreateUserInfo.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/CommandVisitor.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/commands/CreateUserCommandTest.java
  regression-test/suites/ddl_p0/test_create_user_nereids.groovy
Labels: approved, reviewed

#49658 [feat](bi) support default_init_catalog user property for external catalog
  fe/fe-core/src/main/java/org/apache/doris/mysql/MysqlProto.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/Auth.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/CommonUserProperties.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/UserProperty.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/UserPropertyMgr.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/UserPropertyTest.java
  fe/fe-core/src/test/java/org/apache/doris/mysql/MysqlProtoTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/ResourceTagQueryTest.java
Labels: approved, reviewed

#49986 Revert "branch-2.1: [Fix](Serde) Support hive compatible output format #49036"
  be/src/vec/data_types/serde/data_type_array_serde.cpp
  be/src/vec/data_types/serde/data_type_map_serde.cpp
  be/src/vec/data_types/serde/data_type_number_serde.cpp
  be/src/vec/data_types/serde/data_type_serde.h
  be/src/vec/data_types/serde/data_type_struct_serde.cpp
  be/src/vec/sink/vmysql_result_writer.cpp
  fe/fe-core/src/main/java/org/apache/doris/nereids/NereidsPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  gensrc/thrift/PaloInternalService.thrift
  regression-test/data/datatype_p0/serde/test_serde_dialect_hive.out
  regression-test/suites/datatype_p0/serde/test_serde_dialect_hive.groovy
Labels: approved, reviewed

#49837 [Chore](runtime-filter) remove RuntimeFIlterParamsContext
  be/src/pipeline/exec/multi_cast_data_stream_source.cpp
  be/src/pipeline/exec/scan_operator.cpp
  be/src/pipeline/exec/scan_operator.h
  be/src/pipeline/pipeline_fragment_context.cpp
  be/src/pipeline/pipeline_fragment_context.h
  be/src/pipeline/pipeline_task.cpp
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/fragment_mgr.h
  be/src/runtime/query_context.cpp
  be/src/runtime/query_context.h
  be/src/runtime/runtime_state.cpp
  be/src/runtime_filter/runtime_filter.cpp
  be/src/runtime_filter/runtime_filter.h
  be/src/runtime_filter/runtime_filter_consumer.cpp
  be/src/runtime_filter/runtime_filter_consumer.h
  be/src/runtime_filter/runtime_filter_consumer_helper.cpp
  be/src/runtime_filter/runtime_filter_consumer_helper.h
  be/src/runtime_filter/runtime_filter_definitions.h
  be/src/runtime_filter/runtime_filter_merger.h
  be/src/runtime_filter/runtime_filter_mgr.cpp
  be/src/runtime_filter/runtime_filter_mgr.h
  be/src/runtime_filter/runtime_filter_producer.cpp
  be/src/runtime_filter/runtime_filter_producer.h
  be/src/runtime_filter/runtime_filter_producer_helper.cpp
  be/src/runtime_filter/runtime_filter_producer_helper.h
  be/src/runtime_filter/runtime_filter_wrapper.cpp
  be/src/runtime_filter/runtime_filter_wrapper.h
  be/src/vec/exec/scan/scanner.cpp
  be/test/pipeline/operator/partitioned_hash_join_test_helper.h
  be/test/pipeline/pipeline_test.cpp
  be/test/runtime_filter/runtime_filter_consumer_helper_test.cpp
  be/test/runtime_filter/runtime_filter_consumer_test.cpp
  be/test/runtime_filter/runtime_filter_definitions_test.cpp
  be/test/runtime_filter/runtime_filter_merger_test.cpp
  be/test/runtime_filter/runtime_filter_mgr_test.cpp
  be/test/runtime_filter/runtime_filter_producer_test.cpp
  be/test/runtime_filter/runtime_filter_test_utils.h
  be/test/runtime_filter/runtime_filter_wrapper_test.cpp
Labels: approved, reviewed

#49950 [minor](task) Complete debug string if task is finalized
  be/src/pipeline/exec/operator.h
  be/src/pipeline/pipeline.h
  be/src/pipeline/pipeline_task.cpp
  be/src/pipeline/pipeline_task.h
  be/test/pipeline/pipeline_task_test.cpp
Labels: approved, reviewed

#49994 [enhancement](ranger) modify ranger-intg to make testing more stable
  regression-test/framework/pom.xml
Labels: approved, reviewed

#49993 [Fix](function) fix wrong length check of function array_range
  be/src/vec/functions/array/function_array_range.cpp
  regression-test/data/nereids_function_p0/scalar_function/Array.out
  regression-test/suites/nereids_function_p0/scalar_function/Array.groovy
  regression-test/suites/query_p0/sql_functions/array_functions/test_array_functions.groovy
Labels: approved, reviewed, p0_w, dev/2.1.x, dev/3.0.x

#49912 [Fix](TrinoConnector) it will return error when query `information_schema.tables` within `trino-connector` catalog
  fe/fe-core/src/main/java/org/apache/doris/catalog/TableIf.java
  regression-test/suites/external_table_p0/trino_connector/test_trinoconnector_information_schema.groovy
Labels: approved, reviewed, dev/3.0.x, p0_test

#49966 [fix](parquet)fix when hive_parquet_use_column_names=false && read partition tb cause be core.
  be/src/vec/exec/format/parquet/vparquet_reader.cpp
  regression-test/data/external_table_p0/hive/test_external_catalog_hive_partition.out
  regression-test/suites/external_table_p0/hive/test_external_catalog_hive_partition.groovy
Labels: approved, reviewed, p0_c, dev/2.1.x, dev/3.0.x

#49976 branch-3.0:[fix](timer) Fix task execution timer (#49939)
  be/src/pipeline/pipeline_task.cpp
Labels: approved, reviewed

#49983 [fix](iceberg) Fix the failure of creating a table in OBS
  conf/fe.conf
Labels: approved, reviewed, dev/3.0.x

#49893 [Enhancement](nereids)support show functions
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionRegistry.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PlanType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ShowFunctionsCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/CommandVisitor.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/commands/ShowFunctionsCommandTest.java
  regression-test/suites/nereids_p0/show/test_nereids_show_functions.groovy
Labels: approved, reviewed

#49716 [fix](cloud-mow) Make new MS can erase initiator when upgrading MS
  cloud/src/meta-service/meta_service_job.cpp
Labels: approved, reviewed

#49938 [fix](load) fix multi table load repeated failures and retries when meet data quality error
  be/src/io/fs/multi_table_pipe.cpp
  be/src/io/fs/multi_table_pipe.h
  fe/fe-core/src/main/java/org/apache/doris/planner/StreamLoadPlanner.java
  regression-test/data/load_p0/routine_load/test_multi_table_load_data_quality_error.out
  regression-test/suites/load_p0/routine_load/data/multi_table_load_data_quality.csv
  regression-test/suites/load_p0/routine_load/test_multi_table_load_data_quality_error.groovy
Labels: approved, reviewed, p0_b, dev/2.1.x, dev/3.0.x

#49167 [fix](nereids) fix generate column need add cast in stream load
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/CreateTableInfo.java
  regression-test/data/ddl_p0/test_create_table_generated_column/objects3.csv
  regression-test/data/ddl_p0/test_create_table_generated_column/stream_load_and_mysql_load.out
  regression-test/suites/ddl_p0/test_create_table_generated_column/stream_load_and_mysql_load.groovy
Labels: approved, reviewed, usercase, dev/3.0.x

#49319 [fix](nereids)show user friendly error message when meet unsupported subquery
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/ExpressionAnalyzer.java
  regression-test/suites/nereids_p0/subquery/correlated_scalar_subquery.groovy
  regression-test/suites/nereids_syntax_p0/sub_query_correlated.groovy
Labels: approved, reviewed, dev/3.1.x

#49686 [fix](Nereids) fix unix_timestamp
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/executable/DateTimeExtractAndTransform.java
  regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_date_arithmatic.groovy
Labels: approved, reviewed, p0_w, dev/2.1.x, dev/3.0.x

#50023 [fix](ci) remove required check 'Build Third Party Libraries (macOS)' on branch-3.0
  .asf.yaml
Labels: approved, reviewed

#50003 [fix](inverted index) Downgrade ICU version to support lower OS versions #47664
  thirdparty/build-thirdparty.sh
  thirdparty/vars.sh
Labels: approved, reviewed

#50010 [refactor](spill) Refine logics in pipeline task
  be/src/pipeline/exec/operator.h
  be/src/pipeline/pipeline_task.cpp
  be/src/pipeline/pipeline_task.h
Labels: approved, reviewed

#49803 [test](ut) add cases about hash join
  be/src/pipeline/exec/hashjoin_build_sink.h
  be/src/pipeline/exec/hashjoin_probe_operator.cpp
  be/src/pipeline/exec/hashjoin_probe_operator.h
  be/src/runtime/runtime_state.h
  be/src/util/stack_util.cpp
  be/test/pipeline/operator/hash_join_test_helper.cpp
  be/test/pipeline/operator/hash_join_test_helper.h
  be/test/pipeline/operator/hashjoin_build_sink_test.cpp
  be/test/pipeline/operator/hashjoin_probe_operator_test.cpp
  be/test/pipeline/operator/join_test_helper.cpp
  be/test/pipeline/operator/join_test_helper.h
  be/test/testutil/mock/mock_operators.h
  be/test/testutil/mock/mock_runtime_state.h
  be/test/testutil/run_all_tests.cpp
Labels: approved, reviewed

#50013 [opt](inverted index) reset memory after inverted index write_v1 for each dir
  be/src/olap/rowset/segment_v2/inverted_index_file_writer.cpp
  be/test/olap/rowset/segment_v2/inverted_index_file_writer_test.cpp
Labels: approved, reviewed

#49589 [fix](nereids) do eliminate constant group by key in normalizeagg
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/Rewriter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/NormalizeAggregate.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/analysis/EliminateGroupByConstantTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/analysis/NormalizeAggregateTest.java
  regression-test/data/nereids_rules_p0/eliminate_gby_key/eliminate_constant_gby_key.out
  regression-test/suites/nereids_rules_p0/eliminate_gby_key/eliminate_constant_gby_key.groovy
  regression-test/suites/trino_p0/constant_group_key.groovy
Labels: approved, reviewed, usercase, dev/2.1.x, dev/3.0.x

#50019 [Fix](cloud-mow) Handle tablet delete bitmap calculation task's return value unifiedly in `CloudEngineCalcDeleteBitmapTask::execute`
  be/src/cloud/cloud_engine_calc_delete_bitmap_task.cpp
  be/src/cloud/cloud_engine_calc_delete_bitmap_task.h
  regression-test/data/fault_injection_p0/cloud/test_cloud_multi_segments_re_calc_in_publish.out
  regression-test/suites/fault_injection_p0/cloud/test_cloud_multi_segments_re_calc_in_publish.groovy
Labels: approved, reviewed, p0_w, dev/3.0.x

#50012 chore: disable download md5sum check by default
  be/src/common/config.cpp
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#50040 [UT](pipeline task) Test pausing tasks
  be/src/pipeline/exec/operator.h
  be/src/pipeline/pipeline_task.cpp
  be/src/pipeline/pipeline_task.h
  be/src/runtime/workload_group/workload_group_manager.h
  be/test/pipeline/pipeline_task_test.cpp
  be/test/testutil/mock/mock_workload_group_mgr.h
Labels: approved, reviewed

#50011 [improve](function) Optimize the performance of the explode function
  be/src/pipeline/exec/table_function_operator.cpp
  be/src/pipeline/exec/table_function_operator.h
  be/src/vec/exprs/table_function/vexplode_v2.cpp
Labels: approved, reviewed

#49665 [Enhancement] (GEO) Support MultiPolygon for Geometry functions
  be/src/geo/geo_common.h
  be/src/geo/geo_types.cpp
  be/src/geo/geo_types.h
  be/src/geo/wkt_parse_type.h
  be/src/geo/wkt_yacc.y
  be/test/geo/geo_types_test.cpp
  regression-test/data/nereids_p0/sql_functions/spatial_functions/test_gis_function.out
  regression-test/suites/nereids_p0/sql_functions/spatial_functions/test_gis_function.groovy
Labels: approved, reviewed, usercase, dev/2.1.x, dev/3.0.x

#49625 [fix](regression) fix the failed of cold_heat_separation_p2
  regression-test/suites/cold_heat_separation_p2/add_drop_partition.groovy
  regression-test/suites/cold_heat_separation_p2/add_drop_partition_by_hdfs.groovy
  regression-test/suites/cold_heat_separation_p2/create_table_use_dynamic_partition.groovy
  regression-test/suites/cold_heat_separation_p2/create_table_use_dynamic_partition_by_hdfs.groovy
  regression-test/suites/cold_heat_separation_p2/create_table_use_partition_policy.groovy
  regression-test/suites/cold_heat_separation_p2/create_table_use_partition_policy_by_hdfs.groovy
  regression-test/suites/cold_heat_separation_p2/create_table_use_policy.groovy
  regression-test/suites/cold_heat_separation_p2/create_table_use_policy_by_hdfs.groovy
  regression-test/suites/cold_heat_separation_p2/load_colddata_to_hdfs.groovy
  regression-test/suites/cold_heat_separation_p2/modify_replica_use_partition.groovy
  regression-test/suites/cold_heat_separation_p2/modify_replica_use_partition_by_hdfs.groovy
  regression-test/suites/cold_heat_separation_p2/table_modify_resouce_and_policy.groovy
  regression-test/suites/cold_heat_separation_p2/table_modify_resouce_and_policy_by_hdfs.groovy
  regression-test/suites/cold_heat_separation_p2/test_show_storage_policy_using.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#49894 [feat](binlog) add modify distribution bucket num binlog
  fe/fe-core/src/main/java/org/apache/doris/binlog/BinlogManager.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/DistributionInfo.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/HashDistributionInfo.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/RandomDistributionInfo.java
  fe/fe-core/src/main/java/org/apache/doris/persist/EditLog.java
  fe/fe-core/src/main/java/org/apache/doris/persist/ModifyTableDefaultDistributionBucketNumOperationLog.java
  gensrc/thrift/FrontendService.thrift
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x, dev/2.1.x-conflict

#49755 [feat](binlog) filter the temp table related binlogs
  fe/fe-core/src/main/java/org/apache/doris/binlog/BinlogConfigCache.java
  fe/fe-core/src/main/java/org/apache/doris/binlog/BinlogManager.java
Labels: approved, reviewed

#49775 [fix](cloud) Add check for cluster_name empty in cloud
  cloud/src/resource-manager/resource_manager.cpp
  cloud/test/meta_service_http_test.cpp
Labels: approved, reviewed, dev/3.0.x

#50032 [fix](variant)fix core in column_object when sort from empty block
  be/src/vec/columns/column_object.cpp
  be/test/vec/columns/column_object_test.cpp
  be/test/vec/columns/common_column_test.h
  regression-test/data/variant_p0/sql/sort_permute.out
  regression-test/suites/variant_p0/sql/sort_permute.sql
Labels: approved, reviewed, p0_c, dev/2.1.x, dev/3.0.x

#47199 [fix](cloud) Fix cloud resource test ut
  cloud/test/resource_test.cpp
Labels: approved, reviewed, dev/3.0.x

#50063 [Improvement](memory) reduce some memtracker overhead
  be/src/olap/rowset/segment_v2/stream_reader.h
  be/src/vec/columns/column_object.h
  be/src/vec/columns/subcolumn_tree.h
  be/src/vec/common/allocator.cpp
Labels: approved, reviewed

#50055 [chore](profile) Minor refactor on runtime filter producer profile
  be/src/pipeline/exec/hashjoin_build_sink.cpp
  be/src/pipeline/exec/nested_loop_join_build_operator.cpp
  be/src/pipeline/exec/set_sink_operator.cpp
  be/src/runtime/runtime_state.cpp
  be/src/runtime/runtime_state.h
  be/src/runtime_filter/runtime_filter_mgr.cpp
  be/src/runtime_filter/runtime_filter_mgr.h
  be/src/runtime_filter/runtime_filter_producer.h
  be/src/runtime_filter/runtime_filter_producer_helper.cpp
  be/src/runtime_filter/runtime_filter_producer_helper.h
  be/src/runtime_filter/runtime_filter_producer_helper_cross.h
  be/src/runtime_filter/runtime_filter_producer_helper_set.h
  be/test/runtime_filter/runtime_filter_consumer_helper_test.cpp
  be/test/runtime_filter/runtime_filter_consumer_test.cpp
  be/test/runtime_filter/runtime_filter_merger_test.cpp
  be/test/runtime_filter/runtime_filter_mgr_test.cpp
  be/test/runtime_filter/runtime_filter_producer_helper_cross_test.cpp
  be/test/runtime_filter/runtime_filter_producer_helper_test.cpp
  be/test/runtime_filter/runtime_filter_producer_test.cpp
Labels: approved, reviewed
