Repository apache/doris, pull requests merged in 2025-07, with the labels that each got.

#52460 [chore](cpuresource) remove cpu resource limit in be
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/fragment_mgr.h
  be/src/runtime/query_context.cpp
  be/src/runtime/query_context.h
  be/src/vec/exec/scan/scanner_context.cpp
  be/src/vec/exec/scan/scanner_context.h
  be/src/vec/exec/scan/scanner_scheduler.cpp
  be/src/vec/exec/scan/scanner_scheduler.h
Labels: approved, reviewed

#52232 [bugfix](be_metrics) update scan bytes metric correctly
  be/src/olap/rowset/segment_v2/page_io.cpp
  be/src/util/doris_metrics.cpp
  be/src/util/doris_metrics.h
  be/src/vec/exec/scan/olap_scanner.cpp
  be/src/vec/exec/scan/olap_scanner.h
  be/src/vec/exec/scan/scanner.cpp
  be/src/vec/exec/scan/scanner.h
  be/src/vec/exec/scan/scanner_scheduler.cpp
Labels: approved, reviewed, dev/3.1.x

#52378 [fix](nereids) add "Check expression limit" back
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/Expression.java
  regression-test/suites/nereids_p0/expression/expression_depth_check.groovy
Labels: approved, reviewed, dev/3.1.x

#52556 [optimization](filecache) speed up filecache warm up #51776
  be/src/cloud/cloud_backend_service.cpp
  be/src/cloud/cloud_tablet.cpp
  be/src/cloud/cloud_warm_up_manager.cpp
  be/src/cloud/cloud_warm_up_manager.h
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/io/cache/block_file_cache_downloader.cpp
  be/src/io/cache/block_file_cache_downloader.h
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/CacheHotspotManager.java
Labels: approved, reviewed

#52084 [feat](fs)Refactor Catalog FS Access to Use Unified StorageProperties
  fe/fe-common/src/main/java/org/apache/doris/common/security/authentication/AuthenticationConfig.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/LocationPath.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/CatalogProperty.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/FileSplit.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/FileSplitter.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/AcidUtil.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HMSExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HMSExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HiveMetaStoreCache.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/source/HiveScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hudi/source/COWIncrementalRelation.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hudi/source/HudiScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/source/IcebergScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/source/IcebergSplit.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/lakesoul/source/LakeSoulSplit.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/maxcompute/source/MaxComputeScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/paimon/source/PaimonScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/paimon/source/PaimonSplit.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/storage/AzureProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/storage/HdfsProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/storage/HdfsPropertiesUtils.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/trinoconnector/source/TrinoConnectorSplit.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/tvf/source/TVFScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/fs/FileSystemCache.java
  fe/fe-core/src/main/java/org/apache/doris/fs/FileSystemProviderImpl.java
  fe/fe-core/src/main/java/org/apache/doris/fs/SchemaTypeMapper.java
  fe/fe-core/src/main/java/org/apache/doris/fs/remote/SwitchingFileSystem.java
  fe/fe-core/src/main/java/org/apache/doris/planner/HiveTableSink.java
  fe/fe-core/src/main/java/org/apache/doris/planner/IcebergTableSink.java
  fe/fe-core/src/test/java/org/apache/doris/common/util/LocationPathTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/hive/HiveAcidTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/hive/HiveMetaStoreCacheTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/hive/HmsCommitTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/paimon/source/PaimonScanNodeTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/property/storage/HdfsPropertiesUtilsTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/property/storage/S3PropertiesTest.java
  fe/fe-core/src/test/java/org/apache/doris/fs/SchemaTypeMapperTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/FederationBackendPolicyTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/HiveTableSinkTest.java
Labels: approved, reviewed, dev/3.1.x

#52564 [Enhancement](nereids) cancel convert TableRefInfo to TableRef in RestoreCommand
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupHandler.java
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupJobInfo.java
Labels: approved, reviewed

#51826 [clean](planner)mv removes dependency on the old optimizer
  fe/fe-core/src/main/java/org/apache/doris/alter/RollupJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/MaterializedIndexMeta.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/CreateMaterializedViewCommand.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectContextUtil.java
  fe/fe-core/src/test/java/org/apache/doris/alter/RollupJobV2Test.java
Labels: approved, reviewed

#52517 [Opt](performance) Support column like use dict to speed up query
  be/src/olap/like_column_predicate.cpp
  be/src/olap/like_column_predicate.h
Labels: approved, reviewed

#52442 [clean](planner) Remove unused code in PlanNode and delete the implementations in its subclasses
  fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/FileQueryScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/es/source/EsScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/source/HiveScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/source/IcebergScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/source/JdbcScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/odbc/source/OdbcScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/tvf/source/MetadataScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/AggregationNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/AnalyticEvalNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/AssertNumRowsNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/BackendPartitionedSchemaScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/DataGenScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/EmptySetNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/ExchangeNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/FileLoadScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/GroupCommitScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/HashJoinNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/JoinNodeBase.java
  fe/fe-core/src/main/java/org/apache/doris/planner/MysqlScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/NestedLoopJoinNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PlanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/RepeatNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/ScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SchemaScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SelectNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SetOperationNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/SortNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/TableFunctionNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/TestExternalTableScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/rewrite/ExtractCommonFactorsRule.java
Labels: approved, reviewed

#51865 [fix](regression-test) fix broker load regression-test
  regression-test/data/doc/data-operate/import/import-way/broker-load-manual.md.out
  regression-test/suites/doc/data-operate/import/import-way/broker-load-manual.md.groovy
Labels: approved, reviewed

#52550 [test](mtmv) Fix regression test not stable and fail
  regression-test/suites/nereids_rules_p0/mv/availability/grace_period.groovy
  regression-test/suites/nereids_rules_p0/mv/external_table/part_partition_invalid.groovy
Labels: approved, reviewed

#52596 [fix](mow) fix potential mem leak for DeleteBitmap::AggCache
  be/src/olap/tablet_meta.h
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x, dev/3.1.x

#52604 [fix](ci) adjust perf and vault_p0
  regression-test/pipeline/common/doris-utils.sh
  regression-test/pipeline/vault_p0/prepare.sh
Labels: approved, reviewed

#52548 [fix](hudi) fix quering hudi tables error
  fe/fe-core/src/main/java/org/apache/doris/datasource/hudi/source/HudiScanNode.java
Labels: approved, reviewed, dev/3.1.x

#52616 [fix](main) check error immediately after flight_server init
  be/src/service/doris_main.cpp
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x, dev/3.1.x

#52519 branch-3.0: [fix](cloud)Fix auto start affected by daemon jobs #51729
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/system/CloudSystemInfoService.java
Labels: approved, reviewed

#52607 [fix](inverted index) Fix NonConcurrent case failure
  be/src/vec/functions/function_ip.h
Labels: approved, reviewed

#52326 [test](json) fix cases in TestJsonFunctions.sql #52302
  be/test/olap/rowset/segment_v2/inverted_index_file_writer_test.cpp
  be/test/util/jsonb_parser_simd_test.cpp
  regression-test/suites/dialect_compatible/sql/presto/scalar/TestJsonFunctions.sql
Labels: p0_b

#52405 [feat](cluster-snapshot) add cluster snapshot protobuf definition
  cloud/src/meta-service/CMakeLists.txt
  cloud/src/meta-service/meta_service.h
  cloud/src/meta-service/meta_service_snapshot.cpp
  gensrc/proto/cloud.proto
Labels: approved, reviewed

#52133 [fix](txn load) fix delete in txn load
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/PruneEmptyPartition.java
  fe/fe-core/src/main/java/org/apache/doris/transaction/TransactionEntry.java
  regression-test/suites/insert_p0/transaction/txn_insert.groovy
Labels: approved, reviewed, usercase, dev/3.0.x, dev/3.1.x

#51216 [opt](cache) Reset initial capacity of all caches after Cgroup memory limit changes
  be/src/olap/lru_cache.cpp
  be/src/runtime/memory/cache_manager.cpp
  be/src/runtime/memory/cache_manager.h
  be/src/runtime/memory/cache_policy.h
  be/src/runtime/memory/lru_cache_policy.h
  be/src/util/mem_info.cpp
  be/test/olap/lru_cache_test.cpp
Labels: approved, reviewed, usercase, dev/3.1.0-merged, dev/3.0.7-merged

#52513 [fix](cache) Add conf `segment_cache_enable_prune`
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/olap/segment_loader.h
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x

#52104 [feature](function) support to_json function
  be/src/util/jsonb_document.h
  be/src/util/jsonb_utils.h
  be/src/vec/data_types/serde/data_type_array_serde.cpp
  be/src/vec/data_types/serde/data_type_array_serde.h
  be/src/vec/data_types/serde/data_type_decimal_serde.cpp
  be/src/vec/data_types/serde/data_type_decimal_serde.h
  be/src/vec/data_types/serde/data_type_nullable_serde.cpp
  be/src/vec/data_types/serde/data_type_nullable_serde.h
  be/src/vec/data_types/serde/data_type_number_serde.cpp
  be/src/vec/data_types/serde/data_type_number_serde.h
  be/src/vec/data_types/serde/data_type_serde.cpp
  be/src/vec/data_types/serde/data_type_serde.h
  be/src/vec/data_types/serde/data_type_string_serde.cpp
  be/src/vec/data_types/serde/data_type_string_serde.h
  be/src/vec/data_types/serde/data_type_struct_serde.cpp
  be/src/vec/data_types/serde/data_type_struct_serde.h
  be/src/vec/functions/function_to_json.cpp
  be/src/vec/functions/simple_function_factory.h
  be/test/vec/data_types/serde/data_type_write_to_jsonb_test.cpp
  be/test/vec/function/function_jsonb_test.cpp
  be/test/vec/jsonb/jsonb_document_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinScalarFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/ToJson.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/ScalarFunctionVisitor.java
  regression-test/data/jsonb_p0/test_json_to_json.out
  regression-test/suites/jsonb_p0/test_json_to_json.groovy
Labels: approved, reviewed

#52652 [fix](regression-test) fix variant_p2 case to show load failure
  regression-test/suites/variant_p2/load.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x, dev/3.1.x, p0_test

#51475 [Feture](function)Support Time Function
  be/src/vec/functions/function_date_or_datetime_computation.cpp
  be/src/vec/functions/function_date_or_datetime_computation.h
  be/test/vec/function/function_time_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinScalarFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/executable/DateTimeArithmetic.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Time.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/DateTimeV2Literal.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/visitor/ScalarFunctionVisitor.java
  regression-test/data/query_p0/sql_functions/datetime_functions/test_func_time.out
  regression-test/suites/query_p0/sql_functions/datetime_functions/test_func_time.groovy
Labels: approved, reviewed

#52597 [clean](planner) Remove 6 DML stmts
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateTableAsSelectStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/DataDescription.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/DeleteStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/InsertOverwriteTableStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/InsertStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/NativeInsertStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/StmtRewriter.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/UpdateStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/load/CloudLoadManager.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/load/DeleteHandler.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/BulkLoadJob.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadManager.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/LoadManagerAdapter.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/MysqlLoadManager.java
  fe/fe-core/src/main/java/org/apache/doris/planner/GroupCommitPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/planner/PlannerContext.java
  fe/fe-core/src/main/java/org/apache/doris/qe/AuditLogHelper.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/DdlExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/DeleteStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/InsertArrayStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/InsertStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/QueryStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/load/DeleteHandlerTest.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/TestWithFeService.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/UtFrameUtils.java
Labels: approved, reviewed

#52631 [chore](variant) rename object to variant
  be/src/olap/rowset/segment_v2/hierarchical_data_reader.h
  be/src/pipeline/exec/hashjoin_build_sink.cpp
  be/src/vec/columns/column.h
  be/src/vec/columns/column_set.h
  be/src/vec/common/schema_util.cpp
  be/src/vec/data_types/data_type_variant.cpp
  be/src/vec/data_types/data_type_variant.h
  be/src/vec/data_types/serde/data_type_variant_serde.cpp
  be/src/vec/data_types/serde/data_type_variant_serde.h
  be/src/vec/functions/function_cast.h
  be/src/vec/json/parse2column.cpp
  be/test/vec/columns/column_array_test.cpp
  be/test/vec/columns/column_variant_test.cpp
  be/test/vec/columns/common_column_test.h
Labels: approved, reviewed

#52349 [fix](auth)fix when authentication, the permissions of multiple roles should be merged
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/Auth.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/Role.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/RoleManager.java
  fe/fe-core/src/test/java/org/apache/doris/mysql/privilege/AuthTest.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/TestWithFeService.java
  regression-test/suites/account_p0/test_grant_priv.groovy
Labels: approved, reviewed, p0_b, dev/2.1.x, dev/3.0.x, dev/3.1.x

#52508 [fix](inverted index) index-tool compile error
  be/src/index-tools/index_tool.cpp
Labels: approved, reviewed

#52681 [fix](test) fix nonConcurrent case failure
  regression-test/data/inverted_index_p0/load/test_stream_load.out
  regression-test/data/inverted_index_p0/test_index_match_phrase_ordered.out
  regression-test/suites/fault_injection_p0/test_inverted_index_v3_fault_injection.groovy
  regression-test/suites/inverted_index_p0/load/test_stream_load.groovy
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x

#52645 [fix](ubsan) fix ubsan error in DataTypeHLL::deserialize
  be/src/vec/data_types/data_type_hll.cpp
Labels: approved, reviewed

#52679 [behavior change](agg) The array type returned by foreach is always array<nullable<T>>
  be/src/vec/aggregate_functions/aggregate_function_foreachv2.cpp
  be/src/vec/aggregate_functions/aggregate_function_simple_factory.cpp
  be/src/vec/aggregate_functions/aggregate_function_simple_factory.h
  be/src/vec/exprs/vectorized_agg_fn.cpp
  fe/fe-core/src/main/java/org/apache/doris/catalog/Function.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/combinator/ForEachCombinator.java
Labels: approved, reviewed, dev/3.1.x

#52678 [compile](arm) Add ARM_MARCH to specify the ARM architecture instruction set
  be/CMakeLists.txt
  build.sh
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x

#52665 [regression-test](variant) fix test_show_nested_index_file_http_action_with_variant
  regression-test/suites/inverted_index_p0/test_show_nested_index_file_http_action_with_variant.groovy
Labels: dev/3.1.x, p0_test

#52684 branch-3.1: [fix](regression-test) fix variant_p2 case to show load failure #52652
  regression-test/suites/variant_p2/load.groovy
Labels: p0_test

#52695 [regression-test](variant) fix unstable test_variant_multi_index_nonCurrent
  regression-test/suites/variant_p0/predefine/test_multi_index_nonCurrent.groovy
Labels: dev/3.1.x

#52543 [fix](json) Add . after in JSON path to support correct token parsing
  be/src/vec/functions/function_json.cpp
  be/test/vec/function/function_json_test.cpp
  regression-test/data/json_p0/test_json_load_and_function.out
  regression-test/data/jsonb_p0/test_jsonb_load_and_function.out
  regression-test/data/nereids_function_p0/scalar_function/J.out
  regression-test/data/query_p0/sql_functions/json_functions/test_json_extract.out
  regression-test/suites/query_p0/sql_functions/json_functions/test_json_extract.groovy
Labels: approved, reviewed, kind/behavior-changed, usercase, dev/2.1.x, dev/3.0.x, dev/3.1.x

#52544 [fix](json) Add . after in JSON path to support correct token parsing (#52543)
  be/src/vec/functions/function_json.cpp
  be/test/util/jsonb_parser_simd_test.cpp
  be/test/vec/function/function_json_test.cpp
  regression-test/data/json_p0/test_json_load_and_function.out
  regression-test/data/jsonb_p0/test_jsonb_load_and_function.out
  regression-test/data/nereids_function_p0/scalar_function/J.out
  regression-test/data/nereids_p0/json_p0/test_json_load_and_function.out
  regression-test/data/query_p0/sql_functions/json_functions/test_json_extract.out
  regression-test/suites/query_p0/sql_functions/json_functions/test_json_extract.groovy
Labels: approved, reviewed

#52316 [chore](cloud) add document_put/get/remove methods
  be/src/cloud/pb_convert.cpp
  cloud/script/run_all_tests.sh
  cloud/src/common/config.h
  cloud/src/common/util.cpp
  cloud/src/meta-service/meta_service_helper.h
  cloud/src/meta-store/CMakeLists.txt
  cloud/src/meta-store/blob_message.cpp
  cloud/src/meta-store/document_message.cpp
  cloud/src/meta-store/document_message.h
  cloud/src/meta-store/mem_txn_kv.cpp
  cloud/src/meta-store/mem_txn_kv.h
  cloud/src/meta-store/txn_kv.cpp
  cloud/src/meta-store/txn_kv.h
  cloud/src/meta-store/txn_kv_error.h
  cloud/test/CMakeLists.txt
  cloud/test/document_message_test.cpp
  gensrc/proto/cloud.proto
  gensrc/proto/olap_file.proto
Labels: approved, reviewed, cloud, snapshot

#52733 [Fix](fe) fix redundant stdout by mistake
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/ComputeSignatureHelper.java
Labels: approved, reviewed

#52658 [Chore](function) remove some unused code and reduce some template about agg function
  be/src/vec/aggregate_functions/aggregate_function_approx_count_distinct.cpp
  be/src/vec/aggregate_functions/aggregate_function_approx_top_k.cpp
  be/src/vec/aggregate_functions/aggregate_function_approx_top_sum.cpp
  be/src/vec/aggregate_functions/aggregate_function_array_agg.cpp
  be/src/vec/aggregate_functions/aggregate_function_binary.h
  be/src/vec/aggregate_functions/aggregate_function_collect.cpp
  be/src/vec/aggregate_functions/aggregate_function_collect.h
  be/src/vec/aggregate_functions/aggregate_function_corr.cpp
  be/src/vec/aggregate_functions/aggregate_function_corr.h
  be/src/vec/aggregate_functions/aggregate_function_covar.cpp
  be/src/vec/aggregate_functions/aggregate_function_group_array_intersect.cpp
  be/src/vec/aggregate_functions/aggregate_function_orthogonal_bitmap.cpp
  be/src/vec/aggregate_functions/factory_helpers.h
  be/src/vec/aggregate_functions/helpers.h
Labels: approved, reviewed

#51807 [fix](nereids) fix bug when CTEConsumer is used as runtime filter target
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/RuntimeFilterTranslator.java
  regression-test/data/nereids_p0/runtime_filter/cte-runtime-filter.out
  regression-test/suites/nereids_p0/runtime_filter/cte-runtime-filter.groovy
Labels: approved, reviewed, usercase, dev/2.1.x, dev/3.0.x, dev/3.1.x

#52238 [opt](nereids)add comments for CompressedMaterialize and NormalizeAggregate order
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/Analyzer.java
Labels: approved, reviewed

#52651 [improve](statistics)Add hot values to column statistics to string.
  fe/fe-core/src/main/java/org/apache/doris/statistics/ColumnStatistic.java
  regression-test/suites/statistics/test_hot_value.groovy
Labels: approved, reviewed

#52747 [fix](inverted index) fix memory leaks in inverted index
  be/src/olap/rowset/segment_v2/inverted_index_common.h
  be/src/olap/rowset/segment_v2/inverted_index_compound_reader.cpp
  be/src/olap/rowset/segment_v2/inverted_index_compound_reader.h
  be/src/olap/rowset/segment_v2/inverted_index_file_writer.cpp
  be/src/olap/rowset/segment_v2/inverted_index_fs_directory.cpp
Labels: approved, reviewed

#52590 [fix](nereids) update shape plan in order_push_down.out
  regression-test/data/nereids_rules_p0/limit_push_down/order_push_down.out
Labels: approved, reviewed

#52560 [fix](sink) fix sink operator tolerate failed replica number incorrect
  be/src/exec/tablet_info.cpp
  be/src/exec/tablet_info.h
  be/src/runtime/load_channel.cpp
  be/src/vec/sink/writer/vtablet_writer.cpp
  be/src/vec/sink/writer/vtablet_writer.h
  be/src/vec/sink/writer/vtablet_writer_v2.cpp
  be/src/vec/sink/writer/vtablet_writer_v2.h
  be/test/vec/sink/vtablet_writer_v2_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapTableSink.java
  gensrc/thrift/Descriptors.thrift
  regression-test/framework/src/main/groovy/org/apache/doris/regression/util/DebugPoint.groovy
  regression-test/suites/load_p0/stream_load/test_sink_tolerate.groovy
Labels: approved, reviewed, dev/3.1.x

#52719 [fix](move-memtable) gracefully shutdown flush token in TabletStream::pre_close
  be/src/runtime/load_stream.cpp
Labels: approved, reviewed

#52742 [opt](nereids) opt eliminate empty relation with union
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/EliminateEmptyRelation.java
  regression-test/data/empty_relation/eliminate_empty.out
  regression-test/suites/empty_relation/eliminate_empty.groovy
Labels: approved, reviewed

#52569 [typo](nereids)remove useless code
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/EliminateGroupByConstant.java
Labels: approved, reviewed

#52661 [fix] remove duplicate tableName field in Index related options.
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/BuildIndexOp.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/CreateIndexOp.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/DropIndexOp.java
Labels: approved, reviewed

#51936 [feat](catalog) Support reading Hive table with MultiDelimitSerDe
  be/src/vec/exec/format/text/text_reader.cpp
  be/src/vec/exec/format/text/text_reader.h
  be/test/vec/exec/format/text/hive_text_field_splitter_test.cpp
  docker/thirdparties/docker-compose/hive/scripts/data/regression/multi_delimit_serde/create_table.hql
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HiveMetaStoreClientHelper.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/HiveProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/hive/source/HiveScanNode.java
  fe/fe-core/src/main/java/org/apache/doris/planner/HiveTableSink.java
  regression-test/data/external_table_p0/hive/test_multi_delimit_serde.out
  regression-test/suites/external_table_p0/hive/test_multi_delimit_serde.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x, dev/3.1.x

#52711 [fix](ui) fix ui builds failed error
  ui/package.json
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x, dev/3.1.x

#52692 [fix](regression-framework) fix time type compatibility in regression…
  regression-test/data/cast_p0/cast_to_time.out
  regression-test/data/correctness/test_cast_as_time.out
  regression-test/data/nereids_p0/datatype/test_cast.out
  regression-test/data/query_p0/sql_functions/datetime_functions/test_func_time.out
  regression-test/framework/src/main/groovy/org/apache/doris/regression/util/JdbcUtils.groovy
Labels: approved, reviewed, p0_test

#52675 [Chore](util) remove some unused code on var_int.h
  be/src/vec/io/var_int.h
  be/src/vec/runtime/vdatetime_value.cpp
  be/src/vec/runtime/vdatetime_value.h
Labels: approved, reviewed

#52784 [fix](ci) exclude case with known issue of memory leak
  regression-test/pipeline/nonConcurrent/conf/regression-conf.groovy
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x

#52774 [opt](tvf) longer the timeout of getting file list from backend
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/LocalTableValuedFunction.java
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x

#51733 [opt](cloud) Optimize balance speed by reducing the complexity of the rebalance algorithm
  fe/fe-core/src/main/java/org/apache/doris/cloud/catalog/CloudTabletRebalancer.java
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x, cloud

#52821 [fix](be-jni-env) Fix java.lang.StackOverflowError thrown from the UncaughtExceptionHandler in thread "process reaper".
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/util/jni-util.cpp
Labels: approved, reviewed

#52819 [Exec](alias) support stddev alias to std
  be/src/vec/aggregate_functions/aggregate_function_stddev.cpp
  fe/fe-core/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinAggregateFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionSet.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/analysis/GenerateFunction.java
  regression-test/data/query_p0/sql_functions/aggregate_functions/test_aggregate_all_functions.out
  regression-test/suites/query_p0/sql_functions/aggregate_functions/test_aggregate_all_functions.groovy
Labels: approved, reviewed

#52817 [fix](test)(jdbc) fix some external regression test cases and jdbc bug
  fe/fe-core/src/main/java/org/apache/doris/catalog/JdbcTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/IcebergMetadataOps.java
  fe/fe-core/src/main/java/org/apache/doris/journal/bdbje/BDBJEJournal.java
  regression-test/data/external_table_p0/iceberg/test_iceberg_hadoop_case_sensibility.out
  regression-test/data/external_table_p0/iceberg/test_iceberg_rest_case_sensibility.out
  regression-test/suites/external_table_p0/iceberg/test_iceberg_hadoop_case_sensibility.groovy
  regression-test/suites/external_table_p0/iceberg/test_iceberg_rest_case_sensibility.groovy
  regression-test/suites/external_table_p0/iceberg/write/test_iceberg_create_table.groovy
  regression-test/suites/external_table_p0/tvf/test_file_tvf_hdfs.groovy
  regression-test/suites/external_table_p0/tvf/upgrade/load.groovy
  regression-test/suites/external_table_p0/tvf/upgrade/test.groovy
  regression-test/suites/nereids_rules_p0/mv/external_table/part_partition_invalid.groovy
  regression-test/suites/nereids_rules_p0/mv/external_table/single_external_table.groovy
Labels: approved, reviewed, dev/3.1.x

#52315 [fix](external) check duplicate column names for external table schema
  docker/thirdparties/docker-compose/hive/scripts/paimon1/db1.db/dup_columns_table/bucket-0/data-72d4d52a-eca9-4542-a2af-cc17499731e6-0.parquet
  docker/thirdparties/docker-compose/hive/scripts/paimon1/db1.db/dup_columns_table/manifest/manifest-5cae1365-d123-4172-9a89-4fbc02bee658-0
  docker/thirdparties/docker-compose/hive/scripts/paimon1/db1.db/dup_columns_table/manifest/manifest-list-391058a9-952c-4aa9-892f-df3334e4109b-0
  docker/thirdparties/docker-compose/hive/scripts/paimon1/db1.db/dup_columns_table/manifest/manifest-list-391058a9-952c-4aa9-892f-df3334e4109b-1
  docker/thirdparties/docker-compose/hive/scripts/paimon1/db1.db/dup_columns_table/schema/schema-0
  docker/thirdparties/docker-compose/hive/scripts/paimon1/db1.db/dup_columns_table/snapshot/EARLIEST
  docker/thirdparties/docker-compose/hive/scripts/paimon1/db1.db/dup_columns_table/snapshot/LATEST
  docker/thirdparties/docker-compose/hive/scripts/paimon1/db1.db/dup_columns_table/snapshot/snapshot-1
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalSchemaCache.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/SchemaCacheValue.java
  regression-test/suites/external_table_p0/paimon/test_paimon_catalog.groovy
Labels: approved, reviewed, dev/3.1.x

#52756 [fix](chore) fix cache release core
  be/src/olap/tablet_meta.cpp
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x

#52795 [improve](hive row count)Log stack info when fetch hive row count fail.
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalRowCountCache.java
Labels: approved, reviewed, usercase, dev/2.1.x, dev/3.0.x, dev/3.1.x

#52138 [improve](analytic) support window function execute with incremental mode
  be/src/pipeline/exec/analytic_sink_operator.cpp
  be/src/pipeline/exec/analytic_sink_operator.h
  be/src/vec/aggregate_functions/aggregate_function.h
  be/src/vec/aggregate_functions/aggregate_function_avg.h
  be/src/vec/aggregate_functions/aggregate_function_count.h
  be/src/vec/aggregate_functions/aggregate_function_java_udaf.h
  be/src/vec/aggregate_functions/aggregate_function_min_max.h
  be/src/vec/aggregate_functions/aggregate_function_null.h
  be/src/vec/aggregate_functions/aggregate_function_reader_first_last.h
  be/src/vec/aggregate_functions/aggregate_function_sum.h
  be/src/vec/aggregate_functions/aggregate_function_window.h
  regression-test/data/query_p0/sql_functions/window_functions/test_window_fn.out
  regression-test/suites/query_p0/sql_functions/window_functions/test_window_fn.groovy
Labels: approved, reviewed

#52476 [Opt](cloud-mow) Do fast retry when commit compaction job for mow tablet
  cloud/src/meta-service/meta_service_job.cpp
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x

#52816 [chore](cloud) Add async wrap for `bthread_fork_join` with promise-future
  be/src/cloud/cloud_meta_mgr.cpp
  be/src/cloud/cloud_meta_mgr.h
  be/test/cloud/cloud_meta_mgr_test.cpp
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x

#52671 [feat](txnkv) support atomic_set_ver_key with offset
  cloud/src/meta-store/mem_txn_kv.cpp
  cloud/src/meta-store/mem_txn_kv.h
  cloud/src/meta-store/txn_kv.cpp
  cloud/src/meta-store/txn_kv.h
  cloud/test/http_encode_key_test.cpp
  cloud/test/mem_txn_kv_test.cpp
  cloud/test/recycler_test.cpp
  cloud/test/txn_kv_test.cpp
Labels: approved, reviewed, cloud, snapshot

#52547 [Opt](cloud-mow) Retry to commit txn when encounter stale calc delete bitmap response regardless of status code
  fe/fe-core/src/main/java/org/apache/doris/master/MasterImpl.java
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x

#52762 [opt](auditlog) Use varchar(1024) for column frontend_ip of audit log table
  fe/fe-core/src/main/java/org/apache/doris/catalog/InternalSchema.java
  regression-test/suites/manager/test_manager_interface_1.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x, dev/3.1.x

#52788 [opt](nereids) optimize stats derive when using delta rows
  fe/fe-core/src/main/java/org/apache/doris/nereids/stats/FilterEstimation.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/stats/FilterEstimationTest.java
Labels: approved, reviewed

#52440 [opt](rowset) Remote fetch rowsets to avoid -230 error when capturing rowsets
  be/src/cloud/cloud_base_compaction.cpp
  be/src/cloud/cloud_cumulative_compaction.cpp
  be/src/cloud/cloud_full_compaction.cpp
  be/src/cloud/cloud_meta_mgr.cpp
  be/src/cloud/cloud_schema_change_job.cpp
  be/src/cloud/cloud_tablet.cpp
  be/src/cloud/cloud_tablet.h
  be/src/cloud/cloud_tablet_mgr.cpp
  be/src/cloud/cloud_tablet_mgr.h
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/http/action/delete_bitmap_action.cpp
  be/src/olap/base_tablet.cpp
  be/src/olap/base_tablet.h
  be/src/olap/compaction.cpp
  be/src/olap/data_dir.cpp
  be/src/olap/full_compaction.cpp
  be/src/olap/merger.cpp
  be/src/olap/parallel_scanner_builder.cpp
  be/src/olap/parallel_scanner_builder.h
  be/src/olap/rowset/rowset_reader_context.h
  be/src/olap/rowset_version_mgr.cpp
  be/src/olap/schema_change.cpp
  be/src/olap/snapshot_manager.cpp
  be/src/olap/tablet.cpp
  be/src/olap/tablet.h
  be/src/olap/tablet_manager.cpp
  be/src/olap/tablet_meta.cpp
  be/src/olap/tablet_meta.h
  be/src/olap/tablet_reader.cpp
  be/src/olap/tablet_reader.h
  be/src/olap/task/engine_checksum_task.cpp
  be/src/olap/task/engine_clone_task.cpp
  be/src/olap/task/engine_storage_migration_task.cpp
  be/src/olap/task/index_builder.cpp
  be/src/pipeline/exec/olap_scan_operator.cpp
  be/src/pipeline/exec/olap_scan_operator.h
  be/src/service/internal_service.cpp
  be/src/service/internal_service.h
  be/src/vec/exec/scan/new_olap_scanner.cpp
  be/src/vec/exec/scan/new_olap_scanner.h
  be/test/olap/delta_writer_test.cpp
  be/test/olap/segcompaction_mow_test.cpp
  be/test/olap/tablet_meta_test.cpp
  be/test/olap/test_data/rowset_meta.json
  fe/fe-core/src/main/java/org/apache/doris/cloud/catalog/CloudReplica.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  gensrc/proto/internal_service.proto
  regression-test/data/fault_injection_p0/cloud/test_cloud_version_already_merged.out
  regression-test/pipeline/p0/conf/be.conf
  regression-test/suites/fault_injection_p0/cloud/test_cloud_version_already_merged.groovy
Labels: approved, reviewed

#52630 branch-3.0: [fix](fe) multi statements different behavior in master and follower (#52144)
  fe/fe-core/src/main/java/org/apache/doris/qe/ConnectProcessor.java
  regression-test/data/insert_p0/insert.out
  regression-test/suites/insert_p0/insert.groovy
Labels: approved, reviewed

#52800 [fix](txnkv) avoid skip keys during reverse full range iteration
  cloud/src/meta-store/mem_txn_kv.cpp
  cloud/src/meta-store/mem_txn_kv.h
  cloud/src/meta-store/txn_kv.cpp
  cloud/src/meta-store/txn_kv.h
  cloud/test/mem_txn_kv_test.cpp
  cloud/test/txn_kv_test.cpp
Labels: approved, reviewed, cloud, snapshot

#49109 [Enhancement] (nereids) implement mysqlLoadCommand in nereids
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/analysis/Separator.java
  fe/fe-core/src/main/java/org/apache/doris/load/loadv2/MysqlLoadManager.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PlanType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/load/MysqlDataDescription.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/load/MysqlLoadCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/CommandVisitor.java
Labels: approved, reviewed

#51165 [fix](nereids)fix multi_leading regression test case
  regression-test/data/nereids_p0/hint/multi_leading.out
Labels: approved, reviewed

#52667 [fix](nereids)scalar subquery should not show error message when there are multiple agg functions in top-level agg node
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/SubqueryToApply.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/UnCorrelatedApplyAggregateFilter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/UnCorrelatedApplyFilter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/UnCorrelatedApplyProjectFilter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/copier/LogicalPlanDeepCopier.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/ScalarSubquery.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalApply.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/analysis/SubqueryToApplyTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/ExistsApplyToJoinTest.java
  regression-test/data/nereids_p0/subquery/correlated_scalar_subquery.out
  regression-test/suites/nereids_p0/subquery/correlated_scalar_subquery.groovy
Labels: approved, reviewed, dev/3.1.x

#52809 [Fix](UBSan) fix mem alignment in rapidjson ralated code
  be/src/exprs/json_functions.cpp
  be/src/vec/functions/function_json.cpp
Labels: approved, reviewed, dev/3.1.x

#52901 [Fix](ub) Fix undefined behaviour on visiting vector
  be/src/vec/sink/vrow_distribution.cpp
Labels: approved, reviewed

#52737 branch-3.0: [Opt](mow) Move `DeleteBitmapAggCache` to `ExecEnv` (#52649)
  be/src/olap/tablet_meta.cpp
  be/src/olap/tablet_meta.h
  be/src/runtime/exec_env.h
  be/src/runtime/exec_env_init.cpp
  be/test/testutil/run_all_tests.cpp
Labels: approved, reviewed

#52714 branch-3.0: [enhance](meta-service)add bvar for ms kv get del put count
  cloud/src/common/bvars.cpp
  cloud/src/common/bvars.h
  cloud/src/common/stats.h
  cloud/src/meta-service/mem_txn_kv.cpp
  cloud/src/meta-service/mem_txn_kv.h
  cloud/src/meta-service/meta_service.cpp
  cloud/src/meta-service/meta_service.h
  cloud/src/meta-service/meta_service_helper.h
  cloud/src/meta-service/meta_service_job.cpp
  cloud/src/meta-service/meta_service_partition.cpp
  cloud/src/meta-service/meta_service_resource.cpp
  cloud/src/meta-service/meta_service_txn.cpp
  cloud/src/meta-service/txn_kv.cpp
  cloud/src/meta-service/txn_kv.h
  cloud/src/meta-service/txn_lazy_committer.cpp
  cloud/test/CMakeLists.txt
  cloud/test/meta_server_test.cpp
  cloud/test/rpc_kv_bvar_test.cpp
Labels: approved, reviewed

#52902 [fix](load) Convert RowInBlock* to shared_ptr to fix potential memory leaks in MemTable
  be/src/olap/memtable.cpp
  be/src/olap/memtable.h
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x

#52688 [opt](create table) Fixed table creation becomes slower as the number of tablets increases
  fe/fe-core/src/main/java/org/apache/doris/catalog/TabletInvertedIndex.java
  fe/fe-core/src/main/java/org/apache/doris/system/SystemInfoService.java
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x

#51821 [feat](nereids)support count/sum(distinct A) for window
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/Rewriter.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/RuleType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/DistinctWindowExpression.java
  regression-test/data/nereids_p0/multi_distinct/multi_distinct_window.out
  regression-test/suites/nereids_p0/multi_distinct/multi_distinct_window.groovy
Labels: approved, reviewed

#52511 [refine](function) function catch throw exception
  be/src/vec/functions/function.h
  be/src/vec/functions/function_rpc.cpp
  be/src/vec/functions/function_rpc.h
  be/src/vec/functions/simple_function_factory.h
  be/test/vec/function/function_throw_exception_test.cpp
  be/test/vec/function/function_time_test.cpp
Labels: approved, reviewed

#52805 [opt](group_concat) allow args be types other than string
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/GroupConcat.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/MultiDistinctGroupConcat.java
  regression-test/data/query_p0/group_concat/test_group_concat.out
  regression-test/suites/query_p0/group_concat/test_group_concat.groovy
Labels: approved, reviewed, kind/behavior-changed, dev/3.1.x

#52913 [fix](audit) fix audit log test
  regression-test/data/audit/test_audit_log_behavior.out
Labels: approved, reviewed

#52799 [Improve](Variant) Add more static type constraints to ensure the safety of predefined types in Variant.
  fe/fe-common/src/main/java/org/apache/doris/catalog/Type.java
  fe/fe-common/src/main/java/org/apache/doris/catalog/VariantType.java
  regression-test/suites/variant_p0/predefine/multi_var.groovy
  regression-test/suites/variant_p0/predefine/test_predefine_ddl.groovy
Labels: dev/3.1.x

#50139 [enhance](auth)Remove restrictions on user creation and other operations when enabling ranger/LDAP
  fe/fe-core/src/main/java/org/apache/doris/analysis/DropUserStmt.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/DropUserCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/CreateUserInfo.java
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x

#52834 [Enhancement] (nereids)implement unsupportedStartTransactionCommand in nereids
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PlanType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/StartTransactionCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/CommandVisitor.java
  regression-test/suites/nereids_p0/test_unsupported_start_transaction_command.groovy
Labels: approved, reviewed

#51778 [feat](iceberg) implement hdfs fileio for iceberg
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/IcebergHadoopExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/IcebergUtils.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/fileio/DelegateFileIO.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/fileio/DelegateInputFile.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/fileio/DelegateOutputFile.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/fileio/DelegateSeekableInputStream.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/storage/HdfsProperties.java
  fe/fe-core/src/main/java/org/apache/doris/fs/FileSystem.java
  fe/fe-core/src/main/java/org/apache/doris/fs/io/DorisInput.java
  fe/fe-core/src/main/java/org/apache/doris/fs/io/DorisInputFile.java
  fe/fe-core/src/main/java/org/apache/doris/fs/io/DorisInputStream.java
  fe/fe-core/src/main/java/org/apache/doris/fs/io/DorisOutputFile.java
  fe/fe-core/src/main/java/org/apache/doris/fs/io/ParsedPath.java
  fe/fe-core/src/main/java/org/apache/doris/fs/io/hdfs/HdfsInput.java
  fe/fe-core/src/main/java/org/apache/doris/fs/io/hdfs/HdfsInputFile.java
  fe/fe-core/src/main/java/org/apache/doris/fs/io/hdfs/HdfsInputStream.java
  fe/fe-core/src/main/java/org/apache/doris/fs/io/hdfs/HdfsOutputFile.java
  fe/fe-core/src/main/java/org/apache/doris/fs/io/hdfs/HdfsOutputStream.java
  fe/fe-core/src/main/java/org/apache/doris/fs/obj/ObjStorage.java
  fe/fe-core/src/main/java/org/apache/doris/fs/obj/S3ObjStorage.java
  fe/fe-core/src/main/java/org/apache/doris/fs/remote/dfs/DFSFileSystem.java
  fe/fe-core/src/test/java/org/apache/doris/external/iceberg/IcebergHadoopCatalogTest.java
Labels: approved, reviewed, dev/3.1.x

#52881 [fix](paimon) fix CacheException msg in loadSnapshot
  fe/fe-core/src/main/java/org/apache/doris/datasource/paimon/PaimonMetadataCache.java
Labels: approved, reviewed, dev/3.1.x

#52752 [feat](cloud) Add versioned keys definition
  cloud/src/meta-store/keys.cpp
  cloud/src/meta-store/keys.h
  cloud/test/keys_test.cpp
Labels: approved, reviewed, cloud, snapshot

#52825 [chore](typo) fix typo error
  be/src/vec/exprs/vdirect_in_predicate.h
  be/src/vec/exprs/vectorized_fn_call.cpp
  be/src/vec/exprs/vectorized_fn_call.h
  be/src/vec/exprs/vexpr.h
  be/src/vec/exprs/vruntimefilter_wrapper.cpp
Labels: approved, reviewed

#52952 branch-3.0; [Opt](cloud-mow) Do fast retry when commit compaction job for mow tablet (#52476)
  cloud/src/meta-service/meta_service_job.cpp
Labels: approved, reviewed

#52582 [Fix](mow) Fix `DeleteBitmap`'s assignment operator and constructor
  be/src/olap/tablet_meta.cpp
  be/src/olap/tablet_meta.h
  regression-test/data/fault_injection_p0/cloud/test_cloud_mow_sc_inc_rowsets_dup.out
  regression-test/suites/fault_injection_p0/cloud/test_cloud_mow_sc_inc_rowsets_dup.groovy
Labels: approved, reviewed, p0_w, dev/3.0.x, dev/3.1.x

#52850 [fix](pipeline) premature exit causing core dump during concurrent pr…
  be/src/pipeline/pipeline_x/pipeline_x_fragment_context.cpp
  be/src/util/countdown_latch.h
Labels: approved, reviewed

#52769 [fix](test) fix nonConcurrent case failure
  regression-test/data/inverted_index_p0/load/test_stream_load.out
  regression-test/suites/inverted_index_p0/load/test_stream_load.groovy
Labels: approved, reviewed

#52883 [opt](cloud) add Sanitizer options
  cloud/CMakeLists.txt
  cloud/conf/asan_suppr.conf
  cloud/conf/lsan_suppr.conf
  cloud/conf/ubsan_suppr.conf
  cloud/script/run_all_tests.sh
  cloud/script/start.sh
  cloud/test/CMakeLists.txt
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x, cloud

#52669 [Chore](function) keep invalid escape as literal mean in function 'like'
  be/src/vec/functions/like.cpp
  be/src/vec/functions/like.h
  be/test/vec/function/function_like_test.cpp
  regression-test/data/query_p0/sql_functions/string_functions/test_like_literal.out
  regression-test/data/query_p0/sql_functions/string_functions/test_like_table.out
  regression-test/suites/query_p0/sql_functions/string_functions/test_like_literal.groovy
  regression-test/suites/query_p0/sql_functions/string_functions/test_like_table.groovy
Labels: approved, reviewed

#52970 [fix](regression-suites) fix compare result bug
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
Labels: approved, reviewed

#52926 [fix](nereids)fix show temp table status in ShowTableStatusCommand
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ShowTableStatusCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/AliasInfo.java
Labels: approved, reviewed

#52959 [ci](nonConcurrent) suppress leaks about index
  conf/lsan_suppr.conf
Labels: approved, reviewed

#52987 [ci](nonConcurrent) set required on master
  .asf.yaml
Labels: approved, reviewed

#52820 [Chore](build) Adapt ldb toolchain 0.25
  be/src/glibc-compatibility/glibc-compatibility.c
  be/src/pipeline/exec/exchange_sink_buffer.cpp
  be/src/pipeline/exec/exchange_sink_buffer.h
  be/src/util/proto_util.h
  be/src/vec/columns/column_dictionary.h
  be/src/vec/data_types/serde/data_type_string_serde.h
  be/test/io/cache/block_file_cache_test_common.h
  be/test/olap/storage_resource_test.cpp
  be/test/vec/exec/exchange_sink_test.h
  be/test/vec/exec/sort/heap_sorter_test.cpp
  be/test/vec/exec/sort/sort_test.cpp
Labels: approved, reviewed

#52950 branch-3.0: [fix](nereids) fix sum0 cannot pass multi distinct check #51234
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/CheckMultiDistinct.java
  regression-test/data/nereids_syntax_p0/analyze_agg.out
  regression-test/suites/nereids_syntax_p0/analyze_agg.groovy
Labels: approved, reviewed

#52968 [fix](audit) fix invalid audit log column and line separator
  fe/fe-core/src/main/java/org/apache/doris/plugin/audit/AuditLoader.java
Labels: approved, reviewed, dev/3.1.x

#52886 [ci](cloud_p0) pipeline fail if stop grace fail
  regression-test/pipeline/cloud_p0/clean.sh
  regression-test/pipeline/cloud_p0/run.sh
  regression-test/pipeline/common/doris-utils.sh
  regression-test/pipeline/vault_p0/clean.sh
  regression-test/pipeline/vault_p0/run.sh
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x, cloud

#52771 [feature](encryption) Add metadata for transparent data encryption
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/encryption/KeyManager.java
  fe/fe-core/src/main/java/org/apache/doris/journal/JournalEntity.java
  fe/fe-core/src/main/java/org/apache/doris/persist/EditLog.java
  fe/fe-core/src/main/java/org/apache/doris/persist/KeyOperationInfo.java
  fe/fe-core/src/main/java/org/apache/doris/persist/OperationType.java
  fe/fe-core/src/main/java/org/apache/doris/persist/meta/MetaPersistMethod.java
  fe/fe-core/src/main/java/org/apache/doris/persist/meta/PersistMetaModules.java
Labels: approved, reviewed, security, dev/3.1.x, encryption

#52897 [fix](export) don't transform varchar and char to string in get_data_type_with_default_argument
  be/src/vec/data_types/data_type_decimal.cpp
Labels: approved, reviewed

#52985 [opt](auditlog) Use varchar(1024) for column frontend_ip of audit log table #52762
  fe/fe-core/src/main/java/org/apache/doris/catalog/InternalSchema.java
  regression-test/data/audit/test_audit_log_behavior.out
  regression-test/suites/manager/test_manager_interface_1.groovy
Labels: approved, reviewed

#52862 [feature](Nereids): Convert log(x) to ln(x)
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/ExpressionOptimization.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/ExpressionRuleType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/LogToLn.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/Log.java
  regression-test/data/query_p0/sql_functions/math_functions/test_math_unary_always_nullable.out
  regression-test/suites/query_p0/sql_functions/math_functions/test_math_unary_always_nullable.groovy
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x

#52802 [fix](nereids) fix insert into values throw 'Invalid call to sql on unbound object' and 'Insert has filtered data in strict mode' exception
  fe/fe-core/src/main/java/org/apache/doris/nereids/load/NereidsLoadUtils.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/BindSink.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/insert/InsertUtils.java
  regression-test/data/nereids_p0/insert_into_table/insert_values.out
  regression-test/suites/nereids_p0/insert_into_table/insert_values.groovy
Labels: approved, reviewed, dev/3.1.x

#52941 [opt](nereids) optimize stats derive rule
  fe/fe-core/src/main/java/org/apache/doris/nereids/StatementContext.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/RewriteCteChildren.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/StatsDerive.java
Labels: approved, reviewed

#53023 [chore](nereids) delete redundant code
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ShowCreateUserCommand.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/commands/ShowCreateUserCommandTest.java
  regression-test/suites/nereids_p0/show/test_nereids_show_create_user.groovy
Labels: approved, reviewed

#53009 [Chore](json) remove some unused code on SimdJSONParser
  be/src/olap/compaction.h
  be/src/vec/json/simd_json_parser.h
Labels: approved, reviewed

#51913 [fix](jni)add ExceptionCheck for safe jni call.
  be/src/util/jni-util.cpp
  be/src/util/jni-util.h
  be/src/vec/aggregate_functions/aggregate_function_java_udaf.h
  be/src/vec/exec/format/table/trino_connector_jni_reader.cpp
  be/src/vec/exec/jni_connector.cpp
  be/src/vec/exec/jni_connector.h
  be/src/vec/exec/vjdbc_connector.cpp
  be/src/vec/exec/vjdbc_connector.h
  be/src/vec/exprs/table_function/udf_table_function.cpp
  be/src/vec/exprs/table_function/udf_table_function.h
  be/src/vec/functions/function_java_udf.cpp
  be/src/vec/functions/function_java_udf.h
  regression-test/pipeline/external/conf/be.conf
  regression-test/pipeline/p0/conf/be.conf
Labels: approved, reviewed, p0_c, dev/2.1.x, dev/3.0.x, dev/3.1.x

#52888 [refine](array) check array column data must be a nullable column and refine array filter function
  be/src/vec/columns/column_array.cpp
  be/src/vec/columns/column_array.h
Labels: approved, reviewed

#53049 [chore](lsan) lsan add dl_find_object_update
  conf/lsan_suppr.conf
Labels: p0_test

#52853 [fix](ci) adjust docker image
  regression-test/pipeline/performance/compile.sh
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x

#52900 [fix](case) fix case bug
  regression-test/suites/temp_table_p0/test_temp_table.groovy
Labels: approved, reviewed, dev/3.1.x, p0_test

#52743 [test](case) add some test case for coverage of BE code
  be/src/vec/data_types/serde/data_type_struct_serde.cpp
  be/src/vec/data_types/serde/data_type_struct_serde.h
  be/test/vec/data_types/data_type_struct_test.cpp
  be/test/vec/data_types/serde/data_type_serde_timev2_test.cpp
  regression-test/data/json_p0/test_json_predict_is_null.out
  regression-test/data/nereids_p0/sql_functions/table_function/explode_map.out
  regression-test/data/nereids_p0/sql_functions/table_function/posexplode.out
  regression-test/data/nereids_syntax_p0/lateral_view.out
  regression-test/data/query_p0/sql_functions/table_function/explode_json_array.out
  regression-test/suites/json_p0/test_json_predict_is_null.groovy
  regression-test/suites/nereids_p0/sql_functions/table_function/explode_map.groovy
  regression-test/suites/nereids_p0/sql_functions/table_function/posexplode.groovy
  regression-test/suites/nereids_syntax_p0/lateral_view.groovy
  regression-test/suites/query_p0/sql_functions/table_function/explode_json_array.groovy
Labels: approved, reviewed

#52997 [Bug](window) fix window function can't return NULL value
  be/src/vec/aggregate_functions/aggregate_function_null.h
  regression-test/data/query_p0/sql_functions/window_functions/test_sum.out
  regression-test/suites/query_p0/sql_functions/window_functions/test_sum.groovy
Labels: approved, reviewed

#53015 [feat](json) new version of JsonObject
  be/src/vec/functions/function_json.cpp
  be/src/vec/functions/function_jsonb.cpp
  fe/fe-core/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/BuiltinScalarFunctions.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/ExpressionRuleType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/JsonFunctionRewrite.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/JsonObject.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/util/TypeCoercionUtils.java
  regression-test/data/ddl_p0/test_ctas.out
  regression-test/data/nereids_p0/create_table/test_ctas.out
  regression-test/data/query_p0/sql_functions/json_function/test_query_json_object.out
  regression-test/suites/nereids_p0/sql_functions/json_function/test_query_json_object.groovy
  regression-test/suites/query_p0/sql_functions/json_function/test_query_json_object.groovy
Labels: approved, reviewed

#52898 [feat](cloud) add versioned_put/get/get_range/remove function
  cloud/src/meta-store/CMakeLists.txt
  cloud/src/meta-store/codec.cpp
  cloud/src/meta-store/codec.h
  cloud/src/meta-store/document_message.cpp
  cloud/src/meta-store/mem_txn_kv.cpp
  cloud/src/meta-store/versioned_value.cpp
  cloud/src/meta-store/versioned_value.h
  cloud/src/meta-store/versionstamp.h
  cloud/test/CMakeLists.txt
  cloud/test/document_message_test.cpp
  cloud/test/versioned_value_test.cpp
Labels: approved, reviewed, cloud, snapshot

#53052 [chore](cloud) remove versionstamp from the key creation functions
  cloud/src/meta-store/keys.cpp
  cloud/src/meta-store/keys.h
  cloud/test/keys_test.cpp
Labels: approved, reviewed, cloud, snapshot

#52915 [fix](test) Avoid the configuration item disable_datev1 affecting other test cases
  regression-test/suites/bloom_filter_p0/test_bloom_filter.groovy
  regression-test/suites/query_p0/sql_functions/conditional_functions/test_coalesce_new.groovy
Labels: approved, reviewed

#52885 [feature](regression) add waitUntilSafeExecutionTime function to framework
  regression-test/framework/src/main/groovy/org/apache/doris/regression/suite/Suite.groovy
  regression-test/suites/external_table_p0/info_schema_db/test_information_schema_timezone.groovy
Labels: approved, reviewed

#53068 [Chore](function) remove some unused code about functions and add some case
  be/src/vec/functions/function.cpp
  be/src/vec/functions/function.h
  be/src/vec/functions/function_cast.h
  be/src/vec/functions/function_java_udf.h
  be/src/vec/functions/function_size.cpp
  be/test/vec/function/function_ip_dict_test.cpp
  regression-test/suites/query_p0/system/test_query_sys.groovy
Labels: approved, reviewed

#53041 [chore](function) function catch std:: exception
  be/src/vec/functions/function.h
  be/test/vec/function/function_throw_exception_test.cpp
Labels: approved, reviewed

#51676 [fix](mow) remove checker code for enable_delete_bitmap_merge_on_compaction
  cloud/src/common/config.h
  cloud/src/recycler/checker.cpp
  cloud/src/recycler/checker.h
  cloud/test/recycler_test.cpp
Labels: approved, reviewed, dev/3.1.x

#52934 [fix](regression) update case huge_compound.groovy
  regression-test/suites/nereids_p0/huge_compound/huge_compound.groovy
Labels: approved, reviewed

#53051 [fix](nereids)should distinguish hash and other conjuncts for outer join in MultiJoin
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/MultiJoin.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/ReorderJoin.java
  regression-test/suites/nereids_p0/join/test_many_multi_join.groovy
Labels: approved, reviewed, p0_b, dev/2.1.x, dev/3.0.x, dev/3.1.x

#53048 [Chore](function) Improve the code coverage of function_json.cpp
  be/src/vec/functions/function_json.cpp
  regression-test/data/query_p0/sql_functions/json_functions/test_json_function.out
  regression-test/suites/query_p0/sql_functions/json_functions/test_json_function.groovy
Labels: approved, reviewed

#52911 [fix](job) use cluster name rather than cluster id to find available be
  fe/fe-core/src/main/java/org/apache/doris/cloud/load/CloudRoutineLoadManager.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/KafkaTaskInfo.java
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadJob.java
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x

#53038 [fix](job) fix show routine load job result incorrect after alter job property
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadJob.java
  regression-test/suites/load_p0/routine_load/test_routine_load.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.1.x

#52983 [feat](fe) Upgrade azure.sdk.version from 1.2.30 to 1.2.36
  fe/pom.xml
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x, cloud

#52280 [fix](cloud)fix tablet_path when rowset is null
  be/src/cloud/cloud_tablet.cpp
  be/src/cloud/cloud_tablet.h
  be/src/olap/base_tablet.h
  be/src/olap/tablet.h
Labels: approved, reviewed, dev/3.0.x

#52882 [enhance](meta-service)add bvar for fdb process status
  cloud/src/common/bvars.cpp
  cloud/src/common/bvars.h
  cloud/src/common/metric.cpp
  cloud/test/metric_test.cpp
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x, cloud

#52514 branch-3.0: [feature](cloud) support event driven or periodic warm up #52370
  be/src/cloud/cloud_backend_service.cpp
  be/src/cloud/cloud_internal_service.cpp
  be/src/cloud/cloud_internal_service.h
  be/src/cloud/cloud_meta_mgr.cpp
  be/src/cloud/cloud_meta_mgr.h
  be/src/cloud/cloud_tablet.cpp
  be/src/cloud/cloud_tablet.h
  be/src/cloud/cloud_warm_up_manager.cpp
  be/src/cloud/cloud_warm_up_manager.h
  be/src/cloud/config.cpp
  be/src/cloud/config.h
  be/src/common/config.h
  be/src/io/cache/block_file_cache_downloader.cpp
  be/src/olap/rowset/rowset_meta.cpp
  be/src/olap/rowset/rowset_meta.h
  fe/fe-common/src/main/java/org/apache/doris/common/Config.java
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowCloudWarmUpStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/WarmUpClusterStmt.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/CacheHotspotManager.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/CloudWarmUpJob.java
  fe/fe-core/src/main/java/org/apache/doris/metric/CloudMetrics.java
  fe/fe-core/src/main/java/org/apache/doris/metric/DorisMetricRegistry.java
  fe/fe-core/src/main/java/org/apache/doris/metric/MetricRepo.java
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  fe/fe-core/src/test/java/org/apache/doris/persist/ModifyCloudWarmUpJobTest.java
  gensrc/proto/internal_service.proto
  gensrc/thrift/BackendService.thrift
  gensrc/thrift/FrontendService.thrift
  regression-test/suites/cloud_p0/cache/multi_cluster/warm_up/cluster/test_warm_up_cluster.groovy
  regression-test/suites/cloud_p0/cache/multi_cluster/warm_up/cluster/test_warm_up_cluster_batch.groovy
  regression-test/suites/cloud_p0/cache/multi_cluster/warm_up/cluster/test_warm_up_cluster_bigsize.groovy
  regression-test/suites/cloud_p0/cache/multi_cluster/warm_up/cluster/test_warm_up_cluster_empty.groovy
  regression-test/suites/cloud_p0/cache/multi_cluster/warm_up/cluster/test_warm_up_cluster_event.groovy
  regression-test/suites/cloud_p0/cache/multi_cluster/warm_up/cluster/test_warm_up_cluster_event_add_new_be.groovy
  regression-test/suites/cloud_p0/cache/multi_cluster/warm_up/cluster/test_warm_up_cluster_event_cancel_active.groovy
  regression-test/suites/cloud_p0/cache/multi_cluster/warm_up/cluster/test_warm_up_cluster_event_cancel_passive.groovy
  regression-test/suites/cloud_p0/cache/multi_cluster/warm_up/cluster/test_warm_up_cluster_event_compaction.groovy
  regression-test/suites/cloud_p0/cache/multi_cluster/warm_up/cluster/test_warm_up_cluster_event_rename.groovy
  regression-test/suites/cloud_p0/cache/multi_cluster/warm_up/cluster/test_warm_up_cluster_event_restart_all_be.groovy
  regression-test/suites/cloud_p0/cache/multi_cluster/warm_up/cluster/test_warm_up_cluster_event_restart_master_fe.groovy
  regression-test/suites/cloud_p0/cache/multi_cluster/warm_up/cluster/test_warm_up_cluster_event_schema_change.groovy
  regression-test/suites/cloud_p0/cache/multi_cluster/warm_up/cluster/test_warm_up_cluster_periodic.groovy
  regression-test/suites/cloud_p0/cache/multi_cluster/warm_up/cluster/test_warm_up_cluster_periodic_add_new_be.groovy
  regression-test/suites/cloud_p0/cache/multi_cluster/warm_up/cluster/test_warm_up_cluster_periodic_and_event.groovy
  regression-test/suites/cloud_p0/cache/multi_cluster/warm_up/cluster/test_warm_up_cluster_periodic_rename.groovy
  regression-test/suites/cloud_p0/cache/multi_cluster/warm_up/cluster/test_warm_up_cluster_periodic_restart_master_fe.groovy
  regression-test/suites/cloud_p0/cache/multi_cluster/warm_up/cluster/test_warm_up_cluster_periodic_slow_job.groovy
  regression-test/suites/cloud_p0/cache/multi_cluster/warm_up/cluster/test_warm_up_cluster_repeat_jobs.groovy
  regression-test/suites/cloud_p0/cache/multi_cluster/warm_up/cluster/test_warm_up_compute_group.groovy
  regression-test/suites/cloud_p0/cache/multi_cluster/warm_up/table/test_warm_up_partition.groovy
  regression-test/suites/cloud_p0/cache/multi_cluster/warm_up/table/test_warm_up_table.groovy
  regression-test/suites/cloud_p0/cache/multi_cluster/warm_up/table/test_warm_up_tables.groovy
Labels: approved, reviewed

#52696 [fix](variant)fix variant type conflicts in nested types
  be/src/vec/columns/column_variant.cpp
  be/src/vec/columns/column_variant.h
  be/src/vec/data_types/convert_field_to_type.cpp
  be/src/vec/functions/function_cast.h
  be/src/vec/json/json_parser.cpp
  be/src/vec/json/json_parser.h
  be/test/vec/function/cast/function_variant_cast_test.cpp
  be/test/vec/jsonb/convert_field_to_type_test.cpp
  be/test/vec/jsonb/json_parser_test.cpp
  regression-test/data/variant_p0/desc.out
  regression-test/data/variant_p0/load.out
  regression-test/data/variant_p0/nested2.out
  regression-test/suites/variant_p0/nested2.groovy
Labels: approved, reviewed, p0_b, dev/3.0.x, dev/3.1.x

#53081 [fix](httpserver) Fix lsan check error when stop libevent server
  be/src/http/ev_http_server.cpp
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x, dev/3.1.x

#52430 [enhance](meta-service)collect fdb kv meta range info as metrics
  cloud/src/common/bvars.cpp
  cloud/src/common/bvars.h
  cloud/src/common/metric.cpp
  cloud/src/common/metric.h
  cloud/src/meta-service/meta_service_http.cpp
  cloud/src/meta-store/keys.cpp
Labels: approved, reviewed, dev/3.0.x, dev/3.1.x, cloud

#53066 [opt](nereids) use one phase aggregate for group_concat with order
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/PhysicalPlanTranslator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/glue/translator/PlanTranslatorContext.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/implementation/AggregateStrategies.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/AggregateFunction.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/agg/GroupConcat.java
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
  regression-test/suites/nereids_syntax_p0/group_concat.groovy
Labels: approved, reviewed, usercase

#52243 [Exec](meta) Support set propertiy dict_page_size by create table
  be/src/cloud/pb_convert.cpp
  be/src/olap/rowset/segment_v2/binary_dict_page.cpp
  be/src/olap/rowset/segment_v2/column_writer.cpp
  be/src/olap/rowset/segment_v2/column_writer.h
  be/src/olap/rowset/segment_v2/options.h
  be/src/olap/rowset/segment_v2/segment_writer.cpp
  be/src/olap/rowset/segment_v2/vertical_segment_writer.cpp
  be/src/olap/tablet_meta.cpp
  be/src/olap/tablet_schema.cpp
  be/src/olap/tablet_schema.h
  fe/fe-core/src/main/java/org/apache/doris/alter/CloudRollupJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/alter/CloudSchemaChangeJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/alter/RollupJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/alter/SchemaChangeJobV2.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/ModifyTablePropertiesClause.java
  fe/fe-core/src/main/java/org/apache/doris/backup/RestoreJob.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/OlapTable.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/TableProperty.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/datasource/CloudInternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/PropertyAnalyzer.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/InternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/master/ReportHandler.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/ModifyTablePropertiesOp.java
  fe/fe-core/src/main/java/org/apache/doris/task/CreateReplicaTask.java
  fe/fe-core/src/test/java/org/apache/doris/common/PropertyAnalyzerTest.java
  fe/fe-core/src/test/java/org/apache/doris/task/AgentTaskTest.java
  gensrc/proto/olap_file.proto
  gensrc/thrift/AgentService.thrift
  regression-test/data/query_p0/system/test_table_properties.out
Labels: approved, reviewed, dev/3.1.x

#52896 [Fix](function) fix wrong time to datetime cast in FE constant folding
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/TimeV2Literal.java
  regression-test/suites/correctness/test_cast_time_to_datetime.groovy
Labels: approved, reviewed

#52812 [Fix](Clone) Fix compaction and mow failure when missing rowset
  be/src/agent/agent_server.cpp
  be/src/agent/task_worker_pool.cpp
  be/src/agent/task_worker_pool.h
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/olap/cumulative_compaction.cpp
  be/src/olap/storage_engine.cpp
  be/src/olap/storage_engine.h
  be/src/olap/task/engine_clone_task.cpp
  be/src/olap/task/engine_publish_version_task.cpp
  be/src/util/blocking_priority_queue.hpp
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  gensrc/thrift/Types.thrift
  regression-test/suites/fault_injection_p0/test_compaction_clone_missing_rowset_fault_injection.groovy
  regression-test/suites/fault_injection_p0/test_mow_publish_clone_missing_rowset.groovy
Labels: approved, reviewed, usercase, dev/2.1.x, dev/3.0.x, dev/3.1.x

#53028 [fix](regression) fix unstable test_iceberg_sys_table.groovy
  regression-test/data/external_table_p0/iceberg/test_iceberg_sys_table.out
  regression-test/suites/external_table_p0/iceberg/test_iceberg_sys_table.groovy
Labels: approved, reviewed, dev/3.1.x

#53115 [fix](test) fix test_routine_load_timeout_value unstable
  regression-test/suites/load_p0/routine_load/test_routine_load_timeout_value.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x, dev/3.1.x, p0_test

#53137 [fix](iceberg) Fix s3tables system table
  fe/be-java-extensions/iceberg-metadata-scanner/pom.xml
  fe/be-java-extensions/iceberg-metadata-scanner/src/main/java/org/apache/doris/datasource/iceberg/s3tables/CustomAwsCredentialsProvider.java
  fe/be-java-extensions/preload-extensions/pom.xml
  regression-test/data/external_table_p0/iceberg/test_iceberg_equality_delete.out
  regression-test/data/external_table_p2/iceberg/test_s3tables_write_partitions.out
  regression-test/suites/external_table_p0/iceberg/iceberg_query_tag_branch.groovy
  regression-test/suites/external_table_p0/iceberg/test_iceberg_equality_delete.groovy
  regression-test/suites/external_table_p0/iceberg/test_iceberg_position_delete.groovy
  regression-test/suites/external_table_p2/iceberg/test_s3tables_write_partitions.groovy
Labels: approved, reviewed, dev/3.1.x
