Repository apache/doris, pull requests merged in 2025-06, with the labels that each got.

#51387 [fix](compaction) Add read lock for compaction score calculation
  be/src/olap/base_tablet.cpp
Labels: approved, reviewed, dev/3.0.x

#51371 [enhancement](time_series) increase the version limit for the time series table
  be/src/agent/task_worker_pool.cpp
  be/src/cloud/cloud_delete_task.cpp
  be/src/cloud/cloud_rowset_builder.cpp
  be/src/cloud/cloud_tablet_mgr.cpp
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/olap/base_tablet.cpp
  be/src/olap/base_tablet.h
  be/src/olap/olap_server.cpp
  be/src/olap/push_handler.cpp
  be/src/olap/rowset_builder.cpp
Labels: approved, reviewed, usercase, dev/2.1.x, dev/3.0.x

#51377 [fix](cloud) Fix cloud fe cluster metrics not registered in FOLLOWER
  fe/fe-core/src/main/java/org/apache/doris/cloud/catalog/CloudClusterChecker.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/system/CloudSystemInfoService.java
Labels: approved, reviewed, dev/3.0.x, cloud

#51380 [Chore](case) adjust test_insert_limit
  regression-test/data/query_p1/test_insert_limit.out
  regression-test/suites/query_p1/test_insert_limit.groovy
Labels: approved, reviewed

#50453 [bugfix](fold) Skip constant folding in from_base64 function to fix binary data handling
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/expression/rules/FoldConstantRuleOnBE.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/expressions/LiteralTest.java
Labels: approved, reviewed, p0_w, dev/2.1.x, dev/3.0.x

#51234 [fix](nereids) fix sum0 cannot pass multi distinct check
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/CheckMultiDistinct.java
  regression-test/data/nereids_syntax_p0/analyze_agg.out
  regression-test/suites/nereids_syntax_p0/analyze_agg.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#51354 [opt](nereids) avoid printing duplicated table stats in profile
  fe/fe-core/src/main/java/org/apache/doris/common/profile/Profile.java
Labels: approved, reviewed, dev/3.0.x

#51397 [improvment](show)support jobid in show export
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ShowExportCommand.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/commands/ShowExportCommandTest.java
  regression-test/suites/nereids_p0/show/test_nereids_show_export.groovy
Labels: approved, reviewed

#51437 [regression-test](cases) fix global vars
  regression-test/suites/account_p0/test_alter_user.groovy
  regression-test/suites/alter_p2/test_alter_table_property.groovy
  regression-test/suites/compaction/test_cu_compaction_remove_old_version_delete_bitmap.groovy
  regression-test/suites/fault_injection_p0/partial_update/test_partial_update_publish_conflict_with_error.groovy
  regression-test/suites/fault_injection_p0/test_calc_crc_fault_injection.groovy
  regression-test/suites/fault_injection_p0/test_full_compaciton_run_status.groovy
  regression-test/suites/fault_injection_p0/test_memtable_flush_is_high_priority_for_vtablet_writerV2.groovy
  regression-test/suites/fault_injection_p0/test_memtable_flush_is_high_priority_for_vtablet_writerv1_fault_injection.groovy
  regression-test/suites/fault_injection_p0/test_segcompaction_fault_injection.groovy
  regression-test/suites/fault_injection_p0/test_too_many_segments_fault_injection.groovy
  regression-test/suites/fault_injection_p0/test_variant_bloom_filter.groovy
  regression-test/suites/inverted_index_p0/array_contains/test_index_compaction_with_multi_index_segments_arr.groovy
  regression-test/suites/inverted_index_p0/index_compaction/test_index_compaction_empty_segments.groovy
  regression-test/suites/inverted_index_p0/index_compaction/test_index_compaction_p0.groovy
  regression-test/suites/inverted_index_p0/test_index_like_select.groovy
  regression-test/suites/inverted_index_p1/index_compaction/test_index_compaction_p1.groovy
  regression-test/suites/inverted_index_p2/show_data/test_show_index_data_p2.groovy
  regression-test/suites/inverted_index_p2/test_show_data.groovy
  regression-test/suites/load_p0/spark_load/test_spark_load.groovy
  regression-test/suites/load_p2/broker_load/test_broker_load.groovy
  regression-test/suites/schema_change_p2/test_schema_change.groovy
  regression-test/suites/ssb_sf1_p2/nereids/q1.1.groovy
  regression-test/suites/ssb_sf1_p2/nereids/q1.2.groovy
  regression-test/suites/ssb_sf1_p2/nereids/q1.3.groovy
  regression-test/suites/ssb_sf1_p2/nereids/q2.1.groovy
  regression-test/suites/ssb_sf1_p2/nereids/q2.2.groovy
  regression-test/suites/ssb_sf1_p2/nereids/q2.3.groovy
  regression-test/suites/ssb_sf1_p2/nereids/q3.1.groovy
  regression-test/suites/ssb_sf1_p2/nereids/q3.2.groovy
  regression-test/suites/ssb_sf1_p2/nereids/q3.3.groovy
  regression-test/suites/ssb_sf1_p2/nereids/q3.4.groovy
  regression-test/suites/ssb_sf1_p2/nereids/q4.1.groovy
  regression-test/suites/ssb_sf1_p2/nereids/q4.2.groovy
  regression-test/suites/ssb_sf1_p2/nereids/q4.3.groovy
  regression-test/suites/tpcds_sf1_unique_ck_p1/query46.groovy
Labels: approved, reviewed

#51450 [regression-test](cases) remove unused case
  regression-test/data/inverted_index_p0/test_index_like_select.out
  regression-test/suites/inverted_index_p0/test_index_like_select.groovy
Labels: approved, reviewed, dev/3.0.x, p0_test

#51432 [fix](log) fix http stream exception log
  fe/fe-core/src/main/java/org/apache/doris/service/FrontendServiceImpl.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/GroupCommitTableValuedFunction.java
  regression-test/suites/insert_p0/insert_group_commit_into.groovy
Labels: approved, reviewed, dev/3.0.x, p0_test

#51458 [regression-test](cases) update variant_p2 result
  regression-test/data/variant_p2/load.out
  regression-test/data/variant_p2/sql/authorsWithTheMostPushes.out
  regression-test/data/variant_p2/sql/countingStar1.out
  regression-test/data/variant_p2/sql/countingStar2.out
  regression-test/data/variant_p2/sql/countingStar3.out
  regression-test/data/variant_p2/sql/distributionOfRepositoriesByStarCount.out
  regression-test/data/variant_p2/sql/howHasTheListOfTopRepositoriesChangedOverTheYears1.out
  regression-test/data/variant_p2/sql/howHasTheListOfTopRepositoriesChangedOverTheYears2.out
  regression-test/data/variant_p2/sql/howHasTheListOfTopRepositoriesChangedOverTheYears3.out
  regression-test/data/variant_p2/sql/howHasTheListOfTopRepositoriesChangedOverTheYears4.out
  regression-test/data/variant_p2/sql/howHasTheListOfTopRepositoriesChangedOverTheYears5.out
  regression-test/data/variant_p2/sql/howHasTheListOfTopRepositoriesChangedOverTheYears6.out
  regression-test/data/variant_p2/sql/howHasTheTotalNumberOfStarsChangedOverTime.out
  regression-test/data/variant_p2/sql/issuesWithTheMostComments1.out
  regression-test/data/variant_p2/sql/issuesWithTheMostComments2.out
  regression-test/data/variant_p2/sql/issuesWithTheMostComments3.out
  regression-test/data/variant_p2/sql/issuesWithTheMostComments4.out
  regression-test/data/variant_p2/sql/issuesWithTheMostComments5.out
  regression-test/data/variant_p2/sql/issuesWithTheMostComments6.out
  regression-test/data/variant_p2/sql/issuesWithTheMostComments7.out
  regression-test/data/variant_p2/sql/mostForkedRepositories.out
  regression-test/data/variant_p2/sql/organizationsByTheNumberOfRepositories.out
  regression-test/data/variant_p2/sql/organizationsByTheNumberOfStars.out
  regression-test/data/variant_p2/sql/organizationsByTheSizeOfCommunity.out
  regression-test/data/variant_p2/sql/proportionsBetweenStarsAndForks1.out
  regression-test/data/variant_p2/sql/proportionsBetweenStarsAndForks2.out
  regression-test/data/variant_p2/sql/proportionsBetweenStarsAndForks3.out
  regression-test/data/variant_p2/sql/proportionsBetweenStarsAndForks4.out
  regression-test/data/variant_p2/sql/proportionsBetweenStarsAndForks5.out
  regression-test/data/variant_p2/sql/repositoriesWithClickhouse_related_comments2.out
  regression-test/data/variant_p2/sql/repositoriesWithTheMaximumAmountOfIssues1.out
  regression-test/data/variant_p2/sql/repositoriesWithTheMaximumAmountOfIssues2.out
  regression-test/data/variant_p2/sql/repositoriesWithTheMaximumAmountOfIssues3.out
  regression-test/data/variant_p2/sql/repositoriesWithTheMaximumAmountOfIssues4.out
  regression-test/data/variant_p2/sql/repositoriesWithTheMaximumAmountOfPullRequests2.out
  regression-test/data/variant_p2/sql/repositoriesWithTheMaximumNumberOfAcceptedInvitations.out
  regression-test/data/variant_p2/sql/repositoriesWithTheMostPeopleWhoHavePushAccess1.out
  regression-test/data/variant_p2/sql/repositoriesWithTheMostPeopleWhoHavePushAccess2.out
  regression-test/data/variant_p2/sql/repositoriesWithTheMostPeopleWhoHavePushAccess3.out
  regression-test/data/variant_p2/sql/repositoriesWithTheMostStarsOverOneDay1.out
  regression-test/data/variant_p2/sql/repositoriesWithTheMostStarsOverOneDay2.out
  regression-test/data/variant_p2/sql/repositoriesWithTheMostStarsOverOneDay3.out
  regression-test/data/variant_p2/sql/repositoriesWithTheWorstStagnation_order.out
  regression-test/data/variant_p2/sql/repositoryAffinityList2.out
  regression-test/data/variant_p2/sql/sql02.out
  regression-test/data/variant_p2/sql/sql03.out
  regression-test/data/variant_p2/sql/sql06.out
  regression-test/data/variant_p2/sql/theLongestRepositoryNames2.out
  regression-test/data/variant_p2/sql/theMostToughCodeReviews.out
  regression-test/data/variant_p2/sql/theTotalNumberOfRepositoriesOnGithub.out
  regression-test/data/variant_p2/sql/theTotalNumberOfUsersOnGithub1.out
  regression-test/data/variant_p2/sql/theTotalNumberOfUsersOnGithub2.out
  regression-test/data/variant_p2/sql/theTotalNumberOfUsersOnGithub3.out
  regression-test/data/variant_p2/sql/theTotalNumberOfUsersOnGithub4.out
  regression-test/data/variant_p2/sql/topRepositoriesByStars.out
  regression-test/data/variant_p2/sql/whatIsTheBestDayOfTheWeekToCatchAStar.out
  regression-test/data/variant_p2/sql/whoAreAllThosePeopleGivingStars1.out
Labels: approved, reviewed

#51464 [regression-test](fix) global vars
  regression-test/suites/inverted_index_p2/test_show_data.groovy
Labels: approved, reviewed

#51420 [fix](arrow) Fix `convert_to_arrow_type` return error
  be/src/util/arrow/row_batch.cpp
Labels: approved, reviewed

#51419 [refactor](decimal) Replace template arg of DataTypeDecimal
  be/src/runtime/primitive_type.h
  be/src/util/string_parser.hpp
  be/src/vec/aggregate_functions/aggregate_function_avg.h
  be/src/vec/columns/column.h
  be/src/vec/columns/column_vector.cpp
  be/src/vec/core/call_on_type_index.h
  be/src/vec/core/decimal_comparison.h
  be/src/vec/core/field.cpp
  be/src/vec/data_types/data_type_decimal.cpp
  be/src/vec/data_types/data_type_decimal.h
  be/src/vec/data_types/data_type_factory.cpp
  be/src/vec/data_types/serde/data_type_decimal_serde.cpp
  be/src/vec/data_types/serde/data_type_decimal_serde.h
  be/src/vec/exec/format/column_type_convert.h
  be/src/vec/exec/format/format_common.h
  be/src/vec/exec/format/orc/vorc_reader.cpp
  be/src/vec/exec/format/orc/vorc_reader.h
  be/src/vec/exec/format/parquet/parquet_pred_cmp.h
  be/src/vec/functions/array/function_array_cum_sum.cpp
  be/src/vec/functions/dictionary.h
  be/src/vec/functions/function_binary_arithmetic.h
  be/src/vec/functions/function_cast.h
  be/src/vec/functions/function_dict_get.cpp
  be/src/vec/functions/function_dict_get_many.cpp
  be/src/vec/functions/function_string.h
  be/src/vec/functions/function_timestamp.cpp
  be/src/vec/functions/function_unary_arithmetic.h
  be/src/vec/functions/round.h
  be/src/vec/sink/vmysql_result_writer.cpp
  be/src/vec/sink/vtablet_block_convertor.cpp
  be/test/olap/rowset/segment_v2/column_reader_writer_test.cpp
  be/test/pipeline/common/distinct_agg_utils_test.cpp
  be/test/pipeline/common/set_utils_test.cpp
  be/test/vec/aggregate_functions/agg_collect_test.cpp
  be/test/vec/aggregate_functions/agg_histogram_test.cpp
  be/test/vec/aggregate_functions/agg_linear_histogram_test.cpp
  be/test/vec/aggregate_functions/agg_min_max_test.cpp
  be/test/vec/aggregate_functions/agg_replace_test.cpp
  be/test/vec/columns/column_hash_func_test.cpp
  be/test/vec/columns/column_resize_test.cpp
  be/test/vec/core/block_test.cpp
  be/test/vec/data_types/data_type_decimal_test.cpp
  be/test/vec/data_types/decimal_test.cpp
  be/test/vec/data_types/serde/data_type_serde_arrow_test.cpp
  be/test/vec/data_types/serde/data_type_serde_decimal_test.cpp
  be/test/vec/exec/column_type_convert_test.cpp
  be/test/vec/exec/orc/orc_reader_fill_data_test.cpp
  be/test/vec/function/cast/cast_to_decimal.cpp
  be/test/vec/function/cast/cast_to_float_double.cpp
  be/test/vec/function/cast/cast_to_integer.cpp
  be/test/vec/function/function_array_element_test.cpp
  be/test/vec/function/function_math_test.cpp
  be/test/vec/function/function_money_format_test.cpp
  be/test/vec/function/function_round_test.cpp
  be/test/vec/function/function_test_util.cpp
  be/test/vec/function/function_test_util.h
  be/test/vec/function/function_time_test.cpp
  be/test/vec/sink/writer/iceberg/partition_transformers_test.cpp
Labels: approved, reviewed

#51449 branch-2.1:[case](auth)fix case test_dml_select_udf_auth
  regression-test/suites/auth_call/test_dml_select_udf_auth.groovy
Labels: approved, reviewed

#51395 [Enhancement](nereids)support show create function
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PlanType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ShowCreateFunctionCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/CommandVisitor.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/commands/ShowCreateFunctionCommandTest.java
  regression-test/suites/nereids_p0/show/test_show_create_function.groovy
Labels: approved, reviewed

#50101 [fix](csv) escape quote with double quote for csv format table
  be/src/vec/data_types/serde/data_type_serde.h
  be/src/vec/data_types/serde/data_type_string_serde.h
  be/src/vec/exec/format/csv/csv_reader.cpp
  be/src/vec/exec/format/file_reader/new_plain_text_line_reader.cpp
  be/src/vec/exec/format/file_reader/new_plain_text_line_reader.h
  be/test/vec/data_types/data_type_string_test.cpp
  be/test/vec/exec/format/file_reader/new_plain_text_line_reader_test.cpp
  docker/thirdparties/docker-compose/hive/scripts/create_preinstalled_scripts/run76.hql
  docker/thirdparties/docker-compose/hive/scripts/preinstalled_data/csv/csv_json_table_simple/csv_json_table_simple.csv
  regression-test/data/external_table_p0/hive/test_hive_serde_prop.out
  regression-test/data/external_table_p0/hive/test_open_csv_serde.out
  regression-test/data/load_p0/broker_load/test_csv_with_enclose_and_escapeS3_load.out
  regression-test/data/load_p0/stream_load/enclose_with_escape_doublequote.csv
  regression-test/data/load_p0/stream_load/enclose_with_escape_quote.csv
  regression-test/data/load_p0/stream_load/test_csv_with_enclose_and_escape.out
  regression-test/suites/external_table_p0/hive/test_open_csv_serde.groovy
  regression-test/suites/load_p0/stream_load/test_csv_with_enclose_and_escape.groovy
Labels: approved, reviewed, usercase, dev/3.0.x

#51428 [Fix](Load) fix load hang when the instance cancel with memory tracker before exe…
  be/src/runtime/plan_fragment_executor.cpp
Labels: approved, reviewed

#51353 [Fix](cloud-mow) Remove potential existing split delete bitmap KVs before update them in schema change
  cloud/src/meta-service/meta_service.cpp
  cloud/src/meta-service/meta_service_job.cpp
  cloud/test/meta_service_job_test.cpp
  cloud/test/meta_service_test.cpp
Labels: approved, reviewed, p0_w, dev/3.0.x

#51342 [Enhancement] (nereids)implement DropViewCommand in nereids
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PlanType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/DropViewCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/CommandVisitor.java
  regression-test/data/ddl_p0/test_drop_view_nereids.out
  regression-test/suites/ddl_p0/test_drop_view_nereids.groovy
Labels: approved, reviewed

#51445 [test](case) Fix instability case caused by fold_constant_by_be.
  regression-test/data/dictionary_p0/test_dict_get_many.out
  regression-test/suites/dictionary_p0/test_dict_get_many.groovy
Labels: approved, reviewed

#51415 [opt](multi-catalog) Optimize remote scan concurrency.
  be/src/pipeline/exec/file_scan_operator.cpp
  be/src/vec/exec/scan/scanner_scheduler.cpp
Labels: approved, reviewed, dev/3.0.x, p0_r

#51145 [enhance](array) array_min/max support array<string>
  be/src/vec/functions/array/function_array_aggregation.cpp
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/ArrayAvg.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/ArrayJoin.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/ArrayProduct.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/functions/scalar/ArraySum.java
  regression-test/data/function_p0/test_array_agg.out
  regression-test/data/variant_p0/test_array_function.out
  regression-test/suites/function_p0/test_array_agg.groovy
  regression-test/suites/variant_p0/test_array_function.groovy
Labels: approved, reviewed, usercase, dev/3.0.x

#51489 [fix](hudi) fix hudi scan problem
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/logical/LogicalHudiScan.java
Labels: approved, reviewed

#51496 [chore](be) fix typo error in config
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/runtime/fragment_mgr.cpp
Labels: approved, reviewed, kind/behavior-changed

#51467 [enhancement](inverted index) ensure consistent ordering of properties for inverted index show
  fe/fe-core/src/main/java/org/apache/doris/catalog/Index.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ShowCreateTableStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/IndexPropertiesOrderTest.java
  fe/fe-core/src/test/java/org/apache/doris/common/proc/IndexesProcNodeTest.java
  regression-test/suites/backup_restore/test_backup_restore_inverted_index.groovy
  regression-test/suites/index_p0/test_index_meta.groovy
Labels: approved, reviewed, kind/behavior-changed

#51512 [fix](beut) fix beut core when input invalid json string
  be/test/vec/function/function_test_util.cpp
Labels: approved, reviewed

#47375 [improve](cloud-mow) reduce ms update_delete_bitmap kv confict
  cloud/src/meta-service/meta_service.cpp
  cloud/src/meta-service/meta_service.h
  cloud/src/meta-service/meta_service_job.cpp
Labels: approved, reviewed, dev/3.0.x

#51461 [regression-test](fix) fix StreamLoadAction bug
  regression-test/framework/src/main/groovy/org/apache/doris/regression/action/StreamLoadAction.groovy
Labels: approved, reviewed

#51094 [Enhancement] (nereids) implement showRoutineLoadTaskCommand in nereids
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PlanType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ShowRoutineLoadTaskCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/CommandVisitor.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/commands/ShowRoutineLoadTaskCommandTest.java
Labels: approved, reviewed

#51508 [fix](iceberg)Fix the thread pool issue used for commit.
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/IcebergMetadataOps.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/iceberg/IcebergTransaction.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#51024 [Enhancement](systable)add information_schema backend_configuration table
  be/src/exec/schema_scanner.cpp
  be/src/exec/schema_scanner/schema_backend_configuration_scanner.cpp
  be/src/exec/schema_scanner/schema_backend_configuration_scanner.h
  fe/fe-core/src/main/java/org/apache/doris/analysis/SchemaTableType.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/SchemaTable.java
  fe/fe-core/src/main/java/org/apache/doris/planner/BackendPartitionedSchemaScanNode.java
  gensrc/thrift/Descriptors.thrift
  regression-test/suites/external_table_p0/info_schema_db/test_backend_configuration.groovy
Labels: approved, reviewed, dev/3.0.x

#51421 [Opt](bvar) Add bvar for cloud mow tablet compaction get delete bitmap lock time
  be/src/cloud/cloud_tablet.cpp
Labels: approved, reviewed

#51470 [chore](be) modify seek to postition method in be to return correct error status
  be/src/olap/rowset/segment_v2/binary_plain_page.h
  be/src/olap/rowset/segment_v2/binary_prefix_page.cpp
  be/src/olap/rowset/segment_v2/bitshuffle_page.h
  be/src/olap/rowset/segment_v2/column_reader.cpp
  be/src/olap/rowset/segment_v2/column_reader.h
  be/src/olap/rowset/segment_v2/frame_of_reference_page.h
  be/src/olap/rowset/segment_v2/page_decoder.h
  be/src/olap/rowset/segment_v2/plain_page.h
  be/src/olap/rowset/segment_v2/rle_page.h
Labels: approved, reviewed

#51518 [Bug](fix) try to fix double free materialization status
  be/src/pipeline/dependency.h
  be/src/pipeline/exec/materialization_sink_operator.cpp
  be/src/pipeline/exec/materialization_source_operator.cpp
Labels: approved, reviewed

#51300 [Refactor](Jsonb) Refactor the JsonBinaryValue and remove unnecessary files.
  be/src/exec/es/es_scroll_parser.cpp
  be/src/runtime/jsonb_value.cpp
  be/src/runtime/jsonb_value.h
  be/src/util/jsonb_error.h
  be/src/util/jsonb_parser_simd.h
  be/src/util/jsonb_updater.h
  be/src/vec/columns/column_variant.cpp
  be/src/vec/data_types/data_type_jsonb.cpp
  be/src/vec/data_types/data_type_jsonb.h
  be/src/vec/data_types/serde/data_type_jsonb_serde.cpp
  be/src/vec/data_types/serde/data_type_object_serde.cpp
  be/src/vec/functions/function_json.cpp
  be/src/vec/functions/function_jsonb.cpp
  be/test/runtime/jsonb_value_test.cpp
  be/test/util/jsonb_parser_simd_test.cpp
  be/test/vec/function/function_test_util.cpp
Labels: approved, reviewed

#50671 [Enhancement] (nereids) implement cancelDecommissionBackend in nereids
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/alter/SystemHandler.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PlanType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/CancelDecommissionBackendCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/CommandVisitor.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/commands/CancelDecommissionBackendCommandTest.java
  regression-test/suites/auth_p0/test_cancel_alter_system_auth.groovy
Labels: approved, reviewed

#51536 [Chore](nereids) Remove ShowQueryStatsStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowQueryStatsStmt.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
Labels: approved, reviewed

#51182 [fix](test) Fix the unstable test
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/commands/CreateStorageVaultCommandTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/commands/TruncateTableCommandTest.java
Labels: approved, reviewed

#51482 [Fix](Compaction) Fix delete rowset sleeping when compaction
  be/src/cloud/cloud_cumulative_compaction.cpp
  be/src/olap/cumulative_compaction.cpp
  be/src/olap/tablet.cpp
Labels: approved, reviewed

#51433 [fix](case) fix unstable cases
  regression-test/suites/inverted_index_p0/test_is_null_expr.groovy
  regression-test/suites/variant_p0/test_variant_is_null_expr.groovy
Labels: approved, reviewed

#51538 [release](version) bump to 3.0.6
  gensrc/script/gen_build_version.sh
Labels: approved, reviewed

#51554 [chore](tool) fix stream load header
  tools/clickbench-tools/load-clickbench-data.sh
  tools/ssb-tools/bin/load-ssb-data.sh
  tools/tpcds-tools/bin/load-tpcds-data.sh
  tools/tpch-tools/bin/load-tpch-data.sh
Labels: approved, reviewed

#51479 [fix](mow) remove enable_delete_bitmap_merge_on_compaction
  be/src/cloud/cloud_cumulative_compaction.cpp
  be/src/cloud/cloud_cumulative_compaction.h
  be/src/cloud/cloud_meta_mgr.cpp
  be/src/cloud/cloud_meta_mgr.h
  be/src/cloud/cloud_tablet.cpp
  be/src/common/config.cpp
  be/src/common/config.h
  be/src/olap/compaction.cpp
  be/src/olap/compaction.h
  be/src/olap/tablet.cpp
  be/src/olap/tablet_meta.cpp
  be/src/olap/tablet_meta.h
  regression-test/data/compaction/test_cu_compaction_remove_old_version_delete_bitmap.out
  regression-test/data/compaction/test_mow_compaction_and_schema_change.out
  regression-test/suites/compaction/test_cu_compaction_remove_old_version_delete_bitmap.groovy
  regression-test/suites/compaction/test_mow_compaction_and_schema_change.groovy
Labels: approved, reviewed

#51533 [fix](decimal)Fix the issue where decimal multiplication produces incorrect results due to mul_overflow error
  be/src/vec/common/arithmetic_overflow.h
  be/test/common/check_overflow.cpp
  regression-test/data/datatype_p0/decimalv3/test_decimalv3_cast3.out
  regression-test/suites/datatype_p0/decimalv3/test_decimalv3_cast3.groovy
Labels: approved, reviewed

#51096 [Enhancement] (nereids) implement showRoutineLoadCommand in nereids
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PlanType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ShowRoutineLoadCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/CommandVisitor.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/commands/ShowRoutineLoadCommandTest.java
Labels: approved, reviewed

#51549 [Chore](nereids) Remove ShowCatalogRecycleBinStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowCatalogRecycleBinStmt.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
Labels: approved, reviewed

#51497 [regression-test](fix) fix tpcds q24 query and result
  regression-test/data/inverted_index_p1/tpcds_sf1_index/sql/q24_1.out
  regression-test/data/inverted_index_p1/tpcds_sf1_index/sql/q24_2.out
  regression-test/data/tpcds_sf100_dup_without_key_p2/sql/q24_1.out
  regression-test/data/tpcds_sf100_dup_without_key_p2/sql/q24_2.out
  regression-test/data/tpcds_sf100_p2/sql/q24_1.out
  regression-test/data/tpcds_sf100_p2/sql/q24_2.out
  regression-test/data/tpcds_sf1_p1/sql/q24_1.out
  regression-test/data/tpcds_sf1_p1/sql/q24_2.out
  regression-test/data/tpcds_sf1_unique_ck_p1/sql/q24_1.out
  regression-test/data/tpcds_sf1_unique_ck_p1/sql/q24_2.out
  regression-test/data/tpcds_sf1_unique_p1/sql/q24_1.out
  regression-test/data/tpcds_sf1_unique_p1/sql/q24_2.out
  regression-test/suites/inverted_index_p1/tpcds_sf1_index/sql/q24_1.sql
  regression-test/suites/inverted_index_p1/tpcds_sf1_index/sql/q24_2.sql
  regression-test/suites/tpcds_sf100_dup_without_key_p2/sql/q24_1.sql
  regression-test/suites/tpcds_sf100_dup_without_key_p2/sql/q24_2.sql
  regression-test/suites/tpcds_sf100_p2/sql/q24_1.sql
  regression-test/suites/tpcds_sf100_p2/sql/q24_2.sql
  regression-test/suites/tpcds_sf1_p1/sql/q24_1.sql
  regression-test/suites/tpcds_sf1_p1/sql/q24_2.sql
  regression-test/suites/tpcds_sf1_unique_ck_p1/sql/q24_1.sql
  regression-test/suites/tpcds_sf1_unique_ck_p1/sql/q24_2.sql
  regression-test/suites/tpcds_sf1_unique_p1/sql/q24_1.sql
  regression-test/suites/tpcds_sf1_unique_p1/sql/q24_2.sql
Labels: approved, reviewed

#51411 [check](cast) add nullable check after cast expr execute
  be/src/vec/exprs/vcast_expr.cpp
Labels: approved, reviewed

#51572 [fix](case)Use relative cooldown time instead of absolute time in storage policy test case
  regression-test/suites/cold_heat_separation/policy/drop.groovy
  regression-test/suites/cold_heat_separation/policy/drop_hdfs_reource.groovy
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#51060 branch-3.0:[improve](nereids)Remove use of session variable deprecated_group_by_and_having_use_alias_first (#51015)
  fe/fe-core/src/main/java/org/apache/doris/analysis/QueryStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/analysis/BindExpression.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/UnsupportedTypeTest.java
Labels: approved, reviewed

#51517 [fix](group commit) replay wal set cloud cluster name
  fe/fe-core/src/main/java/org/apache/doris/load/StreamLoadHandler.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/ExternalFileTableValuedFunction.java
  regression-test/data/cloud_p0/multi_cluster/test_group_commit_replay_wal.csv
  regression-test/suites/cloud_p0/multi_cluster/test_group_commit_replay_wal.groovy
  regression-test/suites/insert_p0/insert_group_commit_into.groovy
Labels: approved, reviewed

#51578 [Chore](nereids) Remove ShowTabletStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowTabletStmt.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/TempPartitionTest.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/TruncateTableTest.java
Labels: approved, reviewed

#51562 [Enhancement](nereids)support show alter table
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/common/proc/RollupProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/common/proc/SchemaChangeProcDir.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PlanType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ShowAlterTableCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/CommandVisitor.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/commands/ShowAlterTableCommandTest.java
  regression-test/suites/nereids_p0/show/test_nereids_show_alter_table.groovy
Labels: approved, reviewed

#51372 [chore](dep)bump up parquet to 1.15.2
  fe/fe-common/pom.xml
  fe/pom.xml
  fe/spark-dpp/pom.xml
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#51463 [fix](cloud) fix file cache types priority order
  be/src/io/cache/file_cache_common.h
  be/test/io/cache/block_file_cache_test.cpp
Labels: approved, reviewed, dev/3.0.x

#51442 [fix](topn)fix external table topn lazy materialize cause be core.
  be/src/exec/rowid_fetcher.cpp
  be/src/olap/id_manager.h
  be/src/pipeline/exec/file_scan_operator.cpp
  be/src/runtime/runtime_state.cpp
  be/src/runtime/runtime_state.h
  be/src/vec/exec/scan/file_scanner.cpp
  be/src/vec/exec/scan/file_scanner.h
Labels: approved, reviewed

#51490 [Opt](log) remove a mow log
  be/src/olap/rowset/beta_rowset_reader.cpp
Labels: approved, reviewed, dev/3.0.x

#51473 [fix](build) fix macOS build
  be/src/vec/exec/format/parquet/vparquet_group_reader.cpp
Labels: approved, reviewed

#51589 [opt](catalog) throw explict error when operation is not supported
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalCatalog.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#51614 [Debug](exec) Add Debug log for topn
  be/src/pipeline/dependency.cpp
  be/src/service/internal_service.cpp
Labels: approved, reviewed

#51558 [clean](planner)stream load task removes dependency on the old optimizer
  fe/fe-core/src/main/java/org/apache/doris/task/StreamLoadTask.java
  fe/fe-core/src/test/java/org/apache/doris/load/sync/canal/CanalSyncDataTest.java
Labels: approved, reviewed

#51606 [Enhancement](nereids)support show type_cast
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PlanType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ShowTypeCastCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/CommandVisitor.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/commands/ShowTypeCastCommandTest.java
  regression-test/suites/nereids_p0/show/test_nereids_show_typecast.groovy
Labels: approved, reviewed

#51267 branch-3.0:[fix](parquet/orc) Disable string dictionary filtering when predicate express is not binary pred and in pred (#50749)
  be/src/vec/exec/format/orc/vorc_reader.cpp
  be/src/vec/exec/format/parquet/vparquet_group_reader.cpp
  regression-test/data/external_table_p0/hive/test_string_dict_filter.out
  regression-test/suites/external_table_p0/hive/test_string_dict_filter.groovy
Labels: approved, reviewed

#51621 [ci](cloud) timeout 2m for stop be grace
  regression-test/pipeline/cloud_p0/clean.sh
  regression-test/pipeline/cloud_p0/run.sh
  regression-test/pipeline/vault_p0/clean.sh
  regression-test/pipeline/vault_p0/run.sh
Labels: approved, reviewed, cloud

#51156 [fix](join)Consider mark join when computing right_col_idx(#50720)
  be/src/pipeline/exec/hashjoin_probe_operator.cpp
  be/src/pipeline/exec/hashjoin_probe_operator.h
  be/src/pipeline/exec/join/process_hash_table_probe.h
  be/src/pipeline/exec/join/process_hash_table_probe_impl.h
  be/src/vec/common/hash_table/join_hash_table.h
  regression-test/data/query_p0/join/mark_join/mark_join.out
  regression-test/data/query_p0/join/mark_join/right_semi_mark_join.out
  regression-test/suites/query_p0/join/mark_join/mark_join.groovy
  regression-test/suites/query_p0/join/mark_join/right_semi_mark_join.groovy
Labels: approved, reviewed

#51628 [fix](memory-leak) skip libzip and libjvm memory leak
  conf/lsan_suppr.conf
Labels: approved, reviewed

#50617 [Enhancement] (nereids)implement adminSetReplicaVersionCommand in nereids
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PlanType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/AdminSetReplicaVersionCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/CommandVisitor.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/commands/AdminSetReplicaVersionCommandTest.java
Labels: approved, reviewed

#51615 [fix](load) fix concurrent read and write to runningTxnIds
  fe/fe-core/src/main/java/org/apache/doris/load/routineload/RoutineLoadStatistic.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#51577 [refactor](type) Add `FIXED_LENGTH_OBJECT` type
  be/src/olap/rowset/segment_v2/column_reader.cpp
  be/src/olap/rowset/segment_v2/column_writer.cpp
  be/src/runtime/define_primitive_type.h
  be/src/vec/data_types/data_type.cpp
  be/src/vec/data_types/data_type.h
  be/src/vec/data_types/data_type_fixed_length_object.h
  be/src/vec/data_types/data_type_nullable.h
  be/src/vec/olap/olap_data_convertor.cpp
  be/test/vec/data_types/common_data_type_test.h
  be/test/vec/data_types/data_type_agg_state_test.cpp
  gensrc/thrift/Types.thrift
Labels: approved, reviewed

#51635 [Chore](nereids) Remove ShowTableStatusStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowTableStatusStmt.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/ColumnPrivTest.java
Labels: approved, reviewed

#51633 [fix](regression-test) fix global var in cases
  regression-test/suites/load_p0/spark_load/test_spark_load.groovy
Labels: approved, reviewed

#51569 [opt](nereids) support extract join multiple tables
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/ExtractSingleTableExpressionFromDisjunction.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/NamedExpression.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/rewrite/ExtractSingleTableExpressionFromDisjunctionTest.java
Labels: approved, reviewed

#51650 [fix](spill) Fix SpillReader read buff use PODArray
  be/src/vec/spill/spill_reader.cpp
  be/src/vec/spill/spill_reader.h
Labels: approved, reviewed

#51642 [Chore](nereids) Remove ShowDataStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowDataStmt.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/ShowDataStmtTest.java
Labels: approved, reviewed

#51588 [Enhancement](nereids)support show index
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PlanType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ShowIndexCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/TableNameInfo.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/CommandVisitor.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/commands/ShowIndexCommandTest.java
  regression-test/suites/nereids_p0/show/test_nereids_show_index.groovy
Labels: approved, reviewed

#50589 [Enhancement] (nereids) implement backupCommand in nereids
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupHandler.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/TableSample.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PlanType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/BackupCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/TableRefInfo.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/CommandVisitor.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/commands/BackupCommandTest.java
Labels: approved, reviewed

#51465 [Refactor]get workload group from compute group
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/AlterWorkloadGroupCommand.java
  fe/fe-core/src/main/java/org/apache/doris/resource/computegroup/AllBackendComputeGroup.java
  fe/fe-core/src/main/java/org/apache/doris/resource/computegroup/CloudComputeGroup.java
  fe/fe-core/src/main/java/org/apache/doris/resource/computegroup/ComputeGroup.java
  fe/fe-core/src/main/java/org/apache/doris/resource/computegroup/MergedComputeGroup.java
  fe/fe-core/src/main/java/org/apache/doris/resource/workloadgroup/WorkloadGroupMgr.java
  fe/fe-core/src/test/java/org/apache/doris/planner/ResourceTagQueryTest.java
  fe/fe-core/src/test/java/org/apache/doris/resource/ComputeGroupTest.java
  fe/fe-core/src/test/java/org/apache/doris/resource/workloadgroup/WorkloadGroupMgrTest.java
Labels: approved, reviewed

#51361 [feature](Cloud) support volcano engine object storage tos
  be/src/io/fs/obj_storage_client.h
  be/src/util/s3_util.cpp
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/constants/S3Properties.java
  gensrc/proto/cloud.proto
  gensrc/thrift/AgentService.thrift
Labels: approved, reviewed

#51414 [feature](Cloud) support volcano engine object storage tos
  be/src/io/fs/obj_storage_client.h
  be/src/util/s3_util.cpp
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/constants/S3Properties.java
  gensrc/proto/cloud.proto
  gensrc/thrift/AgentService.thrift
Labels: approved, reviewed, cloud, dev/3.0.7-merged

#51581 [ci](nonConcurrent) add new ci check
  .github/workflows/comment-to-trigger-teamcity.yml
  regression-test/pipeline/common/teamcity-utils.sh
  regression-test/pipeline/nonConcurrent/conf/be.conf
  regression-test/pipeline/nonConcurrent/conf/fe.conf
  regression-test/pipeline/nonConcurrent/conf/regression-conf.groovy
  regression-test/suites/query_p0/sql_functions/window_functions/test_column_boundary.groovy
Labels: approved, reviewed

#51406 [fix](test) Fix multi check test
  regression-test/plugins/plugin_multi_cluster.groovy
Labels: approved, reviewed

#51162 [feat](cloud) Support alter operation for obj_info and s3 vault obj_info
  cloud/src/meta-service/meta_service_http.cpp
  cloud/src/meta-service/meta_service_resource.cpp
  cloud/test/meta_service_test.cpp
  fe/fe-core/src/main/java/org/apache/doris/catalog/S3StorageVault.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/StorageVault.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/rpc/MetaServiceClient.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/rpc/MetaServiceProxy.java
  gensrc/proto/cloud.proto
  regression-test/suites/aws_iam_role_p0/test_alter_s3_vault_with_role.groovy
  regression-test/suites/cloud_p0/node_mgr/test_ms_alter_obj_info.groovy
  regression-test/suites/cloud_p0/node_mgr/test_ms_alter_s3_vault.groovy
Labels: approved, reviewed

#51647 [fix](trash) Fix shadow variable causing garbage scheduling time errors
  be/src/olap/olap_server.cpp
Labels: approved, reviewed, dev/3.0.x

#51692 [fix](ci) fix syntax error
  regression-test/pipeline/common/teamcity-utils.sh
Labels: approved, reviewed

#51551 [Enchancement](scan) use CpuInfo::num_cores as default max scanners count
  be/src/pipeline/exec/olap_scan_operator.cpp
  fe/fe-core/src/main/java/org/apache/doris/qe/SessionVariable.java
Labels: approved, reviewed

#51637 [fix](cases) global vars
  regression-test/suites/inverted_index_p2/show_data/test_show_index_data_p2.groovy
  regression-test/suites/load_p2/broker_load/test_parquet_large_metadata_load.groovy
  regression-test/suites/unique_with_mow_p2/ssb_unique_load_zstd/one/load_one_step.groovy
  regression-test/suites/unique_with_mow_p2/ssb_unique_load_zstd/two/load_two_step.groovy
Labels: approved, reviewed

#51509 [clean](planner)alias function removes dependency on the old optimizer
  fe/fe-core/src/main/java/org/apache/doris/catalog/AliasFunction.java
Labels: approved, reviewed

#51702 [Fix]quick fix for duplicate wg id
  be/src/runtime/workload_group/workload_group_manager.cpp
Labels: approved, reviewed

#51618 [bug](function) fix array_map cause coredump as NULL
  be/src/vec/exprs/lambda_function/varray_map_function.cpp
  regression-test/data/query_p0/sql_functions/array_functions/test_array_map_function.out
  regression-test/suites/query_p0/sql_functions/array_functions/test_array_map_function.groovy
Labels: approved, reviewed, dev/2.0.x, dev/2.1.x, dev/3.0.x

#51651 [bugfix](query) Fix for incorrect query results of variant type
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/LogicalResultSinkToShortCircuitPointQuery.java
  regression-test/data/point_query_p0/test_point_query.out
  regression-test/data/variant_p0/variant_with_rowstore.out
  regression-test/suites/point_query_p0/test_point_query.groovy
Labels: approved, reviewed, usercase, dev/2.1.x, dev/3.0.x

#51699 [fix](test) fix fe UT failed because of timeout
  fe/fe-core/src/test/java/org/apache/doris/qe/HmsQueryCacheTest.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/MockedFrontend.java
Labels: dev/2.1.11-merged

#51665 [Chore](nereids) Remove ShowColumnHistStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/ShowColumnHistStmt.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
Labels: approved, reviewed

#51546 [fix](nereids) fix cast ipv4 to string
  fe/fe-core/src/main/java/org/apache/doris/common/util/NetUtils.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/expressions/literal/IPv4Literal.java
  fe/fe-core/src/test/java/org/apache/doris/common/util/NetUtilsTest.java
  regression-test/data/nereids_rules_p0/infer_predicate/pull_up_predicate_literal.out
  regression-test/suites/nereids_p0/expression/fold_constant/fold_constant_ip.groovy
Labels: approved, reviewed, p0_w, dev/2.1.x, dev/3.0.x

#51644 [fix](doris-compose) fix docker file create directory
  docker/runtime/doris-compose/Dockerfile
Labels: approved, reviewed

#51743 [be](gracefulexit) should stop async result writer when graceful exit
  be/src/runtime/fragment_mgr.cpp
  be/src/runtime/fragment_mgr.h
  be/src/vec/sink/writer/async_result_writer.cpp
Labels: approved, reviewed

#51741 [Enhancement](nereids)optimize showloadCommand in nereids
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ShowLoadCommand.java
Labels: approved, reviewed

#51659 branch-2.1: [improvement](jdbc catalog) Optimize the acquisition of indentity type in SQLServer
  docker/thirdparties/docker-compose/sqlserver/init/03-create-table.sql
  docker/thirdparties/docker-compose/sqlserver/init/04-insert.sql
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/client/JdbcSQLServerClient.java
  regression-test/data/external_table_p0/jdbc/test_sqlserver_jdbc_catalog.out
  regression-test/suites/external_table_p0/jdbc/test_sqlserver_jdbc_catalog.groovy
Labels: approved, reviewed

#51471 [feat](jdbc) support custom function rules in catalog properties
  fe/fe-core/src/main/java/org/apache/doris/catalog/JdbcResource.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/JdbcTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalDatabase.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/ExternalFunctionRules.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/JdbcExternalCatalog.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/JdbcExternalTable.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/source/JdbcFunctionPushDownRule.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/source/JdbcScanNode.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/ExternalFunctionPushDownRulesTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/ExternalFunctionRewriteRulesTest.java
  regression-test/suites/external_table_p0/jdbc/test_clickhouse_jdbc_catalog.groovy
  regression-test/suites/external_table_p0/jdbc/test_jdbc_query_mysql.groovy
  regression-test/suites/external_table_p0/jdbc/test_mysql_jdbc_catalog.groovy
  regression-test/suites/external_table_p0/jdbc/test_oracle_jdbc_catalog.groovy
Labels: approved, reviewed, usercase, dev/3.0.x

#51703 [Fix]Fix FE send duplicate wg id to BE
  be/src/runtime/workload_group/workload_group_manager.cpp
  fe/fe-core/src/main/java/org/apache/doris/resource/computegroup/AllBackendComputeGroup.java
Labels: approved, reviewed

#51697 [enhancement](log) should print query id when failed to get fragment context
  be/src/runtime/fragment_mgr.cpp
Labels: approved, reviewed

#51368 [Enchancement](sort) optimize for heap sort
  be/src/vec/common/sort/heap_sorter.cpp
  be/src/vec/common/sort/heap_sorter.h
  be/src/vec/common/sort/partition_sorter.cpp
  be/src/vec/common/sort/sorter.cpp
  be/src/vec/common/sort/sorter.h
  be/src/vec/common/sort/topn_sorter.cpp
  be/src/vec/core/sort_cursor.h
  be/src/vec/runtime/vsorted_run_merger.cpp
  be/test/pipeline/operator/sort_operator_test.cpp
  be/test/vec/exec/sort/heap_sorter_test.cpp
  be/test/vec/exec/sort/merge_sorter_state.cpp
  regression-test/data/variant_p0/test_sub_path_pruning.out
  regression-test/data/variant_p0/topn_opt_read_by_rowids.out
  regression-test/suites/variant_p0/test_sub_path_pruning.groovy
  regression-test/suites/variant_p0/topn_opt_read_by_rowids.groovy
Labels: approved, reviewed

#51772 [Fix](Variant) fix potential mem leak in `DataTypeArraySerDe::write_one_cell_to_json`
  be/src/vec/data_types/serde/data_type_array_serde.cpp
  be/src/vec/data_types/serde/data_type_object_serde.cpp
  be/src/vec/data_types/serde/data_type_object_serde.h
Labels: approved, reviewed

#51765 [fix](regress) fix test_simplify_comparison_predicate
  regression-test/suites/nereids_rules_p0/expression/test_simplify_comparison_predicate.groovy
Labels: approved, reviewed

#51736 [Enhancement](nereids)support show load warnings
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PlanType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ShowLoadWarningsCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/CommandVisitor.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/commands/ShowLoadWarningsCommandTest.java
  regression-test/suites/nereids_p0/show/test_nereids_show_load_warnings.groovy
Labels: approved, reviewed

#50277 [Enhancement] (nereids) implement warmUpCluster in nereids
  fe/fe-core/src/main/antlr4/org/apache/doris/nereids/DorisParser.g4
  fe/fe-core/src/main/java/org/apache/doris/cloud/CacheHotspotManager.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/PlanType.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/WarmUpClusterCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/info/WarmUpItem.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/visitor/CommandVisitor.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/commands/WarmUpClusterCommandTest.java
Labels: approved, reviewed

#51720 [opt](community) update keywords
  .asf.yaml
Labels: approved, reviewed

#51752 [fix](feut) fix unstable fe test case DecreaseReplicationNumTest
  fe/fe-core/src/test/java/org/apache/doris/clone/DecreaseReplicationNumTest.java
Labels: approved, reviewed

#51662 [fix](alter) alter partition without storage_policy property will also cancel storage_policy
  fe/fe-core/src/main/java/org/apache/doris/alter/Alter.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/PropertyAnalyzer.java
  regression-test/suites/cold_heat_separation_p2/test_show_storage_policy_using.groovy
Labels: approved, reviewed

#51712 [Chore](nereids) Remove DescribeStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/DescribeStmt.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/qe/ShowExecutorTest.java
Labels: approved, reviewed

#51634 [opt](deps) upgrade paimon to 1.1.1 and iceberg to 1.9.1
  fe/fe-core/src/main/java/org/apache/doris/datasource/paimon/PaimonMetadataCache.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/iceberg/IcebergExternalTableTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/iceberg/source/IcebergScanNodeTest.java
  fe/pom.xml
Labels: approved, reviewed, dev/3.0.x

#51761 [Fix](case) Fix case `test_key_bounds_truncation_write_scenarios`
  regression-test/suites/unique_with_mow_p0/key_bounds/test_key_bounds_truncation_write_scenarios.groovy
Labels: approved, reviewed, dev/3.0.x

#51757 [Fix](case) Fix unstable case `test_delete_publish_skip_read`
  regression-test/suites/fault_injection_p0/flexible/legacy/test_f_delete_publish_skip_read.groovy
Labels: approved, reviewed, dev/3.0.x

#51573 [feat](cloud) Add unused rowset state for CloudTablet
  be/src/cloud/cloud_tablet.cpp
  be/src/cloud/cloud_tablet.h
  regression-test/data/compaction/test_filecache_compaction_and_read_stale_cloud_docker.out
  regression-test/suites/compaction/test_filecache_compaction_and_read_stale_cloud_docker.groovy
  regression-test/suites/compaction/test_filecache_compaction_multisegments_and_read_stale_cloud_docker.groovy
Labels: approved, reviewed, usercase, dev/3.0.x, cloud

#51781 [fix](compile) fix ShowLoadWarningsCommand compilation error
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ShowLoadWarningsCommand.java
  fe/fe-core/src/main/java/org/apache/doris/qe/ShowExecutor.java
  regression-test/suites/doc/data-operate/import/import-way/mysql-load-manual.md.groovy
Labels: approved, reviewed

#51594 [feat](warmup) display tables in SHOW WARM UP JOB results
  fe/fe-common/src/main/java/org/apache/doris/common/Triple.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/WarmUpClusterStmt.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/CacheHotspotManager.java
  fe/fe-core/src/main/java/org/apache/doris/cloud/CloudWarmUpJob.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ShowWarmUpCommand.java
  fe/fe-core/src/test/java/org/apache/doris/cloud/cache/CacheHotspotManagerTest.java
  regression-test/suites/cloud_p0/cache/multi_cluster/warm_up/table/test_warm_up_table.groovy
  regression-test/suites/cloud_p0/cache/multi_cluster/warm_up/table/test_warm_up_tables.groovy
Labels: reviewed, dev/3.0.x

#51519 [enhance](systable)Improve remote_data_size for partitions table
  be/src/exec/schema_scanner/schema_partitions_scanner.cpp
  fe/fe-core/src/main/java/org/apache/doris/catalog/SchemaTable.java
  fe/fe-core/src/main/java/org/apache/doris/tablefunction/MetadataGenerator.java
  regression-test/data/query_p0/system/test_query_sys_tables.out
Labels: approved, reviewed, dev/3.0.x

#51732 [improve](auto partition) random choose dummy partition location to enhance fault tolerance
  fe/fe-core/src/main/java/org/apache/doris/planner/OlapTableSink.java
Labels: approved, reviewed

#51813 [fix](nereids)fix WarmUpClusterCommand compile failure
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/WarmUpClusterCommand.java
Labels: approved, reviewed

#51219 [fix](load) fix S3 load cannot use HTTPS protocol for loading data
  fe/fe-core/src/main/java/org/apache/doris/analysis/LoadStmt.java
Labels: approved, reviewed, dev/3.0.x

#51790 [Chore](nereids) remove AlterColumnStatsStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/AlterColumnStatsStmt.java
  fe/fe-core/src/main/java/org/apache/doris/qe/DdlExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/StatisticsRepository.java
Labels: approved, reviewed

#51678 [Fix](Oss-Hdfs)ensure single URI and correct OSS-HDFS type detection
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/ConnectionProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/metastore/HMSProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/storage/HdfsCompatibleProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/storage/HdfsProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/storage/HdfsPropertiesUtils.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/storage/OSSHdfsProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/storage/OSSProperties.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/property/metastore/HMSPropertiesTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/property/storage/HdfsPropertiesUtilsTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/property/storage/OSSHdfsPropertiesTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/property/storage/OSSPropertiesTest.java
Labels: approved, reviewed, dev/3.1.x

#51831 [Bug](function) fix wrong result of hll_to_base64
  be/src/vec/functions/function_hll.cpp
  regression-test/data/load_p0/http_stream/test_http_stream_compress.out
  regression-test/suites/load_p0/http_stream/test_http_stream_compress.groovy
Labels: approved, reviewed

#51791 [Chore](nereids) remove DropCachedStatsStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/DropCachedStatsStmt.java
  fe/fe-core/src/main/java/org/apache/doris/qe/DdlExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisManager.java
Labels: approved, reviewed

#51800 [fix](build) fix macOS build
  be/src/vec/functions/function_string.h
Labels: approved, reviewed

#51674 [feat](cloud) Add unused rowset state for CloudTablet
  be/src/cloud/cloud_tablet.cpp
  be/src/cloud/cloud_tablet.h
  be/src/cloud/cloud_tablet_mgr.cpp
Labels: approved, reviewed

#51784 [env](simdjson)The version of simdjson has been upgraded from 3.0.1 to 3.11.6.
  thirdparty/CHANGELOG.md
  thirdparty/download-thirdparty.sh
  thirdparty/vars.sh
Labels: approved, reviewed

#51700 [fix](mtmv) Fix compensate union wrongly when direct query is empty relation
  fe/fe-core/src/main/java/org/apache/doris/common/profile/SummaryProfile.java
  fe/fe-core/src/main/java/org/apache/doris/mtmv/MTMVRelationManager.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/CascadesContext.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/NereidsPlanner.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/jobs/executor/TablePartitionCollector.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/AbstractMaterializedViewRule.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/InitMaterializationContextHook.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/MaterializedViewUtils.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/PartitionCompensator.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/exploration/mv/StructInfo.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/rules/rewrite/QueryPartitionCollector.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/exploration/mv/PartitionCompensatorTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/util/PlanChecker.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#51825 [fix](s3client) Fix `aws_config.maxConnections` set incorrectly
  be/src/util/s3_util.cpp
Labels: approved, reviewed

#51556 [clean](planner)copy into removes dependency on the old optimizer
  fe/fe-core/src/main/java/org/apache/doris/cloud/stage/StageUtil.java
  fe/fe-core/src/main/java/org/apache/doris/httpv2/rest/CopyIntoAction.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/parser/LogicalPlanBuilder.java
Labels: approved, reviewed

#51521 [clean](planner)view removes dependency on the old optimizer
  fe/fe-core/src/main/java/org/apache/doris/analysis/AlterViewStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/BaseViewStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateViewStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/View.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/CreateViewStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/CreateViewTest.java
  fe/fe-core/src/test/java/org/apache/doris/external/hms/HmsCatalogTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/privileges/TestCheckPrivileges.java
  fe/fe-core/src/test/java/org/apache/doris/qe/HmsQueryCacheTest.java
  fe/fe-core/src/test/java/org/apache/doris/qe/OlapQueryCacheTest.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/TestWithFeService.java
Labels: approved, reviewed

#51609 [fix](export) The export task thread pool uses a blocking queue strategy
  fe/fe-core/src/main/java/org/apache/doris/task/ExportExportingTask.java
Labels: approved, reviewed

#51713 [fix](hudi catalog) Fix the Kerberos authentication error when querying hudi table
  fe/fe-core/src/main/java/org/apache/doris/datasource/hudi/source/HudiScanNode.java
Labels: approved, reviewed, dev/2.1.x, dev/3.0.x

#51684 [fix](filecache) fix load_cache_info_into_memory crash
  be/src/io/cache/block_file_cache.h
Labels: approved, reviewed, dev/3.0.x, cloud

#51694 [fix](catalog)Fixed the issue of missing data when querying external tables in multi-BE and batch mode.
  fe/fe-core/src/main/java/org/apache/doris/datasource/SplitAssignment.java
Labels: approved, reviewed, dev/3.1.x

#50922 [fix](docker) resolve Python Logger warnings
  docker/runtime/doris-compose/command.py
  docker/runtime/doris-compose/database.py
Labels: approved, reviewed

#51888 [feat](param-refactor)Unify FS Factory Creation Logic and Support Broker Properties for Catalog Compatibility
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateRepositoryStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/StorageDesc.java
  fe/fe-core/src/main/java/org/apache/doris/backup/BackupHandler.java
  fe/fe-core/src/main/java/org/apache/doris/backup/Repository.java
  fe/fe-core/src/main/java/org/apache/doris/common/util/BrokerUtil.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/storage/BrokerProperties.java
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/storage/StorageProperties.java
  fe/fe-core/src/main/java/org/apache/doris/fs/FileSystemCache.java
  fe/fe-core/src/main/java/org/apache/doris/fs/FileSystemFactory.java
  fe/fe-core/src/main/java/org/apache/doris/fs/PersistentFileSystem.java
  fe/fe-core/src/main/java/org/apache/doris/fs/StorageTypeMapper.java
  fe/fe-core/src/main/java/org/apache/doris/fs/remote/BrokerFileSystem.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/CreateRepositoryCommand.java
  fe/fe-core/src/test/java/org/apache/doris/backup/BackupJobTest.java
  fe/fe-core/src/test/java/org/apache/doris/backup/BrokerStorageTest.java
  fe/fe-core/src/test/java/org/apache/doris/backup/RepositoryTest.java
  fe/fe-core/src/test/java/org/apache/doris/backup/RestoreJobTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/property/storage/BrokerPropertiesTest.java
  fe/fe-core/src/test/java/org/apache/doris/external/iceberg/IcebergHadoopCatalogTest.java
  fe/fe-core/src/test/java/org/apache/doris/fs/obj/S3FileSystemTest.java
Labels: approved, reviewed, dev/3.1.x

#51894 [fix](oss)Support Aliyun OSS S3-Compatible Public Endpoint Format (eg. s3.oss-cn-xxx.aliyuncs.com)
  fe/fe-core/src/main/java/org/apache/doris/datasource/property/storage/OSSProperties.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/property/storage/OSSPropertiesTest.java
Labels: approved, reviewed, dev/3.1.x

#51868 [improvment](show)support jobid in show load warnings
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ShowLoadWarningsCommand.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/commands/ShowLoadWarningsCommandTest.java
  regression-test/suites/nereids_p0/show/test_nereids_show_load_warnings.groovy
Labels: approved, reviewed

#51838 [Chore](nereids) Remove GrantStmt and RevokeStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/GrantStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/RevokeStmt.java
  fe/fe-core/src/main/java/org/apache/doris/mysql/privilege/Auth.java
  fe/fe-core/src/main/java/org/apache/doris/qe/DdlExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/analysis/GrantStmtTest.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/RefreshDbTest.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/RefreshTableTest.java
  fe/fe-core/src/test/java/org/apache/doris/cooldown/CooldownConfHandlerTest.java
  fe/fe-core/src/test/java/org/apache/doris/datasource/ColumnPrivTest.java
  fe/fe-core/src/test/java/org/apache/doris/mysql/privilege/AuthTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/rules/analysis/CheckRowPolicyTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/commands/ShowFunctionsCommandTest.java
  fe/fe-core/src/test/java/org/apache/doris/nereids/trees/plans/commands/ShowGrantsCommandTest.java
  fe/fe-core/src/test/java/org/apache/doris/policy/PolicyTest.java
  fe/fe-core/src/test/java/org/apache/doris/utframe/MockUsers.java
Labels: approved, reviewed

#51839 [fix](profile) Fix data race and refactor on threads usage of profile report
  be/src/runtime/exec_env_init.cpp
  be/src/runtime/query_context.cpp
  be/src/runtime/runtime_query_statistics_mgr.cpp
  be/src/runtime/runtime_query_statistics_mgr.h
Labels: approved, reviewed

#51859 [Chore](nereids) Remove DropStats/AnalyzeStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/DropAnalyzeJobStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/DropStatsStmt.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/KillAnalysisJobStmt.java
  fe/fe-core/src/main/java/org/apache/doris/qe/DdlExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/statistics/AnalysisManager.java
Labels: approved, reviewed

#51822 [Chore](nereids) Remove CreateWorkloadGroupStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/analysis/CreateWorkloadGroupStmt.java
  fe/fe-core/src/main/java/org/apache/doris/qe/DdlExecutor.java
  fe/fe-core/src/main/java/org/apache/doris/resource/workloadgroup/WorkloadGroupMgr.java
Labels: reviewed

#51850 [Enhancement] (nereids) delete translate paritionNamesIno in ShowReplicaDistributionCommand/ShowDataSkewCommand
  fe/fe-core/src/main/java/org/apache/doris/catalog/MetadataViewer.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ShowDataSkewCommand.java
  fe/fe-core/src/main/java/org/apache/doris/nereids/trees/plans/commands/ShowReplicaDistributionCommand.java
Labels: approved, reviewed

#51786 [bugfix](memleak) fix memory leak for tabletschema and result cache
  be/src/olap/tablet_schema.cpp
  be/src/olap/tablet_schema.h
  be/src/runtime/cache/result_cache.h
Labels: approved, reviewed

#51876 [test](jsonb) Add test case for Jsonb format
  be/test/util/jsonb_serialize_test.cpp
  be/test/util/test_data/jsonb_serialize_test_data.bin
Labels: approved, reviewed

#51715 [Fix](compile) Fix arm compile failure caused by undefined symbol
  be/src/vec/common/arithmetic_overflow.h
Labels: approved, reviewed, p0_b, dev/2.1.x, dev/3.0.x

#51890 [Chore](nereids) Remove AlterSystemStmt
  fe/fe-core/src/main/cup/sql_parser.cup
  fe/fe-core/src/main/java/org/apache/doris/alter/Alter.java
  fe/fe-core/src/main/java/org/apache/doris/analysis/AlterSystemStmt.java
  fe/fe-core/src/main/java/org/apache/doris/catalog/Env.java
  fe/fe-core/src/main/java/org/apache/doris/qe/DdlExecutor.java
  fe/fe-core/src/test/java/org/apache/doris/catalog/ModifyBackendTest.java
  fe/fe-core/src/test/java/org/apache/doris/clone/DecommissionTest.java
  fe/fe-core/src/test/java/org/apache/doris/clone/TabletRepairAndBalanceTest.java
  fe/fe-core/src/test/java/org/apache/doris/cluster/DecommissionBackendTest.java
  fe/fe-core/src/test/java/org/apache/doris/planner/ResourceTagQueryTest.java
Labels: approved, reviewed

#51693 [Enhancement][docker] entrypoint parse meta dir
  docker/runtime/fe/resource/fe_entrypoint.sh
Labels: approved, reviewed
